UPDATE dbc_chartitles SET Name_Lang_zhTW='士兵 %s', Name1_Lang_zhTW='士兵 %s' WHERE ID=1;
UPDATE dbc_chartitles SET Name_Lang_zhTW='下士 %s', Name1_Lang_zhTW='下士 %s' WHERE ID=2;
UPDATE dbc_chartitles SET Name_Lang_zhTW='士官 %s', Name1_Lang_zhTW='士官 %s' WHERE ID=3;
UPDATE dbc_chartitles SET Name_Lang_zhTW='上士 %s', Name1_Lang_zhTW='上士 %s' WHERE ID=4;
UPDATE dbc_chartitles SET Name_Lang_zhTW='士官長 %s', Name1_Lang_zhTW='士官長 %s' WHERE ID=5;
UPDATE dbc_chartitles SET Name_Lang_zhTW='騎士 %s', Name1_Lang_zhTW='騎士 %s' WHERE ID=6;
UPDATE dbc_chartitles SET Name_Lang_zhTW='中尉騎士 %s', Name1_Lang_zhTW='中尉騎士 %s' WHERE ID=7;
UPDATE dbc_chartitles SET Name_Lang_zhTW='上尉騎士 %s', Name1_Lang_zhTW='上尉騎士 %s' WHERE ID=8;
UPDATE dbc_chartitles SET Name_Lang_zhTW='一等騎士 %s', Name1_Lang_zhTW='一等騎士 %s' WHERE ID=9;
UPDATE dbc_chartitles SET Name_Lang_zhTW='少校 %s', Name1_Lang_zhTW='少校 %s' WHERE ID=10;
UPDATE dbc_chartitles SET Name_Lang_zhTW='指揮官 %s', Name1_Lang_zhTW='指揮官 %s' WHERE ID=11;
UPDATE dbc_chartitles SET Name_Lang_zhTW='元帥 %s', Name1_Lang_zhTW='元帥 %s' WHERE ID=12;
UPDATE dbc_chartitles SET Name_Lang_zhTW='戰場元帥 %s', Name1_Lang_zhTW='戰場元帥 %s' WHERE ID=13;
UPDATE dbc_chartitles SET Name_Lang_zhTW='總元帥 %s', Name1_Lang_zhTW='總元帥 %s' WHERE ID=14;
UPDATE dbc_chartitles SET Name_Lang_zhTW='斥候 %s', Name1_Lang_zhTW='斥候 %s' WHERE ID=15;
UPDATE dbc_chartitles SET Name_Lang_zhTW='蠻兵 %s', Name1_Lang_zhTW='蠻兵 %s' WHERE ID=16;
UPDATE dbc_chartitles SET Name_Lang_zhTW='士官 %s', Name1_Lang_zhTW='士官 %s' WHERE ID=17;
UPDATE dbc_chartitles SET Name_Lang_zhTW='資深士官 %s', Name1_Lang_zhTW='資深士官 %s' WHERE ID=18;
UPDATE dbc_chartitles SET Name_Lang_zhTW='一等士官 %s', Name1_Lang_zhTW='一等士官 %s' WHERE ID=19;
UPDATE dbc_chartitles SET Name_Lang_zhTW='石衛士 %s', Name1_Lang_zhTW='石衛士 %s' WHERE ID=20;
UPDATE dbc_chartitles SET Name_Lang_zhTW='血衛士 %s', Name1_Lang_zhTW='血衛士 %s' WHERE ID=21;
UPDATE dbc_chartitles SET Name_Lang_zhTW='軍團士兵 %s', Name1_Lang_zhTW='軍團士兵 %s' WHERE ID=22;
UPDATE dbc_chartitles SET Name_Lang_zhTW='百夫長 %s', Name1_Lang_zhTW='百夫長 %s' WHERE ID=23;
UPDATE dbc_chartitles SET Name_Lang_zhTW='勇士 %s', Name1_Lang_zhTW='勇士 %s' WHERE ID=24;
UPDATE dbc_chartitles SET Name_Lang_zhTW='中將 %s', Name1_Lang_zhTW='中將 %s' WHERE ID=25;
UPDATE dbc_chartitles SET Name_Lang_zhTW='將軍 %s', Name1_Lang_zhTW='將軍 %s' WHERE ID=26;
UPDATE dbc_chartitles SET Name_Lang_zhTW='督軍 %s', Name1_Lang_zhTW='督軍 %s' WHERE ID=27;
UPDATE dbc_chartitles SET Name_Lang_zhTW='高階督軍 %s', Name1_Lang_zhTW='高階督軍 %s' WHERE ID=28;
UPDATE dbc_chartitles SET Name_Lang_zhTW='鬥士 %s', Name1_Lang_zhTW='鬥士 %s' WHERE ID=42;
UPDATE dbc_chartitles SET Name_Lang_zhTW='決鬥者 %s', Name1_Lang_zhTW='決鬥者 %s' WHERE ID=43;
UPDATE dbc_chartitles SET Name_Lang_zhTW='競爭者 %s', Name1_Lang_zhTW='競爭者 %s' WHERE ID=44;
UPDATE dbc_chartitles SET Name_Lang_zhTW='挑戰者 %s', Name1_Lang_zhTW='挑戰者 %s' WHERE ID=45;
UPDATE dbc_chartitles SET Name_Lang_zhTW='聖甲蟲領主 %s', Name1_Lang_zhTW='聖甲蟲領主 %s' WHERE ID=46;
UPDATE dbc_chartitles SET Name_Lang_zhTW='征服者 %s', Name1_Lang_zhTW='征服者 %s' WHERE ID=47;
UPDATE dbc_chartitles SET Name_Lang_zhTW='審判者 %s', Name1_Lang_zhTW='審判者 %s' WHERE ID=48;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『那魯的勇士』%s', Name1_Lang_zhTW='『那魯的勇士』%s' WHERE ID=53;
UPDATE dbc_chartitles SET Name_Lang_zhTW='殘忍鬥士 %s', Name1_Lang_zhTW='殘忍鬥士 %s' WHERE ID=62;
UPDATE dbc_chartitles SET Name_Lang_zhTW='破碎之日的%s', Name1_Lang_zhTW='破碎之日的%s' WHERE ID=63;
UPDATE dbc_chartitles SET Name_Lang_zhTW='阿達歐之手 %s', Name1_Lang_zhTW='阿達歐之手 %s' WHERE ID=64;
UPDATE dbc_chartitles SET Name_Lang_zhTW='復仇鬥士 %s', Name1_Lang_zhTW='復仇鬥士 %s' WHERE ID=71;
UPDATE dbc_chartitles SET Name_Lang_zhTW='戰鬥大師 %s', Name1_Lang_zhTW='戰鬥大師 %s' WHERE ID=72;
UPDATE dbc_chartitles SET Name_Lang_zhTW='長老 %s', Name1_Lang_zhTW='長老 %s' WHERE ID=74;
UPDATE dbc_chartitles SET Name_Lang_zhTW='火焰看守者 %s', Name1_Lang_zhTW='火焰看守者 %s' WHERE ID=75;
UPDATE dbc_chartitles SET Name_Lang_zhTW='火焰守護者 %s', Name1_Lang_zhTW='火焰守護者 %s' WHERE ID=76;
UPDATE dbc_chartitles SET Name_Lang_zhTW='人人崇拜的%s', Name1_Lang_zhTW='人人崇拜的%s' WHERE ID=77;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『探險家』%s', Name1_Lang_zhTW='『探險家』%s' WHERE ID=78;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『外交官』%s', Name1_Lang_zhTW='『外交官』%s' WHERE ID=79;
UPDATE dbc_chartitles SET Name_Lang_zhTW='野蠻鬥士 %s', Name1_Lang_zhTW='野蠻鬥士 %s' WHERE ID=80;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『追尋者』%s', Name1_Lang_zhTW='『追尋者』%s' WHERE ID=81;
UPDATE dbc_chartitles SET Name_Lang_zhTW='競技場大師 %s', Name1_Lang_zhTW='競技場大師 %s' WHERE ID=82;
UPDATE dbc_chartitles SET Name_Lang_zhTW='熟練釣手 %s', Name1_Lang_zhTW='熟練釣手 %s' WHERE ID=83;
UPDATE dbc_chartitles SET Name_Lang_zhTW='大廚 %s', Name1_Lang_zhTW='大廚 %s' WHERE ID=84;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『至高者』%s', Name1_Lang_zhTW='『至高者』%s' WHERE ID=85;
UPDATE dbc_chartitles SET Name_Lang_zhTW='無盡風暴的%s', Name1_Lang_zhTW='無盡風暴的%s' WHERE ID=86;
UPDATE dbc_chartitles SET Name_Lang_zhTW='翡翠夢境的%s', Name1_Lang_zhTW='翡翠夢境的%s' WHERE ID=87;
UPDATE dbc_chartitles SET Name_Lang_zhTW='先知 %s', Name1_Lang_zhTW='先知 %s' WHERE ID=89;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『煞星』%s', Name1_Lang_zhTW='『煞星』%s' WHERE ID=90;
UPDATE dbc_chartitles SET Name_Lang_zhTW='巡者 %s', Name1_Lang_zhTW='巡者 %s' WHERE ID=91;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『黯刃』%s', Name1_Lang_zhTW='『黯刃』%s' WHERE ID=92;
UPDATE dbc_chartitles SET Name_Lang_zhTW='大法師 %s', Name1_Lang_zhTW='大法師 %s' WHERE ID=93;
UPDATE dbc_chartitles SET Name_Lang_zhTW='戰爭使者 %s', Name1_Lang_zhTW='戰爭使者 %s' WHERE ID=94;
UPDATE dbc_chartitles SET Name_Lang_zhTW='刺客 %s', Name1_Lang_zhTW='刺客 %s' WHERE ID=95;
UPDATE dbc_chartitles SET Name_Lang_zhTW='宗師級鍊金師 %s', Name1_Lang_zhTW='宗師級鍊金師 %s' WHERE ID=96;
UPDATE dbc_chartitles SET Name_Lang_zhTW='宗師級鐵匠 %s', Name1_Lang_zhTW='宗師級鐵匠 %s' WHERE ID=97;
UPDATE dbc_chartitles SET Name_Lang_zhTW='料理鐵人 %s', Name1_Lang_zhTW='料理鐵人 %s' WHERE ID=98;
UPDATE dbc_chartitles SET Name_Lang_zhTW='宗師級附魔師 %s', Name1_Lang_zhTW='宗師級附魔師 %s' WHERE ID=99;
UPDATE dbc_chartitles SET Name_Lang_zhTW='宗師級工程師 %s', Name1_Lang_zhTW='宗師級工程師 %s' WHERE ID=100;
UPDATE dbc_chartitles SET Name_Lang_zhTW='醫生 %s', Name1_Lang_zhTW='醫生 %s' WHERE ID=101;
UPDATE dbc_chartitles SET Name_Lang_zhTW='宗師級釣手 %s', Name1_Lang_zhTW='宗師級釣手 %s' WHERE ID=102;
UPDATE dbc_chartitles SET Name_Lang_zhTW='宗師級草藥師 %s', Name1_Lang_zhTW='宗師級草藥師 %s' WHERE ID=103;
UPDATE dbc_chartitles SET Name_Lang_zhTW='宗師級雕銘師 %s', Name1_Lang_zhTW='宗師級雕銘師 %s' WHERE ID=104;
UPDATE dbc_chartitles SET Name_Lang_zhTW='宗師級珠寶設計師 %s', Name1_Lang_zhTW='宗師級珠寶設計師 %s' WHERE ID=105;
UPDATE dbc_chartitles SET Name_Lang_zhTW='宗師級製皮師%s', Name1_Lang_zhTW='宗師級製皮師%s' WHERE ID=106;
UPDATE dbc_chartitles SET Name_Lang_zhTW='宗師級礦工 %s', Name1_Lang_zhTW='宗師級礦工 %s' WHERE ID=107;
UPDATE dbc_chartitles SET Name_Lang_zhTW='宗師級剝皮師 %s', Name1_Lang_zhTW='宗師級剝皮師 %s' WHERE ID=108;
UPDATE dbc_chartitles SET Name_Lang_zhTW='宗師級裁縫 %s', Name1_Lang_zhTW='宗師級裁縫 %s' WHERE ID=109;
UPDATE dbc_chartitles SET Name_Lang_zhTW='奎爾薩拉斯的%s', Name1_Lang_zhTW='奎爾薩拉斯的%s' WHERE ID=110;
UPDATE dbc_chartitles SET Name_Lang_zhTW='阿古斯的%s', Name1_Lang_zhTW='阿古斯的%s' WHERE ID=111;
UPDATE dbc_chartitles SET Name_Lang_zhTW='卡茲莫丹的%s', Name1_Lang_zhTW='卡茲莫丹的%s' WHERE ID=112;
UPDATE dbc_chartitles SET Name_Lang_zhTW='諾姆瑞根的%s', Name1_Lang_zhTW='諾姆瑞根的%s' WHERE ID=113;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『獅心』%s', Name1_Lang_zhTW='『獅心』%s' WHERE ID=114;
UPDATE dbc_chartitles SET Name_Lang_zhTW='伊露恩勇士 %s', Name1_Lang_zhTW='伊露恩勇士 %s' WHERE ID=115;
UPDATE dbc_chartitles SET Name_Lang_zhTW='奧格瑪英雄 %s', Name1_Lang_zhTW='奧格瑪英雄 %s' WHERE ID=116;
UPDATE dbc_chartitles SET Name_Lang_zhTW='曠野奔馳者 %s', Name1_Lang_zhTW='曠野奔馳者 %s' WHERE ID=117;
UPDATE dbc_chartitles SET Name_Lang_zhTW='暗矛的%s', Name1_Lang_zhTW='暗矛的%s' WHERE ID=118;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『被遺忘者』%s', Name1_Lang_zhTW='『被遺忘者』%s' WHERE ID=119;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『魔法追尋者』%s', Name1_Lang_zhTW='『魔法追尋者』%s' WHERE ID=120;
UPDATE dbc_chartitles SET Name_Lang_zhTW='暮光鎮壓者 %s', Name1_Lang_zhTW='暮光鎮壓者 %s' WHERE ID=121;
UPDATE dbc_chartitles SET Name_Lang_zhTW='納克薩瑪斯征服者 %s', Name1_Lang_zhTW='納克薩瑪斯征服者 %s' WHERE ID=122;
UPDATE dbc_chartitles SET Name_Lang_zhTW='北裂境英雄 %s', Name1_Lang_zhTW='北裂境英雄 %s' WHERE ID=123;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『萬鬼』%s', Name1_Lang_zhTW='『萬鬼』%s' WHERE ID=124;
UPDATE dbc_chartitles SET Name_Lang_zhTW='博學大師 %s', Name1_Lang_zhTW='博學大師 %s' WHERE ID=125;
UPDATE dbc_chartitles SET Name_Lang_zhTW='聯盟的%s', Name1_Lang_zhTW='聯盟的%s' WHERE ID=126;
UPDATE dbc_chartitles SET Name_Lang_zhTW='部落的%s', Name1_Lang_zhTW='部落的%s' WHERE ID=127;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『完美勝利者』%s', Name1_Lang_zhTW='『完美勝利者』%s' WHERE ID=128;
UPDATE dbc_chartitles SET Name_Lang_zhTW='冰凍荒原勇士%s', Name1_Lang_zhTW='冰凍荒原勇士%s' WHERE ID=129;
UPDATE dbc_chartitles SET Name_Lang_zhTW='大使 %s', Name1_Lang_zhTW='大使 %s' WHERE ID=130;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『銀白勇士』%s', Name1_Lang_zhTW='『銀白勇士』%s' WHERE ID=131;
UPDATE dbc_chartitles SET Name_Lang_zhTW='塞納留斯守護者%s', Name1_Lang_zhTW='塞納留斯守護者%s' WHERE ID=132;
UPDATE dbc_chartitles SET Name_Lang_zhTW='釀酒大師 %s', Name1_Lang_zhTW='釀酒大師 %s' WHERE ID=133;
UPDATE dbc_chartitles SET Name_Lang_zhTW='狂歡客 %s', Name1_Lang_zhTW='狂歡客 %s' WHERE ID=134;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『愛情傻瓜』%s', Name1_Lang_zhTW='『愛情傻瓜』%s' WHERE ID=135;
UPDATE dbc_chartitles SET Name_Lang_zhTW='女監護 %s', Name1_Lang_zhTW='女監護 %s' WHERE ID=137;
UPDATE dbc_chartitles SET Name_Lang_zhTW='男監護 %s', Name1_Lang_zhTW='男監護 %s' WHERE ID=138;
UPDATE dbc_chartitles SET Name_Lang_zhTW='黑曜殺戮者 %s', Name1_Lang_zhTW='黑曜殺戮者 %s' WHERE ID=139;
UPDATE dbc_chartitles SET Name_Lang_zhTW='夜暮的%s', Name1_Lang_zhTW='夜暮的%s' WHERE ID=140;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『不朽』%s', Name1_Lang_zhTW='『不朽』%s' WHERE ID=141;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『不滅』%s', Name1_Lang_zhTW='『不滅』%s' WHERE ID=142;
UPDATE dbc_chartitles SET Name_Lang_zhTW='炸雞勇者 %s', Name1_Lang_zhTW='炸雞勇者 %s' WHERE ID=143;
UPDATE dbc_chartitles SET Name_Lang_zhTW='血帆上將 %s', Name1_Lang_zhTW='血帆上將 %s' WHERE ID=144;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『神經病』%s', Name1_Lang_zhTW='『神經病』%s' WHERE ID=145;
UPDATE dbc_chartitles SET Name_Lang_zhTW='艾克索達的%s', Name1_Lang_zhTW='艾克索達的%s' WHERE ID=146;
UPDATE dbc_chartitles SET Name_Lang_zhTW='達納蘇斯的%s', Name1_Lang_zhTW='達納蘇斯的%s' WHERE ID=147;
UPDATE dbc_chartitles SET Name_Lang_zhTW='鐵爐堡的%s', Name1_Lang_zhTW='鐵爐堡的%s' WHERE ID=148;
UPDATE dbc_chartitles SET Name_Lang_zhTW='暴風城的%s', Name1_Lang_zhTW='暴風城的%s' WHERE ID=149;
UPDATE dbc_chartitles SET Name_Lang_zhTW='奧格瑪的%s', Name1_Lang_zhTW='奧格瑪的%s' WHERE ID=150;
UPDATE dbc_chartitles SET Name_Lang_zhTW='森金的%s', Name1_Lang_zhTW='森金的%s' WHERE ID=151;
UPDATE dbc_chartitles SET Name_Lang_zhTW='銀月城的%s', Name1_Lang_zhTW='銀月城的%s' WHERE ID=152;
UPDATE dbc_chartitles SET Name_Lang_zhTW='雷霆崖的%s', Name1_Lang_zhTW='雷霆崖的%s' WHERE ID=153;
UPDATE dbc_chartitles SET Name_Lang_zhTW='幽暗城的%s', Name1_Lang_zhTW='幽暗城的%s' WHERE ID=154;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『貴族』%s', Name1_Lang_zhTW='『貴族』%s' WHERE ID=155;
UPDATE dbc_chartitles SET Name_Lang_zhTW='十字軍 %s', Name1_Lang_zhTW='十字軍 %s' WHERE ID=156;
UPDATE dbc_chartitles SET Name_Lang_zhTW='致命鬥士 %s', Name1_Lang_zhTW='致命鬥士 %s' WHERE ID=157;
UPDATE dbc_chartitles SET Name_Lang_zhTW='死神葬送者 %s', Name1_Lang_zhTW='死神葬送者 %s' WHERE ID=158;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『星穹防衛者』%s', Name1_Lang_zhTW='『星穹防衛者』%s' WHERE ID=159;
UPDATE dbc_chartitles SET Name_Lang_zhTW='奧杜亞征服者 %s', Name1_Lang_zhTW='奧杜亞征服者 %s' WHERE ID=160;
UPDATE dbc_chartitles SET Name_Lang_zhTW='奧杜亞勇士 %s', Name1_Lang_zhTW='奧杜亞勇士 %s' WHERE ID=161;
UPDATE dbc_chartitles SET Name_Lang_zhTW='霸者 %s', Name1_Lang_zhTW='霸者 %s' WHERE ID=163;
UPDATE dbc_chartitles SET Name_Lang_zhTW='喚星者 %s', Name1_Lang_zhTW='喚星者 %s' WHERE ID=164;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『星界巡行者』%s', Name1_Lang_zhTW='『星界巡行者』%s' WHERE ID=165;
UPDATE dbc_chartitles SET Name_Lang_zhTW='泰坦信使 %s', Name1_Lang_zhTW='泰坦信使 %s' WHERE ID=166;
UPDATE dbc_chartitles SET Name_Lang_zhTW='狂烈鬥士 %s', Name1_Lang_zhTW='狂烈鬥士 %s' WHERE ID=167;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『旅人』%s', Name1_Lang_zhTW='『旅人』%s' WHERE ID=168;
UPDATE dbc_chartitles SET Name_Lang_zhTW='無情鬥士 %s', Name1_Lang_zhTW='無情鬥士 %s' WHERE ID=169;
UPDATE dbc_chartitles SET Name_Lang_zhTW='大十字軍 %s', Name1_Lang_zhTW='大十字軍 %s' WHERE ID=170;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『銀白防衛者』%s', Name1_Lang_zhTW='『銀白防衛者』%s' WHERE ID=171;
UPDATE dbc_chartitles SET Name_Lang_zhTW='有耐心的%s', Name1_Lang_zhTW='有耐心的%s' WHERE ID=172;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『黎明曙光』%s', Name1_Lang_zhTW='『黎明曙光』%s' WHERE ID=173;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『墮王煞星』%s', Name1_Lang_zhTW='『墮王煞星』%s' WHERE ID=174;
UPDATE dbc_chartitles SET Name_Lang_zhTW='『誅王勇者』%s', Name1_Lang_zhTW='『誅王勇者』%s' WHERE ID=175;
UPDATE dbc_chartitles SET Name_Lang_zhTW='灰燼裁決軍的%s', Name1_Lang_zhTW='灰燼裁決軍的%s' WHERE ID=176;
UPDATE dbc_chartitles SET Name_Lang_zhTW='憤怒鬥士 %s', Name1_Lang_zhTW='憤怒鬥士 %s' WHERE ID=177;
