UPDATE dbc_totemcategory SET Name_Lang_zhTW='剝皮小刀 (OLD)' WHERE ID=1;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='大地圖騰' WHERE ID=2;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='風之圖騰' WHERE ID=3;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='火焰圖騰' WHERE ID=4;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='水之圖騰' WHERE ID=5;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='符文銅棒' WHERE ID=6;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='符文銀棒' WHERE ID=7;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='符文金棒' WHERE ID=8;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='符文真銀棒' WHERE ID=9;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='符文奧金棒' WHERE ID=10;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='礦工鋤 (OLD)' WHERE ID=11;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='點金石' WHERE ID=12;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='鐵匠之錘 (OLD)' WHERE ID=13;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='扳手' WHERE ID=14;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='地精微調器' WHERE ID=15;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='大師圖騰' WHERE ID=21;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='符文魔鐵棒' WHERE ID=41;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='符文堅鋼棒' WHERE ID=62;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='符文恆金棒' WHERE ID=63;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='中空羽毛筆' WHERE ID=81;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='符文藍銅棒' WHERE ID=101;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='行家書寫工具組' WHERE ID=121;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='鼓' WHERE ID=141;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='地精軍用小刀' WHERE ID=161;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='鐵匠之錘' WHERE ID=162;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='挖礦鎬' WHERE ID=165;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='剝皮小刀' WHERE ID=166;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='錘鎬' WHERE ID=167;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='刃鎬' WHERE ID=168;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='燧石和火絨' WHERE ID=169;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='符文鈷藍棒 (不要使用)' WHERE ID=189;
UPDATE dbc_totemcategory SET Name_Lang_zhTW='符文泰坦鋼棒' WHERE ID=190;
