UPDATE dbc_skillline SET DisplayName_Lang_zhTW='冰霜', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=6;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='火焰', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=8;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='武器', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=26;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='戰鬥', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=38;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='敏銳', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=39;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='劍', Description_Lang_zhTW='武器技能越高，擊中敵人的機率就越高。', AlternateVerb_Lang_zhTW='' WHERE ID=43;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='斧', Description_Lang_zhTW='武器技能越高，擊中敵人的機率就越高。', AlternateVerb_Lang_zhTW='' WHERE ID=44;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='弓', Description_Lang_zhTW='武器技能越高，擊中敵人的機率就越高。', AlternateVerb_Lang_zhTW='' WHERE ID=45;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='槍械', Description_Lang_zhTW='武器技能越高，擊中敵人的機率就越高。', AlternateVerb_Lang_zhTW='' WHERE ID=46;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='野獸控制', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=50;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='生存技能', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=51;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='錘', Description_Lang_zhTW='武器技能越高，擊中敵人的機率就越高。', AlternateVerb_Lang_zhTW='' WHERE ID=54;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='雙手劍', Description_Lang_zhTW='武器技能越高，擊中敵人的機率就越高。', AlternateVerb_Lang_zhTW='' WHERE ID=55;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='神聖', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=56;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='暗影魔法', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=78;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='防禦', Description_Lang_zhTW='防禦技能可提高你閃躲、招架和格擋攻擊的機率。防禦越高，你就越難以被擊中，怪物也越難對你造成致命一擊。', AlternateVerb_Lang_zhTW='' WHERE ID=95;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='語言:通用語', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=98;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='矮人種族特長', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=101;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='語言:獸人語', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=109;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='語言:矮人語', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=111;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='語言:達納蘇斯語', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=113;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='語言:牛頭人語', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=115;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='雙武器', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=118;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='牛頭人種族特長', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=124;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='獸人種族特長', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=125;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='夜精靈種族特長', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=126;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='急救', Description_Lang_zhTW='高級的急救技能使你可以學習高級的急救能力。你可以在訓練師那裡學習新的能力，也可以通過完成任務或殺死怪物獲得新的能力。', AlternateVerb_Lang_zhTW='' WHERE ID=129;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='野性戰鬥', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=134;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='法杖', Description_Lang_zhTW='武器技能越高，擊中敵人的機率就越高。', AlternateVerb_Lang_zhTW='' WHERE ID=136;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='語言:薩拉斯語', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=137;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='語言:龍語', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=138;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='語言:惡魔語', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=139;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='語言:泰坦語', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=140;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='語言:古代語', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=141;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='生存技能', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=142;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='騎術:馬', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=148;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='騎術:狼', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=149;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='騎術:虎', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=150;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='騎術:羊', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=152;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='游泳', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=155;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='雙手錘', Description_Lang_zhTW='武器技能越高，擊中敵人的機率就越高。', AlternateVerb_Lang_zhTW='' WHERE ID=160;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='徒手戰鬥', Description_Lang_zhTW='此技能等級越高，你擊中目標的機率越高。', AlternateVerb_Lang_zhTW='' WHERE ID=162;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='射擊', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=163;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='鍛造', Description_Lang_zhTW='高級的鍛造技能使你可以學習高級的鍛造設計圖。你可以在訓練師那裡學習新的設計圖，也可以通過完成任務或殺死怪物獲得新的設計圖。', AlternateVerb_Lang_zhTW='鎔鑄' WHERE ID=164;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='製皮', Description_Lang_zhTW='高級的製皮技能使你可以學習高級的製皮圖樣。你可以在訓練師那裡學習新的圖樣，也可以通過完成任務或殺死怪物獲得新的圖樣。', AlternateVerb_Lang_zhTW='皮雕' WHERE ID=165;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='鍊金術', Description_Lang_zhTW='高級的鍊金術技能使你可以學習高級的鍊金術配方。你可以在訓練師那裡學習新的配方，也可以通過完成任務或殺死怪物獲得新的配方。', AlternateVerb_Lang_zhTW='灌注' WHERE ID=171;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='雙手斧', Description_Lang_zhTW='武器技能越高，擊中敵人的機率就越高。', AlternateVerb_Lang_zhTW='' WHERE ID=172;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='匕首', Description_Lang_zhTW='武器技能越高，擊中敵人的機率就越高。', AlternateVerb_Lang_zhTW='' WHERE ID=173;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='投擲武器', Description_Lang_zhTW='武器技能越高，擊中敵人的機率就越高。', AlternateVerb_Lang_zhTW='' WHERE ID=176;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='草藥學', Description_Lang_zhTW='高級的草藥學技能使你可以採集高級的草藥。如果你不能採集某種草藥，請先在較低等級的地區採集低等級草藥，以此提高你的草藥學技能。', AlternateVerb_Lang_zhTW='' WHERE ID=182;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='GENERIC (DND)', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=183;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='懲戒', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=184;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='烹飪', Description_Lang_zhTW='高級的烹飪技能使你可以學習高級的食譜。你可以在訓練師那裡學習新的食譜，也可以通過完成任務或殺死怪物獲得新的食譜。', AlternateVerb_Lang_zhTW='' WHERE ID=185;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='採礦', Description_Lang_zhTW='高級的採礦技能使你可以採集高級的礦石。如果你不能採集某種礦石，請先在較低等級的地區採集低等級礦石，以此提高你的採礦技能。', AlternateVerb_Lang_zhTW='' WHERE ID=186;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 小鬼', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=188;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 惡魔獵犬', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=189;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='裁縫', Description_Lang_zhTW='高級的裁縫技能使你可以學習高級的裁縫圖樣。你可以在訓練師那裡學習新的圖樣，也可以通過完成任務或殺死怪物獲得新的圖樣。', AlternateVerb_Lang_zhTW='縫製' WHERE ID=197;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='工程學', Description_Lang_zhTW='高級的工程學技能使你可以學習高級的工程學圖紙。你可以在訓練師那裡學習新的圖紙，也可以通過完成任務或殺死怪物獲得新的圖紙。', AlternateVerb_Lang_zhTW='裝置' WHERE ID=202;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 蜘蛛', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=203;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 虛無行者', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=204;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 魅魔', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=205;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 煉獄火', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=206;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 末日守衛', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=207;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 狼', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=208;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 豹', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=209;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 熊', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=210;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 野豬', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=211;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 鱷魚', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=212;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 食腐鳥', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=213;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 螃蟹', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=214;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 猩猩', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=215;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 迅猛龍', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=217;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 陸行鳥', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=218;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='不死族種族特長', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=220;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='弩', Description_Lang_zhTW='武器技能越高，擊中敵人的機率就越高。', AlternateVerb_Lang_zhTW='' WHERE ID=226;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='魔杖', Description_Lang_zhTW='武器技能越高，擊中敵人的機率就越高。', AlternateVerb_Lang_zhTW='' WHERE ID=228;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='長柄武器', Description_Lang_zhTW='武器技能越高，擊中敵人的機率就越高。', AlternateVerb_Lang_zhTW='' WHERE ID=229;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 蠍子', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=236;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='秘法', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=237;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 海龜', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=251;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='刺殺', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=253;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='狂怒', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=256;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='防護', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=257;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='防護', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=267;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 一般獵人', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=270;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='鎧甲', Description_Lang_zhTW='使你可以穿鎧甲。', AlternateVerb_Lang_zhTW='' WHERE ID=293;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='語言:地精語', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=313;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='語言:食人妖語', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=315;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='附魔', Description_Lang_zhTW='高級的附魔技能使你可以學習高級的附魔公式。你可以在訓練師那裡學習新的公式，也可以通過完成任務或殺死怪物獲得新的公式。', AlternateVerb_Lang_zhTW='附魔' WHERE ID=333;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='惡魔學識', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=354;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='痛苦', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=355;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='釣魚', Description_Lang_zhTW='高級的釣魚技能使你可以釣到高級的魚。如果你在某個區域釣不到魚，請到低等級區域去釣魚，或者購買魚餌再來嘗試。', AlternateVerb_Lang_zhTW='' WHERE ID=356;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='增強', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=373;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='恢復', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=374;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='元素戰鬥', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=375;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='剝皮', Description_Lang_zhTW='高級的剝皮技能使你可以從高級怪物身上剝取毛皮。如果你的剝皮技能大於100，那麼你可剝皮的怪物的最高等級是你的剝皮技能點數除以5。', AlternateVerb_Lang_zhTW='' WHERE ID=393;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='鎖甲', Description_Lang_zhTW='使你可以穿鎖甲。', AlternateVerb_Lang_zhTW='' WHERE ID=413;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='皮甲', Description_Lang_zhTW='使你可以穿皮甲。', AlternateVerb_Lang_zhTW='' WHERE ID=414;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='布甲', Description_Lang_zhTW='使你可以穿布甲。', AlternateVerb_Lang_zhTW='' WHERE ID=415;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='盾牌', Description_Lang_zhTW='學會使用盾牌。', AlternateVerb_Lang_zhTW='' WHERE ID=433;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='拳套', Description_Lang_zhTW='學會使用拳套作戰。擊中敵人的機率取決於徒手戰鬥技能。', AlternateVerb_Lang_zhTW='' WHERE ID=473;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='騎術:迅猛龍', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=533;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='騎術:機械陸行鳥', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=553;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='騎術:骸骨戰馬', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=554;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='恢復', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=573;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='平衡', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=574;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='毀滅', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=593;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='神聖', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=594;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='戒律', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=613;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='開鎖', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=633;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 蝙蝠', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=653;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 土狼', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=654;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 猛禽', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=655;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 風蛇', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=656;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='語言:不死族語', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=673;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='騎術:科多獸', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=713;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='種族特長 - 食人妖', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=733;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='種族特長 - 地精', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=753;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='種族特長 - 人類', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=754;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='珠寶設計', Description_Lang_zhTW='高級的珠寶設計技能使你可以學習高級的珠寶設計。你可以在訓練師那裡學習新的圖樣，也可以通過完成任務或殺死怪物獲得新的圖樣。', AlternateVerb_Lang_zhTW='加工' WHERE ID=755;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='種族特長 - 血精靈', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=756;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 事件 - 遙控', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=758;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='語言:德萊尼語', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=759;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='種族特長 - 德萊尼', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=760;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 惡魔守衛', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=761;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='騎術', Description_Lang_zhTW='高等級的騎術能讓你騎乘更快且更奇特的動物。', AlternateVerb_Lang_zhTW='' WHERE ID=762;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 龍鷹', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=763;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 虛空鰭刺', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=764;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 孢子蝙蝠', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=765;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 扭曲巡者', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=766;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 劫毀者', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=767;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 毒蛇', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=768;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='內部', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=769;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='血魄', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=770;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='冰霜', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=771;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='穢邪', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=772;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='銘文學', Description_Lang_zhTW='高等級的銘文學可以讓你學會更高級的銘文。你也可以透過來自各地的卷軸學習銘文。', AlternateVerb_Lang_zhTW='銘刻' WHERE ID=773;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 飛蛾', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=775;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='符文鑄造', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='紋刻' WHERE ID=776;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='坐騎', Description_Lang_zhTW='你的坐騎。', AlternateVerb_Lang_zhTW='' WHERE ID=777;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='夥伴', Description_Lang_zhTW='你的夥伴。', AlternateVerb_Lang_zhTW='' WHERE ID=778;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 奇特奇美拉', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=780;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 奇特魔暴龍', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=781;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 食屍鬼', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=782;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 奇特異種蟲', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=783;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 奇特蟲類', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=784;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 黃蜂', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=785;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 奇特犀牛', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=786;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 奇特熔核犬', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=787;
UPDATE dbc_skillline SET DisplayName_Lang_zhTW='寵物 - 奇特靈獸', Description_Lang_zhTW='', AlternateVerb_Lang_zhTW='' WHERE ID=788;
