UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Self Only', DisplayNameShort_Lang_zhTW='Self' WHERE ID=1;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Combat Range', DisplayNameShort_Lang_zhTW='Combat' WHERE ID=2;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Short Range', DisplayNameShort_Lang_zhTW='Short' WHERE ID=3;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Medium Range', DisplayNameShort_Lang_zhTW='Medium' WHERE ID=4;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Long Range', DisplayNameShort_Lang_zhTW='Long' WHERE ID=5;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Vision Range', DisplayNameShort_Lang_zhTW='Vision' WHERE ID=6;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Very Short Range', DisplayNameShort_Lang_zhTW='Very Short' WHERE ID=7;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Short Range', DisplayNameShort_Lang_zhTW='Short' WHERE ID=8;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Medium Range', DisplayNameShort_Lang_zhTW='Medium' WHERE ID=9;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Long Range', DisplayNameShort_Lang_zhTW='Long' WHERE ID=10;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Shorter Range', DisplayNameShort_Lang_zhTW='Shorter' WHERE ID=11;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Interact Range', DisplayNameShort_Lang_zhTW='Interact' WHERE ID=12;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Anywhere', DisplayNameShort_Lang_zhTW='Anywhere' WHERE ID=13;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Extra Long Range', DisplayNameShort_Lang_zhTW='Extra Long' WHERE ID=14;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Medium-Short Range', DisplayNameShort_Lang_zhTW='Medium-Short' WHERE ID=34;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Medium-Long Range', DisplayNameShort_Lang_zhTW='Medium-Long' WHERE ID=35;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Longer Range', DisplayNameShort_Lang_zhTW='Longer' WHERE ID=36;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Extended Range', DisplayNameShort_Lang_zhTW='Extended' WHERE ID=37;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Extra Medium Range', DisplayNameShort_Lang_zhTW='Extra Medium' WHERE ID=38;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Geoff Monster Shoot', DisplayNameShort_Lang_zhTW='Geoff' WHERE ID=54;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Ranged Weapon', DisplayNameShort_Lang_zhTW='Ranged' WHERE ID=74;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Sting', DisplayNameShort_Lang_zhTW='Sting' WHERE ID=94;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Charge', DisplayNameShort_Lang_zhTW='Charge' WHERE ID=95;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Trap', DisplayNameShort_Lang_zhTW='Trap' WHERE ID=96;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Hunter Range', DisplayNameShort_Lang_zhTW='Hunter' WHERE ID=114;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Tower 80', DisplayNameShort_Lang_zhTW='Tower' WHERE ID=134;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Tower 100', DisplayNameShort_Lang_zhTW='Tower' WHERE ID=135;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Artillery Range', DisplayNameShort_Lang_zhTW='Artillery' WHERE ID=136;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Very Short Range', DisplayNameShort_Lang_zhTW='Very Short' WHERE ID=137;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Long Range Hunter Shoot', DisplayNameShort_Lang_zhTW='Hunter Long' WHERE ID=139;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Six yards', DisplayNameShort_Lang_zhTW='Six yards' WHERE ID=140;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Seven yards', DisplayNameShort_Lang_zhTW='Seven yards' WHERE ID=141;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Valgarde 8/100', DisplayNameShort_Lang_zhTW='Valgarde' WHERE ID=150;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Long Range Hunter Shoot', DisplayNameShort_Lang_zhTW='Hunter 45' WHERE ID=151;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Super Long', DisplayNameShort_Lang_zhTW='Super Long' WHERE ID=152;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Charge, 60', DisplayNameShort_Lang_zhTW='Huge Charge' WHERE ID=153;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Tower 80, 10', DisplayNameShort_Lang_zhTW='Tower 10' WHERE ID=154;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Hunter Range (Long)', DisplayNameShort_Lang_zhTW='Hunter (Long)' WHERE ID=155;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Boulder Range', DisplayNameShort_Lang_zhTW='Boulder' WHERE ID=156;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Ninety', DisplayNameShort_Lang_zhTW='Ninety' WHERE ID=157;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Super Long, 15 Min', DisplayNameShort_Lang_zhTW='Super Long' WHERE ID=158;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='TEST - Long Range', DisplayNameShort_Lang_zhTW='TestLong' WHERE ID=159;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Medium/Long Range', DisplayNameShort_Lang_zhTW='Medium/Long' WHERE ID=160;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Short/Long Range', DisplayNameShort_Lang_zhTW='Short/Long' WHERE ID=161;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Medium/Short Range', DisplayNameShort_Lang_zhTW='Medium/Short' WHERE ID=162;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Death Grip', DisplayNameShort_Lang_zhTW='Death Grip' WHERE ID=163;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Catapult Range', DisplayNameShort_Lang_zhTW='Catapult' WHERE ID=164;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Fourteen yards', DisplayNameShort_Lang_zhTW='Shorter' WHERE ID=165;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Thirteen yards', DisplayNameShort_Lang_zhTW='Shorter' WHERE ID=166;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Super Long (Min Range)', DisplayNameShort_Lang_zhTW='Super Long' WHERE ID=167;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Medium-Long Range (38)', DisplayNameShort_Lang_zhTW='Medium-Long' WHERE ID=168;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Three Yards', DisplayNameShort_Lang_zhTW='Three Yards' WHERE ID=169;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Fifty Five Yards', DisplayNameShort_Lang_zhTW='Extended' WHERE ID=170;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Min Range 1, 10', DisplayNameShort_Lang_zhTW='Very Short' WHERE ID=171;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Eleven yards', DisplayNameShort_Lang_zhTW='Shorter' WHERE ID=172;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Anywhere (Combat Min Range)', DisplayNameShort_Lang_zhTW='Hunter Long' WHERE ID=173;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='U L T R A', DisplayNameShort_Lang_zhTW='U L T R A' WHERE ID=174;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Seventy yards', DisplayNameShort_Lang_zhTW='Extended' WHERE ID=176;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Donut 20-70', DisplayNameShort_Lang_zhTW='Donut 20-70' WHERE ID=177;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Min Range 5, 15', DisplayNameShort_Lang_zhTW='Shorter' WHERE ID=179;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Tournament - Ranged', DisplayNameShort_Lang_zhTW='Argent Tournament - Ranged' WHERE ID=180;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Two-Hundred Yard Range', DisplayNameShort_Lang_zhTW='200' WHERE ID=181;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Min Range 5, 25', DisplayNameShort_Lang_zhTW='Medium' WHERE ID=184;
UPDATE dbc_spellrange SET DisplayName_Lang_zhTW='Three Hundred Yards', DisplayNameShort_Lang_zhTW='300' WHERE ID=187;
