UPDATE dbc_taxinodes SET Name_Lang_zhTW='北郡修道院' WHERE ID=1;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='暴風城，艾爾文森林' WHERE ID=2;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='工程師島' WHERE ID=3;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='哨兵嶺，西部荒野' WHERE ID=4;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='湖畔鎮，赤脊山' WHERE ID=5;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='鐵爐堡，丹莫洛' WHERE ID=6;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='米奈希爾港，濕地' WHERE ID=7;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='塞爾薩瑪，洛克莫丹' WHERE ID=8;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='藏寶海灣，荊棘谷' WHERE ID=9;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='瑟伯切爾，銀松森林' WHERE ID=10;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='幽暗城，提里斯法林地' WHERE ID=11;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='夜色鎮，暮色森林' WHERE ID=12;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='塔倫米爾，希爾斯布萊德' WHERE ID=13;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='南海鎮，希爾斯布萊德' WHERE ID=14;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='東瘟疫之地' WHERE ID=15;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='避難谷地，阿拉希高地' WHERE ID=16;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='落錘鎮，阿拉希高地' WHERE ID=17;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='藏寶海灣，荊棘谷' WHERE ID=18;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='藏寶海灣，荊棘谷' WHERE ID=19;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='格羅姆高，荊棘谷' WHERE ID=20;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='卡加斯，荒蕪之地' WHERE ID=21;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='雷霆崖，莫高雷' WHERE ID=22;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='奧格瑪，杜洛塔' WHERE ID=23;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='Generic, World Target 002' WHERE ID=24;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='十字路口，貧瘠之地' WHERE ID=25;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='奧伯丁，黑海岸' WHERE ID=26;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='魯瑟蘭村，泰達希爾' WHERE ID=27;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='阿斯特蘭納，梣谷' WHERE ID=28;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='烈日石居，石爪山' WHERE ID=29;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='亂風崗 ，千針石林' WHERE ID=30;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='薩蘭納爾，千針石林' WHERE ID=31;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='塞拉摩，塵泥沼澤' WHERE ID=32;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='石爪峰，石爪山' WHERE ID=33;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，藏寶海灣' WHERE ID=34;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，奧格瑪' WHERE ID=35;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='Generic, World Target 001' WHERE ID=36;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='尼耶爾前哨站，淒涼之地' WHERE ID=37;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='葬影村，淒涼之地' WHERE ID=38;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='加基森，塔納利斯' WHERE ID=39;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='加基森，塔納利斯' WHERE ID=40;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='羽月要塞，菲拉斯' WHERE ID=41;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='莫沙徹營地，菲拉斯' WHERE ID=42;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='鷹巢山，辛特蘭' WHERE ID=43;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='瓦羅莫克，艾薩拉' WHERE ID=44;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='守望堡，詛咒之地' WHERE ID=45;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，南海鎮' WHERE ID=46;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，格羅姆高' WHERE ID=47;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='血毒河，費伍德森林' WHERE ID=48;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='月光林地' WHERE ID=49;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，米奈希爾港' WHERE ID=50;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，奧伯丁' WHERE ID=51;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='永望鎮，冬泉谷' WHERE ID=52;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='永望鎮，冬泉谷' WHERE ID=53;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='菲拉斯，羽月要塞' WHERE ID=54;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='蕨牆村，塵泥沼澤' WHERE ID=55;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='斯通納德，悲傷沼澤' WHERE ID=56;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='釣魚村，泰達希爾' WHERE ID=57;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='佐拉姆加前哨站，梣谷' WHERE ID=58;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='丹巴達爾，奧特蘭克山谷' WHERE ID=59;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='霜狼要塞，奧特蘭克山谷' WHERE ID=60;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='碎木崗哨，梣谷' WHERE ID=61;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='永夜港，月光林地' WHERE ID=62;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='永夜港，月光林地' WHERE ID=63;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='塔倫迪斯營地，艾薩拉' WHERE ID=64;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='刺枝林地，費伍德森林' WHERE ID=65;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='冰風營地，西瘟疫之地' WHERE ID=66;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='聖光之願禮拜堂，東瘟疫之地' WHERE ID=67;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='聖光之願禮拜堂，東瘟疫之地' WHERE ID=68;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='月光林地' WHERE ID=69;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='烈焰峰，燃燒平原' WHERE ID=70;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='摩根的崗哨，燃燒平原' WHERE ID=71;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='塞納里奧城堡，希利蘇斯' WHERE ID=72;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='塞納里奧城堡，希利蘇斯' WHERE ID=73;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='瑟銀哨塔，灼熱峽谷' WHERE ID=74;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='瑟銀哨塔，灼熱峽谷' WHERE ID=75;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='惡齒村，辛特蘭' WHERE ID=76;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='陶拉祖營地，貧瘠之地' WHERE ID=77;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='納克薩瑪斯' WHERE ID=78;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='馬紹爾營地，安戈洛環形山' WHERE ID=79;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='棘齒城，貧瘠之地' WHERE ID=80;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='薄霧之地' WHERE ID=81;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='銀月城' WHERE ID=82;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='安寧地，鬼魂之地' WHERE ID=83;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='病木林哨塔，東瘟疫之地' WHERE ID=84;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='北地哨塔，東瘟疫之地' WHERE ID=85;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='東牆之塔，東瘟疫之地' WHERE ID=86;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='皇冠哨塔，東瘟疫之地' WHERE ID=87;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，艾克索達' WHERE ID=88;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，塞拉摩島' WHERE ID=89;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，幽暗城' WHERE ID=90;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 藍謎薩滿目標' WHERE ID=91;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 藍謎薩滿起點' WHERE ID=92;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='血色守望，血謎島' WHERE ID=93;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='艾克索達' WHERE ID=94;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='贊格沼澤 - 任務 - 烏鴉高飛時' WHERE ID=95;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='贊格沼澤 - 任務 - 烏鴉高飛時 - 終點' WHERE ID=96;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 伊萊克小徑到凱索' WHERE ID=97;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 伊萊克到凱索目標' WHERE ID=98;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='索爾瑪，地獄火半島' WHERE ID=99;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='榮譽堡，地獄火半島' WHERE ID=100;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='特爾哈曼神廟，地獄火半島' WHERE ID=101;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='獵鷹哨站，地獄火半島' WHERE ID=102;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='納葛蘭 - PvP - 攻擊路線起點1' WHERE ID=103;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='納葛蘭 - PvP - 攻擊路線終點1' WHERE ID=104;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='納葛蘭 - PvP - 攻擊路線起點2' WHERE ID=105;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='納葛蘭 - PvP - 攻擊路線終點2' WHERE ID=106;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='納葛蘭 - PvP - 攻擊路線起點3' WHERE ID=107;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='納葛蘭 - PvP - 攻擊路線終點3' WHERE ID=108;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='納葛蘭 - PvP - 攻擊路線起點4' WHERE ID=109;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='納葛蘭 - PvP - 攻擊路線終點4' WHERE ID=110;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='永歌 - 暗木傳送' WHERE ID=111;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='永歌 - 暗木傳送終點' WHERE ID=112;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 尼軒德瑪斯起點' WHERE ID=113;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 尼軒德瑪斯終點目標' WHERE ID=114;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 時光之穴 OH - 起點' WHERE ID=115;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 時光之穴 OH - 終點' WHERE ID=116;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='泰倫多爾，贊格沼澤' WHERE ID=117;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='薩布拉金，贊格沼澤' WHERE ID=118;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='泰拉，納葛蘭' WHERE ID=119;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='卡拉達爾，納葛蘭' WHERE ID=120;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='艾蘭里堡壘，泰洛卡森林' WHERE ID=121;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='52區，虛空風暴' WHERE ID=122;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='影月村，影月谷' WHERE ID=123;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='蠻錘要塞，影月谷' WHERE ID=124;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='希瓦納爾，劍刃山脈' WHERE ID=125;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='雷霆王村，劍刃山脈' WHERE ID=126;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='碎石堡，泰洛卡森林' WHERE ID=127;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='撒塔斯，泰洛卡森林' WHERE ID=128;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='地獄火半島，黑暗之門，聯盟' WHERE ID=129;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='地獄火半島，黑暗之門，部落' WHERE ID=130;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 部落地獄火起點' WHERE ID=131;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 部落地獄火終點' WHERE ID=132;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 地獄火半島 (聯盟路線) 起點' WHERE ID=133;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 地獄火半島 (聯盟) 終點' WHERE ID=134;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 地獄火， 船空任務 (部落) 起點' WHERE ID=135;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 地獄火， 船空任務 (部落) 終點' WHERE ID=136;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 地獄火， 船空任務 (聯盟) 起點' WHERE ID=137;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 地獄火， 船空任務 (聯盟) 終點' WHERE ID=138;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='風暴之尖，虛空風暴' WHERE ID=139;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='薩塔祭壇，影月谷' WHERE ID=140;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='斷脊山脈，地獄火半島' WHERE ID=141;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='地獄火半島 - 劫奪者荒野' WHERE ID=142;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 時光之穴(介紹飛行路線)(終點)' WHERE ID=143;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 時光之穴(介紹飛行路線)(起點)' WHERE ID=144;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 虛空風暴 - 隱形飛行 - 開始' WHERE ID=145;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 虛空風暴 - 隱形飛行 - 結束' WHERE ID=146;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='地獄火半島 - 軍隊營地海角' WHERE ID=147;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='破碎崗哨，地獄火半島(海邊突襲)' WHERE ID=148;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='破碎崗哨，地獄火半島' WHERE ID=149;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='扭曲太空，虛空風暴' WHERE ID=150;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='斯溫派特崗哨，贊格沼澤' WHERE ID=151;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 虛空風暴 - 法力熔爐奧崔斯 (起點)' WHERE ID=152;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 虛空風暴 - 法力熔爐奧崔斯 (終點)' WHERE ID=153;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 虛空風暴 - 法力熔爐奧崔斯 (第二次通過) 起點' WHERE ID=154;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 虛空風暴 - 法力熔爐奧崔斯 (第二次通過) 終點' WHERE ID=155;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='托斯利基地，劍刃山脈' WHERE ID=156;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 劍刃山脈 - 視覺引導 - 起點' WHERE ID=157;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 劍刃山脈 - 視覺引導 - 終點' WHERE ID=158;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='星光聖所，影月谷' WHERE ID=159;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='永恆樹林，劍刃山脈' WHERE ID=160;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 虛空龍同盟 - 起點' WHERE ID=161;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 虛空龍同盟 - 終點' WHERE ID=162;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='摩克納薩爾村，劍刃山脈' WHERE ID=163;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='奧雷伯爾港，贊格沼澤' WHERE ID=164;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，北裂境2' WHERE ID=165;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='翡翠聖地，費伍德森林' WHERE ID=166;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='林歌神殿，梣谷' WHERE ID=167;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='薄霧之地' WHERE ID=168;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 虛空之翼岩架 - 搭乘礦坑推車 - 南方 - 開始' WHERE ID=169;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 虛空之翼岩架 - 搭乘礦坑推車 - 南方 - 結束' WHERE ID=170;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='司凱堤斯' WHERE ID=171;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='歐格利拉' WHERE ID=172;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 亞吉歐飛行開始' WHERE ID=173;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 亞吉歐飛行開始結束' WHERE ID=174;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，凜風峽灣' WHERE ID=175;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 凜風峽灣牛頭人獨木舟 (開始)' WHERE ID=176;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 凜風峽灣牛頭人獨木舟 (結束)' WHERE ID=177;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，北風凍原' WHERE ID=178;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='泥鏈營地，塵泥沼澤' WHERE ID=179;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 塵泥 - 勘察奧卡茲開始' WHERE ID=180;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 塵泥 - 勘察奧卡茲結束' WHERE ID=181;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 凜風峽灣 - 突破封鎖線飛艇' WHERE ID=182;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='瓦爾加德港口，凜風峽灣' WHERE ID=183;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='威德瓦堡壘, 凜風峽灣' WHERE ID=184;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='鎮西要塞，凜風峽灣' WHERE ID=185;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 凜風峽灣 - 飛到風行者 - 開始' WHERE ID=186;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 凜風峽灣 - 飛到風行者 - 結束' WHERE ID=187;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 凜風峽灣 - 海上的試驗 - 開始' WHERE ID=188;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 凜風峽灣 - 海上的試驗 - 結束' WHERE ID=189;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='新阿加曼德，凜風峽灣' WHERE ID=190;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='復仇臺地，凜風峽灣' WHERE ID=191;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='冬蹄營地，凜風峽灣' WHERE ID=192;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 凜風峽灣 - 任務:毀掉瘟疫! - 結束' WHERE ID=193;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 凜風峽灣 - 任務:毀掉瘟疫! - 開始' WHERE ID=194;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='反抗軍營地，荊棘谷' WHERE ID=195;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='Test - SP' WHERE ID=196;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='Test SP2' WHERE ID=197;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='Test SP1' WHERE ID=198;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 凜風峽灣 - 馬概先開始' WHERE ID=199;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 凜風峽灣 - 馬概先結束' WHERE ID=200;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='開發之地 - 凱爾·雷度開始' WHERE ID=201;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='開發之地 - 凱爾·雷度結束' WHERE ID=202;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 繁星之眠 -> 溫特加德' WHERE ID=203;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 新阿加曼德 -> 毒怨之地' WHERE ID=204;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='祖阿曼，鬼魂之地' WHERE ID=205;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，羽月要塞(東北方船)' WHERE ID=206;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 凜風峽灣 - 慈悲姐妹號 (開始)' WHERE ID=207;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 凜風峽灣 - 慈悲姐妹號 (結束)' WHERE ID=208;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 太陽之井每日 - 死亡之痕轟炸 - 開始' WHERE ID=209;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 太陽之井每日 - 死亡之痕轟炸 - 結束' WHERE ID=210;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 太陽之井每日 - 轟炸船隻 - 開始' WHERE ID=211;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 太陽之井每日 - 轟炸船隻 - 結束' WHERE ID=212;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='破碎之日會所' WHERE ID=213;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 凜風峽灣 - 奈格法 (開始)' WHERE ID=214;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 凜風峽灣 - 奈格法(點)' WHERE ID=215;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='' WHERE ID=216;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='' WHERE ID=217;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，凜風峽灣 (纜車，上層)' WHERE ID=218;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，凜風峽灣 (纜車，下層)' WHERE ID=219;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='' WHERE ID=220;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='琥珀岩臺，北風 (往碧晶)' WHERE ID=221;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='碧晶哨點，北風' WHERE ID=222;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 納戈瓦' WHERE ID=223;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='北風凍原，納戈瓦' WHERE ID=224;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='琥珀岩臺，北風 (到凜懼島)' WHERE ID=225;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='隘境之盾，凜懼島' WHERE ID=226;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，PattyMacDevTest' WHERE ID=227;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='開發之地 - 帕特測試開始' WHERE ID=228;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='開發之地 - 帕特測試結束' WHERE ID=229;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，巨牙海民01' WHERE ID=230;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，巨牙海民02' WHERE ID=231;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='北風凍原 - 戰歌堡狼開始' WHERE ID=232;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='北風凍原 - 戰歌堡狼結束' WHERE ID=233;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='凜懼島岩臺，凜懼島' WHERE ID=234;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='隘境之盾，凜懼島 (NOT USED)' WHERE ID=235;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='凜懼島，凱瑞史卓莎到瑪里苟斯' WHERE ID=236;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='凜懼島，凱瑞史卓莎平臺' WHERE ID=237;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='' WHERE ID=238;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='北風凍原 - 任務 - 幽暮開始' WHERE ID=239;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='北風凍原 - 任務 - 幽暮結束' WHERE ID=240;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，驍勇要塞' WHERE ID=241;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 龍骨荒野 - 靈魂視覺 - 開始' WHERE ID=242;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 龍骨荒野 - 靈魂視覺 - 結束' WHERE ID=243;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='溫特加德要塞，龍骨荒野' WHERE ID=244;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='驍勇要塞，北風凍原' WHERE ID=245;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='嘶軸簡易機場，北風凍原' WHERE ID=246;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='繁星之眠，龍骨荒野' WHERE ID=247;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='藥劑師營地，凜風峽灣' WHERE ID=248;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='歐尼克瓦營地，灰白之丘' WHERE ID=249;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='征服堡，灰白之丘' WHERE ID=250;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='弗塔根堡，龍骨荒野' WHERE ID=251;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='龍眠神殿，龍骨荒野' WHERE ID=252;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='琥珀松小屋，灰白之丘' WHERE ID=253;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='毒怨之地，龍骨荒野' WHERE ID=254;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='西荒兵團，灰白之丘' WHERE ID=255;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='阿格瑪之錘，龍骨荒野' WHERE ID=256;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='戰歌堡，北風凍原' WHERE ID=257;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='坦卡雷村，北風凍原' WHERE ID=258;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='博格洛克前哨，北風凍原' WHERE ID=259;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='柯爾克隆先鋒駐地，龍骨荒野' WHERE ID=260;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 繁星之眠到溫特加德結束' WHERE ID=261;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='灰白之丘，聯盟木材行開始01' WHERE ID=262;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='灰白之丘，聯盟木材行結束01' WHERE ID=263;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，奧伯丁 (NEW)' WHERE ID=264;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，塞拉摩 (NEW)' WHERE ID=265;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，米奈希爾 (NEW)' WHERE ID=266;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='灰白之丘，聯盟木材行開始' WHERE ID=267;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='灰白之丘，聯盟木材行結束' WHERE ID=268;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 鎮西要塞到溫特加德要塞開始' WHERE ID=269;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 鎮西要塞到溫特加德要塞結束' WHERE ID=270;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='灰白之丘，部落木材行開始' WHERE ID=271;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='灰白之丘，部落木材行結束' WHERE ID=272;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='龍眠神殿 - 下層到上層，龍骨荒野 - 起點' WHERE ID=273;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='龍眠神殿 - 下層到上層，龍骨荒野 - 終點' WHERE ID=274;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='龍眠神殿 - 上層到下層，龍骨荒野 - 起點' WHERE ID=275;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='龍眠神殿 - 上層到下層，龍骨荒野 - 終點' WHERE ID=276;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='龍眠神殿 - 上層到中層，龍骨荒野 - 起點' WHERE ID=277;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='龍眠神殿 - 上層到中層，龍骨荒野 - 終點' WHERE ID=278;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='龍眠神殿 - 中層到上層，龍骨荒野 - 終點' WHERE ID=279;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='龍眠神殿 - 中層到上層，龍骨荒野 - 起點' WHERE ID=280;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='龍眠神殿 - 中層到下層，龍骨荒野 - 終點' WHERE ID=281;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='龍眠神殿 - 中層到下層，龍骨荒野 - 起點' WHERE ID=282;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='龍眠神殿 - 下層到中層，龍骨荒野 - 終點' WHERE ID=283;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='龍眠神殿 - 下層到中層，龍骨荒野 - 起點' WHERE ID=284;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 溫特加德 -> 繁星之眠 (開始)' WHERE ID=285;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 溫特加德 -> 繁星之眠 (結束)' WHERE ID=286;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 瓦爾加德 -> 溫特加德要塞開始' WHERE ID=287;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 瓦爾加德 -> 鎮西要塞結束' WHERE ID=288;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='琥珀岩臺，北風凍原' WHERE ID=289;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='銀白看臺，祖爾德拉克' WHERE ID=290;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='廢墟之城崗哨 01，祖爾德拉克' WHERE ID=291;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='樣式 - 暴風港 - 起點' WHERE ID=292;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='樣式 - 暴風港 - 終點' WHERE ID=293;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='默亞基，龍骨荒野' WHERE ID=294;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='卡瑪廓，凜風峽灣' WHERE ID=295;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='昂紐沛，北風凍原' WHERE ID=296;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='休拉薩盆地 - 任務 - 偵察 - 開始' WHERE ID=297;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='休拉薩盆地 - 任務 - 偵察 - 結束' WHERE ID=298;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='Transport: Menethil <-> Valgarde' WHERE ID=299;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，暴風城' WHERE ID=300;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 北風凍原 - 找出碧西 - 起點' WHERE ID=301;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 北風凍原 - 找出碧西 - 終點' WHERE ID=302;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='驍勇臺地營地，冬握湖' WHERE ID=303;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='銀白看臺，祖爾德拉克' WHERE ID=304;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='黯黑守望，祖爾德拉克' WHERE ID=305;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='聖光止境，祖爾德拉克' WHERE ID=306;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='辛托加，祖爾德拉克' WHERE ID=307;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='大河之心，休拉薩盆地' WHERE ID=308;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='奈辛瓦里營地，休拉薩盆地' WHERE ID=309;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='達拉然' WHERE ID=310;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='歐尼克瓦營地，灰白之丘 (任務)' WHERE ID=311;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='聖光止境，祖爾德拉克(任務)' WHERE ID=312;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='西荒兵團，灰白之丘 (任務)' WHERE ID=313;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='辛托加，祖爾德拉克 (任務)' WHERE ID=314;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='亞榭洛:黯黑堡' WHERE ID=315;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='黯黑堡 - 亞榭洛 -> 死亡止境開始' WHERE ID=316;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='黯黑堡 - 亞榭洛 -> 死亡止境結束' WHERE ID=317;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='黯黑堡 - 死亡止境 -> 亞榭洛開始' WHERE ID=318;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='黯黑堡 - 死亡止境 -> 亞榭洛結束' WHERE ID=319;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='K3，風暴群山' WHERE ID=320;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='霜堡，風暴群山' WHERE ID=321;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='丹尼弗蘭，風暴群山' WHERE ID=322;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='葛羅姆亞什失事地，風暴群山' WHERE ID=323;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='坦卡羅營地，風暴群山' WHERE ID=324;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='死亡高崗，寒冰皇冠' WHERE ID=325;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='奧杜亞，風暴群山' WHERE ID=326;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='石崖避難所，風暴群山' WHERE ID=327;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，寒冰皇冠飛船 (A)' WHERE ID=328;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，寒冰皇冠飛船 (H)' WHERE ID=329;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送，寒冰皇冠(目標)' WHERE ID=330;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='剛德拉克，祖爾德拉克' WHERE ID=331;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='戰歌營地，冬握湖' WHERE ID=332;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='暗影穹殿，寒冰皇冠' WHERE ID=333;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='銀白先鋒駐地，寒冰皇冠' WHERE ID=334;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='十字軍之巔，寒冰皇冠' WHERE ID=335;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='風行者瞰臺，水晶之歌森林' WHERE ID=336;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='奪日者指揮所，水晶之歌森林' WHERE ID=337;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='銀白聯賽場地，寒冰皇冠' WHERE ID=340;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='奧杜亞團隊 - 內部 - 嵌入點' WHERE ID=341;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='奧杜亞團隊 - 鐵之集合場' WHERE ID=342;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='傳送:雷霆崖 <-> 奧格瑪(飛艇)' WHERE ID=348;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='征服之島 - 砲艇' WHERE ID=352;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='' WHERE ID=353;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='' WHERE ID=357;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 寒冰皇冠 - 北海海怪轟炸 - 起始' WHERE ID=358;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='任務 - 寒冰皇冠 - 北海海怪轟炸 - 結束' WHERE ID=359;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='REUSEME' WHERE ID=375;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='AAAIcecrown Raid - Airship Battle Taxi Paths' WHERE ID=376;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='冰冠地城 - 砲艇' WHERE ID=377;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='AAAAIcecrown Raid - Saurfang''s Ship (End)' WHERE ID=379;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='AAAAIcecrown Raid - Saurfang''s Ship (Start)' WHERE ID=380;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='AAAAQuest [Transport] Icecrown Raid - Saurfang Ship (START)' WHERE ID=381;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='Quest [Transport] Icecrown Raid - Saurfang Ship (END)' WHERE ID=382;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='索多里爾河，西瘟疫之地' WHERE ID=383;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='亡靈壁壘，提里斯法' WHERE ID=384;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='浩劫與重生序章- GT - 任務 - 通風地平線 - 開始' WHERE ID=392;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='浩劫與重生序章- GT - 任務 - 通風地平線 - 結束' WHERE ID=393;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='浩劫與重生序章- GT - 戰鬥飛行 - 開始' WHERE ID=394;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='浩劫與重生序章- GT - 戰鬥飛行 - 結束' WHERE ID=395;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='杜洛塔 - ET - CC 序章間諜青蛙開始' WHERE ID=404;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='杜洛塔 - ET - CC 序章間諜青蛙結束' WHERE ID=405;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='杜洛塔 - ET - CC 序章食人妖計程車蝙蝠開始' WHERE ID=438;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='杜洛塔 - ET - CC 序章食人妖徵召結束' WHERE ID=439;
UPDATE dbc_taxinodes SET Name_Lang_zhTW='杜洛塔 - ET - CC 序章食人妖戰鬥結束' WHERE ID=440;
