UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='獵豹形態' WHERE ID=1;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='樹形' WHERE ID=2;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='旅行形態' WHERE ID=3;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='水棲形態' WHERE ID=4;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='熊形態' WHERE ID=5;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='小動物' WHERE ID=6;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='食屍鬼' WHERE ID=7;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='巨熊形態' WHERE ID=8;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='史蒂芬的食屍鬼' WHERE ID=9;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='薩隆杰骷髏' WHERE ID=10;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='暗月 - 力量試煉' WHERE ID=11;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='BLB玩家' WHERE ID=12;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='暗影之舞' WHERE ID=13;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='生物 - 熊' WHERE ID=14;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='生物 - 豹' WHERE ID=15;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='鬼魂之狼' WHERE ID=16;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='戰鬥姿態' WHERE ID=17;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='防禦姿態' WHERE ID=18;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='狂暴姿態' WHERE ID=19;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='測試' WHERE ID=20;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='殭屍' WHERE ID=21;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='變形形態' WHERE ID=22;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='' WHERE ID=23;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='' WHERE ID=24;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='不死生物' WHERE ID=25;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='狂亂' WHERE ID=26;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='飛行形態，史詩' WHERE ID=27;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='暗影形態' WHERE ID=28;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='飛行形態' WHERE ID=29;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='潛行' WHERE ID=30;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='梟獸形態' WHERE ID=31;
UPDATE dbc_spellshapeshiftform SET Name_Lang_zhTW='救贖之靈' WHERE ID=32;
