UPDATE dbc_areapoi SET Name_Lang_enGB='Aerie Peak', Description_Lang_enGB='' WHERE ID=792;
UPDATE dbc_areapoi SET Name_Lang_enGB='Algaz Station', Description_Lang_enGB='' WHERE ID=1032;
UPDATE dbc_areapoi SET Name_Lang_enGB='Angor Fortress', Description_Lang_enGB='' WHERE ID=27;
UPDATE dbc_areapoi SET Name_Lang_enGB='Anvilmar', Description_Lang_enGB='' WHERE ID=1;
UPDATE dbc_areapoi SET Name_Lang_enGB='Ariden''s Camp', Description_Lang_enGB='' WHERE ID=1287;
UPDATE dbc_areapoi SET Name_Lang_enGB='Beggar''s Haunt', Description_Lang_enGB='' WHERE ID=1128;
UPDATE dbc_areapoi SET Name_Lang_enGB='Booty Bay', Description_Lang_enGB='' WHERE ID=40;
UPDATE dbc_areapoi SET Name_Lang_enGB='Boulderfist Outpost', Description_Lang_enGB='' WHERE ID=1010;
UPDATE dbc_areapoi SET Name_Lang_enGB='Brill', Description_Lang_enGB='' WHERE ID=2;
UPDATE dbc_areapoi SET Name_Lang_enGB='Browman Mill', Description_Lang_enGB='' WHERE ID=1018;
UPDATE dbc_areapoi SET Name_Lang_enGB='Chillwind Camp', Description_Lang_enGB='' WHERE ID=1307;
UPDATE dbc_areapoi SET Name_Lang_enGB='Crown Guard Tower', Description_Lang_enGB='' WHERE ID=1770;
UPDATE dbc_areapoi SET Name_Lang_enGB='Crown Guard Tower', Description_Lang_enGB='Alliance, Contested' WHERE ID=1771;
UPDATE dbc_areapoi SET Name_Lang_enGB='Crown Guard Tower', Description_Lang_enGB='Horde, Contested' WHERE ID=1772;
UPDATE dbc_areapoi SET Name_Lang_enGB='Crown Guard Tower', Description_Lang_enGB='Alliance, Progressing' WHERE ID=1773;
UPDATE dbc_areapoi SET Name_Lang_enGB='Crown Guard Tower', Description_Lang_enGB='Horde, Progressing' WHERE ID=1774;
UPDATE dbc_areapoi SET Name_Lang_enGB='Crown Guard Tower', Description_Lang_enGB='Alliance' WHERE ID=1775;
UPDATE dbc_areapoi SET Name_Lang_enGB='Crown Guard Tower', Description_Lang_enGB='Horde' WHERE ID=1776;
UPDATE dbc_areapoi SET Name_Lang_enGB='Darkshire', Description_Lang_enGB='' WHERE ID=3;
UPDATE dbc_areapoi SET Name_Lang_enGB='Deadwind Ravine', Description_Lang_enGB='' WHERE ID=1288;
UPDATE dbc_areapoi SET Name_Lang_enGB='Deathknell', Description_Lang_enGB='' WHERE ID=4;
UPDATE dbc_areapoi SET Name_Lang_enGB='Drywhisker Gorge', Description_Lang_enGB='' WHERE ID=327;
UPDATE dbc_areapoi SET Name_Lang_enGB='Dun Algaz', Description_Lang_enGB='' WHERE ID=5;
UPDATE dbc_areapoi SET Name_Lang_enGB='Dun Modr', Description_Lang_enGB='' WHERE ID=6;
UPDATE dbc_areapoi SET Name_Lang_enGB='Dustbelch Grotto', Description_Lang_enGB='' WHERE ID=1028;
UPDATE dbc_areapoi SET Name_Lang_enGB='Eastwall Tower', Description_Lang_enGB='' WHERE ID=1749;
UPDATE dbc_areapoi SET Name_Lang_enGB='Eastwall Tower', Description_Lang_enGB='Alliance, Contested' WHERE ID=1750;
UPDATE dbc_areapoi SET Name_Lang_enGB='Eastwall Tower', Description_Lang_enGB='Alliance, Progressing' WHERE ID=1751;
UPDATE dbc_areapoi SET Name_Lang_enGB='Eastwall Tower', Description_Lang_enGB='Horde, Contested' WHERE ID=1752;
UPDATE dbc_areapoi SET Name_Lang_enGB='Eastwall Tower', Description_Lang_enGB='Horde, Progressing' WHERE ID=1753;
UPDATE dbc_areapoi SET Name_Lang_enGB='Eastwall Tower', Description_Lang_enGB='Horde' WHERE ID=1754;
UPDATE dbc_areapoi SET Name_Lang_enGB='Eastwall Tower', Description_Lang_enGB='Alliance' WHERE ID=1755;
UPDATE dbc_areapoi SET Name_Lang_enGB='Echo Ridge Mine', Description_Lang_enGB='' WHERE ID=949;
UPDATE dbc_areapoi SET Name_Lang_enGB='Flame Crest', Description_Lang_enGB='' WHERE ID=1177;
UPDATE dbc_areapoi SET Name_Lang_enGB='Goldshire', Description_Lang_enGB='' WHERE ID=7;
UPDATE dbc_areapoi SET Name_Lang_enGB='Grim Batol', Description_Lang_enGB='' WHERE ID=1033;
UPDATE dbc_areapoi SET Name_Lang_enGB='Grom''gol Base Camp', Description_Lang_enGB='' WHERE ID=41;
UPDATE dbc_areapoi SET Name_Lang_enGB='Grosh''gok Compound', Description_Lang_enGB='' WHERE ID=1011;
UPDATE dbc_areapoi SET Name_Lang_enGB='Hammerfall', Description_Lang_enGB='' WHERE ID=25;
UPDATE dbc_areapoi SET Name_Lang_enGB='Ironband''s Compound', Description_Lang_enGB='' WHERE ID=948;
UPDATE dbc_areapoi SET Name_Lang_enGB='Ironforge', Description_Lang_enGB='' WHERE ID=8;
UPDATE dbc_areapoi SET Name_Lang_enGB='Ivar''s Patch', Description_Lang_enGB='' WHERE ID=1702;
UPDATE dbc_areapoi SET Name_Lang_enGB='Janeiro''s Point', Description_Lang_enGB='' WHERE ID=1031;
UPDATE dbc_areapoi SET Name_Lang_enGB='Jasperlode Mine', Description_Lang_enGB='' WHERE ID=1030;
UPDATE dbc_areapoi SET Name_Lang_enGB='Kargath', Description_Lang_enGB='' WHERE ID=26;
UPDATE dbc_areapoi SET Name_Lang_enGB='Kharanos', Description_Lang_enGB='' WHERE ID=9;
UPDATE dbc_areapoi SET Name_Lang_enGB='Lakeshire', Description_Lang_enGB='' WHERE ID=10;
UPDATE dbc_areapoi SET Name_Lang_enGB='Maclure Vineyards', Description_Lang_enGB='' WHERE ID=950;
UPDATE dbc_areapoi SET Name_Lang_enGB='Menethil Harbor', Description_Lang_enGB='' WHERE ID=11;
UPDATE dbc_areapoi SET Name_Lang_enGB='Mirror Lake', Description_Lang_enGB='' WHERE ID=227;
UPDATE dbc_areapoi SET Name_Lang_enGB='Misty Reed Post', Description_Lang_enGB='' WHERE ID=1683;
UPDATE dbc_areapoi SET Name_Lang_enGB='Moonbrook', Description_Lang_enGB='' WHERE ID=12;
UPDATE dbc_areapoi SET Name_Lang_enGB='Night Web''s Hollow', Description_Lang_enGB='' WHERE ID=1016;
UPDATE dbc_areapoi SET Name_Lang_enGB='Northpass Tower', Description_Lang_enGB='' WHERE ID=1763;
UPDATE dbc_areapoi SET Name_Lang_enGB='Northpass Tower', Description_Lang_enGB='Alliance, Contested' WHERE ID=1764;
UPDATE dbc_areapoi SET Name_Lang_enGB='Northpass Tower', Description_Lang_enGB='Horde, Contested' WHERE ID=1765;
UPDATE dbc_areapoi SET Name_Lang_enGB='Northpass Tower', Description_Lang_enGB='Alliance, Progressing' WHERE ID=1766;
UPDATE dbc_areapoi SET Name_Lang_enGB='Northpass Tower', Description_Lang_enGB='Horde, Progressing' WHERE ID=1767;
UPDATE dbc_areapoi SET Name_Lang_enGB='Northpass Tower', Description_Lang_enGB='Alliance' WHERE ID=1768;
UPDATE dbc_areapoi SET Name_Lang_enGB='Northpass Tower', Description_Lang_enGB='Horde' WHERE ID=1769;
UPDATE dbc_areapoi SET Name_Lang_enGB='Northshire Abbey', Description_Lang_enGB='' WHERE ID=13;
UPDATE dbc_areapoi SET Name_Lang_enGB='Northshire Vineyards', Description_Lang_enGB='' WHERE ID=954;
UPDATE dbc_areapoi SET Name_Lang_enGB='Plaguewood Tower', Description_Lang_enGB='' WHERE ID=1756;
UPDATE dbc_areapoi SET Name_Lang_enGB='Plaguewood Tower', Description_Lang_enGB='Alliance, Contested' WHERE ID=1757;
UPDATE dbc_areapoi SET Name_Lang_enGB='Plaguewood Tower', Description_Lang_enGB='Horde, Progressing' WHERE ID=1760;
UPDATE dbc_areapoi SET Name_Lang_enGB='Plaguewood Tower', Description_Lang_enGB='Alliance' WHERE ID=1761;
UPDATE dbc_areapoi SET Name_Lang_enGB='Plaguewood Tower', Description_Lang_enGB='Horde' WHERE ID=1762;
UPDATE dbc_areapoi SET Name_Lang_enGB='Plaguewood Tower', Description_Lang_enGB='Alliance, Progressing' WHERE ID=1777;
UPDATE dbc_areapoi SET Name_Lang_enGB='Raven Hill', Description_Lang_enGB='' WHERE ID=14;
UPDATE dbc_areapoi SET Name_Lang_enGB='Refuge Pointe', Description_Lang_enGB='' WHERE ID=24;
UPDATE dbc_areapoi SET Name_Lang_enGB='Render''s Rock', Description_Lang_enGB='' WHERE ID=956;
UPDATE dbc_areapoi SET Name_Lang_enGB='Rethban Caverns', Description_Lang_enGB='' WHERE ID=1008;
UPDATE dbc_areapoi SET Name_Lang_enGB='Revantusk Village', Description_Lang_enGB='' WHERE ID=1507;
UPDATE dbc_areapoi SET Name_Lang_enGB='Roland''s Doom', Description_Lang_enGB='' WHERE ID=1127;
UPDATE dbc_areapoi SET Name_Lang_enGB='Scholomance', Description_Lang_enGB='' WHERE ID=710;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sentinel Hill', Description_Lang_enGB='' WHERE ID=15;
UPDATE dbc_areapoi SET Name_Lang_enGB='Slaughter Hollow', Description_Lang_enGB='' WHERE ID=247;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sleeping Gorge', Description_Lang_enGB='' WHERE ID=1289;
UPDATE dbc_areapoi SET Name_Lang_enGB='Slither Rock', Description_Lang_enGB='' WHERE ID=1176;
UPDATE dbc_areapoi SET Name_Lang_enGB='Southshore', Description_Lang_enGB='' WHERE ID=22;
UPDATE dbc_areapoi SET Name_Lang_enGB='Spirit Den', Description_Lang_enGB='' WHERE ID=1007;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stagalbog Cave', Description_Lang_enGB='' WHERE ID=1012;
UPDATE dbc_areapoi SET Name_Lang_enGB='Steelgrill''s Depot', Description_Lang_enGB='' WHERE ID=947;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stonard', Description_Lang_enGB='' WHERE ID=788;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stonefield Farm', Description_Lang_enGB='' WHERE ID=951;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stormwind City', Description_Lang_enGB='' WHERE ID=16;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stormwind Harbor', Description_Lang_enGB='' WHERE ID=2110;
UPDATE dbc_areapoi SET Name_Lang_enGB='Tarren Mill', Description_Lang_enGB='' WHERE ID=23;
UPDATE dbc_areapoi SET Name_Lang_enGB='Temple of Atal''Hakkar', Description_Lang_enGB='' WHERE ID=1013;
UPDATE dbc_areapoi SET Name_Lang_enGB='Terrorweb Tunnel', Description_Lang_enGB='' WHERE ID=1017;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Sepulcher', Description_Lang_enGB='' WHERE ID=17;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Tower of Arathor', Description_Lang_enGB='' WHERE ID=1014;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Weeping Cave', Description_Lang_enGB='' WHERE ID=1551;
UPDATE dbc_areapoi SET Name_Lang_enGB='Thelsamar', Description_Lang_enGB='' WHERE ID=19;
UPDATE dbc_areapoi SET Name_Lang_enGB='Thorium Point', Description_Lang_enGB='' WHERE ID=1508;
UPDATE dbc_areapoi SET Name_Lang_enGB='Tower of Ilgalar', Description_Lang_enGB='' WHERE ID=955;
UPDATE dbc_areapoi SET Name_Lang_enGB='Uldaman', Description_Lang_enGB='' WHERE ID=1027;
UPDATE dbc_areapoi SET Name_Lang_enGB='Under Attack', Description_Lang_enGB='Blasted Lands' WHERE ID=1698;
UPDATE dbc_areapoi SET Name_Lang_enGB='Under Attack', Description_Lang_enGB='Burning Steppes' WHERE ID=1699;
UPDATE dbc_areapoi SET Name_Lang_enGB='Under Attack', Description_Lang_enGB='Eastern Plaguelands' WHERE ID=1701;
UPDATE dbc_areapoi SET Name_Lang_enGB='Undercity', Description_Lang_enGB='' WHERE ID=18;
UPDATE dbc_areapoi SET Name_Lang_enGB='Uther''s Tomb', Description_Lang_enGB='' WHERE ID=709;
UPDATE dbc_areapoi SET Name_Lang_enGB='Valgan''s Field', Description_Lang_enGB='' WHERE ID=1703;
UPDATE dbc_areapoi SET Name_Lang_enGB='Westbrook Garrison', Description_Lang_enGB='' WHERE ID=1029;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wildhammer Keep', Description_Lang_enGB='' WHERE ID=1015;
UPDATE dbc_areapoi SET Name_Lang_enGB='Yojamba Isle', Description_Lang_enGB='' WHERE ID=1588;
UPDATE dbc_areapoi SET Name_Lang_enGB='Aldrassil', Description_Lang_enGB='' WHERE ID=36;
UPDATE dbc_areapoi SET Name_Lang_enGB='Aldrassil', Description_Lang_enGB='' WHERE ID=907;
UPDATE dbc_areapoi SET Name_Lang_enGB='Astranaar', Description_Lang_enGB='' WHERE ID=42;
UPDATE dbc_areapoi SET Name_Lang_enGB='Auberdine', Description_Lang_enGB='' WHERE ID=798;
UPDATE dbc_areapoi SET Name_Lang_enGB='Ban''ethil Barrow Den', Description_Lang_enGB='' WHERE ID=911;
UPDATE dbc_areapoi SET Name_Lang_enGB='Bathran''s Haunt', Description_Lang_enGB='' WHERE ID=1233;
UPDATE dbc_areapoi SET Name_Lang_enGB='Blackwood Den', Description_Lang_enGB='' WHERE ID=1048;
UPDATE dbc_areapoi SET Name_Lang_enGB='Bloodfen Burrow', Description_Lang_enGB='' WHERE ID=1096;
UPDATE dbc_areapoi SET Name_Lang_enGB='Bloodhoof Village', Description_Lang_enGB='' WHERE ID=28;
UPDATE dbc_areapoi SET Name_Lang_enGB='Bloodtooth Camp', Description_Lang_enGB='' WHERE ID=1244;
UPDATE dbc_areapoi SET Name_Lang_enGB='Bloodvenom Post', Description_Lang_enGB='' WHERE ID=1220;
UPDATE dbc_areapoi SET Name_Lang_enGB='Bluefen', Description_Lang_enGB='' WHERE ID=1090;
UPDATE dbc_areapoi SET Name_Lang_enGB='Bolgan''s Hole', Description_Lang_enGB='' WHERE ID=1147;
UPDATE dbc_areapoi SET Name_Lang_enGB='Bones of Grakkarond', Description_Lang_enGB='' WHERE ID=1473;
UPDATE dbc_areapoi SET Name_Lang_enGB='Brackenwall Village', Description_Lang_enGB='' WHERE ID=1684;
UPDATE dbc_areapoi SET Name_Lang_enGB='Bronzebeard Encampment', Description_Lang_enGB='' WHERE ID=1694;
UPDATE dbc_areapoi SET Name_Lang_enGB='Camp Mojache', Description_Lang_enGB='' WHERE ID=790;
UPDATE dbc_areapoi SET Name_Lang_enGB='Camp Narache', Description_Lang_enGB='' WHERE ID=30;
UPDATE dbc_areapoi SET Name_Lang_enGB='Camp Taurajo', Description_Lang_enGB='' WHERE ID=1469;
UPDATE dbc_areapoi SET Name_Lang_enGB='Cenarion Hold', Description_Lang_enGB='' WHERE ID=1685;
UPDATE dbc_areapoi SET Name_Lang_enGB='Cliffspring Falls', Description_Lang_enGB='' WHERE ID=1050;
UPDATE dbc_areapoi SET Name_Lang_enGB='Cragpool Lake', Description_Lang_enGB='' WHERE ID=1228;
UPDATE dbc_areapoi SET Name_Lang_enGB='Darkcloud Pinnacle', Description_Lang_enGB='' WHERE ID=1108;
UPDATE dbc_areapoi SET Name_Lang_enGB='Darkmist Cavern', Description_Lang_enGB='' WHERE ID=1088;
UPDATE dbc_areapoi SET Name_Lang_enGB='Darnassus', Description_Lang_enGB='' WHERE ID=38;
UPDATE dbc_areapoi SET Name_Lang_enGB='Demon Fall Canyon', Description_Lang_enGB='' WHERE ID=1239;
UPDATE dbc_areapoi SET Name_Lang_enGB='Dolanaar', Description_Lang_enGB='' WHERE ID=37;
UPDATE dbc_areapoi SET Name_Lang_enGB='Dun Mandarr', Description_Lang_enGB='' WHERE ID=1214;
UPDATE dbc_areapoi SET Name_Lang_enGB='Emberstrife''s Den', Description_Lang_enGB='' WHERE ID=1095;
UPDATE dbc_areapoi SET Name_Lang_enGB='Everlook', Description_Lang_enGB='' WHERE ID=794;
UPDATE dbc_areapoi SET Name_Lang_enGB='Falfarren River', Description_Lang_enGB='' WHERE ID=1235;
UPDATE dbc_areapoi SET Name_Lang_enGB='Feathermoon Stronghold', Description_Lang_enGB='' WHERE ID=796;
UPDATE dbc_areapoi SET Name_Lang_enGB='Fel Rock', Description_Lang_enGB='' WHERE ID=909;
UPDATE dbc_areapoi SET Name_Lang_enGB='Forest Song', Description_Lang_enGB='' WHERE ID=1238;
UPDATE dbc_areapoi SET Name_Lang_enGB='Fray Island', Description_Lang_enGB='' WHERE ID=1067;
UPDATE dbc_areapoi SET Name_Lang_enGB='Freewind Post', Description_Lang_enGB='' WHERE ID=46;
UPDATE dbc_areapoi SET Name_Lang_enGB='Fungal Rock', Description_Lang_enGB='' WHERE ID=1105;
UPDATE dbc_areapoi SET Name_Lang_enGB='Gadgetzan', Description_Lang_enGB='' WHERE ID=789;
UPDATE dbc_areapoi SET Name_Lang_enGB='Ghost Walker Post', Description_Lang_enGB='' WHERE ID=1149;
UPDATE dbc_areapoi SET Name_Lang_enGB='Greenpaw Village', Description_Lang_enGB='' WHERE ID=1243;
UPDATE dbc_areapoi SET Name_Lang_enGB='Hetaera''s Clutch', Description_Lang_enGB='' WHERE ID=708;
UPDATE dbc_areapoi SET Name_Lang_enGB='Ironstone Camp', Description_Lang_enGB='' WHERE ID=1114;
UPDATE dbc_areapoi SET Name_Lang_enGB='Irontree Cavern', Description_Lang_enGB='' WHERE ID=1219;
UPDATE dbc_areapoi SET Name_Lang_enGB='Lariss Pavillion', Description_Lang_enGB='' WHERE ID=1175;
UPDATE dbc_areapoi SET Name_Lang_enGB='Lost Point', Description_Lang_enGB='' WHERE ID=1091;
UPDATE dbc_areapoi SET Name_Lang_enGB='Maraudon', Description_Lang_enGB='' WHERE ID=1148;
UPDATE dbc_areapoi SET Name_Lang_enGB='Marshal''s Refuge', Description_Lang_enGB='' WHERE ID=1104;
UPDATE dbc_areapoi SET Name_Lang_enGB='Mirage Raceway', Description_Lang_enGB='' WHERE ID=1110;
UPDATE dbc_areapoi SET Name_Lang_enGB='Moon Horror Den', Description_Lang_enGB='' WHERE ID=1217;
UPDATE dbc_areapoi SET Name_Lang_enGB='Mor''shan Base Camp', Description_Lang_enGB='' WHERE ID=1512;
UPDATE dbc_areapoi SET Name_Lang_enGB='Mudsprocket', Description_Lang_enGB='' WHERE ID=2083;
UPDATE dbc_areapoi SET Name_Lang_enGB='Nighthaven', Description_Lang_enGB='' WHERE ID=1247;
UPDATE dbc_areapoi SET Name_Lang_enGB='Nijel''s Point', Description_Lang_enGB='' WHERE ID=799;
UPDATE dbc_areapoi SET Name_Lang_enGB='North Point Tower', Description_Lang_enGB='' WHERE ID=1089;
UPDATE dbc_areapoi SET Name_Lang_enGB='Onyxia''s Lair', Description_Lang_enGB='' WHERE ID=1094;
UPDATE dbc_areapoi SET Name_Lang_enGB='Orgrimmar', Description_Lang_enGB='' WHERE ID=33;
UPDATE dbc_areapoi SET Name_Lang_enGB='Ortell''s Hideout', Description_Lang_enGB='' WHERE ID=1690;
UPDATE dbc_areapoi SET Name_Lang_enGB='Rage Scar Hold', Description_Lang_enGB='' WHERE ID=1168;
UPDATE dbc_areapoi SET Name_Lang_enGB='Ratchet', Description_Lang_enGB='' WHERE ID=39;
UPDATE dbc_areapoi SET Name_Lang_enGB='Ravaged Twilight Camp', Description_Lang_enGB='' WHERE ID=1171;
UPDATE dbc_areapoi SET Name_Lang_enGB='Razor Hill', Description_Lang_enGB='' WHERE ID=31;
UPDATE dbc_areapoi SET Name_Lang_enGB='Razorwind Canyon', Description_Lang_enGB='' WHERE ID=913;
UPDATE dbc_areapoi SET Name_Lang_enGB='Rethress Sanctum', Description_Lang_enGB='' WHERE ID=1216;
UPDATE dbc_areapoi SET Name_Lang_enGB='Roguefeather Den', Description_Lang_enGB='' WHERE ID=1109;
UPDATE dbc_areapoi SET Name_Lang_enGB='Ruins of Solarsal', Description_Lang_enGB='' WHERE ID=1169;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sandworm!', Description_Lang_enGB='A Silithyst beast has surfaced' WHERE ID=1724;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sandworm!', Description_Lang_enGB='A Silithyst beast has surfaced' WHERE ID=1725;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sandworm!', Description_Lang_enGB='A Silithyst beast has surfaced' WHERE ID=1726;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sandworm!', Description_Lang_enGB='A Silithyst beast has surfaced' WHERE ID=1727;
UPDATE dbc_areapoi SET Name_Lang_enGB='Scalebeard''s Cave', Description_Lang_enGB='' WHERE ID=1211;
UPDATE dbc_areapoi SET Name_Lang_enGB='Scrabblescrew''s Camp', Description_Lang_enGB='' WHERE ID=1150;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sen''jin Village', Description_Lang_enGB='' WHERE ID=34;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sentry Point', Description_Lang_enGB='' WHERE ID=1097;
UPDATE dbc_areapoi SET Name_Lang_enGB='Shadowprey Village', Description_Lang_enGB='' WHERE ID=795;
UPDATE dbc_areapoi SET Name_Lang_enGB='Shadowthread Cave', Description_Lang_enGB='' WHERE ID=908;
UPDATE dbc_areapoi SET Name_Lang_enGB='Shady Rest Inn', Description_Lang_enGB='' WHERE ID=1087;
UPDATE dbc_areapoi SET Name_Lang_enGB='Shalzaru''s Lair', Description_Lang_enGB='' WHERE ID=1187;
UPDATE dbc_areapoi SET Name_Lang_enGB='Shrine of Remulos', Description_Lang_enGB='' WHERE ID=1246;
UPDATE dbc_areapoi SET Name_Lang_enGB='Silverwind Refuge', Description_Lang_enGB='' WHERE ID=1242;
UPDATE dbc_areapoi SET Name_Lang_enGB='Silverwing Grove', Description_Lang_enGB='' WHERE ID=1513;
UPDATE dbc_areapoi SET Name_Lang_enGB='Silverwing Outpost', Description_Lang_enGB='' WHERE ID=1240;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sishir Canyon', Description_Lang_enGB='' WHERE ID=1227;
UPDATE dbc_areapoi SET Name_Lang_enGB='Splintertree Post', Description_Lang_enGB='' WHERE ID=1471;
UPDATE dbc_areapoi SET Name_Lang_enGB='Splithoof Hold', Description_Lang_enGB='' WHERE ID=1112;
UPDATE dbc_areapoi SET Name_Lang_enGB='Staghelm Point', Description_Lang_enGB='' WHERE ID=1688;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stonemaul Ruins', Description_Lang_enGB='' WHERE ID=1093;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stonetalon Peak', Description_Lang_enGB='' WHERE ID=44;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stormrage Barrow Dens', Description_Lang_enGB='' WHERE ID=1248;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sun Rock Retreat', Description_Lang_enGB='' WHERE ID=701;
UPDATE dbc_areapoi SET Name_Lang_enGB='Swamplight Manor', Description_Lang_enGB='' WHERE ID=1098;
UPDATE dbc_areapoi SET Name_Lang_enGB='Tahonda Ruins', Description_Lang_enGB='' WHERE ID=1116;
UPDATE dbc_areapoi SET Name_Lang_enGB='Talrendis Point', Description_Lang_enGB='' WHERE ID=1215;
UPDATE dbc_areapoi SET Name_Lang_enGB='Temple of Zin-Malor', Description_Lang_enGB='' WHERE ID=707;
UPDATE dbc_areapoi SET Name_Lang_enGB='Thalanaar', Description_Lang_enGB='' WHERE ID=45;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Cleft', Description_Lang_enGB='' WHERE ID=912;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Crossroads', Description_Lang_enGB='' WHERE ID=35;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Den', Description_Lang_enGB='' WHERE ID=32;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Dor''Danil Barrow Den', Description_Lang_enGB='' WHERE ID=1241;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Ruins of Kel''Theril', Description_Lang_enGB='' WHERE ID=1213;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Ruins of Ordil''Aran', Description_Lang_enGB='' WHERE ID=1232;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Rustmaul Digsite', Description_Lang_enGB='' WHERE ID=1111;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Swarming Pillar', Description_Lang_enGB='' WHERE ID=1472;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Talon Den', Description_Lang_enGB='' WHERE ID=1231;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Talondeep Path', Description_Lang_enGB='' WHERE ID=1230;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Talondeep Path', Description_Lang_enGB='' WHERE ID=1245;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Weathered Nook', Description_Lang_enGB='' WHERE ID=1113;
UPDATE dbc_areapoi SET Name_Lang_enGB='Theramore Isle', Description_Lang_enGB='' WHERE ID=791;
UPDATE dbc_areapoi SET Name_Lang_enGB='Thunder Bluff', Description_Lang_enGB='' WHERE ID=29;
UPDATE dbc_areapoi SET Name_Lang_enGB='Tidefury Cove', Description_Lang_enGB='' WHERE ID=1092;
UPDATE dbc_areapoi SET Name_Lang_enGB='Timbermaw Hold', Description_Lang_enGB='' WHERE ID=1212;
UPDATE dbc_areapoi SET Name_Lang_enGB='Timbermaw Hold', Description_Lang_enGB='' WHERE ID=1218;
UPDATE dbc_areapoi SET Name_Lang_enGB='Tor''kren Farm', Description_Lang_enGB='' WHERE ID=929;
UPDATE dbc_areapoi SET Name_Lang_enGB='Twilight Base Camp', Description_Lang_enGB='' WHERE ID=1687;
UPDATE dbc_areapoi SET Name_Lang_enGB='Twilight Outpost', Description_Lang_enGB='' WHERE ID=1173;
UPDATE dbc_areapoi SET Name_Lang_enGB='Twilight Post', Description_Lang_enGB='' WHERE ID=1172;
UPDATE dbc_areapoi SET Name_Lang_enGB='Twilight''s Run', Description_Lang_enGB='' WHERE ID=1689;
UPDATE dbc_areapoi SET Name_Lang_enGB='Uldum', Description_Lang_enGB='' WHERE ID=1107;
UPDATE dbc_areapoi SET Name_Lang_enGB='Under Attack', Description_Lang_enGB='Winterspring' WHERE ID=1696;
UPDATE dbc_areapoi SET Name_Lang_enGB='Under Attack', Description_Lang_enGB='Azshara' WHERE ID=1697;
UPDATE dbc_areapoi SET Name_Lang_enGB='Under Attack', Description_Lang_enGB='Tanaris Desert' WHERE ID=1700;
UPDATE dbc_areapoi SET Name_Lang_enGB='Valley of Bones', Description_Lang_enGB='' WHERE ID=1151;
UPDATE dbc_areapoi SET Name_Lang_enGB='Valor''s Rest', Description_Lang_enGB='' WHERE ID=1567;
UPDATE dbc_areapoi SET Name_Lang_enGB='Venture Co. Mine', Description_Lang_enGB='' WHERE ID=1047;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wailing Caverns', Description_Lang_enGB='' WHERE ID=1068;
UPDATE dbc_areapoi SET Name_Lang_enGB='Warsong Labor Camp', Description_Lang_enGB='' WHERE ID=1268;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wavestrider Beach', Description_Lang_enGB='' WHERE ID=1106;
UPDATE dbc_areapoi SET Name_Lang_enGB='Weazel''s Crater', Description_Lang_enGB='' WHERE ID=1115;
UPDATE dbc_areapoi SET Name_Lang_enGB='Whitereach Post', Description_Lang_enGB='' WHERE ID=767;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wildbend River', Description_Lang_enGB='' WHERE ID=1049;
UPDATE dbc_areapoi SET Name_Lang_enGB='Windshear Mine', Description_Lang_enGB='' WHERE ID=1229;
UPDATE dbc_areapoi SET Name_Lang_enGB='Woodpaw Den', Description_Lang_enGB='' WHERE ID=1475;
UPDATE dbc_areapoi SET Name_Lang_enGB='Woodpaw Hills', Description_Lang_enGB='' WHERE ID=1174;
UPDATE dbc_areapoi SET Name_Lang_enGB='Xavian', Description_Lang_enGB='' WHERE ID=1237;
UPDATE dbc_areapoi SET Name_Lang_enGB='Zoram''gar Outpost', Description_Lang_enGB='' WHERE ID=1234;
UPDATE dbc_areapoi SET Name_Lang_enGB='Coldtooth Mine', Description_Lang_enGB='Horde Controlled' WHERE ID=1102;
UPDATE dbc_areapoi SET Name_Lang_enGB='Coldtooth Mine', Description_Lang_enGB='Alliance Controlled' WHERE ID=1358;
UPDATE dbc_areapoi SET Name_Lang_enGB='Coldtooth Mine', Description_Lang_enGB='Kobold Controlled' WHERE ID=1359;
UPDATE dbc_areapoi SET Name_Lang_enGB='Dun Baldar', Description_Lang_enGB='' WHERE ID=1328;
UPDATE dbc_areapoi SET Name_Lang_enGB='Dun Baldar North Bunker', Description_Lang_enGB='Alliance Controlled' WHERE ID=1250;
UPDATE dbc_areapoi SET Name_Lang_enGB='Dun Baldar North Bunker', Description_Lang_enGB='Destroyed' WHERE ID=1352;
UPDATE dbc_areapoi SET Name_Lang_enGB='Dun Baldar North Bunker', Description_Lang_enGB='In Conflict' WHERE ID=1353;
UPDATE dbc_areapoi SET Name_Lang_enGB='Dun Baldar North Bunker', Description_Lang_enGB='In Conflict' WHERE ID=1354;
UPDATE dbc_areapoi SET Name_Lang_enGB='Dun Baldar South Bunker', Description_Lang_enGB='Alliance Controlled' WHERE ID=1249;
UPDATE dbc_areapoi SET Name_Lang_enGB='Dun Baldar South Bunker', Description_Lang_enGB='Destroyed' WHERE ID=1355;
UPDATE dbc_areapoi SET Name_Lang_enGB='Dun Baldar South Bunker', Description_Lang_enGB='In Conflict' WHERE ID=1356;
UPDATE dbc_areapoi SET Name_Lang_enGB='Dun Baldar South Bunker', Description_Lang_enGB='In Conflict' WHERE ID=1357;
UPDATE dbc_areapoi SET Name_Lang_enGB='East Frostwolf Tower', Description_Lang_enGB='Horde Controlled' WHERE ID=1255;
UPDATE dbc_areapoi SET Name_Lang_enGB='East Frostwolf Tower', Description_Lang_enGB='Destoyed' WHERE ID=1362;
UPDATE dbc_areapoi SET Name_Lang_enGB='East Frostwolf Tower', Description_Lang_enGB='In Conflict' WHERE ID=1363;
UPDATE dbc_areapoi SET Name_Lang_enGB='East Frostwolf Tower', Description_Lang_enGB='In Conflict' WHERE ID=1364;
UPDATE dbc_areapoi SET Name_Lang_enGB='Frostwolf Graveyard', Description_Lang_enGB='Horde Controlled' WHERE ID=1210;
UPDATE dbc_areapoi SET Name_Lang_enGB='Frostwolf Graveyard', Description_Lang_enGB='Alliance Controlled' WHERE ID=1368;
UPDATE dbc_areapoi SET Name_Lang_enGB='Frostwolf Graveyard', Description_Lang_enGB='In Conflict' WHERE ID=1369;
UPDATE dbc_areapoi SET Name_Lang_enGB='Frostwolf Graveyard', Description_Lang_enGB='In Conflict' WHERE ID=1370;
UPDATE dbc_areapoi SET Name_Lang_enGB='Frostwolf Keep', Description_Lang_enGB='' WHERE ID=1103;
UPDATE dbc_areapoi SET Name_Lang_enGB='Frostwolf Relief Hut', Description_Lang_enGB='Horde Controlled' WHERE ID=1351;
UPDATE dbc_areapoi SET Name_Lang_enGB='Frostwolf Relief Hut', Description_Lang_enGB='Alliance Controlled' WHERE ID=1371;
UPDATE dbc_areapoi SET Name_Lang_enGB='Frostwolf Relief Hut', Description_Lang_enGB='In Conflict' WHERE ID=1372;
UPDATE dbc_areapoi SET Name_Lang_enGB='Frostwolf Relief Hut', Description_Lang_enGB='In Conflict' WHERE ID=1373;
UPDATE dbc_areapoi SET Name_Lang_enGB='Iceblood Garrison', Description_Lang_enGB='' WHERE ID=1101;
UPDATE dbc_areapoi SET Name_Lang_enGB='Iceblood Graveyard', Description_Lang_enGB='Horde Controlled' WHERE ID=1349;
UPDATE dbc_areapoi SET Name_Lang_enGB='Iceblood Graveyard', Description_Lang_enGB='Alliance Controlled' WHERE ID=1374;
UPDATE dbc_areapoi SET Name_Lang_enGB='Iceblood Graveyard', Description_Lang_enGB='In Conflict' WHERE ID=1375;
UPDATE dbc_areapoi SET Name_Lang_enGB='Iceblood Graveyard', Description_Lang_enGB='In Conflict' WHERE ID=1376;
UPDATE dbc_areapoi SET Name_Lang_enGB='Iceblood Tower', Description_Lang_enGB='Horde Controlled' WHERE ID=1252;
UPDATE dbc_areapoi SET Name_Lang_enGB='Iceblood Tower', Description_Lang_enGB='Destroyed' WHERE ID=1377;
UPDATE dbc_areapoi SET Name_Lang_enGB='Iceblood Tower', Description_Lang_enGB='In Conflict' WHERE ID=1378;
UPDATE dbc_areapoi SET Name_Lang_enGB='Iceblood Tower', Description_Lang_enGB='In Conflict' WHERE ID=1379;
UPDATE dbc_areapoi SET Name_Lang_enGB='Icewing Bunker', Description_Lang_enGB='Alliance Controlled' WHERE ID=1251;
UPDATE dbc_areapoi SET Name_Lang_enGB='Icewing Bunker', Description_Lang_enGB='Destroyed' WHERE ID=1380;
UPDATE dbc_areapoi SET Name_Lang_enGB='Icewing Bunker', Description_Lang_enGB='In Conflict' WHERE ID=1381;
UPDATE dbc_areapoi SET Name_Lang_enGB='Icewing Bunker', Description_Lang_enGB='In Conflict' WHERE ID=1382;
UPDATE dbc_areapoi SET Name_Lang_enGB='Icewing Cavern', Description_Lang_enGB='' WHERE ID=1569;
UPDATE dbc_areapoi SET Name_Lang_enGB='Irondeep Mine', Description_Lang_enGB='Alliance Controlled' WHERE ID=1099;
UPDATE dbc_areapoi SET Name_Lang_enGB='Irondeep Mine', Description_Lang_enGB='Horde Controlled' WHERE ID=1383;
UPDATE dbc_areapoi SET Name_Lang_enGB='Irondeep Mine', Description_Lang_enGB='Trogg Controlled' WHERE ID=1384;
UPDATE dbc_areapoi SET Name_Lang_enGB='Pre-alliance POI test', Description_Lang_enGB='' WHERE ID=1550;
UPDATE dbc_areapoi SET Name_Lang_enGB='Snowfall Graveyard', Description_Lang_enGB='Horde Controlled' WHERE ID=1209;
UPDATE dbc_areapoi SET Name_Lang_enGB='Snowfall Graveyard', Description_Lang_enGB='Alliance Controlled' WHERE ID=1386;
UPDATE dbc_areapoi SET Name_Lang_enGB='Snowfall Graveyard', Description_Lang_enGB='In Conflict' WHERE ID=1387;
UPDATE dbc_areapoi SET Name_Lang_enGB='Snowfall Graveyard', Description_Lang_enGB='In Conflict' WHERE ID=1388;
UPDATE dbc_areapoi SET Name_Lang_enGB='Snowfall Graveyard', Description_Lang_enGB='Uncontrolled' WHERE ID=1682;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stonehearth Bunker', Description_Lang_enGB='Alliance Controlled' WHERE ID=1347;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stonehearth Bunker', Description_Lang_enGB='Destroyed' WHERE ID=1389;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stonehearth Bunker', Description_Lang_enGB='In Conflict' WHERE ID=1390;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stonehearth Bunker', Description_Lang_enGB='In Conflict' WHERE ID=1391;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stonehearth Graveyard', Description_Lang_enGB='Alliance Controlled' WHERE ID=1350;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stonehearth Graveyard', Description_Lang_enGB='Horde Controlled' WHERE ID=1392;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stonehearth Graveyard', Description_Lang_enGB='In Conflict' WHERE ID=1393;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stonehearth Graveyard', Description_Lang_enGB='In Conflict' WHERE ID=1394;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stonehearth Outpost', Description_Lang_enGB='' WHERE ID=1100;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stormpike Aid Station', Description_Lang_enGB='Alliance Controlled' WHERE ID=1348;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stormpike Aid Station', Description_Lang_enGB='Horde Controlled' WHERE ID=1395;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stormpike Aid Station', Description_Lang_enGB='In Conflict' WHERE ID=1396;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stormpike Aid Station', Description_Lang_enGB='In Conflict' WHERE ID=1397;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stormpike Graveyard', Description_Lang_enGB='Alliance Controlled' WHERE ID=1208;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stormpike Graveyard', Description_Lang_enGB='Horde Controlled' WHERE ID=1398;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stormpike Graveyard', Description_Lang_enGB='In Conflict' WHERE ID=1399;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stormpike Graveyard', Description_Lang_enGB='In Conflict' WHERE ID=1400;
UPDATE dbc_areapoi SET Name_Lang_enGB='Tower Point', Description_Lang_enGB='Horde Controlled' WHERE ID=1254;
UPDATE dbc_areapoi SET Name_Lang_enGB='Tower Point', Description_Lang_enGB='Destroyed' WHERE ID=1405;
UPDATE dbc_areapoi SET Name_Lang_enGB='Tower Point', Description_Lang_enGB='In Conflict' WHERE ID=1406;
UPDATE dbc_areapoi SET Name_Lang_enGB='Tower Point', Description_Lang_enGB='In Conflict' WHERE ID=1407;
UPDATE dbc_areapoi SET Name_Lang_enGB='West Frostwolf Tower', Description_Lang_enGB='Horde Controlled' WHERE ID=1527;
UPDATE dbc_areapoi SET Name_Lang_enGB='West Frostwolf Tower', Description_Lang_enGB='Destroyed' WHERE ID=1528;
UPDATE dbc_areapoi SET Name_Lang_enGB='West Frostwolf Tower', Description_Lang_enGB='In Conflict' WHERE ID=1529;
UPDATE dbc_areapoi SET Name_Lang_enGB='West Frostwolf Tower', Description_Lang_enGB='In Conflict' WHERE ID=1530;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wildpaw Cavern', Description_Lang_enGB='' WHERE ID=1568;
UPDATE dbc_areapoi SET Name_Lang_enGB='Alliance', Description_Lang_enGB='' WHERE ID=20;
UPDATE dbc_areapoi SET Name_Lang_enGB='Horde', Description_Lang_enGB='' WHERE ID=21;
UPDATE dbc_areapoi SET Name_Lang_enGB='Blacksmith', Description_Lang_enGB='Uncontrolled' WHERE ID=1614;
UPDATE dbc_areapoi SET Name_Lang_enGB='Blacksmith', Description_Lang_enGB='Alliance Controlled' WHERE ID=1615;
UPDATE dbc_areapoi SET Name_Lang_enGB='Blacksmith', Description_Lang_enGB='Horde Controlled' WHERE ID=1616;
UPDATE dbc_areapoi SET Name_Lang_enGB='Blacksmith', Description_Lang_enGB='In Conflict' WHERE ID=1617;
UPDATE dbc_areapoi SET Name_Lang_enGB='Blacksmith', Description_Lang_enGB='In Conflict' WHERE ID=1618;
UPDATE dbc_areapoi SET Name_Lang_enGB='Farm', Description_Lang_enGB='Uncontrolled' WHERE ID=1629;
UPDATE dbc_areapoi SET Name_Lang_enGB='Farm', Description_Lang_enGB='Alliance Controlled' WHERE ID=1630;
UPDATE dbc_areapoi SET Name_Lang_enGB='Farm', Description_Lang_enGB='Horde Controlled' WHERE ID=1631;
UPDATE dbc_areapoi SET Name_Lang_enGB='Farm', Description_Lang_enGB='In Conflict' WHERE ID=1632;
UPDATE dbc_areapoi SET Name_Lang_enGB='Farm', Description_Lang_enGB='In Conflict' WHERE ID=1633;
UPDATE dbc_areapoi SET Name_Lang_enGB='Gold Mine', Description_Lang_enGB='Uncontrolled' WHERE ID=1624;
UPDATE dbc_areapoi SET Name_Lang_enGB='Gold Mine', Description_Lang_enGB='Alliance Controlled' WHERE ID=1625;
UPDATE dbc_areapoi SET Name_Lang_enGB='Gold Mine', Description_Lang_enGB='Horde Controlled' WHERE ID=1626;
UPDATE dbc_areapoi SET Name_Lang_enGB='Gold Mine', Description_Lang_enGB='In Conflict' WHERE ID=1627;
UPDATE dbc_areapoi SET Name_Lang_enGB='Gold Mine', Description_Lang_enGB='In Conflict' WHERE ID=1628;
UPDATE dbc_areapoi SET Name_Lang_enGB='Lumber Mill', Description_Lang_enGB='Uncontrolled' WHERE ID=1619;
UPDATE dbc_areapoi SET Name_Lang_enGB='Lumber Mill', Description_Lang_enGB='Alliance Controlled' WHERE ID=1620;
UPDATE dbc_areapoi SET Name_Lang_enGB='Lumber Mill', Description_Lang_enGB='Horde Controlled' WHERE ID=1621;
UPDATE dbc_areapoi SET Name_Lang_enGB='Lumber Mill', Description_Lang_enGB='In Conflict' WHERE ID=1622;
UPDATE dbc_areapoi SET Name_Lang_enGB='Lumber Mill', Description_Lang_enGB='In Conflict' WHERE ID=1623;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stables', Description_Lang_enGB='Uncontrolled' WHERE ID=1609;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stables', Description_Lang_enGB='Alliance Controlled' WHERE ID=1610;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stables', Description_Lang_enGB='Horde Controlled' WHERE ID=1611;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stables', Description_Lang_enGB='In Conflict' WHERE ID=1612;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stables', Description_Lang_enGB='In Conflict' WHERE ID=1613;
UPDATE dbc_areapoi SET Name_Lang_enGB='Allerian Stronghold', Description_Lang_enGB='' WHERE ID=2074;
UPDATE dbc_areapoi SET Name_Lang_enGB='Alliance Field Scout', Description_Lang_enGB='' WHERE ID=1904;
UPDATE dbc_areapoi SET Name_Lang_enGB='Alliance Field Scout', Description_Lang_enGB='' WHERE ID=1905;
UPDATE dbc_areapoi SET Name_Lang_enGB='Altar of Sha''tar', Description_Lang_enGB='' WHERE ID=2078;
UPDATE dbc_areapoi SET Name_Lang_enGB='Amani Catacombs', Description_Lang_enGB='' WHERE ID=1809;
UPDATE dbc_areapoi SET Name_Lang_enGB='Amani Pass', Description_Lang_enGB='' WHERE ID=1811;
UPDATE dbc_areapoi SET Name_Lang_enGB='Amberweb Pass', Description_Lang_enGB='' WHERE ID=1837;
UPDATE dbc_areapoi SET Name_Lang_enGB='Ammen Fields', Description_Lang_enGB='' WHERE ID=1799;
UPDATE dbc_areapoi SET Name_Lang_enGB='An''daroth', Description_Lang_enGB='' WHERE ID=1819;
UPDATE dbc_areapoi SET Name_Lang_enGB='An''owyn', Description_Lang_enGB='' WHERE ID=2006;
UPDATE dbc_areapoi SET Name_Lang_enGB='An''telas', Description_Lang_enGB='' WHERE ID=1808;
UPDATE dbc_areapoi SET Name_Lang_enGB='Andilien Estate', Description_Lang_enGB='' WHERE ID=1812;
UPDATE dbc_areapoi SET Name_Lang_enGB='Area 52', Description_Lang_enGB='' WHERE ID=2071;
UPDATE dbc_areapoi SET Name_Lang_enGB='Axxarien', Description_Lang_enGB='' WHERE ID=1834;
UPDATE dbc_areapoi SET Name_Lang_enGB='Azure Watch', Description_Lang_enGB='' WHERE ID=1784;
UPDATE dbc_areapoi SET Name_Lang_enGB='Bladewood', Description_Lang_enGB='' WHERE ID=1830;
UPDATE dbc_areapoi SET Name_Lang_enGB='Bleeding Ziggurat', Description_Lang_enGB='' WHERE ID=1814;
UPDATE dbc_areapoi SET Name_Lang_enGB='Blood Watch', Description_Lang_enGB='' WHERE ID=1940;
UPDATE dbc_areapoi SET Name_Lang_enGB='Bristlebend Enclave', Description_Lang_enGB='' WHERE ID=1840;
UPDATE dbc_areapoi SET Name_Lang_enGB='Bristlelimb Village', Description_Lang_enGB='' WHERE ID=1780;
UPDATE dbc_areapoi SET Name_Lang_enGB='Broken Hill', Description_Lang_enGB='Neutral' WHERE ID=1844;
UPDATE dbc_areapoi SET Name_Lang_enGB='Broken Hill', Description_Lang_enGB='Alliance Controlled' WHERE ID=1845;
UPDATE dbc_areapoi SET Name_Lang_enGB='Broken Hill', Description_Lang_enGB='Horde Controlled' WHERE ID=1846;
UPDATE dbc_areapoi SET Name_Lang_enGB='Cenarion Refuge', Description_Lang_enGB='' WHERE ID=2062;
UPDATE dbc_areapoi SET Name_Lang_enGB='Clan Post', Description_Lang_enGB='' WHERE ID=1722;
UPDATE dbc_areapoi SET Name_Lang_enGB='Coilfang Reservoir', Description_Lang_enGB='' WHERE ID=2021;
UPDATE dbc_areapoi SET Name_Lang_enGB='Cosmowrench', Description_Lang_enGB='' WHERE ID=2072;
UPDATE dbc_areapoi SET Name_Lang_enGB='Crash Site', Description_Lang_enGB='' WHERE ID=1795;
UPDATE dbc_areapoi SET Name_Lang_enGB='Dawnstar Spire', Description_Lang_enGB='' WHERE ID=1804;
UPDATE dbc_areapoi SET Name_Lang_enGB='Deatholme', Description_Lang_enGB='' WHERE ID=1711;
UPDATE dbc_areapoi SET Name_Lang_enGB='Den of Haal''esh', Description_Lang_enGB='' WHERE ID=1719;
UPDATE dbc_areapoi SET Name_Lang_enGB='Duskwither Spire', Description_Lang_enGB='' WHERE ID=2018;
UPDATE dbc_areapoi SET Name_Lang_enGB='East Beacon', Description_Lang_enGB='Alliance Controlled' WHERE ID=1901;
UPDATE dbc_areapoi SET Name_Lang_enGB='East Beacon', Description_Lang_enGB='Horde Controlled' WHERE ID=1902;
UPDATE dbc_areapoi SET Name_Lang_enGB='East Beacon', Description_Lang_enGB='' WHERE ID=1903;
UPDATE dbc_areapoi SET Name_Lang_enGB='East Sanctum', Description_Lang_enGB='' WHERE ID=1822;
UPDATE dbc_areapoi SET Name_Lang_enGB='Emberglade', Description_Lang_enGB='' WHERE ID=1792;
UPDATE dbc_areapoi SET Name_Lang_enGB='Evergrove', Description_Lang_enGB='' WHERE ID=2068;
UPDATE dbc_areapoi SET Name_Lang_enGB='Fairbreeze Village', Description_Lang_enGB='' WHERE ID=1709;
UPDATE dbc_areapoi SET Name_Lang_enGB='Falcon Watch', Description_Lang_enGB='' WHERE ID=1720;
UPDATE dbc_areapoi SET Name_Lang_enGB='Falconwing Square', Description_Lang_enGB='' WHERE ID=1705;
UPDATE dbc_areapoi SET Name_Lang_enGB='Falconwing Square, Paladin Trainer', Description_Lang_enGB='' WHERE ID=1999;
UPDATE dbc_areapoi SET Name_Lang_enGB='Farstride Retreat', Description_Lang_enGB='' WHERE ID=1710;
UPDATE dbc_areapoi SET Name_Lang_enGB='Farstrider Enclave', Description_Lang_enGB='' WHERE ID=1805;
UPDATE dbc_areapoi SET Name_Lang_enGB='Garadar', Description_Lang_enGB='' WHERE ID=2064;
UPDATE dbc_areapoi SET Name_Lang_enGB='Geezle''s Camp', Description_Lang_enGB='' WHERE ID=1783;
UPDATE dbc_areapoi SET Name_Lang_enGB='Golden Mist Village', Description_Lang_enGB='' WHERE ID=1818;
UPDATE dbc_areapoi SET Name_Lang_enGB='Golden Strand', Description_Lang_enGB='' WHERE ID=2015;
UPDATE dbc_areapoi SET Name_Lang_enGB='Golden Strand', Description_Lang_enGB='' WHERE ID=2019;
UPDATE dbc_areapoi SET Name_Lang_enGB='Halaa', Description_Lang_enGB='' WHERE ID=1920;
UPDATE dbc_areapoi SET Name_Lang_enGB='Halaa', Description_Lang_enGB='Horde Controlled' WHERE ID=1921;
UPDATE dbc_areapoi SET Name_Lang_enGB='Halaa', Description_Lang_enGB='Alliance Controlled' WHERE ID=1922;
UPDATE dbc_areapoi SET Name_Lang_enGB='Halaa', Description_Lang_enGB='' WHERE ID=1923;
UPDATE dbc_areapoi SET Name_Lang_enGB='Halaa', Description_Lang_enGB='' WHERE ID=1924;
UPDATE dbc_areapoi SET Name_Lang_enGB='Hellfire Citadel', Description_Lang_enGB='' WHERE ID=1718;
UPDATE dbc_areapoi SET Name_Lang_enGB='Honor Hold', Description_Lang_enGB='' WHERE ID=1714;
UPDATE dbc_areapoi SET Name_Lang_enGB='Horde Field Scout', Description_Lang_enGB='' WHERE ID=1906;
UPDATE dbc_areapoi SET Name_Lang_enGB='Horde Field Scout', Description_Lang_enGB='' WHERE ID=1907;
UPDATE dbc_areapoi SET Name_Lang_enGB='Howling Ziggurat', Description_Lang_enGB='' WHERE ID=1813;
UPDATE dbc_areapoi SET Name_Lang_enGB='Menagerie Wreckage', Description_Lang_enGB='' WHERE ID=1789;
UPDATE dbc_areapoi SET Name_Lang_enGB='Moonwing Den', Description_Lang_enGB='' WHERE ID=1800;
UPDATE dbc_areapoi SET Name_Lang_enGB='Nazzivian', Description_Lang_enGB='' WHERE ID=1833;
UPDATE dbc_areapoi SET Name_Lang_enGB='Nestlewood Thicket', Description_Lang_enGB='' WHERE ID=1798;
UPDATE dbc_areapoi SET Name_Lang_enGB='North Sanctum', Description_Lang_enGB='' WHERE ID=1825;
UPDATE dbc_areapoi SET Name_Lang_enGB='Odesyus'' Landing', Description_Lang_enGB='' WHERE ID=1793;
UPDATE dbc_areapoi SET Name_Lang_enGB='Ogri''la', Description_Lang_enGB='' WHERE ID=2080;
UPDATE dbc_areapoi SET Name_Lang_enGB='Orebor Harborage', Description_Lang_enGB='' WHERE ID=2060;
UPDATE dbc_areapoi SET Name_Lang_enGB='Pod Cluster', Description_Lang_enGB='' WHERE ID=1781;
UPDATE dbc_areapoi SET Name_Lang_enGB='Pod Wreckage', Description_Lang_enGB='' WHERE ID=1782;
UPDATE dbc_areapoi SET Name_Lang_enGB='Pools of Aggonar', Description_Lang_enGB='' WHERE ID=1723;
UPDATE dbc_areapoi SET Name_Lang_enGB='Ragefeather Ridge', Description_Lang_enGB='' WHERE ID=1838;
UPDATE dbc_areapoi SET Name_Lang_enGB='Ruins of Loreth''Aran', Description_Lang_enGB='' WHERE ID=1832;
UPDATE dbc_areapoi SET Name_Lang_enGB='Ruins of Sha''naar', Description_Lang_enGB='' WHERE ID=1721;
UPDATE dbc_areapoi SET Name_Lang_enGB='Saltheril''s Haven', Description_Lang_enGB='' WHERE ID=1823;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sanctum of the Moon', Description_Lang_enGB='' WHERE ID=1817;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sanctum of the Stars', Description_Lang_enGB='' WHERE ID=2077;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sanctum of the Sun', Description_Lang_enGB='' WHERE ID=1807;
UPDATE dbc_areapoi SET Name_Lang_enGB='Serpent Lake', Description_Lang_enGB='' WHERE ID=2022;
UPDATE dbc_areapoi SET Name_Lang_enGB='Serpent Lake', Description_Lang_enGB='' WHERE ID=2023;
UPDATE dbc_areapoi SET Name_Lang_enGB='Shadow Ridge', Description_Lang_enGB='' WHERE ID=1796;
UPDATE dbc_areapoi SET Name_Lang_enGB='Shadowmoon Village', Description_Lang_enGB='' WHERE ID=2075;
UPDATE dbc_areapoi SET Name_Lang_enGB='Shalandris Isle', Description_Lang_enGB='' WHERE ID=2005;
UPDATE dbc_areapoi SET Name_Lang_enGB='Shattrath City', Description_Lang_enGB='' WHERE ID=1961;
UPDATE dbc_areapoi SET Name_Lang_enGB='Silting Shore', Description_Lang_enGB='' WHERE ID=1787;
UPDATE dbc_areapoi SET Name_Lang_enGB='Silverline Lake', Description_Lang_enGB='' WHERE ID=1797;
UPDATE dbc_areapoi SET Name_Lang_enGB='Silvermoon City', Description_Lang_enGB='' WHERE ID=1704;
UPDATE dbc_areapoi SET Name_Lang_enGB='Spirit Tower', Description_Lang_enGB='' WHERE ID=1925;
UPDATE dbc_areapoi SET Name_Lang_enGB='Spirit Tower', Description_Lang_enGB='Alliance Controlled' WHERE ID=1926;
UPDATE dbc_areapoi SET Name_Lang_enGB='Spirit Tower', Description_Lang_enGB='Horde Controlled' WHERE ID=1927;
UPDATE dbc_areapoi SET Name_Lang_enGB='Spirit Tower', Description_Lang_enGB='' WHERE ID=1928;
UPDATE dbc_areapoi SET Name_Lang_enGB='Spirit Tower', Description_Lang_enGB='Alliance Controlled' WHERE ID=1929;
UPDATE dbc_areapoi SET Name_Lang_enGB='Spirit Tower', Description_Lang_enGB='Horde Controlled' WHERE ID=1930;
UPDATE dbc_areapoi SET Name_Lang_enGB='Spirit Tower', Description_Lang_enGB='' WHERE ID=1931;
UPDATE dbc_areapoi SET Name_Lang_enGB='Spirit Tower', Description_Lang_enGB='Alliance Controlled' WHERE ID=1932;
UPDATE dbc_areapoi SET Name_Lang_enGB='Spirit Tower', Description_Lang_enGB='Horde Controlled' WHERE ID=1933;
UPDATE dbc_areapoi SET Name_Lang_enGB='Spirit Tower', Description_Lang_enGB='' WHERE ID=1934;
UPDATE dbc_areapoi SET Name_Lang_enGB='Spirit Tower', Description_Lang_enGB='Alliance Controlled' WHERE ID=1935;
UPDATE dbc_areapoi SET Name_Lang_enGB='Spirit Tower', Description_Lang_enGB='Horde Controlled' WHERE ID=1936;
UPDATE dbc_areapoi SET Name_Lang_enGB='Spirit Tower', Description_Lang_enGB='' WHERE ID=1937;
UPDATE dbc_areapoi SET Name_Lang_enGB='Spirit Tower', Description_Lang_enGB='Alliance Controlled' WHERE ID=1938;
UPDATE dbc_areapoi SET Name_Lang_enGB='Spirit Tower', Description_Lang_enGB='Horde Controlled' WHERE ID=1939;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sporeggar', Description_Lang_enGB='' WHERE ID=2059;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stillpine Hold', Description_Lang_enGB='' WHERE ID=1788;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stillwhisper Pond', Description_Lang_enGB='' WHERE ID=1826;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stonebreaker Hold', Description_Lang_enGB='' WHERE ID=2073;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sun''s Reach Armory', Description_Lang_enGB='Held by the enemy' WHERE ID=2098;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sun''s Reach Armory', Description_Lang_enGB='Shattered Sun Offensive' WHERE ID=2099;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sun''s Reach Harbor', Description_Lang_enGB='Held by the enemy' WHERE ID=2100;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sun''s Reach Harbor', Description_Lang_enGB='Shattered Sun Offensive' WHERE ID=2101;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sun''s Reach Sanctum', Description_Lang_enGB='Held by the enemy' WHERE ID=2096;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sun''s Reach Sanctum', Description_Lang_enGB='Shattered Sun Offensive' WHERE ID=2097;
UPDATE dbc_areapoi SET Name_Lang_enGB='Suncrown Village', Description_Lang_enGB='' WHERE ID=1802;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sunsail Anchorage', Description_Lang_enGB='' WHERE ID=1708;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sunstrider Isle', Description_Lang_enGB='' WHERE ID=1706;
UPDATE dbc_areapoi SET Name_Lang_enGB='Swamprat Post', Description_Lang_enGB='' WHERE ID=2063;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sylvanaar', Description_Lang_enGB='' WHERE ID=2066;
UPDATE dbc_areapoi SET Name_Lang_enGB='Talon Stand', Description_Lang_enGB='' WHERE ID=1839;
UPDATE dbc_areapoi SET Name_Lang_enGB='Telaar', Description_Lang_enGB='' WHERE ID=2065;
UPDATE dbc_areapoi SET Name_Lang_enGB='Telredor', Description_Lang_enGB='' WHERE ID=2061;
UPDATE dbc_areapoi SET Name_Lang_enGB='Temple of Telhamat', Description_Lang_enGB='' WHERE ID=2069;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Cryo-Core', Description_Lang_enGB='' WHERE ID=1828;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Dead Scar', Description_Lang_enGB='' WHERE ID=2016;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Dead Scar', Description_Lang_enGB='' WHERE ID=2020;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Exodar', Description_Lang_enGB='' WHERE ID=1785;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Foul Pond', Description_Lang_enGB='' WHERE ID=1835;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Hidden Reef', Description_Lang_enGB='' WHERE ID=1836;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Overlook', Description_Lang_enGB='Neutral' WHERE ID=1841;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Overlook', Description_Lang_enGB='Alliance Controlled' WHERE ID=1842;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Overlook', Description_Lang_enGB='Horde Controlled' WHERE ID=1843;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Sacred Grove', Description_Lang_enGB='' WHERE ID=1790;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Stadium', Description_Lang_enGB='Neutral' WHERE ID=1847;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Stadium', Description_Lang_enGB='Alliance Controlled' WHERE ID=1848;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Stadium', Description_Lang_enGB='Horde Controlled' WHERE ID=1849;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Stair of Destiny', Description_Lang_enGB='' WHERE ID=1716;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Stormspire', Description_Lang_enGB='' WHERE ID=2070;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Sunspire', Description_Lang_enGB='' WHERE ID=1707;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Vector Coil', Description_Lang_enGB='' WHERE ID=1827;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Warp Piston', Description_Lang_enGB='' WHERE ID=1829;
UPDATE dbc_areapoi SET Name_Lang_enGB='Thrallmar', Description_Lang_enGB='' WHERE ID=1715;
UPDATE dbc_areapoi SET Name_Lang_enGB='Throne of Kil''Jaeden', Description_Lang_enGB='' WHERE ID=1717;
UPDATE dbc_areapoi SET Name_Lang_enGB='Thunderlord Stronghold', Description_Lang_enGB='' WHERE ID=2067;
UPDATE dbc_areapoi SET Name_Lang_enGB='Thuron''s Livery', Description_Lang_enGB='' WHERE ID=2017;
UPDATE dbc_areapoi SET Name_Lang_enGB='Tide''s Hollow', Description_Lang_enGB='' WHERE ID=1801;
UPDATE dbc_areapoi SET Name_Lang_enGB='Tor''Watha', Description_Lang_enGB='' WHERE ID=1820;
UPDATE dbc_areapoi SET Name_Lang_enGB='Toshley''s Station', Description_Lang_enGB='' WHERE ID=2034;
UPDATE dbc_areapoi SET Name_Lang_enGB='Traitor''s Cove', Description_Lang_enGB='' WHERE ID=1794;
UPDATE dbc_areapoi SET Name_Lang_enGB='Tranquillien', Description_Lang_enGB='' WHERE ID=1713;
UPDATE dbc_areapoi SET Name_Lang_enGB='Twinspire Graveyard', Description_Lang_enGB='' WHERE ID=1897;
UPDATE dbc_areapoi SET Name_Lang_enGB='Twinspire Graveyard', Description_Lang_enGB='Alliance Controlled' WHERE ID=1898;
UPDATE dbc_areapoi SET Name_Lang_enGB='Twinspire Graveyard', Description_Lang_enGB='Horde Controlled' WHERE ID=1899;
UPDATE dbc_areapoi SET Name_Lang_enGB='Umbrafen Lake', Description_Lang_enGB='' WHERE ID=2024;
UPDATE dbc_areapoi SET Name_Lang_enGB='Umbrafen Lake', Description_Lang_enGB='' WHERE ID=2025;
UPDATE dbc_areapoi SET Name_Lang_enGB='Underlight Mines', Description_Lang_enGB='' WHERE ID=1815;
UPDATE dbc_areapoi SET Name_Lang_enGB='Valaar''s Berth', Description_Lang_enGB='' WHERE ID=1786;
UPDATE dbc_areapoi SET Name_Lang_enGB='West Beacon', Description_Lang_enGB='Alliance Controlled' WHERE ID=1894;
UPDATE dbc_areapoi SET Name_Lang_enGB='West Beacon', Description_Lang_enGB='Horde Controlled' WHERE ID=1895;
UPDATE dbc_areapoi SET Name_Lang_enGB='West Beacon', Description_Lang_enGB='' WHERE ID=1896;
UPDATE dbc_areapoi SET Name_Lang_enGB='West Sanctum', Description_Lang_enGB='' WHERE ID=1824;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wildhammer Stronghold', Description_Lang_enGB='' WHERE ID=2076;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wildwind Peak', Description_Lang_enGB='' WHERE ID=1791;
UPDATE dbc_areapoi SET Name_Lang_enGB='Windrunner Spire', Description_Lang_enGB='' WHERE ID=1712;
UPDATE dbc_areapoi SET Name_Lang_enGB='Windrunner Village', Description_Lang_enGB='' WHERE ID=1816;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wrathscale Lair', Description_Lang_enGB='' WHERE ID=1831;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wrathscale Point', Description_Lang_enGB='' WHERE ID=1779;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyvern Camp', Description_Lang_enGB='Uncontrolled' WHERE ID=1908;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyvern Camp', Description_Lang_enGB='Horde Controlled' WHERE ID=1909;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyvern Camp', Description_Lang_enGB='Alliance Controlled' WHERE ID=1910;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyvern Camp', Description_Lang_enGB='Uncontrolled' WHERE ID=1911;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyvern Camp', Description_Lang_enGB='Alliance Controlled' WHERE ID=1912;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyvern Camp', Description_Lang_enGB='Horde Controlled' WHERE ID=1913;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyvern Camp', Description_Lang_enGB='Uncontrolled' WHERE ID=1914;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyvern Camp', Description_Lang_enGB='Horde Controlled' WHERE ID=1915;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyvern Camp', Description_Lang_enGB='Alliance Controlled' WHERE ID=1916;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyvern Camp', Description_Lang_enGB='Uncontrolled' WHERE ID=1917;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyvern Camp', Description_Lang_enGB='Alliance Controlled' WHERE ID=1918;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyvern Camp', Description_Lang_enGB='Horde Controlled' WHERE ID=1919;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyvern Camp', Description_Lang_enGB='Uncontrolled' WHERE ID=1963;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyvern Camp', Description_Lang_enGB='Uncontrolled' WHERE ID=1964;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyvern Camp', Description_Lang_enGB='Uncontrolled' WHERE ID=1965;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyvern Camp', Description_Lang_enGB='Uncontrolled' WHERE ID=1966;
UPDATE dbc_areapoi SET Name_Lang_enGB='Zabra''jin', Description_Lang_enGB='' WHERE ID=2058;
UPDATE dbc_areapoi SET Name_Lang_enGB='Zeb''Nowa', Description_Lang_enGB='' WHERE ID=1810;
UPDATE dbc_areapoi SET Name_Lang_enGB='Zeb''Sora', Description_Lang_enGB='' WHERE ID=1803;
UPDATE dbc_areapoi SET Name_Lang_enGB='Zeb''Tela', Description_Lang_enGB='' WHERE ID=1806;
UPDATE dbc_areapoi SET Name_Lang_enGB='Zeb''Watha', Description_Lang_enGB='' WHERE ID=1821;
UPDATE dbc_areapoi SET Name_Lang_enGB='Blood Elf Tower', Description_Lang_enGB='Uncontrolled' WHERE ID=1941;
UPDATE dbc_areapoi SET Name_Lang_enGB='Blood Elf Tower', Description_Lang_enGB='Alliance Controlled' WHERE ID=1942;
UPDATE dbc_areapoi SET Name_Lang_enGB='Blood Elf Tower', Description_Lang_enGB='Horde Controlled' WHERE ID=1943;
UPDATE dbc_areapoi SET Name_Lang_enGB='Blood Elf Tower', Description_Lang_enGB='In Conflict' WHERE ID=1959;
UPDATE dbc_areapoi SET Name_Lang_enGB='Blood Elf Tower', Description_Lang_enGB='In Conflict' WHERE ID=1960;
UPDATE dbc_areapoi SET Name_Lang_enGB='Draenei Ruins', Description_Lang_enGB='Uncontrolled' WHERE ID=1950;
UPDATE dbc_areapoi SET Name_Lang_enGB='Draenei Ruins', Description_Lang_enGB='Alliance Controlled' WHERE ID=1951;
UPDATE dbc_areapoi SET Name_Lang_enGB='Draenei Ruins', Description_Lang_enGB='Horde Controlled' WHERE ID=1952;
UPDATE dbc_areapoi SET Name_Lang_enGB='Draenei Ruins', Description_Lang_enGB='In Conflict' WHERE ID=1953;
UPDATE dbc_areapoi SET Name_Lang_enGB='Draenei Ruins', Description_Lang_enGB='In Conflict' WHERE ID=1954;
UPDATE dbc_areapoi SET Name_Lang_enGB='Fel Reaver Ruins', Description_Lang_enGB='Uncontrolled' WHERE ID=1944;
UPDATE dbc_areapoi SET Name_Lang_enGB='Fel Reaver Ruins', Description_Lang_enGB='Alliance Controlled' WHERE ID=1945;
UPDATE dbc_areapoi SET Name_Lang_enGB='Fel Reaver Ruins', Description_Lang_enGB='Horde Controlled' WHERE ID=1946;
UPDATE dbc_areapoi SET Name_Lang_enGB='Fel Reaver Ruins', Description_Lang_enGB='In Conflict' WHERE ID=1957;
UPDATE dbc_areapoi SET Name_Lang_enGB='Fel Reaver Ruins', Description_Lang_enGB='In Conflict' WHERE ID=1958;
UPDATE dbc_areapoi SET Name_Lang_enGB='Mage Tower', Description_Lang_enGB='Uncontrolled' WHERE ID=1947;
UPDATE dbc_areapoi SET Name_Lang_enGB='Mage Tower', Description_Lang_enGB='Alliance Controlled' WHERE ID=1948;
UPDATE dbc_areapoi SET Name_Lang_enGB='Mage Tower', Description_Lang_enGB='Horde Controlled' WHERE ID=1949;
UPDATE dbc_areapoi SET Name_Lang_enGB='Mage Tower', Description_Lang_enGB='In Conflict' WHERE ID=1955;
UPDATE dbc_areapoi SET Name_Lang_enGB='Mage Tower', Description_Lang_enGB='In Conflict' WHERE ID=1956;
UPDATE dbc_areapoi SET Name_Lang_enGB='Netherstorm Flag', Description_Lang_enGB='Not Controlled' WHERE ID=1962;
UPDATE dbc_areapoi SET Name_Lang_enGB='Agmar''s Hammer', Description_Lang_enGB='' WHERE ID=2301;
UPDATE dbc_areapoi SET Name_Lang_enGB='Amberpine Lodge', Description_Lang_enGB='' WHERE ID=2311;
UPDATE dbc_areapoi SET Name_Lang_enGB='Bor''gorok Outpost', Description_Lang_enGB='' WHERE ID=2308;
UPDATE dbc_areapoi SET Name_Lang_enGB='Broken Temple Graveyard', Description_Lang_enGB='' WHERE ID=2266;
UPDATE dbc_areapoi SET Name_Lang_enGB='Broken Temple Vehicle Workshop', Description_Lang_enGB='' WHERE ID=2153;
UPDATE dbc_areapoi SET Name_Lang_enGB='Brunnhildar Village', Description_Lang_enGB='' WHERE ID=2319;
UPDATE dbc_areapoi SET Name_Lang_enGB='Camp Oneqwah', Description_Lang_enGB='' WHERE ID=2312;
UPDATE dbc_areapoi SET Name_Lang_enGB='Camp Tunka''lo', Description_Lang_enGB='' WHERE ID=2318;
UPDATE dbc_areapoi SET Name_Lang_enGB='Camp Winterhoof', Description_Lang_enGB='' WHERE ID=2090;
UPDATE dbc_areapoi SET Name_Lang_enGB='Conquest Hold', Description_Lang_enGB='' WHERE ID=2310;
UPDATE dbc_areapoi SET Name_Lang_enGB='Crusaders'' Pinnacle', Description_Lang_enGB='' WHERE ID=2323;
UPDATE dbc_areapoi SET Name_Lang_enGB='Dalaran', Description_Lang_enGB='' WHERE ID=2317;
UPDATE dbc_areapoi SET Name_Lang_enGB='Death''s Rise', Description_Lang_enGB='' WHERE ID=2138;
UPDATE dbc_areapoi SET Name_Lang_enGB='Eastspark Vehicle Workshop', Description_Lang_enGB='' WHERE ID=2151;
UPDATE dbc_areapoi SET Name_Lang_enGB='Fizzcrank Airstrip', Description_Lang_enGB='' WHERE ID=2307;
UPDATE dbc_areapoi SET Name_Lang_enGB='Flamewatch Tower', Description_Lang_enGB='' WHERE ID=2143;
UPDATE dbc_areapoi SET Name_Lang_enGB='Fort Wildervar', Description_Lang_enGB='' WHERE ID=2089;
UPDATE dbc_areapoi SET Name_Lang_enGB='Fortress Graveyard', Description_Lang_enGB='' WHERE ID=2268;
UPDATE dbc_areapoi SET Name_Lang_enGB='Fortress Vehicle Workshop (E)', Description_Lang_enGB='' WHERE ID=2149;
UPDATE dbc_areapoi SET Name_Lang_enGB='Fortress Vehicle Workshop (W)', Description_Lang_enGB='' WHERE ID=2150;
UPDATE dbc_areapoi SET Name_Lang_enGB='Frosthold', Description_Lang_enGB='' WHERE ID=2321;
UPDATE dbc_areapoi SET Name_Lang_enGB='Grom''arsh Crash-Site', Description_Lang_enGB='' WHERE ID=2322;
UPDATE dbc_areapoi SET Name_Lang_enGB='K3', Description_Lang_enGB='' WHERE ID=2320;
UPDATE dbc_areapoi SET Name_Lang_enGB='Kamagua', Description_Lang_enGB='' WHERE ID=2085;
UPDATE dbc_areapoi SET Name_Lang_enGB='Moa''ki Harbor', Description_Lang_enGB='' WHERE ID=2302;
UPDATE dbc_areapoi SET Name_Lang_enGB='Nesingwary Base Camp', Description_Lang_enGB='' WHERE ID=2316;
UPDATE dbc_areapoi SET Name_Lang_enGB='New Agamand', Description_Lang_enGB='' WHERE ID=2088;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2199;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2200;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2201;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2203;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2205;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2206;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2207;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2208;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2209;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2210;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2211;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2212;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2213;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2214;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2215;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2216;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2217;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2218;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2219;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2220;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2221;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2247;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2248;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2249;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2250;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2251;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2252;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2253;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2254;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2255;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2256;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2257;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2258;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2259;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2260;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2261;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2262;
UPDATE dbc_areapoi SET Name_Lang_enGB='PvP Activity Detected', Description_Lang_enGB='' WHERE ID=2263;
UPDATE dbc_areapoi SET Name_Lang_enGB='Shadowsight Tower', Description_Lang_enGB='' WHERE ID=2141;
UPDATE dbc_areapoi SET Name_Lang_enGB='Southeast Graveyard', Description_Lang_enGB='' WHERE ID=2270;
UPDATE dbc_areapoi SET Name_Lang_enGB='Southwest Graveyard', Description_Lang_enGB='' WHERE ID=2269;
UPDATE dbc_areapoi SET Name_Lang_enGB='Stars'' Rest', Description_Lang_enGB='' WHERE ID=2300;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sunken Ring Graveyard', Description_Lang_enGB='' WHERE ID=2265;
UPDATE dbc_areapoi SET Name_Lang_enGB='Sunken Ring Vehicle Workshop', Description_Lang_enGB='' WHERE ID=2154;
UPDATE dbc_areapoi SET Name_Lang_enGB='Taunka''le Village', Description_Lang_enGB='' WHERE ID=2306;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Argent Stand', Description_Lang_enGB='' WHERE ID=2314;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Shadow Vault', Description_Lang_enGB='' WHERE ID=2139;
UPDATE dbc_areapoi SET Name_Lang_enGB='Unu''pe', Description_Lang_enGB='' WHERE ID=2305;
UPDATE dbc_areapoi SET Name_Lang_enGB='Valgarde', Description_Lang_enGB='' WHERE ID=2086;
UPDATE dbc_areapoi SET Name_Lang_enGB='Valiance Keep', Description_Lang_enGB='' WHERE ID=2303;
UPDATE dbc_areapoi SET Name_Lang_enGB='Vengeance Landing', Description_Lang_enGB='' WHERE ID=2087;
UPDATE dbc_areapoi SET Name_Lang_enGB='Venomspite', Description_Lang_enGB='' WHERE ID=2299;
UPDATE dbc_areapoi SET Name_Lang_enGB='Warsong Hold', Description_Lang_enGB='' WHERE ID=2304;
UPDATE dbc_areapoi SET Name_Lang_enGB='Westfall Brigade Encampment', Description_Lang_enGB='' WHERE ID=2313;
UPDATE dbc_areapoi SET Name_Lang_enGB='Westguard Keep', Description_Lang_enGB='' WHERE ID=2084;
UPDATE dbc_areapoi SET Name_Lang_enGB='Westspark Vehicle Workshop', Description_Lang_enGB='' WHERE ID=2152;
UPDATE dbc_areapoi SET Name_Lang_enGB='Winter''s Edge Tower', Description_Lang_enGB='' WHERE ID=2142;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergarde Keep', Description_Lang_enGB='' WHERE ID=2309;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp', Description_Lang_enGB='Control of Wintergrasp' WHERE ID=2264;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress', Description_Lang_enGB='' WHERE ID=2246;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Gate', Description_Lang_enGB='' WHERE ID=2229;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Tower (NE)', Description_Lang_enGB='' WHERE ID=2146;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Tower (NW)', Description_Lang_enGB='' WHERE ID=2147;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Tower (SE)', Description_Lang_enGB='' WHERE ID=2145;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Tower (SW)', Description_Lang_enGB='' WHERE ID=2144;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2222;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2223;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2224;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2225;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2226;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2227;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2228;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2230;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2231;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2232;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2233;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2234;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2235;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2236;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2237;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2238;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2239;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2240;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2241;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2242;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2243;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2244;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wintergrasp Fortress Wall', Description_Lang_enGB='' WHERE ID=2245;
UPDATE dbc_areapoi SET Name_Lang_enGB='Wyrmrest Temple', Description_Lang_enGB='' WHERE ID=2298;
UPDATE dbc_areapoi SET Name_Lang_enGB='Zim''Torga', Description_Lang_enGB='' WHERE ID=2315;
UPDATE dbc_areapoi SET Name_Lang_enGB='Elder''s Square Gate', Description_Lang_enGB='Elder''s Square Gate' WHERE ID=2106;
UPDATE dbc_areapoi SET Name_Lang_enGB='Festival Lane Gate', Description_Lang_enGB='Festival Lane Gate' WHERE ID=2107;
UPDATE dbc_areapoi SET Name_Lang_enGB='King''s Square Fountain', Description_Lang_enGB='King''s Square Fountain' WHERE ID=2109;
UPDATE dbc_areapoi SET Name_Lang_enGB='Market Row Gate', Description_Lang_enGB='Market Row Gate' WHERE ID=2108;
UPDATE dbc_areapoi SET Name_Lang_enGB='Town Hall', Description_Lang_enGB='Town Hall' WHERE ID=2105;
UPDATE dbc_areapoi SET Name_Lang_enGB='Tower of Flames', Description_Lang_enGB='Provides power to Mimiron''s Inferno' WHERE ID=2332;
UPDATE dbc_areapoi SET Name_Lang_enGB='Tower of Frost', Description_Lang_enGB='Provides power to Hodir''s Fury' WHERE ID=2333;
UPDATE dbc_areapoi SET Name_Lang_enGB='Tower of Life', Description_Lang_enGB='Supplies power to Freya''s Ward' WHERE ID=2331;
UPDATE dbc_areapoi SET Name_Lang_enGB='Tower of Storms', Description_Lang_enGB='Provides power to Thorim''s Hammer' WHERE ID=2334;
UPDATE dbc_areapoi SET Name_Lang_enGB='Alliance Defense', Description_Lang_enGB='' WHERE ID=2128;
UPDATE dbc_areapoi SET Name_Lang_enGB='Chamber of Ancient Relics', Description_Lang_enGB='' WHERE ID=2292;
UPDATE dbc_areapoi SET Name_Lang_enGB='East Graveyard', Description_Lang_enGB='Horde Controlled' WHERE ID=2129;
UPDATE dbc_areapoi SET Name_Lang_enGB='East Graveyard', Description_Lang_enGB='Alliance Controlled' WHERE ID=2130;
UPDATE dbc_areapoi SET Name_Lang_enGB='Gate of the Blue Sapphire', Description_Lang_enGB='' WHERE ID=2117;
UPDATE dbc_areapoi SET Name_Lang_enGB='Gate of the Green Emerald', Description_Lang_enGB='' WHERE ID=2120;
UPDATE dbc_areapoi SET Name_Lang_enGB='Gate of the Purple Amethyst', Description_Lang_enGB='' WHERE ID=2111;
UPDATE dbc_areapoi SET Name_Lang_enGB='Gate of the Red Sun', Description_Lang_enGB='' WHERE ID=2114;
UPDATE dbc_areapoi SET Name_Lang_enGB='Gate of the Yellow Moon', Description_Lang_enGB='' WHERE ID=2135;
UPDATE dbc_areapoi SET Name_Lang_enGB='Horde Defense', Description_Lang_enGB='' WHERE ID=2127;
UPDATE dbc_areapoi SET Name_Lang_enGB='South Graveyard', Description_Lang_enGB='Horde Controlled' WHERE ID=2133;
UPDATE dbc_areapoi SET Name_Lang_enGB='South Graveyard', Description_Lang_enGB='Alliance Controlled' WHERE ID=2134;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Blightbringer', Description_Lang_enGB='Horde Offense' WHERE ID=2125;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Casket Carrier', Description_Lang_enGB='Horde Offense' WHERE ID=2126;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Frostbreaker', Description_Lang_enGB='Alliance Offense' WHERE ID=2123;
UPDATE dbc_areapoi SET Name_Lang_enGB='The Graceful Maiden', Description_Lang_enGB='Alliance Offense' WHERE ID=2124;
UPDATE dbc_areapoi SET Name_Lang_enGB='West Graveyard', Description_Lang_enGB='Alliance Controlled' WHERE ID=2132;
UPDATE dbc_areapoi SET Name_Lang_enGB='West Graveyard', Description_Lang_enGB='Horde Controlled' WHERE ID=2324;
UPDATE dbc_areapoi SET Name_Lang_enGB='Alliance Gate', Description_Lang_enGB='East Gate' WHERE ID=2377;
UPDATE dbc_areapoi SET Name_Lang_enGB='Alliance Gate', Description_Lang_enGB='Destroyed' WHERE ID=2378;
UPDATE dbc_areapoi SET Name_Lang_enGB='Alliance Gate', Description_Lang_enGB='Destroyed' WHERE ID=2379;
UPDATE dbc_areapoi SET Name_Lang_enGB='Alliance Gate', Description_Lang_enGB='West Gate' WHERE ID=2380;
UPDATE dbc_areapoi SET Name_Lang_enGB='Alliance Gate', Description_Lang_enGB='Destroyed' WHERE ID=2381;
UPDATE dbc_areapoi SET Name_Lang_enGB='Alliance Gate', Description_Lang_enGB='Front Gate' WHERE ID=2382;
UPDATE dbc_areapoi SET Name_Lang_enGB='Alliance Keep', Description_Lang_enGB='Uncontrolled' WHERE ID=2383;
UPDATE dbc_areapoi SET Name_Lang_enGB='Alliance Keep', Description_Lang_enGB='Alliance Controlled' WHERE ID=2384;
UPDATE dbc_areapoi SET Name_Lang_enGB='Alliance Keep', Description_Lang_enGB='In Conflict' WHERE ID=2385;
UPDATE dbc_areapoi SET Name_Lang_enGB='Alliance Keep', Description_Lang_enGB='In Conflict' WHERE ID=2386;
UPDATE dbc_areapoi SET Name_Lang_enGB='Alliance Keep', Description_Lang_enGB='Horde Controlled' WHERE ID=2387;
UPDATE dbc_areapoi SET Name_Lang_enGB='Docks', Description_Lang_enGB='In Conflict' WHERE ID=2356;
UPDATE dbc_areapoi SET Name_Lang_enGB='Docks', Description_Lang_enGB='Horde Controlled' WHERE ID=2357;
UPDATE dbc_areapoi SET Name_Lang_enGB='Docks', Description_Lang_enGB='Alliance Controlled' WHERE ID=2358;
UPDATE dbc_areapoi SET Name_Lang_enGB='Docks', Description_Lang_enGB='In Conflict' WHERE ID=2359;
UPDATE dbc_areapoi SET Name_Lang_enGB='Docks', Description_Lang_enGB='Uncontrolled' WHERE ID=2360;
UPDATE dbc_areapoi SET Name_Lang_enGB='Hangar', Description_Lang_enGB='Alliance Controlled' WHERE ID=2350;
UPDATE dbc_areapoi SET Name_Lang_enGB='Hangar', Description_Lang_enGB='Horde Controlled' WHERE ID=2352;
UPDATE dbc_areapoi SET Name_Lang_enGB='Hangar', Description_Lang_enGB='In Conflict' WHERE ID=2353;
UPDATE dbc_areapoi SET Name_Lang_enGB='Hangar', Description_Lang_enGB='In Conflict' WHERE ID=2354;
UPDATE dbc_areapoi SET Name_Lang_enGB='Hangar', Description_Lang_enGB='Uncontrolled' WHERE ID=2355;
UPDATE dbc_areapoi SET Name_Lang_enGB='Horde Gate', Description_Lang_enGB='Front Gate' WHERE ID=2371;
UPDATE dbc_areapoi SET Name_Lang_enGB='Horde Gate', Description_Lang_enGB='Destroyed' WHERE ID=2372;
UPDATE dbc_areapoi SET Name_Lang_enGB='Horde Gate', Description_Lang_enGB='East Gate' WHERE ID=2373;
UPDATE dbc_areapoi SET Name_Lang_enGB='Horde Gate', Description_Lang_enGB='Destroyed' WHERE ID=2374;
UPDATE dbc_areapoi SET Name_Lang_enGB='Horde Gate', Description_Lang_enGB='West Gate' WHERE ID=2375;
UPDATE dbc_areapoi SET Name_Lang_enGB='Horde Gate', Description_Lang_enGB='Destroyed' WHERE ID=2376;
UPDATE dbc_areapoi SET Name_Lang_enGB='Horde Keep', Description_Lang_enGB='Horde Controlled' WHERE ID=2388;
UPDATE dbc_areapoi SET Name_Lang_enGB='Horde Keep', Description_Lang_enGB='Alliance Controlled' WHERE ID=2389;
UPDATE dbc_areapoi SET Name_Lang_enGB='Horde Keep', Description_Lang_enGB='In Conflict' WHERE ID=2390;
UPDATE dbc_areapoi SET Name_Lang_enGB='Horde Keep', Description_Lang_enGB='In Conflict' WHERE ID=2391;
UPDATE dbc_areapoi SET Name_Lang_enGB='Horde Keep', Description_Lang_enGB='Uncontrolled' WHERE ID=2392;
UPDATE dbc_areapoi SET Name_Lang_enGB='Quarry', Description_Lang_enGB='Uncontrolled' WHERE ID=2361;
UPDATE dbc_areapoi SET Name_Lang_enGB='Quarry', Description_Lang_enGB='Alliance Controlled' WHERE ID=2362;
UPDATE dbc_areapoi SET Name_Lang_enGB='Quarry', Description_Lang_enGB='Horde Controlled' WHERE ID=2363;
UPDATE dbc_areapoi SET Name_Lang_enGB='Quarry', Description_Lang_enGB='In Conflict' WHERE ID=2364;
UPDATE dbc_areapoi SET Name_Lang_enGB='Quarry', Description_Lang_enGB='In Conflict' WHERE ID=2365;
UPDATE dbc_areapoi SET Name_Lang_enGB='Refinery', Description_Lang_enGB='Horde Controlled' WHERE ID=2366;
UPDATE dbc_areapoi SET Name_Lang_enGB='Refinery', Description_Lang_enGB='Alliance Controlled' WHERE ID=2367;
UPDATE dbc_areapoi SET Name_Lang_enGB='Refinery', Description_Lang_enGB='In Conflict' WHERE ID=2368;
UPDATE dbc_areapoi SET Name_Lang_enGB='Refinery', Description_Lang_enGB='In Conflict' WHERE ID=2369;
UPDATE dbc_areapoi SET Name_Lang_enGB='Refinery', Description_Lang_enGB='Uncontrolled' WHERE ID=2370;
UPDATE dbc_areapoi SET Name_Lang_enGB='Workshop', Description_Lang_enGB='Alliance Controlled' WHERE ID=2345;
UPDATE dbc_areapoi SET Name_Lang_enGB='Workshop', Description_Lang_enGB='Horde Controlled' WHERE ID=2346;
UPDATE dbc_areapoi SET Name_Lang_enGB='Workshop', Description_Lang_enGB='In Conflict' WHERE ID=2347;
UPDATE dbc_areapoi SET Name_Lang_enGB='Workshop', Description_Lang_enGB='In Conflict' WHERE ID=2348;
UPDATE dbc_areapoi SET Name_Lang_enGB='Workshop', Description_Lang_enGB='Uncontrolled' WHERE ID=2349;
