UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Long', Description_Lang_enGB='' WHERE ID=3;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Foxtail', Description_Lang_enGB='' WHERE ID=4;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braids', Description_Lang_enGB='' WHERE ID=5;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Swept', Description_Lang_enGB='' WHERE ID=6;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Spiked Tail', Description_Lang_enGB='' WHERE ID=7;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Beaded Braid', Description_Lang_enGB='' WHERE ID=8;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Horned', Description_Lang_enGB='' WHERE ID=9;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Looped Tail', Description_Lang_enGB='' WHERE ID=10;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bald', Description_Lang_enGB='' WHERE ID=11;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bare', Description_Lang_enGB='' WHERE ID=19;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Splayed Tendrils', Description_Lang_enGB='' WHERE ID=20;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Burns', Description_Lang_enGB='' WHERE ID=21;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Chops', Description_Lang_enGB='' WHERE ID=22;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Mustachioed', Description_Lang_enGB='' WHERE ID=23;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Soul Patch', Description_Lang_enGB='' WHERE ID=24;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Goatee', Description_Lang_enGB='' WHERE ID=25;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Twin Tendrils', Description_Lang_enGB='' WHERE ID=26;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Straight', Description_Lang_enGB='' WHERE ID=27;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Loose', Description_Lang_enGB='' WHERE ID=28;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bangs', Description_Lang_enGB='' WHERE ID=29;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Full', Description_Lang_enGB='' WHERE ID=30;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Parted Long', Description_Lang_enGB='' WHERE ID=31;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Flipped', Description_Lang_enGB='' WHERE ID=32;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tomboy', Description_Lang_enGB='' WHERE ID=33;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Pony Right', Description_Lang_enGB='' WHERE ID=34;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Pony Left', Description_Lang_enGB='' WHERE ID=35;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bobbed', Description_Lang_enGB='' WHERE ID=36;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Layered', Description_Lang_enGB='' WHERE ID=37;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Short', Description_Lang_enGB='' WHERE ID=38;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Flirty', Description_Lang_enGB='' WHERE ID=39;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Waved', Description_Lang_enGB='' WHERE ID=40;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bun', Description_Lang_enGB='' WHERE ID=41;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Parted Short', Description_Lang_enGB='' WHERE ID=42;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Waved Bob', Description_Lang_enGB='' WHERE ID=43;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Rushed', Description_Lang_enGB='' WHERE ID=44;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Unpierced', Description_Lang_enGB='' WHERE ID=55;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Earrings', Description_Lang_enGB='' WHERE ID=56;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Upper Earrings', Description_Lang_enGB='' WHERE ID=57;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Double Upper Earrings', Description_Lang_enGB='' WHERE ID=58;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Full Earrings', Description_Lang_enGB='' WHERE ID=59;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Nose Ring', Description_Lang_enGB='' WHERE ID=60;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Nose & Brow Rings', Description_Lang_enGB='' WHERE ID=61;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Soaked', Description_Lang_enGB='' WHERE ID=62;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bald', Description_Lang_enGB='' WHERE ID=63;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Peasant', Description_Lang_enGB='' WHERE ID=64;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Soldier', Description_Lang_enGB='' WHERE ID=65;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Monk', Description_Lang_enGB='' WHERE ID=66;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Barbarian', Description_Lang_enGB='' WHERE ID=67;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Dashing', Description_Lang_enGB='' WHERE ID=68;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Loose', Description_Lang_enGB='' WHERE ID=69;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Courtier', Description_Lang_enGB='' WHERE ID=70;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Scholar', Description_Lang_enGB='' WHERE ID=71;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Rogue', Description_Lang_enGB='' WHERE ID=72;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Fabulous', Description_Lang_enGB='' WHERE ID=73;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Samson', Description_Lang_enGB='' WHERE ID=74;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bearded', Description_Lang_enGB='' WHERE ID=85;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Colonel', Description_Lang_enGB='' WHERE ID=86;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Duelist', Description_Lang_enGB='' WHERE ID=87;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Goatee', Description_Lang_enGB='' WHERE ID=88;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Wizard', Description_Lang_enGB='' WHERE ID=89;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Chops', Description_Lang_enGB='' WHERE ID=90;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Van Dyke', Description_Lang_enGB='' WHERE ID=91;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Mustachioed', Description_Lang_enGB='' WHERE ID=92;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Clean', Description_Lang_enGB='' WHERE ID=93;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Straight', Description_Lang_enGB='' WHERE ID=125;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Flipped', Description_Lang_enGB='' WHERE ID=126;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Cute', Description_Lang_enGB='' WHERE ID=127;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Feathered', Description_Lang_enGB='' WHERE ID=128;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Buns', Description_Lang_enGB='' WHERE ID=129;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Jeweled Band', Description_Lang_enGB='' WHERE ID=130;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bangs', Description_Lang_enGB='' WHERE ID=131;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Elegant', Description_Lang_enGB='' WHERE ID=132;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bounce', Description_Lang_enGB='' WHERE ID=133;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Nape', Description_Lang_enGB='' WHERE ID=134;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Sassy', Description_Lang_enGB='' WHERE ID=135;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Sweeping', Description_Lang_enGB='' WHERE ID=143;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Curled', Description_Lang_enGB='' WHERE ID=144;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Arced', Description_Lang_enGB='' WHERE ID=145;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='High', Description_Lang_enGB='' WHERE ID=146;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Spread', Description_Lang_enGB='' WHERE ID=147;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Grand', Description_Lang_enGB='' WHERE ID=148;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Short', Description_Lang_enGB='' WHERE ID=149;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='High Tail', Description_Lang_enGB='' WHERE ID=175;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Parted Long', Description_Lang_enGB='' WHERE ID=176;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Soaked', Description_Lang_enGB='' WHERE ID=177;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Trouble', Description_Lang_enGB='' WHERE ID=178;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Jeweled Band', Description_Lang_enGB='' WHERE ID=179;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Full', Description_Lang_enGB='' WHERE ID=180;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tied', Description_Lang_enGB='' WHERE ID=181;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bun', Description_Lang_enGB='' WHERE ID=182;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Parted Short', Description_Lang_enGB='' WHERE ID=183;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Simple', Description_Lang_enGB='' WHERE ID=184;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Shy', Description_Lang_enGB='' WHERE ID=185;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Raquel', Description_Lang_enGB='' WHERE ID=186;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Curled', Description_Lang_enGB='' WHERE ID=187;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Headband', Description_Lang_enGB='' WHERE ID=188;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Rubies', Description_Lang_enGB='' WHERE ID=200;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Hoops', Description_Lang_enGB='' WHERE ID=201;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Earrings', Description_Lang_enGB='' WHERE ID=202;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Dangling Emeralds', Description_Lang_enGB='' WHERE ID=203;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Emeralds & Bars', Description_Lang_enGB='' WHERE ID=204;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Upper Earrings', Description_Lang_enGB='' WHERE ID=205;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Pearls', Description_Lang_enGB='' WHERE ID=206;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Dangling Rubies', Description_Lang_enGB='' WHERE ID=207;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Emerald & Pearl Bars', Description_Lang_enGB='' WHERE ID=208;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Rubies & Diamonds', Description_Lang_enGB='' WHERE ID=209;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Flipped', Description_Lang_enGB='' WHERE ID=245;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Swept', Description_Lang_enGB='' WHERE ID=246;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Falcon', Description_Lang_enGB='' WHERE ID=247;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Foxtail', Description_Lang_enGB='' WHERE ID=248;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Parted Long', Description_Lang_enGB='' WHERE ID=249;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Spiked', Description_Lang_enGB='' WHERE ID=250;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Long Bangs', Description_Lang_enGB='' WHERE ID=251;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Feathered Part', Description_Lang_enGB='' WHERE ID=252;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Slicked', Description_Lang_enGB='' WHERE ID=253;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Headband', Description_Lang_enGB='' WHERE ID=254;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Topknot', Description_Lang_enGB='' WHERE ID=255;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Clean', Description_Lang_enGB='' WHERE ID=266;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Point', Description_Lang_enGB='' WHERE ID=267;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Soul Patch', Description_Lang_enGB='' WHERE ID=268;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Spike', Description_Lang_enGB='' WHERE ID=269;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Pointed Chin', Description_Lang_enGB='' WHERE ID=270;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Cropped Chin', Description_Lang_enGB='' WHERE ID=271;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Soul Strip', Description_Lang_enGB='' WHERE ID=272;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Dagger', Description_Lang_enGB='' WHERE ID=273;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Goatee', Description_Lang_enGB='' WHERE ID=274;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Styled Chin', Description_Lang_enGB='' WHERE ID=275;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Mane', Description_Lang_enGB='' WHERE ID=307;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Chonmage Braids', Description_Lang_enGB='' WHERE ID=308;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Long', Description_Lang_enGB='' WHERE ID=309;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tail', Description_Lang_enGB='' WHERE ID=310;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Chonmage Long', Description_Lang_enGB='' WHERE ID=311;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Short Tail', Description_Lang_enGB='' WHERE ID=312;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Windswept', Description_Lang_enGB='' WHERE ID=313;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Clean', Description_Lang_enGB='' WHERE ID=322;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Groomed', Description_Lang_enGB='' WHERE ID=323;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bearded', Description_Lang_enGB='' WHERE ID=324;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Mustachioed', Description_Lang_enGB='' WHERE ID=325;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Chops', Description_Lang_enGB='' WHERE ID=326;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Goatee', Description_Lang_enGB='' WHERE ID=327;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bald', Description_Lang_enGB='' WHERE ID=349;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Long', Description_Lang_enGB='' WHERE ID=350;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tail', Description_Lang_enGB='' WHERE ID=351;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Short', Description_Lang_enGB='' WHERE ID=352;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Topknot', Description_Lang_enGB='' WHERE ID=353;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Short Tail', Description_Lang_enGB='' WHERE ID=354;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Swept', Description_Lang_enGB='' WHERE ID=355;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Receding', Description_Lang_enGB='' WHERE ID=356;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Chonmage', Description_Lang_enGB='' WHERE ID=357;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braid', Description_Lang_enGB='' WHERE ID=358;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Short Braid', Description_Lang_enGB='' WHERE ID=359;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Full', Description_Lang_enGB='' WHERE ID=370;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Double-Braided', Description_Lang_enGB='' WHERE ID=371;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Groomed', Description_Lang_enGB='' WHERE ID=372;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Short', Description_Lang_enGB='' WHERE ID=373;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Grand Mustache', Description_Lang_enGB='' WHERE ID=374;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braided Mustache', Description_Lang_enGB='' WHERE ID=375;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Styled', Description_Lang_enGB='' WHERE ID=376;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Pointed', Description_Lang_enGB='' WHERE ID=377;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braided', Description_Lang_enGB='' WHERE ID=378;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Humbug', Description_Lang_enGB='' WHERE ID=379;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Grimbeard', Description_Lang_enGB='' WHERE ID=380;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Topknot', Description_Lang_enGB='' WHERE ID=413;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tail', Description_Lang_enGB='' WHERE ID=414;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Crest', Description_Lang_enGB='' WHERE ID=415;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tufts', Description_Lang_enGB='' WHERE ID=416;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Boar Tails', Description_Lang_enGB='' WHERE ID=417;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Horns', Description_Lang_enGB='' WHERE ID=418;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Mane', Description_Lang_enGB='' WHERE ID=419;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Shaved', Description_Lang_enGB='' WHERE ID=420;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Unpierced', Description_Lang_enGB='' WHERE ID=429;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Earrings', Description_Lang_enGB='' WHERE ID=430;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Upper Earrings', Description_Lang_enGB='' WHERE ID=431;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Nose Ring', Description_Lang_enGB='' WHERE ID=432;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Nose & Earrings', Description_Lang_enGB='' WHERE ID=433;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Nose & Upper Earrings', Description_Lang_enGB='' WHERE ID=434;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Full Earrings', Description_Lang_enGB='' WHERE ID=435;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Double-Braided', Description_Lang_enGB='' WHERE ID=459;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braided Buns', Description_Lang_enGB='' WHERE ID=460;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braided', Description_Lang_enGB='' WHERE ID=461;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Boar Tails', Description_Lang_enGB='' WHERE ID=462;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braided Bun', Description_Lang_enGB='' WHERE ID=463;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Looped', Description_Lang_enGB='' WHERE ID=464;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tied', Description_Lang_enGB='' WHERE ID=465;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Short', Description_Lang_enGB='' WHERE ID=466;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Parted', Description_Lang_enGB='' WHERE ID=467;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Short Braids', Description_Lang_enGB='' WHERE ID=468;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bobbed', Description_Lang_enGB='' WHERE ID=469;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Cropped', Description_Lang_enGB='' WHERE ID=470;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bangs & Braids', Description_Lang_enGB='' WHERE ID=471;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Gathered', Description_Lang_enGB='' WHERE ID=472;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Unpierced', Description_Lang_enGB='' WHERE ID=483;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Earrings', Description_Lang_enGB='' WHERE ID=484;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Upper Earring', Description_Lang_enGB='' WHERE ID=485;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Double Upper Earring', Description_Lang_enGB='' WHERE ID=486;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Nose Ring', Description_Lang_enGB='' WHERE ID=487;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Small Earrings', Description_Lang_enGB='' WHERE ID=488;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tower', Description_Lang_enGB='' WHERE ID=519;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Sprouts', Description_Lang_enGB='' WHERE ID=520;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Boar Tails', Description_Lang_enGB='' WHERE ID=521;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Parted', Description_Lang_enGB='' WHERE ID=522;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Soaked', Description_Lang_enGB='' WHERE ID=523;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braided Buns', Description_Lang_enGB='' WHERE ID=524;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bobbed', Description_Lang_enGB='' WHERE ID=525;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Unpierced', Description_Lang_enGB='' WHERE ID=535;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Earrings', Description_Lang_enGB='' WHERE ID=536;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Small Earrings', Description_Lang_enGB='' WHERE ID=537;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Upper Earrings', Description_Lang_enGB='' WHERE ID=538;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Full Earrings', Description_Lang_enGB='' WHERE ID=539;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Left Earring', Description_Lang_enGB='' WHERE ID=540;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Right Earring', Description_Lang_enGB='' WHERE ID=541;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bald', Description_Lang_enGB='' WHERE ID=565;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Wings', Description_Lang_enGB='' WHERE ID=566;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Groomed', Description_Lang_enGB='' WHERE ID=567;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Cowlicked', Description_Lang_enGB='' WHERE ID=568;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Styled', Description_Lang_enGB='' WHERE ID=569;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Balding', Description_Lang_enGB='' WHERE ID=570;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Combover', Description_Lang_enGB='' WHERE ID=571;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Clean', Description_Lang_enGB='' WHERE ID=581;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Goatee', Description_Lang_enGB='' WHERE ID=582;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Chops', Description_Lang_enGB='' WHERE ID=583;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Waxed', Description_Lang_enGB='' WHERE ID=584;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bearded', Description_Lang_enGB='' WHERE ID=585;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Handlebars', Description_Lang_enGB='' WHERE ID=586;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Styled', Description_Lang_enGB='' WHERE ID=587;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Mustachioed', Description_Lang_enGB='' WHERE ID=588;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bald', Description_Lang_enGB='' WHERE ID=613;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Mohawk', Description_Lang_enGB='' WHERE ID=614;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Shaggy', Description_Lang_enGB='' WHERE ID=615;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Wisps', Description_Lang_enGB='' WHERE ID=616;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Spiked', Description_Lang_enGB='' WHERE ID=617;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Wild', Description_Lang_enGB='' WHERE ID=618;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Scholar', Description_Lang_enGB='' WHERE ID=619;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Full', Description_Lang_enGB='' WHERE ID=620;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Topknot', Description_Lang_enGB='' WHERE ID=621;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Long', Description_Lang_enGB='' WHERE ID=622;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Intact', Description_Lang_enGB='' WHERE ID=633;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Rot-Kissed', Description_Lang_enGB='' WHERE ID=634;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Strapped', Description_Lang_enGB='' WHERE ID=635;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Strapped Slackjaw', Description_Lang_enGB='' WHERE ID=636;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Strapped Drooler', Description_Lang_enGB='' WHERE ID=637;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Rotting', Description_Lang_enGB='' WHERE ID=638;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Rotting Slackjaw', Description_Lang_enGB='' WHERE ID=639;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Rotting Drooler', Description_Lang_enGB='' WHERE ID=640;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bonejawed', Description_Lang_enGB='' WHERE ID=641;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Jawsome', Description_Lang_enGB='' WHERE ID=642;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Toothy', Description_Lang_enGB='' WHERE ID=643;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Toothy Slackjaw', Description_Lang_enGB='' WHERE ID=644;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Cheeky', Description_Lang_enGB='' WHERE ID=645;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Cheeky Slackjaw', Description_Lang_enGB='' WHERE ID=646;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Putrid', Description_Lang_enGB='' WHERE ID=647;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Putrid Slackjaw', Description_Lang_enGB='' WHERE ID=648;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Putrid Drooler', Description_Lang_enGB='' WHERE ID=649;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Wild', Description_Lang_enGB='' WHERE ID=687;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Shaggy', Description_Lang_enGB='' WHERE ID=688;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Loose', Description_Lang_enGB='' WHERE ID=689;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Windswept', Description_Lang_enGB='' WHERE ID=690;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Long', Description_Lang_enGB='' WHERE ID=691;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='The Bride', Description_Lang_enGB='' WHERE ID=692;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tomboy', Description_Lang_enGB='' WHERE ID=693;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Styled', Description_Lang_enGB='' WHERE ID=694;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bobbed', Description_Lang_enGB='' WHERE ID=695;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Soaked', Description_Lang_enGB='' WHERE ID=696;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Intact', Description_Lang_enGB='' WHERE ID=707;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Stitched', Description_Lang_enGB='' WHERE ID=708;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Strapped', Description_Lang_enGB='' WHERE ID=709;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Rotting', Description_Lang_enGB='' WHERE ID=710;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bonejawed', Description_Lang_enGB='' WHERE ID=711;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Toothy', Description_Lang_enGB='' WHERE ID=712;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Cheeky', Description_Lang_enGB='' WHERE ID=713;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Putrid', Description_Lang_enGB='' WHERE ID=714;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Longhorn', Description_Lang_enGB='' WHERE ID=743;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bull', Description_Lang_enGB='' WHERE ID=744;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Charger', Description_Lang_enGB='' WHERE ID=745;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Broken', Description_Lang_enGB='' WHERE ID=746;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Snapped', Description_Lang_enGB='' WHERE ID=747;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tiny', Description_Lang_enGB='' WHERE ID=748;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Buffalo', Description_Lang_enGB='' WHERE ID=749;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Gorefest', Description_Lang_enGB='' WHERE ID=750;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Clean', Description_Lang_enGB='' WHERE ID=754;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Triple Braids', Description_Lang_enGB='' WHERE ID=755;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Ringed', Description_Lang_enGB='' WHERE ID=756;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braid', Description_Lang_enGB='' WHERE ID=757;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bearded', Description_Lang_enGB='' WHERE ID=758;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Double Braids', Description_Lang_enGB='' WHERE ID=759;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Ringed & Braided', Description_Lang_enGB='' WHERE ID=760;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bald', Description_Lang_enGB='' WHERE ID=779;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Topknot', Description_Lang_enGB='' WHERE ID=780;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Chonmage', Description_Lang_enGB='' WHERE ID=781;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Crest', Description_Lang_enGB='' WHERE ID=782;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Chonmage Long', Description_Lang_enGB='' WHERE ID=783;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braided', Description_Lang_enGB='' WHERE ID=784;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tail', Description_Lang_enGB='' WHERE ID=785;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Clean', Description_Lang_enGB='' WHERE ID=794;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Rough', Description_Lang_enGB='' WHERE ID=795;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Groomed Beard', Description_Lang_enGB='' WHERE ID=796;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Cropped Beard', Description_Lang_enGB='' WHERE ID=797;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Wild Beard', Description_Lang_enGB='' WHERE ID=798;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Thick Braid', Description_Lang_enGB='' WHERE ID=799;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Twin Braids', Description_Lang_enGB='' WHERE ID=800;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Chop Braids', Description_Lang_enGB='' WHERE ID=801;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Thin Braid', Description_Lang_enGB='' WHERE ID=802;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Chops', Description_Lang_enGB='' WHERE ID=803;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tufts', Description_Lang_enGB='' WHERE ID=804;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Horned', Description_Lang_enGB='' WHERE ID=831;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Low', Description_Lang_enGB='' WHERE ID=832;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Long', Description_Lang_enGB='' WHERE ID=833;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Upturned', Description_Lang_enGB='' WHERE ID=834;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Small', Description_Lang_enGB='' WHERE ID=835;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Wide', Description_Lang_enGB='' WHERE ID=836;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Buffalo', Description_Lang_enGB='' WHERE ID=837;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Maned', Description_Lang_enGB='' WHERE ID=841;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braids', Description_Lang_enGB='' WHERE ID=842;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Loops', Description_Lang_enGB='' WHERE ID=843;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tails', Description_Lang_enGB='' WHERE ID=844;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tufts', Description_Lang_enGB='' WHERE ID=845;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Long', Description_Lang_enGB='' WHERE ID=861;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Loose Tail', Description_Lang_enGB='' WHERE ID=862;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Short', Description_Lang_enGB='' WHERE ID=863;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='High Tail', Description_Lang_enGB='' WHERE ID=864;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braided Tails', Description_Lang_enGB='' WHERE ID=865;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Short Tail', Description_Lang_enGB='' WHERE ID=866;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braided Tail', Description_Lang_enGB='' WHERE ID=867;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bear', Description_Lang_enGB='' WHERE ID=876;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Blades', Description_Lang_enGB='' WHERE ID=877;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Crane', Description_Lang_enGB='' WHERE ID=878;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Leaf', Description_Lang_enGB='' WHERE ID=879;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Claws', Description_Lang_enGB='' WHERE ID=880;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Wings', Description_Lang_enGB='' WHERE ID=881;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Serpent', Description_Lang_enGB='' WHERE ID=882;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Owl', Description_Lang_enGB='' WHERE ID=883;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Shadow', Description_Lang_enGB='' WHERE ID=884;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='No Tattoo', Description_Lang_enGB='' WHERE ID=885;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bald', Description_Lang_enGB='' WHERE ID=911;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Receding', Description_Lang_enGB='' WHERE ID=912;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Crest', Description_Lang_enGB='' WHERE ID=913;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Windswept', Description_Lang_enGB='' WHERE ID=914;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Topknot', Description_Lang_enGB='' WHERE ID=915;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tail', Description_Lang_enGB='' WHERE ID=916;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tusked', Description_Lang_enGB='' WHERE ID=927;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Gougers', Description_Lang_enGB='' WHERE ID=928;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Mammoth', Description_Lang_enGB='' WHERE ID=929;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Upturned', Description_Lang_enGB='' WHERE ID=930;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bridle', Description_Lang_enGB='' WHERE ID=931;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tusked Mask', Description_Lang_enGB='' WHERE ID=932;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Warpaint Gougers', Description_Lang_enGB='' WHERE ID=933;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Striped Mammoth', Description_Lang_enGB='' WHERE ID=934;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Painted Upturned', Description_Lang_enGB='' WHERE ID=935;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Painted Bridle', Description_Lang_enGB='' WHERE ID=936;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Spotted Mammoth', Description_Lang_enGB='' WHERE ID=937;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braids', Description_Lang_enGB='' WHERE ID=965;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='High Tail', Description_Lang_enGB='' WHERE ID=966;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Swept Braids', Description_Lang_enGB='' WHERE ID=967;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Topknot', Description_Lang_enGB='' WHERE ID=968;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braided Crest', Description_Lang_enGB='' WHERE ID=969;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Nibblers', Description_Lang_enGB='' WHERE ID=980;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Short', Description_Lang_enGB='' WHERE ID=981;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Straight', Description_Lang_enGB='' WHERE ID=982;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Upturned', Description_Lang_enGB='' WHERE ID=983;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Long', Description_Lang_enGB='' WHERE ID=984;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Oni', Description_Lang_enGB='' WHERE ID=985;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Prince', Description_Lang_enGB='' WHERE ID=1012;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Spikes', Description_Lang_enGB='' WHERE ID=1013;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Swept', Description_Lang_enGB='' WHERE ID=1014;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Foxtail', Description_Lang_enGB='' WHERE ID=1015;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Slicked', Description_Lang_enGB='' WHERE ID=1016;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Styled', Description_Lang_enGB='' WHERE ID=1017;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Elaborate', Description_Lang_enGB='' WHERE ID=1018;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Nape', Description_Lang_enGB='' WHERE ID=1019;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Boar Tails', Description_Lang_enGB='' WHERE ID=1020;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bangs', Description_Lang_enGB='' WHERE ID=1021;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Unpierced', Description_Lang_enGB='' WHERE ID=1022;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Mane', Description_Lang_enGB='' WHERE ID=1029;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Chonmage Braids', Description_Lang_enGB='' WHERE ID=1030;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tail', Description_Lang_enGB='' WHERE ID=1031;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Windswept', Description_Lang_enGB='' WHERE ID=1032;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Chonmage Long', Description_Lang_enGB='' WHERE ID=1033;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Spiked', Description_Lang_enGB='' WHERE ID=1034;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Backspike', Description_Lang_enGB='' WHERE ID=1035;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Horned Foxtail', Description_Lang_enGB='' WHERE ID=1036;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Topknot', Description_Lang_enGB='' WHERE ID=1037;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Emo', Description_Lang_enGB='' WHERE ID=1038;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Hairband', Description_Lang_enGB='' WHERE ID=1039;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Trouble', Description_Lang_enGB='' WHERE ID=1040;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Shy', Description_Lang_enGB='' WHERE ID=1041;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='High Tail', Description_Lang_enGB='' WHERE ID=1042;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Soaked', Description_Lang_enGB='' WHERE ID=1043;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Barbarian', Description_Lang_enGB='' WHERE ID=1044;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Soldier', Description_Lang_enGB='' WHERE ID=1045;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Scholar', Description_Lang_enGB='' WHERE ID=1046;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Laurel Wreath', Description_Lang_enGB='' WHERE ID=1047;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Fabulous', Description_Lang_enGB='' WHERE ID=1048;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Bun', Description_Lang_enGB='' WHERE ID=1049;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Flirty', Description_Lang_enGB='' WHERE ID=1050;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Waved Bob', Description_Lang_enGB='' WHERE ID=1051;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braided Tails', Description_Lang_enGB='' WHERE ID=1052;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braided Tail', Description_Lang_enGB='' WHERE ID=1053;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Windswept', Description_Lang_enGB='' WHERE ID=1054;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Shaggy', Description_Lang_enGB='' WHERE ID=1055;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Mohawk', Description_Lang_enGB='' WHERE ID=1056;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Loose', Description_Lang_enGB='' WHERE ID=1057;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Wild', Description_Lang_enGB='' WHERE ID=1058;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Short', Description_Lang_enGB='' WHERE ID=1059;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Cute', Description_Lang_enGB='' WHERE ID=1060;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tail', Description_Lang_enGB='' WHERE ID=1061;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Looped', Description_Lang_enGB='' WHERE ID=1062;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tied', Description_Lang_enGB='' WHERE ID=1063;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Slicked', Description_Lang_enGB='' WHERE ID=1064;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Styled', Description_Lang_enGB='' WHERE ID=1065;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Curled', Description_Lang_enGB='' WHERE ID=1066;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Raquel', Description_Lang_enGB='' WHERE ID=1067;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Simple', Description_Lang_enGB='' WHERE ID=1068;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Short Braided Tail', Description_Lang_enGB='' WHERE ID=1069;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Wild', Description_Lang_enGB='' WHERE ID=1070;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braided Tail', Description_Lang_enGB='' WHERE ID=1071;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Mohawk', Description_Lang_enGB='' WHERE ID=1072;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Long Braided Tail', Description_Lang_enGB='' WHERE ID=1073;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Hairband', Description_Lang_enGB='' WHERE ID=1074;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Soaked', Description_Lang_enGB='' WHERE ID=1075;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tomboy', Description_Lang_enGB='' WHERE ID=1076;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Gathered', Description_Lang_enGB='' WHERE ID=1077;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Looped', Description_Lang_enGB='' WHERE ID=1078;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Spiked', Description_Lang_enGB='' WHERE ID=1079;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Mohawk', Description_Lang_enGB='' WHERE ID=1080;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Slicked Topknot', Description_Lang_enGB='' WHERE ID=1081;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Long', Description_Lang_enGB='' WHERE ID=1082;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Wild', Description_Lang_enGB='' WHERE ID=1083;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Wild', Description_Lang_enGB='' WHERE ID=1084;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Styled', Description_Lang_enGB='' WHERE ID=1085;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tomboy', Description_Lang_enGB='' WHERE ID=1086;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Flipped', Description_Lang_enGB='' WHERE ID=1087;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Tipped', Description_Lang_enGB='' WHERE ID=1088;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Curled', Description_Lang_enGB='' WHERE ID=1089;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Capped', Description_Lang_enGB='' WHERE ID=1090;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Lyre', Description_Lang_enGB='' WHERE ID=1091;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Ringed', Description_Lang_enGB='' WHERE ID=1092;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Charger', Description_Lang_enGB='' WHERE ID=1093;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Snapped', Description_Lang_enGB='' WHERE ID=1094;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Gougers', Description_Lang_enGB='' WHERE ID=1095;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Close', Description_Lang_enGB='' WHERE ID=1096;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Stubs', Description_Lang_enGB='' WHERE ID=1097;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Braids', Description_Lang_enGB='' WHERE ID=1098;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Plume', Description_Lang_enGB='' WHERE ID=1099;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Scruffy', Description_Lang_enGB='' WHERE ID=1100;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Mohawk', Description_Lang_enGB='' WHERE ID=1101;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Jungle Flower', Description_Lang_enGB='' WHERE ID=1102;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Wrapped Braid', Description_Lang_enGB='' WHERE ID=1103;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Mohawk', Description_Lang_enGB='' WHERE ID=1104;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Mota', Description_Lang_enGB='' WHERE ID=1105;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Fauxhawk', Description_Lang_enGB='' WHERE ID=1106;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Swept', Description_Lang_enGB='' WHERE ID=1107;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Monk', Description_Lang_enGB='' WHERE ID=1108;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='High', Description_Lang_enGB='' WHERE ID=1109;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Barbarian', Description_Lang_enGB='' WHERE ID=1110;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Short', Description_Lang_enGB='' WHERE ID=1111;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Boar Tails', Description_Lang_enGB='' WHERE ID=1112;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Parted', Description_Lang_enGB='' WHERE ID=1113;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Short', Description_Lang_enGB='' WHERE ID=1114;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Unkept', Description_Lang_enGB='' WHERE ID=1115;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Sprouts', Description_Lang_enGB='' WHERE ID=1116;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='Long', Description_Lang_enGB='' WHERE ID=1117;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1120;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1121;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1122;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1123;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1124;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1125;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1126;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1127;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1128;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1129;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1130;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1131;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1132;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1133;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1134;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1135;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1136;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1137;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1138;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1139;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1140;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1141;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1142;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1143;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1144;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1145;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1146;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1147;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1148;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_enGB='', Description_Lang_enGB='' WHERE ID=1149;
