UPDATE dbc_chartitles SET Name_Lang_enGB='Private %s', Name1_Lang_enGB='Private %s' WHERE ID=1;
UPDATE dbc_chartitles SET Name_Lang_enGB='Corporal %s', Name1_Lang_enGB='Corporal %s' WHERE ID=2;
UPDATE dbc_chartitles SET Name_Lang_enGB='Sergeant %s', Name1_Lang_enGB='Sergeant %s' WHERE ID=3;
UPDATE dbc_chartitles SET Name_Lang_enGB='Master Sergeant %s', Name1_Lang_enGB='Master Sergeant %s' WHERE ID=4;
UPDATE dbc_chartitles SET Name_Lang_enGB='Sergeant Major %s', Name1_Lang_enGB='Sergeant Major %s' WHERE ID=5;
UPDATE dbc_chartitles SET Name_Lang_enGB='Knight %s', Name1_Lang_enGB='Knight %s' WHERE ID=6;
UPDATE dbc_chartitles SET Name_Lang_enGB='Knight-Lieutenant %s', Name1_Lang_enGB='Knight-Lieutenant %s' WHERE ID=7;
UPDATE dbc_chartitles SET Name_Lang_enGB='Knight-Captain %s', Name1_Lang_enGB='Knight-Captain %s' WHERE ID=8;
UPDATE dbc_chartitles SET Name_Lang_enGB='Knight-Champion %s', Name1_Lang_enGB='Knight-Champion %s' WHERE ID=9;
UPDATE dbc_chartitles SET Name_Lang_enGB='Lieutenant Commander %s', Name1_Lang_enGB='Lieutenant Commander %s' WHERE ID=10;
UPDATE dbc_chartitles SET Name_Lang_enGB='Commander %s', Name1_Lang_enGB='Commander %s' WHERE ID=11;
UPDATE dbc_chartitles SET Name_Lang_enGB='Marshal %s', Name1_Lang_enGB='Marshal %s' WHERE ID=12;
UPDATE dbc_chartitles SET Name_Lang_enGB='Field Marshal %s', Name1_Lang_enGB='Field Marshal %s' WHERE ID=13;
UPDATE dbc_chartitles SET Name_Lang_enGB='Grand Marshal %s', Name1_Lang_enGB='Grand Marshal %s' WHERE ID=14;
UPDATE dbc_chartitles SET Name_Lang_enGB='Scout %s', Name1_Lang_enGB='Scout %s' WHERE ID=15;
UPDATE dbc_chartitles SET Name_Lang_enGB='Grunt %s', Name1_Lang_enGB='Grunt %s' WHERE ID=16;
UPDATE dbc_chartitles SET Name_Lang_enGB='Sergeant %s', Name1_Lang_enGB='Sergeant %s' WHERE ID=17;
UPDATE dbc_chartitles SET Name_Lang_enGB='Senior Sergeant %s', Name1_Lang_enGB='Senior Sergeant %s' WHERE ID=18;
UPDATE dbc_chartitles SET Name_Lang_enGB='First Sergeant %s', Name1_Lang_enGB='First Sergeant %s' WHERE ID=19;
UPDATE dbc_chartitles SET Name_Lang_enGB='Stone Guard %s', Name1_Lang_enGB='Stone Guard %s' WHERE ID=20;
UPDATE dbc_chartitles SET Name_Lang_enGB='Blood Guard %s', Name1_Lang_enGB='Blood Guard %s' WHERE ID=21;
UPDATE dbc_chartitles SET Name_Lang_enGB='Legionnaire %s', Name1_Lang_enGB='Legionnaire %s' WHERE ID=22;
UPDATE dbc_chartitles SET Name_Lang_enGB='Centurion %s', Name1_Lang_enGB='Centurion %s' WHERE ID=23;
UPDATE dbc_chartitles SET Name_Lang_enGB='Champion %s', Name1_Lang_enGB='Champion %s' WHERE ID=24;
UPDATE dbc_chartitles SET Name_Lang_enGB='Lieutenant General %s', Name1_Lang_enGB='Lieutenant General %s' WHERE ID=25;
UPDATE dbc_chartitles SET Name_Lang_enGB='General %s', Name1_Lang_enGB='General %s' WHERE ID=26;
UPDATE dbc_chartitles SET Name_Lang_enGB='Warlord %s', Name1_Lang_enGB='Warlord %s' WHERE ID=27;
UPDATE dbc_chartitles SET Name_Lang_enGB='High Warlord %s', Name1_Lang_enGB='High Warlord %s' WHERE ID=28;
UPDATE dbc_chartitles SET Name_Lang_enGB='Gladiator %s', Name1_Lang_enGB='Gladiator %s' WHERE ID=42;
UPDATE dbc_chartitles SET Name_Lang_enGB='Duelist %s', Name1_Lang_enGB='Duelist %s' WHERE ID=43;
UPDATE dbc_chartitles SET Name_Lang_enGB='Rival %s', Name1_Lang_enGB='Rival %s' WHERE ID=44;
UPDATE dbc_chartitles SET Name_Lang_enGB='Challenger %s', Name1_Lang_enGB='Challenger %s' WHERE ID=45;
UPDATE dbc_chartitles SET Name_Lang_enGB='Scarab Lord %s', Name1_Lang_enGB='Scarab Lord %s' WHERE ID=46;
UPDATE dbc_chartitles SET Name_Lang_enGB='Conqueror %s', Name1_Lang_enGB='Conqueror %s' WHERE ID=47;
UPDATE dbc_chartitles SET Name_Lang_enGB='Justicar %s', Name1_Lang_enGB='Justicar %s' WHERE ID=48;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s, Champion of the Naaru', Name1_Lang_enGB='%s, Champion of the Naaru' WHERE ID=53;
UPDATE dbc_chartitles SET Name_Lang_enGB='Merciless Gladiator %s', Name1_Lang_enGB='Merciless Gladiator %s' WHERE ID=62;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of the Shattered Sun', Name1_Lang_enGB='%s of the Shattered Sun' WHERE ID=63;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s, Hand of A''dal', Name1_Lang_enGB='%s, Hand of A''dal' WHERE ID=64;
UPDATE dbc_chartitles SET Name_Lang_enGB='Vengeful Gladiator %s', Name1_Lang_enGB='Vengeful Gladiator %s' WHERE ID=71;
UPDATE dbc_chartitles SET Name_Lang_enGB='Battlemaster %s', Name1_Lang_enGB='Battlemaster %s' WHERE ID=72;
UPDATE dbc_chartitles SET Name_Lang_enGB='Elder %s', Name1_Lang_enGB='Elder %s' WHERE ID=74;
UPDATE dbc_chartitles SET Name_Lang_enGB='Flame Warden %s', Name1_Lang_enGB='Flame Warden %s' WHERE ID=75;
UPDATE dbc_chartitles SET Name_Lang_enGB='Flame Keeper %s', Name1_Lang_enGB='Flame Keeper %s' WHERE ID=76;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Exalted', Name1_Lang_enGB='%s the Exalted' WHERE ID=77;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Explorer', Name1_Lang_enGB='%s the Explorer' WHERE ID=78;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Diplomat', Name1_Lang_enGB='%s the Diplomat' WHERE ID=79;
UPDATE dbc_chartitles SET Name_Lang_enGB='Brutal Gladiator %s', Name1_Lang_enGB='Brutal Gladiator %s' WHERE ID=80;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Seeker', Name1_Lang_enGB='%s the Seeker' WHERE ID=81;
UPDATE dbc_chartitles SET Name_Lang_enGB='Arena Master %s', Name1_Lang_enGB='Arena Master %s' WHERE ID=82;
UPDATE dbc_chartitles SET Name_Lang_enGB='Salty %s', Name1_Lang_enGB='Salty %s' WHERE ID=83;
UPDATE dbc_chartitles SET Name_Lang_enGB='Chef %s', Name1_Lang_enGB='Chef %s' WHERE ID=84;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Supreme', Name1_Lang_enGB='%s the Supreme' WHERE ID=85;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of the Ten Storms', Name1_Lang_enGB='%s of the Ten Storms' WHERE ID=86;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of the Emerald Dream', Name1_Lang_enGB='%s of the Emerald Dream' WHERE ID=87;
UPDATE dbc_chartitles SET Name_Lang_enGB='Prophet %s', Name1_Lang_enGB='Prophet %s' WHERE ID=89;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Malefic', Name1_Lang_enGB='%s the Malefic' WHERE ID=90;
UPDATE dbc_chartitles SET Name_Lang_enGB='Stalker %s', Name1_Lang_enGB='Stalker %s' WHERE ID=91;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of the Ebon Blade', Name1_Lang_enGB='%s of the Ebon Blade' WHERE ID=92;
UPDATE dbc_chartitles SET Name_Lang_enGB='Archmage %s', Name1_Lang_enGB='Archmage %s' WHERE ID=93;
UPDATE dbc_chartitles SET Name_Lang_enGB='Warbringer %s', Name1_Lang_enGB='Warbringer %s' WHERE ID=94;
UPDATE dbc_chartitles SET Name_Lang_enGB='Assassin %s', Name1_Lang_enGB='Assassin %s' WHERE ID=95;
UPDATE dbc_chartitles SET Name_Lang_enGB='Grand Master Alchemist %s', Name1_Lang_enGB='Grand Master Alchemist %s' WHERE ID=96;
UPDATE dbc_chartitles SET Name_Lang_enGB='Grand Master Blacksmith %s', Name1_Lang_enGB='Grand Master Blacksmith %s' WHERE ID=97;
UPDATE dbc_chartitles SET Name_Lang_enGB='Iron Chef %s', Name1_Lang_enGB='Iron Chef %s' WHERE ID=98;
UPDATE dbc_chartitles SET Name_Lang_enGB='Grand Master Enchanter %s', Name1_Lang_enGB='Grand Master Enchanter %s' WHERE ID=99;
UPDATE dbc_chartitles SET Name_Lang_enGB='Grand Master Engineer %s', Name1_Lang_enGB='Grand Master Engineer %s' WHERE ID=100;
UPDATE dbc_chartitles SET Name_Lang_enGB='Doctor %s', Name1_Lang_enGB='Doctor %s' WHERE ID=101;
UPDATE dbc_chartitles SET Name_Lang_enGB='Grand Master Angler %s', Name1_Lang_enGB='Grand Master Angler %s' WHERE ID=102;
UPDATE dbc_chartitles SET Name_Lang_enGB='Grand Master Herbalist %s', Name1_Lang_enGB='Grand Master Herbalist %s' WHERE ID=103;
UPDATE dbc_chartitles SET Name_Lang_enGB='Grand Master Scribe %s', Name1_Lang_enGB='Grand Master Scribe %s' WHERE ID=104;
UPDATE dbc_chartitles SET Name_Lang_enGB='Grand Master Jewelcrafter %s', Name1_Lang_enGB='Grand Master Jewelcrafter %s' WHERE ID=105;
UPDATE dbc_chartitles SET Name_Lang_enGB='Grand Master Leatherworker %s', Name1_Lang_enGB='Grand Master Leatherworker %s' WHERE ID=106;
UPDATE dbc_chartitles SET Name_Lang_enGB='Grand Master Miner %s', Name1_Lang_enGB='Grand Master Miner %s' WHERE ID=107;
UPDATE dbc_chartitles SET Name_Lang_enGB='Grand Master Skinner %s', Name1_Lang_enGB='Grand Master Skinner %s' WHERE ID=108;
UPDATE dbc_chartitles SET Name_Lang_enGB='Grand Master Tailor %s', Name1_Lang_enGB='Grand Master Tailor %s' WHERE ID=109;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of Quel''Thalas', Name1_Lang_enGB='%s of Quel''Thalas' WHERE ID=110;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of Argus', Name1_Lang_enGB='%s of Argus' WHERE ID=111;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of Khaz Modan', Name1_Lang_enGB='%s of Khaz Modan' WHERE ID=112;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of Gnomeregan', Name1_Lang_enGB='%s of Gnomeregan' WHERE ID=113;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Lion Hearted', Name1_Lang_enGB='%s the Lion Hearted' WHERE ID=114;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s, Champion of Elune', Name1_Lang_enGB='%s, Champion of Elune' WHERE ID=115;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s, Hero of Orgrimmar', Name1_Lang_enGB='%s, Hero of Orgrimmar' WHERE ID=116;
UPDATE dbc_chartitles SET Name_Lang_enGB='Plainsrunner %s', Name1_Lang_enGB='Plainsrunner %s' WHERE ID=117;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of the Darkspear', Name1_Lang_enGB='%s of the Darkspear' WHERE ID=118;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Forsaken', Name1_Lang_enGB='%s the Forsaken' WHERE ID=119;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Magic Seeker', Name1_Lang_enGB='%s the Magic Seeker' WHERE ID=120;
UPDATE dbc_chartitles SET Name_Lang_enGB='Twilight Vanquisher %s', Name1_Lang_enGB='Twilight Vanquisher %s' WHERE ID=121;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s, Conqueror of Naxxramas', Name1_Lang_enGB='%s, Conqueror of Naxxramas' WHERE ID=122;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s, Hero of Northrend', Name1_Lang_enGB='%s, Hero of Northrend' WHERE ID=123;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Hallowed', Name1_Lang_enGB='%s the Hallowed' WHERE ID=124;
UPDATE dbc_chartitles SET Name_Lang_enGB='Loremaster %s', Name1_Lang_enGB='Loremaster %s' WHERE ID=125;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of the Alliance', Name1_Lang_enGB='%s of the Alliance' WHERE ID=126;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of the Horde', Name1_Lang_enGB='%s of the Horde' WHERE ID=127;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Flawless Victor', Name1_Lang_enGB='%s the Flawless Victor' WHERE ID=128;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s, Champion of the Frozen Wastes', Name1_Lang_enGB='%s, Champion of the Frozen Wastes' WHERE ID=129;
UPDATE dbc_chartitles SET Name_Lang_enGB='Ambassador %s', Name1_Lang_enGB='Ambassador %s' WHERE ID=130;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Argent Champion', Name1_Lang_enGB='%s the Argent Champion' WHERE ID=131;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s, Guardian of Cenarius', Name1_Lang_enGB='%s, Guardian of Cenarius' WHERE ID=132;
UPDATE dbc_chartitles SET Name_Lang_enGB='Brewmaster %s', Name1_Lang_enGB='Brewmaster %s' WHERE ID=133;
UPDATE dbc_chartitles SET Name_Lang_enGB='Merrymaker %s', Name1_Lang_enGB='Merrymaker %s' WHERE ID=134;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Love Fool', Name1_Lang_enGB='%s the Love Fool' WHERE ID=135;
UPDATE dbc_chartitles SET Name_Lang_enGB='Matron %s', Name1_Lang_enGB='Matron %s' WHERE ID=137;
UPDATE dbc_chartitles SET Name_Lang_enGB='Patron %s', Name1_Lang_enGB='Patron %s' WHERE ID=138;
UPDATE dbc_chartitles SET Name_Lang_enGB='Obsidian Slayer %s', Name1_Lang_enGB='Obsidian Slayer %s' WHERE ID=139;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of the Nightfall', Name1_Lang_enGB='%s of the Nightfall' WHERE ID=140;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Immortal', Name1_Lang_enGB='%s the Immortal' WHERE ID=141;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Undying', Name1_Lang_enGB='%s the Undying' WHERE ID=142;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s Jenkins', Name1_Lang_enGB='%s Jenkins' WHERE ID=143;
UPDATE dbc_chartitles SET Name_Lang_enGB='Bloodsail Admiral %s', Name1_Lang_enGB='Bloodsail Admiral %s' WHERE ID=144;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Insane', Name1_Lang_enGB='%s the Insane' WHERE ID=145;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of the Exodar', Name1_Lang_enGB='%s of the Exodar' WHERE ID=146;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of Darnassus', Name1_Lang_enGB='%s of Darnassus' WHERE ID=147;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of Ironforge', Name1_Lang_enGB='%s of Ironforge' WHERE ID=148;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of Stormwind', Name1_Lang_enGB='%s of Stormwind' WHERE ID=149;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of Orgrimmar', Name1_Lang_enGB='%s of Orgrimmar' WHERE ID=150;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of Sen''jin', Name1_Lang_enGB='%s of Sen''jin' WHERE ID=151;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of Silvermoon', Name1_Lang_enGB='%s of Silvermoon' WHERE ID=152;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of Thunder Bluff', Name1_Lang_enGB='%s of Thunder Bluff' WHERE ID=153;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of the Undercity', Name1_Lang_enGB='%s of the Undercity' WHERE ID=154;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Noble', Name1_Lang_enGB='%s the Noble' WHERE ID=155;
UPDATE dbc_chartitles SET Name_Lang_enGB='Crusader %s', Name1_Lang_enGB='Crusader %s' WHERE ID=156;
UPDATE dbc_chartitles SET Name_Lang_enGB='Deadly Gladiator %s', Name1_Lang_enGB='Deadly Gladiator %s' WHERE ID=157;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s, Death''s Demise', Name1_Lang_enGB='%s, Death''s Demise' WHERE ID=158;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Celestial Defender', Name1_Lang_enGB='%s the Celestial Defender' WHERE ID=159;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s, Conqueror of Ulduar', Name1_Lang_enGB='%s, Conqueror of Ulduar' WHERE ID=160;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s, Champion of Ulduar', Name1_Lang_enGB='%s, Champion of Ulduar' WHERE ID=161;
UPDATE dbc_chartitles SET Name_Lang_enGB='Vanquisher %s', Name1_Lang_enGB='Vanquisher %s' WHERE ID=163;
UPDATE dbc_chartitles SET Name_Lang_enGB='Starcaller %s', Name1_Lang_enGB='Starcaller %s' WHERE ID=164;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Astral Walker', Name1_Lang_enGB='%s the Astral Walker' WHERE ID=165;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s, Herald of the Titans', Name1_Lang_enGB='%s, Herald of the Titans' WHERE ID=166;
UPDATE dbc_chartitles SET Name_Lang_enGB='Furious Gladiator %s', Name1_Lang_enGB='Furious Gladiator %s' WHERE ID=167;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Pilgrim', Name1_Lang_enGB='%s the Pilgrim' WHERE ID=168;
UPDATE dbc_chartitles SET Name_Lang_enGB='Relentless Gladiator %s', Name1_Lang_enGB='Relentless Gladiator %s' WHERE ID=169;
UPDATE dbc_chartitles SET Name_Lang_enGB='Grand Crusader %s', Name1_Lang_enGB='Grand Crusader %s' WHERE ID=170;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Argent Defender', Name1_Lang_enGB='%s the Argent Defender' WHERE ID=171;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Patient', Name1_Lang_enGB='%s the Patient' WHERE ID=172;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Light of Dawn', Name1_Lang_enGB='%s the Light of Dawn' WHERE ID=173;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s, Bane of the Fallen King', Name1_Lang_enGB='%s, Bane of the Fallen King' WHERE ID=174;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s the Kingslayer', Name1_Lang_enGB='%s the Kingslayer' WHERE ID=175;
UPDATE dbc_chartitles SET Name_Lang_enGB='%s of the Ashen Verdict', Name1_Lang_enGB='%s of the Ashen Verdict' WHERE ID=176;
UPDATE dbc_chartitles SET Name_Lang_enGB='Wrathful Gladiator %s', Name1_Lang_enGB='Wrathful Gladiator %s' WHERE ID=177;
