UPDATE dbc_chrraces SET Name_Lang_enGB='Human', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=1;
UPDATE dbc_chrraces SET Name_Lang_enGB='Orc', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=2;
UPDATE dbc_chrraces SET Name_Lang_enGB='Dwarf', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=3;
UPDATE dbc_chrraces SET Name_Lang_enGB='Night Elf', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=4;
UPDATE dbc_chrraces SET Name_Lang_enGB='Undead', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=5;
UPDATE dbc_chrraces SET Name_Lang_enGB='Tauren', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=6;
UPDATE dbc_chrraces SET Name_Lang_enGB='Gnome', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=7;
UPDATE dbc_chrraces SET Name_Lang_enGB='Troll', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=8;
UPDATE dbc_chrraces SET Name_Lang_enGB='Goblin', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=9;
UPDATE dbc_chrraces SET Name_Lang_enGB='Blood Elf', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=10;
UPDATE dbc_chrraces SET Name_Lang_enGB='Draenei', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=11;
UPDATE dbc_chrraces SET Name_Lang_enGB='Fel Orc', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=12;
UPDATE dbc_chrraces SET Name_Lang_enGB='Naga', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=13;
UPDATE dbc_chrraces SET Name_Lang_enGB='Broken', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=14;
UPDATE dbc_chrraces SET Name_Lang_enGB='Skeleton', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=15;
UPDATE dbc_chrraces SET Name_Lang_enGB='Vrykul', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=16;
UPDATE dbc_chrraces SET Name_Lang_enGB='Tuskarr', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=17;
UPDATE dbc_chrraces SET Name_Lang_enGB='Forest Troll', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=18;
UPDATE dbc_chrraces SET Name_Lang_enGB='Taunka', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=19;
UPDATE dbc_chrraces SET Name_Lang_enGB='Northrend Skeleton', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=20;
UPDATE dbc_chrraces SET Name_Lang_enGB='Ice Troll', Name_Female_Lang_enGB='', Name_Male_Lang_enGB='' WHERE ID=21;
