UPDATE dbc_creaturefamily SET Name_Lang_enGB='Wolf' WHERE ID=1;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Cat' WHERE ID=2;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Spider' WHERE ID=3;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Bear' WHERE ID=4;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Boar' WHERE ID=5;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Crocolisk' WHERE ID=6;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Carrion Bird' WHERE ID=7;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Crab' WHERE ID=8;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Gorilla' WHERE ID=9;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Raptor' WHERE ID=11;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Tallstrider' WHERE ID=12;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Felhunter' WHERE ID=15;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Voidwalker' WHERE ID=16;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Succubus' WHERE ID=17;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Doomguard' WHERE ID=19;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Scorpid' WHERE ID=20;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Turtle' WHERE ID=21;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Imp' WHERE ID=23;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Bat' WHERE ID=24;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Hyena' WHERE ID=25;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Bird of Prey' WHERE ID=26;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Wind Serpent' WHERE ID=27;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Remote Control' WHERE ID=28;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Felguard' WHERE ID=29;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Dragonhawk' WHERE ID=30;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Ravager' WHERE ID=31;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Warp Stalker' WHERE ID=32;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Sporebat' WHERE ID=33;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Nether Ray' WHERE ID=34;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Serpent' WHERE ID=35;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Moth' WHERE ID=37;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Chimaera' WHERE ID=38;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Devilsaur' WHERE ID=39;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Ghoul' WHERE ID=40;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Silithid' WHERE ID=41;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Worm' WHERE ID=42;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Rhino' WHERE ID=43;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Wasp' WHERE ID=44;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Core Hound' WHERE ID=45;
UPDATE dbc_creaturefamily SET Name_Lang_enGB='Spirit Beast' WHERE ID=46;
