UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Rethilgore' WHERE ID=464;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Razorclaw the Butcher' WHERE ID=465;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Baron Silverlaine' WHERE ID=466;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Commander Springvale' WHERE ID=467;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Odo the Blindwatcher' WHERE ID=468;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Fenrus the Devourer' WHERE ID=469;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Wolf Master Nandos' WHERE ID=470;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Archmage Arugal' WHERE ID=471;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Targorr the Dread' WHERE ID=536;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Kam Deepfury' WHERE ID=537;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hamhock' WHERE ID=538;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Dextren Ward' WHERE ID=540;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Bazil Thredd' WHERE ID=539;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Rhahk''zor' WHERE ID=161;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Sneed' WHERE ID=162;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Gilnid' WHERE ID=163;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mr. Smite' WHERE ID=164;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Cookie' WHERE ID=165;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Captain Greenskin' WHERE ID=166;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Edwin VanCleef' WHERE ID=167;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lady Anacondra' WHERE ID=585;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lord Cobrahn' WHERE ID=586;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Kresh' WHERE ID=587;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lord Pythas' WHERE ID=588;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Skum' WHERE ID=589;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lord Serpentis' WHERE ID=590;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Verdan the Everliving' WHERE ID=591;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mutanus the Devourer' WHERE ID=592;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Death Speaker Jargba' WHERE ID=440;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Roogug' WHERE ID=438;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Aggem Thorncurse' WHERE ID=439;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Overlord Ramtusk' WHERE ID=441;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Agathelos the Raging' WHERE ID=883;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Charlga Razorflank' WHERE ID=443;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ghamoo-ra' WHERE ID=219;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lady Sarevess' WHERE ID=220;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Gelihast' WHERE ID=221;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lorgus Jett' WHERE ID=222;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Old Serra''kis' WHERE ID=224;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Twilight Lord Kelris' WHERE ID=225;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Aku''mai' WHERE ID=226;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Revelosh' WHERE ID=547;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Lost Dwarves' WHERE ID=548;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ironaya' WHERE ID=549;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ancient Stone Keeper' WHERE ID=551;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Galgann Firehammer' WHERE ID=552;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Grimlok' WHERE ID=553;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Archaedas' WHERE ID=554;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Grubbis' WHERE ID=379;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Viscous Fallout' WHERE ID=378;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Electrocutioner 6000' WHERE ID=380;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Crowd Pummeler 9-60' WHERE ID=381;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mekgineer Thermaplugg' WHERE ID=382;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Atal''alarion' WHERE ID=485;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Jammal''an the Prophet' WHERE ID=488;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Dreamscythe' WHERE ID=486;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Weaver' WHERE ID=487;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Morphaz' WHERE ID=490;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hazzas' WHERE ID=491;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Avatar of Hakkar' WHERE ID=492;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Shade of Eranikus' WHERE ID=493;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Tuten''kash' WHERE ID=434;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mordresh Fire Eye' WHERE ID=435;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Glutton' WHERE ID=436;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Amnennar the Coldbringer' WHERE ID=437;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Interrogator Vishas' WHERE ID=444;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Bloodmage Thalnos' WHERE ID=445;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Houndmaster Loksey' WHERE ID=446;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Arcanist Doan' WHERE ID=447;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Herod' WHERE ID=448;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='High Inquisitor Fairbanks' WHERE ID=449;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='High Inquisitor Whitemane' WHERE ID=450;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hydromancer Velratha' WHERE ID=593;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ghaz''rilla' WHERE ID=594;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Antu''sul' WHERE ID=595;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Theka the Martyr' WHERE ID=596;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Witch Doctor Zum''rah' WHERE ID=597;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Nekrum Gutchewer' WHERE ID=598;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Shadowpriest Sezz''ziz' WHERE ID=599;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Chief Ukorz Sandscalp' WHERE ID=600;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Highlord Omokk' WHERE ID=267;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Shadow Hunter Vosh''gajin' WHERE ID=268;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='War Master Voone' WHERE ID=269;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mother Smolderweb' WHERE ID=270;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Urok Doomhowl' WHERE ID=271;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Quartermaster Zigris' WHERE ID=272;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Halycon' WHERE ID=274;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Gizrul the Slavener' WHERE ID=273;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Overlord Wyrmthalak' WHERE ID=275;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Pyroguard Emberseer' WHERE ID=276;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Solakar Flamewreath' WHERE ID=277;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Warchief Rend Blackhand' WHERE ID=278;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Beast' WHERE ID=279;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='General Drakkisath' WHERE ID=280;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='High Interrogator Gerstahn' WHERE ID=227;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lord Roccor' WHERE ID=228;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Houndmaster Grebmar' WHERE ID=229;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ring of Law' WHERE ID=230;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Pyromancer Loregrain' WHERE ID=231;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lord Incendius' WHERE ID=232;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Warder Stilgiss' WHERE ID=233;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Fineous Darkvire' WHERE ID=234;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Bael''Gar' WHERE ID=235;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='General Angerforge' WHERE ID=236;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Golem Lord Argelmach' WHERE ID=237;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hurley Blackbreath' WHERE ID=238;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Phalanx' WHERE ID=239;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ribbly Screwspigot' WHERE ID=240;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Plugger Spazzring' WHERE ID=241;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ambassador Flamelash' WHERE ID=242;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Seven' WHERE ID=243;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Magmus' WHERE ID=244;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Emperor Dagran Thaurissan' WHERE ID=245;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Onyxia' WHERE ID=707;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Onyxia' WHERE ID=708;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Chrono Lord Deja' WHERE ID=287;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Chrono Lord Deja' WHERE ID=288;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Temporus' WHERE ID=289;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Temporus' WHERE ID=290;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Aeonus' WHERE ID=291;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Aeonus' WHERE ID=292;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Kirtonos the Herald' WHERE ID=451;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Jandice Barov' WHERE ID=452;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Rattlegore' WHERE ID=453;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Marduk Blackpool' WHERE ID=454;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Vectus' WHERE ID=455;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ras Frostwhisper' WHERE ID=456;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Instructor Malicia' WHERE ID=457;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Doctor Theolen Krastinov' WHERE ID=458;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lorekeeper Polkelt' WHERE ID=459;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Ravenian' WHERE ID=460;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lord Alexei Barov' WHERE ID=461;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lady Illucia Barov' WHERE ID=462;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Darkmaster Gandling' WHERE ID=463;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='High Priestess Jeklik' WHERE ID=785;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='High Priest Venoxis' WHERE ID=784;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='High Priestess Mar''li' WHERE ID=786;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Bloodlord Mandokir' WHERE ID=787;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Edge of Madness' WHERE ID=788;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='High Priest Thekal' WHERE ID=789;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Gahz''ranka' WHERE ID=790;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='High Priestess Arlokk' WHERE ID=791;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Jin''do the Hexxer' WHERE ID=792;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hakkar' WHERE ID=793;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hearthsinger Forresten' WHERE ID=473;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Timmy the Cruel' WHERE ID=474;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Cannon Master Willey' WHERE ID=475;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Malor the Zealous' WHERE ID=476;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Archivist Galford' WHERE ID=477;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Balnazzar' WHERE ID=478;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Unforgiven' WHERE ID=472;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Baroness Anastari' WHERE ID=479;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Nerub''enkan' WHERE ID=480;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Maleki the Pallid' WHERE ID=481;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Magistrate Barthilas' WHERE ID=482;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ramnstein the Gorger' WHERE ID=483;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Baron Rivendare' WHERE ID=484;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Noxxion' WHERE ID=422;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Razorlash' WHERE ID=423;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lord Vyletongue' WHERE ID=424;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Celebras the Cursed' WHERE ID=425;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Landslide' WHERE ID=426;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Tinkerer Gizlock' WHERE ID=427;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Rotgrip' WHERE ID=428;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Princess Theradras' WHERE ID=429;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Oggleflint' WHERE ID=430;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Jergosh the Invoker' WHERE ID=432;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Bazzalan' WHERE ID=433;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Taragaman the Hungerer' WHERE ID=431;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lucifron' WHERE ID=663;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Magmadar' WHERE ID=664;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Gehennas' WHERE ID=665;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Garr' WHERE ID=666;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Shazzrah' WHERE ID=667;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Baron Geddon' WHERE ID=668;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Sulfuron Harbinger' WHERE ID=669;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Golemagg the Incinerator' WHERE ID=670;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Majordomo Executus' WHERE ID=671;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ragnaros' WHERE ID=672;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Zevrim Thornhoof' WHERE ID=343;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hydrospawn' WHERE ID=344;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lethtendris' WHERE ID=345;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Alzzin the Wildshaper' WHERE ID=346;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Tendris Warpwood' WHERE ID=350;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Illyanna Ravenoak' WHERE ID=347;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Magister Kalendris' WHERE ID=348;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Immol''thar' WHERE ID=349;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Prince Tortheldrin' WHERE ID=361;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Guard Mol''dar' WHERE ID=362;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Stomper Kreeg' WHERE ID=363;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Guard Fengus' WHERE ID=364;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Guard Slip''kik' WHERE ID=365;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Captain Kromcrush' WHERE ID=366;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Cho''Rush the Observer' WHERE ID=367;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='King Gordok' WHERE ID=368;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Razorgore the Untamed' WHERE ID=610;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Vaelastrasz the Corrupt' WHERE ID=611;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Broodlord Lashlayer' WHERE ID=612;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Firemaw' WHERE ID=613;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ebonroc' WHERE ID=614;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Flamegor' WHERE ID=615;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Chromaggus' WHERE ID=616;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Nefarian' WHERE ID=617;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Kurinnaxx' WHERE ID=718;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='General Rajaxx' WHERE ID=719;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Moam' WHERE ID=720;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Buru the Gorger' WHERE ID=721;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ayamiss the Hunter' WHERE ID=722;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ossirian the Unscarred' WHERE ID=723;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Prophet Skeram' WHERE ID=709;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Silithid Royalty' WHERE ID=710;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Battleguard Sartura' WHERE ID=711;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Fankriss the Unyielding' WHERE ID=712;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Viscidus' WHERE ID=713;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Princess Huhuran' WHERE ID=714;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Twin Emperors' WHERE ID=715;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ouro' WHERE ID=716;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='C''thun' WHERE ID=717;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Attumen the Huntsman' WHERE ID=652;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Moroes' WHERE ID=653;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Maiden of the Virtue' WHERE ID=654;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Opera Event' WHERE ID=655;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Curator' WHERE ID=656;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Terestian Illhoof' WHERE ID=657;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Shade of Aran' WHERE ID=658;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Netherspite' WHERE ID=659;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Chess Event' WHERE ID=660;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Prince Malchezaar' WHERE ID=661;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Nightbane' WHERE ID=662;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Anub''Rekhan' WHERE ID=673;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Anub''Rekhan' WHERE ID=674;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Grand Widow Faerlina' WHERE ID=677;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Grand Widow Faerlina' WHERE ID=678;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Maexxna' WHERE ID=679;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Maexxna' WHERE ID=680;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Noth the Plaguebringer' WHERE ID=681;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Noth the Plaguebringer' WHERE ID=682;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Heigan the Unclean' WHERE ID=683;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Heigan the Unclean ' WHERE ID=684;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Loatheb' WHERE ID=685;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Loatheb' WHERE ID=686;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Instructor Razuvious' WHERE ID=687;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Instructor Razuvious' WHERE ID=689;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Gothik the Harvester' WHERE ID=690;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Gothik the Harvester' WHERE ID=691;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Four Horsemen' WHERE ID=692;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Four Horsemen' WHERE ID=693;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Patchwerk' WHERE ID=694;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Patchwerk ' WHERE ID=695;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Grobbulus' WHERE ID=696;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Grobbulus' WHERE ID=697;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Gluth' WHERE ID=698;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Gluth' WHERE ID=699;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Thaddius' WHERE ID=700;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Thaddius' WHERE ID=701;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Sapphiron' WHERE ID=702;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Sapphiron' WHERE ID=703;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Kel''Thuzad' WHERE ID=704;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Kel''Thuzad' WHERE ID=706;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Rage Winterchill' WHERE ID=618;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Anetheron' WHERE ID=619;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Kaz''rogal' WHERE ID=620;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Azgalor' WHERE ID=621;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Archimonde' WHERE ID=622;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Grand Warlock Nethekurse' WHERE ID=407;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Grand Warlock Nethekurse' WHERE ID=408;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Warbringer O''mrogg' WHERE ID=410;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Blood Guard Porung' WHERE ID=409;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Warchief Kargath Bladefist' WHERE ID=412;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Warbringer O''mrogg' WHERE ID=411;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Warchief Kargath Bladefist' WHERE ID=413;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Maker' WHERE ID=401;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Maker' WHERE ID=402;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Broggok' WHERE ID=403;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Broggok' WHERE ID=404;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Keli''dan the Breaker' WHERE ID=405;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Keli''dan the Breaker' WHERE ID=406;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Watchkeeper Gargolmar' WHERE ID=392;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Watchkeeper Gargolmar' WHERE ID=393;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Omor the Unscarred' WHERE ID=394;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Omor the Unscarred' WHERE ID=395;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Vazruden the Herald' WHERE ID=396;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Vazruden the Herald' WHERE ID=397;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Magtheridon' WHERE ID=651;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hydromancer Thespia' WHERE ID=314;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hydromancer Thespia' WHERE ID=315;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mekgineer Steamrigger' WHERE ID=316;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mekgineer Steamrigger' WHERE ID=317;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Warlord Kalithresh' WHERE ID=318;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Warlord Kalithresh' WHERE ID=319;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hungarfen' WHERE ID=320;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hungarfen' WHERE ID=321;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ghaz''an' WHERE ID=322;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ghaz''an' WHERE ID=323;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Swamplord Musel''ek' WHERE ID=329;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Swamplord Musel''ek' WHERE ID=330;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Black Stalker' WHERE ID=331;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Black Stalker' WHERE ID=332;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mennu the Betrayer' WHERE ID=301;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mennu the Betrayer' WHERE ID=304;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Rokmar the Crackler' WHERE ID=302;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Rokmar the Crackler' WHERE ID=305;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Quagmirran' WHERE ID=303;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Quagmirran' WHERE ID=306;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hydross the Unstable' WHERE ID=623;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Lurker Below' WHERE ID=624;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Leotheras the Blind' WHERE ID=625;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Fathom-Lord Karathress' WHERE ID=626;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Morogrim Tidewalker' WHERE ID=627;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lady Vashj' WHERE ID=628;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Al''ar' WHERE ID=730;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Void Reaver' WHERE ID=731;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='High Astromancer Solarian' WHERE ID=732;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Kael''thas Sunstrider' WHERE ID=733;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Zereketh the Unbound' WHERE ID=494;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Zereketh the Unbound' WHERE ID=495;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Dalliah the Doomsayer' WHERE ID=496;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Dalliah the Doomsayer' WHERE ID=497;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Wrath-Scryer Soccothrates' WHERE ID=498;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Wrath-Scryer Soccothrates' WHERE ID=499;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Harbinger Skyriss' WHERE ID=500;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Harbinger Skyriss' WHERE ID=501;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Commander Sarannis' WHERE ID=502;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Commander Sarannis' WHERE ID=504;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='High Botanist Freywinn' WHERE ID=505;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='High Botanist Freywinn' WHERE ID=506;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Thorngrin the Tender' WHERE ID=507;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Thorngrin the Tender' WHERE ID=508;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Laj' WHERE ID=509;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Laj' WHERE ID=510;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Warp Splinter' WHERE ID=511;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Warp Splinter' WHERE ID=512;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mechano-Lord Capacitus' WHERE ID=513;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mechano-Lord Capacitus' WHERE ID=514;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Nethermancer Sepethrea' WHERE ID=515;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Nethermancer Sepethrea' WHERE ID=516;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Pathaleon the Calculator' WHERE ID=517;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Pathaleon the Calculator' WHERE ID=518;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ambassador Hellmaw' WHERE ID=208;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ambassador Hellmaw' WHERE ID=255;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Blackheart the Inciter' WHERE ID=209;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Blackheart the Inciter' WHERE ID=256;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Grandmaster Vorpil' WHERE ID=210;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Grandmaster Vorpil' WHERE ID=257;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Murmur' WHERE ID=211;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Murmur' WHERE ID=258;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Darkweaver Syth' WHERE ID=206;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Darkweaver Syth' WHERE ID=252;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Talon King Ikiss' WHERE ID=207;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Anzu' WHERE ID=253;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Talon King Ikiss' WHERE ID=254;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Pandemonius' WHERE ID=203;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Pandemonius' WHERE ID=248;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Tavarok' WHERE ID=204;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Tavarok' WHERE ID=249;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Yor' WHERE ID=250;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Nexus-Prince Shaffar' WHERE ID=205;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Nexus-Prince Shaffar' WHERE ID=251;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Shirrak the Dead Watcher' WHERE ID=201;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Shirrak the Dead Watcher' WHERE ID=246;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Exarch Maladaar' WHERE ID=202;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Exarch Maladaar' WHERE ID=247;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lieutenant Drake' WHERE ID=286;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lieutenant Drake' WHERE ID=285;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Captain Skarloc' WHERE ID=283;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Captain Skarloc' WHERE ID=284;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Epoch Hunter' WHERE ID=281;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Epoch Hunter' WHERE ID=282;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='High Warlord Naj''entus' WHERE ID=601;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Supremus' WHERE ID=602;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Shade of Akama' WHERE ID=603;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Teron Gorefiend' WHERE ID=604;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Gurtogg Bloodboil' WHERE ID=605;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Reliquary of Souls' WHERE ID=606;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mother Shahraz' WHERE ID=607;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Illidari Council' WHERE ID=608;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Illidan Stormrage' WHERE ID=609;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='High King Maulgar' WHERE ID=649;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Gruul the Dragonkiller' WHERE ID=650;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Akil''zon' WHERE ID=778;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Nalorakk' WHERE ID=779;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Jan''alai' WHERE ID=780;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Halazzi' WHERE ID=781;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hex Lord Malacrass' WHERE ID=782;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Zul''jin' WHERE ID=783;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Prince Keleseth' WHERE ID=571;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Prince Keleseth' WHERE ID=572;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Skarvold & Dalronn' WHERE ID=573;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Skarvold & Dalronn' WHERE ID=574;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ingvar the Plunderer' WHERE ID=575;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ingvar the Plunderer' WHERE ID=576;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Svala Sorrowgrave' WHERE ID=577;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Svala Sorrowgrave' WHERE ID=578;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Gortok Palehoof' WHERE ID=579;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Gortok Palehoof' WHERE ID=580;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Skadi the Ruthless' WHERE ID=581;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Skadi the Ruthless' WHERE ID=582;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='King Ymiron' WHERE ID=583;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='King Ymiron' WHERE ID=584;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Frozen Commander' WHERE ID=519;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Grand Magus Telestra' WHERE ID=520;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Grand Magus Telestra' WHERE ID=521;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Anomalus' WHERE ID=522;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Anomalus' WHERE ID=523;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ormorok the Tree-Shaper' WHERE ID=524;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ormrok the Tree-Shaper' WHERE ID=525;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Keristrasza' WHERE ID=526;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Keristrasza' WHERE ID=527;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Drakos the Interrogator' WHERE ID=528;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Drakos the Interrogator' WHERE ID=529;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Varos Cloudstrider' WHERE ID=530;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Varos Cloudstrider' WHERE ID=531;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mage-Lord Urom' WHERE ID=532;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mage-Lord Urom' WHERE ID=533;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ley-Guardian Eregos' WHERE ID=534;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ley-Guardian Eregos' WHERE ID=535;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Kalecgos' WHERE ID=724;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Brutallus' WHERE ID=725;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Felmyst' WHERE ID=726;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Eredar Twins' WHERE ID=727;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='M''uru' WHERE ID=728;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Kil''jaeden' WHERE ID=729;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Selin Fireheart' WHERE ID=414;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Selin Fireheart' WHERE ID=415;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Vexallus' WHERE ID=416;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Vexallus' WHERE ID=417;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Priestess Delrissa' WHERE ID=418;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Priestess Delrissa' WHERE ID=419;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Kael''thas Sunstrider' WHERE ID=420;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Kael''thas Sunstrider' WHERE ID=421;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Meathook' WHERE ID=293;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Meathook' WHERE ID=297;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Salram the Fleshcrafter' WHERE ID=294;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Salram the Fleshcrafter' WHERE ID=298;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Chrono-Lord Epoch' WHERE ID=295;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Chrono-Lord Epoch' WHERE ID=299;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mal''ganis' WHERE ID=296;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mal''ganis' WHERE ID=300;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Krystallus' WHERE ID=563;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Krystallus' WHERE ID=564;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Maiden of Grief' WHERE ID=565;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Maiden of Grief' WHERE ID=566;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Tribunal of Ages' WHERE ID=567;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Tribunal of Ages' WHERE ID=568;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Sjonnir the Ironshaper' WHERE ID=569;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Sjonnir the Ironshaper' WHERE ID=570;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Trollgore' WHERE ID=369;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Trollgore' WHERE ID=370;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Novos the Summoner' WHERE ID=371;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Novos the Summoner' WHERE ID=372;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='King Dred' WHERE ID=373;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='King Dred' WHERE ID=374;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Prophet Tharon''ja' WHERE ID=375;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Prophet Tharon''ja' WHERE ID=376;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Krik''thir the Gatewatcher' WHERE ID=216;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Krik''thir the Gatewatcher' WHERE ID=264;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hadronox' WHERE ID=217;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hadronox' WHERE ID=265;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Anub''arak' WHERE ID=218;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Anub''arak' WHERE ID=266;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='General Bjarngrim' WHERE ID=555;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='General Bjarngrim' WHERE ID=556;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Volkhan' WHERE ID=557;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Volkhan' WHERE ID=558;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ionar' WHERE ID=559;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ionar' WHERE ID=560;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Loken' WHERE ID=561;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Loken' WHERE ID=562;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Flame Leviathan' WHERE ID=744;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Flame Leviathan' WHERE ID=758;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ignis the Furnace Master' WHERE ID=745;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Ignis the Furnace Master' WHERE ID=759;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Razorscale' WHERE ID=746;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='XT-002 Deconstructor' WHERE ID=747;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Iron Council' WHERE ID=748;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Razorscale' WHERE ID=760;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Kologarn' WHERE ID=749;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='XT-002 Deconstructor' WHERE ID=761;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Auriaya' WHERE ID=750;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Iron Council' WHERE ID=762;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hodir' WHERE ID=751;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Kologarn' WHERE ID=763;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Thorim' WHERE ID=752;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Auriaya' WHERE ID=764;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Freya' WHERE ID=753;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Hodir' WHERE ID=765;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mimiron' WHERE ID=754;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Thorim' WHERE ID=766;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='General Vezax' WHERE ID=755;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Freya' WHERE ID=767;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Yogg-Saron' WHERE ID=756;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Mimiron' WHERE ID=768;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Algalon the Observer' WHERE ID=757;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='General Vezax' WHERE ID=769;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Yogg-Saron' WHERE ID=770;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Algalon the Observer' WHERE ID=771;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Slad''ran' WHERE ID=383;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Slad''ran' WHERE ID=384;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Drakkari Colossus' WHERE ID=385;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Drakkari Colossus' WHERE ID=386;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Moorabi' WHERE ID=387;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Moorabi' WHERE ID=388;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Gal''darah' WHERE ID=390;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Eck the Ferocious' WHERE ID=389;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Gal''darah' WHERE ID=391;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='First Prisoner' WHERE ID=541;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='First Prisoner' WHERE ID=542;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Second Prisoner' WHERE ID=543;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Second Prisoner' WHERE ID=544;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Cyanigosa' WHERE ID=545;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Cyanigosa' WHERE ID=546;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Vesperon' WHERE ID=740;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Tenebron' WHERE ID=736;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Vesperon' WHERE ID=741;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Tenebron' WHERE ID=737;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Shadron' WHERE ID=738;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Shadron' WHERE ID=739;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Sartharion' WHERE ID=742;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Sartharion' WHERE ID=743;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Malygos' WHERE ID=734;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Malygos' WHERE ID=735;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Elder Nadox' WHERE ID=212;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Elder Nadox' WHERE ID=259;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Prince Taldaram' WHERE ID=213;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Prince Taldaram' WHERE ID=260;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Jedoga Shadowseeker' WHERE ID=214;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Jedoga Shadowseeker' WHERE ID=261;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Herald Volazj' WHERE ID=215;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Amanitar' WHERE ID=262;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Herald Volazj' WHERE ID=263;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Archavon the Stone Watcher' WHERE ID=772;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Archavon the Stone Watcher' WHERE ID=773;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Emalon the Storm Watcher' WHERE ID=774;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Emalon the Storm Watcher' WHERE ID=775;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Koralon the Flame Watcher' WHERE ID=776;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Koralon the Flame Watcher' WHERE ID=777;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Toravon the Ice Watcher' WHERE ID=885;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Toravon the Ice Watcher' WHERE ID=886;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lord Marrowgar' WHERE ID=845;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lord Marrowgar' WHERE ID=857;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lady Deathwhisper' WHERE ID=846;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lady Deathwhisper' WHERE ID=858;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Icecrown Gunship Battle' WHERE ID=847;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Icecrown Gunship Battle' WHERE ID=859;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Deathbringer Saurfang' WHERE ID=848;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Deathbringer Saurfang' WHERE ID=860;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Festergut' WHERE ID=849;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Festergut' WHERE ID=861;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Rotface' WHERE ID=850;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Rotface' WHERE ID=862;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Professor Putricide' WHERE ID=851;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Professor Putricide' WHERE ID=863;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Blood Council' WHERE ID=852;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Blood Council' WHERE ID=864;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Queen Lana''thel' WHERE ID=853;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Queen Lana''thel' WHERE ID=865;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Valithria Dreamwalker' WHERE ID=854;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Valithria Dreamwalker' WHERE ID=866;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Sindragosa' WHERE ID=855;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Sindragosa' WHERE ID=867;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Lich King' WHERE ID=856;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Lich King' WHERE ID=868;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Bronjahm' WHERE ID=829;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Bronjahm ' WHERE ID=830;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Devourer of Souls' WHERE ID=831;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Devourer of Souls' WHERE ID=832;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Northrend Beasts' WHERE ID=629;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Northrend Beasts' WHERE ID=630;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lord Jaraxxus' WHERE ID=633;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Northrend Beasts' WHERE ID=631;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lord Jaraxxus' WHERE ID=634;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Faction Champions' WHERE ID=637;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Northrend Beasts' WHERE ID=632;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lord Jaraxxus' WHERE ID=635;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Faction Champions' WHERE ID=638;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Val''kyr Twins' WHERE ID=641;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Lord Jaraxxus' WHERE ID=636;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Faction Champions' WHERE ID=639;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Val''kyr Twins' WHERE ID=642;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Anub''arak' WHERE ID=645;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Faction Champions' WHERE ID=640;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Val''kyr Twins' WHERE ID=643;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Anub''arak' WHERE ID=646;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Val''kyr Twins' WHERE ID=644;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Anub''arak' WHERE ID=647;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Anub''arak' WHERE ID=648;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Grand Champions' WHERE ID=334;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Grand Champions' WHERE ID=336;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Argent Champion' WHERE ID=338;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Argent Champion' WHERE ID=339;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Black Knight' WHERE ID=340;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='The Black Knight' WHERE ID=341;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Forgemaster Garfrost' WHERE ID=833;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Forgemaster Garfrost' WHERE ID=834;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Krick' WHERE ID=835;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Krick' WHERE ID=836;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Overlrod Tyrannus' WHERE ID=837;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Overlrod Tyrannus' WHERE ID=838;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Falric' WHERE ID=842;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Falric' WHERE ID=841;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Marwyn' WHERE ID=840;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Marwyn' WHERE ID=839;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Escaped from Arthas' WHERE ID=843;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Escaped from Arthas' WHERE ID=844;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Baltharus the Warborn' WHERE ID=889;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Baltharus the Warborn' WHERE ID=890;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Saviana Ragefire' WHERE ID=891;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Saviana Ragefire' WHERE ID=892;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='General Zarithrian' WHERE ID=893;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='General Zarithrian' WHERE ID=894;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Halion' WHERE ID=887;
UPDATE dbc_dungeonencounter SET Name_Lang_enGB='Halion' WHERE ID=888;
