UPDATE dbc_faction SET Name_Lang_enGB='PLAYER, Human', Description_Lang_enGB='' WHERE ID=1;
UPDATE dbc_faction SET Name_Lang_enGB='PLAYER, Orc', Description_Lang_enGB='' WHERE ID=2;
UPDATE dbc_faction SET Name_Lang_enGB='PLAYER, Dwarf', Description_Lang_enGB='' WHERE ID=3;
UPDATE dbc_faction SET Name_Lang_enGB='PLAYER, Night Elf', Description_Lang_enGB='' WHERE ID=4;
UPDATE dbc_faction SET Name_Lang_enGB='PLAYER, Undead', Description_Lang_enGB='' WHERE ID=5;
UPDATE dbc_faction SET Name_Lang_enGB='PLAYER, Tauren ', Description_Lang_enGB='' WHERE ID=6;
UPDATE dbc_faction SET Name_Lang_enGB='Creature', Description_Lang_enGB='' WHERE ID=7;
UPDATE dbc_faction SET Name_Lang_enGB='PLAYER, Gnome', Description_Lang_enGB='' WHERE ID=8;
UPDATE dbc_faction SET Name_Lang_enGB='PLAYER, Troll', Description_Lang_enGB='' WHERE ID=9;
UPDATE dbc_faction SET Name_Lang_enGB='Monster', Description_Lang_enGB='' WHERE ID=14;
UPDATE dbc_faction SET Name_Lang_enGB='Defias Brotherhood', Description_Lang_enGB='' WHERE ID=15;
UPDATE dbc_faction SET Name_Lang_enGB='Gnoll - Riverpaw', Description_Lang_enGB='' WHERE ID=16;
UPDATE dbc_faction SET Name_Lang_enGB='Gnoll - Redridge', Description_Lang_enGB='' WHERE ID=17;
UPDATE dbc_faction SET Name_Lang_enGB='Gnoll - Shadowhide', Description_Lang_enGB='' WHERE ID=18;
UPDATE dbc_faction SET Name_Lang_enGB='Murloc', Description_Lang_enGB='' WHERE ID=19;
UPDATE dbc_faction SET Name_Lang_enGB='Undead, Scourge', Description_Lang_enGB='' WHERE ID=20;
UPDATE dbc_faction SET Name_Lang_enGB='Booty Bay', Description_Lang_enGB='This booming coastal city is run by Baron Revilgaz of the Blackwater Raiders.  Mortal enemies of the Bloodsail Buccaneers and part of the Steamwheedle Cartel.' WHERE ID=21;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Spider', Description_Lang_enGB='' WHERE ID=22;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Boar', Description_Lang_enGB='' WHERE ID=23;
UPDATE dbc_faction SET Name_Lang_enGB='Worgen', Description_Lang_enGB='' WHERE ID=24;
UPDATE dbc_faction SET Name_Lang_enGB='Kobold', Description_Lang_enGB='' WHERE ID=25;
UPDATE dbc_faction SET Name_Lang_enGB='Troll, Bloodscalp', Description_Lang_enGB='' WHERE ID=26;
UPDATE dbc_faction SET Name_Lang_enGB='Troll, Skullsplitter', Description_Lang_enGB='' WHERE ID=27;
UPDATE dbc_faction SET Name_Lang_enGB='Prey', Description_Lang_enGB='' WHERE ID=28;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Wolf', Description_Lang_enGB='' WHERE ID=29;
UPDATE dbc_faction SET Name_Lang_enGB='Defias Brotherhood Traitor', Description_Lang_enGB='' WHERE ID=30;
UPDATE dbc_faction SET Name_Lang_enGB='Friendly', Description_Lang_enGB='' WHERE ID=31;
UPDATE dbc_faction SET Name_Lang_enGB='Trogg', Description_Lang_enGB='' WHERE ID=32;
UPDATE dbc_faction SET Name_Lang_enGB='Troll, Frostmane', Description_Lang_enGB='' WHERE ID=33;
UPDATE dbc_faction SET Name_Lang_enGB='Orc, Blackrock', Description_Lang_enGB='' WHERE ID=34;
UPDATE dbc_faction SET Name_Lang_enGB='Villian', Description_Lang_enGB='' WHERE ID=35;
UPDATE dbc_faction SET Name_Lang_enGB='Victim', Description_Lang_enGB='' WHERE ID=36;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Bear', Description_Lang_enGB='' WHERE ID=37;
UPDATE dbc_faction SET Name_Lang_enGB='Ogre', Description_Lang_enGB='' WHERE ID=38;
UPDATE dbc_faction SET Name_Lang_enGB='Kurzen''s Mercenaries', Description_Lang_enGB='' WHERE ID=39;
UPDATE dbc_faction SET Name_Lang_enGB='Escortee', Description_Lang_enGB='' WHERE ID=40;
UPDATE dbc_faction SET Name_Lang_enGB='Venture Company', Description_Lang_enGB='' WHERE ID=41;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Raptor', Description_Lang_enGB='' WHERE ID=42;
UPDATE dbc_faction SET Name_Lang_enGB='Basilisk', Description_Lang_enGB='' WHERE ID=43;
UPDATE dbc_faction SET Name_Lang_enGB='Dragonflight, Green', Description_Lang_enGB='' WHERE ID=44;
UPDATE dbc_faction SET Name_Lang_enGB='Lost Ones', Description_Lang_enGB='' WHERE ID=45;
UPDATE dbc_faction SET Name_Lang_enGB=' Blacksmithing - Armorsmithing', Description_Lang_enGB='' WHERE ID=46;
UPDATE dbc_faction SET Name_Lang_enGB='Ironforge', Description_Lang_enGB='This Alliance capital is the pride of the Dun Morogh dwarves.  Home to King Magni.' WHERE ID=47;
UPDATE dbc_faction SET Name_Lang_enGB='Dark Iron Dwarves', Description_Lang_enGB='' WHERE ID=48;
UPDATE dbc_faction SET Name_Lang_enGB='Human, Night Watch', Description_Lang_enGB='' WHERE ID=49;
UPDATE dbc_faction SET Name_Lang_enGB='Dragonflight, Red', Description_Lang_enGB='' WHERE ID=50;
UPDATE dbc_faction SET Name_Lang_enGB='Gnoll - Mosshide', Description_Lang_enGB='' WHERE ID=51;
UPDATE dbc_faction SET Name_Lang_enGB='Orc, Dragonmaw', Description_Lang_enGB='' WHERE ID=52;
UPDATE dbc_faction SET Name_Lang_enGB='Gnome - Leper', Description_Lang_enGB='' WHERE ID=53;
UPDATE dbc_faction SET Name_Lang_enGB='Gnomeregan Exiles', Description_Lang_enGB='The former denizens of Gnomeregan, now living in exile in Ironforge and in league with the Alliance.' WHERE ID=54;
UPDATE dbc_faction SET Name_Lang_enGB='Leopard', Description_Lang_enGB='' WHERE ID=55;
UPDATE dbc_faction SET Name_Lang_enGB='Scarlet Crusade', Description_Lang_enGB='' WHERE ID=56;
UPDATE dbc_faction SET Name_Lang_enGB='Gnoll - Rothide', Description_Lang_enGB='' WHERE ID=57;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Gorilla', Description_Lang_enGB='' WHERE ID=58;
UPDATE dbc_faction SET Name_Lang_enGB='Thorium Brotherhood', Description_Lang_enGB='The dwarves of the Thorium Brotherhood epitomize excellence in craftsmanship and are bent on unlocking the secrets of Blackrock Mountain.' WHERE ID=59;
UPDATE dbc_faction SET Name_Lang_enGB='Naga', Description_Lang_enGB='' WHERE ID=60;
UPDATE dbc_faction SET Name_Lang_enGB='Dalaran', Description_Lang_enGB='' WHERE ID=61;
UPDATE dbc_faction SET Name_Lang_enGB='Forlorn Spirit', Description_Lang_enGB='' WHERE ID=62;
UPDATE dbc_faction SET Name_Lang_enGB='Darkhowl', Description_Lang_enGB='' WHERE ID=63;
UPDATE dbc_faction SET Name_Lang_enGB='Grell', Description_Lang_enGB='' WHERE ID=64;
UPDATE dbc_faction SET Name_Lang_enGB='Furbolg', Description_Lang_enGB='' WHERE ID=65;
UPDATE dbc_faction SET Name_Lang_enGB='Horde Generic', Description_Lang_enGB='' WHERE ID=66;
UPDATE dbc_faction SET Name_Lang_enGB='Horde', Description_Lang_enGB='' WHERE ID=67;
UPDATE dbc_faction SET Name_Lang_enGB='Undercity', Description_Lang_enGB='Led by Sylvanas Windrunner, the Forsaken have joined a tenuous alliance with the Horde and established this capital in the vast depths under the Ruins of Lordaeron.' WHERE ID=68;
UPDATE dbc_faction SET Name_Lang_enGB='Darnassus', Description_Lang_enGB='This Alliance capital is populated by Night Elves and is located in the Island of Teldrassil.  Ruled by the Priestess of the Moon, Tyrande Whisperwind.' WHERE ID=69;
UPDATE dbc_faction SET Name_Lang_enGB='Syndicate', Description_Lang_enGB='A primarily human criminal organization that operates mostly out of the Alterac Mountains and Hillsbrad Foothills.' WHERE ID=70;
UPDATE dbc_faction SET Name_Lang_enGB='Hillsbrad Militia', Description_Lang_enGB='' WHERE ID=71;
UPDATE dbc_faction SET Name_Lang_enGB='Stormwind', Description_Lang_enGB='One of the last bastions of human power, this Alliance capital is ruled by the prodigal king, Varian Wrynn.' WHERE ID=72;
UPDATE dbc_faction SET Name_Lang_enGB='Demon', Description_Lang_enGB='' WHERE ID=73;
UPDATE dbc_faction SET Name_Lang_enGB='Elemental', Description_Lang_enGB='' WHERE ID=74;
UPDATE dbc_faction SET Name_Lang_enGB='Spirit', Description_Lang_enGB='' WHERE ID=75;
UPDATE dbc_faction SET Name_Lang_enGB='Orgrimmar', Description_Lang_enGB='Founded by Thrall, this Horde capital city is home to many of the proud orc clans of Durotar.' WHERE ID=76;
UPDATE dbc_faction SET Name_Lang_enGB='Treasure', Description_Lang_enGB='' WHERE ID=77;
UPDATE dbc_faction SET Name_Lang_enGB='Gnoll - Mudsnout', Description_Lang_enGB='' WHERE ID=78;
UPDATE dbc_faction SET Name_Lang_enGB='HIllsbrad, Southshore Mayor', Description_Lang_enGB='' WHERE ID=79;
UPDATE dbc_faction SET Name_Lang_enGB='Dragonflight, Black', Description_Lang_enGB='' WHERE ID=80;
UPDATE dbc_faction SET Name_Lang_enGB='Thunder Bluff', Description_Lang_enGB='Cairne Bloodhoof leads his people, the proud Tauren, from this mighty Horde capital.' WHERE ID=81;
UPDATE dbc_faction SET Name_Lang_enGB='Troll, Witherbark', Description_Lang_enGB='' WHERE ID=82;
UPDATE dbc_faction SET Name_Lang_enGB=' Leatherworking - Elemental', Description_Lang_enGB='' WHERE ID=83;
UPDATE dbc_faction SET Name_Lang_enGB='Quilboar, Razormane', Description_Lang_enGB='' WHERE ID=84;
UPDATE dbc_faction SET Name_Lang_enGB='Quilboar, Bristleback', Description_Lang_enGB='' WHERE ID=85;
UPDATE dbc_faction SET Name_Lang_enGB=' Leatherworking - Dragonscale', Description_Lang_enGB='' WHERE ID=86;
UPDATE dbc_faction SET Name_Lang_enGB='Bloodsail Buccaneers', Description_Lang_enGB='These bloodthirsty corsairs are the bane of many a merchant in the high seas.  Sworn enemies of Booty Bay.' WHERE ID=87;
UPDATE dbc_faction SET Name_Lang_enGB='Blackfathom', Description_Lang_enGB='' WHERE ID=88;
UPDATE dbc_faction SET Name_Lang_enGB='Makrura', Description_Lang_enGB='' WHERE ID=89;
UPDATE dbc_faction SET Name_Lang_enGB='Centaur, Kolkar', Description_Lang_enGB='' WHERE ID=90;
UPDATE dbc_faction SET Name_Lang_enGB='Centaur, Galak', Description_Lang_enGB='' WHERE ID=91;
UPDATE dbc_faction SET Name_Lang_enGB='Gelkis Clan Centaur', Description_Lang_enGB='These centaur have made their home in the southern region of Desolace.  Mortal enemies of the Magram Centaur.' WHERE ID=92;
UPDATE dbc_faction SET Name_Lang_enGB='Magram Clan Centaur', Description_Lang_enGB='These centaur have made their home in the eastern region of Desolace.  Mortal enemies of the Gelkis Centaur.' WHERE ID=93;
UPDATE dbc_faction SET Name_Lang_enGB='Maraudine', Description_Lang_enGB='' WHERE ID=94;
UPDATE dbc_faction SET Name_Lang_enGB='Theramore', Description_Lang_enGB='' WHERE ID=108;
UPDATE dbc_faction SET Name_Lang_enGB='Quilboar, Razorfen', Description_Lang_enGB='' WHERE ID=109;
UPDATE dbc_faction SET Name_Lang_enGB='Quilboar, Razormane 2', Description_Lang_enGB='' WHERE ID=110;
UPDATE dbc_faction SET Name_Lang_enGB='Quilboar, Deathshead', Description_Lang_enGB='' WHERE ID=111;
UPDATE dbc_faction SET Name_Lang_enGB='Enemy', Description_Lang_enGB='' WHERE ID=128;
UPDATE dbc_faction SET Name_Lang_enGB='Ambient', Description_Lang_enGB='' WHERE ID=148;
UPDATE dbc_faction SET Name_Lang_enGB='Nethergarde Caravan', Description_Lang_enGB='' WHERE ID=168;
UPDATE dbc_faction SET Name_Lang_enGB='Steamwheedle Cartel', Description_Lang_enGB='' WHERE ID=169;
UPDATE dbc_faction SET Name_Lang_enGB='Alliance Generic', Description_Lang_enGB='' WHERE ID=189;
UPDATE dbc_faction SET Name_Lang_enGB='Nethergarde', Description_Lang_enGB='' WHERE ID=209;
UPDATE dbc_faction SET Name_Lang_enGB='Wailing Caverns', Description_Lang_enGB='' WHERE ID=229;
UPDATE dbc_faction SET Name_Lang_enGB='Silithid', Description_Lang_enGB='' WHERE ID=249;
UPDATE dbc_faction SET Name_Lang_enGB='Silvermoon Remnant', Description_Lang_enGB='' WHERE ID=269;
UPDATE dbc_faction SET Name_Lang_enGB='Zandalar Tribe', Description_Lang_enGB='These trolls have come to Yojamba Isle in an effort to recruit help against the resurrected Blood God and his Atal''ai Priests in Zul''Gurub.' WHERE ID=270;
UPDATE dbc_faction SET Name_Lang_enGB=' Blacksmithing - Weaponsmithing', Description_Lang_enGB='' WHERE ID=289;
UPDATE dbc_faction SET Name_Lang_enGB='Scorpid', Description_Lang_enGB='' WHERE ID=309;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Bat', Description_Lang_enGB='' WHERE ID=310;
UPDATE dbc_faction SET Name_Lang_enGB='Titan', Description_Lang_enGB='' WHERE ID=311;
UPDATE dbc_faction SET Name_Lang_enGB='Taskmaster Fizzule', Description_Lang_enGB='' WHERE ID=329;
UPDATE dbc_faction SET Name_Lang_enGB='Ravenholdt', Description_Lang_enGB='This guild of thieves and assassins welcomes only those of extraordinary prowess into its fold.  Sworn rivals of the Syndicate.' WHERE ID=349;
UPDATE dbc_faction SET Name_Lang_enGB='Gadgetzan', Description_Lang_enGB='Capital of the Steamwheedle Cartel and home to goblinhood''s finest engineers, alchemists and merchants.' WHERE ID=369;
UPDATE dbc_faction SET Name_Lang_enGB='Gnomeregan Bug', Description_Lang_enGB='' WHERE ID=389;
UPDATE dbc_faction SET Name_Lang_enGB='Harpy', Description_Lang_enGB='' WHERE ID=409;
UPDATE dbc_faction SET Name_Lang_enGB='Burning Blade', Description_Lang_enGB='' WHERE ID=429;
UPDATE dbc_faction SET Name_Lang_enGB='Shadowsilk Poacher', Description_Lang_enGB='' WHERE ID=449;
UPDATE dbc_faction SET Name_Lang_enGB='Searing Spider', Description_Lang_enGB='' WHERE ID=450;
UPDATE dbc_faction SET Name_Lang_enGB='Alliance', Description_Lang_enGB='' WHERE ID=469;
UPDATE dbc_faction SET Name_Lang_enGB='Ratchet', Description_Lang_enGB='Part of the Steamwheedle Cartel, this goblin city provides a neutral haven for those that wish to trade goods and services in the Barrens.' WHERE ID=470;
UPDATE dbc_faction SET Name_Lang_enGB='Wildhammer Clan', Description_Lang_enGB='Though not a part of the Alliance, the dwarves of Aerie Peak have opened their doors to it and hold the Horde as enemies.' WHERE ID=471;
UPDATE dbc_faction SET Name_Lang_enGB='Goblin, Dark Iron Bar Patron', Description_Lang_enGB='' WHERE ID=489;
UPDATE dbc_faction SET Name_Lang_enGB='The League of Arathor', Description_Lang_enGB='The League of Arathor seeks to reclaim the lost land of Arathi Basin for their benefactors in Stormwind.' WHERE ID=509;
UPDATE dbc_faction SET Name_Lang_enGB='The Defilers', Description_Lang_enGB='The Defilers seek to claim Arathi Basin''s valuable resources for the Horde.' WHERE ID=510;
UPDATE dbc_faction SET Name_Lang_enGB='Giant', Description_Lang_enGB='' WHERE ID=511;
UPDATE dbc_faction SET Name_Lang_enGB='Argent Dawn', Description_Lang_enGB='An organization focused on protecting Azeroth from the threat of the Scourge.  Strongholds of the Argent Dawn can be found in the Eastern and Western Plaguelands.' WHERE ID=529;
UPDATE dbc_faction SET Name_Lang_enGB='Darkspear Trolls', Description_Lang_enGB='This tribe of exiled trolls has joined forces with Thrall and the Horde.  They now call Durotar their home, which they share with their orc allies.' WHERE ID=530;
UPDATE dbc_faction SET Name_Lang_enGB='Dragonflight, Bronze', Description_Lang_enGB='' WHERE ID=531;
UPDATE dbc_faction SET Name_Lang_enGB='Dragonflight, Blue', Description_Lang_enGB='' WHERE ID=532;
UPDATE dbc_faction SET Name_Lang_enGB=' Leatherworking - Tribal', Description_Lang_enGB='' WHERE ID=549;
UPDATE dbc_faction SET Name_Lang_enGB=' Engineering - Goblin', Description_Lang_enGB='' WHERE ID=550;
UPDATE dbc_faction SET Name_Lang_enGB=' Engineering - Gnome', Description_Lang_enGB='' WHERE ID=551;
UPDATE dbc_faction SET Name_Lang_enGB=' Blacksmithing - Hammersmithing', Description_Lang_enGB='' WHERE ID=569;
UPDATE dbc_faction SET Name_Lang_enGB=' Blacksmithing - Axesmithing', Description_Lang_enGB='' WHERE ID=570;
UPDATE dbc_faction SET Name_Lang_enGB=' Blacksmithing - Swordsmithing', Description_Lang_enGB='' WHERE ID=571;
UPDATE dbc_faction SET Name_Lang_enGB='Troll, Vilebranch', Description_Lang_enGB='' WHERE ID=572;
UPDATE dbc_faction SET Name_Lang_enGB='Southsea Freebooters', Description_Lang_enGB='' WHERE ID=573;
UPDATE dbc_faction SET Name_Lang_enGB='Caer Darrow', Description_Lang_enGB='' WHERE ID=574;
UPDATE dbc_faction SET Name_Lang_enGB='Furbolg, Uncorrupted', Description_Lang_enGB='' WHERE ID=575;
UPDATE dbc_faction SET Name_Lang_enGB='Timbermaw Hold', Description_Lang_enGB='As the last uncorrupted furbolg tribe, the Timbermaw seek to preserve their spiritual ways and end the suffering of their brethren.' WHERE ID=576;
UPDATE dbc_faction SET Name_Lang_enGB='Everlook', Description_Lang_enGB='This trading post is run by the goblins of the Steamwheedle Cartel and it sits in the crossroads of Winterspring''s main trade routes.' WHERE ID=577;
UPDATE dbc_faction SET Name_Lang_enGB='Wintersaber Trainers', Description_Lang_enGB='This small group of reclusive night elves raises and trains wintersabers in the Winterspring area.' WHERE ID=589;
UPDATE dbc_faction SET Name_Lang_enGB='Cenarion Circle', Description_Lang_enGB='The druids of Cenarion Circle are guardians of nature and make their home in tranquil Moonglade.' WHERE ID=609;
UPDATE dbc_faction SET Name_Lang_enGB='Shatterspear Trolls', Description_Lang_enGB='' WHERE ID=629;
UPDATE dbc_faction SET Name_Lang_enGB='Ravasaur Trainers', Description_Lang_enGB='' WHERE ID=630;
UPDATE dbc_faction SET Name_Lang_enGB='Majordomo Executus', Description_Lang_enGB='' WHERE ID=649;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Carrion Bird', Description_Lang_enGB='' WHERE ID=669;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Cat', Description_Lang_enGB='' WHERE ID=670;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Crab', Description_Lang_enGB='' WHERE ID=671;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Crocilisk', Description_Lang_enGB='' WHERE ID=672;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Hyena', Description_Lang_enGB='' WHERE ID=673;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Owl', Description_Lang_enGB='' WHERE ID=674;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Scorpid', Description_Lang_enGB='' WHERE ID=675;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Tallstrider', Description_Lang_enGB='' WHERE ID=676;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Turtle', Description_Lang_enGB='' WHERE ID=677;
UPDATE dbc_faction SET Name_Lang_enGB='Beast - Wind Serpent', Description_Lang_enGB='' WHERE ID=678;
UPDATE dbc_faction SET Name_Lang_enGB='Training Dummy', Description_Lang_enGB='' WHERE ID=679;
UPDATE dbc_faction SET Name_Lang_enGB='Dragonflight, Black - Bait', Description_Lang_enGB='' WHERE ID=689;
UPDATE dbc_faction SET Name_Lang_enGB='Battleground Neutral', Description_Lang_enGB='' WHERE ID=709;
UPDATE dbc_faction SET Name_Lang_enGB='Frostwolf Clan', Description_Lang_enGB='The Frostwolf Clan seeks to drive out the dwarves of the Stormpike Expedition from Alterac Valley.' WHERE ID=729;
UPDATE dbc_faction SET Name_Lang_enGB='Stormpike Guard', Description_Lang_enGB='The Stormpike Dwarves have set up residence in Alterac Valley, where they''re locked in battle with the Frostwolf Orcs.' WHERE ID=730;
UPDATE dbc_faction SET Name_Lang_enGB='Hydraxian Waterlords', Description_Lang_enGB='These elementals have made their home on the islands east of Azshara.  Sworn enemies of the armies of Ragnaros.' WHERE ID=749;
UPDATE dbc_faction SET Name_Lang_enGB='Sulfuron Firelords', Description_Lang_enGB='' WHERE ID=750;
UPDATE dbc_faction SET Name_Lang_enGB='Gizlock''s Dummy', Description_Lang_enGB='' WHERE ID=769;
UPDATE dbc_faction SET Name_Lang_enGB='Gizlock''s Charm', Description_Lang_enGB='' WHERE ID=770;
UPDATE dbc_faction SET Name_Lang_enGB='Gizlock', Description_Lang_enGB='' WHERE ID=771;
UPDATE dbc_faction SET Name_Lang_enGB='Moro''gai', Description_Lang_enGB='' WHERE ID=789;
UPDATE dbc_faction SET Name_Lang_enGB='Spirit Guide - Alliance', Description_Lang_enGB='' WHERE ID=790;
UPDATE dbc_faction SET Name_Lang_enGB='Shen''dralar', Description_Lang_enGB='A remnant of the once powerful elves living in Dire Maul, yet still wise and knowledgeable about great secrets. ' WHERE ID=809;
UPDATE dbc_faction SET Name_Lang_enGB='Ogre (Captain Kromcrush)', Description_Lang_enGB='' WHERE ID=829;
UPDATE dbc_faction SET Name_Lang_enGB='Spirit Guide - Horde', Description_Lang_enGB='' WHERE ID=849;
UPDATE dbc_faction SET Name_Lang_enGB='Jaedenar', Description_Lang_enGB='' WHERE ID=869;
UPDATE dbc_faction SET Name_Lang_enGB='Warsong Outriders', Description_Lang_enGB='Fierce orcs of the Warsong Clan, locked in battle against the Silverwing Sentinels in Warsong Gulch.' WHERE ID=889;
UPDATE dbc_faction SET Name_Lang_enGB='Silverwing Sentinels', Description_Lang_enGB='Staunch defenders of Ashenvale, locked in battle against the Warsong Outriders in Warsong Gulch.' WHERE ID=890;
UPDATE dbc_faction SET Name_Lang_enGB='Alliance Forces', Description_Lang_enGB='' WHERE ID=891;
UPDATE dbc_faction SET Name_Lang_enGB='Horde Forces', Description_Lang_enGB='' WHERE ID=892;
UPDATE dbc_faction SET Name_Lang_enGB='Revantusk Trolls', Description_Lang_enGB='' WHERE ID=893;
UPDATE dbc_faction SET Name_Lang_enGB='Darkmoon Faire', Description_Lang_enGB='A traveling fair that showcases the weird and the extraordinary.  Often spotted in Elwynn Forest, Mulgore, and Terokkar Forest.' WHERE ID=909;
UPDATE dbc_faction SET Name_Lang_enGB='Brood of Nozdormu', Description_Lang_enGB='The descendants of the Bronze Dragonflight are the guardians of time and care little for the mortal races.' WHERE ID=910;
UPDATE dbc_faction SET Name_Lang_enGB='Silvermoon City', Description_Lang_enGB='The capital of Quel''Thalas, home of the blood elves.  Though nearly destroyed by Arthas'' attack on the Sunwell, Silvermoon is once again a thriving city.' WHERE ID=911;
UPDATE dbc_faction SET Name_Lang_enGB='Might of Kalimdor', Description_Lang_enGB='' WHERE ID=912;
UPDATE dbc_faction SET Name_Lang_enGB='PLAYER, Blood Elf', Description_Lang_enGB='' WHERE ID=914;
UPDATE dbc_faction SET Name_Lang_enGB='Armies of C''Thun', Description_Lang_enGB='' WHERE ID=915;
UPDATE dbc_faction SET Name_Lang_enGB='Silithid Attackers', Description_Lang_enGB='' WHERE ID=916;
UPDATE dbc_faction SET Name_Lang_enGB='The Ironforge Brigade', Description_Lang_enGB='' WHERE ID=917;
UPDATE dbc_faction SET Name_Lang_enGB='RC Enemies', Description_Lang_enGB='' WHERE ID=918;
UPDATE dbc_faction SET Name_Lang_enGB='RC Objects', Description_Lang_enGB='' WHERE ID=919;
UPDATE dbc_faction SET Name_Lang_enGB='Red', Description_Lang_enGB='' WHERE ID=920;
UPDATE dbc_faction SET Name_Lang_enGB='Blue', Description_Lang_enGB='' WHERE ID=921;
UPDATE dbc_faction SET Name_Lang_enGB='Tranquillien', Description_Lang_enGB='Once a high elf town, Tranquillien became abandoned after the Scourge invaded Quel''Thalas.  It has now been reclaimed by the Forsaken and the blood elves who seek to rid the Ghostlands of the Scourge.' WHERE ID=922;
UPDATE dbc_faction SET Name_Lang_enGB='Farstriders', Description_Lang_enGB='' WHERE ID=923;
UPDATE dbc_faction SET Name_Lang_enGB='DEPRECATED', Description_Lang_enGB='' WHERE ID=924;
UPDATE dbc_faction SET Name_Lang_enGB='Sunstriders', Description_Lang_enGB='' WHERE ID=925;
UPDATE dbc_faction SET Name_Lang_enGB='Magister''s Guild', Description_Lang_enGB='' WHERE ID=926;
UPDATE dbc_faction SET Name_Lang_enGB='PLAYER, Draenei', Description_Lang_enGB='' WHERE ID=927;
UPDATE dbc_faction SET Name_Lang_enGB='Scourge Invaders', Description_Lang_enGB='' WHERE ID=928;
UPDATE dbc_faction SET Name_Lang_enGB='Bloodmaul Clan', Description_Lang_enGB='' WHERE ID=929;
UPDATE dbc_faction SET Name_Lang_enGB='Exodar', Description_Lang_enGB='The naaru vessel that brought the draenei to Azeroth.  Though stranded in the Azuremyst Isles, it acts as a home city for this noble race.' WHERE ID=930;
UPDATE dbc_faction SET Name_Lang_enGB='Test Faction (not a real faction)', Description_Lang_enGB='This faction only exists to test the editing of faction names and descriptions...' WHERE ID=931;
UPDATE dbc_faction SET Name_Lang_enGB='The Aldor', Description_Lang_enGB='An ancient order of draenei priests once run by Velen, the Aldor are currently led by High Priestess Ishanah.  They are servants of the naaru in Shattrath City known as the Sha''tar.  Rivals of the Scryers.' WHERE ID=932;
UPDATE dbc_faction SET Name_Lang_enGB='The Consortium', Description_Lang_enGB='Led by Nexus-Prince Haramad, the Consortium is a loosely affiliated cartel of ethereal smugglers, traders and thieves that has come to Outland to benefit from its riches.' WHERE ID=933;
UPDATE dbc_faction SET Name_Lang_enGB='The Scryers', Description_Lang_enGB='Voren''thal the Seer leads the dissident blood elves who''ve rejected Kael''thas'' path to power.  They''ve joined forces with the naaru of Shattrath City, much to the dismay of the Aldor.' WHERE ID=934;
UPDATE dbc_faction SET Name_Lang_enGB='The Sha''tar', Description_Lang_enGB='The Sha''tar are a group of powerful naaru who rule over a rebuilt Shattrath City.  With the help of the Aldor and the Scryers, they lead the battle against Illidan and the Burning Legion.' WHERE ID=935;
UPDATE dbc_faction SET Name_Lang_enGB='Shattrath City', Description_Lang_enGB='' WHERE ID=936;
UPDATE dbc_faction SET Name_Lang_enGB='Troll, Forest', Description_Lang_enGB='' WHERE ID=937;
UPDATE dbc_faction SET Name_Lang_enGB='The Omenai', Description_Lang_enGB='' WHERE ID=938;
UPDATE dbc_faction SET Name_Lang_enGB='DEPRECATED', Description_Lang_enGB='' WHERE ID=939;
UPDATE dbc_faction SET Name_Lang_enGB='The Sons of Lothar', Description_Lang_enGB='' WHERE ID=940;
UPDATE dbc_faction SET Name_Lang_enGB='The Mag''har', Description_Lang_enGB='This reclusive group of brown-skinned orcs has escaped any form of demonic corruption.  They have retained their traditional way of life in the face of great changes in Outland.' WHERE ID=941;
UPDATE dbc_faction SET Name_Lang_enGB='Cenarion Expedition', Description_Lang_enGB='An exploratory force sent to Outland by the Cenarion Circle to study surviving life forms.  The Cenarion Expedition has quickly gained in size and autonomy since the opening of the Dark Portal.' WHERE ID=942;
UPDATE dbc_faction SET Name_Lang_enGB='Fel Orc', Description_Lang_enGB='' WHERE ID=943;
UPDATE dbc_faction SET Name_Lang_enGB='Fel Orc Ghost', Description_Lang_enGB='' WHERE ID=944;
UPDATE dbc_faction SET Name_Lang_enGB='Sons of Lothar Ghosts', Description_Lang_enGB='' WHERE ID=945;
UPDATE dbc_faction SET Name_Lang_enGB='Honor Hold', Description_Lang_enGB='Vestiges of the Sons of Lothar, veterans of the Alliance that first came into Draenor, have steadfastly held on to this Hellfire outpost.  They are now joined by the armies from Stormwind and Ironforge.' WHERE ID=946;
UPDATE dbc_faction SET Name_Lang_enGB='Thrallmar', Description_Lang_enGB='The expedition sent through the Dark Portal by Thrall has built a stronghold in Hellfire Peninsula.  Thrallmar serves as a base of operations for much of the Horde''s activities in Outland.' WHERE ID=947;
UPDATE dbc_faction SET Name_Lang_enGB='Test Faction 2', Description_Lang_enGB='' WHERE ID=948;
UPDATE dbc_faction SET Name_Lang_enGB='Test Faction 1', Description_Lang_enGB='' WHERE ID=949;
UPDATE dbc_faction SET Name_Lang_enGB='ToWoW - Flag', Description_Lang_enGB='' WHERE ID=950;
UPDATE dbc_faction SET Name_Lang_enGB='ToWoW - Flag Trigger Alliance (DND)', Description_Lang_enGB='' WHERE ID=951;
UPDATE dbc_faction SET Name_Lang_enGB='Test Faction 3', Description_Lang_enGB='' WHERE ID=952;
UPDATE dbc_faction SET Name_Lang_enGB='Test Faction 4', Description_Lang_enGB='' WHERE ID=953;
UPDATE dbc_faction SET Name_Lang_enGB='ToWoW - Flag Trigger Horde (DND)', Description_Lang_enGB='' WHERE ID=954;
UPDATE dbc_faction SET Name_Lang_enGB='Broken', Description_Lang_enGB='' WHERE ID=955;
UPDATE dbc_faction SET Name_Lang_enGB='Ethereum', Description_Lang_enGB='' WHERE ID=956;
UPDATE dbc_faction SET Name_Lang_enGB='Earth Elemental', Description_Lang_enGB='' WHERE ID=957;
UPDATE dbc_faction SET Name_Lang_enGB='Fighting Robots', Description_Lang_enGB='' WHERE ID=958;
UPDATE dbc_faction SET Name_Lang_enGB='Actor Good', Description_Lang_enGB='' WHERE ID=959;
UPDATE dbc_faction SET Name_Lang_enGB='Actor Evil', Description_Lang_enGB='' WHERE ID=960;
UPDATE dbc_faction SET Name_Lang_enGB='Stillpine Furbolg', Description_Lang_enGB='' WHERE ID=961;
UPDATE dbc_faction SET Name_Lang_enGB='Crazed Owlkin', Description_Lang_enGB='' WHERE ID=962;
UPDATE dbc_faction SET Name_Lang_enGB='Chess Alliance', Description_Lang_enGB='' WHERE ID=963;
UPDATE dbc_faction SET Name_Lang_enGB='Chess Horde', Description_Lang_enGB='' WHERE ID=964;
UPDATE dbc_faction SET Name_Lang_enGB='Monster Spar', Description_Lang_enGB='' WHERE ID=965;
UPDATE dbc_faction SET Name_Lang_enGB='Monster Spar Buddy', Description_Lang_enGB='' WHERE ID=966;
UPDATE dbc_faction SET Name_Lang_enGB='The Violet Eye', Description_Lang_enGB='A secret sect of the Kirin Tor founded to spy on Medivh and his activities.' WHERE ID=967;
UPDATE dbc_faction SET Name_Lang_enGB='Sunhawks', Description_Lang_enGB='' WHERE ID=968;
UPDATE dbc_faction SET Name_Lang_enGB='Hand of Argus', Description_Lang_enGB='' WHERE ID=969;
UPDATE dbc_faction SET Name_Lang_enGB='Sporeggar', Description_Lang_enGB='The sporelings are a mostly peaceful race of mushroom-men native to Outland. Their home is located in the southern bogs of Zangarmarsh. ' WHERE ID=970;
UPDATE dbc_faction SET Name_Lang_enGB='Fungal Giant', Description_Lang_enGB='' WHERE ID=971;
UPDATE dbc_faction SET Name_Lang_enGB='Spore Bat', Description_Lang_enGB='' WHERE ID=972;
UPDATE dbc_faction SET Name_Lang_enGB='Monster, Predator', Description_Lang_enGB='' WHERE ID=973;
UPDATE dbc_faction SET Name_Lang_enGB='Monster, Prey', Description_Lang_enGB='' WHERE ID=974;
UPDATE dbc_faction SET Name_Lang_enGB='Void Anomaly', Description_Lang_enGB='' WHERE ID=975;
UPDATE dbc_faction SET Name_Lang_enGB='Hyjal Defenders', Description_Lang_enGB='' WHERE ID=976;
UPDATE dbc_faction SET Name_Lang_enGB='Hyjal Invaders', Description_Lang_enGB='' WHERE ID=977;
UPDATE dbc_faction SET Name_Lang_enGB='Kurenai', Description_Lang_enGB='Draenei for "redeemed."  These Broken have escaped the grasp of their various slavers in Outland and have made their home in Nagrand.  It is there that they seek to rediscover their destiny.' WHERE ID=978;
UPDATE dbc_faction SET Name_Lang_enGB='Earthen Ring', Description_Lang_enGB='' WHERE ID=979;
UPDATE dbc_faction SET Name_Lang_enGB='The Burning Crusade', Description_Lang_enGB='' WHERE ID=980;
UPDATE dbc_faction SET Name_Lang_enGB='Arakkoa', Description_Lang_enGB='' WHERE ID=981;
UPDATE dbc_faction SET Name_Lang_enGB='Zangarmarsh Banner (Alliance)', Description_Lang_enGB='' WHERE ID=982;
UPDATE dbc_faction SET Name_Lang_enGB='Zangarmarsh Banner (Horde)', Description_Lang_enGB='' WHERE ID=983;
UPDATE dbc_faction SET Name_Lang_enGB='Zangarmarsh Banner (Neutral)', Description_Lang_enGB='' WHERE ID=984;
UPDATE dbc_faction SET Name_Lang_enGB='Caverns of Time - Thrall', Description_Lang_enGB='' WHERE ID=985;
UPDATE dbc_faction SET Name_Lang_enGB='Caverns of Time - Durnholde', Description_Lang_enGB='' WHERE ID=986;
UPDATE dbc_faction SET Name_Lang_enGB='Caverns of Time - Southshore Guards', Description_Lang_enGB='' WHERE ID=987;
UPDATE dbc_faction SET Name_Lang_enGB='Shadow Council Covert', Description_Lang_enGB='' WHERE ID=988;
UPDATE dbc_faction SET Name_Lang_enGB='Keepers of Time', Description_Lang_enGB='The Keepers of Time are bronze dragons hand-picked by Nozdormu to watch over the Caverns of Time.' WHERE ID=989;
UPDATE dbc_faction SET Name_Lang_enGB='The Scale of the Sands', Description_Lang_enGB='A secretive subgroup of the Bronze Dragonflight, led by Soridormi, prime mate of Nozdormu.' WHERE ID=990;
UPDATE dbc_faction SET Name_Lang_enGB='Dark Portal Defender, Alliance', Description_Lang_enGB='' WHERE ID=991;
UPDATE dbc_faction SET Name_Lang_enGB='Dark Portal Defender, Horde', Description_Lang_enGB='' WHERE ID=992;
UPDATE dbc_faction SET Name_Lang_enGB='Dark Portal Attacker, Legion', Description_Lang_enGB='' WHERE ID=993;
UPDATE dbc_faction SET Name_Lang_enGB='Inciter Trigger', Description_Lang_enGB='Used for the Blackheart the Inciter event.' WHERE ID=994;
UPDATE dbc_faction SET Name_Lang_enGB='Inciter Trigger 2', Description_Lang_enGB='Used for the Blackheart the Inciter event.' WHERE ID=995;
UPDATE dbc_faction SET Name_Lang_enGB='Inciter Trigger 3', Description_Lang_enGB='Used for the Blackheart the Inciter event.' WHERE ID=996;
UPDATE dbc_faction SET Name_Lang_enGB='Inciter Trigger 4', Description_Lang_enGB='Used for the Blackheart the Inciter event.' WHERE ID=997;
UPDATE dbc_faction SET Name_Lang_enGB='Inciter Trigger 5', Description_Lang_enGB='Used for the Blackheart the Inciter event.' WHERE ID=998;
UPDATE dbc_faction SET Name_Lang_enGB='Mana Creature', Description_Lang_enGB='' WHERE ID=999;
UPDATE dbc_faction SET Name_Lang_enGB='Khadgar''s Servant', Description_Lang_enGB='' WHERE ID=1000;
UPDATE dbc_faction SET Name_Lang_enGB='Bladespire Clan', Description_Lang_enGB='' WHERE ID=1001;
UPDATE dbc_faction SET Name_Lang_enGB='Ethereum Sparbuddy', Description_Lang_enGB='' WHERE ID=1002;
UPDATE dbc_faction SET Name_Lang_enGB='Protectorate', Description_Lang_enGB='' WHERE ID=1003;
UPDATE dbc_faction SET Name_Lang_enGB='Arcane Annihilator (DNR)', Description_Lang_enGB='' WHERE ID=1004;
UPDATE dbc_faction SET Name_Lang_enGB='Friendly, Hidden', Description_Lang_enGB='' WHERE ID=1005;
UPDATE dbc_faction SET Name_Lang_enGB='Kirin''Var - Dathric', Description_Lang_enGB='' WHERE ID=1006;
UPDATE dbc_faction SET Name_Lang_enGB='Kirin''Var - Belmara', Description_Lang_enGB='' WHERE ID=1007;
UPDATE dbc_faction SET Name_Lang_enGB='Kirin''Var - Luminrath', Description_Lang_enGB='' WHERE ID=1008;
UPDATE dbc_faction SET Name_Lang_enGB='Kirin''Var - Cohlien', Description_Lang_enGB='' WHERE ID=1009;
UPDATE dbc_faction SET Name_Lang_enGB='Servant of Illidan', Description_Lang_enGB='' WHERE ID=1010;
UPDATE dbc_faction SET Name_Lang_enGB='Lower City', Description_Lang_enGB='The refugees of Shattrath come from diverse backgrounds and races.  Word of helpful deeds spreads quickly among the Denizens of Lower City.' WHERE ID=1011;
UPDATE dbc_faction SET Name_Lang_enGB='Ashtongue Deathsworn', Description_Lang_enGB='The elite of the Broken tribe known as the Ashtongue, officially aligned with Illidan. The Deathsworn are Akama''s most trusted lieutenants and are privy to their leader''s mysterious motivations.' WHERE ID=1012;
UPDATE dbc_faction SET Name_Lang_enGB='Spirits of Shadowmoon 1', Description_Lang_enGB='' WHERE ID=1013;
UPDATE dbc_faction SET Name_Lang_enGB='Spirits of Shadowmoon 2', Description_Lang_enGB='' WHERE ID=1014;
UPDATE dbc_faction SET Name_Lang_enGB='Netherwing', Description_Lang_enGB='This unusual brood of dragons was spawned from the eggs of Deathwing''s black dragonflight, and infused with raw nether-energies.  Now, they seek to find their identity beyond the shadows of their father''s destructive heritage.' WHERE ID=1015;
UPDATE dbc_faction SET Name_Lang_enGB='Wyrmcult', Description_Lang_enGB='' WHERE ID=1016;
UPDATE dbc_faction SET Name_Lang_enGB='Treant', Description_Lang_enGB='' WHERE ID=1017;
UPDATE dbc_faction SET Name_Lang_enGB='Leotheras Demon I', Description_Lang_enGB='' WHERE ID=1018;
UPDATE dbc_faction SET Name_Lang_enGB='Leotheras Demon II', Description_Lang_enGB='' WHERE ID=1019;
UPDATE dbc_faction SET Name_Lang_enGB='Leotheras Demon III', Description_Lang_enGB='' WHERE ID=1020;
UPDATE dbc_faction SET Name_Lang_enGB='Leotheras Demon IV', Description_Lang_enGB='' WHERE ID=1021;
UPDATE dbc_faction SET Name_Lang_enGB='Leotheras Demon V', Description_Lang_enGB='' WHERE ID=1022;
UPDATE dbc_faction SET Name_Lang_enGB='Azaloth', Description_Lang_enGB='' WHERE ID=1023;
UPDATE dbc_faction SET Name_Lang_enGB='Rock Flayer', Description_Lang_enGB='' WHERE ID=1024;
UPDATE dbc_faction SET Name_Lang_enGB='Flayer Hunter', Description_Lang_enGB='' WHERE ID=1025;
UPDATE dbc_faction SET Name_Lang_enGB='Shadowmoon Shade', Description_Lang_enGB='' WHERE ID=1026;
UPDATE dbc_faction SET Name_Lang_enGB='Legion Communicator', Description_Lang_enGB='' WHERE ID=1027;
UPDATE dbc_faction SET Name_Lang_enGB='Ravenswood Ancients', Description_Lang_enGB='' WHERE ID=1028;
UPDATE dbc_faction SET Name_Lang_enGB='Chess, Friendly to All Chess', Description_Lang_enGB='' WHERE ID=1029;
UPDATE dbc_faction SET Name_Lang_enGB='Black Temple Gates - Illidari', Description_Lang_enGB='' WHERE ID=1030;
UPDATE dbc_faction SET Name_Lang_enGB='Sha''tari Skyguard', Description_Lang_enGB='An airborne military force created by Shattrath City to deal with the threats that loom in the highest reaches of Outland.' WHERE ID=1031;
UPDATE dbc_faction SET Name_Lang_enGB='Area 52', Description_Lang_enGB='' WHERE ID=1032;
UPDATE dbc_faction SET Name_Lang_enGB='Maiev', Description_Lang_enGB='' WHERE ID=1033;
UPDATE dbc_faction SET Name_Lang_enGB='Skettis Shadowy Arakkoa', Description_Lang_enGB='' WHERE ID=1034;
UPDATE dbc_faction SET Name_Lang_enGB='Skettis Arakkoa', Description_Lang_enGB='' WHERE ID=1035;
UPDATE dbc_faction SET Name_Lang_enGB='Dragonmaw Enemy', Description_Lang_enGB='' WHERE ID=1036;
UPDATE dbc_faction SET Name_Lang_enGB='Alliance Vanguard', Description_Lang_enGB='The combined forces of the Alliance in Northrend, lead by the Valiance Expedition, but also including civilian groups such as the Explorer''s League.' WHERE ID=1037;
UPDATE dbc_faction SET Name_Lang_enGB='Ogri''la', Description_Lang_enGB='The enlightened denizens of Ogri''la have made their dwelling in the western Blade''s Edge Mountains, where proximity to apexis crystals has caused them to transcend their brutish ogre nature.' WHERE ID=1038;
UPDATE dbc_faction SET Name_Lang_enGB='Ravager', Description_Lang_enGB='' WHERE ID=1039;
UPDATE dbc_faction SET Name_Lang_enGB='REUSE', Description_Lang_enGB='' WHERE ID=1040;
UPDATE dbc_faction SET Name_Lang_enGB='Frenzy', Description_Lang_enGB='' WHERE ID=1041;
UPDATE dbc_faction SET Name_Lang_enGB='Skyguard Enemy', Description_Lang_enGB='' WHERE ID=1042;
UPDATE dbc_faction SET Name_Lang_enGB='Skunk, Petunia', Description_Lang_enGB='' WHERE ID=1043;
UPDATE dbc_faction SET Name_Lang_enGB='Theramore Deserter', Description_Lang_enGB='' WHERE ID=1044;
UPDATE dbc_faction SET Name_Lang_enGB='Vrykul', Description_Lang_enGB='' WHERE ID=1045;
UPDATE dbc_faction SET Name_Lang_enGB='Northsea Pirates', Description_Lang_enGB='' WHERE ID=1046;
UPDATE dbc_faction SET Name_Lang_enGB='Tuskarr', Description_Lang_enGB='' WHERE ID=1047;
UPDATE dbc_faction SET Name_Lang_enGB='UNUSED', Description_Lang_enGB='' WHERE ID=1048;
UPDATE dbc_faction SET Name_Lang_enGB='Troll, Amani', Description_Lang_enGB='' WHERE ID=1049;
UPDATE dbc_faction SET Name_Lang_enGB='Valiance Expedition', Description_Lang_enGB='The main armies of the Alliance in Northrend, moving against the Scourge and unified under King Varian Wrynn''s command.' WHERE ID=1050;
UPDATE dbc_faction SET Name_Lang_enGB='UNUSED', Description_Lang_enGB='' WHERE ID=1051;
UPDATE dbc_faction SET Name_Lang_enGB='Horde Expedition', Description_Lang_enGB='The combined forces of the Horde in Northrend, spearheaded by the Warsong Offensive.' WHERE ID=1052;
UPDATE dbc_faction SET Name_Lang_enGB='Westguard', Description_Lang_enGB='' WHERE ID=1053;
UPDATE dbc_faction SET Name_Lang_enGB='Spotted Gryphon', Description_Lang_enGB='' WHERE ID=1054;
UPDATE dbc_faction SET Name_Lang_enGB='Tamed Plaguehound', Description_Lang_enGB='' WHERE ID=1055;
UPDATE dbc_faction SET Name_Lang_enGB='Vrykul (Ancient Spirit 1)', Description_Lang_enGB='' WHERE ID=1056;
UPDATE dbc_faction SET Name_Lang_enGB='Vrykul (Ancient Siprit 2)', Description_Lang_enGB='' WHERE ID=1057;
UPDATE dbc_faction SET Name_Lang_enGB='Vrykul (Ancient Siprit 3)', Description_Lang_enGB='' WHERE ID=1058;
UPDATE dbc_faction SET Name_Lang_enGB='CTF - Flag - Alliance', Description_Lang_enGB='' WHERE ID=1059;
UPDATE dbc_faction SET Name_Lang_enGB='Test', Description_Lang_enGB='' WHERE ID=1060;
UPDATE dbc_faction SET Name_Lang_enGB='vrykul', Description_Lang_enGB='' WHERE ID=1061;
UPDATE dbc_faction SET Name_Lang_enGB='Vrykul Gladiator', Description_Lang_enGB='' WHERE ID=1062;
UPDATE dbc_faction SET Name_Lang_enGB='Valgarde Combatant', Description_Lang_enGB='' WHERE ID=1063;
UPDATE dbc_faction SET Name_Lang_enGB='The Taunka', Description_Lang_enGB='These hardy people are cousins of the Tauren and have become valuable scouts for the armies of the Horde as they march northward.' WHERE ID=1064;
UPDATE dbc_faction SET Name_Lang_enGB='Monster, Zone Force Reaction 1', Description_Lang_enGB='' WHERE ID=1065;
UPDATE dbc_faction SET Name_Lang_enGB='Monster, Zone Force Reaction 2', Description_Lang_enGB='' WHERE ID=1066;
UPDATE dbc_faction SET Name_Lang_enGB='The Hand of Vengeance', Description_Lang_enGB='The Forsaken tasked by Sylvanas Windrunner with enacting Undercity''s vengeance against Arthas by delivering the latest strain of their deadly Plague.' WHERE ID=1067;
UPDATE dbc_faction SET Name_Lang_enGB='Explorers'' League', Description_Lang_enGB='This organization seeks to find the origin of the dwarven race by collecting Titan artifacts.  Their most recent research has led them to various archeological sites in Northrend.' WHERE ID=1068;
UPDATE dbc_faction SET Name_Lang_enGB='Ram Racing Powerup DND', Description_Lang_enGB='' WHERE ID=1069;
UPDATE dbc_faction SET Name_Lang_enGB='Ram Racing Trap DND', Description_Lang_enGB='' WHERE ID=1070;
UPDATE dbc_faction SET Name_Lang_enGB='Craig''s Squirrels', Description_Lang_enGB='A test faction.' WHERE ID=1071;
UPDATE dbc_faction SET Name_Lang_enGB='REUSE', Description_Lang_enGB='' WHERE ID=1072;
UPDATE dbc_faction SET Name_Lang_enGB='The Kalu''ak', Description_Lang_enGB='The tuskarr are a tough but peaceful people who derive their livelihood from fishing and whaling.  Their settlements have recently come under fierce attack and welcome any allies who would come to their aid.' WHERE ID=1073;
UPDATE dbc_faction SET Name_Lang_enGB='Holiday - Water Barrel', Description_Lang_enGB='' WHERE ID=1074;
UPDATE dbc_faction SET Name_Lang_enGB='Holiday - Generic', Description_Lang_enGB='' WHERE ID=1075;
UPDATE dbc_faction SET Name_Lang_enGB='Iron Dwarves', Description_Lang_enGB='' WHERE ID=1076;
UPDATE dbc_faction SET Name_Lang_enGB='Shattered Sun Offensive', Description_Lang_enGB='Shattrath City''s final push against Prince Kael''thas'' operations in the Sunwell.' WHERE ID=1077;
UPDATE dbc_faction SET Name_Lang_enGB='Fighting Vanity Pet', Description_Lang_enGB='' WHERE ID=1078;
UPDATE dbc_faction SET Name_Lang_enGB='Murloc, Winterfin', Description_Lang_enGB='' WHERE ID=1079;
UPDATE dbc_faction SET Name_Lang_enGB='Friendly, Force Reaction', Description_Lang_enGB='' WHERE ID=1080;
UPDATE dbc_faction SET Name_Lang_enGB='Object, Force Reaction', Description_Lang_enGB='' WHERE ID=1081;
UPDATE dbc_faction SET Name_Lang_enGB='REUSE', Description_Lang_enGB='' WHERE ID=1082;
UPDATE dbc_faction SET Name_Lang_enGB='REUSE', Description_Lang_enGB='' WHERE ID=1083;
UPDATE dbc_faction SET Name_Lang_enGB='Vrykul, Sea', Description_Lang_enGB='' WHERE ID=1084;
UPDATE dbc_faction SET Name_Lang_enGB='Warsong Offensive', Description_Lang_enGB='Garrosh Hellscream commands the Horde''s main expeditionary forces as they make their way into Northrend to face Arthas and the armies of the Scourge.' WHERE ID=1085;
UPDATE dbc_faction SET Name_Lang_enGB='Poacher', Description_Lang_enGB='' WHERE ID=1086;
UPDATE dbc_faction SET Name_Lang_enGB='Holiday Monster', Description_Lang_enGB='' WHERE ID=1087;
UPDATE dbc_faction SET Name_Lang_enGB='Furbolg, Redfang', Description_Lang_enGB='' WHERE ID=1088;
UPDATE dbc_faction SET Name_Lang_enGB='Furbolg, Frostpaw', Description_Lang_enGB='' WHERE ID=1089;
UPDATE dbc_faction SET Name_Lang_enGB='Kirin Tor', Description_Lang_enGB='The mages and archmages running the city of Dalaran.  Faced with the rising threats of the Blue Dragonflight and the Scourge, they''ve transported their city to the heart of Northrend.' WHERE ID=1090;
UPDATE dbc_faction SET Name_Lang_enGB='The Wyrmrest Accord', Description_Lang_enGB='With the Blue Dragonflight''s violent upheaval against all mortal users of magic, the remaining dragonflights have banded under the leadership of the Red Dragonflight to combat their wayward kin.' WHERE ID=1091;
UPDATE dbc_faction SET Name_Lang_enGB='Azjol-Nerub', Description_Lang_enGB='' WHERE ID=1092;
UPDATE dbc_faction SET Name_Lang_enGB='REUSE', Description_Lang_enGB='' WHERE ID=1093;
UPDATE dbc_faction SET Name_Lang_enGB='The Silver Covenant', Description_Lang_enGB='A militant core of high elves that rejects the admission of blood elves into the Kirin Tor.  They''ve united under the banner of Vereesa Windrunner and joined the Alliance forces in Northrend.' WHERE ID=1094;
UPDATE dbc_faction SET Name_Lang_enGB='Grizzly Hills Trapper', Description_Lang_enGB='' WHERE ID=1095;
UPDATE dbc_faction SET Name_Lang_enGB='REUSE', Description_Lang_enGB='' WHERE ID=1096;
UPDATE dbc_faction SET Name_Lang_enGB='Wrath of the Lich King', Description_Lang_enGB='' WHERE ID=1097;
UPDATE dbc_faction SET Name_Lang_enGB='Knights of the Ebon Blade', Description_Lang_enGB='Freed from the grasp of the Lich King, his former Death Knights have regrouped against him under the banner of Highlord Darion Mograine.' WHERE ID=1098;
UPDATE dbc_faction SET Name_Lang_enGB='Wrathgate Scourge', Description_Lang_enGB='' WHERE ID=1099;
UPDATE dbc_faction SET Name_Lang_enGB='Wrathgate Alliance', Description_Lang_enGB='' WHERE ID=1100;
UPDATE dbc_faction SET Name_Lang_enGB='Wrathgate Horde', Description_Lang_enGB='' WHERE ID=1101;
UPDATE dbc_faction SET Name_Lang_enGB='CTF - Flag - Horde', Description_Lang_enGB='' WHERE ID=1102;
UPDATE dbc_faction SET Name_Lang_enGB='CTF - Flag - Neutral', Description_Lang_enGB='' WHERE ID=1103;
UPDATE dbc_faction SET Name_Lang_enGB='Frenzyheart Tribe', Description_Lang_enGB='Driven from their lands by the Scourge, this fierce tribe of wolvar stumbled upon Sholazar Basin, where they intend to make their new home.  Their aggressive nature has put them at odds with the various gorloc tribes known collectively as the Oracles.' WHERE ID=1104;
UPDATE dbc_faction SET Name_Lang_enGB='The Oracles', Description_Lang_enGB='The gorlocs of Sholazar Basin are a race of reptilian creatures who see themselves as guardians of the titan technology that remains in the zone (though they understand little of it).  They find themselves in an escalating territorial war with the wolvar.' WHERE ID=1105;
UPDATE dbc_faction SET Name_Lang_enGB='Argent Crusade', Description_Lang_enGB='Led by Tirion Fordring, the Argent Crusade combines the reformed Order of the Silver Hand with the Argent Dawn in one final push against the forces of the Lich King.' WHERE ID=1106;
UPDATE dbc_faction SET Name_Lang_enGB='Troll, Drakkari', Description_Lang_enGB='' WHERE ID=1107;
UPDATE dbc_faction SET Name_Lang_enGB='CoT Arthas', Description_Lang_enGB='' WHERE ID=1108;
UPDATE dbc_faction SET Name_Lang_enGB='CoT Stratholme Citizen', Description_Lang_enGB='' WHERE ID=1109;
UPDATE dbc_faction SET Name_Lang_enGB='CoT Scourge', Description_Lang_enGB='' WHERE ID=1110;
UPDATE dbc_faction SET Name_Lang_enGB='Freya', Description_Lang_enGB='' WHERE ID=1111;
UPDATE dbc_faction SET Name_Lang_enGB='Mount - Taxi - Alliance', Description_Lang_enGB='' WHERE ID=1112;
UPDATE dbc_faction SET Name_Lang_enGB='Mount - Taxi - Horde', Description_Lang_enGB='' WHERE ID=1113;
UPDATE dbc_faction SET Name_Lang_enGB='Mount - Taxi - Neutral', Description_Lang_enGB='' WHERE ID=1114;
UPDATE dbc_faction SET Name_Lang_enGB='Elemental, Water', Description_Lang_enGB='' WHERE ID=1115;
UPDATE dbc_faction SET Name_Lang_enGB='Elemental, Air', Description_Lang_enGB='' WHERE ID=1116;
UPDATE dbc_faction SET Name_Lang_enGB='Sholazar Basin', Description_Lang_enGB='' WHERE ID=1117;
UPDATE dbc_faction SET Name_Lang_enGB='Classic', Description_Lang_enGB='' WHERE ID=1118;
UPDATE dbc_faction SET Name_Lang_enGB='The Sons of Hodir', Description_Lang_enGB='The frost giants of the Storm Peaks are a war-like race that makes their home in Dun Nifelem.' WHERE ID=1119;
UPDATE dbc_faction SET Name_Lang_enGB='Iron Giants', Description_Lang_enGB='' WHERE ID=1120;
UPDATE dbc_faction SET Name_Lang_enGB='Frost Vrykul', Description_Lang_enGB='' WHERE ID=1121;
UPDATE dbc_faction SET Name_Lang_enGB='Earthen', Description_Lang_enGB='' WHERE ID=1122;
UPDATE dbc_faction SET Name_Lang_enGB='Monster Referee', Description_Lang_enGB='' WHERE ID=1123;
UPDATE dbc_faction SET Name_Lang_enGB='The Sunreavers', Description_Lang_enGB='Traditionally barred from Dalaran, the Horde has been accepted into the city through the efforts of Archmage Aethas Sunreaver.  His followers have taken up his name and watch over the ward known as Sunreaver''s Sanctuary.' WHERE ID=1124;
UPDATE dbc_faction SET Name_Lang_enGB='Hyldsmeet', Description_Lang_enGB='' WHERE ID=1125;
UPDATE dbc_faction SET Name_Lang_enGB='The Frostborn', Description_Lang_enGB='This mysterious race of frost dwarves makes their home in the Storm Peaks.  They''ve recently befriended members of the Explorers'' League and welcome Alliance members within their settlements.' WHERE ID=1126;
UPDATE dbc_faction SET Name_Lang_enGB='Orgrimmar (Alex Test)', Description_Lang_enGB='' WHERE ID=1127;
UPDATE dbc_faction SET Name_Lang_enGB='Tranquillien Conversion', Description_Lang_enGB='' WHERE ID=1136;
UPDATE dbc_faction SET Name_Lang_enGB='Wintersaber Conversion', Description_Lang_enGB='' WHERE ID=1137;
UPDATE dbc_faction SET Name_Lang_enGB='Hates Everything', Description_Lang_enGB='' WHERE ID=1145;
UPDATE dbc_faction SET Name_Lang_enGB='Silver Covenant Conversion', Description_Lang_enGB='' WHERE ID=1154;
UPDATE dbc_faction SET Name_Lang_enGB='Sunreavers Conversion', Description_Lang_enGB='' WHERE ID=1155;
UPDATE dbc_faction SET Name_Lang_enGB='The Ashen Verdict', Description_Lang_enGB='Under a pact by Tirion Fordring and Darion Mograine, the Argent Crusade and the Knights of the Ebon Blade have set aside their differences during the attack on Icecrown Citadel until the Lich King is slain.' WHERE ID=1156;
UPDATE dbc_faction SET Name_Lang_enGB='CTF - Flag - Alliance 2', Description_Lang_enGB='' WHERE ID=1159;
UPDATE dbc_faction SET Name_Lang_enGB='CTF - Flag - Horde 2', Description_Lang_enGB='' WHERE ID=1160;
