UPDATE dbc_itemset SET Name_Lang_enGB='The Gladiator' WHERE ID=1;
UPDATE dbc_itemset SET Name_Lang_enGB='Dal''Rend''s Arms' WHERE ID=41;
UPDATE dbc_itemset SET Name_Lang_enGB='Spider''s Kiss' WHERE ID=65;
UPDATE dbc_itemset SET Name_Lang_enGB='The Postmaster' WHERE ID=81;
UPDATE dbc_itemset SET Name_Lang_enGB='Cadaverous Garb' WHERE ID=121;
UPDATE dbc_itemset SET Name_Lang_enGB='Necropile Raiment' WHERE ID=122;
UPDATE dbc_itemset SET Name_Lang_enGB='Bloodmail Regalia' WHERE ID=123;
UPDATE dbc_itemset SET Name_Lang_enGB='Deathbone Guardian' WHERE ID=124;
UPDATE dbc_itemset SET Name_Lang_enGB='Volcanic Armor' WHERE ID=141;
UPDATE dbc_itemset SET Name_Lang_enGB='Stormshroud Armor' WHERE ID=142;
UPDATE dbc_itemset SET Name_Lang_enGB='Devilsaur Armor' WHERE ID=143;
UPDATE dbc_itemset SET Name_Lang_enGB='Ironfeather Armor' WHERE ID=144;
UPDATE dbc_itemset SET Name_Lang_enGB='Defias Leather' WHERE ID=161;
UPDATE dbc_itemset SET Name_Lang_enGB='Embrace of the Viper' WHERE ID=162;
UPDATE dbc_itemset SET Name_Lang_enGB='Chain of the Scarlet Crusade' WHERE ID=163;
UPDATE dbc_itemset SET Name_Lang_enGB='Magister''s Regalia' WHERE ID=181;
UPDATE dbc_itemset SET Name_Lang_enGB='Vestments of the Devout' WHERE ID=182;
UPDATE dbc_itemset SET Name_Lang_enGB='Dreadmist Raiment' WHERE ID=183;
UPDATE dbc_itemset SET Name_Lang_enGB='Shadowcraft Armor' WHERE ID=184;
UPDATE dbc_itemset SET Name_Lang_enGB='Wildheart Raiment' WHERE ID=185;
UPDATE dbc_itemset SET Name_Lang_enGB='Beaststalker Armor' WHERE ID=186;
UPDATE dbc_itemset SET Name_Lang_enGB='The Elements' WHERE ID=187;
UPDATE dbc_itemset SET Name_Lang_enGB='Lightforge Armor' WHERE ID=188;
UPDATE dbc_itemset SET Name_Lang_enGB='Battlegear of Valor' WHERE ID=189;
UPDATE dbc_itemset SET Name_Lang_enGB='Arcanist Regalia' WHERE ID=201;
UPDATE dbc_itemset SET Name_Lang_enGB='Vestments of Prophecy' WHERE ID=202;
UPDATE dbc_itemset SET Name_Lang_enGB='Felheart Raiment' WHERE ID=203;
UPDATE dbc_itemset SET Name_Lang_enGB='Nightslayer Armor' WHERE ID=204;
UPDATE dbc_itemset SET Name_Lang_enGB='Cenarion Raiment' WHERE ID=205;
UPDATE dbc_itemset SET Name_Lang_enGB='Giantstalker Armor' WHERE ID=206;
UPDATE dbc_itemset SET Name_Lang_enGB='The Earthfury' WHERE ID=207;
UPDATE dbc_itemset SET Name_Lang_enGB='Lawbringer Armor' WHERE ID=208;
UPDATE dbc_itemset SET Name_Lang_enGB='Battlegear of Might' WHERE ID=209;
UPDATE dbc_itemset SET Name_Lang_enGB='Netherwind Regalia' WHERE ID=210;
UPDATE dbc_itemset SET Name_Lang_enGB='Vestments of Transcendence' WHERE ID=211;
UPDATE dbc_itemset SET Name_Lang_enGB='Nemesis Raiment' WHERE ID=212;
UPDATE dbc_itemset SET Name_Lang_enGB='Bloodfang Armor' WHERE ID=213;
UPDATE dbc_itemset SET Name_Lang_enGB='Stormrage Raiment' WHERE ID=214;
UPDATE dbc_itemset SET Name_Lang_enGB='Dragonstalker Armor' WHERE ID=215;
UPDATE dbc_itemset SET Name_Lang_enGB='The Ten Storms' WHERE ID=216;
UPDATE dbc_itemset SET Name_Lang_enGB='Judgement Armor' WHERE ID=217;
UPDATE dbc_itemset SET Name_Lang_enGB='Battlegear of Wrath' WHERE ID=218;
UPDATE dbc_itemset SET Name_Lang_enGB='Garb of Thero-shan' WHERE ID=221;
UPDATE dbc_itemset SET Name_Lang_enGB='Shard of the Gods' WHERE ID=241;
UPDATE dbc_itemset SET Name_Lang_enGB='Spirit of Eskhandar' WHERE ID=261;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Battlegear' WHERE ID=281;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Battlegear' WHERE ID=282;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Earthshaker' WHERE ID=301;
UPDATE dbc_itemset SET Name_Lang_enGB='Imperial Plate' WHERE ID=321;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Regalia' WHERE ID=341;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Raiment' WHERE ID=342;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Regalia' WHERE ID=343;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Raiment' WHERE ID=344;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Threads' WHERE ID=345;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Threads' WHERE ID=346;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Vestments' WHERE ID=347;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Vestments' WHERE ID=348;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Pursuit' WHERE ID=361;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Pursuit' WHERE ID=362;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Sanctuary' WHERE ID=381;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Sanctuary' WHERE ID=382;
UPDATE dbc_itemset SET Name_Lang_enGB='Warlord''s Battlegear' WHERE ID=383;
UPDATE dbc_itemset SET Name_Lang_enGB='Field Marshal''s Battlegear' WHERE ID=384;
UPDATE dbc_itemset SET Name_Lang_enGB='Warlord''s Earthshaker' WHERE ID=386;
UPDATE dbc_itemset SET Name_Lang_enGB='Warlord''s Regalia' WHERE ID=387;
UPDATE dbc_itemset SET Name_Lang_enGB='Field Marshal''s Regalia' WHERE ID=388;
UPDATE dbc_itemset SET Name_Lang_enGB='Field Marshal''s Raiment' WHERE ID=389;
UPDATE dbc_itemset SET Name_Lang_enGB='Warlord''s Raiment' WHERE ID=390;
UPDATE dbc_itemset SET Name_Lang_enGB='Warlord''s Threads' WHERE ID=391;
UPDATE dbc_itemset SET Name_Lang_enGB='Field Marshal''s Threads' WHERE ID=392;
UPDATE dbc_itemset SET Name_Lang_enGB='Warlord''s Vestments' WHERE ID=393;
UPDATE dbc_itemset SET Name_Lang_enGB='Field Marshal''s Vestments' WHERE ID=394;
UPDATE dbc_itemset SET Name_Lang_enGB='Field Marshal''s Pursuit' WHERE ID=395;
UPDATE dbc_itemset SET Name_Lang_enGB='Warlord''s Pursuit' WHERE ID=396;
UPDATE dbc_itemset SET Name_Lang_enGB='Field Marshal''s Sanctuary' WHERE ID=397;
UPDATE dbc_itemset SET Name_Lang_enGB='Warlord''s Sanctuary' WHERE ID=398;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Aegis' WHERE ID=401;
UPDATE dbc_itemset SET Name_Lang_enGB='Field Marshal''s Aegis' WHERE ID=402;
UPDATE dbc_itemset SET Name_Lang_enGB='Bloodvine Garb' WHERE ID=421;
UPDATE dbc_itemset SET Name_Lang_enGB='Primal Batskin' WHERE ID=441;
UPDATE dbc_itemset SET Name_Lang_enGB='Blood Tiger Harness' WHERE ID=442;
UPDATE dbc_itemset SET Name_Lang_enGB='Bloodsoul Embrace' WHERE ID=443;
UPDATE dbc_itemset SET Name_Lang_enGB='The Darksoul' WHERE ID=444;
UPDATE dbc_itemset SET Name_Lang_enGB='The Twin Blades of Hakkari' WHERE ID=461;
UPDATE dbc_itemset SET Name_Lang_enGB='Zanzil''s Concentration' WHERE ID=462;
UPDATE dbc_itemset SET Name_Lang_enGB='Primal Blessing' WHERE ID=463;
UPDATE dbc_itemset SET Name_Lang_enGB='Overlord''s Resolution' WHERE ID=464;
UPDATE dbc_itemset SET Name_Lang_enGB='Prayer of the Primal' WHERE ID=465;
UPDATE dbc_itemset SET Name_Lang_enGB='Major Mojo Infusion' WHERE ID=466;
UPDATE dbc_itemset SET Name_Lang_enGB='The Highlander''s Resolution' WHERE ID=467;
UPDATE dbc_itemset SET Name_Lang_enGB='The Highlander''s Resolve' WHERE ID=468;
UPDATE dbc_itemset SET Name_Lang_enGB='The Highlander''s Determination' WHERE ID=469;
UPDATE dbc_itemset SET Name_Lang_enGB='The Highlander''s Fortitude' WHERE ID=470;
UPDATE dbc_itemset SET Name_Lang_enGB='The Highlander''s Purpose' WHERE ID=471;
UPDATE dbc_itemset SET Name_Lang_enGB='The Highlander''s Will' WHERE ID=472;
UPDATE dbc_itemset SET Name_Lang_enGB='The Highlander''s Intent' WHERE ID=473;
UPDATE dbc_itemset SET Name_Lang_enGB='Vindicator''s Battlegear' WHERE ID=474;
UPDATE dbc_itemset SET Name_Lang_enGB='Freethinker''s Armor' WHERE ID=475;
UPDATE dbc_itemset SET Name_Lang_enGB='Augur''s Regalia' WHERE ID=476;
UPDATE dbc_itemset SET Name_Lang_enGB='Predator''s Armor' WHERE ID=477;
UPDATE dbc_itemset SET Name_Lang_enGB='Madcap''s Outfit' WHERE ID=478;
UPDATE dbc_itemset SET Name_Lang_enGB='Haruspex''s Garb' WHERE ID=479;
UPDATE dbc_itemset SET Name_Lang_enGB='Confessor''s Raiment' WHERE ID=480;
UPDATE dbc_itemset SET Name_Lang_enGB='Demoniac''s Threads' WHERE ID=481;
UPDATE dbc_itemset SET Name_Lang_enGB='Illusionist''s Attire' WHERE ID=482;
UPDATE dbc_itemset SET Name_Lang_enGB='The Defiler''s Determination' WHERE ID=483;
UPDATE dbc_itemset SET Name_Lang_enGB='The Defiler''s Fortitude' WHERE ID=484;
UPDATE dbc_itemset SET Name_Lang_enGB='The Defiler''s Intent' WHERE ID=485;
UPDATE dbc_itemset SET Name_Lang_enGB='The Defiler''s Purpose' WHERE ID=486;
UPDATE dbc_itemset SET Name_Lang_enGB='The Defiler''s Resolution' WHERE ID=487;
UPDATE dbc_itemset SET Name_Lang_enGB='The Defiler''s Will' WHERE ID=488;
UPDATE dbc_itemset SET Name_Lang_enGB='Black Dragon Mail' WHERE ID=489;
UPDATE dbc_itemset SET Name_Lang_enGB='Green Dragon Mail' WHERE ID=490;
UPDATE dbc_itemset SET Name_Lang_enGB='Blue Dragon Mail' WHERE ID=491;
UPDATE dbc_itemset SET Name_Lang_enGB='Twilight Trappings' WHERE ID=492;
UPDATE dbc_itemset SET Name_Lang_enGB='Genesis Raiment' WHERE ID=493;
UPDATE dbc_itemset SET Name_Lang_enGB='Symbols of Unending Life' WHERE ID=494;
UPDATE dbc_itemset SET Name_Lang_enGB='Battlegear of Unyielding Strength' WHERE ID=495;
UPDATE dbc_itemset SET Name_Lang_enGB='Conqueror''s Battlegear' WHERE ID=496;
UPDATE dbc_itemset SET Name_Lang_enGB='Deathdealer''s Embrace' WHERE ID=497;
UPDATE dbc_itemset SET Name_Lang_enGB='Emblems of Veiled Shadows' WHERE ID=498;
UPDATE dbc_itemset SET Name_Lang_enGB='Doomcaller''s Attire' WHERE ID=499;
UPDATE dbc_itemset SET Name_Lang_enGB='Implements of Unspoken Names' WHERE ID=500;
UPDATE dbc_itemset SET Name_Lang_enGB='Stormcaller''s Garb' WHERE ID=501;
UPDATE dbc_itemset SET Name_Lang_enGB='Gift of the Gathering Storm' WHERE ID=502;
UPDATE dbc_itemset SET Name_Lang_enGB='Enigma Vestments' WHERE ID=503;
UPDATE dbc_itemset SET Name_Lang_enGB='Trappings of Vaulted Secrets' WHERE ID=504;
UPDATE dbc_itemset SET Name_Lang_enGB='Avenger''s Battlegear' WHERE ID=505;
UPDATE dbc_itemset SET Name_Lang_enGB='Battlegear of Eternal Justice' WHERE ID=506;
UPDATE dbc_itemset SET Name_Lang_enGB='Garments of the Oracle' WHERE ID=507;
UPDATE dbc_itemset SET Name_Lang_enGB='Finery of Infinite Wisdom' WHERE ID=508;
UPDATE dbc_itemset SET Name_Lang_enGB='Striker''s Garb' WHERE ID=509;
UPDATE dbc_itemset SET Name_Lang_enGB='Trappings of the Unseen Path' WHERE ID=510;
UPDATE dbc_itemset SET Name_Lang_enGB='Battlegear of Heroism' WHERE ID=511;
UPDATE dbc_itemset SET Name_Lang_enGB='Darkmantle Armor' WHERE ID=512;
UPDATE dbc_itemset SET Name_Lang_enGB='Feralheart Raiment' WHERE ID=513;
UPDATE dbc_itemset SET Name_Lang_enGB='Vestments of the Virtuous' WHERE ID=514;
UPDATE dbc_itemset SET Name_Lang_enGB='Beastmaster Armor' WHERE ID=515;
UPDATE dbc_itemset SET Name_Lang_enGB='Soulforge Armor' WHERE ID=516;
UPDATE dbc_itemset SET Name_Lang_enGB='Sorcerer''s Regalia' WHERE ID=517;
UPDATE dbc_itemset SET Name_Lang_enGB='Deathmist Raiment' WHERE ID=518;
UPDATE dbc_itemset SET Name_Lang_enGB='The Five Thunders' WHERE ID=519;
UPDATE dbc_itemset SET Name_Lang_enGB='Ironweave Battlesuit' WHERE ID=520;
UPDATE dbc_itemset SET Name_Lang_enGB='Dreamwalker Raiment' WHERE ID=521;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Guard' WHERE ID=522;
UPDATE dbc_itemset SET Name_Lang_enGB='Dreadnaught''s Battlegear' WHERE ID=523;
UPDATE dbc_itemset SET Name_Lang_enGB='Bonescythe Armor' WHERE ID=524;
UPDATE dbc_itemset SET Name_Lang_enGB='Vestments of Faith' WHERE ID=525;
UPDATE dbc_itemset SET Name_Lang_enGB='Frostfire Regalia' WHERE ID=526;
UPDATE dbc_itemset SET Name_Lang_enGB='The Earthshatterer' WHERE ID=527;
UPDATE dbc_itemset SET Name_Lang_enGB='Redemption Armor' WHERE ID=528;
UPDATE dbc_itemset SET Name_Lang_enGB='Plagueheart Raiment' WHERE ID=529;
UPDATE dbc_itemset SET Name_Lang_enGB='Cryptstalker Armor' WHERE ID=530;
UPDATE dbc_itemset SET Name_Lang_enGB='Battlegear of Undead Slaying' WHERE ID=533;
UPDATE dbc_itemset SET Name_Lang_enGB='Undead Slayer''s Armor' WHERE ID=534;
UPDATE dbc_itemset SET Name_Lang_enGB='Garb of the Undead Slayer' WHERE ID=535;
UPDATE dbc_itemset SET Name_Lang_enGB='Regalia of Undead Cleansing' WHERE ID=536;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Battlearmor' WHERE ID=537;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Stormcaller' WHERE ID=538;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Refuge' WHERE ID=539;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Investiture' WHERE ID=540;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Dreadgear' WHERE ID=541;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Arcanum' WHERE ID=542;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Pursuance' WHERE ID=543;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Redoubt' WHERE ID=544;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Battlearmor' WHERE ID=545;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Arcanum' WHERE ID=546;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Dreadgear' WHERE ID=547;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Guard' WHERE ID=548;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Investiture' WHERE ID=549;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Pursuance' WHERE ID=550;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Refuge' WHERE ID=551;
UPDATE dbc_itemset SET Name_Lang_enGB='Wrath of Spellfire' WHERE ID=552;
UPDATE dbc_itemset SET Name_Lang_enGB='Shadow''s Embrace' WHERE ID=553;
UPDATE dbc_itemset SET Name_Lang_enGB='Primal Mooncloth' WHERE ID=554;
UPDATE dbc_itemset SET Name_Lang_enGB='Netherweave Vestments' WHERE ID=555;
UPDATE dbc_itemset SET Name_Lang_enGB='Imbued Netherweave' WHERE ID=556;
UPDATE dbc_itemset SET Name_Lang_enGB='Soulcloth Embrace' WHERE ID=557;
UPDATE dbc_itemset SET Name_Lang_enGB='Arcanoweave Vestments' WHERE ID=558;
UPDATE dbc_itemset SET Name_Lang_enGB='Spellstrike Infusion' WHERE ID=559;
UPDATE dbc_itemset SET Name_Lang_enGB='Fel Iron Plate' WHERE ID=560;
UPDATE dbc_itemset SET Name_Lang_enGB='Fel Iron Chain' WHERE ID=561;
UPDATE dbc_itemset SET Name_Lang_enGB='Adamantite Battlegear' WHERE ID=562;
UPDATE dbc_itemset SET Name_Lang_enGB='Enchanted Adamantite Armor' WHERE ID=563;
UPDATE dbc_itemset SET Name_Lang_enGB='Flame Guard' WHERE ID=564;
UPDATE dbc_itemset SET Name_Lang_enGB='Khorium Ward' WHERE ID=565;
UPDATE dbc_itemset SET Name_Lang_enGB='Burning Rage' WHERE ID=566;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Battlegear' WHERE ID=567;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Dreadgear' WHERE ID=568;
UPDATE dbc_itemset SET Name_Lang_enGB='Faith in Felsteel' WHERE ID=569;
UPDATE dbc_itemset SET Name_Lang_enGB='The Unyielding' WHERE ID=570;
UPDATE dbc_itemset SET Name_Lang_enGB='Whitemend Wisdom' WHERE ID=571;
UPDATE dbc_itemset SET Name_Lang_enGB='Battlecast Garb' WHERE ID=572;
UPDATE dbc_itemset SET Name_Lang_enGB='Fel Skin' WHERE ID=573;
UPDATE dbc_itemset SET Name_Lang_enGB='Strength of the Clefthoof' WHERE ID=574;
UPDATE dbc_itemset SET Name_Lang_enGB='Felstalker Armor' WHERE ID=575;
UPDATE dbc_itemset SET Name_Lang_enGB='Fury of the Nether' WHERE ID=576;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Vestments' WHERE ID=577;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Earthshaker' WHERE ID=578;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Regalia' WHERE ID=579;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Thunderfist' WHERE ID=580;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Raiment' WHERE ID=581;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Aegis' WHERE ID=582;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Vindication' WHERE ID=583;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Sanctuary' WHERE ID=584;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Wildhide' WHERE ID=585;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Pursuit' WHERE ID=586;
UPDATE dbc_itemset SET Name_Lang_enGB='High Warlord''s Aegis' WHERE ID=587;
UPDATE dbc_itemset SET Name_Lang_enGB='High Warlord''s Battlegear' WHERE ID=588;
UPDATE dbc_itemset SET Name_Lang_enGB='Grand Marshal''s Aegis' WHERE ID=589;
UPDATE dbc_itemset SET Name_Lang_enGB='Grand Marshal''s Battlegear' WHERE ID=590;
UPDATE dbc_itemset SET Name_Lang_enGB='Grand Marshal''s Dreadgear' WHERE ID=591;
UPDATE dbc_itemset SET Name_Lang_enGB='High Warlord''s Dreadgear' WHERE ID=592;
UPDATE dbc_itemset SET Name_Lang_enGB='Grand Marshal''s Earthshaker' WHERE ID=593;
UPDATE dbc_itemset SET Name_Lang_enGB='High Warlord''s Earthshaker' WHERE ID=594;
UPDATE dbc_itemset SET Name_Lang_enGB='Grand Marshal''s Pursuit' WHERE ID=595;
UPDATE dbc_itemset SET Name_Lang_enGB='High Warlord''s Pursuit' WHERE ID=596;
UPDATE dbc_itemset SET Name_Lang_enGB='Grand Marshal''s Raiment' WHERE ID=597;
UPDATE dbc_itemset SET Name_Lang_enGB='High Warlord''s Raiment' WHERE ID=598;
UPDATE dbc_itemset SET Name_Lang_enGB='Grand Marshal''s Regalia' WHERE ID=599;
UPDATE dbc_itemset SET Name_Lang_enGB='High Warlord''s Regalia' WHERE ID=600;
UPDATE dbc_itemset SET Name_Lang_enGB='Grand Marshal''s Sanctuary' WHERE ID=601;
UPDATE dbc_itemset SET Name_Lang_enGB='High Warlord''s Sanctuary' WHERE ID=602;
UPDATE dbc_itemset SET Name_Lang_enGB='Grand Marshal''s Thunderfist' WHERE ID=603;
UPDATE dbc_itemset SET Name_Lang_enGB='High Warlord''s Thunderfist' WHERE ID=604;
UPDATE dbc_itemset SET Name_Lang_enGB='Grand Marshal''s Vestments' WHERE ID=605;
UPDATE dbc_itemset SET Name_Lang_enGB='High Warlord''s Vestments' WHERE ID=606;
UPDATE dbc_itemset SET Name_Lang_enGB='Grand Marshal''s Vindication' WHERE ID=607;
UPDATE dbc_itemset SET Name_Lang_enGB='High Warlord''s Vindication' WHERE ID=608;
UPDATE dbc_itemset SET Name_Lang_enGB='Grand Marshal''s Wildhide' WHERE ID=609;
UPDATE dbc_itemset SET Name_Lang_enGB='High Warlord''s Wildhide' WHERE ID=610;
UPDATE dbc_itemset SET Name_Lang_enGB='Felscale Armor' WHERE ID=611;
UPDATE dbc_itemset SET Name_Lang_enGB='Scaled Draenic Armor' WHERE ID=612;
UPDATE dbc_itemset SET Name_Lang_enGB='Thick Draenic Armor' WHERE ID=613;
UPDATE dbc_itemset SET Name_Lang_enGB='Wild Draenish Armor' WHERE ID=614;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Felshroud' WHERE ID=615;
UPDATE dbc_itemset SET Name_Lang_enGB='Netherscale Armor' WHERE ID=616;
UPDATE dbc_itemset SET Name_Lang_enGB='Netherstrike Armor' WHERE ID=617;
UPDATE dbc_itemset SET Name_Lang_enGB='Windhawk Armor' WHERE ID=618;
UPDATE dbc_itemset SET Name_Lang_enGB='Primal Intent' WHERE ID=619;
UPDATE dbc_itemset SET Name_Lang_enGB='Assassination Armor' WHERE ID=620;
UPDATE dbc_itemset SET Name_Lang_enGB='Netherblade' WHERE ID=621;
UPDATE dbc_itemset SET Name_Lang_enGB='Deathmantle' WHERE ID=622;
UPDATE dbc_itemset SET Name_Lang_enGB='Righteous Armor' WHERE ID=623;
UPDATE dbc_itemset SET Name_Lang_enGB='Justicar Raiment' WHERE ID=624;
UPDATE dbc_itemset SET Name_Lang_enGB='Justicar Armor' WHERE ID=625;
UPDATE dbc_itemset SET Name_Lang_enGB='Justicar Battlegear' WHERE ID=626;
UPDATE dbc_itemset SET Name_Lang_enGB='Crystalforge Raiment' WHERE ID=627;
UPDATE dbc_itemset SET Name_Lang_enGB='Crystalforge Armor' WHERE ID=628;
UPDATE dbc_itemset SET Name_Lang_enGB='Crystalforge Battlegear' WHERE ID=629;
UPDATE dbc_itemset SET Name_Lang_enGB='Tidefury Raiment' WHERE ID=630;
UPDATE dbc_itemset SET Name_Lang_enGB='Cyclone Raiment' WHERE ID=631;
UPDATE dbc_itemset SET Name_Lang_enGB='Cyclone Regalia' WHERE ID=632;
UPDATE dbc_itemset SET Name_Lang_enGB='Cyclone Harness' WHERE ID=633;
UPDATE dbc_itemset SET Name_Lang_enGB='Cataclysm Raiment' WHERE ID=634;
UPDATE dbc_itemset SET Name_Lang_enGB='Cataclysm Regalia' WHERE ID=635;
UPDATE dbc_itemset SET Name_Lang_enGB='Cataclysm Harness' WHERE ID=636;
UPDATE dbc_itemset SET Name_Lang_enGB='Moonglade Raiment' WHERE ID=637;
UPDATE dbc_itemset SET Name_Lang_enGB='Malorne Raiment' WHERE ID=638;
UPDATE dbc_itemset SET Name_Lang_enGB='Malorne Regalia' WHERE ID=639;
UPDATE dbc_itemset SET Name_Lang_enGB='Malorne Harness' WHERE ID=640;
UPDATE dbc_itemset SET Name_Lang_enGB='Nordrassil Harness' WHERE ID=641;
UPDATE dbc_itemset SET Name_Lang_enGB='Nordrassil Raiment' WHERE ID=642;
UPDATE dbc_itemset SET Name_Lang_enGB='Nordrassil Regalia' WHERE ID=643;
UPDATE dbc_itemset SET Name_Lang_enGB='Oblivion Raiment' WHERE ID=644;
UPDATE dbc_itemset SET Name_Lang_enGB='Voidheart Raiment' WHERE ID=645;
UPDATE dbc_itemset SET Name_Lang_enGB='Corruptor Raiment' WHERE ID=646;
UPDATE dbc_itemset SET Name_Lang_enGB='Incanter''s Regalia' WHERE ID=647;
UPDATE dbc_itemset SET Name_Lang_enGB='Aldor Regalia' WHERE ID=648;
UPDATE dbc_itemset SET Name_Lang_enGB='Tirisfal Regalia' WHERE ID=649;
UPDATE dbc_itemset SET Name_Lang_enGB='Beast Lord Armor' WHERE ID=650;
UPDATE dbc_itemset SET Name_Lang_enGB='Demon Stalker Armor' WHERE ID=651;
UPDATE dbc_itemset SET Name_Lang_enGB='Rift Stalker Armor' WHERE ID=652;
UPDATE dbc_itemset SET Name_Lang_enGB='Bold Armor' WHERE ID=653;
UPDATE dbc_itemset SET Name_Lang_enGB='Warbringer Armor' WHERE ID=654;
UPDATE dbc_itemset SET Name_Lang_enGB='Warbringer Battlegear' WHERE ID=655;
UPDATE dbc_itemset SET Name_Lang_enGB='Destroyer Armor' WHERE ID=656;
UPDATE dbc_itemset SET Name_Lang_enGB='Destroyer Battlegear' WHERE ID=657;
UPDATE dbc_itemset SET Name_Lang_enGB='Mana-Etched Regalia' WHERE ID=658;
UPDATE dbc_itemset SET Name_Lang_enGB='Wastewalker Armor' WHERE ID=659;
UPDATE dbc_itemset SET Name_Lang_enGB='Desolation Battlegear' WHERE ID=660;
UPDATE dbc_itemset SET Name_Lang_enGB='Doomplate Battlegear' WHERE ID=661;
UPDATE dbc_itemset SET Name_Lang_enGB='Hallowed Raiment' WHERE ID=662;
UPDATE dbc_itemset SET Name_Lang_enGB='Incarnate Raiment' WHERE ID=663;
UPDATE dbc_itemset SET Name_Lang_enGB='Incarnate Regalia' WHERE ID=664;
UPDATE dbc_itemset SET Name_Lang_enGB='Avatar Raiment' WHERE ID=665;
UPDATE dbc_itemset SET Name_Lang_enGB='Avatar Regalia' WHERE ID=666;
UPDATE dbc_itemset SET Name_Lang_enGB='The Twin Stars' WHERE ID=667;
UPDATE dbc_itemset SET Name_Lang_enGB='Slayer''s Armor' WHERE ID=668;
UPDATE dbc_itemset SET Name_Lang_enGB='Gronnstalker''s Armor' WHERE ID=669;
UPDATE dbc_itemset SET Name_Lang_enGB='Malefic Raiment' WHERE ID=670;
UPDATE dbc_itemset SET Name_Lang_enGB='Tempest Regalia' WHERE ID=671;
UPDATE dbc_itemset SET Name_Lang_enGB='Onslaught Battlegear' WHERE ID=672;
UPDATE dbc_itemset SET Name_Lang_enGB='Onslaught Armor' WHERE ID=673;
UPDATE dbc_itemset SET Name_Lang_enGB='Absolution Regalia' WHERE ID=674;
UPDATE dbc_itemset SET Name_Lang_enGB='Vestments of Absolution' WHERE ID=675;
UPDATE dbc_itemset SET Name_Lang_enGB='Thunderheart Harness' WHERE ID=676;
UPDATE dbc_itemset SET Name_Lang_enGB='Thunderheart Regalia' WHERE ID=677;
UPDATE dbc_itemset SET Name_Lang_enGB='Thunderheart Raiment' WHERE ID=678;
UPDATE dbc_itemset SET Name_Lang_enGB='Lightbringer Armor' WHERE ID=679;
UPDATE dbc_itemset SET Name_Lang_enGB='Lightbringer Battlegear' WHERE ID=680;
UPDATE dbc_itemset SET Name_Lang_enGB='Lightbringer Raiment' WHERE ID=681;
UPDATE dbc_itemset SET Name_Lang_enGB='Skyshatter Harness' WHERE ID=682;
UPDATE dbc_itemset SET Name_Lang_enGB='Skyshatter Raiment' WHERE ID=683;
UPDATE dbc_itemset SET Name_Lang_enGB='Skyshatter Regalia' WHERE ID=684;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Refuge' WHERE ID=685;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Wartide' WHERE ID=686;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Investiture' WHERE ID=687;
UPDATE dbc_itemset SET Name_Lang_enGB='Grand Marshal''s Refuge' WHERE ID=688;
UPDATE dbc_itemset SET Name_Lang_enGB='High Warlord''s Refuge' WHERE ID=689;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Redemption' WHERE ID=690;
UPDATE dbc_itemset SET Name_Lang_enGB='Grand Marshal''s Investiture' WHERE ID=691;
UPDATE dbc_itemset SET Name_Lang_enGB='High Warlord''s Investiture' WHERE ID=692;
UPDATE dbc_itemset SET Name_Lang_enGB='Grand Marshal''s Redemption' WHERE ID=693;
UPDATE dbc_itemset SET Name_Lang_enGB='High Warlord''s Redemption' WHERE ID=694;
UPDATE dbc_itemset SET Name_Lang_enGB='Grand Marshal''s Wartide' WHERE ID=695;
UPDATE dbc_itemset SET Name_Lang_enGB='High Warlord''s Wartide' WHERE ID=696;
UPDATE dbc_itemset SET Name_Lang_enGB='Champion''s Redoubt' WHERE ID=697;
UPDATE dbc_itemset SET Name_Lang_enGB='Warlord''s Aegis' WHERE ID=698;
UPDATE dbc_itemset SET Name_Lang_enGB='The Twin Blades of Azzinoth' WHERE ID=699;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Aegis' WHERE ID=700;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Battlegear' WHERE ID=701;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Dreadgear' WHERE ID=702;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Earthshaker' WHERE ID=703;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Felshroud' WHERE ID=704;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Investiture' WHERE ID=705;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Pursuit' WHERE ID=706;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Raiment' WHERE ID=707;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Redemption' WHERE ID=708;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Refuge' WHERE ID=709;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Regalia' WHERE ID=710;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Sanctuary' WHERE ID=711;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Thunderfist' WHERE ID=712;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Vestments' WHERE ID=713;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Vindication' WHERE ID=714;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Wartide' WHERE ID=715;
UPDATE dbc_itemset SET Name_Lang_enGB='Merciless Gladiator''s Wildhide' WHERE ID=716;
UPDATE dbc_itemset SET Name_Lang_enGB='Field Marshal''s Earthshaker' WHERE ID=717;
UPDATE dbc_itemset SET Name_Lang_enGB='Lieutenant Commander''s Earthshaker' WHERE ID=718;
UPDATE dbc_itemset SET Name_Lang_enGB='The Fists of Fury' WHERE ID=719;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Refuge' WHERE ID=720;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Sanctuary' WHERE ID=721;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Wildhide' WHERE ID=722;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Pursuit' WHERE ID=723;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Regalia' WHERE ID=724;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Redemption' WHERE ID=725;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Vindication' WHERE ID=726;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Aegis' WHERE ID=727;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Investiture' WHERE ID=728;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Raiment' WHERE ID=729;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Vestments' WHERE ID=730;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Wartide' WHERE ID=731;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Earthshaker' WHERE ID=732;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Thunderfist' WHERE ID=733;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Dreadgear' WHERE ID=734;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Felshroud' WHERE ID=735;
UPDATE dbc_itemset SET Name_Lang_enGB='Vengeful Gladiator''s Battlegear' WHERE ID=736;
UPDATE dbc_itemset SET Name_Lang_enGB='Latro''s Flurry' WHERE ID=737;
UPDATE dbc_itemset SET Name_Lang_enGB='Dreadweave Battlegear' WHERE ID=738;
UPDATE dbc_itemset SET Name_Lang_enGB='Mooncloth Battlegear' WHERE ID=739;
UPDATE dbc_itemset SET Name_Lang_enGB='Satin Battlegear' WHERE ID=740;
UPDATE dbc_itemset SET Name_Lang_enGB='Evoker''s Silk Battlegear' WHERE ID=741;
UPDATE dbc_itemset SET Name_Lang_enGB='Dragonhide Battlegear' WHERE ID=742;
UPDATE dbc_itemset SET Name_Lang_enGB='Wyrmhide Battlegear' WHERE ID=743;
UPDATE dbc_itemset SET Name_Lang_enGB='Kodohide Battlegear' WHERE ID=744;
UPDATE dbc_itemset SET Name_Lang_enGB='Opportunist''s Battlegear' WHERE ID=745;
UPDATE dbc_itemset SET Name_Lang_enGB='Seer''s Mail Battlegear' WHERE ID=746;
UPDATE dbc_itemset SET Name_Lang_enGB='Seer''s Ringmail Battlegear' WHERE ID=747;
UPDATE dbc_itemset SET Name_Lang_enGB='Seer''s Linked Battlegear' WHERE ID=748;
UPDATE dbc_itemset SET Name_Lang_enGB='Stalker''s Chain Battlegear' WHERE ID=749;
UPDATE dbc_itemset SET Name_Lang_enGB='Savage Plate Battlegear' WHERE ID=750;
UPDATE dbc_itemset SET Name_Lang_enGB='Crusader''s Ornamented Battlegear' WHERE ID=751;
UPDATE dbc_itemset SET Name_Lang_enGB='Crusader''s Scaled Battlegear' WHERE ID=752;
UPDATE dbc_itemset SET Name_Lang_enGB='Borean Embrace' WHERE ID=754;
UPDATE dbc_itemset SET Name_Lang_enGB='Nerubian Hive' WHERE ID=755;
UPDATE dbc_itemset SET Name_Lang_enGB='Frostscale Binding' WHERE ID=756;
UPDATE dbc_itemset SET Name_Lang_enGB='Iceborne Embrace' WHERE ID=757;
UPDATE dbc_itemset SET Name_Lang_enGB='Raine''s Revenge' WHERE ID=759;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Dreadplate' WHERE ID=760;
UPDATE dbc_itemset SET Name_Lang_enGB='Winter Garb' WHERE ID=761;
UPDATE dbc_itemset SET Name_Lang_enGB='Brewfest Garb' WHERE ID=762;
UPDATE dbc_itemset SET Name_Lang_enGB='Frostwoven Power' WHERE ID=763;
UPDATE dbc_itemset SET Name_Lang_enGB='Duskweaver' WHERE ID=764;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Battlegear' WHERE ID=765;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Vindication' WHERE ID=766;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Redemption' WHERE ID=767;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Desecration' WHERE ID=768;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Thunderfist' WHERE ID=769;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Earthshaker' WHERE ID=770;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Wartide' WHERE ID=771;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Pursuit' WHERE ID=772;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Refuge' WHERE ID=773;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Wildhide' WHERE ID=774;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Sanctuary' WHERE ID=775;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Vestments' WHERE ID=776;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Investiture' WHERE ID=777;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Raiment' WHERE ID=778;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Regalia' WHERE ID=779;
UPDATE dbc_itemset SET Name_Lang_enGB='Gladiator''s Felshroud' WHERE ID=780;
UPDATE dbc_itemset SET Name_Lang_enGB='Blessed Regalia of Undead Cleansing' WHERE ID=781;
UPDATE dbc_itemset SET Name_Lang_enGB='Undead Slayer''s Blessed Armor' WHERE ID=782;
UPDATE dbc_itemset SET Name_Lang_enGB='Blessed Garb of the Undead Slayer' WHERE ID=783;
UPDATE dbc_itemset SET Name_Lang_enGB='Blessed Battlegear of Undead Slaying' WHERE ID=784;
UPDATE dbc_itemset SET Name_Lang_enGB='Midsummer Reveler' WHERE ID=785;
UPDATE dbc_itemset SET Name_Lang_enGB='Dreadnaught Plate' WHERE ID=787;
UPDATE dbc_itemset SET Name_Lang_enGB='Dreadnaught Battlegear' WHERE ID=788;
UPDATE dbc_itemset SET Name_Lang_enGB='Redemption Battlegear' WHERE ID=789;
UPDATE dbc_itemset SET Name_Lang_enGB='Redemption Regalia' WHERE ID=790;
UPDATE dbc_itemset SET Name_Lang_enGB='Redemption Plate' WHERE ID=791;
UPDATE dbc_itemset SET Name_Lang_enGB='Scourgeborne Battlegear' WHERE ID=792;
UPDATE dbc_itemset SET Name_Lang_enGB='Scourgeborne Plate' WHERE ID=793;
UPDATE dbc_itemset SET Name_Lang_enGB='Cryptstalker Battlegear' WHERE ID=794;
UPDATE dbc_itemset SET Name_Lang_enGB='Earthshatter Battlegear' WHERE ID=795;
UPDATE dbc_itemset SET Name_Lang_enGB='Earthshatter Garb' WHERE ID=796;
UPDATE dbc_itemset SET Name_Lang_enGB='Earthshatter Regalia' WHERE ID=797;
UPDATE dbc_itemset SET Name_Lang_enGB='Dreamwalker Battlegear' WHERE ID=798;
UPDATE dbc_itemset SET Name_Lang_enGB='Dreamwalker Regalia' WHERE ID=799;
UPDATE dbc_itemset SET Name_Lang_enGB='Dreamwalker Garb' WHERE ID=800;
UPDATE dbc_itemset SET Name_Lang_enGB='Bonescythe Battlegear' WHERE ID=801;
UPDATE dbc_itemset SET Name_Lang_enGB='Plagueheart Garb' WHERE ID=802;
UPDATE dbc_itemset SET Name_Lang_enGB='Frostfire Garb' WHERE ID=803;
UPDATE dbc_itemset SET Name_Lang_enGB='Regalia of Faith' WHERE ID=804;
UPDATE dbc_itemset SET Name_Lang_enGB='Garb of Faith' WHERE ID=805;
UPDATE dbc_itemset SET Name_Lang_enGB='Spring Tuxedo' WHERE ID=812;
UPDATE dbc_itemset SET Name_Lang_enGB='Eviscerator''s Battlegear' WHERE ID=813;
UPDATE dbc_itemset SET Name_Lang_enGB='Ornate Saronite Battlegear' WHERE ID=814;
UPDATE dbc_itemset SET Name_Lang_enGB='Overcaster Battlegear' WHERE ID=815;
UPDATE dbc_itemset SET Name_Lang_enGB='Savage Saronite Battlegear' WHERE ID=816;
UPDATE dbc_itemset SET Name_Lang_enGB='Stormhide Battlegear' WHERE ID=817;
UPDATE dbc_itemset SET Name_Lang_enGB='Swiftarrow Battlegear' WHERE ID=818;
UPDATE dbc_itemset SET Name_Lang_enGB='Frostsavage Battlegear' WHERE ID=819;
UPDATE dbc_itemset SET Name_Lang_enGB='Aegis Battlegear' WHERE ID=820;
UPDATE dbc_itemset SET Name_Lang_enGB='Aegis Plate' WHERE ID=821;
UPDATE dbc_itemset SET Name_Lang_enGB='Aegis Regalia' WHERE ID=822;
UPDATE dbc_itemset SET Name_Lang_enGB='Worldbreaker Battlegear' WHERE ID=823;
UPDATE dbc_itemset SET Name_Lang_enGB='Worldbreaker Garb' WHERE ID=824;
UPDATE dbc_itemset SET Name_Lang_enGB='Worldbreaker Regalia' WHERE ID=825;
UPDATE dbc_itemset SET Name_Lang_enGB='Terrorblade Battlegear' WHERE ID=826;
UPDATE dbc_itemset SET Name_Lang_enGB='Nightsong Battlegear' WHERE ID=827;
UPDATE dbc_itemset SET Name_Lang_enGB='Nightsong Garb' WHERE ID=828;
UPDATE dbc_itemset SET Name_Lang_enGB='Nightsong Regalia' WHERE ID=829;
UPDATE dbc_itemset SET Name_Lang_enGB='Siegebreaker Battlegear' WHERE ID=830;
UPDATE dbc_itemset SET Name_Lang_enGB='Siegebreaker Plate' WHERE ID=831;
UPDATE dbc_itemset SET Name_Lang_enGB='Sanctification Garb' WHERE ID=832;
UPDATE dbc_itemset SET Name_Lang_enGB='Sanctification Regalia' WHERE ID=833;
UPDATE dbc_itemset SET Name_Lang_enGB='Darkruned Battlegear' WHERE ID=834;
UPDATE dbc_itemset SET Name_Lang_enGB='Darkruned Plate' WHERE ID=835;
UPDATE dbc_itemset SET Name_Lang_enGB='Kirin Tor Garb' WHERE ID=836;
UPDATE dbc_itemset SET Name_Lang_enGB='Deathbringer Garb' WHERE ID=837;
UPDATE dbc_itemset SET Name_Lang_enGB='Scourgestalker Battlegear' WHERE ID=838;
UPDATE dbc_itemset SET Name_Lang_enGB='Khadgar''s Regalia' WHERE ID=843;
UPDATE dbc_itemset SET Name_Lang_enGB='Sunstrider''s Regalia' WHERE ID=844;
UPDATE dbc_itemset SET Name_Lang_enGB='Gul''dan''s Regalia' WHERE ID=845;
UPDATE dbc_itemset SET Name_Lang_enGB='Kel''Thuzad''s Regalia' WHERE ID=846;
UPDATE dbc_itemset SET Name_Lang_enGB='Velen''s Raiment' WHERE ID=847;
UPDATE dbc_itemset SET Name_Lang_enGB='Zabra''s Raiment' WHERE ID=848;
UPDATE dbc_itemset SET Name_Lang_enGB='Velen''s Regalia' WHERE ID=849;
UPDATE dbc_itemset SET Name_Lang_enGB='Zabra''s Regalia' WHERE ID=850;
UPDATE dbc_itemset SET Name_Lang_enGB='Malfurion''s Garb' WHERE ID=851;
UPDATE dbc_itemset SET Name_Lang_enGB='Runetotem''s Garb' WHERE ID=852;
UPDATE dbc_itemset SET Name_Lang_enGB='Malfurion''s Regalia' WHERE ID=853;
UPDATE dbc_itemset SET Name_Lang_enGB='Runetotem''s Regalia' WHERE ID=854;
UPDATE dbc_itemset SET Name_Lang_enGB='Malfurion''s Battlegear' WHERE ID=855;
UPDATE dbc_itemset SET Name_Lang_enGB='Runetotem''s Battlegear' WHERE ID=856;
UPDATE dbc_itemset SET Name_Lang_enGB='VanCleef''s Battlegear' WHERE ID=857;
UPDATE dbc_itemset SET Name_Lang_enGB='Garona''s Battlegear' WHERE ID=858;
UPDATE dbc_itemset SET Name_Lang_enGB='Windrunner''s Battlegear' WHERE ID=859;
UPDATE dbc_itemset SET Name_Lang_enGB='Windrunner''s Pursuit' WHERE ID=860;
UPDATE dbc_itemset SET Name_Lang_enGB='Nobundo''s Garb' WHERE ID=861;
UPDATE dbc_itemset SET Name_Lang_enGB='Thrall''s Garb' WHERE ID=862;
UPDATE dbc_itemset SET Name_Lang_enGB='Thrall''s Regalia' WHERE ID=863;
UPDATE dbc_itemset SET Name_Lang_enGB='Nobundo''s Regalia' WHERE ID=864;
UPDATE dbc_itemset SET Name_Lang_enGB='Nobundo''s Battlegear' WHERE ID=865;
UPDATE dbc_itemset SET Name_Lang_enGB='Thrall''s Battlegear' WHERE ID=866;
UPDATE dbc_itemset SET Name_Lang_enGB='Wrynn''s Battlegear' WHERE ID=867;
UPDATE dbc_itemset SET Name_Lang_enGB='Hellscream''s Battlegear' WHERE ID=868;
UPDATE dbc_itemset SET Name_Lang_enGB='Wrynn''s Plate' WHERE ID=869;
UPDATE dbc_itemset SET Name_Lang_enGB='Hellscream''s Plate' WHERE ID=870;
UPDATE dbc_itemset SET Name_Lang_enGB='Thassarian''s Battlegear' WHERE ID=871;
UPDATE dbc_itemset SET Name_Lang_enGB='Koltira''s Battlegear' WHERE ID=872;
UPDATE dbc_itemset SET Name_Lang_enGB='Thassarian''s Plate' WHERE ID=873;
UPDATE dbc_itemset SET Name_Lang_enGB='Koltira''s Plate' WHERE ID=874;
UPDATE dbc_itemset SET Name_Lang_enGB='Turalyon''s Garb' WHERE ID=875;
UPDATE dbc_itemset SET Name_Lang_enGB='Liadrin''s Garb' WHERE ID=876;
UPDATE dbc_itemset SET Name_Lang_enGB='Turalyon''s Battlegear' WHERE ID=877;
UPDATE dbc_itemset SET Name_Lang_enGB='Liadrin''s Battlegear' WHERE ID=878;
UPDATE dbc_itemset SET Name_Lang_enGB='Turalyon''s Plate' WHERE ID=879;
UPDATE dbc_itemset SET Name_Lang_enGB='Liadrin''s Plate' WHERE ID=880;
UPDATE dbc_itemset SET Name_Lang_enGB='Purified Shard of the Gods' WHERE ID=881;
UPDATE dbc_itemset SET Name_Lang_enGB='Shiny Shard of the Gods' WHERE ID=882;
UPDATE dbc_itemset SET Name_Lang_enGB='Bloodmage''s Regalia' WHERE ID=883;
UPDATE dbc_itemset SET Name_Lang_enGB='Dark Coven''s Regalia' WHERE ID=884;
UPDATE dbc_itemset SET Name_Lang_enGB='Crimson Acolyte''s Raiment' WHERE ID=885;
UPDATE dbc_itemset SET Name_Lang_enGB='Crimson Acolyte''s Regalia' WHERE ID=886;
UPDATE dbc_itemset SET Name_Lang_enGB='Lasherweave Garb' WHERE ID=887;
UPDATE dbc_itemset SET Name_Lang_enGB='Lasherweave Regalia' WHERE ID=888;
UPDATE dbc_itemset SET Name_Lang_enGB='Lasherweave Battlegear' WHERE ID=889;
UPDATE dbc_itemset SET Name_Lang_enGB='Shadowblade''s Battlegear' WHERE ID=890;
UPDATE dbc_itemset SET Name_Lang_enGB='Ahn''Kahar Blood Hunter''s Battlegear' WHERE ID=891;
UPDATE dbc_itemset SET Name_Lang_enGB='Frost Witch''s Garb' WHERE ID=892;
UPDATE dbc_itemset SET Name_Lang_enGB='Frost Witch''s Regalia' WHERE ID=893;
UPDATE dbc_itemset SET Name_Lang_enGB='Frost Witch''s Battlegear' WHERE ID=894;
UPDATE dbc_itemset SET Name_Lang_enGB='Ymirjar Lord''s Battlegear' WHERE ID=895;
UPDATE dbc_itemset SET Name_Lang_enGB='Ymirjar Lord''s Plate' WHERE ID=896;
UPDATE dbc_itemset SET Name_Lang_enGB='Scourgelord''s Battlegear' WHERE ID=897;
UPDATE dbc_itemset SET Name_Lang_enGB='Scourgelord''s Plate' WHERE ID=898;
UPDATE dbc_itemset SET Name_Lang_enGB='Lightsworn Garb' WHERE ID=899;
UPDATE dbc_itemset SET Name_Lang_enGB='Lightsworn Battlegear' WHERE ID=900;
UPDATE dbc_itemset SET Name_Lang_enGB='Lightsworn Plate' WHERE ID=901;
