UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Jeweler''s Gems' WHERE ID=2;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Healthstone' WHERE ID=3;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Mana Gem' WHERE ID=4;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Stormjewel' WHERE ID=6;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Enchanted Pearl' WHERE ID=7;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Binding Light' WHERE ID=8;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Binding Stone' WHERE ID=9;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Death''s Choice' WHERE ID=10;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Death''s Verdict' WHERE ID=11;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Eitrigg''s Oath' WHERE ID=12;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Fervor of the Frostborn' WHERE ID=13;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Fetish of Volatile Power' WHERE ID=14;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Juggernaut''s Vitality' WHERE ID=15;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Reign of the Dead' WHERE ID=16;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Reign of the Unliving' WHERE ID=17;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Satrina''s Impeding Scarab' WHERE ID=18;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Solace of the Defeated' WHERE ID=19;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Solace of the Fallen' WHERE ID=20;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Talisman of Volatile Power' WHERE ID=21;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Vengeance of the Forsaken' WHERE ID=22;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Victor''s Call' WHERE ID=23;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Band of Callous Aggression' WHERE ID=24;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Band of Deplorable Violence' WHERE ID=25;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Band of the Traitor King' WHERE ID=26;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Band of the Twin Val''kyr' WHERE ID=27;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Band of the Violent Temperment' WHERE ID=28;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Carnivorous Band' WHERE ID=29;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Circle of the Darkmender' WHERE ID=30;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Firestorm Band' WHERE ID=31;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Firestorm Ring' WHERE ID=32;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Gormok''s Band' WHERE ID=33;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Loop of the Twin Val''kyr' WHERE ID=34;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Lurid Manifestation' WHERE ID=35;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Planestalker Band' WHERE ID=36;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Planestalker Signet' WHERE ID=37;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Ring of Callous Aggression' WHERE ID=38;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Ring of Callous Aggression' WHERE ID=39;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Ring of the Darkmender' WHERE ID=40;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Ring of the Violent Temperament' WHERE ID=41;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Signet of the Traitor King' WHERE ID=42;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Test Ring Limit' WHERE ID=43;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Althor''s Abacus' WHERE ID=44;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Bauble of True Blood' WHERE ID=45;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Corpse Tongue Coin' WHERE ID=46;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Deathbringer''s Will' WHERE ID=47;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Dislodged Foreign Object' WHERE ID=48;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Phylactery of the Nameless Lich' WHERE ID=49;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Tiny Abomination in a Jar' WHERE ID=50;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Sindragosa''s Flawless Fang' WHERE ID=51;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Abomination''s Bloody Ring' WHERE ID=52;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Signet of Putrefaction' WHERE ID=53;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Cerise Coiled Ring' WHERE ID=54;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Rotface''s Rupturing Ring' WHERE ID=55;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Saurfang''s Cold-Forged Band' WHERE ID=56;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Seal of the Twilight Queen' WHERE ID=57;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Thrice Fanged Signet' WHERE ID=58;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Band of the Bone Colossus' WHERE ID=59;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Devium''s Eternally Cold Ring' WHERE ID=60;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Seal of Many Mouths' WHERE ID=61;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Frostbrood Sapphire Ring' WHERE ID=62;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Juggernaut Band' WHERE ID=63;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Loop of the Endless Labyrinth' WHERE ID=64;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Marrowgar''s Frigid Eye' WHERE ID=65;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Memory of Malygos' WHERE ID=66;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Might of Blight' WHERE ID=67;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Ring of Maddening Whispers' WHERE ID=68;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Ring of Rapid Ascent' WHERE ID=69;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Skeleton Lord''s Circle' WHERE ID=70;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Valanar''s Other Signet Ring' WHERE ID=71;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Incarnadine Band of Mending' WHERE ID=72;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Muradin''s Spyglass' WHERE ID=73;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Sliver of Pure Ice' WHERE ID=74;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Unidentifiable Organ' WHERE ID=75;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Whispering Fanged Skull' WHERE ID=76;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Twilight Scale' WHERE ID=77;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Ring of Phased Regeneration' WHERE ID=78;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Saviana''s Tribute' WHERE ID=79;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Signet of Twilight' WHERE ID=80;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Zarithrian''s Offering' WHERE ID=81;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Sharpened Twilight Scale' WHERE ID=82;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Petrified Twilight Scale' WHERE ID=83;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Glowing Twilight Scale' WHERE ID=84;
UPDATE dbc_itemlimitcategory SET Name_Lang_enGB='Charred Twilight Scale' WHERE ID=85;
