UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Monkey' WHERE ID=5;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Eagle' WHERE ID=6;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Bear' WHERE ID=7;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Whale' WHERE ID=8;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Owl' WHERE ID=9;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Gorilla' WHERE ID=10;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Falcon' WHERE ID=11;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Boar' WHERE ID=12;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Wolf' WHERE ID=13;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Tiger' WHERE ID=14;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Spirit' WHERE ID=15;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Stamina' WHERE ID=16;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Strength' WHERE ID=17;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Agility' WHERE ID=18;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Intellect' WHERE ID=19;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Power' WHERE ID=20;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Spell Power' WHERE ID=21;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Spell Power' WHERE ID=22;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Spell Power' WHERE ID=23;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Spell Power' WHERE ID=24;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Spell Power' WHERE ID=25;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Spell Power' WHERE ID=26;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Defense' WHERE ID=27;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Regeneration' WHERE ID=28;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Eluding' WHERE ID=29;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Concentration' WHERE ID=30;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Arcane Protection' WHERE ID=31;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Fire Protection' WHERE ID=32;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Frost Protection' WHERE ID=33;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Nature Protection' WHERE ID=34;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Shadow Protection' WHERE ID=35;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Sorcerer' WHERE ID=36;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Physician' WHERE ID=37;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Prophet' WHERE ID=38;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Invoker' WHERE ID=39;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Bandit' WHERE ID=40;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Beast' WHERE ID=41;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Hierophant' WHERE ID=42;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Soldier' WHERE ID=43;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Elder' WHERE ID=44;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Champion' WHERE ID=45;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Test' WHERE ID=46;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Blocking' WHERE ID=47;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Paladin Testing' WHERE ID=48;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Grove' WHERE ID=49;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Hunt' WHERE ID=50;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Mind' WHERE ID=51;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Crusade' WHERE ID=52;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Vision' WHERE ID=53;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Ancestor' WHERE ID=54;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Nightmare' WHERE ID=55;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Battle' WHERE ID=56;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Shadow' WHERE ID=57;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Sun' WHERE ID=58;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Moon' WHERE ID=59;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Wild' WHERE ID=60;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Spell Power' WHERE ID=61;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Strength' WHERE ID=62;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Agility' WHERE ID=63;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Power' WHERE ID=64;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Magic' WHERE ID=65;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Knight' WHERE ID=66;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Seer' WHERE ID=67;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Bear' WHERE ID=68;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Eagle' WHERE ID=69;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Ancestor' WHERE ID=70;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Bandit' WHERE ID=71;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Battle' WHERE ID=72;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Elder' WHERE ID=73;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Beast' WHERE ID=74;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Champion' WHERE ID=75;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Grove' WHERE ID=76;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Knight' WHERE ID=77;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Monkey' WHERE ID=78;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Moon' WHERE ID=79;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Wild' WHERE ID=80;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Whale' WHERE ID=81;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Vision' WHERE ID=82;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Sun' WHERE ID=83;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Stamina' WHERE ID=84;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Sorcerer' WHERE ID=85;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Soldier' WHERE ID=86;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Shadow' WHERE ID=87;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Foreseer' WHERE ID=88;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Thief' WHERE ID=89;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Necromancer' WHERE ID=90;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Marksman' WHERE ID=91;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of the Squire' WHERE ID=92;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Restoration' WHERE ID=93;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='' WHERE ID=94;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='' WHERE ID=95;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='' WHERE ID=96;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='' WHERE ID=97;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='' WHERE ID=98;
UPDATE dbc_itemrandomsuffix SET Name_Lang_enGB='of Speed' WHERE ID=99;
