UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Wailing Caverns', Description_Lang_enGB='' WHERE ID=1;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Scholomance', Description_Lang_enGB='' WHERE ID=2;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Ragefire Chasm', Description_Lang_enGB='' WHERE ID=4;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Deadmines', Description_Lang_enGB='' WHERE ID=6;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Shadowfang Keep', Description_Lang_enGB='' WHERE ID=8;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Blackfathom Deeps', Description_Lang_enGB='' WHERE ID=10;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Stormwind Stockade', Description_Lang_enGB='' WHERE ID=12;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Gnomeregan', Description_Lang_enGB='' WHERE ID=14;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Razorfen Kraul', Description_Lang_enGB='' WHERE ID=16;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Scarlet Monastery - Graveyard', Description_Lang_enGB='' WHERE ID=18;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Razorfen Downs', Description_Lang_enGB='' WHERE ID=20;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Uldaman', Description_Lang_enGB='' WHERE ID=22;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Zul''Farrak', Description_Lang_enGB='' WHERE ID=24;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Maraudon - Orange Crystals', Description_Lang_enGB='' WHERE ID=26;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Sunken Temple', Description_Lang_enGB='' WHERE ID=28;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Blackrock Depths - Prison', Description_Lang_enGB='' WHERE ID=30;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Lower Blackrock Spire', Description_Lang_enGB='' WHERE ID=32;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Dire Maul - East', Description_Lang_enGB='' WHERE ID=34;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Dire Maul - West', Description_Lang_enGB='' WHERE ID=36;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Dire Maul - North', Description_Lang_enGB='' WHERE ID=38;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Stratholme - Main Gate', Description_Lang_enGB='' WHERE ID=40;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Hellfire Ramparts', Description_Lang_enGB='' WHERE ID=136;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Blood Furnace', Description_Lang_enGB='' WHERE ID=137;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Shattered Halls', Description_Lang_enGB='' WHERE ID=138;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Slave Pens', Description_Lang_enGB='' WHERE ID=140;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Underbog', Description_Lang_enGB='' WHERE ID=146;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Steamvault', Description_Lang_enGB='' WHERE ID=147;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Mana-Tombs', Description_Lang_enGB='' WHERE ID=148;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Auchenai Crypts', Description_Lang_enGB='' WHERE ID=149;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Sethekk Halls', Description_Lang_enGB='' WHERE ID=150;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Shadow Labyrinth', Description_Lang_enGB='' WHERE ID=151;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Scarlet Monastery - Armory', Description_Lang_enGB='' WHERE ID=163;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Scarlet Monastery - Cathedral', Description_Lang_enGB='' WHERE ID=164;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Scarlet Monastery - Library', Description_Lang_enGB='' WHERE ID=165;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Escape From Durnholde', Description_Lang_enGB='' WHERE ID=170;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Black Morass', Description_Lang_enGB='' WHERE ID=171;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Mechanar', Description_Lang_enGB='' WHERE ID=172;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Botanica', Description_Lang_enGB='' WHERE ID=173;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Arcatraz', Description_Lang_enGB='' WHERE ID=174;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Magisters'' Terrace', Description_Lang_enGB='' WHERE ID=198;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Utgarde Keep', Description_Lang_enGB='' WHERE ID=202;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Utgarde Pinnacle', Description_Lang_enGB='' WHERE ID=203;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Azjol-Nerub', Description_Lang_enGB='' WHERE ID=204;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Oculus', Description_Lang_enGB='' WHERE ID=206;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Halls of Lightning', Description_Lang_enGB='' WHERE ID=207;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Halls of Stone', Description_Lang_enGB='' WHERE ID=208;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Culling of Stratholme', Description_Lang_enGB='' WHERE ID=209;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Drak''Tharon Keep', Description_Lang_enGB='' WHERE ID=214;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Gundrak', Description_Lang_enGB='' WHERE ID=216;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Ahn''kahet: The Old Kingdom', Description_Lang_enGB='' WHERE ID=218;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Violet Hold', Description_Lang_enGB='' WHERE ID=220;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Nexus', Description_Lang_enGB='' WHERE ID=225;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Trial of the Champion', Description_Lang_enGB='' WHERE ID=245;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Forge of Souls', Description_Lang_enGB='' WHERE ID=251;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Pit of Saron', Description_Lang_enGB='' WHERE ID=253;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Halls of Reflection', Description_Lang_enGB='' WHERE ID=255;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Maraudon - Purple Crystals', Description_Lang_enGB='' WHERE ID=272;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Maraudon - Pristine Waters', Description_Lang_enGB='' WHERE ID=273;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Stratholme - Service Entrance', Description_Lang_enGB='' WHERE ID=274;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Blackrock Depths - Upper City', Description_Lang_enGB='' WHERE ID=276;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Headless Horseman', Description_Lang_enGB='Defeat the mad Headless Horseman before he burns down every last settlement in Azeroth.' WHERE ID=285;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Frost Lord Ahune', Description_Lang_enGB='Defeat Ahune, the Frost Lord, before he fully manifests in Azeroth and puts an end to Summer forever.' WHERE ID=286;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Coren Direbrew', Description_Lang_enGB='Defeat the jealous Coren Direbrew to stop his incessant attacks upon the Brewfest festivities.' WHERE ID=287;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Crown Chemical Co.', Description_Lang_enGB='Defeat the insidious undead apothecaries of the Crown Chemical Co. before they unleash their newest, horrific plague.' WHERE ID=288;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Zul''Gurub', Description_Lang_enGB='' WHERE ID=42;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Upper Blackrock Spire', Description_Lang_enGB='' WHERE ID=44;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Onyxia''s Lair', Description_Lang_enGB='' WHERE ID=46;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Molten Core', Description_Lang_enGB='' WHERE ID=48;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Blackwing Lair', Description_Lang_enGB='' WHERE ID=50;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Naxxramas', Description_Lang_enGB='' WHERE ID=159;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Ahn''Qiraj Ruins', Description_Lang_enGB='' WHERE ID=160;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Ahn''Qiraj Temple', Description_Lang_enGB='' WHERE ID=161;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Karazhan', Description_Lang_enGB='' WHERE ID=175;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Magtheridon''s Lair', Description_Lang_enGB='' WHERE ID=176;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Gruul''s Lair', Description_Lang_enGB='' WHERE ID=177;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Tempest Keep', Description_Lang_enGB='' WHERE ID=193;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Serpentshrine Cavern', Description_Lang_enGB='' WHERE ID=194;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Hyjal Past', Description_Lang_enGB='' WHERE ID=195;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Black Temple', Description_Lang_enGB='' WHERE ID=196;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Zul''Aman', Description_Lang_enGB='' WHERE ID=197;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Sunwell', Description_Lang_enGB='' WHERE ID=199;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Eye of Eternity', Description_Lang_enGB='' WHERE ID=223;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Obsidian Sanctum', Description_Lang_enGB='' WHERE ID=224;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Naxxramas', Description_Lang_enGB='' WHERE ID=227;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Eye of Eternity', Description_Lang_enGB='' WHERE ID=237;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Obsidian Sanctum', Description_Lang_enGB='' WHERE ID=238;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Vault of Archavon', Description_Lang_enGB='' WHERE ID=239;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Vault of Archavon', Description_Lang_enGB='' WHERE ID=240;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Ulduar', Description_Lang_enGB='' WHERE ID=243;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Ulduar', Description_Lang_enGB='' WHERE ID=244;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Trial of the Crusader', Description_Lang_enGB='' WHERE ID=246;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Trial of the Grand Crusader', Description_Lang_enGB='' WHERE ID=247;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Trial of the Crusader', Description_Lang_enGB='' WHERE ID=248;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Trial of the Grand Crusader', Description_Lang_enGB='' WHERE ID=250;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Onyxia''s Lair', Description_Lang_enGB='' WHERE ID=257;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Icecrown Citadel', Description_Lang_enGB='' WHERE ID=279;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Icecrown Citadel', Description_Lang_enGB='' WHERE ID=280;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Ruby Sanctum', Description_Lang_enGB='' WHERE ID=293;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Ruby Sanctum', Description_Lang_enGB='' WHERE ID=294;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Elwynn Forest', Description_Lang_enGB='' WHERE ID=58;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Westfall', Description_Lang_enGB='' WHERE ID=60;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Duskwood', Description_Lang_enGB='' WHERE ID=62;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Dun Morogh', Description_Lang_enGB='' WHERE ID=64;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Loch Modan', Description_Lang_enGB='' WHERE ID=66;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Wetlands', Description_Lang_enGB='' WHERE ID=68;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Stranglethorn Vale', Description_Lang_enGB='' WHERE ID=70;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Blasted Lands', Description_Lang_enGB='' WHERE ID=72;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Swamp of Sorrows', Description_Lang_enGB='' WHERE ID=74;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Redridge Mountains', Description_Lang_enGB='' WHERE ID=76;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Burning Steppes', Description_Lang_enGB='' WHERE ID=78;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Searing Gorge', Description_Lang_enGB='' WHERE ID=80;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Badlands', Description_Lang_enGB='' WHERE ID=82;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Arathi Highlands', Description_Lang_enGB='' WHERE ID=84;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Hillsbrad Foothills', Description_Lang_enGB='' WHERE ID=86;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Hinterlands', Description_Lang_enGB='' WHERE ID=88;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Western Plaguelands', Description_Lang_enGB='' WHERE ID=90;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Eastern Plaguelands', Description_Lang_enGB='' WHERE ID=92;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Tirisfal Glades', Description_Lang_enGB='' WHERE ID=94;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Silverpine Forest', Description_Lang_enGB='' WHERE ID=96;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Alterac Mountains', Description_Lang_enGB='' WHERE ID=98;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Durotar', Description_Lang_enGB='' WHERE ID=100;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Mulgore', Description_Lang_enGB='' WHERE ID=102;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Barrens', Description_Lang_enGB='' WHERE ID=104;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Stonetalon Mountains', Description_Lang_enGB='' WHERE ID=106;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Thousand Needles', Description_Lang_enGB='' WHERE ID=108;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Desolace', Description_Lang_enGB='' WHERE ID=110;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Feralas', Description_Lang_enGB='' WHERE ID=112;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Dustwallow Marsh', Description_Lang_enGB='' WHERE ID=114;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Tanaris', Description_Lang_enGB='' WHERE ID=116;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Un''Goro Crater', Description_Lang_enGB='' WHERE ID=118;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Silithus', Description_Lang_enGB='' WHERE ID=120;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Teldrassil', Description_Lang_enGB='' WHERE ID=122;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Darkshore', Description_Lang_enGB='' WHERE ID=124;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Ashenvale', Description_Lang_enGB='' WHERE ID=126;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Felwood', Description_Lang_enGB='' WHERE ID=128;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Azshara', Description_Lang_enGB='' WHERE ID=130;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Winterspring', Description_Lang_enGB='' WHERE ID=132;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Hellfire Peninsula', Description_Lang_enGB='' WHERE ID=152;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Zangarmarsh', Description_Lang_enGB='' WHERE ID=153;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Terokkar Forest', Description_Lang_enGB='' WHERE ID=154;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Nagrand', Description_Lang_enGB='' WHERE ID=155;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Shadowmoon Valley', Description_Lang_enGB='' WHERE ID=156;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Blade''s Edge Mountains', Description_Lang_enGB='' WHERE ID=157;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Netherstorm', Description_Lang_enGB='' WHERE ID=158;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Eversong Woods', Description_Lang_enGB='' WHERE ID=166;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Azuremyst Isle', Description_Lang_enGB='' WHERE ID=167;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Ghostlands', Description_Lang_enGB='' WHERE ID=168;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Bloodmyst Isle', Description_Lang_enGB='' WHERE ID=169;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Isle of Quel''Danas', Description_Lang_enGB='' WHERE ID=200;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Borean Tundra', Description_Lang_enGB='' WHERE ID=228;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Howling Fjord', Description_Lang_enGB='' WHERE ID=229;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Grizzly Hills', Description_Lang_enGB='' WHERE ID=230;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Dragonblight', Description_Lang_enGB='' WHERE ID=231;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Wintergrasp', Description_Lang_enGB='' WHERE ID=232;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Zul''Drak', Description_Lang_enGB='' WHERE ID=233;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Sholazar Basin', Description_Lang_enGB='' WHERE ID=234;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Storm Peaks', Description_Lang_enGB='' WHERE ID=235;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Icecrown', Description_Lang_enGB='' WHERE ID=236;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Auchenai Crypts', Description_Lang_enGB='' WHERE ID=178;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Mana-Tombs', Description_Lang_enGB='' WHERE ID=179;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Sethekk Halls', Description_Lang_enGB='' WHERE ID=180;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Shadow Labyrinth', Description_Lang_enGB='' WHERE ID=181;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Black Morass', Description_Lang_enGB='' WHERE ID=182;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Escape From Durnholde', Description_Lang_enGB='' WHERE ID=183;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Slave Pens', Description_Lang_enGB='' WHERE ID=184;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Steamvault', Description_Lang_enGB='' WHERE ID=185;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Underbog', Description_Lang_enGB='' WHERE ID=186;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Blood Furnace', Description_Lang_enGB='' WHERE ID=187;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Hellfire Ramparts', Description_Lang_enGB='' WHERE ID=188;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Shattered Halls', Description_Lang_enGB='' WHERE ID=189;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Arcatraz', Description_Lang_enGB='' WHERE ID=190;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Botanica', Description_Lang_enGB='' WHERE ID=191;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Mechanar', Description_Lang_enGB='' WHERE ID=192;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Magisters'' Terrace', Description_Lang_enGB='' WHERE ID=201;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Utgarde Pinnacle', Description_Lang_enGB='' WHERE ID=205;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Culling of Stratholme', Description_Lang_enGB='' WHERE ID=210;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Oculus', Description_Lang_enGB='' WHERE ID=211;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Halls of Lightning', Description_Lang_enGB='' WHERE ID=212;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Halls of Stone', Description_Lang_enGB='' WHERE ID=213;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Drak''Tharon Keep', Description_Lang_enGB='' WHERE ID=215;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Gundrak', Description_Lang_enGB='' WHERE ID=217;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Ahn''kahet: The Old Kingdom', Description_Lang_enGB='' WHERE ID=219;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Violet Hold', Description_Lang_enGB='' WHERE ID=221;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Nexus', Description_Lang_enGB='' WHERE ID=226;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Azjol-Nerub', Description_Lang_enGB='' WHERE ID=241;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Utgarde Keep', Description_Lang_enGB='' WHERE ID=242;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Trial of the Champion', Description_Lang_enGB='' WHERE ID=249;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='The Forge of Souls', Description_Lang_enGB='' WHERE ID=252;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Pit of Saron', Description_Lang_enGB='' WHERE ID=254;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Halls of Reflection', Description_Lang_enGB='' WHERE ID=256;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Random Classic Dungeon', Description_Lang_enGB='' WHERE ID=258;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Random Burning Crusade Dungeon', Description_Lang_enGB='' WHERE ID=259;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Random Burning Crusade Heroic', Description_Lang_enGB='' WHERE ID=260;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Random Lich King Dungeon', Description_Lang_enGB='' WHERE ID=261;
UPDATE dbc_lfgdungeons SET Name_Lang_enGB='Random Lich King Heroic', Description_Lang_enGB='' WHERE ID=262;
