UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='this is a test' WHERE ID=83;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=84;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=85;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='This small token will give no answers, but perhaps it will be of some amusement to you.' WHERE ID=86;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Hello there again.  I''m Gubber Blump.

I hope you are doing real well.  I hope you are still fishing too.  I love fishing.  The Blump family is known for fishing.  Here is a bauble, so that you can fish a little better.  I love using them when I fish.  Good luck, and thank you again for helping me catch them groupers from before.

Keep on fishing!

Gubber Blump' WHERE ID=87;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=88;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=89;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=90;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='This small token will give no answers, but perhaps it will be of some amusement to you.' WHERE ID=91;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=92;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Esteemed $N,$B$BI went through the stack of texts you brought me and I decoded the attached articles for you.  I carefully selected only those items which I thought would be of use.  It was quite problematic to get to a mailbox without being seen, but months of hiding in the desert have turned me into quite a sneak!$B$BI hope you enjoy these.$B$B-Ortell' WHERE ID=93;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Greetings, $N!$B$BI''m getting pretty good at sneaking into Cenarion Hold to use their mailbox.  Again, I''ve attached some items that might be of interest.  Hope something in there is of use to you!$B$B-Ortell' WHERE ID=94;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=95;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=96;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=97;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='It took much time to translate the high chief''s text. I was dismayed by what I found. High Chief Winterfall was in an extreme state of paranoia in his last days and was addicted to a substance he called "firewater." He believed that all creatures were his enemies. Well, I will let you read it for yourself -- I have included a translation of his words with this letter. If you are ever in need, please visit me again.' WHERE ID=98;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for renewing your membership with the Mechanical Engineering Guild, Associated!  We are delighted to have you as an active member.  Please accept this gift as a token of our appreciation for the wonderful contributions you continue to make to the world of gnome engineering.' WHERE ID=99;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for renewing your membership with the Mechanical Engineering Guild, Associated!  We are delighted to have you as an active member.  Please accept this gift as a token of our appreciation for the wonderful contributions you continue to make to the world of gnome engineering.' WHERE ID=100;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='My friend - though my arm is weary from the battle we continue to wage in the Plaguelands, it is always strong enough to pen this missive to a hero such as you.  It pleases me to know the aid you rendered us continues to yield benefits, ones we try to enact upon on a daily basis.

Should you find yourself in the Western Plaguelands soon, please stop by the Bulwark.  Your seasoned hand would be most welcomed in a cauldron run!

Yours in the Darkness:
High Executor Derrington' WHERE ID=101;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Ho Ho Hello, $N!  I hope you have a fantastic Feast of Winter Veil!$B$BYou were so nice in helping me out with my sweet tooth, that I wanted to send you a little something extra.  It''s a sampler of delicious Smokywood Pastures treats.  If you haven''t gotten any yet, be sure to do so before the season ends!$B$BSeasons Greetings...$BGreatfather Winter' WHERE ID=102;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for renewing your membership with the Goblin Experimental Engineering Korporation!  We are delighted to have you as an active member.  Please accept this gift as a token of our appreciation for the wonderful contributions you continue to make to the world of goblin engineering.' WHERE ID=103;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for renewing your membership with the Goblin Experimental Engineering Korporation!  We are delighted to have you as an active member.  Please accept this gift as a token of our appreciation for the wonderful contributions you continue to make to the world of goblin engineering.' WHERE ID=104;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='<UNUSED>', Body_Lang_enGB='This mail was sent to you because you signed up for Viagra! More text.' WHERE ID=105;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Those rabbits came back!  NO!  Oh, don''t bother coming back...' WHERE ID=106;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Greetings my friend - though my arm is weary from the battle we continue to wage in the ruins of Lordaeron, it is always strong enough to pen this missive to a hero such as you.  It pleases me to know the aid you lent us days ago continues to yield benefits, ones we try to enact upon on a daily basis.

Should you find yourself in the Western Plaguelands soon, please stop by the camp.  Your seasoned hand would be most welcomed in a cauldron run!

For Stormwind!
Commander Ashlam Valorfist' WHERE ID=107;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Ho ho hello again, $N!$B$BThough I and the good folks of Smokywood Pastures have been quite busy this season, I just wanted to send you something special along to you.  You''ll be happy to know what we unfroze Sacks out in the Alterac Mountains; he sends his best.$B$BIn freeing Sacks, we managed to develop a novelty device that I think you might enjoy.  You will need a snowball to power it, but I think you''ll enjoy it quite a bit!$B$BGreat-father Winter' WHERE ID=108;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Greetings, my friend!  I hope all is well with you.$B$BI thought I would take this time to thank you once again for aiding us in our struggle against Hakkar.  I look forward to seeing you soon as we rise to the challenge of defeating the Blood God.  Your absence here is sorely felt!$B$BI''ve enclosed an Honor Token as a small means of thanking you for what you have done for us.  Together we may finally destroy Hakkar once and for all!$B$BMay Zanza always bless you!$BVinchaxa, Servitor of Zanza' WHERE ID=109;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Esteemed $N,$B$BThe information you brought to my attention earlier has turned out to be extremely valuable.  Already I am calling for changes to our battle plans to account for the new importance we attribute to the Twilight''s Hammer presence.$B$BPlease accept this item as a small token of our gratitude.  I hope we can continue to count on you as a valiant ally in our fight in Silithus.$B$BSincerely,$B$BCommander Mar''alith' WHERE ID=110;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I bid you well, my friend.  I hope your fight for the Horde is a glorious one.  I certainly look forward to a time where others will look upon you with a legacy anywhere as rich and as treasured as the one of Grom Hellscream.$B$BI have not forgotten your act of kindness not only to me, but to the memory of Grom during the Harvest Festival.  I''ve sent you something I hope you might find to your liking.  Use it well.$B$BFor the Horde!$BJavnir' WHERE ID=111;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Greetings, young druid!

I''m quite proud of the effort you put into the training given to you thus far.  You should feel proud to have become one with the Claw.  More such lessons will be given; the next of your lessons will be available once you have reached at least 14th level.  When you are ready at that time, seek me out in the Cenarion Enclave of Darnassus.

Mathrengyl Bearwalker' WHERE ID=112;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I bid you well, my friend.  I hope your fight on behalf of the Alliance goes to your satisfaction.  I certainly look forward to a time where others will look upon you with a legacy anywhere as rich and as treasured as the one of Uther Lightbringer.$B$BI have not forgotten your act of kindness not only to me, but to the memory of Uther during the Harvest Festival.  I''ve sent you something I hope you might find to your liking.  Use it well.$B$BBy Bronzebeard''s Hammer,$BWagner' WHERE ID=113;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Greetings, young druid!

I''ve sent you this note as a reminder to check in with me from time to time as you advance through the ranks.  There is much to learn as a druid in the service of Cenarius, and I am only happy to help you along the way.  Soon you will be ready to learn about your aquatic form; seek me out when you reach 16th level and I''ll get you started along the path of knowledge.

Turak Runetotem' WHERE ID=114;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Greetings, young druid!

I''ve sent you this note as a reminder to check in with me from time to time as you advance through the ranks.  There is much to learn as a druid in the service of Cenarius, and I am only happy to help you along the way.  Soon you will be ready to learn about your aquatic form; seek me out when you reach 16th level and I''ll get you started along the path of knowledge.

Mathrengyl Bearwalker' WHERE ID=115;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Greetings, young druid!

I''m quite proud of the effort you put into the training given to you thus far.  You should feel proud to have become one with the Claw.  More such lessons will be given; the next of your lessons will be available once you have reached at least 14th level.  When you are ready at that time, seek me out on the Elder Rise of Thunder Bluff.

Turak Runetotem' WHERE ID=116;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Ho ho hello again, $N!$B$BThough I and the good folks of Smokywood Pastures have been quite busy this season, I just wanted to send you something special along to you.  You''ll be happy to know what we unfroze Sacks out in the Alterac Mountains; he sends his best.$B$BIn freeing Sacks, we managed to develop a novelty device that I think you might enjoy.  You will need a snowball to power it, but I think you''ll enjoy it quite a bit!$B$BGreatfather Winter' WHERE ID=117;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Ho Ho Hello, $N!  I hope you have a fantastic Feast of Winter Veil!$B$BYou were so nice in helping me out with my sweet tooth, that I wanted to send you a little something extra.  It''s a sampler of delicious Smokywood Pastures treats.  If you haven''t gotten any yet, be sure to do so before the season ends!$B$BSeasons Greetings...$BGreatfather Winter' WHERE ID=118;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Hello again - I just wanted to drop you a note that things here in Feathermoon Stronghold are fine.  I''ve managed to make several new pieces of leather items, thanks in no small part to the help you gave me!$B$BI had some extra bits of leather left over, so I thought I''d send you something extra for all the help you''ve given me.  If you''re ever by the Stronghold again, be sure to look us up!$B$BYour friend,$BPratt' WHERE ID=119;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Greetings once again - I just wanted to send you word that things here in Camp Mojache are going well.  I''ve managed to make several new pieces of leather items, thanks in no small part to your aid!$B$BI had some extra bits of leather left over, so I thought I''d send you something extra as a way of saying thank you once more.  If you''re ever by the Camp again, be sure to visit!$B$BPeace to you and your ancestors,$BJangdor' WHERE ID=120;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='This small token will give no answers, but perhaps it will be of some amusement to you.' WHERE ID=121;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='$N -$B$BI just wanted to say once again thanks for rescuing Metzen from his kidnappers.  Believe me when I say you''ve got a friend for life at Smokywood Pastures.$B$BSpeaking of which... Master Chef Graccu has been working on a new recipe here, and I thought you might like a little sample of what he has been whipping up!  Have a wondrous Winter Veil!$B$BMay your cash box always jingle,$BKaymard Copperpinch' WHERE ID=122;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Champion,$B$BThe Blue Dragonflight believes that you are fated for greater things than even I could predict.$B$BDespite what some would have you believe, our world needs heroes. In your darkest hour, when you face the blight of Kalimdor, recall the epic journies, trials, and tribulations that you undertook for an old gnome and let those memories lift your spirits.$B$BHumbly,$B$BNarain Soothfancy$B$BP.S. Sorry about the repair costs.' WHERE ID=123;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=124;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=125;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=126;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=127;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=128;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=129;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=130;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=131;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='This small token will give no answers, but perhaps it will be of some amusement to you.' WHERE ID=132;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=133;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=134;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=135;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=136;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='This small token will give no answers, but perhaps it will be of some amusement to you.' WHERE ID=137;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='This small token will give no answers, but perhaps it will be of some amusement to you.' WHERE ID=138;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='This small token will give no answers, but perhaps it will be of some amusement to you.' WHERE ID=139;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='This small token will give no answers, but perhaps it will be of some amusement to you.' WHERE ID=140;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='This small token will give no answers, but perhaps it will be of some amusement to you.' WHERE ID=141;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='This small token will give no answers, but perhaps it will be of some amusement to you.' WHERE ID=142;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=143;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=144;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=145;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=146;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=147;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=148;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=149;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=150;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=151;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=152;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='This small token will give no answers, but perhaps it will be of some amusement to you.' WHERE ID=153;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='This small token will give no answers, but perhaps it will be of some amusement to you.' WHERE ID=154;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='This small token will give no answers, but perhaps it will be of some amusement to you.' WHERE ID=155;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='This small token will give no answers, but perhaps it will be of some amusement to you.' WHERE ID=156;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='This small token will give no answers, but perhaps it will be of some amusement to you.' WHERE ID=157;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=158;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=159;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='This small token will give no answers, but perhaps it will be of some amusement to you.' WHERE ID=160;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='$N -$B$BI just wanted to say once again thanks for rescuing Metzen from his kidnappers.  Believe me when I say you''ve got a friend for life at Smokywood Pastures.$B$BSpeaking of which... Master Chef Graccu has been working on a new recipe here, and I thought you might like a little sample of what he has been whipping up!  Have a wondrous Winter Veil!$B$BMay your cash box always jingle,$BWulmort Jinglepocket' WHERE ID=161;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='New Mail', Body_Lang_enGB='Need to fix tab ordergin' WHERE ID=162;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii', Body_Lang_enGB='YOh!' WHERE ID=165;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii', Body_Lang_enGB='ab' WHERE ID=166;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='<UNUSED>', Body_Lang_enGB='This mail was sent to you because you signed up for Viagra! More text.' WHERE ID=167;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=168;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Testing Mass Mail!', Body_Lang_enGB='This is a test of the emergency broadcast system.' WHERE ID=169;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='asdjaksld dsf as  -', Body_Lang_enGB='Hello. What are you talking about?  This isn''t crashing?' WHERE ID=170;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='The Argent Dawn needs your help!', Body_Lang_enGB='$N$B$BWith all haste, please open and heed the attached letter.  The Argent Dawn needs your help!' WHERE ID=171;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Research Report ', Body_Lang_enGB='$n,$B$BI received this report regarding the document you retrieved from the Scourge. While not pressing, you may find it of interest.$B$BThank you again for your service.$BKeeper of the Rolls$BThe Argent Dawn' WHERE ID=172;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Research Report ', Body_Lang_enGB='$n,$B$BI received this report regarding the document you retrieved from the Scourge. While not pressing, you may find it of interest.$B$BThank you again for your service.$BKeeper of the Rolls$BThe Argent Dawn' WHERE ID=173;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Research Report ', Body_Lang_enGB='$n,$B$BI received this report regarding the document you retrieved from the Scourge. While not pressing, you may find it of interest.$B$BThank you again for your service.$BKeeper of the Rolls$BThe Argent Dawn' WHERE ID=174;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Research Report ', Body_Lang_enGB='$n,$B$BI received this report regarding the document you retrieved from the Scourge. While not pressing, you may find it of interest.$B$BThank you again for your service.$BKeeper of the Rolls$BThe Argent Dawn' WHERE ID=175;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Research Report ', Body_Lang_enGB='$n,$B$BI received this report regarding the document you retrieved from the Scourge. While not pressing, you may find it of interest.$B$BThank you again for your service.$BKeeper of the Rolls$BThe Argent Dawn' WHERE ID=176;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Research Report ', Body_Lang_enGB='$n,$B$BI received this report regarding the document you retrieved from the Scourge. While not pressing, you may find it of interest.$B$BThank you again for your service.$BKeeper of the Rolls$BThe Argent Dawn' WHERE ID=177;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A Gift For You', Body_Lang_enGB='Thanks for playing World of Warcraft!' WHERE ID=178;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Congratulations, Lottery Winner', Body_Lang_enGB='Here''s your reward, you lucky stiff!  Don''t spend it all in one auction house....' WHERE ID=179;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Urgent letter enclosed!', Body_Lang_enGB='Open immediately. ' WHERE ID=180;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Found Enchantment', Body_Lang_enGB='Upon periodic perusal of the nether, we came across the following reagents.  Good day, and... please be more careful when dealing with the arcane.' WHERE ID=181;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Congrats!', Body_Lang_enGB='You won a nether drake.  An armored netherdrake, at that oh snap.' WHERE ID=182;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A letter from Shattrath City', Body_Lang_enGB='You have received a letter from Khadgar.' WHERE ID=183;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Thank you!', Body_Lang_enGB='$N,$B$BThank you for the time that we spent together during Children''s Week. Did you know that Farseer Nobundo has asked the orphan matron to allow me to study with him at the Exodar?$B$BThank you for taking me to all of those neat places, and to visit my brother, Jheel. I miss him almost as much as I miss you. And, the Ring of Observance, the Dark Portal and the Caverns of Time were neato!$B$BI''m sure that you''re taking good care of my pet. Tell him that I miss him, too!$B$BLove,$B$BDornaa' WHERE ID=184;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Thank you!', Body_Lang_enGB='Dear, $N,$B$BThank you for taking me out during Children''s Week. Lady Liadrin, the leader of the Blood Knights, has asked that I be released to her custody for training in Silvermoon City!$B$BI just wanted to thank you for taking me to see my friend, Hch''uu, as well as the Dark Portal, the Throne of the Elements, and the Caverns of Time. I like my toy dragon very much!$B$BI''m sure that you''re taking good care of my pet. Please tell him that I miss him!$B$BSincerely,$B$BSalandria' WHERE ID=185;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Recovered Fortune Coin', Body_Lang_enGB='We recovered a lost fortune coin while searching the twisting nether, and saw that it was yours. Enjoy!' WHERE ID=186;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Happy Feast of Winter Veil!', Body_Lang_enGB='Please brew, share and enjoy some steaming-hot spiced apple cider with your friends through the holidays!' WHERE ID=187;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Happy Feast of Winter Veil!', Body_Lang_enGB='Please sew, share and enjoy some fine green winter clothes with your friends through the holidays!' WHERE ID=188;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Lost Nether Drake', Body_Lang_enGB='I recently picked up this little drake while perusing the Nether.  He appears to be yours but he could find no home in your packs when given to you.$B$BPlease do enjoy feisty new pet!  He is quite eager to settle into his new home!' WHERE ID=189;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Guild Bank Closure', Body_Lang_enGB='Please find the following assets, gathered from your guild bank vault upon its closure.' WHERE ID=190;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Happy Feast of Winter Veil!', Body_Lang_enGB='Please sew, share and enjoy some fine red winter clothes with your friends through the holidays!' WHERE ID=191;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Happy Feast of Winter Veil!', Body_Lang_enGB='Please craft, share and enjoy some cozy winter boots with your friends through the holidays!' WHERE ID=192;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A letter from Archmage Malin', Body_Lang_enGB='Dear, $N,$B$BCommander Azuresteel''s personal courier saw to it that I received my daughter''s letter. The courier also told me that it was you who found it.$B$BI just want to thank you for seeing to it that the letter got to me. I know that times must be tough for all of you brave souls who are daring to fight in Northrend.$B$BRest assured that I will avenge Emmy. The blue dragonflight will suffer for what they did to my little girl!$B$BWith the utmost respect and gratitude,$B$BArchmage Malin' WHERE ID=193;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A letter from Deino', Body_Lang_enGB='Dearest, $N,$B$BOverlord Agmar''s personal courier saw to it that I received my brother''s letter. The courier also told me that it was you who found it.$B$BI just want to thank you for seeing to it that the letter got to me. I know that times must be tough for all of you brave souls who are daring to fight in Northrend.$B$BRest assured that I will avenge Ta''zinni. The blue dragonflight will suffer for what they did to my little brother!$B$BWith the utmost respect and gratitude,$B$BDeino' WHERE ID=194;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='The Competitor''s Tabard', Body_Lang_enGB='You fought bravely in a battleground and impressed the Spirits of Competition... well done! As a reward, you have been gifted with this mark of favor: a Competitor''s Tabard. Wear it proudly.' WHERE ID=195;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A Gold Medallion', Body_Lang_enGB='You have honored the Spirits of Competition with your fervor in the face of the enemy. Congratulations! With this Gold Medallion, they will be proud to be seen at your side.' WHERE ID=196;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A New Year, A New Brew!', Body_Lang_enGB='Greetings $n!$b$b   We hope that the new year is treating you well.  If it isn''t, stop by our vendors to pick up the latest brew.  It is sure to bring out the animal in you.$b$b   Enjoy the samples and have a great new year!$b$b- Brew of the Month Club' WHERE ID=197;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Can''t Keep A Good Brew Down.', Body_Lang_enGB='$n,$b$b   Sometimes you can''t keep a good brew down.  This new brew is good, but can you keep it down?$b$b   Remember, if you like these samples, you can get more from visiting our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=198;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Some Buzz On The Latest Brew', Body_Lang_enGB='Hello $n,$b$b   Sometimes you want a fragrant brew, and what is a better aroma than honey?  Creatures great and small all love the sweet smell of honey.  Once you try this brew out, we think you''ll agree.$b$b   Remember, if you enjoyed these samples, you can purchase more from visiting our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=199;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Because You Demanded It', Body_Lang_enGB='Greetings $n,$b$b   We''ve heard that some of our members wanted a brew that was a little more light and bubbly.  We''ve tried to tell them this isn''t the "Champagne of the Month Club."  Unfortunately, that didn''t stop the demand.  Hopefully this month''s brew will satisfy those that want a lighter and more bubbly brew.$b$b   Don''t forget, if you enjoyed this sample, it is available for purchase from our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=200;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A Springtime Celebration!', Body_Lang_enGB='Hello $n,$b$b   Spring is definitely in the air, and this month you may find it underfoot!  Try out our new brew, Springtime Stout.  It''s a refreshing brew perfect for this time of year.$b$b  Enjoy the sample, and remember that you can visit our vendors to purchase more!$b$b- Brew of the Month Club' WHERE ID=201;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='This Brew Is Hot', Body_Lang_enGB='$n,$b$b   We''ve got a hot brew for you this month!  All the way from Blackrock Mountain comes Blackrock Lager.$b$b   Remember, if you enjoyed this small sample, you can purchase more from our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=202;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A Dangerous Brew', Body_Lang_enGB='Greetings $n,$b$b   We have an exciting brew for you this month.  Brew of the Month Club members have braved the jungles of Stranglethorn and have returned with this mysterious brew.$b$b   Don''t forget that if you enjoyed this brew sample, you can purchase more from our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=203;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A Brew You Won''t Forget', Body_Lang_enGB='Warm wishes $n,$b$b   Sometimes you have to go out of your way to find the best brew.  This month''s brew has traveled a long way, but we feel that it is well worth it.$b$b   Remember that if you enjoyed this brew sample, you can purchase more from our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=204;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A Brew You''ll Like', Body_Lang_enGB='Hi $n,$b$b   Our brew this month is a polarizing one; you either love it or like it.  We''ll let you decide.$b$b   If you enjoy this brew, you can purchase more from our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=205;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='An Autumn Affair', Body_Lang_enGB='Hello $n,$b$b   Our brew this month is a celebration of autumn.  We think this brew captures just some of the essence of this season.  But you don''t have to take our word for it, give it a try.$b$b   If you enjoyed this sample, you can purchase more from our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=206;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A Brew Even Your Friends Can Enjoy', Body_Lang_enGB='Greetings $n!$b$b   We hope that the year has been treating you well.  If it hasn''t, stop by our vendors to pick up our latest: Bartlett''s Bitter Brew.  The flavor is unmatched, but we warn you that it is not for the weak of stomach.$b$b   Enjoy the samples and share with your friends!$b$b- Brew of the Month Club' WHERE ID=207;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A Chilling Tale', Body_Lang_enGB='$n,$b$b   This past summer we had some of our members tackle with the mighty Lord of Frost.  More importantly, they discovered a large stash of his own brew.  We''ve manage to stockpile a large amount of this rare brew and are sending you some samples.$b$b   If you enjoyed this refreshing sample, you can purchase more from our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=208;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Welcome to the Brew of the Month Club!', Body_Lang_enGB='$n,$b$b   Welcome to the Brew of the Month club!  This club is dedicated to bringing you some of the finest brew in all the realms.$b$b   Every month a new brew will be mailed directly to you.  If you enjoy that brew and want more, head to the Stonefire Tavern in Ironforge and talk to the Brew of the Month club members there.$b$b   Again, welcome to the club, $n.$b$b$b- Brew of the Month Club' WHERE ID=209;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Welcome to the Brew of the Month Club!', Body_Lang_enGB='$n,$b$b   Welcome to the Brew of the Month club!  This club is dedicated to bringing you some of the finest brew in all the realms.$b$b   Every month a new brew will be mailed directly to you.  If you enjoy that brew and want more, head to the Darkbriar Lodge in Orgrimmar''s Valley of Spirits and talk to the Brew of the Month club members there.$b$b   Again, welcome to the club, $n.$b$b$b- Brew of the Month Club' WHERE ID=210;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Congratulations!', Body_Lang_enGB='On behalf of the Steamwheedle Fighting Circuit, we congratulate you for your successes in this arena season.$B$BIn recognition of your skill and savagery, we hereby bestow upon you this Vengeful Nether Drake.  May it serve you well.' WHERE ID=211;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A New Year Calls For A New Brew!', Body_Lang_enGB='Greetings $n!$b$b   We hope that the new year is treating you well.  If it isn''t, stop by our vendors to pick up the latest brew.  It is sure to bring out the animal in you.$b$b   Enjoy the samples and have a great new year!$b$b- Brew of the Month Club' WHERE ID=212;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='It''s Hard To Keep A Good Brew Down.', Body_Lang_enGB='$n,$b$b   Sometimes you can''t keep a good brew down.  This new brew is good, but can you keep it down?$b$b   Remember, if you like these samples, you can get more from visiting our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=213;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='The Latest Buzz', Body_Lang_enGB='Hello $n,$b$b   Sometimes you want a fragrant brew, and what is a better aroma than honey?  Creatures great and small all love the sweet smell of honey.  Once you try this brew out, we think you''ll agree.$b$b   Remember, if you enjoyed these samples, you can purchase more from visiting our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=214;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Because You Asked For It', Body_Lang_enGB='Greetings $n,$b$b   We''ve heard that some of our members wanted a brew that was a little more light and bubbly.  We''ve tried to tell them this isn''t the "Champagne of the Month Club."  Unfortunately, that didn''t stop the demand.  Hopefully this month''s brew will satisfy those that want a lighter and more bubbly brew.$b$b   Don''t forget, if you enjoyed this sample, it is available for purchase from our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=215;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='It''s Time To Celebrate Spring!', Body_Lang_enGB='Hello $n,$b$b   Spring is definitely in the air, and this month you may find it underfoot!  Try out our new brew, Springtime Stout.  It''s a refreshing brew perfect for this time of year.$b$b  Enjoy the sample, and remember that you can visit our vendors to purchase more!$b$b- Brew of the Month Club' WHERE ID=216;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A Hot Brew', Body_Lang_enGB='$n,$b$b   We''ve got a hot brew for you this month!  All the way from Blackrock Mountain comes Blackrock Lager.$b$b   Remember, if you enjoyed this small sample, you can purchase more from our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=217;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A Mysterious Brew', Body_Lang_enGB='Greetings $n,$b$b   We have an exciting brew for you this month.  Brew of the Month Club members have braved the jungles of Stranglethorn and have returned with this mysterious brew.$b$b   Don''t forget that if you enjoyed this brew sample, you can purchase more from our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=218;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Did You Remember Your Brew?', Body_Lang_enGB='Warm wishes $n,$b$b   Sometimes you have to go out of your way to find the best brew.  This month''s brew has traveled a long way, but we feel that it is well worth it.$b$b   Remember that if you enjoyed this brew sample, you can purchase more from our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=219;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A Brew You''ll Love', Body_Lang_enGB='Hi $n,$b$b   Our brew this month is a polarizing one; you either love it or like it.  We''ll let you decide.$b$b   If you enjoy this brew, you can purchase more from our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=220;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A Festive Fall', Body_Lang_enGB='Hello $n,$b$b   Our brew this month is a celebration of autumn.  We think this brew captures just some of the essence of this season.  But you don''t have to take our word for it, give it a try.$b$b   If you enjoyed this sample, you can purchase more from our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=221;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Fun For You And Your Friends', Body_Lang_enGB='Greetings $n!$b$b   We hope that the year has been treating you well.  If it hasn''t, stop by our vendors to pick up our latest: Bartlett''s Bitter Brew.  The flavor is unmatched, but we warn you that it is not for the weak of stomach.$b$b   Enjoy the samples and share with your friends!$b$b- Brew of the Month Club' WHERE ID=222;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A Cool Brew', Body_Lang_enGB='$n,$b$b   This past summer we had some of our members tackle with the mighty Lord of Frost.  More importantly, they discovered a large stash of his own brew.  We''ve manage to stockpile a large amount of this rare brew and are sending you some samples.$b$b   If you enjoyed this refreshing sample, you can purchase more from our vendors.$b$bEnjoy!$b$b- Brew of the Month Club' WHERE ID=223;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Learn to Ride in Elwynn Forest', Body_Lang_enGB='Good $gSir:Lady; $n,$B$BI hope this letter finds you well. I am writing to make you aware of my services as a riding trainer. Should you wish to learn, you need only visit me at the Eastvale Logging Camp, found along the road east out of Stormwind. My fee is a modest four gold coins.$B$BIf you''d care to purchase a mount upon learning how to ride, the horse breeder Katie Hunter offers a number of noble steeds, each no more than one gold coin.$B$BYours, Randal Hunter' WHERE ID=224;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Learn to Ride in Darnassus', Body_Lang_enGB='Good fortune to you, $n.$B$BI am writing to make you aware of my services as a riding trainer. Should you wish to learn, you need only visit me at the Cenarion Enclave in Darnassus. My fee is a modest four gold coins.$B$BIf you desire to purchase a mount upon learning how to ride, the saber handler Lelanai offers a number of noble beasts, each no more than one gold coin.$B$BWishing you well, Jartsam' WHERE ID=225;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Learn to Ride in Dun Morogh', Body_Lang_enGB='Hey there, $glad:lass;! Looking to learn to ride? Then come visit me at the Amberstill Ranch, found along the road east out of Ironforge.$B$BMy fee''s only four gold coins, and if you want a ram to ride, Veron Amberstill offers a number of noble steeds for no more than one gold coin a piece.$B$B- Ultham' WHERE ID=226;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Learn to Ride at The Exodar', Body_Lang_enGB='Greetings, $n.$B$BI hope this letter finds you well. I am writing to make you aware of my services as a riding trainer. Should you wish to learn, you need only visit me at the entrance to The Exodar. My fee is a modest four gold coins.$B$BIf you desire to purchase an elekk upon learning how to ride, Torallius the Pack Handler offers a number of noble steeds, each no more than one gold coin.$B$BGo in peace, Aalun' WHERE ID=227;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Learn to Ride in Dun Morogh', Body_Lang_enGB='Salutations, $n! Looking to get around faster? Then come visit Milli and me at Steelgrill''s Depot, just northeast of Kharanos.$B$BMy riding trainer''s fee is only four gold coins, and if you want your own mechanostrider, Milli builds them for no more than one gold coin each!$B$BHoping to see you soon, Binjy' WHERE ID=228;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Learn to Ride in Mulgore', Body_Lang_enGB='Hail, brave $n.$B$BI wish to make you aware of my services as a riding trainer. Should you desire to learn, you need only visit me in Bloodhoof Village. My fee is a modest four gold coins.$B$BIf you wish to purchase a kodo upon learning how to ride, Harb Clawhoof offers a number of noble beasts, each no more than one gold coin.$B$BGood journeys, Kar' WHERE ID=229;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Learn to Ride in Durotar', Body_Lang_enGB='You want to ride, $n? Then you come see me in Senjin Village. I teach you for only four gold coins.$B$BMaybe then you want a raptor to ride on? You talk to Zjolnir. He sell you one for one gold coin, maybe less.$B$BStay away from the voodoo!$B$BXar''Ti' WHERE ID=230;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Learn to Ride in Orgrimmar', Body_Lang_enGB='Strength and Honor, $n.$B$BI am Orgrimmar''s riding trainer. Should you desire to learn, you need only visit me in the Valley of Honor. My fee is a modest four gold coins.$B$BIf you wish to purchase a wolf upon learning how to ride, Ogunaro Wolfrunner''s kennels house a number of noble beasts, each no more than one gold coin.$B$B- Kildar' WHERE ID=231;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Learn to Ride in the Eversong Woods', Body_Lang_enGB='Good $n,$B$BI hope this letter finds you well. I am writing to make you aware of my services as a riding trainer. Should you wish to learn, you need only visit me at Thuron''s Livery, found southeast of the Shepherd''s Gate leaving Silvermoon City. My fee is a modest four gold coins.$B$BIf you''d care to purchase a mount upon learning how to ride, the hawkstrider breeder Winaestra offers a number of noble steeds, each no more than a gold coin.$B$BSafe travels, Perascamin' WHERE ID=232;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Learn to Ride in Tirisfal Glades', Body_Lang_enGB='Good $gSir:Lady; $n,$B$BI write to make you aware of my services as a riding trainer. Should you wish to learn, you need only visit me in Brill. My fee is a modest four gold coins.$B$BIf you''d care to purchase a mount upon learning how to ride, Zachariah Post has gathered a number of horses suitable to our needs and sells them for no more than one gold coin per head.$B$BYours, Velma Warnam' WHERE ID=233;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Watch Your Back', Body_Lang_enGB='Krenna heard that we freed one of the trappers and she''s absolutely furious.$B$BYou''d best keep your head down for a while or we''ll both end up wrestling bears in the pit.$B$B-Gorgonna' WHERE ID=234;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='A Swift Zhevra', Body_Lang_enGB='TO: $n$B$BFROM: Nesingwary Exotic Mount Supply Co. LLC$B$BCONTENTS OF CRATE:$B$B- One (1) Zhevra$B$B- One (1) Zhevra Saddle$B$B- Four (4) Zhevra Hooves$B$B- Two (2) Spare Zhevra Hooves$B$B- DO NOT OBSTRUCT AIR HOLES -' WHERE ID=235;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='In The Name Of The Light!', Body_Lang_enGB='To: High General Abbendis
New Avalon, Scarlet Lands
' WHERE ID=236;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=237;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=238;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=239;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=240;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=241;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=242;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=243;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=244;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=245;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=246;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=247;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=248;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=249;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=250;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=251;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=252;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=253;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=254;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=255;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=256;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=257;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=258;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=259;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='Thank you for visiting me, $N. It makes me happy to know we are not forgotten.' WHERE ID=260;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='', Body_Lang_enGB='I was grateful for your visit today, take this as a gift for your Lunar Festival.' WHERE ID=261;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Congratulations!', Body_Lang_enGB='On behalf of the Steamwheedle Fighting Circuit, we congratulate you for your successes in this arena season.$B$BIn recognition of your skill and savagery, we hereby bestow upon you this Brutal Nether Drake.  May it serve you well.' WHERE ID=262;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='It''s Time to Pity Some Fools!', Body_Lang_enGB='Get out there and spread some Mohawk Love.' WHERE ID=263;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='You got Manabonked!', Body_Lang_enGB='Hey there $n,
   Remember when you got sheeped in Dalaran?  Yeah, that was me, Minigob Manabonk!  I just wanted to send you a letter to let you know who sheeped you.  Also, because you were such a good sport about it I''m sending you a wand of my own.  Now you can "Manabonk" your friends.  When you do, tell them "Minigob Manabonk sent you."

- Minigob Manabonk' WHERE ID=264;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='The Argent Tournament', Body_Lang_enGB='The Argent Crusade invites you to test your skills in honorable combat against other heroes of Azeroth at the Argent Tournament. The champions of the world''s great nations have gathered at the Argent Tournament Grounds in northeastern Icecrown to face all challengers.' WHERE ID=265;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Congratulations!', Body_Lang_enGB='On behalf of the Steamwheedle Fighting Circuit, we congratulate you for your successes in this arena season.$B$BIn recognition of your skill and savagery, we hereby bestow upon you this Deadly Gladiator''s Frost Wyrm.  May it serve you well.' WHERE ID=266;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Congratulations!', Body_Lang_enGB='On behalf of the Steamwheedle Fighting Circuit, we congratulate you for your successes in this arena season.$B$BIn recognition of your skill and savagery, we hereby bestow upon you this Furious Gladiator''s Frost Wyrm.  May it serve you well.' WHERE ID=267;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='URGENT ACTION BULLETIN', Body_Lang_enGB='






The orphans of Northrend need your help. For less than the cost of a cup of Kungaloosh, you can sponsor an unfortunate orphan like little Roo or Kekek. Simply contact Orphan Matron Aria in Dalaran. You can make all the difference in the life of a young oracle or wolvar. Act now!' WHERE ID=268;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='From Roo', Body_Lang_enGB='Dear $N,$B$BWe miss you a lot. Everybody likes our story about meeting the Great One and now they all want to meet a Great One too. They don''t believe some of our stories. They think we made up dragon queen and dragonshrine stories. They just jealous.$B$BLife at orphanage is better these days. Matron takes us out to play in the park and sometimes we even get new toys, but we still lonely. We want to come visit with you. Maybe you take us some more places? You like that?$B$BYour friend,$BRoo' WHERE ID=269;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='From Kekek', Body_Lang_enGB='Dear $N,$B$BKekek not good at writing, but learn how just to write you letter. Orphan-lady found old copy of Green Hills book Hemet talked about. Been reading it, learning how to be great hunter like you and Hemet Nesingwary.  Takes a lot of words to be good hunter, Kekek guess.$B$BKekek want to try out stuff he read about in Green Hills book. Maybe you let Kekek come visit and we can hunt together? Kekek promise not to kill steal.$B$BYour friend,$BKekek' WHERE ID=270;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='In Recognition', Body_Lang_enGB='Your skills, and considerable talents, in the field of jewelcrafting have not gone unnoticed.  It is important we continue our tradition with the pride and attention to detail you have demonstrated.

To recognize said efforts, I''ve included a special writ.  Return it to me for some well-earned rewards.

Timothy Jones' WHERE ID=271;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Journeyman Riding in the Eversong Woods', Body_Lang_enGB='Good $n,$B$BI am once more writing to remind you of my services as a riding trainer. Should you wish to learn Journeyman Riding for faster mounts, you need only visit me at Thuron''s Livery, found southeast of the Shepherd''s Gate leaving Silvermoon City. My fee is a modest fifty gold coins.$B$BIf you''d care to purchase a swift mount, the hawkstrider breeder Winaestra offers a number of noble steeds, each no more than ten gold coins.$B$BSafe travels, Perascamin' WHERE ID=272;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Journeyman Riding at The Exodar', Body_Lang_enGB='Greetings, $n.$B$BI am writing again to remind you of my services as a riding trainer. Should you wish to learn Journeyman Riding for faster mounts, you need only visit me at the entrance to The Exodar. My fee is a modest fifty gold coins.$B$BIf you desire to purchase a swift elekk, Torallius the Pack Handler offers a number of noble steeds, each no more than ten gold coins.$B$BGo in peace, Aalun' WHERE ID=273;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Journeyman Riding in Dun Morogh', Body_Lang_enGB='Hey there, $glad:lass;! Looking to learn Journeyman Riding for faster  mounts? Then come visit me at the Amberstill Ranch, found along the road east out of Ironforge.$B$BMy fee''s only fifty gold coins, and if you want a swift ram to ride, Veron Amberstill offers a number of noble steeds for no more than ten gold coins a piece.$B$B- Ultham' WHERE ID=274;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Journeyman Riding in Dun Morogh', Body_Lang_enGB='Salutations, $n! Looking to get around even FASTER? Then come visit Milli and me at Steelgrill''s Depot, just northeast of Kharanos.$B$BMy Journeyman Riding trainer''s fee is only fifty gold coins, and if you want your own swift mechanostrider, Milli builds them for no more than ten gold coins each!$B$BHoping to see you soon, Binjy' WHERE ID=275;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Journeyman Riding in Elwynn Forest', Body_Lang_enGB='Good $gSir:Lady; $n,$B$BI am writing again to remind you of my services as a riding trainer. Should you wish to learn Journeyman Riding for faster mounts, you need only visit me at the Eastvale Logging Camp, found along the road east out of Stormwind. My fee is a modest fifty gold coins.$B$BIf you''d care to purchase a swift mount, the horse breeder Katie Hunter offers a number of noble steeds, each no more than ten gold coins.$B$BYours, Randal Hunter' WHERE ID=276;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Journeyman Riding in Darnassus', Body_Lang_enGB='Good fortune to you, $n.$B$BI am writing once more to remind you of my services as a riding trainer. Should you wish to learn Journeyman Riding for faster mounts, you need only visit me at the Cenarion Enclave in Darnassus. My fee is a modest fifty gold coins.$B$BIf you desire to purchase a swift mount, the saber handler Lelanai offers a number of noble beasts, each no more than ten gold coins.$B$BWishing you well, Jartsam' WHERE ID=277;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Journeyman Riding in Orgrimmar', Body_Lang_enGB='Strength and Honor, $n.$B$BShould you desire to learn Journeyman Riding for faster mounts, you need only visit me in the Valley of Honor. My fee is a modest fifty gold coins.$B$BIf you wish to purchase a swift wolf, Ogunaro Wolfrunner''s kennels house a number of noble beasts, each no more than ten gold coins.$B$B- Kildar' WHERE ID=278;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Journeyman Riding in Mulgore', Body_Lang_enGB='Hail, brave $n.$B$BI wish to remind you of my services as a riding trainer. Should you desire to learn Journeyman Riding for faster mounts, you need only visit me in Bloodhoof Village. My fee is a modest fifty gold coins.$B$BIf you wish to purchase a swift kodo, Harb Clawhoof offers a number of noble beasts, each no more than ten gold coins.$B$BGood journeys, Kar' WHERE ID=279;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Journeyman Riding in Durotar', Body_Lang_enGB='You want to ride even FASTER, $n? Then you come see me in Senjin Village. I teach you Journeyman Riding for only fifty gold coins.$B$BMaybe then you want a swift raptor to ride even FASTER on? You talk to Zjolnir. He sell you one for ten gold coins, maybe less.$B$BStay away from the voodoo!$B$BXar''Ti' WHERE ID=280;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Journeyman Riding in Tirisfal Glades', Body_Lang_enGB='Good $gSir:Lady; $n,$B$BI write once more to remind you of my services as a riding trainer. Should you wish to learn Journeyman Riding for faster mounts, you need only visit me in Brill. My fee is a modest fifty gold coins.$B$BIf you''d care to purchase a swift mount, Zachariah Post has gathered a number of horses suitable to our needs and sells them for no more than ten gold coins per head.$B$BYours, Velma Warnam' WHERE ID=281;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Learn to Fly at Thrallmar', Body_Lang_enGB='Hey there, $n.$B$BIf you want to learn Expert Riding for flying mounts, visit me at Thrallmar in Hellfire Peninsula. My fee is two hundred and fifty gold coins.$B$BIf you want to buy a flying mount once you learn, Bana Wildmane sells them for no more than fifty gold coins.$B$B- Jahubo' WHERE ID=282;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Learn to Fly at Honor Hold', Body_Lang_enGB='Ho there, $glad:lass;! Looking to learn Expert Riding for flying mounts? Then come visit me at Honor Hold in Hellfire Peninsula.$B$BMy fee''s two hundred and fifty gold coins, and if you want a flying mount, my goodly spouse Grunda raises and sells gryphons for no more than fifty gold coins a piece.$B$B- Hargen' WHERE ID=283;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Artisan Riding at Valiance Keep', Body_Lang_enGB='Hey there, $glad:lass;! Looking to learn Artisan Riding for faster flying mounts? Then visit me at Valiance Keep in Borean Tundra.$B$BMy fee''s five thousand gold coins, plus a thousand for more Cold Weather Flying training if you want to ride in Northrend.$B$BIf you want a swift flying mount, the good Durgan Thunderbeak offers them for no more than one hundred gold coins a piece.$B$B- Maigra$B$BP.S. If you can''t make it to Northrend, visit Hargen Bronzewing at Honor Hold in Hellfire Peninsula.' WHERE ID=284;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Artisan Riding at Warsong Hold', Body_Lang_enGB='How you doing, $n.$B$BIf you want to learn Artisan Riding for faster flying mounts, visit me at Warsong Hold in Borean Tundra. My fee is five thousand gold coins, plus a thousand for more Cold Weather Flying training if you want to ride in Northrend.$B$BIf you want a swift flying mount once you learn, Tohfo Skyhoof sells them for no more than one hundred gold coins.$B$B- Sabamba$B$BP.S. If you can''t make it to Northrend, visit Wind Rider Jahubo at Thrallmar in Hellfire Peninsula.' WHERE ID=285;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Congratulations!', Body_Lang_enGB='On behalf of the Steamwheedle Fighting Circuit, we congratulate you for your successes in this arena season.$B$BIn recognition of your skill and savagery, we hereby bestow upon you this Relentless Gladiator''s Frost Wyrm.  May it serve you well.' WHERE ID=286;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Congratulations!', Body_Lang_enGB='On behalf of the Steamwheedle Fighting Circuit, we congratulate you for your successes in this arena season.$B$BIn recognition of your skill and savagery, we hereby bestow upon you this Wrathful Gladiator''s Frost Wyrm.  May it serve you well.' WHERE ID=287;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Operation: Gnomeregan', Body_Lang_enGB='Good Sir/Madame,

As a proud member of the Alliance, duty compels you to journey to Ironforge with haste and submit yourself to the will of High Tinker Mekkatorque, King of Gnomes.*

The end of of our exile draws nigh - Operation: Gnomeregan is about to begin!**

* Lawyerbot 2000 informs me that I actually possess no legal authority whatsoever - over gnomes or otherwise - but still, you have to admit that sounded impressive!

** Seriously, please come help out if you can. Many thanks!' WHERE ID=288;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Zalazane''s Fall', Body_Lang_enGB='Brothas and Sistas,
In de name of all de ancestors, Vol''jin, de son of Sen''jin, issues de call to war! For too long, de traitor Zalazane been usin'' his black magic to desecrate our dead, to lull us into believin'' him defeated, and to keep de Echo Isles from de Darkspears. 
De time has come to deal wit'' him once and for all. I be helpin'' Vol''jin gather his forces outside Sen''jin Village. Join me dere an'' help us bring long-awaited justice to dis renegade!
In service to Vol''jin,
Vanira
' WHERE ID=289;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='Congratulations, Vanquisher!', Body_Lang_enGB='On behalf of the Steamwheedle Fighting Circuit, we congratulate you upon your successes in the latest Arena Tournament.$B$BIn recognition of your skill and savagery, we hereby bestow upon you the title of Vanquisher.  May you wear it proudly.' WHERE ID=290;
UPDATE dbc_mailtemplate SET Subject_Lang_enGB='X-53 Touring Rocket', Body_Lang_enGB='TO: $N$B$BFROM: B.O.O.M. Rocket Works$B$BCONTENTS OF CRATE:$B$B- One (1) X-53 Nether-Rocket, Touring Model$B$B- One (1) Rocket Ignition Key$B$B- One (1) Rear-Mounted Ejector Seat$B$B- Zero (0) Parachutes' WHERE ID=291;
