UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=1;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=2;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=3;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=4;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=5;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=6;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=126;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=163;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=522;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=7;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=8;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=9;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=10;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=11;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=12;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=13;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=14;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=15;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=16;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=17;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=18;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=19;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=20;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=21;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=22;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=23;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=24;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=25;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be level 80 and in a raid group to enter.' WHERE ID=26;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be level 80 and in a raid group to enter.' WHERE ID=323;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=27;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires the Key of Time.' WHERE ID=127;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=28;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=29;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=30;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=31;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=32;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=33;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=34;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=35;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=36;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=37;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=38;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=39;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=40;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=41;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=42;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=43;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=44;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=45;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be level 80 and in a raid group to enter.' WHERE ID=46;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be level 80 and in a raid group to enter.' WHERE ID=128;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=47;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=48;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires the Flamewrought Key.' WHERE ID=129;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=49;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires the Flamewrought Key.' WHERE ID=130;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=50;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires the Flamewrought Key.' WHERE ID=131;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=51;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=52;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires the Reservoir Key.' WHERE ID=132;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=53;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires the Reservoir Key.' WHERE ID=133;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=54;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires the Reservoir Key.' WHERE ID=134;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=55;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=56;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=57;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires the Warpforged Key.' WHERE ID=135;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=58;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires the Warpforged Key.' WHERE ID=136;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=59;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires the Warpforged Key.' WHERE ID=137;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=60;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires the Auchenai Key.' WHERE ID=138;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=61;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires the Auchenai Key.' WHERE ID=139;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=62;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires the Auchenai Key.' WHERE ID=140;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=63;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires the Auchenai Key.' WHERE ID=141;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=64;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=65;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires the Key of Time.' WHERE ID=142;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=66;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=67;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=68;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=69;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=70;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=71;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=72;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=73;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 65 to enter.' WHERE ID=74;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires you to be level 80.' WHERE ID=143;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=75;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires you to be level 80.' WHERE ID=144;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 66 to enter.' WHERE ID=76;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires you to be level 80.' WHERE ID=145;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 75 to enter.' WHERE ID=77;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires you to be level 80.' WHERE ID=146;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=78;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=79;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=80;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=81;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires completion of the "Hard to Kill" quest.' WHERE ID=147;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=82;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=83;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=84;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=85;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=86;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=87;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=88;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=89;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=90;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 75 to enter.' WHERE ID=91;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires you to be level 80.' WHERE ID=148;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=92;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=93;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=94;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires the Sunforged Key[PH].' WHERE ID=149;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 72 to enter.' WHERE ID=95;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires you to be level 80.' WHERE ID=150;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 69 to enter.' WHERE ID=96;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires you to be level 80.' WHERE ID=151;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 67 to enter.' WHERE ID=97;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires you to be level 80.' WHERE ID=152;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 75 to enter.' WHERE ID=98;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires you to be level 80.' WHERE ID=153;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be level 80 and in a raid group to enter.' WHERE ID=99;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be level 80 and in a raid group to enter.' WHERE ID=154;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 71 to enter.' WHERE ID=100;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires you to be level 80.' WHERE ID=155;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=101;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=102;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=103;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=301;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 70 to enter.' WHERE ID=104;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires you to be level 80.' WHERE ID=156;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=105;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=106;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=107;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=108;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=109;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be level 80 and in a raid group to enter.' WHERE ID=110;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be level 80 and in a raid group to enter.' WHERE ID=157;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 80 and in a raid group to enter.' WHERE ID=111;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 80 and in a raid group to enter.' WHERE ID=158;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=112;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=113;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 68 to enter.' WHERE ID=114;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires you to be level 80.' WHERE ID=159;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=115;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=116;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=117;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=118;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 80, in control of Wintergrasp and in a raid group to enter.' WHERE ID=119;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 80, in control of Wintergrasp and in a raid group to enter.' WHERE ID=160;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=120;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=281;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 80 and in a raid group to enter.' WHERE ID=485;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 80 and in a raid group to enter.' WHERE ID=486;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must have defeated The Lich King in the 10 Player raid before attempting 10 Player Heroic difficulty.' WHERE ID=487;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must have defeated The Lich King in the 25 Player raid before attempting 25 Player Heroic difficulty.' WHERE ID=488;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 75 to enter.' WHERE ID=481;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires you to be level 80.' WHERE ID=482;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=121;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=122;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=123;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 80 and in a raid group to enter.' WHERE ID=124;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 80 and in a raid group to enter.' WHERE ID=161;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 80 and in a raid group to enter.' WHERE ID=221;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 80 and in a raid group to enter.' WHERE ID=222;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be at least level 75 to enter.' WHERE ID=125;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='Heroic Difficulty requires you to be level 80.' WHERE ID=162;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must complete the quest "Echoes of Tortured Souls" before entering the Pit of Saron.' WHERE ID=483;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must complete the quest "Echoes of Tortured Souls" and be level 80 before entering the Heroic difficulty of the Pit of Saron.' WHERE ID=484;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must complete the quest "Deliverance from the Pit" before entering the Halls of Reflection.' WHERE ID=341;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must complete the quest "Deliverance from the Pit" and be level 80 before entering the Heroic difficulty of the Halls of Reflection.' WHERE ID=342;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=642;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=641;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=701;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='' WHERE ID=744;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be level 80 and in a raid group to enter.' WHERE ID=750;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be level 80 and in a raid group to enter.' WHERE ID=751;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be level 80 and in a raid group to enter.' WHERE ID=752;
UPDATE dbc_mapdifficulty SET Message_Lang_enGB='You must be level 80 and in a raid group to enter.' WHERE ID=753;
