UPDATE dbc_questsort SET SortName_Lang_enGB='Epic' WHERE ID=1;
UPDATE dbc_questsort SET SortName_Lang_enGB='REUSE - old wailing caverns' WHERE ID=21;
UPDATE dbc_questsort SET SortName_Lang_enGB='Seasonal' WHERE ID=22;
UPDATE dbc_questsort SET SortName_Lang_enGB='REUSE - old undercity one' WHERE ID=23;
UPDATE dbc_questsort SET SortName_Lang_enGB='Herbalism' WHERE ID=24;
UPDATE dbc_questsort SET SortName_Lang_enGB='Battlegrounds' WHERE ID=25;
UPDATE dbc_questsort SET SortName_Lang_enGB='Day of the Dead' WHERE ID=41;
UPDATE dbc_questsort SET SortName_Lang_enGB='Warlock' WHERE ID=61;
UPDATE dbc_questsort SET SortName_Lang_enGB='Warrior' WHERE ID=81;
UPDATE dbc_questsort SET SortName_Lang_enGB='Shaman' WHERE ID=82;
UPDATE dbc_questsort SET SortName_Lang_enGB='Fishing' WHERE ID=101;
UPDATE dbc_questsort SET SortName_Lang_enGB='Blacksmithing' WHERE ID=121;
UPDATE dbc_questsort SET SortName_Lang_enGB='Paladin' WHERE ID=141;
UPDATE dbc_questsort SET SortName_Lang_enGB='Mage' WHERE ID=161;
UPDATE dbc_questsort SET SortName_Lang_enGB='Rogue' WHERE ID=162;
UPDATE dbc_questsort SET SortName_Lang_enGB='Alchemy' WHERE ID=181;
UPDATE dbc_questsort SET SortName_Lang_enGB='Leatherworking' WHERE ID=182;
UPDATE dbc_questsort SET SortName_Lang_enGB='Engineering' WHERE ID=201;
UPDATE dbc_questsort SET SortName_Lang_enGB='Treasure Map' WHERE ID=221;
UPDATE dbc_questsort SET SortName_Lang_enGB='Tournament' WHERE ID=241;
UPDATE dbc_questsort SET SortName_Lang_enGB='Hunter' WHERE ID=261;
UPDATE dbc_questsort SET SortName_Lang_enGB='Priest' WHERE ID=262;
UPDATE dbc_questsort SET SortName_Lang_enGB='Druid' WHERE ID=263;
UPDATE dbc_questsort SET SortName_Lang_enGB='Tailoring' WHERE ID=264;
UPDATE dbc_questsort SET SortName_Lang_enGB='Special' WHERE ID=284;
UPDATE dbc_questsort SET SortName_Lang_enGB='Cooking' WHERE ID=304;
UPDATE dbc_questsort SET SortName_Lang_enGB='First Aid' WHERE ID=324;
UPDATE dbc_questsort SET SortName_Lang_enGB='Legendary' WHERE ID=344;
UPDATE dbc_questsort SET SortName_Lang_enGB='Darkmoon Faire' WHERE ID=364;
UPDATE dbc_questsort SET SortName_Lang_enGB='Ahn''Qiraj War' WHERE ID=365;
UPDATE dbc_questsort SET SortName_Lang_enGB='Lunar Festival' WHERE ID=366;
UPDATE dbc_questsort SET SortName_Lang_enGB='Reputation' WHERE ID=367;
UPDATE dbc_questsort SET SortName_Lang_enGB='Invasion' WHERE ID=368;
UPDATE dbc_questsort SET SortName_Lang_enGB='Midsummer' WHERE ID=369;
UPDATE dbc_questsort SET SortName_Lang_enGB='Brewfest' WHERE ID=370;
UPDATE dbc_questsort SET SortName_Lang_enGB='Inscription' WHERE ID=371;
UPDATE dbc_questsort SET SortName_Lang_enGB='Death Knight' WHERE ID=372;
UPDATE dbc_questsort SET SortName_Lang_enGB='Jewelcrafting' WHERE ID=373;
UPDATE dbc_questsort SET SortName_Lang_enGB='Noblegarden' WHERE ID=374;
UPDATE dbc_questsort SET SortName_Lang_enGB='Pilgrim''s Bounty' WHERE ID=375;
UPDATE dbc_questsort SET SortName_Lang_enGB='Love is in the Air' WHERE ID=376;
