UPDATE dbc_skillline SET DisplayName_Lang_enGB='Frost', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=6;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Fire', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=8;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Arms', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=26;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Combat', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=38;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Subtlety', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=39;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Swords', Description_Lang_enGB='Higher weapon skill increases your chance to hit.', AlternateVerb_Lang_enGB='' WHERE ID=43;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Axes', Description_Lang_enGB='Higher weapon skill increases your chance to hit.', AlternateVerb_Lang_enGB='' WHERE ID=44;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Bows', Description_Lang_enGB='Higher weapon skill increases your chance to hit.', AlternateVerb_Lang_enGB='' WHERE ID=45;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Guns', Description_Lang_enGB='Higher weapon skill increases your chance to hit.', AlternateVerb_Lang_enGB='' WHERE ID=46;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Beast Mastery', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=50;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Survival', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=51;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Maces', Description_Lang_enGB='Higher weapon skill increases your chance to hit.', AlternateVerb_Lang_enGB='' WHERE ID=54;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Two-Handed Swords', Description_Lang_enGB='Higher weapon skill increases your chance to hit.', AlternateVerb_Lang_enGB='' WHERE ID=55;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Holy', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=56;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Shadow Magic', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=78;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Defense', Description_Lang_enGB='Higher defense improves your chance to dodge, parry, and block attacks, makes you harder to hit,  and makes monsters less likely to land a critical strike against you.', AlternateVerb_Lang_enGB='' WHERE ID=95;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Language: Common', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=98;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Dwarven Racial', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=101;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Language: Orcish', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=109;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Language: Dwarven', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=111;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Language: Darnassian', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=113;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Language: Taurahe', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=115;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Dual Wield', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=118;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Tauren Racial', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=124;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Orc Racial', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=125;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Night Elf Racial', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=126;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='First Aid', Description_Lang_enGB='Higher first aid skill allows you to learn higher level first aid abilities.  First aid abilities can be found on trainers around the world as well as from quests and as drops from monsters.', AlternateVerb_Lang_enGB='' WHERE ID=129;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Feral Combat', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=134;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Staves', Description_Lang_enGB='Higher weapon skill increases your chance to hit.', AlternateVerb_Lang_enGB='' WHERE ID=136;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Language: Thalassian', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=137;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Language: Draconic', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=138;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Language: Demon Tongue', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=139;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Language: Titan', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=140;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Language: Old Tongue', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=141;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Survival', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=142;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Horse Riding', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=148;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Wolf Riding', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=149;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Tiger Riding', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=150;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Ram Riding', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=152;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Swimming', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=155;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Two-Handed Maces', Description_Lang_enGB='Higher weapon skill increases your chance to hit.', AlternateVerb_Lang_enGB='' WHERE ID=160;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Unarmed', Description_Lang_enGB='Higher skill increases your chance to hit.', AlternateVerb_Lang_enGB='' WHERE ID=162;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Marksmanship', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=163;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Blacksmithing', Description_Lang_enGB='Higher smithing skill allows you to learn higher level smithing plans.  Blacksmithing plans can be found on trainers around the world as well as from quests and monsters.', AlternateVerb_Lang_enGB='Modify' WHERE ID=164;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Leatherworking', Description_Lang_enGB='Higher leatherworking skill allows you to learn higher level leatherworking patterns.  Leatherworking patterns can be found on trainers around the world as well as from quests and monsters.', AlternateVerb_Lang_enGB='Emboss' WHERE ID=165;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Alchemy', Description_Lang_enGB='Higher alchemy skill allows you to learn higher level alchemy recipes.  Alchemy recipes can be found on trainers around the world as well as from quests and monsters.', AlternateVerb_Lang_enGB='Refill' WHERE ID=171;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Two-Handed Axes', Description_Lang_enGB='Higher weapon skill increases your chance to hit.', AlternateVerb_Lang_enGB='' WHERE ID=172;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Daggers', Description_Lang_enGB='Higher weapon skill increases your chance to hit.', AlternateVerb_Lang_enGB='' WHERE ID=173;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Thrown', Description_Lang_enGB='Higher weapon skill increases your chance to hit.', AlternateVerb_Lang_enGB='' WHERE ID=176;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Herbalism', Description_Lang_enGB='Higher herbalism skill allows you to harvest more difficult herbs around the world.  If you cannot harvest a specific herb, then increase your skill by harvesting easier to gather herbs in lower level areas.', AlternateVerb_Lang_enGB='' WHERE ID=182;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='GENERIC (DND)', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=183;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Retribution', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=184;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Cooking', Description_Lang_enGB='Higher cooking skill allows you to learn higher level cooking recipes.  Recipes can be found on trainers around the world as well as from quests and as drops from monsters.', AlternateVerb_Lang_enGB='' WHERE ID=185;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Mining', Description_Lang_enGB='Higher mining skill allows you to harvest more difficult minerals nodes around the world.  If you cannot harvest a specific mineral, then increase your skill by mining easier to mine minerals in lower level areas.', AlternateVerb_Lang_enGB='' WHERE ID=186;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Imp', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=188;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Felhunter', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=189;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Tailoring', Description_Lang_enGB='Higher tailoring skill allows you to learn higher level tailoring patterns.  Tailoring patterns can be found on trainers around the world as well as from quests and monsters.', AlternateVerb_Lang_enGB='Embroider' WHERE ID=197;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Engineering', Description_Lang_enGB='Higher engineering skill allows you to learn higher level engineering schematics.  Schematics can be found on trainers around the world as well as from quests and monsters.', AlternateVerb_Lang_enGB='Tinker' WHERE ID=202;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Spider', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=203;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Voidwalker', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=204;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Succubus', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=205;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Infernal', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=206;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Doomguard', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=207;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Wolf', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=208;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Cat', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=209;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Bear', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=210;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Boar', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=211;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Crocolisk', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=212;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Carrion Bird', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=213;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Crab', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=214;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Gorilla', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=215;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Raptor', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=217;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Tallstrider', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=218;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Racial - Undead', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=220;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Crossbows', Description_Lang_enGB='Higher weapon skill increases your chance to hit.', AlternateVerb_Lang_enGB='' WHERE ID=226;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Wands', Description_Lang_enGB='Higher weapon skill increases your chance to hit.', AlternateVerb_Lang_enGB='' WHERE ID=228;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Polearms', Description_Lang_enGB='Higher weapon skill increases your chance to hit.', AlternateVerb_Lang_enGB='' WHERE ID=229;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Scorpid', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=236;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Arcane', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=237;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Turtle', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=251;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Assassination', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=253;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Fury', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=256;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Protection', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=257;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Protection', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=267;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Generic Hunter', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=270;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Plate Mail', Description_Lang_enGB='Allows the wearing of plate armor.', AlternateVerb_Lang_enGB='' WHERE ID=293;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Language: Gnomish', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=313;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Language: Troll', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=315;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Enchanting', Description_Lang_enGB='Higher enchanting skill allows you to learn more powerful formulae.  Formulae can be found on trainers around the world as well as from quests and monsters.', AlternateVerb_Lang_enGB='Enchant' WHERE ID=333;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Demonology', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=354;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Affliction', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=355;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Fishing', Description_Lang_enGB='Higher fishing skill increases your chance of catching fish in bodies of water around the world.  If you are having trouble catching fish in a given area, move to a lower level area or purchase a fishing lure and try again.', AlternateVerb_Lang_enGB='' WHERE ID=356;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Enhancement', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=373;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Restoration', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=374;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Elemental Combat', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=375;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Skinning', Description_Lang_enGB='Higher skinning skill allows you to skin hides from higher level monsters around the world.    Once your skill is above 100, you can divide your skill by 5 to determine the highest level of monster you can skin.', AlternateVerb_Lang_enGB='' WHERE ID=393;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Mail', Description_Lang_enGB='Allows the wearing of mail armor.', AlternateVerb_Lang_enGB='' WHERE ID=413;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Leather', Description_Lang_enGB='Allows the wearing of leather armor.', AlternateVerb_Lang_enGB='' WHERE ID=414;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Cloth', Description_Lang_enGB='Allows the wearing of cloth armor.', AlternateVerb_Lang_enGB='' WHERE ID=415;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Shield', Description_Lang_enGB='Allows the use of shields.', AlternateVerb_Lang_enGB='' WHERE ID=433;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Fist Weapons', Description_Lang_enGB='Allows for the use of fist weapons.  Chance to hit is determined by the Unarmed skill.', AlternateVerb_Lang_enGB='' WHERE ID=473;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Raptor Riding', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=533;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Mechanostrider Piloting', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=553;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Undead Horsemanship', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=554;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Restoration', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=573;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Balance', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=574;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Destruction', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=593;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Holy', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=594;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Discipline', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=613;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Lockpicking', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=633;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Bat', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=653;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Hyena', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=654;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Bird of Prey', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=655;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Wind Serpent', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=656;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Language: Gutterspeak', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=673;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Kodo Riding', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=713;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Racial - Troll', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=733;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Racial - Gnome', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=753;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Racial - Human', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=754;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Jewelcrafting', Description_Lang_enGB='Higher jewelcrafting skill allows you to learn higher level jewelcrafting plans.  Jewelcrafting plans can be found on trainers around the world as well as from quests and monsters.', AlternateVerb_Lang_enGB='Modify' WHERE ID=755;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Blood Elf Racial', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=756;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Event - Remote Control', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=758;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Language: Draenei', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=759;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Draenei Racial', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=760;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Felguard', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=761;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Riding', Description_Lang_enGB='Higher riding skill allows you to ride faster and more exotic beasts.', AlternateVerb_Lang_enGB='' WHERE ID=762;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Dragonhawk', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=763;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Nether Ray', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=764;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Sporebat', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=765;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Warp Stalker', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=766;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Ravager', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=767;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Serpent', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=768;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Internal', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=769;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Blood', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=770;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Frost', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=771;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Unholy', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=772;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Inscription', Description_Lang_enGB='Higher inscription skill allows you to learn more advanced inscriptions.  Inscriptions are acquired from learned scribes throughout the world.', AlternateVerb_Lang_enGB='Inscribe' WHERE ID=773;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Moth', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=775;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Runeforging', Description_Lang_enGB='', AlternateVerb_Lang_enGB='Engrave' WHERE ID=776;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Mounts', Description_Lang_enGB='Your mounts.', AlternateVerb_Lang_enGB='' WHERE ID=777;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Companions', Description_Lang_enGB='Your companions.', AlternateVerb_Lang_enGB='' WHERE ID=778;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Exotic Chimaera', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=780;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Exotic Devlisaur', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=781;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Ghoul', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=782;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Exotic Silithid', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=783;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Exotic Worm', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=784;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet- Wasp', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=785;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Exotic Rhino', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=786;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Exotic Core Hound', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=787;
UPDATE dbc_skillline SET DisplayName_Lang_enGB='Pet - Exotic Spirit Beast', Description_Lang_enGB='', AlternateVerb_Lang_enGB='' WHERE ID=788;
