UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Anvil' WHERE ID=1;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Loom' WHERE ID=2;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Forge' WHERE ID=3;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Cooking Fire' WHERE ID=4;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Shards of Myzrael' WHERE ID=5;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Winterhoof Water Well' WHERE ID=6;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Thunderhorn Water Well' WHERE ID=7;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Wildmane Water Well' WHERE ID=8;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Tribal Fire' WHERE ID=9;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Machine Shop' WHERE ID=10;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Shadowglen Moonwell' WHERE ID=11;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Starbreeze Village Moonwell' WHERE ID=12;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Pools of Arlithrien Moonwell' WHERE ID=13;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Oracle Glade Moonwell' WHERE ID=14;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Venture Co. Airport' WHERE ID=15;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Venture Co. Wagon (Blue)' WHERE ID=16;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Venture Co. Wagon (Red)' WHERE ID=17;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='NG-5 Explosives (Red)' WHERE ID=18;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='NG-5 Explosives (Blue)' WHERE ID=19;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Flame of Uzel' WHERE ID=20;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ashenvale Moonwell' WHERE ID=21;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Seaworn Altar' WHERE ID=22;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Nearby Tubers' WHERE ID=23;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Undercity Summoning Circle' WHERE ID=43;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Shaman Shrine' WHERE ID=63;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Stormwind Summoning Circle' WHERE ID=83;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Barrens Summoning Circle' WHERE ID=103;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Mirror Lake Waterfall' WHERE ID=123;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Talon Den' WHERE ID=143;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Xavian Waterfall' WHERE ID=163;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Stone of Outer Binding' WHERE ID=164;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Mana Rift Disturbance' WHERE ID=183;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Orgrimmar Summoning Circle' WHERE ID=203;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Wrathscale Fountain' WHERE ID=223;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Quilboar Watering Hole' WHERE ID=224;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Water Purity - Silverpine' WHERE ID=225;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Spring Well' WHERE ID=226;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Temple of the Moon Fountain' WHERE ID=243;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Jintha''Alor Altar' WHERE ID=263;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Pirate Ship Bilge' WHERE ID=264;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Equinex Monolith' WHERE ID=283;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Witherbark Village' WHERE ID=303;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Shadra''Alor Altar' WHERE ID=304;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Sandsorrow Watch Water Hole' WHERE ID=323;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Hatetalon Stones' WHERE ID=343;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Echeyakee''s Lair' WHERE ID=363;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='The Dead Tree' WHERE ID=383;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Makeshift Helipad' WHERE ID=403;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Circle of Aquementas' WHERE ID=423;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Sanctum of the Fallen God' WHERE ID=424;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='the First Tide Pool' WHERE ID=443;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='the Second Tide Pool' WHERE ID=444;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='the Third Tide Pool' WHERE ID=445;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='the Fourth Tide Pool' WHERE ID=446;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Gorishi Hive Hatchery' WHERE ID=463;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Miblon Snarltooth' WHERE ID=483;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Gadgetzan Graveyard' WHERE ID=503;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='the ruins of Irontree Woods' WHERE ID=523;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Black Forge' WHERE ID=543;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Golakka Crater' WHERE ID=563;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Tomb of the Seven' WHERE ID=583;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Flat Un''Goro Rock' WHERE ID=603;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Preserved Threshadon Carcass' WHERE ID=604;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Black Anvil' WHERE ID=623;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Gorishi Silithid Crystal' WHERE ID=643;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Corrupted Moonwell' WHERE ID=644;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Alchemy Lab' WHERE ID=663;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Unforged Seal of Ascension' WHERE ID=683;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Auberdine Moonwell' WHERE ID=703;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Blackwood Furbolg North Bonfire' WHERE ID=704;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Cliffspring River Waterfall' WHERE ID=705;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Fire Plume Ridge Hot Spot' WHERE ID=723;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Urok''s Tribute Pile' WHERE ID=743;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Andorhal Silo Temporal Rift' WHERE ID=763;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Stone of Shy-Rotam' WHERE ID=783;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Sacred Fire of Life' WHERE ID=803;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Scarlet Crusade Forward Camp' WHERE ID=804;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Andorhal Tower' WHERE ID=805;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Scholomance Viewing Room' WHERE ID=823;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='the Jaedenar Corrupt Moon Well' WHERE ID=843;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Umi''s Friend' WHERE ID=863;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Moonwell' WHERE ID=883;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Fire Plume Ridge Lava Lake' WHERE ID=903;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='the crate in the center of the Northridge Lumber Mill' WHERE ID=923;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Moonkin Stone' WHERE ID=943;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Darrowshire Town Square' WHERE ID=944;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Bright Light Beam' WHERE ID=963;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Mark of Detonation' WHERE ID=983;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Cliffspring Falls Cave Mouth' WHERE ID=1003;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Dreadmist Peak Pool' WHERE ID=1004;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='The Dead Goliaths' WHERE ID=1023;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Shrine of Remulos' WHERE ID=1043;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Foulweald Totem Mound' WHERE ID=1063;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Dire Pool' WHERE ID=1083;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Maraudon Portal' WHERE ID=1103;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Horde Globe of Scrying' WHERE ID=1123;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Eastern Crater' WHERE ID=1143;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Western Crater' WHERE ID=1144;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Snowfall Graveyard' WHERE ID=1145;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Alliance Globe of Scrying' WHERE ID=1163;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Dun Baldar Courtyard' WHERE ID=1164;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Frostwolf Keep Courtyard' WHERE ID=1165;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Snowfall Graveyard' WHERE ID=1183;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='East Crater' WHERE ID=1184;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='West Crater' WHERE ID=1185;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Orange Crystal Pool' WHERE ID=1203;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Onyxia''s Flame Breath' WHERE ID=1223;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Kroshius'' Remains' WHERE ID=1243;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Pedestal of Immol''thar' WHERE ID=1263;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Circle of Dark Summoning' WHERE ID=1264;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='The Great Ossuary' WHERE ID=1283;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Terrordale Haunting Spirit' WHERE ID=1284;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Aerie Peak Town Center' WHERE ID=1303;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Uther''s Tomb Statue' WHERE ID=1323;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Grom''s Monument' WHERE ID=1324;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Pagle''s Pointe' WHERE ID=1343;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Altar of Zanza' WHERE ID=1344;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Southshore' WHERE ID=1345;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Bones of Grakkarond' WHERE ID=1346;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Forsaken Stink Bomb' WHERE ID=1347;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Drop-Off Point' WHERE ID=1348;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Swirling Maelstrom' WHERE ID=1349;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='High Chief Winterfall''s Cave' WHERE ID=1350;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Firework Launcher' WHERE ID=1351;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Cluster Launcher' WHERE ID=1352;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Greater Moonlight' WHERE ID=1353;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Voone''s Chamber' WHERE ID=1354;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Alzzin''s Chamber' WHERE ID=1355;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='The Crimson Throne' WHERE ID=1356;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ras Frostwhisper''s Chamber' WHERE ID=1357;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='The Beast''s Chamber' WHERE ID=1358;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Haunted Locus' WHERE ID=1359;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Blackrock Depths Arena' WHERE ID=1360;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='[PH] Crystal Corpse' WHERE ID=1361;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Icebellow Anvil' WHERE ID=1362;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Eversong Runestone' WHERE ID=1363;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Consecrated Earth' WHERE ID=1364;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Midsummer Bonfire' WHERE ID=1365;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Maypole' WHERE ID=1366;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Altar of Aggonar' WHERE ID=1367;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Bones of Aggonar' WHERE ID=1368;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='School of Red Snapper' WHERE ID=1369;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Krun Spinebreaker''s Corpse' WHERE ID=1370;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Thalanaar Moonwell' WHERE ID=1371;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Concealed Control Panel' WHERE ID=1372;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Altar of Naias' WHERE ID=1373;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Discreet Location' WHERE ID=1374;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Rune of Summoning' WHERE ID=1375;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Fel Brazier' WHERE ID=1376;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='you to be in Traitor''s Cove while the Naga Flag is up.' WHERE ID=1377;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Sedai''s Corpse' WHERE ID=1378;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Nazzivus Monument' WHERE ID=1379;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Impact Site Crystal' WHERE ID=1380;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Altered Bloodmyst Crystal' WHERE ID=1381;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Axxarien Crystal' WHERE ID=1382;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='the southern end of the Master''s Terrace' WHERE ID=1383;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Medivh''s Telescope' WHERE ID=1384;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Alonsus Chapel Eternal Flame' WHERE ID=1385;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Bloodmyst Waterfall' WHERE ID=1386;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Steam Pump Controls' WHERE ID=1387;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Windyreed Hut' WHERE ID=1388;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Earthen Brand' WHERE ID=1389;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Underground Water Source' WHERE ID=1390;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Boha''mu Ruins Stairs' WHERE ID=1391;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Daggerfen Rock' WHERE ID=1392;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Burning Blade pyre in the Burning Blade Ruins.' WHERE ID=1393;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ysiel''s Balcony' WHERE ID=1394;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Blazing Warmaul Pyre' WHERE ID=1395;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Veil Shalas Totem' WHERE ID=1396;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Trampled Skeleton' WHERE ID=1397;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Alliance Cannon' WHERE ID=1398;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Horde Blade Thrower' WHERE ID=1399;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Legion Antenna' WHERE ID=1400;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Scorched Grove Runestone' WHERE ID=1401;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Bookcase' WHERE ID=1402;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Weapon Rack' WHERE ID=1403;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Dresser' WHERE ID=1404;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Footlocker' WHERE ID=1405;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ruined Alliance Siege Tower' WHERE ID=1406;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Uncontrolled Scrap Reaver X6000' WHERE ID=1407;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Kirin''Var Rune' WHERE ID=1408;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Archmage Vargoth''s Orb' WHERE ID=1409;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Elrendar Falls' WHERE ID=1410;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Dragon Skeleton' WHERE ID=1411;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ethereal Teleport Pad' WHERE ID=1412;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Arklon Brazier' WHERE ID=1413;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Void Stone' WHERE ID=1414;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Manaforge B''naar Pipe' WHERE ID=1415;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Draenei Banner' WHERE ID=1416;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Earthbinder''s Circle' WHERE ID=1417;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Salhadaar''s Power Conduit' WHERE ID=1418;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Socrethar''s Teleporter' WHERE ID=1419;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Eco-Dome Sutheron Generator' WHERE ID=1420;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='you to be closer to Manaforge Ultris' WHERE ID=1421;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Northmaul Tower' WHERE ID=1422;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Altar of Shadows' WHERE ID=1423;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Shadowmoon Tuber Mound' WHERE ID=1424;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Rokgah Bloodgrip' WHERE ID=1425;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Mana Loom' WHERE ID=1426;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ancient Draenei Altar' WHERE ID=1427;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ogre Building Entrance' WHERE ID=1428;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Blade''s Edge Arakkoa Circle' WHERE ID=1429;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Lashh''an Spell Circle' WHERE ID=1430;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Vekh''nir Circle of Power' WHERE ID=1431;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='you to be at the end of the bridge.' WHERE ID=1432;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Torgos''s Bane' WHERE ID=1433;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Vekh''nir Spell Circle' WHERE ID=1434;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='you to be standing next to Gul''dan at the Altar of Damnation.' WHERE ID=1435;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Legion Hold Teleporter' WHERE ID=1436;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ruuan''ok Oracle Circle' WHERE ID=1437;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Legion Communication Device' WHERE ID=1438;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Foreman Razelcraz' WHERE ID=1439;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Portal at Marshlight Lake' WHERE ID=1440;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Blade''s Edge - Quest - Bird Spying' WHERE ID=1441;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Malukaz''s Candles' WHERE ID=1442;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Bleeding Hollow Forge' WHERE ID=1443;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Marmot Den' WHERE ID=1444;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Gehenna Teleporter' WHERE ID=1445;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Force Commander Gorax''s Corpse' WHERE ID=1446;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Zeth''Gor Tower' WHERE ID=1447;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Unguarded Summoning Site' WHERE ID=1448;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Locked Wyvern Cage' WHERE ID=1449;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Gorgrom''s Corpse' WHERE ID=1450;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Death''s Door Fel Cannon' WHERE ID=1451;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Writhing Mound Summoning Circle' WHERE ID=1452;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Altar of Goc and that Goc has not been summoned' WHERE ID=1453;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='The Raven''s Claw' WHERE ID=1454;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Arakkoa Shrine' WHERE ID=1455;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Soulgrinder''s Altar' WHERE ID=1456;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Shartuul''s Transporter Platform' WHERE ID=1457;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Shipwreck Debris' WHERE ID=1458;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Blackhoof Village Windmill' WHERE ID=1459;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Grimtotem Tent' WHERE ID=1460;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Hyal Family Monument' WHERE ID=1461;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Burning Troll Hut' WHERE ID=1462;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Entrance to Onyxia''s Lair' WHERE ID=1463;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Swamplight Manor Dock' WHERE ID=1464;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='The Wyrmcaller''s Platform' WHERE ID=1465;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Shattered Strand Cannon' WHERE ID=1466;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='cannon on northern Alliance wall.' WHERE ID=1467;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='The Thane''s Pyre' WHERE ID=1468;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Frozen Waterfall' WHERE ID=1469;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='proximity to plaguehound cages at Vengeance Landing.' WHERE ID=1470;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Standing at the Booth Counter' WHERE ID=1471;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Cauldron of Vrykul Blood.' WHERE ID=1472;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Harris''s Plague Samples.' WHERE ID=1473;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='you to be closer to plaguehound cages.' WHERE ID=1474;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Broken Tablet' WHERE ID=1475;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Sunken Boat' WHERE ID=1476;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Center of Baleheim' WHERE ID=1477;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Brewfest - Mug Request' WHERE ID=1478;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Walt''s Transport Rune' WHERE ID=1479;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Iron Dwarf Transport Rune' WHERE ID=1480;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ley Lines of Quel''Danas' WHERE ID=1481;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Razorthorn Dirt Mound' WHERE ID=1482;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Crystal Ward' WHERE ID=1483;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Legion Teleporter' WHERE ID=1484;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Hauthaa''s Anvil' WHERE ID=1485;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Vrykul Burial Mound' WHERE ID=1486;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Westrift Seismic Anomaly' WHERE ID=1487;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='JSB - Reuse post 2.4.0' WHERE ID=1488;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Nerub''ar Sinkhole' WHERE ID=1489;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Snarlfang''s Totem' WHERE ID=1490;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='En''kilah Cauldron' WHERE ID=1491;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='you to be at or near the front of a Kvaldir ship.' WHERE ID=1492;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='you to be standing at the end of Warsong Jetty.' WHERE ID=1493;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Imprisoned Beryl Sorcerer' WHERE ID=1494;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Beryl Force Shield' WHERE ID=1495;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Den of Dying Plague Cauldron' WHERE ID=1496;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='South Sinkhole' WHERE ID=1497;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='you to be at the crossroads, east of Warsong Hold with an Alliance Deserter in tow.' WHERE ID=1498;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='you to be standing next to Bloodmage Laurith at the Bloodspore Plains.' WHERE ID=1499;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Shattered Sun Portal' WHERE ID=1500;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Shattered Sun Portal' WHERE ID=1501;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Crashed Flying Machine' WHERE ID=1502;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Geyser Fields Steam Vent' WHERE ID=1503;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Nexus Dimensional Rift' WHERE ID=1504;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Farshire Grain' WHERE ID=1505;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Saragosa''s Landing' WHERE ID=1506;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='proximity to a Scourge sinkhole.' WHERE ID=1507;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Northwest Nexus Entrance' WHERE ID=1508;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Drakuru''s Brazier' WHERE ID=1509;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='East End of Thor Modan Tunnel' WHERE ID=1510;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Tua''kea''s Fishing Hook' WHERE ID=1511;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Toalu''u''s Brazier' WHERE ID=1512;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Fizzcrank Practice Parachute Zone' WHERE ID=1513;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Fizzcrank Paratrooper Teleporter' WHERE ID=1514;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ley Line Focus on the Beach' WHERE ID=1515;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ley Line Focus in the Lothalor Woodlands' WHERE ID=1516;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ley Line Focus Under the Lake' WHERE ID=1517;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Drakil''jin Gongs' WHERE ID=1518;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Marked Coldwind Tree' WHERE ID=1519;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Center of the pit under the Surge Needle' WHERE ID=1520;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='depths below Vordrassil''s remains.' WHERE ID=1521;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='depths below Vordrassil''s Limb.' WHERE ID=1522;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='depths below Vordrassil''s Tears.' WHERE ID=1523;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Hansel Bauer' WHERE ID=1524;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Grom''thar''s Challenging Area' WHERE ID=1525;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Wintergarde Gryphon Station' WHERE ID=1526;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='New Hearthglen Lumbermill' WHERE ID=1527;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Vordrassil''s Sapling' WHERE ID=1528;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Basecamp' WHERE ID=1529;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Obsidian Dragonshrine Exit Path' WHERE ID=1530;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='you to be standing next to Siege Engineer Quarterflash.' WHERE ID=1531;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Necromantic Rune' WHERE ID=1532;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='you to be standing at one of the entrance points to Wintergarde Mine.' WHERE ID=1533;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='School of Northern Salmon' WHERE ID=1534;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='you to be standing in the center of the ruins at the Forgotten Shore.' WHERE ID=1535;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='you to be at the front of the Wintergarde Mausoleum.' WHERE ID=1536;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ruuna''s Crystal Ball' WHERE ID=1537;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Squire Percy' WHERE ID=1538;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='that you be closer to Alystros the Verdant Keeper' WHERE ID=1539;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Frostmourne Altar' WHERE ID=1540;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='that you be on the sands of the Bronze Dragonshrine' WHERE ID=1541;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Vrykul Hawk Roost' WHERE ID=1542;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Scourged Mummy Fire' WHERE ID=1543;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Drakkari Ritual Statue' WHERE ID=1544;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Finklestein''s Cauldron' WHERE ID=1545;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Mistwhisper Weather Shrine' WHERE ID=1546;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Offering Bowl' WHERE ID=1547;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Drakkari Pedestal' WHERE ID=1548;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Fallen Log' WHERE ID=1549;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ancient Dirt Mound' WHERE ID=1550;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Nerubian Crater' WHERE ID=1551;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Runeforge' WHERE ID=1552;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Landing Pad' WHERE ID=1553;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Scourgewagon' WHERE ID=1554;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Quetz''lun''s Corpse and that the Prophet of Quetz''lun be present and unengaged' WHERE ID=1555;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Altar of Kartak' WHERE ID=1556;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Great Lightning Stone' WHERE ID=1557;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Warlord Zol''Maz present and unengaged in combat.' WHERE ID=1558;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Top of the Suntouched Pillar' WHERE ID=1559;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Convocation Summoning Circle' WHERE ID=1560;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Soaked Fertile Dirt' WHERE ID=1561;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Top of Sholazar Pillar' WHERE ID=1562;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Top of the Glimmering Pillar' WHERE ID=1563;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Exposed Lifeblood Pillar Crystal' WHERE ID=1564;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Uzo Deathcaller' WHERE ID=1565;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Archbishop Landgren''s corpse and Lord-Commander Arete not be present' WHERE ID=1566;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='School of Tasty Reef Fish' WHERE ID=1567;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Magmawyrm Resurrection Chamber' WHERE ID=1568;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Frostgut''s Altar' WHERE ID=1569;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Garm Teleporter' WHERE ID=1570;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Thane Ufrang the Mighty present and seated' WHERE ID=1571;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Northern Ice Spike' WHERE ID=1572;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Icy Crater' WHERE ID=1573;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Vanguard Infirmary' WHERE ID=1574;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Snowdrift' WHERE ID=1575;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='the Broodmother''s Nest' WHERE ID=1576;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='K3 Landing' WHERE ID=1577;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Thane Illskar be present and that he and his champions not be engaged in battle' WHERE ID=1578;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Pile of Crusader Skulls' WHERE ID=1579;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Malykriss Furnace' WHERE ID=1580;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ahn''kahet Brazier' WHERE ID=1581;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Sanctum of Reanimation Slab' WHERE ID=1582;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Dalaran Fountain' WHERE ID=1583;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ymirheim Peak Skulls' WHERE ID=1584;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Mord''rethar Plague Cauldron' WHERE ID=1585;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Grimkor''s Orb' WHERE ID=1586;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Cultists'' Cauldron' WHERE ID=1587;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Alumeth''s Soulstone' WHERE ID=1588;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='you to be near a Lexicon of Power' WHERE ID=1589;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Smoldering Scrap' WHERE ID=1590;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Altar of the Ebon Depths' WHERE ID=1591;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Corpse of the Fallen Worg' WHERE ID=1592;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Unlit Signal Fire' WHERE ID=1596;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Drak''Mar Offering Ring' WHERE ID=1597;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Tournament Stables' WHERE ID=1599;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Black Knight''s Gryphon' WHERE ID=1601;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Stone Block' WHERE ID=1602;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Ghostly Cooking Fire' WHERE ID=1613;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Mysterious Snow Mound' WHERE ID=1618;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Mistcaller''s Cave' WHERE ID=1620;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Tualiq Monuments' WHERE ID=1621;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='the deck of Bor''s Fury' WHERE ID=1622;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Forgemaster''s Anvil' WHERE ID=1636;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Crown Supply Camp' WHERE ID=1639;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Sunwell' WHERE ID=1641;
UPDATE dbc_spellfocusobject SET Name_Lang_enGB='Chemical Wagon' WHERE ID=1650;
