UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Self Only', DisplayNameShort_Lang_enGB='Self' WHERE ID=1;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Combat Range', DisplayNameShort_Lang_enGB='Combat' WHERE ID=2;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Twenty yards', DisplayNameShort_Lang_enGB='Short' WHERE ID=3;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Medium Range', DisplayNameShort_Lang_enGB='Medium' WHERE ID=4;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Long Range', DisplayNameShort_Lang_enGB='Long' WHERE ID=5;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Vision Range', DisplayNameShort_Lang_enGB='Vision' WHERE ID=6;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Ten yards', DisplayNameShort_Lang_enGB='Very Short' WHERE ID=7;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Min Range 10, 20', DisplayNameShort_Lang_enGB='Short' WHERE ID=8;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Medium Range', DisplayNameShort_Lang_enGB='Medium' WHERE ID=9;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Long Range', DisplayNameShort_Lang_enGB='Long' WHERE ID=10;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Fifteen yards', DisplayNameShort_Lang_enGB='Shorter' WHERE ID=11;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Interact Range', DisplayNameShort_Lang_enGB='Interact' WHERE ID=12;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Anywhere', DisplayNameShort_Lang_enGB='Anywhere' WHERE ID=13;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Extra Long Range', DisplayNameShort_Lang_enGB='Extra Long' WHERE ID=14;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Twenty-Five yards', DisplayNameShort_Lang_enGB='Medium-Short' WHERE ID=34;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Medium-Long Range', DisplayNameShort_Lang_enGB='Medium-Long' WHERE ID=35;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Longer Range', DisplayNameShort_Lang_enGB='Longer' WHERE ID=36;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Extended Range', DisplayNameShort_Lang_enGB='Extended' WHERE ID=37;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Min-Range 10, 25', DisplayNameShort_Lang_enGB='Extra Medium' WHERE ID=38;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Monster Shoot', DisplayNameShort_Lang_enGB='Monster Shoot Range' WHERE ID=54;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Ranged Weapon', DisplayNameShort_Lang_enGB='Ranged' WHERE ID=74;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Sting', DisplayNameShort_Lang_enGB='Sting' WHERE ID=94;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Charge', DisplayNameShort_Lang_enGB='Charge' WHERE ID=95;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Trap', DisplayNameShort_Lang_enGB='Trap' WHERE ID=96;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Hunter Range', DisplayNameShort_Lang_enGB='Hunter' WHERE ID=114;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Tower 80', DisplayNameShort_Lang_enGB='Tower' WHERE ID=134;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Tower 100', DisplayNameShort_Lang_enGB='Tower' WHERE ID=135;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Thirty-to-80', DisplayNameShort_Lang_enGB='Thirty-to-80' WHERE ID=136;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Eight yards', DisplayNameShort_Lang_enGB='Very Short' WHERE ID=137;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Long Range Hunter Shoot', DisplayNameShort_Lang_enGB='Hunter Long' WHERE ID=139;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Six yards', DisplayNameShort_Lang_enGB='Six yards' WHERE ID=140;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Seven yards', DisplayNameShort_Lang_enGB='Seven yards' WHERE ID=141;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Valgarde 8/100', DisplayNameShort_Lang_enGB='Valgarde' WHERE ID=150;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Long Range Hunter Shoot', DisplayNameShort_Lang_enGB='Hunter 45' WHERE ID=151;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Super Long', DisplayNameShort_Lang_enGB='Super Long' WHERE ID=152;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Charge, 60', DisplayNameShort_Lang_enGB='Huge Charge' WHERE ID=153;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Tower 80, 10', DisplayNameShort_Lang_enGB='Tower 10' WHERE ID=154;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Hunter Range (Long)', DisplayNameShort_Lang_enGB='Hunter (Long)' WHERE ID=155;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Boulder Range', DisplayNameShort_Lang_enGB='Boulder' WHERE ID=156;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Ninety', DisplayNameShort_Lang_enGB='Ninety' WHERE ID=157;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Super Long, 15 Min', DisplayNameShort_Lang_enGB='Super Long' WHERE ID=158;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='TEST - Long Range', DisplayNameShort_Lang_enGB='TestLong' WHERE ID=159;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Medium/Long Range', DisplayNameShort_Lang_enGB='Medium/Long' WHERE ID=160;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Short/Long Range', DisplayNameShort_Lang_enGB='Short/Long' WHERE ID=161;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Medium/Short Range', DisplayNameShort_Lang_enGB='Medium/Short' WHERE ID=162;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Death Grip', DisplayNameShort_Lang_enGB='Death Grip' WHERE ID=163;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Catapult Range', DisplayNameShort_Lang_enGB='Catapult' WHERE ID=164;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Fourteen yards', DisplayNameShort_Lang_enGB='Shorter' WHERE ID=165;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Thirteen yards', DisplayNameShort_Lang_enGB='Shorter' WHERE ID=166;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Super Long (Min Range)', DisplayNameShort_Lang_enGB='Super Long' WHERE ID=167;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Medium-Long Range (38)', DisplayNameShort_Lang_enGB='Medium-Long' WHERE ID=168;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Three Yards', DisplayNameShort_Lang_enGB='Three Yards' WHERE ID=169;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Fifty Five Yards', DisplayNameShort_Lang_enGB='Extended' WHERE ID=170;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Min Range 1, 10', DisplayNameShort_Lang_enGB='Very Short' WHERE ID=171;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Eleven yards', DisplayNameShort_Lang_enGB='Shorter' WHERE ID=172;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Anywhere (Combat Min Range)', DisplayNameShort_Lang_enGB='Hunter Long' WHERE ID=173;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='U L T R A', DisplayNameShort_Lang_enGB='U L T R A' WHERE ID=174;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Seventy yards', DisplayNameShort_Lang_enGB='Extended' WHERE ID=176;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Donut 20-70', DisplayNameShort_Lang_enGB='Donut 20-70' WHERE ID=177;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Min Range 5, 15', DisplayNameShort_Lang_enGB='Shorter' WHERE ID=179;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Tournament - Ranged', DisplayNameShort_Lang_enGB='Argent Tournament - Ranged' WHERE ID=180;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Two-Hundred Yard Range', DisplayNameShort_Lang_enGB='200' WHERE ID=181;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Min Range 5, 25', DisplayNameShort_Lang_enGB='Medium' WHERE ID=184;
UPDATE dbc_spellrange SET DisplayName_Lang_enGB='Three Hundred Yards', DisplayNameShort_Lang_enGB='300' WHERE ID=187;
