UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Cat Form' WHERE ID=1;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Tree of Life Form' WHERE ID=2;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Travel Form' WHERE ID=3;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Aquatic Form' WHERE ID=4;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Bear Form' WHERE ID=5;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Ambient' WHERE ID=6;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Ghoul' WHERE ID=7;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Dire Bear Form' WHERE ID=8;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Steve''s Ghoul' WHERE ID=9;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Tharon''ja Skeleton' WHERE ID=10;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Darkmoon - Test of Strength' WHERE ID=11;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='BLB Player' WHERE ID=12;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Shadow Dance' WHERE ID=13;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Creature - Bear' WHERE ID=14;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Creature - Cat' WHERE ID=15;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Ghost Wolf' WHERE ID=16;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Battle Stance' WHERE ID=17;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Defensive Stance' WHERE ID=18;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Berserker Stance' WHERE ID=19;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Test' WHERE ID=20;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Zombie' WHERE ID=21;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Metamorphosis' WHERE ID=22;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='' WHERE ID=23;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='' WHERE ID=24;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Undead' WHERE ID=25;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Frenzy' WHERE ID=26;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Flight Form, Epic' WHERE ID=27;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Shadowform' WHERE ID=28;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Flight Form' WHERE ID=29;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Stealth' WHERE ID=30;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Moonkin Form' WHERE ID=31;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enGB='Spirit of Redemption' WHERE ID=32;
