UPDATE dbc_taxinodes SET Name_Lang_enGB='Northshire Abbey' WHERE ID=1;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Stormwind, Elwynn' WHERE ID=2;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Programmer Isle' WHERE ID=3;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Sentinel Hill, Westfall' WHERE ID=4;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Lakeshire, Redridge' WHERE ID=5;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Ironforge, Dun Morogh' WHERE ID=6;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Menethil Harbor, Wetlands' WHERE ID=7;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Thelsamar, Loch Modan' WHERE ID=8;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Booty Bay, Stranglethorn' WHERE ID=9;
UPDATE dbc_taxinodes SET Name_Lang_enGB='The Sepulcher, Silverpine Forest' WHERE ID=10;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Undercity, Tirisfal' WHERE ID=11;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Darkshire, Duskwood' WHERE ID=12;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Tarren Mill, Hillsbrad' WHERE ID=13;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Southshore, Hillsbrad' WHERE ID=14;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Eastern Plaguelands' WHERE ID=15;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Refuge Pointe, Arathi' WHERE ID=16;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Hammerfall, Arathi' WHERE ID=17;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Booty Bay, Stranglethorn' WHERE ID=18;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Booty Bay, Stranglethorn' WHERE ID=19;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Grom''gol, Stranglethorn' WHERE ID=20;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Kargath, Badlands' WHERE ID=21;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Thunder Bluff, Mulgore' WHERE ID=22;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Orgrimmar, Durotar' WHERE ID=23;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Generic, World Target 002' WHERE ID=24;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Crossroads, The Barrens' WHERE ID=25;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Auberdine, Darkshore' WHERE ID=26;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Rut''theran Village, Teldrassil' WHERE ID=27;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Astranaar, Ashenvale' WHERE ID=28;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Sun Rock Retreat, Stonetalon Mountains' WHERE ID=29;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Freewind Post, Thousand Needles' WHERE ID=30;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Thalanaar, Feralas' WHERE ID=31;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Theramore, Dustwallow Marsh' WHERE ID=32;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Stonetalon Peak, Stonetalon Mountains' WHERE ID=33;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Booty Bay' WHERE ID=34;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Orgrimmar' WHERE ID=35;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Generic, World Target 001' WHERE ID=36;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Nijel''s Point, Desolace' WHERE ID=37;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Shadowprey Village, Desolace' WHERE ID=38;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Gadgetzan, Tanaris' WHERE ID=39;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Gadgetzan, Tanaris' WHERE ID=40;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Feathermoon, Feralas' WHERE ID=41;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Camp Mojache, Feralas' WHERE ID=42;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Aerie Peak, The Hinterlands' WHERE ID=43;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Valormok, Azshara' WHERE ID=44;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Nethergarde Keep, Blasted Lands' WHERE ID=45;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Southshore' WHERE ID=46;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Grom''gol' WHERE ID=47;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Bloodvenom Post, Felwood' WHERE ID=48;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Moonglade' WHERE ID=49;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Menethil Harbor' WHERE ID=50;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Auberdine' WHERE ID=51;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Everlook, Winterspring' WHERE ID=52;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Everlook, Winterspring' WHERE ID=53;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Feathermoon' WHERE ID=54;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Brackenwall Village, Dustwallow Marsh' WHERE ID=55;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Stonard, Swamp of Sorrows' WHERE ID=56;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Fishing Village, Teldrassil' WHERE ID=57;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Zoram''gar Outpost, Ashenvale' WHERE ID=58;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Dun Baldar, Alterac Valley' WHERE ID=59;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Frostwolf Keep, Alterac Valley' WHERE ID=60;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Splintertree Post, Ashenvale' WHERE ID=61;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Nighthaven, Moonglade' WHERE ID=62;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Nighthaven, Moonglade' WHERE ID=63;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Talrendis Point, Azshara' WHERE ID=64;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Talonbranch Glade, Felwood' WHERE ID=65;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Chillwind Camp, Western Plaguelands' WHERE ID=66;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Light''s Hope Chapel, Eastern Plaguelands' WHERE ID=67;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Light''s Hope Chapel, Eastern Plaguelands' WHERE ID=68;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Moonglade' WHERE ID=69;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Flame Crest, Burning Steppes' WHERE ID=70;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Morgan''s Vigil, Burning Steppes' WHERE ID=71;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Cenarion Hold, Silithus' WHERE ID=72;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Cenarion Hold, Silithus' WHERE ID=73;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Thorium Point, Searing Gorge' WHERE ID=74;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Thorium Point, Searing Gorge' WHERE ID=75;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Revantusk Village, The Hinterlands' WHERE ID=76;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Camp Taurajo, The Barrens' WHERE ID=77;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Naxxramas' WHERE ID=78;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Marshal''s Refuge, Un''Goro Crater' WHERE ID=79;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Ratchet, The Barrens' WHERE ID=80;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Filming' WHERE ID=81;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Silvermoon City' WHERE ID=82;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Tranquillien, Ghostlands' WHERE ID=83;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Plaguewood Tower, Eastern Plaguelands' WHERE ID=84;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Northpass Tower, Eastern Plaguelands' WHERE ID=85;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Eastwall Tower, Eastern Plaguelands' WHERE ID=86;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Crown Guard Tower, Eastern Plaguelands' WHERE ID=87;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Exodar' WHERE ID=88;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Theramore' WHERE ID=89;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Undercity' WHERE ID=90;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Azuremyst Shaman Target' WHERE ID=91;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Azuremyst Shaman Start' WHERE ID=92;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Blood Watch, Bloodmyst Isle' WHERE ID=93;
UPDATE dbc_taxinodes SET Name_Lang_enGB='The Exodar' WHERE ID=94;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Zangarmarsh - Quest - As the Crow Flies' WHERE ID=95;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Zangarmarsh - Quest - As the Crow Flies - End' WHERE ID=96;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Elekk Path to Kessel' WHERE ID=97;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Elekk to Kessel Target' WHERE ID=98;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Thrallmar, Hellfire Peninsula' WHERE ID=99;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Honor Hold, Hellfire Peninsula' WHERE ID=100;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Temple of Telhamat, Hellfire Peninsula' WHERE ID=101;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Falcon Watch, Hellfire Peninsula' WHERE ID=102;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Nagrand - PvP - Attack Run Start 1 ' WHERE ID=103;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Nagrand - PvP - Attack Run End 1' WHERE ID=104;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Nagrand - PvP - Attack Run Start 2' WHERE ID=105;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Nagrand - PvP - Attack Run End 2' WHERE ID=106;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Nagrand - PvP - Attack Run Start 3' WHERE ID=107;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Nagrand - PvP - Attack Run End 3' WHERE ID=108;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Nagrand - PvP - Attack Run Start 4' WHERE ID=109;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Nagrand - PvP - Attack Run End 4' WHERE ID=110;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Eversong - Duskwither Teleport' WHERE ID=111;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Eversong - Duskwither Teleport End' WHERE ID=112;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Nethrandamus Start' WHERE ID=113;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Nethrandamus End Target' WHERE ID=114;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Caverns of Time OH - Begin' WHERE ID=115;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Caverns of Time OH - End' WHERE ID=116;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Telredor, Zangarmarsh' WHERE ID=117;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Zabra''jin, Zangarmarsh' WHERE ID=118;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Telaar, Nagrand' WHERE ID=119;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Garadar, Nagrand' WHERE ID=120;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Allerian Stronghold, Terokkar Forest' WHERE ID=121;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Area 52, Netherstorm' WHERE ID=122;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Shadowmoon Village, Shadowmoon Valley' WHERE ID=123;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Wildhammer Stronghold, Shadowmoon Valley' WHERE ID=124;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Sylvanaar, Blade''s Edge Mountains' WHERE ID=125;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Thunderlord Stronghold, Blade''s Edge Mountains' WHERE ID=126;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Stonebreaker Hold, Terokkar Forest' WHERE ID=127;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Shattrath, Terokkar Forest' WHERE ID=128;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Hellfire Peninsula, The Dark Portal, Alliance' WHERE ID=129;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Hellfire Peninsula, The Dark Portal, Horde' WHERE ID=130;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Horde Hellfire Start' WHERE ID=131;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Horde Hellfire End' WHERE ID=132;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Hellfire Peninsula (Alliance Path) Start' WHERE ID=133;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Hellfire Peninsula (Alliance) End' WHERE ID=134;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Hellfire, Aerial Mission (Horde) Start' WHERE ID=135;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Hellfire, Aerial Mission (Horde) End' WHERE ID=136;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Hellfire, Aerial Mission (Alliance) Start' WHERE ID=137;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Hellfire, Aerial Mission (Alliance) End' WHERE ID=138;
UPDATE dbc_taxinodes SET Name_Lang_enGB='The Stormspire, Netherstorm' WHERE ID=139;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Altar of Sha''tar, Shadowmoon Valley' WHERE ID=140;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Spinebreaker Ridge, Hellfire Peninsula' WHERE ID=141;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Hellfire Peninsula - Reaver''s Fall' WHERE ID=142;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Caverns of Time (Intro Flight Path) (End)' WHERE ID=143;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Caverns of Time (Intro Flight Path) (Start)' WHERE ID=144;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Netherstorm - Stealth Flight - Begin' WHERE ID=145;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Netherstorm - Stealth Flight - End' WHERE ID=146;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Hellfire Peninsula - Force Camp Beach Head' WHERE ID=147;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Shatter Point, Hellfire Peninsula (Beach Assault)' WHERE ID=148;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Shatter Point, Hellfire Peninsula' WHERE ID=149;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Cosmowrench, Netherstorm' WHERE ID=150;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Swamprat Post, Zangarmarsh' WHERE ID=151;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Netherstorm - Manaforge Ultris (Start)' WHERE ID=152;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Netherstorm - Manaforge Ultris (End)' WHERE ID=153;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Netherstorm - Manaforge Ultris (Second Pass) Start' WHERE ID=154;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Netherstorm - Manaforge Ultris (Second Pass) End' WHERE ID=155;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Toshley''s Station, Blade''s Edge Mountains' WHERE ID=156;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Blade''s Edge - Vision Guide - Start' WHERE ID=157;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Blade''s Edge - Vision Guide - End' WHERE ID=158;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Sanctum of the Stars, Shadowmoon Valley' WHERE ID=159;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Evergrove, Blade''s Edge Mountains' WHERE ID=160;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Nether Dragon Ally - Start' WHERE ID=161;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Nether Dragon Ally - End' WHERE ID=162;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Mok''Nathal Village, Blade''s Edge Mountains' WHERE ID=163;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Orebor Harborage, Zangarmarsh' WHERE ID=164;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Northrend 2' WHERE ID=165;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Emerald Sanctuary, Felwood' WHERE ID=166;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Forest Song, Ashenvale' WHERE ID=167;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Filming' WHERE ID=168;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Netherwing Ledge - Mine Cart Ride - South - Start' WHERE ID=169;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Netherwing Ledge - Mine Cart Ride - South - End' WHERE ID=170;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Skettis' WHERE ID=171;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Ogri''La' WHERE ID=172;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Yarzill Flight Start' WHERE ID=173;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Yarzill Flight Start End' WHERE ID=174;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Howling Fjord' WHERE ID=175;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Howling Fjord Tauren Canoe (Start)' WHERE ID=176;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Howling Fjord Tauren Canoe (End)' WHERE ID=177;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Borean Tundra' WHERE ID=178;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Mudsprocket, Dustwallow Marsh' WHERE ID=179;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Dustwallow - Alcaz Survey Start' WHERE ID=180;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Dustwallow - Alcaz Survey End' WHERE ID=181;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Howling Fjord - Break the Blockade Zeppelin' WHERE ID=182;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Valgarde Port, Howling Fjord' WHERE ID=183;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Fort Wildervar, Howling Fjord' WHERE ID=184;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Westguard Keep, Howling Fjord' WHERE ID=185;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Howling Fjord - Flight to the Windrunner - Start' WHERE ID=186;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Howling Fjord - Flight to the Windrunner - End' WHERE ID=187;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Howling Fjord - Test at Sea - Start' WHERE ID=188;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Howling Fjord - Test at Sea - End' WHERE ID=189;
UPDATE dbc_taxinodes SET Name_Lang_enGB='New Agamand, Howling Fjord' WHERE ID=190;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Vengeance Landing, Howling Fjord' WHERE ID=191;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Camp Winterhoof, Howling Fjord' WHERE ID=192;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Howling Fjord - Mission: Plague This! - End' WHERE ID=193;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Howling Fjord - Mission: Plague This! - Start' WHERE ID=194;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Rebel Camp, Stranglethorn Vale' WHERE ID=195;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Test - SP' WHERE ID=196;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Test SP2' WHERE ID=197;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Test SP1' WHERE ID=198;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Howling Fjord - McGoyver Start' WHERE ID=199;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Howling Fjord - McGoyver End' WHERE ID=200;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Development Land - Kyle Radue Start' WHERE ID=201;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Development Land - Kyle Radue End' WHERE ID=202;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Stars'' Rest -> Wintergarde' WHERE ID=203;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - New Agamand -> Venomspite' WHERE ID=204;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Zul''Aman, Ghostlands' WHERE ID=205;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Feathermoon (NE Ship)' WHERE ID=206;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Howling Fjord - Sister Mercy (Start)' WHERE ID=207;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Howling Fjord - Sister Mercy (End)' WHERE ID=208;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Sunwell Daily - Dead Scar Bombing - Start' WHERE ID=209;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Sunwell Daily - Dead Scar Bombing - End' WHERE ID=210;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Sunwell Daily - Ship Bombing - Start' WHERE ID=211;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Sunwell Daily - Ship Bombing - End' WHERE ID=212;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Shattered Sun Staging Area' WHERE ID=213;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Howling Fjord - Naglfar (Start)' WHERE ID=214;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Howling Fjord - Naglfar (Nodes)' WHERE ID=215;
UPDATE dbc_taxinodes SET Name_Lang_enGB='' WHERE ID=216;
UPDATE dbc_taxinodes SET Name_Lang_enGB='' WHERE ID=217;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Howling Fjord (Gondola, Top)' WHERE ID=218;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Howling Fjord (Gondola, Bottom)' WHERE ID=219;
UPDATE dbc_taxinodes SET Name_Lang_enGB='' WHERE ID=220;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Amber Ledge, Borean (To Beryl)' WHERE ID=221;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Beryl Point, Borean' WHERE ID=222;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Naglevar' WHERE ID=223;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Borean Tundra, Naglevar' WHERE ID=224;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Amber Ledge, Borean (to Coldarra)' WHERE ID=225;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transitus Shield, Coldarra' WHERE ID=226;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, PattyMacDevTest' WHERE ID=227;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Development Land - Pat Test Start' WHERE ID=228;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Development Land - Pat Test End' WHERE ID=229;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Tuskarr 01' WHERE ID=230;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Tuskarr 02' WHERE ID=231;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Borean Tundra - Warsong Hold Wolf Start' WHERE ID=232;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Borean Tundra - Warsong Hold Wolf End' WHERE ID=233;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Coldarra Ledge, Coldarra' WHERE ID=234;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transitus Shield, Coldarra (NOT USED)' WHERE ID=235;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Coldarra, Keristrasza to Malygos' WHERE ID=236;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Coldarra, Keristrasza Landing' WHERE ID=237;
UPDATE dbc_taxinodes SET Name_Lang_enGB='' WHERE ID=238;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Borean Tundra - Quest - Dusk Start' WHERE ID=239;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Borean Tundra - Quest - Dusk - End' WHERE ID=240;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Valiance Keep' WHERE ID=241;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Dragonblight - Spiritual Vision - Begin' WHERE ID=242;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Dragonblight - Spiritual Vision - End' WHERE ID=243;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Wintergarde Keep, Dragonblight' WHERE ID=244;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Valiance Keep, Borean Tundra' WHERE ID=245;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Fizzcrank Airstrip, Borean Tundra' WHERE ID=246;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Stars'' Rest, Dragonblight' WHERE ID=247;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Apothecary Camp, Howling Fjord' WHERE ID=248;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Camp Oneqwah, Grizzly Hills' WHERE ID=249;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Conquest Hold, Grizzly Hills' WHERE ID=250;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Fordragon Hold, Dragonblight' WHERE ID=251;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Wyrmrest Temple, Dragonblight' WHERE ID=252;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Amberpine Lodge, Grizzly Hills' WHERE ID=253;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Venomspite, Dragonblight' WHERE ID=254;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Westfall Brigade, Grizzly Hills' WHERE ID=255;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Agmar''s Hammer, Dragonblight' WHERE ID=256;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Warsong Hold, Borean Tundra' WHERE ID=257;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Taunka''le Village, Borean Tundra' WHERE ID=258;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Bor''gorok Outpost, Borean Tundra' WHERE ID=259;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Kor''koron Vanguard, Dragonblight' WHERE ID=260;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Stars'' Rest to Wintergarde End' WHERE ID=261;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Grizzly Hills, Alliance Log Ride Start 01' WHERE ID=262;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Grizzly Hills, Alliance Log Ride End 01' WHERE ID=263;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Auberdine (NEW)' WHERE ID=264;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Theramore (NEW)' WHERE ID=265;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Menethil (NEW)' WHERE ID=266;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Grizzly Hills, Alliance Log Ride Start' WHERE ID=267;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Grizzly Hills, Alliance Log Ride End' WHERE ID=268;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Westguard Keep to Wintergarde Keep Begin' WHERE ID=269;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Westguard Keep to Wintergarde Keep End' WHERE ID=270;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Grizzly Hills, Horde Log Ride Start' WHERE ID=271;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Grizzly Hills, Horde Log Ride End' WHERE ID=272;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Wyrmrest Temple - bottom to top, Dragonblight - Begin' WHERE ID=273;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Wyrmrest Temple - bottom to top, Dragonblight - End' WHERE ID=274;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Wyrmrest Temple - top to bottom, Dragonblight - Begin' WHERE ID=275;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Wyrmrest Temple - top to bottom, Dragonblight - End' WHERE ID=276;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Wyrmrest Temple - top to middle, Dragonblight - Begin' WHERE ID=277;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Wyrmrest Temple - top to middle, Dragonblight - End' WHERE ID=278;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Wyrmrest Temple - middle to top, Dragonblight - End' WHERE ID=279;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Wyrmrest Temple - middle to top, Dragonblight - Begin' WHERE ID=280;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Wyrmrest Temple - middle to bottom, Dragonblight - End' WHERE ID=281;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Wyrmrest Temple - middle to bottom, Dragonblight - Begin' WHERE ID=282;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Wyrmrest Temple - bottom to middle, Dragonblight - End' WHERE ID=283;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Wyrmrest Temple - bottom to middle, Dragonblight - Begin' WHERE ID=284;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Wintergarde -> Stars'' Rest (Start)' WHERE ID=285;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Wintergarde -> Stars'' Rest (End)' WHERE ID=286;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Valgarde -> Westguard Keep Start' WHERE ID=287;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Valgarde -> Westguard Keep End' WHERE ID=288;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Amber Ledge, Borean Tundra' WHERE ID=289;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Argent Stand, Zul''Drak' WHERE ID=290;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Ruined City Post 01, Zul''Drak' WHERE ID=291;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Flavor - Stormwind Harbor  - Start' WHERE ID=292;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Flavor - Stormwind Harbor - Stop' WHERE ID=293;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Moa''ki, Dragonblight' WHERE ID=294;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Kamagua, Howling Fjord' WHERE ID=295;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Unu''pe, Borean Tundra' WHERE ID=296;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Sholazar Basin - Quest - Reconnaisance - Start' WHERE ID=297;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Sholazar Basin - Quest - Reconnaisance - End' WHERE ID=298;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport: Menethil <-> Valgarde' WHERE ID=299;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Stormwind' WHERE ID=300;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Borean Tundra - Check In With Bixie - Begin' WHERE ID=301;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Borean Tundra - Check In With Bixie - End' WHERE ID=302;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Valiance Landing Camp, Wintergrasp' WHERE ID=303;
UPDATE dbc_taxinodes SET Name_Lang_enGB='The Argent Stand, Zul''Drak' WHERE ID=304;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Ebon Watch, Zul''Drak' WHERE ID=305;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Light''s Breach, Zul''Drak' WHERE ID=306;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Zim''Torga, Zul''Drak' WHERE ID=307;
UPDATE dbc_taxinodes SET Name_Lang_enGB='River''s Heart, Sholazar Basin' WHERE ID=308;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Nesingwary Base Camp, Sholazar Basin' WHERE ID=309;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Dalaran' WHERE ID=310;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Camp Onequah, Grizzly Hills (Quest)' WHERE ID=311;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Light''s Breach, Zul''Drak (Quest)' WHERE ID=312;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Westfall Brigade, Grizzly Hills (Quest)' WHERE ID=313;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Zim''Torga, Zul''Drak (Quest)' WHERE ID=314;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Acherus: The Ebon Hold' WHERE ID=315;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Ebon Hold - Acherus -> Death''s Breach Start' WHERE ID=316;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Ebon Hold - Acherus -> Death''s Breach End' WHERE ID=317;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Ebon Hold - Death''s Breach -> Acherus Start' WHERE ID=318;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Ebon Hold - Death''s Breach -> Acherus End' WHERE ID=319;
UPDATE dbc_taxinodes SET Name_Lang_enGB='K3, The Storm Peaks' WHERE ID=320;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Frosthold, The Storm Peaks' WHERE ID=321;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Dun Nifflelem, The Storm Peaks' WHERE ID=322;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Grom''arsh Crash-Site, The Storm Peaks' WHERE ID=323;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Camp Tunka''lo, The Storm Peaks' WHERE ID=324;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Death''s Rise, Icecrown' WHERE ID=325;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Ulduar, The Storm Peaks' WHERE ID=326;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Bouldercrag''s Refuge, The Storm Peaks' WHERE ID=327;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Icecrown Airship (A)' WHERE ID=328;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Icecrown Airship (H)' WHERE ID=329;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport, Icecrown (Target)' WHERE ID=330;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Gundrak, Zul''Drak' WHERE ID=331;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Warsong Camp, Wintergrasp' WHERE ID=332;
UPDATE dbc_taxinodes SET Name_Lang_enGB='The Shadow Vault, Icecrown' WHERE ID=333;
UPDATE dbc_taxinodes SET Name_Lang_enGB='The Argent Vanguard, Icecrown' WHERE ID=334;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Crusaders'' Pinnacle, Icecrown' WHERE ID=335;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Windrunner''s Overlook, Crystalsong Forest' WHERE ID=336;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Sunreaver''s Command, Crystalsong Forest' WHERE ID=337;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Argent Tournament Grounds, Icecrown' WHERE ID=340;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Ulduar Raid - Interior - Insertion Point' WHERE ID=341;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Ulduar Raid - Iron Concourse' WHERE ID=342;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Transport: Thunder Bluff <-> Org (Zep)' WHERE ID=348;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Isle of Conquest - Gunships' WHERE ID=352;
UPDATE dbc_taxinodes SET Name_Lang_enGB='' WHERE ID=353;
UPDATE dbc_taxinodes SET Name_Lang_enGB='' WHERE ID=357;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Icecrown - North Sea Kraken Bombing - Start' WHERE ID=358;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest - Icecrown - North Sea Kraken Bombing - End' WHERE ID=359;
UPDATE dbc_taxinodes SET Name_Lang_enGB='REUSEME' WHERE ID=375;
UPDATE dbc_taxinodes SET Name_Lang_enGB='AAAIcecrown Raid - Airship Battle Taxi Paths' WHERE ID=376;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Icecrown Dungeon - Gunships' WHERE ID=377;
UPDATE dbc_taxinodes SET Name_Lang_enGB='AAAAIcecrown Raid - Saurfang''s Ship (End)' WHERE ID=379;
UPDATE dbc_taxinodes SET Name_Lang_enGB='AAAAIcecrown Raid - Saurfang''s Ship (Start)' WHERE ID=380;
UPDATE dbc_taxinodes SET Name_Lang_enGB='AAAAQuest [Transport] Icecrown Raid - Saurfang Ship (START)' WHERE ID=381;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Quest [Transport] Icecrown Raid - Saurfang Ship (END)' WHERE ID=382;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Thondoril River, Western Plaguelands' WHERE ID=383;
UPDATE dbc_taxinodes SET Name_Lang_enGB='The Bulwark, Tirisfal' WHERE ID=384;
UPDATE dbc_taxinodes SET Name_Lang_enGB='CC Prologue - GT - Quest - Vent Horizon - Start' WHERE ID=392;
UPDATE dbc_taxinodes SET Name_Lang_enGB='CC Prologue - GT - Quest - Vent Horizon - End' WHERE ID=393;
UPDATE dbc_taxinodes SET Name_Lang_enGB='CC Prologue - GT - Battle Flight - Start' WHERE ID=394;
UPDATE dbc_taxinodes SET Name_Lang_enGB='CC Prologue - GT - Battle Flight - End' WHERE ID=395;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Durotar - ET - CC Prologue Spy Frog Start' WHERE ID=404;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Durotar - ET - CC Prologue Spy Frog End' WHERE ID=405;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Durotar - ET - CC Prologue Troll Taxi Bat Start' WHERE ID=438;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Durotar - ET - CC Prologue Troll Recruit End' WHERE ID=439;
UPDATE dbc_taxinodes SET Name_Lang_enGB='Durotar - ET - CC Prologue - Troll Battle End' WHERE ID=440;
