UPDATE dbc_totemcategory SET Name_Lang_enGB='Skinning Knife (OLD)' WHERE ID=1;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Earth Totem' WHERE ID=2;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Air Totem' WHERE ID=3;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Fire Totem' WHERE ID=4;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Water Totem' WHERE ID=5;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Runed Copper Rod' WHERE ID=6;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Runed Silver Rod' WHERE ID=7;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Runed Golden Rod' WHERE ID=8;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Runed Truesilver Rod' WHERE ID=9;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Runed Arcanite Rod' WHERE ID=10;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Mining Pick (OLD)' WHERE ID=11;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Philosopher''s Stone' WHERE ID=12;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Blacksmith Hammer (OLD)' WHERE ID=13;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Arclight Spanner' WHERE ID=14;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Gyromatic Micro-Adjustor' WHERE ID=15;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Master Totem' WHERE ID=21;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Runed Fel Iron Rod' WHERE ID=41;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Runed Adamantite Rod' WHERE ID=62;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Runed Eternium Rod' WHERE ID=63;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Hollow Quill' WHERE ID=81;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Runed Azurite Rod' WHERE ID=101;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Virtuoso Inking Set' WHERE ID=121;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Drums' WHERE ID=141;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Gnomish Army Knife' WHERE ID=161;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Blacksmith Hammer' WHERE ID=162;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Mining Pick' WHERE ID=165;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Skinning Knife' WHERE ID=166;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Hammer Pick' WHERE ID=167;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Bladed Pickaxe' WHERE ID=168;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Flint and Tinder' WHERE ID=169;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Runed Cobalt Rod (DO NOT USE)' WHERE ID=189;
UPDATE dbc_totemcategory SET Name_Lang_enGB='Runed Titanium Rod' WHERE ID=190;
