UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Stormwind' WHERE ID=1;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Redridge Mountains' WHERE ID=2;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Duskwood, Darkshire' WHERE ID=3;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Westfall, Sentinel Hill' WHERE ID=4;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dun Morogh' WHERE ID=5;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Loch Modan, Thelsamar' WHERE ID=6;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Wetlands, Crossroads' WHERE ID=7;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Badlands, Graveyard NE ' WHERE ID=8;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='The Barrens, The Crossroads' WHERE ID=10;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Desolace, Ethel Rethor' WHERE ID=31;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Durotar, Razor Hill' WHERE ID=32;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Durotar, Orgrimmar' WHERE ID=33;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Mulgore, Red Cloud Mesa' WHERE ID=34;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Darkshore, Auberdine' WHERE ID=35;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Deadwind Pass, Morgan''s Plot' WHERE ID=36;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Thousand Needles, The Great Lift' WHERE ID=39;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Plains of Snow - Horde Start' WHERE ID=49;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Silithus, Valor''s Rest' WHERE ID=70;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Mulgore, Bloodhoof Village' WHERE ID=89;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Teldrassil, Darnassus' WHERE ID=90;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Teldrassil, Dolanaar' WHERE ID=91;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Ashenvale, Astranaar' WHERE ID=92;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Teldrassil, Aldrassil' WHERE ID=93;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Tirisfal Glades, Deathknell' WHERE ID=94;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Tirisfal Glades, Undercity' WHERE ID=96;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Silverpine Forest, The Sepulcher' WHERE ID=97;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hillsbrad Foothills, Tarren Mill' WHERE ID=98;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Arathi Highlands, Eastern Road' WHERE ID=99;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dun Morogh, Anvilmar' WHERE ID=100;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dun Morogh, Kharanos' WHERE ID=101;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dun Morogh, Ironforge' WHERE ID=102;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Badlands, Kargath' WHERE ID=103;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Redridge Mountains, Lakeshire' WHERE ID=104;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Elwynn Forest, Northshire' WHERE ID=105;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Elwynn Forest, Goldshire' WHERE ID=106;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Elwynn Forest, Stormwind' WHERE ID=107;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Swamp of Sorrows, Stonard' WHERE ID=108;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Stranglethorn Vale, Booty Bay' WHERE ID=109;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Teldrassil, Rut''theran Village' WHERE ID=129;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hillsbrad Foothills, Southshore' WHERE ID=149;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Alterac Valley, Snowfall Graveyard (Mid)' WHERE ID=169;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dustwallow Marsh, Theramore Isle' WHERE ID=189;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Tanaris, Gadgetzan' WHERE ID=209;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='The Barrens, Camp Taurajo' WHERE ID=229;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='The Barrens, Ratchet' WHERE ID=249;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Plains of Snow - Alliance Start' WHERE ID=269;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Tirisfal Glades, Brill' WHERE ID=289;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Feralas, Feathermoon Stronghold' WHERE ID=309;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Feralas, Camp Mojache' WHERE ID=310;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Thousand Needles, Shimmering Flats' WHERE ID=329;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='The Hinterlands, Aerie Peak' WHERE ID=349;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Azshara, Talrendis Point' WHERE ID=369;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blasted Lands, Dreadmaul Hold' WHERE ID=370;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Stranglethorn Vale, Northern Stranglethorn' WHERE ID=389;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Stonetalon Mountains, Webwinder Path' WHERE ID=409;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Tirisfal Glades, Faol''s Rest' WHERE ID=429;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Felwood, Morlos''Aran' WHERE ID=449;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Un''Goro Crater, The Marshlands' WHERE ID=450;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Darkshore, Twilight Vale' WHERE ID=469;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Wetlands, Baradin Bay' WHERE ID=489;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Western Plaguelands, Chillwind Camp' WHERE ID=509;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Eastern Plaguelands, Pestilent Scar' WHERE ID=510;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Winterspring, Everlook' WHERE ID=511;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Ashenvale, Kargathia' WHERE ID=512;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Programmer Isle' WHERE ID=529;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Programmer Isle' WHERE ID=549;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Western Plaguelands, Bulwark' WHERE ID=569;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='GM Island' WHERE ID=589;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Azshara, Southridge Beach' WHERE ID=609;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Alterac Valley, Horde Safe' WHERE ID=610;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Alterac Valley, Alliance Safe' WHERE ID=611;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='TEST for GM Client Only - Do Not Bug' WHERE ID=629;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Azshara, Legash Encampment' WHERE ID=630;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dustwallow Marsh, Brackenwall Village' WHERE ID=631;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Moonglade' WHERE ID=633;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Eastern Plaguelands, Darrowshire' WHERE ID=634;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Felwood, Irontree Woods' WHERE ID=635;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Searing Gorge, Thorium Point' WHERE ID=636;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Durotar, Sen''jin Village' WHERE ID=649;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Programmer Isle, Bucklers Cemetery 2' WHERE ID=669;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Programmer Isle, Bucklers Cemetery 1' WHERE ID=670;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Programmer Isle, Bucklers Cemetery 3' WHERE ID=671;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Alterac Valley, Stormpike Graveyard (Hi)' WHERE ID=689;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Alterac Valley, Frostwolf Graveyard (Lo)' WHERE ID=690;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Durotar, Valley of Trials' WHERE ID=709;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Alterac Valley, PvP Alliance Choke Graveyard (A-choke)' WHERE ID=729;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Alterac Valley, PvP Horde Choke Graveyard (H-choke)' WHERE ID=749;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Alterac Valley, Frostwolf Relief Hut (H-base)' WHERE ID=750;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Alterac Valley, Stormpike Aid Station (A-base)' WHERE ID=751;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Warsong Gulch - Alliance Enter Loc' WHERE ID=769;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Warsong Gulch - Horde Enter Loc' WHERE ID=770;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Warsong Gulch - Alliance Rez Loc' WHERE ID=771;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Warsong Gulch - Horde Rez Loc' WHERE ID=772;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='The Hinterlands, The Overlook Cliffs' WHERE ID=789;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Warsong Gulch - Horde Exit Loc' WHERE ID=809;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Warsong Gulch - Alliance Exit Loc' WHERE ID=810;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Alterac Valley, Alliance Exit' WHERE ID=829;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Alterac Valley, Horde Exit' WHERE ID=830;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Feralas, Dire Maul' WHERE ID=849;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Durotar, Northern Durotar' WHERE ID=850;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Mulgore, Thunder Bluff' WHERE ID=851;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dun Morogh, Gates of Ironforge' WHERE ID=852;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Tirisfal Glades, Ruins of Lordaeron' WHERE ID=853;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Elwynn Forest, Eastvale Logging Camp' WHERE ID=854;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Western Plaguelands, Caer Darrow' WHERE ID=869;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Arathi Basin - Horde Entrance' WHERE ID=889;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Arathi Basin - Alliance Entrance' WHERE ID=890;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Arathi Basin - Horde Exit' WHERE ID=891;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Arathi Basin - Alliance Exit' WHERE ID=892;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Arathi Basin - Graveyard, H-Mid (Farm)' WHERE ID=893;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Arathi Basin - Graveyard, Mid (Blacksmith)' WHERE ID=894;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Arathi Basin - Graveyard, A-Mid (Stables)' WHERE ID=895;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Arathi Basin - Graveyard, ALT-N (Gold Mine)' WHERE ID=896;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Arathi Basin - Graveyard, ALT-S (Lumber Mill)' WHERE ID=897;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Arathi Basin - Graveyard, A-Base (Trollbane Hall)' WHERE ID=898;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Arathi Basin - Graveyard, H-Base (Defiler''s Den)' WHERE ID=899;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Eastern Plaguelands, Blackwood Lake' WHERE ID=909;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Silithus, Cenarion Hold' WHERE ID=910;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Duskwood, Ravenhill' WHERE ID=911;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Eversong Woods, Sunstrider Isle' WHERE ID=912;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Silithus, Scarab Wall (AQ Only)' WHERE ID=913;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Eversong Woods, Farstrider Lodge GY' WHERE ID=914;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Ghostlands, Tranquillien' WHERE ID=915;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Ghostlands, Sanctum' WHERE ID=916;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Ghostlands, Amani Pass' WHERE ID=917;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Azuremyst Isle, Ammen Vale' WHERE ID=918;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Thrallmar' WHERE ID=919;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Honor Hold' WHERE ID=920;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Eversong Woods, Silvermoon City' WHERE ID=921;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Eversong Woods, Fairbreeze GY' WHERE ID=922;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Azuremyst, Azure Watch GY' WHERE ID=923;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Azuremyst, Stillpine GY' WHERE ID=924;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Bloodmyst, Blood Watch GY' WHERE ID=925;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Bloodmyst, Wilderness GY' WHERE ID=926;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Eastern Plaguelands, Graveyard CG Tower' WHERE ID=927;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Zabra''jin GY' WHERE ID=928;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand Arena, Team 1 Start' WHERE ID=929;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, SE Graveyard' WHERE ID=930;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Programmer Isle' WHERE ID=931;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Programmer Isle' WHERE ID=932;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Temple' WHERE ID=933;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Falcon Watch' WHERE ID=934;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 004' WHERE ID=935;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand Arena, Team 2 Start' WHERE ID=936;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Reuse' WHERE ID=937;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Alterac Valley, Alliance Exit' WHERE ID=938;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge Arena, Team 1' WHERE ID=939;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge Arena, Team 2' WHERE ID=940;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Test Corpse Location' WHERE ID=941;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 001' WHERE ID=942;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 002' WHERE ID=943;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 003' WHERE ID=944;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 005' WHERE ID=945;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 006' WHERE ID=946;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 007' WHERE ID=947;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 008' WHERE ID=948;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 009' WHERE ID=949;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 010' WHERE ID=950;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 011' WHERE ID=951;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 012' WHERE ID=952;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 013' WHERE ID=953;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 014' WHERE ID=954;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 015' WHERE ID=955;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 016' WHERE ID=956;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 017' WHERE ID=957;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 018' WHERE ID=958;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 019' WHERE ID=959;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 020' WHERE ID=960;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 021' WHERE ID=961;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 022' WHERE ID=962;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 023' WHERE ID=963;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 024' WHERE ID=964;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 025' WHERE ID=965;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 026' WHERE ID=966;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 027' WHERE ID=967;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Corpse Location 028' WHERE ID=968;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, PvP GY' WHERE ID=969;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Telredor GY' WHERE ID=970;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blades Edge - PvP - Arena Graveyard' WHERE ID=971;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 006' WHERE ID=972;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Cenarion GY' WHERE ID=973;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 001' WHERE ID=974;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 002' WHERE ID=975;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 003' WHERE ID=976;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 004' WHERE ID=977;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 008' WHERE ID=978;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 005' WHERE ID=979;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 007' WHERE ID=980;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 009' WHERE ID=981;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 011' WHERE ID=982;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 010' WHERE ID=983;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 012' WHERE ID=984;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 013' WHERE ID=985;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 014' WHERE ID=986;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 016' WHERE ID=987;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 015' WHERE ID=988;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 017' WHERE ID=989;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 018' WHERE ID=990;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Corpse Location 019' WHERE ID=991;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Northwind Cleft' WHERE ID=992;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Halaa GY' WHERE ID=993;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Shattrath GY' WHERE ID=994;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Wilderness GY' WHERE ID=995;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Test - Programmer' WHERE ID=996;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Test - Programmer 001' WHERE ID=997;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand - PvP - Arena Graveyard' WHERE ID=998;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Corpse Location 001' WHERE ID=999;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Corpse Location 002' WHERE ID=1000;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Corpse Location 003' WHERE ID=1001;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Corpse Location 004' WHERE ID=1002;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Corpse Location 005' WHERE ID=1003;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Corpse Location 006' WHERE ID=1004;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Corpse Location 007' WHERE ID=1005;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Corpse Location 008' WHERE ID=1006;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Corpse Location 009' WHERE ID=1007;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Corpse Location 010' WHERE ID=1008;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Corpse Location 011' WHERE ID=1009;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Corpse Location 012' WHERE ID=1010;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Corpse Location 013' WHERE ID=1011;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Corpse Location 014' WHERE ID=1012;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 001' WHERE ID=1013;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 002' WHERE ID=1014;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 003' WHERE ID=1015;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 004' WHERE ID=1016;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 005' WHERE ID=1017;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 006' WHERE ID=1018;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 007' WHERE ID=1019;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 008' WHERE ID=1020;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 009' WHERE ID=1021;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 010' WHERE ID=1022;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 011' WHERE ID=1023;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 001' WHERE ID=1024;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 002' WHERE ID=1025;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 003' WHERE ID=1026;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 004' WHERE ID=1027;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 016' WHERE ID=1028;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 017' WHERE ID=1029;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 018' WHERE ID=1030;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 019' WHERE ID=1031;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 020' WHERE ID=1032;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 021' WHERE ID=1033;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 022' WHERE ID=1034;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Corpse Location 023' WHERE ID=1035;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Reuse' WHERE ID=1036;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Portal Plateau' WHERE ID=1037;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, Elemental Plateau' WHERE ID=1038;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Nagrand, SW Graveyard' WHERE ID=1039;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Throne of Kil''Jaedan' WHERE ID=1040;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Dark Portal' WHERE ID=1041;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Bone Wastes GY' WHERE ID=1042;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Harborage GY' WHERE ID=1043;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zangarmarsh, Sporeggar GY' WHERE ID=1044;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm, Stormspire GY' WHERE ID=1045;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm, Area 52 GY' WHERE ID=1046;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon Valley, Shadowmoon Village GY' WHERE ID=1047;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon Valley, Wildhammer GY' WHERE ID=1048;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Sylvanaar GY' WHERE ID=1049;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Thunderlord GY' WHERE ID=1050;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Skettis GY' WHERE ID=1051;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 005' WHERE ID=1052;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 006' WHERE ID=1053;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 007' WHERE ID=1054;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 008' WHERE ID=1055;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 009' WHERE ID=1056;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 010' WHERE ID=1057;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 011' WHERE ID=1058;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 012' WHERE ID=1059;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 013' WHERE ID=1060;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 014' WHERE ID=1061;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 015' WHERE ID=1062;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 016' WHERE ID=1063;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 017' WHERE ID=1064;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 018' WHERE ID=1065;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 019' WHERE ID=1066;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 020' WHERE ID=1067;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 021' WHERE ID=1068;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 022' WHERE ID=1069;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 023' WHERE ID=1070;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon, Corpse Location 024' WHERE ID=1071;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 000' WHERE ID=1072;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 001' WHERE ID=1073;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 002' WHERE ID=1074;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 003' WHERE ID=1075;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 004' WHERE ID=1076;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 005' WHERE ID=1077;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 006' WHERE ID=1078;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 007' WHERE ID=1079;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 008' WHERE ID=1080;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 009' WHERE ID=1081;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 010' WHERE ID=1082;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 011' WHERE ID=1083;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 012' WHERE ID=1084;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 013' WHERE ID=1085;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 014' WHERE ID=1086;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 015' WHERE ID=1087;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 016' WHERE ID=1088;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 017' WHERE ID=1089;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 018' WHERE ID=1090;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 019' WHERE ID=1091;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 020' WHERE ID=1092;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 021' WHERE ID=1093;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 022' WHERE ID=1094;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 023' WHERE ID=1095;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 024' WHERE ID=1096;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 025' WHERE ID=1097;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 026' WHERE ID=1098;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 027' WHERE ID=1099;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 028' WHERE ID=1100;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 029' WHERE ID=1101;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 030' WHERE ID=1102;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Graveyard (Alliance Start)' WHERE ID=1103;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Graveyard (Horde Start)' WHERE ID=1104;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Graveyard (Felreaver)' WHERE ID=1105;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Graveyard (BE Tower)' WHERE ID=1106;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Graveyard (Draenei Tower)' WHERE ID=1107;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Graveyard (Human Tower)' WHERE ID=1108;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 000' WHERE ID=1109;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 001' WHERE ID=1110;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 002' WHERE ID=1111;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 003' WHERE ID=1112;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 004' WHERE ID=1113;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 005' WHERE ID=1114;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 006' WHERE ID=1115;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 007' WHERE ID=1116;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 008' WHERE ID=1117;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 009' WHERE ID=1118;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 010' WHERE ID=1119;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 011' WHERE ID=1120;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 012' WHERE ID=1121;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 013' WHERE ID=1122;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 014' WHERE ID=1123;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 015' WHERE ID=1124;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 016' WHERE ID=1125;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 017' WHERE ID=1126;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 018' WHERE ID=1127;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 019' WHERE ID=1128;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 020' WHERE ID=1129;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 021' WHERE ID=1130;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 022' WHERE ID=1131;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 023' WHERE ID=1132;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm BG - Corpse Catcher 024' WHERE ID=1133;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 000' WHERE ID=1134;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 001' WHERE ID=1135;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 002' WHERE ID=1136;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 003' WHERE ID=1137;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 004' WHERE ID=1138;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 005' WHERE ID=1139;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 006' WHERE ID=1140;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 007' WHERE ID=1141;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 008' WHERE ID=1142;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 009' WHERE ID=1143;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 010' WHERE ID=1144;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 011' WHERE ID=1145;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 012' WHERE ID=1146;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 013' WHERE ID=1147;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 014' WHERE ID=1148;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 015' WHERE ID=1149;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 016' WHERE ID=1150;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 017' WHERE ID=1151;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 018' WHERE ID=1152;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 019' WHERE ID=1153;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 020' WHERE ID=1154;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 021' WHERE ID=1155;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 022' WHERE ID=1156;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 023' WHERE ID=1157;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 024' WHERE ID=1158;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 025' WHERE ID=1159;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 026' WHERE ID=1160;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 027' WHERE ID=1161;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 028' WHERE ID=1162;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 029' WHERE ID=1163;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 030' WHERE ID=1164;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 031' WHERE ID=1165;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 032' WHERE ID=1166;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 033' WHERE ID=1167;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 034' WHERE ID=1168;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 035' WHERE ID=1169;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 036' WHERE ID=1170;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 037' WHERE ID=1171;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 038' WHERE ID=1172;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 039' WHERE ID=1173;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 040' WHERE ID=1174;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 041' WHERE ID=1175;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 042' WHERE ID=1176;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 043' WHERE ID=1177;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 044' WHERE ID=1178;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 045' WHERE ID=1179;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 046' WHERE ID=1180;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 047' WHERE ID=1181;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 048' WHERE ID=1182;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 049' WHERE ID=1183;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 050' WHERE ID=1184;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 051' WHERE ID=1185;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 052' WHERE ID=1186;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 053' WHERE ID=1187;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 054' WHERE ID=1188;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 055' WHERE ID=1189;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 056' WHERE ID=1190;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 057' WHERE ID=1191;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 058' WHERE ID=1192;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 059' WHERE ID=1193;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 060' WHERE ID=1194;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 061' WHERE ID=1195;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 062' WHERE ID=1196;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 063' WHERE ID=1197;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 064' WHERE ID=1198;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 065' WHERE ID=1199;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 066' WHERE ID=1200;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 067' WHERE ID=1201;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 068' WHERE ID=1202;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 069' WHERE ID=1203;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 070' WHERE ID=1204;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 071' WHERE ID=1205;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 072' WHERE ID=1206;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 073' WHERE ID=1207;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 074' WHERE ID=1208;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 075' WHERE ID=1209;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 076' WHERE ID=1210;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 077' WHERE ID=1211;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 078' WHERE ID=1212;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 079' WHERE ID=1213;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 080' WHERE ID=1214;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 081' WHERE ID=1215;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 082' WHERE ID=1216;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 083' WHERE ID=1217;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 084' WHERE ID=1218;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 085' WHERE ID=1219;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 086' WHERE ID=1220;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 087' WHERE ID=1221;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 088' WHERE ID=1222;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 089' WHERE ID=1223;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 090' WHERE ID=1224;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 091' WHERE ID=1225;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 092' WHERE ID=1226;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 093' WHERE ID=1227;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 094' WHERE ID=1228;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 095' WHERE ID=1229;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 096' WHERE ID=1230;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 097' WHERE ID=1231;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 098' WHERE ID=1232;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 099' WHERE ID=1233;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 100' WHERE ID=1234;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 101' WHERE ID=1235;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 102' WHERE ID=1236;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 103' WHERE ID=1237;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 104' WHERE ID=1238;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm - Corpse Catcher 105' WHERE ID=1239;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Force Camps (Alliance)' WHERE ID=1240;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Evergrove GY' WHERE ID=1241;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, North Ridge GY' WHERE ID=1242;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, West Ridge GY' WHERE ID=1243;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, East Ridge GY' WHERE ID=1244;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Icecrown BG - Horde Zone In' WHERE ID=1245;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Alterac Valley, Alliance Exit' WHERE ID=1246;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm, Cosmowrench GY' WHERE ID=1247;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hellfire Peninsula, Spinebreaker GY' WHERE ID=1248;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Tanaris, CoT' WHERE ID=1249;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon Valley, Altar GY' WHERE ID=1250;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Shadowmoon Valley, Sanctum GY' WHERE ID=1251;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Netherstorm, Kirin''Var GY' WHERE ID=1252;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Toshley GY' WHERE ID=1253;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Raven Wood GY' WHERE ID=1254;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, NE Ridge GY' WHERE ID=1255;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Silverpine Forest, South GY' WHERE ID=1256;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Ogre GY' WHERE ID=1257;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Lordaeron, PVP - Team 1 Start' WHERE ID=1258;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Lordaeron, PVP - Team 2 Start' WHERE ID=1259;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Lordaeron, PVP - Graveyard' WHERE ID=1260;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Black Temple, Alliance GY' WHERE ID=1261;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Black Temple, Horde GY' WHERE ID=1262;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blade''s Edge, Corpse Location 031' WHERE ID=1263;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dustwallow Marsh, Tabetha''s' WHERE ID=1264;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dustwallow Marsh, Mudsprocket' WHERE ID=1265;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Howling Fjord, Northwest GY' WHERE ID=1266;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Howling Fjord, Tuskarr GY' WHERE ID=1267;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Howling Fjord, Island GY' WHERE ID=1268;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Howling Fjord, Central GY' WHERE ID=1269;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Howling Fjord, North GY' WHERE ID=1270;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Howling Fjord, Vengance GY' WHERE ID=1271;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Howling Fjord, Southeast GY' WHERE ID=1272;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Howling Fjord, South Beach GY' WHERE ID=1273;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Howling Fjord, South GY' WHERE ID=1274;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Howling Fjord, Valgarde GY' WHERE ID=1275;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Howling Fjord, Northeast GY' WHERE ID=1276;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Un''Goro Crater, Central GY' WHERE ID=1277;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Un''Goro Crater, Marshal''s GY' WHERE ID=1278;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Stonetalon Mountains, Charred Vale' WHERE ID=1279;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Stonetalon Mountains, Peak GY' WHERE ID=1280;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Tanaris, Pirate GY' WHERE ID=1281;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Tanaris, Central GY' WHERE ID=1282;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Winterspring, South GY' WHERE ID=1283;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Winterspring, West GY' WHERE ID=1284;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Wintergrasp, Fortress (East)' WHERE ID=1285;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Western Plaguelands, Central GY' WHERE ID=1286;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Searing Gorge, SE GY' WHERE ID=1287;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Badlands, South GY' WHERE ID=1288;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='The Barrens, South GY' WHERE ID=1289;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Borean Tundra, Tuskar GY' WHERE ID=1290;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Razorthorn Rise GY' WHERE ID=1291;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Isle of Quel''Danas, Staging Area GY' WHERE ID=1292;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Isle of Quel''Danas, Staging Area GY' WHERE ID=1293;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Isle of Quel''Danas, Staging Area GY' WHERE ID=1294;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Development Land, Theresa''s Test Land GY' WHERE ID=1295;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Development Land, Theresa''s Test Land 2 GY' WHERE ID=1296;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Development Land, Theresa''s Test land 3 GY' WHERE ID=1297;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Terokkar Forest, Lake Jorune GY' WHERE ID=1298;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Icecrown BG - Alliance Zone In' WHERE ID=1299;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Grizzly Hills, Vileprey GY' WHERE ID=1300;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Grizzly Hills, Amberpine GY' WHERE ID=1301;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Grizzly Hills, Westfall GY' WHERE ID=1302;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Grizzly Hills, Eastern GY' WHERE ID=1303;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Grizzly Hills, Northwestern GY' WHERE ID=1304;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Grizzly Hills, Southwestern GY' WHERE ID=1305;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Grizzly Hills, Central GY' WHERE ID=1306;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dragonblight, Northeastern GY' WHERE ID=1307;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dragonblight, Wintergarde GY' WHERE ID=1308;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dragonblight, Forsaken East GY' WHERE ID=1309;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dragonblight, Agmar''s Hammer GY' WHERE ID=1310;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dragonblight, Star''s Rest GY' WHERE ID=1311;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dragonblight, Moa''ki Harbor GY' WHERE ID=1312;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dragonblight, Borean Border GY' WHERE ID=1313;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dragonblight, Wyrmrest GY' WHERE ID=1314;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dragonblight, Wrathgate Horde GY' WHERE ID=1315;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dragonblight, Wrathgate Alliance GY' WHERE ID=1316;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Borean Tundra, Warsong Hold GY' WHERE ID=1317;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Borean Tundra, Riplash GY' WHERE ID=1318;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Borean Tundra, Coldarra GY' WHERE ID=1319;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Borean Tundra, Amber Ledge GY' WHERE ID=1320;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Borean Tundra, Fizzcrank GY' WHERE ID=1321;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Borean Tundra, Bor''Gorok GY' WHERE ID=1322;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Borean Tundra, Death''s Stand GY' WHERE ID=1323;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Borean Tundra, Taunka''le GY' WHERE ID=1324;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Borean Tundra, Coast of Echoes GY' WHERE ID=1325;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Borean Tundra, Valiance Keep GY' WHERE ID=1326;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Alterac Valley - DO NOT EDIT' WHERE ID=1327;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Wintergrasp, Fortress (West)' WHERE ID=1328;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Wintergrasp, Siege Factory (Defense NE)' WHERE ID=1329;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Wintergrasp, Siege Factory (Defense NW)' WHERE ID=1330;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Wintergrasp, Horde Starting Area' WHERE ID=1331;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Wintergrasp, Alliance Starting Area' WHERE ID=1332;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Wintergrasp, Siege Factory (SE)' WHERE ID=1333;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Wintergrasp, Siege Factory (SW)' WHERE ID=1334;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Sholazar Basin, South GY' WHERE ID=1336;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Howling Fjord, Utgarde GY' WHERE ID=1337;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Sholazar Basin, Nesingwary GY' WHERE ID=1341;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Sholazar Basin, Central GY' WHERE ID=1342;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Sholazar Basin, Northwest GY' WHERE ID=1343;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Sholazar Basin, Northeast GY' WHERE ID=1344;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Sholazar Basin, East GY' WHERE ID=1345;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Northrend BG - Controlled - South' WHERE ID=1346;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Northrend BG - Controlled - South West' WHERE ID=1347;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Northrend BG - Controlled - Central' WHERE ID=1348;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Northrend BG - Defender - Final' WHERE ID=1349;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Northrend BG - Offense - Beach' WHERE ID=1350;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Northrend BG - Offense - Boat' WHERE ID=1351;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zul''Drak, Western GY' WHERE ID=1352;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zul''Drak, Northwestern GY' WHERE ID=1353;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zul''Drak, Southwestern GY' WHERE ID=1354;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zul''Drak, Southern GY' WHERE ID=1355;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zul''Drak, Central GY' WHERE ID=1356;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zul''Drak, Southeastern GY' WHERE ID=1357;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Zul''Drak, Gun''Drak GY' WHERE ID=1358;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Crystalsong Forest, Dalaran GY' WHERE ID=1359;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Ebon Hold GY - Chapter I' WHERE ID=1360;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dalaran Arena - PvP Graveyard' WHERE ID=1361;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dalaran Arena - Team 1 Spawn' WHERE ID=1362;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dalaran Arena - Team 2 Spawn' WHERE ID=1363;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Orgrimmar Arena - Team 1 Spawn' WHERE ID=1364;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Orgrimmar Arena - Team 2 Spawn' WHERE ID=1365;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Orgrimmar Arena - Graveyard' WHERE ID=1366;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Sands of Ulduran - Alliance Spawn' WHERE ID=1367;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Sands of Ulduran - Horde Spawn' WHERE ID=1368;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Eastern Plaguelands, Ebon Hold GY' WHERE ID=1369;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Ebon Hold GY - Chapter II/III' WHERE ID=1370;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Ebon Hold GY - Chapter IV' WHERE ID=1371;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Un''Goro Crater, Shaper''s Terrace' WHERE ID=1372;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dustwallow Marsh, Theramore Safe' WHERE ID=1373;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Durotar, Orgrimmar Safe' WHERE ID=1374;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Stormwind City, Stormwind Safe' WHERE ID=1375;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Howling Fjord, Utgarde 2 GY' WHERE ID=1376;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='The Great Sea - Safe Point Tirisfal' WHERE ID=1377;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Durotar, Orgrimmar Safe 2' WHERE ID=1378;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Sholazar Basin, Stormwright GY' WHERE ID=1379;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Crystalsong Forest, Alliance GY' WHERE ID=1380;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Icecrown, Argent Vanguard' WHERE ID=1381;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Storm Peaks, Valkyrion GY' WHERE ID=1383;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Storm Peaks, Ulduar GY' WHERE ID=1384;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Storm Peaks, Temple East GY' WHERE ID=1385;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Storm Peaks, Temple West GY' WHERE ID=1387;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Storm Peaks, Frostfield GY' WHERE ID=1388;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Crystalsong Forest, West GY' WHERE ID=1391;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Crystalsong Forest, Horde GY' WHERE ID=1392;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dragonblight, Naxxramas GY' WHERE ID=1393;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dragonblight, Icemist GY' WHERE ID=1394;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Icecrown Glacier, Quarry GY' WHERE ID=1395;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Icecrown Glacier, Vrykul Central GY' WHERE ID=1396;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Icecrown Glacier, Northeast Ice GY' WHERE ID=1397;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Grizzly Hills, Drak''tharon GY' WHERE ID=1398;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Northrend BG - Defender Start' WHERE ID=1399;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Storm Peaks, Temple of the Makers GY' WHERE ID=1400;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Storm Peaks, Snowdrift GY' WHERE ID=1401;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Storm Peaks, Temple of Storms GY' WHERE ID=1402;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Storm Peaks, K3 GY' WHERE ID=1403;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Sholazar Basin, Frenzyheart GY' WHERE ID=1404;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Eastern Plaguelands: Acherus' WHERE ID=1405;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Icecrown Glacier, Jotunheim GY' WHERE ID=1407;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Storm Peaks, Foot Steppes GY' WHERE ID=1408;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Undercity - Alliance - Wrath Gate' WHERE ID=1409;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='AAAAA Test Port Loc' WHERE ID=1410;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Alterac Mountains - Central GY' WHERE ID=1411;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Winterspring, Wintersaber GY' WHERE ID=1416;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Winterspring, Crossroad GY' WHERE ID=1417;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Winterspring, Darkwhisper GY' WHERE ID=1418;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Azshara, Ursolan' WHERE ID=1419;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Azshara, Forlorn Ridge' WHERE ID=1420;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Desolace, Ghost Walker Post' WHERE ID=1421;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Desolace, Sar''theris Strand' WHERE ID=1422;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Desolace, Mannoroc Coven' WHERE ID=1423;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Desolace, Magram Village' WHERE ID=1424;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Desolace, Roadside' WHERE ID=1425;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Ashenvale, Shrine of Aessina' WHERE ID=1426;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Ashenvale, Nightsong' WHERE ID=1427;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Stonetalon Mountains, Windshear Crag' WHERE ID=1428;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Stonetalon Mountains, Mirkfallon' WHERE ID=1429;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='The Barrens, Forgotten Pools' WHERE ID=1430;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='The Barrens, North GY' WHERE ID=1431;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='The Barrens, Raptor Grounds' WHERE ID=1432;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='The Barrens, Central GY' WHERE ID=1433;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='The Barrens, East GY' WHERE ID=1434;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Mulgore, Southeast GY' WHERE ID=1435;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Mulgore, Red Rocks' WHERE ID=1436;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Thousand Needles, Freewind Post' WHERE ID=1437;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Thousand Needles, Mirage Raceway' WHERE ID=1438;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Tanaris, Southwest GY' WHERE ID=1439;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Tanaris, Abyssal Sands' WHERE ID=1440;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Feralas, Ruins of Isildien' WHERE ID=1441;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Feralas, Lower Wilds' WHERE ID=1442;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Feralas, Twin Colossals' WHERE ID=1443;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Silithus, Hive''Regal' WHERE ID=1444;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Silithus, Twilight Base Camp' WHERE ID=1445;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Arathi Highlands, Stromgarde' WHERE ID=1446;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hillsbrad Foothills, Thoradin''s Wall' WHERE ID=1447;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Eastern Plaguelands, Northdale' WHERE ID=1448;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Eastern Plaguelands, Stratholme' WHERE ID=1449;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Eastern Plaguelands, West GY' WHERE ID=1450;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Western Plaguelands, Hearthglen' WHERE ID=1451;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Hillsbrad Foothills, Hillsbrad Fields' WHERE ID=1452;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='The Hinterlands, Seradane' WHERE ID=1453;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='The Hinterlands, Shadra''Alor' WHERE ID=1454;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Wetlands, Sundown Marsh' WHERE ID=1455;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Wetlands, South Road' WHERE ID=1456;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Wetlands, Raptor Ridge' WHERE ID=1457;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Stranglethorn Vale, Gurubashi Arena' WHERE ID=1458;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Stranglethorn Vale, Central GY' WHERE ID=1459;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Stranglethorn Vale, Savage Coast' WHERE ID=1460;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Duskwood, Central GY' WHERE ID=1461;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Westfall, Dagger Hills' WHERE ID=1462;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Westfall, Longshore' WHERE ID=1463;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Blasted Lands, Dark Portal' WHERE ID=1464;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Swamp of Sorrows, Pool of Tears' WHERE ID=1465;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Swamp of Sorrows, Splinterspear' WHERE ID=1466;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Redridge Mountains, Stonewatch' WHERE ID=1467;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Elwynn Forest, Tower of Azora' WHERE ID=1468;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Burning Steppes, Blackrock Mountain' WHERE ID=1469;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Burning Steppes, East GY' WHERE ID=1470;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dun Morogh, Iceflow Lake' WHERE ID=1471;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dun Morogh, East Road' WHERE ID=1472;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Loch Modan, The Loch' WHERE ID=1473;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Wintergrasp, Fortress Graveyard (Indoors)' WHERE ID=1474;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Stonetalon Mountains, Southeast GY' WHERE ID=1476;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dragonblight, Crystal Vice GY' WHERE ID=1477;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Icecrown, Argent Tournament GY' WHERE ID=1478;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Icecrown BG - GY - Docks' WHERE ID=1480;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Icecrown BG - GY - Airport' WHERE ID=1481;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Icecrown BG - GY - Workshop' WHERE ID=1482;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Icecrown BG - GY - Alliance Default' WHERE ID=1483;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Icecrown BG - GY - Horde Default' WHERE ID=1484;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Icecrown BG - GY - Alliance Keep' WHERE ID=1485;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Icecrown BG - GY - Horde Keep' WHERE ID=1486;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='The Barrens, Honor''s Stand' WHERE ID=1493;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Dustwallow Marsh, The Wyrmbog' WHERE ID=1681;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Icecrown Glacier, Citadel GY' WHERE ID=1682;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Sunwell - Quel''Delar Entrance' WHERE ID=1683;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='AAA - Arena (Dev Test)' WHERE ID=1691;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enGB='Howling Fjord, Frostblade GY' WHERE ID=1720;
