UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='猎豹形态' WHERE ID=1;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='生命之树形态' WHERE ID=2;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='旅行形态' WHERE ID=3;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='水生形态' WHERE ID=4;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='熊形态' WHERE ID=5;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='小动物' WHERE ID=6;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='食尸鬼' WHERE ID=7;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='巨熊形态' WHERE ID=8;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='斯蒂文的食尸鬼' WHERE ID=9;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='萨隆亚的骷髅' WHERE ID=10;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='Darkmoon - Test of Strength' WHERE ID=11;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='BLB Player' WHERE ID=12;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='暗影之舞' WHERE ID=13;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='Creature - Bear' WHERE ID=14;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='Creature - Cat' WHERE ID=15;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='幽魂之狼' WHERE ID=16;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='战斗姿态' WHERE ID=17;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='防御姿态' WHERE ID=18;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='狂暴姿态' WHERE ID=19;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='测试' WHERE ID=20;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='僵尸' WHERE ID=21;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='恶魔变身' WHERE ID=22;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='' WHERE ID=23;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='' WHERE ID=24;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='亡灵' WHERE ID=25;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='狂乱' WHERE ID=26;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='史诗飞行形态' WHERE ID=27;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='暗影形态' WHERE ID=28;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='飞行形态' WHERE ID=29;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='潜行' WHERE ID=30;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='枭兽形态' WHERE ID=31;
UPDATE dbc_spellshapeshiftform SET Name_Lang_enCN='救赎之魂' WHERE ID=32;
