UPDATE dbc_faction SET Name_Lang_enCN='人类(玩家)', Description_Lang_enCN='' WHERE ID=1;
UPDATE dbc_faction SET Name_Lang_enCN='兽人(玩家)', Description_Lang_enCN='' WHERE ID=2;
UPDATE dbc_faction SET Name_Lang_enCN='矮人(玩家)', Description_Lang_enCN='' WHERE ID=3;
UPDATE dbc_faction SET Name_Lang_enCN='暗夜精灵(玩家)', Description_Lang_enCN='' WHERE ID=4;
UPDATE dbc_faction SET Name_Lang_enCN='亡灵(玩家)', Description_Lang_enCN='' WHERE ID=5;
UPDATE dbc_faction SET Name_Lang_enCN='牛头人(玩家)', Description_Lang_enCN='' WHERE ID=6;
UPDATE dbc_faction SET Name_Lang_enCN='生物', Description_Lang_enCN='' WHERE ID=7;
UPDATE dbc_faction SET Name_Lang_enCN='侏儒(玩家)', Description_Lang_enCN='' WHERE ID=8;
UPDATE dbc_faction SET Name_Lang_enCN='巨魔(玩家)', Description_Lang_enCN='' WHERE ID=9;
UPDATE dbc_faction SET Name_Lang_enCN='怪物', Description_Lang_enCN='' WHERE ID=14;
UPDATE dbc_faction SET Name_Lang_enCN='迪菲亚盗贼', Description_Lang_enCN='' WHERE ID=15;
UPDATE dbc_faction SET Name_Lang_enCN='河爪豺狼人', Description_Lang_enCN='' WHERE ID=16;
UPDATE dbc_faction SET Name_Lang_enCN='赤脊山豺狼人', Description_Lang_enCN='' WHERE ID=17;
UPDATE dbc_faction SET Name_Lang_enCN='暗皮豺狼人', Description_Lang_enCN='' WHERE ID=18;
UPDATE dbc_faction SET Name_Lang_enCN='鱼人', Description_Lang_enCN='' WHERE ID=19;
UPDATE dbc_faction SET Name_Lang_enCN='亡灵(天灾军团)', Description_Lang_enCN='' WHERE ID=20;
UPDATE dbc_faction SET Name_Lang_enCN='藏宝海湾', Description_Lang_enCN='一个由黑水海盗的头目，大财主里维加兹经营的繁荣的海港城市。它也是热砂集团的一部分，主要仇敌是血帆海盗。' WHERE ID=21;
UPDATE dbc_faction SET Name_Lang_enCN='蜘蛛', Description_Lang_enCN='' WHERE ID=22;
UPDATE dbc_faction SET Name_Lang_enCN='野猪', Description_Lang_enCN='' WHERE ID=23;
UPDATE dbc_faction SET Name_Lang_enCN='狼人', Description_Lang_enCN='' WHERE ID=24;
UPDATE dbc_faction SET Name_Lang_enCN='狗头人', Description_Lang_enCN='' WHERE ID=25;
UPDATE dbc_faction SET Name_Lang_enCN='血顶巨魔', Description_Lang_enCN='' WHERE ID=26;
UPDATE dbc_faction SET Name_Lang_enCN='劈颅巨魔', Description_Lang_enCN='' WHERE ID=27;
UPDATE dbc_faction SET Name_Lang_enCN='猎物', Description_Lang_enCN='' WHERE ID=28;
UPDATE dbc_faction SET Name_Lang_enCN='狼人', Description_Lang_enCN='' WHERE ID=29;
UPDATE dbc_faction SET Name_Lang_enCN='叛变的迪菲亚盗贼(艾泽拉斯)', Description_Lang_enCN='' WHERE ID=30;
UPDATE dbc_faction SET Name_Lang_enCN='友方', Description_Lang_enCN='' WHERE ID=31;
UPDATE dbc_faction SET Name_Lang_enCN='穴居人', Description_Lang_enCN='' WHERE ID=32;
UPDATE dbc_faction SET Name_Lang_enCN='冰巨魔', Description_Lang_enCN='' WHERE ID=33;
UPDATE dbc_faction SET Name_Lang_enCN='黑石氏族兽人', Description_Lang_enCN='' WHERE ID=34;
UPDATE dbc_faction SET Name_Lang_enCN='Villian', Description_Lang_enCN='' WHERE ID=35;
UPDATE dbc_faction SET Name_Lang_enCN='牺牲品', Description_Lang_enCN='' WHERE ID=36;
UPDATE dbc_faction SET Name_Lang_enCN='熊', Description_Lang_enCN='' WHERE ID=37;
UPDATE dbc_faction SET Name_Lang_enCN='食人魔', Description_Lang_enCN='' WHERE ID=38;
UPDATE dbc_faction SET Name_Lang_enCN='库森的雇佣兵', Description_Lang_enCN='' WHERE ID=39;
UPDATE dbc_faction SET Name_Lang_enCN='卫队', Description_Lang_enCN='' WHERE ID=40;
UPDATE dbc_faction SET Name_Lang_enCN='荆棘谷地精', Description_Lang_enCN='' WHERE ID=41;
UPDATE dbc_faction SET Name_Lang_enCN='迅猛龙', Description_Lang_enCN='' WHERE ID=42;
UPDATE dbc_faction SET Name_Lang_enCN='石化蜥蜴', Description_Lang_enCN='' WHERE ID=43;
UPDATE dbc_faction SET Name_Lang_enCN='绿龙', Description_Lang_enCN='' WHERE ID=44;
UPDATE dbc_faction SET Name_Lang_enCN='失落者', Description_Lang_enCN='' WHERE ID=45;
UPDATE dbc_faction SET Name_Lang_enCN='斯通纳德兽人', Description_Lang_enCN='' WHERE ID=46;
UPDATE dbc_faction SET Name_Lang_enCN='铁炉堡', Description_Lang_enCN='这座联盟的大都市是丹莫罗矮人们的骄傲，也是麦格尼国王的家。' WHERE ID=47;
UPDATE dbc_faction SET Name_Lang_enCN='黑铁矮人', Description_Lang_enCN='' WHERE ID=48;
UPDATE dbc_faction SET Name_Lang_enCN='暮色森林守夜人', Description_Lang_enCN='' WHERE ID=49;
UPDATE dbc_faction SET Name_Lang_enCN='红龙', Description_Lang_enCN='' WHERE ID=50;
UPDATE dbc_faction SET Name_Lang_enCN='藓皮豺狼人', Description_Lang_enCN='' WHERE ID=51;
UPDATE dbc_faction SET Name_Lang_enCN='龙喉氏族兽人', Description_Lang_enCN='' WHERE ID=52;
UPDATE dbc_faction SET Name_Lang_enCN='疯狂侏儒', Description_Lang_enCN='' WHERE ID=53;
UPDATE dbc_faction SET Name_Lang_enCN='诺莫瑞根流亡者', Description_Lang_enCN='诺莫瑞根以前的居民，现在流亡到了铁炉堡并居住在此，联盟方的重要成员。' WHERE ID=54;
UPDATE dbc_faction SET Name_Lang_enCN='豹', Description_Lang_enCN='' WHERE ID=55;
UPDATE dbc_faction SET Name_Lang_enCN='血色十字军', Description_Lang_enCN='' WHERE ID=56;
UPDATE dbc_faction SET Name_Lang_enCN='烂皮豺狼人', Description_Lang_enCN='' WHERE ID=57;
UPDATE dbc_faction SET Name_Lang_enCN='猩猩', Description_Lang_enCN='' WHERE ID=58;
UPDATE dbc_faction SET Name_Lang_enCN='瑟银兄弟会', Description_Lang_enCN='瑟银兄弟会的矮人有着无与伦比的制造技术，并致力于解开黑石山中的全部秘密。' WHERE ID=59;
UPDATE dbc_faction SET Name_Lang_enCN='纳迦', Description_Lang_enCN='' WHERE ID=60;
UPDATE dbc_faction SET Name_Lang_enCN='达拉然', Description_Lang_enCN='' WHERE ID=61;
UPDATE dbc_faction SET Name_Lang_enCN='弃灵', Description_Lang_enCN='' WHERE ID=62;
UPDATE dbc_faction SET Name_Lang_enCN='Darkhowl', Description_Lang_enCN='' WHERE ID=63;
UPDATE dbc_faction SET Name_Lang_enCN='劣魔', Description_Lang_enCN='' WHERE ID=64;
UPDATE dbc_faction SET Name_Lang_enCN='熊怪', Description_Lang_enCN='' WHERE ID=65;
UPDATE dbc_faction SET Name_Lang_enCN='部落友军', Description_Lang_enCN='' WHERE ID=66;
UPDATE dbc_faction SET Name_Lang_enCN='部落', Description_Lang_enCN='' WHERE ID=67;
UPDATE dbc_faction SET Name_Lang_enCN='幽暗城', Description_Lang_enCN='希尔瓦娜斯·风行者领导下的被遗忘者与部落之间建立起了微弱的同盟关系，并在洛丹伦地下遗迹的深处建立起了这座城市。' WHERE ID=68;
UPDATE dbc_faction SET Name_Lang_enCN='达纳苏斯', Description_Lang_enCN='坐落在泰达希尔岛上的联盟城市，暗夜精灵的首都，由月女祭司泰兰德·语风统治。' WHERE ID=69;
UPDATE dbc_faction SET Name_Lang_enCN='辛迪加', Description_Lang_enCN='一个主要由人类组成的犯罪组织，目前占据着奥特兰克山脉与希尔斯布莱德丘陵的部分地区。' WHERE ID=70;
UPDATE dbc_faction SET Name_Lang_enCN='希尔斯布莱德民兵', Description_Lang_enCN='' WHERE ID=71;
UPDATE dbc_faction SET Name_Lang_enCN='暴风城', Description_Lang_enCN='这座人类势力的最后堡垒目前由流浪归来的国王瓦里安·乌瑞恩统治着。' WHERE ID=72;
UPDATE dbc_faction SET Name_Lang_enCN='恶魔', Description_Lang_enCN='' WHERE ID=73;
UPDATE dbc_faction SET Name_Lang_enCN='元素生物', Description_Lang_enCN='' WHERE ID=74;
UPDATE dbc_faction SET Name_Lang_enCN='灵魂', Description_Lang_enCN='' WHERE ID=75;
UPDATE dbc_faction SET Name_Lang_enCN='奥格瑞玛', Description_Lang_enCN='这座由萨尔建立的部落城市是许多兽人氏族的家园。' WHERE ID=76;
UPDATE dbc_faction SET Name_Lang_enCN='宝物', Description_Lang_enCN='' WHERE ID=77;
UPDATE dbc_faction SET Name_Lang_enCN='泥嘴豺狼人', Description_Lang_enCN='' WHERE ID=78;
UPDATE dbc_faction SET Name_Lang_enCN='希尔斯布莱德，南海镇', Description_Lang_enCN='' WHERE ID=79;
UPDATE dbc_faction SET Name_Lang_enCN='黑龙', Description_Lang_enCN='' WHERE ID=80;
UPDATE dbc_faction SET Name_Lang_enCN='雷霆崖', Description_Lang_enCN='凯恩·血蹄及其领导下的牛头人的家园，壮丽而伟大的部落城市。' WHERE ID=81;
UPDATE dbc_faction SET Name_Lang_enCN='枯木巨魔', Description_Lang_enCN='' WHERE ID=82;
UPDATE dbc_faction SET Name_Lang_enCN='怪物 - 无组织', Description_Lang_enCN='' WHERE ID=83;
UPDATE dbc_faction SET Name_Lang_enCN='钢鬃野猪人', Description_Lang_enCN='' WHERE ID=84;
UPDATE dbc_faction SET Name_Lang_enCN='刺背野猪人', Description_Lang_enCN='' WHERE ID=85;
UPDATE dbc_faction SET Name_Lang_enCN='怪物 - 有组织', Description_Lang_enCN='' WHERE ID=86;
UPDATE dbc_faction SET Name_Lang_enCN='血帆海盗', Description_Lang_enCN='一群嗜血的海盗，所有海上商人的公敌。藏宝海湾的死敌。' WHERE ID=87;
UPDATE dbc_faction SET Name_Lang_enCN='黑暗深渊', Description_Lang_enCN='' WHERE ID=88;
UPDATE dbc_faction SET Name_Lang_enCN='龙虾人', Description_Lang_enCN='' WHERE ID=89;
UPDATE dbc_faction SET Name_Lang_enCN='科卡尔半人马', Description_Lang_enCN='' WHERE ID=90;
UPDATE dbc_faction SET Name_Lang_enCN='加拉克半人马', Description_Lang_enCN='' WHERE ID=91;
UPDATE dbc_faction SET Name_Lang_enCN='吉尔吉斯半人马', Description_Lang_enCN='一群居住在凄凉之地南方的半人马，玛格拉姆半人马的仇敌。' WHERE ID=92;
UPDATE dbc_faction SET Name_Lang_enCN='玛格拉姆半人马', Description_Lang_enCN='一群居住在凄凉之地东部的半人马，吉尔吉斯半人马的仇敌。' WHERE ID=93;
UPDATE dbc_faction SET Name_Lang_enCN='玛洛迪', Description_Lang_enCN='' WHERE ID=94;
UPDATE dbc_faction SET Name_Lang_enCN='塞拉摩', Description_Lang_enCN='' WHERE ID=108;
UPDATE dbc_faction SET Name_Lang_enCN='剃刀沼泽野猪人', Description_Lang_enCN='' WHERE ID=109;
UPDATE dbc_faction SET Name_Lang_enCN='钢鬃野猪人', Description_Lang_enCN='' WHERE ID=110;
UPDATE dbc_faction SET Name_Lang_enCN='Quilboar, Deathshead', Description_Lang_enCN='' WHERE ID=111;
UPDATE dbc_faction SET Name_Lang_enCN='敌人', Description_Lang_enCN='' WHERE ID=128;
UPDATE dbc_faction SET Name_Lang_enCN='小动物', Description_Lang_enCN='' WHERE ID=148;
UPDATE dbc_faction SET Name_Lang_enCN='奈瑟加德商队', Description_Lang_enCN='' WHERE ID=168;
UPDATE dbc_faction SET Name_Lang_enCN='热砂港', Description_Lang_enCN='' WHERE ID=169;
UPDATE dbc_faction SET Name_Lang_enCN='联盟', Description_Lang_enCN='' WHERE ID=189;
UPDATE dbc_faction SET Name_Lang_enCN='守望堡', Description_Lang_enCN='' WHERE ID=209;
UPDATE dbc_faction SET Name_Lang_enCN='哀嚎洞穴', Description_Lang_enCN='' WHERE ID=229;
UPDATE dbc_faction SET Name_Lang_enCN='异种蝎', Description_Lang_enCN='' WHERE ID=249;
UPDATE dbc_faction SET Name_Lang_enCN='银月幸存者', Description_Lang_enCN='' WHERE ID=269;
UPDATE dbc_faction SET Name_Lang_enCN='赞达拉部族', Description_Lang_enCN='这群居住在尤亚姆巴岛的巨魔正在努力招募全世界的勇士，希望他们能够帮助自己对抗祖尔格拉布中的邪神哈卡以及他的阿塔莱祭司们。' WHERE ID=270;
UPDATE dbc_faction SET Name_Lang_enCN='黑水海盗', Description_Lang_enCN='' WHERE ID=289;
UPDATE dbc_faction SET Name_Lang_enCN='蝎子', Description_Lang_enCN='' WHERE ID=309;
UPDATE dbc_faction SET Name_Lang_enCN='蝙蝠', Description_Lang_enCN='' WHERE ID=310;
UPDATE dbc_faction SET Name_Lang_enCN='泰坦', Description_Lang_enCN='' WHERE ID=311;
UPDATE dbc_faction SET Name_Lang_enCN='工头费苏勒', Description_Lang_enCN='' WHERE ID=329;
UPDATE dbc_faction SET Name_Lang_enCN='拉文霍德', Description_Lang_enCN='这个由盗贼与刺客组成的行会只欢迎那些有着出色实力的人进入他们的领地。他们也是辛迪加的仇敌。' WHERE ID=349;
UPDATE dbc_faction SET Name_Lang_enCN='加基森', Description_Lang_enCN='热砂集团的首府，诸多优秀地精技师、炼金师和商人的家乡。' WHERE ID=369;
UPDATE dbc_faction SET Name_Lang_enCN='Gnomeregan Bug', Description_Lang_enCN='' WHERE ID=389;
UPDATE dbc_faction SET Name_Lang_enCN='鹰身人', Description_Lang_enCN='' WHERE ID=409;
UPDATE dbc_faction SET Name_Lang_enCN='火刃氏族', Description_Lang_enCN='' WHERE ID=429;
UPDATE dbc_faction SET Name_Lang_enCN='暗影蛛丝偷猎者', Description_Lang_enCN='' WHERE ID=449;
UPDATE dbc_faction SET Name_Lang_enCN='Searing Spider', Description_Lang_enCN='' WHERE ID=450;
UPDATE dbc_faction SET Name_Lang_enCN='联盟', Description_Lang_enCN='' WHERE ID=469;
UPDATE dbc_faction SET Name_Lang_enCN='棘齿城', Description_Lang_enCN='热砂集团的成员，这座城市给许多希望在贫瘠之地做生意的人提供了一个开放和中立的天堂。' WHERE ID=470;
UPDATE dbc_faction SET Name_Lang_enCN='蛮锤部族', Description_Lang_enCN='尽管并非是联盟的一份子，但鹰巢山的矮人还是将联盟视为他们的朋友，并与部落保持着交战关系。' WHERE ID=471;
UPDATE dbc_faction SET Name_Lang_enCN='Goblin, Dark Iron Bar Patron', Description_Lang_enCN='' WHERE ID=489;
UPDATE dbc_faction SET Name_Lang_enCN='阿拉索联军', Description_Lang_enCN='阿拉索联军正试图为暴风城夺回阿拉希盆地。' WHERE ID=509;
UPDATE dbc_faction SET Name_Lang_enCN='污染者', Description_Lang_enCN='污染者试图为部落夺取阿拉希盆地的重要资源。' WHERE ID=510;
UPDATE dbc_faction SET Name_Lang_enCN='巨人', Description_Lang_enCN='' WHERE ID=511;
UPDATE dbc_faction SET Name_Lang_enCN='银色黎明', Description_Lang_enCN='一个致力于从亡灵天灾军团的威胁下拯救艾泽拉斯世界的组织。银色黎明的据点遍布东西瘟疫之地。' WHERE ID=529;
UPDATE dbc_faction SET Name_Lang_enCN='暗矛巨魔', Description_Lang_enCN='一群被放逐的巨魔，加入了萨尔领导下的部落。他们现在将杜隆塔尔当作自己的新家，并与兽人盟友们一起生活在那里。' WHERE ID=530;
UPDATE dbc_faction SET Name_Lang_enCN='青铜龙军团', Description_Lang_enCN='' WHERE ID=531;
UPDATE dbc_faction SET Name_Lang_enCN='蓝龙军团', Description_Lang_enCN='' WHERE ID=532;
UPDATE dbc_faction SET Name_Lang_enCN=' Leatherworking - Tribal', Description_Lang_enCN='' WHERE ID=549;
UPDATE dbc_faction SET Name_Lang_enCN=' Engineering - Goblin', Description_Lang_enCN='' WHERE ID=550;
UPDATE dbc_faction SET Name_Lang_enCN=' Engineering - Gnome', Description_Lang_enCN='' WHERE ID=551;
UPDATE dbc_faction SET Name_Lang_enCN=' Blacksmithing - Hammersmithing', Description_Lang_enCN='' WHERE ID=569;
UPDATE dbc_faction SET Name_Lang_enCN=' Blacksmithing - Axesmithing', Description_Lang_enCN='' WHERE ID=570;
UPDATE dbc_faction SET Name_Lang_enCN=' Blacksmithing - Swordsmithing', Description_Lang_enCN='' WHERE ID=571;
UPDATE dbc_faction SET Name_Lang_enCN='邪枝巨魔', Description_Lang_enCN='' WHERE ID=572;
UPDATE dbc_faction SET Name_Lang_enCN='南海海盗', Description_Lang_enCN='' WHERE ID=573;
UPDATE dbc_faction SET Name_Lang_enCN='凯尔达隆', Description_Lang_enCN='' WHERE ID=574;
UPDATE dbc_faction SET Name_Lang_enCN='未堕落的熊怪', Description_Lang_enCN='' WHERE ID=575;
UPDATE dbc_faction SET Name_Lang_enCN='木喉要塞', Description_Lang_enCN='作为最后一支尚未堕落的熊怪部族，木喉部族正致力于保留他们那种独特的精神修行之道，并试图终结其他熊怪部族的痛苦。' WHERE ID=576;
UPDATE dbc_faction SET Name_Lang_enCN='永望镇', Description_Lang_enCN='热砂集团经营之下的一座贸易城市，坐落于冬泉谷的两条主要干道的交叉处。' WHERE ID=577;
UPDATE dbc_faction SET Name_Lang_enCN='冬刃豹训练师', Description_Lang_enCN='这是一些专门在冬泉谷地区驯养冬泉霜刃豹的暗夜精灵。' WHERE ID=589;
UPDATE dbc_faction SET Name_Lang_enCN='塞纳里奥议会', Description_Lang_enCN='塞纳里奥议会的德鲁伊是自然的守卫者，他们定居于宁静的月光林地。' WHERE ID=609;
UPDATE dbc_faction SET Name_Lang_enCN='断矛巨魔', Description_Lang_enCN='' WHERE ID=629;
UPDATE dbc_faction SET Name_Lang_enCN='暴掠龙训练师', Description_Lang_enCN='' WHERE ID=630;
UPDATE dbc_faction SET Name_Lang_enCN='管理者埃克索图斯', Description_Lang_enCN='' WHERE ID=649;
UPDATE dbc_faction SET Name_Lang_enCN='Beast - Carrion Bird', Description_Lang_enCN='' WHERE ID=669;
UPDATE dbc_faction SET Name_Lang_enCN='Beast - Cat', Description_Lang_enCN='' WHERE ID=670;
UPDATE dbc_faction SET Name_Lang_enCN='Beast - Crab', Description_Lang_enCN='' WHERE ID=671;
UPDATE dbc_faction SET Name_Lang_enCN='Beast - Crocilisk', Description_Lang_enCN='' WHERE ID=672;
UPDATE dbc_faction SET Name_Lang_enCN='Beast - Hyena', Description_Lang_enCN='' WHERE ID=673;
UPDATE dbc_faction SET Name_Lang_enCN='Beast - Owl', Description_Lang_enCN='' WHERE ID=674;
UPDATE dbc_faction SET Name_Lang_enCN='Beast - Scorpid', Description_Lang_enCN='' WHERE ID=675;
UPDATE dbc_faction SET Name_Lang_enCN='Beast - Tallstrider', Description_Lang_enCN='' WHERE ID=676;
UPDATE dbc_faction SET Name_Lang_enCN='Beast - Turtle', Description_Lang_enCN='' WHERE ID=677;
UPDATE dbc_faction SET Name_Lang_enCN='Beast - Wind Serpent', Description_Lang_enCN='' WHERE ID=678;
UPDATE dbc_faction SET Name_Lang_enCN='Training Dummy', Description_Lang_enCN='' WHERE ID=679;
UPDATE dbc_faction SET Name_Lang_enCN='Dragonflight, Black - Bait', Description_Lang_enCN='' WHERE ID=689;
UPDATE dbc_faction SET Name_Lang_enCN='Battleground Neutral', Description_Lang_enCN='' WHERE ID=709;
UPDATE dbc_faction SET Name_Lang_enCN='霜狼氏族', Description_Lang_enCN='霜狼氏族正在努力将雷矛探险队赶出奥特兰克山谷。' WHERE ID=729;
UPDATE dbc_faction SET Name_Lang_enCN='雷矛卫队', Description_Lang_enCN='一群在奥特兰克山谷建立了永久居所的矮人，正与霜狼氏族的兽人激烈交战中。' WHERE ID=730;
UPDATE dbc_faction SET Name_Lang_enCN='海达希亚水元素', Description_Lang_enCN='这些元素生物定居于艾萨拉的东部的一座小岛上，是拉格纳罗斯及其军团的死敌。' WHERE ID=749;
UPDATE dbc_faction SET Name_Lang_enCN='萨弗隆火元素', Description_Lang_enCN='' WHERE ID=750;
UPDATE dbc_faction SET Name_Lang_enCN='吉兹洛克的假人', Description_Lang_enCN='' WHERE ID=769;
UPDATE dbc_faction SET Name_Lang_enCN='Gizlock''s Charm', Description_Lang_enCN='' WHERE ID=770;
UPDATE dbc_faction SET Name_Lang_enCN='吉兹洛克', Description_Lang_enCN='' WHERE ID=771;
UPDATE dbc_faction SET Name_Lang_enCN='莫洛加', Description_Lang_enCN='' WHERE ID=789;
UPDATE dbc_faction SET Name_Lang_enCN='Spirit Guide - Alliance', Description_Lang_enCN='' WHERE ID=790;
UPDATE dbc_faction SET Name_Lang_enCN='辛德拉', Description_Lang_enCN='一群居住在厄运之槌的精灵后裔，他们仍然具有着相当渊博的智慧与学识，并保守着一些伟大的秘密。' WHERE ID=809;
UPDATE dbc_faction SET Name_Lang_enCN='Ogre (Captain Kromcrush)', Description_Lang_enCN='' WHERE ID=829;
UPDATE dbc_faction SET Name_Lang_enCN='Spirit Guide - Horde', Description_Lang_enCN='' WHERE ID=849;
UPDATE dbc_faction SET Name_Lang_enCN='加德纳尔', Description_Lang_enCN='' WHERE ID=869;
UPDATE dbc_faction SET Name_Lang_enCN='战歌氏族', Description_Lang_enCN='战歌氏族是最具攻击性的兽人氏族，目前正与暗夜精灵的银翼哨兵部队在战歌峡谷激烈地交战中。' WHERE ID=889;
UPDATE dbc_faction SET Name_Lang_enCN='银翼要塞', Description_Lang_enCN='灰谷地区坚定的守卫者，目前正与战歌氏族在战歌峡谷中激烈交战。' WHERE ID=890;
UPDATE dbc_faction SET Name_Lang_enCN='联盟部队', Description_Lang_enCN='' WHERE ID=891;
UPDATE dbc_faction SET Name_Lang_enCN='部落军队', Description_Lang_enCN='' WHERE ID=892;
UPDATE dbc_faction SET Name_Lang_enCN='恶齿巨魔', Description_Lang_enCN='' WHERE ID=893;
UPDATE dbc_faction SET Name_Lang_enCN='暗月马戏团', Description_Lang_enCN='一个向全世界展示着各类珍奇异宝的旅行马戏团。他们经常会访问艾尔文森林、莫高雷和泰罗卡森林。' WHERE ID=909;
UPDATE dbc_faction SET Name_Lang_enCN='诺兹多姆的子嗣', Description_Lang_enCN='青铜龙军团的后代，时间的守卫者，对凡人种族漠不关心。' WHERE ID=910;
UPDATE dbc_faction SET Name_Lang_enCN='银月城', Description_Lang_enCN='奎尔萨拉斯的首都，血精灵的家园。虽然银月城几乎被阿尔萨斯毁灭，但它再次成为了一座繁荣的城市。' WHERE ID=911;
UPDATE dbc_faction SET Name_Lang_enCN='卡利姆多联军', Description_Lang_enCN='' WHERE ID=912;
UPDATE dbc_faction SET Name_Lang_enCN='玩家，血精灵', Description_Lang_enCN='' WHERE ID=914;
UPDATE dbc_faction SET Name_Lang_enCN='克苏恩的军队', Description_Lang_enCN='' WHERE ID=915;
UPDATE dbc_faction SET Name_Lang_enCN='异种虫类', Description_Lang_enCN='' WHERE ID=916;
UPDATE dbc_faction SET Name_Lang_enCN='铁炉堡军团', Description_Lang_enCN='' WHERE ID=917;
UPDATE dbc_faction SET Name_Lang_enCN='RC Enemies', Description_Lang_enCN='' WHERE ID=918;
UPDATE dbc_faction SET Name_Lang_enCN='RC Objects', Description_Lang_enCN='' WHERE ID=919;
UPDATE dbc_faction SET Name_Lang_enCN='红', Description_Lang_enCN='' WHERE ID=920;
UPDATE dbc_faction SET Name_Lang_enCN='蓝', Description_Lang_enCN='' WHERE ID=921;
UPDATE dbc_faction SET Name_Lang_enCN='塔奎林', Description_Lang_enCN='塔奎林曾是一座高等精灵的城镇，但是在天灾军团入侵奎尔萨拉斯之后被废弃了。现在，被遗忘者和血精灵联手夺回了这座城镇。' WHERE ID=922;
UPDATE dbc_faction SET Name_Lang_enCN='远行者', Description_Lang_enCN='' WHERE ID=923;
UPDATE dbc_faction SET Name_Lang_enCN='DEPRECATED', Description_Lang_enCN='' WHERE ID=924;
UPDATE dbc_faction SET Name_Lang_enCN='逐日者', Description_Lang_enCN='' WHERE ID=925;
UPDATE dbc_faction SET Name_Lang_enCN='魔导师公会', Description_Lang_enCN='' WHERE ID=926;
UPDATE dbc_faction SET Name_Lang_enCN='玩家，德莱尼', Description_Lang_enCN='' WHERE ID=927;
UPDATE dbc_faction SET Name_Lang_enCN='天灾入侵者', Description_Lang_enCN='' WHERE ID=928;
UPDATE dbc_faction SET Name_Lang_enCN='血槌氏族', Description_Lang_enCN='' WHERE ID=929;
UPDATE dbc_faction SET Name_Lang_enCN='埃索达', Description_Lang_enCN='将德莱尼人带到艾泽拉斯世界来的纳鲁飞船，目前搁浅在秘蓝岛上。对于这个高贵的种族来说，埃索达是他们的主城。' WHERE ID=930;
UPDATE dbc_faction SET Name_Lang_enCN='Test Faction (not a real faction)', Description_Lang_enCN='This faction only exists to test the editing of faction names and descriptions...' WHERE ID=931;
UPDATE dbc_faction SET Name_Lang_enCN='奥尔多', Description_Lang_enCN='一个古老的德莱尼祭司组织，起初由维伦领导。现在他们在高阶女祭司伊沙娜的指引下为沙塔斯城的纳鲁效力。与占星者势力敌对。' WHERE ID=932;
UPDATE dbc_faction SET Name_Lang_enCN='星界财团', Description_Lang_enCN='由星界巨商哈拉麦德领导的星界财团是一个结构松散的商业联盟，其成员都是从事走私、贸易或盗窃的虚灵。' WHERE ID=933;
UPDATE dbc_faction SET Name_Lang_enCN='占星者', Description_Lang_enCN='由先知沃雷塔尔领导的这群血精灵拒绝跟随凯尔萨斯。他们加入了沙塔斯城的纳鲁联军，这令奥尔多感到非常不安。' WHERE ID=934;
UPDATE dbc_faction SET Name_Lang_enCN='沙塔尔', Description_Lang_enCN='沙塔尔是一群统治沙塔斯城的强大纳鲁人的组织。在奥尔多和占星者的帮助下，他们正在领导针对伊利丹和燃烧军团的战斗。' WHERE ID=935;
UPDATE dbc_faction SET Name_Lang_enCN='沙塔斯城', Description_Lang_enCN='' WHERE ID=936;
UPDATE dbc_faction SET Name_Lang_enCN='森林巨魔', Description_Lang_enCN='' WHERE ID=937;
UPDATE dbc_faction SET Name_Lang_enCN='欧麦尼', Description_Lang_enCN='' WHERE ID=938;
UPDATE dbc_faction SET Name_Lang_enCN='DEPRECATED', Description_Lang_enCN='' WHERE ID=939;
UPDATE dbc_faction SET Name_Lang_enCN='洛萨之子', Description_Lang_enCN='' WHERE ID=940;
UPDATE dbc_faction SET Name_Lang_enCN='玛格汉', Description_Lang_enCN='这群隐居的棕皮兽人逃脱了恶魔的腐蚀，并在天崩地裂的外域中保持了古老的传统。' WHERE ID=941;
UPDATE dbc_faction SET Name_Lang_enCN='塞纳里奥远征队', Description_Lang_enCN='塞纳里奥议会派往外域研究生态的探险队。在黑暗之门开启后，远征队迅速壮大，并获得了自治权。' WHERE ID=942;
UPDATE dbc_faction SET Name_Lang_enCN='邪兽人', Description_Lang_enCN='' WHERE ID=943;
UPDATE dbc_faction SET Name_Lang_enCN='邪兽人幽灵', Description_Lang_enCN='' WHERE ID=944;
UPDATE dbc_faction SET Name_Lang_enCN='洛萨之子', Description_Lang_enCN='' WHERE ID=945;
UPDATE dbc_faction SET Name_Lang_enCN='荣耀堡', Description_Lang_enCN='这座前哨基地坐落在地狱火半岛上，由第一批深入德拉诺的联盟精英部队“洛萨之子”的残余力量坚守。现在他们得到了来自暴风城和铁炉堡的支援。' WHERE ID=946;
UPDATE dbc_faction SET Name_Lang_enCN='萨尔玛', Description_Lang_enCN='由萨尔派出的远征军在地狱火半岛建立的要塞。萨尔玛是部落在外域的大部分行动的根据地。' WHERE ID=947;
UPDATE dbc_faction SET Name_Lang_enCN='Test Faction 2', Description_Lang_enCN='' WHERE ID=948;
UPDATE dbc_faction SET Name_Lang_enCN='Test Faction 1', Description_Lang_enCN='' WHERE ID=949;
UPDATE dbc_faction SET Name_Lang_enCN='ToWoW - Flag', Description_Lang_enCN='' WHERE ID=950;
UPDATE dbc_faction SET Name_Lang_enCN='ToWoW - Flag Trigger Alliance (DND)', Description_Lang_enCN='' WHERE ID=951;
UPDATE dbc_faction SET Name_Lang_enCN='Test Faction 3', Description_Lang_enCN='' WHERE ID=952;
UPDATE dbc_faction SET Name_Lang_enCN='Test Faction 4', Description_Lang_enCN='' WHERE ID=953;
UPDATE dbc_faction SET Name_Lang_enCN='ToWoW - Flag Trigger Horde (DND)', Description_Lang_enCN='' WHERE ID=954;
UPDATE dbc_faction SET Name_Lang_enCN='破碎者', Description_Lang_enCN='' WHERE ID=955;
UPDATE dbc_faction SET Name_Lang_enCN='复仇军', Description_Lang_enCN='' WHERE ID=956;
UPDATE dbc_faction SET Name_Lang_enCN='土元素', Description_Lang_enCN='' WHERE ID=957;
UPDATE dbc_faction SET Name_Lang_enCN='打架机器人', Description_Lang_enCN='' WHERE ID=958;
UPDATE dbc_faction SET Name_Lang_enCN='好演员', Description_Lang_enCN='' WHERE ID=959;
UPDATE dbc_faction SET Name_Lang_enCN='坏演员', Description_Lang_enCN='' WHERE ID=960;
UPDATE dbc_faction SET Name_Lang_enCN='止松熊怪', Description_Lang_enCN='' WHERE ID=961;
UPDATE dbc_faction SET Name_Lang_enCN='疯狂的枭兽', Description_Lang_enCN='' WHERE ID=962;
UPDATE dbc_faction SET Name_Lang_enCN='联盟棋子', Description_Lang_enCN='' WHERE ID=963;
UPDATE dbc_faction SET Name_Lang_enCN='部落棋子', Description_Lang_enCN='' WHERE ID=964;
UPDATE dbc_faction SET Name_Lang_enCN='Monster Spar', Description_Lang_enCN='' WHERE ID=965;
UPDATE dbc_faction SET Name_Lang_enCN='Monster Spar Buddy', Description_Lang_enCN='' WHERE ID=966;
UPDATE dbc_faction SET Name_Lang_enCN='紫罗兰之眼', Description_Lang_enCN='一个由肯瑞托为了调查麦迪文和监视他的活动而建立的秘密组织。' WHERE ID=967;
UPDATE dbc_faction SET Name_Lang_enCN='炎鹰', Description_Lang_enCN='' WHERE ID=968;
UPDATE dbc_faction SET Name_Lang_enCN='阿古斯之手', Description_Lang_enCN='' WHERE ID=969;
UPDATE dbc_faction SET Name_Lang_enCN='孢子村', Description_Lang_enCN='生活在外域的孢子人是一个非常温和的种族。他们的家园就坐落在赞加沼泽南部的沼泽地中。' WHERE ID=970;
UPDATE dbc_faction SET Name_Lang_enCN='真菌巨人', Description_Lang_enCN='' WHERE ID=971;
UPDATE dbc_faction SET Name_Lang_enCN='孢子蝠', Description_Lang_enCN='' WHERE ID=972;
UPDATE dbc_faction SET Name_Lang_enCN='Monster, Predator', Description_Lang_enCN='' WHERE ID=973;
UPDATE dbc_faction SET Name_Lang_enCN='Monster, Prey', Description_Lang_enCN='' WHERE ID=974;
UPDATE dbc_faction SET Name_Lang_enCN='虚空畸能', Description_Lang_enCN='' WHERE ID=975;
UPDATE dbc_faction SET Name_Lang_enCN='海加尔防御者', Description_Lang_enCN='' WHERE ID=976;
UPDATE dbc_faction SET Name_Lang_enCN='海加尔入侵者', Description_Lang_enCN='' WHERE ID=977;
UPDATE dbc_faction SET Name_Lang_enCN='库雷尼', Description_Lang_enCN='在德莱尼语中意为“得到救赎”。这些从各种奴役和控制中逃出来的破碎者在纳格兰建立了自己的家园，寻找自己真正的命运。' WHERE ID=978;
UPDATE dbc_faction SET Name_Lang_enCN='大地之环', Description_Lang_enCN='' WHERE ID=979;
UPDATE dbc_faction SET Name_Lang_enCN='燃烧的远征', Description_Lang_enCN='' WHERE ID=980;
UPDATE dbc_faction SET Name_Lang_enCN='鸦人', Description_Lang_enCN='' WHERE ID=981;
UPDATE dbc_faction SET Name_Lang_enCN='赞加沼泽军旗（联盟）', Description_Lang_enCN='' WHERE ID=982;
UPDATE dbc_faction SET Name_Lang_enCN='赞加沼泽军旗（部落）', Description_Lang_enCN='' WHERE ID=983;
UPDATE dbc_faction SET Name_Lang_enCN='赞加沼泽军旗（中立）', Description_Lang_enCN='' WHERE ID=984;
UPDATE dbc_faction SET Name_Lang_enCN='时光之穴 - 萨尔', Description_Lang_enCN='' WHERE ID=985;
UPDATE dbc_faction SET Name_Lang_enCN='时光之穴 - 敦霍尔德', Description_Lang_enCN='' WHERE ID=986;
UPDATE dbc_faction SET Name_Lang_enCN='时光之穴 - 南海镇卫兵', Description_Lang_enCN='' WHERE ID=987;
UPDATE dbc_faction SET Name_Lang_enCN='暗影议会', Description_Lang_enCN='' WHERE ID=988;
UPDATE dbc_faction SET Name_Lang_enCN='时光守护者', Description_Lang_enCN='这些由诺兹多姆亲自挑选的青铜龙无时无刻不在监视着时光之穴。' WHERE ID=989;
UPDATE dbc_faction SET Name_Lang_enCN='流沙之鳞', Description_Lang_enCN='隶属于青铜龙军团的秘密组织，由诺兹多姆最亲密的伴侣索莉多米领导。' WHERE ID=990;
UPDATE dbc_faction SET Name_Lang_enCN='Dark Portal Defender, Alliance', Description_Lang_enCN='' WHERE ID=991;
UPDATE dbc_faction SET Name_Lang_enCN='Dark Portal Defender, Horde', Description_Lang_enCN='' WHERE ID=992;
UPDATE dbc_faction SET Name_Lang_enCN='Dark Portal Attacker, Legion', Description_Lang_enCN='' WHERE ID=993;
UPDATE dbc_faction SET Name_Lang_enCN='Inciter Trigger', Description_Lang_enCN='Used for the Blackheart the Inciter event.' WHERE ID=994;
UPDATE dbc_faction SET Name_Lang_enCN='Inciter Trigger 2', Description_Lang_enCN='Used for the Blackheart the Inciter event.' WHERE ID=995;
UPDATE dbc_faction SET Name_Lang_enCN='Inciter Trigger 3', Description_Lang_enCN='Used for the Blackheart the Inciter event.' WHERE ID=996;
UPDATE dbc_faction SET Name_Lang_enCN='Inciter Trigger 4', Description_Lang_enCN='Used for the Blackheart the Inciter event.' WHERE ID=997;
UPDATE dbc_faction SET Name_Lang_enCN='Inciter Trigger 5', Description_Lang_enCN='Used for the Blackheart the Inciter event.' WHERE ID=998;
UPDATE dbc_faction SET Name_Lang_enCN='法力生物', Description_Lang_enCN='' WHERE ID=999;
UPDATE dbc_faction SET Name_Lang_enCN='卡德加的仆从', Description_Lang_enCN='' WHERE ID=1000;
UPDATE dbc_faction SET Name_Lang_enCN='刀塔氏族', Description_Lang_enCN='' WHERE ID=1001;
UPDATE dbc_faction SET Name_Lang_enCN='复仇军', Description_Lang_enCN='' WHERE ID=1002;
UPDATE dbc_faction SET Name_Lang_enCN='维序派', Description_Lang_enCN='' WHERE ID=1003;
UPDATE dbc_faction SET Name_Lang_enCN='Arcane Annihilator (DNR)', Description_Lang_enCN='' WHERE ID=1004;
UPDATE dbc_faction SET Name_Lang_enCN='Friendly, Hidden', Description_Lang_enCN='' WHERE ID=1005;
UPDATE dbc_faction SET Name_Lang_enCN='Kirin''Var - Dathric', Description_Lang_enCN='' WHERE ID=1006;
UPDATE dbc_faction SET Name_Lang_enCN='Kirin''Var - Belmara', Description_Lang_enCN='' WHERE ID=1007;
UPDATE dbc_faction SET Name_Lang_enCN='Kirin''Var - Luminrath', Description_Lang_enCN='' WHERE ID=1008;
UPDATE dbc_faction SET Name_Lang_enCN='Kirin''Var - Cohlien', Description_Lang_enCN='' WHERE ID=1009;
UPDATE dbc_faction SET Name_Lang_enCN='伊利丹的仆从', Description_Lang_enCN='' WHERE ID=1010;
UPDATE dbc_faction SET Name_Lang_enCN='贫民窟', Description_Lang_enCN='来自各个地方、各个种族的避难者在沙塔斯城的聚集地。在贫民窟中，善行善举总是会很快传遍所有人的耳朵。' WHERE ID=1011;
UPDATE dbc_faction SET Name_Lang_enCN='灰舌死誓者', Description_Lang_enCN='来自破碎者灰舌部族的精英勇士，表面上与伊利丹结盟。这些勇士是阿卡玛最信任的部下，并参与了他的秘密计划。' WHERE ID=1012;
UPDATE dbc_faction SET Name_Lang_enCN='Spirits of Shadowmoon 1', Description_Lang_enCN='' WHERE ID=1013;
UPDATE dbc_faction SET Name_Lang_enCN='Spirits of Shadowmoon 2', Description_Lang_enCN='' WHERE ID=1014;
UPDATE dbc_faction SET Name_Lang_enCN='灵翼之龙', Description_Lang_enCN='这种罕见的龙是死亡之翼的后代，受到原始的虚空能量影响后发生了变异。现在，他们正在努力摆脱死亡之翼的血脉带来的阴影，找寻自己的命运。' WHERE ID=1015;
UPDATE dbc_faction SET Name_Lang_enCN='拜龙教', Description_Lang_enCN='' WHERE ID=1016;
UPDATE dbc_faction SET Name_Lang_enCN='树人', Description_Lang_enCN='' WHERE ID=1017;
UPDATE dbc_faction SET Name_Lang_enCN='Leotheras Demon I', Description_Lang_enCN='' WHERE ID=1018;
UPDATE dbc_faction SET Name_Lang_enCN='Leotheras Demon II', Description_Lang_enCN='' WHERE ID=1019;
UPDATE dbc_faction SET Name_Lang_enCN='Leotheras Demon III', Description_Lang_enCN='' WHERE ID=1020;
UPDATE dbc_faction SET Name_Lang_enCN='Leotheras Demon IV', Description_Lang_enCN='' WHERE ID=1021;
UPDATE dbc_faction SET Name_Lang_enCN='Leotheras Demon V', Description_Lang_enCN='' WHERE ID=1022;
UPDATE dbc_faction SET Name_Lang_enCN='阿萨洛斯', Description_Lang_enCN='' WHERE ID=1023;
UPDATE dbc_faction SET Name_Lang_enCN='剥石者', Description_Lang_enCN='' WHERE ID=1024;
UPDATE dbc_faction SET Name_Lang_enCN='剥石者猎手', Description_Lang_enCN='' WHERE ID=1025;
UPDATE dbc_faction SET Name_Lang_enCN='影月之魂', Description_Lang_enCN='' WHERE ID=1026;
UPDATE dbc_faction SET Name_Lang_enCN='军团联络器', Description_Lang_enCN='' WHERE ID=1027;
UPDATE dbc_faction SET Name_Lang_enCN='乌鸦林古树', Description_Lang_enCN='' WHERE ID=1028;
UPDATE dbc_faction SET Name_Lang_enCN='Chess, Friendly to All Chess', Description_Lang_enCN='' WHERE ID=1029;
UPDATE dbc_faction SET Name_Lang_enCN='Black Temple Gates - Illidari', Description_Lang_enCN='' WHERE ID=1030;
UPDATE dbc_faction SET Name_Lang_enCN='沙塔尔天空卫队', Description_Lang_enCN='一支由沙塔斯城建立的空中武装力量，职责是应对潜伏在外域天空中的威胁。' WHERE ID=1031;
UPDATE dbc_faction SET Name_Lang_enCN='52区', Description_Lang_enCN='' WHERE ID=1032;
UPDATE dbc_faction SET Name_Lang_enCN='玛维', Description_Lang_enCN='' WHERE ID=1033;
UPDATE dbc_faction SET Name_Lang_enCN='斯克提斯阴影鸦人', Description_Lang_enCN='' WHERE ID=1034;
UPDATE dbc_faction SET Name_Lang_enCN='斯克提斯鸦人', Description_Lang_enCN='' WHERE ID=1035;
UPDATE dbc_faction SET Name_Lang_enCN='龙喉之敌', Description_Lang_enCN='' WHERE ID=1036;
UPDATE dbc_faction SET Name_Lang_enCN='联盟先遣军', Description_Lang_enCN='联盟派往诺森德的多支部队的统称，由无畏远征军领导。同时也包括一些非军事组织，如探险者协会。' WHERE ID=1037;
UPDATE dbc_faction SET Name_Lang_enCN='奥格瑞拉', Description_Lang_enCN='聪明而开化的奥格瑞拉食人魔居住在刀锋山的西部区域，那里富产的埃匹希斯水晶使得他们的智商远远超越了其他野蛮的同类。' WHERE ID=1038;
UPDATE dbc_faction SET Name_Lang_enCN='掠食者', Description_Lang_enCN='' WHERE ID=1039;
UPDATE dbc_faction SET Name_Lang_enCN='REUSE', Description_Lang_enCN='' WHERE ID=1040;
UPDATE dbc_faction SET Name_Lang_enCN='狂鱼', Description_Lang_enCN='' WHERE ID=1041;
UPDATE dbc_faction SET Name_Lang_enCN='天空卫队之敌', Description_Lang_enCN='' WHERE ID=1042;
UPDATE dbc_faction SET Name_Lang_enCN='臭鼬', Description_Lang_enCN='' WHERE ID=1043;
UPDATE dbc_faction SET Name_Lang_enCN='塞拉摩叛逃者', Description_Lang_enCN='' WHERE ID=1044;
UPDATE dbc_faction SET Name_Lang_enCN='维库人', Description_Lang_enCN='' WHERE ID=1045;
UPDATE dbc_faction SET Name_Lang_enCN='北海海盗', Description_Lang_enCN='' WHERE ID=1046;
UPDATE dbc_faction SET Name_Lang_enCN='海象人', Description_Lang_enCN='' WHERE ID=1047;
UPDATE dbc_faction SET Name_Lang_enCN='UNUSED', Description_Lang_enCN='' WHERE ID=1048;
UPDATE dbc_faction SET Name_Lang_enCN='阿曼尼巨魔', Description_Lang_enCN='' WHERE ID=1049;
UPDATE dbc_faction SET Name_Lang_enCN='无畏远征军', Description_Lang_enCN='联盟在诺森德的主力部队，由瓦里安·乌瑞恩国王统领，对抗天灾军团。' WHERE ID=1050;
UPDATE dbc_faction SET Name_Lang_enCN='UNUSED', Description_Lang_enCN='' WHERE ID=1051;
UPDATE dbc_faction SET Name_Lang_enCN='部落先遣军', Description_Lang_enCN='部落派往诺森德的多支部队的统称，由战歌远征军充当先头部队。' WHERE ID=1052;
UPDATE dbc_faction SET Name_Lang_enCN='Westguard', Description_Lang_enCN='' WHERE ID=1053;
UPDATE dbc_faction SET Name_Lang_enCN='Spotted Gryphon', Description_Lang_enCN='' WHERE ID=1054;
UPDATE dbc_faction SET Name_Lang_enCN='Tamed Plaguehound', Description_Lang_enCN='' WHERE ID=1055;
UPDATE dbc_faction SET Name_Lang_enCN='Vrykul (Ancient Spirit 1)', Description_Lang_enCN='' WHERE ID=1056;
UPDATE dbc_faction SET Name_Lang_enCN='Vrykul (Ancient Siprit 2)', Description_Lang_enCN='' WHERE ID=1057;
UPDATE dbc_faction SET Name_Lang_enCN='Vrykul (Ancient Siprit 3)', Description_Lang_enCN='' WHERE ID=1058;
UPDATE dbc_faction SET Name_Lang_enCN='CTF - Flag - Alliance', Description_Lang_enCN='' WHERE ID=1059;
UPDATE dbc_faction SET Name_Lang_enCN='Test', Description_Lang_enCN='' WHERE ID=1060;
UPDATE dbc_faction SET Name_Lang_enCN='维库人', Description_Lang_enCN='' WHERE ID=1061;
UPDATE dbc_faction SET Name_Lang_enCN='维库角斗士', Description_Lang_enCN='' WHERE ID=1062;
UPDATE dbc_faction SET Name_Lang_enCN='Valgarde Combatant', Description_Lang_enCN='' WHERE ID=1063;
UPDATE dbc_faction SET Name_Lang_enCN='牦牛人', Description_Lang_enCN='这些坚强的牦牛人是牛头人的同类，在部落远征诺森德的战役中，他们成为了具有重要价值的斥候。' WHERE ID=1064;
UPDATE dbc_faction SET Name_Lang_enCN='Monster, Zone Force Reaction 1', Description_Lang_enCN='' WHERE ID=1065;
UPDATE dbc_faction SET Name_Lang_enCN='Monster, Zone Force Reaction 2', Description_Lang_enCN='' WHERE ID=1066;
UPDATE dbc_faction SET Name_Lang_enCN='复仇之手', Description_Lang_enCN='这支由希尔瓦娜斯·风行者派遣的被遗忘者势力想要在诺森德散播他们最新研制成功的瘟疫病菌，以此来向阿尔萨斯复仇。' WHERE ID=1067;
UPDATE dbc_faction SET Name_Lang_enCN='探险者协会', Description_Lang_enCN='这个组织致力于通过发掘泰坦遗留下来的古器追寻矮人种族的起源。最近他们来到诺森德的多处古迹进行研究。' WHERE ID=1068;
UPDATE dbc_faction SET Name_Lang_enCN='Ram Racing Powerup DND', Description_Lang_enCN='' WHERE ID=1069;
UPDATE dbc_faction SET Name_Lang_enCN='Ram Racing Trap DND', Description_Lang_enCN='' WHERE ID=1070;
UPDATE dbc_faction SET Name_Lang_enCN='Craig''s Squirrels', Description_Lang_enCN='A test faction.' WHERE ID=1071;
UPDATE dbc_faction SET Name_Lang_enCN='REUSE', Description_Lang_enCN='' WHERE ID=1072;
UPDATE dbc_faction SET Name_Lang_enCN='卡鲁亚克', Description_Lang_enCN='海象人是坚韧而和平的种族，通过捕鲸和捕鱼谋生。他们的家园最近正在遭受凶猛的攻击，急需来自外界的援手。' WHERE ID=1073;
UPDATE dbc_faction SET Name_Lang_enCN='Holiday - Water Barrel', Description_Lang_enCN='' WHERE ID=1074;
UPDATE dbc_faction SET Name_Lang_enCN='Holiday - Generic', Description_Lang_enCN='' WHERE ID=1075;
UPDATE dbc_faction SET Name_Lang_enCN='铁矮人', Description_Lang_enCN='' WHERE ID=1076;
UPDATE dbc_faction SET Name_Lang_enCN='破碎残阳', Description_Lang_enCN='沙塔斯城的精锐部队，目标是向太阳之井的凯尔萨斯王子发动最终的攻势。' WHERE ID=1077;
UPDATE dbc_faction SET Name_Lang_enCN='战斗宠物', Description_Lang_enCN='' WHERE ID=1078;
UPDATE dbc_faction SET Name_Lang_enCN='冬鳞鱼人', Description_Lang_enCN='' WHERE ID=1079;
UPDATE dbc_faction SET Name_Lang_enCN='Friendly, Force Reaction', Description_Lang_enCN='' WHERE ID=1080;
UPDATE dbc_faction SET Name_Lang_enCN='Object, Force Reaction', Description_Lang_enCN='' WHERE ID=1081;
UPDATE dbc_faction SET Name_Lang_enCN='REUSE', Description_Lang_enCN='' WHERE ID=1082;
UPDATE dbc_faction SET Name_Lang_enCN='REUSE', Description_Lang_enCN='' WHERE ID=1083;
UPDATE dbc_faction SET Name_Lang_enCN='Vrykul, Sea', Description_Lang_enCN='' WHERE ID=1084;
UPDATE dbc_faction SET Name_Lang_enCN='战歌远征军', Description_Lang_enCN='部落的主力部队由加尔鲁什·地狱咆哮率领，向盘踞在诺森德的阿尔萨斯和天灾军团发起挑战。' WHERE ID=1085;
UPDATE dbc_faction SET Name_Lang_enCN='Poacher', Description_Lang_enCN='' WHERE ID=1086;
UPDATE dbc_faction SET Name_Lang_enCN='节日怪物', Description_Lang_enCN='' WHERE ID=1087;
UPDATE dbc_faction SET Name_Lang_enCN='Furbolg, Redfang', Description_Lang_enCN='' WHERE ID=1088;
UPDATE dbc_faction SET Name_Lang_enCN='Furbolg, Frostpaw', Description_Lang_enCN='' WHERE ID=1089;
UPDATE dbc_faction SET Name_Lang_enCN='肯瑞托', Description_Lang_enCN='统治达拉然的法师和大法师们。由于蓝龙军团和亡灵天灾造成的威胁，他们将整座城市传送到了诺森德的腹地。' WHERE ID=1090;
UPDATE dbc_faction SET Name_Lang_enCN='龙眠联军', Description_Lang_enCN='由于蓝龙军团粗暴地干涉凡人种族使用魔法的权利，其余的龙族不得不联合在红龙军团旗下，与这些狂乱的同胞抗衡。' WHERE ID=1091;
UPDATE dbc_faction SET Name_Lang_enCN='艾卓-尼鲁布', Description_Lang_enCN='' WHERE ID=1092;
UPDATE dbc_faction SET Name_Lang_enCN='REUSE', Description_Lang_enCN='' WHERE ID=1093;
UPDATE dbc_faction SET Name_Lang_enCN='银色盟约', Description_Lang_enCN='这支高等精灵中的精锐部队拒绝让血精灵进入肯瑞托。他们联合在温蕾萨·风行者的旗帜下，与诺森德的联盟军队并肩作战。' WHERE ID=1094;
UPDATE dbc_faction SET Name_Lang_enCN='Grizzly Hills Trapper', Description_Lang_enCN='' WHERE ID=1095;
UPDATE dbc_faction SET Name_Lang_enCN='REUSE', Description_Lang_enCN='' WHERE ID=1096;
UPDATE dbc_faction SET Name_Lang_enCN='巫妖王之怒', Description_Lang_enCN='' WHERE ID=1097;
UPDATE dbc_faction SET Name_Lang_enCN='黑锋骑士团', Description_Lang_enCN='在脱离了巫妖王的控制之后，这些曾经效命于他的死亡骑士联合起来，在大领主达里安·莫格莱尼的领导下对抗巫妖王。' WHERE ID=1098;
UPDATE dbc_faction SET Name_Lang_enCN='Wrathgate Scourge', Description_Lang_enCN='' WHERE ID=1099;
UPDATE dbc_faction SET Name_Lang_enCN='Wrathgate Alliance', Description_Lang_enCN='' WHERE ID=1100;
UPDATE dbc_faction SET Name_Lang_enCN='Wrathgate Horde', Description_Lang_enCN='' WHERE ID=1101;
UPDATE dbc_faction SET Name_Lang_enCN='CTF - Flag - Horde', Description_Lang_enCN='' WHERE ID=1102;
UPDATE dbc_faction SET Name_Lang_enCN='CTF - Flag - Neutral', Description_Lang_enCN='' WHERE ID=1103;
UPDATE dbc_faction SET Name_Lang_enCN='狂心氏族', Description_Lang_enCN='这群凶猛的狼獾人被天灾军团追杀，偶然来到了索拉查盆地，遂决定在此安家。由于极富攻击性，他们与被称为神谕者的鳄鱼人部族成水火之势。' WHERE ID=1104;
UPDATE dbc_faction SET Name_Lang_enCN='神谕者', Description_Lang_enCN='索拉查盆地的鳄鱼人将自己视为该区域中存留的泰坦科技的守护者（虽然他们基本不了解这种科技）。目前他们正在与狼獾人进行着不断激化的领土战争。' WHERE ID=1105;
UPDATE dbc_faction SET Name_Lang_enCN='银色北伐军', Description_Lang_enCN='提里奥·弗丁领导的银色北伐军是由白银之手骑士团和银色黎明重组而成的，他们的目标是击溃巫妖王的军队。' WHERE ID=1106;
UPDATE dbc_faction SET Name_Lang_enCN='Troll, Drakkari', Description_Lang_enCN='' WHERE ID=1107;
UPDATE dbc_faction SET Name_Lang_enCN='CoT Arthas', Description_Lang_enCN='' WHERE ID=1108;
UPDATE dbc_faction SET Name_Lang_enCN='CoT Stratholme Citizen', Description_Lang_enCN='' WHERE ID=1109;
UPDATE dbc_faction SET Name_Lang_enCN='CoT Scourge', Description_Lang_enCN='' WHERE ID=1110;
UPDATE dbc_faction SET Name_Lang_enCN='弗蕾亚', Description_Lang_enCN='' WHERE ID=1111;
UPDATE dbc_faction SET Name_Lang_enCN='Mount - Taxi - Alliance', Description_Lang_enCN='' WHERE ID=1112;
UPDATE dbc_faction SET Name_Lang_enCN='Mount - Taxi - Horde', Description_Lang_enCN='' WHERE ID=1113;
UPDATE dbc_faction SET Name_Lang_enCN='Mount - Taxi - Neutral', Description_Lang_enCN='' WHERE ID=1114;
UPDATE dbc_faction SET Name_Lang_enCN='Elemental, Water', Description_Lang_enCN='' WHERE ID=1115;
UPDATE dbc_faction SET Name_Lang_enCN='Elemental, Air', Description_Lang_enCN='' WHERE ID=1116;
UPDATE dbc_faction SET Name_Lang_enCN='索拉查盆地', Description_Lang_enCN='' WHERE ID=1117;
UPDATE dbc_faction SET Name_Lang_enCN='经典旧世', Description_Lang_enCN='' WHERE ID=1118;
UPDATE dbc_faction SET Name_Lang_enCN='霍迪尔之子', Description_Lang_enCN='这支风暴峭壁的冰霜巨人部族非常好战，他们定居在丹尼芬雷。' WHERE ID=1119;
UPDATE dbc_faction SET Name_Lang_enCN='铁巨人', Description_Lang_enCN='' WHERE ID=1120;
UPDATE dbc_faction SET Name_Lang_enCN='冰霜维库人', Description_Lang_enCN='' WHERE ID=1121;
UPDATE dbc_faction SET Name_Lang_enCN='土灵', Description_Lang_enCN='' WHERE ID=1122;
UPDATE dbc_faction SET Name_Lang_enCN='Monster Referee', Description_Lang_enCN='' WHERE ID=1123;
UPDATE dbc_faction SET Name_Lang_enCN='夺日者', Description_Lang_enCN='在大法师艾萨斯·夺日者的努力下，一贯被达拉然据之门外的部落也获准进入这座城市。他的追随者保卫着以他的名字命名的夺日者圣殿。' WHERE ID=1124;
UPDATE dbc_faction SET Name_Lang_enCN='海德比武会', Description_Lang_enCN='' WHERE ID=1125;
UPDATE dbc_faction SET Name_Lang_enCN='霜脉矮人', Description_Lang_enCN='这个神秘的冰霜矮人种族定居在风暴峭壁。他们最近与探险者协会成为了朋友，并且欢迎联盟的成员造访他们的家园。' WHERE ID=1126;
UPDATE dbc_faction SET Name_Lang_enCN='Orgrimmar (Alex Test)', Description_Lang_enCN='' WHERE ID=1127;
UPDATE dbc_faction SET Name_Lang_enCN='塔奎林声望转换', Description_Lang_enCN='' WHERE ID=1136;
UPDATE dbc_faction SET Name_Lang_enCN='霜刃豹声望转换', Description_Lang_enCN='' WHERE ID=1137;
UPDATE dbc_faction SET Name_Lang_enCN='憎世者', Description_Lang_enCN='' WHERE ID=1145;
UPDATE dbc_faction SET Name_Lang_enCN='银色盟约声望转换', Description_Lang_enCN='' WHERE ID=1154;
UPDATE dbc_faction SET Name_Lang_enCN='夺日者声望转换', Description_Lang_enCN='' WHERE ID=1155;
UPDATE dbc_faction SET Name_Lang_enCN='灰烬审判军', Description_Lang_enCN='在提里奥·弗丁与达里安·莫格莱尼的共同协议下，银色北伐军与黑锋骑士团决定暂时放下分歧、统一战线，合力攻入冰冠堡垒，击败巫妖王。' WHERE ID=1156;
UPDATE dbc_faction SET Name_Lang_enCN='CTF - Flag - Alliance 2', Description_Lang_enCN='' WHERE ID=1159;
UPDATE dbc_faction SET Name_Lang_enCN='CTF - Flag - Horde 2', Description_Lang_enCN='' WHERE ID=1160;
