UPDATE dbc_taxinodes SET Name_Lang_enCN='北郡修道院' WHERE ID=1;
UPDATE dbc_taxinodes SET Name_Lang_enCN='暴风城，艾尔文森林' WHERE ID=2;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Programmer Isle' WHERE ID=3;
UPDATE dbc_taxinodes SET Name_Lang_enCN='哨兵岭，西部荒野' WHERE ID=4;
UPDATE dbc_taxinodes SET Name_Lang_enCN='湖畔镇，赤脊山' WHERE ID=5;
UPDATE dbc_taxinodes SET Name_Lang_enCN='铁炉堡，丹莫罗' WHERE ID=6;
UPDATE dbc_taxinodes SET Name_Lang_enCN='米奈希尔港，湿地' WHERE ID=7;
UPDATE dbc_taxinodes SET Name_Lang_enCN='塞尔萨玛，洛克莫丹' WHERE ID=8;
UPDATE dbc_taxinodes SET Name_Lang_enCN='藏宝海湾，荆棘谷' WHERE ID=9;
UPDATE dbc_taxinodes SET Name_Lang_enCN='瑟伯切尔，银松森林' WHERE ID=10;
UPDATE dbc_taxinodes SET Name_Lang_enCN='幽暗城，提瑞斯法林地' WHERE ID=11;
UPDATE dbc_taxinodes SET Name_Lang_enCN='夜色镇，暮色森林' WHERE ID=12;
UPDATE dbc_taxinodes SET Name_Lang_enCN='塔伦米尔，希尔斯布莱德' WHERE ID=13;
UPDATE dbc_taxinodes SET Name_Lang_enCN='南海镇，希尔斯布莱德' WHERE ID=14;
UPDATE dbc_taxinodes SET Name_Lang_enCN='东瘟疫之地' WHERE ID=15;
UPDATE dbc_taxinodes SET Name_Lang_enCN='避难谷地，阿拉希高地' WHERE ID=16;
UPDATE dbc_taxinodes SET Name_Lang_enCN='落锤镇，阿拉希高地' WHERE ID=17;
UPDATE dbc_taxinodes SET Name_Lang_enCN='藏宝海湾，荆棘谷' WHERE ID=18;
UPDATE dbc_taxinodes SET Name_Lang_enCN='藏宝海湾，荆棘谷' WHERE ID=19;
UPDATE dbc_taxinodes SET Name_Lang_enCN='格罗姆高，荆棘谷' WHERE ID=20;
UPDATE dbc_taxinodes SET Name_Lang_enCN='卡加斯，荒芜之地' WHERE ID=21;
UPDATE dbc_taxinodes SET Name_Lang_enCN='雷霆崖，莫高雷' WHERE ID=22;
UPDATE dbc_taxinodes SET Name_Lang_enCN='奥格瑞玛，杜隆塔尔' WHERE ID=23;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Generic, World Target 002' WHERE ID=24;
UPDATE dbc_taxinodes SET Name_Lang_enCN='十字路口，贫瘠之地' WHERE ID=25;
UPDATE dbc_taxinodes SET Name_Lang_enCN='奥伯丁，黑海岸' WHERE ID=26;
UPDATE dbc_taxinodes SET Name_Lang_enCN='鲁瑟兰村，泰达希尔' WHERE ID=27;
UPDATE dbc_taxinodes SET Name_Lang_enCN='阿斯特兰纳，灰谷' WHERE ID=28;
UPDATE dbc_taxinodes SET Name_Lang_enCN='烈日石居，石爪山' WHERE ID=29;
UPDATE dbc_taxinodes SET Name_Lang_enCN='乱风岗 ，千针石林' WHERE ID=30;
UPDATE dbc_taxinodes SET Name_Lang_enCN='萨兰纳尔，千针石林' WHERE ID=31;
UPDATE dbc_taxinodes SET Name_Lang_enCN='塞拉摩，尘泥沼泽' WHERE ID=32;
UPDATE dbc_taxinodes SET Name_Lang_enCN='石爪峰，石爪山' WHERE ID=33;
UPDATE dbc_taxinodes SET Name_Lang_enCN='交通工具，藏宝海湾' WHERE ID=34;
UPDATE dbc_taxinodes SET Name_Lang_enCN='交通工具，奥格瑞玛' WHERE ID=35;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Generic, World Target 001' WHERE ID=36;
UPDATE dbc_taxinodes SET Name_Lang_enCN='尼耶尔前哨站，凄凉之地' WHERE ID=37;
UPDATE dbc_taxinodes SET Name_Lang_enCN='葬影村，凄凉之地' WHERE ID=38;
UPDATE dbc_taxinodes SET Name_Lang_enCN='加基森，塔纳利斯' WHERE ID=39;
UPDATE dbc_taxinodes SET Name_Lang_enCN='加基森，塔纳利斯' WHERE ID=40;
UPDATE dbc_taxinodes SET Name_Lang_enCN='羽月要塞，菲拉斯' WHERE ID=41;
UPDATE dbc_taxinodes SET Name_Lang_enCN='莫沙彻营地，菲拉斯' WHERE ID=42;
UPDATE dbc_taxinodes SET Name_Lang_enCN='鹰巢山，辛特兰' WHERE ID=43;
UPDATE dbc_taxinodes SET Name_Lang_enCN='瓦罗莫克，艾萨拉' WHERE ID=44;
UPDATE dbc_taxinodes SET Name_Lang_enCN='守望堡，诅咒之地' WHERE ID=45;
UPDATE dbc_taxinodes SET Name_Lang_enCN='交通工具，南海镇' WHERE ID=46;
UPDATE dbc_taxinodes SET Name_Lang_enCN='交通工具，格罗姆高' WHERE ID=47;
UPDATE dbc_taxinodes SET Name_Lang_enCN='血毒河，费伍德森林' WHERE ID=48;
UPDATE dbc_taxinodes SET Name_Lang_enCN='月光林地' WHERE ID=49;
UPDATE dbc_taxinodes SET Name_Lang_enCN='交通工具，米奈希尔港' WHERE ID=50;
UPDATE dbc_taxinodes SET Name_Lang_enCN='交通工具，奥伯丁' WHERE ID=51;
UPDATE dbc_taxinodes SET Name_Lang_enCN='永望镇，冬泉谷' WHERE ID=52;
UPDATE dbc_taxinodes SET Name_Lang_enCN='永望镇，冬泉谷' WHERE ID=53;
UPDATE dbc_taxinodes SET Name_Lang_enCN='交通工具，羽月要塞' WHERE ID=54;
UPDATE dbc_taxinodes SET Name_Lang_enCN='蕨墙村，尘泥沼泽' WHERE ID=55;
UPDATE dbc_taxinodes SET Name_Lang_enCN='斯通纳德，悲伤沼泽' WHERE ID=56;
UPDATE dbc_taxinodes SET Name_Lang_enCN='钓鱼村，泰达希尔' WHERE ID=57;
UPDATE dbc_taxinodes SET Name_Lang_enCN='佐拉姆加前哨站，灰谷' WHERE ID=58;
UPDATE dbc_taxinodes SET Name_Lang_enCN='丹巴达尔，奥特兰克山谷' WHERE ID=59;
UPDATE dbc_taxinodes SET Name_Lang_enCN='部落要塞，奥特兰克山谷' WHERE ID=60;
UPDATE dbc_taxinodes SET Name_Lang_enCN='碎木岗哨，灰谷' WHERE ID=61;
UPDATE dbc_taxinodes SET Name_Lang_enCN='永夜港，月光林地' WHERE ID=62;
UPDATE dbc_taxinodes SET Name_Lang_enCN='永夜港，月光林地' WHERE ID=63;
UPDATE dbc_taxinodes SET Name_Lang_enCN='塔伦迪斯营地，艾萨拉' WHERE ID=64;
UPDATE dbc_taxinodes SET Name_Lang_enCN='刺枝林地，费伍德森林' WHERE ID=65;
UPDATE dbc_taxinodes SET Name_Lang_enCN='冰风岗，西瘟疫之地' WHERE ID=66;
UPDATE dbc_taxinodes SET Name_Lang_enCN='圣光之愿礼拜堂，东瘟疫之地' WHERE ID=67;
UPDATE dbc_taxinodes SET Name_Lang_enCN='圣光之愿礼拜堂，东瘟疫之地' WHERE ID=68;
UPDATE dbc_taxinodes SET Name_Lang_enCN='月光林地' WHERE ID=69;
UPDATE dbc_taxinodes SET Name_Lang_enCN='烈焰峰，燃烧平原' WHERE ID=70;
UPDATE dbc_taxinodes SET Name_Lang_enCN='摩根的岗哨，燃烧平原' WHERE ID=71;
UPDATE dbc_taxinodes SET Name_Lang_enCN='塞纳里奥要塞，希利苏斯' WHERE ID=72;
UPDATE dbc_taxinodes SET Name_Lang_enCN='塞纳里奥要塞，希利苏斯' WHERE ID=73;
UPDATE dbc_taxinodes SET Name_Lang_enCN='瑟银哨塔，灼热峡谷' WHERE ID=74;
UPDATE dbc_taxinodes SET Name_Lang_enCN='瑟银哨塔，灼热峡谷' WHERE ID=75;
UPDATE dbc_taxinodes SET Name_Lang_enCN='恶齿村，辛特兰' WHERE ID=76;
UPDATE dbc_taxinodes SET Name_Lang_enCN='陶拉祖营地，贫瘠之地' WHERE ID=77;
UPDATE dbc_taxinodes SET Name_Lang_enCN='纳克萨玛斯' WHERE ID=78;
UPDATE dbc_taxinodes SET Name_Lang_enCN='马绍尔营地，安戈洛环形山' WHERE ID=79;
UPDATE dbc_taxinodes SET Name_Lang_enCN='棘齿城，贫瘠之地' WHERE ID=80;
UPDATE dbc_taxinodes SET Name_Lang_enCN='拍摄' WHERE ID=81;
UPDATE dbc_taxinodes SET Name_Lang_enCN='银月城' WHERE ID=82;
UPDATE dbc_taxinodes SET Name_Lang_enCN='塔奎林，幽魂之地' WHERE ID=83;
UPDATE dbc_taxinodes SET Name_Lang_enCN='病木林哨塔，东瘟疫之地' WHERE ID=84;
UPDATE dbc_taxinodes SET Name_Lang_enCN='北地哨塔，东瘟疫之地' WHERE ID=85;
UPDATE dbc_taxinodes SET Name_Lang_enCN='东墙哨塔，东瘟疫之地' WHERE ID=86;
UPDATE dbc_taxinodes SET Name_Lang_enCN='皇冠哨塔，东瘟疫之地' WHERE ID=87;
UPDATE dbc_taxinodes SET Name_Lang_enCN='交通工具，埃索达' WHERE ID=88;
UPDATE dbc_taxinodes SET Name_Lang_enCN='交通工具，塞拉摩' WHERE ID=89;
UPDATE dbc_taxinodes SET Name_Lang_enCN='交通工具，幽暗城' WHERE ID=90;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Azuremyst Shaman Target' WHERE ID=91;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Azuremyst Shaman Start' WHERE ID=92;
UPDATE dbc_taxinodes SET Name_Lang_enCN='秘血岗哨，秘血岛' WHERE ID=93;
UPDATE dbc_taxinodes SET Name_Lang_enCN='埃索达' WHERE ID=94;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Zangarmarsh - Quest - As the Crow Flies' WHERE ID=95;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Zangarmarsh - Quest - As the Crow Flies - End' WHERE ID=96;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Elekk Path to Kessel' WHERE ID=97;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Elekk to Kessel Target' WHERE ID=98;
UPDATE dbc_taxinodes SET Name_Lang_enCN='萨尔玛，地狱火半岛' WHERE ID=99;
UPDATE dbc_taxinodes SET Name_Lang_enCN='荣耀堡，地狱火半岛' WHERE ID=100;
UPDATE dbc_taxinodes SET Name_Lang_enCN='塔哈玛特神殿，地狱火半岛' WHERE ID=101;
UPDATE dbc_taxinodes SET Name_Lang_enCN='猎鹰岗哨，地狱火半岛' WHERE ID=102;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Nagrand - PvP - Attack Run Start 1' WHERE ID=103;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Nagrand - PvP - Attack Run End 1' WHERE ID=104;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Nagrand - PvP - Attack Run Start 2' WHERE ID=105;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Nagrand - PvP - Attack Run End 2' WHERE ID=106;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Nagrand - PvP - Attack Run Start 3' WHERE ID=107;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Nagrand - PvP - Attack Run End 3' WHERE ID=108;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Nagrand - PvP - Attack Run Start 4' WHERE ID=109;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Nagrand - PvP - Attack Run End 4' WHERE ID=110;
UPDATE dbc_taxinodes SET Name_Lang_enCN='永歌森林 - 达斯维瑟' WHERE ID=111;
UPDATE dbc_taxinodes SET Name_Lang_enCN='永歌森林 - 达斯维瑟' WHERE ID=112;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Nethrandamus Start' WHERE ID=113;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Nethrandamus End Target' WHERE ID=114;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Caverns of Time OH - Begin' WHERE ID=115;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Caverns of Time OH - End' WHERE ID=116;
UPDATE dbc_taxinodes SET Name_Lang_enCN='泰雷多尔，赞加沼泽' WHERE ID=117;
UPDATE dbc_taxinodes SET Name_Lang_enCN='萨布拉金，赞加沼泽' WHERE ID=118;
UPDATE dbc_taxinodes SET Name_Lang_enCN='塔拉，纳格兰' WHERE ID=119;
UPDATE dbc_taxinodes SET Name_Lang_enCN='加拉达尔，纳格兰' WHERE ID=120;
UPDATE dbc_taxinodes SET Name_Lang_enCN='奥蕾莉亚要塞，泰罗卡森林' WHERE ID=121;
UPDATE dbc_taxinodes SET Name_Lang_enCN='52区，虚空风暴' WHERE ID=122;
UPDATE dbc_taxinodes SET Name_Lang_enCN='影月村，影月谷' WHERE ID=123;
UPDATE dbc_taxinodes SET Name_Lang_enCN='蛮锤要塞，影月谷' WHERE ID=124;
UPDATE dbc_taxinodes SET Name_Lang_enCN='希尔瓦纳，刀锋山' WHERE ID=125;
UPDATE dbc_taxinodes SET Name_Lang_enCN='雷神要塞，刀锋山' WHERE ID=126;
UPDATE dbc_taxinodes SET Name_Lang_enCN='裂石堡，泰罗卡森林' WHERE ID=127;
UPDATE dbc_taxinodes SET Name_Lang_enCN='沙塔斯，泰罗卡森林' WHERE ID=128;
UPDATE dbc_taxinodes SET Name_Lang_enCN='地狱火半岛，黑暗之门，联盟' WHERE ID=129;
UPDATE dbc_taxinodes SET Name_Lang_enCN='地狱火半岛，黑暗之门，部落' WHERE ID=130;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Horde Hellfire Start' WHERE ID=131;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Horde Hellfire End' WHERE ID=132;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Hellfire Peninsula (Alliance Path) Start' WHERE ID=133;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Hellfire Peninsula (Alliance) End' WHERE ID=134;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Hellfire, Aerial Mission (Horde) Start' WHERE ID=135;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Hellfire, Aerial Mission (Horde) End' WHERE ID=136;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Hellfire, Aerial Mission (Alliance) Start' WHERE ID=137;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Hellfire, Aerial Mission (Alliance) End' WHERE ID=138;
UPDATE dbc_taxinodes SET Name_Lang_enCN='风暴尖塔，虚空风暴' WHERE ID=139;
UPDATE dbc_taxinodes SET Name_Lang_enCN='沙塔尔祭坛，影月谷' WHERE ID=140;
UPDATE dbc_taxinodes SET Name_Lang_enCN='断背山，地狱火半岛' WHERE ID=141;
UPDATE dbc_taxinodes SET Name_Lang_enCN='地狱火半岛 - 机甲残骸' WHERE ID=142;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Caverns of Time (Intro Flight Path) (End)' WHERE ID=143;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Caverns of Time (Intro Flight Path) (Start)' WHERE ID=144;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Netherstorm - Stealth Flight - Begin' WHERE ID=145;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Netherstorm - Stealth Flight - End' WHERE ID=146;
UPDATE dbc_taxinodes SET Name_Lang_enCN='地狱火半岛 - 前敌营地' WHERE ID=147;
UPDATE dbc_taxinodes SET Name_Lang_enCN='破碎岗哨，地狱火半岛' WHERE ID=148;
UPDATE dbc_taxinodes SET Name_Lang_enCN='破碎岗哨，地狱火半岛' WHERE ID=149;
UPDATE dbc_taxinodes SET Name_Lang_enCN='扳钳镇，虚空风暴' WHERE ID=150;
UPDATE dbc_taxinodes SET Name_Lang_enCN='沼泽鼠岗哨，赞加沼泽' WHERE ID=151;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Netherstorm - Manaforge Ultris (Start)' WHERE ID=152;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Netherstorm - Manaforge Ultris (End)' WHERE ID=153;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Netherstorm - Manaforge Ultris (Second Pass) Start' WHERE ID=154;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Netherstorm - Manaforge Ultris (Second Pass) End' WHERE ID=155;
UPDATE dbc_taxinodes SET Name_Lang_enCN='托什雷的基地，刀锋山' WHERE ID=156;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Blade''s Edge - Vision Guide - Start' WHERE ID=157;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Blade''s Edge - Vision Guide - End' WHERE ID=158;
UPDATE dbc_taxinodes SET Name_Lang_enCN='群星圣殿，影月谷' WHERE ID=159;
UPDATE dbc_taxinodes SET Name_Lang_enCN='常青林，刀锋山' WHERE ID=160;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Nether Dragon Ally - Start' WHERE ID=161;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Nether Dragon Ally - End' WHERE ID=162;
UPDATE dbc_taxinodes SET Name_Lang_enCN='莫克纳萨村，刀锋山' WHERE ID=163;
UPDATE dbc_taxinodes SET Name_Lang_enCN='奥雷柏尔营地，赞加沼泽' WHERE ID=164;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport, Northrend 2' WHERE ID=165;
UPDATE dbc_taxinodes SET Name_Lang_enCN='翡翠圣地，费伍德森林' WHERE ID=166;
UPDATE dbc_taxinodes SET Name_Lang_enCN='林歌神殿，灰谷' WHERE ID=167;
UPDATE dbc_taxinodes SET Name_Lang_enCN='拍摄' WHERE ID=168;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Netherwing Ledge - Mine Cart Ride - South - Start' WHERE ID=169;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Netherwing Ledge - Mine Cart Ride - South - End' WHERE ID=170;
UPDATE dbc_taxinodes SET Name_Lang_enCN='斯克提斯' WHERE ID=171;
UPDATE dbc_taxinodes SET Name_Lang_enCN='奥格瑞拉' WHERE ID=172;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Yarzill Flight Start' WHERE ID=173;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Yarzill Flight Start End' WHERE ID=174;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport, Howling Fjord' WHERE ID=175;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Howling Fjord Tauren Canoe (Start)' WHERE ID=176;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Howling Fjord Tauren Canoe (End)' WHERE ID=177;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport, Borean Tundra' WHERE ID=178;
UPDATE dbc_taxinodes SET Name_Lang_enCN='泥链镇，尘泥沼泽' WHERE ID=179;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Dustwallow - Alcaz Survey Start' WHERE ID=180;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Dustwallow - Alcaz Survey End' WHERE ID=181;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Howling Fjord - Break the Blockade Zeppelin' WHERE ID=182;
UPDATE dbc_taxinodes SET Name_Lang_enCN='瓦加德港口，嚎风峡湾' WHERE ID=183;
UPDATE dbc_taxinodes SET Name_Lang_enCN='维德瓦堡垒，嚎风峡湾' WHERE ID=184;
UPDATE dbc_taxinodes SET Name_Lang_enCN='西部卫戍要塞，嚎风峡湾' WHERE ID=185;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Howling Fjord - Flight to the Windrunner - Start' WHERE ID=186;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Howling Fjord - Flight to the Windrunner - End' WHERE ID=187;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Howling Fjord - Test at Sea - Start' WHERE ID=188;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Howling Fjord - Test at Sea - End' WHERE ID=189;
UPDATE dbc_taxinodes SET Name_Lang_enCN='新阿加曼德，嚎风峡湾' WHERE ID=190;
UPDATE dbc_taxinodes SET Name_Lang_enCN='复仇港，嚎风峡湾' WHERE ID=191;
UPDATE dbc_taxinodes SET Name_Lang_enCN='冬蹄营地，嚎风峡湾' WHERE ID=192;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Howling Fjord - Mission: Plague This! - End' WHERE ID=193;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Howling Fjord - Mission: Plague This! - Start' WHERE ID=194;
UPDATE dbc_taxinodes SET Name_Lang_enCN='反抗军营地，荆棘谷' WHERE ID=195;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Test - SP' WHERE ID=196;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Test SP2' WHERE ID=197;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Test SP1' WHERE ID=198;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Howling Fjord - McGoyver Start' WHERE ID=199;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Howling Fjord - McGoyver End' WHERE ID=200;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Development Land - Kyle Radue Start' WHERE ID=201;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Development Land - Kyle Radue End' WHERE ID=202;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Stars'' Rest -> Wintergarde' WHERE ID=203;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - New Agamand -> Venomspite' WHERE ID=204;
UPDATE dbc_taxinodes SET Name_Lang_enCN='祖阿曼，幽魂之地' WHERE ID=205;
UPDATE dbc_taxinodes SET Name_Lang_enCN='运输，羽月要塞' WHERE ID=206;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Howling Fjord - Sister Mercy (Start)' WHERE ID=207;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Howling Fjord - Sister Mercy (End)' WHERE ID=208;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Sunwell Daily - Dead Scar Bombing - Start' WHERE ID=209;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Sunwell Daily - Dead Scar Bombing - End' WHERE ID=210;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Sunwell Daily - Ship Bombing - Start' WHERE ID=211;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Sunwell Daily - Ship Bombing - End' WHERE ID=212;
UPDATE dbc_taxinodes SET Name_Lang_enCN='破碎残阳基地' WHERE ID=213;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Howling Fjord - Naglfar (Start)' WHERE ID=214;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Howling Fjord - Naglfar (Nodes)' WHERE ID=215;
UPDATE dbc_taxinodes SET Name_Lang_enCN='' WHERE ID=216;
UPDATE dbc_taxinodes SET Name_Lang_enCN='' WHERE ID=217;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport, Howling Fjord (Gondola, Top)' WHERE ID=218;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport, Howling Fjord (Gondola, Bottom)' WHERE ID=219;
UPDATE dbc_taxinodes SET Name_Lang_enCN='' WHERE ID=220;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Amber Ledge, Borean (To Beryl)' WHERE ID=221;
UPDATE dbc_taxinodes SET Name_Lang_enCN='蓝玉营地，北风苔原' WHERE ID=222;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Naglevar' WHERE ID=223;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Borean Tundra, Naglevar' WHERE ID=224;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Amber Ledge, Borean (to Coldarra)' WHERE ID=225;
UPDATE dbc_taxinodes SET Name_Lang_enCN='永生之盾，考达拉' WHERE ID=226;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport, PattyMacDevTest' WHERE ID=227;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Development Land - Pat Test Start' WHERE ID=228;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Development Land - Pat Test End' WHERE ID=229;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport, Tuskarr 01' WHERE ID=230;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport, Tuskarr 02' WHERE ID=231;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Borean Tundra - Warsong Hold Wolf Start' WHERE ID=232;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Borean Tundra - Warsong Hold Wolf End' WHERE ID=233;
UPDATE dbc_taxinodes SET Name_Lang_enCN='考达拉台地，考达拉' WHERE ID=234;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transitus Shield, Coldarra (NOT USED)' WHERE ID=235;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Coldarra, Keristrasza to Malygos' WHERE ID=236;
UPDATE dbc_taxinodes SET Name_Lang_enCN='考达拉，克莉斯塔萨平台' WHERE ID=237;
UPDATE dbc_taxinodes SET Name_Lang_enCN='' WHERE ID=238;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Borean Tundra - Quest - Dusk Start' WHERE ID=239;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Borean Tundra - Quest - Dusk - End' WHERE ID=240;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport, Valiance Keep' WHERE ID=241;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Dragonblight - Spiritual Vision - Begin' WHERE ID=242;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Dragonblight - Spiritual Vision - End' WHERE ID=243;
UPDATE dbc_taxinodes SET Name_Lang_enCN='暮冬要塞，龙骨荒野' WHERE ID=244;
UPDATE dbc_taxinodes SET Name_Lang_enCN='无畏要塞，北风苔原' WHERE ID=245;
UPDATE dbc_taxinodes SET Name_Lang_enCN='菲兹兰克机场，北风苔原' WHERE ID=246;
UPDATE dbc_taxinodes SET Name_Lang_enCN='群星之墓，龙骨荒野' WHERE ID=247;
UPDATE dbc_taxinodes SET Name_Lang_enCN='药剂师营地，嚎风峡湾' WHERE ID=248;
UPDATE dbc_taxinodes SET Name_Lang_enCN='欧尼瓦营地，灰熊丘陵' WHERE ID=249;
UPDATE dbc_taxinodes SET Name_Lang_enCN='征服堡，灰熊丘陵' WHERE ID=250;
UPDATE dbc_taxinodes SET Name_Lang_enCN='弗塔根要塞，龙骨荒野' WHERE ID=251;
UPDATE dbc_taxinodes SET Name_Lang_enCN='龙眠神殿，龙骨荒野' WHERE ID=252;
UPDATE dbc_taxinodes SET Name_Lang_enCN='琥珀松木营地，灰熊丘陵' WHERE ID=253;
UPDATE dbc_taxinodes SET Name_Lang_enCN='怨毒镇，龙骨荒野' WHERE ID=254;
UPDATE dbc_taxinodes SET Name_Lang_enCN='月溪旅，灰熊丘陵' WHERE ID=255;
UPDATE dbc_taxinodes SET Name_Lang_enCN='阿格玛之锤，龙骨荒野' WHERE ID=256;
UPDATE dbc_taxinodes SET Name_Lang_enCN='战歌要塞，北风苔原' WHERE ID=257;
UPDATE dbc_taxinodes SET Name_Lang_enCN='牦牛村，北风苔原' WHERE ID=258;
UPDATE dbc_taxinodes SET Name_Lang_enCN='博古洛克前哨站，北风苔原' WHERE ID=259;
UPDATE dbc_taxinodes SET Name_Lang_enCN='库卡隆先锋营地，龙骨荒野' WHERE ID=260;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Stars'' Rest to Wintergarde End' WHERE ID=261;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Grizzly Hills, Alliance Log Ride Start 01' WHERE ID=262;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Grizzly Hills, Alliance Log Ride End 01' WHERE ID=263;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport, Auberdine (NEW)' WHERE ID=264;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport, Theramore (NEW)' WHERE ID=265;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport, Menethil (NEW)' WHERE ID=266;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Grizzly Hills, Alliance Log Ride Start' WHERE ID=267;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Grizzly Hills, Alliance Log Ride End' WHERE ID=268;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Westguard Keep to Wintergarde Keep Begin' WHERE ID=269;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Westguard Keep to Wintergarde Keep End' WHERE ID=270;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Grizzly Hills, Horde Log Ride Start' WHERE ID=271;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Grizzly Hills, Horde Log Ride End' WHERE ID=272;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Wyrmrest Temple - bottom to top, Dragonblight - Begin' WHERE ID=273;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Wyrmrest Temple - bottom to top, Dragonblight - End' WHERE ID=274;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Wyrmrest Temple - top to bottom, Dragonblight - Begin' WHERE ID=275;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Wyrmrest Temple - top to bottom, Dragonblight - End' WHERE ID=276;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Wyrmrest Temple - top to middle, Dragonblight - Begin' WHERE ID=277;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Wyrmrest Temple - top to middle, Dragonblight - End' WHERE ID=278;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Wyrmrest Temple - middle to top, Dragonblight - End' WHERE ID=279;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Wyrmrest Temple - middle to top, Dragonblight - Begin' WHERE ID=280;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Wyrmrest Temple - middle to bottom, Dragonblight - End' WHERE ID=281;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Wyrmrest Temple - middle to bottom, Dragonblight - Begin' WHERE ID=282;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Wyrmrest Temple - bottom to middle, Dragonblight - End' WHERE ID=283;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Wyrmrest Temple - bottom to middle, Dragonblight - Begin' WHERE ID=284;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Wintergarde -> Stars'' Rest (Start)' WHERE ID=285;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Wintergarde -> Stars'' Rest (End)' WHERE ID=286;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Valgarde -> Westguard Keep Start' WHERE ID=287;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Valgarde -> Westguard Keep End' WHERE ID=288;
UPDATE dbc_taxinodes SET Name_Lang_enCN='琥珀崖，北风苔原' WHERE ID=289;
UPDATE dbc_taxinodes SET Name_Lang_enCN='银色前沿，祖达克' WHERE ID=290;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Ruined City Post 01, Zul''Drak' WHERE ID=291;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Flavor - Stormwind Harbor  - Start' WHERE ID=292;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Flavor - Stormwind Harbor - Stop' WHERE ID=293;
UPDATE dbc_taxinodes SET Name_Lang_enCN='莫亚基，龙骨荒野' WHERE ID=294;
UPDATE dbc_taxinodes SET Name_Lang_enCN='卡玛古，嚎风峡湾' WHERE ID=295;
UPDATE dbc_taxinodes SET Name_Lang_enCN='乌努比，北风苔原' WHERE ID=296;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Sholazar Basin - Quest - Reconnaisance - Start' WHERE ID=297;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Sholazar Basin - Quest - Reconnaisance - End' WHERE ID=298;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport: Menethil <-> Valgarde' WHERE ID=299;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport, Stormwind' WHERE ID=300;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Borean Tundra - Check In With Bixie - Begin' WHERE ID=301;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Borean Tundra - Check In With Bixie - End' WHERE ID=302;
UPDATE dbc_taxinodes SET Name_Lang_enCN='无畏远征军营地，冬拥湖' WHERE ID=303;
UPDATE dbc_taxinodes SET Name_Lang_enCN='银色前沿，祖达克' WHERE ID=304;
UPDATE dbc_taxinodes SET Name_Lang_enCN='黑锋哨站，祖达克' WHERE ID=305;
UPDATE dbc_taxinodes SET Name_Lang_enCN='圣光据点，祖达克' WHERE ID=306;
UPDATE dbc_taxinodes SET Name_Lang_enCN='希姆托加，祖达克' WHERE ID=307;
UPDATE dbc_taxinodes SET Name_Lang_enCN='河流之心，索拉查盆地' WHERE ID=308;
UPDATE dbc_taxinodes SET Name_Lang_enCN='奈辛瓦里营地，索拉查盆地' WHERE ID=309;
UPDATE dbc_taxinodes SET Name_Lang_enCN='达拉然' WHERE ID=310;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Camp Onequah, Grizzly Hills (Quest)' WHERE ID=311;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Light''s Breach, Zul''Drak (Quest)' WHERE ID=312;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Westfall Brigade, Grizzly Hills (Quest)' WHERE ID=313;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Zim''Torga, Zul''Drak (Quest)' WHERE ID=314;
UPDATE dbc_taxinodes SET Name_Lang_enCN='阿彻鲁斯：黑锋要塞' WHERE ID=315;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Ebon Hold - Acherus -> Death''s Breach Start' WHERE ID=316;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Ebon Hold - Acherus -> Death''s Breach End' WHERE ID=317;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Ebon Hold - Death''s Breach -> Acherus Start' WHERE ID=318;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Ebon Hold - Death''s Breach -> Acherus End' WHERE ID=319;
UPDATE dbc_taxinodes SET Name_Lang_enCN='K3，风暴峭壁' WHERE ID=320;
UPDATE dbc_taxinodes SET Name_Lang_enCN='冰霜堡，风暴峭壁' WHERE ID=321;
UPDATE dbc_taxinodes SET Name_Lang_enCN='丹尼芬雷，风暴峭壁' WHERE ID=322;
UPDATE dbc_taxinodes SET Name_Lang_enCN='格罗玛什坠毁点，风暴峭壁' WHERE ID=323;
UPDATE dbc_taxinodes SET Name_Lang_enCN='唐卡洛营地，风暴峭壁' WHERE ID=324;
UPDATE dbc_taxinodes SET Name_Lang_enCN='死亡高地，冰冠冰川' WHERE ID=325;
UPDATE dbc_taxinodes SET Name_Lang_enCN='奥杜尔，风暴峭壁' WHERE ID=326;
UPDATE dbc_taxinodes SET Name_Lang_enCN='布德克拉格庇护所，风暴峭壁' WHERE ID=327;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport, Icecrown Airship (A)' WHERE ID=328;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport, Icecrown Airship (H)' WHERE ID=329;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport, Icecrown (Target)' WHERE ID=330;
UPDATE dbc_taxinodes SET Name_Lang_enCN='古达克，祖达克' WHERE ID=331;
UPDATE dbc_taxinodes SET Name_Lang_enCN='战歌营地，冬拥湖' WHERE ID=332;
UPDATE dbc_taxinodes SET Name_Lang_enCN='暗影拱顶，冰冠冰川' WHERE ID=333;
UPDATE dbc_taxinodes SET Name_Lang_enCN='银色前线基地，冰冠冰川' WHERE ID=334;
UPDATE dbc_taxinodes SET Name_Lang_enCN='北伐军之峰，冰冠冰川' WHERE ID=335;
UPDATE dbc_taxinodes SET Name_Lang_enCN='风行者观察站，晶歌森林' WHERE ID=336;
UPDATE dbc_taxinodes SET Name_Lang_enCN='夺日者指挥站，晶歌森林' WHERE ID=337;
UPDATE dbc_taxinodes SET Name_Lang_enCN='银色比武场，冰冠冰川' WHERE ID=340;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Ulduar Raid - Interior - Insertion Point' WHERE ID=341;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Ulduar Raid - Iron Concourse' WHERE ID=342;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Transport: Thunder Bluff <-> Org (Zep)' WHERE ID=348;
UPDATE dbc_taxinodes SET Name_Lang_enCN='征服之岛 - 炮艇' WHERE ID=352;
UPDATE dbc_taxinodes SET Name_Lang_enCN='' WHERE ID=353;
UPDATE dbc_taxinodes SET Name_Lang_enCN='' WHERE ID=357;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Icecrown - North Sea Kraken Bombing - Start' WHERE ID=358;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest - Icecrown - North Sea Kraken Bombing - End' WHERE ID=359;
UPDATE dbc_taxinodes SET Name_Lang_enCN='REUSEME' WHERE ID=375;
UPDATE dbc_taxinodes SET Name_Lang_enCN='AAAIcecrown Raid - Airship Battle Taxi Paths' WHERE ID=376;
UPDATE dbc_taxinodes SET Name_Lang_enCN='冰冠堡垒副本 - 炮艇' WHERE ID=377;
UPDATE dbc_taxinodes SET Name_Lang_enCN='AAAAIcecrown Raid - Saurfang''s Ship (End)' WHERE ID=379;
UPDATE dbc_taxinodes SET Name_Lang_enCN='AAAAIcecrown Raid - Saurfang''s Ship (Start)' WHERE ID=380;
UPDATE dbc_taxinodes SET Name_Lang_enCN='AAAAQuest [Transport] Icecrown Raid - Saurfang Ship (START)' WHERE ID=381;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Quest [Transport] Icecrown Raid - Saurfang Ship (END)' WHERE ID=382;
UPDATE dbc_taxinodes SET Name_Lang_enCN='索多里尔河，西瘟疫之地' WHERE ID=383;
UPDATE dbc_taxinodes SET Name_Lang_enCN='亡灵壁垒，提瑞斯法' WHERE ID=384;
UPDATE dbc_taxinodes SET Name_Lang_enCN='CC Prologue - GT - Quest - Vent Horizon - Start' WHERE ID=392;
UPDATE dbc_taxinodes SET Name_Lang_enCN='CC Prologue - GT - Quest - Vent Horizon - End' WHERE ID=393;
UPDATE dbc_taxinodes SET Name_Lang_enCN='CC Prologue - GT - Battle Flight - Start' WHERE ID=394;
UPDATE dbc_taxinodes SET Name_Lang_enCN='CC Prologue - GT - Battle Flight - End' WHERE ID=395;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Durotar - ET - CC Prologue Spy Frog Start' WHERE ID=404;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Durotar - ET - CC Prologue Spy Frog End' WHERE ID=405;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Durotar - ET - CC Prologue Troll Taxi Bat Start' WHERE ID=438;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Durotar - ET - CC Prologue Troll Recruit End' WHERE ID=439;
UPDATE dbc_taxinodes SET Name_Lang_enCN='Durotar - ET - CC Prologue - Troll Battle End' WHERE ID=440;
