UPDATE dbc_skillline SET DisplayName_Lang_enCN='冰霜', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=6;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='火焰', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=8;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='武器', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=26;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='战斗', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=38;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='敏锐', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=39;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='单手剑', Description_Lang_enCN='武器技能越高，用该武器击中敌人的几率就越高。', AlternateVerb_Lang_enCN='' WHERE ID=43;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='单手斧', Description_Lang_enCN='武器技能越高，用该武器击中敌人的几率就越高。', AlternateVerb_Lang_enCN='' WHERE ID=44;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='弓', Description_Lang_enCN='武器技能越高，用该武器击中敌人的几率就越高。', AlternateVerb_Lang_enCN='' WHERE ID=45;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='枪械', Description_Lang_enCN='武器技能越高，用该武器击中敌人的几率就越高。', AlternateVerb_Lang_enCN='' WHERE ID=46;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='野兽控制', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=50;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='生存技能', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=51;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='单手锤', Description_Lang_enCN='武器技能越高，用该武器击中敌人的几率就越高。', AlternateVerb_Lang_enCN='' WHERE ID=54;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='双手剑', Description_Lang_enCN='武器技能越高，用该武器击中敌人的几率就越高。', AlternateVerb_Lang_enCN='' WHERE ID=55;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='神圣', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=56;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='暗影魔法', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=78;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='防御', Description_Lang_enCN='防御越高，你躲闪、招架和格挡攻击的几率就越高，因此越难以被击中，怪物对你造成爆击的几率也越低。', AlternateVerb_Lang_enCN='' WHERE ID=95;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='语言：通用语', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=98;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='矮人种族特长', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=101;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='语言：兽人语', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=109;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='语言：矮人语', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=111;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='语言：达纳苏斯语', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=113;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='语言：牛头人语', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=115;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='双武器', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=118;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='牛头人种族特长', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=124;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='兽人种族特长', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=125;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='暗夜精灵种族特长', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=126;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='急救', Description_Lang_enCN='高级的急救技能使你可以学习高级的急救能力。你可以在训练师那里学习新的能力，也可以通过完成任务或杀死怪物获得新的能力。', AlternateVerb_Lang_enCN='' WHERE ID=129;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='野性战斗', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=134;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='法杖', Description_Lang_enCN='武器技能越高，用该武器击中敌人的几率就越高。', AlternateVerb_Lang_enCN='' WHERE ID=136;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='语言：萨拉斯语', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=137;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='语言：龙语', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=138;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='语言：恶魔语', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=139;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='语言：泰坦语', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=140;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='语言：古代语', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=141;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='生存技能', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=142;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='骑术：马', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=148;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='骑术：狼', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=149;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='骑术：豹', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=150;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='骑术：羊', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=152;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='游泳', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=155;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='双手锤', Description_Lang_enCN='武器技能越高，用该武器击中敌人的几率就越高。', AlternateVerb_Lang_enCN='' WHERE ID=160;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='徒手战斗', Description_Lang_enCN='此技能等级越高，你击中目标的几率越高。', AlternateVerb_Lang_enCN='' WHERE ID=162;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='射击', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=163;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='锻造', Description_Lang_enCN='高级的锻造技能使你可以学习高级的锻造设计图。你可以在训练师那里学习新的设计图，也可以通过完成任务或杀死怪物获得新的设计图。', AlternateVerb_Lang_enCN='修改' WHERE ID=164;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='制皮', Description_Lang_enCN='高级的制皮技能使你可以学习高级的制皮图样。你可以在训练师那里学习新的图样，也可以通过完成任务或杀死怪物获得新的图样。', AlternateVerb_Lang_enCN='雕饰' WHERE ID=165;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='炼金术', Description_Lang_enCN='高级的炼金术技能使你可以学习高级的炼金术配方。你可以在训练师那里学习新的配方，也可以通过完成任务或杀死怪物获得新的配方。', AlternateVerb_Lang_enCN='装填' WHERE ID=171;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='双手斧', Description_Lang_enCN='武器技能越高，用该武器击中敌人的几率就越高。', AlternateVerb_Lang_enCN='' WHERE ID=172;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='匕首', Description_Lang_enCN='武器技能越高，用该武器击中敌人的几率就越高。', AlternateVerb_Lang_enCN='' WHERE ID=173;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='投掷武器', Description_Lang_enCN='武器技能越高，用该武器击中敌人的几率就越高。', AlternateVerb_Lang_enCN='' WHERE ID=176;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='草药学', Description_Lang_enCN='高级的草药学技能使你可以采集高级的草药。如果你不能采集某种草药，请先在较低等级的地区采集低等级草药，以此提高你的草药学技能。', AlternateVerb_Lang_enCN='' WHERE ID=182;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='GENERIC (DND)', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=183;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='惩戒', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=184;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='烹饪', Description_Lang_enCN='高级的烹饪技能使你可以学习高级的菜谱。你可以在训练师那里学习新的菜谱，也可以通过完成任务或杀死怪物获得新的菜谱。', AlternateVerb_Lang_enCN='' WHERE ID=185;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='采矿', Description_Lang_enCN='高级的采矿技能使你可以采集高级的矿石。如果你不能采集某种矿石，请先在较低等级的地区采集低等级矿石，以此提高你的采矿技能。', AlternateVerb_Lang_enCN='' WHERE ID=186;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 小鬼', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=188;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 地狱猎犬', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=189;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='裁缝', Description_Lang_enCN='高级的裁缝技能使你可以学习高级的裁缝图样。你可以在训练师那里学习新的图样，也可以通过完成任务或杀死怪物获得新的图样。', AlternateVerb_Lang_enCN='刺绣' WHERE ID=197;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='工程学', Description_Lang_enCN='高级的工程学技能使你可以学习高级的工程学图纸。你可以在训练师那里学习新的图纸，也可以通过完成任务或杀死怪物获得新的图纸。', AlternateVerb_Lang_enCN='制造' WHERE ID=202;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 蜘蛛', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=203;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 虚空行者', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=204;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 魅魔', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=205;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 地狱火', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=206;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 末日守卫', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=207;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 狼', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=208;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 豹', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=209;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 熊', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=210;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 野猪', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=211;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 鳄鱼', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=212;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 食腐鸟', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=213;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 螃蟹', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=214;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 猩猩', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=215;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 迅猛龙', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=217;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 陆行鸟', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=218;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='亡灵种族特长', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=220;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='弩', Description_Lang_enCN='武器技能越高，用该武器击中敌人的几率就越高。', AlternateVerb_Lang_enCN='' WHERE ID=226;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='魔杖', Description_Lang_enCN='武器技能越高，用该武器击中敌人的几率就越高。', AlternateVerb_Lang_enCN='' WHERE ID=228;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='长柄武器', Description_Lang_enCN='武器技能越高，用该武器击中敌人的几率就越高。', AlternateVerb_Lang_enCN='' WHERE ID=229;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 蝎子', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=236;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='奥术', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=237;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 海龟', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=251;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='刺杀', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=253;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='狂怒', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=256;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='防护', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=257;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='防护', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=267;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 猎人宠物', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=270;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='板甲', Description_Lang_enCN='使你可以穿板甲。', AlternateVerb_Lang_enCN='' WHERE ID=293;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='语言：侏儒语', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=313;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='语言：巨魔语', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=315;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='附魔', Description_Lang_enCN='高级的附魔技能使你可以学习高级的附魔公式。你可以在训练师那里学习新的公式，也可以通过完成任务或杀死怪物获得新的公式。', AlternateVerb_Lang_enCN='附魔' WHERE ID=333;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='恶魔学识', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=354;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='痛苦', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=355;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='钓鱼', Description_Lang_enCN='高级的钓鱼技能使你可以钓到高级的鱼。如果你在某个区域钓不到鱼，请到低等级区域去钓鱼，或者购买鱼饵再来尝试。', AlternateVerb_Lang_enCN='' WHERE ID=356;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='增强', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=373;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='恢复', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=374;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='元素战斗', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=375;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='剥皮', Description_Lang_enCN='高级的剥皮技能使你可以从高级怪物身上剥取毛皮。如果你的剥皮技能大于100，那么你可剥皮的怪物的最高等级是你的剥皮技能点数除以5。', AlternateVerb_Lang_enCN='' WHERE ID=393;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='锁甲', Description_Lang_enCN='使你可以穿锁甲。', AlternateVerb_Lang_enCN='' WHERE ID=413;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='皮甲', Description_Lang_enCN='使你可以穿皮甲。', AlternateVerb_Lang_enCN='' WHERE ID=414;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='布甲', Description_Lang_enCN='使你可以穿布甲。', AlternateVerb_Lang_enCN='' WHERE ID=415;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='盾牌', Description_Lang_enCN='学会使用盾牌。', AlternateVerb_Lang_enCN='' WHERE ID=433;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='拳套', Description_Lang_enCN='学会使用拳套作战。击中敌人的几率取决于徒手战斗能力的熟练程度。', AlternateVerb_Lang_enCN='' WHERE ID=473;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='骑术：迅猛龙', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=533;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='骑术：机械陆行鸟', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=553;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='骑术：骸骨战马', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=554;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='恢复', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=573;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='平衡', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=574;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='毁灭', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=593;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='神圣', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=594;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='戒律', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=613;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='开锁', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=633;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 蝙蝠', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=653;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 土狼', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=654;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 猛禽', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=655;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 风蛇', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=656;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='语言：亡灵语', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=673;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='骑术：科多兽', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=713;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='种族特长 - 巨魔', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=733;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='种族特长 - 侏儒', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=753;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='种族特长 - 人类', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=754;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='珠宝加工', Description_Lang_enCN='高级的珠宝加工技能使你可以学习高级的珠宝加工图鉴。你可以在训练师那里学习新的图鉴，也可以通过完成任务或杀死怪物获得新的图鉴。', AlternateVerb_Lang_enCN='修改' WHERE ID=755;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='血精灵种族特长', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=756;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='Pet - Event - Remote Control', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=758;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='语言：德莱尼语', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=759;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='德莱尼种族特长', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=760;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 恶魔卫士', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=761;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='骑术', Description_Lang_enCN='高级的骑术令你可以骑乘更加快速和稀有的野兽。', AlternateVerb_Lang_enCN='' WHERE ID=762;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 龙鹰', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=763;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 虚空鳐', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=764;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 孢子蝠', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=765;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 迁跃跟踪者', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=766;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 掠食者', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=767;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 蛇', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=768;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='内部', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=769;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='鲜血', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=770;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='冰霜', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=771;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='邪恶', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=772;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='铭文', Description_Lang_enCN='高级的铭文技能使你可以学习制作高级的铭文。你可以通过各种卷轴学习铭文。', AlternateVerb_Lang_enCN='铭文' WHERE ID=773;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 蛾子', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=775;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='符文熔铸', Description_Lang_enCN='', AlternateVerb_Lang_enCN='铭刻' WHERE ID=776;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='坐骑', Description_Lang_enCN='你的坐骑。', AlternateVerb_Lang_enCN='' WHERE ID=777;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='小伙伴', Description_Lang_enCN='你的小伙伴。', AlternateVerb_Lang_enCN='' WHERE ID=778;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 奇美拉（特殊）', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=780;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 魔暴龙（特殊）', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=781;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 食尸鬼', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=782;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 异种虫（特殊）', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=783;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 蠕虫（特殊）', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=784;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 巨蜂', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=785;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 犀牛（特殊）', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=786;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 熔火犬（特殊）', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=787;
UPDATE dbc_skillline SET DisplayName_Lang_enCN='宠物 - 灵魂兽（特殊）', Description_Lang_enCN='', AlternateVerb_Lang_enCN='' WHERE ID=788;
