UPDATE dbc_chartitles SET Name_Lang_enCN='列兵 %s', Name1_Lang_enCN='列兵 %s' WHERE ID=1;
UPDATE dbc_chartitles SET Name_Lang_enCN='下士 %s', Name1_Lang_enCN='下士 %s' WHERE ID=2;
UPDATE dbc_chartitles SET Name_Lang_enCN='中士 %s', Name1_Lang_enCN='中士 %s' WHERE ID=3;
UPDATE dbc_chartitles SET Name_Lang_enCN='军士长 %s', Name1_Lang_enCN='军士长 %s' WHERE ID=4;
UPDATE dbc_chartitles SET Name_Lang_enCN='士官长 %s', Name1_Lang_enCN='士官长 %s' WHERE ID=5;
UPDATE dbc_chartitles SET Name_Lang_enCN='骑士 %s', Name1_Lang_enCN='骑士 %s' WHERE ID=6;
UPDATE dbc_chartitles SET Name_Lang_enCN='骑士中尉 %s', Name1_Lang_enCN='骑士中尉 %s' WHERE ID=7;
UPDATE dbc_chartitles SET Name_Lang_enCN='骑士队长 %s', Name1_Lang_enCN='骑士队长 %s' WHERE ID=8;
UPDATE dbc_chartitles SET Name_Lang_enCN='护卫骑士 %s', Name1_Lang_enCN='护卫骑士 %s' WHERE ID=9;
UPDATE dbc_chartitles SET Name_Lang_enCN='少校 %s', Name1_Lang_enCN='少校 %s' WHERE ID=10;
UPDATE dbc_chartitles SET Name_Lang_enCN='司令 %s', Name1_Lang_enCN='司令 %s' WHERE ID=11;
UPDATE dbc_chartitles SET Name_Lang_enCN='统帅 %s', Name1_Lang_enCN='统帅 %s' WHERE ID=12;
UPDATE dbc_chartitles SET Name_Lang_enCN='元帅 %s', Name1_Lang_enCN='元帅 %s' WHERE ID=13;
UPDATE dbc_chartitles SET Name_Lang_enCN='大元帅 %s', Name1_Lang_enCN='大元帅 %s' WHERE ID=14;
UPDATE dbc_chartitles SET Name_Lang_enCN='斥候 %s', Name1_Lang_enCN='斥候 %s' WHERE ID=15;
UPDATE dbc_chartitles SET Name_Lang_enCN='步兵 %s', Name1_Lang_enCN='步兵 %s' WHERE ID=16;
UPDATE dbc_chartitles SET Name_Lang_enCN='中士 %s', Name1_Lang_enCN='中士 %s' WHERE ID=17;
UPDATE dbc_chartitles SET Name_Lang_enCN='高阶军士 %s', Name1_Lang_enCN='高阶军士 %s' WHERE ID=18;
UPDATE dbc_chartitles SET Name_Lang_enCN='一等军士长 %s', Name1_Lang_enCN='一等军士长 %s' WHERE ID=19;
UPDATE dbc_chartitles SET Name_Lang_enCN='石头守卫 %s', Name1_Lang_enCN='石头守卫 %s' WHERE ID=20;
UPDATE dbc_chartitles SET Name_Lang_enCN='血卫士 %s', Name1_Lang_enCN='血卫士 %s' WHERE ID=21;
UPDATE dbc_chartitles SET Name_Lang_enCN='军团士兵 %s', Name1_Lang_enCN='军团士兵 %s' WHERE ID=22;
UPDATE dbc_chartitles SET Name_Lang_enCN='百夫长 %s', Name1_Lang_enCN='百夫长 %s' WHERE ID=23;
UPDATE dbc_chartitles SET Name_Lang_enCN='勇士 %s', Name1_Lang_enCN='勇士 %s' WHERE ID=24;
UPDATE dbc_chartitles SET Name_Lang_enCN='中将 %s', Name1_Lang_enCN='中将 %s' WHERE ID=25;
UPDATE dbc_chartitles SET Name_Lang_enCN='将军 %s', Name1_Lang_enCN='将军 %s' WHERE ID=26;
UPDATE dbc_chartitles SET Name_Lang_enCN='督军 %s', Name1_Lang_enCN='督军 %s' WHERE ID=27;
UPDATE dbc_chartitles SET Name_Lang_enCN='高阶督军 %s', Name1_Lang_enCN='高阶督军 %s' WHERE ID=28;
UPDATE dbc_chartitles SET Name_Lang_enCN='角斗士 %s', Name1_Lang_enCN='角斗士 %s' WHERE ID=42;
UPDATE dbc_chartitles SET Name_Lang_enCN='决斗者 %s', Name1_Lang_enCN='决斗者 %s' WHERE ID=43;
UPDATE dbc_chartitles SET Name_Lang_enCN='竞争者 %s', Name1_Lang_enCN='竞争者 %s' WHERE ID=44;
UPDATE dbc_chartitles SET Name_Lang_enCN='挑战者 %s', Name1_Lang_enCN='挑战者 %s' WHERE ID=45;
UPDATE dbc_chartitles SET Name_Lang_enCN='甲虫之王 %s', Name1_Lang_enCN='甲虫之王 %s' WHERE ID=46;
UPDATE dbc_chartitles SET Name_Lang_enCN='征服者 %s', Name1_Lang_enCN='征服者 %s' WHERE ID=47;
UPDATE dbc_chartitles SET Name_Lang_enCN='审判者 %s', Name1_Lang_enCN='审判者 %s' WHERE ID=48;
UPDATE dbc_chartitles SET Name_Lang_enCN='%s, 纳鲁的勇士', Name1_Lang_enCN='%s, 纳鲁的勇士' WHERE ID=53;
UPDATE dbc_chartitles SET Name_Lang_enCN='残酷角斗士 %s', Name1_Lang_enCN='残酷角斗士 %s' WHERE ID=62;
UPDATE dbc_chartitles SET Name_Lang_enCN='破碎残阳的%s', Name1_Lang_enCN='破碎残阳的%s' WHERE ID=63;
UPDATE dbc_chartitles SET Name_Lang_enCN='%s, 阿达尔之手', Name1_Lang_enCN='%s, 阿达尔之手' WHERE ID=64;
UPDATE dbc_chartitles SET Name_Lang_enCN='复仇角斗士 %s', Name1_Lang_enCN='复仇角斗士 %s' WHERE ID=71;
UPDATE dbc_chartitles SET Name_Lang_enCN='战斗大师 %s', Name1_Lang_enCN='战斗大师 %s' WHERE ID=72;
UPDATE dbc_chartitles SET Name_Lang_enCN='长者 %s', Name1_Lang_enCN='长者 %s' WHERE ID=74;
UPDATE dbc_chartitles SET Name_Lang_enCN='护焰者 %s', Name1_Lang_enCN='护焰者 %s' WHERE ID=75;
UPDATE dbc_chartitles SET Name_Lang_enCN='护火者 %s', Name1_Lang_enCN='护火者 %s' WHERE ID=76;
UPDATE dbc_chartitles SET Name_Lang_enCN='崇高者 %s', Name1_Lang_enCN='崇高者 %s' WHERE ID=77;
UPDATE dbc_chartitles SET Name_Lang_enCN='探索者 %s', Name1_Lang_enCN='探索者 %s' WHERE ID=78;
UPDATE dbc_chartitles SET Name_Lang_enCN='外交家 %s', Name1_Lang_enCN='外交家 %s' WHERE ID=79;
UPDATE dbc_chartitles SET Name_Lang_enCN='野蛮角斗士 %s', Name1_Lang_enCN='野蛮角斗士 %s' WHERE ID=80;
UPDATE dbc_chartitles SET Name_Lang_enCN='搜寻者 %s', Name1_Lang_enCN='搜寻者 %s' WHERE ID=81;
UPDATE dbc_chartitles SET Name_Lang_enCN='竞技场大师 %s', Name1_Lang_enCN='竞技场大师 %s' WHERE ID=82;
UPDATE dbc_chartitles SET Name_Lang_enCN='咸鱼 %s', Name1_Lang_enCN='咸鱼 %s' WHERE ID=83;
UPDATE dbc_chartitles SET Name_Lang_enCN='厨师 %s', Name1_Lang_enCN='厨师 %s' WHERE ID=84;
UPDATE dbc_chartitles SET Name_Lang_enCN='伟大的%s', Name1_Lang_enCN='伟大的%s' WHERE ID=85;
UPDATE dbc_chartitles SET Name_Lang_enCN='无尽风暴的%s', Name1_Lang_enCN='无尽风暴的%s' WHERE ID=86;
UPDATE dbc_chartitles SET Name_Lang_enCN='翡翠梦境的%s', Name1_Lang_enCN='翡翠梦境的%s' WHERE ID=87;
UPDATE dbc_chartitles SET Name_Lang_enCN='预言者 %s', Name1_Lang_enCN='预言者 %s' WHERE ID=89;
UPDATE dbc_chartitles SET Name_Lang_enCN='凶星 %s', Name1_Lang_enCN='凶星 %s' WHERE ID=90;
UPDATE dbc_chartitles SET Name_Lang_enCN='追踪者 %s', Name1_Lang_enCN='追踪者 %s' WHERE ID=91;
UPDATE dbc_chartitles SET Name_Lang_enCN='黑锋骑士团的%s', Name1_Lang_enCN='黑锋骑士团的%s' WHERE ID=92;
UPDATE dbc_chartitles SET Name_Lang_enCN='大法师 %s', Name1_Lang_enCN='大法师 %s' WHERE ID=93;
UPDATE dbc_chartitles SET Name_Lang_enCN='战神 %s', Name1_Lang_enCN='战神 %s' WHERE ID=94;
UPDATE dbc_chartitles SET Name_Lang_enCN='刺客 %s', Name1_Lang_enCN='刺客 %s' WHERE ID=95;
UPDATE dbc_chartitles SET Name_Lang_enCN='宗师级炼金师 %s', Name1_Lang_enCN='宗师级炼金师 %s' WHERE ID=96;
UPDATE dbc_chartitles SET Name_Lang_enCN='宗师级铁匠 %s', Name1_Lang_enCN='宗师级铁匠 %s' WHERE ID=97;
UPDATE dbc_chartitles SET Name_Lang_enCN='钢铁厨师 %s', Name1_Lang_enCN='钢铁厨师 %s' WHERE ID=98;
UPDATE dbc_chartitles SET Name_Lang_enCN='宗师级附魔师 %s', Name1_Lang_enCN='宗师级附魔师 %s' WHERE ID=99;
UPDATE dbc_chartitles SET Name_Lang_enCN='宗师级技师 %s', Name1_Lang_enCN='宗师级技师 %s' WHERE ID=100;
UPDATE dbc_chartitles SET Name_Lang_enCN='医师 %s', Name1_Lang_enCN='医师 %s' WHERE ID=101;
UPDATE dbc_chartitles SET Name_Lang_enCN='宗师级垂钓者 %s', Name1_Lang_enCN='宗师级垂钓者 %s' WHERE ID=102;
UPDATE dbc_chartitles SET Name_Lang_enCN='宗师级草药师 %s', Name1_Lang_enCN='宗师级草药师 %s' WHERE ID=103;
UPDATE dbc_chartitles SET Name_Lang_enCN='宗师级铭文师 %s', Name1_Lang_enCN='宗师级铭文师 %s' WHERE ID=104;
UPDATE dbc_chartitles SET Name_Lang_enCN='宗师级珠宝匠 %s', Name1_Lang_enCN='宗师级珠宝匠 %s' WHERE ID=105;
UPDATE dbc_chartitles SET Name_Lang_enCN='宗师级制皮师 %s', Name1_Lang_enCN='宗师级制皮师 %s' WHERE ID=106;
UPDATE dbc_chartitles SET Name_Lang_enCN='宗师级矿工 %s', Name1_Lang_enCN='宗师级矿工 %s' WHERE ID=107;
UPDATE dbc_chartitles SET Name_Lang_enCN='宗师级剥皮师 %s', Name1_Lang_enCN='宗师级剥皮师 %s' WHERE ID=108;
UPDATE dbc_chartitles SET Name_Lang_enCN='宗师级裁缝 %s', Name1_Lang_enCN='宗师级裁缝 %s' WHERE ID=109;
UPDATE dbc_chartitles SET Name_Lang_enCN='奎尔萨拉斯的%s', Name1_Lang_enCN='奎尔萨拉斯的%s' WHERE ID=110;
UPDATE dbc_chartitles SET Name_Lang_enCN='阿古斯的%s', Name1_Lang_enCN='阿古斯的%s' WHERE ID=111;
UPDATE dbc_chartitles SET Name_Lang_enCN='卡兹莫丹的%s', Name1_Lang_enCN='卡兹莫丹的%s' WHERE ID=112;
UPDATE dbc_chartitles SET Name_Lang_enCN='诺莫瑞根的%s', Name1_Lang_enCN='诺莫瑞根的%s' WHERE ID=113;
UPDATE dbc_chartitles SET Name_Lang_enCN='狮心王 %s', Name1_Lang_enCN='狮心王 %s' WHERE ID=114;
UPDATE dbc_chartitles SET Name_Lang_enCN='%s, 艾露恩的勇士', Name1_Lang_enCN='%s, 艾露恩的勇士' WHERE ID=115;
UPDATE dbc_chartitles SET Name_Lang_enCN='%s, 奥格瑞玛的英雄', Name1_Lang_enCN='%s, 奥格瑞玛的英雄' WHERE ID=116;
UPDATE dbc_chartitles SET Name_Lang_enCN='平原行者 %s', Name1_Lang_enCN='平原行者 %s' WHERE ID=117;
UPDATE dbc_chartitles SET Name_Lang_enCN='暗矛部族的%s', Name1_Lang_enCN='暗矛部族的%s' WHERE ID=118;
UPDATE dbc_chartitles SET Name_Lang_enCN='被遗忘者%s', Name1_Lang_enCN='被遗忘者%s' WHERE ID=119;
UPDATE dbc_chartitles SET Name_Lang_enCN='魔法追寻者 %s', Name1_Lang_enCN='魔法追寻者 %s' WHERE ID=120;
UPDATE dbc_chartitles SET Name_Lang_enCN='暮光征服者 %s', Name1_Lang_enCN='暮光征服者 %s' WHERE ID=121;
UPDATE dbc_chartitles SET Name_Lang_enCN='%s, 纳克萨玛斯的征服者', Name1_Lang_enCN='%s, 纳克萨玛斯的征服者' WHERE ID=122;
UPDATE dbc_chartitles SET Name_Lang_enCN='%s, 诺森德的英雄', Name1_Lang_enCN='%s, 诺森德的英雄' WHERE ID=123;
UPDATE dbc_chartitles SET Name_Lang_enCN='神圣的%s', Name1_Lang_enCN='神圣的%s' WHERE ID=124;
UPDATE dbc_chartitles SET Name_Lang_enCN='博学者 %s', Name1_Lang_enCN='博学者 %s' WHERE ID=125;
UPDATE dbc_chartitles SET Name_Lang_enCN='联盟的%s', Name1_Lang_enCN='联盟的%s' WHERE ID=126;
UPDATE dbc_chartitles SET Name_Lang_enCN='部落的%s', Name1_Lang_enCN='部落的%s' WHERE ID=127;
UPDATE dbc_chartitles SET Name_Lang_enCN='完美胜者 %s', Name1_Lang_enCN='完美胜者 %s' WHERE ID=128;
UPDATE dbc_chartitles SET Name_Lang_enCN='%s, 冰冻废土的勇士', Name1_Lang_enCN='%s, 冰冻废土的勇士' WHERE ID=129;
UPDATE dbc_chartitles SET Name_Lang_enCN='大使 %s', Name1_Lang_enCN='大使 %s' WHERE ID=130;
UPDATE dbc_chartitles SET Name_Lang_enCN='银色勇士 %s', Name1_Lang_enCN='银色勇士 %s' WHERE ID=131;
UPDATE dbc_chartitles SET Name_Lang_enCN='%s, 塞纳留斯的卫士', Name1_Lang_enCN='%s, 塞纳留斯的卫士' WHERE ID=132;
UPDATE dbc_chartitles SET Name_Lang_enCN='酒仙 %s', Name1_Lang_enCN='酒仙 %s' WHERE ID=133;
UPDATE dbc_chartitles SET Name_Lang_enCN='欢乐使者 %s', Name1_Lang_enCN='欢乐使者 %s' WHERE ID=134;
UPDATE dbc_chartitles SET Name_Lang_enCN='痴情的%s', Name1_Lang_enCN='痴情的%s' WHERE ID=135;
UPDATE dbc_chartitles SET Name_Lang_enCN='护士长 %s', Name1_Lang_enCN='护士长 %s' WHERE ID=137;
UPDATE dbc_chartitles SET Name_Lang_enCN='监护人 %s', Name1_Lang_enCN='监护人 %s' WHERE ID=138;
UPDATE dbc_chartitles SET Name_Lang_enCN='黑曜石杀手 %s', Name1_Lang_enCN='黑曜石杀手 %s' WHERE ID=139;
UPDATE dbc_chartitles SET Name_Lang_enCN='夜幕的%s', Name1_Lang_enCN='夜幕的%s' WHERE ID=140;
UPDATE dbc_chartitles SET Name_Lang_enCN='永恒者 %s', Name1_Lang_enCN='永恒者 %s' WHERE ID=141;
UPDATE dbc_chartitles SET Name_Lang_enCN='不朽者 %s', Name1_Lang_enCN='不朽者 %s' WHERE ID=142;
UPDATE dbc_chartitles SET Name_Lang_enCN='火车王 %s', Name1_Lang_enCN='火车王 %s' WHERE ID=143;
UPDATE dbc_chartitles SET Name_Lang_enCN='血帆舰队司令 %s', Name1_Lang_enCN='血帆舰队司令 %s' WHERE ID=144;
UPDATE dbc_chartitles SET Name_Lang_enCN='疯狂的%s', Name1_Lang_enCN='疯狂的%s' WHERE ID=145;
UPDATE dbc_chartitles SET Name_Lang_enCN='埃索达的%s', Name1_Lang_enCN='埃索达的%s' WHERE ID=146;
UPDATE dbc_chartitles SET Name_Lang_enCN='达纳苏斯的%s', Name1_Lang_enCN='达纳苏斯的%s' WHERE ID=147;
UPDATE dbc_chartitles SET Name_Lang_enCN='铁炉堡的%s', Name1_Lang_enCN='铁炉堡的%s' WHERE ID=148;
UPDATE dbc_chartitles SET Name_Lang_enCN='暴风城的%s', Name1_Lang_enCN='暴风城的%s' WHERE ID=149;
UPDATE dbc_chartitles SET Name_Lang_enCN='奥格瑞玛的%s', Name1_Lang_enCN='奥格瑞玛的%s' WHERE ID=150;
UPDATE dbc_chartitles SET Name_Lang_enCN='森金的%s', Name1_Lang_enCN='森金的%s' WHERE ID=151;
UPDATE dbc_chartitles SET Name_Lang_enCN='银月城的%s', Name1_Lang_enCN='银月城的%s' WHERE ID=152;
UPDATE dbc_chartitles SET Name_Lang_enCN='雷霆崖的%s', Name1_Lang_enCN='雷霆崖的%s' WHERE ID=153;
UPDATE dbc_chartitles SET Name_Lang_enCN='幽暗城的%s', Name1_Lang_enCN='幽暗城的%s' WHERE ID=154;
UPDATE dbc_chartitles SET Name_Lang_enCN='贵族 %s', Name1_Lang_enCN='贵族 %s' WHERE ID=155;
UPDATE dbc_chartitles SET Name_Lang_enCN='十字军 %s', Name1_Lang_enCN='十字军 %s' WHERE ID=156;
UPDATE dbc_chartitles SET Name_Lang_enCN='致命角斗士 %s', Name1_Lang_enCN='致命角斗士 %s' WHERE ID=157;
UPDATE dbc_chartitles SET Name_Lang_enCN='%s, 死亡的终结者', Name1_Lang_enCN='%s, 死亡的终结者' WHERE ID=158;
UPDATE dbc_chartitles SET Name_Lang_enCN='天界保卫者 %s', Name1_Lang_enCN='天界保卫者 %s' WHERE ID=159;
UPDATE dbc_chartitles SET Name_Lang_enCN='%s, 奥杜尔的征服者', Name1_Lang_enCN='%s, 奥杜尔的征服者' WHERE ID=160;
UPDATE dbc_chartitles SET Name_Lang_enCN='%s, 奥杜尔的勇士', Name1_Lang_enCN='%s, 奥杜尔的勇士' WHERE ID=161;
UPDATE dbc_chartitles SET Name_Lang_enCN='胜利者 %s', Name1_Lang_enCN='胜利者 %s' WHERE ID=163;
UPDATE dbc_chartitles SET Name_Lang_enCN='唤星者 %s', Name1_Lang_enCN='唤星者 %s' WHERE ID=164;
UPDATE dbc_chartitles SET Name_Lang_enCN='星界旅行者 %s', Name1_Lang_enCN='星界旅行者 %s' WHERE ID=165;
UPDATE dbc_chartitles SET Name_Lang_enCN='%s, 泰坦的使者', Name1_Lang_enCN='%s, 泰坦的使者' WHERE ID=166;
UPDATE dbc_chartitles SET Name_Lang_enCN='狂怒角斗士 %s', Name1_Lang_enCN='狂怒角斗士 %s' WHERE ID=167;
UPDATE dbc_chartitles SET Name_Lang_enCN='感恩者 %s', Name1_Lang_enCN='感恩者 %s' WHERE ID=168;
UPDATE dbc_chartitles SET Name_Lang_enCN='无情角斗士 %s', Name1_Lang_enCN='无情角斗士 %s' WHERE ID=169;
UPDATE dbc_chartitles SET Name_Lang_enCN='大十字军 %s', Name1_Lang_enCN='大十字军 %s' WHERE ID=170;
UPDATE dbc_chartitles SET Name_Lang_enCN='银色护卫者 %s', Name1_Lang_enCN='银色护卫者 %s' WHERE ID=171;
UPDATE dbc_chartitles SET Name_Lang_enCN='百折不挠的%s', Name1_Lang_enCN='百折不挠的%s' WHERE ID=172;
UPDATE dbc_chartitles SET Name_Lang_enCN='黎明之光 %s', Name1_Lang_enCN='黎明之光 %s' WHERE ID=173;
UPDATE dbc_chartitles SET Name_Lang_enCN='%s, 堕落君王的克星', Name1_Lang_enCN='%s, 堕落君王的克星' WHERE ID=174;
UPDATE dbc_chartitles SET Name_Lang_enCN='弑君者 %s', Name1_Lang_enCN='弑君者 %s' WHERE ID=175;
UPDATE dbc_chartitles SET Name_Lang_enCN='灰烬审判军 %s', Name1_Lang_enCN='灰烬审判军 %s' WHERE ID=176;
UPDATE dbc_chartitles SET Name_Lang_enCN='暴怒角斗士 %s', Name1_Lang_enCN='暴怒角斗士 %s' WHERE ID=177;
