UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='暴风城' WHERE ID=1;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赤脊山' WHERE ID=2;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='暮色森林，夜色镇' WHERE ID=3;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='西部荒野，哨兵岭' WHERE ID=4;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='丹莫罗' WHERE ID=5;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='洛克莫丹，塞尔萨玛' WHERE ID=6;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='湿地，十字路口' WHERE ID=7;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='荒芜之地，东北墓地' WHERE ID=8;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='贫瘠之地，十字路口' WHERE ID=10;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='凄凉之地，艾瑟雷索' WHERE ID=31;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='杜隆塔尔，剃刀岭' WHERE ID=32;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='杜隆塔尔，奥格瑞玛' WHERE ID=33;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='莫高雷，红云台地' WHERE ID=34;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='黑海岸，奥伯丁' WHERE ID=35;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='逆风小径，摩根墓场' WHERE ID=36;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='千针石林，升降梯' WHERE ID=39;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='积雪平原 - 部落起始点' WHERE ID=49;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='希利苏斯，勇士之墓' WHERE ID=70;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='莫高雷，血蹄村' WHERE ID=89;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰达希尔，达纳苏斯' WHERE ID=90;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰达希尔，多兰纳尔' WHERE ID=91;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='灰谷，阿斯特兰纳' WHERE ID=92;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰达希尔，奥达希尔' WHERE ID=93;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='提瑞斯法林地，丧钟镇' WHERE ID=94;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='提瑞斯法林地，幽暗城' WHERE ID=96;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='银松森林，瑟伯切尔' WHERE ID=97;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='希尔斯布莱德，塔伦米尔' WHERE ID=98;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='阿拉希高地，东部大道' WHERE ID=99;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='丹莫罗，安威玛尔' WHERE ID=100;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='丹莫罗，卡拉诺斯' WHERE ID=101;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='丹莫罗，铁炉堡' WHERE ID=102;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='荒芜之地，卡加斯' WHERE ID=103;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赤脊山，湖畔镇' WHERE ID=104;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='艾尔文森林，北郡' WHERE ID=105;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='艾尔文森林，闪金镇' WHERE ID=106;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='艾尔文森林，暴风城' WHERE ID=107;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='悲伤沼泽，斯通纳德' WHERE ID=108;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='荆棘谷，藏宝海湾' WHERE ID=109;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰达希尔，鲁瑟兰村' WHERE ID=129;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='希尔斯布莱德丘陵，南海镇' WHERE ID=149;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥特兰克山谷，落雪墓地（中）' WHERE ID=169;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='尘泥沼泽，塞拉摩' WHERE ID=189;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='塔纳利斯，加基森' WHERE ID=209;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='贫瘠之地，陶拉祖营地' WHERE ID=229;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='贫瘠之地，棘齿城' WHERE ID=249;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='积雪平原 - 联盟起始点' WHERE ID=269;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='提瑞斯法林地，布瑞尔' WHERE ID=289;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='菲拉斯，羽月要塞' WHERE ID=309;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='菲拉斯，莫沙彻营地' WHERE ID=310;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='千针石林，闪光平原' WHERE ID=329;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='辛特兰，鹰巢山' WHERE ID=349;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='艾萨拉，塔伦迪斯营地' WHERE ID=369;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='诅咒之地，巨槌要塞' WHERE ID=370;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='荆棘谷，北荆棘谷' WHERE ID=389;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='石爪山脉，蛛网小径' WHERE ID=409;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='提瑞斯法林地，法奥之墓' WHERE ID=429;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='费伍德森林，摩罗萨兰' WHERE ID=449;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='安戈洛环形山，沼泽地' WHERE ID=450;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='黑海岸，暮光谷' WHERE ID=469;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='湿地，巴拉丁海湾' WHERE ID=489;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='西瘟疫之地，冰风岗' WHERE ID=509;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='东瘟疫之地，腐烂之痕' WHERE ID=510;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冬泉谷，永望镇' WHERE ID=511;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='灰谷，卡加希亚' WHERE ID=512;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='程序员之岛' WHERE ID=529;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='程序员之岛' WHERE ID=549;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='西瘟疫之地，亡灵壁垒' WHERE ID=569;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='GM之岛' WHERE ID=589;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='艾萨拉，南山海滩' WHERE ID=609;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥特兰克山谷，部落安全点' WHERE ID=610;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥特兰克山谷，联盟安全点' WHERE ID=611;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='只用于客户端GM测试 - 不要汇报BUG' WHERE ID=629;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='艾萨拉，雷加什营地' WHERE ID=630;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='尘泥沼泽，蕨墙村' WHERE ID=631;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='月光林地' WHERE ID=633;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='东瘟疫之地，达隆郡' WHERE ID=634;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='费伍德，铁木森林' WHERE ID=635;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='灼热峡谷，瑟银哨塔' WHERE ID=636;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='杜隆塔尔，森金村' WHERE ID=649;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='Programmer Isle, Bucklers Cemetery 2' WHERE ID=669;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='Programmer Isle, Bucklers Cemetery 1' WHERE ID=670;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='Programmer Isle, Bucklers Cemetery 3' WHERE ID=671;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥特兰克山谷，雷矛墓地' WHERE ID=689;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥特兰克山谷，霜狼墓地' WHERE ID=690;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='杜隆塔尔，试炼谷' WHERE ID=709;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥特兰克山谷，PvP联盟墓地' WHERE ID=729;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥特兰克山谷，PvP部落墓地' WHERE ID=749;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥特兰克山谷，霜狼急救站' WHERE ID=750;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥特兰克山谷，雷矛急救站' WHERE ID=751;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='战歌峡谷 - 联盟入口位置' WHERE ID=769;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='战歌峡谷 - 部落入口位置' WHERE ID=770;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='战歌峡谷 - 联盟复活点' WHERE ID=771;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='战歌峡谷 - 部落复活点' WHERE ID=772;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='辛特兰，望海崖' WHERE ID=789;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='战歌峡谷 - 部落出口位置' WHERE ID=809;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='战歌峡谷 - 联盟出口位置' WHERE ID=810;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥特兰克山谷，联盟出口' WHERE ID=829;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥特兰克山谷，部落出口' WHERE ID=830;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='菲拉斯，厄运之槌' WHERE ID=849;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='杜隆塔尔，北杜隆塔尔' WHERE ID=850;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='莫高雷，雷霆崖' WHERE ID=851;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='丹莫罗，铁炉堡大门' WHERE ID=852;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='提瑞斯法林地，洛丹伦废墟' WHERE ID=853;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='艾尔文森林，东谷伐木场' WHERE ID=854;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='西瘟疫之地，凯尔达隆' WHERE ID=869;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='阿拉希盆地 - 部落入口' WHERE ID=889;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='阿拉希盆地 - 联盟入口' WHERE ID=890;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='阿拉希 - 阿拉希前线部落出口' WHERE ID=891;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='阿拉希 - 阿拉希前线联盟出口' WHERE ID=892;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='阿拉希盆地 - 墓地， 中央（农场）' WHERE ID=893;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='阿拉希盆地 - 墓地，中部（铁匠）' WHERE ID=894;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='阿拉希盆地 - 墓地，中央（马厩）' WHERE ID=895;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='阿拉希盆地 - 墓地， ALT-N（金矿）' WHERE ID=896;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='阿拉希盆地 - 墓地， ALT-S（伐木场）' WHERE ID=897;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='阿拉希盆地 - 墓地， 基地（托尔贝恩大厅）' WHERE ID=898;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='阿拉希盆地 - 墓地，总部基地（污染者之穴）' WHERE ID=899;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='东瘟疫之地，黑木湖' WHERE ID=909;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='希利苏斯，塞纳里奥要塞' WHERE ID=910;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='暮色森林，乌鸦岭' WHERE ID=911;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='永歌森林，逐日岛' WHERE ID=912;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='希利苏斯，甲虫之墙' WHERE ID=913;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='永歌森林， 旅行者营地 墓地' WHERE ID=914;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='幽魂之地，塔奎林' WHERE ID=915;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='幽魂之地，密室' WHERE ID=916;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='幽魂之地，阿曼尼小径' WHERE ID=917;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='秘蓝岛，埃门谷' WHERE ID=918;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，萨尔玛' WHERE ID=919;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，荣耀堡' WHERE ID=920;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='永歌森林，银月城' WHERE ID=921;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='永歌森林，晴风村墓地' WHERE ID=922;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='秘蓝岛，碧蓝岗哨墓地' WHERE ID=923;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='秘蓝岛，止松墓地' WHERE ID=924;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='秘血岛，秘血岗哨墓地' WHERE ID=925;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='秘血岛，高原荒野墓地' WHERE ID=926;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='东瘟疫之地，哨塔墓地' WHERE ID=927;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，萨布拉金墓地' WHERE ID=928;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰竞技场，队伍1起始点' WHERE ID=929;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰， SE 墓地' WHERE ID=930;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='程序员之岛' WHERE ID=931;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='程序员之岛' WHERE ID=932;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，神殿' WHERE ID=933;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，猎鹰岗哨' WHERE ID=934;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置004' WHERE ID=935;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰竞技场，队伍2起始点' WHERE ID=936;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='Reuse' WHERE ID=937;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥特兰克山谷，联盟出口' WHERE ID=938;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山竞技场，队伍1' WHERE ID=939;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山竞技场，队伍2' WHERE ID=940;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体地点（测试）' WHERE ID=941;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置001' WHERE ID=942;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置002' WHERE ID=943;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置003' WHERE ID=944;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置005' WHERE ID=945;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置006' WHERE ID=946;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置007' WHERE ID=947;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置008' WHERE ID=948;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置009' WHERE ID=949;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置010' WHERE ID=950;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置011' WHERE ID=951;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置012' WHERE ID=952;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置013' WHERE ID=953;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置014' WHERE ID=954;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置015' WHERE ID=955;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置016' WHERE ID=956;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置017' WHERE ID=957;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置018' WHERE ID=958;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置019' WHERE ID=959;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置020' WHERE ID=960;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置021' WHERE ID=961;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置022' WHERE ID=962;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置023' WHERE ID=963;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置024' WHERE ID=964;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置025' WHERE ID=965;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置026' WHERE ID=966;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置027' WHERE ID=967;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，尸体位置028' WHERE ID=968;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽， PvP 墓地' WHERE ID=969;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，泰雷多尔墓地' WHERE ID=970;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山 - PvP - 竞技场墓地' WHERE ID=971;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置006' WHERE ID=972;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，塞纳里奥墓地' WHERE ID=973;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置001' WHERE ID=974;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置002' WHERE ID=975;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置003' WHERE ID=976;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置004' WHERE ID=977;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置008' WHERE ID=978;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置005' WHERE ID=979;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置007' WHERE ID=980;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置009' WHERE ID=981;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置011' WHERE ID=982;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置010' WHERE ID=983;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置012' WHERE ID=984;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置013' WHERE ID=985;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置014' WHERE ID=986;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置016' WHERE ID=987;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置015' WHERE ID=988;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置017' WHERE ID=989;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置018' WHERE ID=990;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，尸体位置019' WHERE ID=991;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，北风裂谷' WHERE ID=992;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，哈兰墓地' WHERE ID=993;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，沙塔斯墓地' WHERE ID=994;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，荒野墓地' WHERE ID=995;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='Test - Programmer' WHERE ID=996;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='Test - Programmer 001' WHERE ID=997;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰 - PvP - 竞技场墓地' WHERE ID=998;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，尸体位置001' WHERE ID=999;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，尸体位置002' WHERE ID=1000;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，尸体位置003' WHERE ID=1001;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，尸体位置004' WHERE ID=1002;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，尸体位置005' WHERE ID=1003;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，尸体位置006' WHERE ID=1004;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，尸体位置007' WHERE ID=1005;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，尸体位置008' WHERE ID=1006;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，尸体位置009' WHERE ID=1007;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，尸体位置010' WHERE ID=1008;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，尸体位置011' WHERE ID=1009;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，尸体位置012' WHERE ID=1010;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，尸体位置013' WHERE ID=1011;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，尸体位置014' WHERE ID=1012;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置001' WHERE ID=1013;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置002' WHERE ID=1014;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置003' WHERE ID=1015;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置004' WHERE ID=1016;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置005' WHERE ID=1017;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置006' WHERE ID=1018;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置007' WHERE ID=1019;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置008' WHERE ID=1020;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置009' WHERE ID=1021;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置010' WHERE ID=1022;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置011' WHERE ID=1023;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置001' WHERE ID=1024;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置002' WHERE ID=1025;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置003' WHERE ID=1026;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置004' WHERE ID=1027;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置016' WHERE ID=1028;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置017' WHERE ID=1029;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置018' WHERE ID=1030;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置019' WHERE ID=1031;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置020' WHERE ID=1032;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置021' WHERE ID=1033;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置022' WHERE ID=1034;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尸体位置023' WHERE ID=1035;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='Reuse' WHERE ID=1036;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，高地传送门' WHERE ID=1037;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，元素高地' WHERE ID=1038;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='纳格兰，西南墓地' WHERE ID=1039;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，基尔加丹王座' WHERE ID=1040;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，黑暗之门' WHERE ID=1041;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，白骨荒野墓地' WHERE ID=1042;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，避难营墓地' WHERE ID=1043;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赞加沼泽，孢子村墓地' WHERE ID=1044;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴，风暴尖塔墓地' WHERE ID=1045;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴，区域52 墓地' WHERE ID=1046;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月谷，影月村墓地' WHERE ID=1047;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月谷，蛮锤墓地' WHERE ID=1048;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，希尔瓦纳墓地' WHERE ID=1049;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，雷神要塞墓地' WHERE ID=1050;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，斯克提斯墓地' WHERE ID=1051;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置005' WHERE ID=1052;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置006' WHERE ID=1053;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置007' WHERE ID=1054;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置008' WHERE ID=1055;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置009' WHERE ID=1056;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置010' WHERE ID=1057;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置011' WHERE ID=1058;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置012' WHERE ID=1059;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置013' WHERE ID=1060;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置014' WHERE ID=1061;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置015' WHERE ID=1062;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置016' WHERE ID=1063;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置017' WHERE ID=1064;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置018' WHERE ID=1065;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置019' WHERE ID=1066;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置020' WHERE ID=1067;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置021' WHERE ID=1068;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置022' WHERE ID=1069;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置023' WHERE ID=1070;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月，尸体位置024' WHERE ID=1071;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置000' WHERE ID=1072;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置001' WHERE ID=1073;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置002' WHERE ID=1074;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置003' WHERE ID=1075;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置004' WHERE ID=1076;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置005' WHERE ID=1077;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置006' WHERE ID=1078;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置007' WHERE ID=1079;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置008' WHERE ID=1080;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置009' WHERE ID=1081;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置010' WHERE ID=1082;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置011' WHERE ID=1083;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置012' WHERE ID=1084;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置013' WHERE ID=1085;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置014' WHERE ID=1086;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置015' WHERE ID=1087;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置016' WHERE ID=1088;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置017' WHERE ID=1089;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置018' WHERE ID=1090;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置019' WHERE ID=1091;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置020' WHERE ID=1092;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置021' WHERE ID=1093;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置022' WHERE ID=1094;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置023' WHERE ID=1095;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置024' WHERE ID=1096;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置025' WHERE ID=1097;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置026' WHERE ID=1098;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置027' WHERE ID=1099;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置028' WHERE ID=1100;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置029' WHERE ID=1101;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置030' WHERE ID=1102;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 墓地（联盟起始点）' WHERE ID=1103;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 墓地（联盟起始点）' WHERE ID=1104;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 墓地（魔能机甲）' WHERE ID=1105;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 墓地 （血精灵塔）' WHERE ID=1106;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 墓地（德莱尼塔）' WHERE ID=1107;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 墓地（人类塔）' WHERE ID=1108;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找000' WHERE ID=1109;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找001' WHERE ID=1110;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找002' WHERE ID=1111;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找003' WHERE ID=1112;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找004' WHERE ID=1113;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找005' WHERE ID=1114;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找006' WHERE ID=1115;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找007' WHERE ID=1116;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找008' WHERE ID=1117;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找009' WHERE ID=1118;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找010' WHERE ID=1119;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找011' WHERE ID=1120;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找012' WHERE ID=1121;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找013' WHERE ID=1122;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找014' WHERE ID=1123;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找015' WHERE ID=1124;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找016' WHERE ID=1125;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找017' WHERE ID=1126;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找018' WHERE ID=1127;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找019' WHERE ID=1128;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找020' WHERE ID=1129;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找021' WHERE ID=1130;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找022' WHERE ID=1131;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找023' WHERE ID=1132;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴BG - 尸体寻找024' WHERE ID=1133;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找000' WHERE ID=1134;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找001' WHERE ID=1135;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找002' WHERE ID=1136;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找003' WHERE ID=1137;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找004' WHERE ID=1138;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找005' WHERE ID=1139;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找006' WHERE ID=1140;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找007' WHERE ID=1141;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找008' WHERE ID=1142;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找009' WHERE ID=1143;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找010' WHERE ID=1144;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找011' WHERE ID=1145;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找012' WHERE ID=1146;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找013' WHERE ID=1147;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找014' WHERE ID=1148;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找015' WHERE ID=1149;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找016' WHERE ID=1150;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找017' WHERE ID=1151;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找018' WHERE ID=1152;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找019' WHERE ID=1153;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找020' WHERE ID=1154;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找021' WHERE ID=1155;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找022' WHERE ID=1156;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找023' WHERE ID=1157;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找024' WHERE ID=1158;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找025' WHERE ID=1159;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找026' WHERE ID=1160;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找027' WHERE ID=1161;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找028' WHERE ID=1162;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找029' WHERE ID=1163;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找030' WHERE ID=1164;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找031' WHERE ID=1165;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找032' WHERE ID=1166;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找033' WHERE ID=1167;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找034' WHERE ID=1168;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找035' WHERE ID=1169;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找036' WHERE ID=1170;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找037' WHERE ID=1171;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找038' WHERE ID=1172;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找039' WHERE ID=1173;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找040' WHERE ID=1174;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找041' WHERE ID=1175;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找042' WHERE ID=1176;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找043' WHERE ID=1177;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找044' WHERE ID=1178;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找045' WHERE ID=1179;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找046' WHERE ID=1180;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找047' WHERE ID=1181;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找048' WHERE ID=1182;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找049' WHERE ID=1183;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找050' WHERE ID=1184;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找051' WHERE ID=1185;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找052' WHERE ID=1186;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找053' WHERE ID=1187;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找054' WHERE ID=1188;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找055' WHERE ID=1189;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找056' WHERE ID=1190;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找057' WHERE ID=1191;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找058' WHERE ID=1192;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找059' WHERE ID=1193;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找060' WHERE ID=1194;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找061' WHERE ID=1195;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找062' WHERE ID=1196;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找063' WHERE ID=1197;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找064' WHERE ID=1198;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找065' WHERE ID=1199;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找066' WHERE ID=1200;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找067' WHERE ID=1201;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找068' WHERE ID=1202;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找069' WHERE ID=1203;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找070' WHERE ID=1204;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找071' WHERE ID=1205;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找072' WHERE ID=1206;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找073' WHERE ID=1207;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找074' WHERE ID=1208;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找075' WHERE ID=1209;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找076' WHERE ID=1210;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找077' WHERE ID=1211;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找078' WHERE ID=1212;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找079' WHERE ID=1213;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找080' WHERE ID=1214;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找081' WHERE ID=1215;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找082' WHERE ID=1216;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找083' WHERE ID=1217;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找084' WHERE ID=1218;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找085' WHERE ID=1219;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找086' WHERE ID=1220;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找087' WHERE ID=1221;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找088' WHERE ID=1222;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找089' WHERE ID=1223;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找090' WHERE ID=1224;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找091' WHERE ID=1225;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找092' WHERE ID=1226;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找093' WHERE ID=1227;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找094' WHERE ID=1228;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找095' WHERE ID=1229;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找096' WHERE ID=1230;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找097' WHERE ID=1231;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找098' WHERE ID=1232;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找099' WHERE ID=1233;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找100' WHERE ID=1234;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找101' WHERE ID=1235;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找102' WHERE ID=1236;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找103' WHERE ID=1237;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找104' WHERE ID=1238;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴 - 尸体寻找105' WHERE ID=1239;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，部队营地（联盟）' WHERE ID=1240;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，常青林墓地' WHERE ID=1241;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，北部山脊墓地' WHERE ID=1242;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，西山脊墓地' WHERE ID=1243;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，东山脊墓地' WHERE ID=1244;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冰冠冰川BG - 部落进入区域' WHERE ID=1245;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥特兰克山谷，联盟出口' WHERE ID=1246;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴，扳钳镇墓地' WHERE ID=1247;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='地狱火半岛，断背山墓地' WHERE ID=1248;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='塔纳利斯，时光之穴' WHERE ID=1249;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月谷，祭坛墓地' WHERE ID=1250;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='影月谷，圣殿墓地' WHERE ID=1251;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='虚空风暴，肯瑞瓦墓地' WHERE ID=1252;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，托什雷墓地' WHERE ID=1253;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，乌鸦林墓地' WHERE ID=1254;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，东北山脊墓地' WHERE ID=1255;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='银松森林，南墓地' WHERE ID=1256;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，食人魔墓地' WHERE ID=1257;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='洛丹伦，PVP - 队伍1起始点' WHERE ID=1258;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='洛丹伦，PVP - 队伍2起始点' WHERE ID=1259;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='洛丹伦，PVP - 墓地' WHERE ID=1260;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='黑暗神殿，联盟墓地' WHERE ID=1261;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='黑暗神殿，部落墓地' WHERE ID=1262;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='刀锋山，尸体位置031' WHERE ID=1263;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='尘泥沼泽，塔贝萨的农场' WHERE ID=1264;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='尘泥沼泽，泥链镇' WHERE ID=1265;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='嚎风峡湾，西北墓地' WHERE ID=1266;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='嚎风峡湾，海象人墓地' WHERE ID=1267;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='嚎风峡湾，岛屿墓地' WHERE ID=1268;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='嚎风峡湾，中部墓地' WHERE ID=1269;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='嚎风峡湾，北部墓地' WHERE ID=1270;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='嚎风峡湾，复仇港墓地' WHERE ID=1271;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='嚎风峡湾，东南墓地' WHERE ID=1272;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='嚎风峡湾，南部海滩 墓地' WHERE ID=1273;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='嚎风峡湾，南墓地' WHERE ID=1274;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='嚎风峡湾，瓦加德墓地' WHERE ID=1275;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='嚎风峡湾，东北墓地' WHERE ID=1276;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='安戈洛环形山，中部墓地' WHERE ID=1277;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='安戈洛环形山，马绍尔营地墓地' WHERE ID=1278;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='石爪山脉，焦炭谷' WHERE ID=1279;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='石爪山脉，峰顶墓地' WHERE ID=1280;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='塔纳利斯，海盗墓地' WHERE ID=1281;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='塔纳利斯，中部墓地' WHERE ID=1282;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冬泉谷，南部墓地' WHERE ID=1283;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冬泉谷，西部墓地' WHERE ID=1284;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冬拥湖，城堡（东）' WHERE ID=1285;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='西瘟疫之地，中部墓地' WHERE ID=1286;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='灼热峡谷，东南墓地' WHERE ID=1287;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='荒芜之地，南墓地' WHERE ID=1288;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='贫瘠之地，南墓地' WHERE ID=1289;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='北风苔原，海象人墓地' WHERE ID=1290;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，荆刺高地墓地' WHERE ID=1291;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奎尔丹纳斯岛，露台区墓地' WHERE ID=1292;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奎尔丹纳斯岛，露台区墓地' WHERE ID=1293;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奎尔丹纳斯岛，露台区墓地' WHERE ID=1294;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='Development Land, Theresa''s Test Land 墓地' WHERE ID=1295;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='Development Land, Theresa''s Test Land 2 墓地' WHERE ID=1296;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='Development Land, Theresa''s Test land 3 墓地' WHERE ID=1297;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='泰罗卡森林，尤鲁恩湖墓地' WHERE ID=1298;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冰冠冰川BG - 联盟进入区域' WHERE ID=1299;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='灰熊丘陵，邪猎村墓地' WHERE ID=1300;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='灰熊丘陵，琥珀松木墓地' WHERE ID=1301;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='灰熊丘陵，西部荒野墓地' WHERE ID=1302;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='灰熊丘陵，东部墓地' WHERE ID=1303;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='灰熊丘陵，西北墓地' WHERE ID=1304;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='灰熊丘陵，西南墓地' WHERE ID=1305;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='灰熊丘陵，中部墓地' WHERE ID=1306;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='龙骨荒野，东北墓地' WHERE ID=1307;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='龙骨荒野，暮冬墓地' WHERE ID=1308;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='龙骨荒野，被遗忘者东墓地' WHERE ID=1309;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='龙骨荒野，阿格玛之锤墓地' WHERE ID=1310;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='龙骨荒野，群星之墓 墓地' WHERE ID=1311;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='龙骨荒野，莫亚基港口墓地' WHERE ID=1312;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='龙骨荒野，北风边界墓地' WHERE ID=1313;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='龙骨荒野，龙眠墓地' WHERE ID=1314;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='龙骨荒野，天谴之门部落墓地' WHERE ID=1315;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='龙骨荒野，天谴之门，联盟墓地' WHERE ID=1316;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='北风苔原，战歌要塞墓地' WHERE ID=1317;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='北风苔原，裂鞭墓地' WHERE ID=1318;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='北风苔原，考达拉墓地' WHERE ID=1319;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='北风苔原，琥珀崖墓地' WHERE ID=1320;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='北风苔原，菲兹兰克墓地' WHERE ID=1321;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='北风苔原，博古洛克墓地' WHERE ID=1322;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='北风苔原，死亡营地墓地' WHERE ID=1323;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='北风苔原，牦牛村墓地' WHERE ID=1324;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='北风苔原，回音海岸墓地' WHERE ID=1325;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='北风苔原，无畏要塞墓地' WHERE ID=1326;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥特兰克山谷 - 不要编辑' WHERE ID=1327;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冬拥湖，城堡（西）' WHERE ID=1328;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冬拥湖，攻城武器工厂（防御，东北）' WHERE ID=1329;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冬拥湖，攻城武器工厂（防御，西北）' WHERE ID=1330;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冬拥湖，部落开始区域' WHERE ID=1331;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冬拥湖，联盟开始区域' WHERE ID=1332;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冬拥湖，攻城武器工厂（东南）' WHERE ID=1333;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冬拥湖，攻城武器工厂（西南）' WHERE ID=1334;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='索拉查盆地，南墓地' WHERE ID=1336;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='嚎风峡湾，乌特加德墓地' WHERE ID=1337;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='索拉查盆地，奈辛瓦里墓地' WHERE ID=1341;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='索拉查盆地，中部墓地' WHERE ID=1342;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='索拉查盆地，西北墓地' WHERE ID=1343;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='索拉查盆地，东北墓地' WHERE ID=1344;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='索拉查盆地，东墓地' WHERE ID=1345;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='诺森德BG - 被控制的 - 南' WHERE ID=1346;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='诺森德BG - 被控制的 -西南' WHERE ID=1347;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='诺森德BG - 被控制的 - 中央' WHERE ID=1348;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='诺森德BG - 防御者 - 最终' WHERE ID=1349;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='诺森德BG - 进攻者 - 海滩' WHERE ID=1350;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='诺森德BG - 进攻者 - 小艇' WHERE ID=1351;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='祖达克，西部墓地' WHERE ID=1352;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='祖达克，西北墓地' WHERE ID=1353;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='祖达克，西南墓地' WHERE ID=1354;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='祖达克，南部墓地' WHERE ID=1355;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='祖达克，中部墓地' WHERE ID=1356;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='祖达克，东南墓地' WHERE ID=1357;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='祖达克，古达克墓地' WHERE ID=1358;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='晶歌森林，达拉然墓地' WHERE ID=1359;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='黑锋要塞墓地 - 第一章' WHERE ID=1360;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='达拉然竞技场 - PvP 墓地' WHERE ID=1361;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='达拉然竞技场 - 第1队重生点' WHERE ID=1362;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='达拉然竞技场 -队伍2重生点' WHERE ID=1363;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥格瑞玛竞技场 -队伍1重生点' WHERE ID=1364;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥格瑞玛竞技场 -队伍2重生点' WHERE ID=1365;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥格瑞玛竞技场 - 墓地' WHERE ID=1366;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='Sands of Ulduran -联盟重生点' WHERE ID=1367;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='Sands of Ulduran -部落重生点' WHERE ID=1368;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='东瘟疫之地，黑锋要塞墓地' WHERE ID=1369;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='黑锋要塞墓地 - 第二/三章' WHERE ID=1370;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='黑锋要塞墓地 - 第四章' WHERE ID=1371;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='安戈洛环形山，塑造者之台' WHERE ID=1372;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='尘泥沼泽，塞拉摩安全点' WHERE ID=1373;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='杜隆塔尔，奥格瑞玛安全点' WHERE ID=1374;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='暴风城，暴风城安全点' WHERE ID=1375;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='嚎风峡湾，乌特加德2 墓地' WHERE ID=1376;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='无尽之海 - 安全点提瑞斯法' WHERE ID=1377;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='杜隆塔尔，奥格瑞玛安全点2' WHERE ID=1378;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='索拉查盆地，雷暴台地墓地' WHERE ID=1379;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='晶歌森林，联盟墓地' WHERE ID=1380;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冰冠冰川，银色前线基地' WHERE ID=1381;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='风暴峭壁，瓦基里安墓地' WHERE ID=1383;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='风暴峭壁，奥杜尔墓地' WHERE ID=1384;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='风暴峭壁，神殿东墓地' WHERE ID=1385;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='风暴峭壁，神殿西墓地' WHERE ID=1387;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='风暴峭壁，霜原墓地' WHERE ID=1388;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='晶歌森林，西墓地' WHERE ID=1391;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='晶歌森林，部落墓地' WHERE ID=1392;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='龙骨荒野，纳克萨玛斯墓地' WHERE ID=1393;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='龙骨荒野，冰雾墓地' WHERE ID=1394;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冰冠冰川，采掘场墓地' WHERE ID=1395;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冰冠冰川，维库中部墓地' WHERE ID=1396;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冰冠冰川，东北寒冰墓地' WHERE ID=1397;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='灰熊丘陵，达克萨隆墓地' WHERE ID=1398;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='诺森德BG - 防御者起始点' WHERE ID=1399;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='风暴峭壁，造物者神殿墓地' WHERE ID=1400;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='风暴峭壁，雪流墓地' WHERE ID=1401;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='风暴峭壁，风暴神殿墓地' WHERE ID=1402;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='风暴峭壁， K3 墓地' WHERE ID=1403;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='索拉查盆地，狂心墓地' WHERE ID=1404;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='东瘟疫之地：阿彻鲁斯' WHERE ID=1405;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冰冠冰川，尤顿海姆墓地' WHERE ID=1407;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='风暴峭壁，山底平原墓地' WHERE ID=1408;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='幽暗城 -联盟- 天谴之门' WHERE ID=1409;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='AAAAA Test Port Loc' WHERE ID=1410;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='奥特兰克山脉 -中部墓地' WHERE ID=1411;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冬泉谷， 霜刃豹墓地' WHERE ID=1416;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冬泉谷，十字路口墓地' WHERE ID=1417;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冬泉谷，暗语峡谷墓地' WHERE ID=1418;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='艾萨拉，乌索兰' WHERE ID=1419;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='艾萨拉，凄凉山' WHERE ID=1420;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='凄凉之地，幽灵岗哨' WHERE ID=1421;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='凄凉之地，萨瑟里斯海岸' WHERE ID=1422;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='凄凉之地，玛诺洛克集会所' WHERE ID=1423;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='凄凉之地，玛格拉姆村' WHERE ID=1424;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='凄凉之地，路旁' WHERE ID=1425;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='灰谷，艾森娜神殿' WHERE ID=1426;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='灰谷，夜歌森林' WHERE ID=1427;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='石爪山脉，狂风峭壁' WHERE ID=1428;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='石爪山脉，暗色湖' WHERE ID=1429;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='贫瘠之地，遗忘之池' WHERE ID=1430;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='贫瘠之地，北部墓地' WHERE ID=1431;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='贫瘠之地，迅猛龙巢穴' WHERE ID=1432;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='贫瘠之地，中部墓地' WHERE ID=1433;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='贫瘠之地，东墓地' WHERE ID=1434;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='莫高雷，东南墓地' WHERE ID=1435;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='莫高雷，赤色石' WHERE ID=1436;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='千针石林，乱风岗' WHERE ID=1437;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='千针石林，沙漠赛道' WHERE ID=1438;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='塔纳利斯，西南墓地' WHERE ID=1439;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='塔纳利斯，深沙平原' WHERE ID=1440;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='菲拉斯，伊斯迪尔废墟' WHERE ID=1441;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='菲拉斯，低地荒野' WHERE ID=1442;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='菲拉斯，双塔山' WHERE ID=1443;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='希利苏斯，雷戈虫巢' WHERE ID=1444;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='希利苏斯，暮光营地' WHERE ID=1445;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='阿拉希高地，激流堡' WHERE ID=1446;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='希尔斯布莱德丘陵，索拉丁之墙' WHERE ID=1447;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='东瘟疫之地，北谷' WHERE ID=1448;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='东瘟疫之地，斯坦索姆' WHERE ID=1449;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='东瘟疫之地，西部墓地' WHERE ID=1450;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='西瘟疫之地，壁炉谷' WHERE ID=1451;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='希尔斯布莱德丘陵，希尔斯布莱德农场' WHERE ID=1452;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='辛特兰，瑟拉丹' WHERE ID=1453;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='辛特兰，沙德拉洛' WHERE ID=1454;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='湿地，日落沼泽' WHERE ID=1455;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='湿地，南大道' WHERE ID=1456;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='湿地，恐龙岭' WHERE ID=1457;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='荆棘谷，古拉巴什竞技场' WHERE ID=1458;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='荆棘谷，中部墓地' WHERE ID=1459;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='荆棘谷，野人海岸' WHERE ID=1460;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='暮色森林，中部墓地' WHERE ID=1461;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='西部荒野，比首岭' WHERE ID=1462;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='西部荒野，长滩' WHERE ID=1463;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='诅咒之地，黑暗之门' WHERE ID=1464;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='悲伤沼泽，泪水之池' WHERE ID=1465;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='悲伤沼泽，断矛' WHERE ID=1466;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='赤脊山，石堡' WHERE ID=1467;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='艾尔文森林，阿祖拉之塔' WHERE ID=1468;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='燃烧平原，黑石山' WHERE ID=1469;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='燃烧平原，东墓地' WHERE ID=1470;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='丹莫罗，涌冰湖' WHERE ID=1471;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='丹莫罗，东大道' WHERE ID=1472;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='洛克莫丹，洛克湖' WHERE ID=1473;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冬拥湖，城堡墓地（室内）' WHERE ID=1474;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='石爪山脉，东南墓地' WHERE ID=1476;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='龙骨荒野，水晶裂痕墓地' WHERE ID=1477;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冰冠冰川，银色比武场墓地' WHERE ID=1478;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冰冠冰川战场 - 墓地 - 码头' WHERE ID=1480;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冰冠冰川战场 - 墓地 - 飞艇基地' WHERE ID=1481;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冰冠冰川战场 - 墓地 - 车间' WHERE ID=1482;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冰冠冰川战场 - 墓地 - 联盟默认' WHERE ID=1483;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冰冠冰川战场 - 墓地 - 部落默认' WHERE ID=1484;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冰冠冰川战场 - 墓地 - 联盟要塞' WHERE ID=1485;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冰冠冰川战场 - 墓地 - 部落要塞' WHERE ID=1486;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='贫瘠之地，荣誉岗哨' WHERE ID=1493;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='尘泥沼泽，龙人泥沼' WHERE ID=1681;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='冰冠冰川，冰冠堡垒墓地' WHERE ID=1682;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='太阳之井 - 奎尔德拉入口' WHERE ID=1683;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='AAA - Arena (Dev Test)' WHERE ID=1691;
UPDATE dbc_worldsafelocs SET AreaName_Lang_enCN='Howling Fjord, Frostblade GY' WHERE ID=1720;
