UPDATE dbc_spellrange SET DisplayName_Lang_enCN='自身', DisplayNameShort_Lang_enCN='自身' WHERE ID=1;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='作战范围', DisplayNameShort_Lang_enCN='作战范围' WHERE ID=2;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='较近', DisplayNameShort_Lang_enCN='较近' WHERE ID=3;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='中程', DisplayNameShort_Lang_enCN='中程' WHERE ID=4;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='较远', DisplayNameShort_Lang_enCN='较远' WHERE ID=5;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='视野范围', DisplayNameShort_Lang_enCN='视野范围' WHERE ID=6;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='近身', DisplayNameShort_Lang_enCN='近身' WHERE ID=7;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='较近', DisplayNameShort_Lang_enCN='较近' WHERE ID=8;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='中程', DisplayNameShort_Lang_enCN='中程' WHERE ID=9;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='较远', DisplayNameShort_Lang_enCN='较远' WHERE ID=10;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='近程', DisplayNameShort_Lang_enCN='近程' WHERE ID=11;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='交互范围', DisplayNameShort_Lang_enCN='交互范围' WHERE ID=12;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='任意地点', DisplayNameShort_Lang_enCN='任意地点' WHERE ID=13;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='超远程', DisplayNameShort_Lang_enCN='超远程' WHERE ID=14;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='中近程', DisplayNameShort_Lang_enCN='中近程' WHERE ID=34;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='中远程', DisplayNameShort_Lang_enCN='中远程' WHERE ID=35;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='远程', DisplayNameShort_Lang_enCN='远程' WHERE ID=36;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='延长范围', DisplayNameShort_Lang_enCN='延长范围' WHERE ID=37;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='额外中程', DisplayNameShort_Lang_enCN='额外中程' WHERE ID=38;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Geoff Monster Shoot', DisplayNameShort_Lang_enCN='Geoff' WHERE ID=54;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Ranged Weapon', DisplayNameShort_Lang_enCN='Ranged' WHERE ID=74;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Sting', DisplayNameShort_Lang_enCN='Sting' WHERE ID=94;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Charge', DisplayNameShort_Lang_enCN='Charge' WHERE ID=95;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Trap', DisplayNameShort_Lang_enCN='Trap' WHERE ID=96;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Hunter Range', DisplayNameShort_Lang_enCN='Hunter' WHERE ID=114;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Tower 80', DisplayNameShort_Lang_enCN='Tower' WHERE ID=134;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Tower 100', DisplayNameShort_Lang_enCN='Tower' WHERE ID=135;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Thirty-to-80', DisplayNameShort_Lang_enCN='Thirty-to-80' WHERE ID=136;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Eight yards', DisplayNameShort_Lang_enCN='Very Short' WHERE ID=137;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Long Range Hunter Shoot', DisplayNameShort_Lang_enCN='Hunter Long' WHERE ID=139;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Six yards', DisplayNameShort_Lang_enCN='Six yards' WHERE ID=140;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Seven yards', DisplayNameShort_Lang_enCN='Seven yards' WHERE ID=141;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Valgarde 8/100', DisplayNameShort_Lang_enCN='Valgarde' WHERE ID=150;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Long Range Hunter Shoot', DisplayNameShort_Lang_enCN='Hunter 45' WHERE ID=151;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Super Long', DisplayNameShort_Lang_enCN='Super Long' WHERE ID=152;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Charge, 60', DisplayNameShort_Lang_enCN='Huge Charge' WHERE ID=153;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Tower 80, 10', DisplayNameShort_Lang_enCN='Tower 10' WHERE ID=154;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Hunter Range (Long)', DisplayNameShort_Lang_enCN='Hunter (Long)' WHERE ID=155;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Boulder Range', DisplayNameShort_Lang_enCN='Boulder' WHERE ID=156;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Ninety', DisplayNameShort_Lang_enCN='Ninety' WHERE ID=157;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Super Long, 15 Min', DisplayNameShort_Lang_enCN='Super Long' WHERE ID=158;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='TEST - Long Range', DisplayNameShort_Lang_enCN='TestLong' WHERE ID=159;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Medium/Long Range', DisplayNameShort_Lang_enCN='Medium/Long' WHERE ID=160;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Short/Long Range', DisplayNameShort_Lang_enCN='Short/Long' WHERE ID=161;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Medium/Short Range', DisplayNameShort_Lang_enCN='Medium/Short' WHERE ID=162;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Death Grip', DisplayNameShort_Lang_enCN='Death Grip' WHERE ID=163;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Catapult Range', DisplayNameShort_Lang_enCN='Catapult' WHERE ID=164;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Fourteen yards', DisplayNameShort_Lang_enCN='Shorter' WHERE ID=165;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Thirteen yards', DisplayNameShort_Lang_enCN='Shorter' WHERE ID=166;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Super Long (Min Range)', DisplayNameShort_Lang_enCN='Super Long' WHERE ID=167;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Medium-Long Range (38)', DisplayNameShort_Lang_enCN='Medium-Long' WHERE ID=168;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Three Yards', DisplayNameShort_Lang_enCN='Three Yards' WHERE ID=169;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Fifty Five Yards', DisplayNameShort_Lang_enCN='Extended' WHERE ID=170;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Min Range 1, 10', DisplayNameShort_Lang_enCN='Very Short' WHERE ID=171;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Eleven yards', DisplayNameShort_Lang_enCN='Shorter' WHERE ID=172;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Anywhere (Combat Min Range)', DisplayNameShort_Lang_enCN='Hunter Long' WHERE ID=173;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='U L T R A', DisplayNameShort_Lang_enCN='U L T R A' WHERE ID=174;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Seventy yards', DisplayNameShort_Lang_enCN='Extended' WHERE ID=176;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Donut 20-70', DisplayNameShort_Lang_enCN='Donut 20-70' WHERE ID=177;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Min Range 5, 15', DisplayNameShort_Lang_enCN='Shorter' WHERE ID=179;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Tournament - Ranged', DisplayNameShort_Lang_enCN='Argent Tournament - Ranged' WHERE ID=180;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Two-Hundred Yard Range', DisplayNameShort_Lang_enCN='200' WHERE ID=181;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Min Range 5, 25', DisplayNameShort_Lang_enCN='Medium' WHERE ID=184;
UPDATE dbc_spellrange SET DisplayName_Lang_enCN='Three Hundred Yards', DisplayNameShort_Lang_enCN='300' WHERE ID=187;
