-- esES lang
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Humano', `Name_Female_Lang_esES` = 'Humana', `Name_Male_Lang_esES` = 'Humano' WHERE `ID` = 1;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Orco', `Name_Female_Lang_esES` = 'Orco', `Name_Male_Lang_esES` = 'Orco' WHERE `ID` = 2;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Enano', `Name_Female_Lang_esES` = 'Enana', `Name_Male_Lang_esES` = 'Enano' WHERE `ID` = 3;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Elfo de la noche', `Name_Female_Lang_esES` = 'Elfa de la noche', `Name_Male_Lang_esES` = 'Elfo de la noche' WHERE `ID` = 4;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'No-muerto', `Name_Female_Lang_esES` = 'No-muerta', `Name_Male_Lang_esES` = 'No-muerto' WHERE `ID` = 5;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Tauren', `Name_Female_Lang_esES` = 'Tauren', `Name_Male_Lang_esES` = 'Tauren' WHERE `ID` = 6;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Gnomo', `Name_Female_Lang_esES` = 'Gnoma', `Name_Male_Lang_esES` = 'Gnomo' WHERE `ID` = 7;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Trol', `Name_Female_Lang_esES` = 'Trol', `Name_Male_Lang_esES` = 'Trol' WHERE `ID` = 8;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Goblin', `Name_Female_Lang_esES` = 'Goblin', `Name_Male_Lang_esES` = 'Goblin' WHERE `ID` = 9;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Elfo de sangre', `Name_Female_Lang_esES` = 'Elfa de sangre', `Name_Male_Lang_esES` = 'Elfo de sangre' WHERE `ID` = 10;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Draenei', `Name_Female_Lang_esES` = 'Draenei', `Name_Male_Lang_esES` = 'Draenei' WHERE `ID` = 11;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Orco vil', `Name_Female_Lang_esES` = 'Orco vil', `Name_Male_Lang_esES` = 'Orco vil' WHERE `ID` = 12;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Naga', `Name_Female_Lang_esES` = 'Naga', `Name_Male_Lang_esES` = 'Naga' WHERE `ID` = 13;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Tábido', `Name_Female_Lang_esES` = 'Tábida', `Name_Male_Lang_esES` = 'Tábido' WHERE `ID` = 14;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Esqueleto', `Name_Female_Lang_esES` = 'Esqueleto', `Name_Male_Lang_esES` = 'Esqueleto' WHERE `ID` = 15;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Vrykul', `Name_Female_Lang_esES` = 'Vrykul', `Name_Male_Lang_esES` = 'Vrykul' WHERE `ID` = 16;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Colmillarr', `Name_Female_Lang_esES` = 'Colmillarr', `Name_Male_Lang_esES` = 'Colmillarr' WHERE `ID` = 17;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Trol de bosque', `Name_Female_Lang_esES` = 'Trol de bosque', `Name_Male_Lang_esES` = 'Trol de bosque' WHERE `ID` = 18;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Taunka', `Name_Female_Lang_esES` = 'Taunka', `Name_Male_Lang_esES` = 'Taunka' WHERE `ID` = 19;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Esqueleto de Rasganorte', `Name_Female_Lang_esES` = 'Esqueleto de Rasganorte', `Name_Male_Lang_esES` = 'Esqueleto de Rasganorte' WHERE `ID` = 20;
UPDATE `dbc_chrraces` SET `Name_Lang_esES` = 'Trol de hielo', `Name_Female_Lang_esES` = 'Trol de hielo', `Name_Male_Lang_esES` = 'Trol de hielo' WHERE `ID` = 21;
-- frFR lang
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Humain', `Name_Female_Lang_frFR` = 'Humaine', `Name_Male_Lang_frFR` = 'Humain' WHERE `ID` = 1;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Orc', `Name_Female_Lang_frFR` = 'Orque', `Name_Male_Lang_frFR` = 'Orc' WHERE `ID` = 2;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Nain', `Name_Female_Lang_frFR` = 'Naine', `Name_Male_Lang_frFR` = 'Nain' WHERE `ID` = 3;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Elfe de la nuit', `Name_Female_Lang_frFR` = 'Elfe de la nuit', `Name_Male_Lang_frFR` = 'Elfe de la nuit' WHERE `ID` = 4;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Mort-vivant', `Name_Female_Lang_frFR` = 'Morte-vivante', `Name_Male_Lang_frFR` = 'Mort-vivant' WHERE `ID` = 5;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Tauren', `Name_Female_Lang_frFR` = 'Taurène', `Name_Male_Lang_frFR` = 'Tauren' WHERE `ID` = 6;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Gnome', `Name_Female_Lang_frFR` = 'Gnome', `Name_Male_Lang_frFR` = 'Gnome' WHERE `ID` = 7;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Troll', `Name_Female_Lang_frFR` = 'Trollesse', `Name_Male_Lang_frFR` = 'Troll' WHERE `ID` = 8;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Gobelin', `Name_Female_Lang_frFR` = 'Gobeline', `Name_Male_Lang_frFR` = 'Gobelin' WHERE `ID` = 9;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Elfe de sang', `Name_Female_Lang_frFR` = 'Elfe de sang', `Name_Male_Lang_frFR` = 'Elfe de sang' WHERE `ID` = 10;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Draeneï', `Name_Female_Lang_frFR` = 'Draeneï', `Name_Male_Lang_frFR` = 'Draeneï' WHERE `ID` = 11;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Gangr\'orc', `Name_Female_Lang_frFR` = 'Gangr\'orque', `Name_Male_Lang_frFR` = 'Gangr\'orc' WHERE `ID` = 12;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Naga', `Name_Female_Lang_frFR` = 'Naga', `Name_Male_Lang_frFR` = 'Naga' WHERE `ID` = 13;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Roué', `Name_Female_Lang_frFR` = 'Rouée', `Name_Male_Lang_frFR` = 'Roué' WHERE `ID` = 14;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Squelette', `Name_Female_Lang_frFR` = 'Squelette', `Name_Male_Lang_frFR` = 'Squelette' WHERE `ID` = 15;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Vrykul', `Name_Female_Lang_frFR` = 'Vrykule', `Name_Male_Lang_frFR` = 'Vrykul' WHERE `ID` = 16;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Rohart', `Name_Female_Lang_frFR` = 'Rohart', `Name_Male_Lang_frFR` = 'Rohart' WHERE `ID` = 17;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Troll des forêts', `Name_Female_Lang_frFR` = 'Trollesse des forêts', `Name_Male_Lang_frFR` = 'Troll des forêts' WHERE `ID` = 18;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Taunka', `Name_Female_Lang_frFR` = 'Taunka', `Name_Male_Lang_frFR` = 'Taunka' WHERE `ID` = 19;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Squelette du Norfendre', `Name_Female_Lang_frFR` = 'Squelette du Norfendre', `Name_Male_Lang_frFR` = 'Squelette du Norfendre' WHERE `ID` = 20;
UPDATE `dbc_chrraces` SET `Name_Lang_frFR` = 'Troll des glaces', `Name_Female_Lang_frFR` = 'Trollesse des glaces', `Name_Male_Lang_frFR` = 'Troll des glaces' WHERE `ID` = 21;
