UPDATE dbc_taxinodes SET Name_Lang_koKR='노스샤이어 대성당' WHERE ID=1;
UPDATE dbc_taxinodes SET Name_Lang_koKR='스톰윈드 (엘윈 숲)' WHERE ID=2;
UPDATE dbc_taxinodes SET Name_Lang_koKR='프로그래머의 섬' WHERE ID=3;
UPDATE dbc_taxinodes SET Name_Lang_koKR='감시의 언덕 (서부 몰락지대)' WHERE ID=4;
UPDATE dbc_taxinodes SET Name_Lang_koKR='레이크샤이어 (붉은마루 산맥)' WHERE ID=5;
UPDATE dbc_taxinodes SET Name_Lang_koKR='아이언포지 (던 모로)' WHERE ID=6;
UPDATE dbc_taxinodes SET Name_Lang_koKR='메네실 항구 (저습지)' WHERE ID=7;
UPDATE dbc_taxinodes SET Name_Lang_koKR='텔사마 (모단 호수)' WHERE ID=8;
UPDATE dbc_taxinodes SET Name_Lang_koKR='무법항 (가시덤불 골짜기)' WHERE ID=9;
UPDATE dbc_taxinodes SET Name_Lang_koKR='공동묘지 (은빛소나무 숲)' WHERE ID=10;
UPDATE dbc_taxinodes SET Name_Lang_koKR='언더시티 (티리스팔 숲)' WHERE ID=11;
UPDATE dbc_taxinodes SET Name_Lang_koKR='다크샤이어 (그늘숲)' WHERE ID=12;
UPDATE dbc_taxinodes SET Name_Lang_koKR='타렌 밀농장 (힐스브래드 구릉지)' WHERE ID=13;
UPDATE dbc_taxinodes SET Name_Lang_koKR='사우스쇼어 (힐스브래드 구릉지)' WHERE ID=14;
UPDATE dbc_taxinodes SET Name_Lang_koKR='동부 오염지역' WHERE ID=15;
UPDATE dbc_taxinodes SET Name_Lang_koKR='임시 주둔지 (아라시 고원)' WHERE ID=16;
UPDATE dbc_taxinodes SET Name_Lang_koKR='해머폴 (아라시 고원)' WHERE ID=17;
UPDATE dbc_taxinodes SET Name_Lang_koKR='무법항 (가시덤불 골짜기)' WHERE ID=18;
UPDATE dbc_taxinodes SET Name_Lang_koKR='무법항 (가시덤불 골짜기)' WHERE ID=19;
UPDATE dbc_taxinodes SET Name_Lang_koKR='그롬골 (가시덤불 골짜기)' WHERE ID=20;
UPDATE dbc_taxinodes SET Name_Lang_koKR='카르가스 (황야의 땅)' WHERE ID=21;
UPDATE dbc_taxinodes SET Name_Lang_koKR='썬더 블러프 (멀고어)' WHERE ID=22;
UPDATE dbc_taxinodes SET Name_Lang_koKR='오그리마 (듀로타)' WHERE ID=23;
UPDATE dbc_taxinodes SET Name_Lang_koKR='일반 (세계 목적지 002)' WHERE ID=24;
UPDATE dbc_taxinodes SET Name_Lang_koKR='크로스로드 (불모의 땅)' WHERE ID=25;
UPDATE dbc_taxinodes SET Name_Lang_koKR='아우버다인 (어둠의 해안)' WHERE ID=26;
UPDATE dbc_taxinodes SET Name_Lang_koKR='루테란 마을 (텔드랏실)' WHERE ID=27;
UPDATE dbc_taxinodes SET Name_Lang_koKR='아스트라나르 (잿빛 골짜기)' WHERE ID=28;
UPDATE dbc_taxinodes SET Name_Lang_koKR='해바위 야영지, 돌발톱 산맥' WHERE ID=29;
UPDATE dbc_taxinodes SET Name_Lang_koKR='높새바람 봉우리 (버섯구름 봉우리)' WHERE ID=30;
UPDATE dbc_taxinodes SET Name_Lang_koKR='탈라나르 (페랄라스)' WHERE ID=31;
UPDATE dbc_taxinodes SET Name_Lang_koKR='테라모어 섬 (먼지진흙 습지대)' WHERE ID=32;
UPDATE dbc_taxinodes SET Name_Lang_koKR='돌발톱 봉우리 (돌발톱 산맥)' WHERE ID=33;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송 수단 (무법항)' WHERE ID=34;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송 수단 (오그리마)' WHERE ID=35;
UPDATE dbc_taxinodes SET Name_Lang_koKR='일반 (세계 목적지 001)' WHERE ID=36;
UPDATE dbc_taxinodes SET Name_Lang_koKR='나이젤의 야영지 (잊혀진 땅)' WHERE ID=37;
UPDATE dbc_taxinodes SET Name_Lang_koKR='그늘수렵 마을 (잊혀진 땅)' WHERE ID=38;
UPDATE dbc_taxinodes SET Name_Lang_koKR='가젯잔 (타나리스)' WHERE ID=39;
UPDATE dbc_taxinodes SET Name_Lang_koKR='가젯잔 (타나리스)' WHERE ID=40;
UPDATE dbc_taxinodes SET Name_Lang_koKR='페더문 요새 (페랄라스)' WHERE ID=41;
UPDATE dbc_taxinodes SET Name_Lang_koKR='모자케 야영지 (페랄라스)' WHERE ID=42;
UPDATE dbc_taxinodes SET Name_Lang_koKR='맹금의 봉우리 (동부 내륙지)' WHERE ID=43;
UPDATE dbc_taxinodes SET Name_Lang_koKR='발로르모크 (아즈샤라)' WHERE ID=44;
UPDATE dbc_taxinodes SET Name_Lang_koKR='네더가드 요새 (저주받은 땅)' WHERE ID=45;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송 수단 (사우스쇼어)' WHERE ID=46;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송 수단 (그롬골)' WHERE ID=47;
UPDATE dbc_taxinodes SET Name_Lang_koKR='피멍울 초소 (악령의 숲)' WHERE ID=48;
UPDATE dbc_taxinodes SET Name_Lang_koKR='달의 숲' WHERE ID=49;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송 수단 (메네실 항구)' WHERE ID=50;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송 수단 (아우버다인)' WHERE ID=51;
UPDATE dbc_taxinodes SET Name_Lang_koKR='눈망루 마을 (여명의 설원)' WHERE ID=52;
UPDATE dbc_taxinodes SET Name_Lang_koKR='눈망루 마을 (여명의 설원)' WHERE ID=53;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송 수단 (페더문)' WHERE ID=54;
UPDATE dbc_taxinodes SET Name_Lang_koKR='담쟁이 마을 (먼지진흙 습지대)' WHERE ID=55;
UPDATE dbc_taxinodes SET Name_Lang_koKR='스토나드 (슬픔의 늪)' WHERE ID=56;
UPDATE dbc_taxinodes SET Name_Lang_koKR='고기잡이 마을 (텔드랏실)' WHERE ID=57;
UPDATE dbc_taxinodes SET Name_Lang_koKR='조람가르 전초기지 (잿빛 골짜기)' WHERE ID=58;
UPDATE dbc_taxinodes SET Name_Lang_koKR='던 발다르 (알터랙 계곡)' WHERE ID=59;
UPDATE dbc_taxinodes SET Name_Lang_koKR='서리늑대 요새 (알터랙 계곡)' WHERE ID=60;
UPDATE dbc_taxinodes SET Name_Lang_koKR='토막나무 주둔지 (잿빛 골짜기)' WHERE ID=61;
UPDATE dbc_taxinodes SET Name_Lang_koKR='나이트헤이븐 (달의 숲)' WHERE ID=62;
UPDATE dbc_taxinodes SET Name_Lang_koKR='나이트헤이븐 (달의 숲)' WHERE ID=63;
UPDATE dbc_taxinodes SET Name_Lang_koKR='탈렌드리스 초소 (아즈샤라)' WHERE ID=64;
UPDATE dbc_taxinodes SET Name_Lang_koKR='갈퀴가지 숲 (악령의 숲)' WHERE ID=65;
UPDATE dbc_taxinodes SET Name_Lang_koKR='서리바람 야영지 (서부 역병지대)' WHERE ID=66;
UPDATE dbc_taxinodes SET Name_Lang_koKR='희망의 빛 예배당 (동부 역병지대)' WHERE ID=67;
UPDATE dbc_taxinodes SET Name_Lang_koKR='희망의 빛 예배당 (동부 역병지대)' WHERE ID=68;
UPDATE dbc_taxinodes SET Name_Lang_koKR='달의 숲' WHERE ID=69;
UPDATE dbc_taxinodes SET Name_Lang_koKR='화염 마루 (불타는 평원)' WHERE ID=70;
UPDATE dbc_taxinodes SET Name_Lang_koKR='모건의 망루 (불타는 평원)' WHERE ID=71;
UPDATE dbc_taxinodes SET Name_Lang_koKR='세나리온 요새 (실리더스)' WHERE ID=72;
UPDATE dbc_taxinodes SET Name_Lang_koKR='세나리온 요새 (실리더스)' WHERE ID=73;
UPDATE dbc_taxinodes SET Name_Lang_koKR='토륨 조합 거점 (이글거리는 협곡)' WHERE ID=74;
UPDATE dbc_taxinodes SET Name_Lang_koKR='토륨 조합 거점 (이글거리는 협곡)' WHERE ID=75;
UPDATE dbc_taxinodes SET Name_Lang_koKR='레반터스크 마을 (동부 내륙지)' WHERE ID=76;
UPDATE dbc_taxinodes SET Name_Lang_koKR='타우라조 야영지 (불모의 땅)' WHERE ID=77;
UPDATE dbc_taxinodes SET Name_Lang_koKR='낙스라마스' WHERE ID=78;
UPDATE dbc_taxinodes SET Name_Lang_koKR='마샬의 야영지 (운고로 분화구)' WHERE ID=79;
UPDATE dbc_taxinodes SET Name_Lang_koKR='톱니항 (불모의 땅)' WHERE ID=80;
UPDATE dbc_taxinodes SET Name_Lang_koKR='필르밍' WHERE ID=81;
UPDATE dbc_taxinodes SET Name_Lang_koKR='실버문' WHERE ID=82;
UPDATE dbc_taxinodes SET Name_Lang_koKR='트랜퀼리엔 (유령의 땅)' WHERE ID=83;
UPDATE dbc_taxinodes SET Name_Lang_koKR='역병의 숲 경비탑 (동부 역병지대)' WHERE ID=84;
UPDATE dbc_taxinodes SET Name_Lang_koKR='북부관문 경비탑 (동부 역병지대)' WHERE ID=85;
UPDATE dbc_taxinodes SET Name_Lang_koKR='동부방벽 경비탑 (동부 역병지대)' WHERE ID=86;
UPDATE dbc_taxinodes SET Name_Lang_koKR='산마루 경비탑 (동부 역병지대)' WHERE ID=87;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단 (엑소다르)' WHERE ID=88;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단 (테라모어)' WHERE ID=89;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단 (언더시티)' WHERE ID=90;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Azuremyst Shaman Target' WHERE ID=91;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Azuremyst Shaman Start' WHERE ID=92;
UPDATE dbc_taxinodes SET Name_Lang_koKR='핏빛 감시초소 (핏빛안개 섬)' WHERE ID=93;
UPDATE dbc_taxinodes SET Name_Lang_koKR='엑소다르' WHERE ID=94;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Zangarmarsh - Quest - As the Crow Flies' WHERE ID=95;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Zangarmarsh - Quest - As the Crow Flies - End' WHERE ID=96;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Elekk Path to Kessel' WHERE ID=97;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Elekk to Kessel Target' WHERE ID=98;
UPDATE dbc_taxinodes SET Name_Lang_koKR='스랄마 (지옥불 반도)' WHERE ID=99;
UPDATE dbc_taxinodes SET Name_Lang_koKR='명예의 요새 (지옥불 반도)' WHERE ID=100;
UPDATE dbc_taxinodes SET Name_Lang_koKR='텔하마트 사원 (지옥불 반도)' WHERE ID=101;
UPDATE dbc_taxinodes SET Name_Lang_koKR='매의 감시탑 (지옥불 반도)' WHERE ID=102;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Nagrand - PvP - Attack Run Start 1' WHERE ID=103;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Nagrand - PvP - Attack Run End 1' WHERE ID=104;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Nagrand - PvP - Attack Run Start 2' WHERE ID=105;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Nagrand - PvP - Attack Run End 2' WHERE ID=106;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Nagrand - PvP - Attack Run Start 3' WHERE ID=107;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Nagrand - PvP - Attack Run End 3' WHERE ID=108;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Nagrand - PvP - Attack Run Start 4' WHERE ID=109;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Nagrand - PvP - Attack Run End 4' WHERE ID=110;
UPDATE dbc_taxinodes SET Name_Lang_koKR='영원노래 숲 - 더스크위더 순간이동' WHERE ID=111;
UPDATE dbc_taxinodes SET Name_Lang_koKR='영원노래 숲 - 더스크위더 순간이동' WHERE ID=112;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Nethrandamus Start' WHERE ID=113;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Nethrandamus End Target' WHERE ID=114;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Caverns of Time OH - Begin' WHERE ID=115;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Caverns of Time OH - End' WHERE ID=116;
UPDATE dbc_taxinodes SET Name_Lang_koKR='텔레도르 (장가르 습지대)' WHERE ID=117;
UPDATE dbc_taxinodes SET Name_Lang_koKR='자브라진 (장가르 습지대)' WHERE ID=118;
UPDATE dbc_taxinodes SET Name_Lang_koKR='텔라아르 (나그란드)' WHERE ID=119;
UPDATE dbc_taxinodes SET Name_Lang_koKR='가라다르 (나그란드)' WHERE ID=120;
UPDATE dbc_taxinodes SET Name_Lang_koKR='알레리아 성채 (테로카르 숲)' WHERE ID=121;
UPDATE dbc_taxinodes SET Name_Lang_koKR='52번 구역 (황천의 폭풍)' WHERE ID=122;
UPDATE dbc_taxinodes SET Name_Lang_koKR='어둠달 마을 (어둠달 골짜기)' WHERE ID=123;
UPDATE dbc_taxinodes SET Name_Lang_koKR='와일드해머 성채 (어둠달 골짜기)' WHERE ID=124;
UPDATE dbc_taxinodes SET Name_Lang_koKR='실바나르 (칼날 산맥)' WHERE ID=125;
UPDATE dbc_taxinodes SET Name_Lang_koKR='천둥군주 요새 (칼날 산맥)' WHERE ID=126;
UPDATE dbc_taxinodes SET Name_Lang_koKR='돌망치 요새 (테로카르 숲)' WHERE ID=127;
UPDATE dbc_taxinodes SET Name_Lang_koKR='샤트라스 (테로카르 숲)' WHERE ID=128;
UPDATE dbc_taxinodes SET Name_Lang_koKR='어둠의 문 (지옥불 반도, 얼라이언스)' WHERE ID=129;
UPDATE dbc_taxinodes SET Name_Lang_koKR='어둠의 문 (지옥불 반도, 호드)' WHERE ID=130;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Horde Hellfire Start' WHERE ID=131;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Horde Hellfire End' WHERE ID=132;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Hellfire Peninsula (Alliance Path) Start' WHERE ID=133;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Hellfire Peninsula (Alliance) End' WHERE ID=134;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Hellfire, Aerial Mission (Horde) Start' WHERE ID=135;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Hellfire, Aerial Mission (Horde) End' WHERE ID=136;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Hellfire, Aerial Mission (Alliance) Start' WHERE ID=137;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Hellfire, Aerial Mission (Alliance) End' WHERE ID=138;
UPDATE dbc_taxinodes SET Name_Lang_koKR='폭풍 첨탑 (황천의 폭풍)' WHERE ID=139;
UPDATE dbc_taxinodes SET Name_Lang_koKR='샤타르 제단 (어둠달 골짜기)' WHERE ID=140;
UPDATE dbc_taxinodes SET Name_Lang_koKR='해골망치 마루 (지옥불 반도)' WHERE ID=141;
UPDATE dbc_taxinodes SET Name_Lang_koKR='지옥절단기 함락지 (지옥불 반도)' WHERE ID=142;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Caverns of Time (Intro Flight Path) (End)' WHERE ID=143;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Caverns of Time (Intro Flight Path) (Start)' WHERE ID=144;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 황천의 폭풍 - 은신 비행 - 시작' WHERE ID=145;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 황천의 폭풍 - 은신 비행 - 끝' WHERE ID=146;
UPDATE dbc_taxinodes SET Name_Lang_koKR='교두보 거점 (지옥불 반도)' WHERE ID=147;
UPDATE dbc_taxinodes SET Name_Lang_koKR='징검다리 거점 (지옥불 반도 공습)' WHERE ID=148;
UPDATE dbc_taxinodes SET Name_Lang_koKR='징검다리 거점 (지옥불 반도)' WHERE ID=149;
UPDATE dbc_taxinodes SET Name_Lang_koKR='코스모렌치 (황천의 폭풍)' WHERE ID=150;
UPDATE dbc_taxinodes SET Name_Lang_koKR='늪쥐 감시초소 (장가르 습지대)' WHERE ID=151;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Netherstorm - Manaforge Ultris (Start)' WHERE ID=152;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Netherstorm - Manaforge Ultris (End)' WHERE ID=153;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Netherstorm - Manaforge Ultris (Second Pass) Start' WHERE ID=154;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Netherstorm - Manaforge Ultris (Second Pass) End' WHERE ID=155;
UPDATE dbc_taxinodes SET Name_Lang_koKR='토쉴리의 연구기지 (칼날 산맥)' WHERE ID=156;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 칼날 산맥 - 예언 안내 - 시작' WHERE ID=157;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 칼날 산맥 - 예언 안내 - 끝' WHERE ID=158;
UPDATE dbc_taxinodes SET Name_Lang_koKR='별의 성소 (어둠달 골짜기)' WHERE ID=159;
UPDATE dbc_taxinodes SET Name_Lang_koKR='영원의 숲 (칼날 산맥)' WHERE ID=160;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 황천의 용 연합 - 시작' WHERE ID=161;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 황천의 용 연합 - 끝' WHERE ID=162;
UPDATE dbc_taxinodes SET Name_Lang_koKR='모크나탈 마을 (칼날 산맥)' WHERE ID=163;
UPDATE dbc_taxinodes SET Name_Lang_koKR='오레보르 피난처 (장가르 습지대)' WHERE ID=164;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단(노스렌드 2)' WHERE ID=165;
UPDATE dbc_taxinodes SET Name_Lang_koKR='에메랄드 성소 (악령의 숲)' WHERE ID=166;
UPDATE dbc_taxinodes SET Name_Lang_koKR='숲의 노래 (잿빛 골짜기)' WHERE ID=167;
UPDATE dbc_taxinodes SET Name_Lang_koKR='촬영 장소' WHERE ID=168;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 황천날개 마루 - 광산 수레 - 남쪽 - 시작점' WHERE ID=169;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 황천날개 마루 - 광산 수레 - 남쪽 - 도착점' WHERE ID=170;
UPDATE dbc_taxinodes SET Name_Lang_koKR='스케티스' WHERE ID=171;
UPDATE dbc_taxinodes SET Name_Lang_koKR='오그릴라' WHERE ID=172;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 야르질 비행 시작' WHERE ID=173;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 야르질 비행 완료' WHERE ID=174;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단(울부짖는 협만)' WHERE ID=175;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 울부짖는 협만 타우렌 통나무배 (시작)' WHERE ID=176;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 울부짖는 협만 타우렌 통나무배 (끝)' WHERE ID=177;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단(북풍의 땅)' WHERE ID=178;
UPDATE dbc_taxinodes SET Name_Lang_koKR='진흙톱니 거점 (먼지진흙 습지대)' WHERE ID=179;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 먼지진흙 습지대 - 알카즈 조사 시작' WHERE ID=180;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 먼지진흙 습지대 - 알카즈 조사 완료' WHERE ID=181;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 울부짖는 협만 - 차단선 돌파 비행선' WHERE ID=182;
UPDATE dbc_taxinodes SET Name_Lang_koKR='발가드 항만 (울부짖는 협만)' WHERE ID=183;
UPDATE dbc_taxinodes SET Name_Lang_koKR='빌더바르 요새 (울부짖는 협만)' WHERE ID=184;
UPDATE dbc_taxinodes SET Name_Lang_koKR='서부경비대 성채 (울부짖는 협만)' WHERE ID=185;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 울부짖는 협만 - 윈드러너 비행 경로 - 시작' WHERE ID=186;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 울부짖는 협만 - 윈드러너 비행 경로 - 끝' WHERE ID=187;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 울부짖는 협만 - 해상 실험 - 시작' WHERE ID=188;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 울부짖는 협만 - 해상 실험 - 끝' WHERE ID=189;
UPDATE dbc_taxinodes SET Name_Lang_koKR='신 아가만드 (울부짖는 협만)' WHERE ID=190;
UPDATE dbc_taxinodes SET Name_Lang_koKR='복수의 상륙지 (울부짖는 협만)' WHERE ID=191;
UPDATE dbc_taxinodes SET Name_Lang_koKR='겨울발굽 야영지 (울부짖는 협만)' WHERE ID=192;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 울부짖는 협만 - 임무: 역병 막기! - 끝' WHERE ID=193;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 울부짖는 협만 - 임무: 역병 막기! - 시작' WHERE ID=194;
UPDATE dbc_taxinodes SET Name_Lang_koKR='반란군 야영지 (가시덤불 골짜기)' WHERE ID=195;
UPDATE dbc_taxinodes SET Name_Lang_koKR='시험용 - SP' WHERE ID=196;
UPDATE dbc_taxinodes SET Name_Lang_koKR='시험용 SP2' WHERE ID=197;
UPDATE dbc_taxinodes SET Name_Lang_koKR='시험용 SP1' WHERE ID=198;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 울부짖는 협만 - 맥고이버 시작' WHERE ID=199;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 울부짖는 협만 - 맥고이버 끝' WHERE ID=200;
UPDATE dbc_taxinodes SET Name_Lang_koKR='진화의 대지 - 카일 라듀 시작' WHERE ID=201;
UPDATE dbc_taxinodes SET Name_Lang_koKR='진화의 대지 - 카일 라듀 종료' WHERE ID=202;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 별의 쉼터 - 윈터가드' WHERE ID=203;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 신 아가만드 - 원한의 초소' WHERE ID=204;
UPDATE dbc_taxinodes SET Name_Lang_koKR='줄아만, 유령의 땅' WHERE ID=205;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단, 페더문 (나이트 엘프 함선)' WHERE ID=206;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 울부짖는 협만 - 자비로운 수녀호 (시작)' WHERE ID=207;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 울부짖는 협만 - 자비로운 수녀호 (끝)' WHERE ID=208;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 태양샘 일일 - 죽음의 흉터 폭탄 투하 - 시작' WHERE ID=209;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 태양샘 일일 - 죽음의 흉터 폭탄 투하 - 종료' WHERE ID=210;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Sunwell Daily - Ship Bombing - Start' WHERE ID=211;
UPDATE dbc_taxinodes SET Name_Lang_koKR='Quest - Sunwell Daily - Ship Bombing - End' WHERE ID=212;
UPDATE dbc_taxinodes SET Name_Lang_koKR='무너진 태양 집결지' WHERE ID=213;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 울부짖는 협만 - 나글파르 (시작)' WHERE ID=214;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 울부짖는 협만 - 나글파르' WHERE ID=215;
UPDATE dbc_taxinodes SET Name_Lang_koKR='' WHERE ID=216;
UPDATE dbc_taxinodes SET Name_Lang_koKR='' WHERE ID=217;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단 (울부짖는 협만) - 승강기 위쪽' WHERE ID=218;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단 (울부짖는 협만) - 승강기 아래쪽' WHERE ID=219;
UPDATE dbc_taxinodes SET Name_Lang_koKR='' WHERE ID=220;
UPDATE dbc_taxinodes SET Name_Lang_koKR='호박석 절벽 (북풍의 땅) - 녹주석 거점으로' WHERE ID=221;
UPDATE dbc_taxinodes SET Name_Lang_koKR='녹주석 거점 (북풍의 땅)' WHERE ID=222;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 나글바르' WHERE ID=223;
UPDATE dbc_taxinodes SET Name_Lang_koKR='북풍의 땅, 나글바르' WHERE ID=224;
UPDATE dbc_taxinodes SET Name_Lang_koKR='호박석 절벽 (북풍의 땅) - 콜다라로' WHERE ID=225;
UPDATE dbc_taxinodes SET Name_Lang_koKR='변위의 보호막 (콜다라)' WHERE ID=226;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단 시험용' WHERE ID=227;
UPDATE dbc_taxinodes SET Name_Lang_koKR='진화의 대지 - 애완동물 실험 시작' WHERE ID=228;
UPDATE dbc_taxinodes SET Name_Lang_koKR='진화의 대지 - 애완동물 실험 시작' WHERE ID=229;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단 (투스카르 01)' WHERE ID=230;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단 (투스카르 02)' WHERE ID=231;
UPDATE dbc_taxinodes SET Name_Lang_koKR='북풍의 땅 - 전쟁노래부족 요새 늑대 시작' WHERE ID=232;
UPDATE dbc_taxinodes SET Name_Lang_koKR='북풍의 땅 - 전쟁노래부족 요새 늑대 끝' WHERE ID=233;
UPDATE dbc_taxinodes SET Name_Lang_koKR='콜다라 절벽 (콜다라)' WHERE ID=234;
UPDATE dbc_taxinodes SET Name_Lang_koKR='변위의 보호막 (콜다라)' WHERE ID=235;
UPDATE dbc_taxinodes SET Name_Lang_koKR='콜다라 (케리스트라자에게서 말리고스)' WHERE ID=236;
UPDATE dbc_taxinodes SET Name_Lang_koKR='콜다라 (케리스트라자 착륙지)' WHERE ID=237;
UPDATE dbc_taxinodes SET Name_Lang_koKR='' WHERE ID=238;
UPDATE dbc_taxinodes SET Name_Lang_koKR='북풍의 땅 - 퀘스트 황혼이 시작' WHERE ID=239;
UPDATE dbc_taxinodes SET Name_Lang_koKR='북풍의 땅 - 퀘스트 황혼이 끝' WHERE ID=240;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단 (용맹의 성채)' WHERE ID=241;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 용의 안식처 - 영혼 환영 - 시작' WHERE ID=242;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 용의 안식처 - 영혼 환영 - 끝' WHERE ID=243;
UPDATE dbc_taxinodes SET Name_Lang_koKR='윈터가드 성채 (용의 안식처)' WHERE ID=244;
UPDATE dbc_taxinodes SET Name_Lang_koKR='용맹의 성채 (북풍의 땅)' WHERE ID=245;
UPDATE dbc_taxinodes SET Name_Lang_koKR='피즈크랭크 비행장 (북풍의 땅)' WHERE ID=246;
UPDATE dbc_taxinodes SET Name_Lang_koKR='별의 쉼터 (용의 안식처)' WHERE ID=247;
UPDATE dbc_taxinodes SET Name_Lang_koKR='연금술사 야영지 (울부짖는 협만)' WHERE ID=248;
UPDATE dbc_taxinodes SET Name_Lang_koKR='원크와 야영지 (회색 구릉지)' WHERE ID=249;
UPDATE dbc_taxinodes SET Name_Lang_koKR='정복의 요새 (회색 구릉지)' WHERE ID=250;
UPDATE dbc_taxinodes SET Name_Lang_koKR='폴드라곤 요새 (용의 안식처)' WHERE ID=251;
UPDATE dbc_taxinodes SET Name_Lang_koKR='고룡쉼터 사원 (용의 안식처)' WHERE ID=252;
UPDATE dbc_taxinodes SET Name_Lang_koKR='호박빛소나무 오두막 (회색 구릉지)' WHERE ID=253;
UPDATE dbc_taxinodes SET Name_Lang_koKR='원한의 초소 (용의 안식처)' WHERE ID=254;
UPDATE dbc_taxinodes SET Name_Lang_koKR='서부 몰락지대 여단 (회색 구릉지)' WHERE ID=255;
UPDATE dbc_taxinodes SET Name_Lang_koKR='아그마르의 망치 (용의 안식처)' WHERE ID=256;
UPDATE dbc_taxinodes SET Name_Lang_koKR='전쟁노래부족 요새 (북풍의 땅)' WHERE ID=257;
UPDATE dbc_taxinodes SET Name_Lang_koKR='타운카르 마을 (북풍의 땅)' WHERE ID=258;
UPDATE dbc_taxinodes SET Name_Lang_koKR='보르고로크 전초기지 (북풍의 땅)' WHERE ID=259;
UPDATE dbc_taxinodes SET Name_Lang_koKR='코르크론 선봉기지 (용의 안식처)' WHERE ID=260;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 별의 쉼터에서 윈터가드' WHERE ID=261;
UPDATE dbc_taxinodes SET Name_Lang_koKR='회색 구릉지 (얼라이언스 벌목장 시작 01)' WHERE ID=262;
UPDATE dbc_taxinodes SET Name_Lang_koKR='회색 구릉지 (얼라이언스 벌목장 끝 01)' WHERE ID=263;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단 (아우버다인) - 신규' WHERE ID=264;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단 (테라모어) - 신규' WHERE ID=265;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단 (메네실) - 신규' WHERE ID=266;
UPDATE dbc_taxinodes SET Name_Lang_koKR='회색 구릉지 (얼라이언스 벌목장 시작)' WHERE ID=267;
UPDATE dbc_taxinodes SET Name_Lang_koKR='회색 구릉지 (얼라이언스 벌목장 끝)' WHERE ID=268;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 서부경비대 성채에서 윈터가드 성채 시작' WHERE ID=269;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 서부경비대 성채에서 윈터가드 성채 끝' WHERE ID=270;
UPDATE dbc_taxinodes SET Name_Lang_koKR='회색 구릉지 (호드 벌목장 시작)' WHERE ID=271;
UPDATE dbc_taxinodes SET Name_Lang_koKR='회색 구릉지 (호드 벌목장 끝)' WHERE ID=272;
UPDATE dbc_taxinodes SET Name_Lang_koKR='고룡쉼터 사원 - 바닥에서 꼭대기(용의 안식처) - 시작' WHERE ID=273;
UPDATE dbc_taxinodes SET Name_Lang_koKR='고룡쉼터 사원 - 바닥에서 꼭대기(용의 안식처) - 끝' WHERE ID=274;
UPDATE dbc_taxinodes SET Name_Lang_koKR='고룡쉼터 사원 - 꼭대기에서 바닥(용의 안식처) - 시작' WHERE ID=275;
UPDATE dbc_taxinodes SET Name_Lang_koKR='고룡쉼터 사원 - 꼭대기에서 바닥(용의 안식처) - 끝' WHERE ID=276;
UPDATE dbc_taxinodes SET Name_Lang_koKR='고룡쉼터 사원 - 꼭대기에서 중앙(용의 안식처) - 시작' WHERE ID=277;
UPDATE dbc_taxinodes SET Name_Lang_koKR='고룡쉼터 사원 - 꼭대기에서 중앙(용의 안식처) - 끝' WHERE ID=278;
UPDATE dbc_taxinodes SET Name_Lang_koKR='고룡쉼터 사원 - 중앙에서 꼭대기(용의 안식처) - 끝' WHERE ID=279;
UPDATE dbc_taxinodes SET Name_Lang_koKR='고룡쉼터 사원 - 중앙에서 꼭대기(용의 안식처) - 시작' WHERE ID=280;
UPDATE dbc_taxinodes SET Name_Lang_koKR='고룡쉼터 사원 - 중앙에서 바닥(용의 안식처) - 끝' WHERE ID=281;
UPDATE dbc_taxinodes SET Name_Lang_koKR='고룡쉼터 사원 - 중앙에서 바닥(용의 안식처) - 시작' WHERE ID=282;
UPDATE dbc_taxinodes SET Name_Lang_koKR='고룡쉼터 사원 - 바닥에서 중앙(용의 안식처) - 끝' WHERE ID=283;
UPDATE dbc_taxinodes SET Name_Lang_koKR='고룡쉼터 사원 - 바닥에서 중앙(용의 안식처) - 시작' WHERE ID=284;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 윈터가드에서 별의 쉼터 (시작)' WHERE ID=285;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 윈터가드에서 별의 쉼터 (끝)' WHERE ID=286;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 발가드 - 서부경비대 성채 시작' WHERE ID=287;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 발가드 - 서부경비대 성채 끝' WHERE ID=288;
UPDATE dbc_taxinodes SET Name_Lang_koKR='호박석 절벽 (북풍의 땅)' WHERE ID=289;
UPDATE dbc_taxinodes SET Name_Lang_koKR='은빛십자군 격전지 (줄드락)' WHERE ID=290;
UPDATE dbc_taxinodes SET Name_Lang_koKR='줄드락 폐허' WHERE ID=291;
UPDATE dbc_taxinodes SET Name_Lang_koKR='스톰윈드 항구 - 시작' WHERE ID=292;
UPDATE dbc_taxinodes SET Name_Lang_koKR='스톰윈드 항구 - 끝' WHERE ID=293;
UPDATE dbc_taxinodes SET Name_Lang_koKR='모아키 항구 (용의 안식처)' WHERE ID=294;
UPDATE dbc_taxinodes SET Name_Lang_koKR='카마구아 (울부짖는 협만)' WHERE ID=295;
UPDATE dbc_taxinodes SET Name_Lang_koKR='우누페 (북풍의 땅)' WHERE ID=296;
UPDATE dbc_taxinodes SET Name_Lang_koKR='숄라자르 분지 - 퀘스트 - 정찰 - 시작' WHERE ID=297;
UPDATE dbc_taxinodes SET Name_Lang_koKR='숄라자르 분지 - 퀘스트 - 정찰 - 끝' WHERE ID=298;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단: 메네실에서 발가드' WHERE ID=299;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단 (스톱윈드)' WHERE ID=300;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 북풍의 땅 - 빅시를 찾아라 - 시작' WHERE ID=301;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 북풍의 땅 - 빅시를 찾아라 - 끝' WHERE ID=302;
UPDATE dbc_taxinodes SET Name_Lang_koKR='용맹의 주둔지 (겨울손아귀 호수)' WHERE ID=303;
UPDATE dbc_taxinodes SET Name_Lang_koKR='은빛십자군 격전지 (줄드락)' WHERE ID=304;
UPDATE dbc_taxinodes SET Name_Lang_koKR='칠흑의 감시초소 (줄드락)' WHERE ID=305;
UPDATE dbc_taxinodes SET Name_Lang_koKR='빛의 틈 (줄드락)' WHERE ID=306;
UPDATE dbc_taxinodes SET Name_Lang_koKR='짐토르가 (줄드락)' WHERE ID=307;
UPDATE dbc_taxinodes SET Name_Lang_koKR='강의 심장부 (숄라자르 분지)' WHERE ID=308;
UPDATE dbc_taxinodes SET Name_Lang_koKR='네싱워리 주둔지 (숄라자르 분지)' WHERE ID=309;
UPDATE dbc_taxinodes SET Name_Lang_koKR='달라란' WHERE ID=310;
UPDATE dbc_taxinodes SET Name_Lang_koKR='원크와 야영지 (회색 구릉지)' WHERE ID=311;
UPDATE dbc_taxinodes SET Name_Lang_koKR='빛의 틈 (줄드락)' WHERE ID=312;
UPDATE dbc_taxinodes SET Name_Lang_koKR='서부 몰락지대 여단 (회색 구릉지)' WHERE ID=313;
UPDATE dbc_taxinodes SET Name_Lang_koKR='짐토르가 (줄드락)' WHERE ID=314;
UPDATE dbc_taxinodes SET Name_Lang_koKR='아케루스: 칠흑의 요새' WHERE ID=315;
UPDATE dbc_taxinodes SET Name_Lang_koKR='칠흑의 요새 (아케루스 -> 죽음의 틈 시작)' WHERE ID=316;
UPDATE dbc_taxinodes SET Name_Lang_koKR='칠흑의 요새 (아케루스 -> 죽음의 틈 끝)' WHERE ID=317;
UPDATE dbc_taxinodes SET Name_Lang_koKR='칠흑의 요새 (죽음의 틈 -> 아케루스 시작)' WHERE ID=318;
UPDATE dbc_taxinodes SET Name_Lang_koKR='칠흑의 요새 (죽음의 틈 -> 아케루스 끝)' WHERE ID=319;
UPDATE dbc_taxinodes SET Name_Lang_koKR='K3 (폭풍우 봉우리)' WHERE ID=320;
UPDATE dbc_taxinodes SET Name_Lang_koKR='서리요새 (폭풍우 봉우리)' WHERE ID=321;
UPDATE dbc_taxinodes SET Name_Lang_koKR='던 니펠렘 (폭풍우 봉우리)' WHERE ID=322;
UPDATE dbc_taxinodes SET Name_Lang_koKR='그롬마쉬 추락 지점 (폭풍우 봉우리)' WHERE ID=323;
UPDATE dbc_taxinodes SET Name_Lang_koKR='툰카로 야영지 (폭풍우 봉우리)' WHERE ID=324;
UPDATE dbc_taxinodes SET Name_Lang_koKR='죽음의 마루 (얼음왕관)' WHERE ID=325;
UPDATE dbc_taxinodes SET Name_Lang_koKR='울두아르 (폭풍우 봉우리)' WHERE ID=326;
UPDATE dbc_taxinodes SET Name_Lang_koKR='바울더크랙의 은거처 (폭풍우 봉우리)' WHERE ID=327;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단 (얼음왕관)' WHERE ID=328;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단 (얼음왕관)' WHERE ID=329;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단 (얼음왕관) 대상' WHERE ID=330;
UPDATE dbc_taxinodes SET Name_Lang_koKR='군드락 (줄드락)' WHERE ID=331;
UPDATE dbc_taxinodes SET Name_Lang_koKR='전쟁노래부족 야영지 (겨울손아귀)' WHERE ID=332;
UPDATE dbc_taxinodes SET Name_Lang_koKR='어둠의 무기고 (얼음왕관)' WHERE ID=333;
UPDATE dbc_taxinodes SET Name_Lang_koKR='은빛십자군 선봉기지 (얼음왕관)' WHERE ID=334;
UPDATE dbc_taxinodes SET Name_Lang_koKR='십자군 봉우리 (얼음왕관)' WHERE ID=335;
UPDATE dbc_taxinodes SET Name_Lang_koKR='윈드러너 전망대 (수정노래 숲)' WHERE ID=336;
UPDATE dbc_taxinodes SET Name_Lang_koKR='선리버 지휘초소 (수정노래 숲)' WHERE ID=337;
UPDATE dbc_taxinodes SET Name_Lang_koKR='은빛십자군 마상시합 광장, 얼음왕관' WHERE ID=340;
UPDATE dbc_taxinodes SET Name_Lang_koKR='울두아르 공격대 - 내부 - 잠입 지점' WHERE ID=341;
UPDATE dbc_taxinodes SET Name_Lang_koKR='울두아르 공격대 - 무쇠 대합실' WHERE ID=342;
UPDATE dbc_taxinodes SET Name_Lang_koKR='운송수단: 썬더 블러프에서 오그리마 (비행선)' WHERE ID=348;
UPDATE dbc_taxinodes SET Name_Lang_koKR='정복의 섬 - 비행포격선' WHERE ID=352;
UPDATE dbc_taxinodes SET Name_Lang_koKR='' WHERE ID=353;
UPDATE dbc_taxinodes SET Name_Lang_koKR='' WHERE ID=357;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 얼음왕관 - 북해 크라켄 폭탄 투하 - 시작' WHERE ID=358;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 - 얼음왕관 - 북해 크라켄 폭탄 투하 - 종료' WHERE ID=359;
UPDATE dbc_taxinodes SET Name_Lang_koKR='재사용' WHERE ID=375;
UPDATE dbc_taxinodes SET Name_Lang_koKR='얼음왕관 공격대 - 운송수단 전투 비행 경로' WHERE ID=376;
UPDATE dbc_taxinodes SET Name_Lang_koKR='얼음왕관 던전 - 비행포격선' WHERE ID=377;
UPDATE dbc_taxinodes SET Name_Lang_koKR='얼음왕관 공격대 - 사울팽의 함선 (끝)' WHERE ID=379;
UPDATE dbc_taxinodes SET Name_Lang_koKR='얼음왕관 공격대 - 사울팽의 함선 (시작)' WHERE ID=380;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 [이동] 얼음왕관 공격대 - 사울팽의 함선 (시작)' WHERE ID=381;
UPDATE dbc_taxinodes SET Name_Lang_koKR='퀘스트 [이동] 얼음왕관 공격대 - 사울팽의 함선 (끝)' WHERE ID=382;
UPDATE dbc_taxinodes SET Name_Lang_koKR='톤드로릴 강 (서부 역병지대)' WHERE ID=383;
UPDATE dbc_taxinodes SET Name_Lang_koKR='보루 (티리스팔 숲)' WHERE ID=384;
UPDATE dbc_taxinodes SET Name_Lang_koKR='CC 사전진행 - GT - 퀘스트 - 환기의 지평선 - 시작' WHERE ID=392;
UPDATE dbc_taxinodes SET Name_Lang_koKR='CC 사전진행 - GT - 퀘스트 - 환기의 지평선 - 끝' WHERE ID=393;
UPDATE dbc_taxinodes SET Name_Lang_koKR='CC 사전진행 - GT - 전투 - 시작' WHERE ID=394;
UPDATE dbc_taxinodes SET Name_Lang_koKR='CC 사전진행 - GT - 전투- 끝' WHERE ID=395;
UPDATE dbc_taxinodes SET Name_Lang_koKR='듀로타 - ET - CC 사전진행 - 첩보원 개구리 시작' WHERE ID=404;
UPDATE dbc_taxinodes SET Name_Lang_koKR='듀로타 - ET - CC 사전진행 - 첩보원 개구리 끝' WHERE ID=405;
UPDATE dbc_taxinodes SET Name_Lang_koKR='듀로타 - ET - CC 사전진행 트롤 운송수단 박쥐 시작' WHERE ID=438;
UPDATE dbc_taxinodes SET Name_Lang_koKR='듀로타 - ET - CC 사전진행 트롤 모집 끝' WHERE ID=439;
UPDATE dbc_taxinodes SET Name_Lang_koKR='듀로타 - ET - CC 사전진행 - 트롤 전투 끝' WHERE ID=440;
