UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='보석세공인의 보석' WHERE ID=2;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='생명석' WHERE ID=3;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='마나석' WHERE ID=4;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='폭풍석' WHERE ID=6;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='마력 깃든 진주' WHERE ID=7;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='결속의 빛' WHERE ID=8;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='결속의 돌' WHERE ID=9;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='죽음의 선택' WHERE ID=10;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='죽음의 선고' WHERE ID=11;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='아이트리그의 서약' WHERE ID=12;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='서릿결부족의 열정' WHERE ID=13;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='작열의 우상' WHERE ID=14;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='돌격전차의 활력' WHERE ID=15;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='생명이 없는 자의 통치' WHERE ID=16;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='생명이 사라진 자의 통치' WHERE ID=17;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='사트리나의 방어 스카라베' WHERE ID=18;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='패배한 자의 위안' WHERE ID=19;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='쓰러진 자의 위안' WHERE ID=20;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='작열의 부적' WHERE ID=21;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='포세이큰의 원한' WHERE ID=22;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='승자의 부름' WHERE ID=23;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='냉담한 침략의 고리' WHERE ID=24;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='통탄할만한 폭력의 고리' WHERE ID=25;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='배신자 왕의 고리' WHERE ID=26;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='발키르 쌍둥이의 고리' WHERE ID=27;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='격분하는 기질의 고리' WHERE ID=28;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='탐욕스러운 고리' WHERE ID=29;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='암흑치유사의 고리' WHERE ID=30;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='화염폭풍 고리' WHERE ID=31;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='화염폭풍 반지' WHERE ID=32;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='고르목의 고리' WHERE ID=33;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='발키르 쌍둥이의 실반지' WHERE ID=34;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='소름끼치는 징후' WHERE ID=35;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='이계추적자 고리' WHERE ID=36;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='이계추적자 인장' WHERE ID=37;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='냉담한 침략의 반지' WHERE ID=38;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='냉담한 침략의 반지' WHERE ID=39;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='암흑치유사의 반지' WHERE ID=40;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='격분하는 기질의 반지' WHERE ID=41;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='배신자 왕의 인장' WHERE ID=42;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='시험용 반지 제한' WHERE ID=43;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='알소르의 연산장치' WHERE ID=44;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='진정한 피의 노리개' WHERE ID=45;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='시체조각 동전' WHERE ID=46;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='죽음인도자의 의지' WHERE ID=47;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='제거된 이물질' WHERE ID=48;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='이름없는 리치의 성물함' WHERE ID=49;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='단지 안에 든 작은 누더기골렘' WHERE ID=50;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='신드라고사의 완전무결한 송곳니' WHERE ID=51;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='누더기골렘의 혈반지' WHERE ID=52;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='부패의 인장' WHERE ID=53;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='선홍색 고리모양 반지' WHERE ID=54;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='썩은얼굴의 파열 반지' WHERE ID=55;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='사울팽의 냉기로 벼려낸 고리' WHERE ID=56;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='황혼 여왕의 인장' WHERE ID=57;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='삼중 송곳니 인장' WHERE ID=58;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='해골 괴수의 고리' WHERE ID=59;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='일탈의 영원한 한기 반지' WHERE ID=60;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='수많은 입의 인장' WHERE ID=61;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='서리고룡족 사파이어 반지' WHERE ID=62;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='무력의 고리' WHERE ID=63;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='끝없는 미궁의 실반지' WHERE ID=64;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='매로우가르의 얼어붙은 눈' WHERE ID=65;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='말리고스의 추억' WHERE ID=66;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='역병의 힘' WHERE ID=67;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='광기의 속삭임 반지' WHERE ID=68;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='재빠른 비상의 반지' WHERE ID=69;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='해골 군주의 고리' WHERE ID=70;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='발라나르의 다른 인장 반지' WHERE ID=71;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='치유의 살구색 고리' WHERE ID=72;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='무라딘의 망원경' WHERE ID=73;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='순수한 얼음 조각' WHERE ID=74;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='정체불명의 기관' WHERE ID=75;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='속삭이는 송곳니 해골' WHERE ID=76;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='황혼의 미늘' WHERE ID=77;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='단계적 재생의 반지' WHERE ID=78;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='사비아나의 공물' WHERE ID=79;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='황혼의 인장' WHERE ID=80;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='자리스리안의 공물' WHERE ID=81;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='날카로운 황혼의 비늘' WHERE ID=82;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='석화된 황혼의 비늘' WHERE ID=83;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='빛나는 황혼의 비늘' WHERE ID=84;
UPDATE dbc_itemlimitcategory SET Name_Lang_koKR='그을린 황혼의 비늘' WHERE ID=85;
