UPDATE dbc_creaturefamily SET Name_Lang_koKR='늑대' WHERE ID=1;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='살쾡이' WHERE ID=2;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='거미' WHERE ID=3;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='곰' WHERE ID=4;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='멧돼지' WHERE ID=5;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='악어' WHERE ID=6;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='독수리' WHERE ID=7;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='게' WHERE ID=8;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='고릴라' WHERE ID=9;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='랩터' WHERE ID=11;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='타조' WHERE ID=12;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='지옥사냥개' WHERE ID=15;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='보이드워커' WHERE ID=16;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='서큐버스' WHERE ID=17;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='파멸의 수호병' WHERE ID=19;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='전갈' WHERE ID=20;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='거북' WHERE ID=21;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='임프' WHERE ID=23;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='박쥐' WHERE ID=24;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='하이에나' WHERE ID=25;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='맹금' WHERE ID=26;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='천둥매' WHERE ID=27;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='무선조종 장난감' WHERE ID=28;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='지옥수호병' WHERE ID=29;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='용매' WHERE ID=30;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='칼날발톱' WHERE ID=31;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='차원의 추적자' WHERE ID=32;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='포자날개' WHERE ID=33;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='황천의 가오리' WHERE ID=34;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='뱀' WHERE ID=35;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='나방' WHERE ID=37;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='키메라' WHERE ID=38;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='데빌사우루스' WHERE ID=39;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='구울' WHERE ID=40;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='실리시드' WHERE ID=41;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='벌레' WHERE ID=42;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='코뿔소' WHERE ID=43;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='말벌' WHERE ID=44;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='심장부 사냥개' WHERE ID=45;
UPDATE dbc_creaturefamily SET Name_Lang_koKR='야수 정령' WHERE ID=46;
