UPDATE dbc_skillline SET DisplayName_Lang_koKR='냉기', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=6;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='화염', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=8;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='무기', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=26;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='전투', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=38;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='잠행', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=39;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='도검류', Description_Lang_koKR='무기 숙련이 올라갈수록 적중률이 높아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=43;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='도끼류', Description_Lang_koKR='무기 숙련이 올라갈수록 적중률이 높아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=44;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='활류', Description_Lang_koKR='무기 숙련이 올라갈수록 적중률이 높아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=45;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='총기류', Description_Lang_koKR='무기 숙련이 올라갈수록 적중률이 높아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=46;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=50;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='생존', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=51;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='둔기류', Description_Lang_koKR='무기 숙련이 올라갈수록 적중률이 높아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=54;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='양손 도검류', Description_Lang_koKR='무기 숙련이 올라갈수록 적중률이 높아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=55;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='신성', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=56;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='암흑', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=78;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='방어', Description_Lang_koKR='방어 숙련도가 높을수록 회피, 무기 막기, 방패 막기 및 적의 공격이 빗나갈 확률이 높아지며 적의 치명타 적중률이 낮아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=95;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='언어: 공용어', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=98;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='드워프 종족 특성', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=101;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='언어: 오크어', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=109;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='언어: 드워프어', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=111;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='언어: 나이트 엘프어', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=113;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='언어: 타우렌어', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=115;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='쌍수 무기', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=118;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='타우렌 종족 특성', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=124;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='오크 종족 특성', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=125;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='나이트 엘프 족종 특성', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=126;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='응급치료', Description_Lang_koKR='응급치료 숙련도가 올라갈수록 고급 응급치료술을 배울 수 있습니다. 응급치료술은 전문 응급치료사나 퀘스트로 배울 수 있습니다.', AlternateVerb_Lang_koKR='' WHERE ID=129;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야성', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=134;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='지팡이류', Description_Lang_koKR='무기 숙련이 올라갈수록 적중률이 높아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=136;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='언어: 하이엘프어', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=137;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='언어: 용언', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=138;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='언어: 악마어', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=139;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='언어: 티탄어', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=140;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='언어: 고대어', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=141;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야영', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=142;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='말 타기', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=148;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='늑대 타기', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=149;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='호랑이 타기', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=150;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='산양 타기', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=152;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='수영', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=155;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='양손 둔기류', Description_Lang_koKR='무기 숙련이 올라갈수록 적중률이 높아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=160;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='맨손 전투', Description_Lang_koKR='숙련도가 올라갈수록 적중률이 높아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=162;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='사격', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=163;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='대장기술', Description_Lang_koKR='대장기술 숙련도가 올라갈수록 고레벨의 대장기술 도면을 배울 수 있습니다. 도면은 전문 대장장이나 퀘스트를 통해 배우거나 몬스터에게서 얻을 수 있습니다.', AlternateVerb_Lang_koKR='개조' WHERE ID=164;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='가죽세공', Description_Lang_koKR='가죽세공 숙련도가 올라갈수록 고레벨의 가죽세공 도안을 배울 수 있습니다. 도안은 전문 가죽세공인이나 퀘스트를 통해 배우거나 몬스터에게서 얻을 수 있습니다.', AlternateVerb_Lang_koKR='새김무늬' WHERE ID=165;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='연금술', Description_Lang_koKR='연금술 숙련도가 올라갈수록 고레벨의 연금술 조제법을 배울 수 있습니다. 조제법은 전문 연금술사나 퀘스트를 통해 배우거나 몬스터에게서 얻을 수 있습니다.', AlternateVerb_Lang_koKR='보충' WHERE ID=171;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='양손 도끼류', Description_Lang_koKR='무기 숙련이 올라갈수록 적중률이 높아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=172;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='단검류', Description_Lang_koKR='무기 숙련이 올라갈수록 적중률이 높아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=173;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='투척 무기류', Description_Lang_koKR='무기 숙련이 올라갈수록 적중률이 높아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=176;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='약초채집', Description_Lang_koKR='약초채집 숙련도가 올라갈수록 좀더 희귀한 약초를 채집할 수 있습니다. 특정한 약초을 채집할 수 없다면 그 전 단계의 쉬운 약초를 채집하여 숙련도를 올리십시오.', AlternateVerb_Lang_koKR='' WHERE ID=182;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='일반 (DND)', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=183;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='징벌', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=184;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='요리', Description_Lang_koKR='요리 숙련도가 올라갈수록 고레벨의 요리 조리법을 배울 수 있습니다. 조리법은 전문 요리사나 퀘스트를 통해 배우거나 몬스터에게서 얻을 수 있습니다.', AlternateVerb_Lang_koKR='' WHERE ID=185;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='채광', Description_Lang_koKR='채광 숙련도가 올라갈수록 좀더 희귀한 광석을 채집할 수 있습니다. 특정한 광맥을 채광할 수 없다면 그 전 단계의 쉬운 광맥을 채광하여 숙련도를 올리십시오.', AlternateVerb_Lang_koKR='' WHERE ID=186;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 임프', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=188;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 지옥사냥개', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=189;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='재봉술', Description_Lang_koKR='재봉술 숙련도가 올라갈수록 고레벨의 재봉 도안을 배울 수 있습니다. 도안은 전문 재봉사나 퀘스트를 통해 배우거나 몬스터에게서 얻을 수 있습니다.', AlternateVerb_Lang_koKR='자수' WHERE ID=197;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='기계공학', Description_Lang_koKR='기계공학 숙련도가 올라갈수록 고레벨의 기계공학 설계도를 배울 수 있습니다. 설계도는 전문 기술자나 퀘스트를 통해 배우거나 몬스터에게서 얻을 수 있습니다.', AlternateVerb_Lang_koKR='수선' WHERE ID=202;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 거미', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=203;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 보이드워커', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=204;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 서큐버스', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=205;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 지옥불정령', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=206;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 파멸의 수호병', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=207;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 늑대', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=208;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 살쾡이', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=209;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 곰', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=210;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 멧돼지', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=211;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 악어', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=212;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 독수리', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=213;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 게', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=214;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 고릴라', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=215;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 랩터', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=217;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 타조', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=218;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='언데드 종족 특성', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=220;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='석궁류', Description_Lang_koKR='무기 숙련이 올라갈수록 적중률이 높아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=226;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='마법봉류', Description_Lang_koKR='무기 숙련이 올라갈수록 적중률이 높아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=228;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='장창류', Description_Lang_koKR='무기 숙련이 올라갈수록 적중률이 높아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=229;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 전갈', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=236;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='비전', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=237;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 거북', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=251;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='암살', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=253;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='분노', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=256;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='방어', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=257;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='보호', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=267;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 사냥꾼 일반', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=270;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='판금 갑옷', Description_Lang_koKR='판금 방어구를 입을 수 있습니다.', AlternateVerb_Lang_koKR='' WHERE ID=293;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='언어: 노움어', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=313;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='언어: 트롤어', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=315;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='마법부여', Description_Lang_koKR='마법부여 숙련도가 올라갈수록 더 강력한 주문식을 배울 수 있습니다. 주문식은 전문 마법부여사나 퀘스트를 통해 배우거나 몬스터에게서 얻을 수 있습니다.', AlternateVerb_Lang_koKR='마법부여' WHERE ID=333;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='악마', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=354;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='고통', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=355;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='낚시', Description_Lang_koKR='낚시 숙련도가 올라갈수록 물고기를 낚을 확률이 증가합니다. 만약 해당 지역에서 물고기를 낚을 수 없다면 좀 더 낮은 레벨의 장소로 이동하거나 미끼를 사용해 보십시오.', AlternateVerb_Lang_koKR='' WHERE ID=356;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='고양', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=373;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='복원', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=374;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='정기', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=375;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='무두질', Description_Lang_koKR='무두질 숙련도가 올라갈수록 고레벨의 몬스터의 가죽을 채집할 수 있습니다. 숙련도가 100 이상이 되면 숙련도를 5로 나눈 숫자가 가죽 채집이 가능한 몬스터의 최고 레벨입니다.', AlternateVerb_Lang_koKR='' WHERE ID=393;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='사슬', Description_Lang_koKR='사슬 방어구를 입을 수 있습니다.', AlternateVerb_Lang_koKR='' WHERE ID=413;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='가죽', Description_Lang_koKR='가죽 방어구를 입을 수 있습니다.', AlternateVerb_Lang_koKR='' WHERE ID=414;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='천', Description_Lang_koKR='천 방어구를 입을 수 있습니다.', AlternateVerb_Lang_koKR='' WHERE ID=415;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='방패', Description_Lang_koKR='방패를 사용할 수 있습니다.', AlternateVerb_Lang_koKR='' WHERE ID=433;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='장착 무기류', Description_Lang_koKR='장착 무기를 사용할 수 있습니다. 맨손 전투 숙련도가 올라갈수록 적중률이 높아집니다.', AlternateVerb_Lang_koKR='' WHERE ID=473;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='랩터 타기', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=533;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='기계타조 조종', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=553;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='언데드 승마술', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=554;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='회복', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=573;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='조화', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=574;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='파괴', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=593;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='신성', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=594;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='수양', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=613;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='자물쇠 따기', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=633;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 박쥐', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=653;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 하이에나', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=654;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 맹금', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=655;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 천둥매', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=656;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='언어: 언데드어', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=673;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='코도 타기', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=713;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='트롤 종족 특성', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=733;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='노움 종족 특성', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=753;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='인간 종족 특성', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=754;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='보석세공', Description_Lang_koKR='보석세공 숙련도가 올라갈수록 고급 세공술을 배울 수 있습니다. 보석세공은 전문 보석세공인이나 퀘스트로 배울 수 있습니다.', AlternateVerb_Lang_koKR='연마' WHERE ID=755;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='블러드 엘프 종족 특성', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=756;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='이벤트 - 원격조종', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=758;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='언어: 드레나이어', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=759;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='드레나이 종족 특성', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=760;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 지옥수호병', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=761;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='탈것 타기', Description_Lang_koKR='탈것 타기 숙련도가 올라갈수록 더 빠르고 희귀한 야수를 탈 수 있습니다.', AlternateVerb_Lang_koKR='' WHERE ID=762;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 용매', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=763;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 황천의 가오리', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=764;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 포자날개', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=765;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 차원의 추적자', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=766;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 칼날발톱', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=767;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 뱀', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=768;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='내부', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=769;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='혈기', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=770;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='냉기', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=771;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='부정', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=772;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='주문각인', Description_Lang_koKR='주문각인 숙련도가 올라갈수록 고급 주문각인술을 배울 수 있습니다. 세계 각지의 숙련된 각인사들을 통해 지식을 습득할 수 있습니다.', AlternateVerb_Lang_koKR='각인' WHERE ID=773;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='야수 - 나방', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=775;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='룬벼리기', Description_Lang_koKR='', AlternateVerb_Lang_koKR='새김' WHERE ID=776;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='탈것', Description_Lang_koKR='탈것을 탈 수 있습니다.', AlternateVerb_Lang_koKR='' WHERE ID=777;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수', Description_Lang_koKR='소환수를 부립니다.', AlternateVerb_Lang_koKR='' WHERE ID=778;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 키메라 (특수)', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=780;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 데빌사우루스 (특수)', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=781;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 구울', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=782;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 실리시드 (특수)', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=783;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 벌레 (특수)', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=784;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 말벌', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=785;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 코뿔소 (특수)', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=786;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 심장부 사냥개 (특수)', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=787;
UPDATE dbc_skillline SET DisplayName_Lang_koKR='소환수 - 야수 정령 (특수)', Description_Lang_koKR='', AlternateVerb_Lang_koKR='' WHERE ID=788;
