UPDATE dbc_spellfocusobject SET Name_Lang_koKR='모루' WHERE ID=1;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='베틀' WHERE ID=2;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='가열로' WHERE ID=3;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='요리용 불' WHERE ID=4;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='미즈라엘의 결정' WHERE ID=5;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='윈터후프 우물' WHERE ID=6;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='썬더혼 우물' WHERE ID=7;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='와일드메인 우물' WHERE ID=8;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='부족의 불' WHERE ID=9;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='작업소' WHERE ID=10;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='그늘 협곡 달샘' WHERE ID=11;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='별바람 마을 달샘' WHERE ID=12;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='아리스리엔 연못 달샘' WHERE ID=13;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='신탁의 숲 달샘' WHERE ID=14;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='투자개발회사 비행장' WHERE ID=15;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='투자개발회사 짐마차 (청)' WHERE ID=16;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='투자개발회사 짐마차 (적)' WHERE ID=17;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='NG-5 폭탄 (적)' WHERE ID=18;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='NG-5 폭탄 (청)' WHERE ID=19;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='우젤의 불꽃' WHERE ID=20;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='잿빛골짜기 달샘' WHERE ID=21;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='침식된 제단' WHERE ID=22;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='줄기 근처에서 사용' WHERE ID=23;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='언더시티 소환 마법진' WHERE ID=43;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='주술의 제단' WHERE ID=63;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='스톰윈드 소환 마법진' WHERE ID=83;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='불모의 땅 소환 마법진' WHERE ID=103;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='거울 호수 폭포' WHERE ID=123;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='갈퀴발톱굴' WHERE ID=143;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='사비안 폭포' WHERE ID=163;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='외부 봉인석' WHERE ID=164;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='마나의 균열' WHERE ID=183;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='오그리마 소환 마법진' WHERE ID=203;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='성난비늘 샘' WHERE ID=223;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='가시멧돼지 물 구멍' WHERE ID=224;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='순수한 물 - 은빛소나무 숲' WHERE ID=225;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='우물' WHERE ID=226;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='달의 신전 샘' WHERE ID=243;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='진타알로 제단' WHERE ID=263;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='해적선 구멍' WHERE ID=264;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='에퀴넥스 비석탑' WHERE ID=283;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='마른나무껍질 마을' WHERE ID=303;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='샤드라알로 제단' WHERE ID=304;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='슬픈모래 감시탑 물 웅덩이' WHERE ID=323;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='헤이트탈론 비석' WHERE ID=343;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='에체야키의 둥지' WHERE ID=363;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='고목' WHERE ID=383;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='임시 착륙장' WHERE ID=403;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='아쿠에멘타스의 마법진' WHERE ID=423;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='죽은 신의 성소' WHERE ID=424;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='첫번째 해일의 웅덩이' WHERE ID=443;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='두번째 해일의 웅덩이' WHERE ID=444;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='세번째 해일의 웅덩이' WHERE ID=445;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='네번째 해일의 웅덩이' WHERE ID=446;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='고리쉬 부화장' WHERE ID=463;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='미블론 스날투스' WHERE ID=483;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='가젯잔 무덤' WHERE ID=503;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='강철나무 숲의 폐허' WHERE ID=523;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='검은 가열로' WHERE ID=543;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='골락카 분화구' WHERE ID=563;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='일곱 현자의 무덤' WHERE ID=583;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='반반한 운고로 바위' WHERE ID=603;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='보존된 트레샤돈 시체' WHERE ID=604;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='검은 모루' WHERE ID=623;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='고리쉬 실리시드 수정' WHERE ID=643;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='오염된 달샘' WHERE ID=644;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='연금술 실험대' WHERE ID=663;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='벼려지지 않은 승천의 인장' WHERE ID=683;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='아우버다인 달샘' WHERE ID=703;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='검은나무일족 화톳불' WHERE ID=704;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='절벽 폭포' WHERE ID=705;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='불기둥 마루 열점' WHERE ID=723;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='우로크의 제물더미' WHERE ID=743;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='안돌할 저장고 시간의 균열' WHERE ID=763;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='샤이로탐의 돌' WHERE ID=783;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='신성한 생명의 불' WHERE ID=803;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='붉은십자군 전진기지' WHERE ID=804;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='안돌할 탑' WHERE ID=805;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='스칼로맨스 강당' WHERE ID=823;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='오염된 자에데나르 달샘' WHERE ID=843;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='우미의 친구' WHERE ID=863;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='달샘' WHERE ID=883;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='불기둥 마루 용암의 강' WHERE ID=903;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='북마루 벌목지 상자' WHERE ID=923;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='달빛야수 비석' WHERE ID=943;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='다로우샤이어 마을 광장' WHERE ID=944;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='밝은 빛' WHERE ID=963;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='폭파 지점' WHERE ID=983;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='절벽 폭포 동굴' WHERE ID=1003;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='공포의 안개봉우리 웅덩이' WHERE ID=1004;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='죽은 골리아스' WHERE ID=1023;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='레물로스의 제단' WHERE ID=1043;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='썩은나무일족 토템고분' WHERE ID=1063;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='혈투의 웅덩이' WHERE ID=1083;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='마라우돈 차원문' WHERE ID=1103;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='호드 관측용 지구본' WHERE ID=1123;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='동부 분화구' WHERE ID=1143;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='서부 분화구' WHERE ID=1144;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='눈사태 무덤' WHERE ID=1145;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='얼라이언스 관측용 지구본' WHERE ID=1163;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='던 발다르 안마당' WHERE ID=1164;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='서리늑대 요새 안마당' WHERE ID=1165;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='눈사태 무덤' WHERE ID=1183;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='동부 분화구' WHERE ID=1184;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='서부 분화구' WHERE ID=1185;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='투명한 황색 웅덩이' WHERE ID=1203;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='오닉시아의 화염 숨결' WHERE ID=1223;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='크로쉬우스의 잔해' WHERE ID=1243;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='이몰타르의 대좌' WHERE ID=1263;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='암흑의 소환진' WHERE ID=1264;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='대형 납골당' WHERE ID=1283;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='떠도는 테러데일 영혼' WHERE ID=1284;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='맹금의 봉우리 마을회관' WHERE ID=1303;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='우서 경의 무덤 석상' WHERE ID=1323;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='그롬 헬스크림의 기념비' WHERE ID=1324;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='페이글의 낚시터' WHERE ID=1343;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='잔자의 제단' WHERE ID=1344;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='사우스쇼어' WHERE ID=1345;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='그락카론드의 무덤' WHERE ID=1346;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='포세이큰 구린내 폭탄' WHERE ID=1347;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='약속 장소' WHERE ID=1348;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='회오리치는 소용돌이' WHERE ID=1349;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='대족장 눈사태의 동굴' WHERE ID=1350;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='폭죽 발사대' WHERE ID=1351;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='연발탄 발사대' WHERE ID=1352;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='환한 달빛' WHERE ID=1353;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='부네의 방' WHERE ID=1354;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='알진의 방' WHERE ID=1355;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='진홍십자군 사령실' WHERE ID=1356;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='라스 프로스트위스퍼의 방' WHERE ID=1357;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='괴수의 방' WHERE ID=1358;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='출몰 장소' WHERE ID=1359;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='검은바위 나락 투기장' WHERE ID=1360;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='파괴된 수정' WHERE ID=1361;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='얼음비명 모루' WHERE ID=1362;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='영원노래 마법석' WHERE ID=1363;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='정화된 땅' WHERE ID=1364;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='한여름 축제 화톳불' WHERE ID=1365;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='축제 기둥' WHERE ID=1366;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='아고나르의 제단' WHERE ID=1367;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='아고나르의 뼈' WHERE ID=1368;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='붉은퉁돔 떼' WHERE ID=1369;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='크룬 스파인브레이커의 시체' WHERE ID=1370;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='탈라나르 달샘' WHERE ID=1371;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='숨겨놓은 제어판' WHERE ID=1372;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='나이아스의 제단' WHERE ID=1373;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='은밀한 장소' WHERE ID=1374;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='소환의 룬' WHERE ID=1375;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='지옥 화로' WHERE ID=1376;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='나가 깃발이 올려져 있는 배신자의 만 근처' WHERE ID=1377;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='세다이의 시체' WHERE ID=1378;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='나지부스 기념비' WHERE ID=1379;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='충돌 지점 수정' WHERE ID=1380;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='변형된 핏빛안개 수정' WHERE ID=1381;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='악사리엔 수정' WHERE ID=1382;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='주인의 테라스 남쪽 끝' WHERE ID=1383;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='메디브의 망원경' WHERE ID=1384;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='알론서스 교회 영원의 불꽃' WHERE ID=1385;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='핏빛안개 폭포' WHERE ID=1386;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='증기 양수기 제어장치' WHERE ID=1387;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='바람갈대 오두막' WHERE ID=1388;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='대지의 낙인' WHERE ID=1389;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='지하 수원지' WHERE ID=1390;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='보하무 폐허의 계단' WHERE ID=1391;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='비수늪 바위' WHERE ID=1392;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='불타는 칼날 폐허 내의 불타는 칼날단 장작불' WHERE ID=1393;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='이시엘의 발코니' WHERE ID=1394;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='타오르는 전쟁망치 장작불' WHERE ID=1395;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='장막의 샬라스 토템' WHERE ID=1396;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='짓이겨진 해골' WHERE ID=1397;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='얼라이언스 대포' WHERE ID=1398;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='호드 톱날 투척기' WHERE ID=1399;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='군단 송수신기' WHERE ID=1400;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='불타버린 숲 마법석' WHERE ID=1401;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='책장' WHERE ID=1402;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='무기 선반' WHERE ID=1403;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='옷장' WHERE ID=1404;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='사물함' WHERE ID=1405;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='파괴된 얼라이언스 공성탑' WHERE ID=1406;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='조종 중이지 않은 고철절단기 X6000' WHERE ID=1407;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='키린바르 룬' WHERE ID=1408;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='대마법사 바르고스의 수정구슬' WHERE ID=1409;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='엘렌다르 폭포' WHERE ID=1410;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='용의 뼈' WHERE ID=1411;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='에테리얼 순간이동 장치' WHERE ID=1412;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='알클론 화로' WHERE ID=1413;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='공허의 돌' WHERE ID=1414;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='브나르 마나괴철로 수송관' WHERE ID=1415;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='드레나이 깃발' WHERE ID=1416;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='대지의 결속자의 마법진' WHERE ID=1417;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='살라다르의 마력 수송관' WHERE ID=1418;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='소크레타르의 순간이동기' WHERE ID=1419;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='수데론 생태지구 생성기' WHERE ID=1420;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='울트리스 마나괴철로 근처' WHERE ID=1421;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='북녘망치 탑' WHERE ID=1422;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='어둠의 제단' WHERE ID=1423;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='어둠달 덩이줄기 흙더미' WHERE ID=1424;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='로크가 블러드그립' WHERE ID=1425;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='마나 베틀' WHERE ID=1426;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='고대 드레나이 제단' WHERE ID=1427;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='오우거 건물 입구' WHERE ID=1428;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='칼날 산맥 아라코아 마법진' WHERE ID=1429;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='라쉬안 마법진' WHERE ID=1430;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='베크니르 마법진' WHERE ID=1431;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='다리 끝부분' WHERE ID=1432;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='토르고스의 파멸' WHERE ID=1433;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='베크니르 마법진' WHERE ID=1434;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='저주의 제단에 있는 굴단 근처' WHERE ID=1435;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='군단 요새 순간이동기' WHERE ID=1436;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='루안오크 점쟁이 마법진' WHERE ID=1437;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='군단 통신 장비' WHERE ID=1438;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='현장감독 라젤크라즈' WHERE ID=1439;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='수렁등불 호수의 차원문' WHERE ID=1440;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='칼날 산맥' WHERE ID=1441;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='말루카즈의 초' WHERE ID=1442;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='피투성이굴 가열로' WHERE ID=1443;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='마모트 굴' WHERE ID=1444;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='지옥의 순간이동기' WHERE ID=1445;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='사령관 고락스의 시체' WHERE ID=1446;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='제스고르 경비탑' WHERE ID=1447;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='경비가 허술한 소환 장소' WHERE ID=1448;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='잠긴 와이번 우리' WHERE ID=1449;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='고르그롬의 시체' WHERE ID=1450;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='죽음의 문 지옥 대포' WHERE ID=1451;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='고뇌의 언덕 소환 마법진' WHERE ID=1452;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='고크가 없는 고크의 제단 근처' WHERE ID=1453;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='까마귀의 발톱' WHERE ID=1454;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='아라코아 제단' WHERE ID=1455;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='영혼분쇄자의 제단' WHERE ID=1456;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='샤툴의 순간이동 장치' WHERE ID=1457;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='난파선 파편' WHERE ID=1458;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='블랙후프 마을 풍차' WHERE ID=1459;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='그림토템부족 천막' WHERE ID=1460;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='하이얄 가족 추모비' WHERE ID=1461;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='불타는 트롤 오두막' WHERE ID=1462;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='오닉시아의 둥지 입구' WHERE ID=1463;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='늪지기 오두막 부둣가' WHERE ID=1464;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='용소환사의 단' WHERE ID=1465;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='조각난 해안 대포' WHERE ID=1466;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='북쪽 얼라이언스 벽 대포' WHERE ID=1467;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='영주의 장작불' WHERE ID=1468;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='얼어붙은 폭포' WHERE ID=1469;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='복수의 상륙지에 있는 역병사냥개 우리' WHERE ID=1470;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='가판대' WHERE ID=1471;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='브리쿨 혈액이 담긴 가마솥' WHERE ID=1472;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='해리스의 역병 견본' WHERE ID=1473;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='역병사냥개 우리 근처' WHERE ID=1474;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='부서진 서판' WHERE ID=1475;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='가라앉은 나룻배' WHERE ID=1476;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='베일하임 중앙' WHERE ID=1477;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='가을 축제 - 잔 요청' WHERE ID=1478;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='왈트의 이동 룬' WHERE ID=1479;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='무쇠 드워프 이동 룬' WHERE ID=1480;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='쿠엘다나스의 지맥' WHERE ID=1481;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='서슬가시 흙더미' WHERE ID=1482;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='수호의 수정' WHERE ID=1483;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='군단 순간이동기' WHERE ID=1484;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='하우타의 모루' WHERE ID=1485;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='브리쿨 무덤' WHERE ID=1486;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='변형 지형' WHERE ID=1487;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='푯말' WHERE ID=1488;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='네룹아르 구덩이' WHERE ID=1489;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='스날팡의 토템' WHERE ID=1490;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='엔킬라 가마솥' WHERE ID=1491;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='크발디르 배 정면이나 근처' WHERE ID=1492;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='전쟁노래부족 부두 끝' WHERE ID=1493;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='구속된 녹주석 거점 마술사' WHERE ID=1494;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='녹주석 거점 보호막' WHERE ID=1495;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='사자의 동굴 역병 가마솥' WHERE ID=1496;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='남쪽 구덩이' WHERE ID=1497;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='얼라이언스 탈영병과 전쟁노래부족 요새 동쪽 교차로' WHERE ID=1498;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='핏빛포자 평원에 있는 혈법사 라우리스 근처' WHERE ID=1499;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='무너진 태양 차원의 문' WHERE ID=1500;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='무너진 태양 차원의 문' WHERE ID=1501;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='추락한 비행선 잔해' WHERE ID=1502;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='간헐천 지대 증기 분출구' WHERE ID=1503;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='마력의 탑 차원 균열' WHERE ID=1504;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='파샤이어 곡식' WHERE ID=1505;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='사라고사의 영지' WHERE ID=1506;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='스컬지 구덩이 근처' WHERE ID=1507;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='마력의 탑 북서쪽 입구' WHERE ID=1508;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='드라쿠루의 화로' WHERE ID=1509;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='토르 모단 굴 동쪽 끝' WHERE ID=1510;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='투아키의 낚싯바늘' WHERE ID=1511;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='토아루우의 화로' WHERE ID=1512;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='피즈크랭크 낙하 연습장' WHERE ID=1513;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='피즈크랭크 낙하산병 순간이동기' WHERE ID=1514;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='반짝이는 해안 지맥 집중점' WHERE ID=1515;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='로탈로르 숲 지맥 집중점' WHERE ID=1516;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='인두르 호수 아래 지맥 집중점' WHERE ID=1517;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='드라킬진 징' WHERE ID=1518;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='표시된 눈바람 언덕 나무' WHERE ID=1519;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='폭풍 바늘 아래 구덩이 중앙' WHERE ID=1520;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='볼드랏실의 심장 아래 깊숙한 곳' WHERE ID=1521;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='볼드랏실의 가지 아래 깊숙한 곳' WHERE ID=1522;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='볼드랏실의 눈물 아래 깊숙한 곳' WHERE ID=1523;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='한셀 바우어' WHERE ID=1524;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='그롬타르 도전 장소' WHERE ID=1525;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='윈터가드 그리핀 기지' WHERE ID=1526;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='신 하스글렌 제재소' WHERE ID=1527;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='볼드랏실의 묘목' WHERE ID=1528;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='기지' WHERE ID=1529;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='흑요석 용제단에서 나가는 길 끝' WHERE ID=1530;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='공성 기술자 쿼터플래쉬 근처' WHERE ID=1531;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='강령술 룬' WHERE ID=1532;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='윈터가드 광산 입구' WHERE ID=1533;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='극지 연어 떼' WHERE ID=1534;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='망각의 해변에 있는 폐허 중앙' WHERE ID=1535;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='윈터가드 묘지 입구' WHERE ID=1536;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='루나의 수정 구슬' WHERE ID=1537;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='종자 퍼시' WHERE ID=1538;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='신록의 수호자 알리스트로스' WHERE ID=1539;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='서리한 제단' WHERE ID=1540;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='청동 용제단 바닥' WHERE ID=1541;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='브리쿨 매 횃대' WHERE ID=1542;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='스컬지 미라 불더미' WHERE ID=1543;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='드라카리 의식 석상' WHERE ID=1544;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='핀클스타인의 가마솥' WHERE ID=1545;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='안개속삭임 기우 제단' WHERE ID=1546;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='공물 그릇' WHERE ID=1547;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='드라카리 단상' WHERE ID=1548;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='떨어진 통나무' WHERE ID=1549;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='고대 흙더미' WHERE ID=1550;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='네루비안 굴' WHERE ID=1551;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='룬가열로' WHERE ID=1552;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='착륙장' WHERE ID=1553;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='스컬지마차' WHERE ID=1554;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='쿠에츠룬의 시체 및 전투 상태가 아닌 쿠에츠룬의 예언자' WHERE ID=1555;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='카르탁의 제단' WHERE ID=1556;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='거대한 번개 바위' WHERE ID=1557;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='전투 상태가 아닌 장군 졸마즈' WHERE ID=1558;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='해마루 봉우리의 꼭대기' WHERE ID=1559;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='졸헤브 힘의 마법진' WHERE ID=1560;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='물에 젖은 기름진 흙더미' WHERE ID=1561;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='숄라자르 분지 봉우리 꼭대기' WHERE ID=1562;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='미명의 봉우리의 꼭대기' WHERE ID=1563;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='드러난 생명의 피 봉우리 수정' WHERE ID=1564;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='우조 데스콜러' WHERE ID=1565;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='사령관 아레트 경 부재 중 대주교 랜드그렌의 시체' WHERE ID=1566;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='맛있는 모래톱 물고기 떼' WHERE ID=1567;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='용암고룡 부활의 방' WHERE ID=1568;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='프로스트거트의 제단' WHERE ID=1569;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='가름 순간이동기' WHERE ID=1570;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='비전투 상태인 강력한 영주 우프랑' WHERE ID=1571;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='북쪽 얼음창' WHERE ID=1572;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='얼음 분화구' WHERE ID=1573;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='선봉기지 치료소' WHERE ID=1574;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='눈더미' WHERE ID=1575;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='여왕의 둥지' WHERE ID=1576;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='K3 착륙지' WHERE ID=1577;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='영주 일스카르와 전투 상태가 아닌 일스카르의 용사' WHERE ID=1578;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='십자군 유골 더미' WHERE ID=1579;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='말리크리스의 용광로' WHERE ID=1580;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='안카헤트 화로' WHERE ID=1581;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='부활의 성소 석판' WHERE ID=1582;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='달라란 분수' WHERE ID=1583;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='이미르하임 봉우리 해골' WHERE ID=1584;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='모드레타르 역병 가마솥' WHERE ID=1585;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='그림코르의 수정구' WHERE ID=1586;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='이교도 가마솥' WHERE ID=1587;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='알루메스의 영혼석' WHERE ID=1588;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='마력의 사전 근처' WHERE ID=1589;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='이글거리는 무쇠 조각' WHERE ID=1590;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='칠흑의 심연 제단' WHERE ID=1591;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='쓰러진 검은늑대 시체' WHERE ID=1592;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='불붙지 않은 봉화' WHERE ID=1596;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='드락마 공물 마법진' WHERE ID=1597;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='마상시합 마구간' WHERE ID=1599;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='흑기사의 그리핀' WHERE ID=1601;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='돌덩어리' WHERE ID=1602;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='유령의 요리용 모닥불' WHERE ID=1613;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='이상한 눈더미' WHERE ID=1618;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='안개부름이의 동굴' WHERE ID=1620;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='투알리크 기념비' WHERE ID=1621;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='보르의 분노 갑판' WHERE ID=1622;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='제련장인의 모루' WHERE ID=1636;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='왕관 보급 기지' WHERE ID=1639;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='태양샘' WHERE ID=1641;
UPDATE dbc_spellfocusobject SET Name_Lang_koKR='화학약품 수레' WHERE ID=1650;
