UPDATE dbc_spellrange SET DisplayName_Lang_koKR='자신', DisplayNameShort_Lang_koKR='Self' WHERE ID=1;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='근접거리', DisplayNameShort_Lang_koKR='Combat' WHERE ID=2;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='단거리', DisplayNameShort_Lang_koKR='Short' WHERE ID=3;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='중거리', DisplayNameShort_Lang_koKR='Medium' WHERE ID=4;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='장거리', DisplayNameShort_Lang_koKR='Long' WHERE ID=5;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='시야거리', DisplayNameShort_Lang_koKR='Vision' WHERE ID=6;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='최단거리', DisplayNameShort_Lang_koKR='Very Short' WHERE ID=7;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='단거리', DisplayNameShort_Lang_koKR='Short' WHERE ID=8;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='중거리', DisplayNameShort_Lang_koKR='Medium' WHERE ID=9;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='장거리', DisplayNameShort_Lang_koKR='Long' WHERE ID=10;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='단거리', DisplayNameShort_Lang_koKR='Shorter' WHERE ID=11;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='작용거리', DisplayNameShort_Lang_koKR='Interact' WHERE ID=12;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='거리제한 없음', DisplayNameShort_Lang_koKR='Anywhere' WHERE ID=13;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='최장거리', DisplayNameShort_Lang_koKR='Extra Long' WHERE ID=14;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='중단거리', DisplayNameShort_Lang_koKR='Medium-Short' WHERE ID=34;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='중장거리', DisplayNameShort_Lang_koKR='Medium-Long' WHERE ID=35;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Longer Range', DisplayNameShort_Lang_koKR='Longer' WHERE ID=36;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Extended Range', DisplayNameShort_Lang_koKR='Extended' WHERE ID=37;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Min-Range 10, 25', DisplayNameShort_Lang_koKR='Extra Medium' WHERE ID=38;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Monster Shoot', DisplayNameShort_Lang_koKR='Monster Shoot Range' WHERE ID=54;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Ranged Weapon', DisplayNameShort_Lang_koKR='Ranged' WHERE ID=74;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Sting', DisplayNameShort_Lang_koKR='Sting' WHERE ID=94;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Charge', DisplayNameShort_Lang_koKR='Charge' WHERE ID=95;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Trap', DisplayNameShort_Lang_koKR='Trap' WHERE ID=96;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Hunter Range', DisplayNameShort_Lang_koKR='Hunter' WHERE ID=114;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Tower 80', DisplayNameShort_Lang_koKR='Tower' WHERE ID=134;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Tower 100', DisplayNameShort_Lang_koKR='Tower' WHERE ID=135;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Thirty-to-80', DisplayNameShort_Lang_koKR='Thirty-to-80' WHERE ID=136;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Eight yards', DisplayNameShort_Lang_koKR='Very Short' WHERE ID=137;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Long Range Hunter Shoot', DisplayNameShort_Lang_koKR='Hunter Long' WHERE ID=139;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Six yards', DisplayNameShort_Lang_koKR='Six yards' WHERE ID=140;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Seven yards', DisplayNameShort_Lang_koKR='Seven yards' WHERE ID=141;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Valgarde 8/100', DisplayNameShort_Lang_koKR='Valgarde' WHERE ID=150;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Long Range Hunter Shoot', DisplayNameShort_Lang_koKR='Hunter 45' WHERE ID=151;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Super Long', DisplayNameShort_Lang_koKR='Super Long' WHERE ID=152;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Charge, 60', DisplayNameShort_Lang_koKR='Huge Charge' WHERE ID=153;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Tower 80, 10', DisplayNameShort_Lang_koKR='Tower 10' WHERE ID=154;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Hunter Range (Long)', DisplayNameShort_Lang_koKR='Hunter (Long)' WHERE ID=155;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Boulder Range', DisplayNameShort_Lang_koKR='Boulder' WHERE ID=156;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Ninety', DisplayNameShort_Lang_koKR='Ninety' WHERE ID=157;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Super Long, 15 Min', DisplayNameShort_Lang_koKR='Super Long' WHERE ID=158;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='TEST - Long Range', DisplayNameShort_Lang_koKR='TestLong' WHERE ID=159;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Medium/Long Range', DisplayNameShort_Lang_koKR='Medium/Long' WHERE ID=160;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Short/Long Range', DisplayNameShort_Lang_koKR='Short/Long' WHERE ID=161;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Medium/Short Range', DisplayNameShort_Lang_koKR='Medium/Short' WHERE ID=162;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Death Grip', DisplayNameShort_Lang_koKR='Death Grip' WHERE ID=163;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Catapult Range', DisplayNameShort_Lang_koKR='Catapult' WHERE ID=164;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Fourteen yards', DisplayNameShort_Lang_koKR='Shorter' WHERE ID=165;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Thirteen yards', DisplayNameShort_Lang_koKR='Shorter' WHERE ID=166;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Super Long (Min Range)', DisplayNameShort_Lang_koKR='Super Long' WHERE ID=167;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Medium-Long Range (38)', DisplayNameShort_Lang_koKR='Medium-Long' WHERE ID=168;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Three Yards', DisplayNameShort_Lang_koKR='Three Yards' WHERE ID=169;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Fifty Five Yards', DisplayNameShort_Lang_koKR='Extended' WHERE ID=170;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Min Range 1, 10', DisplayNameShort_Lang_koKR='Very Short' WHERE ID=171;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Eleven yards', DisplayNameShort_Lang_koKR='Shorter' WHERE ID=172;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Anywhere (Combat Min Range)', DisplayNameShort_Lang_koKR='Hunter Long' WHERE ID=173;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='U L T R A', DisplayNameShort_Lang_koKR='U L T R A' WHERE ID=174;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Seventy yards', DisplayNameShort_Lang_koKR='Extended' WHERE ID=176;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Donut 20-70', DisplayNameShort_Lang_koKR='Donut 20-70' WHERE ID=177;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Min Range 5, 15', DisplayNameShort_Lang_koKR='Shorter' WHERE ID=179;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Tournament - Ranged', DisplayNameShort_Lang_koKR='Argent Tournament - Ranged' WHERE ID=180;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Two-Hundred Yard Range', DisplayNameShort_Lang_koKR='200' WHERE ID=181;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Min Range 5, 25', DisplayNameShort_Lang_koKR='Medium' WHERE ID=184;
UPDATE dbc_spellrange SET DisplayName_Lang_koKR='Three Hundred Yards', DisplayNameShort_Lang_koKR='300' WHERE ID=187;
