UPDATE dbc_dungeonencounter SET Name_Lang_koKR='레실고어' WHERE ID=464;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='도살자 칼날발톱' WHERE ID=465;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='남작 실버레인' WHERE ID=466;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사령관 스프링베일' WHERE ID=467;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='눈먼감시자 오도' WHERE ID=468;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='파멸의 펜루스' WHERE ID=469;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='늑대왕 난도스' WHERE ID=470;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대마법사 아루갈' WHERE ID=471;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='흉악범 타고르' WHERE ID=536;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='캄 딥퓨리' WHERE ID=537;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='햄혹' WHERE ID=538;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='덱스트렌 워드' WHERE ID=540;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='바질 스레드' WHERE ID=539;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='라크조르' WHERE ID=161;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='스니드' WHERE ID=162;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='길니드' WHERE ID=163;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='스마이트씨' WHERE ID=164;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='쿠키' WHERE ID=165;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='선장 그린스킨' WHERE ID=166;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='에드윈 밴클리프' WHERE ID=167;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='여군주 아나콘드라' WHERE ID=585;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='군주 코브란' WHERE ID=586;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='크레쉬' WHERE ID=587;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='군주 피타스' WHERE ID=588;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='스컴' WHERE ID=589;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='군주 서펜티스' WHERE ID=590;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='영생의 베르단' WHERE ID=591;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='걸신들린 무타누스' WHERE ID=592;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='죽음의예언자 잘그바' WHERE ID=440;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='루구그' WHERE ID=438;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='저주의가시 아겜' WHERE ID=439;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대군주 램터스크' WHERE ID=441;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='흉포한 아가테로스' WHERE ID=883;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='서슬깃 차를가' WHERE ID=443;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='가무라' WHERE ID=219;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='여왕 사레베스' WHERE ID=220;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='겔리하스트' WHERE ID=221;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='로구스 제트' WHERE ID=222;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='늙은 세라키스' WHERE ID=224;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='황혼의 군주 켈리스' WHERE ID=225;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아쿠마이' WHERE ID=226;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='레벨로쉬' WHERE ID=547;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='길 잃은 드워프' WHERE ID=548;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아이로나야' WHERE ID=549;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='고대 바위 문지기' WHERE ID=551;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='갈간 파이어해머' WHERE ID=552;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='그림로크' WHERE ID=553;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아카에다스' WHERE ID=554;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='그루비스' WHERE ID=379;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='방사성 폐기물' WHERE ID=378;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='기계화 문지기 6000' WHERE ID=380;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='고철 압축기 9-60' WHERE ID=381;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='기계박사 텔마플러그' WHERE ID=382;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아탈알라리온' WHERE ID=485;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='예언자 잠말란' WHERE ID=488;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='드림사이드' WHERE ID=486;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='위버' WHERE ID=487;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='몰파즈' WHERE ID=490;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='하자스' WHERE ID=491;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='학카르의 화신' WHERE ID=492;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='에라니쿠스의 사령' WHERE ID=493;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='투텐카쉬' WHERE ID=434;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='불꽃눈 모드레쉬' WHERE ID=435;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='게걸먹보' WHERE ID=436;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='혹한의 암네나르' WHERE ID=437;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='심문관 비샤스' WHERE ID=444;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='혈법사 탈노스' WHERE ID=445;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사냥개조련사 록시' WHERE ID=446;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='신비술사 도안' WHERE ID=447;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='헤로드' WHERE ID=448;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='종교재판관 페어뱅크스' WHERE ID=449;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='종교재판관 화이트메인' WHERE ID=450;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='유체술사 벨라타' WHERE ID=593;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='가즈릴라' WHERE ID=594;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='안투술' WHERE ID=595;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='순교자 데카' WHERE ID=596;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='의술사 줌라' WHERE ID=597;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='네크룸 거트츄어' WHERE ID=598;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='암흑사제 세즈지즈' WHERE ID=599;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='족장 우코르즈 샌드스칼프' WHERE ID=600;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대군주 오모크' WHERE ID=267;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='어둠사냥꾼 보쉬가진' WHERE ID=268;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대장군 부네' WHERE ID=269;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='여왕 불그물거미' WHERE ID=270;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='우로크 둠하울' WHERE ID=271;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='병참장교 지그리스' WHERE ID=272;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='할리콘' WHERE ID=274;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='흉포한 기즈룰' WHERE ID=273;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대군주 웜타라크' WHERE ID=275;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='불의수호자 엠버시어' WHERE ID=276;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='화염고리 솔라카르' WHERE ID=277;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대족장 렌드 블랙핸드' WHERE ID=278;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='괴수' WHERE ID=279;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사령관 드라키사스' WHERE ID=280;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대심문관 게르스탄' WHERE ID=227;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='불의군주 록코르' WHERE ID=228;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사냥개조련사 그렙마르' WHERE ID=229;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='법의 심판장' WHERE ID=230;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='화염술사 로어그레인' WHERE ID=231;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='불의군주 인센디우스' WHERE ID=232;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='문지기 스틸기스' WHERE ID=233;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='파이너스 다크바이어' WHERE ID=234;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='밸가르' WHERE ID=235;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사령관 앵거포지' WHERE ID=236;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='골렘 군주 아젤마크' WHERE ID=237;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='헐레이 블랙브레스' WHERE ID=238;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='팔란스' WHERE ID=239;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='리블리 스크류스피곳' WHERE ID=240;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='플러거 스파즈링' WHERE ID=241;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사자 화염채찍' WHERE ID=242;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='일곱 현자' WHERE ID=243;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='마그무스' WHERE ID=244;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='제왕 다그란 타우릿산' WHERE ID=245;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='오닉시아' WHERE ID=707;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='오닉시아' WHERE ID=708;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='시간의 군주 데자' WHERE ID=287;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='시간의 군주 데자' WHERE ID=288;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='템퍼루스' WHERE ID=289;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='템퍼루스' WHERE ID=290;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아에누스' WHERE ID=291;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아에누스' WHERE ID=292;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사자 키르토노스' WHERE ID=451;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='잔다이스 바로브' WHERE ID=452;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='들창엄니' WHERE ID=453;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='마르두크 블랙풀' WHERE ID=454;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='벡투스' WHERE ID=455;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='라스 프로스트위스퍼' WHERE ID=456;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='조교 말리시아' WHERE ID=457;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='학자 테올렌 크라스티노브' WHERE ID=458;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='현자 폴켈트' WHERE ID=459;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='라베니안' WHERE ID=460;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='군주 알렉세이 바로브' WHERE ID=461;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='여군주 일루시아 바로브' WHERE ID=462;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='암흑스승 간들링' WHERE ID=463;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대여사제 제클릭' WHERE ID=785;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대사제 베녹시스' WHERE ID=784;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대여사제 말리' WHERE ID=786;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='혈군주 만도키르' WHERE ID=787;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='광란의 경계' WHERE ID=788;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대사제 데칼' WHERE ID=789;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='가즈란카' WHERE ID=790;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대여사제 알로크' WHERE ID=791;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='주술사 진도' WHERE ID=792;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='학카르' WHERE ID=793;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='하스싱어 포레스턴' WHERE ID=473;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='잔혹한 티미' WHERE ID=474;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='포병대장 윌리' WHERE ID=475;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='광신자 말로' WHERE ID=476;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='기록관 갈포드' WHERE ID=477;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='발나자르' WHERE ID=478;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='용서받지 못한 자' WHERE ID=472;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='남작부인 아나스타리' WHERE ID=479;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='네룹엔칸' WHERE ID=480;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='냉혈한 말레키' WHERE ID=481;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='집정관 발실라스' WHERE ID=482;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='먹보 람스타인' WHERE ID=483;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='남작 리븐데어' WHERE ID=484;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='녹시온' WHERE ID=422;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='칼날채찍' WHERE ID=423;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='군주 바일텅' WHERE ID=424;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='저주받은 셀레브라스' WHERE ID=425;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='산사태' WHERE ID=426;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='땜장이 기즐록' WHERE ID=427;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='썩은아귀' WHERE ID=428;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='공주 테라드라스' WHERE ID=429;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='오글플린트' WHERE ID=430;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='기원사 제로쉬' WHERE ID=432;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='바잘란' WHERE ID=433;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='욕망의 타라가만' WHERE ID=431;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='루시프론' WHERE ID=663;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='마그마다르' WHERE ID=664;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='게헨나스' WHERE ID=665;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='가르' WHERE ID=666;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='샤즈라' WHERE ID=667;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='남작 게돈' WHERE ID=668;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='설퍼론 사자' WHERE ID=669;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='초열의 골레마그' WHERE ID=670;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='청지기 이그젝큐투스' WHERE ID=671;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='라그나로스' WHERE ID=672;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='제브림 쏜후프' WHERE ID=343;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='히드로스폰' WHERE ID=344;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='레스텐드리스' WHERE ID=345;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='칼날바람 알진' WHERE ID=346;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='굽이나무 텐드리스' WHERE ID=350;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='일샨나 레이븐오크' WHERE ID=347;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='마법학자 칼렌드리스' WHERE ID=348;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='이몰타르' WHERE ID=349;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='왕자 토르텔드린' WHERE ID=361;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='경비병 몰다르' WHERE ID=362;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='천둥발 크리그' WHERE ID=363;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='경비병 펜구스' WHERE ID=364;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='경비병 슬립킥' WHERE ID=365;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대장 크롬크러쉬' WHERE ID=366;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='정찰병 초루쉬' WHERE ID=367;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='왕 고르독' WHERE ID=368;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='폭군 서슬송곳니' WHERE ID=610;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='타락한 밸라스트라즈' WHERE ID=611;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='용기대장 래쉬레이어' WHERE ID=612;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='화염아귀' WHERE ID=613;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='에본로크' WHERE ID=614;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='플레임고르' WHERE ID=615;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='크로마구스' WHERE ID=616;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='네파리안' WHERE ID=617;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='쿠린낙스' WHERE ID=718;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='장군 라작스' WHERE ID=719;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='모암' WHERE ID=720;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='먹보 부루' WHERE ID=721;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사냥꾼 아야미스' WHERE ID=722;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='무적의 오시리안' WHERE ID=723;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='예언자 스케람' WHERE ID=709;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='실리시드 왕실' WHERE ID=710;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='전투감시병 살투라' WHERE ID=711;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='불굴의 판크리스' WHERE ID=712;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='비시두스' WHERE ID=713;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='공주 후후란' WHERE ID=714;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='쌍둥이 제왕' WHERE ID=715;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아우로' WHERE ID=716;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='쑨' WHERE ID=717;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사냥꾼 어튜멘' WHERE ID=652;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='모로스' WHERE ID=653;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='고결의 여신' WHERE ID=654;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='오페라 이벤트' WHERE ID=655;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='전시 관리인' WHERE ID=656;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='테레스티안 일후프' WHERE ID=657;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아란의 망령' WHERE ID=658;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='황천의 원령' WHERE ID=659;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='체스 이벤트' WHERE ID=660;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='공작 말체자르' WHERE ID=661;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='파멸의 어둠' WHERE ID=662;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아눕레칸' WHERE ID=673;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아눕레칸' WHERE ID=674;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='귀부인 팰리나' WHERE ID=677;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='귀부인 팰리나' WHERE ID=678;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='맥스나' WHERE ID=679;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='맥스나' WHERE ID=680;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='역병술사 노스' WHERE ID=681;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='역병술사 노스' WHERE ID=682;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='부정의 헤이건' WHERE ID=683;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='부정의 헤이건' WHERE ID=684;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='로데브' WHERE ID=685;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='로데브' WHERE ID=686;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='훈련교관 라주비어스' WHERE ID=687;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='훈련교관 라주비어스' WHERE ID=689;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='영혼 착취자 고딕' WHERE ID=690;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='영혼 착취자 고딕' WHERE ID=691;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='4인 기사단' WHERE ID=692;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='4인 기사단' WHERE ID=693;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='패치워크' WHERE ID=694;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='패치워크' WHERE ID=695;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='그라불루스' WHERE ID=696;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='그라불루스' WHERE ID=697;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='글루스' WHERE ID=698;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='글루스' WHERE ID=699;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='타디우스' WHERE ID=700;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='타디우스' WHERE ID=701;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사피론' WHERE ID=702;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사피론' WHERE ID=703;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='켈투자드' WHERE ID=704;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='켈투자드' WHERE ID=706;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='격노한 윈터칠' WHERE ID=618;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아네테론' WHERE ID=619;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='카즈로갈' WHERE ID=620;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아즈갈로' WHERE ID=621;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아키몬드' WHERE ID=622;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대흑마법사 네더쿠르스' WHERE ID=407;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대흑마법사 네더쿠르스' WHERE ID=408;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='돌격대장 오므로그' WHERE ID=410;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='혈투사 포룽' WHERE ID=409;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대족장 카르가스 블레이드피스트' WHERE ID=412;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='돌격대장 오므로그' WHERE ID=411;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대족장 카르가스 블레이드피스트' WHERE ID=413;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='재앙의 창조자' WHERE ID=401;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='재앙의 창조자' WHERE ID=402;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='브로고크' WHERE ID=403;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='브로고크' WHERE ID=404;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='파괴자 켈리단' WHERE ID=405;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='파괴자 켈리단' WHERE ID=406;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='감시자 가르골마르' WHERE ID=392;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='감시자 가르골마르' WHERE ID=393;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='무적의 오모르' WHERE ID=394;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='무적의 오모르' WHERE ID=395;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사자 바즈루덴' WHERE ID=396;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사자 바즈루덴' WHERE ID=397;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='마그테리돈' WHERE ID=651;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='풍수사 세스피아' WHERE ID=314;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='풍수사 세스피아' WHERE ID=315;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='기계박사 스팀리거' WHERE ID=316;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='기계박사 스팀리거' WHERE ID=317;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='장군 칼리스레쉬' WHERE ID=318;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='장군 칼리스레쉬' WHERE ID=319;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='헝가르펜' WHERE ID=320;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='헝가르펜' WHERE ID=321;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='가즈안' WHERE ID=322;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='가즈안' WHERE ID=323;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='늪군주 뮤즐레크' WHERE ID=329;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='늪군주 뮤즐레크' WHERE ID=330;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='검은 추적자' WHERE ID=331;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='검은 추적자' WHERE ID=332;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='배반자 멘누' WHERE ID=301;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='배반자 멘누' WHERE ID=304;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='딱딱이 로크마르' WHERE ID=302;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='딱딱이 로크마르' WHERE ID=305;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='쿠아그미란' WHERE ID=303;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='쿠아그미란' WHERE ID=306;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='불안정한 히드로스' WHERE ID=623;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='심연의 잠복꾼' WHERE ID=624;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='눈먼 레오테라스' WHERE ID=625;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='심연의 군주 카라드레스' WHERE ID=626;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='겅둥파도 모로그림' WHERE ID=627;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='여군주 바쉬' WHERE ID=628;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='알라르' WHERE ID=730;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='공허의 절단기' WHERE ID=731;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='고위 점성술사 솔라리안' WHERE ID=732;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='캘타스 선스트라이더' WHERE ID=733;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='속박이 풀린 제레케스' WHERE ID=494;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='속박이 풀린 제레케스' WHERE ID=495;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='파멸의 예언자 달리아' WHERE ID=496;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='파멸의 예언자 달리아' WHERE ID=497;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='격노의 점술사 소코드라테스' WHERE ID=498;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='격노의 점술사 소코드라테스' WHERE ID=499;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='선구자 스키리스' WHERE ID=500;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='선구자 스키리스' WHERE ID=501;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='지휘관 새래니스' WHERE ID=502;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='지휘관 새래니스' WHERE ID=504;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='고위 식물학자 프레이윈' WHERE ID=505;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='고위 식물학자 프레이윈' WHERE ID=506;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='감시인 쏜그린' WHERE ID=507;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='감시인 쏜그린' WHERE ID=508;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='라즈' WHERE ID=509;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='라즈' WHERE ID=510;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='차원의 분리자' WHERE ID=511;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='차원의 분리자' WHERE ID=512;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='기계군주 캐퍼시투스' WHERE ID=513;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='기계군주 캐퍼시투스' WHERE ID=514;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='황천술사 세페스레아' WHERE ID=515;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='황천술사 세페스레아' WHERE ID=516;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='철두철미한 파탈리온' WHERE ID=517;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='철두철미한 파탈리온' WHERE ID=518;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사자 지옥아귀' WHERE ID=208;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사자 지옥아귀' WHERE ID=255;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='선동자 검은심장' WHERE ID=209;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='선동자 검은심장' WHERE ID=256;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='단장 보르필' WHERE ID=210;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='단장 보르필' WHERE ID=257;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='울림' WHERE ID=211;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='울림' WHERE ID=258;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='흑마술사 시스' WHERE ID=206;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='흑마술사 시스' WHERE ID=252;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='갈퀴대왕 이키스' WHERE ID=207;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='안주' WHERE ID=253;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='갈퀴대왕 이키스' WHERE ID=254;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='팬더모니우스' WHERE ID=203;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='팬더모니우스' WHERE ID=248;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='타바로크' WHERE ID=204;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='타바로크' WHERE ID=249;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='요르' WHERE ID=250;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='연합왕자 샤파르' WHERE ID=205;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='연합왕자 샤파르' WHERE ID=251;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='죽음의 감시인 쉴라크' WHERE ID=201;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='죽음의 감시인 쉴라크' WHERE ID=246;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='총독 말라다르' WHERE ID=202;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='총독 말라다르' WHERE ID=247;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='부관 드레이크' WHERE ID=286;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='부관 드레이크' WHERE ID=285;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='경비대장 스칼록' WHERE ID=283;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='경비대장 스칼록' WHERE ID=284;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='시대의 사냥꾼' WHERE ID=281;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='시대의 사냥꾼' WHERE ID=282;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대장군 나젠투스' WHERE ID=601;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='궁극의 심연' WHERE ID=602;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아카마의 망령' WHERE ID=603;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='테론 고어핀드' WHERE ID=604;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='구르토그 블러드보일' WHERE ID=605;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='잃어버린 자의 성골함' WHERE ID=606;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대모 샤라즈' WHERE ID=607;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='일리다리 의회' WHERE ID=608;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='일리단 스톰레이지' WHERE ID=609;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='왕중왕 마울가르' WHERE ID=649;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='용 학살자 그룰' WHERE ID=650;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아킬존' WHERE ID=778;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='날로라크' WHERE ID=779;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='잔알라이' WHERE ID=780;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='할라지' WHERE ID=781;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='주술 군주 말라크라스' WHERE ID=782;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='줄진' WHERE ID=783;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='공작 켈레세스' WHERE ID=571;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='공작 켈레세스' WHERE ID=572;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='스카발드와 달론' WHERE ID=573;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='스카발드와 달론' WHERE ID=574;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='약탈자 잉그바르' WHERE ID=575;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='약탈자 잉그바르' WHERE ID=576;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='스발라 소로우그레이브' WHERE ID=577;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='스발라 소로우그레이브' WHERE ID=578;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='고르톡 페일후프' WHERE ID=579;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='고르톡 페일후프' WHERE ID=580;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='학살자 스카디' WHERE ID=581;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='학살자 스카디' WHERE ID=582;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='왕 이미론' WHERE ID=583;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='왕 이미론' WHERE ID=584;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='얼어붙은 사령관' WHERE ID=519;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대학자 텔레스트라' WHERE ID=520;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='대학자 텔레스트라' WHERE ID=521;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아노말루스' WHERE ID=522;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아노말루스' WHERE ID=523;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='정원사 오르모로크' WHERE ID=524;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='정원사 오르모로크' WHERE ID=525;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='케리스트라자' WHERE ID=526;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='케리스트라자' WHERE ID=527;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='심문관 드라코스' WHERE ID=528;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='심문관 드라코스' WHERE ID=529;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='바로스 클라우드스트라이더' WHERE ID=530;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='바로스 클라우드스트라이더' WHERE ID=531;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='마법사 군주 우롬' WHERE ID=532;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='마법사 군주 우롬' WHERE ID=533;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='지맥 수호자 에레고스' WHERE ID=534;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='지맥 수호자 에레고스' WHERE ID=535;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='칼렉고스' WHERE ID=724;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='브루탈루스' WHERE ID=725;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='지옥안개' WHERE ID=726;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='에레다르 쌍둥이' WHERE ID=727;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='므우루' WHERE ID=728;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='킬제덴' WHERE ID=729;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='셀린 파이어하트' WHERE ID=414;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='셀린 파이어하트' WHERE ID=415;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='벡살루스' WHERE ID=416;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='벡살루스' WHERE ID=417;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='여사제 델리사' WHERE ID=418;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='여사제 델리사' WHERE ID=419;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='캘타스 선스트라이더' WHERE ID=420;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='캘타스 선스트라이더' WHERE ID=421;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='살덩이갈고리' WHERE ID=293;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='살덩이갈고리' WHERE ID=297;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='살덩이창조자 살람' WHERE ID=294;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='살덩이창조자 살람' WHERE ID=298;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='시간의 군주 에포크' WHERE ID=295;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='시간의 군주 에포크' WHERE ID=299;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='말가니스' WHERE ID=296;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='말가니스' WHERE ID=300;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='크리스탈루스' WHERE ID=563;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='크리스탈루스' WHERE ID=564;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='고뇌의 마녀' WHERE ID=565;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='고뇌의 마녀' WHERE ID=566;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='시대의 심판장' WHERE ID=567;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='시대의 심판장' WHERE ID=568;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='무쇠구체자 쇼니르' WHERE ID=569;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='무쇠구체자 쇼니르' WHERE ID=570;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='송곳아귀' WHERE ID=369;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='송곳아귀' WHERE ID=370;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='소환사 노보스' WHERE ID=371;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='소환사 노보스' WHERE ID=372;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='랩터왕 서슬발톱' WHERE ID=373;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='랩터왕 서슬발톱' WHERE ID=374;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='예언자 타론자' WHERE ID=375;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='예언자 타론자' WHERE ID=376;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='문지기 크릭시르' WHERE ID=216;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='문지기 크릭시르' WHERE ID=264;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='하드로녹스' WHERE ID=217;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='하드로녹스' WHERE ID=265;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아눕아락' WHERE ID=218;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아눕아락' WHERE ID=266;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='장군 비야른그림' WHERE ID=555;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='장군 비야른그림' WHERE ID=556;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='볼칸' WHERE ID=557;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='볼칸' WHERE ID=558;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아이오나' WHERE ID=559;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아이오나' WHERE ID=560;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='로켄' WHERE ID=561;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='로켄' WHERE ID=562;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='거대 화염전차' WHERE ID=744;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='거대 화염전차' WHERE ID=758;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='용광로 군주 이그니스' WHERE ID=745;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='용광로 군주 이그니스' WHERE ID=759;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='칼날비늘' WHERE ID=746;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='XT-002 해체자' WHERE ID=747;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='무쇠 평의회' WHERE ID=748;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='칼날비늘' WHERE ID=760;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='콜로간' WHERE ID=749;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='XT-002 해체자' WHERE ID=761;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아우리아야' WHERE ID=750;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='무쇠 평의회' WHERE ID=762;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='호디르' WHERE ID=751;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='콜로간' WHERE ID=763;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='토림' WHERE ID=752;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아우리아야' WHERE ID=764;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='프레이야' WHERE ID=753;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='호디르' WHERE ID=765;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='미미론' WHERE ID=754;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='토림' WHERE ID=766;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='장군 베작스' WHERE ID=755;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='프레이야' WHERE ID=767;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='요그사론' WHERE ID=756;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='미미론' WHERE ID=768;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='관찰자 알갈론' WHERE ID=757;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='장군 베작스' WHERE ID=769;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='요그사론' WHERE ID=770;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='관찰자 알갈론' WHERE ID=771;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='슬라드란' WHERE ID=383;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='슬라드란' WHERE ID=384;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='드라카리 거대골렘' WHERE ID=385;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='드라카리 거대골렘' WHERE ID=386;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='무라비' WHERE ID=387;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='무라비' WHERE ID=388;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='갈다라' WHERE ID=390;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사나운 엑크' WHERE ID=389;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='갈다라' WHERE ID=391;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='첫 번째 포로' WHERE ID=541;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='첫 번째 포로' WHERE ID=542;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='두 번째 포로' WHERE ID=543;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='두 번째 포로' WHERE ID=544;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='시아니고사' WHERE ID=545;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='시아니고사' WHERE ID=546;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='베스페론' WHERE ID=740;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='테네브론' WHERE ID=736;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='베스페론' WHERE ID=741;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='테네브론' WHERE ID=737;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='샤드론' WHERE ID=738;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='샤드론' WHERE ID=739;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='살타리온' WHERE ID=742;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='살타리온' WHERE ID=743;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='말리고스' WHERE ID=734;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='말리고스' WHERE ID=735;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='장로 나독스' WHERE ID=212;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='장로 나독스' WHERE ID=259;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='공작 탈다람' WHERE ID=213;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='공작 탈다람' WHERE ID=260;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='어둠추적자 제도가' WHERE ID=214;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='어둠추적자 제도가' WHERE ID=261;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사자 볼라즈' WHERE ID=215;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아마니타르' WHERE ID=262;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사자 볼라즈' WHERE ID=263;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='바위 감시자 아카본' WHERE ID=772;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='바위 감시자 아카본' WHERE ID=773;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='폭풍 감시자 에말론' WHERE ID=774;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='폭풍 감시자 에말론' WHERE ID=775;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='화염 감시자 코랄론' WHERE ID=776;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='화염 감시자 코랄론' WHERE ID=777;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='얼음 감시자 토라본' WHERE ID=885;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='얼음 감시자 토라본' WHERE ID=886;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='군주 매로우가르' WHERE ID=845;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='군주 매로우가르' WHERE ID=857;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='여교주 데스위스퍼' WHERE ID=846;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='여교주 데스위스퍼' WHERE ID=858;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='얼음왕관 비행포격선 전투' WHERE ID=847;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='얼음왕관 비행포격선 전투' WHERE ID=859;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='죽음의 인도자 사울팽' WHERE ID=848;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='죽음의 인도자 사울팽' WHERE ID=860;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='구린속' WHERE ID=849;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='구린속' WHERE ID=861;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='썩은얼굴' WHERE ID=850;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='썩은얼굴' WHERE ID=862;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='교수 퓨트리사이드' WHERE ID=851;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='교수 퓨트리사이드' WHERE ID=863;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='피의 의회' WHERE ID=852;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='피의 의회' WHERE ID=864;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='여왕 라나텔' WHERE ID=853;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='여왕 라나텔' WHERE ID=865;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='발리스리아 드림워커' WHERE ID=854;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='발리스리아 드림워커' WHERE ID=866;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='신드라고사' WHERE ID=855;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='신드라고사' WHERE ID=867;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='리치 왕' WHERE ID=856;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='리치 왕' WHERE ID=868;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='브론잠' WHERE ID=829;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='브론잠' WHERE ID=830;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='영혼의 포식자' WHERE ID=831;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='영혼의 포식자' WHERE ID=832;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='노스렌드 야수' WHERE ID=629;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='노스렌드 야수' WHERE ID=630;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='군주 자락서스' WHERE ID=633;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='노스렌드 야수' WHERE ID=631;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='군주 자락서스' WHERE ID=634;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='진영 대표 용사' WHERE ID=637;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='노스렌드 야수' WHERE ID=632;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='군주 자락서스' WHERE ID=635;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='진영 대표 용사' WHERE ID=638;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='발키르 쌍둥이' WHERE ID=641;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='군주 자락서스' WHERE ID=636;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='진영 대표 용사' WHERE ID=639;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='발키르 쌍둥이' WHERE ID=642;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아눕아락' WHERE ID=645;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='진영 대표 용사' WHERE ID=640;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='발키르 쌍둥이' WHERE ID=643;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아눕아락' WHERE ID=646;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='발키르 쌍둥이' WHERE ID=644;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아눕아락' WHERE ID=647;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아눕아락' WHERE ID=648;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='최고 용사' WHERE ID=334;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='최고 용사' WHERE ID=336;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='은빛십자군 용사' WHERE ID=338;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='은빛십자군 용사' WHERE ID=339;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='흑기사' WHERE ID=340;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='흑기사' WHERE ID=341;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='제련장인 가프로스트' WHERE ID=833;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='제련장인 가프로스트' WHERE ID=834;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='크리크' WHERE ID=835;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='크리크' WHERE ID=836;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='스컬지군주 티라누스' WHERE ID=837;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='스컬지군주 티라누스' WHERE ID=838;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='팔릭' WHERE ID=842;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='팔릭' WHERE ID=841;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='마윈' WHERE ID=840;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='마윈' WHERE ID=839;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아서스로부터 탈출' WHERE ID=843;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='아서스로부터 탈출' WHERE ID=844;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='전쟁의 아들 발타루스' WHERE ID=889;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='전쟁의 아들 발타루스' WHERE ID=890;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사비아나 레이지파이어' WHERE ID=891;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='사비아나 레이지파이어' WHERE ID=892;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='장군 자리스리안' WHERE ID=893;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='장군 자리스리안' WHERE ID=894;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='할리온' WHERE ID=887;
UPDATE dbc_dungeonencounter SET Name_Lang_koKR='할리온' WHERE ID=888;
