UPDATE dbc_chrraces SET Name_Lang_koKR='인간', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=1;
UPDATE dbc_chrraces SET Name_Lang_koKR='오크', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=2;
UPDATE dbc_chrraces SET Name_Lang_koKR='드워프', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=3;
UPDATE dbc_chrraces SET Name_Lang_koKR='나이트 엘프', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=4;
UPDATE dbc_chrraces SET Name_Lang_koKR='언데드', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=5;
UPDATE dbc_chrraces SET Name_Lang_koKR='타우렌', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=6;
UPDATE dbc_chrraces SET Name_Lang_koKR='노움', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=7;
UPDATE dbc_chrraces SET Name_Lang_koKR='트롤', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=8;
UPDATE dbc_chrraces SET Name_Lang_koKR='고블린', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=9;
UPDATE dbc_chrraces SET Name_Lang_koKR='블러드 엘프', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=10;
UPDATE dbc_chrraces SET Name_Lang_koKR='드레나이', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=11;
UPDATE dbc_chrraces SET Name_Lang_koKR='타락한 오크', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=12;
UPDATE dbc_chrraces SET Name_Lang_koKR='나가', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=13;
UPDATE dbc_chrraces SET Name_Lang_koKR='뒤틀린 드레나이', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=14;
UPDATE dbc_chrraces SET Name_Lang_koKR='해골', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=15;
UPDATE dbc_chrraces SET Name_Lang_koKR='브리쿨', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=16;
UPDATE dbc_chrraces SET Name_Lang_koKR='투스카르', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=17;
UPDATE dbc_chrraces SET Name_Lang_koKR='숲 트롤', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=18;
UPDATE dbc_chrraces SET Name_Lang_koKR='타운카', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=19;
UPDATE dbc_chrraces SET Name_Lang_koKR='노스렌드 해골', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=20;
UPDATE dbc_chrraces SET Name_Lang_koKR='얼음 트롤', Name_Female_Lang_koKR='', Name_Male_Lang_koKR='' WHERE ID=21;
