UPDATE dbc_faction SET Name_Lang_koKR='플레이어 - 인간', Description_Lang_koKR='' WHERE ID=1;
UPDATE dbc_faction SET Name_Lang_koKR='플레이어 - 오크', Description_Lang_koKR='' WHERE ID=2;
UPDATE dbc_faction SET Name_Lang_koKR='플레이어 - 드워프', Description_Lang_koKR='' WHERE ID=3;
UPDATE dbc_faction SET Name_Lang_koKR='플레이어 - 나이트 엘프', Description_Lang_koKR='' WHERE ID=4;
UPDATE dbc_faction SET Name_Lang_koKR='플레이어 - 언데드', Description_Lang_koKR='' WHERE ID=5;
UPDATE dbc_faction SET Name_Lang_koKR='플레이어 - 타우렌', Description_Lang_koKR='' WHERE ID=6;
UPDATE dbc_faction SET Name_Lang_koKR='생물', Description_Lang_koKR='' WHERE ID=7;
UPDATE dbc_faction SET Name_Lang_koKR='플레이어 - 노움', Description_Lang_koKR='' WHERE ID=8;
UPDATE dbc_faction SET Name_Lang_koKR='플레이어 - 트롤', Description_Lang_koKR='' WHERE ID=9;
UPDATE dbc_faction SET Name_Lang_koKR='몬스터', Description_Lang_koKR='' WHERE ID=14;
UPDATE dbc_faction SET Name_Lang_koKR='데피아즈 결사단', Description_Lang_koKR='' WHERE ID=15;
UPDATE dbc_faction SET Name_Lang_koKR='놀 - 갈퀴발일족', Description_Lang_koKR='' WHERE ID=16;
UPDATE dbc_faction SET Name_Lang_koKR='놀 - 붉은마루일족', Description_Lang_koKR='' WHERE ID=17;
UPDATE dbc_faction SET Name_Lang_koKR='놀 - 잿빛가죽일족', Description_Lang_koKR='' WHERE ID=18;
UPDATE dbc_faction SET Name_Lang_koKR='멀록', Description_Lang_koKR='' WHERE ID=19;
UPDATE dbc_faction SET Name_Lang_koKR='언데드 - 스컬지', Description_Lang_koKR='' WHERE ID=20;
UPDATE dbc_faction SET Name_Lang_koKR='무법항', Description_Lang_koKR='최근 급속한 성장을 이룬 무법항은 검은바다 해적단의 레빌가즈 남작이 다스리고 있는 해안 도시입니다. 스팀휘들 무역회사의 지부이며 붉은해적단과는 적대적 관계입니다.' WHERE ID=21;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 거미', Description_Lang_koKR='' WHERE ID=22;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 멧돼지', Description_Lang_koKR='' WHERE ID=23;
UPDATE dbc_faction SET Name_Lang_koKR='늑대인간', Description_Lang_koKR='' WHERE ID=24;
UPDATE dbc_faction SET Name_Lang_koKR='코볼트', Description_Lang_koKR='' WHERE ID=25;
UPDATE dbc_faction SET Name_Lang_koKR='트롤 - 붉은머리부족', Description_Lang_koKR='' WHERE ID=26;
UPDATE dbc_faction SET Name_Lang_koKR='트롤 - 백골가루부족', Description_Lang_koKR='' WHERE ID=27;
UPDATE dbc_faction SET Name_Lang_koKR='희생물', Description_Lang_koKR='' WHERE ID=28;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 늑대', Description_Lang_koKR='' WHERE ID=29;
UPDATE dbc_faction SET Name_Lang_koKR='데피아즈 결사단 배반자', Description_Lang_koKR='' WHERE ID=30;
UPDATE dbc_faction SET Name_Lang_koKR='아군', Description_Lang_koKR='' WHERE ID=31;
UPDATE dbc_faction SET Name_Lang_koKR='트로그', Description_Lang_koKR='' WHERE ID=32;
UPDATE dbc_faction SET Name_Lang_koKR='트롤 - 서리갈기부족', Description_Lang_koKR='' WHERE ID=33;
UPDATE dbc_faction SET Name_Lang_koKR='오크 - 검은바위부족', Description_Lang_koKR='' WHERE ID=34;
UPDATE dbc_faction SET Name_Lang_koKR='민간인', Description_Lang_koKR='' WHERE ID=35;
UPDATE dbc_faction SET Name_Lang_koKR='희생자', Description_Lang_koKR='' WHERE ID=36;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 곰', Description_Lang_koKR='' WHERE ID=37;
UPDATE dbc_faction SET Name_Lang_koKR='오우거', Description_Lang_koKR='' WHERE ID=38;
UPDATE dbc_faction SET Name_Lang_koKR='쿠르젠의 용병단', Description_Lang_koKR='' WHERE ID=39;
UPDATE dbc_faction SET Name_Lang_koKR='호위 대상', Description_Lang_koKR='' WHERE ID=40;
UPDATE dbc_faction SET Name_Lang_koKR='투자개발회사', Description_Lang_koKR='' WHERE ID=41;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 랩터', Description_Lang_koKR='' WHERE ID=42;
UPDATE dbc_faction SET Name_Lang_koKR='바실리스크', Description_Lang_koKR='' WHERE ID=43;
UPDATE dbc_faction SET Name_Lang_koKR='용군단 - 녹색용군단', Description_Lang_koKR='' WHERE ID=44;
UPDATE dbc_faction SET Name_Lang_koKR='잃어버린 드레나이', Description_Lang_koKR='' WHERE ID=45;
UPDATE dbc_faction SET Name_Lang_koKR='대장기술 - 방어구 제작', Description_Lang_koKR='' WHERE ID=46;
UPDATE dbc_faction SET Name_Lang_koKR='아이언포지', Description_Lang_koKR='자랑스러운 던 모로 드워프들의 수도인 아이언포지는 마그니 국왕이 통치하고 있습니다.' WHERE ID=47;
UPDATE dbc_faction SET Name_Lang_koKR='검은무쇠 드워프', Description_Lang_koKR='' WHERE ID=48;
UPDATE dbc_faction SET Name_Lang_koKR='인간 - 어둠의 순찰대', Description_Lang_koKR='' WHERE ID=49;
UPDATE dbc_faction SET Name_Lang_koKR='용군단 - 붉은용군단', Description_Lang_koKR='' WHERE ID=50;
UPDATE dbc_faction SET Name_Lang_koKR='놀 - 이끼가죽일족', Description_Lang_koKR='' WHERE ID=51;
UPDATE dbc_faction SET Name_Lang_koKR='오크 - 용아귀부족', Description_Lang_koKR='' WHERE ID=52;
UPDATE dbc_faction SET Name_Lang_koKR='노움 - 오염된 노움', Description_Lang_koKR='' WHERE ID=53;
UPDATE dbc_faction SET Name_Lang_koKR='놈리건', Description_Lang_koKR='원래 자랑스러운 놈리건의 시민이었던 노움들은 얼라이언스와 동맹을 맺고 아이언포지에서 망명 생활을 하고 있습니다.' WHERE ID=54;
UPDATE dbc_faction SET Name_Lang_koKR='표범', Description_Lang_koKR='' WHERE ID=55;
UPDATE dbc_faction SET Name_Lang_koKR='붉은십자군', Description_Lang_koKR='' WHERE ID=56;
UPDATE dbc_faction SET Name_Lang_koKR='놀 - 썩은가죽일족', Description_Lang_koKR='' WHERE ID=57;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 고릴라', Description_Lang_koKR='' WHERE ID=58;
UPDATE dbc_faction SET Name_Lang_koKR='토륨 대장조합', Description_Lang_koKR='토륨 대장조합의 드워프들은 각종 세공술로 잘 알려져 있으며 검은바위 산의 비밀을 밝혀내고자 노력하고 있습니다.' WHERE ID=59;
UPDATE dbc_faction SET Name_Lang_koKR='나가', Description_Lang_koKR='' WHERE ID=60;
UPDATE dbc_faction SET Name_Lang_koKR='달라란', Description_Lang_koKR='' WHERE ID=61;
UPDATE dbc_faction SET Name_Lang_koKR='외로운 영혼', Description_Lang_koKR='' WHERE ID=62;
UPDATE dbc_faction SET Name_Lang_koKR='다크하울', Description_Lang_koKR='' WHERE ID=63;
UPDATE dbc_faction SET Name_Lang_koKR='그렐', Description_Lang_koKR='' WHERE ID=64;
UPDATE dbc_faction SET Name_Lang_koKR='펄볼그', Description_Lang_koKR='' WHERE ID=65;
UPDATE dbc_faction SET Name_Lang_koKR='호드', Description_Lang_koKR='' WHERE ID=66;
UPDATE dbc_faction SET Name_Lang_koKR='호드 연합', Description_Lang_koKR='' WHERE ID=67;
UPDATE dbc_faction SET Name_Lang_koKR='언더시티', Description_Lang_koKR='실바나스 윈드러너가 이끄는 포세이큰은 호드와 미약한 동맹 관계를 유지하고 있으며 로데론의 폐허 지하 깊숙한 곳에 도시를 건설하였습니다.' WHERE ID=68;
UPDATE dbc_faction SET Name_Lang_koKR='다르나서스', Description_Lang_koKR='나이트 엘프의 수도인 다르나서스는 텔드랏실 섬에 위치해 있습니다. 달의 여사제 티란데 위스퍼윈드가 이끌고 있습니다.' WHERE ID=69;
UPDATE dbc_faction SET Name_Lang_koKR='비밀결사대', Description_Lang_koKR='원래 인간 범죄 집단이었던 비밀결사대는 힐스브래드 구릉지와 알터랙 산맥 등지에서 활동하고 있습니다.' WHERE ID=70;
UPDATE dbc_faction SET Name_Lang_koKR='힐스브래드 민병대', Description_Lang_koKR='' WHERE ID=71;
UPDATE dbc_faction SET Name_Lang_koKR='스톰윈드', Description_Lang_koKR='인간 세력의 최후의 보루 중 하나인 스톰윈드는 돌아온 국왕 바리안 린이 통치하고 있습니다.' WHERE ID=72;
UPDATE dbc_faction SET Name_Lang_koKR='악마', Description_Lang_koKR='' WHERE ID=73;
UPDATE dbc_faction SET Name_Lang_koKR='정령', Description_Lang_koKR='' WHERE ID=74;
UPDATE dbc_faction SET Name_Lang_koKR='영혼', Description_Lang_koKR='' WHERE ID=75;
UPDATE dbc_faction SET Name_Lang_koKR='오그리마', Description_Lang_koKR='스랄에 의해 건설된 호드의 수도인 오그리마는 듀로타에 살고 있는 여러 자랑스러운 오크 부족들의 고향입니다.' WHERE ID=76;
UPDATE dbc_faction SET Name_Lang_koKR='보물', Description_Lang_koKR='' WHERE ID=77;
UPDATE dbc_faction SET Name_Lang_koKR='놀 - 진흙주둥이일족', Description_Lang_koKR='' WHERE ID=78;
UPDATE dbc_faction SET Name_Lang_koKR='힐스브래드 - 사우스쇼어 시장', Description_Lang_koKR='' WHERE ID=79;
UPDATE dbc_faction SET Name_Lang_koKR='용군단 - 검은용군단', Description_Lang_koKR='' WHERE ID=80;
UPDATE dbc_faction SET Name_Lang_koKR='썬더 블러프', Description_Lang_koKR='강력한 호드 대도시 중 하나인 이곳 썬더 블러프는 케른 블러드후프 족장이 이끄는 자랑스러운 타우렌들의 고향입니다.' WHERE ID=81;
UPDATE dbc_faction SET Name_Lang_koKR='트롤 - 마른나무껍질부족', Description_Lang_koKR='' WHERE ID=82;
UPDATE dbc_faction SET Name_Lang_koKR='가죽세공 - 정기', Description_Lang_koKR='' WHERE ID=83;
UPDATE dbc_faction SET Name_Lang_koKR='가시멧돼지 - 서슬갈기일족', Description_Lang_koKR='' WHERE ID=84;
UPDATE dbc_faction SET Name_Lang_koKR='가시멧돼지 - 뾰족털일족', Description_Lang_koKR='' WHERE ID=85;
UPDATE dbc_faction SET Name_Lang_koKR='가죽세공 - 용비늘', Description_Lang_koKR='' WHERE ID=86;
UPDATE dbc_faction SET Name_Lang_koKR='붉은해적단', Description_Lang_koKR='피에 굶주린 붉은해적단은 바다에서 무역을 벌이고 있는 여러 상인들의 천적입니다. 무법항과는 적대 관계입니다.' WHERE ID=87;
UPDATE dbc_faction SET Name_Lang_koKR='검은심연', Description_Lang_koKR='' WHERE ID=88;
UPDATE dbc_faction SET Name_Lang_koKR='마크루라', Description_Lang_koKR='' WHERE ID=89;
UPDATE dbc_faction SET Name_Lang_koKR='켄타우로스 - 콜카르일족', Description_Lang_koKR='' WHERE ID=90;
UPDATE dbc_faction SET Name_Lang_koKR='켄타우로스 - 갈라크일족', Description_Lang_koKR='' WHERE ID=91;
UPDATE dbc_faction SET Name_Lang_koKR='켄타우로스 - 겔키스일족', Description_Lang_koKR='겔키스 일족은 잊혀진 땅 남부 지역에 터전을 마련하고 있습니다. 마그람 일족과는 원수 지간입니다.' WHERE ID=92;
UPDATE dbc_faction SET Name_Lang_koKR='켄타우로스 - 마그람일족', Description_Lang_koKR='마그람 일족은 잊혀진 땅 동부 지역에 터전을 마련하고 있습니다. 겔키스 일족과는 원수 지간입니다.' WHERE ID=93;
UPDATE dbc_faction SET Name_Lang_koKR='마라우딘일족', Description_Lang_koKR='' WHERE ID=94;
UPDATE dbc_faction SET Name_Lang_koKR='테라모어', Description_Lang_koKR='' WHERE ID=108;
UPDATE dbc_faction SET Name_Lang_koKR='가시멧돼지 - 가시덩굴일족', Description_Lang_koKR='' WHERE ID=109;
UPDATE dbc_faction SET Name_Lang_koKR='가시멧돼지 - 서슬갈기일족 2', Description_Lang_koKR='' WHERE ID=110;
UPDATE dbc_faction SET Name_Lang_koKR='가시멧돼지 - 죽음의 머리교', Description_Lang_koKR='' WHERE ID=111;
UPDATE dbc_faction SET Name_Lang_koKR='적', Description_Lang_koKR='' WHERE ID=128;
UPDATE dbc_faction SET Name_Lang_koKR='동물', Description_Lang_koKR='' WHERE ID=148;
UPDATE dbc_faction SET Name_Lang_koKR='네더가드 짐마차', Description_Lang_koKR='' WHERE ID=168;
UPDATE dbc_faction SET Name_Lang_koKR='스팀휘들 무역회사', Description_Lang_koKR='' WHERE ID=169;
UPDATE dbc_faction SET Name_Lang_koKR='얼라이언스', Description_Lang_koKR='' WHERE ID=189;
UPDATE dbc_faction SET Name_Lang_koKR='네더가드', Description_Lang_koKR='' WHERE ID=209;
UPDATE dbc_faction SET Name_Lang_koKR='통곡의 동굴', Description_Lang_koKR='' WHERE ID=229;
UPDATE dbc_faction SET Name_Lang_koKR='실리시드', Description_Lang_koKR='' WHERE ID=249;
UPDATE dbc_faction SET Name_Lang_koKR='실버문 생존자', Description_Lang_koKR='' WHERE ID=269;
UPDATE dbc_faction SET Name_Lang_koKR='잔달라 부족', Description_Lang_koKR='잔달라 부족은 요잠바 섬으로 와서 줄구룹의 부활한 혈신과 아탈라이 사제에 맞서 싸우기 위해 모험가들의 도움을 구하고 있습니다.' WHERE ID=270;
UPDATE dbc_faction SET Name_Lang_koKR='대장기술 - 무기 제작', Description_Lang_koKR='' WHERE ID=289;
UPDATE dbc_faction SET Name_Lang_koKR='전갈', Description_Lang_koKR='' WHERE ID=309;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 박쥐', Description_Lang_koKR='' WHERE ID=310;
UPDATE dbc_faction SET Name_Lang_koKR='티탄', Description_Lang_koKR='' WHERE ID=311;
UPDATE dbc_faction SET Name_Lang_koKR='감독관 피즐', Description_Lang_koKR='' WHERE ID=329;
UPDATE dbc_faction SET Name_Lang_koKR='라벤홀트 암살단', Description_Lang_koKR='도적과 암살자 길드인 라벤홀트 암살단의 일원이 되려면 비상한 솜씨를 지녀야 합니다. 비밀결사대와는 적대 관계입니다.' WHERE ID=349;
UPDATE dbc_faction SET Name_Lang_koKR='가젯잔', Description_Lang_koKR='스팀휘들 무역회사의 본거지인 이곳은 고블린 최고의 기술자들과 연금술사, 상인들의 고향입니다.' WHERE ID=369;
UPDATE dbc_faction SET Name_Lang_koKR='놈리건 버그', Description_Lang_koKR='' WHERE ID=389;
UPDATE dbc_faction SET Name_Lang_koKR='하피', Description_Lang_koKR='' WHERE ID=409;
UPDATE dbc_faction SET Name_Lang_koKR='불타는 칼날단', Description_Lang_koKR='' WHERE ID=429;
UPDATE dbc_faction SET Name_Lang_koKR='그늘거미 밀렵꾼', Description_Lang_koKR='' WHERE ID=449;
UPDATE dbc_faction SET Name_Lang_koKR='용암거미', Description_Lang_koKR='' WHERE ID=450;
UPDATE dbc_faction SET Name_Lang_koKR='얼라이언스 연합', Description_Lang_koKR='' WHERE ID=469;
UPDATE dbc_faction SET Name_Lang_koKR='톱니항', Description_Lang_koKR='스팀휘들 무역회사의 지부인 이곳은 불모의 땅에서 여러 상품을 거래하고자 하는 이들에겐 천국과 같은 곳입니다.' WHERE ID=470;
UPDATE dbc_faction SET Name_Lang_koKR='와일드해머 드워프', Description_Lang_koKR='맹금의 봉우리에 살고 있는 와일드해머 드워프들은 비록 얼라이언스의 일원은 아니지만 얼라이언스와 협력 관계를 유지하고 있으며 호드와는 적대 관계입니다.' WHERE ID=471;
UPDATE dbc_faction SET Name_Lang_koKR='고블린 - 검은무쇠 주점 손님', Description_Lang_koKR='' WHERE ID=489;
UPDATE dbc_faction SET Name_Lang_koKR='아라소르 연맹', Description_Lang_koKR='스톰윈드의 후원을 받고 있는 아라소르 연맹은 아라시 분지의 잃어버린 땅을 되찾기 위해 투쟁하고 있습니다.' WHERE ID=509;
UPDATE dbc_faction SET Name_Lang_koKR='포세이큰 파멸단', Description_Lang_koKR='포세이큰 파멸단은 호드를 위해 아라소르 분지에 있는 귀중한 자원을 차지하기 위한 투쟁을 벌이고 있습니다.' WHERE ID=510;
UPDATE dbc_faction SET Name_Lang_koKR='거인', Description_Lang_koKR='' WHERE ID=511;
UPDATE dbc_faction SET Name_Lang_koKR='은빛 여명회', Description_Lang_koKR='스컬지의 위협에서 아제로스를 지켜내고자 결성된 단체입니다. 은빛 여명회의 주요 거점은 동부 및 서부 역병지대에 위치하고 있습니다.' WHERE ID=529;
UPDATE dbc_faction SET Name_Lang_koKR='검은창 트롤', Description_Lang_koKR='트롤 사회에서 추방당한 검은창 부족은 스랄과 손을 잡고 호드 진영과 힘을 합치게 됩니다. 이제 그들은 동맹인 오크들과 함께 듀로타에 터전을 마련하여 생활하고 있습니다.' WHERE ID=530;
UPDATE dbc_faction SET Name_Lang_koKR='용군단 - 청동용군단', Description_Lang_koKR='' WHERE ID=531;
UPDATE dbc_faction SET Name_Lang_koKR='용군단 - 푸른용군단', Description_Lang_koKR='' WHERE ID=532;
UPDATE dbc_faction SET Name_Lang_koKR='가죽세공 - 부족전통', Description_Lang_koKR='' WHERE ID=549;
UPDATE dbc_faction SET Name_Lang_koKR='기계공학 - 고블린', Description_Lang_koKR='' WHERE ID=550;
UPDATE dbc_faction SET Name_Lang_koKR='기계공학 - 노움', Description_Lang_koKR='' WHERE ID=551;
UPDATE dbc_faction SET Name_Lang_koKR='대장기술 - 망치 제작', Description_Lang_koKR='' WHERE ID=569;
UPDATE dbc_faction SET Name_Lang_koKR='대장기술 - 도끼 제작', Description_Lang_koKR='' WHERE ID=570;
UPDATE dbc_faction SET Name_Lang_koKR='대장기술 - 검 제작', Description_Lang_koKR='' WHERE ID=571;
UPDATE dbc_faction SET Name_Lang_koKR='트롤 - 썩은가지부족', Description_Lang_koKR='' WHERE ID=572;
UPDATE dbc_faction SET Name_Lang_koKR='남쪽바다 해적단', Description_Lang_koKR='' WHERE ID=573;
UPDATE dbc_faction SET Name_Lang_koKR='카엘 다로우', Description_Lang_koKR='' WHERE ID=574;
UPDATE dbc_faction SET Name_Lang_koKR='오염되지 않은 펄볼그', Description_Lang_koKR='' WHERE ID=575;
UPDATE dbc_faction SET Name_Lang_koKR='나무구렁 요새', Description_Lang_koKR='타락하지 않은 마지막 펄볼그 부족인 나무구렁부족은 동족의 고통을 끝내고 자신들의 주체성을 지킬 방법을 모색하고 있습니다.' WHERE ID=576;
UPDATE dbc_faction SET Name_Lang_koKR='눈망루 마을', Description_Lang_koKR='스팀휘들 무역회사의 고블린들이 무역 거점으로 운영 중인 이곳은 여명의 설원을 가로지르는 주 무역로가 교차되는 지점에 위치하고 있습니다.' WHERE ID=577;
UPDATE dbc_faction SET Name_Lang_koKR='눈호랑이 조련사', Description_Lang_koKR='이들은 은둔 중인 나이트 엘프들이며 여명의 설원에서 눈호랑이를 기르고 훈련시킵니다.' WHERE ID=589;
UPDATE dbc_faction SET Name_Lang_koKR='세나리온 의회', Description_Lang_koKR='세나리온 의회의 드루이드들은 자연의 수호자이며 평온한 달의 숲이 그들의 고향입니다.' WHERE ID=609;
UPDATE dbc_faction SET Name_Lang_koKR='트롤 - 뾰족창부족', Description_Lang_koKR='' WHERE ID=629;
UPDATE dbc_faction SET Name_Lang_koKR='라바사우루스 조련사', Description_Lang_koKR='' WHERE ID=630;
UPDATE dbc_faction SET Name_Lang_koKR='청지기 이그젝큐투스', Description_Lang_koKR='' WHERE ID=649;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 독수리', Description_Lang_koKR='' WHERE ID=669;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 살쾡이', Description_Lang_koKR='' WHERE ID=670;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 게', Description_Lang_koKR='' WHERE ID=671;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 악어', Description_Lang_koKR='' WHERE ID=672;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 하이에나', Description_Lang_koKR='' WHERE ID=673;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 올빼미', Description_Lang_koKR='' WHERE ID=674;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 전갈', Description_Lang_koKR='' WHERE ID=675;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 타조', Description_Lang_koKR='' WHERE ID=676;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 거북', Description_Lang_koKR='' WHERE ID=677;
UPDATE dbc_faction SET Name_Lang_koKR='야수 - 천둥매', Description_Lang_koKR='' WHERE ID=678;
UPDATE dbc_faction SET Name_Lang_koKR='훈련용 허수아비', Description_Lang_koKR='' WHERE ID=679;
UPDATE dbc_faction SET Name_Lang_koKR='용군단 - 검은용군단 (미끼)', Description_Lang_koKR='' WHERE ID=689;
UPDATE dbc_faction SET Name_Lang_koKR='전장 중립', Description_Lang_koKR='' WHERE ID=709;
UPDATE dbc_faction SET Name_Lang_koKR='서리늑대 부족', Description_Lang_koKR='서리늑대 부족은 알터랙 계곡에서 스톰파이크 원정대의 드워프들을 몰아내고자 투쟁하고 있습니다.' WHERE ID=729;
UPDATE dbc_faction SET Name_Lang_koKR='스톰파이크 경비대', Description_Lang_koKR='스톰파이크 드워프들은 오크 서리늑대 부족과 전투가 벌어지고 있는 알터랙 계곡에 거점을 마련하고 있습니다.' WHERE ID=730;
UPDATE dbc_faction SET Name_Lang_koKR='히드락시안 물의 군주', Description_Lang_koKR='이 정령들은 아즈샤라 동부의 섬에 위치하고 있습니다. 라그나로스 군대와는 적대 관계입니다.' WHERE ID=749;
UPDATE dbc_faction SET Name_Lang_koKR='설퍼론 불의 군주', Description_Lang_koKR='' WHERE ID=750;
UPDATE dbc_faction SET Name_Lang_koKR='기즐록의 허수아비', Description_Lang_koKR='' WHERE ID=769;
UPDATE dbc_faction SET Name_Lang_koKR='기즐록의 부적', Description_Lang_koKR='' WHERE ID=770;
UPDATE dbc_faction SET Name_Lang_koKR='기즐록', Description_Lang_koKR='' WHERE ID=771;
UPDATE dbc_faction SET Name_Lang_koKR='모로가이', Description_Lang_koKR='' WHERE ID=789;
UPDATE dbc_faction SET Name_Lang_koKR='영혼의 인도자 - 얼라이언스', Description_Lang_koKR='' WHERE ID=790;
UPDATE dbc_faction SET Name_Lang_koKR='셴드랄라', Description_Lang_koKR='한때 혈투의 전장에서 살던 강력한 엘프 가문입니다. 그들은 여전히 지혜로우며 위대한 비밀을 간직한 존재들입니다.' WHERE ID=809;
UPDATE dbc_faction SET Name_Lang_koKR='오우거 (대장 크롬크러쉬)', Description_Lang_koKR='' WHERE ID=829;
UPDATE dbc_faction SET Name_Lang_koKR='영혼의 인도자 - 호드', Description_Lang_koKR='' WHERE ID=849;
UPDATE dbc_faction SET Name_Lang_koKR='자에데나르', Description_Lang_koKR='' WHERE ID=869;
UPDATE dbc_faction SET Name_Lang_koKR='전쟁노래 정찰대', Description_Lang_koKR='용맹한 오크로 구성된 전쟁노래 부족은 전쟁노래 협곡에서 은빛날개 파수대와 치열한 전투를 벌이고 있습니다.' WHERE ID=889;
UPDATE dbc_faction SET Name_Lang_koKR='은빛날개 파수대', Description_Lang_koKR='잿빛 골짜기의 믿음직한 파수꾼인 은빛날개 파수대는 전쟁노래 협곡에서 전쟁노래 정찰대와 치열한 전투를 벌이고 있습니다.' WHERE ID=890;
UPDATE dbc_faction SET Name_Lang_koKR='얼라이언스 군대', Description_Lang_koKR='' WHERE ID=891;
UPDATE dbc_faction SET Name_Lang_koKR='호드 군대', Description_Lang_koKR='' WHERE ID=892;
UPDATE dbc_faction SET Name_Lang_koKR='레반터스크 트롤', Description_Lang_koKR='' WHERE ID=893;
UPDATE dbc_faction SET Name_Lang_koKR='다크문 유랑단', Description_Lang_koKR='신기하고 괴상한 것들을 선보이며 각지를 떠도는 다크문 유랑단은 엘윈 숲, 멀고어, 테로카르 숲에서 축제를 열곤 합니다.' WHERE ID=909;
UPDATE dbc_faction SET Name_Lang_koKR='노즈도르무 혈족', Description_Lang_koKR='청동용군단의 후예들인 노즈도르무 혈족은 시간의 수호자이며 필멸의 종족들에게 별다른 관심을 보이지 않습니다.' WHERE ID=910;
UPDATE dbc_faction SET Name_Lang_koKR='실버문', Description_Lang_koKR='블러드 엘프의 땅, 쿠엘탈라스의 수도인 실버문은 아서스가 태양샘을 공격하여 거의 파괴되었지만 다시 한번 번창의 시기를 맞이하고 있습니다.' WHERE ID=911;
UPDATE dbc_faction SET Name_Lang_koKR='칼림도어 연합군', Description_Lang_koKR='' WHERE ID=912;
UPDATE dbc_faction SET Name_Lang_koKR='플레이어, 블러드 엘프', Description_Lang_koKR='' WHERE ID=914;
UPDATE dbc_faction SET Name_Lang_koKR='쑨의 군대', Description_Lang_koKR='' WHERE ID=915;
UPDATE dbc_faction SET Name_Lang_koKR='실리시드 침략자', Description_Lang_koKR='' WHERE ID=916;
UPDATE dbc_faction SET Name_Lang_koKR='아이언포지 여단', Description_Lang_koKR='' WHERE ID=917;
UPDATE dbc_faction SET Name_Lang_koKR='무선조종 적', Description_Lang_koKR='' WHERE ID=918;
UPDATE dbc_faction SET Name_Lang_koKR='무선조종 장난감', Description_Lang_koKR='' WHERE ID=919;
UPDATE dbc_faction SET Name_Lang_koKR='홍팀', Description_Lang_koKR='' WHERE ID=920;
UPDATE dbc_faction SET Name_Lang_koKR='청팀', Description_Lang_koKR='' WHERE ID=921;
UPDATE dbc_faction SET Name_Lang_koKR='트랜퀼리엔', Description_Lang_koKR='한때 하이 엘프 마을이었던 트랜퀼리엔은 스컬지의 쿠엘탈라스 침공 이후 버려졌습니다. 이제 유령의 땅에서 스컬지를 몰아내려는 포세이큰과 블러드 엘프의 보금자리가 되었습니다.' WHERE ID=922;
UPDATE dbc_faction SET Name_Lang_koKR='원정순찰대', Description_Lang_koKR='' WHERE ID=923;
UPDATE dbc_faction SET Name_Lang_koKR='DEPRECATED', Description_Lang_koKR='' WHERE ID=924;
UPDATE dbc_faction SET Name_Lang_koKR='선스트라이더', Description_Lang_koKR='' WHERE ID=925;
UPDATE dbc_faction SET Name_Lang_koKR='마법학자 길드', Description_Lang_koKR='' WHERE ID=926;
UPDATE dbc_faction SET Name_Lang_koKR='플레이어, 드레나이', Description_Lang_koKR='' WHERE ID=927;
UPDATE dbc_faction SET Name_Lang_koKR='스컬지 침략군', Description_Lang_koKR='' WHERE ID=928;
UPDATE dbc_faction SET Name_Lang_koKR='피망치 일족', Description_Lang_koKR='' WHERE ID=929;
UPDATE dbc_faction SET Name_Lang_koKR='엑소다르', Description_Lang_koKR='드레나이가 아제로스에 타고 온 나루 함선입니다. 하늘안개 섬에 추락해 있지만 지금은 고귀한 드레나이 종족의 고향으로서의 역할을 수행하고 있습니다.' WHERE ID=930;
UPDATE dbc_faction SET Name_Lang_koKR='Test Faction (not a real faction)', Description_Lang_koKR='This faction only exists to test the editing of faction names and descriptions...' WHERE ID=931;
UPDATE dbc_faction SET Name_Lang_koKR='알도르 사제회', Description_Lang_koKR='알도르 사제회는 드레나이 사제 계급의 고대 모임으로 과거엔 벨렌이 이끌었으나 현재는 대여사제 이샤나가 이끌고 있습니다. 그들은 샤타르로 알려진 샤트라스의 나루를 섬기고 있습니다. 점술가 길드와는 경쟁 관계에 있습니다.' WHERE ID=932;
UPDATE dbc_faction SET Name_Lang_koKR='무역연합', Description_Lang_koKR='연합왕자 하라매드가 이끌고 있는 무역연합은 아웃랜드의 부를 노리고 몰려든 에테리얼 밀수꾼과 무역상, 도둑으로 구성된 연합 지부입니다.' WHERE ID=933;
UPDATE dbc_faction SET Name_Lang_koKR='점술가 길드', Description_Lang_koKR='점술가 길드는 마력으로 이끄는 캘타스의 길을 거부한 반체제 블러드 엘프 단체로 현자 보렌살이 이끌고 있습니다. 이들은 알도르의 우려에도 불구하고 최근 샤트라스의 나루와 손을 잡았습니다.' WHERE ID=934;
UPDATE dbc_faction SET Name_Lang_koKR='샤타르', Description_Lang_koKR='샤타르는 재건된 샤트라스를 지배하고 있는 강력한 나루로 이루어진 단체입니다. 알도르 사제회와 점술가 길드의 도움으로 일리단과 불타는 군단에 맞서 전투를 이끌고 있습니다.' WHERE ID=935;
UPDATE dbc_faction SET Name_Lang_koKR='샤트라스', Description_Lang_koKR='' WHERE ID=936;
UPDATE dbc_faction SET Name_Lang_koKR='트롤 - 숲', Description_Lang_koKR='' WHERE ID=937;
UPDATE dbc_faction SET Name_Lang_koKR='오메나이', Description_Lang_koKR='' WHERE ID=938;
UPDATE dbc_faction SET Name_Lang_koKR='DEPRECATED', Description_Lang_koKR='' WHERE ID=939;
UPDATE dbc_faction SET Name_Lang_koKR='로서의 후예들', Description_Lang_koKR='' WHERE ID=940;
UPDATE dbc_faction SET Name_Lang_koKR='마그하르', Description_Lang_koKR='은둔 생활을 하고 있는 이 갈색 피부의 오크들은 악마의 타락으로부터 벗어날 수 있었습니다. 이들은 전통적인 삶의 방식을 고수하면서 아웃랜드에 닥친 변화의 바람에 맞서고 있습니다.' WHERE ID=941;
UPDATE dbc_faction SET Name_Lang_koKR='세나리온 원정대', Description_Lang_koKR='세나리온 원정대는 아웃랜드에서 살아 남은 생명체 연구를 위해 세나리온 의회에서 파견한 원정대입니다. 세나리온 원정대는 어둠의 문이 열린 후 빠른 시간 내에 규모를 확장하고 자주권을 확보하였습니다.' WHERE ID=942;
UPDATE dbc_faction SET Name_Lang_koKR='타락한 오크', Description_Lang_koKR='' WHERE ID=943;
UPDATE dbc_faction SET Name_Lang_koKR='타락한 오크 유령', Description_Lang_koKR='' WHERE ID=944;
UPDATE dbc_faction SET Name_Lang_koKR='로서의 후예 유령', Description_Lang_koKR='' WHERE ID=945;
UPDATE dbc_faction SET Name_Lang_koKR='명예의 요새', Description_Lang_koKR='명예의 요새는 얼라이언스 정예군인 로서의 후예가 드레노어에 처음 도착했을 때 건설한 요새이며 지옥불 반도의 전초기지로서 역할을 수행하고 있습니다. 지금은 스톰윈드와 아이언포지의 군대가 파견되어 주둔 중입니다.' WHERE ID=946;
UPDATE dbc_faction SET Name_Lang_koKR='스랄마', Description_Lang_koKR='스랄의 명에 의해 어둠의 문을 넘어 지옥불 반도에 도착한 원정대는 성채를 건설하고 스랄마라 이름 지었습니다. 스랄마는 아웃랜드에서 활동 중인 호드의 작전 기지 역할을 수행하고 있습니다.' WHERE ID=947;
UPDATE dbc_faction SET Name_Lang_koKR='Test Faction 2', Description_Lang_koKR='' WHERE ID=948;
UPDATE dbc_faction SET Name_Lang_koKR='Test Faction 1', Description_Lang_koKR='' WHERE ID=949;
UPDATE dbc_faction SET Name_Lang_koKR='ToWoW - Flag', Description_Lang_koKR='' WHERE ID=950;
UPDATE dbc_faction SET Name_Lang_koKR='ToWoW - Flag Trigger Alliance (DND)', Description_Lang_koKR='' WHERE ID=951;
UPDATE dbc_faction SET Name_Lang_koKR='Test Faction 3', Description_Lang_koKR='' WHERE ID=952;
UPDATE dbc_faction SET Name_Lang_koKR='Test Faction 4', Description_Lang_koKR='' WHERE ID=953;
UPDATE dbc_faction SET Name_Lang_koKR='ToWoW - Flag Trigger Horde (DND)', Description_Lang_koKR='' WHERE ID=954;
UPDATE dbc_faction SET Name_Lang_koKR='뒤틀린 드레나이', Description_Lang_koKR='' WHERE ID=955;
UPDATE dbc_faction SET Name_Lang_koKR='에테리움', Description_Lang_koKR='' WHERE ID=956;
UPDATE dbc_faction SET Name_Lang_koKR='대지의 정령', Description_Lang_koKR='' WHERE ID=957;
UPDATE dbc_faction SET Name_Lang_koKR='전투 로봇', Description_Lang_koKR='' WHERE ID=958;
UPDATE dbc_faction SET Name_Lang_koKR='선', Description_Lang_koKR='' WHERE ID=959;
UPDATE dbc_faction SET Name_Lang_koKR='악', Description_Lang_koKR='' WHERE ID=960;
UPDATE dbc_faction SET Name_Lang_koKR='너울소나무 펄볼그', Description_Lang_koKR='' WHERE ID=961;
UPDATE dbc_faction SET Name_Lang_koKR='미쳐버린 올빼미야수', Description_Lang_koKR='' WHERE ID=962;
UPDATE dbc_faction SET Name_Lang_koKR='체스 얼라이언스', Description_Lang_koKR='' WHERE ID=963;
UPDATE dbc_faction SET Name_Lang_koKR='체스 호드', Description_Lang_koKR='' WHERE ID=964;
UPDATE dbc_faction SET Name_Lang_koKR='Monster Spar', Description_Lang_koKR='' WHERE ID=965;
UPDATE dbc_faction SET Name_Lang_koKR='Monster Spar Buddy', Description_Lang_koKR='' WHERE ID=966;
UPDATE dbc_faction SET Name_Lang_koKR='보랏빛 눈의 감시자', Description_Lang_koKR='보랏빛 눈의 감시자는 메디브와 그의 활동을 감시하기 위해 설립된 키린 토의 비밀 단체입니다.' WHERE ID=967;
UPDATE dbc_faction SET Name_Lang_koKR='태양매 정찰대', Description_Lang_koKR='' WHERE ID=968;
UPDATE dbc_faction SET Name_Lang_koKR='아르거스의 대리인', Description_Lang_koKR='' WHERE ID=969;
UPDATE dbc_faction SET Name_Lang_koKR='스포어가르', Description_Lang_koKR='스포어가르는 아웃랜드 토착 종족인 평화로운 버섯인간이 살고 있는 마을입니다. 이 마을은 장가르 습지대의 남부 늪지대에 위치하고 있습니다.' WHERE ID=970;
UPDATE dbc_faction SET Name_Lang_koKR='곰팡이 거인', Description_Lang_koKR='' WHERE ID=971;
UPDATE dbc_faction SET Name_Lang_koKR='포자날개', Description_Lang_koKR='' WHERE ID=972;
UPDATE dbc_faction SET Name_Lang_koKR='Monster, Predator', Description_Lang_koKR='' WHERE ID=973;
UPDATE dbc_faction SET Name_Lang_koKR='Monster, Prey', Description_Lang_koKR='' WHERE ID=974;
UPDATE dbc_faction SET Name_Lang_koKR='공허의 변형물', Description_Lang_koKR='' WHERE ID=975;
UPDATE dbc_faction SET Name_Lang_koKR='하이잘 수비군', Description_Lang_koKR='' WHERE ID=976;
UPDATE dbc_faction SET Name_Lang_koKR='하이잘 침략군', Description_Lang_koKR='' WHERE ID=977;
UPDATE dbc_faction SET Name_Lang_koKR='쿠레나이', Description_Lang_koKR='이들은 타락에서 다시 회복된 드레나이들입니다. 이 뒤틀린 드레나이들은 아웃랜드의 지배 계급으로부터 탈출하여 나그란드에 정착하였습니다. 거기서 이들은 자신들의 운명을 되찾으려는 노력을 기울이고 있습니다.' WHERE ID=978;
UPDATE dbc_faction SET Name_Lang_koKR='속세의 고리회', Description_Lang_koKR='' WHERE ID=979;
UPDATE dbc_faction SET Name_Lang_koKR='불타는 성전', Description_Lang_koKR='' WHERE ID=980;
UPDATE dbc_faction SET Name_Lang_koKR='아라코아', Description_Lang_koKR='' WHERE ID=981;
UPDATE dbc_faction SET Name_Lang_koKR='장가르 습지대 깃발 (얼라이언스)', Description_Lang_koKR='' WHERE ID=982;
UPDATE dbc_faction SET Name_Lang_koKR='장가르 습지대 깃발 (호드)', Description_Lang_koKR='' WHERE ID=983;
UPDATE dbc_faction SET Name_Lang_koKR='장가르 습지대 깃발 (중립)', Description_Lang_koKR='' WHERE ID=984;
UPDATE dbc_faction SET Name_Lang_koKR='시간의 동굴 - 스랄', Description_Lang_koKR='' WHERE ID=985;
UPDATE dbc_faction SET Name_Lang_koKR='시간의 동굴 - 던홀드', Description_Lang_koKR='' WHERE ID=986;
UPDATE dbc_faction SET Name_Lang_koKR='시간의 동굴 - 사우스쇼어 경비대', Description_Lang_koKR='' WHERE ID=987;
UPDATE dbc_faction SET Name_Lang_koKR='어둠의 의회', Description_Lang_koKR='' WHERE ID=988;
UPDATE dbc_faction SET Name_Lang_koKR='시간의 수호자', Description_Lang_koKR='시간의 수호자들은 노즈도르무에 의해 선별되어 시간의 동굴을 감시하는 임무를 맡은 청동용들입니다.' WHERE ID=989;
UPDATE dbc_faction SET Name_Lang_koKR='시간의 중재자', Description_Lang_koKR='청동용군단 내의 비밀 조직으로서 노즈도르무의 배필인 소리도르미가 이끌고 있습니다.' WHERE ID=990;
UPDATE dbc_faction SET Name_Lang_koKR='어둠의 문 수비군, 얼라이언스', Description_Lang_koKR='' WHERE ID=991;
UPDATE dbc_faction SET Name_Lang_koKR='어둠의 문 수비군, 호드', Description_Lang_koKR='' WHERE ID=992;
UPDATE dbc_faction SET Name_Lang_koKR='어둠의 문 공격군, 군단', Description_Lang_koKR='' WHERE ID=993;
UPDATE dbc_faction SET Name_Lang_koKR='Inciter Trigger', Description_Lang_koKR='Used for the Blackheart the Inciter event.' WHERE ID=994;
UPDATE dbc_faction SET Name_Lang_koKR='Inciter Trigger 2', Description_Lang_koKR='Used for the Blackheart the Inciter event.' WHERE ID=995;
UPDATE dbc_faction SET Name_Lang_koKR='Inciter Trigger 3', Description_Lang_koKR='Used for the Blackheart the Inciter event.' WHERE ID=996;
UPDATE dbc_faction SET Name_Lang_koKR='Inciter Trigger 4', Description_Lang_koKR='Used for the Blackheart the Inciter event.' WHERE ID=997;
UPDATE dbc_faction SET Name_Lang_koKR='Inciter Trigger 5', Description_Lang_koKR='Used for the Blackheart the Inciter event.' WHERE ID=998;
UPDATE dbc_faction SET Name_Lang_koKR='마나 피조물', Description_Lang_koKR='' WHERE ID=999;
UPDATE dbc_faction SET Name_Lang_koKR='카드가의 하수인', Description_Lang_koKR='' WHERE ID=1000;
UPDATE dbc_faction SET Name_Lang_koKR='칼날첨탑 일족', Description_Lang_koKR='' WHERE ID=1001;
UPDATE dbc_faction SET Name_Lang_koKR='Ethereum Sparbuddy', Description_Lang_koKR='' WHERE ID=1002;
UPDATE dbc_faction SET Name_Lang_koKR='자유연합', Description_Lang_koKR='' WHERE ID=1003;
UPDATE dbc_faction SET Name_Lang_koKR='비전 전멸자', Description_Lang_koKR='' WHERE ID=1004;
UPDATE dbc_faction SET Name_Lang_koKR='Friendly, Hidden', Description_Lang_koKR='' WHERE ID=1005;
UPDATE dbc_faction SET Name_Lang_koKR='Kirin''Var - Dathric', Description_Lang_koKR='' WHERE ID=1006;
UPDATE dbc_faction SET Name_Lang_koKR='Kirin''Var - Belmara', Description_Lang_koKR='' WHERE ID=1007;
UPDATE dbc_faction SET Name_Lang_koKR='Kirin''Var - Luminrath', Description_Lang_koKR='' WHERE ID=1008;
UPDATE dbc_faction SET Name_Lang_koKR='Kirin''Var - Cohlien', Description_Lang_koKR='' WHERE ID=1009;
UPDATE dbc_faction SET Name_Lang_koKR='일리단의 하수인', Description_Lang_koKR='' WHERE ID=1010;
UPDATE dbc_faction SET Name_Lang_koKR='고난의 거리', Description_Lang_koKR='고난의 거리에는 각지에서 모여든 다양한 종족의 피난민들이 거주하고 있습니다. 이들을 돕기 위한 도움의 손길이 주민들 사이에 빠르게 퍼지고 있습니다.' WHERE ID=1011;
UPDATE dbc_faction SET Name_Lang_koKR='잿빛혓바닥 결사단', Description_Lang_koKR='잿빛혓바닥 결사단은 뒤틀린 드레나이 부족 중 정예로 구성되어 있으며 일리단과 연합을 맺고 있습니다. 이 결사대는 아카마의 가장 충성스러운 부대원으로 구성되어 있으며 비밀스러운 음모를 수행하고 있습니다.' WHERE ID=1012;
UPDATE dbc_faction SET Name_Lang_koKR='어둠달의 영혼들 1', Description_Lang_koKR='' WHERE ID=1013;
UPDATE dbc_faction SET Name_Lang_koKR='어둠달의 영혼들 2', Description_Lang_koKR='' WHERE ID=1014;
UPDATE dbc_faction SET Name_Lang_koKR='황천의 용군단', Description_Lang_koKR='이 희귀한 용족은 황천의 에너지를 받은 데스윙의 검은용군단 알로부터 탄생하였습니다. 이제 이들은 부모로부터 물려 받은 파괴적인 천성의 그늘에 가려진 자신들의 정체성을 찾으려하고 있습니다.' WHERE ID=1015;
UPDATE dbc_faction SET Name_Lang_koKR='고룡교단', Description_Lang_koKR='' WHERE ID=1016;
UPDATE dbc_faction SET Name_Lang_koKR='나무정령', Description_Lang_koKR='' WHERE ID=1017;
UPDATE dbc_faction SET Name_Lang_koKR='레오테라스 악마 I', Description_Lang_koKR='' WHERE ID=1018;
UPDATE dbc_faction SET Name_Lang_koKR='레오테라스 악마 II', Description_Lang_koKR='' WHERE ID=1019;
UPDATE dbc_faction SET Name_Lang_koKR='레오테라스 악마 III', Description_Lang_koKR='' WHERE ID=1020;
UPDATE dbc_faction SET Name_Lang_koKR='레오테라스 악마 IV', Description_Lang_koKR='' WHERE ID=1021;
UPDATE dbc_faction SET Name_Lang_koKR='레오테라스 악마 V', Description_Lang_koKR='' WHERE ID=1022;
UPDATE dbc_faction SET Name_Lang_koKR='아잘로스', Description_Lang_koKR='' WHERE ID=1023;
UPDATE dbc_faction SET Name_Lang_koKR='바위갈퀴', Description_Lang_koKR='' WHERE ID=1024;
UPDATE dbc_faction SET Name_Lang_koKR='바위갈퀴 사냥꾼', Description_Lang_koKR='' WHERE ID=1025;
UPDATE dbc_faction SET Name_Lang_koKR='어둠달 악령', Description_Lang_koKR='' WHERE ID=1026;
UPDATE dbc_faction SET Name_Lang_koKR='군단 통신원', Description_Lang_koKR='' WHERE ID=1027;
UPDATE dbc_faction SET Name_Lang_koKR='까마귀나무 고대인', Description_Lang_koKR='' WHERE ID=1028;
UPDATE dbc_faction SET Name_Lang_koKR='체스', Description_Lang_koKR='' WHERE ID=1029;
UPDATE dbc_faction SET Name_Lang_koKR='검은 사원 관문 - 일리다리', Description_Lang_koKR='' WHERE ID=1030;
UPDATE dbc_faction SET Name_Lang_koKR='샤타리 하늘경비대', Description_Lang_koKR='아웃랜드에서 하늘로부터의 위협에 대처하기 위해 조직된 샤트라스 공중 부대입니다.' WHERE ID=1031;
UPDATE dbc_faction SET Name_Lang_koKR='52번 구역', Description_Lang_koKR='' WHERE ID=1032;
UPDATE dbc_faction SET Name_Lang_koKR='마이에브', Description_Lang_koKR='' WHERE ID=1033;
UPDATE dbc_faction SET Name_Lang_koKR='스케티스 어둠의 아라코아', Description_Lang_koKR='' WHERE ID=1034;
UPDATE dbc_faction SET Name_Lang_koKR='스케티스 아라코아', Description_Lang_koKR='' WHERE ID=1035;
UPDATE dbc_faction SET Name_Lang_koKR='적대적 용아귀부족', Description_Lang_koKR='' WHERE ID=1036;
UPDATE dbc_faction SET Name_Lang_koKR='얼라이언스 선봉대', Description_Lang_koKR='용맹의 원정대가 이끄는 노스렌드의 얼라이언스 연합군입니다. 탐험가 연맹 등 민간 조직도 함께 하고 있습니다.' WHERE ID=1037;
UPDATE dbc_faction SET Name_Lang_koKR='오그릴라', Description_Lang_koKR='오그릴라의 개화된 오우거들은 칼날 산맥 서쪽에 자리잡고 있습니다. 이들은 오그릴라 주변에 있는 에펙시스 수정으로 인해 오우거만의 잔인한 본성을 초월할 수 있었습니다.' WHERE ID=1038;
UPDATE dbc_faction SET Name_Lang_koKR='칼날발톱', Description_Lang_koKR='' WHERE ID=1039;
UPDATE dbc_faction SET Name_Lang_koKR='재사용', Description_Lang_koKR='' WHERE ID=1040;
UPDATE dbc_faction SET Name_Lang_koKR='프렌지', Description_Lang_koKR='' WHERE ID=1041;
UPDATE dbc_faction SET Name_Lang_koKR='하늘경비대의 적', Description_Lang_koKR='' WHERE ID=1042;
UPDATE dbc_faction SET Name_Lang_koKR='스컹크 (페튜니아)', Description_Lang_koKR='' WHERE ID=1043;
UPDATE dbc_faction SET Name_Lang_koKR='테라모어 탈영병', Description_Lang_koKR='' WHERE ID=1044;
UPDATE dbc_faction SET Name_Lang_koKR='브리쿨', Description_Lang_koKR='' WHERE ID=1045;
UPDATE dbc_faction SET Name_Lang_koKR='북쪽바다 해적', Description_Lang_koKR='' WHERE ID=1046;
UPDATE dbc_faction SET Name_Lang_koKR='투스카르', Description_Lang_koKR='' WHERE ID=1047;
UPDATE dbc_faction SET Name_Lang_koKR='미사용', Description_Lang_koKR='' WHERE ID=1048;
UPDATE dbc_faction SET Name_Lang_koKR='아마니 트롤', Description_Lang_koKR='' WHERE ID=1049;
UPDATE dbc_faction SET Name_Lang_koKR='용맹의 원정대', Description_Lang_koKR='국왕 바리안 린이 이끄는 노스렌드의 얼라이언스 주력 부대인 용맹의 원정대는 스컬지에 맞서 움직이고 있습니다.' WHERE ID=1050;
UPDATE dbc_faction SET Name_Lang_koKR='미사용', Description_Lang_koKR='' WHERE ID=1051;
UPDATE dbc_faction SET Name_Lang_koKR='호드 원정대', Description_Lang_koKR='노스렌드의 호드 연합군으로 전쟁노래 공격대가 이끌고 있습니다.' WHERE ID=1052;
UPDATE dbc_faction SET Name_Lang_koKR='서부경비대', Description_Lang_koKR='' WHERE ID=1053;
UPDATE dbc_faction SET Name_Lang_koKR='점박이 그리핀', Description_Lang_koKR='' WHERE ID=1054;
UPDATE dbc_faction SET Name_Lang_koKR='길들인 역병사냥개', Description_Lang_koKR='' WHERE ID=1055;
UPDATE dbc_faction SET Name_Lang_koKR='브리쿨', Description_Lang_koKR='' WHERE ID=1056;
UPDATE dbc_faction SET Name_Lang_koKR='브리쿨', Description_Lang_koKR='' WHERE ID=1057;
UPDATE dbc_faction SET Name_Lang_koKR='브리쿨', Description_Lang_koKR='' WHERE ID=1058;
UPDATE dbc_faction SET Name_Lang_koKR='깃발 회수 - 깃발 - 얼라이언스', Description_Lang_koKR='' WHERE ID=1059;
UPDATE dbc_faction SET Name_Lang_koKR='Test용', Description_Lang_koKR='' WHERE ID=1060;
UPDATE dbc_faction SET Name_Lang_koKR='브리쿨', Description_Lang_koKR='' WHERE ID=1061;
UPDATE dbc_faction SET Name_Lang_koKR='브리쿨 검투사', Description_Lang_koKR='' WHERE ID=1062;
UPDATE dbc_faction SET Name_Lang_koKR='발가드 전투원', Description_Lang_koKR='' WHERE ID=1063;
UPDATE dbc_faction SET Name_Lang_koKR='타운카', Description_Lang_koKR='타우렌의 친척이기도 한 이 튼튼한 부족은 북쪽으로 진군하는 호드 군대에 귀중한 수색대로 활약하고 있습니다.' WHERE ID=1064;
UPDATE dbc_faction SET Name_Lang_koKR='몬스터', Description_Lang_koKR='' WHERE ID=1065;
UPDATE dbc_faction SET Name_Lang_koKR='몬스터', Description_Lang_koKR='' WHERE ID=1066;
UPDATE dbc_faction SET Name_Lang_koKR='복수의 대리인', Description_Lang_koKR='아서스에 대한 언더시티의 복수심의 상징인 이들은 실바나스 윈드러너의 명령에 따라 최근까지 연구하고 있었던 죽음의 역병을 가져왔습니다.' WHERE ID=1067;
UPDATE dbc_faction SET Name_Lang_koKR='탐험가 연맹', Description_Lang_koKR='이들은 드워프 종족의 기원을 밝혀내고자 티탄의 유물을 수집하고 있습니다. 최근 노스렌드로 건너와 다양한 고고학 유적에 대한 조사를 시작했습니다.' WHERE ID=1068;
UPDATE dbc_faction SET Name_Lang_koKR='산양 경주', Description_Lang_koKR='' WHERE ID=1069;
UPDATE dbc_faction SET Name_Lang_koKR='산양 경주', Description_Lang_koKR='' WHERE ID=1070;
UPDATE dbc_faction SET Name_Lang_koKR='크레이그의 다람쥐', Description_Lang_koKR='시험용 평판' WHERE ID=1071;
UPDATE dbc_faction SET Name_Lang_koKR='재사용', Description_Lang_koKR='' WHERE ID=1072;
UPDATE dbc_faction SET Name_Lang_koKR='칼루아크', Description_Lang_koKR='투스카르는 낚시와 고래잡이로 생계를 꾸려 나가는 강인하지만 온순한 종족입니다. 최근 마을을 침략한 강력한 위협에 맞서고 있는 투스카르는 자신들을 도와줄 동맹을 찾고 있습니다.' WHERE ID=1073;
UPDATE dbc_faction SET Name_Lang_koKR='축제 - 물통', Description_Lang_koKR='' WHERE ID=1074;
UPDATE dbc_faction SET Name_Lang_koKR='축제 - 일반', Description_Lang_koKR='' WHERE ID=1075;
UPDATE dbc_faction SET Name_Lang_koKR='무쇠 드워프', Description_Lang_koKR='' WHERE ID=1076;
UPDATE dbc_faction SET Name_Lang_koKR='무너진 태양 공격대', Description_Lang_koKR='태양샘에서 벌이는 왕자 캘타스의 만행에 맞서는 샤트라스의 마지막 공격대입니다.' WHERE ID=1077;
UPDATE dbc_faction SET Name_Lang_koKR='전투용 소환수', Description_Lang_koKR='' WHERE ID=1078;
UPDATE dbc_faction SET Name_Lang_koKR='겨울지느러미 멀록', Description_Lang_koKR='' WHERE ID=1079;
UPDATE dbc_faction SET Name_Lang_koKR='Friendly, Force Reaction', Description_Lang_koKR='' WHERE ID=1080;
UPDATE dbc_faction SET Name_Lang_koKR='Object, Force Reaction', Description_Lang_koKR='' WHERE ID=1081;
UPDATE dbc_faction SET Name_Lang_koKR='재사용', Description_Lang_koKR='' WHERE ID=1082;
UPDATE dbc_faction SET Name_Lang_koKR='재사용', Description_Lang_koKR='' WHERE ID=1083;
UPDATE dbc_faction SET Name_Lang_koKR='브리쿨 바다', Description_Lang_koKR='' WHERE ID=1084;
UPDATE dbc_faction SET Name_Lang_koKR='전쟁노래 공격대', Description_Lang_koKR='가로쉬 헬스크림이 이끄는 호드의 노스렌드 원정대는 아서스와 스컬지의 군대에 맞서고 있습니다.' WHERE ID=1085;
UPDATE dbc_faction SET Name_Lang_koKR='밀렵꾼', Description_Lang_koKR='' WHERE ID=1086;
UPDATE dbc_faction SET Name_Lang_koKR='축제 몬스터', Description_Lang_koKR='' WHERE ID=1087;
UPDATE dbc_faction SET Name_Lang_koKR='붉은송곳니 펄볼그', Description_Lang_koKR='' WHERE ID=1088;
UPDATE dbc_faction SET Name_Lang_koKR='펄볼그, 서리발톱일족', Description_Lang_koKR='' WHERE ID=1089;
UPDATE dbc_faction SET Name_Lang_koKR='키린 토', Description_Lang_koKR='달라란의 마법사와 대마법사들은 점점 고조되는 푸른용군단과 스컬지의 위협에 맞서 자신들의 도시를 노스렌드의 중심부로 이동시켰습니다.' WHERE ID=1090;
UPDATE dbc_faction SET Name_Lang_koKR='고룡쉼터 사원 용군단', Description_Lang_koKR='푸른용군단이 마법의 힘을 사용하는 모든 필멸의 존재에 맞서 격변을 일으키자 다른 용군단들은 붉은용군단의 지도 아래 엇나간 동료 용군단과 싸움을 시작했습니다.' WHERE ID=1091;
UPDATE dbc_faction SET Name_Lang_koKR='아졸네룹', Description_Lang_koKR='' WHERE ID=1092;
UPDATE dbc_faction SET Name_Lang_koKR='재사용', Description_Lang_koKR='' WHERE ID=1093;
UPDATE dbc_faction SET Name_Lang_koKR='은빛 서약단', Description_Lang_koKR='블러드 엘프의 키린 토 합류를 거부한 하이 엘프의 군사 조직으로 베리사 윈드러너의 지도 아래 연합하여 노스렌드에서 얼라이언스 군대와 손을 잡았습니다.' WHERE ID=1094;
UPDATE dbc_faction SET Name_Lang_koKR='회색 구릉지 덫사냥꾼', Description_Lang_koKR='' WHERE ID=1095;
UPDATE dbc_faction SET Name_Lang_koKR='재사용', Description_Lang_koKR='' WHERE ID=1096;
UPDATE dbc_faction SET Name_Lang_koKR='리치 왕의 분노', Description_Lang_koKR='' WHERE ID=1097;
UPDATE dbc_faction SET Name_Lang_koKR='칠흑의 기사단', Description_Lang_koKR='리치 왕의 마수에서 해방된 죽음의 기사들은 대영주 다리온 모그레인의 깃발 아래 뭉쳐 리치 왕에 맞서고 있습니다.' WHERE ID=1098;
UPDATE dbc_faction SET Name_Lang_koKR='분노의 관문 스컬지', Description_Lang_koKR='' WHERE ID=1099;
UPDATE dbc_faction SET Name_Lang_koKR='분노의 관문 얼라이언스', Description_Lang_koKR='' WHERE ID=1100;
UPDATE dbc_faction SET Name_Lang_koKR='분노의 관문 호드', Description_Lang_koKR='' WHERE ID=1101;
UPDATE dbc_faction SET Name_Lang_koKR='깃발 회수 - 깃발 - 호드', Description_Lang_koKR='' WHERE ID=1102;
UPDATE dbc_faction SET Name_Lang_koKR='깃발 회수 - 깃발 - 중립', Description_Lang_koKR='' WHERE ID=1103;
UPDATE dbc_faction SET Name_Lang_koKR='광란의심장일족', Description_Lang_koKR='스컬지의 침공으로 고향에서 쫓겨난 이 사나운 울바르 부족은 숄라자르 분지에서 어렵게 새로운 터전을 일구고 있습니다. 이들은 공격적인 본성으로 인해 점쟁이 조합 등 다양한 골록 부족과 대립하고 있습니다.' WHERE ID=1104;
UPDATE dbc_faction SET Name_Lang_koKR='점쟁이 조합', Description_Lang_koKR='숄라자르 분지의 골록은 (비록 거의 이해하고 있지는 못하지만) 스스로를 티탄 기술의 수호자라 칭하는 파충류 생명체입니다. 최근 골록은 울바르와의 영토 전쟁에 깊이 휘말리고 있습니다.' WHERE ID=1105;
UPDATE dbc_faction SET Name_Lang_koKR='은빛십자군', Description_Lang_koKR='티리온 폴드링이 이끄는 은빛십자군은 리치 왕의 군대에 맞서는 은빛 성기사단과 은빛 여명회의 연합군입니다.' WHERE ID=1106;
UPDATE dbc_faction SET Name_Lang_koKR='드라카리 트롤', Description_Lang_koKR='' WHERE ID=1107;
UPDATE dbc_faction SET Name_Lang_koKR='시간의 동굴 아서스', Description_Lang_koKR='' WHERE ID=1108;
UPDATE dbc_faction SET Name_Lang_koKR='시간의 동굴 스트라솔름 시민', Description_Lang_koKR='' WHERE ID=1109;
UPDATE dbc_faction SET Name_Lang_koKR='시간의 동굴 스컬지', Description_Lang_koKR='' WHERE ID=1110;
UPDATE dbc_faction SET Name_Lang_koKR='프레이야', Description_Lang_koKR='' WHERE ID=1111;
UPDATE dbc_faction SET Name_Lang_koKR='탈것 - 비행 경로 - 얼라이언스', Description_Lang_koKR='' WHERE ID=1112;
UPDATE dbc_faction SET Name_Lang_koKR='탈것 - 비행 경로 - 호드', Description_Lang_koKR='' WHERE ID=1113;
UPDATE dbc_faction SET Name_Lang_koKR='탈것 - 비행 경로 - 중립', Description_Lang_koKR='' WHERE ID=1114;
UPDATE dbc_faction SET Name_Lang_koKR='정령 물', Description_Lang_koKR='' WHERE ID=1115;
UPDATE dbc_faction SET Name_Lang_koKR='정령 바람', Description_Lang_koKR='' WHERE ID=1116;
UPDATE dbc_faction SET Name_Lang_koKR='숄라자르 분지', Description_Lang_koKR='' WHERE ID=1117;
UPDATE dbc_faction SET Name_Lang_koKR='월드 오브 워크래프트', Description_Lang_koKR='' WHERE ID=1118;
UPDATE dbc_faction SET Name_Lang_koKR='호디르의 후예', Description_Lang_koKR='던 니펠렘은 폭풍우 봉우리의 호전적인 서리 거인들의 고향입니다.' WHERE ID=1119;
UPDATE dbc_faction SET Name_Lang_koKR='무쇠 거인', Description_Lang_koKR='' WHERE ID=1120;
UPDATE dbc_faction SET Name_Lang_koKR='서리 브리쿨', Description_Lang_koKR='' WHERE ID=1121;
UPDATE dbc_faction SET Name_Lang_koKR='토석인', Description_Lang_koKR='' WHERE ID=1122;
UPDATE dbc_faction SET Name_Lang_koKR='몬스터 중재', Description_Lang_koKR='' WHERE ID=1123;
UPDATE dbc_faction SET Name_Lang_koKR='선리버', Description_Lang_koKR='예전부터 달라란과 접촉이 금지되었던 호드는 대마법사 에이타스 선리버의 노력으로 달라란에 들어오게 되었다. 선리버의 추종자들은 그의 이름을 따서 지은 선리버 성소를 지키는 임무를 수행하고 있다.' WHERE ID=1124;
UPDATE dbc_faction SET Name_Lang_koKR='힐드스미트', Description_Lang_koKR='' WHERE ID=1125;
UPDATE dbc_faction SET Name_Lang_koKR='서릿결부족 드워프', Description_Lang_koKR='이 수수께끼에 싸인 서릿결부족 드워프는 폭풍우 봉우리에 살고 있습니다. 최근 그들은 탐험가 연맹의 몇몇 드워프와 우호적인 관계를 맺어, 마을을 찾는 얼라이언스를 반가이 맞이합니다.' WHERE ID=1126;
UPDATE dbc_faction SET Name_Lang_koKR='오그리마', Description_Lang_koKR='' WHERE ID=1127;
UPDATE dbc_faction SET Name_Lang_koKR='트랜퀼리엔 변환', Description_Lang_koKR='' WHERE ID=1136;
UPDATE dbc_faction SET Name_Lang_koKR='눈호랑이 변환', Description_Lang_koKR='' WHERE ID=1137;
UPDATE dbc_faction SET Name_Lang_koKR='다 싫어', Description_Lang_koKR='' WHERE ID=1145;
UPDATE dbc_faction SET Name_Lang_koKR='은빛 서약단 변환', Description_Lang_koKR='' WHERE ID=1154;
UPDATE dbc_faction SET Name_Lang_koKR='선리버 변환', Description_Lang_koKR='' WHERE ID=1155;
UPDATE dbc_faction SET Name_Lang_koKR='잿빛 선고단', Description_Lang_koKR='티리온 폴드링과 다리온 모그레인의 협정에 따라 은빛십자군과 칠흑의 기사단은 리치 왕이 쓰러질 때까지 서로의 입장 차이를 잠시 접어두고 공동으로 얼음왕관 성채 공격 작전을 펼치기로 했습니다.' WHERE ID=1156;
UPDATE dbc_faction SET Name_Lang_koKR='CTF - Flag - Alliance 2', Description_Lang_koKR='' WHERE ID=1159;
UPDATE dbc_faction SET Name_Lang_koKR='CTF - Flag - Horde 2', Description_Lang_koKR='' WHERE ID=1160;
