UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 머리', Description_Lang_koKR='' WHERE ID=3;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='망나니 머리', Description_Lang_koKR='' WHERE ID=4;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='땋은 머리', Description_Lang_koKR='' WHERE ID=5;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='넘겨 세운 뾰족머리', Description_Lang_koKR='' WHERE ID=6;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='뾰족뾰족 꽁지머리', Description_Lang_koKR='' WHERE ID=7;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='구슬 장식 땋은 머리', Description_Lang_koKR='' WHERE ID=8;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='뿔모양 머리', Description_Lang_koKR='' WHERE ID=9;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='둥근 고리 꽁지머리', Description_Lang_koKR='' WHERE ID=10;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='빡빡머리', Description_Lang_koKR='' WHERE ID=11;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='특징 없음', Description_Lang_koKR='' WHERE ID=19;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='나팔꽃 촉수', Description_Lang_koKR='' WHERE ID=20;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='기다란 구레나룻', Description_Lang_koKR='' WHERE ID=21;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='울퉁불퉁 구레나룻', Description_Lang_koKR='' WHERE ID=22;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='콧수염', Description_Lang_koKR='' WHERE ID=23;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='애교 턱수염', Description_Lang_koKR='' WHERE ID=24;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='염소 수염', Description_Lang_koKR='' WHERE ID=25;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='쌍촉수', Description_Lang_koKR='' WHERE ID=26;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='생머리', Description_Lang_koKR='' WHERE ID=27;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='처진 머리', Description_Lang_koKR='' WHERE ID=28;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='일자 앞머리', Description_Lang_koKR='' WHERE ID=29;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='자연스러운 긴 머리', Description_Lang_koKR='' WHERE ID=30;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='옆 가르마 긴 머리', Description_Lang_koKR='' WHERE ID=31;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='한쪽 넘긴 머리', Description_Lang_koKR='' WHERE ID=32;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='상고머리', Description_Lang_koKR='' WHERE ID=33;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='내려 묶은 긴 머리', Description_Lang_koKR='' WHERE ID=34;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='올려 묶은 긴 머리', Description_Lang_koKR='' WHERE ID=35;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='세련된 단발머리', Description_Lang_koKR='' WHERE ID=36;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 바람머리', Description_Lang_koKR='' WHERE ID=37;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='귀 넘긴 단발머리', Description_Lang_koKR='' WHERE ID=38;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='단발 바람머리', Description_Lang_koKR='' WHERE ID=39;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='물결 머리', Description_Lang_koKR='' WHERE ID=40;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='올림머리', Description_Lang_koKR='' WHERE ID=41;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='옆 가르마 단발머리', Description_Lang_koKR='' WHERE ID=42;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='부풀린 짧은 단발머리', Description_Lang_koKR='' WHERE ID=43;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='대충 묶은 머리', Description_Lang_koKR='' WHERE ID=44;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='귀걸이 없음', Description_Lang_koKR='' WHERE ID=55;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='고리 귀걸이', Description_Lang_koKR='' WHERE ID=56;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='위쪽 귀걸이', Description_Lang_koKR='' WHERE ID=57;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='위쪽 쌍귀걸이', Description_Lang_koKR='' WHERE ID=58;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='위아래 귀걸이', Description_Lang_koKR='' WHERE ID=59;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='코걸이', Description_Lang_koKR='' WHERE ID=60;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='코걸이와 눈썹 고리', Description_Lang_koKR='' WHERE ID=61;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='달라붙은 머리', Description_Lang_koKR='' WHERE ID=62;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='빡빡머리', Description_Lang_koKR='' WHERE ID=63;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='중앙가르마 단발머리', Description_Lang_koKR='' WHERE ID=64;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='군인 머리', Description_Lang_koKR='' WHERE ID=65;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='일출형 머리', Description_Lang_koKR='' WHERE ID=66;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='야만전사 머리', Description_Lang_koKR='' WHERE ID=67;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='화려한 머리', Description_Lang_koKR='' WHERE ID=68;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='처진 머리', Description_Lang_koKR='' WHERE ID=69;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='귀족 머리', Description_Lang_koKR='' WHERE ID=70;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='일출형 긴 머리', Description_Lang_koKR='' WHERE ID=71;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 꽁지머리', Description_Lang_koKR='' WHERE ID=72;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='연예인 머리', Description_Lang_koKR='' WHERE ID=73;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='치렁치렁 머리', Description_Lang_koKR='' WHERE ID=74;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='일반 수염', Description_Lang_koKR='' WHERE ID=85;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='대령 수염', Description_Lang_koKR='' WHERE ID=86;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='결투사 수염', Description_Lang_koKR='' WHERE ID=87;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='염소 수염', Description_Lang_koKR='' WHERE ID=88;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='마술사 수염', Description_Lang_koKR='' WHERE ID=89;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='울퉁불퉁 구레나룻', Description_Lang_koKR='' WHERE ID=90;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='콧수염과 염소수염', Description_Lang_koKR='' WHERE ID=91;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='콧수염', Description_Lang_koKR='' WHERE ID=92;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='수염 없음', Description_Lang_koKR='' WHERE ID=93;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='생머리', Description_Lang_koKR='' WHERE ID=125;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='한쪽 넘긴 머리', Description_Lang_koKR='' WHERE ID=126;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 갈래 머리', Description_Lang_koKR='' WHERE ID=127;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='양쪽 붙인 앞머리', Description_Lang_koKR='' WHERE ID=128;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='양갈래 올림머리', Description_Lang_koKR='' WHERE ID=129;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='보석박힌 머리띠 착용', Description_Lang_koKR='' WHERE ID=130;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='이마 덮는 앞머리', Description_Lang_koKR='' WHERE ID=131;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='우아하게 세운 머리', Description_Lang_koKR='' WHERE ID=132;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='부풀린 머리', Description_Lang_koKR='' WHERE ID=133;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧게 쳐올린 머리', Description_Lang_koKR='' WHERE ID=134;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='바람머리', Description_Lang_koKR='' WHERE ID=135;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='쓸어넘긴 뿔', Description_Lang_koKR='' WHERE ID=143;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='뒤로 말린 뿔', Description_Lang_koKR='' WHERE ID=144;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='활처럼 휜 뿔', Description_Lang_koKR='' WHERE ID=145;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='높이 솟은 뿔', Description_Lang_koKR='' WHERE ID=146;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='옆으로 벌린 뿔', Description_Lang_koKR='' WHERE ID=147;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='웅장한 뿔', Description_Lang_koKR='' WHERE ID=148;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧은 뿔', Description_Lang_koKR='' WHERE ID=149;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='하나로 올려 묶은 머리', Description_Lang_koKR='' WHERE ID=175;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='옆 가르마 긴 머리', Description_Lang_koKR='' WHERE ID=176;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='달라붙은 머리', Description_Lang_koKR='' WHERE ID=177;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='숱 많은 긴 생머리', Description_Lang_koKR='' WHERE ID=178;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='보석박힌 머리띠 착용', Description_Lang_koKR='' WHERE ID=179;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='얌전한 긴 머리', Description_Lang_koKR='' WHERE ID=180;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='내려 묶은 긴 머리', Description_Lang_koKR='' WHERE ID=181;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='하나로 올림머리', Description_Lang_koKR='' WHERE ID=182;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='옆 가르마 단발머리', Description_Lang_koKR='' WHERE ID=183;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='얌전한 단발머리', Description_Lang_koKR='' WHERE ID=184;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='앞머리 긴 단발머리', Description_Lang_koKR='' WHERE ID=185;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='층 낸 긴 생머리', Description_Lang_koKR='' WHERE ID=186;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='구불구불 긴머리', Description_Lang_koKR='' WHERE ID=187;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='머리띠 착용', Description_Lang_koKR='' WHERE ID=188;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='루비', Description_Lang_koKR='' WHERE ID=200;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='큰 고리', Description_Lang_koKR='' WHERE ID=201;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='작은 고리', Description_Lang_koKR='' WHERE ID=202;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='달랑거리는 에메랄드', Description_Lang_koKR='' WHERE ID=203;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='둥근 에메랄드와 진주', Description_Lang_koKR='' WHERE ID=204;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='위쪽 작은 고리', Description_Lang_koKR='' WHERE ID=205;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='진주', Description_Lang_koKR='' WHERE ID=206;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='달랑거리는 루비', Description_Lang_koKR='' WHERE ID=207;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='에메랄드와 네모 진주', Description_Lang_koKR='' WHERE ID=208;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='루비 귀걸이와 다이아몬드 고리', Description_Lang_koKR='' WHERE ID=209;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='한쪽 넘겨 묶은 머리', Description_Lang_koKR='' WHERE ID=245;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='넘겨 세운 뾰족머리', Description_Lang_koKR='' WHERE ID=246;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='매날개 앞머리', Description_Lang_koKR='' WHERE ID=247;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='망나니 머리', Description_Lang_koKR='' WHERE ID=248;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='부분 장발머리', Description_Lang_koKR='' WHERE ID=249;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='불꽃 머리', Description_Lang_koKR='' WHERE ID=250;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 앞머리', Description_Lang_koKR='' WHERE ID=251;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='부분 장발머리', Description_Lang_koKR='' WHERE ID=252;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='윤기좔좔 긴 머리', Description_Lang_koKR='' WHERE ID=253;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='머리띠 착용', Description_Lang_koKR='' WHERE ID=254;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='정수리 매듭 머리', Description_Lang_koKR='' WHERE ID=255;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='수염 없음', Description_Lang_koKR='' WHERE ID=266;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='점 찍은 듯 턱수염', Description_Lang_koKR='' WHERE ID=267;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='입술 밑 턱수염', Description_Lang_koKR='' WHERE ID=268;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='가시 턱수염', Description_Lang_koKR='' WHERE ID=269;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='애교 턱수염', Description_Lang_koKR='' WHERE ID=270;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='들쑥날쑥 턱수염', Description_Lang_koKR='' WHERE ID=271;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='한줄기 턱수염', Description_Lang_koKR='' WHERE ID=272;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='칼날 턱수염', Description_Lang_koKR='' WHERE ID=273;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='염소 턱수염', Description_Lang_koKR='' WHERE ID=274;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='멋 부린 턱수염', Description_Lang_koKR='' WHERE ID=275;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='풍성한 긴 머리', Description_Lang_koKR='' WHERE ID=307;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='상투 튼 양갈래 땋은 머리', Description_Lang_koKR='' WHERE ID=308;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 머리', Description_Lang_koKR='' WHERE ID=309;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 꽁지머리', Description_Lang_koKR='' WHERE ID=310;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='상투 튼 긴 머리', Description_Lang_koKR='' WHERE ID=311;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧은 꽁지머리', Description_Lang_koKR='' WHERE ID=312;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='넘긴 바람머리', Description_Lang_koKR='' WHERE ID=313;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='수염 없음', Description_Lang_koKR='' WHERE ID=322;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='단정한 전체 수염', Description_Lang_koKR='' WHERE ID=323;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='잘 기른 구레나룻', Description_Lang_koKR='' WHERE ID=324;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='콧수염', Description_Lang_koKR='' WHERE ID=325;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='울퉁불퉁 구레나룻', Description_Lang_koKR='' WHERE ID=326;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='염소 수염', Description_Lang_koKR='' WHERE ID=327;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='빡빡머리', Description_Lang_koKR='' WHERE ID=349;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 머리', Description_Lang_koKR='' WHERE ID=350;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 꽁지머리', Description_Lang_koKR='' WHERE ID=351;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧은 머리', Description_Lang_koKR='' WHERE ID=352;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='정수리 매듭 머리', Description_Lang_koKR='' WHERE ID=353;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧은 꽁지머리', Description_Lang_koKR='' WHERE ID=354;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='기름 발라 넘긴 머리', Description_Lang_koKR='' WHERE ID=355;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='벗겨지는 머리', Description_Lang_koKR='' WHERE ID=356;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='상투머리', Description_Lang_koKR='' WHERE ID=357;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='하나로 땋은 머리', Description_Lang_koKR='' WHERE ID=358;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧게 땋은 사과머리', Description_Lang_koKR='' WHERE ID=359;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='무성한 수염', Description_Lang_koKR='' WHERE ID=370;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='양갈래 땋은 수염', Description_Lang_koKR='' WHERE ID=371;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='단정한 수염', Description_Lang_koKR='' WHERE ID=372;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧은 수염', Description_Lang_koKR='' WHERE ID=373;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='엄청난 콧수염', Description_Lang_koKR='' WHERE ID=374;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='땋은 콧수염', Description_Lang_koKR='' WHERE ID=375;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='멋 부린 수염', Description_Lang_koKR='' WHERE ID=376;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='뾰족 수염', Description_Lang_koKR='' WHERE ID=377;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='땋아내린 수염', Description_Lang_koKR='' WHERE ID=378;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='허풍선이 수염', Description_Lang_koKR='' WHERE ID=379;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='무시무시한 턱수염', Description_Lang_koKR='' WHERE ID=380;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='정수리 매듭 머리', Description_Lang_koKR='' WHERE ID=413;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='길게 땋아 내린 머리', Description_Lang_koKR='' WHERE ID=414;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='닭벼슬 머리', Description_Lang_koKR='' WHERE ID=415;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='다섯 꽁지 머리', Description_Lang_koKR='' WHERE ID=416;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧은 갈래 머리', Description_Lang_koKR='' WHERE ID=417;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='양뿔머리', Description_Lang_koKR='' WHERE ID=418;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='풍성한 긴 머리', Description_Lang_koKR='' WHERE ID=419;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='빡빡머리', Description_Lang_koKR='' WHERE ID=420;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='귀걸이 없음', Description_Lang_koKR='' WHERE ID=429;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='귀걸이', Description_Lang_koKR='' WHERE ID=430;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='위쪽 귀걸이', Description_Lang_koKR='' WHERE ID=431;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='코걸이', Description_Lang_koKR='' WHERE ID=432;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='코걸이와 귀걸이', Description_Lang_koKR='' WHERE ID=433;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='코걸이와 쌍귀걸이', Description_Lang_koKR='' WHERE ID=434;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='위아래 귀걸이', Description_Lang_koKR='' WHERE ID=435;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='양갈래 땋은 머리', Description_Lang_koKR='' WHERE ID=459;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='땋은 양갈래 올림머리', Description_Lang_koKR='' WHERE ID=460;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='땋아 내린 머리', Description_Lang_koKR='' WHERE ID=461;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧은 갈래 머리', Description_Lang_koKR='' WHERE ID=462;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='땋은 올림머리', Description_Lang_koKR='' WHERE ID=463;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='양갈래 고리 머리', Description_Lang_koKR='' WHERE ID=464;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='내려 묶은 긴 머리', Description_Lang_koKR='' WHERE ID=465;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='들쑥날쑥 머리', Description_Lang_koKR='' WHERE ID=466;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='중간 가르마 단발 머리', Description_Lang_koKR='' WHERE ID=467;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='세 가닥 땋은 단발머리', Description_Lang_koKR='' WHERE ID=468;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='세련된 단발머리', Description_Lang_koKR='' WHERE ID=469;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧게 친 단발머리', Description_Lang_koKR='' WHERE ID=470;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='두가닥 땋은 일자 앞머리', Description_Lang_koKR='' WHERE ID=471;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='모아 묶은 머리', Description_Lang_koKR='' WHERE ID=472;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='귀걸이 없음', Description_Lang_koKR='' WHERE ID=483;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='고리 귀걸이', Description_Lang_koKR='' WHERE ID=484;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='위쪽 귀걸이', Description_Lang_koKR='' WHERE ID=485;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='위쪽 쌍귀걸이', Description_Lang_koKR='' WHERE ID=486;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='코걸이', Description_Lang_koKR='' WHERE ID=487;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='작은 귀걸이', Description_Lang_koKR='' WHERE ID=488;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='공든탑 머리', Description_Lang_koKR='' WHERE ID=519;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='세 갈래 머리', Description_Lang_koKR='' WHERE ID=520;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧은 갈래 머리', Description_Lang_koKR='' WHERE ID=521;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='앞머리 세운 짧은 머리', Description_Lang_koKR='' WHERE ID=522;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='달라붙은 머리', Description_Lang_koKR='' WHERE ID=523;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='땋은 양갈래 올림머리', Description_Lang_koKR='' WHERE ID=524;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='세련된 단발머리', Description_Lang_koKR='' WHERE ID=525;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='귀걸이 없음', Description_Lang_koKR='' WHERE ID=535;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='고리 귀걸이', Description_Lang_koKR='' WHERE ID=536;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='작은 귀걸이', Description_Lang_koKR='' WHERE ID=537;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='위쪽 귀걸이', Description_Lang_koKR='' WHERE ID=538;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='두 쌍 귀걸이', Description_Lang_koKR='' WHERE ID=539;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='왼쪽 귀걸이', Description_Lang_koKR='' WHERE ID=540;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='오른쪽 귀걸이', Description_Lang_koKR='' WHERE ID=541;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='빡빡머리', Description_Lang_koKR='' WHERE ID=565;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='양날개 머리', Description_Lang_koKR='' WHERE ID=566;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='단정한 머리', Description_Lang_koKR='' WHERE ID=567;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='힘 준 앞머리', Description_Lang_koKR='' WHERE ID=568;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='멋 부린 앞머리', Description_Lang_koKR='' WHERE ID=569;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='벗겨지는 머리', Description_Lang_koKR='' WHERE ID=570;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='겨우 가린 대머리', Description_Lang_koKR='' WHERE ID=571;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='수염 없음', Description_Lang_koKR='' WHERE ID=581;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='염소 수염', Description_Lang_koKR='' WHERE ID=582;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='이어진 수염', Description_Lang_koKR='' WHERE ID=583;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='빳빳한 콧수염', Description_Lang_koKR='' WHERE ID=584;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='무성한 수염', Description_Lang_koKR='' WHERE ID=585;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='손잡이 수염', Description_Lang_koKR='' WHERE ID=586;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='멋 부린 수염', Description_Lang_koKR='' WHERE ID=587;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='콧수염', Description_Lang_koKR='' WHERE ID=588;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='빡빡머리', Description_Lang_koKR='' WHERE ID=613;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='모호크 머리', Description_Lang_koKR='' WHERE ID=614;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='들쑥날쑥 단발머리', Description_Lang_koKR='' WHERE ID=615;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='잡초 머리', Description_Lang_koKR='' WHERE ID=616;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='불꽃 머리', Description_Lang_koKR='' WHERE ID=617;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='삐친 일출 머리', Description_Lang_koKR='' WHERE ID=618;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='일출형 긴 머리', Description_Lang_koKR='' WHERE ID=619;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='보통 단발머리', Description_Lang_koKR='' WHERE ID=620;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='정수리 매듭 머리', Description_Lang_koKR='' WHERE ID=621;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='장발머리', Description_Lang_koKR='' WHERE ID=622;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='잡티 없음', Description_Lang_koKR='' WHERE ID=633;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='썩은 입', Description_Lang_koKR='' WHERE ID=634;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='얼굴 띠', Description_Lang_koKR='' WHERE ID=635;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='턱 빠진 얼굴 띠', Description_Lang_koKR='' WHERE ID=636;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='턱 없는 얼굴 띠', Description_Lang_koKR='' WHERE ID=637;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='검버섯', Description_Lang_koKR='' WHERE ID=638;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='턱 빠진 검버섯', Description_Lang_koKR='' WHERE ID=639;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='턱 없는 검버섯', Description_Lang_koKR='' WHERE ID=640;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='드러난 턱뼈', Description_Lang_koKR='' WHERE ID=641;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='빠진 턱', Description_Lang_koKR='' WHERE ID=642;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='드러난 이빨', Description_Lang_koKR='' WHERE ID=643;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='빠진 턱', Description_Lang_koKR='' WHERE ID=644;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='썩은 양 볼', Description_Lang_koKR='' WHERE ID=645;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='빠진 턱과 썩은 양 볼', Description_Lang_koKR='' WHERE ID=646;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='기미 낀 눈가', Description_Lang_koKR='' WHERE ID=647;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='턱 빠지고 기미 낀 눈가', Description_Lang_koKR='' WHERE ID=648;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='턱 없고 기미 낀 눈가', Description_Lang_koKR='' WHERE ID=649;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='층 진 바람머리', Description_Lang_koKR='' WHERE ID=687;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='들쑥날쑥 단발머리', Description_Lang_koKR='' WHERE ID=688;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='푸석푸석한 머리', Description_Lang_koKR='' WHERE ID=689;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='넘긴 바람머리', Description_Lang_koKR='' WHERE ID=690;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 머리', Description_Lang_koKR='' WHERE ID=691;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='솟아오른 탑 머리', Description_Lang_koKR='' WHERE ID=692;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='상고머리', Description_Lang_koKR='' WHERE ID=693;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='멋 부린 짧은 머리', Description_Lang_koKR='' WHERE ID=694;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='세련된 단발머리', Description_Lang_koKR='' WHERE ID=695;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='달라붙은 머리', Description_Lang_koKR='' WHERE ID=696;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='잡티 없음', Description_Lang_koKR='' WHERE ID=707;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='꿰맨 입', Description_Lang_koKR='' WHERE ID=708;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='얼굴 띠', Description_Lang_koKR='' WHERE ID=709;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='검버섯', Description_Lang_koKR='' WHERE ID=710;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='드러난 턱뼈', Description_Lang_koKR='' WHERE ID=711;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='드러난 이빨', Description_Lang_koKR='' WHERE ID=712;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='썩은 양 볼', Description_Lang_koKR='' WHERE ID=713;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='기미 낀 눈가', Description_Lang_koKR='' WHERE ID=714;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 뿔', Description_Lang_koKR='' WHERE ID=743;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='황소 뿔', Description_Lang_koKR='' WHERE ID=744;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='투우소 뿔', Description_Lang_koKR='' WHERE ID=745;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='양쪽 부러진 뿔', Description_Lang_koKR='' WHERE ID=746;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='한쪽 부러진 뿔', Description_Lang_koKR='' WHERE ID=747;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='깜찍 뿔', Description_Lang_koKR='' WHERE ID=748;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='무소 뿔', Description_Lang_koKR='' WHERE ID=749;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='무시무시한 뿔', Description_Lang_koKR='' WHERE ID=750;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='수염 없음', Description_Lang_koKR='' WHERE ID=754;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='세갈래 땋은 수염', Description_Lang_koKR='' WHERE ID=755;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='코뚜레', Description_Lang_koKR='' WHERE ID=756;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='하나로 땋은 수염', Description_Lang_koKR='' WHERE ID=757;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='턱수염', Description_Lang_koKR='' WHERE ID=758;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='양갈래 땋은 수염', Description_Lang_koKR='' WHERE ID=759;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='코뚜레와 턱수염', Description_Lang_koKR='' WHERE ID=760;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='빡빡머리', Description_Lang_koKR='' WHERE ID=779;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='정수리 매듭 머리', Description_Lang_koKR='' WHERE ID=780;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='상투머리', Description_Lang_koKR='' WHERE ID=781;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='닭벼슬 머리', Description_Lang_koKR='' WHERE ID=782;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='상투 튼 긴 머리', Description_Lang_koKR='' WHERE ID=783;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='양갈래 땋은 머리', Description_Lang_koKR='' WHERE ID=784;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 꽁지머리', Description_Lang_koKR='' WHERE ID=785;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='수염 없음', Description_Lang_koKR='' WHERE ID=794;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='거칠거칠한 수염', Description_Lang_koKR='' WHERE ID=795;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='단정한 긴 턱수염', Description_Lang_koKR='' WHERE ID=796;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='울퉁불퉁 턱수염', Description_Lang_koKR='' WHERE ID=797;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='마구 자란 턱수염', Description_Lang_koKR='' WHERE ID=798;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='하나로 땋은 수염', Description_Lang_koKR='' WHERE ID=799;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='양갈래 땋은 수염', Description_Lang_koKR='' WHERE ID=800;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='땋아내린 구레나룻', Description_Lang_koKR='' WHERE ID=801;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='얇게 땋은 턱수염', Description_Lang_koKR='' WHERE ID=802;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='울퉁불퉁 구레나룻', Description_Lang_koKR='' WHERE ID=803;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='무성한 구레나룻', Description_Lang_koKR='' WHERE ID=804;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='초승달 뿔', Description_Lang_koKR='' WHERE ID=831;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='처진 뿔', Description_Lang_koKR='' WHERE ID=832;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 뿔', Description_Lang_koKR='' WHERE ID=833;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='위로 솟은 뿔', Description_Lang_koKR='' WHERE ID=834;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='작은 뿔', Description_Lang_koKR='' WHERE ID=835;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='벌어진 뿔', Description_Lang_koKR='' WHERE ID=836;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='무소 뿔', Description_Lang_koKR='' WHERE ID=837;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='대충 빗은 긴 머리', Description_Lang_koKR='' WHERE ID=841;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='두 가닥 땋아내린 머리', Description_Lang_koKR='' WHERE ID=842;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='양갈래 고리 머리', Description_Lang_koKR='' WHERE ID=843;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='두가닥 내린 머리', Description_Lang_koKR='' WHERE ID=844;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='네 가닥 꽁지머리', Description_Lang_koKR='' WHERE ID=845;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 생머리', Description_Lang_koKR='' WHERE ID=861;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='하나로 올려 묶은 긴 머리', Description_Lang_koKR='' WHERE ID=862;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='들쑥날쑥 머리', Description_Lang_koKR='' WHERE ID=863;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='하나로 올려 묶은 짧은 머리', Description_Lang_koKR='' WHERE ID=864;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='양갈래 땋은 머리', Description_Lang_koKR='' WHERE ID=865;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧은 꽁지머리', Description_Lang_koKR='' WHERE ID=866;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='댕기머리', Description_Lang_koKR='' WHERE ID=867;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='곰', Description_Lang_koKR='' WHERE ID=876;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='칼날', Description_Lang_koKR='' WHERE ID=877;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='학', Description_Lang_koKR='' WHERE ID=878;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='푸른 나뭇잎', Description_Lang_koKR='' WHERE ID=879;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='야생의 발톱', Description_Lang_koKR='' WHERE ID=880;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='펼친 날개', Description_Lang_koKR='' WHERE ID=881;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='독사', Description_Lang_koKR='' WHERE ID=882;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='올빼미', Description_Lang_koKR='' WHERE ID=883;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='그림자', Description_Lang_koKR='' WHERE ID=884;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='문신 없음', Description_Lang_koKR='' WHERE ID=885;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='빡빡머리', Description_Lang_koKR='' WHERE ID=911;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='벗겨지는 머리', Description_Lang_koKR='' WHERE ID=912;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='닭벼슬 머리', Description_Lang_koKR='' WHERE ID=913;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='넘긴 바람머리', Description_Lang_koKR='' WHERE ID=914;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='정수리 매듭 머리', Description_Lang_koKR='' WHERE ID=915;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 꽁지머리', Description_Lang_koKR='' WHERE ID=916;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='코끼리 엄니', Description_Lang_koKR='' WHERE ID=927;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='투우소 엄니', Description_Lang_koKR='' WHERE ID=928;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='매머드 엄니', Description_Lang_koKR='' WHERE ID=929;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='위로 솟은 엄니', Description_Lang_koKR='' WHERE ID=930;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='가로형 엄니', Description_Lang_koKR='' WHERE ID=931;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='얼굴 그림과 코끼리 엄니', Description_Lang_koKR='' WHERE ID=932;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='전투 문신과 코끼리 엄니', Description_Lang_koKR='' WHERE ID=933;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='줄무늬와 매머드 엄니', Description_Lang_koKR='' WHERE ID=934;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='턱 그림과 위로 솟은 엄니', Description_Lang_koKR='' WHERE ID=935;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='코 그림과 가로형 엄니', Description_Lang_koKR='' WHERE ID=936;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='얼굴 점과 매머드 엄니', Description_Lang_koKR='' WHERE ID=937;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='여러 갈래 땋은 머리', Description_Lang_koKR='' WHERE ID=965;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='올려 묶은 꽁지 머리', Description_Lang_koKR='' WHERE ID=966;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='부분 굵게 땋은 머리', Description_Lang_koKR='' WHERE ID=967;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='정수리 매듭 머리', Description_Lang_koKR='' WHERE ID=968;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='땋은 닭벼슬 머리', Description_Lang_koKR='' WHERE ID=969;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='잘근잘근 송곳니', Description_Lang_koKR='' WHERE ID=980;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='작은 송곳니', Description_Lang_koKR='' WHERE ID=981;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='곧게 뻗은 송곳니', Description_Lang_koKR='' WHERE ID=982;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='위로 솟은 송곳니', Description_Lang_koKR='' WHERE ID=983;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 송곳니', Description_Lang_koKR='' WHERE ID=984;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='도깨비 송곳니', Description_Lang_koKR='' WHERE ID=985;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='왕자 머리', Description_Lang_koKR='' WHERE ID=1012;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='불꽃 머리', Description_Lang_koKR='' WHERE ID=1013;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='넘겨 세운 뾰족머리', Description_Lang_koKR='' WHERE ID=1014;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='망나니 머리', Description_Lang_koKR='' WHERE ID=1015;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='윤기좔좔 긴 머리', Description_Lang_koKR='' WHERE ID=1016;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='멋 부린 긴 머리', Description_Lang_koKR='' WHERE ID=1017;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='공들여 말아 넘긴 머리', Description_Lang_koKR='' WHERE ID=1018;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧게 쳐올린 머리', Description_Lang_koKR='' WHERE ID=1019;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧은 갈래 머리', Description_Lang_koKR='' WHERE ID=1020;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='일자 앞머리', Description_Lang_koKR='' WHERE ID=1021;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='귀걸이 없음', Description_Lang_koKR='' WHERE ID=1022;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='풍성한 긴 머리', Description_Lang_koKR='' WHERE ID=1029;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='상투 틀고 양갈래 땋은 머리', Description_Lang_koKR='' WHERE ID=1030;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 꽁지머리', Description_Lang_koKR='' WHERE ID=1031;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='넘긴 바람머리', Description_Lang_koKR='' WHERE ID=1032;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='상투 튼 긴 머리', Description_Lang_koKR='' WHERE ID=1033;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='불꽃 머리', Description_Lang_koKR='' WHERE ID=1034;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='가시 뒤통수 머리', Description_Lang_koKR='' WHERE ID=1035;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='뿔 달린 망나니 머리', Description_Lang_koKR='' WHERE ID=1036;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='정수리 매듭 머리', Description_Lang_koKR='' WHERE ID=1037;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='개성 만점 머리', Description_Lang_koKR='' WHERE ID=1038;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='머리띠 착용', Description_Lang_koKR='' WHERE ID=1039;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='숱 많은 긴 생머리', Description_Lang_koKR='' WHERE ID=1040;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='앞머리 긴 단발머리', Description_Lang_koKR='' WHERE ID=1041;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='하나로 올려 묶은 머리', Description_Lang_koKR='' WHERE ID=1042;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='달라붙은 머리', Description_Lang_koKR='' WHERE ID=1043;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='야만전사 머리', Description_Lang_koKR='' WHERE ID=1044;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='군인 머리', Description_Lang_koKR='' WHERE ID=1045;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='일출형 긴 머리', Description_Lang_koKR='' WHERE ID=1046;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='월계관 머리', Description_Lang_koKR='' WHERE ID=1047;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='연예인 머리', Description_Lang_koKR='' WHERE ID=1048;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='올림머리', Description_Lang_koKR='' WHERE ID=1049;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='단발 바람머리', Description_Lang_koKR='' WHERE ID=1050;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='부풀린 짧은 단발머리', Description_Lang_koKR='' WHERE ID=1051;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='앞으로 땋은 양갈래 머리', Description_Lang_koKR='' WHERE ID=1052;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='댕기머리', Description_Lang_koKR='' WHERE ID=1053;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='넘긴 바람머리', Description_Lang_koKR='' WHERE ID=1054;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='들쑥날쑥 단발머리', Description_Lang_koKR='' WHERE ID=1055;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='모호크 머리', Description_Lang_koKR='' WHERE ID=1056;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='처진 머리', Description_Lang_koKR='' WHERE ID=1057;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='삐친 일출 머리', Description_Lang_koKR='' WHERE ID=1058;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='들쑥날쑥 머리', Description_Lang_koKR='' WHERE ID=1059;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='귀여운 양갈래머리', Description_Lang_koKR='' WHERE ID=1060;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 꽁지머리', Description_Lang_koKR='' WHERE ID=1061;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='양갈래 고리 머리', Description_Lang_koKR='' WHERE ID=1062;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='내려 묶은 긴 머리', Description_Lang_koKR='' WHERE ID=1063;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='윤기좔좔 긴 머리', Description_Lang_koKR='' WHERE ID=1064;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='굵게 만 긴 머리', Description_Lang_koKR='' WHERE ID=1065;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='구불구불 긴머리', Description_Lang_koKR='' WHERE ID=1066;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='층 낸 긴 생머리', Description_Lang_koKR='' WHERE ID=1067;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='얌전한 단발머리', Description_Lang_koKR='' WHERE ID=1068;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧게 땋은 사과머리', Description_Lang_koKR='' WHERE ID=1069;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='층 진 바람머리', Description_Lang_koKR='' WHERE ID=1070;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='길게 땋은 머리', Description_Lang_koKR='' WHERE ID=1071;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='모호크 머리', Description_Lang_koKR='' WHERE ID=1072;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='아주 길게 땋은 머리', Description_Lang_koKR='' WHERE ID=1073;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='머리띠 착용', Description_Lang_koKR='' WHERE ID=1074;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='달라붙은 머리', Description_Lang_koKR='' WHERE ID=1075;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='상고머리', Description_Lang_koKR='' WHERE ID=1076;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='모아 묶은 머리', Description_Lang_koKR='' WHERE ID=1077;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='양갈래 고리 머리', Description_Lang_koKR='' WHERE ID=1078;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='불꽃 머리', Description_Lang_koKR='' WHERE ID=1079;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='모호크 머리', Description_Lang_koKR='' WHERE ID=1080;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='윤기좔좔 정수리 매듭머리', Description_Lang_koKR='' WHERE ID=1081;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='긴 머리', Description_Lang_koKR='' WHERE ID=1082;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='삐친 일출 머리', Description_Lang_koKR='' WHERE ID=1083;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='층 진 바람머리', Description_Lang_koKR='' WHERE ID=1084;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='멋 부린 짧은 머리', Description_Lang_koKR='' WHERE ID=1085;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='상고머리', Description_Lang_koKR='' WHERE ID=1086;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='한쪽 넘긴 머리', Description_Lang_koKR='' WHERE ID=1087;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='끝 장식 뿔', Description_Lang_koKR='' WHERE ID=1088;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='위로 말린 뿔', Description_Lang_koKR='' WHERE ID=1089;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='뚜껑 달린 뿔', Description_Lang_koKR='' WHERE ID=1090;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='손잡이 뿔', Description_Lang_koKR='' WHERE ID=1091;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='고리낀 뿔', Description_Lang_koKR='' WHERE ID=1092;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='투우소 뿔', Description_Lang_koKR='' WHERE ID=1093;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='부러진 뿔', Description_Lang_koKR='' WHERE ID=1094;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='송곳 뿔', Description_Lang_koKR='' WHERE ID=1095;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='마주보는 뿔', Description_Lang_koKR='' WHERE ID=1096;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='동강 뿔', Description_Lang_koKR='' WHERE ID=1097;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='갈래갈래 땋은 머리', Description_Lang_koKR='' WHERE ID=1098;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='꽁지깃 머리', Description_Lang_koKR='' WHERE ID=1099;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='더벅머리', Description_Lang_koKR='' WHERE ID=1100;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='모호크 머리', Description_Lang_koKR='' WHERE ID=1101;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='풍성한 꽃머리', Description_Lang_koKR='' WHERE ID=1102;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='윗머리 꼬아 묶은 머리', Description_Lang_koKR='' WHERE ID=1103;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='모호크 머리', Description_Lang_koKR='' WHERE ID=1104;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='층진 짧은 머리', Description_Lang_koKR='' WHERE ID=1105;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='가짜 모호크 머리', Description_Lang_koKR='' WHERE ID=1106;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='기름 발라 넘긴 머리', Description_Lang_koKR='' WHERE ID=1107;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='일출 머리', Description_Lang_koKR='' WHERE ID=1108;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='세운 머리', Description_Lang_koKR='' WHERE ID=1109;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='야만전사 머리', Description_Lang_koKR='' WHERE ID=1110;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧은 머리', Description_Lang_koKR='' WHERE ID=1111;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='짧은 갈래 머리', Description_Lang_koKR='' WHERE ID=1112;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='앞머리 세운 짧은 머리', Description_Lang_koKR='' WHERE ID=1113;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='들쑥날쑥 머리', Description_Lang_koKR='' WHERE ID=1114;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='부스스한 머리', Description_Lang_koKR='' WHERE ID=1115;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='세 갈래 머리', Description_Lang_koKR='' WHERE ID=1116;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='층진 긴머리', Description_Lang_koKR='' WHERE ID=1117;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1120;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1121;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1122;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1123;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1124;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1125;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1126;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1127;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1128;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1129;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1130;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1131;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1132;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1133;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1134;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1135;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1136;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1137;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1138;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1139;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1140;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1141;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1142;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1143;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1144;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1145;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1146;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1147;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1148;
UPDATE dbc_barbershopstyle SET DisplayName_Lang_koKR='', Description_Lang_koKR='' WHERE ID=1149;
