UPDATE dbc_areapoi SET Name_Lang_koKR='맹금의 봉우리', Description_Lang_koKR='' WHERE ID=792;
UPDATE dbc_areapoi SET Name_Lang_koKR='알가즈 주둔지', Description_Lang_koKR='' WHERE ID=1032;
UPDATE dbc_areapoi SET Name_Lang_koKR='고통의 요새', Description_Lang_koKR='' WHERE ID=27;
UPDATE dbc_areapoi SET Name_Lang_koKR='앤빌마', Description_Lang_koKR='' WHERE ID=1;
UPDATE dbc_areapoi SET Name_Lang_koKR='아리덴의 야영지', Description_Lang_koKR='' WHERE ID=1287;
UPDATE dbc_areapoi SET Name_Lang_koKR='부랑자 소굴', Description_Lang_koKR='' WHERE ID=1128;
UPDATE dbc_areapoi SET Name_Lang_koKR='무법항', Description_Lang_koKR='' WHERE ID=40;
UPDATE dbc_areapoi SET Name_Lang_koKR='돌주먹 전초기지', Description_Lang_koKR='' WHERE ID=1010;
UPDATE dbc_areapoi SET Name_Lang_koKR='브릴', Description_Lang_koKR='' WHERE ID=2;
UPDATE dbc_areapoi SET Name_Lang_koKR='브라우만 밀농장', Description_Lang_koKR='' WHERE ID=1018;
UPDATE dbc_areapoi SET Name_Lang_koKR='서리바람 야영지', Description_Lang_koKR='' WHERE ID=1307;
UPDATE dbc_areapoi SET Name_Lang_koKR='산마루 경비탑', Description_Lang_koKR='' WHERE ID=1770;
UPDATE dbc_areapoi SET Name_Lang_koKR='산마루 경비탑', Description_Lang_koKR='얼라이언스 분쟁 중' WHERE ID=1771;
UPDATE dbc_areapoi SET Name_Lang_koKR='산마루 경비탑', Description_Lang_koKR='호드 분쟁 중' WHERE ID=1772;
UPDATE dbc_areapoi SET Name_Lang_koKR='산마루 경비탑', Description_Lang_koKR='얼라이언스 점령 중' WHERE ID=1773;
UPDATE dbc_areapoi SET Name_Lang_koKR='산마루 경비탑', Description_Lang_koKR='호드 점령 중' WHERE ID=1774;
UPDATE dbc_areapoi SET Name_Lang_koKR='산마루 경비탑', Description_Lang_koKR='얼라이언스' WHERE ID=1775;
UPDATE dbc_areapoi SET Name_Lang_koKR='산마루 경비탑', Description_Lang_koKR='호드' WHERE ID=1776;
UPDATE dbc_areapoi SET Name_Lang_koKR='다크샤이어', Description_Lang_koKR='' WHERE ID=3;
UPDATE dbc_areapoi SET Name_Lang_koKR='죽음의 협곡', Description_Lang_koKR='' WHERE ID=1288;
UPDATE dbc_areapoi SET Name_Lang_koKR='데스넬', Description_Lang_koKR='' WHERE ID=4;
UPDATE dbc_areapoi SET Name_Lang_koKR='마른수염 골짜기', Description_Lang_koKR='' WHERE ID=327;
UPDATE dbc_areapoi SET Name_Lang_koKR='던 알가즈', Description_Lang_koKR='' WHERE ID=5;
UPDATE dbc_areapoi SET Name_Lang_koKR='던 모드르', Description_Lang_koKR='' WHERE ID=6;
UPDATE dbc_areapoi SET Name_Lang_koKR='먼지목도리 소굴', Description_Lang_koKR='' WHERE ID=1028;
UPDATE dbc_areapoi SET Name_Lang_koKR='동부방벽 경비탑', Description_Lang_koKR='' WHERE ID=1749;
UPDATE dbc_areapoi SET Name_Lang_koKR='동부방벽 경비탑', Description_Lang_koKR='얼라이언스 분쟁 중' WHERE ID=1750;
UPDATE dbc_areapoi SET Name_Lang_koKR='동부방벽 경비탑', Description_Lang_koKR='얼라이언스 점령 중' WHERE ID=1751;
UPDATE dbc_areapoi SET Name_Lang_koKR='동부방벽 경비탑', Description_Lang_koKR='호드 분쟁 중' WHERE ID=1752;
UPDATE dbc_areapoi SET Name_Lang_koKR='동부방벽 경비탑', Description_Lang_koKR='호드 점령 중' WHERE ID=1753;
UPDATE dbc_areapoi SET Name_Lang_koKR='동부방벽 경비탑', Description_Lang_koKR='호드' WHERE ID=1754;
UPDATE dbc_areapoi SET Name_Lang_koKR='동부방벽 경비탑', Description_Lang_koKR='얼라이언스' WHERE ID=1755;
UPDATE dbc_areapoi SET Name_Lang_koKR='메아리 광산', Description_Lang_koKR='' WHERE ID=949;
UPDATE dbc_areapoi SET Name_Lang_koKR='화염 마루', Description_Lang_koKR='' WHERE ID=1177;
UPDATE dbc_areapoi SET Name_Lang_koKR='골드샤이어', Description_Lang_koKR='' WHERE ID=7;
UPDATE dbc_areapoi SET Name_Lang_koKR='그림 바톨', Description_Lang_koKR='' WHERE ID=1033;
UPDATE dbc_areapoi SET Name_Lang_koKR='그롬골 주둔지', Description_Lang_koKR='' WHERE ID=41;
UPDATE dbc_areapoi SET Name_Lang_koKR='그로쉬고크 주둔지', Description_Lang_koKR='' WHERE ID=1011;
UPDATE dbc_areapoi SET Name_Lang_koKR='해머폴', Description_Lang_koKR='' WHERE ID=25;
UPDATE dbc_areapoi SET Name_Lang_koKR='아이언밴드 야영지', Description_Lang_koKR='' WHERE ID=948;
UPDATE dbc_areapoi SET Name_Lang_koKR='아이언포지', Description_Lang_koKR='' WHERE ID=8;
UPDATE dbc_areapoi SET Name_Lang_koKR='이바르 호박밭', Description_Lang_koKR='' WHERE ID=1702;
UPDATE dbc_areapoi SET Name_Lang_koKR='자네이로 섬', Description_Lang_koKR='' WHERE ID=1031;
UPDATE dbc_areapoi SET Name_Lang_koKR='석영 광산', Description_Lang_koKR='' WHERE ID=1030;
UPDATE dbc_areapoi SET Name_Lang_koKR='카르가스', Description_Lang_koKR='' WHERE ID=26;
UPDATE dbc_areapoi SET Name_Lang_koKR='카라노스', Description_Lang_koKR='' WHERE ID=9;
UPDATE dbc_areapoi SET Name_Lang_koKR='레이크샤이어', Description_Lang_koKR='' WHERE ID=10;
UPDATE dbc_areapoi SET Name_Lang_koKR='맥클루어 포도밭', Description_Lang_koKR='' WHERE ID=950;
UPDATE dbc_areapoi SET Name_Lang_koKR='메네실 항구', Description_Lang_koKR='' WHERE ID=11;
UPDATE dbc_areapoi SET Name_Lang_koKR='거울 호수', Description_Lang_koKR='' WHERE ID=227;
UPDATE dbc_areapoi SET Name_Lang_koKR='안개갈대 주둔지', Description_Lang_koKR='' WHERE ID=1683;
UPDATE dbc_areapoi SET Name_Lang_koKR='문브룩', Description_Lang_koKR='' WHERE ID=12;
UPDATE dbc_areapoi SET Name_Lang_koKR='검은그물 거미굴', Description_Lang_koKR='' WHERE ID=1016;
UPDATE dbc_areapoi SET Name_Lang_koKR='북부관문 경비탑', Description_Lang_koKR='' WHERE ID=1763;
UPDATE dbc_areapoi SET Name_Lang_koKR='북부관문 경비탑', Description_Lang_koKR='얼라이언스 분쟁 중' WHERE ID=1764;
UPDATE dbc_areapoi SET Name_Lang_koKR='북부관문 경비탑', Description_Lang_koKR='호드 분쟁 중' WHERE ID=1765;
UPDATE dbc_areapoi SET Name_Lang_koKR='북부관문 경비탑', Description_Lang_koKR='얼라이언스 점령 중' WHERE ID=1766;
UPDATE dbc_areapoi SET Name_Lang_koKR='북부관문 경비탑', Description_Lang_koKR='호드 점령 중' WHERE ID=1767;
UPDATE dbc_areapoi SET Name_Lang_koKR='북부관문 경비탑', Description_Lang_koKR='얼라이언스' WHERE ID=1768;
UPDATE dbc_areapoi SET Name_Lang_koKR='북부관문 경비탑', Description_Lang_koKR='호드' WHERE ID=1769;
UPDATE dbc_areapoi SET Name_Lang_koKR='노스샤이어 수도원', Description_Lang_koKR='' WHERE ID=13;
UPDATE dbc_areapoi SET Name_Lang_koKR='노스샤이어 포도밭', Description_Lang_koKR='' WHERE ID=954;
UPDATE dbc_areapoi SET Name_Lang_koKR='역병의 숲 경비탑', Description_Lang_koKR='' WHERE ID=1756;
UPDATE dbc_areapoi SET Name_Lang_koKR='역병의 숲 경비탑', Description_Lang_koKR='얼라이언스 분쟁 중' WHERE ID=1757;
UPDATE dbc_areapoi SET Name_Lang_koKR='역병의 숲 경비탑', Description_Lang_koKR='호드 점령 중' WHERE ID=1760;
UPDATE dbc_areapoi SET Name_Lang_koKR='역병의 숲 경비탑', Description_Lang_koKR='얼라이언스' WHERE ID=1761;
UPDATE dbc_areapoi SET Name_Lang_koKR='역병의 숲 경비탑', Description_Lang_koKR='호드' WHERE ID=1762;
UPDATE dbc_areapoi SET Name_Lang_koKR='역병의 숲 경비탑', Description_Lang_koKR='얼라이언스 점령 중' WHERE ID=1777;
UPDATE dbc_areapoi SET Name_Lang_koKR='까마귀 언덕', Description_Lang_koKR='' WHERE ID=14;
UPDATE dbc_areapoi SET Name_Lang_koKR='임시 주둔지', Description_Lang_koKR='' WHERE ID=24;
UPDATE dbc_areapoi SET Name_Lang_koKR='약탈의 바위굴', Description_Lang_koKR='' WHERE ID=956;
UPDATE dbc_areapoi SET Name_Lang_koKR='레스밴 동굴', Description_Lang_koKR='' WHERE ID=1008;
UPDATE dbc_areapoi SET Name_Lang_koKR='레반터스크 마을', Description_Lang_koKR='' WHERE ID=1507;
UPDATE dbc_areapoi SET Name_Lang_koKR='롤랜드 광산', Description_Lang_koKR='' WHERE ID=1127;
UPDATE dbc_areapoi SET Name_Lang_koKR='스칼로맨스', Description_Lang_koKR='' WHERE ID=710;
UPDATE dbc_areapoi SET Name_Lang_koKR='감시의 언덕', Description_Lang_koKR='' WHERE ID=15;
UPDATE dbc_areapoi SET Name_Lang_koKR='살육의 동굴', Description_Lang_koKR='' WHERE ID=247;
UPDATE dbc_areapoi SET Name_Lang_koKR='수면의 협곡', Description_Lang_koKR='' WHERE ID=1289;
UPDATE dbc_areapoi SET Name_Lang_koKR='뱀갈퀴 바위굴', Description_Lang_koKR='' WHERE ID=1176;
UPDATE dbc_areapoi SET Name_Lang_koKR='사우스쇼어', Description_Lang_koKR='' WHERE ID=22;
UPDATE dbc_areapoi SET Name_Lang_koKR='정기의 동굴', Description_Lang_koKR='' WHERE ID=1007;
UPDATE dbc_areapoi SET Name_Lang_koKR='진흙늪 동굴', Description_Lang_koKR='' WHERE ID=1012;
UPDATE dbc_areapoi SET Name_Lang_koKR='스틸그릴의 정비소', Description_Lang_koKR='' WHERE ID=947;
UPDATE dbc_areapoi SET Name_Lang_koKR='스토나드', Description_Lang_koKR='' WHERE ID=788;
UPDATE dbc_areapoi SET Name_Lang_koKR='스톤필드 농장', Description_Lang_koKR='' WHERE ID=951;
UPDATE dbc_areapoi SET Name_Lang_koKR='스톰윈드', Description_Lang_koKR='' WHERE ID=16;
UPDATE dbc_areapoi SET Name_Lang_koKR='스톰윈드 항구', Description_Lang_koKR='' WHERE ID=2110;
UPDATE dbc_areapoi SET Name_Lang_koKR='타렌 밀농장', Description_Lang_koKR='' WHERE ID=23;
UPDATE dbc_areapoi SET Name_Lang_koKR='아탈학카르 신전', Description_Lang_koKR='' WHERE ID=1013;
UPDATE dbc_areapoi SET Name_Lang_koKR='공포의 거미굴', Description_Lang_koKR='' WHERE ID=1017;
UPDATE dbc_areapoi SET Name_Lang_koKR='공동묘지', Description_Lang_koKR='' WHERE ID=17;
UPDATE dbc_areapoi SET Name_Lang_koKR='아라소르의 탑', Description_Lang_koKR='' WHERE ID=1014;
UPDATE dbc_areapoi SET Name_Lang_koKR='진흙탕 동굴', Description_Lang_koKR='' WHERE ID=1551;
UPDATE dbc_areapoi SET Name_Lang_koKR='텔사마', Description_Lang_koKR='' WHERE ID=19;
UPDATE dbc_areapoi SET Name_Lang_koKR='토륨 조합 거점', Description_Lang_koKR='' WHERE ID=1508;
UPDATE dbc_areapoi SET Name_Lang_koKR='일갈라의 탑', Description_Lang_koKR='' WHERE ID=955;
UPDATE dbc_areapoi SET Name_Lang_koKR='울다만', Description_Lang_koKR='' WHERE ID=1027;
UPDATE dbc_areapoi SET Name_Lang_koKR='공격받는 중', Description_Lang_koKR='저주받은 땅' WHERE ID=1698;
UPDATE dbc_areapoi SET Name_Lang_koKR='공격받는 중', Description_Lang_koKR='불타는 평원' WHERE ID=1699;
UPDATE dbc_areapoi SET Name_Lang_koKR='공격받는 중', Description_Lang_koKR='동부 역병지대' WHERE ID=1701;
UPDATE dbc_areapoi SET Name_Lang_koKR='언더시티', Description_Lang_koKR='' WHERE ID=18;
UPDATE dbc_areapoi SET Name_Lang_koKR='우서 경의 무덤', Description_Lang_koKR='' WHERE ID=709;
UPDATE dbc_areapoi SET Name_Lang_koKR='발간 농장', Description_Lang_koKR='' WHERE ID=1703;
UPDATE dbc_areapoi SET Name_Lang_koKR='서부 주둔지', Description_Lang_koKR='' WHERE ID=1029;
UPDATE dbc_areapoi SET Name_Lang_koKR='와일드해머 요새', Description_Lang_koKR='' WHERE ID=1015;
UPDATE dbc_areapoi SET Name_Lang_koKR='요잠바 섬', Description_Lang_koKR='' WHERE ID=1588;
UPDATE dbc_areapoi SET Name_Lang_koKR='알드랏실', Description_Lang_koKR='' WHERE ID=36;
UPDATE dbc_areapoi SET Name_Lang_koKR='알드랏실', Description_Lang_koKR='' WHERE ID=907;
UPDATE dbc_areapoi SET Name_Lang_koKR='아스트라나르', Description_Lang_koKR='' WHERE ID=42;
UPDATE dbc_areapoi SET Name_Lang_koKR='아우버다인', Description_Lang_koKR='' WHERE ID=798;
UPDATE dbc_areapoi SET Name_Lang_koKR='바네실 지하굴', Description_Lang_koKR='' WHERE ID=911;
UPDATE dbc_areapoi SET Name_Lang_koKR='배스랜 서식지', Description_Lang_koKR='' WHERE ID=1233;
UPDATE dbc_areapoi SET Name_Lang_koKR='검은나무일족 소굴', Description_Lang_koKR='' WHERE ID=1048;
UPDATE dbc_areapoi SET Name_Lang_koKR='붉은늪지 동굴', Description_Lang_koKR='' WHERE ID=1096;
UPDATE dbc_areapoi SET Name_Lang_koKR='블러드후프 마을', Description_Lang_koKR='' WHERE ID=28;
UPDATE dbc_areapoi SET Name_Lang_koKR='붉은송곳니 야영지', Description_Lang_koKR='' WHERE ID=1244;
UPDATE dbc_areapoi SET Name_Lang_koKR='피멍울 초소', Description_Lang_koKR='' WHERE ID=1220;
UPDATE dbc_areapoi SET Name_Lang_koKR='푸른늪지', Description_Lang_koKR='' WHERE ID=1090;
UPDATE dbc_areapoi SET Name_Lang_koKR='볼간의 구덩이', Description_Lang_koKR='' WHERE ID=1147;
UPDATE dbc_areapoi SET Name_Lang_koKR='그락카론드의 무덤', Description_Lang_koKR='' WHERE ID=1473;
UPDATE dbc_areapoi SET Name_Lang_koKR='담쟁이 마을', Description_Lang_koKR='' WHERE ID=1684;
UPDATE dbc_areapoi SET Name_Lang_koKR='브론즈비어드 야영지', Description_Lang_koKR='' WHERE ID=1694;
UPDATE dbc_areapoi SET Name_Lang_koKR='모자케 야영지', Description_Lang_koKR='' WHERE ID=790;
UPDATE dbc_areapoi SET Name_Lang_koKR='나라체 야영지', Description_Lang_koKR='' WHERE ID=30;
UPDATE dbc_areapoi SET Name_Lang_koKR='타우라조 야영지', Description_Lang_koKR='' WHERE ID=1469;
UPDATE dbc_areapoi SET Name_Lang_koKR='세나리온 요새', Description_Lang_koKR='' WHERE ID=1685;
UPDATE dbc_areapoi SET Name_Lang_koKR='절벽 폭포', Description_Lang_koKR='' WHERE ID=1050;
UPDATE dbc_areapoi SET Name_Lang_koKR='바위웅덩이 호수', Description_Lang_koKR='' WHERE ID=1228;
UPDATE dbc_areapoi SET Name_Lang_koKR='먹구름 봉우리', Description_Lang_koKR='' WHERE ID=1108;
UPDATE dbc_areapoi SET Name_Lang_koKR='암흑안개 거미굴', Description_Lang_koKR='' WHERE ID=1088;
UPDATE dbc_areapoi SET Name_Lang_koKR='다르나서스', Description_Lang_koKR='' WHERE ID=38;
UPDATE dbc_areapoi SET Name_Lang_koKR='악마벼락 협곡', Description_Lang_koKR='' WHERE ID=1239;
UPDATE dbc_areapoi SET Name_Lang_koKR='돌라나르', Description_Lang_koKR='' WHERE ID=37;
UPDATE dbc_areapoi SET Name_Lang_koKR='던 만다르', Description_Lang_koKR='' WHERE ID=1214;
UPDATE dbc_areapoi SET Name_Lang_koKR='엠버스트라이프의 굴', Description_Lang_koKR='' WHERE ID=1095;
UPDATE dbc_areapoi SET Name_Lang_koKR='눈망루 마을', Description_Lang_koKR='' WHERE ID=794;
UPDATE dbc_areapoi SET Name_Lang_koKR='팔파렌 강', Description_Lang_koKR='' WHERE ID=1235;
UPDATE dbc_areapoi SET Name_Lang_koKR='페더문 요새', Description_Lang_koKR='' WHERE ID=796;
UPDATE dbc_areapoi SET Name_Lang_koKR='악마 바위굴', Description_Lang_koKR='' WHERE ID=909;
UPDATE dbc_areapoi SET Name_Lang_koKR='숲의 노래', Description_Lang_koKR='' WHERE ID=1238;
UPDATE dbc_areapoi SET Name_Lang_koKR='격투의 섬', Description_Lang_koKR='' WHERE ID=1067;
UPDATE dbc_areapoi SET Name_Lang_koKR='높새바람 봉우리', Description_Lang_koKR='' WHERE ID=46;
UPDATE dbc_areapoi SET Name_Lang_koKR='버섯 바위굴', Description_Lang_koKR='' WHERE ID=1105;
UPDATE dbc_areapoi SET Name_Lang_koKR='가젯잔', Description_Lang_koKR='' WHERE ID=789;
UPDATE dbc_areapoi SET Name_Lang_koKR='침묵의 초소', Description_Lang_koKR='' WHERE ID=1149;
UPDATE dbc_areapoi SET Name_Lang_koKR='푸른발 마을', Description_Lang_koKR='' WHERE ID=1243;
UPDATE dbc_areapoi SET Name_Lang_koKR='헤타에라의 손아귀', Description_Lang_koKR='' WHERE ID=708;
UPDATE dbc_areapoi SET Name_Lang_koKR='강철바위 야영지', Description_Lang_koKR='' WHERE ID=1114;
UPDATE dbc_areapoi SET Name_Lang_koKR='강철나무 굴', Description_Lang_koKR='' WHERE ID=1219;
UPDATE dbc_areapoi SET Name_Lang_koKR='라리스 정자', Description_Lang_koKR='' WHERE ID=1175;
UPDATE dbc_areapoi SET Name_Lang_koKR='버려진 경비탑', Description_Lang_koKR='' WHERE ID=1091;
UPDATE dbc_areapoi SET Name_Lang_koKR='마라우돈', Description_Lang_koKR='' WHERE ID=1148;
UPDATE dbc_areapoi SET Name_Lang_koKR='마샬의 야영지', Description_Lang_koKR='' WHERE ID=1104;
UPDATE dbc_areapoi SET Name_Lang_koKR='신기루 경주장', Description_Lang_koKR='' WHERE ID=1110;
UPDATE dbc_areapoi SET Name_Lang_koKR='공포의 달빛 동굴', Description_Lang_koKR='' WHERE ID=1217;
UPDATE dbc_areapoi SET Name_Lang_koKR='몰샨 주둔지', Description_Lang_koKR='' WHERE ID=1512;
UPDATE dbc_areapoi SET Name_Lang_koKR='진흙톱니 거점', Description_Lang_koKR='' WHERE ID=2083;
UPDATE dbc_areapoi SET Name_Lang_koKR='나이트헤이븐', Description_Lang_koKR='' WHERE ID=1247;
UPDATE dbc_areapoi SET Name_Lang_koKR='나이젤의 야영지', Description_Lang_koKR='' WHERE ID=799;
UPDATE dbc_areapoi SET Name_Lang_koKR='북부 경비탑', Description_Lang_koKR='' WHERE ID=1089;
UPDATE dbc_areapoi SET Name_Lang_koKR='오닉시아의 둥지', Description_Lang_koKR='' WHERE ID=1094;
UPDATE dbc_areapoi SET Name_Lang_koKR='오그리마', Description_Lang_koKR='' WHERE ID=33;
UPDATE dbc_areapoi SET Name_Lang_koKR='오르텔의 은신처', Description_Lang_koKR='' WHERE ID=1690;
UPDATE dbc_areapoi SET Name_Lang_koKR='무쇠설인 소굴', Description_Lang_koKR='' WHERE ID=1168;
UPDATE dbc_areapoi SET Name_Lang_koKR='톱니항', Description_Lang_koKR='' WHERE ID=39;
UPDATE dbc_areapoi SET Name_Lang_koKR='파괴된 황혼의 야영지', Description_Lang_koKR='' WHERE ID=1171;
UPDATE dbc_areapoi SET Name_Lang_koKR='칼바위 언덕', Description_Lang_koKR='' WHERE ID=31;
UPDATE dbc_areapoi SET Name_Lang_koKR='칼바람 협곡', Description_Lang_koKR='' WHERE ID=913;
UPDATE dbc_areapoi SET Name_Lang_koKR='레스리스 성소', Description_Lang_koKR='' WHERE ID=1216;
UPDATE dbc_areapoi SET Name_Lang_koKR='하피 동굴', Description_Lang_koKR='' WHERE ID=1109;
UPDATE dbc_areapoi SET Name_Lang_koKR='솔라살 폐허', Description_Lang_koKR='' WHERE ID=1169;
UPDATE dbc_areapoi SET Name_Lang_koKR='미늘벌레 경보!', Description_Lang_koKR='실리시스트 괴물이 출현했습니다.' WHERE ID=1724;
UPDATE dbc_areapoi SET Name_Lang_koKR='미늘벌레 경보!', Description_Lang_koKR='실리시스트 괴물이 출현했습니다.' WHERE ID=1725;
UPDATE dbc_areapoi SET Name_Lang_koKR='미늘벌레 경보!', Description_Lang_koKR='실리시스트 괴물이 출현했습니다.' WHERE ID=1726;
UPDATE dbc_areapoi SET Name_Lang_koKR='미늘벌레 경보!', Description_Lang_koKR='실리시스트 괴물이 출현했습니다.' WHERE ID=1727;
UPDATE dbc_areapoi SET Name_Lang_koKR='비늘수염 동굴', Description_Lang_koKR='' WHERE ID=1211;
UPDATE dbc_areapoi SET Name_Lang_koKR='스크래블스크류의 야영지', Description_Lang_koKR='' WHERE ID=1150;
UPDATE dbc_areapoi SET Name_Lang_koKR='센진 마을', Description_Lang_koKR='' WHERE ID=34;
UPDATE dbc_areapoi SET Name_Lang_koKR='감시초소', Description_Lang_koKR='' WHERE ID=1097;
UPDATE dbc_areapoi SET Name_Lang_koKR='그늘수렵 마을', Description_Lang_koKR='' WHERE ID=795;
UPDATE dbc_areapoi SET Name_Lang_koKR='그늘 거미굴', Description_Lang_koKR='' WHERE ID=908;
UPDATE dbc_areapoi SET Name_Lang_koKR='그늘 쉼터 여관', Description_Lang_koKR='' WHERE ID=1087;
UPDATE dbc_areapoi SET Name_Lang_koKR='샬자루의 둥지', Description_Lang_koKR='' WHERE ID=1187;
UPDATE dbc_areapoi SET Name_Lang_koKR='레물로스의 제단', Description_Lang_koKR='' WHERE ID=1246;
UPDATE dbc_areapoi SET Name_Lang_koKR='실바람 산장', Description_Lang_koKR='' WHERE ID=1242;
UPDATE dbc_areapoi SET Name_Lang_koKR='은빛날개 숲', Description_Lang_koKR='' WHERE ID=1513;
UPDATE dbc_areapoi SET Name_Lang_koKR='은빛날개 전초기지', Description_Lang_koKR='' WHERE ID=1240;
UPDATE dbc_areapoi SET Name_Lang_koKR='시쉬르 협곡', Description_Lang_koKR='' WHERE ID=1227;
UPDATE dbc_areapoi SET Name_Lang_koKR='토막나무 주둔지', Description_Lang_koKR='' WHERE ID=1471;
UPDATE dbc_areapoi SET Name_Lang_koKR='갈래발굽 소굴', Description_Lang_koKR='' WHERE ID=1112;
UPDATE dbc_areapoi SET Name_Lang_koKR='스테그헬름 거점', Description_Lang_koKR='' WHERE ID=1688;
UPDATE dbc_areapoi SET Name_Lang_koKR='돌망치일족 폐허', Description_Lang_koKR='' WHERE ID=1093;
UPDATE dbc_areapoi SET Name_Lang_koKR='돌발톱 봉우리', Description_Lang_koKR='' WHERE ID=44;
UPDATE dbc_areapoi SET Name_Lang_koKR='스톰레이지 지하굴', Description_Lang_koKR='' WHERE ID=1248;
UPDATE dbc_areapoi SET Name_Lang_koKR='해바위 야영지', Description_Lang_koKR='' WHERE ID=701;
UPDATE dbc_areapoi SET Name_Lang_koKR='늪지기 오두막', Description_Lang_koKR='' WHERE ID=1098;
UPDATE dbc_areapoi SET Name_Lang_koKR='타혼다 폐허', Description_Lang_koKR='' WHERE ID=1116;
UPDATE dbc_areapoi SET Name_Lang_koKR='탈렌드리스 초소', Description_Lang_koKR='' WHERE ID=1215;
UPDATE dbc_areapoi SET Name_Lang_koKR='진말로의 신전', Description_Lang_koKR='' WHERE ID=707;
UPDATE dbc_areapoi SET Name_Lang_koKR='탈라나르', Description_Lang_koKR='' WHERE ID=45;
UPDATE dbc_areapoi SET Name_Lang_koKR='바위 동굴', Description_Lang_koKR='' WHERE ID=912;
UPDATE dbc_areapoi SET Name_Lang_koKR='크로스로드', Description_Lang_koKR='' WHERE ID=35;
UPDATE dbc_areapoi SET Name_Lang_koKR='동굴 막사', Description_Lang_koKR='' WHERE ID=32;
UPDATE dbc_areapoi SET Name_Lang_koKR='도르다닐 지하굴', Description_Lang_koKR='' WHERE ID=1241;
UPDATE dbc_areapoi SET Name_Lang_koKR='켈테릴의 폐허', Description_Lang_koKR='' WHERE ID=1213;
UPDATE dbc_areapoi SET Name_Lang_koKR='오르딜아란의 폐허', Description_Lang_koKR='' WHERE ID=1232;
UPDATE dbc_areapoi SET Name_Lang_koKR='녹슨망치 발굴현장', Description_Lang_koKR='' WHERE ID=1111;
UPDATE dbc_areapoi SET Name_Lang_koKR='벌레무리 기둥', Description_Lang_koKR='' WHERE ID=1472;
UPDATE dbc_areapoi SET Name_Lang_koKR='갈퀴발톱굴', Description_Lang_koKR='' WHERE ID=1231;
UPDATE dbc_areapoi SET Name_Lang_koKR='돌발톱 토굴길', Description_Lang_koKR='' WHERE ID=1230;
UPDATE dbc_areapoi SET Name_Lang_koKR='돌발톱 토굴길', Description_Lang_koKR='' WHERE ID=1245;
UPDATE dbc_areapoi SET Name_Lang_koKR='비바람 바위굴', Description_Lang_koKR='' WHERE ID=1113;
UPDATE dbc_areapoi SET Name_Lang_koKR='테라모어 섬', Description_Lang_koKR='' WHERE ID=791;
UPDATE dbc_areapoi SET Name_Lang_koKR='썬더 블러프', Description_Lang_koKR='' WHERE ID=29;
UPDATE dbc_areapoi SET Name_Lang_koKR='성난파도 만', Description_Lang_koKR='' WHERE ID=1092;
UPDATE dbc_areapoi SET Name_Lang_koKR='나무구렁 요새', Description_Lang_koKR='' WHERE ID=1212;
UPDATE dbc_areapoi SET Name_Lang_koKR='나무구렁 요새', Description_Lang_koKR='' WHERE ID=1218;
UPDATE dbc_areapoi SET Name_Lang_koKR='톨크렌 농장', Description_Lang_koKR='' WHERE ID=929;
UPDATE dbc_areapoi SET Name_Lang_koKR='황혼의 망치단 주둔지', Description_Lang_koKR='' WHERE ID=1687;
UPDATE dbc_areapoi SET Name_Lang_koKR='황혼의 전초기지', Description_Lang_koKR='' WHERE ID=1173;
UPDATE dbc_areapoi SET Name_Lang_koKR='황혼의 초소', Description_Lang_koKR='' WHERE ID=1172;
UPDATE dbc_areapoi SET Name_Lang_koKR='황혼의 터', Description_Lang_koKR='' WHERE ID=1689;
UPDATE dbc_areapoi SET Name_Lang_koKR='울둠', Description_Lang_koKR='' WHERE ID=1107;
UPDATE dbc_areapoi SET Name_Lang_koKR='공격받는 중', Description_Lang_koKR='여명의 설원' WHERE ID=1696;
UPDATE dbc_areapoi SET Name_Lang_koKR='공격받는 중', Description_Lang_koKR='아즈샤라' WHERE ID=1697;
UPDATE dbc_areapoi SET Name_Lang_koKR='공격받는 중', Description_Lang_koKR='타나리스' WHERE ID=1700;
UPDATE dbc_areapoi SET Name_Lang_koKR='뼈의 골짜기', Description_Lang_koKR='' WHERE ID=1151;
UPDATE dbc_areapoi SET Name_Lang_koKR='용사의 안식처', Description_Lang_koKR='' WHERE ID=1567;
UPDATE dbc_areapoi SET Name_Lang_koKR='투자개발회사 광산', Description_Lang_koKR='' WHERE ID=1047;
UPDATE dbc_areapoi SET Name_Lang_koKR='통곡의 동굴', Description_Lang_koKR='' WHERE ID=1068;
UPDATE dbc_areapoi SET Name_Lang_koKR='전쟁노래부족 노동기지', Description_Lang_koKR='' WHERE ID=1268;
UPDATE dbc_areapoi SET Name_Lang_koKR='파도타기 해안', Description_Lang_koKR='' WHERE ID=1106;
UPDATE dbc_areapoi SET Name_Lang_koKR='위젤의 분화구', Description_Lang_koKR='' WHERE ID=1115;
UPDATE dbc_areapoi SET Name_Lang_koKR='백사장 야영지', Description_Lang_koKR='' WHERE ID=767;
UPDATE dbc_areapoi SET Name_Lang_koKR='성난굽이 강', Description_Lang_koKR='' WHERE ID=1049;
UPDATE dbc_areapoi SET Name_Lang_koKR='칼바람 광산', Description_Lang_koKR='' WHERE ID=1229;
UPDATE dbc_areapoi SET Name_Lang_koKR='덩굴발일족 소굴', Description_Lang_koKR='' WHERE ID=1475;
UPDATE dbc_areapoi SET Name_Lang_koKR='덩굴발 언덕', Description_Lang_koKR='' WHERE ID=1174;
UPDATE dbc_areapoi SET Name_Lang_koKR='사비안', Description_Lang_koKR='' WHERE ID=1237;
UPDATE dbc_areapoi SET Name_Lang_koKR='조람가르 전초기지', Description_Lang_koKR='' WHERE ID=1234;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음이빨 광산', Description_Lang_koKR='호드 점령지' WHERE ID=1102;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음이빨 광산', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1358;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음이빨 광산', Description_Lang_koKR='코볼트 점령지' WHERE ID=1359;
UPDATE dbc_areapoi SET Name_Lang_koKR='던 발다르', Description_Lang_koKR='' WHERE ID=1328;
UPDATE dbc_areapoi SET Name_Lang_koKR='북부 던 발다르 참호', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1250;
UPDATE dbc_areapoi SET Name_Lang_koKR='북부 던 발다르 참호', Description_Lang_koKR='파괴됨' WHERE ID=1352;
UPDATE dbc_areapoi SET Name_Lang_koKR='북부 던 발다르 참호', Description_Lang_koKR='분쟁 지역' WHERE ID=1353;
UPDATE dbc_areapoi SET Name_Lang_koKR='북부 던 발다르 참호', Description_Lang_koKR='분쟁 지역' WHERE ID=1354;
UPDATE dbc_areapoi SET Name_Lang_koKR='남부 던 발다르 참호', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1249;
UPDATE dbc_areapoi SET Name_Lang_koKR='남부 던 발다르 참호', Description_Lang_koKR='파괴됨' WHERE ID=1355;
UPDATE dbc_areapoi SET Name_Lang_koKR='남부 던 발다르 참호', Description_Lang_koKR='분쟁 지역' WHERE ID=1356;
UPDATE dbc_areapoi SET Name_Lang_koKR='남부 던 발다르 참호', Description_Lang_koKR='분쟁 지역' WHERE ID=1357;
UPDATE dbc_areapoi SET Name_Lang_koKR='동부 서리늑대 보초탑', Description_Lang_koKR='호드 점령지' WHERE ID=1255;
UPDATE dbc_areapoi SET Name_Lang_koKR='동부 서리늑대 보초탑', Description_Lang_koKR='파괴됨' WHERE ID=1362;
UPDATE dbc_areapoi SET Name_Lang_koKR='동부 서리늑대 보초탑', Description_Lang_koKR='분쟁 지역' WHERE ID=1363;
UPDATE dbc_areapoi SET Name_Lang_koKR='동부 서리늑대 보초탑', Description_Lang_koKR='분쟁 지역' WHERE ID=1364;
UPDATE dbc_areapoi SET Name_Lang_koKR='서리늑대 무덤', Description_Lang_koKR='호드 점령지' WHERE ID=1210;
UPDATE dbc_areapoi SET Name_Lang_koKR='서리늑대 무덤', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1368;
UPDATE dbc_areapoi SET Name_Lang_koKR='서리늑대 무덤', Description_Lang_koKR='분쟁 지역' WHERE ID=1369;
UPDATE dbc_areapoi SET Name_Lang_koKR='서리늑대 무덤', Description_Lang_koKR='분쟁 지역' WHERE ID=1370;
UPDATE dbc_areapoi SET Name_Lang_koKR='서리늑대 요새', Description_Lang_koKR='' WHERE ID=1103;
UPDATE dbc_areapoi SET Name_Lang_koKR='서리늑대 구호막사', Description_Lang_koKR='호드 점령지' WHERE ID=1351;
UPDATE dbc_areapoi SET Name_Lang_koKR='서리늑대 구호막사', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1371;
UPDATE dbc_areapoi SET Name_Lang_koKR='서리늑대 구호막사', Description_Lang_koKR='분쟁 지역' WHERE ID=1372;
UPDATE dbc_areapoi SET Name_Lang_koKR='서리늑대 구호막사', Description_Lang_koKR='분쟁 지역' WHERE ID=1373;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음피 주둔지', Description_Lang_koKR='' WHERE ID=1101;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음피 무덤', Description_Lang_koKR='호드 점령지' WHERE ID=1349;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음피 무덤', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1374;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음피 무덤', Description_Lang_koKR='분쟁 지역' WHERE ID=1375;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음피 무덤', Description_Lang_koKR='분쟁 지역' WHERE ID=1376;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음피 보초탑', Description_Lang_koKR='호드 점령지' WHERE ID=1252;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음피 보초탑', Description_Lang_koKR='파괴됨' WHERE ID=1377;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음피 보초탑', Description_Lang_koKR='분쟁 지역' WHERE ID=1378;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음피 보초탑', Description_Lang_koKR='분쟁 지역' WHERE ID=1379;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음날개 참호', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1251;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음날개 참호', Description_Lang_koKR='파괴됨' WHERE ID=1380;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음날개 참호', Description_Lang_koKR='분쟁 지역' WHERE ID=1381;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음날개 참호', Description_Lang_koKR='분쟁 지역' WHERE ID=1382;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼음날개 동굴', Description_Lang_koKR='' WHERE ID=1569;
UPDATE dbc_areapoi SET Name_Lang_koKR='깊은무쇠 광산', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1099;
UPDATE dbc_areapoi SET Name_Lang_koKR='깊은무쇠 광산', Description_Lang_koKR='호드 점령지' WHERE ID=1383;
UPDATE dbc_areapoi SET Name_Lang_koKR='깊은무쇠 광산', Description_Lang_koKR='트로그 점령지' WHERE ID=1384;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼라이언스', Description_Lang_koKR='' WHERE ID=1550;
UPDATE dbc_areapoi SET Name_Lang_koKR='눈사태 무덤', Description_Lang_koKR='호드 점령지' WHERE ID=1209;
UPDATE dbc_areapoi SET Name_Lang_koKR='눈사태 무덤', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1386;
UPDATE dbc_areapoi SET Name_Lang_koKR='눈사태 무덤', Description_Lang_koKR='분쟁 지역' WHERE ID=1387;
UPDATE dbc_areapoi SET Name_Lang_koKR='눈사태 무덤', Description_Lang_koKR='분쟁 지역' WHERE ID=1388;
UPDATE dbc_areapoi SET Name_Lang_koKR='눈사태 무덤', Description_Lang_koKR='미점령 지역' WHERE ID=1682;
UPDATE dbc_areapoi SET Name_Lang_koKR='돌심장 참호', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1347;
UPDATE dbc_areapoi SET Name_Lang_koKR='돌심장 참호', Description_Lang_koKR='파괴됨' WHERE ID=1389;
UPDATE dbc_areapoi SET Name_Lang_koKR='돌심장 참호', Description_Lang_koKR='분쟁 지역' WHERE ID=1390;
UPDATE dbc_areapoi SET Name_Lang_koKR='돌심장 참호', Description_Lang_koKR='분쟁 지역' WHERE ID=1391;
UPDATE dbc_areapoi SET Name_Lang_koKR='돌심장 무덤', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1350;
UPDATE dbc_areapoi SET Name_Lang_koKR='돌심장 무덤', Description_Lang_koKR='호드 점령지' WHERE ID=1392;
UPDATE dbc_areapoi SET Name_Lang_koKR='돌심장 무덤', Description_Lang_koKR='분쟁 지역' WHERE ID=1393;
UPDATE dbc_areapoi SET Name_Lang_koKR='돌심장 무덤', Description_Lang_koKR='분쟁 지역' WHERE ID=1394;
UPDATE dbc_areapoi SET Name_Lang_koKR='돌심장 전초기지', Description_Lang_koKR='' WHERE ID=1100;
UPDATE dbc_areapoi SET Name_Lang_koKR='스톰파이크 보급기지', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1348;
UPDATE dbc_areapoi SET Name_Lang_koKR='스톰파이크 보급기지', Description_Lang_koKR='호드 점령지' WHERE ID=1395;
UPDATE dbc_areapoi SET Name_Lang_koKR='스톰파이크 보급기지', Description_Lang_koKR='분쟁 지역' WHERE ID=1396;
UPDATE dbc_areapoi SET Name_Lang_koKR='스톰파이크 보급기지', Description_Lang_koKR='분쟁 지역' WHERE ID=1397;
UPDATE dbc_areapoi SET Name_Lang_koKR='스톰파이크 무덤', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1208;
UPDATE dbc_areapoi SET Name_Lang_koKR='스톰파이크 무덤', Description_Lang_koKR='호드 점령지' WHERE ID=1398;
UPDATE dbc_areapoi SET Name_Lang_koKR='스톰파이크 무덤', Description_Lang_koKR='분쟁 지역' WHERE ID=1399;
UPDATE dbc_areapoi SET Name_Lang_koKR='스톰파이크 무덤', Description_Lang_koKR='분쟁 지역' WHERE ID=1400;
UPDATE dbc_areapoi SET Name_Lang_koKR='거점 보초탑', Description_Lang_koKR='호드 점령지' WHERE ID=1254;
UPDATE dbc_areapoi SET Name_Lang_koKR='거점 보초탑', Description_Lang_koKR='파괴됨' WHERE ID=1405;
UPDATE dbc_areapoi SET Name_Lang_koKR='거점 보초탑', Description_Lang_koKR='분쟁 지역' WHERE ID=1406;
UPDATE dbc_areapoi SET Name_Lang_koKR='거점 보초탑', Description_Lang_koKR='분쟁 지역' WHERE ID=1407;
UPDATE dbc_areapoi SET Name_Lang_koKR='서부 서리늑대 보초탑', Description_Lang_koKR='호드 점령지' WHERE ID=1527;
UPDATE dbc_areapoi SET Name_Lang_koKR='서부 서리늑대 보초탑', Description_Lang_koKR='파괴됨' WHERE ID=1528;
UPDATE dbc_areapoi SET Name_Lang_koKR='서부 서리늑대 보초탑', Description_Lang_koKR='분쟁 지역' WHERE ID=1529;
UPDATE dbc_areapoi SET Name_Lang_koKR='서부 서리늑대 보초탑', Description_Lang_koKR='분쟁 지역' WHERE ID=1530;
UPDATE dbc_areapoi SET Name_Lang_koKR='자갈발 동굴', Description_Lang_koKR='' WHERE ID=1568;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼라이언스', Description_Lang_koKR='' WHERE ID=20;
UPDATE dbc_areapoi SET Name_Lang_koKR='호드', Description_Lang_koKR='' WHERE ID=21;
UPDATE dbc_areapoi SET Name_Lang_koKR='대장간', Description_Lang_koKR='미점령 지역' WHERE ID=1614;
UPDATE dbc_areapoi SET Name_Lang_koKR='대장간', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1615;
UPDATE dbc_areapoi SET Name_Lang_koKR='대장간', Description_Lang_koKR='호드 점령지' WHERE ID=1616;
UPDATE dbc_areapoi SET Name_Lang_koKR='대장간', Description_Lang_koKR='분쟁 지역' WHERE ID=1617;
UPDATE dbc_areapoi SET Name_Lang_koKR='대장간', Description_Lang_koKR='분쟁 지역' WHERE ID=1618;
UPDATE dbc_areapoi SET Name_Lang_koKR='농장', Description_Lang_koKR='미점령 지역' WHERE ID=1629;
UPDATE dbc_areapoi SET Name_Lang_koKR='농장', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1630;
UPDATE dbc_areapoi SET Name_Lang_koKR='농장', Description_Lang_koKR='호드 점령지' WHERE ID=1631;
UPDATE dbc_areapoi SET Name_Lang_koKR='농장', Description_Lang_koKR='분쟁 지역' WHERE ID=1632;
UPDATE dbc_areapoi SET Name_Lang_koKR='농장', Description_Lang_koKR='분쟁 지역' WHERE ID=1633;
UPDATE dbc_areapoi SET Name_Lang_koKR='금광', Description_Lang_koKR='미점령 지역' WHERE ID=1624;
UPDATE dbc_areapoi SET Name_Lang_koKR='금광', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1625;
UPDATE dbc_areapoi SET Name_Lang_koKR='금광', Description_Lang_koKR='호드 점령지' WHERE ID=1626;
UPDATE dbc_areapoi SET Name_Lang_koKR='금광', Description_Lang_koKR='분쟁 지역' WHERE ID=1627;
UPDATE dbc_areapoi SET Name_Lang_koKR='금광', Description_Lang_koKR='분쟁 지역' WHERE ID=1628;
UPDATE dbc_areapoi SET Name_Lang_koKR='제재소', Description_Lang_koKR='미점령 지역' WHERE ID=1619;
UPDATE dbc_areapoi SET Name_Lang_koKR='제재소', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1620;
UPDATE dbc_areapoi SET Name_Lang_koKR='제재소', Description_Lang_koKR='호드 점령지' WHERE ID=1621;
UPDATE dbc_areapoi SET Name_Lang_koKR='제재소', Description_Lang_koKR='분쟁 지역' WHERE ID=1622;
UPDATE dbc_areapoi SET Name_Lang_koKR='제재소', Description_Lang_koKR='분쟁 지역' WHERE ID=1623;
UPDATE dbc_areapoi SET Name_Lang_koKR='마구간', Description_Lang_koKR='미점령 지역' WHERE ID=1609;
UPDATE dbc_areapoi SET Name_Lang_koKR='마구간', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1610;
UPDATE dbc_areapoi SET Name_Lang_koKR='마구간', Description_Lang_koKR='호드 점령지' WHERE ID=1611;
UPDATE dbc_areapoi SET Name_Lang_koKR='마구간', Description_Lang_koKR='분쟁 지역' WHERE ID=1612;
UPDATE dbc_areapoi SET Name_Lang_koKR='마구간', Description_Lang_koKR='분쟁 지역' WHERE ID=1613;
UPDATE dbc_areapoi SET Name_Lang_koKR='알레리아 성채', Description_Lang_koKR='' WHERE ID=2074;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼라이언스 척후병', Description_Lang_koKR='' WHERE ID=1904;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼라이언스 척후병', Description_Lang_koKR='' WHERE ID=1905;
UPDATE dbc_areapoi SET Name_Lang_koKR='샤타르 제단', Description_Lang_koKR='' WHERE ID=2078;
UPDATE dbc_areapoi SET Name_Lang_koKR='아마니 지하묘지', Description_Lang_koKR='' WHERE ID=1809;
UPDATE dbc_areapoi SET Name_Lang_koKR='아마니 고개', Description_Lang_koKR='' WHERE ID=1811;
UPDATE dbc_areapoi SET Name_Lang_koKR='호박그물 고개', Description_Lang_koKR='' WHERE ID=1837;
UPDATE dbc_areapoi SET Name_Lang_koKR='암멘 들판', Description_Lang_koKR='' WHERE ID=1799;
UPDATE dbc_areapoi SET Name_Lang_koKR='안다로스', Description_Lang_koKR='' WHERE ID=1819;
UPDATE dbc_areapoi SET Name_Lang_koKR='안오윈', Description_Lang_koKR='' WHERE ID=2006;
UPDATE dbc_areapoi SET Name_Lang_koKR='안텔라스', Description_Lang_koKR='' WHERE ID=1808;
UPDATE dbc_areapoi SET Name_Lang_koKR='안딜리엔 영지', Description_Lang_koKR='' WHERE ID=1812;
UPDATE dbc_areapoi SET Name_Lang_koKR='52번 구역', Description_Lang_koKR='' WHERE ID=2071;
UPDATE dbc_areapoi SET Name_Lang_koKR='악사리엔', Description_Lang_koKR='' WHERE ID=1834;
UPDATE dbc_areapoi SET Name_Lang_koKR='하늘 감시초소', Description_Lang_koKR='' WHERE ID=1784;
UPDATE dbc_areapoi SET Name_Lang_koKR='칼날숲', Description_Lang_koKR='' WHERE ID=1830;
UPDATE dbc_areapoi SET Name_Lang_koKR='피투성이 지구라트', Description_Lang_koKR='' WHERE ID=1814;
UPDATE dbc_areapoi SET Name_Lang_koKR='핏빛 감시초소', Description_Lang_koKR='' WHERE ID=1940;
UPDATE dbc_areapoi SET Name_Lang_koKR='뾰족가지 군락', Description_Lang_koKR='' WHERE ID=1840;
UPDATE dbc_areapoi SET Name_Lang_koKR='뾰족가지 마을', Description_Lang_koKR='' WHERE ID=1780;
UPDATE dbc_areapoi SET Name_Lang_koKR='무너진 언덕', Description_Lang_koKR='미점령 지역' WHERE ID=1844;
UPDATE dbc_areapoi SET Name_Lang_koKR='무너진 언덕', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1845;
UPDATE dbc_areapoi SET Name_Lang_koKR='무너진 언덕', Description_Lang_koKR='호드 점령지' WHERE ID=1846;
UPDATE dbc_areapoi SET Name_Lang_koKR='세나리온 야영지', Description_Lang_koKR='' WHERE ID=2062;
UPDATE dbc_areapoi SET Name_Lang_koKR='마그하르 거점', Description_Lang_koKR='' WHERE ID=1722;
UPDATE dbc_areapoi SET Name_Lang_koKR='갈퀴송곳니 저수지', Description_Lang_koKR='' WHERE ID=2021;
UPDATE dbc_areapoi SET Name_Lang_koKR='코스모렌치', Description_Lang_koKR='' WHERE ID=2072;
UPDATE dbc_areapoi SET Name_Lang_koKR='추락 지점', Description_Lang_koKR='' WHERE ID=1795;
UPDATE dbc_areapoi SET Name_Lang_koKR='돈스타 첨탑', Description_Lang_koKR='' WHERE ID=1804;
UPDATE dbc_areapoi SET Name_Lang_koKR='데솔름', Description_Lang_koKR='' WHERE ID=1711;
UPDATE dbc_areapoi SET Name_Lang_koKR='하알에쉬 소굴', Description_Lang_koKR='' WHERE ID=1719;
UPDATE dbc_areapoi SET Name_Lang_koKR='더스크위더 첨탑', Description_Lang_koKR='' WHERE ID=2018;
UPDATE dbc_areapoi SET Name_Lang_koKR='동쪽 봉화', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1901;
UPDATE dbc_areapoi SET Name_Lang_koKR='동쪽 봉화', Description_Lang_koKR='호드 점령지' WHERE ID=1902;
UPDATE dbc_areapoi SET Name_Lang_koKR='동쪽 봉화', Description_Lang_koKR='' WHERE ID=1903;
UPDATE dbc_areapoi SET Name_Lang_koKR='동부 성소', Description_Lang_koKR='' WHERE ID=1822;
UPDATE dbc_areapoi SET Name_Lang_koKR='잿불숲', Description_Lang_koKR='' WHERE ID=1792;
UPDATE dbc_areapoi SET Name_Lang_koKR='영원의 숲', Description_Lang_koKR='' WHERE ID=2068;
UPDATE dbc_areapoi SET Name_Lang_koKR='산들바람 마을', Description_Lang_koKR='' WHERE ID=1709;
UPDATE dbc_areapoi SET Name_Lang_koKR='매의 감시탑', Description_Lang_koKR='' WHERE ID=1720;
UPDATE dbc_areapoi SET Name_Lang_koKR='매날개 광장', Description_Lang_koKR='' WHERE ID=1705;
UPDATE dbc_areapoi SET Name_Lang_koKR='매날개 광장 상급 성기사', Description_Lang_koKR='' WHERE ID=1999;
UPDATE dbc_areapoi SET Name_Lang_koKR='원정순찰대 산장', Description_Lang_koKR='' WHERE ID=1710;
UPDATE dbc_areapoi SET Name_Lang_koKR='원정순찰대 초소', Description_Lang_koKR='' WHERE ID=1805;
UPDATE dbc_areapoi SET Name_Lang_koKR='가라다르', Description_Lang_koKR='' WHERE ID=2064;
UPDATE dbc_areapoi SET Name_Lang_koKR='기즐의 야영지', Description_Lang_koKR='' WHERE ID=1783;
UPDATE dbc_areapoi SET Name_Lang_koKR='황금안개 마을', Description_Lang_koKR='' WHERE ID=1818;
UPDATE dbc_areapoi SET Name_Lang_koKR='황금 해안', Description_Lang_koKR='' WHERE ID=2015;
UPDATE dbc_areapoi SET Name_Lang_koKR='황금 해안', Description_Lang_koKR='' WHERE ID=2019;
UPDATE dbc_areapoi SET Name_Lang_koKR='할라아', Description_Lang_koKR='' WHERE ID=1920;
UPDATE dbc_areapoi SET Name_Lang_koKR='할라아', Description_Lang_koKR='호드 점령지' WHERE ID=1921;
UPDATE dbc_areapoi SET Name_Lang_koKR='할라아', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1922;
UPDATE dbc_areapoi SET Name_Lang_koKR='할라아', Description_Lang_koKR='' WHERE ID=1923;
UPDATE dbc_areapoi SET Name_Lang_koKR='할라아', Description_Lang_koKR='' WHERE ID=1924;
UPDATE dbc_areapoi SET Name_Lang_koKR='지옥불 성채', Description_Lang_koKR='' WHERE ID=1718;
UPDATE dbc_areapoi SET Name_Lang_koKR='명예의 요새', Description_Lang_koKR='' WHERE ID=1714;
UPDATE dbc_areapoi SET Name_Lang_koKR='호드 척후병', Description_Lang_koKR='' WHERE ID=1906;
UPDATE dbc_areapoi SET Name_Lang_koKR='호드 척후병', Description_Lang_koKR='' WHERE ID=1907;
UPDATE dbc_areapoi SET Name_Lang_koKR='울부짖는 지구라트', Description_Lang_koKR='' WHERE ID=1813;
UPDATE dbc_areapoi SET Name_Lang_koKR='화물선 잔해', Description_Lang_koKR='' WHERE ID=1789;
UPDATE dbc_areapoi SET Name_Lang_koKR='달날개 소굴', Description_Lang_koKR='' WHERE ID=1800;
UPDATE dbc_areapoi SET Name_Lang_koKR='나지비안', Description_Lang_koKR='' WHERE ID=1833;
UPDATE dbc_areapoi SET Name_Lang_koKR='다닥나무 숲', Description_Lang_koKR='' WHERE ID=1798;
UPDATE dbc_areapoi SET Name_Lang_koKR='북부 성소', Description_Lang_koKR='' WHERE ID=1825;
UPDATE dbc_areapoi SET Name_Lang_koKR='오디시우스의 정박지', Description_Lang_koKR='' WHERE ID=1793;
UPDATE dbc_areapoi SET Name_Lang_koKR='오그릴라', Description_Lang_koKR='' WHERE ID=2080;
UPDATE dbc_areapoi SET Name_Lang_koKR='오레보르 피난처', Description_Lang_koKR='' WHERE ID=2060;
UPDATE dbc_areapoi SET Name_Lang_koKR='탈출선 착륙지', Description_Lang_koKR='' WHERE ID=1781;
UPDATE dbc_areapoi SET Name_Lang_koKR='탈출선 잔해', Description_Lang_koKR='' WHERE ID=1782;
UPDATE dbc_areapoi SET Name_Lang_koKR='아고나르의 웅덩이', Description_Lang_koKR='' WHERE ID=1723;
UPDATE dbc_areapoi SET Name_Lang_koKR='성난깃털 마루', Description_Lang_koKR='' WHERE ID=1838;
UPDATE dbc_areapoi SET Name_Lang_koKR='로레스아란 폐허', Description_Lang_koKR='' WHERE ID=1832;
UPDATE dbc_areapoi SET Name_Lang_koKR='샤나르 폐허', Description_Lang_koKR='' WHERE ID=1721;
UPDATE dbc_areapoi SET Name_Lang_koKR='살데릴의 안식처', Description_Lang_koKR='' WHERE ID=1823;
UPDATE dbc_areapoi SET Name_Lang_koKR='달의 성소', Description_Lang_koKR='' WHERE ID=1817;
UPDATE dbc_areapoi SET Name_Lang_koKR='별의 성소', Description_Lang_koKR='' WHERE ID=2077;
UPDATE dbc_areapoi SET Name_Lang_koKR='태양의 성소', Description_Lang_koKR='' WHERE ID=1807;
UPDATE dbc_areapoi SET Name_Lang_koKR='물갈퀴 호수', Description_Lang_koKR='' WHERE ID=2022;
UPDATE dbc_areapoi SET Name_Lang_koKR='물갈퀴 호수', Description_Lang_koKR='' WHERE ID=2023;
UPDATE dbc_areapoi SET Name_Lang_koKR='어둠 마루', Description_Lang_koKR='' WHERE ID=1796;
UPDATE dbc_areapoi SET Name_Lang_koKR='어둠달 마을', Description_Lang_koKR='' WHERE ID=2075;
UPDATE dbc_areapoi SET Name_Lang_koKR='샬란드리스 섬', Description_Lang_koKR='' WHERE ID=2005;
UPDATE dbc_areapoi SET Name_Lang_koKR='샤트라스', Description_Lang_koKR='' WHERE ID=1961;
UPDATE dbc_areapoi SET Name_Lang_koKR='개펄 해안', Description_Lang_koKR='' WHERE ID=1787;
UPDATE dbc_areapoi SET Name_Lang_koKR='희망의 호수', Description_Lang_koKR='' WHERE ID=1797;
UPDATE dbc_areapoi SET Name_Lang_koKR='실버문', Description_Lang_koKR='' WHERE ID=1704;
UPDATE dbc_areapoi SET Name_Lang_koKR='영혼의 탑', Description_Lang_koKR='' WHERE ID=1925;
UPDATE dbc_areapoi SET Name_Lang_koKR='영혼의 탑', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1926;
UPDATE dbc_areapoi SET Name_Lang_koKR='영혼의 탑', Description_Lang_koKR='호드 점령지' WHERE ID=1927;
UPDATE dbc_areapoi SET Name_Lang_koKR='영혼의 탑', Description_Lang_koKR='' WHERE ID=1928;
UPDATE dbc_areapoi SET Name_Lang_koKR='영혼의 탑', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1929;
UPDATE dbc_areapoi SET Name_Lang_koKR='영혼의 탑', Description_Lang_koKR='호드 점령지' WHERE ID=1930;
UPDATE dbc_areapoi SET Name_Lang_koKR='영혼의 탑', Description_Lang_koKR='' WHERE ID=1931;
UPDATE dbc_areapoi SET Name_Lang_koKR='영혼의 탑', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1932;
UPDATE dbc_areapoi SET Name_Lang_koKR='영혼의 탑', Description_Lang_koKR='호드 점령지' WHERE ID=1933;
UPDATE dbc_areapoi SET Name_Lang_koKR='영혼의 탑', Description_Lang_koKR='' WHERE ID=1934;
UPDATE dbc_areapoi SET Name_Lang_koKR='영혼의 탑', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1935;
UPDATE dbc_areapoi SET Name_Lang_koKR='영혼의 탑', Description_Lang_koKR='호드 점령지' WHERE ID=1936;
UPDATE dbc_areapoi SET Name_Lang_koKR='영혼의 탑', Description_Lang_koKR='' WHERE ID=1937;
UPDATE dbc_areapoi SET Name_Lang_koKR='영혼의 탑', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1938;
UPDATE dbc_areapoi SET Name_Lang_koKR='영혼의 탑', Description_Lang_koKR='호드 점령지' WHERE ID=1939;
UPDATE dbc_areapoi SET Name_Lang_koKR='스포어가르', Description_Lang_koKR='' WHERE ID=2059;
UPDATE dbc_areapoi SET Name_Lang_koKR='너울소나무 요새', Description_Lang_koKR='' WHERE ID=1788;
UPDATE dbc_areapoi SET Name_Lang_koKR='잔잔한 속삭임 연못', Description_Lang_koKR='' WHERE ID=1826;
UPDATE dbc_areapoi SET Name_Lang_koKR='돌망치 요새', Description_Lang_koKR='' WHERE ID=2073;
UPDATE dbc_areapoi SET Name_Lang_koKR='태양너울 무기고', Description_Lang_koKR='적에게 점령됨' WHERE ID=2098;
UPDATE dbc_areapoi SET Name_Lang_koKR='태양너울 무기고', Description_Lang_koKR='무너진 태양 공격대' WHERE ID=2099;
UPDATE dbc_areapoi SET Name_Lang_koKR='태양너울 항구', Description_Lang_koKR='적에게 점령됨' WHERE ID=2100;
UPDATE dbc_areapoi SET Name_Lang_koKR='태양너울 항구', Description_Lang_koKR='무너진 태양 공격대' WHERE ID=2101;
UPDATE dbc_areapoi SET Name_Lang_koKR='태양너울 성소', Description_Lang_koKR='적에게 점령됨' WHERE ID=2096;
UPDATE dbc_areapoi SET Name_Lang_koKR='태양너울 성소', Description_Lang_koKR='무너진 태양 공격대' WHERE ID=2097;
UPDATE dbc_areapoi SET Name_Lang_koKR='태양왕관 마을', Description_Lang_koKR='' WHERE ID=1802;
UPDATE dbc_areapoi SET Name_Lang_koKR='해돋이 부두', Description_Lang_koKR='' WHERE ID=1708;
UPDATE dbc_areapoi SET Name_Lang_koKR='선스트라이더 섬', Description_Lang_koKR='' WHERE ID=1706;
UPDATE dbc_areapoi SET Name_Lang_koKR='늪쥐 감시초소', Description_Lang_koKR='' WHERE ID=2063;
UPDATE dbc_areapoi SET Name_Lang_koKR='실바나르', Description_Lang_koKR='' WHERE ID=2066;
UPDATE dbc_areapoi SET Name_Lang_koKR='갈퀴발톱 언덕', Description_Lang_koKR='' WHERE ID=1839;
UPDATE dbc_areapoi SET Name_Lang_koKR='텔라아르', Description_Lang_koKR='' WHERE ID=2065;
UPDATE dbc_areapoi SET Name_Lang_koKR='텔레도르', Description_Lang_koKR='' WHERE ID=2061;
UPDATE dbc_areapoi SET Name_Lang_koKR='텔하마트 사원', Description_Lang_koKR='' WHERE ID=2069;
UPDATE dbc_areapoi SET Name_Lang_koKR='극저온 핵', Description_Lang_koKR='' WHERE ID=1828;
UPDATE dbc_areapoi SET Name_Lang_koKR='죽음의 흉터', Description_Lang_koKR='' WHERE ID=2016;
UPDATE dbc_areapoi SET Name_Lang_koKR='죽음의 흉터', Description_Lang_koKR='' WHERE ID=2020;
UPDATE dbc_areapoi SET Name_Lang_koKR='엑소다르', Description_Lang_koKR='' WHERE ID=1785;
UPDATE dbc_areapoi SET Name_Lang_koKR='타락의 웅덩이', Description_Lang_koKR='' WHERE ID=1835;
UPDATE dbc_areapoi SET Name_Lang_koKR='숨은 산호초', Description_Lang_koKR='' WHERE ID=1836;
UPDATE dbc_areapoi SET Name_Lang_koKR='전망대', Description_Lang_koKR='미점령 지역' WHERE ID=1841;
UPDATE dbc_areapoi SET Name_Lang_koKR='전망대', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1842;
UPDATE dbc_areapoi SET Name_Lang_koKR='전망대', Description_Lang_koKR='호드 점령지' WHERE ID=1843;
UPDATE dbc_areapoi SET Name_Lang_koKR='신성한 숲', Description_Lang_koKR='' WHERE ID=1790;
UPDATE dbc_areapoi SET Name_Lang_koKR='경기장', Description_Lang_koKR='미점령 지역' WHERE ID=1847;
UPDATE dbc_areapoi SET Name_Lang_koKR='경기장', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1848;
UPDATE dbc_areapoi SET Name_Lang_koKR='경기장', Description_Lang_koKR='호드 점령지' WHERE ID=1849;
UPDATE dbc_areapoi SET Name_Lang_koKR='운명의 계단', Description_Lang_koKR='' WHERE ID=1716;
UPDATE dbc_areapoi SET Name_Lang_koKR='폭풍 첨탑', Description_Lang_koKR='' WHERE ID=2070;
UPDATE dbc_areapoi SET Name_Lang_koKR='태양 첨탑', Description_Lang_koKR='' WHERE ID=1707;
UPDATE dbc_areapoi SET Name_Lang_koKR='벡터 코일', Description_Lang_koKR='' WHERE ID=1827;
UPDATE dbc_areapoi SET Name_Lang_koKR='초공간 추진기', Description_Lang_koKR='' WHERE ID=1829;
UPDATE dbc_areapoi SET Name_Lang_koKR='스랄마', Description_Lang_koKR='' WHERE ID=1715;
UPDATE dbc_areapoi SET Name_Lang_koKR='킬제덴의 옥좌', Description_Lang_koKR='' WHERE ID=1717;
UPDATE dbc_areapoi SET Name_Lang_koKR='천둥군주 요새', Description_Lang_koKR='' WHERE ID=2067;
UPDATE dbc_areapoi SET Name_Lang_koKR='투론의 매타조 훈련장', Description_Lang_koKR='' WHERE ID=2017;
UPDATE dbc_areapoi SET Name_Lang_koKR='북부 해안 골짜기', Description_Lang_koKR='' WHERE ID=1801;
UPDATE dbc_areapoi SET Name_Lang_koKR='토르와타', Description_Lang_koKR='' WHERE ID=1820;
UPDATE dbc_areapoi SET Name_Lang_koKR='토쉴리의 연구기지', Description_Lang_koKR='' WHERE ID=2034;
UPDATE dbc_areapoi SET Name_Lang_koKR='배신자의 만', Description_Lang_koKR='' WHERE ID=1794;
UPDATE dbc_areapoi SET Name_Lang_koKR='트랜퀼리엔', Description_Lang_koKR='' WHERE ID=1713;
UPDATE dbc_areapoi SET Name_Lang_koKR='쌍둥이 첨탑 무덤', Description_Lang_koKR='' WHERE ID=1897;
UPDATE dbc_areapoi SET Name_Lang_koKR='쌍둥이 첨탑 무덤', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1898;
UPDATE dbc_areapoi SET Name_Lang_koKR='쌍둥이 첨탑 무덤', Description_Lang_koKR='호드 점령지' WHERE ID=1899;
UPDATE dbc_areapoi SET Name_Lang_koKR='그늘늪 호수', Description_Lang_koKR='' WHERE ID=2024;
UPDATE dbc_areapoi SET Name_Lang_koKR='그늘늪 호수', Description_Lang_koKR='' WHERE ID=2025;
UPDATE dbc_areapoi SET Name_Lang_koKR='미명 광산', Description_Lang_koKR='' WHERE ID=1815;
UPDATE dbc_areapoi SET Name_Lang_koKR='발라르의 나루', Description_Lang_koKR='' WHERE ID=1786;
UPDATE dbc_areapoi SET Name_Lang_koKR='서쪽 봉화', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1894;
UPDATE dbc_areapoi SET Name_Lang_koKR='서쪽 봉화', Description_Lang_koKR='호드 점령지' WHERE ID=1895;
UPDATE dbc_areapoi SET Name_Lang_koKR='서쪽 봉화', Description_Lang_koKR='' WHERE ID=1896;
UPDATE dbc_areapoi SET Name_Lang_koKR='서부 성소', Description_Lang_koKR='' WHERE ID=1824;
UPDATE dbc_areapoi SET Name_Lang_koKR='와일드해머 성채', Description_Lang_koKR='' WHERE ID=2076;
UPDATE dbc_areapoi SET Name_Lang_koKR='갈기바람 봉우리', Description_Lang_koKR='' WHERE ID=1791;
UPDATE dbc_areapoi SET Name_Lang_koKR='윈드러너 첨탑', Description_Lang_koKR='' WHERE ID=1712;
UPDATE dbc_areapoi SET Name_Lang_koKR='윈드러너 마을', Description_Lang_koKR='' WHERE ID=1816;
UPDATE dbc_areapoi SET Name_Lang_koKR='성난비늘 둥지', Description_Lang_koKR='' WHERE ID=1831;
UPDATE dbc_areapoi SET Name_Lang_koKR='성난비늘 거점', Description_Lang_koKR='' WHERE ID=1779;
UPDATE dbc_areapoi SET Name_Lang_koKR='와이번 야영지', Description_Lang_koKR='미점령 지역' WHERE ID=1908;
UPDATE dbc_areapoi SET Name_Lang_koKR='와이번 야영지', Description_Lang_koKR='호드 점령지' WHERE ID=1909;
UPDATE dbc_areapoi SET Name_Lang_koKR='와이번 야영지', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1910;
UPDATE dbc_areapoi SET Name_Lang_koKR='와이번 야영지', Description_Lang_koKR='미점령 지역' WHERE ID=1911;
UPDATE dbc_areapoi SET Name_Lang_koKR='와이번 야영지', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1912;
UPDATE dbc_areapoi SET Name_Lang_koKR='와이번 야영지', Description_Lang_koKR='호드 점령지' WHERE ID=1913;
UPDATE dbc_areapoi SET Name_Lang_koKR='와이번 야영지', Description_Lang_koKR='미점령 지역' WHERE ID=1914;
UPDATE dbc_areapoi SET Name_Lang_koKR='와이번 야영지', Description_Lang_koKR='호드 점령지' WHERE ID=1915;
UPDATE dbc_areapoi SET Name_Lang_koKR='와이번 야영지', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1916;
UPDATE dbc_areapoi SET Name_Lang_koKR='와이번 야영지', Description_Lang_koKR='미점령 지역' WHERE ID=1917;
UPDATE dbc_areapoi SET Name_Lang_koKR='와이번 야영지', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1918;
UPDATE dbc_areapoi SET Name_Lang_koKR='와이번 야영지', Description_Lang_koKR='호드 점령지' WHERE ID=1919;
UPDATE dbc_areapoi SET Name_Lang_koKR='와이번 야영지', Description_Lang_koKR='미점령 지역' WHERE ID=1963;
UPDATE dbc_areapoi SET Name_Lang_koKR='와이번 야영지', Description_Lang_koKR='미점령 지역' WHERE ID=1964;
UPDATE dbc_areapoi SET Name_Lang_koKR='와이번 야영지', Description_Lang_koKR='미점령 지역' WHERE ID=1965;
UPDATE dbc_areapoi SET Name_Lang_koKR='와이번 야영지', Description_Lang_koKR='미점령 지역' WHERE ID=1966;
UPDATE dbc_areapoi SET Name_Lang_koKR='자브라진', Description_Lang_koKR='' WHERE ID=2058;
UPDATE dbc_areapoi SET Name_Lang_koKR='제브노와', Description_Lang_koKR='' WHERE ID=1810;
UPDATE dbc_areapoi SET Name_Lang_koKR='제브소라', Description_Lang_koKR='' WHERE ID=1803;
UPDATE dbc_areapoi SET Name_Lang_koKR='제브텔라', Description_Lang_koKR='' WHERE ID=1806;
UPDATE dbc_areapoi SET Name_Lang_koKR='제브와타', Description_Lang_koKR='' WHERE ID=1821;
UPDATE dbc_areapoi SET Name_Lang_koKR='블러드 엘프 경비탑', Description_Lang_koKR='미점령 지역' WHERE ID=1941;
UPDATE dbc_areapoi SET Name_Lang_koKR='블러드 엘프 경비탑', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1942;
UPDATE dbc_areapoi SET Name_Lang_koKR='블러드 엘프 경비탑', Description_Lang_koKR='호드 점령지' WHERE ID=1943;
UPDATE dbc_areapoi SET Name_Lang_koKR='블러드 엘프 경비탑', Description_Lang_koKR='분쟁 지역' WHERE ID=1959;
UPDATE dbc_areapoi SET Name_Lang_koKR='블러드 엘프 경비탑', Description_Lang_koKR='분쟁 지역' WHERE ID=1960;
UPDATE dbc_areapoi SET Name_Lang_koKR='드레나이 폐허', Description_Lang_koKR='미점령 지역' WHERE ID=1950;
UPDATE dbc_areapoi SET Name_Lang_koKR='드레나이 폐허', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1951;
UPDATE dbc_areapoi SET Name_Lang_koKR='드레나이 폐허', Description_Lang_koKR='호드 점령지' WHERE ID=1952;
UPDATE dbc_areapoi SET Name_Lang_koKR='드레나이 폐허', Description_Lang_koKR='분쟁 지역' WHERE ID=1953;
UPDATE dbc_areapoi SET Name_Lang_koKR='드레나이 폐허', Description_Lang_koKR='분쟁 지역' WHERE ID=1954;
UPDATE dbc_areapoi SET Name_Lang_koKR='지옥절단기 폐허', Description_Lang_koKR='미점령 지역' WHERE ID=1944;
UPDATE dbc_areapoi SET Name_Lang_koKR='지옥절단기 폐허', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1945;
UPDATE dbc_areapoi SET Name_Lang_koKR='지옥절단기 폐허', Description_Lang_koKR='호드 점령지' WHERE ID=1946;
UPDATE dbc_areapoi SET Name_Lang_koKR='지옥절단기 폐허', Description_Lang_koKR='분쟁 지역' WHERE ID=1957;
UPDATE dbc_areapoi SET Name_Lang_koKR='지옥절단기 폐허', Description_Lang_koKR='분쟁 지역' WHERE ID=1958;
UPDATE dbc_areapoi SET Name_Lang_koKR='마법사 탑', Description_Lang_koKR='미점령 지역' WHERE ID=1947;
UPDATE dbc_areapoi SET Name_Lang_koKR='마법사 탑', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=1948;
UPDATE dbc_areapoi SET Name_Lang_koKR='마법사 탑', Description_Lang_koKR='호드 점령지' WHERE ID=1949;
UPDATE dbc_areapoi SET Name_Lang_koKR='마법사 탑', Description_Lang_koKR='분쟁 지역' WHERE ID=1955;
UPDATE dbc_areapoi SET Name_Lang_koKR='마법사 탑', Description_Lang_koKR='분쟁 지역' WHERE ID=1956;
UPDATE dbc_areapoi SET Name_Lang_koKR='황천의 폭풍 깃발', Description_Lang_koKR='미점령 지역' WHERE ID=1962;
UPDATE dbc_areapoi SET Name_Lang_koKR='아그마르의 망치', Description_Lang_koKR='' WHERE ID=2301;
UPDATE dbc_areapoi SET Name_Lang_koKR='호박빛소나무 오두막', Description_Lang_koKR='' WHERE ID=2311;
UPDATE dbc_areapoi SET Name_Lang_koKR='보르고로크 전초기지', Description_Lang_koKR='' WHERE ID=2308;
UPDATE dbc_areapoi SET Name_Lang_koKR='파괴된 신전 무덤', Description_Lang_koKR='' WHERE ID=2266;
UPDATE dbc_areapoi SET Name_Lang_koKR='파괴된 신전 차량 작업장', Description_Lang_koKR='' WHERE ID=2153;
UPDATE dbc_areapoi SET Name_Lang_koKR='브룬힐다르 마을', Description_Lang_koKR='' WHERE ID=2319;
UPDATE dbc_areapoi SET Name_Lang_koKR='원크와 야영지', Description_Lang_koKR='' WHERE ID=2312;
UPDATE dbc_areapoi SET Name_Lang_koKR='툰카로 야영지', Description_Lang_koKR='' WHERE ID=2318;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울발굽 야영지', Description_Lang_koKR='' WHERE ID=2090;
UPDATE dbc_areapoi SET Name_Lang_koKR='정복의 요새', Description_Lang_koKR='' WHERE ID=2310;
UPDATE dbc_areapoi SET Name_Lang_koKR='십자군 봉우리', Description_Lang_koKR='' WHERE ID=2323;
UPDATE dbc_areapoi SET Name_Lang_koKR='달라란', Description_Lang_koKR='' WHERE ID=2317;
UPDATE dbc_areapoi SET Name_Lang_koKR='죽음의 마루', Description_Lang_koKR='' WHERE ID=2138;
UPDATE dbc_areapoi SET Name_Lang_koKR='동부불꽃 차량 작업장', Description_Lang_koKR='' WHERE ID=2151;
UPDATE dbc_areapoi SET Name_Lang_koKR='피즈크랭크 비행장', Description_Lang_koKR='' WHERE ID=2307;
UPDATE dbc_areapoi SET Name_Lang_koKR='불꽃감시 경비탑', Description_Lang_koKR='' WHERE ID=2143;
UPDATE dbc_areapoi SET Name_Lang_koKR='빌더바르 요새', Description_Lang_koKR='' WHERE ID=2089;
UPDATE dbc_areapoi SET Name_Lang_koKR='요새 무덤', Description_Lang_koKR='' WHERE ID=2268;
UPDATE dbc_areapoi SET Name_Lang_koKR='동쪽 공성 차량 작업장', Description_Lang_koKR='' WHERE ID=2149;
UPDATE dbc_areapoi SET Name_Lang_koKR='서쪽 공성 차량 작업장', Description_Lang_koKR='' WHERE ID=2150;
UPDATE dbc_areapoi SET Name_Lang_koKR='서리요새', Description_Lang_koKR='' WHERE ID=2321;
UPDATE dbc_areapoi SET Name_Lang_koKR='그롬아쉬 추락 지점', Description_Lang_koKR='' WHERE ID=2322;
UPDATE dbc_areapoi SET Name_Lang_koKR='K3', Description_Lang_koKR='' WHERE ID=2320;
UPDATE dbc_areapoi SET Name_Lang_koKR='카마구아', Description_Lang_koKR='' WHERE ID=2085;
UPDATE dbc_areapoi SET Name_Lang_koKR='모아키 항구', Description_Lang_koKR='' WHERE ID=2302;
UPDATE dbc_areapoi SET Name_Lang_koKR='네싱워리 주둔지', Description_Lang_koKR='' WHERE ID=2316;
UPDATE dbc_areapoi SET Name_Lang_koKR='신 아가만드', Description_Lang_koKR='' WHERE ID=2088;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2199;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2200;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2201;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2203;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2205;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2206;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2207;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2208;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2209;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2210;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2211;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2212;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2213;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2214;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2215;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2216;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2217;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2218;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2219;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2220;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2221;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2247;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2248;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2249;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2250;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2251;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2252;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2253;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2254;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2255;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2256;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2257;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2258;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2259;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2260;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2261;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2262;
UPDATE dbc_areapoi SET Name_Lang_koKR='분쟁 감지', Description_Lang_koKR='' WHERE ID=2263;
UPDATE dbc_areapoi SET Name_Lang_koKR='그늘눈 경비탑', Description_Lang_koKR='' WHERE ID=2141;
UPDATE dbc_areapoi SET Name_Lang_koKR='남동부 무덤', Description_Lang_koKR='' WHERE ID=2270;
UPDATE dbc_areapoi SET Name_Lang_koKR='남서부 무덤', Description_Lang_koKR='' WHERE ID=2269;
UPDATE dbc_areapoi SET Name_Lang_koKR='별의 쉼터', Description_Lang_koKR='' WHERE ID=2300;
UPDATE dbc_areapoi SET Name_Lang_koKR='가라앉은 경기장 무덤', Description_Lang_koKR='' WHERE ID=2265;
UPDATE dbc_areapoi SET Name_Lang_koKR='가라앉은 경기장 차량 작업장', Description_Lang_koKR='' WHERE ID=2154;
UPDATE dbc_areapoi SET Name_Lang_koKR='타운카르 마을', Description_Lang_koKR='' WHERE ID=2306;
UPDATE dbc_areapoi SET Name_Lang_koKR='은빛십자군 격전지', Description_Lang_koKR='' WHERE ID=2314;
UPDATE dbc_areapoi SET Name_Lang_koKR='어둠의 무기고', Description_Lang_koKR='' WHERE ID=2139;
UPDATE dbc_areapoi SET Name_Lang_koKR='우누페', Description_Lang_koKR='' WHERE ID=2305;
UPDATE dbc_areapoi SET Name_Lang_koKR='발가드', Description_Lang_koKR='' WHERE ID=2086;
UPDATE dbc_areapoi SET Name_Lang_koKR='용맹의 성채', Description_Lang_koKR='' WHERE ID=2303;
UPDATE dbc_areapoi SET Name_Lang_koKR='복수의 상륙지', Description_Lang_koKR='' WHERE ID=2087;
UPDATE dbc_areapoi SET Name_Lang_koKR='원한의 초소', Description_Lang_koKR='' WHERE ID=2299;
UPDATE dbc_areapoi SET Name_Lang_koKR='전쟁노래부족 요새', Description_Lang_koKR='' WHERE ID=2304;
UPDATE dbc_areapoi SET Name_Lang_koKR='서부 몰락지대 여단 야영지', Description_Lang_koKR='' WHERE ID=2313;
UPDATE dbc_areapoi SET Name_Lang_koKR='서부경비대 성채', Description_Lang_koKR='' WHERE ID=2084;
UPDATE dbc_areapoi SET Name_Lang_koKR='서부불꽃 차량 작업장', Description_Lang_koKR='' WHERE ID=2152;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울 칼날 경비탑', Description_Lang_koKR='' WHERE ID=2142;
UPDATE dbc_areapoi SET Name_Lang_koKR='윈터가드 성채', Description_Lang_koKR='' WHERE ID=2309;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 호수', Description_Lang_koKR='겨울손아귀 호수 점령' WHERE ID=2264;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새', Description_Lang_koKR='' WHERE ID=2246;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 관문', Description_Lang_koKR='' WHERE ID=2229;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 북동쪽 경비탑', Description_Lang_koKR='' WHERE ID=2146;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 북서쪽 경비탑', Description_Lang_koKR='' WHERE ID=2147;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 남동쪽 경비탑', Description_Lang_koKR='' WHERE ID=2145;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 남서쪽 경비탑', Description_Lang_koKR='' WHERE ID=2144;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2222;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2223;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2224;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2225;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2226;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2227;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2228;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2230;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2231;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2232;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2233;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2234;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2235;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2236;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2237;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2238;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2239;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2240;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2241;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2242;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2243;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2244;
UPDATE dbc_areapoi SET Name_Lang_koKR='겨울손아귀 요새 성벽', Description_Lang_koKR='' WHERE ID=2245;
UPDATE dbc_areapoi SET Name_Lang_koKR='고룡쉼터 사원', Description_Lang_koKR='' WHERE ID=2298;
UPDATE dbc_areapoi SET Name_Lang_koKR='짐토르가', Description_Lang_koKR='' WHERE ID=2315;
UPDATE dbc_areapoi SET Name_Lang_koKR='장로의 광장 관문', Description_Lang_koKR='장로의 광장 관문' WHERE ID=2106;
UPDATE dbc_areapoi SET Name_Lang_koKR='축제의 거리 관문', Description_Lang_koKR='축제의 거리 관문' WHERE ID=2107;
UPDATE dbc_areapoi SET Name_Lang_koKR='왕의 광장 분수대', Description_Lang_koKR='왕의 광장 분수대' WHERE ID=2109;
UPDATE dbc_areapoi SET Name_Lang_koKR='상가 관문', Description_Lang_koKR='상가 관문' WHERE ID=2108;
UPDATE dbc_areapoi SET Name_Lang_koKR='마을 회관', Description_Lang_koKR='마을 회관' WHERE ID=2105;
UPDATE dbc_areapoi SET Name_Lang_koKR='불길의 탑', Description_Lang_koKR='미미론의 불지옥에 힘을 불어넣습니다.' WHERE ID=2332;
UPDATE dbc_areapoi SET Name_Lang_koKR='서리의 탑', Description_Lang_koKR='호디르의 격노에 힘을 불어넣습니다.' WHERE ID=2333;
UPDATE dbc_areapoi SET Name_Lang_koKR='생명의 탑', Description_Lang_koKR='프레이야의 수호물에 힘을 불어넣습니다.' WHERE ID=2331;
UPDATE dbc_areapoi SET Name_Lang_koKR='폭풍의 탑', Description_Lang_koKR='토림의 망치에 힘을 불어넣습니다.' WHERE ID=2334;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼라이언스 수비', Description_Lang_koKR='' WHERE ID=2128;
UPDATE dbc_areapoi SET Name_Lang_koKR='고대 유물의 방', Description_Lang_koKR='' WHERE ID=2292;
UPDATE dbc_areapoi SET Name_Lang_koKR='동부 무덤', Description_Lang_koKR='호드 점령지' WHERE ID=2129;
UPDATE dbc_areapoi SET Name_Lang_koKR='동부 무덤', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=2130;
UPDATE dbc_areapoi SET Name_Lang_koKR='푸른 사파이어 관문', Description_Lang_koKR='' WHERE ID=2117;
UPDATE dbc_areapoi SET Name_Lang_koKR='초록 에메랄드 관문', Description_Lang_koKR='' WHERE ID=2120;
UPDATE dbc_areapoi SET Name_Lang_koKR='보라 자수정 관문', Description_Lang_koKR='' WHERE ID=2111;
UPDATE dbc_areapoi SET Name_Lang_koKR='붉은 태양 관문', Description_Lang_koKR='' WHERE ID=2114;
UPDATE dbc_areapoi SET Name_Lang_koKR='노란 달 관문', Description_Lang_koKR='' WHERE ID=2135;
UPDATE dbc_areapoi SET Name_Lang_koKR='호드 수비', Description_Lang_koKR='' WHERE ID=2127;
UPDATE dbc_areapoi SET Name_Lang_koKR='남부 무덤', Description_Lang_koKR='호드 점령지' WHERE ID=2133;
UPDATE dbc_areapoi SET Name_Lang_koKR='남부 무덤', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=2134;
UPDATE dbc_areapoi SET Name_Lang_koKR='역병인도자호', Description_Lang_koKR='호드 군대' WHERE ID=2125;
UPDATE dbc_areapoi SET Name_Lang_koKR='죽음의 운반자호', Description_Lang_koKR='호드 군대' WHERE ID=2126;
UPDATE dbc_areapoi SET Name_Lang_koKR='서리파괴자호', Description_Lang_koKR='얼라이언스 군대' WHERE ID=2123;
UPDATE dbc_areapoi SET Name_Lang_koKR='자비의 여신호', Description_Lang_koKR='얼라이언스 군대' WHERE ID=2124;
UPDATE dbc_areapoi SET Name_Lang_koKR='서부 무덤', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=2132;
UPDATE dbc_areapoi SET Name_Lang_koKR='서부 무덤', Description_Lang_koKR='호드 점령지' WHERE ID=2324;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼라이언스 관문', Description_Lang_koKR='동문' WHERE ID=2377;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼라이언스 관문', Description_Lang_koKR='파괴됨' WHERE ID=2378;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼라이언스 관문', Description_Lang_koKR='파괴됨' WHERE ID=2379;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼라이언스 관문', Description_Lang_koKR='서문' WHERE ID=2380;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼라이언스 관문', Description_Lang_koKR='파괴됨' WHERE ID=2381;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼라이언스 관문', Description_Lang_koKR='정문' WHERE ID=2382;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼라이언스 요새', Description_Lang_koKR='미점령 지역' WHERE ID=2383;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼라이언스 요새', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=2384;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼라이언스 요새', Description_Lang_koKR='분쟁 지역' WHERE ID=2385;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼라이언스 요새', Description_Lang_koKR='분쟁 지역' WHERE ID=2386;
UPDATE dbc_areapoi SET Name_Lang_koKR='얼라이언스 요새', Description_Lang_koKR='호드 점령지' WHERE ID=2387;
UPDATE dbc_areapoi SET Name_Lang_koKR='부두', Description_Lang_koKR='분쟁 지역' WHERE ID=2356;
UPDATE dbc_areapoi SET Name_Lang_koKR='부두', Description_Lang_koKR='호드 점령지' WHERE ID=2357;
UPDATE dbc_areapoi SET Name_Lang_koKR='부두', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=2358;
UPDATE dbc_areapoi SET Name_Lang_koKR='부두', Description_Lang_koKR='분쟁 지역' WHERE ID=2359;
UPDATE dbc_areapoi SET Name_Lang_koKR='부두', Description_Lang_koKR='미점령 지역' WHERE ID=2360;
UPDATE dbc_areapoi SET Name_Lang_koKR='격납고', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=2350;
UPDATE dbc_areapoi SET Name_Lang_koKR='격납고', Description_Lang_koKR='호드 점령지' WHERE ID=2352;
UPDATE dbc_areapoi SET Name_Lang_koKR='격납고', Description_Lang_koKR='분쟁 지역' WHERE ID=2353;
UPDATE dbc_areapoi SET Name_Lang_koKR='격납고', Description_Lang_koKR='분쟁 지역' WHERE ID=2354;
UPDATE dbc_areapoi SET Name_Lang_koKR='격납고', Description_Lang_koKR='미점령 지역' WHERE ID=2355;
UPDATE dbc_areapoi SET Name_Lang_koKR='호드 관문', Description_Lang_koKR='정문' WHERE ID=2371;
UPDATE dbc_areapoi SET Name_Lang_koKR='호드 관문', Description_Lang_koKR='파괴됨' WHERE ID=2372;
UPDATE dbc_areapoi SET Name_Lang_koKR='호드 관문', Description_Lang_koKR='동문' WHERE ID=2373;
UPDATE dbc_areapoi SET Name_Lang_koKR='호드 관문', Description_Lang_koKR='파괴됨' WHERE ID=2374;
UPDATE dbc_areapoi SET Name_Lang_koKR='호드 관문', Description_Lang_koKR='서문' WHERE ID=2375;
UPDATE dbc_areapoi SET Name_Lang_koKR='호드 관문', Description_Lang_koKR='파괴됨' WHERE ID=2376;
UPDATE dbc_areapoi SET Name_Lang_koKR='호드 요새', Description_Lang_koKR='호드 점령지' WHERE ID=2388;
UPDATE dbc_areapoi SET Name_Lang_koKR='호드 요새', Description_Lang_koKR='호드 점령지' WHERE ID=2389;
UPDATE dbc_areapoi SET Name_Lang_koKR='호드 요새', Description_Lang_koKR='분쟁 지역' WHERE ID=2390;
UPDATE dbc_areapoi SET Name_Lang_koKR='호드 요새', Description_Lang_koKR='분쟁 지역' WHERE ID=2391;
UPDATE dbc_areapoi SET Name_Lang_koKR='호드 요새', Description_Lang_koKR='미점령 지역' WHERE ID=2392;
UPDATE dbc_areapoi SET Name_Lang_koKR='채석장', Description_Lang_koKR='미점령 지역' WHERE ID=2361;
UPDATE dbc_areapoi SET Name_Lang_koKR='채석장', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=2362;
UPDATE dbc_areapoi SET Name_Lang_koKR='채석장', Description_Lang_koKR='호드 점령지' WHERE ID=2363;
UPDATE dbc_areapoi SET Name_Lang_koKR='채석장', Description_Lang_koKR='분쟁 지역' WHERE ID=2364;
UPDATE dbc_areapoi SET Name_Lang_koKR='채석장', Description_Lang_koKR='분쟁 지역' WHERE ID=2365;
UPDATE dbc_areapoi SET Name_Lang_koKR='정제소', Description_Lang_koKR='호드 점령지' WHERE ID=2366;
UPDATE dbc_areapoi SET Name_Lang_koKR='정제소', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=2367;
UPDATE dbc_areapoi SET Name_Lang_koKR='정제소', Description_Lang_koKR='분쟁 지역' WHERE ID=2368;
UPDATE dbc_areapoi SET Name_Lang_koKR='정제소', Description_Lang_koKR='분쟁 지역' WHERE ID=2369;
UPDATE dbc_areapoi SET Name_Lang_koKR='정제소', Description_Lang_koKR='미점령 지역' WHERE ID=2370;
UPDATE dbc_areapoi SET Name_Lang_koKR='작업장', Description_Lang_koKR='얼라이언스 점령지' WHERE ID=2345;
UPDATE dbc_areapoi SET Name_Lang_koKR='작업장', Description_Lang_koKR='호드 점령지' WHERE ID=2346;
UPDATE dbc_areapoi SET Name_Lang_koKR='작업장', Description_Lang_koKR='분쟁 지역' WHERE ID=2347;
UPDATE dbc_areapoi SET Name_Lang_koKR='작업장', Description_Lang_koKR='분쟁 지역' WHERE ID=2348;
UPDATE dbc_areapoi SET Name_Lang_koKR='작업장', Description_Lang_koKR='미점령 지역' WHERE ID=2349;
