UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='스톰윈드' WHERE ID=1;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='붉은마루 산맥' WHERE ID=2;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='그늘숲 - 다크샤이어' WHERE ID=3;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='서부 몰락지대 - 감시의 언덕' WHERE ID=4;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='던 모로' WHERE ID=5;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='모단 호수 - 텔사마' WHERE ID=6;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='저습지 - 크로스로드' WHERE ID=7;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황야의 땅 - 북동쪽 무덤' WHERE ID=8;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='불모의 땅 - 크로스로드' WHERE ID=10;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='잊혀진 땅, 에텔 레소르' WHERE ID=31;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='듀로타 - 칼바위 언덕' WHERE ID=32;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='듀로타 - 오그리마' WHERE ID=33;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='멀고어 - 붉은구름 고원' WHERE ID=34;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠의 해안 - 아우버다인' WHERE ID=35;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='죽음의 고개 - 모건의 터' WHERE ID=36;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='버섯구름 봉우리 - 구름 승강장' WHERE ID=39;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='설원 (호드 시작지점)' WHERE ID=49;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='실리더스 - 용사의 안식처' WHERE ID=70;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='멀고어 - 블러드후프 마을' WHERE ID=89;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='텔드랏실 - 다르나서스' WHERE ID=90;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='텔드랏실 - 돌라나르' WHERE ID=91;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='잿빛 골짜기 - 아스트라나르' WHERE ID=92;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='텔드랏실 - 알드랏실' WHERE ID=93;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='티리스팔 숲 - 데스넬' WHERE ID=94;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='티리스팔 숲 - 언더시티' WHERE ID=96;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='은빛소나무 숲 - 공동묘지' WHERE ID=97;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='힐스브래드 구릉지 - 타렌 밀농장' WHERE ID=98;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아라시 고원, 동부 길' WHERE ID=99;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='던 모로 - 앤빌마' WHERE ID=100;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='던 모로 - 카라노스' WHERE ID=101;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='던 모로 - 아이언포지' WHERE ID=102;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황야의 땅 - 카르가스' WHERE ID=103;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='붉은마루 산맥 - 레이크샤이어' WHERE ID=104;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='엘윈 숲 - 노스샤이어' WHERE ID=105;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='엘윈 숲 - 골드샤이어' WHERE ID=106;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='엘윈 숲 - 스톰윈드' WHERE ID=107;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='슬픔의 늪 - 스토나드' WHERE ID=108;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='가시덤불 골짜기 - 무법항' WHERE ID=109;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='텔드랏실 - 루테란 마을' WHERE ID=129;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='힐스브래드 구릉지 - 사우스쇼어' WHERE ID=149;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='알터랙 계곡 (눈사태 무덤) 중' WHERE ID=169;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='먼지진흙 습지대 - 테라모어 섬' WHERE ID=189;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='타나리스 - 가젯잔' WHERE ID=209;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='불모의 땅 - 타우라조 야영지' WHERE ID=229;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='불모의 땅 - 톱니항' WHERE ID=249;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='설원 (얼라이언스 시작지점)' WHERE ID=269;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='티리스팔 숲 - 브릴' WHERE ID=289;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='페랄라스 - 페더문 요새' WHERE ID=309;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='페랄라스 - 모자케 야영지' WHERE ID=310;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='버섯구름 봉우리 - 소금평원' WHERE ID=329;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='동부 내륙지 - 맹금의 봉우리' WHERE ID=349;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아즈샤라 - 탈렌드리스 초소' WHERE ID=369;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='저주받은 땅 - 네더가드 요새' WHERE ID=370;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='가시덤불 골짜기 - 가시덤불 골짜기 북부' WHERE ID=389;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='돌발톱 산맥 - 그물누비 고개' WHERE ID=409;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='티리스팔 숲 - 파올의 안식처' WHERE ID=429;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='악령의 숲 - 모를로스아란' WHERE ID=449;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='운고로 분화구 - 늪지대' WHERE ID=450;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠의 해안 - 황혼의 계곡' WHERE ID=469;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='저습지 - 바라딘 만' WHERE ID=489;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='서부 역병지대 - 서리바람 야영지' WHERE ID=509;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='동부 역병지대, 전염의 흉터' WHERE ID=510;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='여명의 설원 - 눈망루 마을' WHERE ID=511;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='잿빛 골짜기 - 카르가시아' WHERE ID=512;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='프로그래머의 섬' WHERE ID=529;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='프로그래머의 섬' WHERE ID=549;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='서부 역병지대 - 보루' WHERE ID=569;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='GM의 안식처' WHERE ID=589;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아즈샤라 - 남녘마루 해안' WHERE ID=609;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='알터랙 계곡 (호드 진영)' WHERE ID=610;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='알터랙 계곡 (얼라이언스 진영)' WHERE ID=611;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='GM 클라이언트 시험용' WHERE ID=629;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아즈샤라 - 레가쉬 야영지' WHERE ID=630;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='먼지진흙 습지대 - 담쟁이 마을' WHERE ID=631;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='달의 숲' WHERE ID=633;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='동부 역병지대 - 다로우샤이어' WHERE ID=634;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='악령의 숲 - 강철나무 숲' WHERE ID=635;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='이글거리는 협곡 - 토륨 조합 거점' WHERE ID=636;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='듀로타 - 센진 마을' WHERE ID=649;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='프로그래머의 섬 - 버클러 묘지 2' WHERE ID=669;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='프로그래머의 섬 - 버클러 묘지 1' WHERE ID=670;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='프로그래머의 섬 - 버클러 묘지 3' WHERE ID=671;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='알터랙 계곡 (스톰파이크 묘지) 상' WHERE ID=689;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='알터랙 계곡 (서리늑대 무덤) 하' WHERE ID=690;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='듀로타 - 시험의 골짜기' WHERE ID=709;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='알터랙 계곡 (얼라이언스 무덤)' WHERE ID=729;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='알터랙 계곡 (호드 무덤)' WHERE ID=749;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='알터랙 계곡 (서리늑대 구호막사)' WHERE ID=750;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='알터랙 계곡 (스톰파이크 보급기지)' WHERE ID=751;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='전쟁노래 협곡 - 얼라이언스 입구' WHERE ID=769;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='전쟁노래 협곡 - 호드 입구' WHERE ID=770;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='전쟁노래 협곡 - 얼라이언스 부활 위치' WHERE ID=771;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='전쟁노래 협곡 - 호드 부활 위치' WHERE ID=772;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='동부 내륙지 - 전망대 절벽' WHERE ID=789;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='전쟁노래 협곡 - 호드 출구' WHERE ID=809;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='전쟁노래 협곡 - 얼라이언스 출구' WHERE ID=810;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='알터랙 계곡 (얼라이언스 출구)' WHERE ID=829;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='알터랙 계곡 (호드 출구)' WHERE ID=830;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='페랄라스 - 혈투의 전장' WHERE ID=849;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='듀로타 - 듀로타 북부' WHERE ID=850;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='멀고어 - 썬더 블러프' WHERE ID=851;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='던 모로 - 아이언포지 관문' WHERE ID=852;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='티리스팔 숲 - 로데론의 폐허' WHERE ID=853;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='엘윈 숲 - 동부 벌목지' WHERE ID=854;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='서부 역병지대 - 카엘 다로우' WHERE ID=869;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아라시 분지 - 호드 입구' WHERE ID=889;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아라시 분지 - 얼라이언스 입구' WHERE ID=890;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아라시 분지 - 호드 출구' WHERE ID=891;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아라시 분지 - 얼라이언스 출구' WHERE ID=892;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아라시 분지 - 무덤 (농장)' WHERE ID=893;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아라시 분지 - 무덤 (대장간)' WHERE ID=894;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아라시 분지 - 무덤 (마구간)' WHERE ID=895;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아라시 분지 - 무덤 (금광)' WHERE ID=896;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아라시 분지 - 무덤 (제재소)' WHERE ID=897;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아라시 분지 - 무덤 (트롤베인 전당)' WHERE ID=898;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아라시 분지 - 무덤 (파멸의 전당)' WHERE ID=899;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='동부 역병지대 - 검은나무 호수' WHERE ID=909;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='실리더스 - 세나리온 요새' WHERE ID=910;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='그늘숲 - 까마귀 언덕' WHERE ID=911;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='영원노래 숲 - 선스트라이더 섬' WHERE ID=912;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='실리더스 - 스카라베 성벽 (안퀴라즈)' WHERE ID=913;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='영원노래 숲, 원정순찰대 산장 무덤' WHERE ID=914;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='유령의 땅, 트랜퀼리엔' WHERE ID=915;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='유령의 땅, 성소' WHERE ID=916;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='유령의 땅, 아마니 고개' WHERE ID=917;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='하늘안개 섬, 암멘 골짜기' WHERE ID=918;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 스랄마' WHERE ID=919;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 명예의 요새' WHERE ID=920;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='영원노래 숲, 실버문' WHERE ID=921;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='영원노래 숲, 산들바람 무덤' WHERE ID=922;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='하늘안개 섬, 하늘 감시초소 무덤' WHERE ID=923;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='하늘안개 섬, 너울소나무 무덤' WHERE ID=924;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='핏빛안개 숲, 핏빛 감시초소 무덤' WHERE ID=925;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='핏빛안개 숲, 평원 무덤' WHERE ID=926;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='동부 역병지대 - 산마루 경비탑 무덤' WHERE ID=927;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 자브라진 무덤' WHERE ID=928;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드 투기장, 팀 1 입구' WHERE ID=929;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, SE 무덤' WHERE ID=930;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='프로그래머의 섬' WHERE ID=931;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='프로그래머의 섬' WHERE ID=932;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 사원' WHERE ID=933;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 매의 감시초소' WHERE ID=934;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 004' WHERE ID=935;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드 투기장, 팀 2 입구' WHERE ID=936;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='Reuse' WHERE ID=937;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='알터랙 골짜기, 얼라이언스 출구' WHERE ID=938;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥 투기장, 팀1' WHERE ID=939;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥 투기장, 팀 2' WHERE ID=940;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시험용 무덤' WHERE ID=941;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 001' WHERE ID=942;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 002' WHERE ID=943;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 003' WHERE ID=944;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 005' WHERE ID=945;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 006' WHERE ID=946;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 007' WHERE ID=947;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 008' WHERE ID=948;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 009' WHERE ID=949;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 010' WHERE ID=950;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 011' WHERE ID=951;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 012' WHERE ID=952;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 013' WHERE ID=953;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 014' WHERE ID=954;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 015' WHERE ID=955;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 016' WHERE ID=956;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 017' WHERE ID=957;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 018' WHERE ID=958;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 019' WHERE ID=959;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 020' WHERE ID=960;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 021' WHERE ID=961;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 022' WHERE ID=962;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 023' WHERE ID=963;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 024' WHERE ID=964;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 025' WHERE ID=965;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 026' WHERE ID=966;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 027' WHERE ID=967;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 시체 거점 028' WHERE ID=968;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, PvP 무덤' WHERE ID=969;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 텔레도르GY' WHERE ID=970;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥 - PvP - 투기장 무덤' WHERE ID=971;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 006' WHERE ID=972;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 세나리온 무덤' WHERE ID=973;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 001' WHERE ID=974;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 002' WHERE ID=975;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 003' WHERE ID=976;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 004' WHERE ID=977;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 008' WHERE ID=978;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 005' WHERE ID=979;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 007' WHERE ID=980;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 009' WHERE ID=981;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 011' WHERE ID=982;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 010' WHERE ID=983;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 012' WHERE ID=984;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 013' WHERE ID=985;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 014' WHERE ID=986;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 016' WHERE ID=987;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 015' WHERE ID=988;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 017' WHERE ID=989;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 018' WHERE ID=990;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 시체 거점 019' WHERE ID=991;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, Northwind Cleft' WHERE ID=992;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 할라아 무덤' WHERE ID=993;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 샤트라스 무덤' WHERE ID=994;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 평원 무덤' WHERE ID=995;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='시험용 - 프로그래머' WHERE ID=996;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='시험용 - 프로그래머 001' WHERE ID=997;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드 - PvP - 투기장 무덤' WHERE ID=998;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 시체 거점 001' WHERE ID=999;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 시체 거점 002' WHERE ID=1000;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 시체 거점 003' WHERE ID=1001;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 시체 거점 004' WHERE ID=1002;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 시체 거점 005' WHERE ID=1003;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 시체 거점 006' WHERE ID=1004;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 시체 거점 007' WHERE ID=1005;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 시체 거점 008' WHERE ID=1006;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 시체 거점 009' WHERE ID=1007;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 시체 거점 010' WHERE ID=1008;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 시체 거점 011' WHERE ID=1009;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 시체 거점 012' WHERE ID=1010;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 시체 거점 013' WHERE ID=1011;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 시체 거점 014' WHERE ID=1012;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 001' WHERE ID=1013;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 002' WHERE ID=1014;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 003' WHERE ID=1015;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 004' WHERE ID=1016;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 005' WHERE ID=1017;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 006' WHERE ID=1018;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 007' WHERE ID=1019;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 008' WHERE ID=1020;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 009' WHERE ID=1021;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 010' WHERE ID=1022;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 011' WHERE ID=1023;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 001' WHERE ID=1024;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 002' WHERE ID=1025;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 003' WHERE ID=1026;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 004' WHERE ID=1027;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 016' WHERE ID=1028;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 017' WHERE ID=1029;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 018' WHERE ID=1030;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 019' WHERE ID=1031;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 020' WHERE ID=1032;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 021' WHERE ID=1033;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 022' WHERE ID=1034;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 시체 거점 023' WHERE ID=1035;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='Reuse' WHERE ID=1036;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 차원문 고원' WHERE ID=1037;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, 정령의 고원' WHERE ID=1038;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='나그란드, SW 무덤' WHERE ID=1039;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 킬제덴의 옥좌' WHERE ID=1040;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도, 어둠의 문' WHERE ID=1041;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 해골 무덤 무덤' WHERE ID=1042;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 오레보르 피난처 무덤' WHERE ID=1043;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='장가르 습지대, 스포어가르GY' WHERE ID=1044;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍, 폭풍 첨탑 무덤' WHERE ID=1045;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍, 52번 구역 무덤' WHERE ID=1046;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 어둠달 마을 무덤' WHERE ID=1047;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 와일드해머 무덤' WHERE ID=1048;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 실바나르 무덤' WHERE ID=1049;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 천둥군주 무덤' WHERE ID=1050;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 스케티스 무덤' WHERE ID=1051;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 005' WHERE ID=1052;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 006' WHERE ID=1053;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 007' WHERE ID=1054;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 008' WHERE ID=1055;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 009' WHERE ID=1056;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 010' WHERE ID=1057;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 011' WHERE ID=1058;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 012' WHERE ID=1059;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 013' WHERE ID=1060;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 014' WHERE ID=1061;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 015' WHERE ID=1062;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 016' WHERE ID=1063;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 017' WHERE ID=1064;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 018' WHERE ID=1065;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 019' WHERE ID=1066;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 020' WHERE ID=1067;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 021' WHERE ID=1068;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 022' WHERE ID=1069;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 023' WHERE ID=1070;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기, 시체 거점 024' WHERE ID=1071;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 000' WHERE ID=1072;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 001' WHERE ID=1073;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 002' WHERE ID=1074;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 003' WHERE ID=1075;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 004' WHERE ID=1076;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 005' WHERE ID=1077;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 006' WHERE ID=1078;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 007' WHERE ID=1079;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 008' WHERE ID=1080;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 009' WHERE ID=1081;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 010' WHERE ID=1082;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 011' WHERE ID=1083;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 012' WHERE ID=1084;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 013' WHERE ID=1085;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 014' WHERE ID=1086;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 015' WHERE ID=1087;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 016' WHERE ID=1088;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 017' WHERE ID=1089;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 018' WHERE ID=1090;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 019' WHERE ID=1091;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 020' WHERE ID=1092;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 021' WHERE ID=1093;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 022' WHERE ID=1094;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 023' WHERE ID=1095;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 024' WHERE ID=1096;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 025' WHERE ID=1097;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 026' WHERE ID=1098;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 027' WHERE ID=1099;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 028' WHERE ID=1100;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 029' WHERE ID=1101;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥, 시체 거점 030' WHERE ID=1102;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 무덤 (얼라이언스 시작지)' WHERE ID=1103;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 무덤 (호드 시작지점)' WHERE ID=1104;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 무덤 (Felreaver)' WHERE ID=1105;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 무덤 (BE 탑)' WHERE ID=1106;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 무덤 (드레나이 탑)' WHERE ID=1107;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 무덤 (인간 감시탑)' WHERE ID=1108;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 000' WHERE ID=1109;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 001' WHERE ID=1110;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 002' WHERE ID=1111;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 003' WHERE ID=1112;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 004' WHERE ID=1113;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 005' WHERE ID=1114;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 006' WHERE ID=1115;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 007' WHERE ID=1116;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 008' WHERE ID=1117;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 009' WHERE ID=1118;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 010' WHERE ID=1119;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 011' WHERE ID=1120;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 012' WHERE ID=1121;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 013' WHERE ID=1122;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 014' WHERE ID=1123;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 015' WHERE ID=1124;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 016' WHERE ID=1125;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 017' WHERE ID=1126;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 018' WHERE ID=1127;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 019' WHERE ID=1128;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 020' WHERE ID=1129;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 021' WHERE ID=1130;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 022' WHERE ID=1131;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 023' WHERE ID=1132;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 BG - 시체 거점 024' WHERE ID=1133;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 000' WHERE ID=1134;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 001' WHERE ID=1135;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 002' WHERE ID=1136;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 003' WHERE ID=1137;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 004' WHERE ID=1138;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 005' WHERE ID=1139;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 006' WHERE ID=1140;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 007' WHERE ID=1141;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 008' WHERE ID=1142;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 009' WHERE ID=1143;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 010' WHERE ID=1144;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 011' WHERE ID=1145;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 012' WHERE ID=1146;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 013' WHERE ID=1147;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 014' WHERE ID=1148;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 015' WHERE ID=1149;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 016' WHERE ID=1150;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 017' WHERE ID=1151;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 018' WHERE ID=1152;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 019' WHERE ID=1153;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 020' WHERE ID=1154;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 021' WHERE ID=1155;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 022' WHERE ID=1156;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 023' WHERE ID=1157;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 024' WHERE ID=1158;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 025' WHERE ID=1159;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 026' WHERE ID=1160;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 027' WHERE ID=1161;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 028' WHERE ID=1162;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 029' WHERE ID=1163;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 030' WHERE ID=1164;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 031' WHERE ID=1165;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 032' WHERE ID=1166;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 033' WHERE ID=1167;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 034' WHERE ID=1168;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 035' WHERE ID=1169;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 036' WHERE ID=1170;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 037' WHERE ID=1171;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 038' WHERE ID=1172;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 039' WHERE ID=1173;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 040' WHERE ID=1174;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 041' WHERE ID=1175;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 042' WHERE ID=1176;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 043' WHERE ID=1177;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 044' WHERE ID=1178;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 045' WHERE ID=1179;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 046' WHERE ID=1180;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 047' WHERE ID=1181;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 048' WHERE ID=1182;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 049' WHERE ID=1183;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 050' WHERE ID=1184;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 051' WHERE ID=1185;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 052' WHERE ID=1186;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 053' WHERE ID=1187;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 054' WHERE ID=1188;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 055' WHERE ID=1189;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 056' WHERE ID=1190;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 057' WHERE ID=1191;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 058' WHERE ID=1192;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 059' WHERE ID=1193;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 060' WHERE ID=1194;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 061' WHERE ID=1195;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 062' WHERE ID=1196;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 063' WHERE ID=1197;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 064' WHERE ID=1198;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 065' WHERE ID=1199;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 066' WHERE ID=1200;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 067' WHERE ID=1201;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 068' WHERE ID=1202;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 069' WHERE ID=1203;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 070' WHERE ID=1204;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 071' WHERE ID=1205;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 072' WHERE ID=1206;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 073' WHERE ID=1207;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 074' WHERE ID=1208;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 075' WHERE ID=1209;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 076' WHERE ID=1210;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 077' WHERE ID=1211;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 078' WHERE ID=1212;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 079' WHERE ID=1213;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 080' WHERE ID=1214;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 081' WHERE ID=1215;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 082' WHERE ID=1216;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 083' WHERE ID=1217;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 084' WHERE ID=1218;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 085' WHERE ID=1219;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 086' WHERE ID=1220;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 087' WHERE ID=1221;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 088' WHERE ID=1222;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 089' WHERE ID=1223;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 090' WHERE ID=1224;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 091' WHERE ID=1225;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 092' WHERE ID=1226;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 093' WHERE ID=1227;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 094' WHERE ID=1228;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 095' WHERE ID=1229;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 096' WHERE ID=1230;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 097' WHERE ID=1231;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 098' WHERE ID=1232;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 099' WHERE ID=1233;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 100' WHERE ID=1234;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 101' WHERE ID=1235;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 102' WHERE ID=1236;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 103' WHERE ID=1237;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 104' WHERE ID=1238;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 - 시체 수집 지점 105' WHERE ID=1239;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도 (얼라이언스 교두보 거점)' WHERE ID=1240;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥 (영원의 숲 무덤)' WHERE ID=1241;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥 (북쪽 마루 무덤)' WHERE ID=1242;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥 (서쪽 마루 무덤)' WHERE ID=1243;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥 (동쪽 마루 무덤)' WHERE ID=1244;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='얼음왕관 전장 - 호드 진입' WHERE ID=1245;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='알터랙 계곡 (얼라이언스 출구)' WHERE ID=1246;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 (코스모렌치 무덤)' WHERE ID=1247;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='지옥불 반도 (해골망치 무덤)' WHERE ID=1248;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='타나리스 (시간의 동굴)' WHERE ID=1249;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기 (제단 무덤)' WHERE ID=1250;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='어둠달 골짜기 (성소 무덤)' WHERE ID=1251;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황천의 폭풍 (키린바르 무덤)' WHERE ID=1252;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥 (토쉴리의 연구기지 무덤)' WHERE ID=1253;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥 (까마귀 숲 무덤)' WHERE ID=1254;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥 (북동쪽 마루 무덤)' WHERE ID=1255;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='은빛소나무 숲 (남쪽 무덤)' WHERE ID=1256;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲 (오우거 무덤)' WHERE ID=1257;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='로데론 (PVP - 팀 1 시작점)' WHERE ID=1258;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='로데론 (PVP - 팀 2 시작점)' WHERE ID=1259;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='로데론 (PVP - 무덤)' WHERE ID=1260;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='검은 사원 (얼라이언스 무덤)' WHERE ID=1261;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='검은 사원 (호드 무덤)' WHERE ID=1262;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칼날 산맥 (시체 거점 031)' WHERE ID=1263;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='먼지진흙 습지대 (타베사의 농장 무덤)' WHERE ID=1264;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='먼지진흙 습지대 (진흙톱니 거점 무덤)' WHERE ID=1265;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울부짖는 협만 (북서쪽 무덤)' WHERE ID=1266;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울부짖는 협만 (투스카르 무덤)' WHERE ID=1267;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울부짖는 협만 (섬 무덤)' WHERE ID=1268;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울부짖는 협만 (중앙 무덤)' WHERE ID=1269;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울부짖는 협만 (북쪽 무덤)' WHERE ID=1270;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울부짖는 협만 (복수의 상륙지 무덤)' WHERE ID=1271;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울부짖는 협만 (남동쪽 무덤)' WHERE ID=1272;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울부짖는 협만 (남쪽 해안 무덤)' WHERE ID=1273;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울부짖는 협만 (남쪽 무덤)' WHERE ID=1274;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울부짖는 협만 (발가드 무덤)' WHERE ID=1275;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울부짖는 협만 (북동쪽 무덤)' WHERE ID=1276;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='운고로 분화구, 중앙 무덤' WHERE ID=1277;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='운고로 분화구, 마샬의 야영지 무덤' WHERE ID=1278;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='돌발톱 산맥, 잿더미 계곡' WHERE ID=1279;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='돌발톱 산맥, 봉우리 무덤' WHERE ID=1280;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='타나리스, 해적단 무덤' WHERE ID=1281;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='타나리스, 중앙 무덤' WHERE ID=1282;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='여명의 설원, 남쪽 무덤' WHERE ID=1283;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='여명의 설원, 서쪽 무덤' WHERE ID=1284;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='겨울손아귀, 요새 (동쪽)' WHERE ID=1285;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='서부 역병지대, 중앙 무덤' WHERE ID=1286;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='이글거리는 협곡, 남동쪽 무덤' WHERE ID=1287;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='황야의 땅, 남쪽 무덤' WHERE ID=1288;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='불모의 땅, 남쪽 무덤' WHERE ID=1289;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='북풍의 땅 (투스카르 무덤)' WHERE ID=1290;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 서슬가시 언덕 무덤' WHERE ID=1291;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='쿠엘다나스 섬, 집결지 무덤' WHERE ID=1292;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='쿠엘다나스 섬, 집결지 무덤' WHERE ID=1293;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='쿠엘다나스 섬 (집결지 무덤)' WHERE ID=1294;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='진화의 대지 (테레사 무덤 시험용)' WHERE ID=1295;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='진화의 대지 (테레사 무덤 시험용)' WHERE ID=1296;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='진화의 대지 (테레사 무덤 시험용)' WHERE ID=1297;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='테로카르 숲, 조룬 호수 무덤' WHERE ID=1298;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='얼음왕관 전장 - 얼라이언스 진입' WHERE ID=1299;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='회색 구릉지 (썩은수렵 무덤)' WHERE ID=1300;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='회색 구릉지 (호박빛소나무 무덤)' WHERE ID=1301;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='회색 구릉지 (서부 몰락지대 무덤)' WHERE ID=1302;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='회색 구릉지 (동쪽 무덤)' WHERE ID=1303;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='회색 구릉지 (북서쪽 무덤)' WHERE ID=1304;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='회색 구릉지 (남서쪽 무덤)' WHERE ID=1305;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='회색 구릉지 (중앙 무덤)' WHERE ID=1306;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='용의 안식처 (북동쪽 무덤)' WHERE ID=1307;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='용의 안식처 (윈터가드 무덤)' WHERE ID=1308;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='용의 안식처 (포세이큰 동쪽 무덤)' WHERE ID=1309;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='용의 안식처 (아그마르의 망치 무덤)' WHERE ID=1310;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='용의 안식처 (별의 쉼터 무덤)' WHERE ID=1311;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='용의 안식처 (모아키 항구 무덤)' WHERE ID=1312;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='용의 안식처 (북풍의 땅 경계 무덤)' WHERE ID=1313;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='용의 안식처 (고룡쉼터 사원 무덤)' WHERE ID=1314;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='용의 안식처 (분노의 관문 호드 무덤)' WHERE ID=1315;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='용의 안식처 (분노의 관문 얼라이언스 무덤)' WHERE ID=1316;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='북풍의 땅 (전쟁노래부족 요새 무덤)' WHERE ID=1317;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='북풍의 땅 (채찍파도 무덤)' WHERE ID=1318;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='북풍의 땅 (콜다라 무덤)' WHERE ID=1319;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='북풍의 땅 (호박석 절벽 무덤)' WHERE ID=1320;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='북풍의 땅 (피즈크랭크 무덤)' WHERE ID=1321;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='북풍의 땅 (보르고로크 무덤)' WHERE ID=1322;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='북풍의 땅 (죽음의 언덕 무덤)' WHERE ID=1323;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='북풍의 땅 (타운카르 마을 무덤)' WHERE ID=1324;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='북풍의 땅 (메아리 해안 무덤)' WHERE ID=1325;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='북풍의 땅 (용맹의 성채 무덤)' WHERE ID=1326;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='알터랙 계곡' WHERE ID=1327;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='겨울손아귀 (서쪽 성채)' WHERE ID=1328;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='겨울손아귀, 공성 공장 (방어 북동쪽)' WHERE ID=1329;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='겨울손아귀, 공성 공장 (방어 북서쪽)' WHERE ID=1330;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='겨울손아귀, 호드 시작 지역' WHERE ID=1331;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='겨울손아귀, 얼라이언스 시작 지역' WHERE ID=1332;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='겨울손아귀, 공성 공장 (남동쪽)' WHERE ID=1333;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='겨울손아귀, 공성 공장 (남서쪽)' WHERE ID=1334;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='숄라자르 분지 (남쪽 무덤)' WHERE ID=1336;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울부짖는 협만 (우트가드 무덤)' WHERE ID=1337;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울부짖는 협만 (네싱워리 무덤)' WHERE ID=1341;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='숄라자르 분지 (중앙 무덤)' WHERE ID=1342;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='숄라자르 분지 (북서쪽 무덤)' WHERE ID=1343;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='숄라자르 분지 (북동쪽 무덤)' WHERE ID=1344;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='숄라자르 분지 (동쪽 무덤)' WHERE ID=1345;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='노스렌드 전장 - 통제 상태 - 남쪽' WHERE ID=1346;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='노스렌드 전장 - 통제 상태 - 남서쪽' WHERE ID=1347;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='노스렌드 전장 - 통제 상태 - 중앙' WHERE ID=1348;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='노스렌드 전장 - 수호자 - 마지막' WHERE ID=1349;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='노스렌드 전장 - 공격자 - 해안' WHERE ID=1350;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='노스렌드 전장 - 공격자 - 배' WHERE ID=1351;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='줄드락 (서쪽 무덤)' WHERE ID=1352;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='줄드락 (북서쪽 무덤)' WHERE ID=1353;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='줄드락 (남서쪽 무덤)' WHERE ID=1354;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='줄드락 (남쪽 무덤)' WHERE ID=1355;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='줄드락 (중앙 무덤)' WHERE ID=1356;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='줄드락 (남동쪽 무덤)' WHERE ID=1357;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='줄드락 (군드락 무덤)' WHERE ID=1358;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='수정노래 숲 (달라란 무덤)' WHERE ID=1359;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칠흑의 요새 (제 1장 무덤)' WHERE ID=1360;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='달라란 투기장 (PvP 무덤)' WHERE ID=1361;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='달라란 투기장 (팀 1)' WHERE ID=1362;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='달라란 투기장 (팀 2)' WHERE ID=1363;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='오그리마 투기장 (팀 1)' WHERE ID=1364;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='오그리마 투기장 (팀 2)' WHERE ID=1365;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='오그리마 투기장 (무덤)' WHERE ID=1366;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울두란의 갯벌 (얼라이언스)' WHERE ID=1367;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울두란의 갯벌 (호드)' WHERE ID=1368;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='동부 역병지대 (칠흑의 요새 무덤)' WHERE ID=1369;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칠흑의 요새 (제 2, 3장 무덤)' WHERE ID=1370;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='칠흑의 요새 (제 4장 무덤)' WHERE ID=1371;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='운고로 분화구 (구체자의 정원)' WHERE ID=1372;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='먼지진흙 습지대 (테라모어)' WHERE ID=1373;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='듀로타 (오그리마)' WHERE ID=1374;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='스톰윈드 (스톰윈드)' WHERE ID=1375;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울부짖는 협만 (우트가드 무덤)' WHERE ID=1376;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='대해 (티리스팔)' WHERE ID=1377;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='듀로타 (오그리마)' WHERE ID=1378;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='숄라자르 분지 (폭풍장인 무덤)' WHERE ID=1379;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='수정노래 숲 (얼라이언스 무덤)' WHERE ID=1380;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='얼음왕관 (은빛십자군 선봉기지 무덤)' WHERE ID=1381;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='폭풍우 봉우리 (발키리온 무덤)' WHERE ID=1383;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='폭풍우 봉우리 (울두아르 무덤)' WHERE ID=1384;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='폭풍우 봉우리 (사원 동쪽 무덤)' WHERE ID=1385;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='폭풍우 봉우리 (사원 서쪽 무덤)' WHERE ID=1387;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='폭풍우 봉우리 (서리평원 무덤)' WHERE ID=1388;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='수정노래 숲 (서쪽 무덤)' WHERE ID=1391;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='수정노래 숲 (호드 무덤)' WHERE ID=1392;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='용의 안식처 (낙스라마스 무덤)' WHERE ID=1393;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='용의 안식처 (얼음안개 무덤)' WHERE ID=1394;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='얼음왕관 빙하 (채석장 무덤)' WHERE ID=1395;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='얼음왕관 빙하 (브리쿨 중앙 무덤)' WHERE ID=1396;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='얼음왕관 빙하 (노스렌드 얼음 무덤)' WHERE ID=1397;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='회색 구릉지 (드락타론 무덤)' WHERE ID=1398;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='노스렌드 전장 - 수호자 시작지' WHERE ID=1399;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='폭풍우 봉우리 (창조주의 신전 무덤)' WHERE ID=1400;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='폭풍우 봉우리 (눈더미 평원 무덤)' WHERE ID=1401;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='폭풍우 봉우리 (폭풍의 신전 무덤)' WHERE ID=1402;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='폭풍우 봉우리 (K3 무덤)' WHERE ID=1403;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='숄라자르 분지 (광란의 심장 무덤)' WHERE ID=1404;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='동부 역병지대: 아케루스' WHERE ID=1405;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='얼음왕관 빙하 (요툰하임 무덤)' WHERE ID=1407;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='폭풍우 봉우리 (눈봉우리 분지 무덤)' WHERE ID=1408;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='언더시티 (얼라이언스 분노의 관문)' WHERE ID=1409;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='AAAAA 이동 시험 장소' WHERE ID=1410;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='알터랙 산맥 (중앙 무덤)' WHERE ID=1411;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='여명의 설원, 눈호랑이 무덤' WHERE ID=1416;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='여명의 설원, 크로스로드 무덤' WHERE ID=1417;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='여명의 설원, 검은속삭임 무덤' WHERE ID=1418;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아즈샤라, 우르솔란' WHERE ID=1419;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아즈샤라, 쓸쓸한 마루' WHERE ID=1420;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='잊혀진 땅, 침묵의 초소' WHERE ID=1421;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='잊혀진 땅, 살데리스 해안' WHERE ID=1422;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='잊혀진 땅, 만노로크 소굴' WHERE ID=1423;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='잊혀진 땅, 마그람 마을' WHERE ID=1424;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='잊혀진 땅, 길가' WHERE ID=1425;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='잿빛 골짜기, 아에시나의 제단' WHERE ID=1426;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='잿빛 골짜기, 별빛노래' WHERE ID=1427;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='돌발톱 산맥, 칼바람 바위산' WHERE ID=1428;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='돌발톱 산맥, 땅거미 호수' WHERE ID=1429;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='불모의 땅, 잊혀진 웅덩이' WHERE ID=1430;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='불모의 땅, 북쪽 무덤' WHERE ID=1431;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='불모의 땅, 랩터 서식지' WHERE ID=1432;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='불모의 땅, 중앙 무덤' WHERE ID=1433;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='불모의 땅, 동쪽 무덤' WHERE ID=1434;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='멀고어, 남동쪽 무덤' WHERE ID=1435;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='멀고어, 붉은 바위 언덕' WHERE ID=1436;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='버섯구름 봉우리, 높새바람 봉우리' WHERE ID=1437;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='버섯구름 봉우리, 신기루 경주장' WHERE ID=1438;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='버섯구름 봉우리, 남서쪽 무덤' WHERE ID=1439;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='타나리스, 끝없는 사막' WHERE ID=1440;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='페랄라스, 이실디엔 폐허' WHERE ID=1441;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='페랄라스, 낮은벌' WHERE ID=1442;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='페랄라스, 쌍둥이 바위산' WHERE ID=1443;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='실리더스, 하이브레갈' WHERE ID=1444;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='실리더스, 황혼의 망치단 주둔지' WHERE ID=1445;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='아라시 고원, 스트롬가드' WHERE ID=1446;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='힐스브래드 구릉지, 소라딘의 성벽' WHERE ID=1447;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='동부 역병지대, 노스데일' WHERE ID=1448;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='동부 역병지대, 스트라솔름' WHERE ID=1449;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='동부 역병지대, 서쪽 무덤' WHERE ID=1450;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='서부 역병지대, 하스글렌' WHERE ID=1451;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='힐스브래드 구릉지, 힐스브래드 농장' WHERE ID=1452;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='동부 내륙지, 세라데인' WHERE ID=1453;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='동부 내륙지, 샤드라알로' WHERE ID=1454;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='저습지, 해몰이 늪' WHERE ID=1455;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='저습지, 남쪽 길' WHERE ID=1456;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='저습지, 랩터 마루' WHERE ID=1457;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='가시덤불 골짜기, 구루바시 투기장' WHERE ID=1458;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='가시덤불 골짜기, 중앙 무덤' WHERE ID=1459;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='가시덤불 골짜기, 폭풍 해안' WHERE ID=1460;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='그늘숲, 중앙 무덤' WHERE ID=1461;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='서부 몰락지대, 비수 언덕' WHERE ID=1462;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='서부 몰락지대, 기나긴 해안' WHERE ID=1463;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='저주받은 땅, 어둠의 문' WHERE ID=1464;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='슬픔의 늪, 눈물의 연못' WHERE ID=1465;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='슬픔의 늪, 부러진창 교차로' WHERE ID=1466;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='슬픔의 늪, 돌망루 요새' WHERE ID=1467;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='엘윈 숲, 아조라의 탑' WHERE ID=1468;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='불타는 평원, 검은바위 산' WHERE ID=1469;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='불타는 평원, 동쪽 무덤' WHERE ID=1470;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='던 모로, 얼음 호수' WHERE ID=1471;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='던 모로, 동쪽 길' WHERE ID=1472;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='모단 호수, 대호수' WHERE ID=1473;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='겨울손아귀, 요새 무덤(실내)' WHERE ID=1474;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='돌발톱 산맥, 남동쪽 무덤' WHERE ID=1476;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='용의 안식처, 수정 계곡 무덤' WHERE ID=1477;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='얼음왕관, 은빛십자군 마상시합 무덤' WHERE ID=1478;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='얼음왕관 전장 - 무덤 - 부두' WHERE ID=1480;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='얼음왕관 전장 - 무덤 - 비행장 무덤' WHERE ID=1481;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='얼음왕관 전장 - 무덤 - 작업장' WHERE ID=1482;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='얼음왕관 전장 - 얼라이언스 기본' WHERE ID=1483;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='얼음왕관 전장 - 무덤 - 호드 기본' WHERE ID=1484;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='얼음왕관 전장 - 무덤 - 얼라이언스 요새' WHERE ID=1485;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='얼음왕관 전장 - 무덤 - 호드 요새' WHERE ID=1486;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='불모의 땅, 명예의 감시탑' WHERE ID=1493;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='먼지진흙 습지대, 용의 둥지' WHERE ID=1681;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='얼음왕관 빙하, 성채 무덤' WHERE ID=1682;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='태양샘 - 쿠엘델라 입구' WHERE ID=1683;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='투기장 (개발팀 시험용)' WHERE ID=1691;
UPDATE dbc_worldsafelocs SET AreaName_Lang_koKR='울부짖는 협만 - 서릿날 무덤' WHERE ID=1720;
