UPDATE dbc_lfgdungeons SET Name_Lang_koKR='통곡의 동굴', Description_Lang_koKR='' WHERE ID=1;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='스칼로맨스', Description_Lang_koKR='' WHERE ID=2;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='성난불길 협곡', Description_Lang_koKR='' WHERE ID=4;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='죽음의 폐광', Description_Lang_koKR='' WHERE ID=6;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='그림자송곳니 성채', Description_Lang_koKR='' WHERE ID=8;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='검은심연의 나락', Description_Lang_koKR='' WHERE ID=10;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='스톰윈드 지하감옥', Description_Lang_koKR='' WHERE ID=12;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='놈리건', Description_Lang_koKR='' WHERE ID=14;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='가시덩굴 우리', Description_Lang_koKR='' WHERE ID=16;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='붉은십자군 수도원 - 묘지', Description_Lang_koKR='' WHERE ID=18;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='가시덩굴 구릉', Description_Lang_koKR='' WHERE ID=20;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='울다만', Description_Lang_koKR='' WHERE ID=22;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='줄파락', Description_Lang_koKR='' WHERE ID=24;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='마라우돈 - 주황색 수정', Description_Lang_koKR='' WHERE ID=26;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='가라앉은 사원', Description_Lang_koKR='' WHERE ID=28;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='검은바위 나락 - 감옥', Description_Lang_koKR='' WHERE ID=30;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='검은바위 첨탑 하층', Description_Lang_koKR='' WHERE ID=32;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='혈투의 전장 - 동부', Description_Lang_koKR='' WHERE ID=34;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='혈투의 전장 - 서부', Description_Lang_koKR='' WHERE ID=36;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='혈투의 전장 - 북부', Description_Lang_koKR='' WHERE ID=38;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='스트라솔름 - 정문', Description_Lang_koKR='' WHERE ID=40;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='지옥불 성루', Description_Lang_koKR='' WHERE ID=136;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='피의 용광로', Description_Lang_koKR='' WHERE ID=137;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='으스러진 손의 전당', Description_Lang_koKR='' WHERE ID=138;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='강제 노역소', Description_Lang_koKR='' WHERE ID=140;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='지하수렁', Description_Lang_koKR='' WHERE ID=146;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='증기 저장고', Description_Lang_koKR='' WHERE ID=147;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='마나 무덤', Description_Lang_koKR='' WHERE ID=148;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='아키나이 납골당', Description_Lang_koKR='' WHERE ID=149;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='세데크 전당', Description_Lang_koKR='' WHERE ID=150;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='어둠의 미궁', Description_Lang_koKR='' WHERE ID=151;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='붉은십자군 수도원 - 무기고', Description_Lang_koKR='' WHERE ID=163;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='붉은십자군 수도원 - 예배당', Description_Lang_koKR='' WHERE ID=164;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='붉은십자군 수도원 - 도서관', Description_Lang_koKR='' WHERE ID=165;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='던홀드 탈출', Description_Lang_koKR='' WHERE ID=170;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='검은늪', Description_Lang_koKR='' WHERE ID=171;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='메카나르', Description_Lang_koKR='' WHERE ID=172;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='신록의 정원', Description_Lang_koKR='' WHERE ID=173;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='알카트라즈', Description_Lang_koKR='' WHERE ID=174;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='마법학자의 정원', Description_Lang_koKR='' WHERE ID=198;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='우트가드 성채', Description_Lang_koKR='' WHERE ID=202;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='우트가드 첨탑', Description_Lang_koKR='' WHERE ID=203;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='아졸네룹', Description_Lang_koKR='' WHERE ID=204;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='마력의 눈', Description_Lang_koKR='' WHERE ID=206;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='번개의 전당', Description_Lang_koKR='' WHERE ID=207;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='돌의 전당', Description_Lang_koKR='' WHERE ID=208;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='옛 스트라솔름', Description_Lang_koKR='' WHERE ID=209;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='드락타론 성채', Description_Lang_koKR='' WHERE ID=214;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='군드락', Description_Lang_koKR='' WHERE ID=216;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='안카헤트: 고대 왕국', Description_Lang_koKR='' WHERE ID=218;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='보랏빛 요새', Description_Lang_koKR='' WHERE ID=220;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='마력의 탑', Description_Lang_koKR='' WHERE ID=225;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='용사의 시험장', Description_Lang_koKR='' WHERE ID=245;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='영혼의 제련소', Description_Lang_koKR='' WHERE ID=251;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='사론의 구덩이', Description_Lang_koKR='' WHERE ID=253;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='투영의 전당', Description_Lang_koKR='' WHERE ID=255;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='마라우돈 - 보라색 수정', Description_Lang_koKR='' WHERE ID=272;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='마라우돈 - 원시의 연못', Description_Lang_koKR='' WHERE ID=273;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='스트라솔름 - 공무용 입구', Description_Lang_koKR='' WHERE ID=274;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='검은바위 나락 - 상부 도시', Description_Lang_koKR='' WHERE ID=276;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='저주받은 기사', Description_Lang_koKR='아제로스 마을이 전부 불타버리기 전에 광기에 찬, 저주받은 기사를 물리쳐야 합니다.' WHERE ID=285;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='서리 군주 아훈', Description_Lang_koKR='서리 군주가 아제로스에 완전히 나타나 여름을 영원히 사라지게 하기 전에 처치해야 합니다.' WHERE ID=286;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='코렌 다이어브루', Description_Lang_koKR='질투심 많은 코렌 다이어브루를 처치하여 가을 축제 행사를 끊임없이 훼방하지 않도록 막아야 합니다.' WHERE ID=287;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='왕관화학회사', Description_Lang_koKR='왕관화학회사의 음흉한 언데드 연금술사들이 끔찍한 최신 역병을 퍼뜨리기 전에 처치해야 합니다.' WHERE ID=288;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='줄구룹', Description_Lang_koKR='' WHERE ID=42;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='검은바위 첨탑 상층', Description_Lang_koKR='' WHERE ID=44;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='오닉시아의 둥지', Description_Lang_koKR='' WHERE ID=46;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='화산 심장부', Description_Lang_koKR='' WHERE ID=48;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='검은날개 둥지', Description_Lang_koKR='' WHERE ID=50;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='낙스라마스', Description_Lang_koKR='' WHERE ID=159;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='안퀴라즈 폐허', Description_Lang_koKR='' WHERE ID=160;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='안퀴라즈 사원', Description_Lang_koKR='' WHERE ID=161;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='카라잔', Description_Lang_koKR='' WHERE ID=175;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='마그테리돈의 둥지', Description_Lang_koKR='' WHERE ID=176;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='그룰의 둥지', Description_Lang_koKR='' WHERE ID=177;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='폭풍우 요새', Description_Lang_koKR='' WHERE ID=193;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='불뱀 제단', Description_Lang_koKR='' WHERE ID=194;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='과거의 하이잘', Description_Lang_koKR='' WHERE ID=195;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='검은 사원', Description_Lang_koKR='' WHERE ID=196;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='줄아만', Description_Lang_koKR='' WHERE ID=197;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='태양샘', Description_Lang_koKR='' WHERE ID=199;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='영원의 눈', Description_Lang_koKR='' WHERE ID=223;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='흑요석 성소', Description_Lang_koKR='' WHERE ID=224;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='낙스라마스', Description_Lang_koKR='' WHERE ID=227;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='영원의 눈', Description_Lang_koKR='' WHERE ID=237;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='흑요석 성소', Description_Lang_koKR='' WHERE ID=238;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='아카본 석실', Description_Lang_koKR='' WHERE ID=239;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='아카본 석실', Description_Lang_koKR='' WHERE ID=240;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='울두아르', Description_Lang_koKR='' WHERE ID=243;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='울두아르', Description_Lang_koKR='' WHERE ID=244;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='십자군의 시험장', Description_Lang_koKR='' WHERE ID=246;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='십자군 사령관의 시험장', Description_Lang_koKR='' WHERE ID=247;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='십자군의 시험장', Description_Lang_koKR='' WHERE ID=248;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='십자군 사령관의 시험장', Description_Lang_koKR='' WHERE ID=250;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='오닉시아의 둥지', Description_Lang_koKR='' WHERE ID=257;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='얼음왕관 성채', Description_Lang_koKR='' WHERE ID=279;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='얼음왕관 성채', Description_Lang_koKR='' WHERE ID=280;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='루비 성소', Description_Lang_koKR='' WHERE ID=293;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='루비 성소', Description_Lang_koKR='' WHERE ID=294;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='엘윈 숲', Description_Lang_koKR='' WHERE ID=58;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='서부 몰락지대', Description_Lang_koKR='' WHERE ID=60;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='그늘숲', Description_Lang_koKR='' WHERE ID=62;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='던 모로', Description_Lang_koKR='' WHERE ID=64;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='모단 호수', Description_Lang_koKR='' WHERE ID=66;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='저습지', Description_Lang_koKR='' WHERE ID=68;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='가시덤불 골짜기', Description_Lang_koKR='' WHERE ID=70;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='저주받은 땅', Description_Lang_koKR='' WHERE ID=72;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='슬픔의 늪', Description_Lang_koKR='' WHERE ID=74;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='붉은마루 산맥', Description_Lang_koKR='' WHERE ID=76;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='불타는 평원', Description_Lang_koKR='' WHERE ID=78;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='이글거리는 협곡', Description_Lang_koKR='' WHERE ID=80;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='황야의 땅', Description_Lang_koKR='' WHERE ID=82;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='아라시 고원', Description_Lang_koKR='' WHERE ID=84;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='힐스브래드 구릉지', Description_Lang_koKR='' WHERE ID=86;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='동부 내륙지', Description_Lang_koKR='' WHERE ID=88;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='서부 역병지대', Description_Lang_koKR='' WHERE ID=90;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='동부 역병지대', Description_Lang_koKR='' WHERE ID=92;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='티리스팔 숲', Description_Lang_koKR='' WHERE ID=94;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='은빛소나무 숲', Description_Lang_koKR='' WHERE ID=96;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='알터랙 산맥', Description_Lang_koKR='' WHERE ID=98;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='듀로타', Description_Lang_koKR='' WHERE ID=100;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='멀고어', Description_Lang_koKR='' WHERE ID=102;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='불모의 땅', Description_Lang_koKR='' WHERE ID=104;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='돌발톱 산맥', Description_Lang_koKR='' WHERE ID=106;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='버섯구름 봉우리', Description_Lang_koKR='' WHERE ID=108;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='잊혀진 땅', Description_Lang_koKR='' WHERE ID=110;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='페랄라스', Description_Lang_koKR='' WHERE ID=112;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='먼지진흙 습지대', Description_Lang_koKR='' WHERE ID=114;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='타나리스', Description_Lang_koKR='' WHERE ID=116;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='운고로 분화구', Description_Lang_koKR='' WHERE ID=118;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='실리더스', Description_Lang_koKR='' WHERE ID=120;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='텔드랏실', Description_Lang_koKR='' WHERE ID=122;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='어둠의 해안', Description_Lang_koKR='' WHERE ID=124;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='잿빛 골짜기', Description_Lang_koKR='' WHERE ID=126;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='악령의 숲', Description_Lang_koKR='' WHERE ID=128;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='아즈샤라', Description_Lang_koKR='' WHERE ID=130;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='여명의 설원', Description_Lang_koKR='' WHERE ID=132;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='지옥불 반도', Description_Lang_koKR='' WHERE ID=152;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='장가르 습지대', Description_Lang_koKR='' WHERE ID=153;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='테로카르 숲', Description_Lang_koKR='' WHERE ID=154;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='나그란드', Description_Lang_koKR='' WHERE ID=155;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='어둠달 골짜기', Description_Lang_koKR='' WHERE ID=156;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='칼날 산맥', Description_Lang_koKR='' WHERE ID=157;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='황천의 폭풍', Description_Lang_koKR='' WHERE ID=158;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='영원노래 숲', Description_Lang_koKR='' WHERE ID=166;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='하늘안개 섬', Description_Lang_koKR='' WHERE ID=167;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='유령의 땅', Description_Lang_koKR='' WHERE ID=168;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='핏빛안개 섬', Description_Lang_koKR='' WHERE ID=169;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='쿠엘다나스 섬', Description_Lang_koKR='' WHERE ID=200;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='북풍의 땅', Description_Lang_koKR='' WHERE ID=228;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='울부짖는 협만', Description_Lang_koKR='' WHERE ID=229;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='회색 구릉지', Description_Lang_koKR='' WHERE ID=230;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='용의 안식처', Description_Lang_koKR='' WHERE ID=231;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='겨울손아귀', Description_Lang_koKR='' WHERE ID=232;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='줄드락', Description_Lang_koKR='' WHERE ID=233;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='숄라자르 분지', Description_Lang_koKR='' WHERE ID=234;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='폭풍우 봉우리', Description_Lang_koKR='' WHERE ID=235;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='얼음왕관', Description_Lang_koKR='' WHERE ID=236;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='아키나이 납골당', Description_Lang_koKR='' WHERE ID=178;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='마나 무덤', Description_Lang_koKR='' WHERE ID=179;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='세데크 전당', Description_Lang_koKR='' WHERE ID=180;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='어둠의 미궁', Description_Lang_koKR='' WHERE ID=181;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='검은늪', Description_Lang_koKR='' WHERE ID=182;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='던홀드 탈출', Description_Lang_koKR='' WHERE ID=183;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='강제 노역소', Description_Lang_koKR='' WHERE ID=184;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='증기 저장고', Description_Lang_koKR='' WHERE ID=185;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='지하수렁', Description_Lang_koKR='' WHERE ID=186;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='피의 용광로', Description_Lang_koKR='' WHERE ID=187;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='지옥불 성루', Description_Lang_koKR='' WHERE ID=188;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='으스러진 손의 전당', Description_Lang_koKR='' WHERE ID=189;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='알카트라즈', Description_Lang_koKR='' WHERE ID=190;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='신록의 정원', Description_Lang_koKR='' WHERE ID=191;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='메카나르', Description_Lang_koKR='' WHERE ID=192;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='마법학자의 정원', Description_Lang_koKR='' WHERE ID=201;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='우트가드 첨탑', Description_Lang_koKR='' WHERE ID=205;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='옛 스트라솔름', Description_Lang_koKR='' WHERE ID=210;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='마력의 눈', Description_Lang_koKR='' WHERE ID=211;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='번개의 전당', Description_Lang_koKR='' WHERE ID=212;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='돌의 전당', Description_Lang_koKR='' WHERE ID=213;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='드락타론 성채', Description_Lang_koKR='' WHERE ID=215;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='군드락', Description_Lang_koKR='' WHERE ID=217;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='안카헤트: 고대 왕국', Description_Lang_koKR='' WHERE ID=219;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='보랏빛 요새', Description_Lang_koKR='' WHERE ID=221;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='마력의 탑', Description_Lang_koKR='' WHERE ID=226;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='아졸네룹', Description_Lang_koKR='' WHERE ID=241;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='우트가드 성채', Description_Lang_koKR='' WHERE ID=242;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='용사의 시험장', Description_Lang_koKR='' WHERE ID=249;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='영혼의 제련소', Description_Lang_koKR='' WHERE ID=252;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='사론의 구덩이', Description_Lang_koKR='' WHERE ID=254;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='투영의 전당', Description_Lang_koKR='' WHERE ID=256;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='무작위 오리지널 던전', Description_Lang_koKR='' WHERE ID=258;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='무작위 불타는 성전 던전', Description_Lang_koKR='' WHERE ID=259;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='무작위 불타는 성전 (영웅)', Description_Lang_koKR='' WHERE ID=260;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='무작위 리치 왕 던전', Description_Lang_koKR='' WHERE ID=261;
UPDATE dbc_lfgdungeons SET Name_Lang_koKR='무작위 리치 왕 (영웅)', Description_Lang_koKR='' WHERE ID=262;
