UPDATE dbc_chartitles SET Name_Lang_koKR='정찰병 %s', Name1_Lang_koKR='정찰병 %s' WHERE ID=1;
UPDATE dbc_chartitles SET Name_Lang_koKR='파수병 %s', Name1_Lang_koKR='파수병 %s' WHERE ID=2;
UPDATE dbc_chartitles SET Name_Lang_koKR='근위병 %s', Name1_Lang_koKR='근위병 %s' WHERE ID=3;
UPDATE dbc_chartitles SET Name_Lang_koKR='정예근위병 %s', Name1_Lang_koKR='정예근위병 %s' WHERE ID=4;
UPDATE dbc_chartitles SET Name_Lang_koKR='하급기사 %s', Name1_Lang_koKR='하급기사 %s' WHERE ID=5;
UPDATE dbc_chartitles SET Name_Lang_koKR='기사 %s', Name1_Lang_koKR='기사 %s' WHERE ID=6;
UPDATE dbc_chartitles SET Name_Lang_koKR='상급기사 %s', Name1_Lang_koKR='상급기사 %s' WHERE ID=7;
UPDATE dbc_chartitles SET Name_Lang_koKR='기사대장 %s', Name1_Lang_koKR='기사대장 %s' WHERE ID=8;
UPDATE dbc_chartitles SET Name_Lang_koKR='기사단장 %s', Name1_Lang_koKR='기사단장 %s' WHERE ID=9;
UPDATE dbc_chartitles SET Name_Lang_koKR='부사령관 %s', Name1_Lang_koKR='부사령관 %s' WHERE ID=10;
UPDATE dbc_chartitles SET Name_Lang_koKR='사령관 %s', Name1_Lang_koKR='사령관 %s' WHERE ID=11;
UPDATE dbc_chartitles SET Name_Lang_koKR='작전사령관 %s', Name1_Lang_koKR='작전사령관 %s' WHERE ID=12;
UPDATE dbc_chartitles SET Name_Lang_koKR='야전사령관 %s', Name1_Lang_koKR='야전사령관 %s' WHERE ID=13;
UPDATE dbc_chartitles SET Name_Lang_koKR='최고사령관 %s', Name1_Lang_koKR='최고사령관 %s' WHERE ID=14;
UPDATE dbc_chartitles SET Name_Lang_koKR='척후병 %s', Name1_Lang_koKR='척후병 %s' WHERE ID=15;
UPDATE dbc_chartitles SET Name_Lang_koKR='그런트 %s', Name1_Lang_koKR='그런트 %s' WHERE ID=16;
UPDATE dbc_chartitles SET Name_Lang_koKR='수호병 %s', Name1_Lang_koKR='수호병 %s' WHERE ID=17;
UPDATE dbc_chartitles SET Name_Lang_koKR='정예수호병 %s', Name1_Lang_koKR='정예수호병 %s' WHERE ID=18;
UPDATE dbc_chartitles SET Name_Lang_koKR='하급투사 %s', Name1_Lang_koKR='하급투사 %s' WHERE ID=19;
UPDATE dbc_chartitles SET Name_Lang_koKR='투사 %s', Name1_Lang_koKR='투사 %s' WHERE ID=20;
UPDATE dbc_chartitles SET Name_Lang_koKR='혈투사 %s', Name1_Lang_koKR='혈투사 %s' WHERE ID=21;
UPDATE dbc_chartitles SET Name_Lang_koKR='용사 %s', Name1_Lang_koKR='용사 %s' WHERE ID=22;
UPDATE dbc_chartitles SET Name_Lang_koKR='백인대장 %s', Name1_Lang_koKR='백인대장 %s' WHERE ID=23;
UPDATE dbc_chartitles SET Name_Lang_koKR='부사령관 %s', Name1_Lang_koKR='부사령관 %s' WHERE ID=24;
UPDATE dbc_chartitles SET Name_Lang_koKR='사령관 %s', Name1_Lang_koKR='사령관 %s' WHERE ID=25;
UPDATE dbc_chartitles SET Name_Lang_koKR='전투사령관 %s', Name1_Lang_koKR='전투사령관 %s' WHERE ID=26;
UPDATE dbc_chartitles SET Name_Lang_koKR='장군 %s', Name1_Lang_koKR='장군 %s' WHERE ID=27;
UPDATE dbc_chartitles SET Name_Lang_koKR='대장군 %s', Name1_Lang_koKR='대장군 %s' WHERE ID=28;
UPDATE dbc_chartitles SET Name_Lang_koKR='검투사 %s', Name1_Lang_koKR='검투사 %s' WHERE ID=42;
UPDATE dbc_chartitles SET Name_Lang_koKR='결투사 %s', Name1_Lang_koKR='결투사 %s' WHERE ID=43;
UPDATE dbc_chartitles SET Name_Lang_koKR='승부사 %s', Name1_Lang_koKR='승부사 %s' WHERE ID=44;
UPDATE dbc_chartitles SET Name_Lang_koKR='도전자 %s', Name1_Lang_koKR='도전자 %s' WHERE ID=45;
UPDATE dbc_chartitles SET Name_Lang_koKR='스카라베 군주 %s', Name1_Lang_koKR='스카라베 군주 %s' WHERE ID=46;
UPDATE dbc_chartitles SET Name_Lang_koKR='정복자 %s', Name1_Lang_koKR='정복자 %s' WHERE ID=47;
UPDATE dbc_chartitles SET Name_Lang_koKR='심판관 %s', Name1_Lang_koKR='심판관 %s' WHERE ID=48;
UPDATE dbc_chartitles SET Name_Lang_koKR='나루의 용사 %s', Name1_Lang_koKR='나루의 용사 %s' WHERE ID=53;
UPDATE dbc_chartitles SET Name_Lang_koKR='무자비한 검투사 %s', Name1_Lang_koKR='무자비한 검투사 %s' WHERE ID=62;
UPDATE dbc_chartitles SET Name_Lang_koKR='무너진 태양의 용사 %s', Name1_Lang_koKR='무너진 태양의 용사 %s' WHERE ID=63;
UPDATE dbc_chartitles SET Name_Lang_koKR='아달의 수호자 %s', Name1_Lang_koKR='아달의 수호자 %s' WHERE ID=64;
UPDATE dbc_chartitles SET Name_Lang_koKR='복수심에 불타는 검투사 %s', Name1_Lang_koKR='복수심에 불타는 검투사 %s' WHERE ID=71;
UPDATE dbc_chartitles SET Name_Lang_koKR='지휘관 %s', Name1_Lang_koKR='지휘관 %s' WHERE ID=72;
UPDATE dbc_chartitles SET Name_Lang_koKR='장로 %s', Name1_Lang_koKR='장로 %s' WHERE ID=74;
UPDATE dbc_chartitles SET Name_Lang_koKR='불꽃감시자 %s', Name1_Lang_koKR='불꽃감시자 %s' WHERE ID=75;
UPDATE dbc_chartitles SET Name_Lang_koKR='불꽃지기 %s', Name1_Lang_koKR='불꽃지기 %s' WHERE ID=76;
UPDATE dbc_chartitles SET Name_Lang_koKR='확고자 %s', Name1_Lang_koKR='확고자 %s' WHERE ID=77;
UPDATE dbc_chartitles SET Name_Lang_koKR='탐험가 %s', Name1_Lang_koKR='탐험가 %s' WHERE ID=78;
UPDATE dbc_chartitles SET Name_Lang_koKR='외교관 %s', Name1_Lang_koKR='외교관 %s' WHERE ID=79;
UPDATE dbc_chartitles SET Name_Lang_koKR='야만적인 검투사 %s', Name1_Lang_koKR='야만적인 검투사 %s' WHERE ID=80;
UPDATE dbc_chartitles SET Name_Lang_koKR='탐구자 %s', Name1_Lang_koKR='탐구자 %s' WHERE ID=81;
UPDATE dbc_chartitles SET Name_Lang_koKR='전문 검투사 %s', Name1_Lang_koKR='전문 검투사 %s' WHERE ID=82;
UPDATE dbc_chartitles SET Name_Lang_koKR='낚시의 달인 %s', Name1_Lang_koKR='낚시의 달인 %s' WHERE ID=83;
UPDATE dbc_chartitles SET Name_Lang_koKR='요리사 %s', Name1_Lang_koKR='요리사 %s' WHERE ID=84;
UPDATE dbc_chartitles SET Name_Lang_koKR='궁극의 수호자 %s', Name1_Lang_koKR='궁극의 수호자 %s' WHERE ID=85;
UPDATE dbc_chartitles SET Name_Lang_koKR='폭풍우의 %s', Name1_Lang_koKR='폭풍우의 %s' WHERE ID=86;
UPDATE dbc_chartitles SET Name_Lang_koKR='에메랄드 꿈의 %s', Name1_Lang_koKR='에메랄드 꿈의 %s' WHERE ID=87;
UPDATE dbc_chartitles SET Name_Lang_koKR='예언자 %s', Name1_Lang_koKR='예언자 %s' WHERE ID=89;
UPDATE dbc_chartitles SET Name_Lang_koKR='재앙의 인도자 %s', Name1_Lang_koKR='재앙의 인도자 %s' WHERE ID=90;
UPDATE dbc_chartitles SET Name_Lang_koKR='추적자 %s', Name1_Lang_koKR='추적자 %s' WHERE ID=91;
UPDATE dbc_chartitles SET Name_Lang_koKR='칠흑의 기사단 %s', Name1_Lang_koKR='칠흑의 기사단 %s' WHERE ID=92;
UPDATE dbc_chartitles SET Name_Lang_koKR='대마법사 %s', Name1_Lang_koKR='대마법사 %s' WHERE ID=93;
UPDATE dbc_chartitles SET Name_Lang_koKR='전쟁의 인도자 %s', Name1_Lang_koKR='전쟁의 인도자 %s' WHERE ID=94;
UPDATE dbc_chartitles SET Name_Lang_koKR='암살자 %s', Name1_Lang_koKR='암살자 %s' WHERE ID=95;
UPDATE dbc_chartitles SET Name_Lang_koKR='연금술의 거장 %s', Name1_Lang_koKR='연금술의 거장 %s' WHERE ID=96;
UPDATE dbc_chartitles SET Name_Lang_koKR='대장기술의 거장 %s', Name1_Lang_koKR='대장기술의 거장 %s' WHERE ID=97;
UPDATE dbc_chartitles SET Name_Lang_koKR='무쇠 요리사 %s', Name1_Lang_koKR='무쇠 요리사 %s' WHERE ID=98;
UPDATE dbc_chartitles SET Name_Lang_koKR='마법부여의 거장 %s', Name1_Lang_koKR='마법부여의 거장 %s' WHERE ID=99;
UPDATE dbc_chartitles SET Name_Lang_koKR='기계공학의 거장 %s', Name1_Lang_koKR='기계공학의 거장 %s' WHERE ID=100;
UPDATE dbc_chartitles SET Name_Lang_koKR='의술사 %s', Name1_Lang_koKR='의술사 %s' WHERE ID=101;
UPDATE dbc_chartitles SET Name_Lang_koKR='낚시의 거장 %s', Name1_Lang_koKR='낚시의 거장 %s' WHERE ID=102;
UPDATE dbc_chartitles SET Name_Lang_koKR='약초채집의 거장 %s', Name1_Lang_koKR='약초채집의 거장 %s' WHERE ID=103;
UPDATE dbc_chartitles SET Name_Lang_koKR='주문각인의 거장 %s', Name1_Lang_koKR='주문각인의 거장 %s' WHERE ID=104;
UPDATE dbc_chartitles SET Name_Lang_koKR='보석세공의 거장 %s', Name1_Lang_koKR='보석세공의 거장 %s' WHERE ID=105;
UPDATE dbc_chartitles SET Name_Lang_koKR='가죽세공의 거장 %s', Name1_Lang_koKR='가죽세공의 거장 %s' WHERE ID=106;
UPDATE dbc_chartitles SET Name_Lang_koKR='채광의 거장 %s', Name1_Lang_koKR='채광의 거장 %s' WHERE ID=107;
UPDATE dbc_chartitles SET Name_Lang_koKR='무두질의 거장 %s', Name1_Lang_koKR='무두질의 거장 %s' WHERE ID=108;
UPDATE dbc_chartitles SET Name_Lang_koKR='재봉의 거장 %s', Name1_Lang_koKR='재봉의 거장 %s' WHERE ID=109;
UPDATE dbc_chartitles SET Name_Lang_koKR='쿠엘탈라스의 %s', Name1_Lang_koKR='쿠엘탈라스의 %s' WHERE ID=110;
UPDATE dbc_chartitles SET Name_Lang_koKR='아르거스의 %s', Name1_Lang_koKR='아르거스의 %s' WHERE ID=111;
UPDATE dbc_chartitles SET Name_Lang_koKR='카즈 모단의 %s', Name1_Lang_koKR='카즈 모단의 %s' WHERE ID=112;
UPDATE dbc_chartitles SET Name_Lang_koKR='놈리건의 %s', Name1_Lang_koKR='놈리건의 %s' WHERE ID=113;
UPDATE dbc_chartitles SET Name_Lang_koKR='사자심장 %s', Name1_Lang_koKR='사자심장 %s' WHERE ID=114;
UPDATE dbc_chartitles SET Name_Lang_koKR='엘룬의 용사 %s', Name1_Lang_koKR='엘룬의 용사 %s' WHERE ID=115;
UPDATE dbc_chartitles SET Name_Lang_koKR='오그리마의 영웅 %s', Name1_Lang_koKR='오그리마의 영웅 %s' WHERE ID=116;
UPDATE dbc_chartitles SET Name_Lang_koKR='평원의 여행자 %s', Name1_Lang_koKR='평원의 여행자 %s' WHERE ID=117;
UPDATE dbc_chartitles SET Name_Lang_koKR='검은창부족의 %s', Name1_Lang_koKR='검은창부족의 %s' WHERE ID=118;
UPDATE dbc_chartitles SET Name_Lang_koKR='포세이큰의 %s', Name1_Lang_koKR='포세이큰의 %s' WHERE ID=119;
UPDATE dbc_chartitles SET Name_Lang_koKR='마법 탐구가 %s', Name1_Lang_koKR='마법 탐구가 %s' WHERE ID=120;
UPDATE dbc_chartitles SET Name_Lang_koKR='황혼의 제압자 %s', Name1_Lang_koKR='황혼의 제압자 %s' WHERE ID=121;
UPDATE dbc_chartitles SET Name_Lang_koKR='낙스라마스의 정복자 %s', Name1_Lang_koKR='낙스라마스의 정복자 %s' WHERE ID=122;
UPDATE dbc_chartitles SET Name_Lang_koKR='노스렌드의 영웅 %s', Name1_Lang_koKR='노스렌드의 영웅 %s' WHERE ID=123;
UPDATE dbc_chartitles SET Name_Lang_koKR='성자 %s', Name1_Lang_koKR='성자 %s' WHERE ID=124;
UPDATE dbc_chartitles SET Name_Lang_koKR='현자 %s', Name1_Lang_koKR='현자 %s' WHERE ID=125;
UPDATE dbc_chartitles SET Name_Lang_koKR='얼라이언스의 전쟁용사 %s', Name1_Lang_koKR='얼라이언스의 전쟁용사 %s' WHERE ID=126;
UPDATE dbc_chartitles SET Name_Lang_koKR='호드의 전쟁용사 %s', Name1_Lang_koKR='호드의 전쟁용사 %s' WHERE ID=127;
UPDATE dbc_chartitles SET Name_Lang_koKR='완벽한 승리자 %s', Name1_Lang_koKR='완벽한 승리자 %s' WHERE ID=128;
UPDATE dbc_chartitles SET Name_Lang_koKR='얼어붙은 황무지의 용사 %s', Name1_Lang_koKR='얼어붙은 황무지의 용사 %s' WHERE ID=129;
UPDATE dbc_chartitles SET Name_Lang_koKR='대사 %s', Name1_Lang_koKR='대사 %s' WHERE ID=130;
UPDATE dbc_chartitles SET Name_Lang_koKR='은빛십자군 용사 %s', Name1_Lang_koKR='은빛십자군 용사 %s' WHERE ID=131;
UPDATE dbc_chartitles SET Name_Lang_koKR='세나리우스의 친구 %s', Name1_Lang_koKR='세나리우스의 친구 %s' WHERE ID=132;
UPDATE dbc_chartitles SET Name_Lang_koKR='시음가 %s', Name1_Lang_koKR='시음가 %s' WHERE ID=133;
UPDATE dbc_chartitles SET Name_Lang_koKR='흥겨운 축제꾼 %s', Name1_Lang_koKR='흥겨운 축제꾼 %s' WHERE ID=134;
UPDATE dbc_chartitles SET Name_Lang_koKR='사랑에 빠진 바보 %s', Name1_Lang_koKR='사랑에 빠진 바보 %s' WHERE ID=135;
UPDATE dbc_chartitles SET Name_Lang_koKR='보모 %s', Name1_Lang_koKR='보모 %s' WHERE ID=137;
UPDATE dbc_chartitles SET Name_Lang_koKR='후원자 %s', Name1_Lang_koKR='후원자 %s' WHERE ID=138;
UPDATE dbc_chartitles SET Name_Lang_koKR='흑요석 성소의 정복자 %s', Name1_Lang_koKR='흑요석 성소의 정복자 %s' WHERE ID=139;
UPDATE dbc_chartitles SET Name_Lang_koKR='일몰의 정복자 %s', Name1_Lang_koKR='일몰의 정복자 %s' WHERE ID=140;
UPDATE dbc_chartitles SET Name_Lang_koKR='불사신 %s', Name1_Lang_koKR='불사신 %s' WHERE ID=141;
UPDATE dbc_chartitles SET Name_Lang_koKR='불멸자 %s', Name1_Lang_koKR='불멸자 %s' WHERE ID=142;
UPDATE dbc_chartitles SET Name_Lang_koKR='젠킨스 %s', Name1_Lang_koKR='젠킨스 %s' WHERE ID=143;
UPDATE dbc_chartitles SET Name_Lang_koKR='붉은해적단 제독 %s', Name1_Lang_koKR='붉은해적단 제독 %s' WHERE ID=144;
UPDATE dbc_chartitles SET Name_Lang_koKR='폐인 %s', Name1_Lang_koKR='폐인 %s' WHERE ID=145;
UPDATE dbc_chartitles SET Name_Lang_koKR='엑소다르의 %s', Name1_Lang_koKR='엑소다르의 %s' WHERE ID=146;
UPDATE dbc_chartitles SET Name_Lang_koKR='다르나서스의 %s', Name1_Lang_koKR='다르나서스의 %s' WHERE ID=147;
UPDATE dbc_chartitles SET Name_Lang_koKR='아이언포지의 %s', Name1_Lang_koKR='아이언포지의 %s' WHERE ID=148;
UPDATE dbc_chartitles SET Name_Lang_koKR='스톰윈드의 %s', Name1_Lang_koKR='스톰윈드의 %s' WHERE ID=149;
UPDATE dbc_chartitles SET Name_Lang_koKR='오그리마의 %s', Name1_Lang_koKR='오그리마의 %s' WHERE ID=150;
UPDATE dbc_chartitles SET Name_Lang_koKR='센진의 %s', Name1_Lang_koKR='센진의 %s' WHERE ID=151;
UPDATE dbc_chartitles SET Name_Lang_koKR='실버문의 %s', Name1_Lang_koKR='실버문의 %s' WHERE ID=152;
UPDATE dbc_chartitles SET Name_Lang_koKR='썬더 블러프의 %s', Name1_Lang_koKR='썬더 블러프의 %s' WHERE ID=153;
UPDATE dbc_chartitles SET Name_Lang_koKR='언더시티의 %s', Name1_Lang_koKR='언더시티의 %s' WHERE ID=154;
UPDATE dbc_chartitles SET Name_Lang_koKR='귀족 %s', Name1_Lang_koKR='귀족 %s' WHERE ID=155;
UPDATE dbc_chartitles SET Name_Lang_koKR='성전사 %s', Name1_Lang_koKR='성전사 %s' WHERE ID=156;
UPDATE dbc_chartitles SET Name_Lang_koKR='죽음을 부르는 검투사 %s', Name1_Lang_koKR='죽음을 부르는 검투사 %s' WHERE ID=157;
UPDATE dbc_chartitles SET Name_Lang_koKR='사신을 쓰러뜨린 자 %s', Name1_Lang_koKR='사신을 쓰러뜨린 자 %s' WHERE ID=158;
UPDATE dbc_chartitles SET Name_Lang_koKR='천체 수호자 %s', Name1_Lang_koKR='천체 수호자 %s' WHERE ID=159;
UPDATE dbc_chartitles SET Name_Lang_koKR='울두아르의 정복자 %s', Name1_Lang_koKR='울두아르의 정복자 %s' WHERE ID=160;
UPDATE dbc_chartitles SET Name_Lang_koKR='울두아르의 용사 %s', Name1_Lang_koKR='울두아르의 용사 %s' WHERE ID=161;
UPDATE dbc_chartitles SET Name_Lang_koKR='제압자 %s', Name1_Lang_koKR='제압자 %s' WHERE ID=163;
UPDATE dbc_chartitles SET Name_Lang_koKR='별소환사 %s', Name1_Lang_koKR='별소환사 %s' WHERE ID=164;
UPDATE dbc_chartitles SET Name_Lang_koKR='은하수 방랑자 %s', Name1_Lang_koKR='은하수 방랑자 %s' WHERE ID=165;
UPDATE dbc_chartitles SET Name_Lang_koKR='티탄의 사자 %s', Name1_Lang_koKR='티탄의 사자 %s' WHERE ID=166;
UPDATE dbc_chartitles SET Name_Lang_koKR='격노한 검투사 %s', Name1_Lang_koKR='격노한 검투사 %s' WHERE ID=167;
UPDATE dbc_chartitles SET Name_Lang_koKR='순례자 %s', Name1_Lang_koKR='순례자 %s' WHERE ID=168;
UPDATE dbc_chartitles SET Name_Lang_koKR='냉혹한 검투사 %s', Name1_Lang_koKR='냉혹한 검투사 %s' WHERE ID=169;
UPDATE dbc_chartitles SET Name_Lang_koKR='십자군 사령관 %s', Name1_Lang_koKR='십자군 사령관 %s' WHERE ID=170;
UPDATE dbc_chartitles SET Name_Lang_koKR='은빛십자군 수호자 %s', Name1_Lang_koKR='은빛십자군 수호자 %s' WHERE ID=171;
UPDATE dbc_chartitles SET Name_Lang_koKR='기다릴 줄 아는 자 %s', Name1_Lang_koKR='기다릴 줄 아는 자 %s' WHERE ID=172;
UPDATE dbc_chartitles SET Name_Lang_koKR='여명의 빛 %s', Name1_Lang_koKR='여명의 빛 %s' WHERE ID=173;
UPDATE dbc_chartitles SET Name_Lang_koKR='왕을 몰락시킨 자 %s', Name1_Lang_koKR='왕을 몰락시킨 자 %s' WHERE ID=174;
UPDATE dbc_chartitles SET Name_Lang_koKR='왕을 쓰러뜨린 자 %s', Name1_Lang_koKR='왕을 쓰러뜨린 자 %s' WHERE ID=175;
UPDATE dbc_chartitles SET Name_Lang_koKR='잿빛 선고단의 %s', Name1_Lang_koKR='잿빛 선고단의 %s' WHERE ID=176;
UPDATE dbc_chartitles SET Name_Lang_koKR='분노한 검투사 %s', Name1_Lang_koKR='분노한 검투사 %s' WHERE ID=177;
