UPDATE dbc_totemcategory SET Name_Lang_koKR='무두질용 손칼' WHERE ID=1;
UPDATE dbc_totemcategory SET Name_Lang_koKR='대지의 토템' WHERE ID=2;
UPDATE dbc_totemcategory SET Name_Lang_koKR='바람의 토템' WHERE ID=3;
UPDATE dbc_totemcategory SET Name_Lang_koKR='불의 토템' WHERE ID=4;
UPDATE dbc_totemcategory SET Name_Lang_koKR='물의 토템' WHERE ID=5;
UPDATE dbc_totemcategory SET Name_Lang_koKR='룬문자 구리마법막대' WHERE ID=6;
UPDATE dbc_totemcategory SET Name_Lang_koKR='룬문자 은마법막대' WHERE ID=7;
UPDATE dbc_totemcategory SET Name_Lang_koKR='룬문자 금마법막대' WHERE ID=8;
UPDATE dbc_totemcategory SET Name_Lang_koKR='룬문자 진은마법막대' WHERE ID=9;
UPDATE dbc_totemcategory SET Name_Lang_koKR='룬문자 아케이나이트 마법막대' WHERE ID=10;
UPDATE dbc_totemcategory SET Name_Lang_koKR='채광용 곡괭이' WHERE ID=11;
UPDATE dbc_totemcategory SET Name_Lang_koKR='현자의 돌' WHERE ID=12;
UPDATE dbc_totemcategory SET Name_Lang_koKR='대장장이 망치' WHERE ID=13;
UPDATE dbc_totemcategory SET Name_Lang_koKR='만능 스패너' WHERE ID=14;
UPDATE dbc_totemcategory SET Name_Lang_koKR='자동회전 초정밀조율기' WHERE ID=15;
UPDATE dbc_totemcategory SET Name_Lang_koKR='만물의 토템' WHERE ID=21;
UPDATE dbc_totemcategory SET Name_Lang_koKR='룬문자 지옥무쇠 마법막대' WHERE ID=41;
UPDATE dbc_totemcategory SET Name_Lang_koKR='룬문자 아다만타이트 마법막대' WHERE ID=62;
UPDATE dbc_totemcategory SET Name_Lang_koKR='룬문자 이터늄 마법막대' WHERE ID=63;
UPDATE dbc_totemcategory SET Name_Lang_koKR='빈 깃대' WHERE ID=81;
UPDATE dbc_totemcategory SET Name_Lang_koKR='룬문자 아주라이트 마법막대' WHERE ID=101;
UPDATE dbc_totemcategory SET Name_Lang_koKR='숙련자의 필기구' WHERE ID=121;
UPDATE dbc_totemcategory SET Name_Lang_koKR='북소리' WHERE ID=141;
UPDATE dbc_totemcategory SET Name_Lang_koKR='노움 군용칼' WHERE ID=161;
UPDATE dbc_totemcategory SET Name_Lang_koKR='대장장이 망치' WHERE ID=162;
UPDATE dbc_totemcategory SET Name_Lang_koKR='채광용 곡괭이' WHERE ID=165;
UPDATE dbc_totemcategory SET Name_Lang_koKR='무두질용 손칼' WHERE ID=166;
UPDATE dbc_totemcategory SET Name_Lang_koKR='망치 곡괭이' WHERE ID=167;
UPDATE dbc_totemcategory SET Name_Lang_koKR='칼날 곡괭이' WHERE ID=168;
UPDATE dbc_totemcategory SET Name_Lang_koKR='부싯돌과 불쏘시개' WHERE ID=169;
UPDATE dbc_totemcategory SET Name_Lang_koKR='룬문자 코발트 마법막대 (미사용)' WHERE ID=189;
UPDATE dbc_totemcategory SET Name_Lang_koKR='룬문자 티타늄 마법막대' WHERE ID=190;
