UPDATE dbc_itemset SET Name_Lang_koKR='검투사' WHERE ID=1;
UPDATE dbc_itemset SET Name_Lang_koKR='달렌드의 무기' WHERE ID=41;
UPDATE dbc_itemset SET Name_Lang_koKR='거미의 입맞춤' WHERE ID=65;
UPDATE dbc_itemset SET Name_Lang_koKR='우체국장' WHERE ID=81;
UPDATE dbc_itemset SET Name_Lang_koKR='시체 수의' WHERE ID=121;
UPDATE dbc_itemset SET Name_Lang_koKR='시체더미 의복' WHERE ID=122;
UPDATE dbc_itemset SET Name_Lang_koKR='피고리 제복' WHERE ID=123;
UPDATE dbc_itemset SET Name_Lang_koKR='죽음의 뼈갑옷' WHERE ID=124;
UPDATE dbc_itemset SET Name_Lang_koKR='화산 갑옷' WHERE ID=141;
UPDATE dbc_itemset SET Name_Lang_koKR='폭풍안개 갑옷' WHERE ID=142;
UPDATE dbc_itemset SET Name_Lang_koKR='데빌사우루스 갑옷' WHERE ID=143;
UPDATE dbc_itemset SET Name_Lang_koKR='무쇠깃털 갑옷' WHERE ID=144;
UPDATE dbc_itemset SET Name_Lang_koKR='데피아즈단' WHERE ID=161;
UPDATE dbc_itemset SET Name_Lang_koKR='독사의 은총' WHERE ID=162;
UPDATE dbc_itemset SET Name_Lang_koKR='붉은십자군' WHERE ID=163;
UPDATE dbc_itemset SET Name_Lang_koKR='원소술사 의복' WHERE ID=181;
UPDATE dbc_itemset SET Name_Lang_koKR='기원의 의복' WHERE ID=182;
UPDATE dbc_itemset SET Name_Lang_koKR='공포의안개 의복' WHERE ID=183;
UPDATE dbc_itemset SET Name_Lang_koKR='어둠추적자 갑옷' WHERE ID=184;
UPDATE dbc_itemset SET Name_Lang_koKR='자연의정수 의복' WHERE ID=185;
UPDATE dbc_itemset SET Name_Lang_koKR='야수추적자 갑옷' WHERE ID=186;
UPDATE dbc_itemset SET Name_Lang_koKR='정령의 방어구' WHERE ID=187;
UPDATE dbc_itemset SET Name_Lang_koKR='성전사 방어구' WHERE ID=188;
UPDATE dbc_itemset SET Name_Lang_koKR='용맹의 전투장비' WHERE ID=189;
UPDATE dbc_itemset SET Name_Lang_koKR='신비술사 의복' WHERE ID=201;
UPDATE dbc_itemset SET Name_Lang_koKR='계시의 의복' WHERE ID=202;
UPDATE dbc_itemset SET Name_Lang_koKR='타락한심장의 의복' WHERE ID=203;
UPDATE dbc_itemset SET Name_Lang_koKR='밤그림자 갑옷' WHERE ID=204;
UPDATE dbc_itemset SET Name_Lang_koKR='세나리온 의복' WHERE ID=205;
UPDATE dbc_itemset SET Name_Lang_koKR='거인추적자 갑옷' WHERE ID=206;
UPDATE dbc_itemset SET Name_Lang_koKR='지각변동의 방어구' WHERE ID=207;
UPDATE dbc_itemset SET Name_Lang_koKR='집행의 방어구' WHERE ID=208;
UPDATE dbc_itemset SET Name_Lang_koKR='투지의 전투장비' WHERE ID=209;
UPDATE dbc_itemset SET Name_Lang_koKR='소용돌이 의복' WHERE ID=210;
UPDATE dbc_itemset SET Name_Lang_koKR='초월의 의복' WHERE ID=211;
UPDATE dbc_itemset SET Name_Lang_koKR='천벌의 의복' WHERE ID=212;
UPDATE dbc_itemset SET Name_Lang_koKR='붉은송곳니 방어구' WHERE ID=213;
UPDATE dbc_itemset SET Name_Lang_koKR='성난폭풍 의복' WHERE ID=214;
UPDATE dbc_itemset SET Name_Lang_koKR='용추적자 갑옷' WHERE ID=215;
UPDATE dbc_itemset SET Name_Lang_koKR='폭풍우 방어구' WHERE ID=216;
UPDATE dbc_itemset SET Name_Lang_koKR='심판의 갑옷' WHERE ID=217;
UPDATE dbc_itemset SET Name_Lang_koKR='격노의 전투장비' WHERE ID=218;
UPDATE dbc_itemset SET Name_Lang_koKR='테로샨의 의복' WHERE ID=221;
UPDATE dbc_itemset SET Name_Lang_koKR='신의 파편' WHERE ID=241;
UPDATE dbc_itemset SET Name_Lang_koKR='에스칸다르의 영혼' WHERE ID=261;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 전투장비' WHERE ID=281;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 전투장비' WHERE ID=282;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 주술사 갑옷' WHERE ID=301;
UPDATE dbc_itemset SET Name_Lang_koKR='황제의 판금장비' WHERE ID=321;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 마법사 의복' WHERE ID=341;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 사제 예복' WHERE ID=342;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 마법사 의복' WHERE ID=343;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 사제 예복' WHERE ID=344;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 흑마법사 의복' WHERE ID=345;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 흑마법사 의복' WHERE ID=346;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 도적 제복' WHERE ID=347;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 도적 제복' WHERE ID=348;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 사냥꾼 갑옷' WHERE ID=361;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 사냥꾼 갑옷' WHERE ID=362;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 드루이드 의복' WHERE ID=381;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 드루이드 의복' WHERE ID=382;
UPDATE dbc_itemset SET Name_Lang_koKR='장군의 전사 갑옷' WHERE ID=383;
UPDATE dbc_itemset SET Name_Lang_koKR='야전사령관의 전사 갑옷' WHERE ID=384;
UPDATE dbc_itemset SET Name_Lang_koKR='장군의 주술사 갑옷' WHERE ID=386;
UPDATE dbc_itemset SET Name_Lang_koKR='장군의 마법사 의복' WHERE ID=387;
UPDATE dbc_itemset SET Name_Lang_koKR='야전사령관의 마법사 의복' WHERE ID=388;
UPDATE dbc_itemset SET Name_Lang_koKR='야전사령관의 사제 예복' WHERE ID=389;
UPDATE dbc_itemset SET Name_Lang_koKR='장군의 사제 예복' WHERE ID=390;
UPDATE dbc_itemset SET Name_Lang_koKR='장군의 흑마법사 의복' WHERE ID=391;
UPDATE dbc_itemset SET Name_Lang_koKR='야전사령관의 흑마법사 의복' WHERE ID=392;
UPDATE dbc_itemset SET Name_Lang_koKR='장군의 도적 제복' WHERE ID=393;
UPDATE dbc_itemset SET Name_Lang_koKR='야전사령관의 도적 제복' WHERE ID=394;
UPDATE dbc_itemset SET Name_Lang_koKR='야전사령관의 사냥꾼 갑옷' WHERE ID=395;
UPDATE dbc_itemset SET Name_Lang_koKR='장군의 사냥꾼 갑옷' WHERE ID=396;
UPDATE dbc_itemset SET Name_Lang_koKR='야전사령관의 드루이드 의복' WHERE ID=397;
UPDATE dbc_itemset SET Name_Lang_koKR='장군의 드루이드 의복' WHERE ID=398;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 성기사 갑옷' WHERE ID=401;
UPDATE dbc_itemset SET Name_Lang_koKR='야전사령관의 성기사 갑옷' WHERE ID=402;
UPDATE dbc_itemset SET Name_Lang_koKR='붉은덩굴 의복' WHERE ID=421;
UPDATE dbc_itemset SET Name_Lang_koKR='원시 박쥐가죽' WHERE ID=441;
UPDATE dbc_itemset SET Name_Lang_koKR='붉은호랑이 방어구' WHERE ID=442;
UPDATE dbc_itemset SET Name_Lang_koKR='붉은영혼의 손아귀' WHERE ID=443;
UPDATE dbc_itemset SET Name_Lang_koKR='검은영혼의 손아귀' WHERE ID=444;
UPDATE dbc_itemset SET Name_Lang_koKR='학카리 쌍검' WHERE ID=461;
UPDATE dbc_itemset SET Name_Lang_koKR='잔질의 집중력' WHERE ID=462;
UPDATE dbc_itemset SET Name_Lang_koKR='원시 축복' WHERE ID=463;
UPDATE dbc_itemset SET Name_Lang_koKR='대군주의 결의' WHERE ID=464;
UPDATE dbc_itemset SET Name_Lang_koKR='원시술사의 기원' WHERE ID=465;
UPDATE dbc_itemset SET Name_Lang_koKR='강력한 모조' WHERE ID=466;
UPDATE dbc_itemset SET Name_Lang_koKR='산악연대의 결의' WHERE ID=467;
UPDATE dbc_itemset SET Name_Lang_koKR='산악연대의 결단' WHERE ID=468;
UPDATE dbc_itemset SET Name_Lang_koKR='산악연대의 결심' WHERE ID=469;
UPDATE dbc_itemset SET Name_Lang_koKR='산악연대의 인내' WHERE ID=470;
UPDATE dbc_itemset SET Name_Lang_koKR='산악연대의 맹세' WHERE ID=471;
UPDATE dbc_itemset SET Name_Lang_koKR='산악연대의 의지' WHERE ID=472;
UPDATE dbc_itemset SET Name_Lang_koKR='산악연대의 기상' WHERE ID=473;
UPDATE dbc_itemset SET Name_Lang_koKR='구원자의 전투장비' WHERE ID=474;
UPDATE dbc_itemset SET Name_Lang_koKR='자유사상가의 갑옷' WHERE ID=475;
UPDATE dbc_itemset SET Name_Lang_koKR='점술가의 의복' WHERE ID=476;
UPDATE dbc_itemset SET Name_Lang_koKR='수렵꾼의 갑옷' WHERE ID=477;
UPDATE dbc_itemset SET Name_Lang_koKR='개혁가의 장비' WHERE ID=478;
UPDATE dbc_itemset SET Name_Lang_koKR='제사장의 의복' WHERE ID=479;
UPDATE dbc_itemset SET Name_Lang_koKR='성자의 의복' WHERE ID=480;
UPDATE dbc_itemset SET Name_Lang_koKR='악령술사의 의복' WHERE ID=481;
UPDATE dbc_itemset SET Name_Lang_koKR='환영술사의 의복' WHERE ID=482;
UPDATE dbc_itemset SET Name_Lang_koKR='파멸단의 결심' WHERE ID=483;
UPDATE dbc_itemset SET Name_Lang_koKR='파멸단의 인내' WHERE ID=484;
UPDATE dbc_itemset SET Name_Lang_koKR='파멸단의 기상' WHERE ID=485;
UPDATE dbc_itemset SET Name_Lang_koKR='파멸단의 맹세' WHERE ID=486;
UPDATE dbc_itemset SET Name_Lang_koKR='파멸단의 결의' WHERE ID=487;
UPDATE dbc_itemset SET Name_Lang_koKR='파멸단의 의지' WHERE ID=488;
UPDATE dbc_itemset SET Name_Lang_koKR='검은용 쇠사슬 갑옷' WHERE ID=489;
UPDATE dbc_itemset SET Name_Lang_koKR='녹색용 쇠사슬 갑옷' WHERE ID=490;
UPDATE dbc_itemset SET Name_Lang_koKR='푸른용 쇠사슬 갑옷' WHERE ID=491;
UPDATE dbc_itemset SET Name_Lang_koKR='황혼의 제복' WHERE ID=492;
UPDATE dbc_itemset SET Name_Lang_koKR='태초의 의복' WHERE ID=493;
UPDATE dbc_itemset SET Name_Lang_koKR='영원한 삶의 의복' WHERE ID=494;
UPDATE dbc_itemset SET Name_Lang_koKR='굴하지 않는 힘의 전투장비' WHERE ID=495;
UPDATE dbc_itemset SET Name_Lang_koKR='정복자의 전투장비' WHERE ID=496;
UPDATE dbc_itemset SET Name_Lang_koKR='죽음의 선고자 전투장비' WHERE ID=497;
UPDATE dbc_itemset SET Name_Lang_koKR='어두운 그림자의 상징' WHERE ID=498;
UPDATE dbc_itemset SET Name_Lang_koKR='파멸의 소환사' WHERE ID=499;
UPDATE dbc_itemset SET Name_Lang_koKR='절대자의 의복' WHERE ID=500;
UPDATE dbc_itemset SET Name_Lang_koKR='폭풍소환사의 의복' WHERE ID=501;
UPDATE dbc_itemset SET Name_Lang_koKR='휘몰아치는 폭풍의 선물' WHERE ID=502;
UPDATE dbc_itemset SET Name_Lang_koKR='불가사의의 의복' WHERE ID=503;
UPDATE dbc_itemset SET Name_Lang_koKR='밝혀진 비밀의 의복' WHERE ID=504;
UPDATE dbc_itemset SET Name_Lang_koKR='응징의 전투장비' WHERE ID=505;
UPDATE dbc_itemset SET Name_Lang_koKR='영원한 정의의 전투장비' WHERE ID=506;
UPDATE dbc_itemset SET Name_Lang_koKR='신탁의 예복' WHERE ID=507;
UPDATE dbc_itemset SET Name_Lang_koKR='무한한 지혜의 의복' WHERE ID=508;
UPDATE dbc_itemset SET Name_Lang_koKR='관통의 전투장비' WHERE ID=509;
UPDATE dbc_itemset SET Name_Lang_koKR='선도자의 전투장비' WHERE ID=510;
UPDATE dbc_itemset SET Name_Lang_koKR='무용의 전투장비' WHERE ID=511;
UPDATE dbc_itemset SET Name_Lang_koKR='검은장막의 방어구' WHERE ID=512;
UPDATE dbc_itemset SET Name_Lang_koKR='야생의정수 의복' WHERE ID=513;
UPDATE dbc_itemset SET Name_Lang_koKR='고결의 의복' WHERE ID=514;
UPDATE dbc_itemset SET Name_Lang_koKR='야수왕의 갑옷' WHERE ID=515;
UPDATE dbc_itemset SET Name_Lang_koKR='성령의 갑옷' WHERE ID=516;
UPDATE dbc_itemset SET Name_Lang_koKR='마술사의 의복' WHERE ID=517;
UPDATE dbc_itemset SET Name_Lang_koKR='죽음의안개 의복' WHERE ID=518;
UPDATE dbc_itemset SET Name_Lang_koKR='우레의 방어구' WHERE ID=519;
UPDATE dbc_itemset SET Name_Lang_koKR='무쇠매듭 전투장비' WHERE ID=520;
UPDATE dbc_itemset SET Name_Lang_koKR='꿈나그네 의복' WHERE ID=521;
UPDATE dbc_itemset SET Name_Lang_koKR='경계의 부사령관 갑옷' WHERE ID=522;
UPDATE dbc_itemset SET Name_Lang_koKR='무쌍의 전투장비' WHERE ID=523;
UPDATE dbc_itemset SET Name_Lang_koKR='해골사신의 갑옷' WHERE ID=524;
UPDATE dbc_itemset SET Name_Lang_koKR='신념의 의복' WHERE ID=525;
UPDATE dbc_itemset SET Name_Lang_koKR='얼음불꽃 의복' WHERE ID=526;
UPDATE dbc_itemset SET Name_Lang_koKR='지축이동의 갑옷' WHERE ID=527;
UPDATE dbc_itemset SET Name_Lang_koKR='구원의 갑옷' WHERE ID=528;
UPDATE dbc_itemset SET Name_Lang_koKR='역병심장 의복' WHERE ID=529;
UPDATE dbc_itemset SET Name_Lang_koKR='지하추적자 갑옷' WHERE ID=530;
UPDATE dbc_itemset SET Name_Lang_koKR='언데드 퇴치의 전투장비' WHERE ID=533;
UPDATE dbc_itemset SET Name_Lang_koKR='언데드 사냥꾼의 갑옷' WHERE ID=534;
UPDATE dbc_itemset SET Name_Lang_koKR='언데드 사냥꾼의 의복' WHERE ID=535;
UPDATE dbc_itemset SET Name_Lang_koKR='언데드 정화의 의복' WHERE ID=536;
UPDATE dbc_itemset SET Name_Lang_koKR='전투의 부사령관 갑옷' WHERE ID=537;
UPDATE dbc_itemset SET Name_Lang_koKR='폭풍의 부사령관 갑옷' WHERE ID=538;
UPDATE dbc_itemset SET Name_Lang_koKR='위안의 부사령관 의복' WHERE ID=539;
UPDATE dbc_itemset SET Name_Lang_koKR='신탁의 부사령관 의복' WHERE ID=540;
UPDATE dbc_itemset SET Name_Lang_koKR='공포의 부사령관 의복' WHERE ID=541;
UPDATE dbc_itemset SET Name_Lang_koKR='비전의 부사령관 의복' WHERE ID=542;
UPDATE dbc_itemset SET Name_Lang_koKR='추적의 부사령관 갑옷' WHERE ID=543;
UPDATE dbc_itemset SET Name_Lang_koKR='보루의 부사령관 갑옷' WHERE ID=544;
UPDATE dbc_itemset SET Name_Lang_koKR='전투의 부사령관 갑옷' WHERE ID=545;
UPDATE dbc_itemset SET Name_Lang_koKR='비전의 부사령관 의복' WHERE ID=546;
UPDATE dbc_itemset SET Name_Lang_koKR='공포의 부사령관 의복' WHERE ID=547;
UPDATE dbc_itemset SET Name_Lang_koKR='경계의 부사령관 갑옷' WHERE ID=548;
UPDATE dbc_itemset SET Name_Lang_koKR='신탁의 부사령관 의복' WHERE ID=549;
UPDATE dbc_itemset SET Name_Lang_koKR='추적의 부사령관 갑옷' WHERE ID=550;
UPDATE dbc_itemset SET Name_Lang_koKR='위안의 부사령관 의복' WHERE ID=551;
UPDATE dbc_itemset SET Name_Lang_koKR='마법불꽃의 격노' WHERE ID=552;
UPDATE dbc_itemset SET Name_Lang_koKR='어둠의 은총' WHERE ID=553;
UPDATE dbc_itemset SET Name_Lang_koKR='태초의 달빛매듭 의복' WHERE ID=554;
UPDATE dbc_itemset SET Name_Lang_koKR='황천매듭 제복' WHERE ID=555;
UPDATE dbc_itemset SET Name_Lang_koKR='마력 깃든 황천매듭 제복' WHERE ID=556;
UPDATE dbc_itemset SET Name_Lang_koKR='영혼매듭 예복' WHERE ID=557;
UPDATE dbc_itemset SET Name_Lang_koKR='비전매듭 의복' WHERE ID=558;
UPDATE dbc_itemset SET Name_Lang_koKR='마법 강타의 마력' WHERE ID=559;
UPDATE dbc_itemset SET Name_Lang_koKR='지옥무쇠 판금장비' WHERE ID=560;
UPDATE dbc_itemset SET Name_Lang_koKR='지옥무쇠 사슬 방어구' WHERE ID=561;
UPDATE dbc_itemset SET Name_Lang_koKR='아다만타이트 전투장비' WHERE ID=562;
UPDATE dbc_itemset SET Name_Lang_koKR='마력 깃든 아다만타이트 갑옷' WHERE ID=563;
UPDATE dbc_itemset SET Name_Lang_koKR='화염의 수호' WHERE ID=564;
UPDATE dbc_itemset SET Name_Lang_koKR='코륨 방어구' WHERE ID=565;
UPDATE dbc_itemset SET Name_Lang_koKR='불타는 분노' WHERE ID=566;
UPDATE dbc_itemset SET Name_Lang_koKR='전투의 검투사 갑옷' WHERE ID=567;
UPDATE dbc_itemset SET Name_Lang_koKR='공포의 검투사 의복' WHERE ID=568;
UPDATE dbc_itemset SET Name_Lang_koKR='지옥강철 전투장비' WHERE ID=569;
UPDATE dbc_itemset SET Name_Lang_koKR='불굴의 방어구' WHERE ID=570;
UPDATE dbc_itemset SET Name_Lang_koKR='백마법의 지혜' WHERE ID=571;
UPDATE dbc_itemset SET Name_Lang_koKR='전투시전술 의복' WHERE ID=572;
UPDATE dbc_itemset SET Name_Lang_koKR='지옥 가죽 방어구' WHERE ID=573;
UPDATE dbc_itemset SET Name_Lang_koKR='갈래발굽의 힘' WHERE ID=574;
UPDATE dbc_itemset SET Name_Lang_koKR='지옥추적자 갑옷' WHERE ID=575;
UPDATE dbc_itemset SET Name_Lang_koKR='황천의 격노' WHERE ID=576;
UPDATE dbc_itemset SET Name_Lang_koKR='암살의 검투사 제복' WHERE ID=577;
UPDATE dbc_itemset SET Name_Lang_koKR='지각변동의 검투사 방어구' WHERE ID=578;
UPDATE dbc_itemset SET Name_Lang_koKR='비전의 검투사 의복' WHERE ID=579;
UPDATE dbc_itemset SET Name_Lang_koKR='천둥주먹의 검투사 방어구' WHERE ID=580;
UPDATE dbc_itemset SET Name_Lang_koKR='믿음의 검투사 예복' WHERE ID=581;
UPDATE dbc_itemset SET Name_Lang_koKR='심판의 검투사 전투장비' WHERE ID=582;
UPDATE dbc_itemset SET Name_Lang_koKR='비호의 검투사 방어구' WHERE ID=583;
UPDATE dbc_itemset SET Name_Lang_koKR='성역의 검투사 의복' WHERE ID=584;
UPDATE dbc_itemset SET Name_Lang_koKR='야생의 검투사 방어구' WHERE ID=585;
UPDATE dbc_itemset SET Name_Lang_koKR='추적의 검투사 장비' WHERE ID=586;
UPDATE dbc_itemset SET Name_Lang_koKR='대장군의 아이기스' WHERE ID=587;
UPDATE dbc_itemset SET Name_Lang_koKR='대장군의 전투장비' WHERE ID=588;
UPDATE dbc_itemset SET Name_Lang_koKR='최고사령관의 아이기스' WHERE ID=589;
UPDATE dbc_itemset SET Name_Lang_koKR='최고사령관의 전투장비' WHERE ID=590;
UPDATE dbc_itemset SET Name_Lang_koKR='최고사령관의 공포의복' WHERE ID=591;
UPDATE dbc_itemset SET Name_Lang_koKR='대장군의 공포의복' WHERE ID=592;
UPDATE dbc_itemset SET Name_Lang_koKR='최고사령관의 지각변동' WHERE ID=593;
UPDATE dbc_itemset SET Name_Lang_koKR='대장군의 지각변동' WHERE ID=594;
UPDATE dbc_itemset SET Name_Lang_koKR='최고사령관의 추격' WHERE ID=595;
UPDATE dbc_itemset SET Name_Lang_koKR='대장군의 추격' WHERE ID=596;
UPDATE dbc_itemset SET Name_Lang_koKR='최고사령관의 예복' WHERE ID=597;
UPDATE dbc_itemset SET Name_Lang_koKR='대장군의 예복' WHERE ID=598;
UPDATE dbc_itemset SET Name_Lang_koKR='최고사령관의 의복' WHERE ID=599;
UPDATE dbc_itemset SET Name_Lang_koKR='대장군의 의복' WHERE ID=600;
UPDATE dbc_itemset SET Name_Lang_koKR='최고사령관의 성역' WHERE ID=601;
UPDATE dbc_itemset SET Name_Lang_koKR='대장군의 성역' WHERE ID=602;
UPDATE dbc_itemset SET Name_Lang_koKR='최고사령관의 천둥주먹' WHERE ID=603;
UPDATE dbc_itemset SET Name_Lang_koKR='대장군의 천둥주먹' WHERE ID=604;
UPDATE dbc_itemset SET Name_Lang_koKR='최고사령관의 제복' WHERE ID=605;
UPDATE dbc_itemset SET Name_Lang_koKR='대장군의 제복' WHERE ID=606;
UPDATE dbc_itemset SET Name_Lang_koKR='최고사령관의 구원' WHERE ID=607;
UPDATE dbc_itemset SET Name_Lang_koKR='대장군의 구원' WHERE ID=608;
UPDATE dbc_itemset SET Name_Lang_koKR='최고사령관의 야생가죽' WHERE ID=609;
UPDATE dbc_itemset SET Name_Lang_koKR='대장군의 야생가죽' WHERE ID=610;
UPDATE dbc_itemset SET Name_Lang_koKR='지옥껍질 갑옷' WHERE ID=611;
UPDATE dbc_itemset SET Name_Lang_koKR='드레나이 미늘 갑옷' WHERE ID=612;
UPDATE dbc_itemset SET Name_Lang_koKR='두꺼운 드레나이 방어구' WHERE ID=613;
UPDATE dbc_itemset SET Name_Lang_koKR='야생의 드레나이 방어구' WHERE ID=614;
UPDATE dbc_itemset SET Name_Lang_koKR='악마의 검투사 수의' WHERE ID=615;
UPDATE dbc_itemset SET Name_Lang_koKR='황천비늘 갑옷' WHERE ID=616;
UPDATE dbc_itemset SET Name_Lang_koKR='황천쐐기 갑옷' WHERE ID=617;
UPDATE dbc_itemset SET Name_Lang_koKR='바람매 갑옷' WHERE ID=618;
UPDATE dbc_itemset SET Name_Lang_koKR='원소쐐기 갑옷' WHERE ID=619;
UPDATE dbc_itemset SET Name_Lang_koKR='암살의 제복' WHERE ID=620;
UPDATE dbc_itemset SET Name_Lang_koKR='황천의 칼날' WHERE ID=621;
UPDATE dbc_itemset SET Name_Lang_koKR='죽음의 장막' WHERE ID=622;
UPDATE dbc_itemset SET Name_Lang_koKR='정의의 방어구' WHERE ID=623;
UPDATE dbc_itemset SET Name_Lang_koKR='심판관의 예복' WHERE ID=624;
UPDATE dbc_itemset SET Name_Lang_koKR='심판관의 갑옷' WHERE ID=625;
UPDATE dbc_itemset SET Name_Lang_koKR='심판관의 전투장비' WHERE ID=626;
UPDATE dbc_itemset SET Name_Lang_koKR='정화의 예복' WHERE ID=627;
UPDATE dbc_itemset SET Name_Lang_koKR='정화의 갑옷' WHERE ID=628;
UPDATE dbc_itemset SET Name_Lang_koKR='정화의 전투장비' WHERE ID=629;
UPDATE dbc_itemset SET Name_Lang_koKR='성난 파도의 방어구' WHERE ID=630;
UPDATE dbc_itemset SET Name_Lang_koKR='회오리 예복' WHERE ID=631;
UPDATE dbc_itemset SET Name_Lang_koKR='회오리 의복' WHERE ID=632;
UPDATE dbc_itemset SET Name_Lang_koKR='회오리 갑옷' WHERE ID=633;
UPDATE dbc_itemset SET Name_Lang_koKR='천재지변의 예복' WHERE ID=634;
UPDATE dbc_itemset SET Name_Lang_koKR='천재지변의 의복' WHERE ID=635;
UPDATE dbc_itemset SET Name_Lang_koKR='천재지변의 갑옷' WHERE ID=636;
UPDATE dbc_itemset SET Name_Lang_koKR='달의 숲 의복' WHERE ID=637;
UPDATE dbc_itemset SET Name_Lang_koKR='말로른의 예복' WHERE ID=638;
UPDATE dbc_itemset SET Name_Lang_koKR='말로른의 의복' WHERE ID=639;
UPDATE dbc_itemset SET Name_Lang_koKR='말로른의 갑옷' WHERE ID=640;
UPDATE dbc_itemset SET Name_Lang_koKR='놀드랏실 갑옷' WHERE ID=641;
UPDATE dbc_itemset SET Name_Lang_koKR='놀드랏실 예복' WHERE ID=642;
UPDATE dbc_itemset SET Name_Lang_koKR='놀드랏실 의복' WHERE ID=643;
UPDATE dbc_itemset SET Name_Lang_koKR='망각의 수의' WHERE ID=644;
UPDATE dbc_itemset SET Name_Lang_koKR='공허의 심장 의복' WHERE ID=645;
UPDATE dbc_itemset SET Name_Lang_koKR='타락자의 의복' WHERE ID=646;
UPDATE dbc_itemset SET Name_Lang_koKR='주문술사 의복' WHERE ID=647;
UPDATE dbc_itemset SET Name_Lang_koKR='알도르 의복' WHERE ID=648;
UPDATE dbc_itemset SET Name_Lang_koKR='티리스팔 의복' WHERE ID=649;
UPDATE dbc_itemset SET Name_Lang_koKR='야수제왕의 갑옷' WHERE ID=650;
UPDATE dbc_itemset SET Name_Lang_koKR='악마추적자의 갑옷' WHERE ID=651;
UPDATE dbc_itemset SET Name_Lang_koKR='균열추적자 갑옷' WHERE ID=652;
UPDATE dbc_itemset SET Name_Lang_koKR='용자의 갑옷' WHERE ID=653;
UPDATE dbc_itemset SET Name_Lang_koKR='전쟁의 인도자 갑옷' WHERE ID=654;
UPDATE dbc_itemset SET Name_Lang_koKR='전쟁의 인도자 전투장비' WHERE ID=655;
UPDATE dbc_itemset SET Name_Lang_koKR='파괴자의 갑옷' WHERE ID=656;
UPDATE dbc_itemset SET Name_Lang_koKR='파괴자의 전투장비' WHERE ID=657;
UPDATE dbc_itemset SET Name_Lang_koKR='마나 깃든 예복' WHERE ID=658;
UPDATE dbc_itemset SET Name_Lang_koKR='거친 황야 의복' WHERE ID=659;
UPDATE dbc_itemset SET Name_Lang_koKR='황량함의 방어구' WHERE ID=660;
UPDATE dbc_itemset SET Name_Lang_koKR='파멸의 판금 갑옷' WHERE ID=661;
UPDATE dbc_itemset SET Name_Lang_koKR='신성의 예복' WHERE ID=662;
UPDATE dbc_itemset SET Name_Lang_koKR='현신의 예복' WHERE ID=663;
UPDATE dbc_itemset SET Name_Lang_koKR='현신의 의복' WHERE ID=664;
UPDATE dbc_itemset SET Name_Lang_koKR='화신의 예복' WHERE ID=665;
UPDATE dbc_itemset SET Name_Lang_koKR='화신의 의복' WHERE ID=666;
UPDATE dbc_itemset SET Name_Lang_koKR='쌍둥이 별' WHERE ID=667;
UPDATE dbc_itemset SET Name_Lang_koKR='학살자의 제복' WHERE ID=668;
UPDATE dbc_itemset SET Name_Lang_koKR='그론추적자 갑옷' WHERE ID=669;
UPDATE dbc_itemset SET Name_Lang_koKR='재앙의 의복' WHERE ID=670;
UPDATE dbc_itemset SET Name_Lang_koKR='폭풍우 의복' WHERE ID=671;
UPDATE dbc_itemset SET Name_Lang_koKR='맹공의 전투장비' WHERE ID=672;
UPDATE dbc_itemset SET Name_Lang_koKR='맹공의 갑옷' WHERE ID=673;
UPDATE dbc_itemset SET Name_Lang_koKR='면죄의 의복' WHERE ID=674;
UPDATE dbc_itemset SET Name_Lang_koKR='면죄의 예복' WHERE ID=675;
UPDATE dbc_itemset SET Name_Lang_koKR='천둥심장 갑옷' WHERE ID=676;
UPDATE dbc_itemset SET Name_Lang_koKR='천둥심장 의복' WHERE ID=677;
UPDATE dbc_itemset SET Name_Lang_koKR='천둥심장 예복' WHERE ID=678;
UPDATE dbc_itemset SET Name_Lang_koKR='빛의 수호자 갑옷' WHERE ID=679;
UPDATE dbc_itemset SET Name_Lang_koKR='빛의 수호자 전투장비' WHERE ID=680;
UPDATE dbc_itemset SET Name_Lang_koKR='빛의 수호자 예복' WHERE ID=681;
UPDATE dbc_itemset SET Name_Lang_koKR='무너지는 하늘의 갑옷' WHERE ID=682;
UPDATE dbc_itemset SET Name_Lang_koKR='무너지는 하늘의 예복' WHERE ID=683;
UPDATE dbc_itemset SET Name_Lang_koKR='무너지는 하늘의 의복' WHERE ID=684;
UPDATE dbc_itemset SET Name_Lang_koKR='위안의 검투사 의복' WHERE ID=685;
UPDATE dbc_itemset SET Name_Lang_koKR='전세의 검투사 방어구' WHERE ID=686;
UPDATE dbc_itemset SET Name_Lang_koKR='신탁의 검투사 예복' WHERE ID=687;
UPDATE dbc_itemset SET Name_Lang_koKR='위안의 최고사령관 의복' WHERE ID=688;
UPDATE dbc_itemset SET Name_Lang_koKR='위안의 대장군 의복' WHERE ID=689;
UPDATE dbc_itemset SET Name_Lang_koKR='구원의 검투사 방어구' WHERE ID=690;
UPDATE dbc_itemset SET Name_Lang_koKR='신탁의 최고사령관 예복' WHERE ID=691;
UPDATE dbc_itemset SET Name_Lang_koKR='신탁의 대장군 예복' WHERE ID=692;
UPDATE dbc_itemset SET Name_Lang_koKR='구원의 최고사령관 방어구' WHERE ID=693;
UPDATE dbc_itemset SET Name_Lang_koKR='구원의 대장군 방어구' WHERE ID=694;
UPDATE dbc_itemset SET Name_Lang_koKR='전세의 최고사령관 방어구' WHERE ID=695;
UPDATE dbc_itemset SET Name_Lang_koKR='전세의 대장군 방어구' WHERE ID=696;
UPDATE dbc_itemset SET Name_Lang_koKR='보루의 부사령관 갑옷' WHERE ID=697;
UPDATE dbc_itemset SET Name_Lang_koKR='장군의 성기사 갑옷' WHERE ID=698;
UPDATE dbc_itemset SET Name_Lang_koKR='아지노스의 쌍날검' WHERE ID=699;
UPDATE dbc_itemset SET Name_Lang_koKR='비호의 무자비한 검투사 방어구' WHERE ID=700;
UPDATE dbc_itemset SET Name_Lang_koKR='전투의 무자비한 검투사 갑옷' WHERE ID=701;
UPDATE dbc_itemset SET Name_Lang_koKR='공포의 무자비한 검투사 전투장비' WHERE ID=702;
UPDATE dbc_itemset SET Name_Lang_koKR='지각변동의 무자비한 검투사 방어구' WHERE ID=703;
UPDATE dbc_itemset SET Name_Lang_koKR='악마의 무자비한 검투사 수의' WHERE ID=704;
UPDATE dbc_itemset SET Name_Lang_koKR='신탁의 무자비한 검투사 예복' WHERE ID=705;
UPDATE dbc_itemset SET Name_Lang_koKR='추적의 무자비한 검투사 장비' WHERE ID=706;
UPDATE dbc_itemset SET Name_Lang_koKR='믿음의 무자비한 검투사 예복' WHERE ID=707;
UPDATE dbc_itemset SET Name_Lang_koKR='구원의 무자비한 검투사 방어구' WHERE ID=708;
UPDATE dbc_itemset SET Name_Lang_koKR='위안의 무자비한 검투사 의복' WHERE ID=709;
UPDATE dbc_itemset SET Name_Lang_koKR='비전의 무자비한 검투사 의복' WHERE ID=710;
UPDATE dbc_itemset SET Name_Lang_koKR='성역의 무자비한 검투사 의복' WHERE ID=711;
UPDATE dbc_itemset SET Name_Lang_koKR='천둥주먹의 무자비한 검투사 방어구' WHERE ID=712;
UPDATE dbc_itemset SET Name_Lang_koKR='암살의 무자비한 검투사 제복' WHERE ID=713;
UPDATE dbc_itemset SET Name_Lang_koKR='심판의 무자비한 검투사 전투장비' WHERE ID=714;
UPDATE dbc_itemset SET Name_Lang_koKR='전세의 무자비한 검투사 방어구' WHERE ID=715;
UPDATE dbc_itemset SET Name_Lang_koKR='야생의 무자비한 검투사 방어구' WHERE ID=716;
UPDATE dbc_itemset SET Name_Lang_koKR='야전사령관의 주술사 갑옷' WHERE ID=717;
UPDATE dbc_itemset SET Name_Lang_koKR='부사령관의 주술사 갑옷' WHERE ID=718;
UPDATE dbc_itemset SET Name_Lang_koKR='격노의 철권' WHERE ID=719;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 의복' WHERE ID=720;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 예복' WHERE ID=721;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 방어구' WHERE ID=722;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 추적장비' WHERE ID=723;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 마법의복' WHERE ID=724;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 구원의복' WHERE ID=725;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 비호장비' WHERE ID=726;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 보호구' WHERE ID=727;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 신성예복' WHERE ID=728;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 예복' WHERE ID=729;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 제복' WHERE ID=730;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 주술방어구' WHERE ID=731;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 주술갑옷' WHERE ID=732;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 주술장비' WHERE ID=733;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 전투장비' WHERE ID=734;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 수의' WHERE ID=735;
UPDATE dbc_itemset SET Name_Lang_koKR='복수심에 불타는 검투사 갑옷' WHERE ID=736;
UPDATE dbc_itemset SET Name_Lang_koKR='질풍의 라트로' WHERE ID=737;
UPDATE dbc_itemset SET Name_Lang_koKR='공포매듭 전투장비' WHERE ID=738;
UPDATE dbc_itemset SET Name_Lang_koKR='달빛매듭 전투장비' WHERE ID=739;
UPDATE dbc_itemset SET Name_Lang_koKR='명주 전투장비' WHERE ID=740;
UPDATE dbc_itemset SET Name_Lang_koKR='마법술사의 전투장비' WHERE ID=741;
UPDATE dbc_itemset SET Name_Lang_koKR='용가죽 전투장비' WHERE ID=742;
UPDATE dbc_itemset SET Name_Lang_koKR='고룡가죽 전투장비' WHERE ID=743;
UPDATE dbc_itemset SET Name_Lang_koKR='코도가죽 전투장비' WHERE ID=744;
UPDATE dbc_itemset SET Name_Lang_koKR='기회주의자의 전투장비' WHERE ID=745;
UPDATE dbc_itemset SET Name_Lang_koKR='예언자의 쇠사슬 전투장비' WHERE ID=746;
UPDATE dbc_itemset SET Name_Lang_koKR='예언자의 고리사슬 전투장비' WHERE ID=747;
UPDATE dbc_itemset SET Name_Lang_koKR='예언자의 사슬매듭 전투장비' WHERE ID=748;
UPDATE dbc_itemset SET Name_Lang_koKR='추적자의 사슬 전투장비' WHERE ID=749;
UPDATE dbc_itemset SET Name_Lang_koKR='야만의 판금 전투장비' WHERE ID=750;
UPDATE dbc_itemset SET Name_Lang_koKR='성전사의 문장 전투장비' WHERE ID=751;
UPDATE dbc_itemset SET Name_Lang_koKR='성전사의 미늘 전투장비' WHERE ID=752;
UPDATE dbc_itemset SET Name_Lang_koKR='북풍의 은총' WHERE ID=754;
UPDATE dbc_itemset SET Name_Lang_koKR='네루비안 껍질' WHERE ID=755;
UPDATE dbc_itemset SET Name_Lang_koKR='서리미늘 예복' WHERE ID=756;
UPDATE dbc_itemset SET Name_Lang_koKR='얼음결 예복' WHERE ID=757;
UPDATE dbc_itemset SET Name_Lang_koKR='레이네의 복수' WHERE ID=759;
UPDATE dbc_itemset SET Name_Lang_koKR='검투사의 공포판금갑옷' WHERE ID=760;
UPDATE dbc_itemset SET Name_Lang_koKR='겨울 예복' WHERE ID=761;
UPDATE dbc_itemset SET Name_Lang_koKR='가을 축제 예복' WHERE ID=762;
UPDATE dbc_itemset SET Name_Lang_koKR='서리장식의 힘' WHERE ID=763;
UPDATE dbc_itemset SET Name_Lang_koKR='그늘매듭 의복' WHERE ID=764;
UPDATE dbc_itemset SET Name_Lang_koKR='전투의 검투사 갑옷' WHERE ID=765;
UPDATE dbc_itemset SET Name_Lang_koKR='비호의 검투사 방어구' WHERE ID=766;
UPDATE dbc_itemset SET Name_Lang_koKR='구원의 검투사 방어구' WHERE ID=767;
UPDATE dbc_itemset SET Name_Lang_koKR='모독의 검투사 방어구' WHERE ID=768;
UPDATE dbc_itemset SET Name_Lang_koKR='천둥주먹의 검투사 방어구' WHERE ID=769;
UPDATE dbc_itemset SET Name_Lang_koKR='지각변동의 검투사 방어구' WHERE ID=770;
UPDATE dbc_itemset SET Name_Lang_koKR='전세의 검투사 방어구' WHERE ID=771;
UPDATE dbc_itemset SET Name_Lang_koKR='추적의 검투사 장비' WHERE ID=772;
UPDATE dbc_itemset SET Name_Lang_koKR='위안의 검투사 의복' WHERE ID=773;
UPDATE dbc_itemset SET Name_Lang_koKR='야생의 검투사 방어구' WHERE ID=774;
UPDATE dbc_itemset SET Name_Lang_koKR='성역의 검투사 의복' WHERE ID=775;
UPDATE dbc_itemset SET Name_Lang_koKR='암살의 검투사 제복' WHERE ID=776;
UPDATE dbc_itemset SET Name_Lang_koKR='신탁의 검투사 예복' WHERE ID=777;
UPDATE dbc_itemset SET Name_Lang_koKR='믿음의 검투사 예복' WHERE ID=778;
UPDATE dbc_itemset SET Name_Lang_koKR='비전의 검투사 의복' WHERE ID=779;
UPDATE dbc_itemset SET Name_Lang_koKR='악마의 검투사 수의' WHERE ID=780;
UPDATE dbc_itemset SET Name_Lang_koKR='언데드 정화의 축복받은 의복' WHERE ID=781;
UPDATE dbc_itemset SET Name_Lang_koKR='언데드 퇴치의 축복받은 갑옷' WHERE ID=782;
UPDATE dbc_itemset SET Name_Lang_koKR='언데드 퇴치의 축복받은 예복' WHERE ID=783;
UPDATE dbc_itemset SET Name_Lang_koKR='언데드 퇴치의 축복받은 전투장비' WHERE ID=784;
UPDATE dbc_itemset SET Name_Lang_koKR='한여름 축제 구경꾼 의상' WHERE ID=785;
UPDATE dbc_itemset SET Name_Lang_koKR='무쌍의 판금장비' WHERE ID=787;
UPDATE dbc_itemset SET Name_Lang_koKR='무쌍의 전투장비' WHERE ID=788;
UPDATE dbc_itemset SET Name_Lang_koKR='구원의 전투장비' WHERE ID=789;
UPDATE dbc_itemset SET Name_Lang_koKR='구원의 의복' WHERE ID=790;
UPDATE dbc_itemset SET Name_Lang_koKR='구원의 판금장비' WHERE ID=791;
UPDATE dbc_itemset SET Name_Lang_koKR='스컬지 전투장비' WHERE ID=792;
UPDATE dbc_itemset SET Name_Lang_koKR='스컬지 판금장비' WHERE ID=793;
UPDATE dbc_itemset SET Name_Lang_koKR='지하추적자 전투장비' WHERE ID=794;
UPDATE dbc_itemset SET Name_Lang_koKR='지축이동의 전투장비' WHERE ID=795;
UPDATE dbc_itemset SET Name_Lang_koKR='지축이동의 제복' WHERE ID=796;
UPDATE dbc_itemset SET Name_Lang_koKR='지축이동의 의복' WHERE ID=797;
UPDATE dbc_itemset SET Name_Lang_koKR='꿈나그네 전투장비' WHERE ID=798;
UPDATE dbc_itemset SET Name_Lang_koKR='꿈나그네 의복' WHERE ID=799;
UPDATE dbc_itemset SET Name_Lang_koKR='꿈나그네 제복' WHERE ID=800;
UPDATE dbc_itemset SET Name_Lang_koKR='해골사신 전투장비' WHERE ID=801;
UPDATE dbc_itemset SET Name_Lang_koKR='역병심장 예복' WHERE ID=802;
UPDATE dbc_itemset SET Name_Lang_koKR='얼음불꽃 의복' WHERE ID=803;
UPDATE dbc_itemset SET Name_Lang_koKR='신념의 의복' WHERE ID=804;
UPDATE dbc_itemset SET Name_Lang_koKR='신념의 제복' WHERE ID=805;
UPDATE dbc_itemset SET Name_Lang_koKR='새봄맞이 턱시도' WHERE ID=812;
UPDATE dbc_itemset SET Name_Lang_koKR='적출자의 전투장비' WHERE ID=813;
UPDATE dbc_itemset SET Name_Lang_koKR='화려한 사로나이트 전투장비' WHERE ID=814;
UPDATE dbc_itemset SET Name_Lang_koKR='구름 덮인 전투장비' WHERE ID=815;
UPDATE dbc_itemset SET Name_Lang_koKR='야만의 사로나이트 전투장비' WHERE ID=816;
UPDATE dbc_itemset SET Name_Lang_koKR='폭풍도마뱀 전투장비' WHERE ID=817;
UPDATE dbc_itemset SET Name_Lang_koKR='바람화살 전투장비' WHERE ID=818;
UPDATE dbc_itemset SET Name_Lang_koKR='야만의 서리 전투장비' WHERE ID=819;
UPDATE dbc_itemset SET Name_Lang_koKR='비호 전투장비' WHERE ID=820;
UPDATE dbc_itemset SET Name_Lang_koKR='비호 판금장비' WHERE ID=821;
UPDATE dbc_itemset SET Name_Lang_koKR='비호 의복' WHERE ID=822;
UPDATE dbc_itemset SET Name_Lang_koKR='세계파괴자 전투장비' WHERE ID=823;
UPDATE dbc_itemset SET Name_Lang_koKR='세계파괴자 제복' WHERE ID=824;
UPDATE dbc_itemset SET Name_Lang_koKR='세계파괴자 의복' WHERE ID=825;
UPDATE dbc_itemset SET Name_Lang_koKR='공포칼날 전투장비' WHERE ID=826;
UPDATE dbc_itemset SET Name_Lang_koKR='별빛노래 전투장비' WHERE ID=827;
UPDATE dbc_itemset SET Name_Lang_koKR='별빛노래 제복' WHERE ID=828;
UPDATE dbc_itemset SET Name_Lang_koKR='별빛노래 의복' WHERE ID=829;
UPDATE dbc_itemset SET Name_Lang_koKR='공성파괴자 전투장비' WHERE ID=830;
UPDATE dbc_itemset SET Name_Lang_koKR='공성파괴자 판금장비' WHERE ID=831;
UPDATE dbc_itemset SET Name_Lang_koKR='축성 제복' WHERE ID=832;
UPDATE dbc_itemset SET Name_Lang_koKR='축성 의복' WHERE ID=833;
UPDATE dbc_itemset SET Name_Lang_koKR='암흑룬문자 전투장비' WHERE ID=834;
UPDATE dbc_itemset SET Name_Lang_koKR='암흑룬문자 판금장비' WHERE ID=835;
UPDATE dbc_itemset SET Name_Lang_koKR='키린 토 제복' WHERE ID=836;
UPDATE dbc_itemset SET Name_Lang_koKR='죽음인도자 제복' WHERE ID=837;
UPDATE dbc_itemset SET Name_Lang_koKR='스컬지추적자 전투장비' WHERE ID=838;
UPDATE dbc_itemset SET Name_Lang_koKR='카드가의 의복' WHERE ID=843;
UPDATE dbc_itemset SET Name_Lang_koKR='선스트라이더의 의복' WHERE ID=844;
UPDATE dbc_itemset SET Name_Lang_koKR='굴단의 의복' WHERE ID=845;
UPDATE dbc_itemset SET Name_Lang_koKR='켈투자드의 의복' WHERE ID=846;
UPDATE dbc_itemset SET Name_Lang_koKR='벨렌의 예복' WHERE ID=847;
UPDATE dbc_itemset SET Name_Lang_koKR='자브라의 예복' WHERE ID=848;
UPDATE dbc_itemset SET Name_Lang_koKR='벨렌의 의복' WHERE ID=849;
UPDATE dbc_itemset SET Name_Lang_koKR='자브라의 의복' WHERE ID=850;
UPDATE dbc_itemset SET Name_Lang_koKR='말퓨리온의 제복' WHERE ID=851;
UPDATE dbc_itemset SET Name_Lang_koKR='룬토템의 제복' WHERE ID=852;
UPDATE dbc_itemset SET Name_Lang_koKR='말퓨리온의 의복' WHERE ID=853;
UPDATE dbc_itemset SET Name_Lang_koKR='룬토템의 의복' WHERE ID=854;
UPDATE dbc_itemset SET Name_Lang_koKR='말퓨리온의 전투장비' WHERE ID=855;
UPDATE dbc_itemset SET Name_Lang_koKR='룬토템의 전투장비' WHERE ID=856;
UPDATE dbc_itemset SET Name_Lang_koKR='밴클리프의 전투장비' WHERE ID=857;
UPDATE dbc_itemset SET Name_Lang_koKR='가로나의 전투장비' WHERE ID=858;
UPDATE dbc_itemset SET Name_Lang_koKR='윈드러너의 전투장비' WHERE ID=859;
UPDATE dbc_itemset SET Name_Lang_koKR='윈드러너의 추격장비' WHERE ID=860;
UPDATE dbc_itemset SET Name_Lang_koKR='노분도의 제복' WHERE ID=861;
UPDATE dbc_itemset SET Name_Lang_koKR='스랄의 제복' WHERE ID=862;
UPDATE dbc_itemset SET Name_Lang_koKR='스랄의 의복' WHERE ID=863;
UPDATE dbc_itemset SET Name_Lang_koKR='노분도의 의복' WHERE ID=864;
UPDATE dbc_itemset SET Name_Lang_koKR='노분도의 전투장비' WHERE ID=865;
UPDATE dbc_itemset SET Name_Lang_koKR='스랄의 전투장비' WHERE ID=866;
UPDATE dbc_itemset SET Name_Lang_koKR='린의 전투장비' WHERE ID=867;
UPDATE dbc_itemset SET Name_Lang_koKR='헬스크림의 전투장비' WHERE ID=868;
UPDATE dbc_itemset SET Name_Lang_koKR='린의 판금장비' WHERE ID=869;
UPDATE dbc_itemset SET Name_Lang_koKR='헬스크림의 판금장비' WHERE ID=870;
UPDATE dbc_itemset SET Name_Lang_koKR='타사리안의 전투장비' WHERE ID=871;
UPDATE dbc_itemset SET Name_Lang_koKR='콜티라의 전투장비' WHERE ID=872;
UPDATE dbc_itemset SET Name_Lang_koKR='타사리안의 판금장비' WHERE ID=873;
UPDATE dbc_itemset SET Name_Lang_koKR='콜티라의 판금장비' WHERE ID=874;
UPDATE dbc_itemset SET Name_Lang_koKR='투랄리온의 제복' WHERE ID=875;
UPDATE dbc_itemset SET Name_Lang_koKR='리아드린의 제복' WHERE ID=876;
UPDATE dbc_itemset SET Name_Lang_koKR='투랄리온의 전투장비' WHERE ID=877;
UPDATE dbc_itemset SET Name_Lang_koKR='리아드린의 전투장비' WHERE ID=878;
UPDATE dbc_itemset SET Name_Lang_koKR='투랄리온의 판금장비' WHERE ID=879;
UPDATE dbc_itemset SET Name_Lang_koKR='리아드린의 판금장비' WHERE ID=880;
UPDATE dbc_itemset SET Name_Lang_koKR='정화된 신의 파편' WHERE ID=881;
UPDATE dbc_itemset SET Name_Lang_koKR='반짝이는 신의 파편' WHERE ID=882;
UPDATE dbc_itemset SET Name_Lang_koKR='혈법사 의복' WHERE ID=883;
UPDATE dbc_itemset SET Name_Lang_koKR='어둠의 집회 의복' WHERE ID=884;
UPDATE dbc_itemset SET Name_Lang_koKR='진홍빛 수행사제 예복' WHERE ID=885;
UPDATE dbc_itemset SET Name_Lang_koKR='진홍빛 수행사제 의복' WHERE ID=886;
UPDATE dbc_itemset SET Name_Lang_koKR='덩굴손매듭 제복' WHERE ID=887;
UPDATE dbc_itemset SET Name_Lang_koKR='덩굴손매듭 의복' WHERE ID=888;
UPDATE dbc_itemset SET Name_Lang_koKR='덩굴손매듭 전투장비' WHERE ID=889;
UPDATE dbc_itemset SET Name_Lang_koKR='그림자칼날 전투장비' WHERE ID=890;
UPDATE dbc_itemset SET Name_Lang_koKR='안카하르 피사냥꾼 전투장비' WHERE ID=891;
UPDATE dbc_itemset SET Name_Lang_koKR='서리술사 제복' WHERE ID=892;
UPDATE dbc_itemset SET Name_Lang_koKR='서리술사 의복' WHERE ID=893;
UPDATE dbc_itemset SET Name_Lang_koKR='서리술사 전투장비' WHERE ID=894;
UPDATE dbc_itemset SET Name_Lang_koKR='이미야르 군주 전투장비' WHERE ID=895;
UPDATE dbc_itemset SET Name_Lang_koKR='이미야르 군주 판금장비' WHERE ID=896;
UPDATE dbc_itemset SET Name_Lang_koKR='스컬지군주 전투장비' WHERE ID=897;
UPDATE dbc_itemset SET Name_Lang_koKR='스컬지군주 판금장비' WHERE ID=898;
UPDATE dbc_itemset SET Name_Lang_koKR='서약의 빛 제복' WHERE ID=899;
UPDATE dbc_itemset SET Name_Lang_koKR='서약의 빛 전투장비' WHERE ID=900;
UPDATE dbc_itemset SET Name_Lang_koKR='서약의 빛 판금장비' WHERE ID=901;
