UPDATE dbc_questsort SET SortName_Lang_koKR='대규모' WHERE ID=1;
UPDATE dbc_questsort SET SortName_Lang_koKR='통곡의 동굴' WHERE ID=21;
UPDATE dbc_questsort SET SortName_Lang_koKR='이벤트' WHERE ID=22;
UPDATE dbc_questsort SET SortName_Lang_koKR='언더시티' WHERE ID=23;
UPDATE dbc_questsort SET SortName_Lang_koKR='약초채집' WHERE ID=24;
UPDATE dbc_questsort SET SortName_Lang_koKR='전장' WHERE ID=25;
UPDATE dbc_questsort SET SortName_Lang_koKR='망자의 날' WHERE ID=41;
UPDATE dbc_questsort SET SortName_Lang_koKR='흑마법사' WHERE ID=61;
UPDATE dbc_questsort SET SortName_Lang_koKR='전사' WHERE ID=81;
UPDATE dbc_questsort SET SortName_Lang_koKR='주술사' WHERE ID=82;
UPDATE dbc_questsort SET SortName_Lang_koKR='낚시꾼' WHERE ID=101;
UPDATE dbc_questsort SET SortName_Lang_koKR='대장장이' WHERE ID=121;
UPDATE dbc_questsort SET SortName_Lang_koKR='성기사' WHERE ID=141;
UPDATE dbc_questsort SET SortName_Lang_koKR='마법사' WHERE ID=161;
UPDATE dbc_questsort SET SortName_Lang_koKR='도적' WHERE ID=162;
UPDATE dbc_questsort SET SortName_Lang_koKR='연금술' WHERE ID=181;
UPDATE dbc_questsort SET SortName_Lang_koKR='가죽세공' WHERE ID=182;
UPDATE dbc_questsort SET SortName_Lang_koKR='기계 공학' WHERE ID=201;
UPDATE dbc_questsort SET SortName_Lang_koKR='보물 지도' WHERE ID=221;
UPDATE dbc_questsort SET SortName_Lang_koKR='마상시합' WHERE ID=241;
UPDATE dbc_questsort SET SortName_Lang_koKR='사냥꾼' WHERE ID=261;
UPDATE dbc_questsort SET SortName_Lang_koKR='사제' WHERE ID=262;
UPDATE dbc_questsort SET SortName_Lang_koKR='드루이드' WHERE ID=263;
UPDATE dbc_questsort SET SortName_Lang_koKR='재봉술' WHERE ID=264;
UPDATE dbc_questsort SET SortName_Lang_koKR='특수' WHERE ID=284;
UPDATE dbc_questsort SET SortName_Lang_koKR='요리' WHERE ID=304;
UPDATE dbc_questsort SET SortName_Lang_koKR='응급치료' WHERE ID=324;
UPDATE dbc_questsort SET SortName_Lang_koKR='전설' WHERE ID=344;
UPDATE dbc_questsort SET SortName_Lang_koKR='다크문 축제' WHERE ID=364;
UPDATE dbc_questsort SET SortName_Lang_koKR='안퀴라즈 전쟁' WHERE ID=365;
UPDATE dbc_questsort SET SortName_Lang_koKR='달의 축제' WHERE ID=366;
UPDATE dbc_questsort SET SortName_Lang_koKR='평판' WHERE ID=367;
UPDATE dbc_questsort SET SortName_Lang_koKR='침공' WHERE ID=368;
UPDATE dbc_questsort SET SortName_Lang_koKR='한여름 불꽃축제' WHERE ID=369;
UPDATE dbc_questsort SET SortName_Lang_koKR='가을 축제' WHERE ID=370;
UPDATE dbc_questsort SET SortName_Lang_koKR='주문각인' WHERE ID=371;
UPDATE dbc_questsort SET SortName_Lang_koKR='죽음의 기사' WHERE ID=372;
UPDATE dbc_questsort SET SortName_Lang_koKR='보석세공' WHERE ID=373;
UPDATE dbc_questsort SET SortName_Lang_koKR='귀족의 정원' WHERE ID=374;
UPDATE dbc_questsort SET SortName_Lang_koKR='순례자의 감사절' WHERE ID=375;
UPDATE dbc_questsort SET SortName_Lang_koKR='온누리에 사랑을' WHERE ID=376;
