UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=1;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=2;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=3;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=4;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=5;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=6;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=126;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=163;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=522;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=7;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=8;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=9;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=10;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=11;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=12;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=13;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=14;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=15;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=16;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=17;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=18;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=19;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=20;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=21;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=22;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=23;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=24;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=25;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=26;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=323;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=27;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 시간의 열쇠가 필요합니다.' WHERE ID=127;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=28;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=29;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=30;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=31;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=32;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=33;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=34;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=35;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=36;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=37;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=38;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=39;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=40;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=41;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=42;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=43;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=44;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=45;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=46;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='80 레벨 이상의 플레이어만 참여할 수 있습니다.' WHERE ID=128;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=47;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=48;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 불꽃세공 열쇠가 필요합니다.' WHERE ID=129;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=49;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 불꽃세공 열쇠가 필요합니다.' WHERE ID=130;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=50;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 불꽃세공 열쇠가 필요합니다.' WHERE ID=131;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=51;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=52;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 저수지 열쇠가 필요합니다.' WHERE ID=132;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=53;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 저수지 열쇠가 필요합니다.' WHERE ID=133;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=54;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 저수지 열쇠가 필요합니다.' WHERE ID=134;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=55;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=56;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=57;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 초공간에서 벼려낸 열쇠가 필요합니다.' WHERE ID=135;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=58;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 초공간에서 벼려낸 열쇠가 필요합니다.' WHERE ID=136;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=59;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 초공간에서 벼려낸 열쇠가 필요합니다.' WHERE ID=137;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=60;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 아키나이 열쇠가 필요합니다.' WHERE ID=138;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=61;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 아키나이 열쇠가 필요합니다.' WHERE ID=139;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=62;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 아키나이 열쇠가 필요합니다.' WHERE ID=140;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=63;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 아키나이 열쇠가 필요합니다.' WHERE ID=141;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=64;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=65;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 시간의 열쇠가 필요합니다.' WHERE ID=142;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=66;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=67;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=68;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=69;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=70;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=71;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=72;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=73;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='65 레벨 이상의 플레이어만 참여할 수 있습니다.' WHERE ID=74;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='80 레벨 이상의 플레이어만 영웅 난이도에 진입할 수 있습니다.' WHERE ID=143;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=75;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='80 레벨 이상의 플레이어만 영웅 난이도에 진입할 수 있습니다.' WHERE ID=144;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='66 레벨 이상의 플레이어만 참여할 수 있습니다.' WHERE ID=76;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='80 레벨 이상의 플레이어만 영웅 난이도에 진입할 수 있습니다.' WHERE ID=145;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='75 레벨 이상의 플레이어만 참여할 수 있습니다.' WHERE ID=77;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='80 레벨 이상의 플레이어만 영웅 난이도에 진입할 수 있습니다.' WHERE ID=146;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=78;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=79;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=80;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=81;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 "어려운 상대" 퀘스트를 완료해야 합니다.' WHERE ID=147;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=82;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=83;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=84;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=85;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=86;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=87;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=88;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=89;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=90;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='75 레벨 이상의 플레이어만 참여할 수 있습니다.' WHERE ID=91;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='80 레벨 이상의 플레이어만 영웅 난이도에 진입할 수 있습니다.' WHERE ID=148;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=92;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=93;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=94;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='영웅 난이도로 진입하려면 태양으로 벼려낸 열쇠가 필요합니다.' WHERE ID=149;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='72 레벨 이상의 플레이어만 참여할 수 있습니다.' WHERE ID=95;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='80 레벨 이상의 플레이어만 영웅 난이도에 진입할 수 있습니다.' WHERE ID=150;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='69 레벨 이상의 플레이어만 참여할 수 있습니다.' WHERE ID=96;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='80 레벨 이상의 플레이어만 영웅 난이도에 진입할 수 있습니다.' WHERE ID=151;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='67 레벨 이상의 플레이어만 참여할 수 있습니다.' WHERE ID=97;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='80 레벨 이상의 플레이어만 영웅 난이도에 진입할 수 있습니다.' WHERE ID=152;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='75 레벨 이상의 플레이어만 참여할 수 있습니다.' WHERE ID=98;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='80 레벨 이상의 플레이어만 영웅 난이도에 진입할 수 있습니다.' WHERE ID=153;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=99;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=154;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='71 레벨 이상의 플레이어만 참여할 수 있습니다.' WHERE ID=100;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='80 레벨 이상의 플레이어만 영웅 난이도에 진입할 수 있습니다.' WHERE ID=155;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=101;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=102;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=103;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=301;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='70 레벨 이상의 플레이어만 참여할 수 있습니다.' WHERE ID=104;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='80 레벨 이상의 플레이어만 영웅 난이도에 진입할 수 있습니다.' WHERE ID=156;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=105;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=106;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=107;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=108;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=109;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=110;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='80 레벨 이상의 플레이어만 영웅 난이도에 진입할 수 있습니다.' WHERE ID=157;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=111;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=158;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=112;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=113;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='68 레벨 이상의 플레이어만 참여할 수 있습니다.' WHERE ID=114;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='80 레벨 이상의 플레이어만 영웅 난이도에 진입할 수 있습니다.' WHERE ID=159;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=115;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=116;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=117;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=118;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다. 또한 겨울손아귀 호수를 점령하고 있어야 합니다.' WHERE ID=119;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다. 또한 겨울손아귀 호수를 점령하고 있어야 합니다.' WHERE ID=160;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=120;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=281;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=485;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=486;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='10인 공격대에 참여하여 리치 왕을 처치한 플레이어만 10인 영웅 난이도에 도전할 수 있습니다.' WHERE ID=487;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='25인 공격대에 참여하여 리치 왕을 처치한 플레이어만 25인 영웅 난이도에 도전할 수 있습니다.' WHERE ID=488;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='75 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=481;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='80 레벨 이상의 플레이어만 영웅 난이도에 진입할 수 있습니다.' WHERE ID=482;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=121;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=122;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=123;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=124;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=161;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=221;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=222;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='75 레벨 이상의 플레이어만 참여할 수 있습니다.' WHERE ID=125;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='80 레벨 이상의 플레이어만 영웅 난이도에 진입할 수 있습니다.' WHERE ID=162;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='사론의 구덩이에 진입하려면 "괴로워하는 영혼의 메아리" 퀘스트를 완료해야 합니다.' WHERE ID=483;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='사론의 구덩이에 영웅 난이도로 진입하려면 80 레벨 이상이며 "괴로워하는 영혼의 메아리" 퀘스트를 완료해야 합니다.' WHERE ID=484;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='투영의 전당에 진입하려면 "구덩이로부터의 해방" 퀘스트를 완료해야 합니다.' WHERE ID=341;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='투영의 전당에 영웅 난이도로 진입하려면 80 레벨 이상이며 "구덩이로부터의 해방" 퀘스트를 완료해야 합니다.' WHERE ID=342;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=642;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=641;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=701;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='' WHERE ID=744;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=750;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=751;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=752;
UPDATE dbc_mapdifficulty SET Message_Lang_koKR='공격대에 참여한 80 레벨 이상의 플레이어만 진입할 수 있습니다.' WHERE ID=753;
