UPDATE dbc_battlemasterlist SET Name_Lang_esMX='Valle de Alterac' WHERE ID=1;
UPDATE dbc_battlemasterlist SET Name_Lang_esMX='Garganta Grito de Guerra' WHERE ID=2;
UPDATE dbc_battlemasterlist SET Name_Lang_esMX='Cuenca de Arathi' WHERE ID=3;
UPDATE dbc_battlemasterlist SET Name_Lang_esMX='Arena de Nagrand' WHERE ID=4;
UPDATE dbc_battlemasterlist SET Name_Lang_esMX='Arena Filospada' WHERE ID=5;
UPDATE dbc_battlemasterlist SET Name_Lang_esMX='Todas las arenas' WHERE ID=6;
UPDATE dbc_battlemasterlist SET Name_Lang_esMX='Ojo de la Tormenta' WHERE ID=7;
UPDATE dbc_battlemasterlist SET Name_Lang_esMX='Ruinas de Lordaeron' WHERE ID=8;
UPDATE dbc_battlemasterlist SET Name_Lang_esMX='Playa de los Ancestros' WHERE ID=9;
UPDATE dbc_battlemasterlist SET Name_Lang_esMX='Cloacas de Dalaran' WHERE ID=10;
UPDATE dbc_battlemasterlist SET Name_Lang_esMX='El Círculo del Valor' WHERE ID=11;
UPDATE dbc_battlemasterlist SET Name_Lang_esMX='Isla de la Conquista' WHERE ID=30;
UPDATE dbc_battlemasterlist SET Name_Lang_esMX='Campo de batalla aleatorio' WHERE ID=32;
