UPDATE dbc_creaturefamily SET Name_Lang_esMX='Lobo' WHERE ID=1;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Felino' WHERE ID=2;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Araña' WHERE ID=3;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Oso' WHERE ID=4;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Jabalí' WHERE ID=5;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Crocolisco' WHERE ID=6;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Carroñero' WHERE ID=7;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Cangrejo' WHERE ID=8;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Gorila' WHERE ID=9;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Raptor' WHERE ID=11;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Zancaalta' WHERE ID=12;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Manáfago' WHERE ID=15;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Abisario' WHERE ID=16;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Súcubo' WHERE ID=17;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Guardia apocalíptico' WHERE ID=19;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Escórpido' WHERE ID=20;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Tortuga' WHERE ID=21;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Diablillo' WHERE ID=23;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Murciélago' WHERE ID=24;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Hiena' WHERE ID=25;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Ave rapaz' WHERE ID=26;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Serpiente alada' WHERE ID=27;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Control remoto' WHERE ID=28;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Guardia vil' WHERE ID=29;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Dracohalcón' WHERE ID=30;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Devastador' WHERE ID=31;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Acechador deformado' WHERE ID=32;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Esporiélago' WHERE ID=33;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Raya abisal' WHERE ID=34;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Serpiente' WHERE ID=35;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Palomilla' WHERE ID=37;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Quimera' WHERE ID=38;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Demosaurio' WHERE ID=39;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Necrófago' WHERE ID=40;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Silítido' WHERE ID=41;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Gusano' WHERE ID=42;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Rinoceronte' WHERE ID=43;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Avispa' WHERE ID=44;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Can del Núcleo' WHERE ID=45;
UPDATE dbc_creaturefamily SET Name_Lang_esMX='Bestia espíritu' WHERE ID=46;
