UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Forma felina' WHERE ID=1;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Forma de árbol de vida' WHERE ID=2;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Forma de viaje' WHERE ID=3;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Forma acuática' WHERE ID=4;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Forma de oso' WHERE ID=5;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Ambiente' WHERE ID=6;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Necrófago' WHERE ID=7;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Forma de oso temible' WHERE ID=8;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Steve''s Ghoul' WHERE ID=9;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Esqueleto Tharon''ja' WHERE ID=10;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Luna Negra - Prueba de fuerza' WHERE ID=11;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='BLB Player' WHERE ID=12;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Danza de las Sombras' WHERE ID=13;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Criatura: oso' WHERE ID=14;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Criatura: felino' WHERE ID=15;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Lobo fantasmal' WHERE ID=16;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Actitud de batalla' WHERE ID=17;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Actitud defensiva' WHERE ID=18;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Actitud rabiosa' WHERE ID=19;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Test' WHERE ID=20;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Zombi' WHERE ID=21;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Metamorfosis' WHERE ID=22;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='' WHERE ID=23;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='' WHERE ID=24;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='No-muerto' WHERE ID=25;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Furia' WHERE ID=26;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Forma voladora, épica' WHERE ID=27;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Forma de las Sombras' WHERE ID=28;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Forma de vuelo' WHERE ID=29;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Sigilo' WHERE ID=30;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Forma de lechúcico lunar' WHERE ID=31;
UPDATE dbc_spellshapeshiftform SET Name_Lang_esMX='Espíritu redentor' WHERE ID=32;
