UPDATE dbc_taxinodes SET Name_Lang_esMX='Abadía de Villanorte' WHERE ID=1;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Ventormenta, Elwynn' WHERE ID=2;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Isla del programador' WHERE ID=3;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Colina del Centinela, Páramos de Poniente' WHERE ID=4;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Villa del Lago, Crestagrana' WHERE ID=5;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Forjaz, Dun Morogh' WHERE ID=6;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Puerto de Menethil, Los Humedales' WHERE ID=7;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Thelsamar, Loch Modan' WHERE ID=8;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bahía del Botín, Tuercespina' WHERE ID=9;
UPDATE dbc_taxinodes SET Name_Lang_esMX='El Sepulcro, Bosque de Argénteos' WHERE ID=10;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Entrañas, Tirisfal' WHERE ID=11;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Villa Oscura, Bosque del Ocaso' WHERE ID=12;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Molino Tarren, Trabalomas' WHERE ID=13;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Costasur, Trabalomas' WHERE ID=14;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Tierras de la Peste del Este' WHERE ID=15;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Refugio de la Zaga, Arathi' WHERE ID=16;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Sentencia, Arathi' WHERE ID=17;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bahía del Botín, Tuercespina' WHERE ID=18;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bahía del Botín, Tuercespina' WHERE ID=19;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Grom''gol, Tuercespina' WHERE ID=20;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Kargath, Tierras Inhóspitas' WHERE ID=21;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Cima del Trueno, Mulgore' WHERE ID=22;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Orgrimmar, Durotar' WHERE ID=23;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Genérico, Objetivo mundial 002' WHERE ID=24;
UPDATE dbc_taxinodes SET Name_Lang_esMX='El Cruce, Los Baldíos' WHERE ID=25;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Auberdine, Costa Oscura' WHERE ID=26;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Aldea Rut''theran, Teldrassil' WHERE ID=27;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Astranaar, Vallefresno' WHERE ID=28;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Refugio Roca del Sol, Sierra Espolón' WHERE ID=29;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Poblado Viento Libre, Las Mil Agujas' WHERE ID=30;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Thalanaar, Feralas' WHERE ID=31;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Theramore, Marjal Revolcafango' WHERE ID=32;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Cima del Espolón, Sierra Espolón' WHERE ID=33;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Bahía del Botín' WHERE ID=34;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Orgrimmar' WHERE ID=35;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Genérico, Objetivo mundial 001' WHERE ID=36;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Punta de Nijel, Desolace' WHERE ID=37;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Aldea Cazasombras, Desolace' WHERE ID=38;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Gadgetzan, Tanaris' WHERE ID=39;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Gadgetzan, Tanaris' WHERE ID=40;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Plumaluna, Feralas' WHERE ID=41;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Campamento Mojache, Feralas' WHERE ID=42;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Pico Nidal, Tierras del Interior' WHERE ID=43;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Valormok, Azshara' WHERE ID=44;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Castillo de Nethergarde, Las Tierras Devastadas' WHERE ID=45;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Costasur' WHERE ID=46;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Grom''gol' WHERE ID=47;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Puesto del Veneno' WHERE ID=48;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Claro de la Luna' WHERE ID=49;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Puerto de Menethil' WHERE ID=50;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Auberdine' WHERE ID=51;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Vista Eterna, Cuna del Invierno' WHERE ID=52;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Vista Eterna, Cuna del Invierno' WHERE ID=53;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Plumaluna' WHERE ID=54;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Poblado Murohelecho, Marjal Revolcafango' WHERE ID=55;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Rocal, Pantano de las Penas' WHERE ID=56;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Aldea Pesquera, Teldrassil' WHERE ID=57;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Avanzada de Zoram''gar, Vallefresno' WHERE ID=58;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Dun Baldar, Valle de Alterac' WHERE ID=59;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bastión Lobo Gélido, Valle de Alterac' WHERE ID=60;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Puesto del Hachazo, Vallefresno' WHERE ID=61;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Amparo de la Noche, Claro de la Luna' WHERE ID=62;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Amparo de la Noche, Claro de la Luna' WHERE ID=63;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Punta Talrendis, Azshara' WHERE ID=64;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Claro Ramaespolón, Frondavil' WHERE ID=65;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Campamento del Orvallo, Tierras de la Peste del Oeste' WHERE ID=66;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Capilla de la Esperanza de la Luz, Tierras de la Peste del Este' WHERE ID=67;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Capilla de la Esperanza de la Luz, Tierras de la Peste del Este' WHERE ID=68;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Claro de la Luna' WHERE ID=69;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Peñasco Llamarada, Las Estepas Ardientes' WHERE ID=70;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Vigilia de Morgan, Las Estepas Ardientes' WHERE ID=71;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Fuerte Cenarion, Silithus' WHERE ID=72;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Fuerte Cenarion, Silithus' WHERE ID=73;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Puesto del Torio, La Garganta de Fuego' WHERE ID=74;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Puesto del Torio, La Garganta de Fuego' WHERE ID=75;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Poblado Sañadiente, Tierras del Interior' WHERE ID=76;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Campamento Taurajo, Los Baldíos' WHERE ID=77;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Naxxramas' WHERE ID=78;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Refugio de Marshal, Cráter de Un''Goro' WHERE ID=79;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Trinquete, Los Baldíos' WHERE ID=80;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Grabando' WHERE ID=81;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Ciudad de Lunargenta' WHERE ID=82;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Tranquilien, Tierras Fantasma' WHERE ID=83;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Torre del Bosque de la Peste, Tierras de la Peste de Este' WHERE ID=84;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Torre del Paso Norte, Tierras de la Peste del Este' WHERE ID=85;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Torre de la Muralla del Este, Tierras de la Peste del Este' WHERE ID=86;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Torre de la Corona, Tierras de la Peste del Este' WHERE ID=87;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, El Exodar' WHERE ID=88;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Theramore' WHERE ID=89;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Entrañas' WHERE ID=90;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Chamán Bruma Azur Objetivo' WHERE ID=91;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Chamán Bruma Azur Comienzo' WHERE ID=92;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Avanzada de Sangre, Isla Bruma de Sangre' WHERE ID=93;
UPDATE dbc_taxinodes SET Name_Lang_esMX='El Exodar' WHERE ID=94;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Marisma de Zangar - Misión - Mientras el cuervo vuela' WHERE ID=95;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Marisma de Zangar - Misión - Mientras el cuervo vuela - Fin' WHERE ID=96;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - El camino de Elekk a Kessel' WHERE ID=97;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - De Elekk a Kessel Objetivo' WHERE ID=98;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Thrallmar, Península del Fuego Infernal' WHERE ID=99;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bastión del Honor, Península del Fuego Infernal' WHERE ID=100;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Templo de Telhamat, Península del Fuego Infernal' WHERE ID=101;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Avanzada del Halcón, Península del Fuego Infernal' WHERE ID=102;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Nagrand - JcJ - Ataque 1 Puesta en Marcha Comienzo' WHERE ID=103;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Nagrand - JcJ - Ataque 1 Puesta en Marcha Fin' WHERE ID=104;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Nagrand - JcJ - Ataque 2 Puesta en Marcha Comienzo' WHERE ID=105;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Nagrand - JcJ - Ataque 2 Puesta en Marcha Fin' WHERE ID=106;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Nagrand - JcJ - Ataque 3 Puesta en Marcha Comienzo' WHERE ID=107;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Nagrand - JcJ - Ataque 3 Puesta en Marcha Fin' WHERE ID=108;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Nagrand - JcJ - Ataque 4 Puesta en Marcha Comienzo' WHERE ID=109;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Nagrand - JcJ - Ataque 4 Puesta en Marcha Fin' WHERE ID=110;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bosque Canción Eterna, Teletransporte a Ocaso Marchito' WHERE ID=111;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bosque Canción Eterna, Teletransporte a Ocaso Marchito Fin' WHERE ID=112;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión,  Nethrandamus Comienzo' WHERE ID=113;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión,  Nethrandamus Fin Objetivo' WHERE ID=114;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Cavernas del Tiempo OH - Comienzo' WHERE ID=115;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Cavernas del Tiempo OH - Fin' WHERE ID=116;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Telredor, Marisma de Zangar' WHERE ID=117;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Zabra''jin, Marisma de Zangar' WHERE ID=118;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Telaar, Nagrand' WHERE ID=119;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Garadar, Nagrand' WHERE ID=120;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bastión Allerian, Bosque de Terokkar' WHERE ID=121;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Área 52, Tormenta Abisal' WHERE ID=122;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Aldea Sombraluna, Valle Sombraluna' WHERE ID=123;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bastión Martillo Salvaje, Valle Sombraluna' WHERE ID=124;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Sylvanaar, Montañas Filospada' WHERE ID=125;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bastión Señor del Trueno, Montañas Filospada' WHERE ID=126;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bastión Rompepedras, Bosque de Terokkar' WHERE ID=127;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Shattrath, Bosque de Terokkar' WHERE ID=128;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Península del Fuego Infernal, El Portal Oscuro, Alianza' WHERE ID=129;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Península del Fuego Infernal, El Portal Oscuro, Horda' WHERE ID=130;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fuego Infernal Horda Comienzo' WHERE ID=131;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fuego Infernal Horda Fin' WHERE ID=132;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Península del Fuego Infernal (Camino Alianza) Comienzo' WHERE ID=133;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Península del Fuego Infernal (Alianza) Fin' WHERE ID=134;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fuego Infernal, Misión Aérea (Horda) Comienzo' WHERE ID=135;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fuego Infernal, Misión Aérea (Horda) Fin' WHERE ID=136;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fuego Infernal, Misión Aérea (Alianza) Comienzo' WHERE ID=137;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fuego Infernal, Misión Aérea (Alianza) Fin' WHERE ID=138;
UPDATE dbc_taxinodes SET Name_Lang_esMX='La Flecha de la Tormenta, Tormenta Abisal' WHERE ID=139;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Altar de Sha''tar, Valle Sombraluna' WHERE ID=140;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Cresta Rompeloma, Península del Fuego Infernal' WHERE ID=141;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Península del Fuego Infernal - Caída del Atracador Vil' WHERE ID=142;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Cavernas del Tiempo (Ruta de Vuelo) (Fin)' WHERE ID=143;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Cavernas del Tiempo (Ruta de Vuelo) (Comienzo)' WHERE ID=144;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Tormenta Abisal - Vuelo sigilo - Comienzo' WHERE ID=145;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Tormenta Abisal - Vuelo en sigilo - Fin' WHERE ID=146;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Península del Fuego Infernal - Force Camp Beach Head' WHERE ID=147;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Puesto Devastación, Península del Fuego Infernal (Asalto a la playa)' WHERE ID=148;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Puesto Devastación, Península del Fuego Infernal' WHERE ID=149;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Cosmotirón, Tormenta Abisal' WHERE ID=150;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Avanzada Rata del Pantano, Marisma de Zangar' WHERE ID=151;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Tormenta Abisal - Forja de Maná Ultris (Comienzo)' WHERE ID=152;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Tormenta Abisal - Forja de Maná Ultris (Fin)' WHERE ID=153;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Tormenta Abisal - Forja de Maná Ultris (Segundo Paso) Comienzo' WHERE ID=154;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Tormenta Abisal - Forja de Maná Ultris (Segundo Paso) Fin' WHERE ID=155;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Estación de Toshley, Montañas Filospada' WHERE ID=156;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Filospada - Guía de visión - Comienzo' WHERE ID=157;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Filospada - Guía de visión - Fin' WHERE ID=158;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Sagrario de las Estrellas, Valle Sombraluna' WHERE ID=159;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Soto Eterno, Montañas Filospada' WHERE ID=160;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Aliado dragón abisal - Comienzo' WHERE ID=161;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Aliado dragón abisal - Fin' WHERE ID=162;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Aldea Mok''Nathal, Montañas Filospada' WHERE ID=163;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Puerto Orebor, Marisma de Zangar' WHERE ID=164;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Rasganorte 2' WHERE ID=165;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Santuario Esmeralda, Frondavil' WHERE ID=166;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Canción del Bosque, Vallefresno' WHERE ID=167;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Grabando' WHERE ID=168;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Arrecife del Ala Abisal – Paseo en vagoneta – Sur - Comienzo' WHERE ID=169;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Arrecife del Ala Abisal – Paseo en vagoneta – Sur – Fin' WHERE ID=170;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Skettis' WHERE ID=171;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Ogri''la' WHERE ID=172;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Vuelo de Yarzill, Inicio' WHERE ID=173;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Vuelo de Yarzill, Fin' WHERE ID=174;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Fiordo Aquilonal' WHERE ID=175;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fiordo Aquilonal, Canoa tauren (Inicio)' WHERE ID=176;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fiordo Aquilonal, Canoa tauren (Fin)' WHERE ID=177;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Tundra Boreal' WHERE ID=178;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Piñón de Barro, Marjal Revolcafango' WHERE ID=179;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Revolcafango, Inicio de sondeo de Alcaz' WHERE ID=180;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Revolcafango, Fin de sondeo de Alcaz' WHERE ID=181;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fiordo Aquilonal, Zepelín de Rompe el bloqueo' WHERE ID=182;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Puerto de Valgarde, Fiordo Aquilonal' WHERE ID=183;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Fuerte Vildervar, Fiordo Aquilonal' WHERE ID=184;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Fortaleza de la Guardia Oeste, Fiordo Aquilonal' WHERE ID=185;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fiordo Aquilonal, Vuelo a El Brisaveloz - Inicio' WHERE ID=186;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fiordo Aquilonal, Vuelo a El Brisaveloz - Fin' WHERE ID=187;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fiordo Aquilonal, Test at Sea - Inicio' WHERE ID=188;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fiordo Aquilonal, Test at Sea - Fin' WHERE ID=189;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Nuevo Agamand, Fiordo Aquilonal' WHERE ID=190;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Campo Venganza, Fiordo Aquilonal' WHERE ID=191;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Campamento Pezuña Invernal, Fiordo Aquilonal' WHERE ID=192;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fiordo Aquilonal, Misión: Echar pestes - Fin' WHERE ID=193;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fiordo Aquilonal, Misión: Echar pestes - Inicio' WHERE ID=194;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Asentamiento Rebelde, Vega de Tuercespina' WHERE ID=195;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Test - SP' WHERE ID=196;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Test SP2' WHERE ID=197;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Test SP1' WHERE ID=198;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fiordo Aquilonal, McGoyver Inicio' WHERE ID=199;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fiordo Aquilonal, McGoyver Fin' WHERE ID=200;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Territorio en desarrollo - Kyle Radue inicio' WHERE ID=201;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Territorio en desarrollo - Kyle Radue Fin' WHERE ID=202;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Reposo Estelar -> Hibergarde' WHERE ID=203;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Nuevo Agamand -> Rencor Venenoso' WHERE ID=204;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Zul''Aman, Tierras Fantasma' WHERE ID=205;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Plumaluna (barco NE)' WHERE ID=206;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fiordo Aquilonal, Hermana Misericordia (Inicio)' WHERE ID=207;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fiordo Aquilonal, Hermana Misericordia (Fin)' WHERE ID=208;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, diaria de Fuente del Sol, bombardeo de La Cicatriz Muerta - Inicio' WHERE ID=209;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, diaria de Fuente del Sol, bombardeo de La Cicatriz Muerta - Fin' WHERE ID=210;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, diaria de Fuente del Sol, bombardeo de barco - Inicio' WHERE ID=211;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, diaria de Fuente del Sol, bombardeo de barco - Fin' WHERE ID=212;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Zona de escala de Sol Devastado' WHERE ID=213;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fiordo Aquilonal, Naglfar (Inicio)' WHERE ID=214;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Fiordo Aquilonal, Naglfar (Nodos)' WHERE ID=215;
UPDATE dbc_taxinodes SET Name_Lang_esMX='' WHERE ID=216;
UPDATE dbc_taxinodes SET Name_Lang_esMX='' WHERE ID=217;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Fiordo Aquilonal (Góndola, superior)' WHERE ID=218;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Fiordo Aquilonal (Góndola, inferior)' WHERE ID=219;
UPDATE dbc_taxinodes SET Name_Lang_esMX='' WHERE ID=220;
UPDATE dbc_taxinodes SET Name_Lang_esMX='El Saliente Ámbar, Boreal (a Berilo)' WHERE ID=221;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Alto de Berilo, Boreal' WHERE ID=222;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Naglevar' WHERE ID=223;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Tundra Boreal, Naglevar' WHERE ID=224;
UPDATE dbc_taxinodes SET Name_Lang_esMX='El Saliente Ámbar, Boreal (a Gelidar)' WHERE ID=225;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Escudo de Tránsito, Gelidar' WHERE ID=226;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transport, PattyMacDevTest' WHERE ID=227;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Development Land - Pat Test Start' WHERE ID=228;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Development Land - Pat Test End' WHERE ID=229;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, colmillarr 01' WHERE ID=230;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, colmillarr 02' WHERE ID=231;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Tundra Boreal, Lobo de Bastión Grito de Guerra inicio' WHERE ID=232;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Tundra Boreal, Lobo de Bastión Grito de Guerra Fin' WHERE ID=233;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Saliente de Gelidar, Gelidar' WHERE ID=234;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Escudo de Tránsito, Gelidar (NOT USED)' WHERE ID=235;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Gelidar, Keristrasza a Malygos' WHERE ID=236;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Gelidar, Alto de Keristrasza' WHERE ID=237;
UPDATE dbc_taxinodes SET Name_Lang_esMX='' WHERE ID=238;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Tundra Boreal, Misión, Anochecer, Final' WHERE ID=239;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Tundra Boreal, Misión, Anochecer, Inicio' WHERE ID=240;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Fortaleza Denuedo' WHERE ID=241;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Cementerio de Dragones - Visión espiritual - Comienzo' WHERE ID=242;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Cementerio de Dragones - Visión espiritual - Fin' WHERE ID=243;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Fortaleza de Hibergarde, Cementerio de Dragones' WHERE ID=244;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Fortaleza Denuedo, Tundra Boreal' WHERE ID=245;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Pista de Aterrizaje de Palanqueta, Tundra Boreal' WHERE ID=246;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Reposo Estelar, Cementerio de Dragones' WHERE ID=247;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Campamento de los Boticarios, Fiordo Aquilonal' WHERE ID=248;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Campamento Oneqwah, Colinas Pardas' WHERE ID=249;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bastión de la Conquista, Colinas Pardas' WHERE ID=250;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bastión de Fordragón, Cementerio de Dragones' WHERE ID=251;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Templo del Reposo del Dragón, Cementerio de Dragones' WHERE ID=252;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Refugio Pino Ámbar, Colinas Pardas' WHERE ID=253;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Rencor Venenoso, Cementerio de Dragones' WHERE ID=254;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Brigada de los Páramos de Poniente, Colinas Pardas' WHERE ID=255;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Martillo de Agmar, Cementerio de Dragones' WHERE ID=256;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bastión Grito de Guerra, Tundra Boreal' WHERE ID=257;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Poblado Taunka''le, Tundra Boreal' WHERE ID=258;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Avanzada Bor''gorok, Tundra Boreal' WHERE ID=259;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Vanguardia Kor''kron, Cementerio de Dragones' WHERE ID=260;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión – Reposo Estelar a Hibergarde Fin' WHERE ID=261;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Colinas Pardas, comienzo de viaje de la Alianza 01' WHERE ID=262;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Colinas Pardas, fin de viaje de la Alianza 01' WHERE ID=263;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Auberdine (NUEVO)' WHERE ID=264;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Theramore (NUEVO)' WHERE ID=265;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Menethil (NUEVO)' WHERE ID=266;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Colinas Pardas, comienzo de viaje de la Alianza' WHERE ID=267;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Colinas Pardas, fin de viaje de la Alianza' WHERE ID=268;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Fortaleza de la Guardia Oeste a Fortaleza de Hibergarde Comienzo' WHERE ID=269;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Fortaleza de la Guardia Oeste a Fortaleza de Hibergarde Fin' WHERE ID=270;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Colinas Pardas, comienzo de viaje de la Horda' WHERE ID=271;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Colinas Pardas, fin de viaje de la Horda' WHERE ID=272;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Templo del Reposo del Dragón - de abajo a arriba, Cementerio de Dragones - Comienzo' WHERE ID=273;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Templo del Reposo del Dragón - de abajo a arriba, Cementerio de Dragones - Fin' WHERE ID=274;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Templo del Reposo del Dragón - de arriba a abajo, Cementerio de Dragones - Comienzo' WHERE ID=275;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Templo del Reposo del Dragón - de arriba a abajo, Cementerio de Dragones - Fin' WHERE ID=276;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Templo del Reposo del Dragón - de arriba a la mitad, Cementerio de Dragones – Comienzo' WHERE ID=277;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Templo del Reposo del Dragón - de arriba a la mitad, Cementerio de Dragones -Fin' WHERE ID=278;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Templo del Reposo del Dragón – de la mitad a arriba, Cementerio de Dragones - Fin' WHERE ID=279;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Templo del Reposo del Dragón – de la mitad a arriba, Cementerio de Dragones - Comienzo' WHERE ID=280;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Templo del Reposo del Dragón – de la mitad abajo, Cementerio de Dragones - Fin' WHERE ID=281;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Templo del Reposo del Dragón – de la mitad abajo, Cementerio de Dragones - Comienzo' WHERE ID=282;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Templo del Reposo del Dragón - de abajo a la mitad, Cementerio de Dragones - Fin' WHERE ID=283;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Templo del Reposo del Dragón - de abajo a la mitad, Cementerio de Dragones - Comienzo' WHERE ID=284;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión – Hibergarde -> Reposo Estelar (Comienzo)' WHERE ID=285;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión – Hibergarde -> Reposo Estelar (Fin)' WHERE ID=286;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Valgarde -> Fortaleza de la Guardia Oeste Inicio' WHERE ID=287;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión - Valgarde -> Fortaleza de la Guardia Oeste Fin' WHERE ID=288;
UPDATE dbc_taxinodes SET Name_Lang_esMX='El Saliente Ámbar, Tundra Boreal' WHERE ID=289;
UPDATE dbc_taxinodes SET Name_Lang_esMX='El Confín Argenta, Zul''Drak' WHERE ID=290;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Puesto 01 de la Ciudad en Ruinas, Zul''Drak' WHERE ID=291;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Flavor - Stormwind Harbor  - Start' WHERE ID=292;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Flavor - Stormwind Harbor - Stop' WHERE ID=293;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Moa''ki, Cementerio de Dragones' WHERE ID=294;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Komawa, Fiordo Aquilonal' WHERE ID=295;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Unu''pe, Tundra Boreal' WHERE ID=296;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Cuenca de Sholazar, misión, reconocimiento, comienzo' WHERE ID=297;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Cuenca de Sholazar, misión, reconocimiento, fin' WHERE ID=298;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte: Menethil <-> Valgarde' WHERE ID=299;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Ventormenta' WHERE ID=300;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Tundra Boreal, Preséntate ante Bixie, comienzo' WHERE ID=301;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Tundra Boreal, Preséntate ante Bixie, final' WHERE ID=302;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Campamento de Aterrizaje de Denuedo, Conquista del Invierno' WHERE ID=303;
UPDATE dbc_taxinodes SET Name_Lang_esMX='El Confín Argenta, Zul''Drak' WHERE ID=304;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Puesto de Vigilancia de Ébano, Zul''Drak' WHERE ID=305;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Brecha de la Luz, Zul''Drak' WHERE ID=306;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Zim''Torga, Zul''Drak' WHERE ID=307;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Corazón del Río, Cuenca de Sholazar' WHERE ID=308;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Campamento Base de Nesingwary, Cuenca de Sholazar' WHERE ID=309;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Dalaran' WHERE ID=310;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Campamento Oneqwah, Colinas Pardas (Misión)' WHERE ID=311;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Brecha de la Luz, Zul''Drak (misión)' WHERE ID=312;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Brigada de los Páramos de Poniente, Colinas Pardas (Misión)' WHERE ID=313;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Zim''Torga, Zul''Drak (Misión)' WHERE ID=314;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Acherus: El Bastión de Ébano' WHERE ID=315;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bastión de Ébano - Acherus -> Brecha de la Muerte, Final' WHERE ID=316;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bastión de Ébano - Acherus -> Brecha de la Muerte, Inicio' WHERE ID=317;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bastión de Ébano - Brecha de la Muerte -> Acherus, Inicio' WHERE ID=318;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Bastión de Ébano - Brecha de la Muerte -> Acherus, Final' WHERE ID=319;
UPDATE dbc_taxinodes SET Name_Lang_esMX='K3, Las Cumbres Tormentosas' WHERE ID=320;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Fuerte Escarcha, Las Cumbres Tormentosas' WHERE ID=321;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Dun Nifflelem, Las Cumbres Tormentosas' WHERE ID=322;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Lugar del accidente de Grom''arsh, Las Cumbres Tormentosas' WHERE ID=323;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Campamento Tunka''lo, Las Cumbres Tormentosas' WHERE ID=324;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Ascenso de la Muerte, Corona de Hielo' WHERE ID=325;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Ulduar, Las Cumbres Tormentosas' WHERE ID=326;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Refugio de Pedruscón, Las Cumbres Tormentosas' WHERE ID=327;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Dirigible Corona de Hielo (A)' WHERE ID=328;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Dirigible Corona de Hielo (H)' WHERE ID=329;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte, Corona de Hielo (objetivo)' WHERE ID=330;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Gundrak, Zul''Drak' WHERE ID=331;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Campamento Grito de Guerra, Conquista del Invierno' WHERE ID=332;
UPDATE dbc_taxinodes SET Name_Lang_esMX='La Cámara de las Sombras, Corona de Hielo' WHERE ID=333;
UPDATE dbc_taxinodes SET Name_Lang_esMX='La Vanguardia Argenta, Corona de Hielo' WHERE ID=334;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Pináculo de los Cruzados, Corona de Hielo' WHERE ID=335;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Mirador Brisaveloz, Bosque Canto de Cristal' WHERE ID=336;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Dominio de los Atracasol, Bosque Canto de Cristal' WHERE ID=337;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Campos del Torneo Argenta, Corona de Hielo' WHERE ID=340;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Banda Ulduar: Interior: Punto de Entrada' WHERE ID=341;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Banda Ulduar: Explanada de Hierro' WHERE ID=342;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Transporte: Cima del Trueno <-> Orgrimmar (Zepelín)' WHERE ID=348;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Isla de la Conquista, Barcos de guerra' WHERE ID=352;
UPDATE dbc_taxinodes SET Name_Lang_esMX='' WHERE ID=353;
UPDATE dbc_taxinodes SET Name_Lang_esMX='' WHERE ID=357;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Corona de Hielo, Bombardeo del Kraken de El Mar del Norte (Inicio)' WHERE ID=358;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, Corona de Hielo, Bombardeo del Kraken de El Mar del Norte (Fin)' WHERE ID=359;
UPDATE dbc_taxinodes SET Name_Lang_esMX='REUSEME' WHERE ID=375;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Banda de la Corona de Hielo - Rutas de vuelo de la batalla aérea' WHERE ID=376;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Mazmorra de Corona de Hielo, naves de guerra' WHERE ID=377;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Banda de la Corona de Hielo - Nave de Colmillosauro (fin)' WHERE ID=379;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Banda de la Corona de Hielo - Nave de Colmillosauro (inicio)' WHERE ID=380;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, transporte, banda de la Corona de Hielo - Nave de Colmillosauro (inicio)' WHERE ID=381;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Misión, banda de la Corona de Hielo - Nave de Colmillosauro (fin)' WHERE ID=382;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Río Thondroril, Tierras de la Peste del Oeste' WHERE ID=383;
UPDATE dbc_taxinodes SET Name_Lang_esMX='El Baluarte, Tirisfal' WHERE ID=384;
UPDATE dbc_taxinodes SET Name_Lang_esMX='CC Prologue - GT - Quest - Vent Horizon - Start' WHERE ID=392;
UPDATE dbc_taxinodes SET Name_Lang_esMX='CC Prologue - GT - Quest - Vent Horizon - End' WHERE ID=393;
UPDATE dbc_taxinodes SET Name_Lang_esMX='CC Prologue - GT - Battle Flight - Start' WHERE ID=394;
UPDATE dbc_taxinodes SET Name_Lang_esMX='CC Prologue - GT - Battle Flight - End' WHERE ID=395;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Durotar - ET - CC Prologue Spy Frog Start' WHERE ID=404;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Durotar - ET - CC Prologue Spy Frog End' WHERE ID=405;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Durotar - ET - CC Prologue Troll Taxi Bat Start' WHERE ID=438;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Durotar - ET - CC Prologue Troll Recruit End' WHERE ID=439;
UPDATE dbc_taxinodes SET Name_Lang_esMX='Durotar - ET - CC Prologue - Troll Battle End' WHERE ID=440;
