UPDATE dbc_faction SET Name_Lang_esMX='JUGADOR, humano', Description_Lang_esMX='' WHERE ID=1;
UPDATE dbc_faction SET Name_Lang_esMX='JUGADOR, orco', Description_Lang_esMX='' WHERE ID=2;
UPDATE dbc_faction SET Name_Lang_esMX='JUGADOR, enano', Description_Lang_esMX='' WHERE ID=3;
UPDATE dbc_faction SET Name_Lang_esMX='JUGADOR, elfo de la noche', Description_Lang_esMX='' WHERE ID=4;
UPDATE dbc_faction SET Name_Lang_esMX='JUGADOR, no-muerto', Description_Lang_esMX='' WHERE ID=5;
UPDATE dbc_faction SET Name_Lang_esMX='JUGADOR, tauren', Description_Lang_esMX='' WHERE ID=6;
UPDATE dbc_faction SET Name_Lang_esMX='Criatura', Description_Lang_esMX='' WHERE ID=7;
UPDATE dbc_faction SET Name_Lang_esMX='JUGADOR, gnomo', Description_Lang_esMX='' WHERE ID=8;
UPDATE dbc_faction SET Name_Lang_esMX='JUGADOR, trol', Description_Lang_esMX='' WHERE ID=9;
UPDATE dbc_faction SET Name_Lang_esMX='Monstruo', Description_Lang_esMX='' WHERE ID=14;
UPDATE dbc_faction SET Name_Lang_esMX='Hermandad Defias', Description_Lang_esMX='' WHERE ID=15;
UPDATE dbc_faction SET Name_Lang_esMX='Gnoll: Zarparrío', Description_Lang_esMX='' WHERE ID=16;
UPDATE dbc_faction SET Name_Lang_esMX='Gnoll: Crestagrana', Description_Lang_esMX='' WHERE ID=17;
UPDATE dbc_faction SET Name_Lang_esMX='Gnoll: Pielsombra', Description_Lang_esMX='' WHERE ID=18;
UPDATE dbc_faction SET Name_Lang_esMX='Múrloc', Description_Lang_esMX='' WHERE ID=19;
UPDATE dbc_faction SET Name_Lang_esMX='No-muertos, Plaga', Description_Lang_esMX='' WHERE ID=20;
UPDATE dbc_faction SET Name_Lang_esMX='Bahía del Botín', Description_Lang_esMX='Esta ciudad costera en auge está dirigida por el Barón Revilgaz, de los Asaltantes Aguasnegras. Son enemigos mortales de los Bucaneros Velasangre y forman parte del Cártel Bonvapor.' WHERE ID=21;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: araña', Description_Lang_esMX='' WHERE ID=22;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: jabalí', Description_Lang_esMX='' WHERE ID=23;
UPDATE dbc_faction SET Name_Lang_esMX='Huargen', Description_Lang_esMX='' WHERE ID=24;
UPDATE dbc_faction SET Name_Lang_esMX='Kóbold', Description_Lang_esMX='' WHERE ID=25;
UPDATE dbc_faction SET Name_Lang_esMX='Trol, Sangrapellejo', Description_Lang_esMX='' WHERE ID=26;
UPDATE dbc_faction SET Name_Lang_esMX='Trol, Machacacráneos', Description_Lang_esMX='' WHERE ID=27;
UPDATE dbc_faction SET Name_Lang_esMX='Presa', Description_Lang_esMX='' WHERE ID=28;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: lobo', Description_Lang_esMX='' WHERE ID=29;
UPDATE dbc_faction SET Name_Lang_esMX='Traidor de la Hermandad Defias', Description_Lang_esMX='' WHERE ID=30;
UPDATE dbc_faction SET Name_Lang_esMX='Amistoso', Description_Lang_esMX='' WHERE ID=31;
UPDATE dbc_faction SET Name_Lang_esMX='Trogg', Description_Lang_esMX='' WHERE ID=32;
UPDATE dbc_faction SET Name_Lang_esMX='Trol, Peloescarcha', Description_Lang_esMX='' WHERE ID=33;
UPDATE dbc_faction SET Name_Lang_esMX='Orco, Roca Negra', Description_Lang_esMX='' WHERE ID=34;
UPDATE dbc_faction SET Name_Lang_esMX='Villian', Description_Lang_esMX='' WHERE ID=35;
UPDATE dbc_faction SET Name_Lang_esMX='Víctima', Description_Lang_esMX='' WHERE ID=36;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: oso', Description_Lang_esMX='' WHERE ID=37;
UPDATE dbc_faction SET Name_Lang_esMX='Ogro', Description_Lang_esMX='' WHERE ID=38;
UPDATE dbc_faction SET Name_Lang_esMX='Mercenarios de Kurzen', Description_Lang_esMX='' WHERE ID=39;
UPDATE dbc_faction SET Name_Lang_esMX='Acompañante', Description_Lang_esMX='' WHERE ID=40;
UPDATE dbc_faction SET Name_Lang_esMX='Ventura y Cía.', Description_Lang_esMX='' WHERE ID=41;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: raptor', Description_Lang_esMX='' WHERE ID=42;
UPDATE dbc_faction SET Name_Lang_esMX='Basilisco', Description_Lang_esMX='' WHERE ID=43;
UPDATE dbc_faction SET Name_Lang_esMX='Vuelo, Verde', Description_Lang_esMX='' WHERE ID=44;
UPDATE dbc_faction SET Name_Lang_esMX='Los Perdidos', Description_Lang_esMX='' WHERE ID=45;
UPDATE dbc_faction SET Name_Lang_esMX=' Herrería: armaduras', Description_Lang_esMX='' WHERE ID=46;
UPDATE dbc_faction SET Name_Lang_esMX='Forjaz', Description_Lang_esMX='Esta capital de la Alianza es el orgullo de los enanos de Dun Morogh y hogar del Rey Magni.' WHERE ID=47;
UPDATE dbc_faction SET Name_Lang_esMX='Enanos Hierro Negro', Description_Lang_esMX='' WHERE ID=48;
UPDATE dbc_faction SET Name_Lang_esMX='Humano, Guardia Nocturna', Description_Lang_esMX='' WHERE ID=49;
UPDATE dbc_faction SET Name_Lang_esMX='Vuelo, Rojo', Description_Lang_esMX='' WHERE ID=50;
UPDATE dbc_faction SET Name_Lang_esMX='Gnoll: Pellejomusgo', Description_Lang_esMX='' WHERE ID=51;
UPDATE dbc_faction SET Name_Lang_esMX='Orco, Faucedraco', Description_Lang_esMX='' WHERE ID=52;
UPDATE dbc_faction SET Name_Lang_esMX='Gnomo: paria', Description_Lang_esMX='' WHERE ID=53;
UPDATE dbc_faction SET Name_Lang_esMX='Exiliados de Gnomeregan', Description_Lang_esMX='Los antiguos habitantes de Gnomeregan viven ahora su exilio en Forjaz, asociados con la Alianza.' WHERE ID=54;
UPDATE dbc_faction SET Name_Lang_esMX='Leopardo', Description_Lang_esMX='' WHERE ID=55;
UPDATE dbc_faction SET Name_Lang_esMX='Cruzada Escarlata', Description_Lang_esMX='' WHERE ID=56;
UPDATE dbc_faction SET Name_Lang_esMX='Gnoll: Putrepellejo', Description_Lang_esMX='' WHERE ID=57;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: gorila', Description_Lang_esMX='' WHERE ID=58;
UPDATE dbc_faction SET Name_Lang_esMX='Hermandad del Torio', Description_Lang_esMX='Los enanos de la Hermandad del Torio son la personificación de la excelencia en la artesanía y están decididos a desvelar los secretos de la Montaña Roca Negra.' WHERE ID=59;
UPDATE dbc_faction SET Name_Lang_esMX='Naga', Description_Lang_esMX='' WHERE ID=60;
UPDATE dbc_faction SET Name_Lang_esMX='Dalaran', Description_Lang_esMX='' WHERE ID=61;
UPDATE dbc_faction SET Name_Lang_esMX='Espíritu Abandonado', Description_Lang_esMX='' WHERE ID=62;
UPDATE dbc_faction SET Name_Lang_esMX='Aullido Oscuro', Description_Lang_esMX='' WHERE ID=63;
UPDATE dbc_faction SET Name_Lang_esMX='Grell', Description_Lang_esMX='' WHERE ID=64;
UPDATE dbc_faction SET Name_Lang_esMX='Fúrbolg', Description_Lang_esMX='' WHERE ID=65;
UPDATE dbc_faction SET Name_Lang_esMX='Genérico de la Horda', Description_Lang_esMX='' WHERE ID=66;
UPDATE dbc_faction SET Name_Lang_esMX='Horda', Description_Lang_esMX='' WHERE ID=67;
UPDATE dbc_faction SET Name_Lang_esMX='Entrañas', Description_Lang_esMX='Liderados por Sylvanas Brisaveloz, los Renegados han forjado una delicada alianza con la Horda y han asentado su capital en las vastas profundidades bajo las Ruinas de Lordaeron.' WHERE ID=68;
UPDATE dbc_faction SET Name_Lang_esMX='Darnassus', Description_Lang_esMX='Esta capital de la Alianza está habitada por los elfos de la noche y se encuentra en la isla de Teldrassil. Está gobernada por la Sacerdotisa de la Luna, Tyrande Susurravientos.' WHERE ID=69;
UPDATE dbc_faction SET Name_Lang_esMX='La Hermandad', Description_Lang_esMX='Una organización criminal mayoritariamente humana que opera principalmente en los alrededores de las montañas de Alterac y las Laderas de Trabalomas.' WHERE ID=70;
UPDATE dbc_faction SET Name_Lang_esMX='Milicia de Trabalomas', Description_Lang_esMX='' WHERE ID=71;
UPDATE dbc_faction SET Name_Lang_esMX='Ventormenta', Description_Lang_esMX='Esta capital de la Alianza, uno de los últimos baluartes del poder humano, está gobernada por el rey pródigo Varian Wrynn.' WHERE ID=72;
UPDATE dbc_faction SET Name_Lang_esMX='Demonio', Description_Lang_esMX='' WHERE ID=73;
UPDATE dbc_faction SET Name_Lang_esMX='Elemental', Description_Lang_esMX='' WHERE ID=74;
UPDATE dbc_faction SET Name_Lang_esMX='Espíritu', Description_Lang_esMX='' WHERE ID=75;
UPDATE dbc_faction SET Name_Lang_esMX='Orgrimmar', Description_Lang_esMX='Fundada por Thrall, esta capital de la Horda es el hogar de muchos de los orgullosos clanes orcos de Durotar.' WHERE ID=76;
UPDATE dbc_faction SET Name_Lang_esMX='Tesoro', Description_Lang_esMX='' WHERE ID=77;
UPDATE dbc_faction SET Name_Lang_esMX='Gnoll: Morrobarro', Description_Lang_esMX='' WHERE ID=78;
UPDATE dbc_faction SET Name_Lang_esMX='Trabalomas, Alcalde de Costasur', Description_Lang_esMX='' WHERE ID=79;
UPDATE dbc_faction SET Name_Lang_esMX='Vuelo, Negro', Description_Lang_esMX='' WHERE ID=80;
UPDATE dbc_faction SET Name_Lang_esMX='Cima del Trueno', Description_Lang_esMX='Cairne Pezuña de Sangre dirige a su pueblo, los orgullosos tauren, desde esta poderosa capital de la Horda.' WHERE ID=81;
UPDATE dbc_faction SET Name_Lang_esMX='Trol, Secacorteza', Description_Lang_esMX='' WHERE ID=82;
UPDATE dbc_faction SET Name_Lang_esMX=' Peletería: elemental', Description_Lang_esMX='' WHERE ID=83;
UPDATE dbc_faction SET Name_Lang_esMX='Jabaespín, Crines de Acero', Description_Lang_esMX='' WHERE ID=84;
UPDATE dbc_faction SET Name_Lang_esMX='Jabaespín, Erizapúas', Description_Lang_esMX='' WHERE ID=85;
UPDATE dbc_faction SET Name_Lang_esMX=' Peletería: dragontina', Description_Lang_esMX='' WHERE ID=86;
UPDATE dbc_faction SET Name_Lang_esMX='Bucaneros Velasangre', Description_Lang_esMX='Estos sanguinarios corsarios son la pesadilla de muchos mercaderes en alta mar. Enemigos acérrimos de Bahía del Botín.' WHERE ID=87;
UPDATE dbc_faction SET Name_Lang_esMX='Brazanegra', Description_Lang_esMX='' WHERE ID=88;
UPDATE dbc_faction SET Name_Lang_esMX='Makrura', Description_Lang_esMX='' WHERE ID=89;
UPDATE dbc_faction SET Name_Lang_esMX='Centauro, Kolkar', Description_Lang_esMX='' WHERE ID=90;
UPDATE dbc_faction SET Name_Lang_esMX='Centauro, Galak', Description_Lang_esMX='' WHERE ID=91;
UPDATE dbc_faction SET Name_Lang_esMX='Centauros del clan Gelkis', Description_Lang_esMX='Estos centauros han establecido su hogar en la región sur de Desolace. Son enemigos mortales de los centauros Magram.' WHERE ID=92;
UPDATE dbc_faction SET Name_Lang_esMX='Centauros del clan Magram', Description_Lang_esMX='Estos centauros han establecido su hogar en la región oriental de Desolace. Son enemigos mortales de los centauros Gelkis.' WHERE ID=93;
UPDATE dbc_faction SET Name_Lang_esMX='Maraudine', Description_Lang_esMX='' WHERE ID=94;
UPDATE dbc_faction SET Name_Lang_esMX='Theramore', Description_Lang_esMX='' WHERE ID=108;
UPDATE dbc_faction SET Name_Lang_esMX='Jabaespín, Rajacieno', Description_Lang_esMX='' WHERE ID=109;
UPDATE dbc_faction SET Name_Lang_esMX='Jabaespín, Crines de Acero 2', Description_Lang_esMX='' WHERE ID=110;
UPDATE dbc_faction SET Name_Lang_esMX='Jabaespín, Galponmuerte', Description_Lang_esMX='' WHERE ID=111;
UPDATE dbc_faction SET Name_Lang_esMX='Enemigo', Description_Lang_esMX='' WHERE ID=128;
UPDATE dbc_faction SET Name_Lang_esMX='Ambiente', Description_Lang_esMX='' WHERE ID=148;
UPDATE dbc_faction SET Name_Lang_esMX='Caravana Nethergarde', Description_Lang_esMX='' WHERE ID=168;
UPDATE dbc_faction SET Name_Lang_esMX='Cártel Bonvapor', Description_Lang_esMX='' WHERE ID=169;
UPDATE dbc_faction SET Name_Lang_esMX='Genérico de la Alianza', Description_Lang_esMX='' WHERE ID=189;
UPDATE dbc_faction SET Name_Lang_esMX='Nethergarde', Description_Lang_esMX='' WHERE ID=209;
UPDATE dbc_faction SET Name_Lang_esMX='Cuevas de los Lamentos', Description_Lang_esMX='' WHERE ID=229;
UPDATE dbc_faction SET Name_Lang_esMX='Silítidos', Description_Lang_esMX='' WHERE ID=249;
UPDATE dbc_faction SET Name_Lang_esMX='Lunargenta Despogiz', Description_Lang_esMX='' WHERE ID=269;
UPDATE dbc_faction SET Name_Lang_esMX='Tribu Zandalar', Description_Lang_esMX='Estos trols han acudido a la isla de Yojamba en un esfuerzo por conseguir aliados contra el resurrecto Dios Sangriento y sus sacerdotes Atal''ai en Zul''Gurub.' WHERE ID=270;
UPDATE dbc_faction SET Name_Lang_esMX=' Herrería: armas', Description_Lang_esMX='' WHERE ID=289;
UPDATE dbc_faction SET Name_Lang_esMX='Escórpido', Description_Lang_esMX='' WHERE ID=309;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: murciélago', Description_Lang_esMX='' WHERE ID=310;
UPDATE dbc_faction SET Name_Lang_esMX='Titán', Description_Lang_esMX='' WHERE ID=311;
UPDATE dbc_faction SET Name_Lang_esMX='Capataz Fizzule', Description_Lang_esMX='' WHERE ID=329;
UPDATE dbc_faction SET Name_Lang_esMX='Ravenholdt', Description_Lang_esMX='La hermandad de ladrones y asesinos solo da la bienvenida a los más aguerridos. Son enemigos acérrimos de la Hermandad.' WHERE ID=349;
UPDATE dbc_faction SET Name_Lang_esMX='Gadgetzan', Description_Lang_esMX='Capital del Cártel Bonvapor y hogar de los mejores ingenieros, alquimistas y mercaderes goblin.' WHERE ID=369;
UPDATE dbc_faction SET Name_Lang_esMX='Bicho de Gnomeregan', Description_Lang_esMX='' WHERE ID=389;
UPDATE dbc_faction SET Name_Lang_esMX='Arpía', Description_Lang_esMX='' WHERE ID=409;
UPDATE dbc_faction SET Name_Lang_esMX='Filo Ardiente', Description_Lang_esMX='' WHERE ID=429;
UPDATE dbc_faction SET Name_Lang_esMX='Furtivo Sedaumbría', Description_Lang_esMX='' WHERE ID=449;
UPDATE dbc_faction SET Name_Lang_esMX='Araña abrasadora', Description_Lang_esMX='' WHERE ID=450;
UPDATE dbc_faction SET Name_Lang_esMX='Alianza', Description_Lang_esMX='' WHERE ID=469;
UPDATE dbc_faction SET Name_Lang_esMX='Trinquete', Description_Lang_esMX='Parte del Cártel Bonvapor, esta ciudad goblin constituye un santuario neutral para los que desean realizar intercambios comerciales y de servicios en los Baldíos.' WHERE ID=470;
UPDATE dbc_faction SET Name_Lang_esMX='Clan Martillo Salvaje', Description_Lang_esMX='A pesar de no formar parte de la Alianza, los enanos de Pico Nidal les han abierto sus puertas y consideran a la Horda como el enemigo.' WHERE ID=471;
UPDATE dbc_faction SET Name_Lang_esMX='Goblin, Dueño de bar Hierro Negro', Description_Lang_esMX='' WHERE ID=489;
UPDATE dbc_faction SET Name_Lang_esMX='Liga de Arathor', Description_Lang_esMX='La Liga de Arathor persigue reclamar las tierras perdidas de Arathi para sus benefactores en Ventormenta.' WHERE ID=509;
UPDATE dbc_faction SET Name_Lang_esMX='Los Rapiñadores', Description_Lang_esMX='Los Rapiñadores buscan hacerse con el control de los valiosos recursos de Arathi para el beneficio de la Horda.' WHERE ID=510;
UPDATE dbc_faction SET Name_Lang_esMX='Gigante', Description_Lang_esMX='' WHERE ID=511;
UPDATE dbc_faction SET Name_Lang_esMX='El Alba Argenta', Description_Lang_esMX='Una organización centrada en proteger Azeroth de la amenaza de la Plaga. Las fortalezas de El Alba Argenta se encuentran en las Tierras de la Peste del Este y del Oeste.' WHERE ID=529;
UPDATE dbc_faction SET Name_Lang_esMX='Trols Lanza Negra', Description_Lang_esMX='Esta tribu de trols exiliados ha unido fuerzas con Thrall y la Horda. Ahora conviven con los orcos en las tierras de Durotar.' WHERE ID=530;
UPDATE dbc_faction SET Name_Lang_esMX='Vuelo, Bronce', Description_Lang_esMX='' WHERE ID=531;
UPDATE dbc_faction SET Name_Lang_esMX='Vuelo, Azul', Description_Lang_esMX='' WHERE ID=532;
UPDATE dbc_faction SET Name_Lang_esMX=' Peletería: tribal', Description_Lang_esMX='' WHERE ID=549;
UPDATE dbc_faction SET Name_Lang_esMX=' Ingeniería: goblin', Description_Lang_esMX='' WHERE ID=550;
UPDATE dbc_faction SET Name_Lang_esMX=' Ingeniería: gnoma', Description_Lang_esMX='' WHERE ID=551;
UPDATE dbc_faction SET Name_Lang_esMX=' Herrería: martillos', Description_Lang_esMX='' WHERE ID=569;
UPDATE dbc_faction SET Name_Lang_esMX=' Herrería: hachas', Description_Lang_esMX='' WHERE ID=570;
UPDATE dbc_faction SET Name_Lang_esMX=' Herrería: espadas', Description_Lang_esMX='' WHERE ID=571;
UPDATE dbc_faction SET Name_Lang_esMX='Trol, Vilrama', Description_Lang_esMX='' WHERE ID=572;
UPDATE dbc_faction SET Name_Lang_esMX='Filibusteros de los Mares del Sur', Description_Lang_esMX='' WHERE ID=573;
UPDATE dbc_faction SET Name_Lang_esMX='Castel Darrow', Description_Lang_esMX='' WHERE ID=574;
UPDATE dbc_faction SET Name_Lang_esMX='Fúrbolg, incorrupto', Description_Lang_esMX='' WHERE ID=575;
UPDATE dbc_faction SET Name_Lang_esMX='Bastión Fauces de Madera', Description_Lang_esMX='Como la última tribu fúrbolg sin corromper, los Fauces de Madera persiguen preservar sus tradiciones espirituales y acabar con el sufrimiento de sus congéneres.' WHERE ID=576;
UPDATE dbc_faction SET Name_Lang_esMX='Vista Eterna', Description_Lang_esMX='Este enclave comercial, regentado por los goblins del Cártel Bonvapor, se sitúa en el cruce de las principales rutas comerciales de Cuna del Invierno.' WHERE ID=577;
UPDATE dbc_faction SET Name_Lang_esMX='Instructores de Sableinvernales', Description_Lang_esMX='Este pequeño grupo de recluidos elfos de la noche cría y amaestra sableinvernales en el área de Cuna del invierno.' WHERE ID=589;
UPDATE dbc_faction SET Name_Lang_esMX='Círculo Cenarion', Description_Lang_esMX='Los druidas del Círculo Cenarion son guardianes de la Naturaleza y conviven en el calmo Claro de la Luna.' WHERE ID=609;
UPDATE dbc_faction SET Name_Lang_esMX='Trols Rompelanzas', Description_Lang_esMX='' WHERE ID=629;
UPDATE dbc_faction SET Name_Lang_esMX='Instructores de Ravasaurios', Description_Lang_esMX='' WHERE ID=630;
UPDATE dbc_faction SET Name_Lang_esMX='Mayordomo Executus', Description_Lang_esMX='' WHERE ID=649;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: pájaro carroñero', Description_Lang_esMX='' WHERE ID=669;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: gato', Description_Lang_esMX='' WHERE ID=670;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: cangrejo', Description_Lang_esMX='' WHERE ID=671;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: crocolisco', Description_Lang_esMX='' WHERE ID=672;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: hiena', Description_Lang_esMX='' WHERE ID=673;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: búho', Description_Lang_esMX='' WHERE ID=674;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: escórpido', Description_Lang_esMX='' WHERE ID=675;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: zancaalta', Description_Lang_esMX='' WHERE ID=676;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: tortuga', Description_Lang_esMX='' WHERE ID=677;
UPDATE dbc_faction SET Name_Lang_esMX='Bestia: serpiente alada', Description_Lang_esMX='' WHERE ID=678;
UPDATE dbc_faction SET Name_Lang_esMX='Muñeco de entrenamiento', Description_Lang_esMX='' WHERE ID=679;
UPDATE dbc_faction SET Name_Lang_esMX='Vuelo, Negro: cebo', Description_Lang_esMX='' WHERE ID=689;
UPDATE dbc_faction SET Name_Lang_esMX='Neutral en campo de batalla', Description_Lang_esMX='' WHERE ID=709;
UPDATE dbc_faction SET Name_Lang_esMX='Clan Lobo Gélido', Description_Lang_esMX='El clan Lobo Gélido busca expulsar a los enanos de la Expedición Pico Tormenta del Valle de Alterac.' WHERE ID=729;
UPDATE dbc_faction SET Name_Lang_esMX='Guardia Pico Tormenta', Description_Lang_esMX='Los enanos Pico Tormenta se han asentado en el Valle de Alterac, enzarzándose en batalla con los orcos Lobo Gélido.' WHERE ID=730;
UPDATE dbc_faction SET Name_Lang_esMX='Srs. del Agua de Hydraxis', Description_Lang_esMX='Estos elementales han construido su hogar en las islas al este de Azshara. Son enemigos acérrimos de los ejércitos de Ragnaros.' WHERE ID=749;
UPDATE dbc_faction SET Name_Lang_esMX='Señores del Fuego de Sulfuron', Description_Lang_esMX='' WHERE ID=750;
UPDATE dbc_faction SET Name_Lang_esMX='Muñeco de Gizlock', Description_Lang_esMX='' WHERE ID=769;
UPDATE dbc_faction SET Name_Lang_esMX='Talismán de Gizlock', Description_Lang_esMX='' WHERE ID=770;
UPDATE dbc_faction SET Name_Lang_esMX='Gizlock', Description_Lang_esMX='' WHERE ID=771;
UPDATE dbc_faction SET Name_Lang_esMX='Moro''gan', Description_Lang_esMX='' WHERE ID=789;
UPDATE dbc_faction SET Name_Lang_esMX='Guía espiritual: Alianza', Description_Lang_esMX='' WHERE ID=790;
UPDATE dbc_faction SET Name_Lang_esMX='Shen''dralar', Description_Lang_esMX='Lo que queda de los antaño poderosos elfos habitantes de La Masacre, todavía sabios y cultivados en grandes secretos.' WHERE ID=809;
UPDATE dbc_faction SET Name_Lang_esMX='Ogro (capitán Kromcrush)', Description_Lang_esMX='' WHERE ID=829;
UPDATE dbc_faction SET Name_Lang_esMX='Guía espiritual: Horda', Description_Lang_esMX='' WHERE ID=849;
UPDATE dbc_faction SET Name_Lang_esMX='Jaedenar', Description_Lang_esMX='' WHERE ID=869;
UPDATE dbc_faction SET Name_Lang_esMX='Escoltas Grito de Guerra', Description_Lang_esMX='Valientes orcos del clan Grito de Guerra en batalla constante contra los Centinelas Ala de Plata en la Garganta Grito de Guerra.' WHERE ID=889;
UPDATE dbc_faction SET Name_Lang_esMX='Centinelas Ala de Plata', Description_Lang_esMX='Incondicionales defensores de Vallefresno, están en constante batalla contra los Escoltas Grito de Guerra en la Garganta Grito de Guerra.' WHERE ID=890;
UPDATE dbc_faction SET Name_Lang_esMX='Fuerzas de la Alianza', Description_Lang_esMX='' WHERE ID=891;
UPDATE dbc_faction SET Name_Lang_esMX='Fuerzas de la Horda', Description_Lang_esMX='' WHERE ID=892;
UPDATE dbc_faction SET Name_Lang_esMX='Trols Sañadiente', Description_Lang_esMX='' WHERE ID=893;
UPDATE dbc_faction SET Name_Lang_esMX='Feria de la Luna Negra', Description_Lang_esMX='Es una feria ambulante que hace espectáculos con lo extraño y lo extraordinario. Suelen dejarse ver por el Bosque de Elwynn, Mulgore y el Bosque de Terokkar.' WHERE ID=909;
UPDATE dbc_faction SET Name_Lang_esMX='Linaje de Nozdormu', Description_Lang_esMX='Los descendientes del Vuelo Bronce son los guardianes del tiempo y poco les importan los mortales.' WHERE ID=910;
UPDATE dbc_faction SET Name_Lang_esMX='Ciudad de Lunargenta', Description_Lang_esMX='La capital de Quel''Thalas, hogar de los elfos de sangre. Aunque casi fuera destruida por el ataque de Arthas sobre La Fuente del Sol, Lunargenta vuelve a ser una ciudad próspera.' WHERE ID=911;
UPDATE dbc_faction SET Name_Lang_esMX='Poder de Kalimdor', Description_Lang_esMX='' WHERE ID=912;
UPDATE dbc_faction SET Name_Lang_esMX='JUGADOR, elfo de sangre', Description_Lang_esMX='' WHERE ID=914;
UPDATE dbc_faction SET Name_Lang_esMX='Ejércitos de C''Thun', Description_Lang_esMX='' WHERE ID=915;
UPDATE dbc_faction SET Name_Lang_esMX='Atacantes silítidos', Description_Lang_esMX='' WHERE ID=916;
UPDATE dbc_faction SET Name_Lang_esMX='Brigada de Forjaz', Description_Lang_esMX='' WHERE ID=917;
UPDATE dbc_faction SET Name_Lang_esMX='Enemigos CR', Description_Lang_esMX='' WHERE ID=918;
UPDATE dbc_faction SET Name_Lang_esMX='Objetos CR', Description_Lang_esMX='' WHERE ID=919;
UPDATE dbc_faction SET Name_Lang_esMX='Rojo', Description_Lang_esMX='' WHERE ID=920;
UPDATE dbc_faction SET Name_Lang_esMX='Azul', Description_Lang_esMX='' WHERE ID=921;
UPDATE dbc_faction SET Name_Lang_esMX='Tranquillien', Description_Lang_esMX='En sus tiempos una ciudad de elfos nobles, Tranquillien quedó abandonada después de que la Plaga invadiera Quel''Thalas. Ahora ha sido reclamada por los Renegados y los elfos de sangre, quienes intentan eliminar de las Tierras Fantasma a la Plaga.' WHERE ID=922;
UPDATE dbc_faction SET Name_Lang_esMX='Los Errantes', Description_Lang_esMX='' WHERE ID=923;
UPDATE dbc_faction SET Name_Lang_esMX='DEPRECATED', Description_Lang_esMX='' WHERE ID=924;
UPDATE dbc_faction SET Name_Lang_esMX='Los Caminante del Sol', Description_Lang_esMX='' WHERE ID=925;
UPDATE dbc_faction SET Name_Lang_esMX='Hermandad de Magíster', Description_Lang_esMX='' WHERE ID=926;
UPDATE dbc_faction SET Name_Lang_esMX='JUGADOR, draenei', Description_Lang_esMX='' WHERE ID=927;
UPDATE dbc_faction SET Name_Lang_esMX='Invasores de la Plaga', Description_Lang_esMX='' WHERE ID=928;
UPDATE dbc_faction SET Name_Lang_esMX='Clan Machacasangre', Description_Lang_esMX='' WHERE ID=929;
UPDATE dbc_faction SET Name_Lang_esMX='El Exodar', Description_Lang_esMX='La nave naaru que trajo a los draenei a Azeroth. A pesar de estar varada en las Islas Bruma Azur, sirve de hogar a esta noble raza.' WHERE ID=930;
UPDATE dbc_faction SET Name_Lang_esMX='Facción de prueba (no es real)', Description_Lang_esMX='Esta facción solo existe para probar a editar nombres de facción y descripciones.' WHERE ID=931;
UPDATE dbc_faction SET Name_Lang_esMX='Los Aldor', Description_Lang_esMX='Es una antigua orden de sacerdotes draenei dirigida antaño por Velen. Los Aldor están actualmente bajo el mando de la suma sacerdotisa Ishanah. Son sirvientes de los naaru de la Ciudad de Shattrath, conocidos como los Sha''tar. Son rivales de los Arúspices.' WHERE ID=932;
UPDATE dbc_faction SET Name_Lang_esMX='El Consorcio', Description_Lang_esMX='Bajo el mando del príncipe-nexo Haramad, el Consorcio es un cártel de afiliación sin excesivo rigor de contrabandistas etéreos, comerciantes y ladrones que han llegado a Terrallende para beneficiarse de sus riquezas.' WHERE ID=933;
UPDATE dbc_faction SET Name_Lang_esMX='Los Arúspices', Description_Lang_esMX='Voren''thal el Vidente lidera a los elfos de sangre disidentes que han rechazado el camino hacia el poder de Kael''thas. Se han unido a los naaru de Ciudad de Shattrath para consternación de los Aldor.' WHERE ID=934;
UPDATE dbc_faction SET Name_Lang_esMX='Los Sha''tar', Description_Lang_esMX='Los Sha''tar son un grupo de poderosos naaru que gobiernan la reconstruida Ciudad de Shattrath. Con el apoyo de los Aldor y los Arúspices lideran la batalla contra Illidan y la Legión Ardiente.' WHERE ID=935;
UPDATE dbc_faction SET Name_Lang_esMX='Ciudad de Shattrath', Description_Lang_esMX='' WHERE ID=936;
UPDATE dbc_faction SET Name_Lang_esMX='Trol, bosque', Description_Lang_esMX='' WHERE ID=937;
UPDATE dbc_faction SET Name_Lang_esMX='Los Omenai', Description_Lang_esMX='' WHERE ID=938;
UPDATE dbc_faction SET Name_Lang_esMX='DEPRECATED', Description_Lang_esMX='' WHERE ID=939;
UPDATE dbc_faction SET Name_Lang_esMX='Los Hijos de Lothar', Description_Lang_esMX='' WHERE ID=940;
UPDATE dbc_faction SET Name_Lang_esMX='Los Mag''har', Description_Lang_esMX='Este grupo de huraños orcos de piel marrón ha escapado de la corrupción demoníaca. Ha mantenido su forma de vida tradicional a pesar de los grandes cambios en Terrallende.' WHERE ID=941;
UPDATE dbc_faction SET Name_Lang_esMX='Expedición Cenarion', Description_Lang_esMX='El Círculo Cenarion envió una partida de exploración a Terrallende para estudiar las formas de vida supervivientes. La expedición Cenarion ha ganado en tamaño y autonomía desde la apertura de El Portal Oscuro.' WHERE ID=942;
UPDATE dbc_faction SET Name_Lang_esMX='Orco vil', Description_Lang_esMX='' WHERE ID=943;
UPDATE dbc_faction SET Name_Lang_esMX='Fantasma de orco vil', Description_Lang_esMX='' WHERE ID=944;
UPDATE dbc_faction SET Name_Lang_esMX='Hijos de los Fantasmas de Lothar', Description_Lang_esMX='' WHERE ID=945;
UPDATE dbc_faction SET Name_Lang_esMX='Bastión del Honor', Description_Lang_esMX='Vestigios de los Hijos de Lothar, los primeros veteranos de la Alianza que llegaron a Draenor, se han aferrado firmemente a esta avanzada de Fuego Infernal. Ahora se han unido a los ejércitos de Ventormenta y Forjaz.' WHERE ID=946;
UPDATE dbc_faction SET Name_Lang_esMX='Thrallmar', Description_Lang_esMX='La expedición que Thrall enviara a través del Portal Oscuro ha construido un fuerte en la Península del Fuego Infernal. Thrallmar sirve de base de operaciones para muchas de las actividades de la Horda en Terrallende.' WHERE ID=947;
UPDATE dbc_faction SET Name_Lang_esMX='Facción de prueba 2', Description_Lang_esMX='' WHERE ID=948;
UPDATE dbc_faction SET Name_Lang_esMX='Facción de prueba 1', Description_Lang_esMX='' WHERE ID=949;
UPDATE dbc_faction SET Name_Lang_esMX='ParaWoW - Bandera', Description_Lang_esMX='' WHERE ID=950;
UPDATE dbc_faction SET Name_Lang_esMX='ParaWoW - Activador de bandera de la Alianza (DND)', Description_Lang_esMX='' WHERE ID=951;
UPDATE dbc_faction SET Name_Lang_esMX='Facción de prueba 3', Description_Lang_esMX='' WHERE ID=952;
UPDATE dbc_faction SET Name_Lang_esMX='Facción de prueba 4', Description_Lang_esMX='' WHERE ID=953;
UPDATE dbc_faction SET Name_Lang_esMX='ParaWoW - Activador de bandera de la Horda (DND)', Description_Lang_esMX='' WHERE ID=954;
UPDATE dbc_faction SET Name_Lang_esMX='Tábidos', Description_Lang_esMX='' WHERE ID=955;
UPDATE dbc_faction SET Name_Lang_esMX='El Etereum', Description_Lang_esMX='' WHERE ID=956;
UPDATE dbc_faction SET Name_Lang_esMX='Elemental de tierra', Description_Lang_esMX='' WHERE ID=957;
UPDATE dbc_faction SET Name_Lang_esMX='Robots luchadores', Description_Lang_esMX='' WHERE ID=958;
UPDATE dbc_faction SET Name_Lang_esMX='Actor bueno', Description_Lang_esMX='' WHERE ID=959;
UPDATE dbc_faction SET Name_Lang_esMX='Actor malo', Description_Lang_esMX='' WHERE ID=960;
UPDATE dbc_faction SET Name_Lang_esMX='Fúrbolg Semprepino', Description_Lang_esMX='' WHERE ID=961;
UPDATE dbc_faction SET Name_Lang_esMX='Buhíco enloquecido', Description_Lang_esMX='' WHERE ID=962;
UPDATE dbc_faction SET Name_Lang_esMX='Ajedrez Alianza', Description_Lang_esMX='' WHERE ID=963;
UPDATE dbc_faction SET Name_Lang_esMX='Ajedrez Horda', Description_Lang_esMX='' WHERE ID=964;
UPDATE dbc_faction SET Name_Lang_esMX='Monstruo de entrenamiento', Description_Lang_esMX='' WHERE ID=965;
UPDATE dbc_faction SET Name_Lang_esMX='Compañero de monstruo de entrenamiento', Description_Lang_esMX='' WHERE ID=966;
UPDATE dbc_faction SET Name_Lang_esMX='El Ojo Violeta', Description_Lang_esMX='Una secta secreta del Kirin Tor fundada para espiar a Medivh y sus actividades.' WHERE ID=967;
UPDATE dbc_faction SET Name_Lang_esMX='Halcones del Sol', Description_Lang_esMX='' WHERE ID=968;
UPDATE dbc_faction SET Name_Lang_esMX='Mano de Argus', Description_Lang_esMX='' WHERE ID=969;
UPDATE dbc_faction SET Name_Lang_esMX='Esporaggar', Description_Lang_esMX='Los esporinos son una raza en su mayoría pacífica de hombres champiñón nativos de Terrallende. Su hogar se encuentra en las ciénagas del sur de la Marisma de Zangar.' WHERE ID=970;
UPDATE dbc_faction SET Name_Lang_esMX='Gigante Fungal', Description_Lang_esMX='' WHERE ID=971;
UPDATE dbc_faction SET Name_Lang_esMX='Esporiélago', Description_Lang_esMX='' WHERE ID=972;
UPDATE dbc_faction SET Name_Lang_esMX='Monstruo, predador', Description_Lang_esMX='' WHERE ID=973;
UPDATE dbc_faction SET Name_Lang_esMX='Monstruo, presa', Description_Lang_esMX='' WHERE ID=974;
UPDATE dbc_faction SET Name_Lang_esMX='Anomalía del vacío', Description_Lang_esMX='' WHERE ID=975;
UPDATE dbc_faction SET Name_Lang_esMX='Defensores de Hyjal', Description_Lang_esMX='' WHERE ID=976;
UPDATE dbc_faction SET Name_Lang_esMX='Invasores de Hyjal', Description_Lang_esMX='' WHERE ID=977;
UPDATE dbc_faction SET Name_Lang_esMX='Kurenai', Description_Lang_esMX='En draenei significa "redimidos." Estos Tábidos han escapado de la esclavitud en Terrallende y han hecho de Nagrand su hogar. Ahí esperan redescubrir su destino.' WHERE ID=978;
UPDATE dbc_faction SET Name_Lang_esMX='Anillo de la Tierra', Description_Lang_esMX='' WHERE ID=979;
UPDATE dbc_faction SET Name_Lang_esMX='The Burning Crusade', Description_Lang_esMX='' WHERE ID=980;
UPDATE dbc_faction SET Name_Lang_esMX='Arakkoa', Description_Lang_esMX='' WHERE ID=981;
UPDATE dbc_faction SET Name_Lang_esMX='Estandarte de Marisma de Zangar (Alianza)', Description_Lang_esMX='' WHERE ID=982;
UPDATE dbc_faction SET Name_Lang_esMX='Estandarte de Marisma de Zangar (Horda)', Description_Lang_esMX='' WHERE ID=983;
UPDATE dbc_faction SET Name_Lang_esMX='Estandarte de Marisma de Zangar (Neutral)', Description_Lang_esMX='' WHERE ID=984;
UPDATE dbc_faction SET Name_Lang_esMX='Cavernas del Tiempo - Thrall', Description_Lang_esMX='' WHERE ID=985;
UPDATE dbc_faction SET Name_Lang_esMX='Cavernas del Tiempo - Durnholde', Description_Lang_esMX='' WHERE ID=986;
UPDATE dbc_faction SET Name_Lang_esMX='Cavernas del Tiempo - Guardias de Costasur', Description_Lang_esMX='' WHERE ID=987;
UPDATE dbc_faction SET Name_Lang_esMX='Secreto del Consejo de la Sombra', Description_Lang_esMX='' WHERE ID=988;
UPDATE dbc_faction SET Name_Lang_esMX='Vigilantes del Tiempo', Description_Lang_esMX='Los Vigilantes del Tiempo son dragones de bronce elegidos personalmente por Nozdormu para vigilar las Cavernas del Tiempo.' WHERE ID=989;
UPDATE dbc_faction SET Name_Lang_esMX='La Escama de las Arenas', Description_Lang_esMX='Un subgrupo secreto del Vuelo Bronce, bajo el mando de Soridormi, primer oficial de Nozdormu.' WHERE ID=990;
UPDATE dbc_faction SET Name_Lang_esMX='Defensor del Portal Oscuro, Alianza', Description_Lang_esMX='' WHERE ID=991;
UPDATE dbc_faction SET Name_Lang_esMX='Defensor del Portal Oscuro, Horda', Description_Lang_esMX='' WHERE ID=992;
UPDATE dbc_faction SET Name_Lang_esMX='Agresor del Portal Oscuro, Legión', Description_Lang_esMX='' WHERE ID=993;
UPDATE dbc_faction SET Name_Lang_esMX='Activador de incitador', Description_Lang_esMX='Usado para el evento de Negrozón el Incitador.' WHERE ID=994;
UPDATE dbc_faction SET Name_Lang_esMX='Activador de incitador 2', Description_Lang_esMX='Usado para el evento de Negrozón el Incitador.' WHERE ID=995;
UPDATE dbc_faction SET Name_Lang_esMX='Activador de incitador 3', Description_Lang_esMX='Usado para el evento de Negrozón el Incitador.' WHERE ID=996;
UPDATE dbc_faction SET Name_Lang_esMX='Activador de incitador 4', Description_Lang_esMX='Usado para el evento de Negrozón el Incitador.' WHERE ID=997;
UPDATE dbc_faction SET Name_Lang_esMX='Activador de incitador 5', Description_Lang_esMX='Usado para el evento de Negrozón el Incitador.' WHERE ID=998;
UPDATE dbc_faction SET Name_Lang_esMX='Criatura de maná', Description_Lang_esMX='' WHERE ID=999;
UPDATE dbc_faction SET Name_Lang_esMX='Sirviente de Khadgar', Description_Lang_esMX='' WHERE ID=1000;
UPDATE dbc_faction SET Name_Lang_esMX='Clan Aguja del Filo', Description_Lang_esMX='' WHERE ID=1001;
UPDATE dbc_faction SET Name_Lang_esMX='Compañero de entrenamiento de El Etereum', Description_Lang_esMX='' WHERE ID=1002;
UPDATE dbc_faction SET Name_Lang_esMX='Protectorado', Description_Lang_esMX='' WHERE ID=1003;
UPDATE dbc_faction SET Name_Lang_esMX='Aniquilador Arcano (DNR)', Description_Lang_esMX='' WHERE ID=1004;
UPDATE dbc_faction SET Name_Lang_esMX='Amistoso, oculto', Description_Lang_esMX='' WHERE ID=1005;
UPDATE dbc_faction SET Name_Lang_esMX='Kirin''Var - Dathric', Description_Lang_esMX='' WHERE ID=1006;
UPDATE dbc_faction SET Name_Lang_esMX='Kirin''Var - Belmara', Description_Lang_esMX='' WHERE ID=1007;
UPDATE dbc_faction SET Name_Lang_esMX='Kirin''Var - Luminrath', Description_Lang_esMX='' WHERE ID=1008;
UPDATE dbc_faction SET Name_Lang_esMX='Kirin''Var - Cohlien', Description_Lang_esMX='' WHERE ID=1009;
UPDATE dbc_faction SET Name_Lang_esMX='Sirviente de Illidan', Description_Lang_esMX='' WHERE ID=1010;
UPDATE dbc_faction SET Name_Lang_esMX='Bajo Arrabal', Description_Lang_esMX='Los refugiados de Shattrath proceden de diferentes razas y contextos. Los relatos de buenas acciones se extienden rápidamente entre los habitantes del Bajo Arrabal.' WHERE ID=1011;
UPDATE dbc_faction SET Name_Lang_esMX='Juramorte Lengua de ceniza', Description_Lang_esMX='La élite de la tribu de los Tábidos se conoce como los Lengua de ceniza, aliados oficiales de Illidan. Los Juramorte son los tenientes más leales de Akama y tienen conocimiento de las misteriosas motivaciones de su líder.' WHERE ID=1012;
UPDATE dbc_faction SET Name_Lang_esMX='Espíritus de Sombraluna 1', Description_Lang_esMX='' WHERE ID=1013;
UPDATE dbc_faction SET Name_Lang_esMX='Espíritus de Sombraluna 2', Description_Lang_esMX='' WHERE ID=1014;
UPDATE dbc_faction SET Name_Lang_esMX='Ala Abisal', Description_Lang_esMX='Esta inusual camada de dragones nació de los huevos del Vuelo Negro de Alamuerte y está imbuida de energías del vacío puras. Ahora buscan su identidad más allá de las sombras de la destructora herencia de su padre.' WHERE ID=1015;
UPDATE dbc_faction SET Name_Lang_esMX='Culto vermis', Description_Lang_esMX='' WHERE ID=1016;
UPDATE dbc_faction SET Name_Lang_esMX='Antárboles', Description_Lang_esMX='' WHERE ID=1017;
UPDATE dbc_faction SET Name_Lang_esMX='Demonio Leotheras I', Description_Lang_esMX='' WHERE ID=1018;
UPDATE dbc_faction SET Name_Lang_esMX='Demonio Leotheras II', Description_Lang_esMX='' WHERE ID=1019;
UPDATE dbc_faction SET Name_Lang_esMX='Demonio Leotheras III', Description_Lang_esMX='' WHERE ID=1020;
UPDATE dbc_faction SET Name_Lang_esMX='Demonio Leotheras IV', Description_Lang_esMX='' WHERE ID=1021;
UPDATE dbc_faction SET Name_Lang_esMX='Demonio Leotheras V', Description_Lang_esMX='' WHERE ID=1022;
UPDATE dbc_faction SET Name_Lang_esMX='Azaloth', Description_Lang_esMX='' WHERE ID=1023;
UPDATE dbc_faction SET Name_Lang_esMX='Despellejador de roca', Description_Lang_esMX='' WHERE ID=1024;
UPDATE dbc_faction SET Name_Lang_esMX='Cazador despellejador', Description_Lang_esMX='' WHERE ID=1025;
UPDATE dbc_faction SET Name_Lang_esMX='Sombra de Sombraluna', Description_Lang_esMX='' WHERE ID=1026;
UPDATE dbc_faction SET Name_Lang_esMX='Comunicador de la Legión', Description_Lang_esMX='' WHERE ID=1027;
UPDATE dbc_faction SET Name_Lang_esMX='Ancianos del Bosque del Cuervo', Description_Lang_esMX='' WHERE ID=1028;
UPDATE dbc_faction SET Name_Lang_esMX='Ajedrez, amistoso con todo el tablero', Description_Lang_esMX='' WHERE ID=1029;
UPDATE dbc_faction SET Name_Lang_esMX='Puertas del Templo Oscuro - Illidari', Description_Lang_esMX='' WHERE ID=1030;
UPDATE dbc_faction SET Name_Lang_esMX='Guardia del cielo Sha''tari', Description_Lang_esMX='Fuerza militar aérea creada en la Ciudad de Shattrath para hacer frente a la amenaza que se cierne sobre el cielo de Terrallende.' WHERE ID=1031;
UPDATE dbc_faction SET Name_Lang_esMX='Área 52', Description_Lang_esMX='' WHERE ID=1032;
UPDATE dbc_faction SET Name_Lang_esMX='Maiev', Description_Lang_esMX='' WHERE ID=1033;
UPDATE dbc_faction SET Name_Lang_esMX='Arakkoa oscuro Skettis', Description_Lang_esMX='' WHERE ID=1034;
UPDATE dbc_faction SET Name_Lang_esMX='Arakkoa Skettis', Description_Lang_esMX='' WHERE ID=1035;
UPDATE dbc_faction SET Name_Lang_esMX='Enemigo Faucedraco', Description_Lang_esMX='' WHERE ID=1036;
UPDATE dbc_faction SET Name_Lang_esMX='Vanguardia de la Alianza', Description_Lang_esMX='Fuerzas conjuntas de la Alianza en Rasganorte, lideradas por la Expedición de Denuedo, además de grupos de civiles como la Liga de Expedicionarios.' WHERE ID=1037;
UPDATE dbc_faction SET Name_Lang_esMX='Ogri''la', Description_Lang_esMX='Los iluminados habitantes de Ogri''la han creado su hogar en las Montañas Filospada occidentales. La proximidad a los cristales de ápices ha hecho que trascienda su bruta naturaleza de ogros.' WHERE ID=1038;
UPDATE dbc_faction SET Name_Lang_esMX='Devastador', Description_Lang_esMX='' WHERE ID=1039;
UPDATE dbc_faction SET Name_Lang_esMX='REUSE', Description_Lang_esMX='' WHERE ID=1040;
UPDATE dbc_faction SET Name_Lang_esMX='Furia', Description_Lang_esMX='' WHERE ID=1041;
UPDATE dbc_faction SET Name_Lang_esMX='Enemigo de la Guardia del cielo', Description_Lang_esMX='' WHERE ID=1042;
UPDATE dbc_faction SET Name_Lang_esMX='Mofeta, Petunia', Description_Lang_esMX='' WHERE ID=1043;
UPDATE dbc_faction SET Name_Lang_esMX='Desierto de Theramore', Description_Lang_esMX='' WHERE ID=1044;
UPDATE dbc_faction SET Name_Lang_esMX='Vrykul', Description_Lang_esMX='' WHERE ID=1045;
UPDATE dbc_faction SET Name_Lang_esMX='Piratas del Mar del Norte', Description_Lang_esMX='' WHERE ID=1046;
UPDATE dbc_faction SET Name_Lang_esMX='Colmillarr', Description_Lang_esMX='' WHERE ID=1047;
UPDATE dbc_faction SET Name_Lang_esMX='UNUSED', Description_Lang_esMX='' WHERE ID=1048;
UPDATE dbc_faction SET Name_Lang_esMX='Trol, Amani', Description_Lang_esMX='' WHERE ID=1049;
UPDATE dbc_faction SET Name_Lang_esMX='Expedición de Denuedo', Description_Lang_esMX='Los principales ejércitos de la Alianza en Rasganorte que hacen frente a la Plaga y que están unificados bajo el mando del Rey Varian Wrynn.' WHERE ID=1050;
UPDATE dbc_faction SET Name_Lang_esMX='UNUSED', Description_Lang_esMX='' WHERE ID=1051;
UPDATE dbc_faction SET Name_Lang_esMX='Expedición de la Horda', Description_Lang_esMX='Fuerzas conjuntas de la Horda en Rasganorte, lideradas por la Ofensiva Grito de Guerra.' WHERE ID=1052;
UPDATE dbc_faction SET Name_Lang_esMX='Guardia Oeste', Description_Lang_esMX='' WHERE ID=1053;
UPDATE dbc_faction SET Name_Lang_esMX='Grifo moteado', Description_Lang_esMX='' WHERE ID=1054;
UPDATE dbc_faction SET Name_Lang_esMX='Can de peste domesticado', Description_Lang_esMX='' WHERE ID=1055;
UPDATE dbc_faction SET Name_Lang_esMX='Vrykul (espíritu antiguo 1)', Description_Lang_esMX='' WHERE ID=1056;
UPDATE dbc_faction SET Name_Lang_esMX='Vrykul (espíritu antiguo 2)', Description_Lang_esMX='' WHERE ID=1057;
UPDATE dbc_faction SET Name_Lang_esMX='Vrykul (espíritu antiguo 3)', Description_Lang_esMX='' WHERE ID=1058;
UPDATE dbc_faction SET Name_Lang_esMX='CLB - Bandera - Alianza', Description_Lang_esMX='' WHERE ID=1059;
UPDATE dbc_faction SET Name_Lang_esMX='Test', Description_Lang_esMX='' WHERE ID=1060;
UPDATE dbc_faction SET Name_Lang_esMX='vrykul', Description_Lang_esMX='' WHERE ID=1061;
UPDATE dbc_faction SET Name_Lang_esMX='Gladiador vrykul', Description_Lang_esMX='' WHERE ID=1062;
UPDATE dbc_faction SET Name_Lang_esMX='Combatiente de Valgarde', Description_Lang_esMX='' WHERE ID=1063;
UPDATE dbc_faction SET Name_Lang_esMX='Los taunka', Description_Lang_esMX='Este recio pueblo está emparentado con los tauren y se ha convertido en la cuna de los valiosos exploradores de los ejércitos de la Horda a medida que esta avanza.' WHERE ID=1064;
UPDATE dbc_faction SET Name_Lang_esMX='Monster, Reacción de fuerza de zona 1', Description_Lang_esMX='' WHERE ID=1065;
UPDATE dbc_faction SET Name_Lang_esMX='Monster, Reacción de fuerza de zona 2', Description_Lang_esMX='' WHERE ID=1066;
UPDATE dbc_faction SET Name_Lang_esMX='La Mano de la Venganza', Description_Lang_esMX='Sylvanas Brisaveloz ha encomiado a los Renegados la tarea de vengarse de Arthas en nombre de Entrañas utilizando su mortífera peste.' WHERE ID=1067;
UPDATE dbc_faction SET Name_Lang_esMX='Liga de Expedicionarios', Description_Lang_esMX='Esta organización busca el origen de la raza de los enanos reuniendo artefactos de los titanes. Su investigación más reciente les ha llevado hasta varias excavaciones arqueológicas en Rasganorte.' WHERE ID=1068;
UPDATE dbc_faction SET Name_Lang_esMX='Ram Racing Powerup DND', Description_Lang_esMX='' WHERE ID=1069;
UPDATE dbc_faction SET Name_Lang_esMX='Ram Racing Trap DND', Description_Lang_esMX='' WHERE ID=1070;
UPDATE dbc_faction SET Name_Lang_esMX='Ardillas de Craig', Description_Lang_esMX='A test faction.' WHERE ID=1071;
UPDATE dbc_faction SET Name_Lang_esMX='REUSE', Description_Lang_esMX='' WHERE ID=1072;
UPDATE dbc_faction SET Name_Lang_esMX='Los Kalu''ak', Description_Lang_esMX='Los colmillarr son una gente dura, pero pacífica que basan su sustento en la pesca y la caza de ballenas. Últimamente sus asentamientos han sufrido unos ataques feroces y dan la bienvenida a cualquier aliado que quiera ayudarles.' WHERE ID=1073;
UPDATE dbc_faction SET Name_Lang_esMX='Fiesta - Barrica de agua', Description_Lang_esMX='' WHERE ID=1074;
UPDATE dbc_faction SET Name_Lang_esMX='Fiesta - Genérico', Description_Lang_esMX='' WHERE ID=1075;
UPDATE dbc_faction SET Name_Lang_esMX='Enanos de Hierro', Description_Lang_esMX='' WHERE ID=1076;
UPDATE dbc_faction SET Name_Lang_esMX='Ofensiva Sol Devastado', Description_Lang_esMX='El último intento de la Ciudad de Shattrath contra las operaciones del príncipe Kael''thas en La Fuente del Sol.' WHERE ID=1077;
UPDATE dbc_faction SET Name_Lang_esMX='Mascota de vanidad combativa', Description_Lang_esMX='' WHERE ID=1078;
UPDATE dbc_faction SET Name_Lang_esMX='Múrloc, Aleta Invernal', Description_Lang_esMX='' WHERE ID=1079;
UPDATE dbc_faction SET Name_Lang_esMX='Aliado, forzar reacción', Description_Lang_esMX='' WHERE ID=1080;
UPDATE dbc_faction SET Name_Lang_esMX='Objeto, Reacción de fuerza', Description_Lang_esMX='' WHERE ID=1081;
UPDATE dbc_faction SET Name_Lang_esMX='REUSE', Description_Lang_esMX='' WHERE ID=1082;
UPDATE dbc_faction SET Name_Lang_esMX='REUSE', Description_Lang_esMX='' WHERE ID=1083;
UPDATE dbc_faction SET Name_Lang_esMX='Vrykul, mar', Description_Lang_esMX='' WHERE ID=1084;
UPDATE dbc_faction SET Name_Lang_esMX='Ofensiva Grito de Guerra', Description_Lang_esMX='Garrosh Grito Infernal lidera las principales fuerzas expedicionarias de la Horda a medida que avanzan hacia Rasganorte para enfrentarse a Arthas y a los ejércitos de la Plaga.' WHERE ID=1085;
UPDATE dbc_faction SET Name_Lang_esMX='Cazador furtivo', Description_Lang_esMX='' WHERE ID=1086;
UPDATE dbc_faction SET Name_Lang_esMX='Monstruo de Fiesta', Description_Lang_esMX='' WHERE ID=1087;
UPDATE dbc_faction SET Name_Lang_esMX='Fúrbolg, Colmillorrojo', Description_Lang_esMX='' WHERE ID=1088;
UPDATE dbc_faction SET Name_Lang_esMX='Fúrbolg, Pataescarcha', Description_Lang_esMX='' WHERE ID=1089;
UPDATE dbc_faction SET Name_Lang_esMX='Kirin Tor', Description_Lang_esMX='Los magos y archimagos que gobiernan la ciudad de Dalaran. Enfrentados a las crecientes amenazas del Vuelo Azul y la Plaga, ahora han mudado su ciudad al corazón de Rasganorte.' WHERE ID=1090;
UPDATE dbc_faction SET Name_Lang_esMX='El Acuerdo del Reposo del Dragón', Description_Lang_esMX='Con el violento levantamiento del Vuelo Azul contra todos los usuarios de magia mortales, los vuelos restantes se han unido bajo el liderazgo del Vuelo Rojo para combatir a sus parientes díscolos.' WHERE ID=1091;
UPDATE dbc_faction SET Name_Lang_esMX='Azjol-Nerub', Description_Lang_esMX='' WHERE ID=1092;
UPDATE dbc_faction SET Name_Lang_esMX='REUSE', Description_Lang_esMX='' WHERE ID=1093;
UPDATE dbc_faction SET Name_Lang_esMX='El Pacto de Plata', Description_Lang_esMX='Un núcleo de elfos nobles militantes que rechazan la admisión de los elfos de sangre en el Kirin Tor. Se han juntado bajo el estandarte de Vereesa Brisaveloz y se han unido a las fuerzas de la Alianza en Rasganorte.' WHERE ID=1094;
UPDATE dbc_faction SET Name_Lang_esMX='Trampero de las Colinas Pardas', Description_Lang_esMX='' WHERE ID=1095;
UPDATE dbc_faction SET Name_Lang_esMX='REUSE', Description_Lang_esMX='' WHERE ID=1096;
UPDATE dbc_faction SET Name_Lang_esMX='Wrath of the Lich King', Description_Lang_esMX='' WHERE ID=1097;
UPDATE dbc_faction SET Name_Lang_esMX='Caballeros de la Espada de Ébano', Description_Lang_esMX='Liberados del control del Rey Exánime, sus otrora caballeros de la Muerte se han reagrupado contra él bajo el estandarte del alto señor Darion Mograine.' WHERE ID=1098;
UPDATE dbc_faction SET Name_Lang_esMX='Puerta de Cólera Plaga', Description_Lang_esMX='' WHERE ID=1099;
UPDATE dbc_faction SET Name_Lang_esMX='Puerta de Cólera Alianza', Description_Lang_esMX='' WHERE ID=1100;
UPDATE dbc_faction SET Name_Lang_esMX='Puerta de Cólera Horda', Description_Lang_esMX='' WHERE ID=1101;
UPDATE dbc_faction SET Name_Lang_esMX='CLB - Bandera - Horda', Description_Lang_esMX='' WHERE ID=1102;
UPDATE dbc_faction SET Name_Lang_esMX='CLB - Bandera - Neutral', Description_Lang_esMX='' WHERE ID=1103;
UPDATE dbc_faction SET Name_Lang_esMX='Tribu Corazón Frenético', Description_Lang_esMX='Expulsados de su tierra por la Plaga, esta feroz tribu de wolvar decidió instalarse en la Cuenca de Sholazar. Su naturaleza agresiva les ha enemistado con las tribus górloc conocidas en conjunto como los Oráculos.' WHERE ID=1104;
UPDATE dbc_faction SET Name_Lang_esMX='Los Oráculos', Description_Lang_esMX='Los górlocs de la Cuenca de Sholazar son una raza de reptiles que se consideran los guardianes de la tecnología titánica restante en la zona (aunque casi no la comprenden). Están sumergidos en una creciente guerra territorial con los wolvar.' WHERE ID=1105;
UPDATE dbc_faction SET Name_Lang_esMX='Cruzada Argenta', Description_Lang_esMX='Liderada por Tirion Vadín, la Cruzada Argenta aúna la reformada Orden de la Mano de Plata con El Alba Argenta en el ataque final contra las fuerzas del Rey Exánime.' WHERE ID=1106;
UPDATE dbc_faction SET Name_Lang_esMX='Trol, Drakkari', Description_Lang_esMX='' WHERE ID=1107;
UPDATE dbc_faction SET Name_Lang_esMX='CdT Arthas', Description_Lang_esMX='' WHERE ID=1108;
UPDATE dbc_faction SET Name_Lang_esMX='CdT Ciudadano de Stratholme', Description_Lang_esMX='' WHERE ID=1109;
UPDATE dbc_faction SET Name_Lang_esMX='CdT Plaga', Description_Lang_esMX='' WHERE ID=1110;
UPDATE dbc_faction SET Name_Lang_esMX='Freya', Description_Lang_esMX='' WHERE ID=1111;
UPDATE dbc_faction SET Name_Lang_esMX='Montura, taxi, Alianza', Description_Lang_esMX='' WHERE ID=1112;
UPDATE dbc_faction SET Name_Lang_esMX='Montura, taxi, Horda', Description_Lang_esMX='' WHERE ID=1113;
UPDATE dbc_faction SET Name_Lang_esMX='Montura, taxi, neutral', Description_Lang_esMX='' WHERE ID=1114;
UPDATE dbc_faction SET Name_Lang_esMX='Elemental, agua', Description_Lang_esMX='' WHERE ID=1115;
UPDATE dbc_faction SET Name_Lang_esMX='Elemental, aire', Description_Lang_esMX='' WHERE ID=1116;
UPDATE dbc_faction SET Name_Lang_esMX='Cuenca de Sholazar', Description_Lang_esMX='' WHERE ID=1117;
UPDATE dbc_faction SET Name_Lang_esMX='Clásicas', Description_Lang_esMX='' WHERE ID=1118;
UPDATE dbc_faction SET Name_Lang_esMX='Los Hijos de Hodir', Description_Lang_esMX='Los gigantes de escarcha de Las Cumbres Tormentosas son una raza bélica afincada en Dun Niffelem.' WHERE ID=1119;
UPDATE dbc_faction SET Name_Lang_esMX='Gigantes de Hierro', Description_Lang_esMX='' WHERE ID=1120;
UPDATE dbc_faction SET Name_Lang_esMX='Vrykul de escarcha', Description_Lang_esMX='' WHERE ID=1121;
UPDATE dbc_faction SET Name_Lang_esMX='Terráneo', Description_Lang_esMX='' WHERE ID=1122;
UPDATE dbc_faction SET Name_Lang_esMX='Árbitro monstruo', Description_Lang_esMX='' WHERE ID=1123;
UPDATE dbc_faction SET Name_Lang_esMX='Los Atracasol', Description_Lang_esMX='Tradicionalmente no se admitía en Dalaran a la Horda, pero han sido admitidos en la ciudad mediante los esfuerzos del archimago Aethas Atracasol. Sus seguidores han retomado su nombre y velan por la sala conocida como Santuario Atracasol.' WHERE ID=1124;
UPDATE dbc_faction SET Name_Lang_esMX='Encuentro Hyldnir', Description_Lang_esMX='' WHERE ID=1125;
UPDATE dbc_faction SET Name_Lang_esMX='Los Natoescarcha', Description_Lang_esMX='Esta misteriosa raza de enanos de escarcha tiene su hogar en Las Cumbres Tormentosas. Hace poco han entablado amistad con miembros de la Liga de Expedicionarios y acogido a miembros de la Alianza en sus tierras.' WHERE ID=1126;
UPDATE dbc_faction SET Name_Lang_esMX='Orgrimmar (Alex Test)', Description_Lang_esMX='' WHERE ID=1127;
UPDATE dbc_faction SET Name_Lang_esMX='Conversión de Tranquillien', Description_Lang_esMX='' WHERE ID=1136;
UPDATE dbc_faction SET Name_Lang_esMX='Conversión Sableinvernales', Description_Lang_esMX='' WHERE ID=1137;
UPDATE dbc_faction SET Name_Lang_esMX='Odia todo', Description_Lang_esMX='' WHERE ID=1145;
UPDATE dbc_faction SET Name_Lang_esMX='Conversión Pacto de Plata', Description_Lang_esMX='' WHERE ID=1154;
UPDATE dbc_faction SET Name_Lang_esMX='Conversión Atracasol', Description_Lang_esMX='' WHERE ID=1155;
UPDATE dbc_faction SET Name_Lang_esMX='El Veredicto Cinéreo', Description_Lang_esMX='Por un pacto entre Tirion Vadín y Darion Mograine, la Cruzada Argenta y los Caballeros de la Espada de Ébano han dejado a un lado sus diferencias durante el ataque a la Ciudadela de la Corona de Hielo hasta que se acabe con el Rey Exánime.' WHERE ID=1156;
UPDATE dbc_faction SET Name_Lang_esMX='CLB - Bandera - Alianza 2', Description_Lang_esMX='' WHERE ID=1159;
UPDATE dbc_faction SET Name_Lang_esMX='CLB - Bandera - Horda 2', Description_Lang_esMX='' WHERE ID=1160;
