UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Gemas de joyero' WHERE ID=2;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Piedra de salud' WHERE ID=3;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Gema de maná' WHERE ID=4;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Joya de tormenta' WHERE ID=6;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Perla encantada' WHERE ID=7;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Luz vinculante' WHERE ID=8;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Piedra vinculante' WHERE ID=9;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Elección de la Muerte' WHERE ID=10;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Veredicto de la muerte' WHERE ID=11;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Juramento de Eitrigg' WHERE ID=12;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Fervor de los Natoescarcha' WHERE ID=13;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Fetiche de poder volátil' WHERE ID=14;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Vitalidad del gigante' WHERE ID=15;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Reino de los muertos' WHERE ID=16;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Reino de los sin vida' WHERE ID=17;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Escarabajo trabador de Satrina' WHERE ID=18;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Consuelo de los derrotados' WHERE ID=19;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Consuelo de los caídos' WHERE ID=20;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Dije de poder volátil' WHERE ID=21;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Venganza de los Renegados' WHERE ID=22;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Llamada de Victor' WHERE ID=23;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sortija de agresión inconmovible' WHERE ID=24;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sortija de violencia deplorable' WHERE ID=25;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sortija del rey traidor' WHERE ID=26;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sortija de las Gemelas Val''kyr' WHERE ID=27;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sortija del temperamento violento' WHERE ID=28;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sortija carnívora' WHERE ID=29;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Aro del Ensalmador oscuro' WHERE ID=30;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sortija de tormenta de fuego' WHERE ID=31;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Anillo de tormenta de fuego' WHERE ID=32;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sortija de Gormok' WHERE ID=33;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Aro de las Gemelas Val''kyr' WHERE ID=34;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Manifestación escabrosa' WHERE ID=35;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sortija de acechallanos' WHERE ID=36;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sello de acechallanos' WHERE ID=37;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Anillo de agresión inconmovible' WHERE ID=38;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Anillo de agresión inconmovible' WHERE ID=39;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Anillo del Ensalmador oscuro' WHERE ID=40;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Anillo del temperamento violento' WHERE ID=41;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sello del rey traidor' WHERE ID=42;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Probar límite de anillo' WHERE ID=43;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Ábaco de Althor' WHERE ID=44;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Adorno de sangre verdadera' WHERE ID=45;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Moneda de la lengua de un cadáver' WHERE ID=46;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Testamento del Libramorte' WHERE ID=47;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Objeto desprendido extraño' WHERE ID=48;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Filacteria del exánime innombrable' WHERE ID=49;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Abominación diminuta en un tarro' WHERE ID=50;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Colmillo impecable de Sindragosa' WHERE ID=51;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Anillo sangriento de abominación' WHERE ID=52;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sello de putrefacción' WHERE ID=53;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Anillo enrollado color guinda' WHERE ID=54;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Anillo desintegrador de Carapútrea' WHERE ID=55;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sortija forjada en frío de Colmillosauro' WHERE ID=56;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sello de la Reina del Crepúsculo' WHERE ID=57;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sello de tres colmillos' WHERE ID=58;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sortija del coloso de hueso' WHERE ID=59;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Anillo eternamente frío de Devium' WHERE ID=60;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sello de muchas bocas' WHERE ID=61;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Anillo de zafiro Razaescarcha' WHERE ID=62;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sortija de gigante' WHERE ID=63;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Aro del laberinto interminable' WHERE ID=64;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Ojo gélido de Tuétano' WHERE ID=65;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Memoria de Malygos' WHERE ID=66;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Poderío de añublo' WHERE ID=67;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Anillo de susurros enloquecedores' WHERE ID=68;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Anillo de rápido ascenso' WHERE ID=69;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Círculo de señor esqueleto' WHERE ID=70;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='El otro sello de Valanar' WHERE ID=71;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sortija de alivio encarnada' WHERE ID=72;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Catalejo de Muradin' WHERE ID=73;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Esquirla de hielo puro' WHERE ID=74;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Órgano inidentificable' WHERE ID=75;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Calavera dentuda susurrante' WHERE ID=76;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Escama Crepuscular' WHERE ID=77;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Anillo de regeneración por fase' WHERE ID=78;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Tributo a Saviana' WHERE ID=79;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Sello de crepúsculo' WHERE ID=80;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Ofrenda de Zarithrian' WHERE ID=81;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Escama Crepuscular afilada' WHERE ID=82;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Escama Crepuscular petrificada' WHERE ID=83;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Escama Crepuscular resplandeciente' WHERE ID=84;
UPDATE dbc_itemlimitcategory SET Name_Lang_esMX='Escama Crepuscular carbonizada' WHERE ID=85;
