UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del mono' WHERE ID=5;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del águila' WHERE ID=6;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del oso' WHERE ID=7;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de la ballena' WHERE ID=8;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del búho' WHERE ID=9;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del gorila' WHERE ID=10;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del falcón' WHERE ID=11;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del jabalí' WHERE ID=12;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del lobo' WHERE ID=13;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del tigre' WHERE ID=14;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de espíritu' WHERE ID=15;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de aguante' WHERE ID=16;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de fuerza' WHERE ID=17;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de agilidad' WHERE ID=18;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de intelecto' WHERE ID=19;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de poder' WHERE ID=20;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de poder con hechizos' WHERE ID=21;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de poder con hechizos' WHERE ID=22;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de poder con hechizos' WHERE ID=23;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de poder con hechizos' WHERE ID=24;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de poder con hechizos' WHERE ID=25;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de poder con hechizos' WHERE ID=26;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de defensa' WHERE ID=27;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de regeneración' WHERE ID=28;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de elusión' WHERE ID=29;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de concentración' WHERE ID=30;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de protección Arcana' WHERE ID=31;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de protección de Fuego' WHERE ID=32;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de protección de Escarcha' WHERE ID=33;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de protección de la Naturaleza' WHERE ID=34;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de protección de las Sombras' WHERE ID=35;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del hechicero' WHERE ID=36;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del médico' WHERE ID=37;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del profeta' WHERE ID=38;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del invocador' WHERE ID=39;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del bandido' WHERE ID=40;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de la bestia' WHERE ID=41;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del hierofante' WHERE ID=42;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del soldado' WHERE ID=43;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del anciano' WHERE ID=44;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del Campeón' WHERE ID=45;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de la prueba' WHERE ID=46;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de bloqueo' WHERE ID=47;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de paladín prueba' WHERE ID=48;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de la arboleda' WHERE ID=49;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de la caza' WHERE ID=50;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de la mente' WHERE ID=51;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del cruzado' WHERE ID=52;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de la visión' WHERE ID=53;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del ancestro' WHERE ID=54;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de la pesadilla' WHERE ID=55;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de la batalla' WHERE ID=56;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de las Sombras' WHERE ID=57;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del Sol' WHERE ID=58;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de la Luna' WHERE ID=59;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de lo Salvaje' WHERE ID=60;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de poder con hechizos' WHERE ID=61;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de fuerza' WHERE ID=62;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de agilidad' WHERE ID=63;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de poder' WHERE ID=64;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de magia' WHERE ID=65;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del caballero' WHERE ID=66;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del vidente' WHERE ID=67;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del oso' WHERE ID=68;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del águila' WHERE ID=69;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del ancestro' WHERE ID=70;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del bandido' WHERE ID=71;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de la batalla' WHERE ID=72;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del anciano' WHERE ID=73;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de la bestia' WHERE ID=74;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del Campeón' WHERE ID=75;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de la arboleda' WHERE ID=76;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del caballero' WHERE ID=77;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del mono' WHERE ID=78;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de la Luna' WHERE ID=79;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de lo Salvaje' WHERE ID=80;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de la ballena' WHERE ID=81;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de la visión' WHERE ID=82;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del Sol' WHERE ID=83;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de aguante' WHERE ID=84;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del hechicero' WHERE ID=85;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del soldado' WHERE ID=86;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de las Sombras' WHERE ID=87;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del pronosticador' WHERE ID=88;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del ladrón' WHERE ID=89;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del nigromante' WHERE ID=90;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del tirador' WHERE ID=91;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='del escudero' WHERE ID=92;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de restauración' WHERE ID=93;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='' WHERE ID=94;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='' WHERE ID=95;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='' WHERE ID=96;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='' WHERE ID=97;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='' WHERE ID=98;
UPDATE dbc_itemrandomsuffix SET Name_Lang_esMX='de velocidad' WHERE ID=99;
