UPDATE dbc_skillline SET DisplayName_Lang_esMX='Escarcha', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=6;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Fuego', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=8;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Armas', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=26;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Combate', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=38;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Sutileza', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=39;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Espadas', Description_Lang_esMX='Cuanto mayor sea tu nivel de habilidad con las armas, mayor será la probabilidad de acertar al dar un golpe.', AlternateVerb_Lang_esMX='' WHERE ID=43;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Hachas', Description_Lang_esMX='Cuanto mayor sea tu nivel de habilidad con las armas, mayor será la probabilidad de acertar al dar un golpe.', AlternateVerb_Lang_esMX='' WHERE ID=44;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Arcos', Description_Lang_esMX='Cuanto mayor sea tu nivel de habilidad con las armas, mayor será la probabilidad de acertar al dar un golpe.', AlternateVerb_Lang_esMX='' WHERE ID=45;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Armas de fuego', Description_Lang_esMX='Cuanto mayor sea tu nivel de habilidad con las armas, mayor será la probabilidad de acertar al dar un golpe.', AlternateVerb_Lang_esMX='' WHERE ID=46;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Dominio de bestias', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=50;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Supervivencia', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=51;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mazas', Description_Lang_esMX='Cuanto mayor sea tu nivel de habilidad con las armas, mayor será la probabilidad de acertar al dar un golpe.', AlternateVerb_Lang_esMX='' WHERE ID=54;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Espadas de dos manos', Description_Lang_esMX='Cuanto mayor sea tu nivel de habilidad con las armas, mayor será la probabilidad de acertar al dar un golpe.', AlternateVerb_Lang_esMX='' WHERE ID=55;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Sagrado', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=56;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Magia sombría', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=78;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Defensa', Description_Lang_esMX='Con una defensa alta tendrás más posibilidades de esquivar, parar o bloquear ataques, así que será más difícil que te acierte un golpe y que los monstruos te asesten un golpe crítico.', AlternateVerb_Lang_esMX='' WHERE ID=95;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Idioma: común', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=98;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Racial enano', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=101;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Idioma: orco', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=109;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Idioma: enánico', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=111;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Idioma: darnassiano', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=113;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Idioma: taurahe', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=115;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Doble empuñadura', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=118;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Racial tauren', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=124;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Racial orco', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=125;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Racial elfo de la noche', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=126;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Primeros auxilios', Description_Lang_esMX='Con un nivel alto de habilidad en primeros auxilios, aprenderás primeros auxilios de nivel superior. Visita a los instructores dispersos por el mundo, completa misiones y derrota a los monstruos para conseguirlas.', AlternateVerb_Lang_esMX='' WHERE ID=129;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Combate feral', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=134;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Bastones', Description_Lang_esMX='Cuanto mayor sea tu nivel de habilidad con las armas, mayor será la probabilidad de acertar al dar un golpe.', AlternateVerb_Lang_esMX='' WHERE ID=136;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Idioma: thalassiano', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=137;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Idioma: dracónico', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=138;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Idioma: demoníaco', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=139;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Idioma: titánico', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=140;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Idioma: lengua antigua', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=141;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Supervivencia', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=142;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Montar caballos', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=148;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Montar lobos', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=149;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Montar tigres', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=150;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Montar carneros', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=152;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Nadar', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=155;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mazas de dos manos', Description_Lang_esMX='Cuanto mayor sea tu nivel de habilidad con las armas, mayor será la probabilidad de acertar al dar un golpe.', AlternateVerb_Lang_esMX='' WHERE ID=160;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Sin armas', Description_Lang_esMX='Cuanto mayor sea tu nivel de habilidad, mayor será la probabilidad de acertar al dar un golpe.', AlternateVerb_Lang_esMX='' WHERE ID=162;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Puntería', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=163;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Herrería', Description_Lang_esMX='Con un nivel alto de habilidad en herrería, podrás aprender mejores diseños de herrería. Visita a los instructores dispersos por el mundo, completa misiones y derrota a los monstruos para conseguirlos.', AlternateVerb_Lang_esMX='Transformar' WHERE ID=164;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Peletería', Description_Lang_esMX='Con un nivel alto de habilidad en peletería, podrás aprender patrones de nivel superior. Visita a los instructores dispersos por el mundo, completa misiones y derrota a los monstruos para conseguirlos.', AlternateVerb_Lang_esMX='Remachar' WHERE ID=165;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Alquimia', Description_Lang_esMX='Con un nivel alto de habilidad en alquimia, podrás aprender recetas de nivel superior. Visita a los instructores dispersos por el mundo, completa misiones y derrota a los monstruos para conseguirlas.', AlternateVerb_Lang_esMX='Rellenar' WHERE ID=171;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Hachas de dos manos', Description_Lang_esMX='Cuanto mayor sea tu nivel de habilidad con las armas, mayor será la probabilidad de acertar al dar un golpe.', AlternateVerb_Lang_esMX='' WHERE ID=172;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Dagas', Description_Lang_esMX='Cuanto mayor sea tu nivel de habilidad con las armas, mayor será la probabilidad de acertar al dar un golpe.', AlternateVerb_Lang_esMX='' WHERE ID=173;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Armas arrojadizas', Description_Lang_esMX='Cuanto mayor sea tu nivel de habilidad con las armas, mayor será la probabilidad de acertar al dar un golpe.', AlternateVerb_Lang_esMX='' WHERE ID=176;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Herboristería', Description_Lang_esMX='Con un nivel alto de habilidad en herboristería podrás recolectar hierbas difíciles de encontrar por el mundo. Si no puedes conseguir una hierba en particular, aumenta tu habilidad recolectando hierbas más fáciles de conseguir en áreas de nivel inferior.', AlternateVerb_Lang_esMX='' WHERE ID=182;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='COMÚN (DND)', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=183;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Reprensión', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=184;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Cocina', Description_Lang_esMX='Con un nivel alto de habilidad en cocina, aprenderás recetas de nivel superior. Visita a los instructores dispersos por el mundo, completa misiones y derrota a los monstruos para conseguirlas.', AlternateVerb_Lang_esMX='' WHERE ID=185;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Minería', Description_Lang_esMX='Con un alto nivel de habilidad en minería, podrás obtener minerales de vetas más complejas. Si no puedes obtener un mineral específico, intenta subir tu nivel de habilidad primero en zonas más fáciles.', AlternateVerb_Lang_esMX='' WHERE ID=186;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: diablillo', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=188;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: manáfago', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=189;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Sastrería', Description_Lang_esMX='Con un nivel alto de habilidad en sastrería, podrás aprender patrones de nivel superior. Visita a los instructores dispersos por el mundo, completa misiones y derrota a los monstruos para conseguirlos.', AlternateVerb_Lang_esMX='Bordar' WHERE ID=197;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Ingeniería', Description_Lang_esMX='Con un nivel alto de habilidad en ingeniería, podrás aprender esquemas de ingeniería de nivel superior. Visita a los instructores dispersos por el mundo, completa misiones y derrota a los monstruos para conseguirlos.', AlternateVerb_Lang_esMX='Componer' WHERE ID=202;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: araña', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=203;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: abisario', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=204;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: súcubo', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=205;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: infernal', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=206;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: guardia apocalíptico', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=207;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: lobo', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=208;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: felino', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=209;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: oso', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=210;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: jabalí', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=211;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: crocolisco', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=212;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: carroñero', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=213;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: cangrejo', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=214;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: gorila', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=215;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: raptor', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=217;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: zancudo', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=218;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Racial: no-muerto', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=220;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Ballestas', Description_Lang_esMX='Cuanto mayor sea tu nivel de habilidad con las armas, mayor será la probabilidad de acertar al dar un golpe.', AlternateVerb_Lang_esMX='' WHERE ID=226;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Varitas', Description_Lang_esMX='Cuanto mayor sea tu nivel de habilidad con las armas, mayor será la probabilidad de acertar al dar un golpe.', AlternateVerb_Lang_esMX='' WHERE ID=228;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Armas de asta', Description_Lang_esMX='Cuanto mayor sea tu nivel de habilidad con las armas, mayor será la probabilidad de acertar al dar un golpe.', AlternateVerb_Lang_esMX='' WHERE ID=229;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: escórpido', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=236;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Arcano', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=237;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: tortuga', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=251;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Asesinato', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=253;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Furia', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=256;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Protección', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=257;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Protección', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=267;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: cazador genérico', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=270;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Malla de placas', Description_Lang_esMX='Permite vestir armaduras de placas.', AlternateVerb_Lang_esMX='' WHERE ID=293;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Idioma: gnomótico', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=313;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Idioma: trol', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=315;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Encantamiento', Description_Lang_esMX='Con un alto nivel de habilidad en encantamiento, podrás aprender formulas mucho más poderosas. Visita a los instructores dispersos por el mundo, completa misiones y derrota a los monstruos para conseguirlas.', AlternateVerb_Lang_esMX='Encantar' WHERE ID=333;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Demonología', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=354;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Aflicción', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=355;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Pesca', Description_Lang_esMX='Con un nivel alto de habilidad en pesca aumentará la probabilidad de que pesques algo en las aguas del mundo. Si te cuesta mucho pescar, ve a pescar a otra área de nivel inferior o compra un cebo.', AlternateVerb_Lang_esMX='' WHERE ID=356;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mejora', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=373;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Restauración', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=374;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Combate elemental', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=375;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Desollar', Description_Lang_esMX='Con un nivel alto de habilidad en desollar podrás despellejar monstruos de nivel superior. Cuando tu habilidad sea superior a 100, podrás dividirla entre 5 para determinar hasta qué nivel puedes despellejar.', AlternateVerb_Lang_esMX='' WHERE ID=393;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Malla', Description_Lang_esMX='Permite vestir armaduras de malla.', AlternateVerb_Lang_esMX='' WHERE ID=413;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Cuero', Description_Lang_esMX='Permite vestir armaduras de cuero.', AlternateVerb_Lang_esMX='' WHERE ID=414;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Tela', Description_Lang_esMX='Permite vestir armaduras de tela.', AlternateVerb_Lang_esMX='' WHERE ID=415;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Escudo', Description_Lang_esMX='Permite el uso de escudos.', AlternateVerb_Lang_esMX='' WHERE ID=433;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Armas de puño', Description_Lang_esMX='Permite el uso de armas de puño. La probabilidad de acertar al dar un golpe viene determinada por tu habilidad sin armas.', AlternateVerb_Lang_esMX='' WHERE ID=473;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Montar raptor', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=533;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Montar mecazancudos', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=553;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Equitación para no-muertos', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=554;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Restauración', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=573;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Equilibrio', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=574;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Destrucción', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=593;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Sagrado', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=594;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Disciplina', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=613;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Ganzúa', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=633;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: murciélago', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=653;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: hiena', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=654;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: ave rapaz', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=655;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: serpiente alada', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=656;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Idioma: viscerálico', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=673;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Montar kodos', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=713;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Racial: trol', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=733;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Racial: gnomo', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=753;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Racial: humano', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=754;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Joyería', Description_Lang_esMX='Con un nivel alto de habilidad en joyería, aprenderás diseños de nivel superior. Visita a los instructores dispersos por el mundo, completa misiones y derrota a los monstruos para conseguirlos.', AlternateVerb_Lang_esMX='Transformar' WHERE ID=755;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Racial elfo de sangre', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=756;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota - Evento - Control remoto', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=758;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Idioma: draenei', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=759;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Racial draenei', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=760;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: guardia vil', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=761;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Equitación', Description_Lang_esMX='Una habilidad superior montando te permite montar bestias más rápidas y exóticas.', AlternateVerb_Lang_esMX='' WHERE ID=762;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: dracohalcón', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=763;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: raya abisal', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=764;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: esporiélago', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=765;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: acechador de distorsión', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=766;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: devastador', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=767;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: serpiente', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=768;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Interno', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=769;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Sangre', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=770;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Escarcha', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=771;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Profano', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=772;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Inscripción', Description_Lang_esMX='Con un nivel alto de habilidad en inscripción podrás aprender inscripciones más avanzadas. Las adquirirás aprendiendo pergaminos por el mundo.', AlternateVerb_Lang_esMX='Inscribir' WHERE ID=773;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: palomilla', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=775;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Forja de runas', Description_Lang_esMX='', AlternateVerb_Lang_esMX='Grabar' WHERE ID=776;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Monturas', Description_Lang_esMX='Tus monturas.', AlternateVerb_Lang_esMX='' WHERE ID=777;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Compañeros', Description_Lang_esMX='Tus compañeros.', AlternateVerb_Lang_esMX='' WHERE ID=778;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: quimera exótica', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=780;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: demosaurio exótico', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=781;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: necrófago', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=782;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: silítido exótico', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=783;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: gusano exótico', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=784;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: avispa', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=785;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: rinoceronte exótico', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=786;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: can del Núcleo exótico', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=787;
UPDATE dbc_skillline SET DisplayName_Lang_esMX='Mascota: bestia espíritu exótica', Description_Lang_esMX='', AlternateVerb_Lang_esMX='' WHERE ID=788;
