UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Rethilgore' WHERE ID=464;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Zarpador el Carnicero' WHERE ID=465;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Barón Filargenta' WHERE ID=466;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Comandante Vallefont' WHERE ID=467;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Odo el vigía ciego' WHERE ID=468;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Fenrus el Devorador' WHERE ID=469;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Maestro de lobos Nandos' WHERE ID=470;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Archimago Arugal' WHERE ID=471;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Targor el Pavoroso' WHERE ID=536;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Kam Furiahonda' WHERE ID=537;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Hamhock' WHERE ID=538;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Dextren Ward' WHERE ID=540;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Bazil Thredd' WHERE ID=539;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Rhahk''zor' WHERE ID=161;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sneed' WHERE ID=162;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gilnid' WHERE ID=163;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Don Mamporro' WHERE ID=164;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Cocinitas' WHERE ID=165;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Capitán Verdetez' WHERE ID=166;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Edwin VanCleef' WHERE ID=167;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lady Anacondra' WHERE ID=585;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lord Cobrahn' WHERE ID=586;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Kresh' WHERE ID=587;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lord Pythas' WHERE ID=588;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Skum' WHERE ID=589;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lord Serpentis' WHERE ID=590;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Verdan el Eterno' WHERE ID=591;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Mutanus el Devorador' WHERE ID=592;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Portavoz de la muerte Jargba' WHERE ID=440;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Roogug' WHERE ID=438;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Aggem Malaespina' WHERE ID=439;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Señor supremo Colmicarnero' WHERE ID=441;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Agathelos el Furioso' WHERE ID=883;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Charlga Filonavaja' WHERE ID=443;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ghamoo-ra' WHERE ID=219;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lady Sarevess' WHERE ID=220;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gelihast' WHERE ID=221;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lorgus Jett' WHERE ID=222;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Viejo Serra''kis' WHERE ID=224;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Señor Crepuscular Kelris' WHERE ID=225;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Aku''mai' WHERE ID=226;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Revelosh' WHERE ID=547;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Los enanos desaparecidos' WHERE ID=548;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Hierraya' WHERE ID=549;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Vigilante de piedra anciano' WHERE ID=551;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Galgann Flamartillo' WHERE ID=552;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Grimlok' WHERE ID=553;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Archaedas' WHERE ID=554;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Grubbis' WHERE ID=379;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Radiactivo viscoso' WHERE ID=378;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Electrocutor 6000' WHERE ID=380;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Golpeamasa 9-60' WHERE ID=381;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Mekigeniero Termochufe' WHERE ID=382;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Atal''alarion' WHERE ID=485;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Jammal''an el Profeta' WHERE ID=488;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Segasueños' WHERE ID=486;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sastrón' WHERE ID=487;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Morphaz' WHERE ID=490;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Hazzas' WHERE ID=491;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Avatar de Hakkar' WHERE ID=492;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sombra de Eranikus' WHERE ID=493;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Tuten''kash' WHERE ID=434;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Mordresh Ojo de Fuego' WHERE ID=435;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Glotón' WHERE ID=436;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Amnennar el Gélido' WHERE ID=437;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Interrogador Vishas' WHERE ID=444;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Mago sangriento Thalnos' WHERE ID=445;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Maestro de canes Loksey' WHERE ID=446;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Arcanista Doan' WHERE ID=447;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Herod' WHERE ID=448;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Alto inquisidor Ribalimpia' WHERE ID=449;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Alta inquisidora Melenablanca' WHERE ID=450;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Hidromántica Velratha' WHERE ID=593;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gahz''rilla' WHERE ID=594;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Antu''sul' WHERE ID=595;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Theka el Mártir' WHERE ID=596;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Médico brujo Zum''rah' WHERE ID=597;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Nekrum Cometripas' WHERE ID=598;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sacerdote oscuro Sezz''ziz' WHERE ID=599;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Jefe Ukorz Cabellarena' WHERE ID=600;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Alto señor Omokk' WHERE ID=267;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Cazadora de las Sombras Vosh''gajin' WHERE ID=268;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Maestro de guerra Voone' WHERE ID=269;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Madre Telabrasada' WHERE ID=270;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Urok Aullasino' WHERE ID=271;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Intendente Zigris' WHERE ID=272;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Halycon' WHERE ID=274;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gizrul el Esclavista' WHERE ID=273;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Señor supremo Vermiothalak' WHERE ID=275;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Piroguardia Brasadivino' WHERE ID=276;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Solakar Corona de Fuego' WHERE ID=277;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Jefe de Guerra Rend Puño Negro' WHERE ID=278;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='La Bestia' WHERE ID=279;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='General Drakkisath' WHERE ID=280;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Alta interrogadora Gerstahn' WHERE ID=227;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lord Roccor' WHERE ID=228;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Maestro de canes Grebmar' WHERE ID=229;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Círculo de la Ley' WHERE ID=230;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Piromántico Fruto del Saber' WHERE ID=231;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lord Incendius' WHERE ID=232;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Depositario Stilgiss' WHERE ID=233;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Finoso Virunegro' WHERE ID=234;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Bael''Gar' WHERE ID=235;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='General Forjainquina' WHERE ID=236;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Señor Gólem Argelmach' WHERE ID=237;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Hurley Negrálito' WHERE ID=238;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Falange' WHERE ID=239;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ribbly Llavenrosca' WHERE ID=240;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Plugger Aropatoso' WHERE ID=241;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Embajador Latifuego' WHERE ID=242;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Los Siete' WHERE ID=243;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Magmus' WHERE ID=244;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Emperador Dagran Thaurissan' WHERE ID=245;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Onyxia' WHERE ID=707;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Onyxia' WHERE ID=708;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Cronolord Deja' WHERE ID=287;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Cronolord Deja' WHERE ID=288;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Temporus' WHERE ID=289;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Temporus' WHERE ID=290;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Aeonus' WHERE ID=291;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Aeonus' WHERE ID=292;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Kirtonos el Heraldo' WHERE ID=451;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Jandice Barov' WHERE ID=452;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Traquesangre' WHERE ID=453;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Marduk Pozonegro' WHERE ID=454;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Vectus' WHERE ID=455;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ras Murmuhielo' WHERE ID=456;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Instructora Malicia' WHERE ID=457;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Doctor Theolen Krastinov' WHERE ID=458;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Tradicionalista Polkelt' WHERE ID=459;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El Devorador' WHERE ID=460;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lord Alexei Barov' WHERE ID=461;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lady Illucia Barov' WHERE ID=462;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Maestro oscuro Gandling' WHERE ID=463;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Suma sacerdotisa Jeklik' WHERE ID=785;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sumo sacerdote Venoxis' WHERE ID=784;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Suma sacerdotisa Mar''li' WHERE ID=786;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Señor sangriento Mandokir' WHERE ID=787;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Extremo de la Locura' WHERE ID=788;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sumo sacerdote Thekal' WHERE ID=789;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gahz''ranka' WHERE ID=790;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Suma sacerdotisa Arlokk' WHERE ID=791;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Jin''do el Aojador' WHERE ID=792;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Hakkar' WHERE ID=793;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Cantachimeneas Forresten' WHERE ID=473;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Timmy el Cruel' WHERE ID=474;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Cañonero Jefe Willey' WHERE ID=475;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Malor el Entusiasta' WHERE ID=476;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Archivista Galford' WHERE ID=477;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Balnazzar' WHERE ID=478;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El Imperdonable' WHERE ID=472;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Baronesa Anastari' WHERE ID=479;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Nerub''enkan' WHERE ID=480;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Maleki el Pálido' WHERE ID=481;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Magistrado Barthilas' WHERE ID=482;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ramstein el Empachador' WHERE ID=483;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Barón Osahendido' WHERE ID=484;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Noxxion' WHERE ID=422;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Latisable' WHERE ID=423;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lord Lenguavil' WHERE ID=424;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Celebras el Maldito' WHERE ID=425;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Derrumblo' WHERE ID=426;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Manitas Gizlock' WHERE ID=427;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Escamapodrida' WHERE ID=428;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Princesa Theradras' WHERE ID=429;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ogglesílex' WHERE ID=430;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Jergosh el Convocador' WHERE ID=432;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Bazzalan' WHERE ID=433;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Taragaman el Hambriento' WHERE ID=431;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lucifron' WHERE ID=663;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Magmadar' WHERE ID=664;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gehennas' WHERE ID=665;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Garr' WHERE ID=666;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Shazzrah' WHERE ID=667;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Barón Geddon' WHERE ID=668;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sulfuron Presagista' WHERE ID=669;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Golemagg el Incinerador' WHERE ID=670;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Mayordomo Executus' WHERE ID=671;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ragnaros' WHERE ID=672;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Zevrim Pezuñahendida' WHERE ID=343;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Hidromilecio' WHERE ID=344;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lethtendris' WHERE ID=345;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Alzzin el Formaferal' WHERE ID=346;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Tendris Madeguerra' WHERE ID=350;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Illyanna Roblecuervo' WHERE ID=347;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Magister Kalendris' WHERE ID=348;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Immol''thar' WHERE ID=349;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Príncipe Tortheldrin' WHERE ID=361;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Guardia Mol''dar' WHERE ID=362;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Vapuleador Kreeg' WHERE ID=363;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Guardia Fengus' WHERE ID=364;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Guardia Slip''kik' WHERE ID=365;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Capitán Kromcrush' WHERE ID=366;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Cho''Rush el Observador' WHERE ID=367;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Rey Gordok' WHERE ID=368;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sangrevaja el Indomable' WHERE ID=610;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Vaelastrasz el Corrupto' WHERE ID=611;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Señor de linaje Capazote' WHERE ID=612;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Faucefogo' WHERE ID=613;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ebanorroca' WHERE ID=614;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Flamagor' WHERE ID=615;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Chromaggus' WHERE ID=616;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Nefarian' WHERE ID=617;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Kurinnaxx' WHERE ID=718;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='General Rajaxx' WHERE ID=719;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Moam' WHERE ID=720;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Buru el Manducador' WHERE ID=721;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ayamiss el Cazador' WHERE ID=722;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Osirio el Sinmarcas' WHERE ID=723;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El profeta Skeram' WHERE ID=709;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Realeza silítida' WHERE ID=710;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Guardia de batalla Sartura' WHERE ID=711;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Fankriss el Implacable' WHERE ID=712;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Viscidus' WHERE ID=713;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Princesa Huhuran' WHERE ID=714;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Emperadores Gemelos' WHERE ID=715;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ouro' WHERE ID=716;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='C''Thun' WHERE ID=717;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Attumen el Montero' WHERE ID=652;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Moroes' WHERE ID=653;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Doncella de Virtud' WHERE ID=654;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Evento de la Opera' WHERE ID=655;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Curator' WHERE ID=656;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Terestian Pezuña Enferma' WHERE ID=657;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sombra de Aran' WHERE ID=658;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Rencor abisal' WHERE ID=659;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Evento del Ajedrez' WHERE ID=660;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Príncipe Malchezaar' WHERE ID=661;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Nocturno' WHERE ID=662;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Anub''Rekhan' WHERE ID=673;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Anub''Rekhan' WHERE ID=674;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gran Viuda Faerlina' WHERE ID=677;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gran Viuda Faerlina' WHERE ID=678;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Maexxna' WHERE ID=679;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Maexxna' WHERE ID=680;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Noth el Pesteador' WHERE ID=681;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Noth el Pesteador' WHERE ID=682;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Heigan el Impuro' WHERE ID=683;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Heigan el Impuro' WHERE ID=684;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Loatheb' WHERE ID=685;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Loatheb' WHERE ID=686;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Instructor Razuvious' WHERE ID=687;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Instructor Razuvious' WHERE ID=689;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gothik el Cosechador' WHERE ID=690;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gothik el Cosechador' WHERE ID=691;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Los Cuatro Jinetes' WHERE ID=692;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Los Cuatro Jinetes' WHERE ID=693;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Remendejo' WHERE ID=694;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Remendejo' WHERE ID=695;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Grobbulus' WHERE ID=696;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Grobbulus' WHERE ID=697;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gluth' WHERE ID=698;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gluth' WHERE ID=699;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Thaddius' WHERE ID=700;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Thaddius' WHERE ID=701;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sapphiron' WHERE ID=702;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sapphiron' WHERE ID=703;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Kel''Thuzad' WHERE ID=704;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Kel''Thuzad' WHERE ID=706;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ira Fríoinvierno' WHERE ID=618;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Anetheron' WHERE ID=619;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Kaz''rogal' WHERE ID=620;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Azgalor' WHERE ID=621;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Archimonde' WHERE ID=622;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Brujo supremo Malbisal' WHERE ID=407;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Brujo supremo Malbisal' WHERE ID=408;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Belisario O''mrogg' WHERE ID=410;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Guardia de sangre Porung' WHERE ID=409;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Jefe de Guerra Kargath Garrafilada' WHERE ID=412;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Belisario O''mrogg' WHERE ID=411;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Jefe de Guerra Kargath Garrafilada' WHERE ID=413;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El Hacedor' WHERE ID=401;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El Hacedor' WHERE ID=402;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Broggok' WHERE ID=403;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Broggok' WHERE ID=404;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Keli''dan el Ultrajador' WHERE ID=405;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Keli''dan el Ultrajador' WHERE ID=406;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Guardián vigía Gargolmar' WHERE ID=392;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Guardián vigía Gargolmar' WHERE ID=393;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Omor el Sinmarcas' WHERE ID=394;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Omor el Sinmarcas' WHERE ID=395;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Vazruden el Heraldo' WHERE ID=396;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Vazruden el Heraldo' WHERE ID=397;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Magtheridon' WHERE ID=651;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Hidromántica Thespia' WHERE ID=314;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Hidromántica Thespia' WHERE ID=315;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Mekigeniero Vaporino' WHERE ID=316;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Mekigeniero Vaporino' WHERE ID=317;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Señor de la guerra Kalithresh' WHERE ID=318;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Señor de la guerra Kalithresh' WHERE ID=319;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Panthambre' WHERE ID=320;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Panthambre' WHERE ID=321;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ghaz''an' WHERE ID=322;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ghaz''an' WHERE ID=323;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Señor del pantano Musel''ek' WHERE ID=329;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Señor del pantano Musel''ek' WHERE ID=330;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='La Acechadora Negra' WHERE ID=331;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='La Acechadora Negra' WHERE ID=332;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Mennu el Traidor' WHERE ID=301;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Mennu el Traidor' WHERE ID=304;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Rokmar el Crujidor' WHERE ID=302;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Rokmar el Crujidor' WHERE ID=305;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Quagmirran' WHERE ID=303;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Quagmirran' WHERE ID=306;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Hydross el Inestable' WHERE ID=623;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El Rondador de abajo' WHERE ID=624;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Leotheras el Ciego' WHERE ID=625;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Señor de las profundidades Karathress' WHERE ID=626;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Morogrim Levantamareas' WHERE ID=627;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lady Vashj' WHERE ID=628;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Al''ar' WHERE ID=730;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Atracador del vacío' WHERE ID=731;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gran astromante Solarian' WHERE ID=732;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Kael''thas Caminante del Sol' WHERE ID=733;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Zereketh el Desatado' WHERE ID=494;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Zereketh el Desatado' WHERE ID=495;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Dalliah la Oradora del Sino' WHERE ID=496;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Dalliah la Oradora del Sino' WHERE ID=497;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Arúspice de cólera Soccothrates' WHERE ID=498;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Arúspice de cólera Soccothrates' WHERE ID=499;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Presagista Cieloriss' WHERE ID=500;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Presagista Cieloriss' WHERE ID=501;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Comandante Sarannis' WHERE ID=502;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Comandante Sarannis' WHERE ID=504;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gran botánico Freywinn' WHERE ID=505;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gran botánico Freywinn' WHERE ID=506;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Thorngrin el Cuidador' WHERE ID=507;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Thorngrin el Cuidador' WHERE ID=508;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Laj' WHERE ID=509;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Laj' WHERE ID=510;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Disidente de distorsión' WHERE ID=511;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Disidente de distorsión' WHERE ID=512;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Mecano-lord Capacitus' WHERE ID=513;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Mecano-lord Capacitus' WHERE ID=514;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Abisálica Sepethrea' WHERE ID=515;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Abisálica Sepethrea' WHERE ID=516;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Pathaleon el Calculador' WHERE ID=517;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Pathaleon el Calculador' WHERE ID=518;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Embajador Faucinferno' WHERE ID=208;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Embajador Faucinferno' WHERE ID=255;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Negrozón el Incitador' WHERE ID=209;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Negrozón el Incitador' WHERE ID=256;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Maestro mayor Vorpil' WHERE ID=210;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Maestro mayor Vorpil' WHERE ID=257;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Murmullo' WHERE ID=211;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Murmullo' WHERE ID=258;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Tejeoscuro Syth' WHERE ID=206;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Tejeoscuro Syth' WHERE ID=252;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Rey Garra Ikiss' WHERE ID=207;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Anzu' WHERE ID=253;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Rey Garra Ikiss' WHERE ID=254;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Pandemonius' WHERE ID=203;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Pandemonius' WHERE ID=248;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Tavarok' WHERE ID=204;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Tavarok' WHERE ID=249;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Yor' WHERE ID=250;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Príncipe-nexo Shaffar' WHERE ID=205;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Príncipe-nexo Shaffar' WHERE ID=251;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Shirrak el Vigía de los Muertos' WHERE ID=201;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Shirrak el Vigía de los Muertos' WHERE ID=246;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Exarca Maladaar' WHERE ID=202;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Exarca Maladaar' WHERE ID=247;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Teniente Drake' WHERE ID=286;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Teniente Drake' WHERE ID=285;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Capitán Skarloc' WHERE ID=283;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Capitán Skarloc' WHERE ID=284;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Cazador de Época' WHERE ID=281;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Cazador de Época' WHERE ID=282;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gran señor de la guerra Naj''entus' WHERE ID=601;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Supremus' WHERE ID=602;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sombra de Akama' WHERE ID=603;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Teron Sanguino' WHERE ID=604;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gurtogg Sangre Hirviente' WHERE ID=605;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Relicario de Almas' WHERE ID=606;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Madre Shahraz' WHERE ID=607;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El Consejo Illidari' WHERE ID=608;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Illidan Tempestira' WHERE ID=609;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Su majestad Maulgar' WHERE ID=649;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gruul el Asesino de Dragones' WHERE ID=650;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Akil''zon' WHERE ID=778;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Nalorakk' WHERE ID=779;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Jan''alai' WHERE ID=780;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Halazzi' WHERE ID=781;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Señor aojador Malacrass' WHERE ID=782;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Zul''jin' WHERE ID=783;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Príncipe Keleseth' WHERE ID=571;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Príncipe Keleseth' WHERE ID=572;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Skarvald y Dalronn' WHERE ID=573;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Skarvald y Dalronn' WHERE ID=574;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ingvar el Desvalijador' WHERE ID=575;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ingvar el Desvalijador' WHERE ID=576;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Svala Tumbapena' WHERE ID=577;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Svala Tumbapena' WHERE ID=578;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gortok Pezuña Pálida' WHERE ID=579;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gortok Pezuña Pálida' WHERE ID=580;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Skadi el Despiadado' WHERE ID=581;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Skadi el Despiadado' WHERE ID=582;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Rey Ymiron' WHERE ID=583;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Rey Ymiron' WHERE ID=584;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Comandante helado' WHERE ID=519;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gran maga Telestra' WHERE ID=520;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gran maga Telestra' WHERE ID=521;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Anomalus' WHERE ID=522;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Anomalus' WHERE ID=523;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ormorok el Talador' WHERE ID=524;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ormorok el Talador' WHERE ID=525;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Keristrasza' WHERE ID=526;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Keristrasza' WHERE ID=527;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Drakos el Interrogador' WHERE ID=528;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Drakos el Interrogador' WHERE ID=529;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Varos Zancanubes' WHERE ID=530;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Varos Zancanubes' WHERE ID=531;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Señor de la Magia Urom' WHERE ID=532;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Señor de la Magia Urom' WHERE ID=533;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Guardián-Ley Eregos' WHERE ID=534;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Guardián-Ley Eregos' WHERE ID=535;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Kalecgos' WHERE ID=724;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Brutallus' WHERE ID=725;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Brumavil' WHERE ID=726;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gemelas Eredar' WHERE ID=727;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='M''uru' WHERE ID=728;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Kil''jaeden' WHERE ID=729;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Selin Corazón de Fuego' WHERE ID=414;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Selin Corazón de Fuego' WHERE ID=415;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Vexallus' WHERE ID=416;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Vexallus' WHERE ID=417;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sacerdotisa Delrissa' WHERE ID=418;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sacerdotisa Delrissa' WHERE ID=419;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Kael''thas Caminante del Sol' WHERE ID=420;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Kael''thas Caminante del Sol' WHERE ID=421;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gancho' WHERE ID=293;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gancho' WHERE ID=297;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Salramm el Modelador de carne' WHERE ID=294;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Salramm el Modelador de carne' WHERE ID=298;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Cronolord Época' WHERE ID=295;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Cronolord Época' WHERE ID=299;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Mal''Ganis' WHERE ID=296;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Mal''Ganis' WHERE ID=300;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Krystallus' WHERE ID=563;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Krystallus' WHERE ID=564;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Doncella de Pena' WHERE ID=565;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Doncella de Pena' WHERE ID=566;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El Tribunal de los Tiempos' WHERE ID=567;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El Tribunal de los Tiempos' WHERE ID=568;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sjonnir el Afilador' WHERE ID=569;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sjonnir el Afilador' WHERE ID=570;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Cuernotrol' WHERE ID=369;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Cuernotrol' WHERE ID=370;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Novos el Invocador' WHERE ID=371;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Novos el Invocador' WHERE ID=372;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Rey Dred' WHERE ID=373;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Rey Dred' WHERE ID=374;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El profeta Tharon''ja' WHERE ID=375;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El profeta Tharon''ja' WHERE ID=376;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Krik''thir el Vigía de las puertas' WHERE ID=216;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Krik''thir el Vigía de las puertas' WHERE ID=264;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Hadronox' WHERE ID=217;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Hadronox' WHERE ID=265;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Anub''arak' WHERE ID=218;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Anub''arak' WHERE ID=266;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='General Bjarngrim' WHERE ID=555;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='General Bjarngrim' WHERE ID=556;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Volkhan' WHERE ID=557;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Volkhan' WHERE ID=558;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ionar' WHERE ID=559;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ionar' WHERE ID=560;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Loken' WHERE ID=561;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Loken' WHERE ID=562;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Leviatán de llamas' WHERE ID=744;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Leviatán de llamas' WHERE ID=758;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ignis el Maestro de la Caldera' WHERE ID=745;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ignis el Maestro de la Caldera' WHERE ID=759;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Tajoescama' WHERE ID=746;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Desarmador XA-002' WHERE ID=747;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El Consejo de Hierro' WHERE ID=748;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Tajoescama' WHERE ID=760;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Kologarn' WHERE ID=749;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Desarmador XA-002' WHERE ID=761;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Auriaya' WHERE ID=750;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El Consejo de Hierro' WHERE ID=762;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Hodir' WHERE ID=751;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Kologarn' WHERE ID=763;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Thorim' WHERE ID=752;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Auriaya' WHERE ID=764;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Freya' WHERE ID=753;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Hodir' WHERE ID=765;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Mimiron' WHERE ID=754;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Thorim' WHERE ID=766;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='General Vezax' WHERE ID=755;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Freya' WHERE ID=767;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Yogg-Saron' WHERE ID=756;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Mimiron' WHERE ID=768;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Algalon el Observador' WHERE ID=757;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='General Vezax' WHERE ID=769;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Yogg-Saron' WHERE ID=770;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Algalon el Observador' WHERE ID=771;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Slad''ran' WHERE ID=383;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Slad''ran' WHERE ID=384;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Coloso Drakkari' WHERE ID=385;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Coloso Drakkari' WHERE ID=386;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Moorabi' WHERE ID=387;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Moorabi' WHERE ID=388;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gal''darah' WHERE ID=390;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Eck el Feroz' WHERE ID=389;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gal''darah' WHERE ID=391;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Primer prisionero' WHERE ID=541;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Primer prisionero' WHERE ID=542;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Segundo prisionero' WHERE ID=543;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Segundo prisionero' WHERE ID=544;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Cianigosa' WHERE ID=545;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Cianigosa' WHERE ID=546;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Vesperon' WHERE ID=740;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Tenebron' WHERE ID=736;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Vesperon' WHERE ID=741;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Tenebron' WHERE ID=737;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Shadron' WHERE ID=738;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Shadron' WHERE ID=739;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sartharion' WHERE ID=742;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sartharion' WHERE ID=743;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Malygos' WHERE ID=734;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Malygos' WHERE ID=735;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ancestro Nadox' WHERE ID=212;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Ancestro Nadox' WHERE ID=259;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Príncipe Taldaram' WHERE ID=213;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Príncipe Taldaram' WHERE ID=260;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Jedoga Buscasombras' WHERE ID=214;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Jedoga Buscasombras' WHERE ID=261;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Heraldo Volazj' WHERE ID=215;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Amanitar' WHERE ID=262;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Heraldo Volazj' WHERE ID=263;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Archavon el Vigía de Piedra' WHERE ID=772;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Archavon el Vigía de Piedra' WHERE ID=773;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Emalon el Vigía de la Tormenta' WHERE ID=774;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Emalon el Vigía de la Tormenta' WHERE ID=775;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Koralon el Vigía de las Llamas' WHERE ID=776;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Koralon el Vigía de las Llamas' WHERE ID=777;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Toravon el Vigía de Hielo' WHERE ID=885;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Toravon el Vigía de Hielo' WHERE ID=886;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lord Tuétano' WHERE ID=845;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lord Tuétano' WHERE ID=857;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lady Susurramuerte' WHERE ID=846;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lady Susurramuerte' WHERE ID=858;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Batalla de naves de guerra de Corona de Hielo' WHERE ID=847;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Batalla de naves de guerra de Corona de Hielo' WHERE ID=859;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Libramorte Colmillosauro' WHERE ID=848;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Libramorte Colmillosauro' WHERE ID=860;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Panzachancro' WHERE ID=849;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Panzachancro' WHERE ID=861;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Carapútrea' WHERE ID=850;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Carapútrea' WHERE ID=862;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Profesor Putricidio' WHERE ID=851;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Profesor Putricidio' WHERE ID=863;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Consejo de Sangre' WHERE ID=852;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Consejo de Sangre' WHERE ID=864;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Reina Lana''thel' WHERE ID=853;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Reina Lana''thel' WHERE ID=865;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Valithria Caminasueños' WHERE ID=854;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Valithria Caminasueños' WHERE ID=866;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sindragosa' WHERE ID=855;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Sindragosa' WHERE ID=867;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El Rey Exánime' WHERE ID=856;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El Rey Exánime' WHERE ID=868;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Bronjahm' WHERE ID=829;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Bronjahm' WHERE ID=830;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Devoraalmas' WHERE ID=831;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Devoraalmas' WHERE ID=832;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Bestias de Rasganorte' WHERE ID=629;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Bestias de Rasganorte' WHERE ID=630;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lord Jaraxxus' WHERE ID=633;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Bestias de Rasganorte' WHERE ID=631;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lord Jaraxxus' WHERE ID=634;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Campeones de la facción' WHERE ID=637;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Bestias de Rasganorte' WHERE ID=632;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lord Jaraxxus' WHERE ID=635;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Campeones de la facción' WHERE ID=638;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gemelas Val''kyr' WHERE ID=641;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Lord Jaraxxus' WHERE ID=636;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Campeones de la facción' WHERE ID=639;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gemelas Val''kyr' WHERE ID=642;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Anub''arak' WHERE ID=645;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Campeones de la facción' WHERE ID=640;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gemelas Val''kyr' WHERE ID=643;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Anub''arak' WHERE ID=646;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Gemelas Val''kyr' WHERE ID=644;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Anub''arak' WHERE ID=647;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Anub''arak' WHERE ID=648;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Grandes Campeones' WHERE ID=334;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Grandes Campeones' WHERE ID=336;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Campeón Argenta' WHERE ID=338;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Campeón Argenta' WHERE ID=339;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El Caballero Negro' WHERE ID=340;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='El Caballero Negro' WHERE ID=341;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Maestro de forja Gargelus' WHERE ID=833;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Maestro de forja Gargelus' WHERE ID=834;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Puagh' WHERE ID=835;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Puagh' WHERE ID=836;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Señor supremo Tyrannus' WHERE ID=837;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Señor supremo Tyrannus' WHERE ID=838;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Falric' WHERE ID=842;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Falric' WHERE ID=841;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Marwyn' WHERE ID=840;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Marwyn' WHERE ID=839;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Escapada de Arthas' WHERE ID=843;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Escapada de Arthas' WHERE ID=844;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Baltharus el Batallante' WHERE ID=889;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Baltharus el Batallante' WHERE ID=890;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Saviana Furia Ardiente' WHERE ID=891;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Saviana Furia Ardiente' WHERE ID=892;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='General Zarithrian' WHERE ID=893;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='General Zarithrian' WHERE ID=894;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Halion' WHERE ID=887;
UPDATE dbc_dungeonencounter SET Name_Lang_esMX='Halion' WHERE ID=888;
