UPDATE dbc_chartitles SET Name_Lang_esMX='Soldado %s', Name1_Lang_esMX='Soldado %s' WHERE ID=1;
UPDATE dbc_chartitles SET Name_Lang_esMX='Cabo %s', Name1_Lang_esMX='Cabo %s' WHERE ID=2;
UPDATE dbc_chartitles SET Name_Lang_esMX='Sargento %s', Name1_Lang_esMX='Sargento %s' WHERE ID=3;
UPDATE dbc_chartitles SET Name_Lang_esMX='Sargento primero %s', Name1_Lang_esMX='Sargento primera %s' WHERE ID=4;
UPDATE dbc_chartitles SET Name_Lang_esMX='Alférez %s', Name1_Lang_esMX='Alférez %s' WHERE ID=5;
UPDATE dbc_chartitles SET Name_Lang_esMX='Caballero %s', Name1_Lang_esMX='Caballero %s' WHERE ID=6;
UPDATE dbc_chartitles SET Name_Lang_esMX='Teniente caballero %s', Name1_Lang_esMX='Teniente caballero %s' WHERE ID=7;
UPDATE dbc_chartitles SET Name_Lang_esMX='Capitán caballero %s', Name1_Lang_esMX='Capitana caballero %s' WHERE ID=8;
UPDATE dbc_chartitles SET Name_Lang_esMX='Campeón caballero %s', Name1_Lang_esMX='Campeona caballero %s' WHERE ID=9;
UPDATE dbc_chartitles SET Name_Lang_esMX='Teniente coronel %s', Name1_Lang_esMX='Teniente coronel %s' WHERE ID=10;
UPDATE dbc_chartitles SET Name_Lang_esMX='Comandante %s', Name1_Lang_esMX='Comandante %s' WHERE ID=11;
UPDATE dbc_chartitles SET Name_Lang_esMX='Mariscal %s', Name1_Lang_esMX='Mariscal %s' WHERE ID=12;
UPDATE dbc_chartitles SET Name_Lang_esMX='Mariscal de campo %s', Name1_Lang_esMX='Mariscal de campo %s' WHERE ID=13;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran mariscal %s', Name1_Lang_esMX='Gran mariscal %s' WHERE ID=14;
UPDATE dbc_chartitles SET Name_Lang_esMX='Rastreador %s', Name1_Lang_esMX='Rastreadora %s' WHERE ID=15;
UPDATE dbc_chartitles SET Name_Lang_esMX='Bruto %s', Name1_Lang_esMX='Bruta %s' WHERE ID=16;
UPDATE dbc_chartitles SET Name_Lang_esMX='Capataz %s', Name1_Lang_esMX='Capataz %s' WHERE ID=17;
UPDATE dbc_chartitles SET Name_Lang_esMX='Capataz primero %s', Name1_Lang_esMX='Capataz primera %s' WHERE ID=18;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran capataz %s', Name1_Lang_esMX='Gran capataz %s' WHERE ID=19;
UPDATE dbc_chartitles SET Name_Lang_esMX='Guardia de piedra %s', Name1_Lang_esMX='Guardia de piedra %s' WHERE ID=20;
UPDATE dbc_chartitles SET Name_Lang_esMX='Guardia de sangre %s', Name1_Lang_esMX='Guardia de sangre %s' WHERE ID=21;
UPDATE dbc_chartitles SET Name_Lang_esMX='Legionario %s', Name1_Lang_esMX='Legionaria %s' WHERE ID=22;
UPDATE dbc_chartitles SET Name_Lang_esMX='Centurión %s', Name1_Lang_esMX='Centurión %s' WHERE ID=23;
UPDATE dbc_chartitles SET Name_Lang_esMX='Campeón %s', Name1_Lang_esMX='Campeona %s' WHERE ID=24;
UPDATE dbc_chartitles SET Name_Lang_esMX='General %s', Name1_Lang_esMX='General %s' WHERE ID=25;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran general %s', Name1_Lang_esMX='Gran general %s' WHERE ID=26;
UPDATE dbc_chartitles SET Name_Lang_esMX='Señor de la Guerra %s', Name1_Lang_esMX='Señora de la Guerra %s' WHERE ID=27;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran Señor de la Guerra %s', Name1_Lang_esMX='Gran Señora de la Guerra %s' WHERE ID=28;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gladiador %s', Name1_Lang_esMX='Gladiadora %s' WHERE ID=42;
UPDATE dbc_chartitles SET Name_Lang_esMX='Duelista %s', Name1_Lang_esMX='Duelista %s' WHERE ID=43;
UPDATE dbc_chartitles SET Name_Lang_esMX='Rival %s', Name1_Lang_esMX='Rival %s' WHERE ID=44;
UPDATE dbc_chartitles SET Name_Lang_esMX='Contendiente %s', Name1_Lang_esMX='Contendiente %s' WHERE ID=45;
UPDATE dbc_chartitles SET Name_Lang_esMX='Señor Escarabajo %s', Name1_Lang_esMX='Señora Escarabajo %s' WHERE ID=46;
UPDATE dbc_chartitles SET Name_Lang_esMX='Conquistador %s', Name1_Lang_esMX='Conquistadora %s' WHERE ID=47;
UPDATE dbc_chartitles SET Name_Lang_esMX='Justicar %s', Name1_Lang_esMX='Justicar %s' WHERE ID=48;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s, Campeón de los naaru', Name1_Lang_esMX='%s, Campeona de los naaru' WHERE ID=53;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gladiador despiadado %s', Name1_Lang_esMX='Gladiadora despiadada %s' WHERE ID=62;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s del Sol Devastado', Name1_Lang_esMX='%s del Sol Devastado' WHERE ID=63;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s, Mano de A''dal', Name1_Lang_esMX='%s, Mano de A''dal' WHERE ID=64;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gladiador vengativo %s', Name1_Lang_esMX='Gladiadora vengativa %s' WHERE ID=71;
UPDATE dbc_chartitles SET Name_Lang_esMX='Maestro de batalla %s', Name1_Lang_esMX='Maestra de batalla %s' WHERE ID=72;
UPDATE dbc_chartitles SET Name_Lang_esMX='Ancestro %s', Name1_Lang_esMX='Ancestro %s' WHERE ID=74;
UPDATE dbc_chartitles SET Name_Lang_esMX='Celador de las llamas %s', Name1_Lang_esMX='Celadora de las llamas %s' WHERE ID=75;
UPDATE dbc_chartitles SET Name_Lang_esMX='Vigilante de las llamas %s', Name1_Lang_esMX='Vigilante de las llamas %s' WHERE ID=76;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Exaltado', Name1_Lang_esMX='%s la Exaltada' WHERE ID=77;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Explorador', Name1_Lang_esMX='%s la Exploradora' WHERE ID=78;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Diplomático', Name1_Lang_esMX='%s la Diplomática' WHERE ID=79;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gladiador brutal %s', Name1_Lang_esMX='Gladiadora brutal %s' WHERE ID=80;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Buscador', Name1_Lang_esMX='%s la Buscadora' WHERE ID=81;
UPDATE dbc_chartitles SET Name_Lang_esMX='Maestro de arena %s', Name1_Lang_esMX='Maestra de arena %s' WHERE ID=82;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Salado', Name1_Lang_esMX='%s la Salada' WHERE ID=83;
UPDATE dbc_chartitles SET Name_Lang_esMX='Jefe de cocina %s', Name1_Lang_esMX='Jefa de cocina %s' WHERE ID=84;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Supremo', Name1_Lang_esMX='%s la Suprema' WHERE ID=85;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de las Diez Tormentas', Name1_Lang_esMX='%s de las Diez Tormentas' WHERE ID=86;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s del Sueño Esmeralda', Name1_Lang_esMX='%s del Sueño Esmeralda' WHERE ID=87;
UPDATE dbc_chartitles SET Name_Lang_esMX='Profeta %s', Name1_Lang_esMX='Profeta %s' WHERE ID=89;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Maléfico', Name1_Lang_esMX='%s la Maléfica' WHERE ID=90;
UPDATE dbc_chartitles SET Name_Lang_esMX='Acechador %s', Name1_Lang_esMX='Acechadora %s' WHERE ID=91;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de los Espada de Ébano', Name1_Lang_esMX='%s de los Espada de Ébano' WHERE ID=92;
UPDATE dbc_chartitles SET Name_Lang_esMX='Archimago %s', Name1_Lang_esMX='Archimaga %s' WHERE ID=93;
UPDATE dbc_chartitles SET Name_Lang_esMX='Belisario %s', Name1_Lang_esMX='Belisaria %s' WHERE ID=94;
UPDATE dbc_chartitles SET Name_Lang_esMX='Asesino %s', Name1_Lang_esMX='Asesina %s' WHERE ID=95;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran maestro alquimista %s', Name1_Lang_esMX='Gran maestra alquimista %s' WHERE ID=96;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran maestro herrero %s', Name1_Lang_esMX='Gran maestra herrera %s' WHERE ID=97;
UPDATE dbc_chartitles SET Name_Lang_esMX='Chef de hierro %s', Name1_Lang_esMX='Chef de hierro %s' WHERE ID=98;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran maestro encantador %s', Name1_Lang_esMX='Gran maestra encantadora %s' WHERE ID=99;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran maestro ingerniero %s', Name1_Lang_esMX='Gran maestra ingerniera %s' WHERE ID=100;
UPDATE dbc_chartitles SET Name_Lang_esMX='Doctor %s', Name1_Lang_esMX='Doctora %s' WHERE ID=101;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran maestro pescador %s', Name1_Lang_esMX='Gran maestra pescadora %s' WHERE ID=102;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran maestro herborista %s', Name1_Lang_esMX='Gran maestra herborista %s' WHERE ID=103;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran maestro escriba %s', Name1_Lang_esMX='Gran maestra escriba %s' WHERE ID=104;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran maestro joyero %s', Name1_Lang_esMX='Gran maestra joyera %s' WHERE ID=105;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran maestro peletero %s', Name1_Lang_esMX='Gran maestra peletera %s' WHERE ID=106;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran maestro minero %s', Name1_Lang_esMX='Gran maestra minera %s' WHERE ID=107;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran maestro desollador %s', Name1_Lang_esMX='Gran maestra desolladora %s' WHERE ID=108;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran maestro sastre %s', Name1_Lang_esMX='Gran maestra sastre %s' WHERE ID=109;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de Quel''Thalas', Name1_Lang_esMX='%s de Quel''Thalas' WHERE ID=110;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de Argus', Name1_Lang_esMX='%s de Argus' WHERE ID=111;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de Khaz Modan', Name1_Lang_esMX='%s de Khaz Modan' WHERE ID=112;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de Gnomeregan', Name1_Lang_esMX='%s de Gnomeregan' WHERE ID=113;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s Corazón de León', Name1_Lang_esMX='%s Corazón de León' WHERE ID=114;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s, Campeón de Elune', Name1_Lang_esMX='%s, Campeona de Elune' WHERE ID=115;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s, Héroe de Orgrimmar', Name1_Lang_esMX='%s, Heroína de Orgrimmar' WHERE ID=116;
UPDATE dbc_chartitles SET Name_Lang_esMX='Correllanuras %s', Name1_Lang_esMX='Correllanuras %s' WHERE ID=117;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de los Lanza Negra', Name1_Lang_esMX='%s de los Lanza Negra' WHERE ID=118;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Renegado', Name1_Lang_esMX='%s la Renegada' WHERE ID=119;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Buscador de Magia', Name1_Lang_esMX='%s la Buscadora de Magia' WHERE ID=120;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s, Vencedor del Crepúsculo', Name1_Lang_esMX='%s, Vencedora del Crepúsculo' WHERE ID=121;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s, Conquistador de Naxxramas', Name1_Lang_esMX='%s, Conquistadora de Naxxramas' WHERE ID=122;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s, Héroe de Rasganorte', Name1_Lang_esMX='%s, Heroína de Rasganorte' WHERE ID=123;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Santificado', Name1_Lang_esMX='%s la Santificada' WHERE ID=124;
UPDATE dbc_chartitles SET Name_Lang_esMX='Maestro cultural %s', Name1_Lang_esMX='Maestra cultural %s' WHERE ID=125;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de la Alianza', Name1_Lang_esMX='%s de la Alianza' WHERE ID=126;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de la Horda', Name1_Lang_esMX='%s de la Horda' WHERE ID=127;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el ganador impecable', Name1_Lang_esMX='%s la ganadora impecable' WHERE ID=128;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s, Campeón de los baldíos helados', Name1_Lang_esMX='%s, Campeona de los baldíos helados' WHERE ID=129;
UPDATE dbc_chartitles SET Name_Lang_esMX='Embajador %s', Name1_Lang_esMX='Embajadora %s' WHERE ID=130;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Campeón Argenta', Name1_Lang_esMX='%s la Campeona Argenta' WHERE ID=131;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s, Guardián de Cenarius', Name1_Lang_esMX='%s, Guardiana de Cenarius' WHERE ID=132;
UPDATE dbc_chartitles SET Name_Lang_esMX='Maestro cervecero %s', Name1_Lang_esMX='Maestra cervecera %s' WHERE ID=133;
UPDATE dbc_chartitles SET Name_Lang_esMX='Juerguista %s', Name1_Lang_esMX='Juerguista %s' WHERE ID=134;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Loco de amor', Name1_Lang_esMX='%s la Loca de amor' WHERE ID=135;
UPDATE dbc_chartitles SET Name_Lang_esMX='Matrona %s', Name1_Lang_esMX='Matrona %s' WHERE ID=137;
UPDATE dbc_chartitles SET Name_Lang_esMX='Patrón %s', Name1_Lang_esMX='Patrón %s' WHERE ID=138;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s, Destripador obsidiana', Name1_Lang_esMX='%s, Destripadora obsidiana' WHERE ID=139;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s del Anochecer', Name1_Lang_esMX='%s del Anochecer' WHERE ID=140;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Inmortal', Name1_Lang_esMX='%s la Inmortal' WHERE ID=141;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Indestructible', Name1_Lang_esMX='%s la Indestructible' WHERE ID=142;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s Jenkins', Name1_Lang_esMX='%s Jenkins' WHERE ID=143;
UPDATE dbc_chartitles SET Name_Lang_esMX='Almirante Velasangre %s', Name1_Lang_esMX='Almirante Velasangre %s' WHERE ID=144;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Demente', Name1_Lang_esMX='%s la Demente' WHERE ID=145;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de El Exodar', Name1_Lang_esMX='%s de El Exodar' WHERE ID=146;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de Darnassus', Name1_Lang_esMX='%s de Darnassus' WHERE ID=147;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de Forjaz', Name1_Lang_esMX='%s de Forjaz' WHERE ID=148;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de Ventormenta', Name1_Lang_esMX='%s de Ventormenta' WHERE ID=149;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de Orgrimmar', Name1_Lang_esMX='%s de Orgrimmar' WHERE ID=150;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de Sen''jin', Name1_Lang_esMX='%s de Sen''jin' WHERE ID=151;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de Lunargenta', Name1_Lang_esMX='%s de Lunargenta' WHERE ID=152;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de Cima del Trueno', Name1_Lang_esMX='%s de Cima del Trueno' WHERE ID=153;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s de Entrañas', Name1_Lang_esMX='%s de Entrañas' WHERE ID=154;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Noble', Name1_Lang_esMX='%s la Noble' WHERE ID=155;
UPDATE dbc_chartitles SET Name_Lang_esMX='Cruzado %s', Name1_Lang_esMX='Cruzada %s' WHERE ID=156;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gladiador mortal %s', Name1_Lang_esMX='Gladiadora mortal %s' WHERE ID=157;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s, Ejecutor de la muerte', Name1_Lang_esMX='%s, Ejecutora de la muerte' WHERE ID=158;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Defensor celestial', Name1_Lang_esMX='%s la Defensora celestial' WHERE ID=159;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s, Conquistador de Ulduar', Name1_Lang_esMX='%s, Conquistadora de Ulduar' WHERE ID=160;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s, Campeón de Ulduar', Name1_Lang_esMX='%s, Campeona de Ulduar' WHERE ID=161;
UPDATE dbc_chartitles SET Name_Lang_esMX='Vencedor %s', Name1_Lang_esMX='Vencedora %s' WHERE ID=163;
UPDATE dbc_chartitles SET Name_Lang_esMX='Llamaestrellas %s', Name1_Lang_esMX='Llamaestrellas %s' WHERE ID=164;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Caminante astral', Name1_Lang_esMX='%s la Caminante astral' WHERE ID=165;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s, Heraldo de los titanes', Name1_Lang_esMX='%s, Heraldo de los titanes' WHERE ID=166;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gladiador furioso %s', Name1_Lang_esMX='Gladiadora furiosa %s' WHERE ID=167;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Peregrino', Name1_Lang_esMX='%s la Peregrina' WHERE ID=168;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gladiador incansable %s', Name1_Lang_esMX='Gladiadora incansable %s' WHERE ID=169;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gran cruzado %s', Name1_Lang_esMX='Gran cruzada %s' WHERE ID=170;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Defensor Argenta', Name1_Lang_esMX='%s la Defensora Argenta' WHERE ID=171;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Paciente', Name1_Lang_esMX='%s la Paciente' WHERE ID=172;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s, la Luz del Alba', Name1_Lang_esMX='%s, la Luz del Alba' WHERE ID=173;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s, la Perdición del Rey caído', Name1_Lang_esMX='%s, la Perdición del Rey caído' WHERE ID=174;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s el Matarreyes', Name1_Lang_esMX='%s la Matarreyes' WHERE ID=175;
UPDATE dbc_chartitles SET Name_Lang_esMX='%s del Veredicto Cinéreo', Name1_Lang_esMX='%s del Veredicto Cinéreo' WHERE ID=176;
UPDATE dbc_chartitles SET Name_Lang_esMX='Gladiador colérico %s', Name1_Lang_esMX='Gladiadora colérica %s' WHERE ID=177;
