UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='esto es una prueba' WHERE ID=83;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=84;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=85;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Este pequeño obsequio no te dará respuestas, pero puede resultarte divertido.' WHERE ID=86;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Hola, otra vez. Soy Gubber Blump.

Espero que te esté yendo bien. También espero que sigas pescando. Me encanta la pesca. La familia Blump es conocida por dedicarse a la pesca. Aquí tienes un cebo para poder pescar un poco mejor. Me encanta usarlo cuando voy de pesca. Buena suerte y gracias, nuevamente, por ayudarme a pescar esos meros.

¡Sigue pescando!

Gubber Blump' WHERE ID=87;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=88;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=89;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=90;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Este pequeño obsequio no te dará respuestas, pero puede resultarte divertido.' WHERE ID=91;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=92;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='$gEstimado:Estimada; $N,$B$BHe revisado la pila de documentos que me trajiste y descifré los artículos adjuntos para ti. Elegí cuidadosamente solo aquello que consideré útil. Fue especialmente complicado ir hasta un buzón sin que me vieran, pero los meses que llevo ocultándome en el desierto me han convertido en $gun verdadero experto:una verdadera experta; en esta práctica.$B$BEspero que los disfrutes,$B$BOrtell' WHERE ID=93;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='¡Saludos, $N!$B$BMe estoy volviendo bastante bueno a la hora de colarme en el Fuerte Cenarion para utilizar el buzón. Nuevamente, he adjuntado algunos objetos que podrían serte interesantes. ¡Ojalá que su contenido te resulte útil!$B$BOrtell' WHERE ID=94;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=95;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=96;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=97;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='"Requirió mucho tiempo traducir el texto del gran jefe. Lo que encontré me dejó consternado. El Gran Jefe Nevada estaba extremadamente paranoico en estos últimos días, hasta el punto de volverse adicto a una sustancia que él llamaba ""aguardiente."" Él creía que todas las criaturas eran sus enemigas. Bien, dejaré que lo leas tú $gmismo:misma;. De hecho, he incluido en esta carta una traducción de sus palabras. Si necesitas ayuda, no dudes en volver a visitarme."' WHERE ID=98;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='¡Gracias por renovar tu afiliación en la Hermandad de Ingeniería Mecánica, $gasociado:asociada;! Nos complace enormemente tenerte como miembro activo. Acepta este obsequio como muestra de nuestro aprecio, por las maravillosas contribuciones que continúas realizando al mundo de la ingeniería gnómica.' WHERE ID=99;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='¡Gracias por renovar tu afiliación en la Hermandad de Ingeniería Mecánica, $gasociado:asociada;! Nos complace enormemente tenerte como miembro activo. Acepta este obsequio como muestra de nuestro aprecio, por las maravillosas contribuciones que continúas realizando al mundo de la ingeniería gnómica.' WHERE ID=100;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='$gAmigo:Amiga;, a mi brazo, cansado de luchar en las Tierras de la Peste, nunca le faltarán fuerzas para escribir una misiva a $gun héroe:una heroína; como tú. Me complace saber que la ayuda que nos prestaste sigue dando sus frutos.

Si pasas por las Tierras de la Peste del Oeste próximamente, ve a El Baluarte. ¡Tu curtida mano será más que bienvenida para compartir una buena caldera! Saludos desde la oscuridad:
Sumo Ejecutor Derrington' WHERE ID=101;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='¡Je, je, je, hola, $N! ¡Espero que pases un excelente Festival de Invierno!$B$BFuiste muy amable al ayudarme a encontrar las golosinas que tanto me apetecían, que quería enviarte un pequeño detalle adicional. Es una muestra de los deliciosos manjares de los Pastos de Bosquehumeante. Si aún no los has conseguido, ¡no olvides hacerlo antes de que acabe la temporada!$B$B¡Felices fiestas!... $BEl Gran Padre Invierno' WHERE ID=102;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='¡Gracias por renovar tu afiliación en la Corporación de Ingeniería Experimental Goblin, $gasociado:asociada;! Nos complace enormemente tenerte como miembro activo. Acepta este obsequio como muestra de nuestro aprecio, por las maravillosas contribuciones que continúas realizando al mundo de la ingeniería goblin.' WHERE ID=103;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='¡Gracias por renovar tu afiliación en la Corporación de Ingeniería Experimental Goblin, $gasociado:asociada;! Nos complace enormemente tenerte como miembro activo. Acepta este obsequio como muestra de nuestro aprecio, por las maravillosas contribuciones que continúas realizando al mundo de la ingeniería goblin.' WHERE ID=104;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='<UNUSED>', Body_Lang_esMX='¡Has recibido este mensaje porque estás incluido en una lista de interesados en recibir Viagra! Más texto.' WHERE ID=105;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='¡Esos conejos han regresado! ¡NO! Eh, no te molestes en regresar…' WHERE ID=106;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Saludos, a mi brazo, cansado de luchar en las Tierras de la Peste, nunca le faltarán fuerzas para escribir una misiva a $gun héroe:una heroína; como tú. Me complace enterarme de que la ayuda que nos prestaste sigue dando sus frutos.

Si pasas por las Tierras de la Peste del Oeste próximamente, ve al campamento. ¡Tu curtida mano será más que bienvenida para compartir una buena caldera! ¡Por Ventormenta!
Comandante Ashlam Puñovalor' WHERE ID=107;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='¡Je, je, hola otra vez, $N!$B$BAunque mis amigos de los Pastos de Bosquehumeante y yo hemos estado muy ocupados esta temporada, quería enviarte algo especial. Te alegrará saber que logramos liberar a Sacks de las montañas Alterac. Por cierto, te manda un afectuoso saludo.$B$BAl hacerlo, desarrollamos un novedoso dispositivo que creo te encantará. Para activarlo, tendrás que usar una bola de nieve, no obstante, ¡creo que te divertirás mucho!$B$BEl Gran Padre Invierno' WHERE ID=108;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='¡Saludos, $gamigo:amiga;!$B$BHe pensado que debería agradecerte una vez más la ayuda prestada en nuestra lucha contra Hakkar. Espero volver a verte pronto pues ante nosotros se presenta el reto de derrotar al Dios de la Sangre y... ¡tu ausencia no pasa desapercibida!$B$BHe incluido una muestra de honor como agradecimiento por todo lo que has hecho por nosotros. ¡Juntos pondremos fin a Hakkar para siempre!$B$BVinchaxa, siervo de Zanza.' WHERE ID=109;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='$gEstimado:Estimada; $N,$B$BLa información que me diste antes ha resultado ser de cuantiosa valía. Ya he ordenado que se modifiquen nuestros planes de guerra debido a la importancia que ahora atribuimos a la presencia del Martillo Crepuscular.$B$BAcepta este objeto como una pequeña muestra de nuestra gratitud. Espero que podamos seguir contando contigo, como valiente $galiado:aliada; que eres, en la batalla que libramos en Silithus.$B$BUn cordial saludo,$B$BComandante Mar''alith' WHERE ID=110;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Te deseo lo mejor, $gamigo mío:amiga mía;. Espero que tu lucha a favor de la Horda resulte victoriosa. Ciertamente, espero que llegue el día en que todos consideren tu legado tan importante y tan valioso como el de Grom Grito Infernal.$B$BNo he olvidado la amabilidad que has demostrado no solo conmigo, sino al honrar la memoria de Grom durante el Festival de la Cosecha. Te he enviado algo que creo que te va a gustar. Úsalo correctamente.$B$B¡Por la Horda!$BJavnir' WHERE ID=111;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='¡Saludos, joven druida!

Estoy muy $gorgulloso:orgullosa; del esfuerzo que has demostrado durante tu instrucción hasta el momento. Debes sentirte $ghonrado:honrada; por haberte unido a la Zarpa. Recibirás más lecciones similares. La siguiente estará disponible una vez que hayas alcanzado el nivel 14. Cuando llegue ese momento, búscame en el Enclave Cenarion de Darnassus.

Mathrengyl Garroso' WHERE ID=112;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Te deseo lo mejor, $gamigo mío:amiga mía;. Espero que tu lucha a favor de la Alianza te resulte satisfactoria. Ciertamente, espero que llegue el día en que todos consideren tu legado tan importante y tan valioso como el de Uther el Iluminado.$B$BNo he olvidado la amabilidad que has demostrado no solo conmigo, sino al honrar la memoria de Uther durante el Festival de la Cosecha. Te he enviado algo que creo que te va a gustar. Úsalo correctamente.$B$BPor el martillo de Barbabronce,$BWagner' WHERE ID=113;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='¡Saludos, joven druida!

Te he enviado esta nota para recordarte que debes venir a verme cada vez que cambies de rango. Como druida tienes mucho que aprender al servicio de Cenarius y me complace enormemente poder ayudarte en el camino. Pronto estarás $gpreparado:preparada; para conocer tu forma acuática. Búscame cuando alcances el nivel 16 y te instruiré en la senda del conocimiento.

Turak Tótem de Runa' WHERE ID=114;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='¡Saludos, joven druida!

Te he enviado esta nota para recordarte que debes venir a verme cada vez que cambies de rango. Como druida tienes mucho que aprender al servicio de Cenarius y me complace enormemente poder ayudarte en el camino. Pronto estarás $gpreparado:preparada; para conocer tu forma acuática. Búscame cuando alcances el nivel 16 y te instruiré en la senda del conocimiento.

Mathrengyl Garroso' WHERE ID=115;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='¡Saludos, joven druida!

Estoy muy $gorgulloso:orgullosa; del esfuerzo que has demostrado durante tu instrucción hasta el momento. Debes sentirte $ghonrado:honrada; por haberte unido a la Zarpa. Recibirás más lecciones similares. La siguiente estará disponible una vez que hayas alcanzado el nivel 14. En ese momento, cuando estés $glisto:lista;, búscame en el Alto de los Ancestros de Cima del Trueno.

Turak Tótem de Runa' WHERE ID=116;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='¡Je, je, hola otra vez, $N!$B$BAunque mis amigos de los Pastos de Bosquehumeante y yo hemos estado muy ocupados esta temporada, quería enviarte algo especial. Te alegrará saber que logramos liberar a Sacks de las montañas Alterac. Por cierto, te manda un afectuoso saludo.$B$BAl hacerlo, desarrollamos un novedoso dispositivo que creo te encantará. Para activarlo, tendrás que usar una bola de nieve, no obstante, ¡creo que te divertirás mucho!$B$BEl Gran Padre Invierno' WHERE ID=117;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='¡Je, je, je, hola, $N! ¡Espero que pases un excelente Festival de Invierno!$B$BFuiste muy amable al ayudarme a encontrar las golosinas que tanto me apetecían, que quería enviarte un pequeño detalle adicional. Es una muestra de los deliciosos manjares de los Pastos de Bosquehumeante. Si aún no los has conseguido, ¡no olvides hacerlo antes de que acabe la temporada!$B$B¡Felices fiestas!... $BEl Gran Padre Invierno' WHERE ID=118;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Hola, otra vez. Solo quería dejarte una nota, comunicándote que las cosas aquí en el Bastión Plumaluna van muy bien. He logrado fabricar numerosos artículos de cuero ¡en gran medida, gracias a tu ayuda!$B$BMe han sobrado algunos retazos de cuero, así que he pensado en enviarte algo adicional por toda la ayuda que me has prestado. Si vuelves a pasar por el fuerte, ¡no dudes en venir a vernos!$B$BTu $gamigo:amiga;,$BPratt' WHERE ID=119;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Buenas, otra vez. Solo quería comunicarte que aquí en el Campamento Mojache las cosas van bien. He logrado fabricar muchos artículos de cuero, ¡en buena medida gracias a tu ayuda!$B$BMe han sobrado algunos retazos de cuero, así que he pensado enviarte algo más en señal de agradecimiento. Si vuelves a pasar por el campamento, ¡no dudes en visitarme!$B$BQue la paz sea contigo y con tus ancestros,$BJangdor' WHERE ID=120;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Este pequeño obsequio no te dará respuestas, pero puede resultarte divertido.' WHERE ID=121;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='$N:$B$BSolo quería volver a darte las gracias por rescatar a Metzen de sus secuestradores. Créeme cuando te digo que has conquistado para siempre $gun amigo:una amiga; en los Pastos de Bosquehumeante.$B$BY a propósito de... El maestro chef Graccu ha estado elaborando una nueva receta y he pensado que tal vez te apetecería probar uno de sus exquisitos platos. ¡Que pases un excelente Festival de Invierno!$B$BQue tu arca esté siempre a rebosar,$BKaymard Cobrellizco' WHERE ID=122;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='$GCampeón:Campeona;:$B$BEl Vuelo Azul cree que el destino te depara más de lo que yo hubiera imaginado.$B$BEn contra de lo que muchos puedan pensar, nuestro mundo necesita héroes. En los momentos difíciles, cuando te enfrentes al añublo de Kalimdor, recuerda tus viajes épicos, las pruebas y las tribulaciones sufridas por un viejo gnomo y deja que esos recuerdos refuercen tu espíritu.$B$BHumildemente,$B$BNarain Sabelotodo$B$BP.D. Siento los gastos de reparación.' WHERE ID=123;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=124;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=125;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=126;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=127;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=128;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=129;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=130;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=131;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Este pequeño obsequio no te dará respuestas, pero puede resultarte divertido.' WHERE ID=132;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=133;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=134;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=135;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=136;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Este pequeño obsequio no te dará respuestas, pero puede resultarte divertido.' WHERE ID=137;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Este pequeño obsequio no te dará respuestas, pero puede resultarte divertido.' WHERE ID=138;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Este pequeño obsequio no te dará respuestas, pero puede resultarte divertido.' WHERE ID=139;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Este pequeño obsequio no te dará respuestas, pero puede resultarte divertido.' WHERE ID=140;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Este pequeño obsequio no te dará respuestas, pero puede resultarte divertido.' WHERE ID=141;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Este pequeño obsequio no te dará respuestas, pero puede resultarte divertido.' WHERE ID=142;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=143;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=144;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=145;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=146;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=147;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=148;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=149;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=150;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=151;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=152;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Este pequeño obsequio no te dará respuestas, pero puede resultarte divertido.' WHERE ID=153;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Este pequeño obsequio no te dará respuestas, pero puede resultarte divertido.' WHERE ID=154;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Este pequeño obsequio no te dará respuestas, pero puede resultarte divertido.' WHERE ID=155;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Este pequeño obsequio no te dará respuestas, pero puede resultarte divertido.' WHERE ID=156;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Este pequeño obsequio no te dará respuestas, pero puede resultarte divertido.' WHERE ID=157;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=158;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=159;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Este pequeño obsequio no te dará respuestas, pero puede resultarte divertido.' WHERE ID=160;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='$N:$B$BSolo quería volver a darte las gracias por rescatar a Metzen de sus secuestradores. Créeme cuando te digo que has conquistado para siempre $gun amigo:una amiga; en los Pastos de Bosquehumeante.$B$BY a propósito de... El maestro chef Graccu ha estado elaborando una nueva receta y he pensado que tal vez te apetecería probar uno de sus exquisitos platos. ¡Que pases un excelente Festival de Invierno!$B$BQue tu arca esté siempre a rebosar,$BWulmort Calderilla' WHERE ID=161;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Correo nuevo', Body_Lang_esMX='Necesito arreglar el orden de las pestañas' WHERE ID=162;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii', Body_Lang_esMX='YOh!' WHERE ID=165;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii', Body_Lang_esMX='ab' WHERE ID=166;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='<UNUSED>', Body_Lang_esMX='¡Has recibido este mensaje porque estás incluido en una lista de interesados en recibir Viagra! Más texto.' WHERE ID=167;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=168;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Prueba de correo masivo', Body_Lang_esMX='Este es un texto del sistema de transmisión de emergencia.' WHERE ID=169;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='asdjaksld dsf as  -', Body_Lang_esMX='Hola. ¿De qué estás hablando? ¿No está fallando esto?' WHERE ID=170;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡El Alba Argenta necesita tu ayuda!', Body_Lang_esMX='$N$B$BAbre rápidamente esta carta y sigue sus indicaciones atentamente. ¡El Alba Argenta necesita tu ayuda!' WHERE ID=171;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Informe de investigación', Body_Lang_esMX='$n,$B$BHe recibido este informe acerca del documento que rescataste de la Plaga. Aun cuando no pulses el botón, puede resultarte interesante.$B$BNuevamente, gracias por tu servicio.$BEl Guardián de los Pergaminos$BEl Alba Argenta' WHERE ID=172;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Informe de investigación', Body_Lang_esMX='$n,$B$BHe recibido este informe acerca del documento que rescataste de la Plaga. Aun cuando no pulses el botón, puede resultarte interesante.$B$BNuevamente, gracias por tu servicio.$BEl Guardián de los Pergaminos$BEl Alba Argenta' WHERE ID=173;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Informe de investigación', Body_Lang_esMX='$n,$B$BHe recibido este informe acerca del documento que rescataste de la Plaga. Aun cuando no pulses el botón, puede resultarte interesante.$B$BNuevamente, gracias por tu servicio.$BEl Guardián de los Pergaminos$BEl Alba Argenta' WHERE ID=174;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Informe de investigación', Body_Lang_esMX='$n,$B$BHe recibido este informe acerca del documento que rescataste de la Plaga. Aun cuando no pulses el botón, puede resultarte interesante.$B$BNuevamente, gracias por tu servicio.$BEl Guardián de los Pergaminos$BEl Alba Argenta' WHERE ID=175;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Informe de investigación', Body_Lang_esMX='$n,$B$BHe recibido este informe acerca del documento que rescataste de la Plaga. Aun cuando no pulses el botón, puede resultarte interesante.$B$BNuevamente, gracias por tu servicio.$BEl Guardián de los Pergaminos$BEl Alba Argenta' WHERE ID=176;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Informe de investigación', Body_Lang_esMX='$n,$B$BHe recibido este informe acerca del documento que rescataste de la Plaga. Aun cuando no pulses el botón, puede resultarte interesante.$B$BNuevamente, gracias por tu servicio.$BEl Guardián de los Pergaminos$BEl Alba Argenta' WHERE ID=177;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Un obsequio para ti', Body_Lang_esMX='¡Gracias por jugar a World of Warcraft!' WHERE ID=178;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Enhorabuena, $gganador:ganadora; de la lotería', Body_Lang_esMX='¡Aquí tienes tu recompensa, fiambre! Y no te lo gastes todo en una casa de subastas…' WHERE ID=179;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Carta urgente adjunta!', Body_Lang_esMX='Abrir inmediatamente.' WHERE ID=180;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Encantamiento encontrado', Body_Lang_esMX='Tras un análisis periódico del vacío, hemos encontrado los siguientes componentes. Que tengas un buen día y… por favor, ten más cuidado cuando trates con el poder Arcano.' WHERE ID=181;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Enhorabuena!', Body_Lang_esMX='¡Has ganado un draco abisal! Uno acorazado, ¡así se hace!' WHERE ID=182;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Una carta de Shattrath', Body_Lang_esMX='Has recibido una carta de Khadgar' WHERE ID=183;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Gracias!', Body_Lang_esMX='$N,$B$BGracias por el tiempo que pasamos juntos durante la Semana de los Niños. El Clarividente Nobundo ha pedido a la matrona del orfanato que me deje estudiar con él en El Exodar$B$BGracias por llevarme a todos esos sitios y a ver a mi hermano Jheel. Lo echo de menos casi tanto como a ti. ¡Y el Círculo de la Observancia, El portal oscuro y las Cavernas del Tiempo fueron geniales!$B$BEstoy segura de que estás cuidando bien de mi mascota. ¡Dile que también le echo de menos!$B$BBesos,$B$BDornaa.' WHERE ID=184;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Gracias!', Body_Lang_esMX='$N,$B$BGracias por el rato que pasamos durante la Semana de los Niños. Lady Liadrin, la líder de los Caballeros de Sangre ha pedido mi custodia para entrenarme en la Ciudad de Lunargenta.$B$BSolo quería darte las gracias por llevarme a ver a Hch''uu, y por enseñarme El portal Oscuro, el Trono de los Elementos y las Cavernas del Tiempo. ¡Me gusta mucho mi dragón de juguete!$B$BEstoy segura de que estás cuidando bien de él. ¡Dile que también le echo de menos!$B$BCon cariño,$B$BSalandria' WHERE ID=185;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Moneda de la fortuna recuperada', Body_Lang_esMX='Hemos recuperado una moneda de la fortuna perdida en El Vacío Abisal y hemos visto que era tuya. ¡Disfrútala!' WHERE ID=186;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Feliz Festival del Invierno!', Body_Lang_esMX='¡Prepara, comparte y disfruta de la sidra de manzana con especias caliente con tus amigos durante las Fiestas!' WHERE ID=187;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Feliz Festival del Invierno!', Body_Lang_esMX='¡Cose, comparte y disfruta de una magnífica ropa de invierno verde con tus amigos durante las vacaciones!' WHERE ID=188;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Draco abisal perdido', Body_Lang_esMX='Hace poco recogí este pequeño dragón mientras examinaba el Vacío. Parece ser tuyo, pero no encontró sitio entre tus pertenencias cuando te lo dieron.$b$b¡Disfruta de tu nueva mascota peleona! ¡Está deseando instalarse en su nuevo hogar!' WHERE ID=189;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Cierre de banco de hermandad', Body_Lang_esMX='Este capital se ha recuperado de la cámara del banco de tu hermandad al cerrarlo.' WHERE ID=190;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Feliz Festival del Invierno!', Body_Lang_esMX='¡Cose, comparte y disfruta de una magnífica ropa de invierno roja con tus amigos durante las vacaciones!' WHERE ID=191;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Feliz Festival del Invierno!', Body_Lang_esMX='¡Crea, comparte y disfruta de unas botas de invierno calentitas y cómodas con tus amigos durante las Fiestas!' WHERE ID=192;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Una carta del archimago Malin', Body_Lang_esMX='$gQuerido:Querida; $N,$B$BEl mensajero personal de la Comandante Aceroazur me dio la carta de mi hija. Me dijo que la encontraste tú.$B$BSolo quería agradecértelo. Sé que todos vosotros, almas valientes dispuestas a luchar en Rasganorte, estáis pasando un momento difícil.$B$BNo dudes que vengaré a Emmy. ¡El Vuelo Azul sufrirá por lo que le hicieron a mi pequeña!$B$BCon todo mi respeto y gratitud,$B$BArchimago Malin' WHERE ID=193;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Una carta de Deino', Body_Lang_esMX='$gQuerido:Querida; $N,$B$BEl mensajero personal del señor supremo Agmar me dio la carta de mi hermano. Me dijo que la encontraste tú.$B$BSolo quiero agradecértelo. Sé que todos vosotros, almas valientes dispuestas a luchar en Rasganorte, estáis pasando un momento difícil.$B$BNo dudes que vengaré a Ta''zinni. ¡El Vuelo Azul sufrirá por lo que le hicieron a mi hermano pequeño!$B$BCon todo mi respeto y gratitud,$B$BDeino' WHERE ID=194;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='El tabardo de competidor', Body_Lang_esMX='Has luchado con valentía en un campo de batalla y has impresionado a los Espíritus de Competición… ¡Bien hecho! Como recompensa, has recibido esta marca de favor. Lúcela con orgullo.' WHERE ID=195;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Un medallón de oro', Body_Lang_esMX='Has honrado a los Espíritus de Competición con tu fervor frente al enemigo. ¡Enhorabuena! Con este medallón de oro, se sentirán orgullosos de verte a su lado.' WHERE ID=196;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Nuevo año, nueva cerveza!', Body_Lang_esMX='¡Saludos, $n!$b$b   Esperamos que el nuevo año te esté tratando bien. Si no es así, visita a nuestros vendedores para probar la última cerveza disponible. Seguro que sacará el animal que llevas dentro.$b$b   ¡Disfruta de las muestras y del nuevo año!$b$b- Club de la Cerveza del Mes' WHERE ID=197;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='No hay quien haga caer una buena cerveza', Body_Lang_esMX='$n,$b$b   A veces es imposible hacer caer una buena cerveza.   Esta nueva birra es buena, ¿pero podrás controlarla?$b$b   Recuerda, si te gustan estas muestras, podrás obtener más de nuestros vendedores.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=198;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Los últimos cotilleos de la birra', Body_Lang_esMX='Hola, $n$b$b   A veces apetece una cerveza con fragancia. Y no hay nada mejor que el aroma de la miel.   A  todas las criaturas, grandes y pequeñas les entusiasma su olor.  Cuando pruebes esta cerveza, estarás de acuerdo con nosotros.$b$b   Recuerda que si te gusta, podrás comprar más a nuestros vendedores.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=199;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Porque lo habéis exigido', Body_Lang_esMX='Saludos, $n$b$b   Oímos que algunos de nuestros miembros querían una cerveza más ligera y espumosa.  Hemos intentado explicarles que no somos el "Club del Champagne del Mes."  Por desgracia, no han cambiado de idea.  Con suerte la cerveza de este mes satisfará a aquellos que prefieren una birra más ligera y espumosa.$b$b   No lo olvides, si te ha gustado esta muestra, podrás adquirir más de nuestros vendedores.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=200;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Celebremos la primavera!', Body_Lang_esMX='Hola, $n$b$b   La primavera se nota en el aire y este mes la notarás en el paladar también.  Prueba nuestra última cerveza: la cerveza de primavera.  Esta refrescante cerveza es perfecta para esta época del año.$b$b  Disfruta la muestra y recuerda que puedes visitar a nuestros vendedores para comprar más.$b$b- Club de la Cerveza del Mes' WHERE ID=201;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Esta cerveza está de moda', Body_Lang_esMX='$n,$b$b   ¡Este mes te presentamos una cerveza de lo más caliente!   Directa de la Montaña Roca Negra llega la cerveza rubia de Roca Negra.$b$b   Recuerda que si te ha gustado esta pequeña muestra, podrás comprar esta cerveza a nuestros vendedores.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=202;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Una cerveza peligrosa', Body_Lang_esMX='Hola, $n$b$b   Este mes te ofrecemos una cerveza emocionante.   Los miembros del Club de la Cerveza del Mes se han adentrado en las selvas de Tuercespina y han vuelvo con esta misteriosa birra.$b$b   No olvides que si te ha gustado esta muestra, podrás comprar más a nuestros vendedores.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=203;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Una cerveza que no olvidarás', Body_Lang_esMX='$gEstimado:Estimada; $n$b$b   A veces hay que explorar para encontrar la mejor cerveza.   La de este mes ha viajado mucho para llegar hasta ti. Esperamos que haya merecido la pena.$b$b   Recuerda que si te gusta, podrás comprar más a nuestros vendedores.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=204;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Una cerveza que te gustará', Body_Lang_esMX='Hola, $n$b$b   Nuestra cerveza de este mes no te dejará indiferente; te encantará o la odiarás.  Lo dejamos en tus manos.$b$b   Si te gusta, ya sabes que puedes adquirir más de nuestros comerciantes.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=205;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Un asunto otoñal', Body_Lang_esMX='Hola, $n$b$b   Nuestra cerveza del mes es una celebración del otoño.  Creemos que esta cerveza ha capturado la esencia de esta estación.  Pero queremos que forjes tu propia opinión, así que pruébala.$b$b   Si te gusta, podrás comprar más a nuestros vendedores.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=206;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Una cerveza que hasta tus amigos disfrutarán', Body_Lang_esMX='¡Saludos, $n!$b$b   Esperamos que el nuevo año te esté tratando bien. Si no es el caso, visita a nuestros vendedores para probar lo último: la cerveza amarga de Bartlett.  Su sabor es incomparable, pero te avisamos que no es para bebedores con el estómago sensible. $b$b   ¡Disfruta de las muestras y compártelas con tus amigos!$b$b- Club de la Cerveza del Mes' WHERE ID=207;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Una historia que te dejará helado', Body_Lang_esMX='$n,$b$b   El verano pasado algunos de nuestros miembros se enfrentaron al poder del Señor de la Escarcha.  Pero lo más importante es que descubrieron un gran alijo de cerveza.   Hemos logrado hacernos con gran cantidad de esta cerveza poco habitual y hemos querido enviarte una muestra.$b$b   Si te gusta esta refrescante muestra, podrás adquirir más de nuestros vendedores.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=208;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Te damos la bienvenida al Club de la Cerveza del Mes!', Body_Lang_esMX='$n,$B$B ¡Te damos la bienvenida al Club de la Cerveza del Mes!  Este club se dedica a acercarte algunas de las mejores cervezas de todos los reinos.$B$B   Cada mes, se te enviará directamente por correo una nueva cerveza. Si te gusta esa cerveza y quieres más, dirígete a la taberna Roca de Fuego de Forjaz y habla con los miembros del Club de la Cerveza del Mes que encontrarás allí.$B$B   Una vez más, te damos la bienvenida al club, $n.$b$b$b Club de la Cerveza del Mes' WHERE ID=209;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Te damos la bienvenida al Club de la Cerveza del Mes!', Body_Lang_esMX='$n,$B$B ¡Te damos la bienvenida al Club de la Cerveza del Mes!  Te proporcionaremos algunas de las mejores cervezas de todos los reinos.$B$B   Cada mes te enviaremos por correo una nueva. Si te gusta y quieres más, dirígete a la Cabaña de Brezo en el Valle de los Espíritus de Orgrimmar y habla con los miembros del Club de la Cerveza del Mes.$B$B   Una vez más, te damos la bienvenida al club, $n.$b$b$b Club de la Cerveza del Mes' WHERE ID=210;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Enhorabuena!', Body_Lang_esMX='De parte del Círculo de Lucha Bonvapor, te damos la enhorabuena por tu éxito en esta temporada de arenas.$B$BComo reconocimiento a tu habilidad y ferocidad, te otorgamos este draco abisal vengativo. Esperamos que te sea de utilidad.' WHERE ID=211;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Un nuevo año pide una cerveza nueva!', Body_Lang_esMX='¡Saludos, $n!$b$b   Esperamos que el nuevo año te esté tratando bien. Si no es así, visita a nuestros vendedores para probar la última cerveza disponible. Seguro que sacará el animal que llevas dentro.$b$b   ¡Disfruta de las muestras y del nuevo año!$b$b- Club de la Cerveza del Mes' WHERE ID=212;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Es difícil hacer caer una buena cerveza', Body_Lang_esMX='$n,$b$b   A veces es imposible hacer caer una buena cerveza.   Esta nueva birra es buena, ¿pero podrás controlarla?$b$b   Recuerda, si te gustan estas muestras, podrás obtener más de nuestros vendedores.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=213;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Lo más moderno', Body_Lang_esMX='Hola, $n$b$b   A veces apetece una cerveza con fragancia. Y no hay nada mejor que el aroma de la miel.   A  todas las criaturas, grandes y pequeñas les entusiasma su olor.  Cuando pruebes esta cerveza, estarás de acuerdo con nosotros.$b$b   Recuerda que si te gusta, podrás comprar más a nuestros vendedores.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=214;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Porque lo habéis pedido', Body_Lang_esMX='Saludos, $n$b$b   Oímos que algunos de nuestros miembros querían una cerveza más ligera y espumosa.  Hemos intentado explicarles que no somos el "Club del Champagne del Mes."  Por desgracia, no han cambiado de idea.  Con suerte la cerveza de este mes satisfará a aquellos que prefieren una birra más ligera y espumosa.$b$b   No lo olvides, si te ha gustado esta muestra, podrás adquirir más de nuestros vendedores.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=215;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Llegó la hora de celebrar la primavera!', Body_Lang_esMX='Hola, $n$b$b   La primavera se nota en el aire y este mes la notarás en el paladar también.  Prueba nuestra última cerveza: la cerveza de primavera.  Esta refrescante cerveza es perfecta para esta época del año.$b$b  Disfruta la muestra y recuerda que puedes visitar a nuestros vendedores para comprar más.$b$b- Club de la Cerveza del Mes' WHERE ID=216;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Una cerveza caliente', Body_Lang_esMX='$n,$b$b   ¡Este mes te presentamos una cerveza de lo más caliente!   Directa de la Montaña Roca Negra llega la cerveza rubia de Roca Negra.$b$b   Recuerda que si te ha gustado esta pequeña muestra, podrás comprar esta cerveza a nuestros vendedores.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=217;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Una cerveza misteriosa', Body_Lang_esMX='Hola, $n$b$b   Este mes te ofrecemos una cerveza emocionante.   Los miembros del Club de la Cerveza del Mes se han adentrado en las selvas de Tuercespina y han vuelvo con esta misteriosa birra.$b$b   No olvides que si te ha gustado esta muestra, podrás comprar más a nuestros vendedores.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=218;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¿Te acordaste de tu cerveza?', Body_Lang_esMX='$gEstimado:Estimada; $n$b$b   A veces hay que explorar para encontrar la mejor cerveza.   La de este mes ha viajado mucho para llegar hasta ti. Esperamos que haya merecido la pena.$b$b   Recuerda que si te gusta, podrás comprar más a nuestros vendedores.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=219;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Una cerveza que te encantará', Body_Lang_esMX='Hola, $n$b$b   Nuestra cerveza de este mes no te dejará indiferente; te encantará o la odiarás.  Lo dejamos en tus manos.$b$b   Si te gusta, ya sabes que puedes adquirir más de nuestros comerciantes.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=220;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Una cerveza muy otoñal', Body_Lang_esMX='Hola, $n$b$b   Nuestra cerveza del mes es una celebración del otoño.  Creemos que esta cerveza ha capturado la esencia de esta estación.  Pero queremos que forjes tu propia opinión, así que pruébala.$b$b   Si te gusta, podrás comprar más a nuestros vendedores.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=221;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Diversión para ti y tus amigos', Body_Lang_esMX='¡Saludos, $n!$b$b   Esperamos que el nuevo año te esté tratando bien. Si no es el caso, visita a nuestros vendedores para probar lo último: la cerveza amarga de Bartlett.  Su sabor es incomparable, pero te avisamos que no es para bebedores con el estómago sensible. $b$b   ¡Disfruta de las muestras y compártelas con tus amigos!$b$b- Club de la Cerveza del Mes' WHERE ID=222;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Una cerveza refrescante', Body_Lang_esMX='$n,$b$b   El verano pasado algunos de nuestros miembros se enfrentaron al poder del Señor de la Escarcha.  Pero lo más importante es que descubrieron un gran alijo de cerveza.   Hemos logrado hacernos con gran cantidad de esta cerveza poco habitual y hemos querido enviarte una muestra.$b$b   Si te gusta esta refrescante muestra, podrás adquirir más de nuestros vendedores.$b$b¡Disfrútala!$b$b- Club de la Cerveza del Mes' WHERE ID=223;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Aprende a montar en el Bosque de Elwynn', Body_Lang_esMX='$gEstimado:Estimada; $n,$B$BEspero que estés bien. Escribo para informarte de mis servicios como instructor de equitación. Si quieres aprender a montar, visítame en el Aserradero de la Vega del Este, en el camino que parte hacia el este de Ventormenta. Mis honorarios son modestos, solo cuatro monedas de oro.$B$BSi después quieres comprar una montura, la criadora de caballos Katie Cazadora ofrece varios corceles nobles, a solo una moneda de oro cada uno.$B$BSuyo, Randal Predatio' WHERE ID=224;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Aprende a montar en Darnassus', Body_Lang_esMX='Que la suerte esté de tu lado, $n.$B$BEscribo para informarte de mis servicios como instructor de equitación. Si quieres aprender a montar, solo tienes que visitarme en el Enclave Cenarion en Darnassus. Mis honorarios son modestos, solo cuatro monedas de oro.$B$BSi después de aprender a montar quieres adquirir una montura, la cuidadora de sables Lelanai ofrece varias bestias nobles, por solo una moneda de oro cada una.$B$BCon mis mejores deseos, Jartsam' WHERE ID=225;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Aprende a montar en Dun Morogh', Body_Lang_esMX='Hola, joven. ¿Quieres aprender a montar? Entonces visítame en la Granja de Semperámbar, que encontrarás en la carretera que sale hacia el este de Forjaz.$B$BMis honorarios son cuatro monedas de oro y si quieres un carnero de montar, Veron Semperámbar ofrece varios corceles nobles por solo una moneda de oro cada uno.$B$BUltham' WHERE ID=226;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Aprende a montar en El Exodar', Body_Lang_esMX='Saludos, $n.$B$BEspero que estés bien. Escribo para informarte de mis servicios como instructor de equitación. Si quieres aprender a montar, solo tienes que visitarme en la entrada de El Exodar. Mis honorarios son modestos, solo cuatro monedas de oro.$B$BSi después de aprender a montar quieres comprar un elekk, Torallius el Controlador de la Manada ofrece varios corceles nobles, a solo una moneda de oro cada uno.$B$BMarcha en paz, Aalun' WHERE ID=227;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Aprende a montar en Dun Morogh', Body_Lang_esMX='¡Saludos, $n! ¿Te gustaría moverte con más rapidez? Entonces ven a visitarnos a Milli y a mí al Almacén de Brasacerada, justo al noreste de Kharanos.$B$BMis honorarios por instruirte en el arte de la equitación son de cuatro monedas de oro. Y si quieres tu propio mecazancudo, Milli los monta por solo una moneda de oro.$B$BEspero verte pronto, Binjy' WHERE ID=228;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Aprende a montar en Mulgore', Body_Lang_esMX='Saludos, valiente $n.$B$BEscribo para informarte de mis servicios como instructor de equitación. Si quieres aprender a montar, solo tienes que visitarme en el Poblado Pezuña de Sangre. Mis honorarios son modestos, solo cuatro monedas de oro.$B$BSi después de aprender a montar quieres adquirir un kodo, Harb Garrapezuña ofrece varias bestias nobles, por solo una moneda de oro cada una.$B$BBuenos viajes, Kar' WHERE ID=229;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Aprende a montar en Durotar', Body_Lang_esMX='¿Quieres montar, $n? Entonces ven a verme al Poblado Senjin. Te enseñaré a montar por solo cuatro monedas de oro.$B$BQuizá después quieras un raptor de montar. Habla con Zjolnir. Te venderá uno por una moneda de oro o menos.$B$B¡Aléjate del vudú!$B$BXar''Ti' WHERE ID=230;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Aprende a montar en Orgrimmar', Body_Lang_esMX='Fuerza y honor, $n.$B$BSoy el instructor de equitación de Orgrimmar. Si quieres aprender a montar, solo tienes que visitarme en el Valle del Honor. Mis honorarios son modestos, solo cuatro monedas de oro.$B$BSi quieres comprar un lobo de montar después, Ogunaro Correlobo tiene varias bestias nobles, cada una por solo una moneda de oro.$B$BKildar' WHERE ID=231;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Aprende a montar en el Bosque Canción Eterna', Body_Lang_esMX='$gEstimado:Estimada; $n,$B$BEspero que estés bien. Escribo para informarte de mis servicios como instructor de equitación. Si quieres aprender a montar, visítame en la Caballería de Thuron, al sureste de la Puerta del Pastor, saliendo de la Ciudad de Lunargenta. Mis honorarios son modestos, solo cuatro monedas de oro.$B$BSi después quieres comprar una montura, la criadora de halcones Winaestra ofrece varios corceles nobles, a solo una moneda de oro cada uno.$B$BViajes seguros, Perascamin' WHERE ID=232;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Aprende a montar en los Claros de Tirisfal', Body_Lang_esMX='$gBuen:Buena; $gseñor:señora; $n,$B$BEscribo para informarte de mis servicios como instructora de equitación. Si quieres aprender a montar, solo tienes que visitarme en Rémol. Mis honorarios son modestos, solo cuatro monedas de oro.$B$BSi después de aprender a montar quieres comprar una montura, Zachariah Post ha reunido varios caballos adaptados a tus necesidades y los vende a solo una moneda de oro por cabeza.$B$BAtentamente, Velma Warnam' WHERE ID=233;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Vigila tu espalda', Body_Lang_esMX='Krenna ha oído que hemos liberado a uno de los tramperos y está hecha una fiera.$b$bSerá mejor que te ocultes un tiempo o ambos terminaremos enfrentándonos a osos en el foso.$b$b-Gorgonna' WHERE ID=234;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Una zhebra presta', Body_Lang_esMX='PARA: $n$B$BDE: Compañía de Provisiones de Monturas Exóticas Nesingwary SL$B$BCONTENIDO DEL CAJÓN:$B$B- una (1) zhebra$B$B- una (1) silla de montar zhebras$B$B- cuatro (4) cascos de zhebra$B$B- dos (2) cascos de zhebra de repuesto$B$B- NO TAPAR LOS AGUJEROS DE VENTILACIÓN -' WHERE ID=235;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡En el nombre de la Luz!', Body_Lang_esMX='Para: Alta general Abbendis
Nuevo Avalon, Tierras Escarlata|n' WHERE ID=236;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=237;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=238;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=239;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=240;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=241;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=242;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=243;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=244;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=245;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=246;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=247;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=248;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=249;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=250;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=251;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=252;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=253;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=254;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=255;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=256;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=257;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=258;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=259;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Gracias por visitarme, $N. Me complace saber que no se nos ha olvidado.' WHERE ID=260;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='', Body_Lang_esMX='Agradezco tu visita de hoy. Toma esto como obsequio para tu Festival Lunar.' WHERE ID=261;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Enhorabuena!', Body_Lang_esMX='De parte del Círculo de Lucha Bonvapor, te damos la enhorabuena por tu éxito en esta temporada de arenas.$B$BComo reconocimiento a tu habilidad y ferocidad, te otorgamos este draco abisal brutal. Esperamos que te sea de utilidad.' WHERE ID=262;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Tened piedad de los inocentes!', Body_Lang_esMX='Sal ahí y propaga tu amor mohicano.' WHERE ID=263;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Toma manacapón!', Body_Lang_esMX='Hola, $N:
 ¿Te acuerdas de cuando te transformaron en oveja en Dalaran? ¡Pues fui yo, Minigob Manacapón! Solo quería escribirte para que supieras quién lo hizo. Y además, ya que te lo tomaste con tanta deportividad, te envío una de mis varitas. Ahora puedes "manacaponear" a tus amigos. Cuando lo hagas, diles que te envió "Minigob Manacapón".

Minigob Manacapón' WHERE ID=264;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='El Torneo Argenta', Body_Lang_esMX='La Cruzada Argenta te invita a probar tus habilidades en combate honorable contra otros héroes de Azeroth en el Torneo Argenta. Los campeones de las mayores ciudades del mundo se han reunido en los Campos del Torneo Argenta al noreste de Corona de Hielo para enfrentarse a todos los que los desafíen.' WHERE ID=265;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Enhorabuena!', Body_Lang_esMX='En nombre del Círculo de Lucha Bonvapor, te damos la enhorabuena por tu éxito en esta temporada de arenas.$B$BComo reconocimiento a tu habilidad y ferocidad, te otorgamos esta vermis de escarcha de Gladiador mortal. Esperamos que te sea de utilidad.' WHERE ID=266;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Enhorabuena!', Body_Lang_esMX='En nombre del Círculo de Lucha Bonvapor, te damos la enhorabuena por tu éxito en esta temporada de arenas.$B$BComo reconocimiento a tu habilidad y ferocidad, te otorgamos esta vermis de escarcha de Gladiador furioso. Esperamos que te sea de utilidad.' WHERE ID=267;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='BOLETÍN DE ACCIÓN URGENTE', Body_Lang_esMX='






Los huérfanos de Rasganorte te necesitan. Por menos del valor de un vaso de Kungaloosh puedes apadrinar a un desafortunado huérfano, como el pequeño Lito o el pequeño Kekek.$B$BSolo tienes que ponerte en contacto con la supervisora de huérfanos Aria en Dalaran. Puedes marcar la diferencia en la vida de un joven Oráculo o wolvar. ¡Actúa ya!' WHERE ID=268;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='De Lito', Body_Lang_esMX='$gQuerido:Querida; $N,$B$BTe echamos de menos. A todos les gusta la historia de cómo conocimos al Magno y quieren conocer a uno. No se creen algunas de nuestras historias. Dicen que nos inventamos la de la reina y los santuarios de los dragones. Están celosos.$B$BLa vida en el orfanato es mejor ahora. La supervisora nos lleva al parque y a veces nos dan juguetes nuevos, pero aún nos sentimos solos. Queremos visitarte. A lo mejor puedes llevarnos a más sitios. ¿Te apetece?$B$BTu amigo,$BLito' WHERE ID=269;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='De Kekek', Body_Lang_esMX='$gEstimado:Estimada; $N,$B$BKekek no sabe escribir, pero ha aprendido para tu carta. La señorita de los huérfanos encontrar Verdes colinas que mencionar Hemet. Yo haberlo leído y aprender a ser gran cazador como tú y como Hemet Nesingwary. Kekek creer que son muchas palabras para ser buen cazador.$B$BKekek querer probar lo que leer en libro sobre Verdes colinas. ¿Tú dejar a Kekek visitar para poder cazar juntos? Kekek prometer no robar presas.$B$BTu amigo, $BKekek' WHERE ID=270;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Como reconocimiento', Body_Lang_esMX='Tus habilidades y considerables talentos en el ámbito de la joyería no han pasado desapercibidos. Es importante que continuemos la tradición con el orgullo y la atención al detalle que has demostrado.

Como reconocimiento de dicho esfuerzo, he incluido una libranza especial. Devuélvemela para obtener unas cuantas recompensas bien merecidas.

Timothy Jones' WHERE ID=271;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Oficial jinete en el Bosque Canción Eterna', Body_Lang_esMX='Amable $n,$B$BTe escribo para recordarte mis servicios como instructor de equitación. Si deseas aprender oficial jinete para monturas más veloces, visítame en la Caballería de Thuron, al sudeste de La Puerta del Pastor, a la salida de la Ciudad de Lunargenta. Mis modestos honorarios son 50 monedas de oro.$B$BSi deseas comprar una montura presta, la criadora de halcones zancudos Winaestra ofrece varios corceles nobles, a solo 10 monedas de oro cada uno.$B$BBuen viaje. Perascamin' WHERE ID=272;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Oficial jinete en El Exodar', Body_Lang_esMX='Saludos $n,$B$BTe escribo de nuevo para recordarte mis servicios como instructor de equitación. Si deseas aprender la habilidad oficial jinete para monturas más veloces, solo tienes que visitarme en la entrada de El Exodar. Mis modestos honorarios son cincuenta monedas de oro.$B$BSi deseas comprar un elekk presto, Torallius el Controlador de la Manada ofrece varios corceles nobles, a solo diez monedas de oro cada uno.$B$BVe en paz, Aalun' WHERE ID=273;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Oficial jinete en Dun Morogh', Body_Lang_esMX='¡Hola $gchico:chica;! ¿Quieres aprender la habilidad oficial jinete para monturas más veloces? Entonces ven a visitarme a la Granja de Semperámbar, en la carretera que sale de Forjaz por el este.$B$BMi tarifa es de solo cincuenta monedas de oro, y si quieres un carnero presto que montar, Veron Semperámbar ofrece varios corceles nobles, a solo diez monedas de oro cada uno.$B$B- Ultham' WHERE ID=274;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Oficial jinete en Dun Morogh', Body_Lang_esMX='¡Saludos, $n! ¿Quieres moverte aún MÁS RÁPIDO? Entonces ven a visitarnos a Milli y a mí al Almacén de Brasacerada, justo al noreste de Kharanos.$B$BMi tarifa de instructor de oficial jinete es solo cincuenta monedas de oro y si quieres tu propio mecazancudo presto, Milli los construye por solo diez monedas de oro cada uno.$B$BEsperamos verte pronto, Binjy' WHERE ID=275;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Oficial jinete en el Bosque de Elwynn', Body_Lang_esMX='$gBuen señor: Buena dama; $n: $B$BTe escribo de nuevo para recordarte mis servicios como instructor de equitación. Si deseas aprender oficial jinete, visítame en el Aserradero de la Vega del Este, en la carretera este de Ventormenta. Mis honorarios son cincuenta monedas de oro.$B$BSi deseas comprar una montura presta, la criadora de caballos Katie Cazadora ofrece varios corceles nobles, a solo diez monedas de oro cada uno.$B$BTuyo, Randal Predatio' WHERE ID=276;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Oficial jinete en Darnassus', Body_Lang_esMX='Que la suerte te acompañe, $n.$B$BTe escribo de nuevo para recordarte mis servicios como instructor de equitación. Si deseas aprender la habilidad oficial jinete para monturas más veloces, solo tienes que visitarme en el Enclave Cenarion, en Darnassus. Mis modestos honorarios son cincuenta monedas de oro.$B$BSi deseas comprar una montura presta, la cuidadora de sables Lelanai ofrece varios corceles nobles, a solo diez monedas de oro cada uno.$B$BTe desea lo mejor, Jartsam' WHERE ID=277;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Oficial jinete en Orgrimmar', Body_Lang_esMX='Fuerza y honor, $n.$B$BSi deseas aprender la habilidad oficial jinete para monturas más veloces, solo tienes que visitarme en el Valle del Honor. Mis modestos honorarios son cincuenta monedas de oro.$B$BSi deseas comprar un lobo presto, la perrera de Ogunaro Correlobo alberga varias bestias, a solo diez monedas de oro cada una.$B$B- Kildar' WHERE ID=278;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Oficial jinete en Mulgore', Body_Lang_esMX='Saludos, valiente $n.$B$BQuiero recordarte mis servicios como instructor de equitación. Si deseas aprender la habilidad oficial jinete para monturas más veloces, solo tienes que visitarme en el Poblado Pezuña de Sangre. Mis modestos honorarios son cincuenta monedas de oro.$B$BSi deseas comprar un kodo presto, Harb Garrapezuña ofrece varias bestias nobles, a solo diez monedas de oro cada uno.$B$BBuen viaje, Kar' WHERE ID=279;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Oficial jinete en Durotar', Body_Lang_esMX='¿Quieres cabalgar aún MÁS RÁPIDO, $n? Entonces ven a verme al Poblado Sen''jin. Te enseñaré la habilidad oficial jinete por solo cincuenta monedas de oro.$B$B¿Quizá entonces quieras un raptor presto para cabalgar aún MÁS DEPRISA? Habla con Zjolnir. Él te venderá uno por diez monedas de oro, quizá menos.$B$B¡Aléjate del vudú!$B$BXar''Ti' WHERE ID=280;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Oficial jinete en Claros de Tirisfal', Body_Lang_esMX='$gBuen señor:Buena dama; $n, $B$BTe escribo de nuevo para recordarte mis servicios como instructor de equitación. Si deseas aprender la habilidad oficial jinete para monturas más veloces, solo tienes que visitarme en Rémol. Mis modestos honorarios son cincuenta monedas de oro.$B$BSi deseas comprar una montura presta, Zachariah Post ha reunido unos cuantos caballos adecuados a nuestras necesidades y los vende por solo diez monedas de oro cada uno.$B$BTuya, Velma Warnam' WHERE ID=281;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Aprende a volar en Thrallmar', Body_Lang_esMX='Hola, $n.$B$BSi quieres aprender Experto jinete para monturas voladoras, visítame en Thrallmar, en la Península del Fuego Infernal. Mis honorarios son 250 monedas de oro.$B$BSi, cuando aprendas, quieres comprar una montura, Bana Ferocrín las vende por tan solo 50 monedas de oro.$B$B- Jahubo' WHERE ID=282;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Aprende a volar en el Bastión del Honor', Body_Lang_esMX='¡Hola, $gchico:chica;! ¿Quieres aprender Experto jinete para monturas voladoras? Entonces ven a visitarme al Bastión del Honor, en la Península del Fuego Infernal.$B$BMis honorarios son 250 monedas de oro y si quieres comprar una montura voladora, mi encantadora esposa, Grunda, cría y vende grifos por tan solo 50 monedas de oro.$B$B- Hargen' WHERE ID=283;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Artesano jinete en la Fortaleza Denuedo', Body_Lang_esMX='¡Hola! ¿Quieres aprender artesano jinete para monturas voladoras más veloces? Ven a la Fortaleza Denuedo, en la Tundra Boreal.$B$BLa tarifa es de cinco mil monedas de oro. Por mil más podrás aprender Vuelo en clima frío y así volar en Rasganorte.$B$BSi quieres una montura voladora presta, Durgan Truenopico las vende por solo cien monedas de oro cada una.$B$B- Maigra$B$BP.D. Si no puedes llegar a Rasganorte, visita a Hargen Alabronce en el Bastión del Honor, en la Península del Fuego Infernal.' WHERE ID=284;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Artesano jinete en el Bastión Grito de Guerra', Body_Lang_esMX='¡Hola, $N! ¿Quieres aprender artesano jinete para monturas voladoras más veloces? Ven al Bastión Grito de Guerra, en la Tundra Boreal.$B$BLa tarifa es de cinco mil monedas de oro. Por mil más podrás aprender Vuelo en clima frío y así volar en Rasganorte.$B$BTohfo Pezuñacielo vende monturas voladoras prestas por tan solo cien monedas de oro cada una.$B$B- Sabamba$B$BP.D. Si no puedes llegar a Rasganorte, visita al jinete del viento Jahubo en Thrallmar, en la Península del Fuego Infernal.' WHERE ID=285;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Enhorabuena!', Body_Lang_esMX='De parte del Círculo de Lucha Bonvapor, te damos la enhorabuena por tu éxito en esta temporada de arenas.$B$BComo reconocimiento a tu habilidad y ferocidad, te otorgamos esta vermis de escarcha de Gladiador incansable. Esperamos que te sea de utilidad.' WHERE ID=286;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Enhorabuena!', Body_Lang_esMX='De parte del Círculo de Lucha Bonvapor, te damos la enhorabuena por tu éxito en esta temporada de arenas.$B$BComo reconocimiento a tu habilidad y ferocidad, te otorgamos esta vermis de escarcha de Gladiador colérico. Esperamos que te sea de utilidad.' WHERE ID=287;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Operación: Gnomeregan', Body_Lang_esMX='Estimado señor/señora,

Orgulloso miembro de la Alianza, el deber le convoca en Forjaz apresuradamente para cumplir con la voluntad del Manitas Mayor Mekkatorque, Rey de los gnomos.*

El fin de nuestro exilio se acerca. ¡Operación: Gnomeregan va a comenzar!**

* El Robojurista 2000 me informa de que no poseo ninguna autoridad legal o de otro tipo (sobre los gnomos o similares) pero aún así, ¡debes reconocer que suena genial!

** En serio, por favor, ayúdanos si puedes. ¡Muchas gracias!' WHERE ID=288;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Caída de Zalazane', Body_Lang_esMX='He''manos y he''manas,
¡En nombre de los anceh''tros, Vol''jin, hijo de Sen''jin, os convoca! Durante mucho tiempo, el traidó Zalazane ha usao su magia negra pa profaná nueh''tros mue''htos, pa haceh''nos creé que e''tá derrotao y mantené a los Lanza Negra fuera de las I''las del Eco.
Ya es hora d''ocuparse de él pa siempre. Ayudaré a Vol''jin a reuní fue''zas fuera del Poblado Sen''jin. ¡Uníos a mí y ayudadnos a administrá la justicia tan esperada a este renegao!
Al servicio de Vol''jin,
Vanira' WHERE ID=289;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='¡Enhorabuena, Vencedor!', Body_Lang_esMX='De parte del Círculo de Lucha Bonvapor, te damos la enhorabuena por tu éxito en el último Torneo de Arenas.$B$BComo reconocimiento a tu habilidad y ferocidad, te otorgamos el título de Vencedor. Llévalo con orgullo.' WHERE ID=290;
UPDATE dbc_mailtemplate SET Subject_Lang_esMX='Cohete de paseo X-53', Body_Lang_esMX='PARA: $N$b$bDE: Taller de cohetes B.U.M.$b$bCONTENIDO DEL CAJÓN:$b$b- un (1) cohete abisal X-53, modelo paseo$b$b- una (1) llave de ignición de cohete$b$b- un (1) asiento eyectable trasero$b$b- cero (0) paracaídas' WHERE ID=291;
