UPDATE dbc_totemcategory SET Name_Lang_esMX='Cuchillo para desollar' WHERE ID=1;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Tótem de tierra' WHERE ID=2;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Tótem de aire' WHERE ID=3;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Tótem de fuego' WHERE ID=4;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Tótem de agua' WHERE ID=5;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Vara rúnica de cobre' WHERE ID=6;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Vara rúnica de plata' WHERE ID=7;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Vara rúnica de oro' WHERE ID=8;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Vara rúnica de veraplata' WHERE ID=9;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Vara rúnica de arcanita' WHERE ID=10;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Pico de minería' WHERE ID=11;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Piedra filosofal' WHERE ID=12;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Martillo de herrero' WHERE ID=13;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Llave de tuerca arcoluz' WHERE ID=14;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Microajustador giromático' WHERE ID=15;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Tótem maestro' WHERE ID=21;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Vara rúnica de hierro vil' WHERE ID=41;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Vara rúnica de adamantita' WHERE ID=62;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Vara rúnica de eternio' WHERE ID=63;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Pluma hueca' WHERE ID=81;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Vara rúnica de azurita' WHERE ID=101;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Juego de caligrafía de virtuoso' WHERE ID=121;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Tambores' WHERE ID=141;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Navaja gnómica' WHERE ID=161;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Martillo de herrero' WHERE ID=162;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Pico de minería' WHERE ID=165;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Cuchillo para desollar' WHERE ID=166;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Martillo pico' WHERE ID=167;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Hacha pico afilada' WHERE ID=168;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Sílex y yesca' WHERE ID=169;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Vara rúnica de cobalto (DO NOT USE)' WHERE ID=189;
UPDATE dbc_totemcategory SET Name_Lang_esMX='Vara rúnica de titanio' WHERE ID=190;
