UPDATE dbc_questsort SET SortName_Lang_esMX='Épica' WHERE ID=1;
UPDATE dbc_questsort SET SortName_Lang_esMX='REUSE - old wailing caverns' WHERE ID=21;
UPDATE dbc_questsort SET SortName_Lang_esMX='Estacional' WHERE ID=22;
UPDATE dbc_questsort SET SortName_Lang_esMX='REUSE - old undercity one' WHERE ID=23;
UPDATE dbc_questsort SET SortName_Lang_esMX='Herboristería' WHERE ID=24;
UPDATE dbc_questsort SET SortName_Lang_esMX='Campos de batalla' WHERE ID=25;
UPDATE dbc_questsort SET SortName_Lang_esMX='Festividad de los Muertos' WHERE ID=41;
UPDATE dbc_questsort SET SortName_Lang_esMX='Brujo' WHERE ID=61;
UPDATE dbc_questsort SET SortName_Lang_esMX='Guerrero' WHERE ID=81;
UPDATE dbc_questsort SET SortName_Lang_esMX='Chamán' WHERE ID=82;
UPDATE dbc_questsort SET SortName_Lang_esMX='Pesca' WHERE ID=101;
UPDATE dbc_questsort SET SortName_Lang_esMX='Herrería' WHERE ID=121;
UPDATE dbc_questsort SET SortName_Lang_esMX='Paladín' WHERE ID=141;
UPDATE dbc_questsort SET SortName_Lang_esMX='Mago' WHERE ID=161;
UPDATE dbc_questsort SET SortName_Lang_esMX='Pícaro' WHERE ID=162;
UPDATE dbc_questsort SET SortName_Lang_esMX='Alquimia' WHERE ID=181;
UPDATE dbc_questsort SET SortName_Lang_esMX='Peletería' WHERE ID=182;
UPDATE dbc_questsort SET SortName_Lang_esMX='Ingeniería' WHERE ID=201;
UPDATE dbc_questsort SET SortName_Lang_esMX='Mapa de tesoro' WHERE ID=221;
UPDATE dbc_questsort SET SortName_Lang_esMX='Torneo' WHERE ID=241;
UPDATE dbc_questsort SET SortName_Lang_esMX='Cazador' WHERE ID=261;
UPDATE dbc_questsort SET SortName_Lang_esMX='Sacerdote' WHERE ID=262;
UPDATE dbc_questsort SET SortName_Lang_esMX='Druida' WHERE ID=263;
UPDATE dbc_questsort SET SortName_Lang_esMX='Sastrería' WHERE ID=264;
UPDATE dbc_questsort SET SortName_Lang_esMX='Especial' WHERE ID=284;
UPDATE dbc_questsort SET SortName_Lang_esMX='Cocina' WHERE ID=304;
UPDATE dbc_questsort SET SortName_Lang_esMX='Primeros auxilios' WHERE ID=324;
UPDATE dbc_questsort SET SortName_Lang_esMX='Legendaria' WHERE ID=344;
UPDATE dbc_questsort SET SortName_Lang_esMX='Feria de la Luna Negra' WHERE ID=364;
UPDATE dbc_questsort SET SortName_Lang_esMX='Guerra de Ahn''Qiraj' WHERE ID=365;
UPDATE dbc_questsort SET SortName_Lang_esMX='Festival Lunar' WHERE ID=366;
UPDATE dbc_questsort SET SortName_Lang_esMX='Reputación' WHERE ID=367;
UPDATE dbc_questsort SET SortName_Lang_esMX='Invasión' WHERE ID=368;
UPDATE dbc_questsort SET SortName_Lang_esMX='Verano' WHERE ID=369;
UPDATE dbc_questsort SET SortName_Lang_esMX='Fiesta de la cerveza' WHERE ID=370;
UPDATE dbc_questsort SET SortName_Lang_esMX='Inscripción' WHERE ID=371;
UPDATE dbc_questsort SET SortName_Lang_esMX='Caballero de la Muerte' WHERE ID=372;
UPDATE dbc_questsort SET SortName_Lang_esMX='Joyería' WHERE ID=373;
UPDATE dbc_questsort SET SortName_Lang_esMX='Jardín Noble' WHERE ID=374;
UPDATE dbc_questsort SET SortName_Lang_esMX='Generosidad del Peregrino' WHERE ID=375;
UPDATE dbc_questsort SET SortName_Lang_esMX='Amor en el aire' WHERE ID=376;
