UPDATE dbc_itemset SET Name_Lang_esMX='El Gladiador' WHERE ID=1;
UPDATE dbc_itemset SET Name_Lang_esMX='Armas de Dal''Rend' WHERE ID=41;
UPDATE dbc_itemset SET Name_Lang_esMX='Beso de la araña' WHERE ID=65;
UPDATE dbc_itemset SET Name_Lang_esMX='El Jefe de correos' WHERE ID=81;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de cadáver' WHERE ID=121;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras necrópilas' WHERE ID=122;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío Mallasangre' WHERE ID=123;
UPDATE dbc_itemset SET Name_Lang_esMX='Guardia de hueso de muerto' WHERE ID=124;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura volcánica' WHERE ID=141;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de sudario de tormenta' WHERE ID=142;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de demosaurio' WHERE ID=143;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura Plumahierro' WHERE ID=144;
UPDATE dbc_itemset SET Name_Lang_esMX='Cuero Defias' WHERE ID=161;
UPDATE dbc_itemset SET Name_Lang_esMX='Abrazo de la víbora' WHERE ID=162;
UPDATE dbc_itemset SET Name_Lang_esMX='Cadena de la Cruzada Escarlata' WHERE ID=163;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de magister' WHERE ID=181;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas del devoto' WHERE ID=182;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras Calígine' WHERE ID=183;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura Arte Sombrío' WHERE ID=184;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras corazón salvaje' WHERE ID=185;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de acechabestias' WHERE ID=186;
UPDATE dbc_itemset SET Name_Lang_esMX='Los elementos' WHERE ID=187;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura Forjaluz' WHERE ID=188;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de valor' WHERE ID=189;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de arcanista' WHERE ID=201;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas de profecía' WHERE ID=202;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras Corazón Oscuro' WHERE ID=203;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de Destripador Nocturno' WHERE ID=204;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Cenarius' WHERE ID=205;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de acechagigantes' WHERE ID=206;
UPDATE dbc_itemset SET Name_Lang_esMX='Furia de la tierra' WHERE ID=207;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de Justiciero' WHERE ID=208;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de poderío' WHERE ID=209;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío viento abisal' WHERE ID=210;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas de trascendencia' WHERE ID=211;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de la Némesis' WHERE ID=212;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura Colmillo de Sangre' WHERE ID=213;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Tempestira' WHERE ID=214;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de acechadragón' WHERE ID=215;
UPDATE dbc_itemset SET Name_Lang_esMX='Las diez tormentas' WHERE ID=216;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de la Sentencia' WHERE ID=217;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de la cólera' WHERE ID=218;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de Thero-shan' WHERE ID=221;
UPDATE dbc_itemset SET Name_Lang_esMX='Fragmentos de los Dioses' WHERE ID=241;
UPDATE dbc_itemset SET Name_Lang_esMX='Espíritu de Eskhandar' WHERE ID=261;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Campeón' WHERE ID=281;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Teniente coronel' WHERE ID=282;
UPDATE dbc_itemset SET Name_Lang_esMX='Sacudetierra de Campeón' WHERE ID=301;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas imperiales' WHERE ID=321;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Campeón' WHERE ID=341;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Campeón' WHERE ID=342;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Teniente coronel' WHERE ID=343;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Teniente coronel' WHERE ID=344;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestuario de Campeón' WHERE ID=345;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestuario de Teniente coronel' WHERE ID=346;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas de Campeón' WHERE ID=347;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas de Teniente coronel' WHERE ID=348;
UPDATE dbc_itemset SET Name_Lang_esMX='Persecución de Campeón' WHERE ID=361;
UPDATE dbc_itemset SET Name_Lang_esMX='Persecución de Teniente coronel' WHERE ID=362;
UPDATE dbc_itemset SET Name_Lang_esMX='Santuario de Teniente coronel' WHERE ID=381;
UPDATE dbc_itemset SET Name_Lang_esMX='Santuario de Campeón' WHERE ID=382;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Señor de la Guerra' WHERE ID=383;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Mariscal de campo' WHERE ID=384;
UPDATE dbc_itemset SET Name_Lang_esMX='Sacudetierra de Señor de la Guerra' WHERE ID=386;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Señor de la Guerra' WHERE ID=387;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Mariscal de campo' WHERE ID=388;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Mariscal de campo' WHERE ID=389;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Señor de la Guerra' WHERE ID=390;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestuario de Señor de la Guerra' WHERE ID=391;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestuario de Mariscal de campo' WHERE ID=392;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas de Señor de la Guerra' WHERE ID=393;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas de Mariscal de campo' WHERE ID=394;
UPDATE dbc_itemset SET Name_Lang_esMX='Persecución de Mariscal de campo' WHERE ID=395;
UPDATE dbc_itemset SET Name_Lang_esMX='Persecución de Señor de la Guerra' WHERE ID=396;
UPDATE dbc_itemset SET Name_Lang_esMX='Santuario del Mariscal de campo' WHERE ID=397;
UPDATE dbc_itemset SET Name_Lang_esMX='Santuario de Señor de la Guerra' WHERE ID=398;
UPDATE dbc_itemset SET Name_Lang_esMX='Égida de Teniente coronel' WHERE ID=401;
UPDATE dbc_itemset SET Name_Lang_esMX='Égida de Mariscal de campo' WHERE ID=402;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de vid de sangre' WHERE ID=421;
UPDATE dbc_itemset SET Name_Lang_esMX='Piel de murciélago primigenia' WHERE ID=441;
UPDATE dbc_itemset SET Name_Lang_esMX='Arnés de tigre de sangre' WHERE ID=442;
UPDATE dbc_itemset SET Name_Lang_esMX='Abrazo de alma de sangre' WHERE ID=443;
UPDATE dbc_itemset SET Name_Lang_esMX='El Almanegra' WHERE ID=444;
UPDATE dbc_itemset SET Name_Lang_esMX='Las hojas gemelas de Hakkari' WHERE ID=461;
UPDATE dbc_itemset SET Name_Lang_esMX='Concentración de Zanzil' WHERE ID=462;
UPDATE dbc_itemset SET Name_Lang_esMX='Bendición primigenia' WHERE ID=463;
UPDATE dbc_itemset SET Name_Lang_esMX='Resolución de Señor Supremo' WHERE ID=464;
UPDATE dbc_itemset SET Name_Lang_esMX='Rezo del Primigenio' WHERE ID=465;
UPDATE dbc_itemset SET Name_Lang_esMX='Infusión de mojo sublime' WHERE ID=466;
UPDATE dbc_itemset SET Name_Lang_esMX='Resolución del montañés' WHERE ID=467;
UPDATE dbc_itemset SET Name_Lang_esMX='Decisión del montañés' WHERE ID=468;
UPDATE dbc_itemset SET Name_Lang_esMX='Determinación del montañés' WHERE ID=469;
UPDATE dbc_itemset SET Name_Lang_esMX='Entereza del montañés' WHERE ID=470;
UPDATE dbc_itemset SET Name_Lang_esMX='Propósito del montañés' WHERE ID=471;
UPDATE dbc_itemset SET Name_Lang_esMX='Voluntad del montañés' WHERE ID=472;
UPDATE dbc_itemset SET Name_Lang_esMX='Intención del montañés' WHERE ID=473;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla del vindicador' WHERE ID=474;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura del librepensador' WHERE ID=475;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Augur' WHERE ID=476;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de depredador' WHERE ID=477;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo del Loquillo' WHERE ID=478;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de Haruspex' WHERE ID=479;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de confesor' WHERE ID=480;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestuario demoníaco' WHERE ID=481;
UPDATE dbc_itemset SET Name_Lang_esMX='Ropajes del Ilusionista' WHERE ID=482;
UPDATE dbc_itemset SET Name_Lang_esMX='Determinación del Envilecido' WHERE ID=483;
UPDATE dbc_itemset SET Name_Lang_esMX='Entereza del Envilecido' WHERE ID=484;
UPDATE dbc_itemset SET Name_Lang_esMX='Intención del Envilecido' WHERE ID=485;
UPDATE dbc_itemset SET Name_Lang_esMX='Propósito del Rapiñador' WHERE ID=486;
UPDATE dbc_itemset SET Name_Lang_esMX='Resolución del Envilecido' WHERE ID=487;
UPDATE dbc_itemset SET Name_Lang_esMX='Voluntad del Rapiñador' WHERE ID=488;
UPDATE dbc_itemset SET Name_Lang_esMX='Malla de dragón negro' WHERE ID=489;
UPDATE dbc_itemset SET Name_Lang_esMX='Malla de dragón verde' WHERE ID=490;
UPDATE dbc_itemset SET Name_Lang_esMX='Malla de dragón azul' WHERE ID=491;
UPDATE dbc_itemset SET Name_Lang_esMX='Ajuar Crepuscular' WHERE ID=492;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras génesis' WHERE ID=493;
UPDATE dbc_itemset SET Name_Lang_esMX='Símbolos de vida inagotable' WHERE ID=494;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de fuerza implacable' WHERE ID=495;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de conquistador' WHERE ID=496;
UPDATE dbc_itemset SET Name_Lang_esMX='Abrazo de mortífero' WHERE ID=497;
UPDATE dbc_itemset SET Name_Lang_esMX='Emblemas de las Sombras Ocultas' WHERE ID=498;
UPDATE dbc_itemset SET Name_Lang_esMX='Ropajes de clamacondenas' WHERE ID=499;
UPDATE dbc_itemset SET Name_Lang_esMX='Implementos de los nombres prohibidos' WHERE ID=500;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de clamatormentas' WHERE ID=501;
UPDATE dbc_itemset SET Name_Lang_esMX='Ofrenda de la tormenta inminente' WHERE ID=502;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas Enigma' WHERE ID=503;
UPDATE dbc_itemset SET Name_Lang_esMX='Ajuar de secretos oscuros' WHERE ID=504;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla del Vengador' WHERE ID=505;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Justicia eterna' WHERE ID=506;
UPDATE dbc_itemset SET Name_Lang_esMX='Prendas del oráculo' WHERE ID=507;
UPDATE dbc_itemset SET Name_Lang_esMX='Galas de sabiduría infinita' WHERE ID=508;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de asediador' WHERE ID=509;
UPDATE dbc_itemset SET Name_Lang_esMX='Ajuar de la senda oculta' WHERE ID=510;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de heroísmo' WHERE ID=511;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura Mantoscuro' WHERE ID=512;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras cuoroferal' WHERE ID=513;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas del virtuoso' WHERE ID=514;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de maestro de bestias' WHERE ID=515;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura Forjaalma' WHERE ID=516;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de hechicero' WHERE ID=517;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras Brumamorta' WHERE ID=518;
UPDATE dbc_itemset SET Name_Lang_esMX='Los Cinco Truenos' WHERE ID=519;
UPDATE dbc_itemset SET Name_Lang_esMX='Traje de Batalla de Hilacero' WHERE ID=520;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Caminasueños' WHERE ID=521;
UPDATE dbc_itemset SET Name_Lang_esMX='Guardia de Campeón' WHERE ID=522;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla acorator' WHERE ID=523;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura Segahuesos' WHERE ID=524;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas de fe' WHERE ID=525;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío Fuego de Escarcha' WHERE ID=526;
UPDATE dbc_itemset SET Name_Lang_esMX='El Trizaterrador' WHERE ID=527;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de redención' WHERE ID=528;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras corazón de peste' WHERE ID=529;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de acechacriptas' WHERE ID=530;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de matanza de no-muertos' WHERE ID=533;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de Asesino de no-muertos' WHERE ID=534;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de Asesino de no-muertos' WHERE ID=535;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de eliminación de no-muertos' WHERE ID=536;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de batalla de Campeón' WHERE ID=537;
UPDATE dbc_itemset SET Name_Lang_esMX='Clamatormentas de Campeón' WHERE ID=538;
UPDATE dbc_itemset SET Name_Lang_esMX='Refugio de Campeón' WHERE ID=539;
UPDATE dbc_itemset SET Name_Lang_esMX='Investidura de Campeón' WHERE ID=540;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de terror de Campeón' WHERE ID=541;
UPDATE dbc_itemset SET Name_Lang_esMX='Arcanum de Campeón' WHERE ID=542;
UPDATE dbc_itemset SET Name_Lang_esMX='Cumplimiento de Campeón' WHERE ID=543;
UPDATE dbc_itemset SET Name_Lang_esMX='Reducto de Teniente coronel' WHERE ID=544;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de batalla de Teniente coronel' WHERE ID=545;
UPDATE dbc_itemset SET Name_Lang_esMX='Arcanum de Teniente coronel' WHERE ID=546;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de terror de Teniente coronel' WHERE ID=547;
UPDATE dbc_itemset SET Name_Lang_esMX='Guardia de Teniente coronel' WHERE ID=548;
UPDATE dbc_itemset SET Name_Lang_esMX='Investidura de Teniente coronel' WHERE ID=549;
UPDATE dbc_itemset SET Name_Lang_esMX='Persistencia de Teniente coronel' WHERE ID=550;
UPDATE dbc_itemset SET Name_Lang_esMX='Refugio de Teniente coronel' WHERE ID=551;
UPDATE dbc_itemset SET Name_Lang_esMX='Cólera de fuego de hechizo' WHERE ID=552;
UPDATE dbc_itemset SET Name_Lang_esMX='Abrazo de las sombras' WHERE ID=553;
UPDATE dbc_itemset SET Name_Lang_esMX='Tela lunar primigenia' WHERE ID=554;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas de tejido abisal' WHERE ID=555;
UPDATE dbc_itemset SET Name_Lang_esMX='Tejido abisal imbuido' WHERE ID=556;
UPDATE dbc_itemset SET Name_Lang_esMX='Abrazo de paño de alma' WHERE ID=557;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas de tejido Arcano' WHERE ID=558;
UPDATE dbc_itemset SET Name_Lang_esMX='Infusión de golpe de hechizo' WHERE ID=559;
UPDATE dbc_itemset SET Name_Lang_esMX='Placa de hierro vil' WHERE ID=560;
UPDATE dbc_itemset SET Name_Lang_esMX='Cadena de hierro vil' WHERE ID=561;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de adamantita' WHERE ID=562;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de adamantita encantada' WHERE ID=563;
UPDATE dbc_itemset SET Name_Lang_esMX='Guardia de las llamas' WHERE ID=564;
UPDATE dbc_itemset SET Name_Lang_esMX='Resguardo de korio' WHERE ID=565;
UPDATE dbc_itemset SET Name_Lang_esMX='Ira ardiente' WHERE ID=566;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Gladiador' WHERE ID=567;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de tinieblas de Gladiador' WHERE ID=568;
UPDATE dbc_itemset SET Name_Lang_esMX='Fe en el acero vil' WHERE ID=569;
UPDATE dbc_itemset SET Name_Lang_esMX='Los implacables' WHERE ID=570;
UPDATE dbc_itemset SET Name_Lang_esMX='Sabiduría con remiendos blancos' WHERE ID=571;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de conjuro de batalla' WHERE ID=572;
UPDATE dbc_itemset SET Name_Lang_esMX='Piel vil' WHERE ID=573;
UPDATE dbc_itemset SET Name_Lang_esMX='Fuerza de los uñagrieta' WHERE ID=574;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de acechador vil' WHERE ID=575;
UPDATE dbc_itemset SET Name_Lang_esMX='Furia del vacío' WHERE ID=576;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas de Gladiador' WHERE ID=577;
UPDATE dbc_itemset SET Name_Lang_esMX='Sacudetierra de Gladiador' WHERE ID=578;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Gladiador' WHERE ID=579;
UPDATE dbc_itemset SET Name_Lang_esMX='Puño de trueno de Gladiador' WHERE ID=580;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Gladiador' WHERE ID=581;
UPDATE dbc_itemset SET Name_Lang_esMX='Égida de Gladiador' WHERE ID=582;
UPDATE dbc_itemset SET Name_Lang_esMX='Vindicación de Gladiador' WHERE ID=583;
UPDATE dbc_itemset SET Name_Lang_esMX='Santuario de Gladiador' WHERE ID=584;
UPDATE dbc_itemset SET Name_Lang_esMX='Envoltura salvaje de Gladiador' WHERE ID=585;
UPDATE dbc_itemset SET Name_Lang_esMX='Persecución de Gladiador' WHERE ID=586;
UPDATE dbc_itemset SET Name_Lang_esMX='Égida de Gran Señor de la Guerra' WHERE ID=587;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Gran Señor de la Guerra' WHERE ID=588;
UPDATE dbc_itemset SET Name_Lang_esMX='Égida de Gran Mariscal' WHERE ID=589;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Gran mariscal' WHERE ID=590;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de terror de Gran mariscal' WHERE ID=591;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de terror de Gran Señor de la Guerra' WHERE ID=592;
UPDATE dbc_itemset SET Name_Lang_esMX='Sacudetierra de Gran mariscal' WHERE ID=593;
UPDATE dbc_itemset SET Name_Lang_esMX='Sacudetierra de Gran Señor de la Guerra' WHERE ID=594;
UPDATE dbc_itemset SET Name_Lang_esMX='Persecución de Gran mariscal' WHERE ID=595;
UPDATE dbc_itemset SET Name_Lang_esMX='Persecución de Gran Señor de la Guerra' WHERE ID=596;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Gran mariscal' WHERE ID=597;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Gran Señor de la Guerra' WHERE ID=598;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Gran mariscal' WHERE ID=599;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Gran Señor de la Guerra' WHERE ID=600;
UPDATE dbc_itemset SET Name_Lang_esMX='Santuario de Gran mariscal' WHERE ID=601;
UPDATE dbc_itemset SET Name_Lang_esMX='Santuario de Gran Señor de la Guerra' WHERE ID=602;
UPDATE dbc_itemset SET Name_Lang_esMX='Puño de trueno de Gran mariscal' WHERE ID=603;
UPDATE dbc_itemset SET Name_Lang_esMX='Puño de trueno de Gran Señor de la Guerra' WHERE ID=604;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas de Gran mariscal' WHERE ID=605;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas de Gran Señor de la Guerra' WHERE ID=606;
UPDATE dbc_itemset SET Name_Lang_esMX='Vindicación de Gran mariscal' WHERE ID=607;
UPDATE dbc_itemset SET Name_Lang_esMX='Vindicación de Gran Señor de la Guerra' WHERE ID=608;
UPDATE dbc_itemset SET Name_Lang_esMX='Envoltura salvaje de Gran mariscal' WHERE ID=609;
UPDATE dbc_itemset SET Name_Lang_esMX='Envoltura salvaje de Gran Señor de la Guerra' WHERE ID=610;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de escama vil' WHERE ID=611;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura draénica escamada' WHERE ID=612;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura draenei gruesa' WHERE ID=613;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura draenei salvaje' WHERE ID=614;
UPDATE dbc_itemset SET Name_Lang_esMX='Sayo vil de Gladiador' WHERE ID=615;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de escamas abisales' WHERE ID=616;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de golpe abisal' WHERE ID=617;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de halcón del viento' WHERE ID=618;
UPDATE dbc_itemset SET Name_Lang_esMX='Intención primigenia' WHERE ID=619;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de asesinato' WHERE ID=620;
UPDATE dbc_itemset SET Name_Lang_esMX='Filo abisal' WHERE ID=621;
UPDATE dbc_itemset SET Name_Lang_esMX='Manto de la Muerte' WHERE ID=622;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura recta' WHERE ID=623;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de justicar' WHERE ID=624;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de justicar' WHERE ID=625;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de justicar' WHERE ID=626;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras forjacristal' WHERE ID=627;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura forjacristal' WHERE ID=628;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla forjacristal' WHERE ID=629;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras Furiamarea' WHERE ID=630;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de ciclón' WHERE ID=631;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de ciclón' WHERE ID=632;
UPDATE dbc_itemset SET Name_Lang_esMX='Arnés de ciclón' WHERE ID=633;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de cataclismo' WHERE ID=634;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de cataclismo' WHERE ID=635;
UPDATE dbc_itemset SET Name_Lang_esMX='Arnés de cataclismo' WHERE ID=636;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Claro de la Luna' WHERE ID=637;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Malorne' WHERE ID=638;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Malorne' WHERE ID=639;
UPDATE dbc_itemset SET Name_Lang_esMX='Arnés de Malorne' WHERE ID=640;
UPDATE dbc_itemset SET Name_Lang_esMX='Arnés de Nordrassil' WHERE ID=641;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Nordrassil' WHERE ID=642;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Nordrassil' WHERE ID=643;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de olvido' WHERE ID=644;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de corazón vacío' WHERE ID=645;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de corruptor' WHERE ID=646;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de embrujamiento' WHERE ID=647;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de los Aldor' WHERE ID=648;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío Tirisfal' WHERE ID=649;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de Señor de Bestias' WHERE ID=650;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de acechademonios' WHERE ID=651;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de acechador de falla' WHERE ID=652;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura del osado' WHERE ID=653;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de belisario' WHERE ID=654;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de belisario' WHERE ID=655;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de destructor' WHERE ID=656;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de destructor' WHERE ID=657;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío grabado con maná' WHERE ID=658;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de transitayermos' WHERE ID=659;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de desolación' WHERE ID=660;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de placas malditas' WHERE ID=661;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras sacralizadas' WHERE ID=662;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras encarnadas' WHERE ID=663;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío encarnado' WHERE ID=664;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de avatar' WHERE ID=665;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de avatar' WHERE ID=666;
UPDATE dbc_itemset SET Name_Lang_esMX='Las estrellas gemelas' WHERE ID=667;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de destripador' WHERE ID=668;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de acechagronns' WHERE ID=669;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras maléficas' WHERE ID=670;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de tempestad' WHERE ID=671;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de acometida' WHERE ID=672;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de acometida' WHERE ID=673;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de absolución' WHERE ID=674;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas de absolución' WHERE ID=675;
UPDATE dbc_itemset SET Name_Lang_esMX='Arnés de Corazón Atronador' WHERE ID=676;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Corazón Atronador' WHERE ID=677;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Corazón Atronador' WHERE ID=678;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura de Iluminado' WHERE ID=679;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Iluminado' WHERE ID=680;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Iluminado' WHERE ID=681;
UPDATE dbc_itemset SET Name_Lang_esMX='Arnés de Devastador del Cielo' WHERE ID=682;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Devastador del Cielo' WHERE ID=683;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Devastador del Cielo' WHERE ID=684;
UPDATE dbc_itemset SET Name_Lang_esMX='Refugio de Gladiador' WHERE ID=685;
UPDATE dbc_itemset SET Name_Lang_esMX='Marea de guerra de Gladiador' WHERE ID=686;
UPDATE dbc_itemset SET Name_Lang_esMX='Investidura de Gladiador' WHERE ID=687;
UPDATE dbc_itemset SET Name_Lang_esMX='Refugio de Gran mariscal' WHERE ID=688;
UPDATE dbc_itemset SET Name_Lang_esMX='Refugio de Gran Señor de la Guerra' WHERE ID=689;
UPDATE dbc_itemset SET Name_Lang_esMX='Redención de Gladiador' WHERE ID=690;
UPDATE dbc_itemset SET Name_Lang_esMX='Investidura de Gran mariscal' WHERE ID=691;
UPDATE dbc_itemset SET Name_Lang_esMX='Investidura de Gran Señor de la Guerra' WHERE ID=692;
UPDATE dbc_itemset SET Name_Lang_esMX='Redención de Gran mariscal' WHERE ID=693;
UPDATE dbc_itemset SET Name_Lang_esMX='Redención de Gran Señor de la Guerra' WHERE ID=694;
UPDATE dbc_itemset SET Name_Lang_esMX='Marea de guerra de Gran mariscal' WHERE ID=695;
UPDATE dbc_itemset SET Name_Lang_esMX='Marea de guerra de Gran Señor de la Guerra' WHERE ID=696;
UPDATE dbc_itemset SET Name_Lang_esMX='Reducto de Campeón' WHERE ID=697;
UPDATE dbc_itemset SET Name_Lang_esMX='Égida de Señor de la Guerra' WHERE ID=698;
UPDATE dbc_itemset SET Name_Lang_esMX='Las hojas gemelas de Azzinoth' WHERE ID=699;
UPDATE dbc_itemset SET Name_Lang_esMX='Égida de Gladiador despiadado' WHERE ID=700;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Gladiador despiadado' WHERE ID=701;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de terror de Gladiador despiadado' WHERE ID=702;
UPDATE dbc_itemset SET Name_Lang_esMX='Sacudetierra de Gladiador despiadado' WHERE ID=703;
UPDATE dbc_itemset SET Name_Lang_esMX='Sayo vil de Gladiador despiadado' WHERE ID=704;
UPDATE dbc_itemset SET Name_Lang_esMX='Investidura de Gladiador despiadado' WHERE ID=705;
UPDATE dbc_itemset SET Name_Lang_esMX='Persecución de Gladiador despiadado' WHERE ID=706;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Gladiador despiadado' WHERE ID=707;
UPDATE dbc_itemset SET Name_Lang_esMX='Redención de Gladiador despiadado' WHERE ID=708;
UPDATE dbc_itemset SET Name_Lang_esMX='Refugio de Gladiador despiadado' WHERE ID=709;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Gladiador despiadado' WHERE ID=710;
UPDATE dbc_itemset SET Name_Lang_esMX='Santuario de Gladiador despiadado' WHERE ID=711;
UPDATE dbc_itemset SET Name_Lang_esMX='Puño de trueno de Gladiador despiadado' WHERE ID=712;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas de Gladiador despiadado' WHERE ID=713;
UPDATE dbc_itemset SET Name_Lang_esMX='Vindicación de Gladiador despiadado' WHERE ID=714;
UPDATE dbc_itemset SET Name_Lang_esMX='Marea de guerra de Gladiador despiadado' WHERE ID=715;
UPDATE dbc_itemset SET Name_Lang_esMX='Envoltura salvaje de Gladiador despiadado' WHERE ID=716;
UPDATE dbc_itemset SET Name_Lang_esMX='Sacudetierra de Mariscal de campo' WHERE ID=717;
UPDATE dbc_itemset SET Name_Lang_esMX='Sacudetierra de Teniente coronel' WHERE ID=718;
UPDATE dbc_itemset SET Name_Lang_esMX='Los puños de furia' WHERE ID=719;
UPDATE dbc_itemset SET Name_Lang_esMX='Refugio de Gladiador vengativo' WHERE ID=720;
UPDATE dbc_itemset SET Name_Lang_esMX='Santuario de Gladiador vengativo' WHERE ID=721;
UPDATE dbc_itemset SET Name_Lang_esMX='Envoltura salvaje de Gladiador vengativo' WHERE ID=722;
UPDATE dbc_itemset SET Name_Lang_esMX='Persecución de Gladiador vengativo' WHERE ID=723;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Gladiador vengativo' WHERE ID=724;
UPDATE dbc_itemset SET Name_Lang_esMX='Redención de Gladiador vengativo' WHERE ID=725;
UPDATE dbc_itemset SET Name_Lang_esMX='Vindicación de Gladiador vengativo' WHERE ID=726;
UPDATE dbc_itemset SET Name_Lang_esMX='Égida de Gladiador vengativo' WHERE ID=727;
UPDATE dbc_itemset SET Name_Lang_esMX='Investidura de Gladiador vengativo' WHERE ID=728;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Gladiador vengativo' WHERE ID=729;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas de Gladiador vengativo' WHERE ID=730;
UPDATE dbc_itemset SET Name_Lang_esMX='Marea de guerra de Gladiador vengativo' WHERE ID=731;
UPDATE dbc_itemset SET Name_Lang_esMX='Sacudetierra de Gladiador vengativo' WHERE ID=732;
UPDATE dbc_itemset SET Name_Lang_esMX='Puño de trueno de Gladiador vengativo' WHERE ID=733;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de terror de Gladiador vengativo' WHERE ID=734;
UPDATE dbc_itemset SET Name_Lang_esMX='Sayo vil de Gladiador vengativo' WHERE ID=735;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Gladiador vengativo' WHERE ID=736;
UPDATE dbc_itemset SET Name_Lang_esMX='Aluvión de Latro' WHERE ID=737;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de tejido de tinieblas' WHERE ID=738;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de tela lunar' WHERE ID=739;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de satén' WHERE ID=740;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de seda evocador' WHERE ID=741;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de pellejo de dragón' WHERE ID=742;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de pellejo de vermis' WHERE ID=743;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de pellejo de kodo' WHERE ID=744;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de oportunista' WHERE ID=745;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de malla de vidente' WHERE ID=746;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de cota guarnecida de vidente' WHERE ID=747;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de eslabones de vidente' WHERE ID=748;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de anillas de acechador' WHERE ID=749;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de placas salvajes' WHERE ID=750;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla ornamentado de cruzado' WHERE ID=751;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla escamado de cruzado' WHERE ID=752;
UPDATE dbc_itemset SET Name_Lang_esMX='Abrazo boreal' WHERE ID=754;
UPDATE dbc_itemset SET Name_Lang_esMX='Enjambre nerubiano' WHERE ID=755;
UPDATE dbc_itemset SET Name_Lang_esMX='Defensa de escamas de escarcha' WHERE ID=756;
UPDATE dbc_itemset SET Name_Lang_esMX='Abrazo de contrahielo' WHERE ID=757;
UPDATE dbc_itemset SET Name_Lang_esMX='Venganza de Raine' WHERE ID=759;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas de tinieblas de Gladiador' WHERE ID=760;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de invierno' WHERE ID=761;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de la Fiesta de la cerveza' WHERE ID=762;
UPDATE dbc_itemset SET Name_Lang_esMX='Poder tejido con Escarcha' WHERE ID=763;
UPDATE dbc_itemset SET Name_Lang_esMX='Tejedor del Alba' WHERE ID=764;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Gladiador' WHERE ID=765;
UPDATE dbc_itemset SET Name_Lang_esMX='Vindicación de Gladiador' WHERE ID=766;
UPDATE dbc_itemset SET Name_Lang_esMX='Redención de Gladiador' WHERE ID=767;
UPDATE dbc_itemset SET Name_Lang_esMX='Profanación de Gladiador' WHERE ID=768;
UPDATE dbc_itemset SET Name_Lang_esMX='Puño de trueno de Gladiador' WHERE ID=769;
UPDATE dbc_itemset SET Name_Lang_esMX='Sacudetierra de Gladiador' WHERE ID=770;
UPDATE dbc_itemset SET Name_Lang_esMX='Marea de guerra de Gladiador' WHERE ID=771;
UPDATE dbc_itemset SET Name_Lang_esMX='Persecución de Gladiador' WHERE ID=772;
UPDATE dbc_itemset SET Name_Lang_esMX='Refugio de Gladiador' WHERE ID=773;
UPDATE dbc_itemset SET Name_Lang_esMX='Envoltura salvaje de Gladiador' WHERE ID=774;
UPDATE dbc_itemset SET Name_Lang_esMX='Santuario de Gladiador' WHERE ID=775;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestimentas de Gladiador' WHERE ID=776;
UPDATE dbc_itemset SET Name_Lang_esMX='Investidura de Gladiador' WHERE ID=777;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Gladiador' WHERE ID=778;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Gladiador' WHERE ID=779;
UPDATE dbc_itemset SET Name_Lang_esMX='Sayo vil de Gladiador' WHERE ID=780;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío bendecido de limpieza de no-muertos' WHERE ID=781;
UPDATE dbc_itemset SET Name_Lang_esMX='Armadura bendecida de Asesino de no-muertos' WHERE ID=782;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo bendecido del Asesino de no-muertos' WHERE ID=783;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla bendecido de matanza de no-muertos' WHERE ID=784;
UPDATE dbc_itemset SET Name_Lang_esMX='Juerguista del solsticio de verano' WHERE ID=785;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas acorator' WHERE ID=787;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla acorator' WHERE ID=788;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de redención' WHERE ID=789;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de la Redención' WHERE ID=790;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas de la Redención' WHERE ID=791;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de vástagos de la Plaga' WHERE ID=792;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas de vástagos de la Plaga' WHERE ID=793;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de acechacriptas' WHERE ID=794;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Rompeterra' WHERE ID=795;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de Rompeterra' WHERE ID=796;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Rompeterra' WHERE ID=797;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Caminasueños' WHERE ID=798;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Caminasueños' WHERE ID=799;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de Caminasueños' WHERE ID=800;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla Segahuesos' WHERE ID=801;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo corazón de peste' WHERE ID=802;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo Fuego de Escarcha' WHERE ID=803;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de fe' WHERE ID=804;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de fe' WHERE ID=805;
UPDATE dbc_itemset SET Name_Lang_esMX='Esmoquin de primavera' WHERE ID=812;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de eviscerador' WHERE ID=813;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de saronita ornamentada' WHERE ID=814;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de taumaturgo supremo' WHERE ID=815;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de saronita salvaje' WHERE ID=816;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Tormentero' WHERE ID=817;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla Flechapresta' WHERE ID=818;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de escarcha salvaje' WHERE ID=819;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de égida' WHERE ID=820;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas de égida' WHERE ID=821;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de égida' WHERE ID=822;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de rompemundos' WHERE ID=823;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de rompemundos' WHERE ID=824;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de rompemundos' WHERE ID=825;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla hoja de terror' WHERE ID=826;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Arrullanoche' WHERE ID=827;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de Arrullanoche' WHERE ID=828;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Arrullanoche' WHERE ID=829;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de rompedor del asedio' WHERE ID=830;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas de rompedor del asedio' WHERE ID=831;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de santificación' WHERE ID=832;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de santificación' WHERE ID=833;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de runaoscura' WHERE ID=834;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas de runaoscura' WHERE ID=835;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo del Kirin Tor' WHERE ID=836;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo libramorte' WHERE ID=837;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de acechador de la Plaga' WHERE ID=838;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Khadgar' WHERE ID=843;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Caminante del Sol' WHERE ID=844;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Gul''dan' WHERE ID=845;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Kel''Thuzad' WHERE ID=846;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Velen' WHERE ID=847;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de Zabra' WHERE ID=848;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Velen' WHERE ID=849;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Zabra' WHERE ID=850;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de Malfurion' WHERE ID=851;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de Tótem de Runa' WHERE ID=852;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Malfurion' WHERE ID=853;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Tótem de Runa' WHERE ID=854;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Malfurion' WHERE ID=855;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Tótem de Runa' WHERE ID=856;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de VanCleef' WHERE ID=857;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Garona' WHERE ID=858;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Brisaveloz' WHERE ID=859;
UPDATE dbc_itemset SET Name_Lang_esMX='Persecución de Brisaveloz' WHERE ID=860;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de Nobundo' WHERE ID=861;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de Thrall' WHERE ID=862;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Thrall' WHERE ID=863;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de Nobundo' WHERE ID=864;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Nobundo' WHERE ID=865;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Thrall' WHERE ID=866;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Wrynn' WHERE ID=867;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Grito Infernal' WHERE ID=868;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas de Wrynn' WHERE ID=869;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas de Grito Infernal' WHERE ID=870;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Thassarian' WHERE ID=871;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Koltira' WHERE ID=872;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas de Thassarian' WHERE ID=873;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas de Koltira' WHERE ID=874;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de Turalyon' WHERE ID=875;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de Liadrin' WHERE ID=876;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Turalyon' WHERE ID=877;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Liadrin' WHERE ID=878;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas de Turalyon' WHERE ID=879;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas de Liadrin' WHERE ID=880;
UPDATE dbc_itemset SET Name_Lang_esMX='Fragmento de los Dioses purificado' WHERE ID=881;
UPDATE dbc_itemset SET Name_Lang_esMX='Fragmento de los Dioses lustroso' WHERE ID=882;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de mago sangriento' WHERE ID=883;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío del aquelarre oscuro' WHERE ID=884;
UPDATE dbc_itemset SET Name_Lang_esMX='Vestiduras de acólito carmesí' WHERE ID=885;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de acólito carmesí' WHERE ID=886;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de tejeazote' WHERE ID=887;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de tejeazote' WHERE ID=888;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de tejeazote' WHERE ID=889;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Hoja de las Sombras' WHERE ID=890;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de cazador de sangre Ahn''Kahar' WHERE ID=891;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de bruja de Escarcha' WHERE ID=892;
UPDATE dbc_itemset SET Name_Lang_esMX='Atavío de bruja de Escarcha' WHERE ID=893;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de bruja de Escarcha' WHERE ID=894;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de señor Ymirjar' WHERE ID=895;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas de señor Ymirjar' WHERE ID=896;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de Señor de la Plaga' WHERE ID=897;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas de Señor de la Plaga' WHERE ID=898;
UPDATE dbc_itemset SET Name_Lang_esMX='Atuendo de juraluz' WHERE ID=899;
UPDATE dbc_itemset SET Name_Lang_esMX='Equipo de batalla de juraluz' WHERE ID=900;
UPDATE dbc_itemset SET Name_Lang_esMX='Placas de juraluz' WHERE ID=901;
