UPDATE dbc_chrraces SET Name_Lang_esMX='Humano', Name_Female_Lang_esMX='Humana', Name_Male_Lang_esMX='Humano' WHERE ID=1;
UPDATE dbc_chrraces SET Name_Lang_esMX='Orco', Name_Female_Lang_esMX='Orco', Name_Male_Lang_esMX='Orco' WHERE ID=2;
UPDATE dbc_chrraces SET Name_Lang_esMX='Enano', Name_Female_Lang_esMX='Enana', Name_Male_Lang_esMX='Enano' WHERE ID=3;
UPDATE dbc_chrraces SET Name_Lang_esMX='Elfo de la noche', Name_Female_Lang_esMX='Elfa de la noche', Name_Male_Lang_esMX='Elfo de la noche' WHERE ID=4;
UPDATE dbc_chrraces SET Name_Lang_esMX='No-muerto', Name_Female_Lang_esMX='No-muerta', Name_Male_Lang_esMX='No-muerto' WHERE ID=5;
UPDATE dbc_chrraces SET Name_Lang_esMX='Tauren', Name_Female_Lang_esMX='Tauren', Name_Male_Lang_esMX='Tauren' WHERE ID=6;
UPDATE dbc_chrraces SET Name_Lang_esMX='Gnomo', Name_Female_Lang_esMX='Gnoma', Name_Male_Lang_esMX='Gnomo' WHERE ID=7;
UPDATE dbc_chrraces SET Name_Lang_esMX='Trol', Name_Female_Lang_esMX='Trol', Name_Male_Lang_esMX='Trol' WHERE ID=8;
UPDATE dbc_chrraces SET Name_Lang_esMX='Goblin', Name_Female_Lang_esMX='Goblin', Name_Male_Lang_esMX='Goblin' WHERE ID=9;
UPDATE dbc_chrraces SET Name_Lang_esMX='Elfo de sangre', Name_Female_Lang_esMX='Elfa de sangre', Name_Male_Lang_esMX='Elfo de sangre' WHERE ID=10;
UPDATE dbc_chrraces SET Name_Lang_esMX='Draenei', Name_Female_Lang_esMX='Draenei', Name_Male_Lang_esMX='Draenei' WHERE ID=11;
UPDATE dbc_chrraces SET Name_Lang_esMX='Orco vil', Name_Female_Lang_esMX='Orco vil', Name_Male_Lang_esMX='Orco vil' WHERE ID=12;
UPDATE dbc_chrraces SET Name_Lang_esMX='Naga', Name_Female_Lang_esMX='Naga', Name_Male_Lang_esMX='Naga' WHERE ID=13;
UPDATE dbc_chrraces SET Name_Lang_esMX='Tábido', Name_Female_Lang_esMX='Tábida', Name_Male_Lang_esMX='Tábido' WHERE ID=14;
UPDATE dbc_chrraces SET Name_Lang_esMX='Esqueleto', Name_Female_Lang_esMX='Esqueleto', Name_Male_Lang_esMX='Esqueleto' WHERE ID=15;
UPDATE dbc_chrraces SET Name_Lang_esMX='Vrykul', Name_Female_Lang_esMX='Vrykul', Name_Male_Lang_esMX='Vrykul' WHERE ID=16;
UPDATE dbc_chrraces SET Name_Lang_esMX='Colmillarr', Name_Female_Lang_esMX='Colmillarr', Name_Male_Lang_esMX='Colmillarr' WHERE ID=17;
UPDATE dbc_chrraces SET Name_Lang_esMX='Trol de bosque', Name_Female_Lang_esMX='Trol de bosque', Name_Male_Lang_esMX='Trol de bosque' WHERE ID=18;
UPDATE dbc_chrraces SET Name_Lang_esMX='Taunka', Name_Female_Lang_esMX='Taunka', Name_Male_Lang_esMX='Taunka' WHERE ID=19;
UPDATE dbc_chrraces SET Name_Lang_esMX='Esqueleto de Rasganorte', Name_Female_Lang_esMX='Esqueleto de Rasganorte', Name_Male_Lang_esMX='Esqueleto de Rasganorte' WHERE ID=20;
UPDATE dbc_chrraces SET Name_Lang_esMX='Trol de hielo', Name_Female_Lang_esMX='Trol de hielo', Name_Male_Lang_esMX='Trol de hielo' WHERE ID=21;
