UPDATE dbc_areapoi SET Name_Lang_esMX='Pico Nidal', Description_Lang_esMX='' WHERE ID=792;
UPDATE dbc_areapoi SET Name_Lang_esMX='Estación de Algaz', Description_Lang_esMX='' WHERE ID=1032;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fortaleza de Angor', Description_Lang_esMX='' WHERE ID=27;
UPDATE dbc_areapoi SET Name_Lang_esMX='Yunquemar', Description_Lang_esMX='' WHERE ID=1;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento de Ariden', Description_Lang_esMX='' WHERE ID=1287;
UPDATE dbc_areapoi SET Name_Lang_esMX='Refugio de los Mendigos', Description_Lang_esMX='' WHERE ID=1128;
UPDATE dbc_areapoi SET Name_Lang_esMX='Bahía del Botín', Description_Lang_esMX='' WHERE ID=40;
UPDATE dbc_areapoi SET Name_Lang_esMX='Avanzada Puño de Roca', Description_Lang_esMX='' WHERE ID=1010;
UPDATE dbc_areapoi SET Name_Lang_esMX='Rémol', Description_Lang_esMX='' WHERE ID=2;
UPDATE dbc_areapoi SET Name_Lang_esMX='Molino Cejifrente', Description_Lang_esMX='' WHERE ID=1018;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento del Orvallo', Description_Lang_esMX='' WHERE ID=1307;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Corona', Description_Lang_esMX='' WHERE ID=1770;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Corona', Description_Lang_esMX='Alianza, en disputa' WHERE ID=1771;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Corona', Description_Lang_esMX='Horda, en disputa' WHERE ID=1772;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Corona', Description_Lang_esMX='Alianza, en progreso' WHERE ID=1773;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Corona', Description_Lang_esMX='Horda, en progreso' WHERE ID=1774;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Corona', Description_Lang_esMX='Alianza' WHERE ID=1775;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Corona', Description_Lang_esMX='Horda' WHERE ID=1776;
UPDATE dbc_areapoi SET Name_Lang_esMX='Villa Oscura', Description_Lang_esMX='' WHERE ID=3;
UPDATE dbc_areapoi SET Name_Lang_esMX='Barranco de la Muerte', Description_Lang_esMX='' WHERE ID=1288;
UPDATE dbc_areapoi SET Name_Lang_esMX='Camposanto', Description_Lang_esMX='' WHERE ID=4;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cañón Mostacho Seco', Description_Lang_esMX='' WHERE ID=327;
UPDATE dbc_areapoi SET Name_Lang_esMX='Dun Algaz', Description_Lang_esMX='' WHERE ID=5;
UPDATE dbc_areapoi SET Name_Lang_esMX='Dun Modr', Description_Lang_esMX='' WHERE ID=6;
UPDATE dbc_areapoi SET Name_Lang_esMX='Gruta Rotapolvo', Description_Lang_esMX='' WHERE ID=1028;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Muralla del Este', Description_Lang_esMX='' WHERE ID=1749;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Muralla del Este', Description_Lang_esMX='Alianza, en disputa' WHERE ID=1750;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Muralla del Este', Description_Lang_esMX='Alianza, en progreso' WHERE ID=1751;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Muralla del Este', Description_Lang_esMX='Horda, en disputa' WHERE ID=1752;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Muralla del Este', Description_Lang_esMX='Horda, en progreso' WHERE ID=1753;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Muralla del Este', Description_Lang_esMX='Horda' WHERE ID=1754;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Muralla del Este', Description_Lang_esMX='Alianza' WHERE ID=1755;
UPDATE dbc_areapoi SET Name_Lang_esMX='Mina del Eco', Description_Lang_esMX='' WHERE ID=949;
UPDATE dbc_areapoi SET Name_Lang_esMX='Peñasco Llamarada', Description_Lang_esMX='' WHERE ID=1177;
UPDATE dbc_areapoi SET Name_Lang_esMX='Villadorada', Description_Lang_esMX='' WHERE ID=7;
UPDATE dbc_areapoi SET Name_Lang_esMX='Grim Batol', Description_Lang_esMX='' WHERE ID=1033;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Grom''Gol', Description_Lang_esMX='' WHERE ID=41;
UPDATE dbc_areapoi SET Name_Lang_esMX='Dominios Grosh''gok', Description_Lang_esMX='' WHERE ID=1011;
UPDATE dbc_areapoi SET Name_Lang_esMX='Sentencia', Description_Lang_esMX='' WHERE ID=25;
UPDATE dbc_areapoi SET Name_Lang_esMX='Complejo Vetaferro', Description_Lang_esMX='' WHERE ID=948;
UPDATE dbc_areapoi SET Name_Lang_esMX='Forjaz', Description_Lang_esMX='' WHERE ID=8;
UPDATE dbc_areapoi SET Name_Lang_esMX='Los Dominios de Ivar', Description_Lang_esMX='' WHERE ID=1702;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cayo de Janeiro', Description_Lang_esMX='' WHERE ID=1031;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cantera de Jaspe', Description_Lang_esMX='' WHERE ID=1030;
UPDATE dbc_areapoi SET Name_Lang_esMX='Kargath', Description_Lang_esMX='' WHERE ID=26;
UPDATE dbc_areapoi SET Name_Lang_esMX='Kharanos', Description_Lang_esMX='' WHERE ID=9;
UPDATE dbc_areapoi SET Name_Lang_esMX='Villa del Lago', Description_Lang_esMX='' WHERE ID=10;
UPDATE dbc_areapoi SET Name_Lang_esMX='Los Viñedos de Maclure', Description_Lang_esMX='' WHERE ID=950;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerto de Menethil', Description_Lang_esMX='' WHERE ID=11;
UPDATE dbc_areapoi SET Name_Lang_esMX='Lago Espejo', Description_Lang_esMX='' WHERE ID=227;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puesto Juncobruma', Description_Lang_esMX='' WHERE ID=1683;
UPDATE dbc_areapoi SET Name_Lang_esMX='Arroyo de la Luna', Description_Lang_esMX='' WHERE ID=12;
UPDATE dbc_areapoi SET Name_Lang_esMX='Hoya Nocturácnidas', Description_Lang_esMX='' WHERE ID=1016;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Paso del Norte', Description_Lang_esMX='' WHERE ID=1763;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Paso del Norte', Description_Lang_esMX='Alianza, en disputa' WHERE ID=1764;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Paso del Norte', Description_Lang_esMX='Horda, en disputa' WHERE ID=1765;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Paso del Norte', Description_Lang_esMX='Alianza, en progreso' WHERE ID=1766;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Paso del Norte', Description_Lang_esMX='Horda, en progreso' WHERE ID=1767;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Paso del Norte', Description_Lang_esMX='Alianza' WHERE ID=1768;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Paso del Norte', Description_Lang_esMX='Horda' WHERE ID=1769;
UPDATE dbc_areapoi SET Name_Lang_esMX='Abadía de Villanorte', Description_Lang_esMX='' WHERE ID=13;
UPDATE dbc_areapoi SET Name_Lang_esMX='Viñedos de Villanorte', Description_Lang_esMX='' WHERE ID=954;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Bosque de la Peste', Description_Lang_esMX='' WHERE ID=1756;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Bosque de la Peste', Description_Lang_esMX='Alianza, en disputa' WHERE ID=1757;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Bosque de la Peste', Description_Lang_esMX='Horda, en progreso' WHERE ID=1760;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Bosque de la Peste', Description_Lang_esMX='Alianza' WHERE ID=1761;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Bosque de la Peste', Description_Lang_esMX='Horda' WHERE ID=1762;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Bosque de la Peste', Description_Lang_esMX='Alianza, en progreso' WHERE ID=1777;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cerro del Cuervo', Description_Lang_esMX='' WHERE ID=14;
UPDATE dbc_areapoi SET Name_Lang_esMX='Refugio de la Zaga', Description_Lang_esMX='' WHERE ID=24;
UPDATE dbc_areapoi SET Name_Lang_esMX='Roca de Render', Description_Lang_esMX='' WHERE ID=956;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cavernas de Rethban', Description_Lang_esMX='' WHERE ID=1008;
UPDATE dbc_areapoi SET Name_Lang_esMX='Poblado Sañadiente', Description_Lang_esMX='' WHERE ID=1507;
UPDATE dbc_areapoi SET Name_Lang_esMX='Condena de Roland', Description_Lang_esMX='' WHERE ID=1127;
UPDATE dbc_areapoi SET Name_Lang_esMX='Scholomance', Description_Lang_esMX='' WHERE ID=710;
UPDATE dbc_areapoi SET Name_Lang_esMX='Colina del Centinela', Description_Lang_esMX='' WHERE ID=15;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cuenca de la Matanza', Description_Lang_esMX='' WHERE ID=247;
UPDATE dbc_areapoi SET Name_Lang_esMX='Desfiladero del Letargo', Description_Lang_esMX='' WHERE ID=1289;
UPDATE dbc_areapoi SET Name_Lang_esMX='Roca Desliz', Description_Lang_esMX='' WHERE ID=1176;
UPDATE dbc_areapoi SET Name_Lang_esMX='Costasur', Description_Lang_esMX='' WHERE ID=22;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cubil del Espíritu', Description_Lang_esMX='' WHERE ID=1007;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cueva Stagalbog', Description_Lang_esMX='' WHERE ID=1012;
UPDATE dbc_areapoi SET Name_Lang_esMX='Almacén de Brasacerada', Description_Lang_esMX='' WHERE ID=947;
UPDATE dbc_areapoi SET Name_Lang_esMX='Rocal', Description_Lang_esMX='' WHERE ID=788;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Granja Pedregosa', Description_Lang_esMX='' WHERE ID=951;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ciudad de Ventormenta', Description_Lang_esMX='' WHERE ID=16;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerto de Ventormenta', Description_Lang_esMX='' WHERE ID=2110;
UPDATE dbc_areapoi SET Name_Lang_esMX='Molino Tarren', Description_Lang_esMX='' WHERE ID=23;
UPDATE dbc_areapoi SET Name_Lang_esMX='Templo de Atal''Hakkar', Description_Lang_esMX='' WHERE ID=1013;
UPDATE dbc_areapoi SET Name_Lang_esMX='Túnel Terroarácnido', Description_Lang_esMX='' WHERE ID=1017;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Sepulcro', Description_Lang_esMX='' WHERE ID=17;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de Arathor', Description_Lang_esMX='' WHERE ID=1014;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Cueva del Llanto', Description_Lang_esMX='' WHERE ID=1551;
UPDATE dbc_areapoi SET Name_Lang_esMX='Thelsamar', Description_Lang_esMX='' WHERE ID=19;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puesto del Torio', Description_Lang_esMX='' WHERE ID=1508;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de Ilgalar', Description_Lang_esMX='' WHERE ID=955;
UPDATE dbc_areapoi SET Name_Lang_esMX='Uldaman', Description_Lang_esMX='' WHERE ID=1027;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ataque enemigo', Description_Lang_esMX='Las Tierras Devastadas' WHERE ID=1698;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ataque enemigo', Description_Lang_esMX='Las Estepas Ardientes' WHERE ID=1699;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ataque enemigo', Description_Lang_esMX='Tierras de la Peste del Este' WHERE ID=1701;
UPDATE dbc_areapoi SET Name_Lang_esMX='Entrañas', Description_Lang_esMX='' WHERE ID=18;
UPDATE dbc_areapoi SET Name_Lang_esMX='Tumba de Uther', Description_Lang_esMX='' WHERE ID=709;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campo de Valgan', Description_Lang_esMX='' WHERE ID=1703;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cuartel de Arroyoeste', Description_Lang_esMX='' WHERE ID=1029;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fortaleza de los Martillo Salvaje', Description_Lang_esMX='' WHERE ID=1015;
UPDATE dbc_areapoi SET Name_Lang_esMX='Isla Yojamba', Description_Lang_esMX='' WHERE ID=1588;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aldrassil', Description_Lang_esMX='' WHERE ID=36;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aldrassil', Description_Lang_esMX='' WHERE ID=907;
UPDATE dbc_areapoi SET Name_Lang_esMX='Astranaar', Description_Lang_esMX='' WHERE ID=42;
UPDATE dbc_areapoi SET Name_Lang_esMX='Auberdine', Description_Lang_esMX='' WHERE ID=798;
UPDATE dbc_areapoi SET Name_Lang_esMX='Túmulo de Ban''ethil', Description_Lang_esMX='' WHERE ID=911;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ruinas de Bathran', Description_Lang_esMX='' WHERE ID=1233;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cubil del Bosque Negro', Description_Lang_esMX='' WHERE ID=1048;
UPDATE dbc_areapoi SET Name_Lang_esMX='Madriguera de los Cienorrojo', Description_Lang_esMX='' WHERE ID=1096;
UPDATE dbc_areapoi SET Name_Lang_esMX='Poblado Pezuña de Sangre', Description_Lang_esMX='' WHERE ID=28;
UPDATE dbc_areapoi SET Name_Lang_esMX='Asentamiento Sangradientes', Description_Lang_esMX='' WHERE ID=1244;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puesto del Veneno', Description_Lang_esMX='' WHERE ID=1220;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ciénaga Azul', Description_Lang_esMX='' WHERE ID=1090;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cuenca de Bolgan', Description_Lang_esMX='' WHERE ID=1147;
UPDATE dbc_areapoi SET Name_Lang_esMX='Huesos de Grakkarond', Description_Lang_esMX='' WHERE ID=1473;
UPDATE dbc_areapoi SET Name_Lang_esMX='Poblado Murohelecho', Description_Lang_esMX='' WHERE ID=1684;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Barbabronce', Description_Lang_esMX='' WHERE ID=1694;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Mojache', Description_Lang_esMX='' WHERE ID=790;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Narache', Description_Lang_esMX='' WHERE ID=30;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Taurajo', Description_Lang_esMX='' WHERE ID=1469;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fuerte Cenarion', Description_Lang_esMX='' WHERE ID=1685;
UPDATE dbc_areapoi SET Name_Lang_esMX='Salto de Fonroca', Description_Lang_esMX='' WHERE ID=1050;
UPDATE dbc_areapoi SET Name_Lang_esMX='Lago del Peñasco', Description_Lang_esMX='' WHERE ID=1228;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cumbre de la Nube Negra', Description_Lang_esMX='' WHERE ID=1108;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cueva Niebla Negra', Description_Lang_esMX='' WHERE ID=1088;
UPDATE dbc_areapoi SET Name_Lang_esMX='Darnassus', Description_Lang_esMX='' WHERE ID=38;
UPDATE dbc_areapoi SET Name_Lang_esMX='Barranco del Demonio', Description_Lang_esMX='' WHERE ID=1239;
UPDATE dbc_areapoi SET Name_Lang_esMX='Dolanaar', Description_Lang_esMX='' WHERE ID=37;
UPDATE dbc_areapoi SET Name_Lang_esMX='Dun Mandarr', Description_Lang_esMX='' WHERE ID=1214;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cubil de Brasaliza', Description_Lang_esMX='' WHERE ID=1095;
UPDATE dbc_areapoi SET Name_Lang_esMX='Vista Eterna', Description_Lang_esMX='' WHERE ID=794;
UPDATE dbc_areapoi SET Name_Lang_esMX='Río Falfarren', Description_Lang_esMX='' WHERE ID=1235;
UPDATE dbc_areapoi SET Name_Lang_esMX='Bastión Plumaluna', Description_Lang_esMX='' WHERE ID=796;
UPDATE dbc_areapoi SET Name_Lang_esMX='Roca Mácula', Description_Lang_esMX='' WHERE ID=909;
UPDATE dbc_areapoi SET Name_Lang_esMX='Canción del Bosque', Description_Lang_esMX='' WHERE ID=1238;
UPDATE dbc_areapoi SET Name_Lang_esMX='Isla de Batalla', Description_Lang_esMX='' WHERE ID=1067;
UPDATE dbc_areapoi SET Name_Lang_esMX='Poblado Viento Libre', Description_Lang_esMX='' WHERE ID=46;
UPDATE dbc_areapoi SET Name_Lang_esMX='Roca Fungal', Description_Lang_esMX='' WHERE ID=1105;
UPDATE dbc_areapoi SET Name_Lang_esMX='Gadgetzan', Description_Lang_esMX='' WHERE ID=789;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento del Espíritu Errante', Description_Lang_esMX='' WHERE ID=1149;
UPDATE dbc_areapoi SET Name_Lang_esMX='Poblado Zarpaverde', Description_Lang_esMX='' WHERE ID=1243;
UPDATE dbc_areapoi SET Name_Lang_esMX='Guarida de Hetaera', Description_Lang_esMX='' WHERE ID=708;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Roca de Hierro', Description_Lang_esMX='' WHERE ID=1114;
UPDATE dbc_areapoi SET Name_Lang_esMX='Caverna de Troncoferro', Description_Lang_esMX='' WHERE ID=1219;
UPDATE dbc_areapoi SET Name_Lang_esMX='Pabellón de Lariss', Description_Lang_esMX='' WHERE ID=1175;
UPDATE dbc_areapoi SET Name_Lang_esMX='Punta Perdida', Description_Lang_esMX='' WHERE ID=1091;
UPDATE dbc_areapoi SET Name_Lang_esMX='Maraudon', Description_Lang_esMX='' WHERE ID=1148;
UPDATE dbc_areapoi SET Name_Lang_esMX='Refugio de Marshal', Description_Lang_esMX='' WHERE ID=1104;
UPDATE dbc_areapoi SET Name_Lang_esMX='Circuito del Espejismo', Description_Lang_esMX='' WHERE ID=1110;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cubil del Horror de la Luna', Description_Lang_esMX='' WHERE ID=1217;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento de Mor''shan', Description_Lang_esMX='' WHERE ID=1512;
UPDATE dbc_areapoi SET Name_Lang_esMX='Piñón de Barro', Description_Lang_esMX='' WHERE ID=2083;
UPDATE dbc_areapoi SET Name_Lang_esMX='Amparo de la Noche', Description_Lang_esMX='' WHERE ID=1247;
UPDATE dbc_areapoi SET Name_Lang_esMX='Punta de Nijel', Description_Lang_esMX='' WHERE ID=799;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Punta Norte', Description_Lang_esMX='' WHERE ID=1089;
UPDATE dbc_areapoi SET Name_Lang_esMX='Guarida de Onyxia', Description_Lang_esMX='' WHERE ID=1094;
UPDATE dbc_areapoi SET Name_Lang_esMX='Orgrimmar', Description_Lang_esMX='' WHERE ID=33;
UPDATE dbc_areapoi SET Name_Lang_esMX='Guarida de Ortell', Description_Lang_esMX='' WHERE ID=1690;
UPDATE dbc_areapoi SET Name_Lang_esMX='Dominios de los Cicatriz de Rabia', Description_Lang_esMX='' WHERE ID=1168;
UPDATE dbc_areapoi SET Name_Lang_esMX='Trinquete', Description_Lang_esMX='' WHERE ID=39;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Crepúsculo Devastado', Description_Lang_esMX='' WHERE ID=1171;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cerrotajo', Description_Lang_esMX='' WHERE ID=31;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cañón del Ventajo', Description_Lang_esMX='' WHERE ID=913;
UPDATE dbc_areapoi SET Name_Lang_esMX='Sagrario de Rethress', Description_Lang_esMX='' WHERE ID=1216;
UPDATE dbc_areapoi SET Name_Lang_esMX='Guarida Malapluma', Description_Lang_esMX='' WHERE ID=1109;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ruinas de Solarsal', Description_Lang_esMX='' WHERE ID=1169;
UPDATE dbc_areapoi SET Name_Lang_esMX='¡Gusano de Arena!', Description_Lang_esMX='Ha aparecido una bestia de silitista' WHERE ID=1724;
UPDATE dbc_areapoi SET Name_Lang_esMX='¡Gusano de Arena!', Description_Lang_esMX='Ha aparecido una bestia de silitista' WHERE ID=1725;
UPDATE dbc_areapoi SET Name_Lang_esMX='¡Gusano de Arena!', Description_Lang_esMX='Ha aparecido una bestia de silitista' WHERE ID=1726;
UPDATE dbc_areapoi SET Name_Lang_esMX='¡Gusano de Arena!', Description_Lang_esMX='Ha aparecido una bestia de silitista' WHERE ID=1727;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cueva de Barbaescamas', Description_Lang_esMX='' WHERE ID=1211;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento de los Mezclatornillos', Description_Lang_esMX='' WHERE ID=1150;
UPDATE dbc_areapoi SET Name_Lang_esMX='Poblado Sen''jin', Description_Lang_esMX='' WHERE ID=34;
UPDATE dbc_areapoi SET Name_Lang_esMX='Alto del Centinela', Description_Lang_esMX='' WHERE ID=1097;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aldea Cazasombras', Description_Lang_esMX='' WHERE ID=795;
UPDATE dbc_areapoi SET Name_Lang_esMX='Gruta Narácnida', Description_Lang_esMX='' WHERE ID=908;
UPDATE dbc_areapoi SET Name_Lang_esMX='Posada Reposo Umbrío', Description_Lang_esMX='' WHERE ID=1087;
UPDATE dbc_areapoi SET Name_Lang_esMX='Guarida de Shalzaru', Description_Lang_esMX='' WHERE ID=1187;
UPDATE dbc_areapoi SET Name_Lang_esMX='Santuario de Remulos', Description_Lang_esMX='' WHERE ID=1246;
UPDATE dbc_areapoi SET Name_Lang_esMX='Refugio Brisa de Plata', Description_Lang_esMX='' WHERE ID=1242;
UPDATE dbc_areapoi SET Name_Lang_esMX='Claro Ala de Plata', Description_Lang_esMX='' WHERE ID=1513;
UPDATE dbc_areapoi SET Name_Lang_esMX='Avanzada Ala de Plata', Description_Lang_esMX='' WHERE ID=1240;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cañón Sishir', Description_Lang_esMX='' WHERE ID=1227;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puesto del Hachazo', Description_Lang_esMX='' WHERE ID=1471;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Pezuña Quebrada', Description_Lang_esMX='' WHERE ID=1112;
UPDATE dbc_areapoi SET Name_Lang_esMX='Punta de Corzocelada', Description_Lang_esMX='' WHERE ID=1688;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ruinas Quebrantarrocas', Description_Lang_esMX='' WHERE ID=1093;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cima del Espolón', Description_Lang_esMX='' WHERE ID=44;
UPDATE dbc_areapoi SET Name_Lang_esMX='Túmulo de Tempestira', Description_Lang_esMX='' WHERE ID=1248;
UPDATE dbc_areapoi SET Name_Lang_esMX='Refugio Roca del Sol', Description_Lang_esMX='' WHERE ID=701;
UPDATE dbc_areapoi SET Name_Lang_esMX='Mansión Cienaluz', Description_Lang_esMX='' WHERE ID=1098;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ruinas de Tahonda', Description_Lang_esMX='' WHERE ID=1116;
UPDATE dbc_areapoi SET Name_Lang_esMX='Punta Talrendis', Description_Lang_esMX='' WHERE ID=1215;
UPDATE dbc_areapoi SET Name_Lang_esMX='Templo de Zin-Malor', Description_Lang_esMX='' WHERE ID=707;
UPDATE dbc_areapoi SET Name_Lang_esMX='Thalanaar', Description_Lang_esMX='' WHERE ID=45;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Grieta', Description_Lang_esMX='' WHERE ID=912;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Cruce', Description_Lang_esMX='' WHERE ID=35;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Cubil', Description_Lang_esMX='' WHERE ID=32;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Túmulo de Dor''danil', Description_Lang_esMX='' WHERE ID=1241;
UPDATE dbc_areapoi SET Name_Lang_esMX='Las Ruinas de Kel''Theril', Description_Lang_esMX='' WHERE ID=1213;
UPDATE dbc_areapoi SET Name_Lang_esMX='Las Ruinas de Ordil''Aran', Description_Lang_esMX='' WHERE ID=1232;
UPDATE dbc_areapoi SET Name_Lang_esMX='Excavación Oximelena', Description_Lang_esMX='' WHERE ID=1111;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Pilar de la Ascensión', Description_Lang_esMX='' WHERE ID=1472;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Cubil del Espolón', Description_Lang_esMX='' WHERE ID=1231;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Paso del Espolón', Description_Lang_esMX='' WHERE ID=1230;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Paso del Espolón', Description_Lang_esMX='' WHERE ID=1245;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Hueco Perdido', Description_Lang_esMX='' WHERE ID=1113;
UPDATE dbc_areapoi SET Name_Lang_esMX='Isla Theramore', Description_Lang_esMX='' WHERE ID=791;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cima del Trueno', Description_Lang_esMX='' WHERE ID=29;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cala Furiamarea', Description_Lang_esMX='' WHERE ID=1092;
UPDATE dbc_areapoi SET Name_Lang_esMX='Bastión Fauces de Madera', Description_Lang_esMX='' WHERE ID=1212;
UPDATE dbc_areapoi SET Name_Lang_esMX='Bastión Fauces de Madera', Description_Lang_esMX='' WHERE ID=1218;
UPDATE dbc_areapoi SET Name_Lang_esMX='Granja Tor''kren', Description_Lang_esMX='' WHERE ID=929;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Crepúsculo', Description_Lang_esMX='' WHERE ID=1687;
UPDATE dbc_areapoi SET Name_Lang_esMX='Avanzada Crepúsculo', Description_Lang_esMX='' WHERE ID=1173;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puesto Crepúsculo', Description_Lang_esMX='' WHERE ID=1172;
UPDATE dbc_areapoi SET Name_Lang_esMX='Paseo Crepúsculo', Description_Lang_esMX='' WHERE ID=1689;
UPDATE dbc_areapoi SET Name_Lang_esMX='Uldum', Description_Lang_esMX='' WHERE ID=1107;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ataque enemigo', Description_Lang_esMX='Cuna del Invierno' WHERE ID=1696;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ataque enemigo', Description_Lang_esMX='Azshara' WHERE ID=1697;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ataque enemigo', Description_Lang_esMX='Desierto de Tanaris' WHERE ID=1700;
UPDATE dbc_areapoi SET Name_Lang_esMX='Valle de los Huesos', Description_Lang_esMX='' WHERE ID=1151;
UPDATE dbc_areapoi SET Name_Lang_esMX='Sosiego del Valor', Description_Lang_esMX='' WHERE ID=1567;
UPDATE dbc_areapoi SET Name_Lang_esMX='Mina Ventura y Cía.', Description_Lang_esMX='' WHERE ID=1047;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cuevas de los Lamentos', Description_Lang_esMX='' WHERE ID=1068;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campo de trabajos forzados Grito de Guerra', Description_Lang_esMX='' WHERE ID=1268;
UPDATE dbc_areapoi SET Name_Lang_esMX='Playa Baile de las Olas', Description_Lang_esMX='' WHERE ID=1106;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cráter de la Comadreja', Description_Lang_esMX='' WHERE ID=1115;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento del Tramo Blanco', Description_Lang_esMX='' WHERE ID=767;
UPDATE dbc_areapoi SET Name_Lang_esMX='Río Culebra', Description_Lang_esMX='' WHERE ID=1049;
UPDATE dbc_areapoi SET Name_Lang_esMX='Mina Cortaviento', Description_Lang_esMX='' WHERE ID=1229;
UPDATE dbc_areapoi SET Name_Lang_esMX='Guarida de los Zarpaleña', Description_Lang_esMX='' WHERE ID=1475;
UPDATE dbc_areapoi SET Name_Lang_esMX='Colinas Zarpaleña', Description_Lang_esMX='' WHERE ID=1174;
UPDATE dbc_areapoi SET Name_Lang_esMX='Xavian', Description_Lang_esMX='' WHERE ID=1237;
UPDATE dbc_areapoi SET Name_Lang_esMX='Avanzada de Zoram''gar', Description_Lang_esMX='' WHERE ID=1234;
UPDATE dbc_areapoi SET Name_Lang_esMX='Mina Dentefrío', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1102;
UPDATE dbc_areapoi SET Name_Lang_esMX='Mina Dentefrío', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1358;
UPDATE dbc_areapoi SET Name_Lang_esMX='Mina Dentefrío', Description_Lang_esMX='Bajo el control de los kóbolds' WHERE ID=1359;
UPDATE dbc_areapoi SET Name_Lang_esMX='Dun Baldar', Description_Lang_esMX='' WHERE ID=1328;
UPDATE dbc_areapoi SET Name_Lang_esMX='Búnker Norte de Dun Baldar', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1250;
UPDATE dbc_areapoi SET Name_Lang_esMX='Búnker Norte de Dun Baldar', Description_Lang_esMX='Destruido' WHERE ID=1352;
UPDATE dbc_areapoi SET Name_Lang_esMX='Búnker Norte de Dun Baldar', Description_Lang_esMX='En conflicto' WHERE ID=1353;
UPDATE dbc_areapoi SET Name_Lang_esMX='Búnker Norte de Dun Baldar', Description_Lang_esMX='En conflicto' WHERE ID=1354;
UPDATE dbc_areapoi SET Name_Lang_esMX='Búnker Sur de Dun Baldar', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1249;
UPDATE dbc_areapoi SET Name_Lang_esMX='Búnker Sur de Dun Baldar', Description_Lang_esMX='Destruido' WHERE ID=1355;
UPDATE dbc_areapoi SET Name_Lang_esMX='Búnker Sur de Dun Baldar', Description_Lang_esMX='En conflicto' WHERE ID=1356;
UPDATE dbc_areapoi SET Name_Lang_esMX='Búnker Sur de Dun Baldar', Description_Lang_esMX='En conflicto' WHERE ID=1357;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre Lobo Gélido Este', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1255;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre Lobo Gélido Este', Description_Lang_esMX='Destruida' WHERE ID=1362;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre Lobo Gélido Este', Description_Lang_esMX='En conflicto' WHERE ID=1363;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre Lobo Gélido Este', Description_Lang_esMX='En conflicto' WHERE ID=1364;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Lobo Gélido', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1210;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Lobo Gélido', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1368;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Lobo Gélido', Description_Lang_esMX='En conflicto' WHERE ID=1369;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Lobo Gélido', Description_Lang_esMX='En conflicto' WHERE ID=1370;
UPDATE dbc_areapoi SET Name_Lang_esMX='Bastión Lobo Gélido', Description_Lang_esMX='' WHERE ID=1103;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puesto de auxilio Lobo Gélido', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1351;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puesto de auxilio Lobo Gélido', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1371;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puesto de auxilio Lobo Gélido', Description_Lang_esMX='En conflicto' WHERE ID=1372;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puesto de auxilio Lobo Gélido', Description_Lang_esMX='En conflicto' WHERE ID=1373;
UPDATE dbc_areapoi SET Name_Lang_esMX='Baluarte Sangrehielo', Description_Lang_esMX='' WHERE ID=1101;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Sangrehielo', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1349;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Sangrehielo', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1374;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Sangrehielo', Description_Lang_esMX='En conflicto' WHERE ID=1375;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Sangrehielo', Description_Lang_esMX='En conflicto' WHERE ID=1376;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre Sangrehielo', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1252;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre Sangrehielo', Description_Lang_esMX='Destruida' WHERE ID=1377;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre Sangrehielo', Description_Lang_esMX='En conflicto' WHERE ID=1378;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre Sangrehielo', Description_Lang_esMX='En conflicto' WHERE ID=1379;
UPDATE dbc_areapoi SET Name_Lang_esMX='Búnker Ala Gélida', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1251;
UPDATE dbc_areapoi SET Name_Lang_esMX='Búnker Ala Gélida', Description_Lang_esMX='Destruido' WHERE ID=1380;
UPDATE dbc_areapoi SET Name_Lang_esMX='Búnker Ala Gélida', Description_Lang_esMX='En conflicto' WHERE ID=1381;
UPDATE dbc_areapoi SET Name_Lang_esMX='Búnker Ala Gélida', Description_Lang_esMX='En conflicto' WHERE ID=1382;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cueva Ala Gélida', Description_Lang_esMX='' WHERE ID=1569;
UPDATE dbc_areapoi SET Name_Lang_esMX='Mina Ferrohondo', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1099;
UPDATE dbc_areapoi SET Name_Lang_esMX='Mina Ferrohondo', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1383;
UPDATE dbc_areapoi SET Name_Lang_esMX='Mina Ferrohondo', Description_Lang_esMX='Bajo el control de los troggs' WHERE ID=1384;
UPDATE dbc_areapoi SET Name_Lang_esMX='Pre-alliance POI test', Description_Lang_esMX='' WHERE ID=1550;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Avalancha', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1209;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Avalancha', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1386;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Avalancha', Description_Lang_esMX='En conflicto' WHERE ID=1387;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Avalancha', Description_Lang_esMX='En conflicto' WHERE ID=1388;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Avalancha', Description_Lang_esMX='No controlado' WHERE ID=1682;
UPDATE dbc_areapoi SET Name_Lang_esMX='Búnker Piedrahogar', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1347;
UPDATE dbc_areapoi SET Name_Lang_esMX='Búnker Piedrahogar', Description_Lang_esMX='Destruido' WHERE ID=1389;
UPDATE dbc_areapoi SET Name_Lang_esMX='Búnker Piedrahogar', Description_Lang_esMX='En conflicto' WHERE ID=1390;
UPDATE dbc_areapoi SET Name_Lang_esMX='Búnker Piedrahogar', Description_Lang_esMX='En conflicto' WHERE ID=1391;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Piedrahogar', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1350;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Piedrahogar', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1392;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Piedrahogar', Description_Lang_esMX='En conflicto' WHERE ID=1393;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Piedrahogar', Description_Lang_esMX='En conflicto' WHERE ID=1394;
UPDATE dbc_areapoi SET Name_Lang_esMX='Avanzada Piedrahogar', Description_Lang_esMX='' WHERE ID=1100;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puesto de auxilio Pico Tormenta', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1348;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puesto de auxilio Pico Tormenta', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1395;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puesto de auxilio Pico Tormenta', Description_Lang_esMX='En conflicto' WHERE ID=1396;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puesto de auxilio Pico Tormenta', Description_Lang_esMX='En conflicto' WHERE ID=1397;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Pico Tormenta', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1208;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Pico Tormenta', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1398;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Pico Tormenta', Description_Lang_esMX='En conflicto' WHERE ID=1399;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio Pico Tormenta', Description_Lang_esMX='En conflicto' WHERE ID=1400;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Punta', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1254;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Punta', Description_Lang_esMX='Destruida' WHERE ID=1405;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Punta', Description_Lang_esMX='En conflicto' WHERE ID=1406;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Punta', Description_Lang_esMX='En conflicto' WHERE ID=1407;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre Lobo Gélido Oeste', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1527;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre Lobo Gélido Oeste', Description_Lang_esMX='Destruida' WHERE ID=1528;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre Lobo Gélido Oeste', Description_Lang_esMX='En conflicto' WHERE ID=1529;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre Lobo Gélido Oeste', Description_Lang_esMX='En conflicto' WHERE ID=1530;
UPDATE dbc_areapoi SET Name_Lang_esMX='Caverna Zarpa Salvaje', Description_Lang_esMX='' WHERE ID=1568;
UPDATE dbc_areapoi SET Name_Lang_esMX='Alianza', Description_Lang_esMX='' WHERE ID=20;
UPDATE dbc_areapoi SET Name_Lang_esMX='Horda', Description_Lang_esMX='' WHERE ID=21;
UPDATE dbc_areapoi SET Name_Lang_esMX='Herrería', Description_Lang_esMX='No controlada' WHERE ID=1614;
UPDATE dbc_areapoi SET Name_Lang_esMX='Herrería', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1615;
UPDATE dbc_areapoi SET Name_Lang_esMX='Herrería', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1616;
UPDATE dbc_areapoi SET Name_Lang_esMX='Herrería', Description_Lang_esMX='En conflicto' WHERE ID=1617;
UPDATE dbc_areapoi SET Name_Lang_esMX='Herrería', Description_Lang_esMX='En conflicto' WHERE ID=1618;
UPDATE dbc_areapoi SET Name_Lang_esMX='Granja', Description_Lang_esMX='No controlada' WHERE ID=1629;
UPDATE dbc_areapoi SET Name_Lang_esMX='Granja', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1630;
UPDATE dbc_areapoi SET Name_Lang_esMX='Granja', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1631;
UPDATE dbc_areapoi SET Name_Lang_esMX='Granja', Description_Lang_esMX='En conflicto' WHERE ID=1632;
UPDATE dbc_areapoi SET Name_Lang_esMX='Granja', Description_Lang_esMX='En conflicto' WHERE ID=1633;
UPDATE dbc_areapoi SET Name_Lang_esMX='Mina de Oro', Description_Lang_esMX='No controlada' WHERE ID=1624;
UPDATE dbc_areapoi SET Name_Lang_esMX='Mina de Oro', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1625;
UPDATE dbc_areapoi SET Name_Lang_esMX='Mina de Oro', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1626;
UPDATE dbc_areapoi SET Name_Lang_esMX='Mina de Oro', Description_Lang_esMX='En conflicto' WHERE ID=1627;
UPDATE dbc_areapoi SET Name_Lang_esMX='Mina de Oro', Description_Lang_esMX='En conflicto' WHERE ID=1628;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aserradero', Description_Lang_esMX='No controlado' WHERE ID=1619;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aserradero', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1620;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aserradero', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1621;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aserradero', Description_Lang_esMX='En conflicto' WHERE ID=1622;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aserradero', Description_Lang_esMX='En conflicto' WHERE ID=1623;
UPDATE dbc_areapoi SET Name_Lang_esMX='Establos', Description_Lang_esMX='No controlados' WHERE ID=1609;
UPDATE dbc_areapoi SET Name_Lang_esMX='Establos', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1610;
UPDATE dbc_areapoi SET Name_Lang_esMX='Establos', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1611;
UPDATE dbc_areapoi SET Name_Lang_esMX='Establos', Description_Lang_esMX='En conflicto' WHERE ID=1612;
UPDATE dbc_areapoi SET Name_Lang_esMX='Establos', Description_Lang_esMX='En conflicto' WHERE ID=1613;
UPDATE dbc_areapoi SET Name_Lang_esMX='Bastión Allerian', Description_Lang_esMX='' WHERE ID=2074;
UPDATE dbc_areapoi SET Name_Lang_esMX='Explorador de campo de la Alianza', Description_Lang_esMX='' WHERE ID=1904;
UPDATE dbc_areapoi SET Name_Lang_esMX='Explorador de campo de la Alianza', Description_Lang_esMX='' WHERE ID=1905;
UPDATE dbc_areapoi SET Name_Lang_esMX='Altar de Sha''tar', Description_Lang_esMX='' WHERE ID=2078;
UPDATE dbc_areapoi SET Name_Lang_esMX='Catacumbas Amani', Description_Lang_esMX='' WHERE ID=1809;
UPDATE dbc_areapoi SET Name_Lang_esMX='Paso de Amani', Description_Lang_esMX='' WHERE ID=1811;
UPDATE dbc_areapoi SET Name_Lang_esMX='Paso de Redámbar', Description_Lang_esMX='' WHERE ID=1837;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campos Ammen', Description_Lang_esMX='' WHERE ID=1799;
UPDATE dbc_areapoi SET Name_Lang_esMX='An''daroth', Description_Lang_esMX='' WHERE ID=1819;
UPDATE dbc_areapoi SET Name_Lang_esMX='An''owyn', Description_Lang_esMX='' WHERE ID=2006;
UPDATE dbc_areapoi SET Name_Lang_esMX='An''telas', Description_Lang_esMX='' WHERE ID=1808;
UPDATE dbc_areapoi SET Name_Lang_esMX='Dominios Andilien', Description_Lang_esMX='' WHERE ID=1812;
UPDATE dbc_areapoi SET Name_Lang_esMX='Área 52', Description_Lang_esMX='' WHERE ID=2071;
UPDATE dbc_areapoi SET Name_Lang_esMX='Axxarien', Description_Lang_esMX='' WHERE ID=1834;
UPDATE dbc_areapoi SET Name_Lang_esMX='Avanzada Azur', Description_Lang_esMX='' WHERE ID=1784;
UPDATE dbc_areapoi SET Name_Lang_esMX='Bosquespada', Description_Lang_esMX='' WHERE ID=1830;
UPDATE dbc_areapoi SET Name_Lang_esMX='Zigurat Sangrante', Description_Lang_esMX='' WHERE ID=1814;
UPDATE dbc_areapoi SET Name_Lang_esMX='Avanzada de Sangre', Description_Lang_esMX='' WHERE ID=1940;
UPDATE dbc_areapoi SET Name_Lang_esMX='Enclave Punta Torcida', Description_Lang_esMX='' WHERE ID=1840;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aldea Brazolanudo', Description_Lang_esMX='' WHERE ID=1780;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cerro Tábido', Description_Lang_esMX='Neutral' WHERE ID=1844;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cerro Tábido', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1845;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cerro Tábido', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1846;
UPDATE dbc_areapoi SET Name_Lang_esMX='Refugio Cenarion', Description_Lang_esMX='' WHERE ID=2062;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puesto del Clan', Description_Lang_esMX='' WHERE ID=1722;
UPDATE dbc_areapoi SET Name_Lang_esMX='Reserva Colmillo Torcido', Description_Lang_esMX='' WHERE ID=2021;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cosmotirón', Description_Lang_esMX='' WHERE ID=2072;
UPDATE dbc_areapoi SET Name_Lang_esMX='Lugar del Accidente', Description_Lang_esMX='' WHERE ID=1795;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aguja de la Estrella del Alba', Description_Lang_esMX='' WHERE ID=1804;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ciudad de la Muerte', Description_Lang_esMX='' WHERE ID=1711;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cubil de Haal''esh', Description_Lang_esMX='' WHERE ID=1719;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aguja Ocaso Marchito', Description_Lang_esMX='' WHERE ID=2018;
UPDATE dbc_areapoi SET Name_Lang_esMX='Baliza del Este', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1901;
UPDATE dbc_areapoi SET Name_Lang_esMX='Baliza del Este', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1902;
UPDATE dbc_areapoi SET Name_Lang_esMX='Baliza del Este', Description_Lang_esMX='' WHERE ID=1903;
UPDATE dbc_areapoi SET Name_Lang_esMX='Sagrario del Este', Description_Lang_esMX='' WHERE ID=1822;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Claro de Ascuas', Description_Lang_esMX='' WHERE ID=1792;
UPDATE dbc_areapoi SET Name_Lang_esMX='Soto Eterno', Description_Lang_esMX='' WHERE ID=2068;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aldea Brisa Pura', Description_Lang_esMX='' WHERE ID=1709;
UPDATE dbc_areapoi SET Name_Lang_esMX='Avanzada del Halcón', Description_Lang_esMX='' WHERE ID=1720;
UPDATE dbc_areapoi SET Name_Lang_esMX='Plaza Alalcón', Description_Lang_esMX='' WHERE ID=1705;
UPDATE dbc_areapoi SET Name_Lang_esMX='Plaza Alalcón, instructor de paladines', Description_Lang_esMX='' WHERE ID=1999;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Retiro del Errante', Description_Lang_esMX='' WHERE ID=1710;
UPDATE dbc_areapoi SET Name_Lang_esMX='Enclave del Errante', Description_Lang_esMX='' WHERE ID=1805;
UPDATE dbc_areapoi SET Name_Lang_esMX='Garadar', Description_Lang_esMX='' WHERE ID=2064;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento de Geezle', Description_Lang_esMX='' WHERE ID=1783;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aldea Bruma Dorada', Description_Lang_esMX='' WHERE ID=1818;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Ensenada Dorada', Description_Lang_esMX='' WHERE ID=2015;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Ensenada Dorada', Description_Lang_esMX='' WHERE ID=2019;
UPDATE dbc_areapoi SET Name_Lang_esMX='Halaa', Description_Lang_esMX='' WHERE ID=1920;
UPDATE dbc_areapoi SET Name_Lang_esMX='Halaa', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1921;
UPDATE dbc_areapoi SET Name_Lang_esMX='Halaa', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1922;
UPDATE dbc_areapoi SET Name_Lang_esMX='Halaa', Description_Lang_esMX='' WHERE ID=1923;
UPDATE dbc_areapoi SET Name_Lang_esMX='Halaa', Description_Lang_esMX='' WHERE ID=1924;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ciudadela del Fuego Infernal', Description_Lang_esMX='' WHERE ID=1718;
UPDATE dbc_areapoi SET Name_Lang_esMX='Bastión del Honor', Description_Lang_esMX='' WHERE ID=1714;
UPDATE dbc_areapoi SET Name_Lang_esMX='Explorador de campo de la Horda', Description_Lang_esMX='' WHERE ID=1906;
UPDATE dbc_areapoi SET Name_Lang_esMX='Explorador de campo de la Horda', Description_Lang_esMX='' WHERE ID=1907;
UPDATE dbc_areapoi SET Name_Lang_esMX='Zigurat Aullante', Description_Lang_esMX='' WHERE ID=1813;
UPDATE dbc_areapoi SET Name_Lang_esMX='Restos del Arca', Description_Lang_esMX='' WHERE ID=1789;
UPDATE dbc_areapoi SET Name_Lang_esMX='Túmulo Lunala', Description_Lang_esMX='' WHERE ID=1800;
UPDATE dbc_areapoi SET Name_Lang_esMX='Nazzivian', Description_Lang_esMX='' WHERE ID=1833;
UPDATE dbc_areapoi SET Name_Lang_esMX='Matorral Cubrebosque', Description_Lang_esMX='' WHERE ID=1798;
UPDATE dbc_areapoi SET Name_Lang_esMX='Sagrario del Norte', Description_Lang_esMX='' WHERE ID=1825;
UPDATE dbc_areapoi SET Name_Lang_esMX='Desembarco de Odesyus', Description_Lang_esMX='' WHERE ID=1793;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ogri''la', Description_Lang_esMX='' WHERE ID=2080;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerto Orebor', Description_Lang_esMX='' WHERE ID=2060;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Maraña de Cápsulas', Description_Lang_esMX='' WHERE ID=1781;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Cementerio de Cápsulas', Description_Lang_esMX='' WHERE ID=1782;
UPDATE dbc_areapoi SET Name_Lang_esMX='Pozas de Aggonar', Description_Lang_esMX='' WHERE ID=1723;
UPDATE dbc_areapoi SET Name_Lang_esMX='Loma Plumira', Description_Lang_esMX='' WHERE ID=1838;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ruinas de Loreth''Aran', Description_Lang_esMX='' WHERE ID=1832;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ruinas de Sha''naar', Description_Lang_esMX='' WHERE ID=1721;
UPDATE dbc_areapoi SET Name_Lang_esMX='Refugio de Saltheril', Description_Lang_esMX='' WHERE ID=1823;
UPDATE dbc_areapoi SET Name_Lang_esMX='Sagrario de la Luna', Description_Lang_esMX='' WHERE ID=1817;
UPDATE dbc_areapoi SET Name_Lang_esMX='Sagrario de las Estrellas', Description_Lang_esMX='' WHERE ID=2077;
UPDATE dbc_areapoi SET Name_Lang_esMX='Sagrario del Sol', Description_Lang_esMX='' WHERE ID=1807;
UPDATE dbc_areapoi SET Name_Lang_esMX='Lago Serpiente', Description_Lang_esMX='' WHERE ID=2022;
UPDATE dbc_areapoi SET Name_Lang_esMX='Lago Serpiente', Description_Lang_esMX='' WHERE ID=2023;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cresta de las Sombras', Description_Lang_esMX='' WHERE ID=1796;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aldea Sombraluna', Description_Lang_esMX='' WHERE ID=2075;
UPDATE dbc_areapoi SET Name_Lang_esMX='Isla Shalandris', Description_Lang_esMX='' WHERE ID=2005;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ciudad de Shattrath', Description_Lang_esMX='' WHERE ID=1961;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Costa de Cieno', Description_Lang_esMX='' WHERE ID=1787;
UPDATE dbc_areapoi SET Name_Lang_esMX='Lago Lineargenta', Description_Lang_esMX='' WHERE ID=1797;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ciudad de Lunargenta', Description_Lang_esMX='' WHERE ID=1704;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Espíritu', Description_Lang_esMX='' WHERE ID=1925;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Espíritu', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1926;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Espíritu', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1927;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Espíritu', Description_Lang_esMX='' WHERE ID=1928;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Espíritu', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1929;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Espíritu', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1930;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Espíritu', Description_Lang_esMX='' WHERE ID=1931;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Espíritu', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1932;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Espíritu', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1933;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Espíritu', Description_Lang_esMX='' WHERE ID=1934;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Espíritu', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1935;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Espíritu', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1936;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Espíritu', Description_Lang_esMX='' WHERE ID=1937;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Espíritu', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1938;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre del Espíritu', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1939;
UPDATE dbc_areapoi SET Name_Lang_esMX='Esporaggar', Description_Lang_esMX='' WHERE ID=2059;
UPDATE dbc_areapoi SET Name_Lang_esMX='Bastión Semprepino', Description_Lang_esMX='' WHERE ID=1788;
UPDATE dbc_areapoi SET Name_Lang_esMX='Charca Plácido Susurro', Description_Lang_esMX='' WHERE ID=1826;
UPDATE dbc_areapoi SET Name_Lang_esMX='Bastión Rompepedras', Description_Lang_esMX='' WHERE ID=2073;
UPDATE dbc_areapoi SET Name_Lang_esMX='Arsenal de Tramo del Sol', Description_Lang_esMX='En manos enemigas' WHERE ID=2098;
UPDATE dbc_areapoi SET Name_Lang_esMX='Arsenal de Tramo del Sol', Description_Lang_esMX='Ofensiva Sol Devastado' WHERE ID=2099;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerto de Tramo del Sol', Description_Lang_esMX='En manos enemigas' WHERE ID=2100;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerto de Tramo del Sol', Description_Lang_esMX='Ofensiva Sol Devastado' WHERE ID=2101;
UPDATE dbc_areapoi SET Name_Lang_esMX='Sagrario de Tramo del Sol', Description_Lang_esMX='En manos enemigas' WHERE ID=2096;
UPDATE dbc_areapoi SET Name_Lang_esMX='Sagrario de Tramo del Sol', Description_Lang_esMX='Ofensiva Sol Devastado' WHERE ID=2097;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aldea Corona del Sol', Description_Lang_esMX='' WHERE ID=1802;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fondeadero Vela del Sol', Description_Lang_esMX='' WHERE ID=1708;
UPDATE dbc_areapoi SET Name_Lang_esMX='Isla del Caminante del Sol', Description_Lang_esMX='' WHERE ID=1706;
UPDATE dbc_areapoi SET Name_Lang_esMX='Avanzada Rata del Pantano', Description_Lang_esMX='' WHERE ID=2063;
UPDATE dbc_areapoi SET Name_Lang_esMX='Sylvanaar', Description_Lang_esMX='' WHERE ID=2066;
UPDATE dbc_areapoi SET Name_Lang_esMX='Alto de la Garra', Description_Lang_esMX='' WHERE ID=1839;
UPDATE dbc_areapoi SET Name_Lang_esMX='Telaar', Description_Lang_esMX='' WHERE ID=2065;
UPDATE dbc_areapoi SET Name_Lang_esMX='Telredor', Description_Lang_esMX='' WHERE ID=2061;
UPDATE dbc_areapoi SET Name_Lang_esMX='Templo de Telhamat', Description_Lang_esMX='' WHERE ID=2069;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Crionúcleo', Description_Lang_esMX='' WHERE ID=1828;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Cicatriz Muerta', Description_Lang_esMX='' WHERE ID=2016;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Cicatriz Muerta', Description_Lang_esMX='' WHERE ID=2020;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Exodar', Description_Lang_esMX='' WHERE ID=1785;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Charca Hedionda', Description_Lang_esMX='' WHERE ID=1835;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Arrecife Oculto', Description_Lang_esMX='' WHERE ID=1836;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Dominancia', Description_Lang_esMX='Neutral' WHERE ID=1841;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Dominancia', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1842;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Dominancia', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1843;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Arboleda Sagrada', Description_Lang_esMX='' WHERE ID=1790;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Estadium', Description_Lang_esMX='Neutral' WHERE ID=1847;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Estadium', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1848;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Estadium', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1849;
UPDATE dbc_areapoi SET Name_Lang_esMX='Los Peldaños del Destino', Description_Lang_esMX='' WHERE ID=1716;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Flecha de la Tormenta', Description_Lang_esMX='' WHERE ID=2070;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Aguja del Sol', Description_Lang_esMX='' WHERE ID=1707;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Espiral Vectorial', Description_Lang_esMX='' WHERE ID=1827;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Pistón de Distorsión', Description_Lang_esMX='' WHERE ID=1829;
UPDATE dbc_areapoi SET Name_Lang_esMX='Thrallmar', Description_Lang_esMX='' WHERE ID=1715;
UPDATE dbc_areapoi SET Name_Lang_esMX='Trono de Kil''Jaeden', Description_Lang_esMX='' WHERE ID=1717;
UPDATE dbc_areapoi SET Name_Lang_esMX='Bastión Señor del Trueno', Description_Lang_esMX='' WHERE ID=2067;
UPDATE dbc_areapoi SET Name_Lang_esMX='Caballería de Thuron', Description_Lang_esMX='' WHERE ID=2017;
UPDATE dbc_areapoi SET Name_Lang_esMX='Hoya de la Marea', Description_Lang_esMX='' WHERE ID=1801;
UPDATE dbc_areapoi SET Name_Lang_esMX='Tor''Watha', Description_Lang_esMX='' WHERE ID=1820;
UPDATE dbc_areapoi SET Name_Lang_esMX='Estación de Toshley', Description_Lang_esMX='' WHERE ID=2034;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cala del Traidor', Description_Lang_esMX='' WHERE ID=1794;
UPDATE dbc_areapoi SET Name_Lang_esMX='Tranquillien', Description_Lang_esMX='' WHERE ID=1713;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio de las Agujas Gemelas', Description_Lang_esMX='' WHERE ID=1897;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio de las Agujas Gemelas', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1898;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio de las Agujas Gemelas', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1899;
UPDATE dbc_areapoi SET Name_Lang_esMX='Lago Umbropantano', Description_Lang_esMX='' WHERE ID=2024;
UPDATE dbc_areapoi SET Name_Lang_esMX='Lago Umbropantano', Description_Lang_esMX='' WHERE ID=2025;
UPDATE dbc_areapoi SET Name_Lang_esMX='Minas Sondaluz', Description_Lang_esMX='' WHERE ID=1815;
UPDATE dbc_areapoi SET Name_Lang_esMX='Atracadero de Valaar', Description_Lang_esMX='' WHERE ID=1786;
UPDATE dbc_areapoi SET Name_Lang_esMX='Baliza del Oeste', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1894;
UPDATE dbc_areapoi SET Name_Lang_esMX='Baliza del Oeste', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1895;
UPDATE dbc_areapoi SET Name_Lang_esMX='Baliza del Oeste', Description_Lang_esMX='' WHERE ID=1896;
UPDATE dbc_areapoi SET Name_Lang_esMX='Sagrario del Oeste', Description_Lang_esMX='' WHERE ID=1824;
UPDATE dbc_areapoi SET Name_Lang_esMX='Bastión Martillo Salvaje', Description_Lang_esMX='' WHERE ID=2076;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cima Ventosalvaje', Description_Lang_esMX='' WHERE ID=1791;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aguja Brisaveloz', Description_Lang_esMX='' WHERE ID=1712;
UPDATE dbc_areapoi SET Name_Lang_esMX='Aldea Brisaveloz', Description_Lang_esMX='' WHERE ID=1816;
UPDATE dbc_areapoi SET Name_Lang_esMX='Guarida Escama de Cólera', Description_Lang_esMX='' WHERE ID=1831;
UPDATE dbc_areapoi SET Name_Lang_esMX='Punto Escama de Cólera', Description_Lang_esMX='' WHERE ID=1779;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Dracoleón', Description_Lang_esMX='No controlado' WHERE ID=1908;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Dracoleón', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1909;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Dracoleón', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1910;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Dracoleón', Description_Lang_esMX='No controlado' WHERE ID=1911;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Dracoleón', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1912;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Dracoleón', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1913;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Dracoleón', Description_Lang_esMX='No controlado' WHERE ID=1914;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Dracoleón', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1915;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Dracoleón', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1916;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Dracoleón', Description_Lang_esMX='No controlado' WHERE ID=1917;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Dracoleón', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1918;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Dracoleón', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1919;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Dracoleón', Description_Lang_esMX='No controlado' WHERE ID=1963;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Dracoleón', Description_Lang_esMX='No controlado' WHERE ID=1964;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Dracoleón', Description_Lang_esMX='No controlado' WHERE ID=1965;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Dracoleón', Description_Lang_esMX='No controlado' WHERE ID=1966;
UPDATE dbc_areapoi SET Name_Lang_esMX='Zabra''jin', Description_Lang_esMX='' WHERE ID=2058;
UPDATE dbc_areapoi SET Name_Lang_esMX='Zeb''Nowa', Description_Lang_esMX='' WHERE ID=1810;
UPDATE dbc_areapoi SET Name_Lang_esMX='Zeb''Sora', Description_Lang_esMX='' WHERE ID=1803;
UPDATE dbc_areapoi SET Name_Lang_esMX='Zeb''Tela', Description_Lang_esMX='' WHERE ID=1806;
UPDATE dbc_areapoi SET Name_Lang_esMX='Zeb''Watha', Description_Lang_esMX='' WHERE ID=1821;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de los Elfos de Sangre', Description_Lang_esMX='No controlada' WHERE ID=1941;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de los Elfos de Sangre', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1942;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de los Elfos de Sangre', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1943;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de los Elfos de Sangre', Description_Lang_esMX='En conflicto' WHERE ID=1959;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de los Elfos de Sangre', Description_Lang_esMX='En conflicto' WHERE ID=1960;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ruinas Draenei', Description_Lang_esMX='No controladas' WHERE ID=1950;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ruinas Draenei', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1951;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ruinas Draenei', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1952;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ruinas Draenei', Description_Lang_esMX='En conflicto' WHERE ID=1953;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ruinas Draenei', Description_Lang_esMX='En conflicto' WHERE ID=1954;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ruinas del Atracador Vil', Description_Lang_esMX='No controladas' WHERE ID=1944;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ruinas del Atracador Vil', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1945;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ruinas del Atracador Vil', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1946;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ruinas del Atracador Vil', Description_Lang_esMX='En conflicto' WHERE ID=1957;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ruinas del Atracador Vil', Description_Lang_esMX='En conflicto' WHERE ID=1958;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de los Magos', Description_Lang_esMX='No controlada' WHERE ID=1947;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de los Magos', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=1948;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de los Magos', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=1949;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de los Magos', Description_Lang_esMX='En conflicto' WHERE ID=1955;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de los Magos', Description_Lang_esMX='En conflicto' WHERE ID=1956;
UPDATE dbc_areapoi SET Name_Lang_esMX='Bandera de Tormenta Abisal', Description_Lang_esMX='No controlada' WHERE ID=1962;
UPDATE dbc_areapoi SET Name_Lang_esMX='Martillo de Agmar', Description_Lang_esMX='' WHERE ID=2301;
UPDATE dbc_areapoi SET Name_Lang_esMX='Refugio Pino Ámbar', Description_Lang_esMX='' WHERE ID=2311;
UPDATE dbc_areapoi SET Name_Lang_esMX='Avanzada Bor''gorok', Description_Lang_esMX='' WHERE ID=2308;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio del Templo Quebrado', Description_Lang_esMX='' WHERE ID=2266;
UPDATE dbc_areapoi SET Name_Lang_esMX='Taller de Vehículos del Templo Quebrado', Description_Lang_esMX='' WHERE ID=2153;
UPDATE dbc_areapoi SET Name_Lang_esMX='Poblado Brunnhildar', Description_Lang_esMX='' WHERE ID=2319;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Oneqwah', Description_Lang_esMX='' WHERE ID=2312;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Tunka''lo', Description_Lang_esMX='' WHERE ID=2318;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Pezuña Invernal', Description_Lang_esMX='' WHERE ID=2090;
UPDATE dbc_areapoi SET Name_Lang_esMX='Bastión de la Conquista', Description_Lang_esMX='' WHERE ID=2310;
UPDATE dbc_areapoi SET Name_Lang_esMX='Pináculo de los Cruzados', Description_Lang_esMX='' WHERE ID=2323;
UPDATE dbc_areapoi SET Name_Lang_esMX='Dalaran', Description_Lang_esMX='' WHERE ID=2317;
UPDATE dbc_areapoi SET Name_Lang_esMX='Ascenso de la Muerte', Description_Lang_esMX='' WHERE ID=2138;
UPDATE dbc_areapoi SET Name_Lang_esMX='Taller de vehículos Chispa Oriental', Description_Lang_esMX='' WHERE ID=2151;
UPDATE dbc_areapoi SET Name_Lang_esMX='Pista de Aterrizaje de Palanqueta', Description_Lang_esMX='' WHERE ID=2307;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Guardia en Llamas', Description_Lang_esMX='' WHERE ID=2143;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fuerte Vildervar', Description_Lang_esMX='' WHERE ID=2089;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio de la Fortaleza', Description_Lang_esMX='' WHERE ID=2268;
UPDATE dbc_areapoi SET Name_Lang_esMX='Taller de vehículos de la fortaleza (E)', Description_Lang_esMX='' WHERE ID=2149;
UPDATE dbc_areapoi SET Name_Lang_esMX='Taller de vehículos de la fortaleza (O)', Description_Lang_esMX='' WHERE ID=2150;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fuerte Escarcha', Description_Lang_esMX='' WHERE ID=2321;
UPDATE dbc_areapoi SET Name_Lang_esMX='Lugar del accidente de Grom''arsh', Description_Lang_esMX='' WHERE ID=2322;
UPDATE dbc_areapoi SET Name_Lang_esMX='K3', Description_Lang_esMX='' WHERE ID=2320;
UPDATE dbc_areapoi SET Name_Lang_esMX='Komawa', Description_Lang_esMX='' WHERE ID=2085;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerto Moa''ki', Description_Lang_esMX='' WHERE ID=2302;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento Base de Nesingwary', Description_Lang_esMX='' WHERE ID=2316;
UPDATE dbc_areapoi SET Name_Lang_esMX='Nuevo Agamand', Description_Lang_esMX='' WHERE ID=2088;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2199;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2200;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2201;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2203;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2205;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2206;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2207;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2208;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2209;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2210;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2211;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2212;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2213;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2214;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2215;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2216;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2217;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2218;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2219;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2220;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2221;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2247;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2248;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2249;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2250;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2251;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2252;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2253;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2254;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2255;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2256;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2257;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2258;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2259;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2260;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2261;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2262;
UPDATE dbc_areapoi SET Name_Lang_esMX='Actividad JcJ detectada', Description_Lang_esMX='' WHERE ID=2263;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Vista de las Sombras', Description_Lang_esMX='' WHERE ID=2141;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio del sureste', Description_Lang_esMX='' WHERE ID=2270;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio del suroeste', Description_Lang_esMX='' WHERE ID=2269;
UPDATE dbc_areapoi SET Name_Lang_esMX='Reposo Estelar', Description_Lang_esMX='' WHERE ID=2300;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio del Anillo Sumergido', Description_Lang_esMX='' WHERE ID=2265;
UPDATE dbc_areapoi SET Name_Lang_esMX='Taller de Vehículos del Anillo Sumergido', Description_Lang_esMX='' WHERE ID=2154;
UPDATE dbc_areapoi SET Name_Lang_esMX='Poblado Taunka''le', Description_Lang_esMX='' WHERE ID=2306;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Confín Argenta', Description_Lang_esMX='' WHERE ID=2314;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Cámara de las Sombras', Description_Lang_esMX='' WHERE ID=2139;
UPDATE dbc_areapoi SET Name_Lang_esMX='Unu''pe', Description_Lang_esMX='' WHERE ID=2305;
UPDATE dbc_areapoi SET Name_Lang_esMX='Valgarde', Description_Lang_esMX='' WHERE ID=2086;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fortaleza Denuedo', Description_Lang_esMX='' WHERE ID=2303;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campo Venganza', Description_Lang_esMX='' WHERE ID=2087;
UPDATE dbc_areapoi SET Name_Lang_esMX='Rencor Venenoso', Description_Lang_esMX='' WHERE ID=2299;
UPDATE dbc_areapoi SET Name_Lang_esMX='Bastión Grito de Guerra', Description_Lang_esMX='' WHERE ID=2304;
UPDATE dbc_areapoi SET Name_Lang_esMX='Campamento de la Brigada de los Páramos de Poniente', Description_Lang_esMX='' WHERE ID=2313;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fortaleza de la Guardia Oeste', Description_Lang_esMX='' WHERE ID=2084;
UPDATE dbc_areapoi SET Name_Lang_esMX='Taller de vehículos Chispa Occidental', Description_Lang_esMX='' WHERE ID=2152;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre Filoinvierno', Description_Lang_esMX='' WHERE ID=2142;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fortaleza de Hibergarde', Description_Lang_esMX='' WHERE ID=2309;
UPDATE dbc_areapoi SET Name_Lang_esMX='Conquista del Invierno', Description_Lang_esMX='Control de Conquista del Invierno' WHERE ID=2264;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2246;
UPDATE dbc_areapoi SET Name_Lang_esMX='Portón de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2229;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Fortaleza de Conquista del Invierno (NE)', Description_Lang_esMX='' WHERE ID=2146;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Fortaleza de Conquista del Invierno (NO)', Description_Lang_esMX='' WHERE ID=2147;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Fortaleza de Conquista del Invierno (SE)', Description_Lang_esMX='' WHERE ID=2145;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de la Fortaleza de Conquista del Invierno (SO)', Description_Lang_esMX='' WHERE ID=2144;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2222;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2223;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2224;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2225;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2226;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2227;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2228;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2230;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2231;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2232;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2233;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2234;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2235;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2236;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2237;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2238;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2239;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2240;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2241;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2242;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2243;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2244;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muralla de la Fortaleza de Conquista del Invierno', Description_Lang_esMX='' WHERE ID=2245;
UPDATE dbc_areapoi SET Name_Lang_esMX='Templo del Reposo del Dragón', Description_Lang_esMX='' WHERE ID=2298;
UPDATE dbc_areapoi SET Name_Lang_esMX='Zim''Torga', Description_Lang_esMX='' WHERE ID=2315;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Plaza de los Ancestros', Description_Lang_esMX='Puerta de la Plaza de los Ancestros' WHERE ID=2106;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Calle del Festival', Description_Lang_esMX='Puerta de la Calle del Festival' WHERE ID=2107;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fuente de la Plaza del Rey', Description_Lang_esMX='Fuente de la Plaza del Rey' WHERE ID=2109;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Fila del Mercado', Description_Lang_esMX='Puerta de la Fila del Mercado' WHERE ID=2108;
UPDATE dbc_areapoi SET Name_Lang_esMX='Concejo', Description_Lang_esMX='Concejo' WHERE ID=2105;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de Llamas', Description_Lang_esMX='Proporciona poder al Infierno de Mimiron' WHERE ID=2332;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de Escarcha', Description_Lang_esMX='Proporciona poder a la Furia de Hodir' WHERE ID=2333;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de Vida', Description_Lang_esMX='Proporciona poder al Resguardo de Freya' WHERE ID=2331;
UPDATE dbc_areapoi SET Name_Lang_esMX='Torre de Tormentas', Description_Lang_esMX='Proporciona poder al Martillo de Thorim' WHERE ID=2334;
UPDATE dbc_areapoi SET Name_Lang_esMX='Defensa de la Alianza', Description_Lang_esMX='' WHERE ID=2128;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cámara de Reliquias Antiguas', Description_Lang_esMX='' WHERE ID=2292;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio oriental', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=2129;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio oriental', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=2130;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta del Zafiro Azul', Description_Lang_esMX='' WHERE ID=2117;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Esmeralda Verde', Description_Lang_esMX='' WHERE ID=2120;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Amatista Púrpura', Description_Lang_esMX='' WHERE ID=2111;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta del Sol Rojo', Description_Lang_esMX='' WHERE ID=2114;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Luna Amarilla', Description_Lang_esMX='' WHERE ID=2135;
UPDATE dbc_areapoi SET Name_Lang_esMX='Defensa de la Horda', Description_Lang_esMX='' WHERE ID=2127;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio sur', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=2133;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio sur', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=2134;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Añublador', Description_Lang_esMX='Ofensiva de la Horda' WHERE ID=2125;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Portador de Ataúdes', Description_Lang_esMX='Ofensiva de la Horda' WHERE ID=2126;
UPDATE dbc_areapoi SET Name_Lang_esMX='El Rompescarcha', Description_Lang_esMX='Ofensiva de la Alianza' WHERE ID=2123;
UPDATE dbc_areapoi SET Name_Lang_esMX='La Doncella Grácil', Description_Lang_esMX='Ofensiva de la Alianza' WHERE ID=2124;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio occidental', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=2132;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cementerio occidental', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=2324;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Alianza', Description_Lang_esMX='Puerta Este' WHERE ID=2377;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Alianza', Description_Lang_esMX='Destruida' WHERE ID=2378;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Alianza', Description_Lang_esMX='Destruida' WHERE ID=2379;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Alianza', Description_Lang_esMX='Puerta Oeste' WHERE ID=2380;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Alianza', Description_Lang_esMX='Destruida' WHERE ID=2381;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Alianza', Description_Lang_esMX='Puerta Principal' WHERE ID=2382;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fortaleza de la Alianza', Description_Lang_esMX='No controlada' WHERE ID=2383;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fortaleza de la Alianza', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=2384;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fortaleza de la Alianza', Description_Lang_esMX='En conflicto' WHERE ID=2385;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fortaleza de la Alianza', Description_Lang_esMX='En conflicto' WHERE ID=2386;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fortaleza de la Alianza', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=2387;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muelles', Description_Lang_esMX='En conflicto' WHERE ID=2356;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muelles', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=2357;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muelles', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=2358;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muelles', Description_Lang_esMX='En conflicto' WHERE ID=2359;
UPDATE dbc_areapoi SET Name_Lang_esMX='Muelles', Description_Lang_esMX='No controlados' WHERE ID=2360;
UPDATE dbc_areapoi SET Name_Lang_esMX='Hangar', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=2350;
UPDATE dbc_areapoi SET Name_Lang_esMX='Hangar', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=2352;
UPDATE dbc_areapoi SET Name_Lang_esMX='Hangar', Description_Lang_esMX='En conflicto' WHERE ID=2353;
UPDATE dbc_areapoi SET Name_Lang_esMX='Hangar', Description_Lang_esMX='En conflicto' WHERE ID=2354;
UPDATE dbc_areapoi SET Name_Lang_esMX='Hangar', Description_Lang_esMX='No controlado' WHERE ID=2355;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Horda', Description_Lang_esMX='Puerta Principal' WHERE ID=2371;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Horda', Description_Lang_esMX='Destruida' WHERE ID=2372;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Horda', Description_Lang_esMX='Puerta Este' WHERE ID=2373;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Horda', Description_Lang_esMX='Destruida' WHERE ID=2374;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Horda', Description_Lang_esMX='Puerta Oeste' WHERE ID=2375;
UPDATE dbc_areapoi SET Name_Lang_esMX='Puerta de la Horda', Description_Lang_esMX='Destruida' WHERE ID=2376;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fortaleza de la Horda', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=2388;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fortaleza de la Horda', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=2389;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fortaleza de la Horda', Description_Lang_esMX='En conflicto' WHERE ID=2390;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fortaleza de la Horda', Description_Lang_esMX='En conflicto' WHERE ID=2391;
UPDATE dbc_areapoi SET Name_Lang_esMX='Fortaleza de la Horda', Description_Lang_esMX='No controlada' WHERE ID=2392;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cantera', Description_Lang_esMX='No controlada' WHERE ID=2361;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cantera', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=2362;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cantera', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=2363;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cantera', Description_Lang_esMX='En conflicto' WHERE ID=2364;
UPDATE dbc_areapoi SET Name_Lang_esMX='Cantera', Description_Lang_esMX='En conflicto' WHERE ID=2365;
UPDATE dbc_areapoi SET Name_Lang_esMX='Refinería', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=2366;
UPDATE dbc_areapoi SET Name_Lang_esMX='Refinería', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=2367;
UPDATE dbc_areapoi SET Name_Lang_esMX='Refinería', Description_Lang_esMX='En conflicto' WHERE ID=2368;
UPDATE dbc_areapoi SET Name_Lang_esMX='Refinería', Description_Lang_esMX='En conflicto' WHERE ID=2369;
UPDATE dbc_areapoi SET Name_Lang_esMX='Refinería', Description_Lang_esMX='No controlada' WHERE ID=2370;
UPDATE dbc_areapoi SET Name_Lang_esMX='Taller', Description_Lang_esMX='Bajo el control de la Alianza' WHERE ID=2345;
UPDATE dbc_areapoi SET Name_Lang_esMX='Taller', Description_Lang_esMX='Bajo el control de la Horda' WHERE ID=2346;
UPDATE dbc_areapoi SET Name_Lang_esMX='Taller', Description_Lang_esMX='En conflicto' WHERE ID=2347;
UPDATE dbc_areapoi SET Name_Lang_esMX='Taller', Description_Lang_esMX='En conflicto' WHERE ID=2348;
UPDATE dbc_areapoi SET Name_Lang_esMX='Taller', Description_Lang_esMX='No controlado' WHERE ID=2349;
