UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Yunque' WHERE ID=1;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Telar' WHERE ID=2;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Forja' WHERE ID=3;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Lumbre' WHERE ID=4;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Fragmentos de Myzrael' WHERE ID=5;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Pozo de agua de Pezuña Invernal' WHERE ID=6;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Pozo de agua de Tronacuerno' WHERE ID=7;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Pozo Ferocrín' WHERE ID=8;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Fuego tribal' WHERE ID=9;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Tienda de máquinas' WHERE ID=10;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Poza de la Luna de Cañada Umbría' WHERE ID=11;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Poza de la Luna de Aldea Brisa Estelar' WHERE ID=12;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Estanques de la Poza de la Luna de Arlithrien' WHERE ID=13;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Poza de la Luna del Claro del Oráculo' WHERE ID=14;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Aeropuerto de Ventura y Cía.' WHERE ID=15;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Vagón de Ventura y Cía. (azul)' WHERE ID=16;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Vagón de Ventura y Cía. (rojo)' WHERE ID=17;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Explosivos NG-5 (rojos)' WHERE ID=18;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Explosivos NG-5 (azules)' WHERE ID=19;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Llama de Uzel' WHERE ID=20;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Poza de la Luna de Vallefresno' WHERE ID=21;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Altar desgastado por el mar' WHERE ID=22;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Tubérculos cercanos' WHERE ID=23;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Círculo de invocación de Entrañas' WHERE ID=43;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Santuario del chamán' WHERE ID=63;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Círculo de invocación de Ventormenta' WHERE ID=83;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Círculo de invocación de los Baldíos' WHERE ID=103;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cascada de Lago Espejo' WHERE ID=123;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='El Cubil del Espolón' WHERE ID=143;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cascada Xavian' WHERE ID=163;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Piedra de Vínculo Exterior' WHERE ID=164;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Interrupción de falla de maná' WHERE ID=183;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Círculo de invocación de Orgrimmar' WHERE ID=203;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Fuente Escama de Cólera' WHERE ID=223;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Abrevadero de jabaespines' WHERE ID=224;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Pureza de agua - Argénteos' WHERE ID=225;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Fontana' WHERE ID=226;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Fuente del Templo de la Luna' WHERE ID=243;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Altar Jintha''Alor' WHERE ID=263;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Sentina de barco pirata' WHERE ID=264;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Monolito Equinex' WHERE ID=283;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Poblado Secacorteza' WHERE ID=303;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Altar Shadra''Alor' WHERE ID=304;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Orificio de hidratación de Vigía Penas de Arena' WHERE ID=323;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Piedras Garraodio' WHERE ID=343;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Guarida de Echeyakee' WHERE ID=363;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='El Árbol Muerto' WHERE ID=383;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Helipuerto improvisado' WHERE ID=403;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Círculo de Aquamentas' WHERE ID=423;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Sagrario del Dios Caído' WHERE ID=424;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='el primer pozo de las mareas' WHERE ID=443;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='la segunda poza de las mareas' WHERE ID=444;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='la tercera poza de las mareas' WHERE ID=445;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='la cuarta poza de las mareas' WHERE ID=446;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Criadero de la colmena Gorishi' WHERE ID=463;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Miblon Gruñediente' WHERE ID=483;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cementerio de Gadgetzan' WHERE ID=503;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='las ruinas del bosque de Troncoferro' WHERE ID=523;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Forja Negra' WHERE ID=543;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cráter Golakka' WHERE ID=563;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Tumba de los Siete' WHERE ID=583;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Roca llana de Un''Goro' WHERE ID=603;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Corteza conservada de trillanodonte' WHERE ID=604;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Yunque Negro' WHERE ID=623;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cristal silítido Gorishi' WHERE ID=643;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Poza de la Luna corrompida' WHERE ID=644;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Laboratorio de alquimia' WHERE ID=663;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Sello de ascensión sin forjar' WHERE ID=683;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Poza de la Luna de Auberdine' WHERE ID=703;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Fogata norte de los fúrbolg Bosque Negro' WHERE ID=704;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cascada del Río Fonroca' WHERE ID=705;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Punto caliente de la Cresta del Penacho en Llamas' WHERE ID=723;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Pila de tributo a Urok' WHERE ID=743;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Falla temporal de silo de Andorhal' WHERE ID=763;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Piedra de Shi-Rotam' WHERE ID=783;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Fuego Sagrado de la Vida' WHERE ID=803;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Campamento avanzado de la Cruzada Escarlata' WHERE ID=804;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Torre de Andorhal' WHERE ID=805;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Sala de visualización de Scholomance' WHERE ID=823;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Poza de la Luna Jaedenar corrompida' WHERE ID=843;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Amigo de Umi' WHERE ID=863;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Poza de la Luna' WHERE ID=883;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Lago de lava de la Cresta del Penacho en Llamas' WHERE ID=903;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='la caja en el centro de la Serrería de Crestanorte' WHERE ID=923;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Piedra de lechúcico lunar' WHERE ID=943;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Plaza de Villa Darrow' WHERE ID=944;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Haz de luz brillante' WHERE ID=963;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Marca de detonación' WHERE ID=983;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Entrada a la cueva Salto de Fonroca' WHERE ID=1003;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Estanque de Cima Calígine' WHERE ID=1004;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Los Goliath muertos' WHERE ID=1023;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Santuario de Remulos' WHERE ID=1043;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Montículo del tótem de los Maderiza' WHERE ID=1063;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Estanque Funesto' WHERE ID=1083;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Portal a Maraudon' WHERE ID=1103;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Globo de visión de la Horda' WHERE ID=1123;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cráter oriental' WHERE ID=1143;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cráter occidental' WHERE ID=1144;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cementerio Avalancha' WHERE ID=1145;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Globo de visión de la Alianza' WHERE ID=1163;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Patio de Dun Baldar' WHERE ID=1164;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Patio del castillo Lobo Gélido' WHERE ID=1165;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cementerio Avalancha' WHERE ID=1183;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cráter este' WHERE ID=1184;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cráter oeste' WHERE ID=1185;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Estanque del cristal naranja' WHERE ID=1203;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Aliento llameante de Onyxia' WHERE ID=1223;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Restos de Kroshius' WHERE ID=1243;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Pedestal de Immol''thar' WHERE ID=1263;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Círculo de Invocación oscura' WHERE ID=1264;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='El Gran Osario' WHERE ID=1283;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Espíritu embrujado de Valle del Terror' WHERE ID=1284;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Alcaldía de Pico Nidal' WHERE ID=1303;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Estatua en tumba de Uther' WHERE ID=1323;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Monumento de Grom' WHERE ID=1324;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Punta de Pagle' WHERE ID=1343;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Altar de Zanza' WHERE ID=1344;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Costasur' WHERE ID=1345;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Huesos de Grakkarond' WHERE ID=1346;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Bomba fétida de los Renegados' WHERE ID=1347;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Punto de llegada' WHERE ID=1348;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Vorágine espiral' WHERE ID=1349;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cueva del Gran Jefe Nevada' WHERE ID=1350;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Lanzafuegos artificiales' WHERE ID=1351;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Lanzatracas' WHERE ID=1352;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Gran Luz de Luna' WHERE ID=1353;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cámara de Voone' WHERE ID=1354;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cámara de Alzzin' WHERE ID=1355;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='El trono carmesí' WHERE ID=1356;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cámara de Ras Murmuhielo' WHERE ID=1357;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cámara de la Bestia' WHERE ID=1358;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Locus embrujado' WHERE ID=1359;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Arena de las Profundidades de Roca Negra' WHERE ID=1360;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='[PH] Cadáver de cristal' WHERE ID=1361;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Yunque Bramelo' WHERE ID=1362;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Piedra rúnica de Cantoeterno' WHERE ID=1363;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Tierra consagrada' WHERE ID=1364;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Fogata de solsticio de verano' WHERE ID=1365;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Poste' WHERE ID=1366;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Altar de Aggonar' WHERE ID=1367;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Huesos de Aggonar' WHERE ID=1368;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Banco de pargos rojos' WHERE ID=1369;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cadáver de Krun Rompeloma' WHERE ID=1370;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Poza de la luna de Thalanaar' WHERE ID=1371;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Panel de control oculto' WHERE ID=1372;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Altar de Naias' WHERE ID=1373;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Lugar discreto' WHERE ID=1374;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Runa de invocación' WHERE ID=1375;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Blandón vil' WHERE ID=1376;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='que estés en la cala del Traidor mientras que la bandera naga está alzada.' WHERE ID=1377;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cadáver de Sedai' WHERE ID=1378;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Monumento de Nazzivus' WHERE ID=1379;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cristal del Lugar del Accidente' WHERE ID=1380;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cristal de Bruma de Sangre modificado' WHERE ID=1381;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cristal Axxarien' WHERE ID=1382;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='el extremo sur de El Bancal del Maestro' WHERE ID=1383;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Telescopio de Medivh' WHERE ID=1384;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Llama Eterna de la Capilla de Alonsus' WHERE ID=1385;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cascada Bruma de Sangre' WHERE ID=1386;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Controles de bomba de vapor' WHERE ID=1387;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cabaña Junco Alabeado' WHERE ID=1388;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Marca terránea' WHERE ID=1389;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Foco de la fuente de agua subterránea' WHERE ID=1390;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Escaleras de las Ruinas Boha''mu' WHERE ID=1391;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Roca de Dagapantano' WHERE ID=1392;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Pira de los Filo Ardiente en las Ruinas Filo Ardiente' WHERE ID=1393;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Balcón de Ysiel' WHERE ID=1394;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Pira Mazo de Guerra llameante' WHERE ID=1395;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Tótem Velo Shalas' WHERE ID=1396;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Esqueleto pisoteado' WHERE ID=1397;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cañón de la Alianza' WHERE ID=1398;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Lanzacuchillos de la Horda' WHERE ID=1399;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Antena de la Legión' WHERE ID=1400;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Piedra rúnica de La Arboleda Agostada' WHERE ID=1401;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Estantería' WHERE ID=1402;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Expositor de armas' WHERE ID=1403;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cómoda' WHERE ID=1404;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Baúl' WHERE ID=1405;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Torre de asedio de la Alianza destruida' WHERE ID=1406;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Atracador desguazador X6000 fuera de control' WHERE ID=1407;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Runa de Kirin''Var' WHERE ID=1408;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Orbe del archimago Vargoth' WHERE ID=1409;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cascadas Elrendar' WHERE ID=1410;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Esqueleto de dragón' WHERE ID=1411;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Plataforma de teletransporte etérea' WHERE ID=1412;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Blandón Arklon' WHERE ID=1413;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Piedra del vacío' WHERE ID=1414;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Conducto de la Forja de Maná B''naar' WHERE ID=1415;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Estandarte draenei' WHERE ID=1416;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Círculo de los vinculadores terrestres' WHERE ID=1417;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Conducto de poder de Salhadaar' WHERE ID=1418;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Teletransportador de Socrethar' WHERE ID=1419;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Generador del Ecodomo Suthron' WHERE ID=1420;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='a que estés más cerca de la Forja de Maná Ultris.' WHERE ID=1421;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Torre Quiebranorte' WHERE ID=1422;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Altar de las Sombras' WHERE ID=1423;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Montículo de tubérculo de Sombraluna' WHERE ID=1424;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Rokgah Agarre Sangriento' WHERE ID=1425;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Telar de maná' WHERE ID=1426;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Altar draenei antiguo' WHERE ID=1427;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Entrada de construcción ogra' WHERE ID=1428;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Círculo arakkoa de Filospada' WHERE ID=1429;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Círculo de hechizo Lashh''an' WHERE ID=1430;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Círculo de poder Vekh''nir' WHERE ID=1431;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='que estés al final del puente.' WHERE ID=1432;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='El Terror de Torgos' WHERE ID=1433;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cículo de hechizos de los Vekh''nir' WHERE ID=1434;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='tú cerca de Gul''dan en El Altar de Condenación.' WHERE ID=1435;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Teletransportador de Bastión de la Legión' WHERE ID=1436;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Círculo del oráculo Ruuan''ok' WHERE ID=1437;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Dispositivo de comunicación de la Legión' WHERE ID=1438;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Supervisor Razelcraz' WHERE ID=1439;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Portal en Lago Luz Pantanosa' WHERE ID=1440;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Filospada - Misión -' WHERE ID=1441;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Velas de Malukaz' WHERE ID=1442;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Forja de Foso Sangrante' WHERE ID=1443;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cubil de la Marmota' WHERE ID=1444;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Teletransportador Gehenna' WHERE ID=1445;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cadáver del Comandante en Jefe Gorax' WHERE ID=1446;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Torre Zeth''Gor' WHERE ID=1447;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Lugar de invocación sin vigilancia' WHERE ID=1448;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Jaula de dracoleón cerrada' WHERE ID=1449;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cadáver de Gorgrom' WHERE ID=1450;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cañón vil de Puerta de la Muerte' WHERE ID=1451;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cículo de invocación del Alcor Tortuoso' WHERE ID=1452;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Altar de Goc y que Goc no ha sido invocado' WHERE ID=1453;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='La garra del Cuervo' WHERE ID=1454;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Santuario de los arakkoa' WHERE ID=1455;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Altar del Moledor de Almas' WHERE ID=1456;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Plataforma del transportador de Shartuul' WHERE ID=1457;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Restos de naufragio' WHERE ID=1458;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Molino de viento del Poblado Pezuñanegra' WHERE ID=1459;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Tienda Tótem Siniestro' WHERE ID=1460;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Monumento de la familia Hyal' WHERE ID=1461;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cabaña de trol ardiendo' WHERE ID=1462;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Entrada a la Guarida de Onyxia' WHERE ID=1463;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Muelle de la Mansión Cienaluz' WHERE ID=1464;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='La Plataforma de clamavermis' WHERE ID=1465;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cañón de La Playa Arrasada' WHERE ID=1466;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='cañón en la muralla noreste de la Alianza.' WHERE ID=1467;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='La pira del señor feudal' WHERE ID=1468;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cascada Helada' WHERE ID=1469;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='cerca de las jaulas de Campo Venganza.' WHERE ID=1470;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='De pie en la barra del puesto' WHERE ID=1471;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Caldera de sangre vrykul.' WHERE ID=1472;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Muestras de peste de Harris.' WHERE ID=1473;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='para que estés más cerca de las jaulas de los canes de peste.' WHERE ID=1474;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Tablilla rota' WHERE ID=1475;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Bote hundido' WHERE ID=1476;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Centro de Baleheim' WHERE ID=1477;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Fiesta de la cerveza: solicitud de jarra' WHERE ID=1478;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Runa de transporte de Walt' WHERE ID=1479;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Runa de transporte de enano de Hierro' WHERE ID=1480;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Líneas Ley de Quel''Danas' WHERE ID=1481;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Túmulo de Rajaespina' WHERE ID=1482;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Resguardo de cristal' WHERE ID=1483;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Teletransportador de la Legión' WHERE ID=1484;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Yunque de Hauthaa' WHERE ID=1485;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Túmulo funerario de los vrykuls' WHERE ID=1486;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Anomalía sísmica de La Falla Oeste' WHERE ID=1487;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='JSB - Reuse post 2.4.0' WHERE ID=1488;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Sumidero de Nerub''ar' WHERE ID=1489;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Tótem de Colmillo Gruñente' WHERE ID=1490;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Caldera de En''kilah' WHERE ID=1491;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='que estés más cerca del barco de Kvaldir.' WHERE ID=1492;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='que estés de pie al final del Malecón Grito de Guerra.' WHERE ID=1493;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Hechicero de Berilo encarcelado' WHERE ID=1494;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Escudo de fuerza de Berilo' WHERE ID=1495;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Caldero de peste del Cubil de los Moribundos' WHERE ID=1496;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Sumidero sur' WHERE ID=1497;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='que estés en los cruces, al este del Bastión Grito de Guerra.' WHERE ID=1498;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='que estés de pie junto al mago de sangre Laurith en las Llanuras Sanguiespora.' WHERE ID=1499;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Portal Sol Devastado' WHERE ID=1500;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Portal Sol Devastado' WHERE ID=1501;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Máquina voladora accidentada' WHERE ID=1502;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Corriente de vapor de Los Campos de Géiseres' WHERE ID=1503;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Falla dimensional de El Nexo' WHERE ID=1504;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Grano de Lindeallá' WHERE ID=1505;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Alto de Saragosa' WHERE ID=1506;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='cerca de un sumidero de la Plaga.' WHERE ID=1507;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Entrada noroeste de El Nexo' WHERE ID=1508;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Blandón de Drakuru' WHERE ID=1509;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Extremo oriental del túnel de Thor Modan' WHERE ID=1510;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Anzuelo de Tua''kea' WHERE ID=1511;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Blandón de Toalu''u' WHERE ID=1512;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Zona de prácticas de paracaidismo de Palanqueta' WHERE ID=1513;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Teletransportador de paracaidistas de Palanqueta' WHERE ID=1514;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Foco de línea Ley en la playa' WHERE ID=1515;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Foco de línea Ley en el Bosque Lothalor' WHERE ID=1516;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Foco de línea Ley bajo el lago' WHERE ID=1517;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Gongs de Drakil''jin' WHERE ID=1518;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Árbol de Viento Helado marcado' WHERE ID=1519;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Centro del foso bajo la Aguja del Flujo' WHERE ID=1520;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='profundidades bajo los restos de Vordrassil.' WHERE ID=1521;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='profundidades bajo el Limbo de Vordrassil.' WHERE ID=1522;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='profundidades bajo las Lágrimas de Vordrassil.' WHERE ID=1523;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Hansel Bauer' WHERE ID=1524;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Zona de desafíos de Grom''thar' WHERE ID=1525;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Estación de grifos de Hibergarde' WHERE ID=1526;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Aserradero de Nueva Vega del Amparo' WHERE ID=1527;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Árbol joven de Vordrassil' WHERE ID=1528;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Campamento' WHERE ID=1529;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Senda de salida del Santuario de Dragones Obsidiana' WHERE ID=1530;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='que estés de pie cerca del ingeniero de asedio Quaterflash.' WHERE ID=1531;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Runa nigromántica' WHERE ID=1532;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='que estés de pie en uno de los puntos de entrada a la Mina de Hibergarde.' WHERE ID=1533;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Banco de salmones del norte' WHERE ID=1534;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='que estés de pie en el centro de las ruinas de La Orilla Olvidada' WHERE ID=1535;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='que bajes a tus pasajeros frente al Mausoleo de Hibergarde.' WHERE ID=1536;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Bola de cristal de Ruuna' WHERE ID=1537;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Escudero Percy' WHERE ID=1538;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='que estés más cerca de Alystros el vigilante verdeante' WHERE ID=1539;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Altar de la Agonía de Escarcha' WHERE ID=1540;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='que estés en las arenas del Santuario de Dragones Bronce' WHERE ID=1541;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Percha de halcón vrykul' WHERE ID=1542;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Fuego de momia plagada' WHERE ID=1543;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Estatua ritual Drakkari' WHERE ID=1544;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Caldero de Finklestein' WHERE ID=1545;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Santuario Climático Susurraneblina' WHERE ID=1546;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cuenco para ofrendas' WHERE ID=1547;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Pedestal Drakkari' WHERE ID=1548;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Tronco caído' WHERE ID=1549;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Túmulo antiguo' WHERE ID=1550;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cráter nerubiano' WHERE ID=1551;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Forja de runas' WHERE ID=1552;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Zona de aterrizaje' WHERE ID=1553;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Carro de la Plaga' WHERE ID=1554;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='El cadáver de Quetz''lun y que el profeta de Quetz''lun esté presente y libre' WHERE ID=1555;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Altar de Kartak' WHERE ID=1556;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Gran piedra relámpago' WHERE ID=1557;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='que el Señor de la Guerra Zol''Maz esté presente y no esté entablando combate.' WHERE ID=1558;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Alto del Pilar Toquesol' WHERE ID=1559;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Círculo de convocación' WHERE ID=1560;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Tierra fértil empapada' WHERE ID=1561;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Alto del Pilar de Sholazar' WHERE ID=1562;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Alto del Pilar Iluminado' WHERE ID=1563;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cristal de Pilar Sangrevida expuesto' WHERE ID=1564;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Uzo Clamamuerte' WHERE ID=1565;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='el cadáver del arzobispo Landgren y que el Lord comandante Arete no esté presente' WHERE ID=1566;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Banco de peces de arrecife ricos' WHERE ID=1567;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='cámara de resurrección de magmavermis' WHERE ID=1568;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Altar de Tripaescarcha' WHERE ID=1569;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Teletransportador de Garm' WHERE ID=1570;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Thane Ufrang el Poderoso presente y sentado' WHERE ID=1571;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Punta de Hielo del Norte' WHERE ID=1572;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cráter gélido' WHERE ID=1573;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Enfermería de la Vanguardia' WHERE ID=1574;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Ventisquero' WHERE ID=1575;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='el nido de la madre de linaje' WHERE ID=1576;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Aterrizaje del K3' WHERE ID=1577;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Que el señor feudal Maleskara esté presente y que ni él ni sus Campeones no estén luchando' WHERE ID=1578;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Pila de calaveras de cruzado' WHERE ID=1579;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Horno de Malykriss' WHERE ID=1580;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Blandón de Ahn''kahet' WHERE ID=1581;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Losa del Sagrario de Reanimación' WHERE ID=1582;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Fuente de Dalaran' WHERE ID=1583;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Calaveras de la cima de Ymirheim' WHERE ID=1584;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Caldero de peste de Mord''rethar' WHERE ID=1585;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Orbe de Grimkor' WHERE ID=1586;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Caldera de cultor' WHERE ID=1587;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Piedra de alma de Alumeth' WHERE ID=1588;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='que estés cerca de un lexicón de poder' WHERE ID=1589;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Chatarra ardiente' WHERE ID=1590;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Altar de las Profundidades de Ébano' WHERE ID=1591;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cadáver del huargo caído' WHERE ID=1592;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Señal de fuego apagada' WHERE ID=1596;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Círculo de ofrenda de Drak''Mar' WHERE ID=1597;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Establos de torneo' WHERE ID=1599;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Grifo del Caballero Negro' WHERE ID=1601;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Bloque de piedra' WHERE ID=1602;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Lumbre fantasmal' WHERE ID=1613;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Montículo de nieve misterioso' WHERE ID=1618;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Cueva del Clamaneblina' WHERE ID=1620;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Monumentos Tualiq' WHERE ID=1621;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='la cubierta de La Furia de Bor' WHERE ID=1622;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Yunque del maestro de forja' WHERE ID=1636;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Campamento de suministros de La Corona' WHERE ID=1639;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='La Fuente del Sol' WHERE ID=1641;
UPDATE dbc_spellfocusobject SET Name_Lang_esMX='Vagón químico' WHERE ID=1650;
