UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Ventormenta' WHERE ID=1;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Montañas Crestagrana' WHERE ID=2;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque del Ocaso, Villa Oscura' WHERE ID=3;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Páramos de Poniente, Colina del Centinela' WHERE ID=4;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Dun Morogh' WHERE ID=5;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Loch Modan, Thelsamar' WHERE ID=6;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Los Humedales, Cruce' WHERE ID=7;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras Inhóspitas, cementerio NE' WHERE ID=8;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Los Baldíos, El Cruce' WHERE ID=10;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Desolace, Ethel Rethor' WHERE ID=31;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Durotar, Cerrotajo' WHERE ID=32;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Durotar, Orgrimmar' WHERE ID=33;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Mulgore, Mesa de la Nube Roja' WHERE ID=34;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Costa Oscura, Auberdine' WHERE ID=35;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Paso de la Muerte, Terreno de Morgan' WHERE ID=36;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Mil Agujas, El Gran Elevador' WHERE ID=39;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Yermos Gélidos: Inicio de la Horda' WHERE ID=49;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Silithus, Sosiego del Valor' WHERE ID=70;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Mulgore, Poblado Pezuña de Sangre' WHERE ID=89;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Teldrassil, Darnassus' WHERE ID=90;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Teldrassil, Dolanaar' WHERE ID=91;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Vallefresno, Astranaar' WHERE ID=92;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Teldrassil, Aldrassil' WHERE ID=93;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Claros de Tirisfal, Camposanto' WHERE ID=94;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Claros de Tirisfal, Entrañas' WHERE ID=96;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Argénteos, El Sepulcro' WHERE ID=97;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Laderas de Trabalomas, Molino Tarren' WHERE ID=98;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras Altas de Arathi, Camino del Este' WHERE ID=99;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Dun Morogh, Yunquemar' WHERE ID=100;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Dun Morogh, Kharanos' WHERE ID=101;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Dun Morogh, Forjaz' WHERE ID=102;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras Inhóspitas, Kargath' WHERE ID=103;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Montañas Crestagrana, Villa del Lago' WHERE ID=104;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Elwynn, Villanorte' WHERE ID=105;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Elwynn, Villadorada' WHERE ID=106;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Elwynn, Ventormenta' WHERE ID=107;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Pantano de las Penas, Rocal' WHERE ID=108;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Vega de Tuercespina, Bahía del Botín' WHERE ID=109;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Teldrassil, Aldea Rut''theran' WHERE ID=129;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Laderas de Trabalomas, Costasur' WHERE ID=149;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle de Alterac, Cementerio Avalancha (Med.)' WHERE ID=169;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marjal Revolcafango, Isla Theramore' WHERE ID=189;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tanaris, Gadgetzan' WHERE ID=209;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Los Baldíos, Campamento Taurajo' WHERE ID=229;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Los Baldíos, Trinquete' WHERE ID=249;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Yermos Gélidos: Inicio de la Alianza' WHERE ID=269;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Claros de Tirisfal, Rémol' WHERE ID=289;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Feralas, Bastión Plumaluna' WHERE ID=309;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Feralas, Campamento Mojache' WHERE ID=310;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Mil Agujas, El Desierto de Sal' WHERE ID=329;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras del Interior, Pico Nidal' WHERE ID=349;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Azshara, Punta Talrendis' WHERE ID=369;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Tierras Devastadas, Bastión Machacamiedo' WHERE ID=370;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Vega de Tuercespina, Tuercespina Norte' WHERE ID=389;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sierra Espolón, Senda de las Tejedoras' WHERE ID=409;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Claros de Tirisfal, Tumba de Faol' WHERE ID=429;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Frondavil, Morlos''Aran' WHERE ID=449;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cráter de Un''Goro, Los Pantanales' WHERE ID=450;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Costa Oscura, Vega Crepuscular' WHERE ID=469;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Los Humedales, Bahía de Baradin' WHERE ID=489;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras de la Peste del Oeste, Campamento del Orvallo' WHERE ID=509;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras de la Peste del Este, Cicatriz Pestilente' WHERE ID=510;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuna del Invierno, Vista Eterna' WHERE ID=511;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Vallefresno, Kargathia' WHERE ID=512;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Isla del Programador' WHERE ID=529;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Isla del Programador' WHERE ID=549;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras de la Peste del Oeste, El Baluarte' WHERE ID=569;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Isla del MJ' WHERE ID=589;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Azshara, Playa del Arrecife Sur' WHERE ID=609;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle de Alterac, punto seguro de la Horda' WHERE ID=610;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle de Alterac, punto seguro de la Alianza' WHERE ID=611;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='PRUEBA para cliente MJ solo: no bug' WHERE ID=629;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Azshara, Campamento Legashi' WHERE ID=630;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marjal Revolcafango, Poblado Murohelecho' WHERE ID=631;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Claro de la Luna' WHERE ID=633;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras de la Peste del Este, Villa Darrow' WHERE ID=634;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Frondavil, Bosque de Troncoferro' WHERE ID=635;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='La Garganta de Fuego, Puesto del Torio' WHERE ID=636;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Durotar, Poblado Sen''jin' WHERE ID=649;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Isla del programador, Cementerio Bucklers 2' WHERE ID=669;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Isla del programador, Cementerio Bucklers 1' WHERE ID=670;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Isla del programador, Cementerio Bucklers 3' WHERE ID=671;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle de Alterac, Cementerio Pico Tormenta (Alto)' WHERE ID=689;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle de Alterac, Cementerio de Lobo Gélido (Bajo)' WHERE ID=690;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Durotar, Valle de los Retos' WHERE ID=709;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle de Alterac, JcJ Cementerio principal de la Alianza (cem. Alz.)' WHERE ID=729;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle de Alterac, JcJ Cementerio principal de la Horda (cem. Hrd.)' WHERE ID=749;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle de Alterac, Puesto de auxilio Lobo Gélido (base Hrd.)' WHERE ID=750;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle de Alterac, Puesto de auxilio Pico Tormenta (base Alz.)' WHERE ID=751;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Garganta Grito de Guerra: Punto de entrada de la Alianza' WHERE ID=769;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Garganta Grito de Guerra: Punto de entrada de la Horda' WHERE ID=770;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Garganta Grito de Guerra: Punto de resurrección de la Alianza' WHERE ID=771;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Garganta Grito de Guerra: Punto de resurrección de la Horda' WHERE ID=772;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras del Interior, Los Acantilados Panorámicos' WHERE ID=789;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Garganta Grito de Guerra: Salida de la Horda' WHERE ID=809;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Garganta Grito de Guerra: Salida de la Alianza' WHERE ID=810;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle de Alterac, Salida de la Alianza' WHERE ID=829;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle de Alterac, Salida de la Horda' WHERE ID=830;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Feralas, La Masacre' WHERE ID=849;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Durotar, Durotar Norte' WHERE ID=850;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Mulgore, Cima del Trueno' WHERE ID=851;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Dun Morogh, Puertas de Forjaz' WHERE ID=852;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Claros de Tirisfal, Ruinas de Lordaeron' WHERE ID=853;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Elwynn, Aserradero de la Vega del Este' WHERE ID=854;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras de la Peste del Oeste, Castel Darrow' WHERE ID=869;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca del Arathi: Entrada de la Horda' WHERE ID=889;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca del Arathi: Entrada de la Alianza' WHERE ID=890;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca del Arathi: Salida de la Horda' WHERE ID=891;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca del Arathi: Salida de la Alianza' WHERE ID=892;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca del Arathi: Cementerio, entorno Hrd. (Granja)' WHERE ID=893;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca del Arathi: Cementerio, entorno (Herrería)' WHERE ID=894;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca del Arathi: Cementerio, entorno Alz. (Establo)' WHERE ID=895;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca del Arathi: Cementerio, Alt. N. (Mina de Oro)' WHERE ID=896;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca del Arathi: Cementerio, Alt. S. (Aserradero)' WHERE ID=897;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca del Arathi: Cementerio, base Alz. (Bastión de Aterratrols)' WHERE ID=898;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca del Arathi: Cementerio, base Hrd. (Guarida de los Rapiñadores)' WHERE ID=899;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras de la Peste del Este, Lago del Bosque Negro' WHERE ID=909;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Silithus, Fuerte Cenarion' WHERE ID=910;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque del Ocaso, Cerro del Cuervo' WHERE ID=911;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque Canción Eterna, Isla del Caminante del Sol' WHERE ID=912;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Silithus, Muro del Escarabajo (solo AQ)' WHERE ID=913;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque Canción Eterna, CE Cabaña del Errante' WHERE ID=914;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras Fantasma, Tranquilien' WHERE ID=915;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras Fantasma, Sagrario' WHERE ID=916;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras Fantasma, Paso de Amani' WHERE ID=917;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Isla Bruma Azur, Valle Ammen' WHERE ID=918;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, Thrallmar' WHERE ID=919;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, Bastión del Honor' WHERE ID=920;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque Canción Eterna, Ciudad de Lunargenta' WHERE ID=921;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque Canción Eterna, CE Aldea Brisa Pura' WHERE ID=922;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Isla Bruma Azur, CE Avanzada Azur' WHERE ID=923;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Isla Bruma Azur, CE Bastión Semprepino' WHERE ID=924;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Isla Bruma de Sangre, CE Avanzada de Sangre' WHERE ID=925;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Isla Bruma de Sangre, CE Tierras Salvajes' WHERE ID=926;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras de la Peste del Este, Cementerio Torre de la Corona' WHERE ID=927;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, CE Zabra''jin' WHERE ID=928;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Arena de Nagrand, Comienzo de Equipo 1' WHERE ID=929;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, Cementerio SE' WHERE ID=930;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Isla del Programador' WHERE ID=931;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Isla del Programador' WHERE ID=932;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, Templo' WHERE ID=933;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, Avanzada del Halcón' WHERE ID=934;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 004' WHERE ID=935;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Arena de Nagrand, Comienzo de Equipo 2' WHERE ID=936;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Reuse' WHERE ID=937;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle de Alterac, Salida de la Alianza' WHERE ID=938;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Arena Filospada, Equipo 1' WHERE ID=939;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Arena Filospada, Equipo 2' WHERE ID=940;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, prueba de ubicación de cadáver' WHERE ID=941;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 001' WHERE ID=942;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 002' WHERE ID=943;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 003' WHERE ID=944;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 005' WHERE ID=945;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 006' WHERE ID=946;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 007' WHERE ID=947;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 008' WHERE ID=948;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 009' WHERE ID=949;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 010' WHERE ID=950;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 011' WHERE ID=951;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 012' WHERE ID=952;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 013' WHERE ID=953;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 014' WHERE ID=954;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 015' WHERE ID=955;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 016' WHERE ID=956;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 017' WHERE ID=957;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 018' WHERE ID=958;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 019' WHERE ID=959;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 020' WHERE ID=960;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 021' WHERE ID=961;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 022' WHERE ID=962;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 023' WHERE ID=963;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 024' WHERE ID=964;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 025' WHERE ID=965;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 026' WHERE ID=966;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 027' WHERE ID=967;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, ubicación de cadáver 028' WHERE ID=968;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, CE JcJ' WHERE ID=969;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, CE Telredor' WHERE ID=970;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, JcJ, Cementerio de Arena' WHERE ID=971;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 006' WHERE ID=972;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, CE Cenarion' WHERE ID=973;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 001' WHERE ID=974;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 002' WHERE ID=975;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 003' WHERE ID=976;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 004' WHERE ID=977;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 008' WHERE ID=978;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 005' WHERE ID=979;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 007' WHERE ID=980;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 009' WHERE ID=981;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 011' WHERE ID=982;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 010' WHERE ID=983;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 012' WHERE ID=984;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 013' WHERE ID=985;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 014' WHERE ID=986;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 016' WHERE ID=987;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 015' WHERE ID=988;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 017' WHERE ID=989;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 018' WHERE ID=990;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, ubicación de cadáver 019' WHERE ID=991;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, Grieta del Viento Norte' WHERE ID=992;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, CE Halaa' WHERE ID=993;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, CE Shattrath' WHERE ID=994;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, CE Tierras Salvajes' WHERE ID=995;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Test - Programmer' WHERE ID=996;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Test - Programmer 001' WHERE ID=997;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, JcJ, Cementerio de Arena' WHERE ID=998;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, ubicación de cadáver 001' WHERE ID=999;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, ubicación de cadáver 002' WHERE ID=1000;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, ubicación de cadáver 003' WHERE ID=1001;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, ubicación de cadáver 004' WHERE ID=1002;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, ubicación de cadáver 005' WHERE ID=1003;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, ubicación de cadáver 006' WHERE ID=1004;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, ubicación de cadáver 007' WHERE ID=1005;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, ubicación de cadáver 008' WHERE ID=1006;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, ubicación de cadáver 009' WHERE ID=1007;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, ubicación de cadáver 010' WHERE ID=1008;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, ubicación de cadáver 011' WHERE ID=1009;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, ubicación de cadáver 012' WHERE ID=1010;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, ubicación de cadáver 013' WHERE ID=1011;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, ubicación de cadáver 014' WHERE ID=1012;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 001' WHERE ID=1013;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 002' WHERE ID=1014;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 003' WHERE ID=1015;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 004' WHERE ID=1016;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 005' WHERE ID=1017;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 006' WHERE ID=1018;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 007' WHERE ID=1019;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 008' WHERE ID=1020;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 009' WHERE ID=1021;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 010' WHERE ID=1022;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 011' WHERE ID=1023;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle Sombraluna, ubicación de cadáver 001' WHERE ID=1024;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle Sombraluna, ubicación de cadáver 002' WHERE ID=1025;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle Sombraluna, ubicación de cadáver 003' WHERE ID=1026;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle Sombraluna, ubicación de cadáver 004' WHERE ID=1027;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 016' WHERE ID=1028;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 017' WHERE ID=1029;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 018' WHERE ID=1030;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 019' WHERE ID=1031;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 020' WHERE ID=1032;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 021' WHERE ID=1033;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 022' WHERE ID=1034;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, ubicación de cadáver 023' WHERE ID=1035;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Reuse' WHERE ID=1036;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, Portal Meseta' WHERE ID=1037;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, Meseta Elemental' WHERE ID=1038;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Nagrand, Cementerio SO' WHERE ID=1039;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, Trono de Kil''Jaedan' WHERE ID=1040;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, El Portal Oscuro' WHERE ID=1041;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, CE El Vertedero de Huesos' WHERE ID=1042;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, CE Puerto' WHERE ID=1043;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marisma de Zangar, CE Esporaggar' WHERE ID=1044;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal, CE La Flecha de la Tormenta' WHERE ID=1045;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal, CE Área 52' WHERE ID=1046;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle Sombraluna, CE Aldea Sombraluna' WHERE ID=1047;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle Sombraluna, CE Bastión Martillo Salvaje' WHERE ID=1048;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Arena Filospada, CE Sylvanaar' WHERE ID=1049;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Arena Filospada, CE Aldea Señor del Trueno' WHERE ID=1050;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, CE Skettis' WHERE ID=1051;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 005' WHERE ID=1052;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 006' WHERE ID=1053;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 007' WHERE ID=1054;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 008' WHERE ID=1055;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 009' WHERE ID=1056;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 010' WHERE ID=1057;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 011' WHERE ID=1058;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 012' WHERE ID=1059;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 013' WHERE ID=1060;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 014' WHERE ID=1061;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 015' WHERE ID=1062;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 016' WHERE ID=1063;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 017' WHERE ID=1064;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 018' WHERE ID=1065;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 019' WHERE ID=1066;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 020' WHERE ID=1067;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 021' WHERE ID=1068;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 022' WHERE ID=1069;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 023' WHERE ID=1070;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sombraluna, ubicación de cadáver 024' WHERE ID=1071;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 000' WHERE ID=1072;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 001' WHERE ID=1073;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 002' WHERE ID=1074;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 003' WHERE ID=1075;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 004' WHERE ID=1076;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 005' WHERE ID=1077;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 006' WHERE ID=1078;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 007' WHERE ID=1079;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 008' WHERE ID=1080;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 009' WHERE ID=1081;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 010' WHERE ID=1082;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 011' WHERE ID=1083;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 012' WHERE ID=1084;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 013' WHERE ID=1085;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 014' WHERE ID=1086;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 015' WHERE ID=1087;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 016' WHERE ID=1088;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 017' WHERE ID=1089;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 018' WHERE ID=1090;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 019' WHERE ID=1091;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 020' WHERE ID=1092;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 021' WHERE ID=1093;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 022' WHERE ID=1094;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 023' WHERE ID=1095;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 024' WHERE ID=1096;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 025' WHERE ID=1097;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 026' WHERE ID=1098;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 027' WHERE ID=1099;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 028' WHERE ID=1100;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 029' WHERE ID=1101;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 030' WHERE ID=1102;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Cementerio (Principio de la Alianza)' WHERE ID=1103;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Cementerio (Principio de la Horda' WHERE ID=1104;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Cementerio (Atracador vil)' WHERE ID=1105;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Cementerio (Torre BE)' WHERE ID=1106;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Cementerio (Torre draenei)' WHERE ID=1107;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Cementerio (Torre humana)' WHERE ID=1108;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 000' WHERE ID=1109;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 001' WHERE ID=1110;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 002' WHERE ID=1111;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 003' WHERE ID=1112;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 004' WHERE ID=1113;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 005' WHERE ID=1114;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 006' WHERE ID=1115;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 007' WHERE ID=1116;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 008' WHERE ID=1117;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 009' WHERE ID=1118;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 010' WHERE ID=1119;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 011' WHERE ID=1120;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 012' WHERE ID=1121;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 013' WHERE ID=1122;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 014' WHERE ID=1123;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 015' WHERE ID=1124;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 016' WHERE ID=1125;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 017' WHERE ID=1126;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 018' WHERE ID=1127;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 019' WHERE ID=1128;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 020' WHERE ID=1129;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 021' WHERE ID=1130;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 022' WHERE ID=1131;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 023' WHERE ID=1132;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal CP - Recolector de cadáveres 024' WHERE ID=1133;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 000' WHERE ID=1134;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 001' WHERE ID=1135;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 002' WHERE ID=1136;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 003' WHERE ID=1137;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 004' WHERE ID=1138;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 005' WHERE ID=1139;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 006' WHERE ID=1140;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 007' WHERE ID=1141;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 008' WHERE ID=1142;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 009' WHERE ID=1143;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 010' WHERE ID=1144;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 011' WHERE ID=1145;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 012' WHERE ID=1146;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 013' WHERE ID=1147;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 014' WHERE ID=1148;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 015' WHERE ID=1149;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 016' WHERE ID=1150;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 017' WHERE ID=1151;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 018' WHERE ID=1152;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 019' WHERE ID=1153;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 020' WHERE ID=1154;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 021' WHERE ID=1155;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 022' WHERE ID=1156;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 023' WHERE ID=1157;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 024' WHERE ID=1158;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 025' WHERE ID=1159;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 026' WHERE ID=1160;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 027' WHERE ID=1161;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 028' WHERE ID=1162;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 029' WHERE ID=1163;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 030' WHERE ID=1164;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 031' WHERE ID=1165;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 032' WHERE ID=1166;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 033' WHERE ID=1167;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 034' WHERE ID=1168;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 035' WHERE ID=1169;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 036' WHERE ID=1170;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 037' WHERE ID=1171;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 038' WHERE ID=1172;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 039' WHERE ID=1173;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 040' WHERE ID=1174;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 041' WHERE ID=1175;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 042' WHERE ID=1176;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 043' WHERE ID=1177;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 044' WHERE ID=1178;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 045' WHERE ID=1179;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 046' WHERE ID=1180;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 047' WHERE ID=1181;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 048' WHERE ID=1182;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 049' WHERE ID=1183;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 050' WHERE ID=1184;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 051' WHERE ID=1185;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 052' WHERE ID=1186;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 053' WHERE ID=1187;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 054' WHERE ID=1188;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 055' WHERE ID=1189;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 056' WHERE ID=1190;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 057' WHERE ID=1191;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 058' WHERE ID=1192;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 059' WHERE ID=1193;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 060' WHERE ID=1194;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 061' WHERE ID=1195;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 062' WHERE ID=1196;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 063' WHERE ID=1197;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 064' WHERE ID=1198;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 065' WHERE ID=1199;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 066' WHERE ID=1200;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 067' WHERE ID=1201;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 068' WHERE ID=1202;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 069' WHERE ID=1203;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 070' WHERE ID=1204;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 071' WHERE ID=1205;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 072' WHERE ID=1206;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 073' WHERE ID=1207;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 074' WHERE ID=1208;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 075' WHERE ID=1209;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 076' WHERE ID=1210;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 077' WHERE ID=1211;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 078' WHERE ID=1212;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 079' WHERE ID=1213;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 080' WHERE ID=1214;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 081' WHERE ID=1215;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 082' WHERE ID=1216;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 083' WHERE ID=1217;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 084' WHERE ID=1218;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 085' WHERE ID=1219;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 086' WHERE ID=1220;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 087' WHERE ID=1221;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 088' WHERE ID=1222;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 089' WHERE ID=1223;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 090' WHERE ID=1224;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 091' WHERE ID=1225;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 092' WHERE ID=1226;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 093' WHERE ID=1227;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 094' WHERE ID=1228;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 095' WHERE ID=1229;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 096' WHERE ID=1230;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 097' WHERE ID=1231;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 098' WHERE ID=1232;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 099' WHERE ID=1233;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 100' WHERE ID=1234;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 101' WHERE ID=1235;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 102' WHERE ID=1236;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 103' WHERE ID=1237;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 104' WHERE ID=1238;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal - Recolector de cadáveres 105' WHERE ID=1239;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, Campos de Fuerza (Alianza)' WHERE ID=1240;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, CE Sotoeterno' WHERE ID=1241;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, CE Cresta Norte' WHERE ID=1242;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, CE Cresta Oeste' WHERE ID=1243;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, CE Cresta Este' WHERE ID=1244;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Corona de Hielo, CP, CE, zona de entrada Horda' WHERE ID=1245;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle de Alterac, Salida de la Alianza' WHERE ID=1246;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal, CE Cosmotirón' WHERE ID=1247;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Península del Fuego Infernal, CE Rompeloma' WHERE ID=1248;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tanaris, CdT' WHERE ID=1249;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle Sombraluna, CE Altar' WHERE ID=1250;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Valle Sombraluna, CE Sagrario' WHERE ID=1251;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tormenta Abisal, CE Kirin''Var' WHERE ID=1252;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, CE Toshley' WHERE ID=1253;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, CE Bosque del Cuervo' WHERE ID=1254;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, CE Cresta NE' WHERE ID=1255;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Argénteos, CE Sur' WHERE ID=1256;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, CE ogro' WHERE ID=1257;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Lordaeron, PVP - Team 1 Start' WHERE ID=1258;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Lordaeron, PVP - Team 2 Start' WHERE ID=1259;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Lordaeron, PVP - Graveyard' WHERE ID=1260;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Templo Oscuro, CE Alianza' WHERE ID=1261;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Templo Oscuro, CE Horda' WHERE ID=1262;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Filospada, ubicación de cadáver 031' WHERE ID=1263;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marjal Revolcafango, Granja de Tabetha' WHERE ID=1264;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marjal Revolcafango, Piñón de Barro' WHERE ID=1265;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Fiordo Aquilonal, CE Noroeste' WHERE ID=1266;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Fiordo Aquilonal, CE Colmillarr' WHERE ID=1267;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Fiordo Aquilonal, CE isla' WHERE ID=1268;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Fiordo Aquilonal, CE Central' WHERE ID=1269;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Fiordo Aquilonal, CE Norte' WHERE ID=1270;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Fiordo Aquilonal, CE Venganza' WHERE ID=1271;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Fiordo Aquilonal, CE Sureste' WHERE ID=1272;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Fiordo Aquilonal, CE playa sur' WHERE ID=1273;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Fiordo Aquilonal, CE Sur' WHERE ID=1274;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Fiordo Aquilonal, CE Valgarde' WHERE ID=1275;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Fiordo Aquilonal, CE Noreste' WHERE ID=1276;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cráter de Un''Goro, CE Central' WHERE ID=1277;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cráter de Un''Goro, CE de mariscal' WHERE ID=1278;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sierra Espolón, La Vega Carbonizada' WHERE ID=1279;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sierra Espolón, CE de la cima' WHERE ID=1280;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tanaris, CE pirata' WHERE ID=1281;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tanaris, CE Central' WHERE ID=1282;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuna del Invierno, CE Sur' WHERE ID=1283;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuna del Invierno, CE Oeste' WHERE ID=1284;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Conquista del Invierno, fortaleza (este)' WHERE ID=1285;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras de la Peste del Oeste, CE Central' WHERE ID=1286;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='La Garganta de Fuego, CE SE' WHERE ID=1287;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras Inhóspitas, CE Sur' WHERE ID=1288;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Los Baldíos, CE Sur' WHERE ID=1289;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tundra Boreal, CE Colmillarr' WHERE ID=1290;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, CE Alto Rajaespina' WHERE ID=1291;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Isla de Quel''Danas, CE Zona de escala' WHERE ID=1292;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Isla de Quel''Danas, CE Zona de escala' WHERE ID=1293;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Isla de Quel''Danas, CE Zona de escala' WHERE ID=1294;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Development Land, Theresa''s Test Land GY' WHERE ID=1295;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Development Land, Theresa''s Test Land 2 GY' WHERE ID=1296;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Development Land, Theresa''s Test land 3 GY' WHERE ID=1297;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Terokkar, CE Lago Jorune' WHERE ID=1298;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Corona de Hielo, CP, CE, zona de entrada Alianza' WHERE ID=1299;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Colinas Pardas, CE Presavil' WHERE ID=1300;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Colinas Pardas, CE Pino Ámbar' WHERE ID=1301;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Colinas Pardas, CE Poniente' WHERE ID=1302;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Colinas Pardas, CE Este' WHERE ID=1303;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Colinas Pardas, CE Noroeste' WHERE ID=1304;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Colinas Pardas, CE Suroeste' WHERE ID=1305;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Colinas Pardas, CE Central' WHERE ID=1306;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cementerio de Dragones, CE Noroeste' WHERE ID=1307;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cementerio de Dragones, CE Hibergarde' WHERE ID=1308;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cementerio de Dragones, CE Este Renegado' WHERE ID=1309;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cementerio de Dragones, CE Martillo de Agmar' WHERE ID=1310;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cementerio de Dragones, CE Reposo Estelar' WHERE ID=1311;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cementerio de Dragones, CE Puerto Moa''ki' WHERE ID=1312;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cementerio de Dragones, CE Frontera Boreal' WHERE ID=1313;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cementerio de Dragones, CE Reposo del Dragón' WHERE ID=1314;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cementerio de Dragones, CE Puerta de Cólera Horda' WHERE ID=1315;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cementerio de Dragones, CE Puerta de Cólera Alianza' WHERE ID=1316;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tundra Boreal, CE Bastión Grito de Guerra' WHERE ID=1317;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tundra Boreal, CE Tralladón' WHERE ID=1318;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tundra Boreal, CE Gelidar' WHERE ID=1319;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tundra Boreal, CE El Saliente Ámbar' WHERE ID=1320;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tundra Boreal, CE Palanqueta' WHERE ID=1321;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tundra Boreal, CE Bor''Gorok' WHERE ID=1322;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tundra Boreal, CE Confín de la Muerte' WHERE ID=1323;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tundra Boreal, CE Taunka''le' WHERE ID=1324;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tundra Boreal, CE Costa de los Ecos' WHERE ID=1325;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tundra Boreal, CE Fortaleza Denuedo' WHERE ID=1326;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Alterac Valley - DO NOT EDIT' WHERE ID=1327;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Conquista del Invierno, fortaleza (oeste)' WHERE ID=1328;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Conquista del Invierno, fábrica de material de asedio (Defensa NE)' WHERE ID=1329;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Conquista del Invierno, fábrica de material de asedio (Defensa NO)' WHERE ID=1330;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Conquista del Invierno, zona de inicio de la Horda' WHERE ID=1331;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Conquista del Invierno, zona de inicio de la Alianza' WHERE ID=1332;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Conquista del Invierno, fábrica de material de asedio (SE)' WHERE ID=1333;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Conquista del Invierno, fábrica de material de asedio (SO)' WHERE ID=1334;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca de Sholazar, CE Sur' WHERE ID=1336;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Fiordo Aquilonal, CE Utgarde' WHERE ID=1337;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca de Sholazar, CE Nesingwary' WHERE ID=1341;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca de Sholazar, CE Central' WHERE ID=1342;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca de Sholazar, CE Noroeste' WHERE ID=1343;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca de Sholazar, CE Noreste' WHERE ID=1344;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca de Sholazar, CE Este' WHERE ID=1345;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Rasganorte, CP, controlado, sur' WHERE ID=1346;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Rasganorte, CP, controlado, suroeste' WHERE ID=1347;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Rasganorte, CP, controlado, central' WHERE ID=1348;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Rasganorte, CP, defensa, final' WHERE ID=1349;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Rasganorte, CP, ofensiva, playa' WHERE ID=1350;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Rasganorte, CP, ofensiva, bote' WHERE ID=1351;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Zul''Drak, CE Oeste' WHERE ID=1352;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Zul''Drak, CE Noroeste' WHERE ID=1353;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Zul''Drak, CE Suroeste' WHERE ID=1354;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Zul''Drak, CE Sur' WHERE ID=1355;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Zul''Drak, CE Central' WHERE ID=1356;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Zul''Drak, CE Sureste' WHERE ID=1357;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Zul''Drak, CE Gun''Drak' WHERE ID=1358;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque Canto de Cristal, CE Dalaran' WHERE ID=1359;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='CE El Bastión de Ébano - Capítulo 1' WHERE ID=1360;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Arena de Dalaran - JcJ Cementerio' WHERE ID=1361;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Arena de Dalaran - Equipo 1 punto de aparición' WHERE ID=1362;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Arena de Dalaran - Equipo 2 punto de aparición' WHERE ID=1363;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Arena de Orgrimmar - Equipo 1 punto de aparición' WHERE ID=1364;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Arena de Orgrimmar - Equipo 2 punto de aparición' WHERE ID=1365;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Arena de Orgrimmar - Cementerio' WHERE ID=1366;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Arenas de Ulduran - Alianza punto de aparición' WHERE ID=1367;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Arenas de Ulduran - Horda punto de aparición' WHERE ID=1368;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras de la Peste del Este, CE El Bastión de Ébano' WHERE ID=1369;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='CE El Bastión de Ébano - Capítulo 2/3' WHERE ID=1370;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='CE El Bastión de Ébano - Capítulo 4' WHERE ID=1371;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cráter de Un''Goro, El Bancal del Creador' WHERE ID=1372;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marjal Revolcafango, punto seguro de Theramore' WHERE ID=1373;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Durotar, punto seguro de Orgrimmar' WHERE ID=1374;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Ciudad de Ventormenta, punto seguro de Ventormenta' WHERE ID=1375;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Fiordo Aquilonal, CE Utgarde 2' WHERE ID=1376;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Mare Magnum, punto seguro de la Alianza' WHERE ID=1377;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Durotar, punto seguro de Orgrimmar 2' WHERE ID=1378;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca de Sholazar, CE P. del Tormentoso' WHERE ID=1379;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque Canto de Cristal, CE Alianza' WHERE ID=1380;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Corona de Hielo, Vanguardia Argenta' WHERE ID=1381;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Cumbres Tormentosas, CE Valkyrion' WHERE ID=1383;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Cumbres Tormentosas, CE Ulduar' WHERE ID=1384;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Cumbres Tormentosas, CE Templo Este' WHERE ID=1385;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Cumbres Tormentosas, CE Templo Oeste' WHERE ID=1387;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Cumbres Tormentosas, CE Campo de Escarcha' WHERE ID=1388;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque Canto de Cristal, CE Oeste' WHERE ID=1391;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque Canto de Cristal, CE Horda' WHERE ID=1392;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cementerio de Dragones, CE Naxxramas' WHERE ID=1393;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cementerio de Dragones, CE Bruma de Hielo' WHERE ID=1394;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Glaciar Corona de Hielo, CE Cantera' WHERE ID=1395;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Glaciar Corona de Hielo, CE vrykul central' WHERE ID=1396;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Glaciar Corona de Hielo, CE Hielo Noreste' WHERE ID=1397;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Colinas Pardas, CE Drak''tharon' WHERE ID=1398;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Northrend BG - Defender Start' WHERE ID=1399;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Cumbres Tormentosas, CE Templo de los Creadores' WHERE ID=1400;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Cumbres Tormentosas, CE Ventisquero' WHERE ID=1401;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Cumbres Tormentosas, CE Templo de las Tormentas' WHERE ID=1402;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Cumbres Tormentosas, CE K3' WHERE ID=1403;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuenca de Sholazar, CE Corazón Frenético' WHERE ID=1404;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras de la Peste del Este: Acherus' WHERE ID=1405;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Glaciar Corona de Hielo, CE Jotunheim' WHERE ID=1407;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Cumbres Tormentosas, CE Las Estepas Inferiores' WHERE ID=1408;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Entrañas, Alianza, Puerta de Cólera' WHERE ID=1409;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='AAAAA Test Port Loc' WHERE ID=1410;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Montañas de Alterac: CE Central' WHERE ID=1411;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cuna del Invierno, CE Sableinvernales' WHERE ID=1416;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Conquista del Invierno, CE Cruce de Caminos' WHERE ID=1417;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Conquista del Invierno, CE Negro Rumor' WHERE ID=1418;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Azshara, Ursolan' WHERE ID=1419;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Azshara, Loma Desolada' WHERE ID=1420;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Desolace, Campamento del Espíritu Errante' WHERE ID=1421;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Desolace, Playa de Sar''theris' WHERE ID=1422;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Desolace, Aquelarre Mannoroc' WHERE ID=1423;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Desolace, Poblado Magram' WHERE ID=1424;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Desolace, Camino' WHERE ID=1425;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Vallefresno, Santuario de Aessina' WHERE ID=1426;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Vallefresno, Arrullanoche' WHERE ID=1427;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sierra Espolón, Risco Cortaviento' WHERE ID=1428;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sierra Espolón, Mirkfallon' WHERE ID=1429;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Los Baldíos, Las Charcas del Olvido' WHERE ID=1430;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Los Baldíos, CE Norte' WHERE ID=1431;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Los Baldíos, Tierras de los Raptores' WHERE ID=1432;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Los Baldíos, CE Central' WHERE ID=1433;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Los Baldíos, CE Este' WHERE ID=1434;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Mulgore, CE Sureste' WHERE ID=1435;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Mulgore, Roca Roja' WHERE ID=1436;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Mil Agujas, Poblado Viento Libre' WHERE ID=1437;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Mil Agujas, Circuito del Espejismo' WHERE ID=1438;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tanaris, CE Sureste' WHERE ID=1439;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tanaris, Arenas Abisales' WHERE ID=1440;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Feralas, Ruinas de Isildien' WHERE ID=1441;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Feralas, Bajas Tierras Salvajes' WHERE ID=1442;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Feralas, Los Dos Colosos' WHERE ID=1443;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Silithus, Colmen''Regal' WHERE ID=1444;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Silithus, Campamento Crepúsculo' WHERE ID=1445;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras Altas de Arathi, Stromgarde' WHERE ID=1446;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Laderas de Trabalomas, Muralla de Thoradin' WHERE ID=1447;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras de la Peste del Este, Vallenorte' WHERE ID=1448;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras de la Peste del Este, Stratholme' WHERE ID=1449;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras de la Peste del Este, CE Oeste' WHERE ID=1450;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras de la Peste del Oeste, Vega del Amparo' WHERE ID=1451;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Laderas de Trabalomas, Campos de Trabalomas' WHERE ID=1452;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras del Interior, Seradane' WHERE ID=1453;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Tierras del Interior, Los Acantilados Dominantes' WHERE ID=1454;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Los Humedales, Pantano del Ocaso' WHERE ID=1455;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Los Humedales, Camino del Sur' WHERE ID=1456;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Los Humedales, Colina del Raptor' WHERE ID=1457;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Vega de Tuercespina, Arena Gurubashi' WHERE ID=1458;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Vega de Tuercespina, CE Central' WHERE ID=1459;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Vega de Tuercespina, La Costa Salvaje' WHERE ID=1460;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Durotar, CE Central' WHERE ID=1461;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Páramos de Poniente, Las Colinas Afiladas' WHERE ID=1462;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Páramos de Poniente, Playa Larga' WHERE ID=1463;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Tierras Devastadas, El Portal Oscuro' WHERE ID=1464;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Pantano de las Penas, Charca de Lágrimas' WHERE ID=1465;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Pantano de las Penas, Lanzarrota' WHERE ID=1466;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Montañas Crestagrana, Petravista' WHERE ID=1467;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Bosque de Elwynn, Torre de Azora' WHERE ID=1468;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Estepas Ardientes, Montaña Roca Negra' WHERE ID=1469;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Las Estepas Ardientes, CE Este' WHERE ID=1470;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Dun Morogh, Lago Glacial' WHERE ID=1471;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Dun Morogh, Camino Este' WHERE ID=1472;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Loch Modan, El Lago' WHERE ID=1473;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Conquista del Invierno, cementerio de la fortaleza (interior)' WHERE ID=1474;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Sierra Espolón, CE Sureste' WHERE ID=1476;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Cementerio de Dragones, CE Vicio de Cristal' WHERE ID=1477;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Corona de Hielo, CE Torneo Argenta' WHERE ID=1478;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Corona de Hielo, CP, CE, embarcaderos' WHERE ID=1480;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Corona de Hielo, CP, CE, aeropuerto' WHERE ID=1481;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Corona de Hielo, CP, CE, taller' WHERE ID=1482;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Corona de Hielo, CP, CE, predeterminado Alianza' WHERE ID=1483;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Corona de Hielo, CP, CE, predeterminado Horda' WHERE ID=1484;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Corona de Hielo CP - CE - Fortaleza de la Alianza' WHERE ID=1485;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Corona de Hielo CP - CE - Fortaleza de la Horda' WHERE ID=1486;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Los Baldíos, El Alto del Honor' WHERE ID=1493;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Marjal Revolcafango, Ciénaga de Fuego' WHERE ID=1681;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Glaciar de la Corona de Hielo, Ciudadela CE' WHERE ID=1682;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='La Fuente del Sol - Entrada a Quel''Delar' WHERE ID=1683;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='AAA - Arena (Dev Test)' WHERE ID=1691;
UPDATE dbc_worldsafelocs SET AreaName_Lang_esMX='Howling Fjord, Frostblade GY' WHERE ID=1720;
