UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Self Only', DisplayNameShort_Lang_esMX='Self' WHERE ID=1;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Combat Range', DisplayNameShort_Lang_esMX='Combat' WHERE ID=2;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Twenty yards', DisplayNameShort_Lang_esMX='Short' WHERE ID=3;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Medium Range', DisplayNameShort_Lang_esMX='Medium' WHERE ID=4;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Long Range', DisplayNameShort_Lang_esMX='Long' WHERE ID=5;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Vision Range', DisplayNameShort_Lang_esMX='Vision' WHERE ID=6;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Ten yards', DisplayNameShort_Lang_esMX='Very Short' WHERE ID=7;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Min Range 10, 20', DisplayNameShort_Lang_esMX='Short' WHERE ID=8;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Medium Range', DisplayNameShort_Lang_esMX='Medium' WHERE ID=9;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Long Range', DisplayNameShort_Lang_esMX='Long' WHERE ID=10;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Fifteen yards', DisplayNameShort_Lang_esMX='Shorter' WHERE ID=11;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Interact Range', DisplayNameShort_Lang_esMX='Interact' WHERE ID=12;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Anywhere', DisplayNameShort_Lang_esMX='Anywhere' WHERE ID=13;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Extra Long Range', DisplayNameShort_Lang_esMX='Extra Long' WHERE ID=14;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Twenty-Five yards', DisplayNameShort_Lang_esMX='Medium-Short' WHERE ID=34;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Medium-Long Range', DisplayNameShort_Lang_esMX='Medium-Long' WHERE ID=35;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Longer Range', DisplayNameShort_Lang_esMX='Longer' WHERE ID=36;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Extended Range', DisplayNameShort_Lang_esMX='Extended' WHERE ID=37;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Min-Range 10, 25', DisplayNameShort_Lang_esMX='Extra Medium' WHERE ID=38;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Monster Shoot', DisplayNameShort_Lang_esMX='Monster Shoot Range' WHERE ID=54;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Ranged Weapon', DisplayNameShort_Lang_esMX='Ranged' WHERE ID=74;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Sting', DisplayNameShort_Lang_esMX='Sting' WHERE ID=94;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Charge', DisplayNameShort_Lang_esMX='Charge' WHERE ID=95;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Trap', DisplayNameShort_Lang_esMX='Trap' WHERE ID=96;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Hunter Range', DisplayNameShort_Lang_esMX='Hunter' WHERE ID=114;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Tower 80', DisplayNameShort_Lang_esMX='Tower' WHERE ID=134;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Tower 100', DisplayNameShort_Lang_esMX='Tower' WHERE ID=135;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Thirty-to-80', DisplayNameShort_Lang_esMX='Thirty-to-80' WHERE ID=136;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Eight yards', DisplayNameShort_Lang_esMX='Very Short' WHERE ID=137;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Long Range Hunter Shoot', DisplayNameShort_Lang_esMX='Hunter Long' WHERE ID=139;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Six yards', DisplayNameShort_Lang_esMX='Six yards' WHERE ID=140;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Seven yards', DisplayNameShort_Lang_esMX='Seven yards' WHERE ID=141;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Valgarde 8/100', DisplayNameShort_Lang_esMX='Valgarde' WHERE ID=150;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Long Range Hunter Shoot', DisplayNameShort_Lang_esMX='Hunter 45' WHERE ID=151;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Super Long', DisplayNameShort_Lang_esMX='Super Long' WHERE ID=152;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Charge, 60', DisplayNameShort_Lang_esMX='Huge Charge' WHERE ID=153;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Tower 80, 10', DisplayNameShort_Lang_esMX='Tower 10' WHERE ID=154;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Hunter Range (Long)', DisplayNameShort_Lang_esMX='Hunter (Long)' WHERE ID=155;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Boulder Range', DisplayNameShort_Lang_esMX='Boulder' WHERE ID=156;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Ninety', DisplayNameShort_Lang_esMX='Ninety' WHERE ID=157;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Super Long, 15 Min', DisplayNameShort_Lang_esMX='Super Long' WHERE ID=158;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='TEST - Long Range', DisplayNameShort_Lang_esMX='TestLong' WHERE ID=159;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Medium/Long Range', DisplayNameShort_Lang_esMX='Medium/Long' WHERE ID=160;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Short/Long Range', DisplayNameShort_Lang_esMX='Short/Long' WHERE ID=161;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Medium/Short Range', DisplayNameShort_Lang_esMX='Medium/Short' WHERE ID=162;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Death Grip', DisplayNameShort_Lang_esMX='Death Grip' WHERE ID=163;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Catapult Range', DisplayNameShort_Lang_esMX='Catapult' WHERE ID=164;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Fourteen yards', DisplayNameShort_Lang_esMX='Shorter' WHERE ID=165;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Thirteen yards', DisplayNameShort_Lang_esMX='Shorter' WHERE ID=166;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Super Long (Min Range)', DisplayNameShort_Lang_esMX='Super Long' WHERE ID=167;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Medium-Long Range (38)', DisplayNameShort_Lang_esMX='Medium-Long' WHERE ID=168;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Three Yards', DisplayNameShort_Lang_esMX='Three Yards' WHERE ID=169;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Fifty Five Yards', DisplayNameShort_Lang_esMX='Extended' WHERE ID=170;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Min Range 1, 10', DisplayNameShort_Lang_esMX='Very Short' WHERE ID=171;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Eleven yards', DisplayNameShort_Lang_esMX='Shorter' WHERE ID=172;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Anywhere (Combat Min Range)', DisplayNameShort_Lang_esMX='Hunter Long' WHERE ID=173;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='U L T R A', DisplayNameShort_Lang_esMX='U L T R A' WHERE ID=174;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Seventy yards', DisplayNameShort_Lang_esMX='Extended' WHERE ID=176;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Donut 20-70', DisplayNameShort_Lang_esMX='Donut 20-70' WHERE ID=177;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Min Range 5, 15', DisplayNameShort_Lang_esMX='Shorter' WHERE ID=179;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Tournament - Ranged', DisplayNameShort_Lang_esMX='Argent Tournament - Ranged' WHERE ID=180;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Two-Hundred Yard Range', DisplayNameShort_Lang_esMX='200' WHERE ID=181;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Min Range 5, 25', DisplayNameShort_Lang_esMX='Medium' WHERE ID=184;
UPDATE dbc_spellrange SET DisplayName_Lang_esMX='Three Hundred Yards', DisplayNameShort_Lang_esMX='300' WHERE ID=187;
