UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=1;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=2;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=3;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=4;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=5;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=6;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=126;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=163;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=522;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=7;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=8;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=9;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=10;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=11;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=12;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=13;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=14;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=15;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=16;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=17;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=18;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=19;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=20;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=21;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=22;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=23;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=24;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=25;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=26;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=323;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=27;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='El nivel de dificultad Heroico requiere la llave del tiempo.' WHERE ID=127;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=28;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=29;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=30;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=31;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=32;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=33;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=34;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=35;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=36;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=37;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=38;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=39;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=40;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=41;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=42;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=43;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=44;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=45;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=46;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=128;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=47;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=48;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='El nivel de dificultad Heroico requiere la llave de Forjallamas.' WHERE ID=129;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=49;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='El nivel de dificultad Heroico requiere la llave de Forjallamas.' WHERE ID=130;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=50;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='El nivel de dificultad Heroico requiere la llave de Forjallamas.' WHERE ID=131;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=51;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=52;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='El nivel de dificultad Heroico requiere la llave de la reserva.' WHERE ID=132;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=53;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='El nivel de dificultad Heroico requiere la llave de la reserva.' WHERE ID=133;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=54;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='El nivel de dificultad Heroico requiere la llave de la reserva.' WHERE ID=134;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=55;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=56;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=57;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='El nivel de dificultad Heroico requiere llave forjada de distorsión.' WHERE ID=135;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=58;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='El nivel de dificultad Heroico requiere llave forjada de distorsión.' WHERE ID=136;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=59;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='El nivel de dificultad Heroico requiere llave forjada de distorsión.' WHERE ID=137;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=60;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='El nivel de dificultad Heroico requiere la llave Auchenai.' WHERE ID=138;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=61;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='El nivel de dificultad Heroico requiere la llave Auchenai.' WHERE ID=139;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=62;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='El nivel de dificultad Heroico requiere la llave Auchenai.' WHERE ID=140;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=63;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='El nivel de dificultad Heroico requiere la llave Auchenai.' WHERE ID=141;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=64;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=65;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='El nivel de dificultad Heroico requiere la llave del tiempo.' WHERE ID=142;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=66;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=67;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=68;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=69;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=70;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=71;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=72;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=73;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 65.' WHERE ID=74;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para acceder al nivel de dificultad Heroico, debes tener nivel 80.' WHERE ID=143;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=75;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para acceder al nivel de dificultad Heroico, debes tener nivel 80.' WHERE ID=144;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 66.' WHERE ID=76;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para acceder al nivel de dificultad Heroico, debes tener nivel 80.' WHERE ID=145;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 75.' WHERE ID=77;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para acceder al nivel de dificultad Heroico, debes tener nivel 80.' WHERE ID=146;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=78;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=79;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=80;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=81;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='La dificultad heroica requiere que completes la misión "Duro de matar".' WHERE ID=147;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=82;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=83;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=84;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=85;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=86;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=87;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=88;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=89;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=90;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 75.' WHERE ID=91;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para acceder al nivel de dificultad Heroico, debes tener nivel 80.' WHERE ID=148;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=92;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=93;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=94;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='El nivel de dificultad Heroico requiere la llave Forjasol.' WHERE ID=149;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 72.' WHERE ID=95;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para acceder al nivel de dificultad Heroico, debes tener nivel 80.' WHERE ID=150;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 69.' WHERE ID=96;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para acceder al nivel de dificultad Heroico, debes tener nivel 80.' WHERE ID=151;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 67.' WHERE ID=97;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para acceder al nivel de dificultad Heroico, debes tener nivel 80.' WHERE ID=152;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 75.' WHERE ID=98;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para acceder al nivel de dificultad Heroico, debes tener nivel 80.' WHERE ID=153;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=99;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=154;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 71.' WHERE ID=100;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para acceder al nivel de dificultad Heroico, debes tener nivel 80.' WHERE ID=155;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=101;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=102;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=103;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=301;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 70.' WHERE ID=104;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para acceder al nivel de dificultad Heroico, debes tener nivel 80.' WHERE ID=156;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=105;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=106;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=107;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=108;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=109;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=110;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=157;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=111;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=158;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=112;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=113;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 68.' WHERE ID=114;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para acceder al nivel de dificultad Heroico, debes tener nivel 80.' WHERE ID=159;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=115;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=116;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=117;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=118;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80, controlar Conquista del Invierno y pertenecer a un grupo de banda.' WHERE ID=119;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80, controlar Conquista del Invierno y pertenecer a un grupo de banda.' WHERE ID=160;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=120;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=281;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=485;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=486;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Tienes que haber derrotado al Rey Exánime en la banda de 10 jugadores para poder intentar la dificultad heroica para 10 jugadores.' WHERE ID=487;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Tienes que haber derrotado al Rey Exánime en la banda de 25 jugadores para poder intentar la dificultad heroica para 25 jugadores.' WHERE ID=488;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 75.' WHERE ID=481;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para acceder al nivel de dificultad Heroico, debes tener nivel 80.' WHERE ID=482;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=121;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=122;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=123;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=124;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=161;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=221;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=222;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 75.' WHERE ID=125;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para acceder al nivel de dificultad Heroico, debes tener nivel 80.' WHERE ID=162;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Debes completar la misión "Ecos de almas torturadas" antes de entrar en el Foso de Saron.' WHERE ID=483;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Debes completar la misión " Ecos de almas torturadas " y ser nivel 80 antes de entrar el Foso de Saron en dificultad heroica.' WHERE ID=484;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Debes completar la misión "Liberación del foso" antes de entrar en las Cámaras de Reflexión.' WHERE ID=341;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Debes completar la misión "Liberación del foso" y ser nivel 80 antes de entrar en las Cámaras de Reflexión en dificultad heroica.' WHERE ID=342;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=642;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=641;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=701;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='' WHERE ID=744;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=750;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=751;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=752;
UPDATE dbc_mapdifficulty SET Message_Lang_esMX='Para entrar, debes tener al menos nivel 80 y pertenecer a un grupo de banda.' WHERE ID=753;
