-- ----------------------------
-- Table structure for dbc_chrraces
-- ----------------------------
DROP TABLE IF EXISTS `dbc_chrraces`;
CREATE TABLE `dbc_chrraces`  (
  `guid` int(11) NOT NULL AUTO_INCREMENT,
  `ID` int(11) NOT NULL DEFAULT 0,
  `Flags` int(11) NOT NULL DEFAULT 0,
  `FactionID` int(11) NOT NULL DEFAULT 0,
  `ExplorationSoundID` int(11) NOT NULL DEFAULT 0,
  `MaleDisplayId` int(11) NOT NULL DEFAULT 0,
  `FemaleDisplayId` int(11) NOT NULL DEFAULT 0,
  `ClientPrefix` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `BaseLanguage` int(11) NOT NULL DEFAULT 0,
  `CreatureType` int(11) NOT NULL DEFAULT 0,
  `ResSicknessSpellID` int(11) NOT NULL DEFAULT 0,
  `SplashSoundID` int(11) NOT NULL DEFAULT 0,
  `ClientFilestring` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `CinematicSequenceID` int(11) NOT NULL DEFAULT 0,
  `Alliance` int(11) NOT NULL DEFAULT 0,
  `Name_Lang_enUS` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_enGB` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_koKR` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_frFR` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_deDE` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_enCN` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_zhCN` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_enTW` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_zhTW` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_esES` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_esMX` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_ruRU` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_ptPT` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_ptBR` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_itIT` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_Unk` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_Mask` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `Name_Female_Lang_enUS` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Female_Lang_enGB` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Female_Lang_koKR` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Female_Lang_frFR` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Female_Lang_deDE` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Female_Lang_enCN` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Female_Lang_zhCN` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Female_Lang_enTW` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Female_Lang_zhTW` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Female_Lang_esES` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Female_Lang_esMX` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Female_Lang_ruRU` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Female_Lang_ptPT` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Female_Lang_ptBR` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Female_Lang_itIT` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Female_Lang_Unk` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Female_Lang_Mask` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `Name_Male_Lang_enUS` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Male_Lang_enGB` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Male_Lang_koKR` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Male_Lang_frFR` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Male_Lang_deDE` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Male_Lang_enCN` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Male_Lang_zhCN` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Male_Lang_enTW` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Male_Lang_zhTW` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Male_Lang_esES` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Male_Lang_esMX` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Male_Lang_ruRU` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Male_Lang_ptPT` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Male_Lang_ptBR` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Male_Lang_itIT` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Male_Lang_Unk` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Male_Lang_Mask` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `FacialHairCustomization_1` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `FacialHairCustomization_2` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `HairCustomization` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Required_Expansion` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`guid`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 22 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of dbc_chrraces
-- ----------------------------
INSERT INTO `dbc_chrraces` VALUES
(1, 1, 12, 1, 4140, 49, 50, 'Hu', 7, 7, 15007, 1096, 'Human', 81, 0, 'Human', '', '', 'Humano', 'Mensch', '', '人类', '', '', '', '', 'Человек', '', '', '', '', 16712191, '', '', '', 'Humana', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', 'Humano', 'Mensch', '', '', '', '', '', '', 'Человек', '', '', '', '', 16712172, 'NORMAL', 'PIERCINGS', 'NORMAL', 0),
(2, 2, 12, 2, 4141, 51, 52, 'Or', 1, 7, 15007, 1096, 'Orc', 21, 1, 'Orc', '', '', 'Orco', 'Orc', '', '兽人', '', '', '', '', 'Орк', '', '', '', '', 16712191, '', '', '', 'Orco', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', 'Orco', 'Orc', '', '', '', '', '', '', 'Орк', '', '', '', '', 16712172, 'NORMAL', 'PIERCINGS', 'NORMAL', 0),
(3, 3, 12, 3, 4147, 53, 54, 'Dw', 7, 7, 15007, 1090, 'Dwarf', 41, 0, 'Dwarf', '', '', 'Enano', 'Zwerg', '', '矮人', '', '', '', '', 'Дворф', '', '', '', '', 16712191, '', '', '', 'Enana', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', 'Enano', 'Zwerg', '', '', '', '', '', '', 'Дворф', '', '', '', '', 16712172, 'NORMAL', 'PIERCINGS', 'NORMAL', 0),
(4, 4, 4, 4, 4145, 55, 56, 'Ni', 7, 7, 15007, 1096, 'NightElf', 61, 0, 'Night Elf', '', '', 'Elfo de la noche', 'Nachtelf', '', '暗夜精灵', '', '', '', '', 'Ночной эльф', '', '', '', '', 16712191, '', '', '', 'Elfa de la noche', 'Nachtelfe', '', '', '', '', '', '', 'Ночная эльфийка', '', '', '', '', 16712172, '', '', '', 'Elfo de la noche', 'Nachtelf', '', '', '', '', '', '', 'Ночной эльф', '', '', '', '', 16712172, 'NORMAL', 'MARKINGS', 'NORMAL', 0),
(5, 5, 12, 5, 4142, 57, 58, 'Sc', 1, 7, 15007, 1096, 'Scourge', 2, 1, 'Undead', '', '', 'No-muerto', 'Untoter', '', '亡灵', '', '', '', '', 'Нежить', '', '', '', '', 16712191, '', '', '', 'No-muerta', 'Untote', '', '', '', '', '', '', 'Нежить', '', '', '', '', 16712172, '', '', '', 'No-muerto', 'Untoter', '', '', '', '', '', '', '', '', '', '', '', 16712172, 'FEATURES', 'FEATURES', 'NORMAL', 0),
(6, 6, 14, 6, 4143, 59, 60, 'Ta', 1, 7, 15007, 1096, 'Tauren', 141, 1, 'Tauren', '', '', 'Tauren', 'Tauren', '', '牛头人', '', '', '', '', 'Таурен', '', '', '', '', 16712191, '', '', '', 'Tauren', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', 'Tauren', 'Tauren', '', '', '', '', '', '', 'Таурен', '', '', '', '', 16712172, 'NORMAL', 'HAIR', 'HORNS', 0),
(7, 7, 12, 115, 4146, 1563, 1564, 'Gn', 7, 7, 15007, 1096, 'Gnome', 101, 0, 'Gnome', '', '', 'Gnomo', 'Gnom', '', '侏儒', '', '', '', '', 'Гном', '', '', '', '', 16712190, '', '', '', 'Gnoma', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', 'Gnomo', 'Gnom', '', '', '', '', '', '', 'Гном', '', '', '', '', 16712172, 'NORMAL', 'EARRINGS', 'NORMAL', 0),
(8, 8, 14, 116, 4144, 1478, 1479, 'Tr', 1, 7, 15007, 1096, 'Troll', 121, 1, 'Troll', '', '', 'Trol', 'Troll', '', '巨魔', '', '', '', '', 'Тролль', '', '', '', '', 16712190, '', '', '', 'Trol', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', 'Trol', 'Troll', '', '', '', '', '', '', 'Тролль', '', '', '', '', 16712172, 'TUSKS', 'TUSKS', 'NORMAL', 0),
(9, 9, 1, 1, 0, 6894, 6895, 'Go', 7, 7, 15007, 1096, 'Goblin', 0, 2, 'Goblin', '', '', 'Goblin', 'Goblin', '', '地精', '', '', '', '', 'Гоблин', '', '', '', '', 16712190, '', '', '', 'Goblin', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', 'Goblin', 'Goblin', '', '', '', '', '', '', 'Гоблин', '', '', '', '', 16712172, 'NORMAL', 'NONE', 'NORMAL', 0),
(10, 10, 12, 1610, 4142, 15476, 15475, 'Be', 1, 7, 15007, 1096, 'BloodElf', 162, 1, 'Blood Elf', '', '', 'Elfo de sangre', 'Blutelf', '', '血精灵', '', '', '', '', 'Эльф крови', '', '', '', '', 16712190, '', '', '', 'Elfa de sangre', 'Blutelfe', '', '', '', '', '', '', 'Эльфийка крови', '', '', '', '', 16712172, '', '', '', 'Elfo de sangre', 'Blutelf', '', '', '', '', '', '', 'Эльф крови', '', '', '', '', 16712172, 'NORMAL', 'EARRINGS', 'NORMAL', 1),
(11, 11, 14, 1629, 4140, 16125, 16126, 'Dr', 7, 7, 15007, 1096, 'Draenei', 163, 0, 'Draenei', '', '', 'Draenei', 'Draenei', '', '德莱尼', '', '', '', '', 'Дреней', '', '', '', '', 16712190, '', '', '', 'Draenei', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', 'Draenei', 'Draenei', '', '', '', '', '', '', 'Дреней', '', '', '', '', 16712172, 'NORMAL', 'HORNS', 'NORMAL', 1),
(12, 12, 5, 1, 0, 16981, 16980, 'Fo', 7, 7, 15007, 1096, 'FelOrc', 0, 2, 'Fel Orc', '', '', 'Orco vil', 'Höllenorc', '', '邪兽人', '', '', '', '', 'Орк Скверны', '', '', '', '', 16712190, '', '', '', 'Orco vil', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', 'Orco vil', 'Höllenorc', '', '', '', '', '', '', 'Орк Скверны', '', '', '', '', 16712172, 'NORMAL', 'NORMAL', 'NORMAL', 0),
(13, 13, 1, 1, 0, 17402, 17403, 'Na', 7, 7, 15007, 1096, 'Naga_', 0, 2, 'Naga', '', '', 'Naga', 'Naga', '', '纳迦', '', '', '', '', 'Нага', '', '', '', '', 16712190, '', '', '', 'Naga', '', '', '', '', '', '', '', 'Нага', '', '', '', '', 16712172, '', '', '', 'Naga', 'Naga', '', '', '', '', '', '', 'Наг', '', '', '', '', 16712172, 'Normal', 'Normal', 'Normal', 0),
(14, 14, 5, 1, 0, 17576, 17577, 'Br', 7, 7, 15007, 1096, 'Broken', 0, 2, 'Broken', '', '', 'Tábido', 'Zerschlagener', '', '破碎者', '', '', '', '', 'Падший', '', '', '', '', 16712190, '', '', '', 'Tábida', '', '', '', '', '', '', '', 'Падшая', '', '', '', '', 16712172, '', '', '', 'Tábido', 'Zerschlagener', '', '', '', '', '', '', 'Падший', '', '', '', '', 16712172, 'Normal', 'Normal', 'Normal', 0),
(15, 15, 1, 1, 0, 17578, 17579, 'Sk', 7, 7, 15007, 1096, 'Skeleton', 0, 2, 'Skeleton', '', '', 'Esqueleto', 'Skelett', '', '骷髅', '', '', '', '', 'Скелет', '', '', '', '', 16712190, '', '', '', 'Esqueleto', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', 'Esqueleto', 'Skelett', '', '', '', '', '', '', 'Скелет', '', '', '', '', 16712172, 'Normal', 'Normal', 'Normal', 0),
(16, 16, 9, 1, 0, 21685, 21686, 'Vr', 7, 7, 15007, 1096, 'Vrykul', 0, 2, 'Vrykul', '', '', 'Vrykul', 'Vrykul', '', '维库人', '', '', '', '', 'Врайкул', '', '', '', '', 16712190, '', '', '', 'Vrykul', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', 'Vrykul', 'Vrykul', '', '', '', '', '', '', 'Врайкул', '', '', '', '', 16712172, 'Normal', 'Normal', 'Normal', 0),
(17, 17, 1, 1, 0, 21780, 21781, 'Tu', 7, 7, 15007, 1096, 'Tuskarr', 0, 2, 'Tuskarr', '', '', 'Colmillarr', 'Tuskarr', '', '海象人', '', '', '', '', 'Клыкарр', '', '', '', '', 16712190, '', '', '', 'Colmillarr', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', 'Colmillarr', 'Tuskarr', '', '', '', '', '', '', 'Клыкарр', '', '', '', '', 16712172, 'Normal', 'Normal', 'Normal', 0),
(18, 18, 15, 1, 0, 21963, 21964, 'Ft', 7, 7, 15007, 1096, 'ForestTroll', 0, 2, 'Forest Troll', '', '', 'Trol de bosque', 'Waldtroll', '', '森林巨魔', '', '', '', '', 'Лесной тролль', '', '', '', '', 16712190, '', '', '', 'Trol de bosque', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', 'Trol de bosque', 'Waldtroll', '', '', '', '', '', '', 'Лесной тролль', '', '', '', '', 16712172, 'TUSKS', 'TUSKS', 'Normal', 0),
(19, 19, 5, 1, 0, 26316, 26317, 'Wt', 7, 7, 15007, 1096, 'Taunka', 0, 2, 'Taunka', '', '', 'Taunka', 'Taunka', '', '牦牛人', '', '', '', '', 'Таунка', '', '', '', '', 16712190, '', '', '', 'Taunka', '', '', '', '', '', '', '', 'Таунка', '', '', '', '', 16712172, '', '', '', 'Taunka', 'Taunka', '', '', '', '', '', '', 'Таунка', '', '', '', '', 16712172, 'Normal', 'Normal', 'Normal', 0),
(20, 20, 5, 1, 0, 26871, 26872, 'NS', 7, 7, 15007, 1096, 'NorthrendSkeleton', 0, 2, 'Northrend Skeleton', '', '', 'Esqueleto de Rasganorte', 'Skelett aus Nordend', '', '诺森德骷髅', '', '', '', '', 'Нордскольский скелет', '', '', '', '', 16712190, '', '', '', 'Esqueleto de Rasganorte', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', 'Esqueleto de Rasganorte', 'Skelett aus Nordend', '', '', '', '', '', '', 'Нордскольский скелет', '', '', '', '', 16712172, 'Normal', 'Normal', 'Normal', 0),
(21, 21, 5, 1, 0, 26873, 26874, 'It', 7, 7, 15007, 1096, 'IceTroll', 0, 2, 'Ice Troll', '', '', 'Trol de hielo', 'Eistroll', '', '冰巨魔', '', '', '', '', 'Ледяной тролль', '', '', '', '', 16712190, '', '', '', 'Trol de hielo', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', 'Trol de hielo', 'Eistroll', '', '', '', '', '', '', 'Ледяной тролль', '', '', '', '', 16712172, 'Normal', 'Normal', 'Normal', 0);
