-- ----------------------------
-- Table structure for dbc_questsort
-- ----------------------------
DROP TABLE IF EXISTS `dbc_questsort`;
CREATE TABLE `dbc_questsort`  (
  `ID` int(11) NOT NULL DEFAULT 0,
  `SortName_Lang_enUS` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SortName_Lang_enGB` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SortName_Lang_koKR` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SortName_Lang_frFR` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SortName_Lang_deDE` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SortName_Lang_enCN` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SortName_Lang_zhCN` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SortName_Lang_enTW` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SortName_Lang_zhTW` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SortName_Lang_esES` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SortName_Lang_esMX` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SortName_Lang_ruRU` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SortName_Lang_ptPT` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SortName_Lang_ptBR` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SortName_Lang_itIT` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SortName_Lang_Unk` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `SortName_Lang_Mask` int(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = MyISAM CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of dbc_questsort
-- ----------------------------
INSERT INTO `dbc_questsort` VALUES
(1, 'Epic', '', '', 'Épique', 'Episch', '', '史诗', '', '', 'Épica', '', 'Эпические', '', '', '', '', 16712190),
(21, 'REUSE - old wailing caverns', '', '', 'REUSE - vieilles caves des lamentation', 'REUSE - old wailing caverns', '', '哀嚎洞穴', '', '', 'REUSE - old wailing caverns', '', 'ПОВТОРНО - Пещеры Стенаний', '', '', '', '', 16712190),
(22, 'Seasonal', '', '', 'Saisonnier', 'Saisonbedingt', '', '季节性', '', '', 'Estacional', '', 'Сезонные', '', '', '', '', 16712190),
(23, 'REUSE - old undercity one', '', '', 'REUSE - vieille Fossoyeuse', 'REUSE - old undercity one', '', '幽暗城', '', '', 'REUSE - old undercity one', '', 'ПОВТОРНО - Подгород 1', '', '', '', '', 16712190),
(24, 'Herbalism', '', '', 'Herboristerie', 'Kräuterkunde', '', '草药学', '', '', 'Herboristería', '', 'Травничество', '', '', '', '', 16712190),
(25, 'Battlegrounds', '', '', 'Champs de bataille', 'Schlachtfelder', '', '战场', '', '', 'Campos de batalla', '', 'Поля сражений', '', '', '', '', 16712190),
(41, 'Day of the Dead', '', '', 'REUSE - vieil Uldaman', 'Tag der Toten', '', '悼念日', '', '', 'Festividad de los Muertos', '', 'ПОВТОРНО - Ульдаман', '', '', '', '', 16712190),
(61, 'Warlock', '', '', 'Démoniste', 'Hexenmeister', '', '术士', '', '', 'Brujo', '', 'Чернокнижник', '', '', '', '', 16712190),
(81, 'Warrior', '', '', 'Guerrier', 'Krieger', '', '战士', '', '', 'Guerrero', '', 'Воин', '', '', '', '', 16712190),
(82, 'Shaman', '', '', 'Chaman', 'Schamane', '', '萨满祭司', '', '', 'Chamán', '', 'Шаман', '', '', '', '', 16712190),
(101, 'Fishing', '', '', 'Pêcheur', 'Angeln', '', '钓鱼', '', '', 'Pesca', '', 'Рыбная ловля', '', '', '', '', 16712190),
(121, 'Blacksmithing', '', '', 'Forgeron', 'Schmiedekunst', '', '锻造', '', '', 'Herrería', '', 'Кузнечное дело', '', '', '', '', 16712190),
(141, 'Paladin', '', '', 'Paladin', 'Paladin', '', '圣骑士', '', '', 'Paladín', '', 'Паладин', '', '', '', '', 16712190),
(161, 'Mage', '', '', 'Mage', 'Magier', '', '法师', '', '', 'Mago', '', 'Маг', '', '', '', '', 16712190),
(162, 'Rogue', '', '', 'Voleur', 'Schurke', '', '潜行者', '', '', 'Pícaro', '', 'Разбойник', '', '', '', '', 16712190),
(181, 'Alchemy', '', '', 'Alchimiste', 'Alchemie', '', '炼金术', '', '', 'Alquimia', '', 'Алхимия', '', '', '', '', 16712190),
(182, 'Leatherworking', '', '', 'Travailleur du cuir', 'Lederverarbeitung', '', '制皮', '', '', 'Peletería', '', 'Кожевничество', '', '', '', '', 16712190),
(201, 'Engineering', '', '', 'Ingénieur', 'Ingenieurskunst', '', '工程学', '', '', 'Ingeniería', '', 'Инженерное дело', '', '', '', '', 16712190),
(221, 'Treasure Map', '', '', 'Carte au trésor', 'Schatzkarte', '', '藏宝图', '', '', 'Mapa de tesoro', '', 'Поиск кладов', '', '', '', '', 16712190),
(241, 'Tournament', '', '', 'Tournoi', 'Turnier', '', '锦标赛', '', '', 'Torneo', '', 'Турнир', '', '', '', '', 16712190),
(261, 'Hunter', '', '', 'Chasseur', 'Jäger', '', '猎人', '', '', 'Cazador', '', 'Охотник', '', '', '', '', 16712190),
(262, 'Priest', '', '', 'Prêtre', 'Priester', '', '牧师', '', '', 'Sacerdote', '', 'Жрец', '', '', '', '', 16712190),
(263, 'Druid', '', '', 'Druide', 'Druide', '', '德鲁伊', '', '', 'Druida', '', 'Друид', '', '', '', '', 16712190),
(264, 'Tailoring', '', '', 'Tailleur', 'Schneiderei', '', '裁缝', '', '', 'Sastrería', '', 'Портняжное дело', '', '', '', '', 16712190),
(284, 'Special', '', '', 'Spécial', 'Spezial', '', '特殊', '', '', 'Especial', '', 'Особые', '', '', '', '', 16712190),
(304, 'Cooking', '', '', 'Cuisinier', 'Kochkunst', '', '烹饪', '', '', 'Cocina', '', 'Кулинария', '', '', '', '', 16712190),
(324, 'First Aid', '', '', 'Secourisme', 'Erste Hilfe', '', '急救', '', '', 'Primeros auxilios', '', 'Первая помощь', '', '', '', '', 16712190),
(344, 'Legendary', '', '', 'Légendaire', 'Legendär', '', '传说', '', '', 'Legendaria', '', 'Легенды', '', '', '', '', 16712190),
(364, 'Darkmoon Faire', '', '', 'Foire de Sombrelune', 'Dunkelmond-Jahrmarkt', '', '暗月马戏团', '', '', 'Feria de la Luna Negra', '', 'Ярмарка Новолуния', '', '', '', '', 16712190),
(365, 'Ahn\'Qiraj War', '', '', 'Guerre d\'Ahn\'Qiraj', 'Krieg von Ahn\'Qiraj', '', '安其拉战争', '', '', 'Guerra de Ahn\'Qiraj', '', 'Ан\'киражская война', '', '', '', '', 16712190),
(366, 'Lunar Festival', '', '', 'Fête lunaire', 'Mondfest', '', '新年', '', '', 'Festival Lunar', '', 'Лунный фестиваль', '', '', '', '', 16712190),
(367, 'Reputation', '', '', 'Réputation', 'Ruf', '', '声望', '', '', 'Reputación', '', 'Репутация', '', '', '', '', 16712190),
(368, 'Invasion', '', '', 'Invasion', 'Invasion der Geißel', '', '天灾入侵', '', '', 'Invasión', '', 'Вторжение', '', '', '', '', 16712190),
(369, 'Midsummer', '', '', 'Solstice d\'été', 'Sonnenwendfest', '', '仲夏', '', '', 'Verano', '', 'Огненный солнцеворот', '', '', '', '', 16712190),
(370, 'Brewfest', '', '', 'Fête des Brasseurs', 'Braufest', '', '美酒节', '', '', 'Fiesta de la cerveza', '', 'Хмельной фестиваль', '', '', '', '', 16712190),
(371, 'Inscription', '', '', 'Calligraphie', 'Inschriftenkunde', '', '铭文', '', '', 'Inscripción', '', 'Начертание', '', '', '', '', 16712190),
(372, 'Death Knight', '', '', 'Chevalier de la mort', 'Todesritter', '', '死亡骑士', '', '', 'Caballero de la Muerte', '', 'Рыцарь смерти', '', '', '', '', 16712190),
(373, 'Jewelcrafting', '', '', 'Joaillerie', 'Juwelenschleifen', '', '珠宝加工', '', '', 'Joyería', '', 'Ювелирное дело', '', '', '', '', 16712190),
(374, 'Noblegarden', '', '', 'Jardin des nobles', 'Nobelgarten', '', '复活节', '', '', 'Jardín Noble', '', 'Сад чудес', '', '', '', '', 16712190),
(375, 'Pilgrim\'s Bounty', '', '', 'Bienfaits du pèlerin', 'Pilgerfreuden', '', '感恩节', '', '', 'Generosidad del Peregrino', '', 'Пиршество странников', '', '', '', '', 16712190),
(376, 'Love is in the Air', '', '', 'De l\'amour dans l\'air', 'Liebe liegt in der Luft', '', '情人节', '', '', 'Amor en el aire', '', 'Любовная лихорадка', '', '', '', '', 16712190);
