-- ----------------------------
-- Table structure for dbc_itemlimitcategory
-- ----------------------------
DROP TABLE IF EXISTS `dbc_itemlimitcategory`;
CREATE TABLE `dbc_itemlimitcategory`  (
  `ID` int(11) NOT NULL DEFAULT 0,
  `Name_Lang_enUS` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_enGB` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_koKR` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_frFR` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_deDE` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_enCN` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_zhCN` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_enTW` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_zhTW` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_esES` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_esMX` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_ruRU` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_ptPT` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_ptBR` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_itIT` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_Unk` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `Name_Lang_Mask` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `Quantity` int(11) NOT NULL DEFAULT 0,
  `Flags` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = MyISAM CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of dbc_itemlimitcategory
-- ----------------------------
INSERT INTO `dbc_itemlimitcategory` VALUES
(2, 'Jeweler\'s Gems', '', '', 'Gemmes de joaillier', 'Juwelierssteine', '', '珠宝匠的宝石', '', '', 'Gemas de joyero', '', 'Самоцветы ювелира', '', '', '', '', 16712190, 3, 1),
(3, 'Healthstone', '', '', 'Pierre de soins', 'Gesundheitsstein', '', '治疗石', '', '', 'Piedra de salud', '', 'Камень здоровья', '', '', '', '', 16712190, 1, 0),
(4, 'Mana Gem', '', '', 'Gemme de mana', 'Manaedelstein', '', '法力宝石', '', '', 'Gema de maná', '', 'Самоцвет маны', '', '', '', '', 16712190, 1, 0),
(6, 'Stormjewel', '', '', 'Joyau-tempête', 'Sturmjuwel', '', '风暴宝钻', '', '', 'Joya de tormenta', '', 'Самоцвет бури', '', '', '', '', 16712190, 1, 1),
(7, 'Enchanted Pearl', '', '', 'Perle enchantée', 'Verzauberte Perle', '', '魔化珍珠', '', '', 'Perla encantada', '', 'Зачарованная жемчужина', '', '', '', '', 16712190, 1, 1),
(8, 'Binding Light', '', '', 'Lien de lumière', 'Bindendes Licht', '', '禁锢之光', '', '', 'Luz vinculante', '', 'Связующий свет', '', '', '', '', 16712190, 1, 1),
(9, 'Binding Stone', '', '', 'Lien de pierre', 'Bindendes Gestein', '', '束缚之石', '', '', 'Piedra vinculante', '', 'Связующий камень', '', '', '', '', 16712190, 1, 1),
(10, 'Death\'s Choice', '', '', 'Choix de la mort', 'Des Todes Wahl', '', '死亡的选择', '', '', 'Elección de la Muerte', '', 'Выбор смерти', '', '', '', '', 16712190, 1, 1),
(11, 'Death\'s Verdict', '', '', 'Verdict de la mort', 'Des Todes Urteil', '', '死亡的裁决', '', '', 'Veredicto de la muerte', '', 'Приговор смерти', '', '', '', '', 16712190, 1, 1),
(12, 'Eitrigg\'s Oath', '', '', 'Serment d\'Eitrigg', 'Etriggs Schwur', '', '伊崔格的誓约', '', '', 'Juramento de Eitrigg', '', 'Клятва Эйтригга', '', '', '', '', 16712190, 1, 1),
(13, 'Fervor of the Frostborn', '', '', 'Ferveur des Givre-nés', 'Eifer der Frosterben', '', '霜脉矮人的热忱', '', '', 'Fervor de los Natoescarcha', '', 'Страсть Закаленных Бурей', '', '', '', '', 16712190, 1, 1),
(14, 'Fetish of Volatile Power', '', '', 'Fétiche du pouvoir volatil', 'Fetisch der flüchtigen Macht', '', '动荡能量雕像', '', '', 'Fetiche de poder volátil', '', 'Фетиш неустойчивой силы', '', '', '', '', 16712190, 1, 1),
(15, 'Juggernaut\'s Vitality', '', '', 'Vitalité du mastodonte', 'Vitalität des Molochs', '', '主宰之力', '', '', 'Vitalidad del gigante', '', 'Жизненная сила Джаганнатха', '', '', '', '', 16712190, 1, 1),
(16, 'Reign of the Dead', '', '', 'Règne de la mort', 'Herrschaft der Toten', '', '亡者的统治', '', '', 'Reino de los muertos', '', 'Власть мертвых', '', '', '', '', 16712190, 1, 1),
(17, 'Reign of the Unliving', '', '', 'Règne des non-vivants', 'Herrschaft der Leblosen', '', '死者的统治', '', '', 'Reino de los sin vida', '', 'Власть неживых', '', '', '', '', 16712190, 1, 1),
(18, 'Satrina\'s Impeding Scarab', '', '', 'Scarabée d\'obstruction de Satrina', 'Satrinas hemmender Skarabäus', '', '萨崔娜的抗阻甲虫', '', '', 'Escarabajo trabador de Satrina', '', 'Упрямый скарабей Сатрины', '', '', '', '', 16712190, 1, 1),
(19, 'Solace of the Defeated', '', '', 'Réconfort des vaincus', 'Trost der Besiegten', '', '战败者的慰藉', '', '', 'Consuelo de los derrotados', '', 'Утешение поверженных', '', '', '', '', 16712190, 1, 1),
(20, 'Solace of the Fallen', '', '', 'Réconfort des défunts', 'Trost der Gefallenen', '', '阵亡者的慰藉', '', '', 'Consuelo de los caídos', '', 'Утешение павших', '', '', '', '', 16712190, 1, 1),
(21, 'Talisman of Volatile Power', '', '', 'Talisman du pouvoir volatil', 'Talisman der flüchtigen Macht', '', '动荡能量饰物', '', '', 'Dije de poder volátil', '', 'Талисман неустойчивой силы', '', '', '', '', 16712190, 1, 1),
(22, 'Vengeance of the Forsaken', '', '', 'Vengeance des Réprouvés', 'Rache der Verlassenen', '', '被遗忘者的复仇', '', '', 'Venganza de los Renegados', '', 'Отмщение Отрекшихся', '', '', '', '', 16712190, 1, 1),
(23, 'Victor\'s Call', '', '', 'Appel de la victoire', 'Ruf des Siegers', '', '胜者的召唤', '', '', 'Llamada de Victor', '', 'Зов Виктора', '', '', '', '', 16712190, 1, 1),
(24, 'Band of Callous Aggression', '', '', 'Bague de l\'agression cruelle', 'Band der gleichgültigen Aggression', '', '无情侵掠指环', '', '', 'Sortija de agresión inconmovible', '', 'Кольцо бездушной агрессии', '', '', '', '', 16712190, 1, 0),
(25, 'Band of Deplorable Violence', '', '', 'Bague de violence déplorable', 'Band der bedauernswerten Gewalt', '', '恶行指环', '', '', 'Sortija de violencia deplorable', '', 'Кольцо удручающего насилия', '', '', '', '', 16712190, 1, 1),
(26, 'Band of the Traitor King', '', '', 'Bague du roi traître', 'Band des Verräterkönigs', '', '叛君指环', '', '', 'Sortija del rey traidor', '', 'Кольцо короля-предателя', '', '', '', '', 16712190, 1, 0),
(27, 'Band of the Twin Val\'kyr', '', '', 'Bague des Val\'kyrs jumelles', 'Band der Zwillingsval\'kyr', '', '双姝指环', '', '', 'Sortija de las Gemelas Val\'kyr', '', 'Кольцо валь\'кир-близнецов', '', '', '', '', 16712190, 1, 1),
(28, 'Band of the Violent Temperment', '', '', 'Bague du tempérament violent', 'Band des wilden Temperaments', '', '暴虐指环', '', '', 'Sortija del temperamento violento', '', 'Кольцо жестокого характера', '', '', '', '', 16712190, 1, 1),
(29, 'Carnivorous Band', '', '', 'Anneau carnivore', 'Fleischfressendes Band', '', '食肉兽指环', '', '', 'Sortija carnívora', '', 'Кольцо хищника', '', '', '', '', 16712190, 1, 1),
(30, 'Circle of the Darkmender', '', '', 'Cercle du sombre réparateur', 'Kreis des Dunkelheilers', '', '黑暗治愈者指环', '', '', 'Aro del Ensalmador oscuro', '', 'Обруч Темной Целительницы', '', '', '', '', 16712190, 1, 1),
(31, 'Firestorm Band', '', '', 'Bague tempête-de-feu', 'Feuersturmband', '', '火焰风暴指环', '', '', 'Sortija de tormenta de fuego', '', 'Кольцо Огненной Бури', '', '', '', '', 16712190, 1, 1),
(32, 'Firestorm Ring', '', '', 'Anneau tempête-de-feu', 'Feuersturmring', '', '火焰风暴之戒', '', '', 'Anillo de tormenta de fuego', '', 'Перстень Огненной Бури', '', '', '', '', 16712190, 1, 1),
(33, 'Gormok\'s Band', '', '', 'Bague de Gormok', 'Gormoks Band', '', '戈莫克的指环', '', '', 'Sortija de Gormok', '', 'Кольцо Гормока', '', '', '', '', 16712190, 1, 1),
(34, 'Loop of the Twin Val\'kyr', '', '', 'Jonc des Val\'kyrs jumelles', 'Schleife der Zwillingsval\'kyr', '', '双姝之戒', '', '', 'Aro de las Gemelas Val\'kyr', '', 'Петля валь\'кир-близнецов', '', '', '', '', 16712190, 1, 1),
(35, 'Lurid Manifestation', '', '', 'Manifestation horrible', 'Blutrünstige Offenbarung', '', '血红显像之戒', '', '', 'Manifestación escabrosa', '', 'Проявление Лурида', '', '', '', '', 16712190, 1, 1),
(36, 'Planestalker Band', '', '', 'Bague du traqueur des plans', 'Ebenenpirscherband', '', '巡界指环', '', '', 'Sortija de acechallanos', '', 'Кольцо ловца граней', '', '', '', '', 16712190, 1, 1),
(37, 'Planestalker Signet', '', '', 'Chevalière du traqueur des plans', 'Ebenenpirschersiegel', '', '巡界徽记', '', '', 'Sello de acechallanos', '', 'Перстень ловца граней', '', '', '', '', 16712190, 1, 1),
(38, 'Ring of Callous Aggression', '', '', 'Anneau de l\'agression cruelle', 'Ring der gleichgültigen Aggression', '', '无情侵掠之戒', '', '', 'Anillo de agresión inconmovible', '', 'Перстень бездушной агрессии', '', '', '', '', 16712190, 1, 1),
(39, 'Ring of Callous Aggression', '', '', 'Anneau de l\'agression cruelle', 'Ring der gleichgültigen Aggression', '', '无情侵掠之戒', '', '', 'Anillo de agresión inconmovible', '', 'Перстень бездушной агрессии', '', '', '', '', 16712190, 1, 1),
(40, 'Ring of the Darkmender', '', '', 'Anneau du sombre réparateur', 'Ring des Dunkelheilers', '', '黑暗治愈者之戒', '', '', 'Anillo del Ensalmador oscuro', '', 'Перстень Темной Целительницы', '', '', '', '', 16712190, 1, 1),
(41, 'Ring of the Violent Temperament', '', '', 'Anneau du tempérament violent', 'Ring des wilden Temperaments', '', '暴戾指环', '', '', 'Anillo del temperamento violento', '', 'Перстень жестокого характера', '', '', '', '', 16712190, 1, 1),
(42, 'Signet of the Traitor King', '', '', 'Chevalière du roi traître', 'Siegel des Verräterkönigs', '', '叛君徽记', '', '', 'Sello del rey traidor', '', 'Перстень короля-предателя', '', '', '', '', 16712190, 1, 1),
(43, 'Test Ring Limit', '', '', 'Limite de l\'anneau test', 'Test Ringlimit', '', 'Test Ring Limit', '', '', 'Probar límite de anillo', '', 'Test Ring Limit', '', '', '', '', 16712190, 1, 1),
(44, 'Althor\'s Abacus', '', '', 'Boulier d\'Althor', 'Althors Abakus', '', '阿尔索的算盘', '', '', 'Ábaco de Althor', '', 'Счеты Алтора', '', '', '', '', 16712190, 1, 1),
(45, 'Bauble of True Blood', '', '', 'Verroterie du sang véritable', 'Schmuckstück des wahren Blutes', '', '纯血珠饰', '', '', 'Adorno de sangre verdadera', '', 'Подвеска истинной крови', '', '', '', '', 16712190, 1, 1),
(46, 'Corpse Tongue Coin', '', '', 'Pièce du passeur', 'Fährmünze der Toten', '', '镇魂币', '', '', 'Moneda de la lengua de un cadáver', '', 'Монета на удачу', '', '', '', '', 16712190, 1, 1),
(47, 'Deathbringer\'s Will', '', '', 'Volonté de porte-mort', 'Wille des Todesbringers', '', '死神的意志', '', '', 'Testamento del Libramorte', '', 'Воля Смертоносного', '', '', '', '', 16712190, 1, 1),
(48, 'Dislodged Foreign Object', '', '', 'Objet étranger déplacé', 'Entferntes Fremdobjekt', '', '被摘除的外物', '', '', 'Objeto desprendido extraño', '', 'Объект из другого измерения', '', '', '', '', 16712190, 1, 1),
(49, 'Phylactery of the Nameless Lich', '', '', 'Phylactère de la liche sans nom', 'Phylakterium des namenlosen Lichs', '', '无名巫妖的护符匣', '', '', 'Filacteria del exánime innombrable', '', 'Талисман безымянного лича', '', '', '', '', 16712190, 1, 1),
(50, 'Tiny Abomination in a Jar', '', '', 'Petite abomination en bouteille', 'Winzige Monstrosität im Glas', '', '瓶中的小憎恶', '', '', 'Abominación diminuta en un tarro', '', 'Миниатюрное поганище в колбе', '', '', '', '', 16712190, 1, 1),
(51, 'Sindragosa\'s Flawless Fang', '', '', 'Croc parfait de Sindragosa', 'Sindragosas fehlerloser Fangzahn', '', '完美之牙', '', '', 'Colmillo impecable de Sindragosa', '', 'Безупречный клык Синдрагосы', '', '', '', '', 16712190, 1, 1),
(52, 'Abomination\'s Bloody Ring', '', '', 'Anneau sanglant d\'abomination', 'Blutiger Ring der Monstrosität', '', '憎恶血戒', '', '', 'Anillo sangriento de abominación', '', 'Окровавленное кольцо поганища', '', '', '', '', 16712190, 1, 1),
(53, 'Signet of Putrefaction', '', '', 'Chevalière de putréfaction', 'Siegelring der Fäulnis', '', '腐败徽记', '', '', 'Sello de putrefacción', '', 'Печатка гниения', '', '', '', '', 16712190, 1, 1),
(54, 'Cerise Coiled Ring', '', '', 'Anneau torsadé cerise', 'Kirschroter verschlungener Ring', '', '樱红缠丝指环', '', '', 'Anillo enrollado color guinda', '', 'Плетеное рубиновое кольцо', '', '', '', '', 16712190, 1, 1),
(55, 'Rotface\'s Rupturing Ring', '', '', 'Anneau de rupture de Trognepus', 'Modermienes reißender Ring', '', '腐面的破碎指环', '', '', 'Anillo desintegrador de Carapútrea', '', 'Разрушающее кольцо Гниломорда', '', '', '', '', 16712190, 1, 1),
(56, 'Saurfang\'s Cold-Forged Band', '', '', 'Anneau de Saurcroc forgé à froid', 'Saurfangs kaltgeschmiedetes Band', '', '萨鲁法尔的寒铸指环', '', '', 'Sortija forjada en frío de Colmillosauro', '', 'Закаленное льдом кольцо Саурфанга', '', '', '', '', 16712190, 1, 1),
(57, 'Seal of the Twilight Queen', '', '', 'Sceau de la reine du crépuscule', 'Siegel der Zwielichtkönigin', '', '暮光女王的印记', '', '', 'Sello de la Reina del Crepúsculo', '', 'Печать королевы сумерек', '', '', '', '', 16712190, 1, 1),
(58, 'Thrice Fanged Signet', '', '', 'Chevalière aux trois crocs', 'Dreigezahntes Signet', '', '三牙饰物', '', '', 'Sello de tres colmillos', '', 'Печатка тройных клыков', '', '', '', '', 16712190, 1, 1),
(59, 'Band of the Bone Colossus', '', '', 'Bague du colosse d\'os', 'Band des Knochenkolosses', '', '白骨巨人指环', '', '', 'Sortija del coloso de hueso', '', 'Кольцо костяного колосса', '', '', '', '', 16712190, 1, 1),
(60, 'Devium\'s Eternally Cold Ring', '', '', 'Anneau éternellement froid de Devium', 'Deviums ewigkalter Ring', '', '永冻指环', '', '', 'Anillo eternamente frío de Devium', '', 'Вечно холодное кольцо Девия', '', '', '', '', 16712190, 1, 1),
(61, 'Seal of Many Mouths', '', '', 'Sceau des bouches nombreuses', 'Siegel der vielen Münder', '', '千口之戒', '', '', 'Sello de muchas bocas', '', 'Печать сонма ртов', '', '', '', '', 16712190, 1, 1),
(62, 'Frostbrood Sapphire Ring', '', '', 'Anneau en saphir couvegivre', 'Saphirring der Frostbrut', '', '霜脉蓝玉指环', '', '', 'Anillo de zafiro Razaescarcha', '', 'Сапфировое кольцо ледяного наследия', '', '', '', '', 16712190, 1, 1),
(63, 'Juggernaut Band', '', '', 'Bague de mastodonte', 'Molochband', '', '蛮力指环', '', '', 'Sortija de gigante', '', 'Кольцо владыки мира', '', '', '', '', 16712190, 1, 1),
(64, 'Loop of the Endless Labyrinth', '', '', 'Jonc de labyrinthe sans fin', 'Fingerreif des endlosen Labyrinths', '', '无尽迷宫指环', '', '', 'Aro del laberinto interminable', '', 'Кольцо бесконечного лабиринта', '', '', '', '', 16712190, 1, 1),
(65, 'Marrowgar\'s Frigid Eye', '', '', 'Oeil glacial de Gargamoelle', 'Mark\'gars kaltes Auge', '', '玛洛加尔的寒冰之瞳', '', '', 'Ojo gélido de Tuétano', '', 'Хладное око Ребрада', '', '', '', '', 16712190, 1, 1),
(66, 'Memory of Malygos', '', '', 'Mémoire de Malygos', 'Erinnerung von Malygos', '', '玛利苟斯的回忆', '', '', 'Memoria de Malygos', '', 'Память Малигоса', '', '', '', '', 16712190, 1, 1),
(67, 'Might of Blight', '', '', 'Puissance de chancre', 'Macht der Seuche', '', '凋零之力', '', '', 'Poderío de añublo', '', 'Сила порчи', '', '', '', '', 16712190, 1, 1),
(68, 'Ring of Maddening Whispers', '', '', 'Anneau de murmures exaspérants', 'Ring des Unerträglichen Flüsterns', '', '狂语之戒', '', '', 'Anillo de susurros enloquecedores', '', 'Кольцо сводящего с ума шепота', '', '', '', '', 16712190, 1, 1),
(69, 'Ring of Rapid Ascent', '', '', 'Anneau d\'ascension rapide', 'Ring des Schnellen Aufstiegs', '', '飞升之戒', '', '', 'Anillo de rápido ascenso', '', 'Перстень стремительного восхождения', '', '', '', '', 16712190, 1, 1),
(70, 'Skeleton Lord\'s Circle', '', '', 'Cercle de seigneur squelette', 'Kreis des Skelettfürsten', '', '骷髅领主之环', '', '', 'Círculo de señor esqueleto', '', 'Кольцо повелителя скелетов', '', '', '', '', 16712190, 1, 1),
(71, 'Valanar\'s Other Signet Ring', '', '', 'Autre chevalière de Valanar', 'Valanars anderer Siegelring', '', '瓦拉纳的备用徽记之戒', '', '', 'El otro sello de Valanar', '', 'Второй перстень-печатка Валанара', '', '', '', '', 16712190, 1, 1),
(72, 'Incarnadine Band of Mending', '', '', 'Bague de guérison incarnadine', 'Blutrotes Heilungsband', '', '愈合血环', '', '', 'Sortija de alivio encarnada', '', 'Кроваво-красное кольцо лечения', '', '', '', '', 16712190, 1, 1),
(73, 'Muradin\'s Spyglass', '', '', 'Longue-vue de Muradin', 'Muradins Handfernrohr', '', '穆拉丁的望远镜', '', '', 'Catalejo de Muradin', '', 'Подзорная труба Мурадина', '', '', '', '', 16712190, 1, 1),
(74, 'Sliver of Pure Ice', '', '', 'Esquille de glace pure', 'Splitter aus reinem Eis', '', '纯冰薄片', '', '', 'Esquirla de hielo puro', '', 'Осколок чистейшего льда', '', '', '', '', 16712190, 1, 1),
(75, 'Unidentifiable Organ', '', '', 'Organe non identifiable', 'Unidentifizierbares Organ', '', '未鉴定的器官', '', '', 'Órgano inidentificable', '', 'Неизвестный орган', '', '', '', '', 16712190, 1, 1),
(76, 'Whispering Fanged Skull', '', '', 'Crâne à crocs murmurant', 'Flüsternder Gezahnter Schädel', '', '密语尖牙颅骨', '', '', 'Calavera dentuda susurrante', '', 'Шепчущий клыкастый череп', '', '', '', '', 16712190, 1, 1),
(77, 'Twilight Scale', '', '', 'Ecaille du crépuscule', 'Zwielichtschuppe', '', '暮光龙鳞', '', '', 'Escama Crepuscular', '', 'Сумеречная чешуя', '', '', '', '', 16712190, 1, 1),
(78, 'Ring of Phased Regeneration', '', '', 'Anneau de régénération phasée', 'Ring der phasenweisen Regeneration', '', '定相恢复之戒', '', '', 'Anillo de regeneración por fase', '', 'Перстень постепенной регенерации', '', '', '', '', 16712190, 1, 1),
(79, 'Saviana\'s Tribute', '', '', 'Offrande à Saviana', 'Savianas Tribut', '', '塞维娅娜的贡品', '', '', 'Tributo a Saviana', '', 'Подношение Савианы', '', '', '', '', 16712190, 1, 1),
(80, 'Signet of Twilight', '', '', 'Chevalière de crépuscule', 'Siegel des Zwielichts', '', '暮光徽记', '', '', 'Sello de crepúsculo', '', 'Печатка Сумеречного Молота', '', '', '', '', 16712190, 1, 1),
(81, 'Zarithrian\'s Offering', '', '', 'Offrande de Zarithrian', 'Zarithrians Opfergabe', '', '萨瑞瑟里安的贡奉', '', '', 'Ofrenda de Zarithrian', '', 'Подношение Заритриана', '', '', '', '', 16712190, 1, 1),
(82, 'Sharpened Twilight Scale', '', '', 'Ecaille du crépuscule aiguisée', 'Geschärfte Zwielichtschuppe', '', '锐锋暮光龙鳞', '', '', 'Escama Crepuscular afilada', '', 'Заостренная сумеречная чешуя', '', '', '', '', 16712190, 1, 1),
(83, 'Petrified Twilight Scale', '', '', 'Ecaille du crépuscule pétrifiée', 'Versteinerte Zwielichtschuppe', '', '石化暮光龙鳞', '', '', 'Escama Crepuscular petrificada', '', 'Окаменелая сумеречная чешуя', '', '', '', '', 16712190, 1, 1),
(84, 'Glowing Twilight Scale', '', '', 'Ecaille du crépuscule luminescente', 'Leuchtende Zwielichtschuppe', '', '明亮暮光龙鳞', '', '', 'Escama Crepuscular resplandeciente', '', 'Светящаяся сумеречная чешуя', '', '', '', '', 16712190, 1, 1),
(85, 'Charred Twilight Scale', '', '', 'Ecaille du crépuscule carbonisée', 'Verkohlte Zwielichtschuppe', '', '焦黑暮光龙鳞', '', '', 'Escama Crepuscular carbonizada', '', 'Обугленная сумеречная чешуя', '', '', '', '', 16712190, 1, 1);
