INSERT INTO `world_config`(`OptionName`, `Type`, `IDInTypeGroup`, `DefaultValue`, `CustomValue`, `Description`) VALUES 
('VanishVisionTimer', 'int', 188, '600', NULL, 'Vanish Fade Delay (vanish evade all spells without CC control in this time) (in ms)'),
('VanishCCbreakTimer', 'int', 189, '300', NULL, 'Vanish Should evade CC spells too, when casted, but it\'s a little lime.'),
('AntiCheats.FlyHackTimer', 'int', 190, '3000', NULL, 'Timer for AntiCheat FlyHack check #Default: 3000 - 1 check in 1 second'),
('FLAB.Script.MaxChars', 'int', 191, '0', NULL, 'Count of characters for give a bonus #Default:     0 - it should be a first character on acc, right?'),
('FLAB.Script.BonusMoney', 'int', 192, '10000000', NULL, 'Count of money ( 1000 gold )'),
('PVPBonusCapReward.MaxCap', 'int', 193, '1500', NULL, 'Max values for Weekly Cap'),
('PVPBonusCapReward.CapChanges.Win', 'int', 194, '180', NULL, 'Value for cap after Win'),
('PVPBonusCapReward.CapChanges.Lose', 'int', 195, '60', NULL, 'Value for cap after Lose'),
('Antispam.Mail.Timer', 'int', 196, '3600', NULL, 'Timer for possible next sending count of mails by mailbox'),
('Antispam.Mail.Count', 'int', 197, '10', NULL, 'How many mails you can sent in game in 1 period of timer'),
('Antispam.Mail.Controller', 'int', 198, '100', NULL, 'How many mails player can hold in mailbox, include mail in future (from auctionhouse and calendar).'),
('BAG.Script.BonusBagsID', 'int', 199, '51809', NULL, 'itemid of bags ( 51809 )'),
('GSystem.GuildWars.Minimal.PlayerCount', 'int', 200, '10', NULL, 'minimal count of members in guild for participation in GW'),
('GSystem.GuildWars.Minimal.Delta.PreviousStartTimer', 'int', 201, '3600', NULL, 'minimal timer for guild from previous start war time for starting a new war'),
('GSystem.GuildWars.Minimal.Delta.PreviousEndTimer', 'int', 202, '3600', NULL, 'minimal timer for guild from previous end war time for starting a new war'),
('GSystem.GuildLevel.Exp.ForArena', 'int', 203, '5', NULL, 'exp of guild for Win on Arena of each guild member'),
('GSystem.GuildLevel.Exp.ForBG', 'int', 204, '1', NULL, 'exp of guild for Win on BG of each guild member'),
('GSystem.GuildLevel.Exp.ForLFG', 'int', 205, '1', NULL, 'exp of guild for Win on LFG of each guild member'),
('GSystem.GuildWars.Exp.ForEnemyGuildKill', 'int', 206, '1', NULL, 'reward guild by exp for killing members of enemy guild (in GW status). Depend from GSystem.GuildLevel.Enabled'),
('GSystem.GuildWars.Exp.ForWinnerOfGW', 'int', 207, '250', NULL, 'reward winner guild by exp for Win in Guild Wars'),
('GSystem.GuildWars.Exp.ForLoserOfGW', 'int', 208, '100', NULL, 'reward winner guild by exp for Lose in Guild Wars'),
('GSystem.GuildLevel.LvL.ForMyBank', 'int', 209, '5', NULL, 'Level of guild for opening MyBank func'),
('GSystem.GuildLevel.LvL.ForRepair', 'int', 210, '3', NULL, 'Level of guild for opening Repair func'),
('DalaranGEvent.Min.Players', 'int', 211, '5', NULL, 'DalaranCrater Event minimal players');
