INSERT INTO `world_config`(`OptionName`, `Type`, `IDInTypeGroup`, `DefaultValue`, `CustomValue`, `Description`) VALUES 
('CheckM2ObjectLoS', 'bool', 95, '1', NULL, 'Include M2 objects (trees etc.) in line of sight checks.'),
('AntiCheats.FakeJumper.Enabled', 'bool', 96, '1', NULL, 'Enable AntiCheat.FakeJumper : when player sent a move opcode (with new Z higher) when has flag falling (client can\'t sent any new packets when falling) It\'s normal for Gagarin hacks and with Air Mode + \"space\" click = \"falling\" mode (player can\'t change orientation of flying, but it move up)'),
('AntiCheats.FakeFlyingmode.Enabled', 'bool', 97, '1', NULL, 'Enable AntiCheat.FakeFlyingmode : when player sent a move opcode with added fly flag but on server this flag doesn\'t restricted for player. It\'s normal for Hitchhiker\'s Hack with Air Mode'),
('AntiCheats.DoubleJump.Enabled', 'bool', 98, '1', NULL, 'Enable AntiCheat.DoubleJump Kick when player sent opcode jump when has flag falling (client can\'t do this)'),
('AntiCheats.FlyHack.Enabled', 'bool', 99, '1', NULL, 'Enable AntiCheat.FlyHack'),
('AntiCheats.SpeedHack.Enabled', 'bool', 100, '1', NULL, 'Enable AntiCheat.SpeedHack'),
('AntiCheats.IgnoreControlMovement.Enabled', 'bool', 101, '1', NULL, 'Enable AntiCheat.IgnoreControlMovement : when player in root state - client can\'t send a new movement packets'),
('AntiCheats.SpeedHack.Kick.Enabled', 'bool', 102, '1', NULL, 'Enable AntiCheat.SpeedHack Kick when detected'),
('AntiCheats.FlyHack.Kick.Enabled', 'bool', 103, '1', NULL, 'Enable AntiCheat.FlyHack Kick when detected'),
('AntiCheats.FakeJumper.Kick.Enabled', 'bool', 104, '1', NULL, 'Enable AntiCheats.FakeJumper Kick when detected'),
('AntiCheats.FakeFlyingmode.Kick.Enabled', 'bool', 105, '1', NULL, 'Enable AntiCheats.FakeFlyingmode Kick when detected'),
('AntiCheats.NoFallingDmg.Kick.Enabled', 'bool', 106, '1', NULL, 'Enable AntiCheats.NoFallingDmg Kick when detected'),
('CrossfactionBG.enable', 'bool', 107, '1', NULL, 'Mixed battleground'),
('GSystem.LootBroadcast.Enabled', 'bool', 108, '1', NULL, 'Guild announce when member take a loot with Quality >= EPIC'),
('FLAB.Script.Enabled', 'bool', 109, '1', NULL, 'First character on account will receive a money bonus'),
('LFG.Channel.Everywhere', 'bool', 110, '1', NULL, 'Allow access at LookupForGroup channel to characters without condition of LFG state.'),
('Config.Vip.Debuff.Command', 'bool', 111, '0', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Bank.Command', 'bool', 112, '0', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Mail.Command', 'bool', 113, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Repair.Command', 'bool', 114, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Reset.Talents.Command', 'bool', 115, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Taxi.Command', 'bool', 116, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Home.Command', 'bool', 117, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Change.Race.Command', 'bool', 118, '0', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Customize.Command', 'bool', 119, '0', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Capital.Command', 'bool', 120, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Appear.Command', 'bool', 121, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Item.Helper', 'bool', 122, '1', NULL, 'Enable/Disable Item helper in game'),
('RaidInfo.Enabled', 'bool', 123, '1', NULL, 'Enable/Disable custom raid info system for world announce of killed bosses'),
('PVPBonusCapReward.Enabled', 'bool', 124, '1', NULL, 'Enable/Disable custom PVP bonus cap reward for arena. It give bonus weekly reward when cap is complited (1500/1500 by default)'),
('LFG.CrossFaction.Groups', 'bool', 125, '1', NULL, 'Enable/Disable custom system for crossfaction DungeonFinder groups'),
('OSXPlayers.Enabled', 'bool', 126, '1', NULL, 'We can block connect for players from OSX OS system'),
('Antispam.Mail.Enabled', 'bool', 127, '1', NULL, 'When player will receive this limit, he just can\'t bid or bidout from auction. Calendar will not sent mail him.  And another player can\'t sent mail to him, just will see error overloaded mailbox of receiver.'),
('Chat.StrictMessages.Enabled', 'bool', 128, '1', NULL, 'Limit player message to language specific symbol set. Prevents character messages and ignore request if not allowed symbols are used'),
('BAG.Script.Enabled', 'bool', 129, '1', NULL, 'Created character will receive a bags bonus'),
('StartPack.Script.Enabled', 'bool', 130, '1', NULL, 'Give a possibility to receive start-pack items from item helper'),
('DuelPhase.Enabled', 'bool', 131, '1', NULL, 'Make a special phase for duel members, they will see only oponent, and can\'t see others units'),
('GSystem.GuildLevel.Enabled', 'bool', 132, '1', NULL, 'Make a possible guild level system'),
('GSystem.GuildWars.Enabled', 'bool', 133, '1', NULL, 'Give possibility to make Guild Wars between guilds'),
('GSystem.GuildWars.BetweenBothFaction.Enabled', 'bool', 134, '1', NULL, 'Give possibility to make Guild Wars between guilds from both faction (Alliance and Horde)'),
('GSystem.GuildLevel.ShowLevelGuild.WhoList.Enabled', 'bool', 135, '1', NULL, 'Make a visible guild level in whoList'),
('GSystem.GuildLevel.ShowLevelGuild.QueryList.Enabled', 'bool', 136, '1', NULL, 'Make a visible guild level in query opcode (visible name/guild above character)'),
('GSystem.GuildWars.ShowLevelGuild.EnemyList.Enabled', 'bool', 137, '1', NULL, 'Show Enemy Guild Level in GW enemy list'),
('VAS.Unit.Enabled', 'bool', 138, '0', NULL, 'VAS Auto Balance system'),
('DalaranGEvent.InstantReviveAndReturn.Enable', 'bool', 139, '0', NULL, NULL),
('DalaranGEvent.Squad.Enable', 'bool', 140, '0', NULL, NULL),
('Player.AutoLearnSpells.Enabled', 'bool', 141, '0', NULL, 'Player will auto learn spell when reach a level (table player_spells_for_level)'),
('Player.UniversalLanguage.Enabled', 'bool', 142, '0', NULL, 'Player talking on Universal language (need for different chatMgr and 1 language for SAY and etc)'),
('External.Mail.Enable', 'bool', 143, '1', NULL, 'MailMgr will look in External table for receive a new mails from site ot something else');
