SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for world_config
-- ----------------------------
DROP TABLE IF EXISTS `world_config`;
CREATE TABLE `world_config`  (
  `OptionName` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Support types - bool, int, float, string',
  `IDInTypeGroup` int(10) NOT NULL,
  `DefaultValue` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `CustomValue` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `Description` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  PRIMARY KEY (`OptionName`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of world_config
-- ----------------------------
INSERT INTO `world_config` VALUES 
('Account.PasswordChangeSecurity', 'int', 155, '0', NULL, 'Controls how secure the password changes are. # Default: 0 - None (Old and new password) #1 - Email (Email confirmation necessary) #2 - RBAC (RBAC enable or disables email confirmation per group)'),
('AccountInstancesPerHour', 'int', 137, '5', NULL, 'Controls the max amount of different instances player can enter within hour. #Default: 5'),
('ActivateWeather', 'bool', 20, '1', NULL, 'Activate the weather system.'),
('AddonChannel', 'bool', 1, '1', NULL, 'Configure the use of the addon channel through the server (some client side addons will not work correctly with disabled addon channel)'),
('AllFlightPaths', 'bool', 11, '0', NULL, 'Character knows all flight paths (of both factions) after creation.'),
('Allow.IP.Based.Action.Logging', 'bool', 72, '0', NULL, 'Logs actions, e.g. account login and logout to name a few, based on IP of current session.'),
('AllowTickets', 'bool', 55, '1', NULL, 'Allow/disallow sending new tickets.'),
('AllowTrackBothResources', 'bool', 73, '0', NULL, 'Allows players to track herbs and minerals at the same time (if they have the skills)'),
('AllowTwoSide.Interaction.Auction', 'bool', 9, '0', NULL, 'Allow auctions between factions.'),
('AllowTwoSide.Interaction.Calendar', 'bool', 5, '0', NULL, 'Allow calendar invites between factions.'),
('AllowTwoSide.Interaction.Channel', 'bool', 6, '0', NULL, 'Allow channel chat between factions. (But not Universal languagem only 1 channelMgr)'),
('AllowTwoSide.Interaction.Group', 'bool', 7, '0', NULL, 'Allow group joining between factions.'),
('AllowTwoSide.Interaction.Guild', 'bool', 8, '0', NULL, 'Allow guild joining between factions.'),
('AllowTwoSide.Trade', 'bool', 10, '0', NULL, 'Allow trading between factions.'),
('AlwaysMaxSkillForLevel', 'bool', 21, '0', NULL, 'Players will automatically gain max skill level when logging in or leveling up.'),
('AlwaysMaxWeaponSkill', 'bool', 48, '0', NULL, 'Players will automatically gain max weapon/defense skill when logging in, or leveling.'),
('AntiCheats.DoubleJump.Enabled', 'bool', 95, '1', NULL, 'Enable AntiCheat.DoubleJump Kick when player sent opcode jump when has flag falling (client can\'t do this)'),
('AntiCheats.FakeFlyingmode.Enabled', 'bool', 94, '1', NULL, 'Enable AntiCheat.FakeFlyingmode : when player sent a move opcode with added fly flag but on server this flag doesn\'t restricted for player. It\'s normal for Hitchhiker\'s Hack with Air Mode'),
('AntiCheats.FakeFlyingmode.Kick.Enabled', 'bool', 102, '1', NULL, 'Enable AntiCheats.FakeFlyingmode Kick when detected'),
('AntiCheats.FakeJumper.Enabled', 'bool', 93, '1', NULL, 'Enable AntiCheat.FakeJumper : when player sent a move opcode (with new Z higher) when has flag falling (client can\'t sent any new packets when falling) It\'s normal for Gagarin hacks and with Air Mode + \"space\" click = \"falling\" mode (player can\'t change orientation of flying, but it move up)'),
('AntiCheats.FakeJumper.Kick.Enabled', 'bool', 101, '1', NULL, 'Enable AntiCheats.FakeJumper Kick when detected'),
('AntiCheats.FlyHack.Enabled', 'bool', 96, '1', NULL, 'Enable AntiCheat.FlyHack'),
('AntiCheats.FlyHack.Kick.Enabled', 'bool', 100, '1', NULL, 'Enable AntiCheat.FlyHack Kick when detected'),
('AntiCheats.FlyHackTimer', 'int', 185, '3000', NULL, 'Timer for AntiCheat FlyHack check #Default: 3000 - 1 check in 1 second'),
('AntiCheats.forceExcludeMapsid', 'string', 4, '', NULL, '616,649'),
('AntiCheats.IgnoreControlMovement.Enabled', 'bool', 98, '1', NULL, 'Enable AntiCheat.IgnoreControlMovement : when player in root state - client can\'t send a new movement packets'),
('AntiCheats.NoFallingDmg.Kick.Enabled', 'bool', 103, '1', NULL, 'Enable AntiCheats.NoFallingDmg Kick when detected'),
('AntiCheats.SpeedHack.Enabled', 'bool', 97, '1', NULL, 'Enable AntiCheat.SpeedHack'),
('AntiCheats.SpeedHack.Kick.Enabled', 'bool', 99, '1', NULL, 'Enable AntiCheat.SpeedHack Kick when detected'),
('Antispam.Mail.Controller', 'int', 193, '100', NULL, 'How many mails player can hold in mailbox, include mail in future (from auctionhouse and calendar).'),
('Antispam.Mail.Count', 'int', 192, '10', NULL, 'How many mails you can sent in game in 1 period of timer'),
('Antispam.Mail.Enabled', 'bool', 124, '1', NULL, 'When player will receive this limit, he just can\'t bid or bidout from auction. Calendar will not sent mail him.  And another player can\'t sent mail to him, just will see error overloaded mailbox of receiver.'),
('Antispam.Mail.Timer', 'int', 191, '3600', NULL, 'Timer for possible next sending count of mails by mailbox'),
('Arena.ArenaLoseRatingModifier', 'float', 16, '24', NULL, 'Modifier of rating subtraction for loser team (increasing this value will subtract more rating) #Default:     24'),
('Arena.ArenaMatchmakerRatingModifier', 'float', 17, '24', NULL, 'Modifier of matchmaker rating'),
('Arena.ArenaSeason.ID', 'int', 106, '8', NULL, 'Current arena season id shown in clients.'),
('Arena.ArenaSeason.InProgress', 'bool', 41, '1', NULL, 'State of current arena season. Default: 1 - (Active) #0 - (Finished)'),
('Arena.ArenaStartMatchmakerRating', 'int', 109, '1500', NULL, 'Start matchmaker rating for players.'),
('Arena.ArenaStartPersonalRating', 'int', 108, '0', NULL, 'Start personal rating when joining a team.'),
('Arena.ArenaStartRating', 'int', 107, '0', NULL, 'Start rating for new arena teams.'),
('Arena.ArenaWinRatingModifier1', 'float', 14, '48', NULL, 'Modifier of rating addition when winner team rating is less than 1300 be aware that from 1000 to 1300 it gradually decreases automatically down to the half of it (increasing this value will give more rating) #Default:     48'),
('Arena.ArenaWinRatingModifier2', 'float', 15, '24', NULL, 'Modifier of rating addition when winner team rating is equal or more than 1300 (increasing this value will give more rating) #Default:     24'),
('Arena.AutoDistributeInterval', 'int', 105, '7', NULL, 'Time (in days) how often arena points should be distributed if automatic distribution is enabled. #Default:  7 - (Weekly)'),
('Arena.AutoDistributePoints', 'bool', 39, '0', NULL, 'Automatically distribute arena points.'),
('Arena.MaxRatingDifference', 'int', 101, '150', NULL, 'Maximum rating difference between two teams in rated matches. #Default: 150 - (Enabled) # 0   - (Disabled)'),
('Arena.PreviousOpponentsDiscardTimer', 'int', 103, '120000', NULL, 'Time (in milliseconds) after which the previous opponents will be ignored. #Default: 120000 - (Enabled, 2 minutes - Blizzlike) #0 - (Disabled)'),
('Arena.QueueAnnouncer.Enable', 'bool', 40, '0', NULL, 'Announce arena queue status to chat.'),
('Arena.RatedUpdateTimer', 'int', 104, '5000', NULL, 'Time (in milliseconds) between checks for match-ups in rated arena. #Default:     5000 - (5 seconds)'),
('Arena.RatingDiscardTimer', 'int', 102, '600000', NULL, 'Time (in milliseconds) after which rating differences are ignored when setting up matches. # Default:  600000 - (Enabled, 10 minutes)'),
('ArenaLog.ExtendedInfo', 'bool', 42, '0', NULL, 'Include extended info to ArenaLogFile for each player after rated arena matches (guid, name, team, IP, healing/damage done, killing blows).'),
('ArenaTeam.CharterCost.2v2', 'int', 167, '800000', NULL, 'Amount of money (in Copper) the petitions costs. 800000 - (80 Gold)'),
('ArenaTeam.CharterCost.3v3', 'int', 168, '1200000', NULL, 'Amount of money (in Copper) the petitions costs. 1200000 - (120 Gold)'),
('ArenaTeam.CharterCost.5v5', 'int', 169, '2000000', NULL, 'Amount of money (in Copper) the petitions costs. 2000000 - (200 Gold)'),
('Auction.GetAllScanDelay', 'int', 172, '900', NULL, 'Sets the minimum time in seconds, a single player character can perform a GetAll scan. The value is only held in memory so a server restart will clear it. Setting this to zero, will disable GetAll functions completely. #Default:  900 - (GetAll scan limited to once every 15mins per player character)'),
('Auction.SearchDelay', 'int', 173, '300', NULL, 'Sets the minimum time in milliseconds (seconds x 1000), that the client must wait between auction search operations. This can be increased if somehow Auction House activity is causing too much load. #Default: 300 - (Time delay between auction searches set to 0.3secs)'),
('AuctionHouseBot.Update.Interval', 'int', 165, '20', NULL, 'Interval in seconds for AHBot to get updated'),
('AutoBroadcast.Center', 'int', 129, '0', NULL, 'Auto broadcasting display method. #Default: 0 - (Announce) #1 - (Notify) #2 - (Both)'),
('AutoBroadcast.On', 'bool', 54, '0', NULL, 'Enable auto broadcast.'),
('AutoBroadcast.Timer', 'int', 130, '600000', NULL, 'Timer (in milliseconds) for auto broadcasts. #Default: 600000 - (10 minutes)'),
('BAG.Script.BankBagsID', 'string', 5, '304005', NULL, 'safe deposit box : Item bag entry list (like 304005,304006,304007...) which can be opened only in Bank (not from inventory)'),
('BAG.Script.BonusBagsID', 'int', 194, '51809', NULL, 'itemid of bags ( 51809 )'),
('BAG.Script.Enabled', 'bool', 126, '1', NULL, 'Created character will receive a bags bonus'),
('BaseMapLoadAllGrids', 'bool', 78, '0', NULL, 'Load all grids for base maps upon load. Requires GridUnload to be 0. This will take around 5GB of ram upon server load, and will take some time to initially load the server.'),
('Battleground.CastDeserter', 'bool', 33, '1', NULL, 'Cast Deserter spell at players who leave battlegrounds in progress.'),
('Battleground.GiveXPForKills', 'bool', 38, '0', NULL, 'Give experience for honorable kills in battlegrounds, the rate can be changed in the Rate.XP.BattlegroundKill setting.'),
('Battleground.InvitationType', 'int', 97, '0', NULL, 'Set Battleground invitation type. #Default: 0 - (Normal, Invite as much players to battlegrounds as queued, Don\'t bother with balance) #1 - (Experimental, Don\'t allow to invite much more players of one faction) #2 - (Experimental, Try to have even teams)'),
('Battleground.PremadeGroupWaitForMatch', 'int', 99, '1800000', NULL, 'Time (in milliseconds) a pre-made group has to wait for matching group of the other faction. #Default: 1800000 - (Enabled, 30 minutes) #0 - (Disabled, Not recommended)'),
('Battleground.PrematureFinishTimer', 'int', 98, '300000', NULL, 'Time (in milliseconds) before battleground will end prematurely if there are not enough players on one team. (Values defined in battleground template) #Default: 300000 - (Enabled, 5 minutes) #0 - (Disabled, Not recommended)'),
('Battleground.QueueAnnouncer.Enable', 'bool', 34, '0', NULL, 'Announce battleground queue status to chat.'),
('Battleground.QueueAnnouncer.PlayerOnly', 'bool', 35, '0', NULL, 'Battleground queue announcement type. Default: 0 - (System message, Anyone can see it) #1 - (Private, Only queued players can see it)'),
('Battleground.Random.ResetHour', 'int', 122, '6', NULL, 'Hour of the day when the global instance resets occur. #Range: 0-23#Default:     6 - (06:00 AM)'),
('Battleground.ReportAFK', 'int', 100, '3', NULL, 'Number of reports needed to kick someone AFK from Battleground. Range: 1-9 #Default:     3'),
('Battleground.RewardLoserHonorFirst', 'int', 160, '5', NULL, 'Random Battlegrounds / call to the arms rewards.'),
('Battleground.RewardLoserHonorLast', 'int', 161, '5', NULL, 'Random Battlegrounds / call to the arms rewards.'),
('Battleground.RewardWinnerArenaFirst', 'int', 157, '25', NULL, 'Random Battlegrounds / call to the arms rewards.'),
('Battleground.RewardWinnerArenaLast', 'int', 159, '0', NULL, 'Random Battlegrounds / call to the arms rewards.'),
('Battleground.RewardWinnerHonorFirst', 'int', 156, '30', NULL, 'Random Battlegrounds / call to the arms rewards.'),
('Battleground.RewardWinnerHonorLast', 'int', 158, '15', NULL, 'Random Battlegrounds / call to the arms rewards.'),
('Battleground.StoreStatistics.Enable', 'bool', 36, '0', NULL, 'Store Battleground scores in the database.'),
('Battleground.TrackDeserters.Enable', 'bool', 37, '0', NULL, 'Track deserters of Battlegrounds.'),
('BirthdayTime', 'int', 162, '1222964635', NULL, 'Set to date of project\'s birth in UNIX time. By default the date when #TrinityCore was started (Thu Oct 2, 2008) #Default: 1222964635'),
('CacheDataQueries', 'bool', 87, '1', NULL, 'Server caches data queries at startup. Can be disabled if not enough memory is available.'),
('Calculate.Creature.Zone.Area.Data', 'bool', 74, '0', NULL, 'Calculate at loading creature zoneId / areaId and save in creature table (WARNING: SLOW WORLD SERVER STARTUP)'),
('Calculate.Gameoject.Zone.Area.Data', 'bool', 75, '0', NULL, 'Calculate at loading gameobject zoneId / areaId and save in gameobject table (WARNING: SLOW WORLD SERVER STARTUP)'),
('Calendar.DeleteOldEventsHour', 'int', 123, '6', NULL, 'Hour of the day when the daily deletion of old calendar events occurs. #Range: 0-23 #Default: 6 - (06:00 AM)'),
('CastUnstuck', 'bool', 15, '1', NULL, 'Allow casting the Unstuck spell using .start or unstuck button in client help options.'),
('ChangeWeatherInterval', 'int', 4, '600000', NULL, 'Time (in milliseconds) for weather update interval.'),
('Channel.RestrictedLfg', 'bool', 25, '1', NULL, 'Restrict LookupForGroup channel to characters registered in the LFG tool.'),
('CharacterCreating.Disabled', 'int', 18, '0', NULL, 'Disable character creation for players based on faction. 0 - (Enabled, All factions are allowed) 1 - (Disabled, Alliance) 2 - (Disabled, Horde)  3 - (Disabled, Both factions)'),
('CharacterCreating.Disabled.ClassMask', 'int', 20, '0', NULL, 'Mask of classes which cannot be created by players. Example:     288 - (32 + 256, Death Knight and Warlock classes are disabled). 0    - (Enabled, All classes are allowed) 1    - (Disabled, Warrior) 2    - (Disabled, Paladin) 4    - (Disabled, Hunter) 8    - (Disabled, Rogue) 16   - (Disabled, Priest) 32   - (Disabled, Death Knight) 64   - (Disabled, Shaman) 128  - (Disabled, Mage) 256  - (Disabled, Warlock) 1024 - (Disabled, Druid)'),
('CharacterCreating.Disabled.RaceMask', 'int', 19, '0', NULL, 'Mask of races which cannot be created by players. # Example:     1536 - (1024 + 512, Blood Elf and Draenei races are disabled) 0    - (Enabled, All races are allowed) 1    - (Disabled, Human) 2    - (Disabled, Orc) 4    - (Disabled, Dwarf) 8    - (Disabled, Night Elf) 16   - (Disabled, Undead) 32   - (Disabled, Tauren) 64   - (Disabled, Gnome) 128  - (Disabled, Troll) 512  - (Disabled, Blood Elf) 1024 - (Disabled, Draenei)'),
('CharacterCreating.MinLevelForDeathKnight', 'int', 24, '55', NULL, 'Limit creating death knights only for account with another character of specific level (ignored for GM accounts).'),
('CharactersPerAccount', 'int', 22, '50', NULL, 'Limit number of characters per account on all realms on this realmlist.'),
('CharactersPerRealm', 'int', 21, '10', NULL, 'Limit number of characters per account on this realm. Range: 1-10'),
('CharDelete.DeathKnight.MinLevel', 'int', 128, '0', NULL, 'Required level to use the unlinking method if enabled for death knights. #Default: 0  - (Same method for every level) #1+ - (Only characters with the specified level will use the unlinking method)'),
('CharDelete.KeepDays', 'int', 125, '30', NULL, 'Time (in days) before unlinked characters will be removed from the database. #Default: 30 - (Enabled) #0  - (Disabled, Don\'t delete any characters)'),
('CharDelete.Method', 'int', 126, '0', NULL, 'Character deletion behavior. #Default: 0 - (Completely remove character from the database) #1 - (Unlink the character from account and free up the name, Appears as deleted in-game)'),
('CharDelete.MinLevel', 'int', 127, '0', NULL, 'Required level to use the unlinking method if enabled for non-heroic classes. #Default: 0  - (Same method for every level) #1+ - (Only characters with the specified level will use the unlinking method)'),
('Chat.StrictMessages.Enabled', 'bool', 125, '1', NULL, 'Limit player message to language specific symbol set. Prevents character messages and ignore request if not allowed symbols are used'),
('ChatFakeMessagePreventing', 'bool', 26, '1', NULL, 'Additional protection from creating fake chat messages using spaces. Collapses multiple subsequent whitespaces into a single whitespace. Not applied to the addon language, but may break old addons that use \"normal\" chat messages for sending data to other clients.'),
('ChatFlood.MessageCount', 'int', 70, '10', NULL, 'Chat flood protection, number of messages before player gets muted. #Default:     10 - (Enabled) #0  - (Disabled)'),
('ChatFlood.MessageDelay', 'int', 71, '1', NULL, 'Time (in seconds) between messages to be counted into ChatFlood.MessageCount.'),
('ChatFlood.MuteTime', 'int', 72, '10', NULL, 'Time (in seconds) characters get muted for violating ChatFlood.MessageCount. #Default:     10'),
('ChatLevelReq.Channel', 'int', 80, '1', NULL, 'Level requirement for characters to be able to use chats.'),
('ChatLevelReq.Emote', 'int', 82, '1', NULL, 'Level requirement for characters to be able to use chats.'),
('ChatLevelReq.Say', 'int', 83, '1', NULL, 'Level requirement for characters to be able to use chats.'),
('ChatLevelReq.Whisper', 'int', 81, '1', NULL, 'Level requirement for characters to be able to use chats.'),
('ChatLevelReq.Yell', 'int', 84, '1', NULL, 'Level requirement for characters to be able to use chats.'),
('ChatStrictLinkChecking.Kick', 'int', 79, '0', NULL, 'Defines what should be done if a message containing invalid control characters is received. #Default: 0 - (Silently ignore message) 1 - (Ignore message and kick player)'),
('ChatStrictLinkChecking.Severity', 'int', 78, '0', NULL, 'Check chat messages for in-game links to spells, items, quests, etc. #Default: 0 - (Only verify that link format looks valid without checking the text) 1 - (Check if color, entry and name don\'t contradict each other. For this to work correctly, please assure that you have extracted locale DBCs of every language specific client playing on this server)'),
('CheckGameObjectLoS', 'bool', 89, '1', NULL, 'Include dynamic game objects (doors, chests etc.) in line of sight checks. This increases CPU usage somewhat.'),
('CheckM2ObjectLoS', 'bool', 90, '1', NULL, 'Include M2 objects (trees etc.) in line of sight checks.'),
('CleanCharacterDB', 'bool', 2, '0', NULL, 'Clean out deprecated achievements, skills, spells and talents from the db.'),
('ClientCacheVersion', 'int', 118, '0', NULL, 'Client cache version for client cache data reset. Use any value different from DB and not recently been used to trigger client side cache reset. #Default:  0 - (Use DB value from world DB version.cache_id field)'),
('Command.LookupMaxResults', 'int', 131, '0', NULL, 'Number of results being displayed using a .lookup command. #Default: 0 - (Unlimited)'),
('Compression', 'int', 0, '1', NULL, 'Compression level for client update packages. (1   - (Speed) -- 9   - (Best compression))'),
('Config.Vip.Appear.Command', 'bool', 118, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Bank.Command', 'bool', 109, '0', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Capital.Command', 'bool', 117, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Change.Race.Command', 'bool', 115, '0', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Customize.Command', 'bool', 116, '0', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Debuff.Command', 'bool', 108, '0', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Home.Command', 'bool', 114, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Item.Helper', 'bool', 119, '1', NULL, 'Enable/Disable Item helper in game'),
('Config.Vip.Mail.Command', 'bool', 110, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Repair.Command', 'bool', 111, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Reset.Talents.Command', 'bool', 112, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Taxi.Command', 'bool', 113, '1', NULL, 'Enable/Disable custom vip command'),
('Corpse.Decay.ELITE', 'int', 92, '300', NULL, 'Time (in seconds) until creature corpse will decay if not looted or skinned.'),
('Corpse.Decay.NORMAL', 'int', 90, '300', NULL, 'Time (in seconds) until creature corpse will decay if not looted or skinned.'),
('Corpse.Decay.RARE', 'int', 91, '300', NULL, 'Time (in seconds) until creature corpse will decay if not looted or skinned.'),
('Corpse.Decay.RAREELITE', 'int', 93, '300', NULL, 'Time (in seconds) until creature corpse will decay if not looted or skinned.'),
('Corpse.Decay.WORLDBOSS', 'int', 94, '3600', NULL, 'Time (in seconds) until creature corpse will decay if not looted or skinned.'),
('Creature.MovingStopTimeForPlayer', 'int', 164, '180000', NULL, 'Time (in milliseconds) during which creature will not move after interaction with player.'),
('Creature.PickPocketRefillDelay', 'int', 163, '600', NULL, 'Time in seconds that the server will wait before refilling the pickpocket loot for a creature #Default: 600'),
('Creature.RegenHPCannotReachTargetInRaid', 'bool', 88, '1', NULL, 'Regenerates HP for Creatures in Raids if they cannot reach the target.'),
('CreatureFamilyAssistanceDelay', 'int', 73, '1500', NULL, 'Time (in milliseconds) before creature assistance call. #Default:     1500 - (1.5 Seconds)'),
('CreatureFamilyAssistanceRadius', 'float', 7, '10', NULL, 'Distance for creatures calling for assistance from other creatures without moving. #Default:  10 - (Enabled) #0  - (Disabled)'),
('CreatureFamilyFleeAssistanceRadius', 'float', 6, '30', NULL, 'Distance for fleeing creatures seeking assistance from other creatures. #Default:     30 - (Enabled) #0  - (Disabled)'),
('CreatureFamilyFleeDelay', 'int', 74, '7000', NULL, 'Time (in milliseconds) during which creature can flee if no assistance was found. #Default:     7000 (7 Seconds)'),
('CrossfactionBG.enable', 'bool', 104, '1', NULL, 'Mixed battleground'),
('DalaranGEvent.InstantReviveAndReturn.Enable', 'bool', 136, '0', NULL, NULL),
('DalaranGEvent.Min.Players', 'int', 206, '5', NULL, 'DalaranCrater Event minimal players'),
('DalaranGEvent.Squad.Enable', 'bool', 137, '0', NULL, NULL),
('DBC.EnforceItemAttributes', 'bool', 57, '1', NULL, 'Disallow overriding item attributes stored in DBC files with values from the database.'),
('Death.Bones.BattlegroundOrArena', 'bool', 30, '1', NULL, 'Create bones instead of corpses at resurrection in normal zones, instances, battleground or arenas.'),
('Death.Bones.World', 'bool', 29, '1', NULL, 'Create bones instead of corpses at resurrection in normal zones, instances, battleground or arenas.'),
('Death.CorpseReclaimDelay.PvE', 'bool', 28, '1', NULL, 'Increase corpse reclaim delay at PvP/PvE deaths.'),
('Death.CorpseReclaimDelay.PvP', 'bool', 27, '1', NULL, 'Increase corpse reclaim delay at PvP/PvE deaths.'),
('Death.SicknessLevel', 'int', 95, '11', NULL, 'Starting level for resurrection sickness. #Example: 11 - (Level 1-10 characters will not be affected, Level 11-19 characters will be affected for 1 minute, Level 20-MaxPlayerLevel characters will be affected for 10 minutes) #Default: 11 - (Enabled, See Example) #MaxPlayerLevel+1 - (Disabled) # -10              - (Enabled, Level 1+ characters have 10 minute duration)'),
('DeathKnightsPerRealm', 'int', 23, '1', NULL, 'Limit number of death knight characters per account on this realm. Range:       1-10'),
('DeclinedNames', 'bool', 32, '1', NULL, 'Allow Russian clients to set and use declined names.'),
('DeletedCharacterTicketTrace', 'bool', 56, '0', NULL, 'Keep trace of tickets opened by deleted characters gm_ticket.playerGuid will be 0, old GUID and character name will be included in gm_ticket.comment'),
('DetectPosCollision', 'bool', 24, '1', NULL, 'Check final move position, summon position, etc for visible collision with other objects or walls (walls only if vmaps are enabled).'),
('Die.Command.Mode', 'bool', 31, '1', NULL, 'Do not trigger things like loot from .die command.'),
('DisableWaterBreath', 'int', 96, '4', NULL, 'Required security level for water breathing. #Default: 4  - (Disabled) #0  - (Enabled, Everyone) #1  - (Enabled, Mods/GMs/Admins) #2  - (Enabled, GMs/Admins) #3  - (Enabled, Admins)'),
('DisconnectToleranceInterval', 'int', 5, '0', NULL, 'Tolerance (in seconds) for disconnected players before reentering the queue.'),
('DuelPhase.Enabled', 'bool', 128, '1', NULL, 'Make a special phase for duel members, they will see only oponent, and can\'t see others units'),
('DungeonFinder.OptionsMask', 'int', 136, '1', NULL, 'Description: Dungeon and raid finder system. Value is a bitmask consisting of: #LFG_OPTION_ENABLE_DUNGEON_FINDER = 1,     Enable the dungeon finder browser #LFG_OPTION_ENABLE_RAID_BROWSER   = 2, Enable the raid browser'),
('DurabilityLoss.InPvP', 'bool', 0, '0', NULL, 'Durability loss on death during PvP.'),
('DurabilityLoss.OnDeath', 'rate', 56, '10', NULL, 'Durability loss percentage on death. #Note: On 3.3.5 client always shows log message \"Your items have lost 10% durability\" #Default:     10'),
('DurabilityLossChance.Absorb', 'rate', 59, '0.5', NULL, 'Chance to lose durability on one equipped armor item when absorbing damage. #Default: 0.5 - (100/0.5 = 200, Each 200 absorbed damage one equipped item will lose durability)'),
('DurabilityLossChance.Block', 'rate', 60, '0.05', NULL, 'Chance to lose durability on shield when blocking attacks. #Default: 0.05 - (100/0.05 = 2000, Each 2000 blocked damage the shield will lose durability)'),
('DurabilityLossChance.Damage', 'rate', 57, '0.5', NULL, 'Chance to lose durability on one equipped item from damage. #Default:  0.5 - (100/0.5 = 200, Each 200 damage one equipped item will use durability)'),
('DurabilityLossChance.Parry', 'rate', 58, '0.05', NULL, 'Chance to lose durability on main weapon when parrying attacks. #Default:     0.05 - (100/0.05 = 2000, Each 2000 parried damage the main weapon will lose durability)'),
('Event.Announce', 'bool', 68, '0', NULL, 'Announce events.'),
('Expansion', 'int', 69, '2', NULL, 'Allow server to use content from expansions. Checks for expansion-related map files, client compatibility and class/race character creation. #Default: 2 - (Expansion 2) #1 - (Expansion 1) #0 - (Disabled, Ignore and disable expansion content (maps, races, classes)'),
('External.Mail.Enable', 'bool', 140, '1', NULL, 'MailMgr will look in External table for receive a new mails from site ot something else'),
('FLAB.Script.BonusMoney', 'int', 187, '10000000', NULL, 'Count of money ( 1000 gold )'),
('FLAB.Script.Enabled', 'bool', 106, '1', NULL, 'First character on account will receive a money bonus'),
('FLAB.Script.MaxChars', 'int', 186, '0', NULL, 'Count of characters for give a bonus #Default:     0 - it should be a first character on acc, right?'),
('GameType', 'int', 10, '0', NULL, 'Server realm type : 0 - normal, 1-pvp, 4-normal, 6-RP, 8-RPPVP, 16-FFA PVP'),
('GM.AllowInvite', 'bool', 16, '0', NULL, 'Allow players to invite GM characters.'),
('GM.Chat', 'int', 49, '2', NULL, 'Description: GM chat mode at login. #Default:     2 - (Last save state) # 0 - (Disable) # 1 - (Enable)'),
('GM.ForceShutdownThreshold', 'int', 54, '30', NULL, 'Minimum shutdown time in seconds before \'force\' is required if other players are connected. #Default:     30'),
('GM.FreezeAuraDuration', 'int', 51, '0', NULL, 'Allows to set a default duration to the Freeze Aura #applied on players when using the .freeze command #Default:     0 - (Original aura duration. Lasts until the .unfreeze command is used) #N - (Aura duration if unspecified in .freeze command, in seconds)'),
('GM.InGMList.Level', 'int', 52, '3', NULL, 'Maximum GM level shown in GM list (if enabled) in non-GM state (.gm off). #Default:     3 - (Anyone) #0 - (Only players) #1 - (Only moderators) #2 - (Only gamemasters)'),
('GM.InWhoList.Level', 'int', 53, '3', NULL, 'Max GM level showed in who list (if visible). #Default: 3 - (Anyone) #0 - (Only players) #1 - (Only moderators) #2 - (Only gamemasters)'),
('GM.LoginState', 'int', 47, '2', NULL, 'GM mode at login. #Default:     2 - (Last save state) #0 - (Disable) # 1 - (Enable)'),
('GM.LowerSecurity', 'bool', 17, '0', NULL, 'Allow lower security levels to use commands on higher security level characters.'),
('GM.StartLevel', 'int', 30, '1', NULL, 'GM character starting level.'),
('GM.TicketSystem.ChanceOfGMSurvey', 'float', 9, '50', NULL, 'Chance of sending a GM survey after ticket completion. #Default: 50 - (Enabled) #0  - (Disabled)'),
('GM.Visible', 'int', 48, '2', NULL, 'GM visibility at login. #Default:     2 - (Last save state) #0 - (Invisible) #1 - (Visible)'),
('GM.WhisperingTo', 'int', 50, '2', NULL, 'Is GM accepting whispers from player by default or not. #Default:     2 - (Last save state) #0 - (Disable) #1 - (Enable)'),
('GridCleanUpDelay', 'int', 2, '300000', NULL, 'Time (in milliseconds) grid clean up delay.'),
('GridUnload', 'bool', 3, '1', NULL, 'Unload grids to save memory. Can be disabled if enough memory is available to speed up moving players to new grids.'),
('GSystem.GuildLevel.Enabled', 'bool', 129, '1', NULL, 'Make a possible guild level system'),
('GSystem.GuildLevel.Exp.ForArena', 'int', 198, '5', NULL, 'exp of guild for Win on Arena of each guild member'),
('GSystem.GuildLevel.Exp.ForBG', 'int', 199, '1', NULL, 'exp of guild for Win on BG of each guild member'),
('GSystem.GuildLevel.Exp.ForLFG', 'int', 200, '1', NULL, 'exp of guild for Win on LFG of each guild member'),
('GSystem.GuildLevel.LvL.ForMyBank', 'int', 204, '5', NULL, 'Level of guild for opening MyBank func'),
('GSystem.GuildLevel.LvL.ForRepair', 'int', 205, '3', NULL, 'Level of guild for opening Repair func'),
('GSystem.GuildLevel.Rate.XP.Bonus', 'rate', 69, '2', NULL, 'Rate for character experience when guild >= 2 level'),
('GSystem.GuildLevel.ShowLevelGuild.QueryList.Enabled', 'bool', 133, '1', NULL, 'Make a visible guild level in query opcode (visible name/guild above character)'),
('GSystem.GuildLevel.ShowLevelGuild.WhoList.Enabled', 'bool', 132, '1', NULL, 'Make a visible guild level in whoList'),
('GSystem.GuildWars.BetweenBothFaction.Enabled', 'bool', 131, '1', NULL, 'Give possibility to make Guild Wars between guilds from both faction (Alliance and Horde)'),
('GSystem.GuildWars.Enabled', 'bool', 130, '1', NULL, 'Give possibility to make Guild Wars between guilds'),
('GSystem.GuildWars.Exp.ForEnemyGuildKill', 'int', 201, '1', NULL, 'reward guild by exp for killing members of enemy guild (in GW status). Depend from GSystem.GuildLevel.Enabled'),
('GSystem.GuildWars.Exp.ForLoserOfGW', 'int', 203, '100', NULL, 'reward winner guild by exp for Lose in Guild Wars'),
('GSystem.GuildWars.Exp.ForWinnerOfGW', 'int', 202, '250', NULL, 'reward winner guild by exp for Win in Guild Wars'),
('GSystem.GuildWars.Minimal.Delta.PreviousEndTimer', 'int', 197, '3600', NULL, 'minimal timer for guild from previous end war time for starting a new war'),
('GSystem.GuildWars.Minimal.Delta.PreviousStartTimer', 'int', 196, '3600', NULL, 'minimal timer for guild from previous start war time for starting a new war'),
('GSystem.GuildWars.Minimal.PlayerCount', 'int', 195, '10', NULL, 'minimal count of members in guild for participation in GW'),
('GSystem.GuildWars.ShowLevelGuild.EnemyList.Enabled', 'bool', 134, '1', NULL, 'Show Enemy Guild Level in GW enemy list'),
('GSystem.LootBroadcast.Enabled', 'bool', 105, '1', NULL, 'Guild announce when member take a loot with Quality >= EPIC'),
('Guild.AllowMultipleGuildMaster', 'bool', 141, '0', NULL, 'Allow more than one guild master. Additional Guild Masters must be set using the \".guild rank\" command.'),
('Guild.BankEventLogRecordsCount', 'int', 120, '25', NULL, 'Number of log entries for guild bank events that are stored per guild. Old entries will be overwritten if the number of log entries exceed the configured value. High numbers prevent this behavior but may have performance impacts. #Default:  25 - (Minimum)'),
('Guild.CharterCost', 'int', 166, '1000', NULL, 'Amount of money (in Copper) the petitions costs. 1000 - (10 Silver)'),
('Guild.EventLogRecordsCount', 'int', 119, '100', NULL, 'Number of log entries for guild events that are stored per guild. Old entries will be overwritten if the number of log entries exceed the configured value. High numbers prevent this behavior but may have performance impacts.'),
('Guild.ResetHour', 'int', 124, '6', NULL, 'Hour of the day when the daily cap resets occur. #Range: 0-23 #Default: 6 - (06:00 AM)'),
('HonorPointsAfterDuel', 'int', 111, '0', NULL, 'Amount of honor points the duel winner will get after a duel. #Default:  0  - (Disabled) #1+ - (Enabled)'),
('HotSwap.EnableBuildFileRecreation', 'bool', 83, '1', NULL, 'Recreate build files when sources to a module were added or removed.'),
('HotSwap.Enabled', 'bool', 80, '1', NULL, 'Enables dynamic script hotswapping. Reloads scripts on changes.'),
('HotSwap.EnableEarlyTermination', 'bool', 82, '1', NULL, 'Terminate the build of a module when an associated source file was changed meanwhile.'),
('HotSwap.EnableInstall', 'bool', 84, '1', NULL, 'Enables cmake install after automatic builds have finished'),
('HotSwap.EnablePrefixCorrection', 'bool', 85, '1', NULL, 'Allows the core to automatic set the CMAKE_INSTALL_PREFIX to its current location in the file system.'),
('HotSwap.EnableReCompiler', 'bool', 81, '1', NULL, 'Enables the dynamic script recompiler. Watches your script source directories and recompiles the script modules on changes.'),
('Instance.IgnoreLevel', 'bool', 13, '0', NULL, 'Ignore level requirement when entering instances.'),
('Instance.IgnoreRaid', 'bool', 14, '0', NULL, 'Ignore raid group requirement when entering instances.'),
('Instance.ResetTimeHour', 'int', 38, '4', NULL, 'Hour of the day when the global instance reset occurs. # Range:       0-23 # Default:     4 - (04:00 AM)'),
('Instance.UnloadDelay', 'int', 39, '1800000', NULL, 'Time (in milliseconds) before instance maps are unloaded from memory if no characters are inside. #Default: 1800000 - (Enabled, 30 minutes) 0       - (Disabled, Instance maps are kept in memory until the instance resets)'),
('InstanceMapLoadAllGrids', 'bool', 79, '0', NULL, 'Load all grids for instance maps upon load. Requires GridUnload to be 0. Upon loading an instance map, all creatures/objects in the map will be pre-loaded'),
('InstancesResetAnnounce', 'bool', 70, '0', NULL, 'Announce the reset of one instance to whole party.'),
('InstantFlightPaths', 'bool', 12, '0', NULL, 'Flight paths will take players to their destination instantly instead of making them wait while flying.'),
('LevelReq.Auction', 'int', 88, '1', NULL, 'Level requirement for characters to be able to use the auction house.'),
('LevelReq.Mail', 'int', 89, '1', NULL, 'Level requirement for characters to be able to send and receive mails.'),
('LevelReq.Ticket', 'int', 87, '1', NULL, 'Level requirement for characters to be able to write tickets.'),
('LevelReq.Trade', 'int', 86, '1', NULL, 'Level requirement for characters to be able to initiate a trade.'),
('LFG.Channel.Everywhere', 'bool', 107, '1', NULL, 'Allow access at LookupForGroup channel to characters without condition of LFG state.'),
('LFG.CrossFaction.Groups', 'bool', 122, '1', NULL, 'Enable/Disable custom system for crossfaction DungeonFinder groups'),
('ListenRange.Say', 'float', 3, '40', NULL, 'Distance in which players can read say messages from creatures or gameobjects.'),
('ListenRange.TextEmote', 'float', 4, '40', NULL, 'Distance in which players can read emotes from creatures or gameobjects.'),
('ListenRange.Yell', 'float', 5, '300', NULL, 'Distance in which players can read yell messages from creatures or gameobjects.'),
('LogDB.Opt.ClearInterval', 'int', 116, '10', NULL, 'Time (in minutes) for the WUPDATE_CLEANDB timer that clears the `logs` table of old entries. #Default: 20 - (10 minutes) #1+'),
('LogDB.Opt.ClearTime', 'int', 117, '1209600', NULL, 'Time (in seconds) for keeping old `logs` table entries. #Default: 1209600 - (Enabled, 14 days)'),
('MailDeliveryDelay', 'int', 56, '3600', NULL, 'Time (in seconds) mail delivery is delayed when sending items. #Default:     3600 - (1 hour)'),
('MapUpdate.Threads', 'int', 115, '1', NULL, 'Number of threads to update maps.'),
('MapUpdateInterval', 'int', 3, '100', NULL, 'Time (milliseconds) for map update interval.'),
('MaxArenaPoints', 'int', 34, '10000', NULL, 'Maximum arena points a character can have.'),
('MaxGroupXPDistance', 'float', 0, '74', NULL, 'Max distance to creature for group member to get experience at creature death.'),
('MaxHonorPoints', 'int', 32, '75000', NULL, 'Maximum honor points a character can have.'),
('MaxOverspeedPings', 'int', 68, '2', NULL, 'Maximum overspeed ping count before character is disconnected. #Default: 2  - (Enabled, Minimum value) #3+ - (Enabled, More checks before kick) #0  - (Disabled)'),
('MaxPingTime', 'int', 132, '30', NULL, 'Time (in minutes) between database pings.'),
('MaxPlayerLevel', 'int', 26, '80', NULL, 'Maximum level that can be reached by players.'),
('MaxPrimaryTradeSkill', 'int', 42, '2', NULL, 'Maximum number of primary professions a character can learn. #Range:       0-11'),
('MaxRecruitAFriendBonusDistance', 'float', 1, '100', NULL, 'Max distance between character and and group to gain the Recruit-A-Friend XP multiplier.'),
('MaxWhoListReturns', 'int', 110, '49', NULL, 'Set the max number of players returned in the /who list and interface.'),
('MinCharterName', 'int', 16, '2', NULL, 'Minimal charter name length. Range: 1-24'),
('MinCreatureScaledXPRatio', 'int', 45, '0', NULL, 'Min ratio of experience that a creature kill can grant when player level scaling is factored.  This will also allow spell procs to trigger, such as Drain Soul, if > 0 and exp is grantable. #Example: 50 (No less than 50% experience granted from a lower leveled creature kill) #100 (Creature kills always grant full experience upon kill) #Default:     0 - (Creatures too low may grant no experience)'),
('MinDiscoveredScaledXPRatio', 'int', 46, '0', NULL, 'Min ratio of experience that an area discovery event will grant when player level scaling is factored. #Example: 50 (No less than 50% experience granted from discovering a new section of map) #00 (Map exploration always grant full experience upon discovery) Default:     0 - (No experience granted when discovered area is too low level)'),
('MinDualSpecLevel', 'int', 27, '40', NULL, 'Level requirement for Dual Talent Specialization.'),
('MinPetitionSigns', 'int', 43, '9', NULL, 'Number of required signatures on charters to create a guild. #Range:       0-9'),
('MinPetName', 'int', 17, '2', NULL, 'Minimal pet name length. Range: 1-12'),
('MinPlayerName', 'int', 15, '2', NULL, 'Minimal player name length. Range: 1-12'),
('MinQuestScaledXPRatio', 'int', 44, '0', NULL, 'Min ratio of experience that a quest can grant when player level scaling is factored. Example:  50 (No less than 50% experience granted from a lower leveled quests completion) #100 (Quests always grant full experience upon completion) #Default:     0 - (Quests too low may grant no experience)'),
('mmap.enablePathFinding', 'bool', 65, '1', NULL, 'Enable/Disable pathfinding using mmaps - recommended.'),
('MonsterSight', 'float', 2, '50', NULL, 'The maximum distance in yards that a \"monster\" creature can see regardless of level difference (through CreatureAI::IsVisible). Increases CONFIG_SIGHT_MONSTER to 50 yards. Used to be 20 yards. #Default:     50.000000'),
('Motd', 'string', 2, 'Welcome to a Trinity Core Server.', NULL, NULL),
('NoGrayAggro.Above', 'int', 170, '0', NULL, 'Gray mobs will not aggro players above/below some levels NoGrayAggro.Above: If player is at this level or above, gray mobs will not attack NoGrayAggro.Below: If player is at this level or below, gray mobs will not attack #Example: You can for example make players free from gray until they reach level 30. #Then gray will start to attack them, until they reach max level (80 for example): #NoGrayAggro.Above = 80 #NoGrayAggro.Below = 29 #Default: 0 - (Blizzlike)'),
('NoGrayAggro.Below', 'int', 171, '0', NULL, 'Gray mobs will not aggro players above/below some levels NoGrayAggro.Above: If player is at this level or above, gray mobs will not attack NoGrayAggro.Below: If player is at this level or below, gray mobs will not attack #Example: You can for example make players free from gray until they reach level 30. #Then gray will start to attack them, until they reach max level (80 for example): #NoGrayAggro.Above = 80 #NoGrayAggro.Below = 29 #Default: 0 - (Blizzlike)'),
('NoResetTalentsCost', 'bool', 50, '0', NULL, 'Resetting talents doesn\'t cost anything.'),
('OffhandCheckAtSpellUnlearn', 'bool', 43, '1', NULL, 'Unlearning certain spells can change offhand weapon restrictions for equip slots. Default: 1 - (Recheck offhand slot weapon at unlearning a spell) # 0 - (Recheck offhand slot weapon only at zone update)'),
('OSXPlayers.Enabled', 'bool', 123, '1', NULL, 'We can block connect for players from OSX OS system'),
('PacketSpoof.BanDuration', 'int', 154, '86400', NULL, 'Duration of the ban in seconds. Only valid if PacketSpoof.Policy is set to 2. #Set to 0 for permanent ban. #Default:  86400 seconds (1 day)'),
('PacketSpoof.BanMode', 'int', 153, '0', NULL, 'If PacketSpoof.Policy equals 2, this will determine the ban mode. #Note: Banning by character not supported for logical reasons. #Default: 0 - Ban Account #2 - Ban IP'),
('PacketSpoof.Policy', 'int', 152, '1', NULL, 'Determines the course of action when packet spoofing is detected. #Default: 1 - (Log + kick) #0 - (Log only \'network\') #2 - (Log + kick + ban)'),
('PartyLevelReq', 'int', 85, '1', NULL, 'Minimum level at which players can invite to group, even if they aren\'t on the invitee friends list. (Players who are on that friend list can always invite despite having lower level)'),
('PartyRaidWarnings', 'bool', 23, '0', NULL, 'Allow any user to use raid warnings when in a 5-man party.'),
('PersistentCharacterCleanFlags', 'int', 135, '0', NULL, 'Determines the character clean flags that remain set after cleanups. This is a bitmask value, check /doc/CharacterDBCleanup.txt for more information. #Example: 14 - (Cleaning up skills, talents and spells will remain enabled after the next cleanup) #Default: 0  - (All cleanup methods will be disabled after the next cleanup)'),
('Player.AutoLearnSpells.Enabled', 'bool', 138, '0', NULL, 'Player will auto learn spell when reach a level (table player_spells_for_level)'),
('Player.UniversalLanguage.Enabled', 'bool', 139, '0', NULL, 'Player talking on Universal language (need for different chatMgr and 1 language for SAY and etc)'),
('PlayerDump.DisallowOverwrite', 'bool', 60, '1', NULL, 'Disallow overwriting existing files with PlayerDump'),
('PlayerDump.DisallowPaths', 'bool', 59, '1', NULL, 'Disallow using paths in PlayerDump output files'),
('PlayerLimit', 'int', 210, '5000', NULL, 'Maximum number of players in the world. Excluding Mods, GMs and Admins.'),
('PlayerSave.Stats.MinLevel', 'int', 121, '0', NULL, 'Minimum level for saving character stats in the database for external usage. #Default: 0  - (Disabled, Do not save character stats) #1+ - (Enabled, Level beyond which character stats are saved)'),
('PlayerSave.Stats.SaveOnlyOnLogout', 'bool', 4, '1', NULL, 'Save player stats only on logout.'),
('PlayerSaveInterval', 'int', 1, '90000', NULL, 'Time (in milliseconds) for player save interval.'),
('PlayerStart.AllReputation', 'bool', 47, '0', NULL, 'Players will start with most of the high level reputations that are needed for items, mounts etc.'),
('PlayerStart.AllSpells', 'bool', 45, '0', NULL, 'If enabled, players will start with all their class spells (not talents). You must populate playercreateinfo_spell_custom table with the spells you want, or this will not work! The table has data for all classes / races up to WoTLK expansion.'),
('PlayerStart.MapsExplored', 'bool', 46, '0', NULL, 'Characters start with all maps explored.'),
('PlayerStart.String', 'string', 3, '', NULL, 'String to be displayed at first login of newly created characters.'),
('PreserveCustomChannelDuration', 'int', 133, '14', NULL, 'Time (in days) that needs to pass before the customs chat channels get cleaned up from the database. Only channels with ownership handout enabled (default behavior) will be cleaned. #Default: 14 - (Enabled, Clean channels that haven\'t been used for 14 days) #0  - (Disabled, Infinite channel storage)'),
('PreserveCustomChannelInterval', 'int', 134, '5', NULL, 'Interval (in minutes) at which custom channel data is saved to the database #Default: 5 minutes'),
('PreserveCustomChannels', 'bool', 58, '1', NULL, 'Description: Store custom chat channel settings like password, automatic ownership handout or ban list in the database. Needs to be enabled to save custom world/trade/etc. channels that have automatic ownership handout disabled. (.channel set ownership $channel off)'),
('PreventRenameCharacterOnCustomization', 'bool', 86, '0', NULL, 'If option is set to 1, player can not rename the character in character customization. Applies to all character customization commands.'),
('PVPBonusCapReward.CapChanges.Lose', 'int', 190, '60', NULL, 'Value for cap after Lose'),
('PVPBonusCapReward.CapChanges.Win', 'int', 189, '180', NULL, 'Value for cap after Win'),
('PVPBonusCapReward.Enabled', 'bool', 121, '1', NULL, 'Enable/Disable custom PVP bonus cap reward for arena. It give bonus weekly reward when cap is complited (1500/1500 by default)'),
('PVPBonusCapReward.MaxCap', 'int', 188, '1500', NULL, 'Max values for Weekly Cap'),
('PvPToken.Enable', 'bool', 49, '0', NULL, 'Character will receive a token after defeating another character that yields honor.'),
('PvPToken.ItemCount', 'int', 114, '1', NULL, 'Number of tokens a character will receive.'),
('PvPToken.ItemID', 'int', 113, '29434', NULL, 'Item characters will receive after defeating another character if PvP Token system is enabled. #Default: 29434 - (Badge of justice)'),
('PvPToken.MapAllowType', 'int', 112, '4', NULL, 'Define where characters can receive tokens. #Default: 4 - (All maps) #3 - (Battlegrounds) #2 - (FFA areas only like Gurubashi arena) # 1 - (Battlegrounds and FFA areas)'),
('Quests.DailyResetTime', 'int', 40, '3', NULL, 'Description: Hour of the day when daily quest reset occurs. Range: 0-23 #Default:     3 - (3:00 AM, Blizzlike)'),
('Quests.EnableQuestTracker', 'bool', 63, '0', NULL, 'Store data in the database about quest completion and abandonment to help finding bugged quests.'),
('Quests.HighLevelHideDiff', 'int', 77, '7', NULL, 'Level difference between player and quest level at which quests are considered high-level and are not shown via exclamation mark (!) at quest givers. #Default: 7  - (Enabled, Hide quests that have 7 levels more than the character) #-1 - (Disabled, Show all available quest marks)'),
('Quests.IgnoreAutoAccept', 'bool', 61, '0', NULL, 'Ignore auto accept flag. Clients will have to manually accept all quests.'),
('Quests.IgnoreAutoComplete', 'bool', 62, '0', NULL, 'Ignore auto complete flag. Clients will have to manually complete all quests.'),
('Quests.IgnoreRaid', 'bool', 22, '0', NULL, 'Allow non-raid quests to be completed while in a raid group.'),
('Quests.LowLevelHideDiff', 'int', 76, '4', NULL, 'Level difference between player and quest level at which quests are considered low-level and are not shown via exclamation mark (!) at quest givers. #Default: 10  - (Enabled, Hide quests that have 10 levels less than the character) #-1 - (Disabled, Show all available quest marks)'),
('Quests.WeeklyResetWDay', 'int', 41, '3', NULL, 'Day of the week when weekly quest reset occurs. #Range: 0 (Sunday) to 6 (Saturday) #Default:     3 - (Wednesday)'),
('RaidInfo.Enabled', 'bool', 120, '1', NULL, 'Enable/Disable custom raid info system for world announce of killed bosses'),
('Rate.ArenaPoints', 'rate', 52, '1', NULL, 'Arena points gain rate.'),
('Rate.Auction.Cut', 'rate', 50, '1', NULL, 'Auction rates (auction time, deposit get at auction start, auction cut from price at auction end).'),
('Rate.Auction.Deposit', 'rate', 49, '1', NULL, 'Auction rates (auction time, deposit get at auction start, auction cut from price at auction end).'),
('Rate.Auction.Time', 'rate', 48, '1', NULL, 'Auction rates (auction time, deposit get at auction start, auction cut from price at auction end).'),
('Rate.Corpse.Decay.Looted', 'rate', 54, '0.5', NULL, 'Multiplier for Corpse.Decay.* to configure how long creature corpses stay after they have been looted. #Default:    0.5'),
('Rate.Creature.Aggro', 'rate', 43, '1', NULL, 'Aggro radius percentage. #Default:  1 - (Enabled, 100%) #1.5 - (Enabled, 150%) #0   - (Disabled, 0%)'),
('Rate.Creature.Elite.Elite.Damage', 'rate', 34, '1', NULL, 'Multiplier for creature melee damage.'),
('Rate.Creature.Elite.Elite.HP', 'rate', 29, '1', NULL, 'Multiplier for creature health.'),
('Rate.Creature.Elite.Elite.SpellDamage', 'rate', 39, '1', NULL, 'Multiplier for creature spell damage.'),
('Rate.Creature.Elite.RARE.Damage', 'rate', 37, '1', NULL, 'Multiplier for creature melee damage.'),
('Rate.Creature.Elite.RARE.HP', 'rate', 32, '1', NULL, 'Multiplier for creature health.'),
('Rate.Creature.Elite.RARE.SpellDamage', 'rate', 42, '1', NULL, 'Multiplier for creature spell damage.'),
('Rate.Creature.Elite.RAREELITE.Damage', 'rate', 35, '1', NULL, 'Multiplier for creature melee damage.'),
('Rate.Creature.Elite.RAREELITE.HP', 'rate', 30, '1', NULL, 'Multiplier for creature health.'),
('Rate.Creature.Elite.RAREELITE.SpellDamage', 'rate', 40, '1', NULL, 'Multiplier for creature spell damage.'),
('Rate.Creature.Elite.WORLDBOSS.Damage', 'rate', 36, '1', NULL, 'Multiplier for creature melee damage.'),
('Rate.Creature.Elite.WORLDBOSS.HP', 'rate', 31, '1', NULL, 'Multiplier for creature health.'),
('Rate.Creature.Elite.WORLDBOSS.SpellDamage', 'rate', 41, '1', NULL, 'Multiplier for creature spell damage.'),
('Rate.Creature.Normal.Damage', 'rate', 33, '1', NULL, 'Multiplier for creature melee damage.'),
('Rate.Creature.Normal.HP', 'rate', 28, '1', NULL, 'Multiplier for creature health.'),
('Rate.Creature.Normal.SpellDamage', 'rate', 38, '1', NULL, 'Multiplier for creature spell damage.'),
('Rate.Damage.Fall', 'rate', 47, '1', NULL, 'Damage after fall rate.'),
('Rate.Drop.Item.Artifact', 'rate', 15, '1', NULL, 'Drop rates for money and items based on quality.'),
('Rate.Drop.Item.Epic', 'rate', 13, '1', NULL, 'Drop rates for money and items based on quality.'),
('Rate.Drop.Item.Legendary', 'rate', 14, '1', NULL, 'Drop rates for money and items based on quality.'),
('Rate.Drop.Item.Normal', 'rate', 10, '1', NULL, 'Drop rates for money and items based on quality.'),
('Rate.Drop.Item.Poor', 'rate', 9, '1', NULL, 'Drop rates for money and items based on quality.'),
('Rate.Drop.Item.Rare', 'rate', 12, '1', NULL, 'Drop rates for money and items based on quality.'),
('Rate.Drop.Item.Referenced', 'rate', 16, '1', NULL, 'Drop rates for money and items based on quality.'),
('Rate.Drop.Item.ReferencedAmount', 'rate', 17, '1', NULL, 'Multiplier for referenced loot amount.'),
('Rate.Drop.Item.Uncommon', 'rate', 11, '1', NULL, 'Drop rates for money and items based on quality.'),
('Rate.Drop.Money', 'rate', 18, '1', NULL, 'Drop rates for money and items based on quality.'),
('Rate.Energy', 'rate', 7, '1', NULL, 'Multiplier to configure health, mana, incoming rage, loss of rage, focus energy and loyalty increase or decrease.'),
('Rate.Focus', 'rate', 6, '1', NULL, 'Multiplier to configure health, mana, incoming rage, loss of rage, focus energy and loyalty increase or decrease.'),
('Rate.Health', 'rate', 0, '1', NULL, 'Multiplier to configure health, mana, incoming rage, loss of rage, focus energy and loyalty increase or decrease.'),
('Rate.Honor', 'rate', 51, '1', NULL, 'Honor gain rate.'),
('Rate.Honor.Premium', 'rate', 67, '1', NULL, 'Individual rate for vip player'),
('Rate.InstanceResetTime', 'rate', 55, '1', NULL, 'Multiplier for the rate between global raid/heroic instance resets (dbc value). Higher value increases the time between resets, lower value lowers the time, you need clean instance_reset in characters db in order to let new values work.'),
('Rate.Mana', 'rate', 1, '1', NULL, 'Multiplier to configure health, mana, incoming rage, loss of rage, focus energy and loyalty increase or decrease.'),
('Rate.MoveSpeed', 'rate', 61, '1', NULL, 'Movement speed rate.'),
('Rate.Quest.Money.Max.Level.Reward', 'rate', 64, '1', NULL, 'Multiplier for money quest rewards. Can not be below 0.'),
('Rate.Quest.Money.Reward', 'rate', 63, '1', NULL, 'Multiplier for money quest rewards. Can not be below 0.'),
('Rate.Rage.Income', 'rate', 2, '1', NULL, 'Multiplier to configure health, mana, incoming rage, loss of rage, focus energy and loyalty increase or decrease.'),
('Rate.Rage.Loss', 'rate', 3, '1', NULL, 'Multiplier to configure health, mana, incoming rage, loss of rage, focus energy and loyalty increase or decrease.'),
('Rate.RepairCost', 'rate', 23, '1', NULL, 'Repair cost rate.'),
('Rate.Reputation.Gain', 'rate', 24, '1', NULL, 'Reputation gain rate.'),
('Rate.Reputation.Gain.Premium', 'rate', 68, '1', NULL, 'Individual rate for vip player'),
('Rate.Reputation.LowLevel.Kill', 'rate', 25, '1', NULL, 'Reputation gain from killing low level (grey) creatures.'),
('Rate.Reputation.LowLevel.Quest', 'rate', 26, '1', NULL, 'Reputation gain rate.'),
('Rate.Reputation.RecruitAFriendBonus', 'rate', 27, '0.1', NULL, 'Reputation bonus rate for recruit-a-friend.'),
('Rate.Rest.InGame', 'rate', 44, '1', NULL, 'Resting points grow rates.'),
('Rate.Rest.Offline.InTavernOrCity', 'rate', 45, '1', NULL, 'Resting points grow rates.'),
('Rate.Rest.Offline.InWilderness', 'rate', 46, '1', NULL, 'Resting points grow rates.'),
('Rate.RunicPower.Income', 'rate', 4, '1', NULL, 'Multiplier to configure health, mana, incoming rage, loss of rage, focus energy and loyalty increase or decrease.'),
('Rate.RunicPower.Loss', 'rate', 5, '1', NULL, 'Multiplier to configure health, mana, incoming rage, loss of rage, focus energy and loyalty increase or decrease.'),
('Rate.Skill.Discovery', 'rate', 8, '1', NULL, 'Multiplier for skill discovery.'),
('Rate.Talent', 'rate', 53, '1', NULL, 'Talent point rate.'),
('Rate.XP.BattlegroundKill', 'rate', 20, '1', NULL, 'Experience rates.'),
('Rate.XP.Explore', 'rate', 22, '1', NULL, 'Experience rates.'),
('Rate.XP.Kill', 'rate', 19, '1', NULL, 'Experience rates.'),
('Rate.XP.Kill.Premium', 'rate', 65, '1', NULL, 'Individual rate for vip player'),
('Rate.XP.Quest', 'rate', 21, '1', NULL, 'Experience rates.'),
('Rate.XP.Quest.Premium', 'rate', 66, '1', NULL, 'Individual rate for vip player'),
('RealmZone', 'int', 11, '1', NULL, 'Server realm zone. Set allowed alphabet in character, etc. names. (1-development any language)'),
('RecruitAFriend.MaxDifference', 'int', 37, '4', NULL, 'Highest level difference between linked Recruiter and Friend benefit from the Recruit-A-Friend experience multiplier.'),
('RecruitAFriend.MaxLevel', 'int', 36, '60', NULL, 'Highest level up to which a character can benefit from the Recruit-A-Friend experience multiplier.'),
('ResetDuelCooldowns', 'bool', 76, '0', NULL, 'Reset all cooldowns before duel starts and restore them when duel ends.'),
('ResetDuelHealthMana', 'bool', 77, '0', NULL, 'Reset health and mana before duel starts and restore them when duel ends.'),
('Respawn.AlertRestartReason', 'string', 1, 'Urgent Maintenance', NULL, 'The shutdown reason given when the alert level is reached. The server will use a fixed time of 5 minutes and the reason for shutdown will be this message'),
('Respawn.DynamicEscortNPC', 'bool', 92, '0', NULL, 'This switch controls the dynamic respawn system for escort NPCs not in instanceable maps (base maps only). This will cause the respawn timer to begin when an escort event begins, and potentially allow multiple instances of the NPC to be alive at the same time (when combined with Respawn.DynamicMode > 0)'),
('Respawn.DynamicMinimumCreature', 'int', 180, '10', NULL, 'The minimum respawn time for a creature under dynamic scaling. #Default: 10 - (10 seconds)'),
('Respawn.DynamicMinimumGameObject', 'int', 181, '10', NULL, 'The minimum respawn time for a GameObject under dynamic scaling.'),
('Respawn.DynamicMode', 'int', 176, '0', NULL, 'Select which mode (if any) should be used to adjust respawn of creatures. This will only affect creatures that have dynamic spawn rate scaling enabled in the spawn group table (by default, gathering nodes and quest targets with respawn time <30min #1 - Use number of players in zone #Default: 0 - No dynamic respawn function'),
('Respawn.DynamicRateCreature', 'float', 18, '10', NULL, 'The rate at which the respawn time is adjusted for high player counts in a zone (for creatures). Up to this number of players, the respawn rate is unchanged. At double this number in players, you get twice as many respawns, at three times this number, three times the respawns, and so forth. #Default: 10'),
('Respawn.DynamicRateGameObject', 'float', 19, '10', NULL, 'The rate at which the respawn time is adjusted for high player counts in a zone (for gameobjects). Up to this number of players, the respawn rate is unchanged. At double this number in players, you get twice as many respawns, at three times this number, three times the respawns, and so forth. #Default: 10'),
('Respawn.GuidAlertLevel', 'int', 178, '16000000', NULL, 'The point at which the highest guid for creatures or gameobjects in any map must reach before the alert logic is enabled. A restart will then be triggered for 30 min. from that point. The maximum guid per map is 16,777,216. So, it must be less than this value. #Default: 16000000 - 16 million'),
('Respawn.GuidWarnLevel', 'int', 177, '12000000', NULL, 'The point at which the highest guid for creatures or gameobjects in any map must reach before the warning logic is enabled. A restart will then be queued at the next quiet time The maximum guid per map is 16,777,216. So, it must be less than this value. #Default: 12000000 - 12 million'),
('Respawn.MinCheckIntervalMS', 'int', 175, '5000', NULL, 'Minimum time that needs to pass between respawn checks for any given map. #Default: 5000 - 5 seconds'),
('Respawn.RestartQuietTime', 'int', 179, '3', NULL, 'The hour at which the server will be restarted after the Respawn.GuidWarnLevel threshold has been reached. This can be between 0 and 23. 20 will be 8pm server time #Default: 3 - 3am'),
('Respawn.WarningFrequency', 'int', 182, '1800', NULL, 'The frequency (in seconds) that the warning message will be sent to users after a quiet time restart is triggered. The message will repeat each time this many seconds passed until the server is restarted. If set to 0, no warnings will be sent. #Default: 1800 - (30 minutes)'),
('Respawn.WarningMessage', 'string', 0, 'There will be an unscheduled server restart at 03:00. The server will be available again shortly after.', NULL, 'This message will be periodically shown (Frequency specified by Respawn.WarningFrequency) to all users of the server, once the Respawn.GuidWarnLevel has been passed, and a restart scheduled. It\'s used to warn users that there will be an out of schedule server restart soon.'),
('Server.LoginInfo', 'bool', 91, '0', NULL, 'Display core version (.server info) on login.'),
('SessionAddDelay', 'int', 9, '10000', NULL, 'Time (in microseconds) that a network thread will sleep after authentication protocol handling before adding a connection to the world session map.'),
('SetDeprecatedExternalPasswords', 'bool', 71, '0', NULL, NULL),
('ShowBanInWorld', 'bool', 53, '0', NULL, 'Determines whether a message is broadcast to the entire server when a player gets banned.'),
('ShowKickInWorld', 'bool', 51, '0', NULL, 'Determines whether a message is broadcast to the entire server when a player gets kicked.'),
('ShowMuteInWorld', 'bool', 52, '0', NULL, 'Determines whether a message is broadcast to the entire server when a player gets muted.'),
('SkillChance.Green', 'int', 60, '25', NULL, 'Chance to increase skill based on recipe color.'),
('SkillChance.Grey', 'int', 61, '0', NULL, 'Chance to increase skill based on recipe color.'),
('SkillChance.Milling', 'bool', 19, '0', NULL, 'Allow skill increase from milling.'),
('SkillChance.MiningSteps', 'int', 62, '0', NULL, 'Skinning and Mining chance decreases with skill level. #Default: 0  - (Disabled) #75 - (In 2 times each 75 skill points)'),
('SkillChance.Orange', 'int', 58, '100', NULL, 'Chance to increase skill based on recipe color.'),
('SkillChance.Prospecting', 'bool', 18, '0', NULL, 'Allow skill increase from prospecting.'),
('SkillChance.SkinningSteps', 'int', 63, '0', NULL, 'Skinning and Mining chance decreases with skill level. #Default: 0  - (Disabled) #75 - (In 2 times each 75 skill points)'),
('SkillChance.Yellow', 'int', 59, '75', NULL, 'Chance to increase skill based on recipe color.'),
('SkillGain.Crafting', 'int', 64, '1', NULL, 'Crafting/defense/gathering/weapon skills gain rate.'),
('SkillGain.Defense', 'int', 65, '1', NULL, 'Crafting/defense/gathering/weapon skills gain rate.'),
('SkillGain.Gathering', 'int', 66, '1', NULL, 'Crafting/defense/gathering/weapon skills gain rate.'),
('SkillGain.Weapon', 'int', 67, '1', NULL, 'Crafting/defense/gathering/weapon skills gain rate.'),
('SkipCinematics', 'int', 25, '0', NULL, 'Disable cinematic intro at first login after character creation. Default:  0 - (Show intro for each new character) 1 - (Show intro only for first character of selected race) 2 - (Disable intro for all classes)'),
('SocketTimeOutTime', 'int', 7, '900', NULL, 'Time (in seconds) after which a connection being idle on the character (900 =15 minutes)'),
('SocketTimeOutTimeActive', 'int', 8, '60', NULL, 'Time (in seconds) after which an idle connection is dropped while logged into the world.'),
('StartArenaPoints', 'int', 35, '0', NULL, 'Amount of arena points that characters has after creation.'),
('StartDeathKnightPlayerLevel', 'int', 29, '55', NULL, 'Starting level for death knight characters after creation.'),
('StartHonorPoints', 'int', 33, '0', NULL, 'Amount of honor points that characters have after creation.'),
('StartPack.Script.Enabled', 'bool', 127, '1', NULL, 'Give a possibility to receive start-pack items from item helper'),
('StartPlayerLevel', 'int', 28, '1', NULL, 'Starting level for characters after creation.'),
('StartPlayerMoney', 'int', 31, '0', NULL, 'Amount of money (in Copper) that a character has after creation.'),
('Stats.Limits.Block', 'float', 12, '95.0', NULL, 'Set percentage limit for dodge, parry, block and crit rating. #Default: 95.0 (95%)'),
('Stats.Limits.Crit', 'float', 13, '95.0', NULL, 'Set percentage limit for dodge, parry, block and crit rating. #Default: 95.0 (95%)'),
('Stats.Limits.Dodge', 'float', 10, '95.0', NULL, 'Set percentage limit for dodge, parry, block and crit rating. #Default: 95.0 (95%)'),
('Stats.Limits.Enable', 'bool', 69, '0', NULL, 'Enable or disable stats system.'),
('Stats.Limits.Parry', 'float', 11, '95.0', NULL, 'Set percentage limit for dodge, parry, block and crit rating. #Default: 95.0 (95%)'),
('StrictCharterNames', 'int', 13, '0', NULL, 'Limit guild/arena team charter names to language specific symbol set. revents charter creation if not allowed symbols are used.'),
('StrictPetNames', 'int', 14, '0', NULL, 'Limit pet names to language specific symbol set. Prevents pet naming if not allowed symbols are used.'),
('StrictPlayerNames', 'int', 12, '0', NULL, 'Limit player name to language specific symbol set. Prevents character creation and forces rename request if not allowed symbols are used '),
('TalentsInspecting', 'int', 174, '1', NULL, 'Allow/disallow inspecting other characters\' talents. Doesn\'t affect game master accounts. #2 - (Enabled for all characters) #Default: 1 - (Enabled for characters of the same faction) #0 - (Talent inspecting is disabled)'),
('ThreatRadius', 'float', 8, '60', NULL, 'Distance for creatures to evade after being pulled away from the combat starting point. If ThreatRadius is less than creature aggro radius then aggro radius will be used. # Default: 60'),
('UI.ShowQuestLevelsInDialogs', 'bool', 67, '0', NULL, 'Show quest levels next to quest titles in UI dialogs # Example:     [13] Westfall Stew#Default:     0  - (Do not show)'),
('UpdateUptimeInterval', 'int', 57, '10', NULL, 'Update realm uptime period (in minutes). #Default:     10 - (10 minutes)'),
('VanishCCbreakTimer', 'int', 184, '300', NULL, 'Vanish Should evade CC spells too, when casted, but it\'s a little lime.'),
('VanishVisionTimer', 'int', 183, '600', NULL, 'Vanish Fade Delay (vanish evade all spells without CC control in this time) (in ms)'),
('VAS.Unit.Enabled', 'bool', 135, '0', NULL, 'VAS Auto Balance system'),
('VAS.Unit.PercentOfDamage', 'rate', 70, '100', NULL, 'Change HP and Damage value for Units in Dungeons in % #Default: 100 - (full HP and Damage) 10 - (units have only 10% of HP or can deal damage 10% of base damage value)'),
('VAS.Unit.PercentOfHeal', 'rate', 71, '100', NULL, 'Change HP and Damage value for Units in Dungeons in % #Default: 100 - (full HP and Damage) 10 - (units have only 10% of HP or can deal damage 10% of base damage value)'),
('VAS.Unit.PercentOfMaxHP', 'rate', 72, '100', NULL, 'Change HP and Damage value for Units in Dungeons in % #Default: 100 - (full HP and Damage) 10 - (units have only 10% of HP or can deal damage 10% of base damage value)'),
('VAS.Unit.PercentOfMaxMP', 'rate', 73, '100', NULL, 'Change HP and Damage value for Units in Dungeons in % #Default: 100 - (full HP and Damage) 10 - (units have only 10% of HP or can deal damage 10% of base damage value)'),
('Visibility.Distance.BGArenas', 'float', 22, '533', NULL, 'Max limited by grid size: 533.33333'),
('Visibility.Distance.Continents', 'float', 20, '100', NULL, 'Visibility on continents on retail ~100 yards.'),
('Visibility.Distance.Instances', 'float', 21, '170', NULL, 'For instances default ~170.'),
('Visibility.GroupMode', 'int', 55, '1', NULL, 'Group visibility modes. Defines which groups can aways detect invisible characters of the same raid, group or faction. #Default:     1 - (Raid) #0 - (Party) #2 - (Faction) #3 - (None)'),
('Visibility.Notify.Period.InBGArenas', 'int', 209, '1000', NULL, 'Time (in milliseconds) for visibility update period. Lower values may have performance impact.'),
('Visibility.Notify.Period.InInstances', 'int', 208, '1000', NULL, 'Time (in milliseconds) for visibility update period. Lower values may have performance impact.'),
('Visibility.Notify.Period.OnContinents', 'int', 207, '1000', NULL, 'Time (in milliseconds) for visibility update period. Lower values may have performance impact.'),
('vmap.enableHeight', 'bool', 143, '1', NULL, 'VMmap support for line of sight and height calculation.'),
('vmap.enableIndoorCheck', 'bool', 44, '1', NULL, 'VMap based indoor check to remove outdoor-only auras (mounts etc.).'),
('vmap.enableLOS', 'bool', 142, '1', NULL, 'VMmap support for line of sight and height calculation.'),
('Warden.BanDuration', 'int', 142, '86400', NULL, 'Time (in seconds) an account will be banned if ClientCheckFailAction is set to ban. #Default: 86400 - (24 hours) #0 - (Permanent ban)'),
('Warden.ClientCheckFailAction', 'int', 141, '0', NULL, 'Default action being taken if a client check failed. Actions can be overwritten for each single check via warden_action table in characters database. #Default: 0 - (Disabled, Logging only) #1 - (Kick) #2 - (Ban)'),
('Warden.ClientCheckHoldOff', 'int', 140, '30', NULL, 'Time (in seconds) to wait before sending the next check request to the client. A low number increases traffic and load on client and server side. #Default: 30 - (30 Seconds) #0  - (Send check as soon as possible)'),
('Warden.ClientResponseDelay', 'int', 139, '600', NULL, 'Time (in seconds) before client is getting disconnecting for not responding. #Default: 600 - (10 Minutes) #0 - (Disabled, client won\'t be kicked)'),
('Warden.Enabled', 'bool', 64, '1', NULL, 'Enable Warden anti-cheat system.'),
('Warden.NumClientModChecks', 'int', 145, '1', NULL, 'Number of Warden checks of the respective category that are sent per cycle.'),
('Warden.NumInjectionChecks', 'int', 143, '9', NULL, 'Number of Warden checks of the respective category that are sent per cycle.'),
('Warden.NumLuaSandboxChecks', 'int', 144, '1', NULL, 'Number of Warden checks of the respective category that are sent per cycle.'),
('Wintergrasp.BattleTimer', 'int', 149, '30', NULL, 'Time (in minutes) for the Wintergrasp battle to last.'),
('Wintergrasp.CrashRestartTimer', 'int', 151, '10', NULL, 'Time (in minutes) to delay the restart of Wintergrasp if the world server crashed during a running battle.'),
('Wintergrasp.Enable', 'bool', 66, '1', NULL, 'Enable the Wintergrasp battlefield.'),
('Wintergrasp.NoBattleTimer', 'int', 150, '150', NULL, 'Time (in minutes) between Wintergrasp battles.'),
('Wintergrasp.PlayerMax', 'int', 146, '100', NULL, 'Maximum number of players allowed in Wintergrasp.'),
('Wintergrasp.PlayerMin', 'int', 147, '0', NULL, 'Minimum number of players required for Wintergrasp.'),
('Wintergrasp.PlayerMinLvl', 'int', 148, '77', NULL, 'Required character level for the Wintergrasp battle.'),
('WorldBossLevelDiff', 'int', 75, '3', NULL, 'World boss level difference.'),
('WorldServerPort', 'int', 6, '8085', NULL, 'TCP port to reach the world server.'),
('XP.Boost.Daymask', 'int', 138, '65', NULL, 'Enables experience boost during the defined days. This field is a bitmask. #Default: 0 - (Disabled) #1 - (Sunday) #2 - (Monday) #4 - (Tuesday) #8 - (Wednesday) #16 - (Thursday) #32 - (Friday) #64 - (Saturday) #65 - (Weekend only) #127 - (Always active)'),
('XP.Boost.Rate', 'rate', 62, '2', NULL, 'The boost multiplier for experience gain during XP boosted days. #Default:     2.0 - (Double experience)');

SET FOREIGN_KEY_CHECKS = 1;
