INSERT INTO `world`.`world_config`(`OptionName`, `Type`, `IDInTypeGroup`, `DefaultValue`, `CustomValue`, `Description`) VALUES 
-- TC configs
('DurabilityLoss.InPvP', 'bool', 0, '0', NULL, 'Durability loss on death during PvP.'),
('AddonChannel', 'bool', 1, '1', NULL, 'Configure the use of the addon channel through the server (some client side addons will not work correctly with disabled addon channel)'),
('CleanCharacterDB', 'bool', 2, '0', NULL, 'Clean out deprecated achievements, skills, spells and talents from the db.'),
('GridUnload', 'bool', 3, '1', NULL, 'Unload grids to save memory. Can be disabled if enough memory is available to speed up moving players to new grids.'),
('PlayerSave.Stats.SaveOnlyOnLogout', 'bool', 4, '1', NULL, 'Save player stats only on logout.'),
('AllowTwoSide.Interaction.Calendar', 'bool', 5, '0', NULL, 'Allow calendar invites between factions.'),
('AllowTwoSide.Interaction.Channel', 'bool', 6, '0', NULL, 'Allow channel chat between factions. (But not Universal languagem only 1 channelMgr)'),
('AllowTwoSide.Interaction.Group', 'bool', 7, '0', NULL, 'Allow group joining between factions.'),
('AllowTwoSide.Interaction.Guild', 'bool', 8, '0', NULL, 'Allow guild joining between factions.'),
('AllowTwoSide.Interaction.Auction', 'bool', 9, '0', NULL, 'Allow auctions between factions.'),
('AllowTwoSide.Trade', 'bool', 10, '0', NULL, 'Allow trading between factions.'),
('AllFlightPaths', 'bool', 11, '0', NULL, 'Character knows all flight paths (of both factions) after creation.'),
('InstantFlightPaths', 'bool', 12, '0', NULL, 'Flight paths will take players to their destination instantly instead of making them wait while flying.'),
('Instance.IgnoreLevel', 'bool', 13, '0', NULL, 'Ignore level requirement when entering instances.'),
('Instance.IgnoreRaid', 'bool', 14, '0', NULL, 'Ignore raid group requirement when entering instances.'),
('CastUnstuck', 'bool', 15, '1', NULL, 'Allow casting the Unstuck spell using .start or unstuck button in client help options.'),
('GM.AllowInvite', 'bool', 16, '0', NULL, 'Allow players to invite GM characters.'),
('GM.LowerSecurity', 'bool', 17, '0', NULL, 'Allow lower security levels to use commands on higher security level characters.'),
('SkillChance.Prospecting', 'bool', 18, '0', NULL, 'Allow skill increase from prospecting.'),
('SkillChance.Milling', 'bool', 19, '0', NULL, 'Allow skill increase from milling.'),
('ActivateWeather', 'bool', 20, '1', NULL, 'Activate the weather system.'),
('AlwaysMaxSkillForLevel', 'bool', 21, '0', NULL, 'Players will automatically gain max skill level when logging in or leveling up.'),
('Quests.IgnoreRaid', 'bool', 22, '0', NULL, 'Allow non-raid quests to be completed while in a raid group.'),
('PartyRaidWarnings', 'bool', 23, '0', NULL, 'Allow any user to use raid warnings when in a 5-man party.'),
('DetectPosCollision', 'bool', 24, '1', NULL, 'Check final move position, summon position, etc for visible collision with other objects or walls (walls only if vmaps are enabled).'),
('Channel.RestrictedLfg', 'bool', 25, '1', NULL, 'Restrict LookupForGroup channel to characters registered in the LFG tool.'),
('ChatFakeMessagePreventing', 'bool', 26, '1', NULL, 'Additional protection from creating fake chat messages using spaces. Collapses multiple subsequent whitespaces into a single whitespace. Not applied to the addon language, but may break old addons that use \"normal\" chat messages for sending data to other clients.'),
('Death.CorpseReclaimDelay.PvP', 'bool', 27, '1', NULL, 'Increase corpse reclaim delay at PvP/PvE deaths.'),
('Death.CorpseReclaimDelay.PvE', 'bool', 28, '1', NULL, 'Increase corpse reclaim delay at PvP/PvE deaths.'),
('Death.Bones.World', 'bool', 29, '1', NULL, 'Create bones instead of corpses at resurrection in normal zones, instances, battleground or arenas.'),
('Death.Bones.BattlegroundOrArena', 'bool', 30, '1', NULL, 'Create bones instead of corpses at resurrection in normal zones, instances, battleground or arenas.'),
('Die.Command.Mode', 'bool', 31, '1', NULL, 'Do not trigger things like loot from .die command.'),
('DeclinedNames', 'bool', 32, '1', NULL, 'Allow Russian clients to set and use declined names.'),
('Battleground.CastDeserter', 'bool', 33, '1', NULL, 'Cast Deserter spell at players who leave battlegrounds in progress.'),
('Battleground.QueueAnnouncer.Enable', 'bool', 34, '0', NULL, 'Announce battleground queue status to chat.'),
('Battleground.QueueAnnouncer.PlayerOnly', 'bool', 35, '0', NULL, 'Battleground queue announcement type. Default: 0 - (System message, Anyone can see it) #1 - (Private, Only queued players can see it)'),
('Battleground.StoreStatistics.Enable', 'bool', 36, '0', NULL, 'Store Battleground scores in the database.'),
('Battleground.TrackDeserters.Enable', 'bool', 37, '0', NULL, 'Track deserters of Battlegrounds.'),
('Battleground.GiveXPForKills', 'bool', 38, '0', NULL, 'Give experience for honorable kills in battlegrounds, the rate can be changed in the Rate.XP.BattlegroundKill setting.'),
('Arena.AutoDistributePoints', 'bool', 39, '0', NULL, 'Automatically distribute arena points.'),
('Arena.QueueAnnouncer.Enable', 'bool', 40, '0', NULL, 'Announce arena queue status to chat.'),
('Arena.ArenaSeason.InProgress', 'bool', 41, '1', NULL, 'State of current arena season. Default: 1 - (Active) #0 - (Finished)'),
('ArenaLog.ExtendedInfo', 'bool', 42, '0', NULL, 'Include extended info to ArenaLogFile for each player after rated arena matches (guid, name, team, IP, healing/damage done, killing blows).'),
('OffhandCheckAtSpellUnlearn', 'bool', 43, '1', NULL, 'Unlearning certain spells can change offhand weapon restrictions for equip slots. Default: 1 - (Recheck offhand slot weapon at unlearning a spell) # 0 - (Recheck offhand slot weapon only at zone update)'),
('vmap.enableIndoorCheck', 'bool', 44, '1', NULL, 'VMap based indoor check to remove outdoor-only auras (mounts etc.).'),
('PlayerStart.AllSpells', 'bool', 45, '0', NULL, 'If enabled, players will start with all their class spells (not talents). You must populate playercreateinfo_spell_custom table with the spells you want, or this will not work! The table has data for all classes / races up to WoTLK expansion.'),
('PlayerStart.MapsExplored', 'bool', 46, '0', NULL, 'Characters start with all maps explored.'),
('PlayerStart.AllReputation', 'bool', 47, '0', NULL, 'Players will start with most of the high level reputations that are needed for items, mounts etc.'),
('AlwaysMaxWeaponSkill', 'bool', 48, '0', NULL, 'Players will automatically gain max weapon/defense skill when logging in, or leveling.'),
('PvPToken.Enable', 'bool', 49, '0', NULL, 'Character will receive a token after defeating another character that yields honor.'),
('NoResetTalentsCost', 'bool', 50, '0', NULL, 'Resetting talents doesn\'t cost anything.'),
('ShowKickInWorld', 'bool', 51, '0', NULL, 'Determines whether a message is broadcast to the entire server when a player gets kicked.'),
('ShowMuteInWorld', 'bool', 52, '0', NULL, 'Determines whether a message is broadcast to the entire server when a player gets muted.'),
('ShowBanInWorld', 'bool', 53, '0', NULL, 'Determines whether a message is broadcast to the entire server when a player gets banned.'),
('AutoBroadcast.On', 'bool', 54, '0', NULL, 'Enable auto broadcast.'),
('AllowTickets', 'bool', 55, '1', NULL, 'Allow/disallow sending new tickets.'),
('DeletedCharacterTicketTrace', 'bool', 56, '0', NULL, 'Keep trace of tickets opened by deleted characters gm_ticket.playerGuid will be 0, old GUID and character name will be included in gm_ticket.comment'),
('DBC.EnforceItemAttributes', 'bool', 57, '1', NULL, 'Disallow overriding item attributes stored in DBC files with values from the database.'),
('PreserveCustomChannels', 'bool', 58, '1', NULL, 'Description: Store custom chat channel settings like password, automatic ownership handout or ban list in the database. Needs to be enabled to save custom world/trade/etc. channels that have automatic ownership handout disabled. (.channel set ownership $channel off)'),
('PlayerDump.DisallowPaths', 'bool', 59, '1', NULL, 'Disallow using paths in PlayerDump output files'),
('PlayerDump.DisallowOverwrite', 'bool', 60, '1', NULL, 'Disallow overwriting existing files with PlayerDump'),
('Quests.IgnoreAutoAccept', 'bool', 61, '0', NULL, 'Ignore auto accept flag. Clients will have to manually accept all quests.'),
('Quests.IgnoreAutoComplete', 'bool', 62, '0', NULL, 'Ignore auto complete flag. Clients will have to manually complete all quests.'),
('Quests.EnableQuestTracker', 'bool', 63, '0', NULL, 'Store data in the database about quest completion and abandonment to help finding bugged quests.'),
('Warden.Enabled', 'bool', 64, '1', NULL, 'Enable Warden anti-cheat system.'),
('mmap.enablePathFinding', 'bool', 65, '1', NULL, 'Enable/Disable pathfinding using mmaps - recommended.'),
('Wintergrasp.Enable', 'bool', 66, '1', NULL, 'Enable the Wintergrasp battlefield.'),
('Event.Announce', 'bool', 67, '0', NULL, 'Announce events.'),
('Stats.Limits.Enable', 'bool', 68, '0', NULL, 'Enable or disable stats system.'),
('InstancesResetAnnounce', 'bool', 69, '0', NULL, 'Announce the reset of one instance to whole party.'),
-- ('SetDeprecatedExternalPasswords', 'bool', 70, '0', NULL, NULL),
('Allow.IP.Based.Action.Logging', 'bool', 70, '0', NULL, 'Logs actions, e.g. account login and logout to name a few, based on IP of current session.'),
('AllowTrackBothResources', 'bool', 71, '0', NULL, 'Allows players to track herbs and minerals at the same time (if they have the skills)'),
('Calculate.Creature.Zone.Area.Data', 'bool', 72, '0', NULL, 'Calculate at loading creature zoneId / areaId and save in creature table (WARNING: SLOW WORLD SERVER STARTUP)'),
('Calculate.Gameoject.Zone.Area.Data', 'bool', 73, '0', NULL, 'Calculate at loading gameobject zoneId / areaId and save in gameobject table (WARNING: SLOW WORLD SERVER STARTUP)'),
('ResetDuelCooldowns', 'bool', 74, '0', NULL, 'Reset all cooldowns before duel starts and restore them when duel ends.'),
('ResetDuelHealthMana', 'bool', 75, '0', NULL, 'Reset health and mana before duel starts and restore them when duel ends.'),
('BaseMapLoadAllGrids', 'bool', 76, '0', NULL, 'Load all grids for base maps upon load. Requires GridUnload to be 0. This will take around 5GB of ram upon server load, and will take some time to initially load the server.'),
('InstanceMapLoadAllGrids', 'bool', 77, '0', NULL, 'Load all grids for instance maps upon load. Requires GridUnload to be 0. Upon loading an instance map, all creatures/objects in the map will be pre-loaded'),
('HotSwap.Enabled', 'bool', 78, '1', NULL, 'Enables dynamic script hotswapping. Reloads scripts on changes.'),
('HotSwap.EnableReCompiler', 'bool', 79, '1', NULL, 'Enables the dynamic script recompiler. Watches your script source directories and recompiles the script modules on changes.'),
('HotSwap.EnableEarlyTermination', 'bool', 80, '1', NULL, 'Terminate the build of a module when an associated source file was changed meanwhile.'),
('HotSwap.EnableBuildFileRecreation', 'bool', 81, '1', NULL, 'Recreate build files when sources to a module were added or removed.'),
('HotSwap.EnableInstall', 'bool', 82, '1', NULL, 'Enables cmake install after automatic builds have finished'),
('HotSwap.EnablePrefixCorrection', 'bool', 83, '1', NULL, 'Allows the core to automatic set the CMAKE_INSTALL_PREFIX to its current location in the file system.'),
('PreventRenameCharacterOnCustomization', 'bool', 84, '0', NULL, 'If option is set to 1, player can not rename the character in character customization. Applies to all character customization commands.'),
('CacheDataQueries', 'bool', 85, '1', NULL, 'Server caches data queries at startup. Can be disabled if not enough memory is available.'),
('CheckGameObjectLoS', 'bool', 86, '1', NULL, 'Include dynamic game objects (doors, chests etc.) in line of sight checks. This increases CPU usage somewhat.'),
('Respawn.DynamicEscortNPC', 'bool', 87, '0', NULL, 'This switch controls the dynamic respawn system for escort NPCs not in instanceable maps (base maps only). This will cause the respawn timer to begin when an escort event begins, and potentially allow multiple instances of the NPC to be alive at the same time (when combined with Respawn.DynamicMode > 0)'),
('Creature.RegenHPCannotReachTargetInRaid', 'bool', 88, '1', NULL, 'Regenerates HP for Creatures in Raids if they cannot reach the target.'),
('AllowLoggingIPAddressesInDatabase', 'bool', 89, '1', NULL, 'Specifies if IP addresses can be logged to the database'),
-- AT configs
('Guild.AllowMultipleGuildMaster', 'bool', 90, '0', NULL, 'Allow more than one guild master. Additional Guild Masters must be set using the \".guild rank\" command.'),
('vmap.enableLOS', 'bool', 91, '1', NULL, 'VMmap support for line of sight and height calculation.'),
('vmap.enableHeight', 'bool', 92, '1', NULL, 'VMmap support for line of sight and height calculation.'),
('Server.LoginInfo', 'bool', 93, '0', NULL, 'Display core version (.server info) on login.'),
('CheckM2ObjectLoS', 'bool', 94, '1', NULL, 'Include M2 objects (trees etc.) in line of sight checks.'),
('AntiCheats.FakeJumper.Enabled', 'bool', 95, '1', NULL, 'Enable AntiCheat.FakeJumper : when player sent a move opcode (with new Z higher) when has flag falling (client can\'t sent any new packets when falling) It\'s normal for Gagarin hacks and with Air Mode + \"space\" click = \"falling\" mode (player can\'t change orientation of flying, but it move up)'),
('AntiCheats.FakeFlyingmode.Enabled', 'bool', 96, '1', NULL, 'Enable AntiCheat.FakeFlyingmode : when player sent a move opcode with added fly flag but on server this flag doesn\'t restricted for player. It\'s normal for Hitchhiker\'s Hack with Air Mode'),
('AntiCheats.DoubleJump.Enabled', 'bool', 97, '1', NULL, 'Enable AntiCheat.DoubleJump Kick when player sent opcode jump when has flag falling (client can\'t do this)'),
('AntiCheats.FlyHack.Enabled', 'bool', 98, '1', NULL, 'Enable AntiCheat.FlyHack'),
('AntiCheats.SpeedHack.Enabled', 'bool', 99, '1', NULL, 'Enable AntiCheat.SpeedHack'),
('AntiCheats.IgnoreControlMovement.Enabled', 'bool', 100, '1', NULL, 'Enable AntiCheat.IgnoreControlMovement : when player in root state - client can\'t send a new movement packets'),
('AntiCheats.SpeedHack.Kick.Enabled', 'bool', 101, '1', NULL, 'Enable AntiCheat.SpeedHack Kick when detected'),
('AntiCheats.FlyHack.Kick.Enabled', 'bool', 102, '1', NULL, 'Enable AntiCheat.FlyHack Kick when detected'),
('AntiCheats.FakeJumper.Kick.Enabled', 'bool', 103, '1', NULL, 'Enable AntiCheats.FakeJumper Kick when detected'),
('AntiCheats.FakeFlyingmode.Kick.Enabled', 'bool', 104, '1', NULL, 'Enable AntiCheats.FakeFlyingmode Kick when detected'),
('AntiCheats.NoFallingDmg.Kick.Enabled', 'bool', 105, '1', NULL, 'Enable AntiCheats.NoFallingDmg Kick when detected'),
('CrossfactionBG.enable', 'bool', 106, '1', NULL, 'Mixed battleground'),
('GSystem.LootBroadcast.Enabled', 'bool', 107, '1', NULL, 'Guild announce when member take a loot with Quality >= EPIC'),
('FLAB.Script.Enabled', 'bool', 108, '1', NULL, 'First character on account will receive a money bonus'),
('LFG.Channel.Everywhere', 'bool', 109, '1', NULL, 'Allow access at LookupForGroup channel to characters without condition of LFG state.'),
('Config.Vip.Debuff.Command', 'bool', 110, '0', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Bank.Command', 'bool', 111, '0', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Mail.Command', 'bool', 112, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Repair.Command', 'bool', 113, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Reset.Talents.Command', 'bool', 114, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Taxi.Command', 'bool', 115, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Home.Command', 'bool', 116, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Change.Race.Command', 'bool', 117, '0', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Customize.Command', 'bool', 118, '0', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Capital.Command', 'bool', 119, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Appear.Command', 'bool', 120, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Item.Helper', 'bool', 121, '1', NULL, 'Enable/Disable Item helper in game'),
('RaidInfo.Enabled', 'bool', 122, '1', NULL, 'Enable/Disable custom raid info system for world announce of killed bosses'),
('PVPBonusCapReward.Enabled', 'bool', 123, '1', NULL, 'Enable/Disable custom PVP bonus cap reward for arena. It give bonus weekly reward when cap is complited (1500/1500 by default)'),
('LFG.CrossFaction.Groups', 'bool', 124, '1', NULL, 'Enable/Disable custom system for crossfaction DungeonFinder groups'),
('OSXPlayers.Enabled', 'bool', 125, '1', NULL, 'We can block connect for players from OSX OS system'),
('Antispam.Mail.Enabled', 'bool', 126, '1', NULL, 'When player will receive this limit, he just can\'t bid or bidout from auction. Calendar will not sent mail him.  And another player can\'t sent mail to him, just will see error overloaded mailbox of receiver.'),
('Chat.StrictMessages.Enabled', 'bool', 127, '1', NULL, 'Limit player message to language specific symbol set. Prevents character messages and ignore request if not allowed symbols are used'),
('BAG.Script.Enabled', 'bool', 128, '1', NULL, 'Created character will receive a bags bonus'),
('StartPack.Script.Enabled', 'bool', 129, '1', NULL, 'Give a possibility to receive start-pack items from item helper'),
('DuelPhase.Enabled', 'bool', 130, '1', NULL, 'Make a special phase for duel members, they will see only oponent, and can\'t see others units'),
('GSystem.GuildLevel.Enabled', 'bool', 131, '1', NULL, 'Make a possible guild level system'),
('GSystem.GuildWars.Enabled', 'bool', 132, '1', NULL, 'Give possibility to make Guild Wars between guilds'),
('GSystem.GuildWars.BetweenBothFaction.Enabled', 'bool', 133, '1', NULL, 'Give possibility to make Guild Wars between guilds from both faction (Alliance and Horde)'),
('GSystem.GuildLevel.ShowLevelGuild.WhoList.Enabled', 'bool', 134, '1', NULL, 'Make a visible guild level in whoList'),
('GSystem.GuildLevel.ShowLevelGuild.QueryList.Enabled', 'bool', 135, '1', NULL, 'Make a visible guild level in query opcode (visible name/guild above character)'),
('GSystem.GuildWars.ShowLevelGuild.EnemyList.Enabled', 'bool', 136, '1', NULL, 'Show Enemy Guild Level in GW enemy list'),
('VAS.Unit.Enabled', 'bool', 137, '0', NULL, 'VAS Auto Balance system'),
('DalaranGEvent.InstantReviveAndReturn.Enable', 'bool', 138, '0', NULL, NULL),
('DalaranGEvent.Squad.Enable', 'bool', 139, '0', NULL, NULL),
('Player.AutoLearnSpells.Enabled', 'bool', 140, '0', NULL, 'Player will auto learn spell when reach a level (table player_spells_for_level)'),
('Player.UniversalLanguage.Enabled', 'bool', 141, '0', NULL, 'Player talking on Universal language (need for different chatMgr and 1 language for SAY and etc)'),
('External.Mail.Enable', 'bool', 142, '1', NULL, 'MailMgr will look in External table for receive a new mails from site ot something else');
