DELETE FROM `world_config` WHERE `Type` = 'int' AND `IDInTypeGroup` between 0 and 190;
INSERT INTO `world_config`(`OptionName`, `Type`, `IDInTypeGroup`, `DefaultValue`, `CustomValue`, `Description`) VALUES 
-- TC configs
('Compression', 'int', 0, '1', NULL, 'Compression level for client update packages. (1   - (Speed) -- 9   - (Best compression))'),
('PlayerSaveInterval', 'int', 1, '90000', NULL, 'Time (in milliseconds) for player save interval.'),
('GridCleanUpDelay', 'int', 2, '300000', NULL, 'Time (in milliseconds) grid clean up delay.'),
('MapUpdateInterval', 'int', 3, '10', NULL, 'Time (milliseconds) for map update interval.'),
('ChangeWeatherInterval', 'int', 4, '600000', NULL, 'Time (in milliseconds) for weather update interval.'),
('DisconnectToleranceInterval', 'int', 5, '0', NULL, 'Tolerance (in seconds) for disconnected players before reentering the queue.'),
('WorldServerPort', 'int', 6, '8085', NULL, 'TCP port to reach the world server.'),
('SocketTimeOutTime', 'int', 7, '900', NULL, 'Time (in seconds) after which a connection being idle on the character (900 =15 minutes)'),
('SessionAddDelay', 'int', 8, '10000', NULL, 'Time (in microseconds) that a network thread will sleep after authentication protocol handling before adding a connection to the world session map.'),
('GameType', 'int', 9, '0', NULL, 'Server realm type : 0 - normal, 1-pvp, 4-normal, 6-RP, 8-RPPVP, 16-FFA PVP'),
('RealmZone', 'int', 10, '1', NULL, 'Server realm zone. Set allowed alphabet in character, etc. names. (1-development any language)'),
('StrictPlayerNames', 'int', 11, '0', NULL, 'Limit player name to language specific symbol set. Prevents character creation and forces rename request if not allowed symbols are used '),
('StrictCharterNames', 'int', 12, '0', NULL, 'Limit guild/arena team charter names to language specific symbol set. revents charter creation if not allowed symbols are used.'),
('StrictPetNames', 'int', 13, '0', NULL, 'Limit pet names to language specific symbol set. Prevents pet naming if not allowed symbols are used.'),
('MinPlayerName', 'int', 14, '2', NULL, 'Minimal player name length. Range: 1-12'),
('MinCharterName', 'int', 15, '2', NULL, 'Minimal charter name length. Range: 1-24'),
('MinPetName', 'int', 16, '2', NULL, 'Minimal pet name length. Range: 1-12'),
('CharacterCreating.Disabled', 'int', 17, '0', NULL, 'Disable character creation for players based on faction. 0 - (Enabled, All factions are allowed) 1 - (Disabled, Alliance) 2 - (Disabled, Horde)  3 - (Disabled, Both factions)'),
('CharacterCreating.Disabled.RaceMask', 'int', 18, '0', NULL, 'Mask of races which cannot be created by players. # Example:     1536 - (1024 + 512, Blood Elf and Draenei races are disabled) 0    - (Enabled, All races are allowed) 1    - (Disabled, Human) 2    - (Disabled, Orc) 4    - (Disabled, Dwarf) 8    - (Disabled, Night Elf) 16   - (Disabled, Undead) 32   - (Disabled, Tauren) 64   - (Disabled, Gnome) 128  - (Disabled, Troll) 512  - (Disabled, Blood Elf) 1024 - (Disabled, Draenei)'),
('CharacterCreating.Disabled.ClassMask', 'int', 19, '0', NULL, 'Mask of classes which cannot be created by players. Example:     288 - (32 + 256, Death Knight and Warlock classes are disabled). 0    - (Enabled, All classes are allowed) 1    - (Disabled, Warrior) 2    - (Disabled, Paladin) 4    - (Disabled, Hunter) 8    - (Disabled, Rogue) 16   - (Disabled, Priest) 32   - (Disabled, Death Knight) 64   - (Disabled, Shaman) 128  - (Disabled, Mage) 256  - (Disabled, Warlock) 1024 - (Disabled, Druid)'),
('CharactersPerAccount', 'int', 20, '50', NULL, 'Limit number of characters per account on all realms on this realmlist.'),
('CharactersPerRealm', 'int', 21, '10', NULL, 'Limit number of characters per account on this realm. Range: 1-10'),
('DeathKnightsPerRealm', 'int', 22, '1', NULL, 'Limit number of death knight characters per account on this realm. Range:       1-10'),
('CharacterCreating.MinLevelForDeathKnight', 'int', 23, '55', NULL, 'Limit creating death knights only for account with another character of specific level (ignored for GM accounts).'),
('SkipCinematics', 'int', 24, '0', NULL, 'Disable cinematic intro at first login after character creation. Default:  0 - (Show intro for each new character) 1 - (Show intro only for first character of selected race) 2 - (Disable intro for all classes)'),
('MaxPlayerLevel', 'int', 25, '80', NULL, 'Maximum level that can be reached by players.'),
('MinDualSpecLevel', 'int', 26, '40', NULL, 'Level requirement for Dual Talent Specialization.'),
('StartPlayerLevel', 'int', 27, '1', NULL, 'Starting level for characters after creation.'),
('StartDeathKnightPlayerLevel', 'int', 28, '55', NULL, 'Starting level for death knight characters after creation.'),
('StartPlayerMoney', 'int', 29, '0', NULL, 'Amount of money (in Copper) that a character has after creation.'),
('MaxHonorPoints', 'int', 30, '75000', NULL, 'Maximum honor points a character can have.'),
('StartHonorPoints', 'int', 31, '0', NULL, 'Amount of honor points that characters have after creation.'),
('MaxArenaPoints', 'int', 32, '10000', NULL, 'Maximum arena points a character can have.'),
('StartArenaPoints', 'int', 33, '0', NULL, 'Amount of arena points that characters has after creation.'),
('RecruitAFriend.MaxLevel', 'int', 34, '60', NULL, 'Highest level up to which a character can benefit from the Recruit-A-Friend experience multiplier.'),
('RecruitAFriend.MaxDifference', 'int', 35, '4', NULL, 'Highest level difference between linked Recruiter and Friend benefit from the Recruit-A-Friend experience multiplier.'),
('Instance.ResetTimeHour', 'int', 36, '4', NULL, 'Hour of the day when the global instance reset occurs. # Range:       0-23 # Default:     4 - (04:00 AM)'),
('Instance.UnloadDelay', 'int', 37, '1800000', NULL, 'Time (in milliseconds) before instance maps are unloaded from memory if no characters are inside. #Default: 1800000 - (Enabled, 30 minutes) 0       - (Disabled, Instance maps are kept in memory until the instance resets)'),
('Quests.DailyResetTime', 'int', 38, '3', NULL, 'Description: Hour of the day when daily quest reset occurs. Range: 0-23 #Default:     3 - (3:00 AM, Blizzlike)'),
('Quests.WeeklyResetWDay', 'int', 39, '3', NULL, 'Day of the week when weekly quest reset occurs. #Range: 0 (Sunday) to 6 (Saturday) #Default:     3 - (Wednesday)'),
('MaxPrimaryTradeSkill', 'int', 40, '2', NULL, 'Maximum number of primary professions a character can learn. #Range:       0-11'),
('MinPetitionSigns', 'int', 41, '9', NULL, 'Number of required signatures on charters to create a guild. #Range:       0-9'),
('MinQuestScaledXPRatio', 'int', 42, '0', NULL, 'Min ratio of experience that a quest can grant when player level scaling is factored. Example:  50 (No less than 50% experience granted from a lower leveled quests completion) #100 (Quests always grant full experience upon completion) #Default:     0 - (Quests too low may grant no experience)'),
('MinCreatureScaledXPRatio', 'int', 43, '0', NULL, 'Min ratio of experience that a creature kill can grant when player level scaling is factored.  This will also allow spell procs to trigger, such as Drain Soul, if > 0 and exp is grantable. #Example: 50 (No less than 50% experience granted from a lower leveled creature kill) #100 (Creature kills always grant full experience upon kill) #Default:     0 - (Creatures too low may grant no experience)'),
('MinDiscoveredScaledXPRatio', 'int', 44, '0', NULL, 'Min ratio of experience that an area discovery event will grant when player level scaling is factored. #Example: 50 (No less than 50% experience granted from discovering a new section of map) #00 (Map exploration always grant full experience upon discovery) Default:     0 - (No experience granted when discovered area is too low level)'),
('GM.LoginState', 'int', 45, '2', NULL, 'GM mode at login. #Default:     2 - (Last save state) #0 - (Disable) # 1 - (Enable)'),
('GM.Visible', 'int', 46, '2', NULL, 'GM visibility at login. #Default:     2 - (Last save state) #0 - (Invisible) #1 - (Visible)'),
-- ('CONFIG_GM_ACCEPT_TICKETS', 'int', 47, '2', NULL, ''),
('GM.Chat', 'int', 48, '2', NULL, 'Description: GM chat mode at login. #Default:     2 - (Last save state) # 0 - (Disable) # 1 - (Enable)'),
('GM.WhisperingTo', 'int', 49, '2', NULL, 'Is GM accepting whispers from player by default or not. #Default:     2 - (Last save state) #0 - (Disable) #1 - (Enable)'),
('GM.FreezeAuraDuration', 'int', 50, '0', NULL, 'Allows to set a default duration to the Freeze Aura #applied on players when using the .freeze command #Default:     0 - (Original aura duration. Lasts until the .unfreeze command is used) #N - (Aura duration if unspecified in .freeze command, in seconds)'),
('GM.InGMList.Level', 'int', 51, '3', NULL, 'Maximum GM level shown in GM list (if enabled) in non-GM state (.gm off). #Default:     3 - (Anyone) #0 - (Only players) #1 - (Only moderators) #2 - (Only gamemasters)'),
('GM.InWhoList.Level', 'int', 52, '3', NULL, 'Max GM level showed in who list (if visible). #Default: 3 - (Anyone) #0 - (Only players) #1 - (Only moderators) #2 - (Only gamemasters)'),
('GM.StartLevel', 'int', 53, '1', NULL, 'GM character starting level.'),
('GM.ForceShutdownThreshold', 'int', 54, '30', NULL, 'Minimum shutdown time in seconds before \'force\' is required if other players are connected. #Default:     30'),
('Visibility.GroupMode', 'int', 55, '1', NULL, 'Group visibility modes. Defines which groups can aways detect invisible characters of the same raid, group or faction. #Default:     1 - (Raid) #0 - (Party) #2 - (Faction) #3 - (None)'),
('MailDeliveryDelay', 'int', 56, '3600', NULL, 'Time (in seconds) mail delivery is delayed when sending items. #Default:     3600 - (1 hour)'),
('CleanOldMailTime', 'int', 57, '4', NULL, 'The hour at which old mails will be returned or deleted by the server. This can be any integer number from 0 to 23. 20 will be 8pm server time.'),
('UpdateUptimeInterval', 'int', 58, '10', NULL, 'Update realm uptime period (in minutes). #Default:     10 - (10 minutes)'),
('SkillChance.Orange', 'int', 59, '100', NULL, 'Chance to increase skill based on recipe color.'),
('SkillChance.Yellow', 'int', 60, '75', NULL, 'Chance to increase skill based on recipe color.'),
('SkillChance.Green', 'int', 61, '25', NULL, 'Chance to increase skill based on recipe color.'),
('SkillChance.Grey', 'int', 62, '0', NULL, 'Chance to increase skill based on recipe color.'),
('SkillChance.MiningSteps', 'int', 63, '0', NULL, 'Skinning and Mining chance decreases with skill level. #Default: 0  - (Disabled) #75 - (In 2 times each 75 skill points)'),
('SkillChance.SkinningSteps', 'int', 64, '0', NULL, 'Skinning and Mining chance decreases with skill level. #Default: 0  - (Disabled) #75 - (In 2 times each 75 skill points)'),
('SkillGain.Crafting', 'int', 65, '1', NULL, 'Crafting/defense/gathering/weapon skills gain rate.'),
('SkillGain.Defense', 'int', 66, '1', NULL, 'Crafting/defense/gathering/weapon skills gain rate.'),
('SkillGain.Gathering', 'int', 67, '1', NULL, 'Crafting/defense/gathering/weapon skills gain rate.'),
('SkillGain.Weapon', 'int', 68, '1', NULL, 'Crafting/defense/gathering/weapon skills gain rate.'),
('MaxOverspeedPings', 'int', 69, '2', NULL, 'Maximum overspeed ping count before character is disconnected. #Default: 2  - (Enabled, Minimum value) #3+ - (Enabled, More checks before kick) #0  - (Disabled)'),
('Expansion', 'int', 70, '2', NULL, 'Allow server to use content from expansions. Checks for expansion-related map files, client compatibility and class/race character creation. #Default: 2 - (Expansion 2) #1 - (Expansion 1) #0 - (Disabled, Ignore and disable expansion content (maps, races, classes)'),
('ChatFlood.MessageCount', 'int', 71, '10', NULL, 'Chat flood protection, number of messages before player gets muted. #Default:     10 - (Enabled) #0  - (Disabled)'),
('ChatFlood.MessageDelay', 'int', 72, '1', NULL, 'Time (in seconds) between messages to be counted into ChatFlood.MessageCount.'),
('ChatFlood.AddonMessageCount', 'int', 73, '10', NULL, 'Chat flood protection, number of addon messages before player gets muted. (100 - enabled, 0 - disabled)'),
('ChatFlood.AddonMessageDelay', 'int', 74, '1', NULL, 'Time (in seconds) between addon messages to be counted into ChatFlood.AddonMessageCount.'),
('ChatFlood.MuteTime', 'int', 75, '10', NULL, 'Time (in seconds) characters get muted for violating ChatFlood.MessageCount. #Default:     10'),
('CreatureFamilyAssistanceDelay', 'int', 76, '1500', NULL, 'Time (in milliseconds) before creature assistance call. #Default:     1500 - (1.5 Seconds)'),
('CreatureFamilyFleeDelay', 'int', 77, '7000', NULL, 'Time (in milliseconds) during which creature can flee if no assistance was found. #Default:     7000 (7 Seconds)'),
('WorldBossLevelDiff', 'int', 78, '3', NULL, 'World boss level difference.'),
('Quests.LowLevelHideDiff', 'int', 79, '4', NULL, 'Level difference between player and quest level at which quests are considered low-level and are not shown via exclamation mark (!) at quest givers. #Default: 10  - (Enabled, Hide quests that have 10 levels less than the character) #-1 - (Disabled, Show all available quest marks)'),
('Quests.HighLevelHideDiff', 'int', 80, '7', NULL, 'Level difference between player and quest level at which quests are considered high-level and are not shown via exclamation mark (!) at quest givers. #Default: 7  - (Enabled, Hide quests that have 7 levels more than the character) #-1 - (Disabled, Show all available quest marks)'),
('ChatStrictLinkChecking.Severity', 'int', 81, '0', NULL, 'Check chat messages for in-game links to spells, items, quests, etc. #Default: 0 - (Only verify that link format looks valid without checking the text) 1 - (Check if color, entry and name don\'t contradict each other. For this to work correctly, please assure that you have extracted locale DBCs of every language specific client playing on this server)'),
('ChatStrictLinkChecking.Kick', 'int', 82, '0', NULL, 'Defines what should be done if a message containing invalid control characters is received. #Default: 0 - (Silently ignore message) 1 - (Ignore message and kick player)'),
('ChatLevelReq.Channel', 'int', 83, '1', NULL, 'Level requirement for characters to be able to use chats.'),
('ChatLevelReq.Whisper', 'int', 84, '1', NULL, 'Level requirement for characters to be able to use chats.'),
('ChatLevelReq.Emote', 'int', 85, '1', NULL, 'Level requirement for characters to be able to use chats.'),
('ChatLevelReq.Say', 'int', 86, '1', NULL, 'Level requirement for characters to be able to use chats.'),
('ChatLevelReq.Yell', 'int', 87, '1', NULL, 'Level requirement for characters to be able to use chats.'),
('PartyLevelReq', 'int', 88, '1', NULL, 'Minimum level at which players can invite to group, even if they aren\'t on the invitee friends list. (Players who are on that friend list can always invite despite having lower level)'),
('LevelReq.Trade', 'int', 89, '1', NULL, 'Level requirement for characters to be able to initiate a trade.'),
('LevelReq.Ticket', 'int', 90, '1', NULL, 'Level requirement for characters to be able to write tickets.'),
('LevelReq.Auction', 'int', 91, '1', NULL, 'Level requirement for characters to be able to use the auction house.'),
('LevelReq.Mail', 'int', 92, '1', NULL, 'Level requirement for characters to be able to send and receive mails.'),
('Corpse.Decay.NORMAL', 'int', 93, '300', NULL, 'Time (in seconds) until creature corpse will decay if not looted or skinned.'),
('Corpse.Decay.RARE', 'int', 94, '300', NULL, 'Time (in seconds) until creature corpse will decay if not looted or skinned.'),
('Corpse.Decay.ELITE', 'int', 95, '300', NULL, 'Time (in seconds) until creature corpse will decay if not looted or skinned.'),
('Corpse.Decay.RAREELITE', 'int', 96, '300', NULL, 'Time (in seconds) until creature corpse will decay if not looted or skinned.'),
('Corpse.Decay.WORLDBOSS', 'int', 97, '3600', NULL, 'Time (in seconds) until creature corpse will decay if not looted or skinned.'),
('Death.SicknessLevel', 'int', 98, '11', NULL, 'Starting level for resurrection sickness. #Example: 11 - (Level 1-10 characters will not be affected, Level 11-19 characters will be affected for 1 minute, Level 20-MaxPlayerLevel characters will be affected for 10 minutes) #Default: 11 - (Enabled, See Example) #MaxPlayerLevel+1 - (Disabled) # -10              - (Enabled, Level 1+ characters have 10 minute duration)'),
-- ('CONFIG_INSTANT_LOGOUT', 'int', 99, '1', NULL, ''),
('DisableWaterBreath', 'int', 100, '4', NULL, 'Required security level for water breathing. #Default: 4  - (Disabled) #0  - (Enabled, Everyone) #1  - (Enabled, Mods/GMs/Admins) #2  - (Enabled, GMs/Admins) #3  - (Enabled, Admins)'),
('Battleground.InvitationType', 'int', 101, '0', NULL, 'Set Battleground invitation type. #Default: 0 - (Normal, Invite as much players to battlegrounds as queued, Don\'t bother with balance) #1 - (Experimental, Don\'t allow to invite much more players of one faction) #2 - (Experimental, Try to have even teams)'),
('Battleground.PrematureFinishTimer', 'int', 102, '300000', NULL, 'Time (in milliseconds) before battleground will end prematurely if there are not enough players on one team. (Values defined in battleground template) #Default: 300000 - (Enabled, 5 minutes) #0 - (Disabled, Not recommended)'),
('Battleground.PremadeGroupWaitForMatch', 'int', 103, '1800000', NULL, 'Time (in milliseconds) a pre-made group has to wait for matching group of the other faction. #Default: 1800000 - (Enabled, 30 minutes) #0 - (Disabled, Not recommended)'),
('Battleground.ReportAFK', 'int', 104, '3', NULL, 'Number of reports needed to kick someone AFK from Battleground. Range: 1-9 #Default:     3'),
('Arena.MaxRatingDifference', 'int', 105, '150', NULL, 'Maximum rating difference between two teams in rated matches. #Default: 150 - (Enabled) # 0   - (Disabled)'),
('Arena.RatingDiscardTimer', 'int', 106, '600000', NULL, 'Time (in milliseconds) after which rating differences are ignored when setting up matches. # Default:  600000 - (Enabled, 10 minutes)'),
('Arena.PreviousOpponentsDiscardTimer', 'int', 107, '120000', NULL, 'Time (in milliseconds) after which the previous opponents will be ignored. #Default: 120000 - (Enabled, 2 minutes - Blizzlike) #0 - (Disabled)'),
('Arena.RatedUpdateTimer', 'int', 108, '5000', NULL, 'Time (in milliseconds) between checks for match-ups in rated arena. #Default:     5000 - (5 seconds)'),
('Arena.AutoDistributeInterval', 'int', 109, '7', NULL, 'Time (in days) how often arena points should be distributed if automatic distribution is enabled. #Default:  7 - (Weekly)'),
('Arena.ArenaSeason.ID', 'int', 110, '8', NULL, 'Current arena season id shown in clients.'),
('Arena.ArenaStartRating', 'int', 111, '0', NULL, 'Start rating for new arena teams.'),
('Arena.ArenaStartPersonalRating', 'int', 112, '0', NULL, 'Start personal rating when joining a team.'),
('Arena.ArenaStartMatchmakerRating', 'int', 113, '1500', NULL, 'Start matchmaker rating for players.'),
('MaxWhoListReturns', 'int', 114, '49', NULL, 'Set the max number of players returned in the /who list and interface.'),
('HonorPointsAfterDuel', 'int', 115, '0', NULL, 'Amount of honor points the duel winner will get after a duel. #Default:  0  - (Disabled) #1+ - (Enabled)'),
('PvPToken.MapAllowType', 'int', 116, '4', NULL, 'Define where characters can receive tokens. #Default: 4 - (All maps) #3 - (Battlegrounds) #2 - (FFA areas only like Gurubashi arena) # 1 - (Battlegrounds and FFA areas)'),
('PvPToken.ItemID', 'int', 117, '29434', NULL, 'Item characters will receive after defeating another character if PvP Token system is enabled. #Default: 29434 - (Badge of justice)'),
('PvPToken.ItemCount', 'int', 118, '1', NULL, 'Number of tokens a character will receive.'),
('Server.LoginInfo', 'int', 119, '0', NULL, 'Display core version (.server info) on login.'),
-- ('CONFIG_PLAYER_ALLOW_COMMANDS', 'int', 120, '1', NULL, ''),
('MapUpdate.Threads', 'int', 121, '1', NULL, 'Number of threads to update maps.'),
('LogDB.Opt.ClearInterval', 'int', 122, '10', NULL, 'Time (in minutes) for the WUPDATE_CLEANDB timer that clears the `logs` table of old entries. #Default: 20 - (10 minutes) #1+'),
('LogDB.Opt.ClearTime', 'int', 123, '1209600', NULL, 'Time (in seconds) for keeping old `logs` table entries. #Default: 1209600 - (Enabled, 14 days)'),
('ClientCacheVersion', 'int', 124, '0', NULL, 'Client cache version for client cache data reset. Use any value different from DB and not recently been used to trigger client side cache reset. #Default:  0 - (Use DB value from world DB version.cache_id field)'),
('Guild.EventLogRecordsCount', 'int', 125, '100', NULL, 'Number of log entries for guild events that are stored per guild. Old entries will be overwritten if the number of log entries exceed the configured value. High numbers prevent this behavior but may have performance impacts.'),
('Guild.BankEventLogRecordsCount', 'int', 126, '25', NULL, 'Number of log entries for guild bank events that are stored per guild. Old entries will be overwritten if the number of log entries exceed the configured value. High numbers prevent this behavior but may have performance impacts. #Default:  25 - (Minimum)'),
('PlayerSave.Stats.MinLevel', 'int', 127, '0', NULL, 'Minimum level for saving character stats in the database for external usage. #Default: 0  - (Disabled, Do not save character stats) #1+ - (Enabled, Level beyond which character stats are saved)'),
('Battleground.Random.ResetHour', 'int', 128, '6', NULL, 'Hour of the day when the global instance resets occur. #Range: 0-23#Default:     6 - (06:00 AM)'),
('Calendar.DeleteOldEventsHour', 'int', 129, '6', NULL, 'Hour of the day when the daily deletion of old calendar events occurs. #Range: 0-23 #Default: 6 - (06:00 AM)'),
('Guild.ResetHour', 'int', 130, '6', NULL, 'Hour of the day when the daily cap resets occur. #Range: 0-23 #Default: 6 - (06:00 AM)'),
('CharDelete.KeepDays', 'int', 131, '30', NULL, 'Time (in days) before unlinked characters will be removed from the database. #Default: 30 - (Enabled) #0  - (Disabled, Don\'t delete any characters)'),
('CharDelete.Method', 'int', 132, '0', NULL, 'Character deletion behavior. #Default: 0 - (Completely remove character from the database) #1 - (Unlink the character from account and free up the name, Appears as deleted in-game)'),
('CharDelete.MinLevel', 'int', 133, '0', NULL, 'Required level to use the unlinking method if enabled for non-heroic classes. #Default: 0  - (Same method for every level) #1+ - (Only characters with the specified level will use the unlinking method)'),
('CharDelete.DeathKnight.MinLevel', 'int', 134, '0', NULL, 'Required level to use the unlinking method if enabled for death knights. #Default: 0  - (Same method for every level) #1+ - (Only characters with the specified level will use the unlinking method)'),
('AutoBroadcast.Center', 'int', 135, '0', NULL, 'Auto broadcasting display method. #Default: 0 - (Announce) #1 - (Notify) #2 - (Both)'),
('AutoBroadcast.Timer', 'int', 136, '600000', NULL, 'Timer (in milliseconds) for auto broadcasts. #Default: 600000 - (10 minutes)'),
('Command.LookupMaxResults', 'int', 137, '0', NULL, 'Number of results being displayed using a .lookup command. #Default: 0 - (Unlimited)'),
('MaxPingTime', 'int', 138, '30', NULL, 'Time (in minutes) between database pings.'),
('PreserveCustomChannelDuration', 'int', 139, '14', NULL, 'Time (in days) that needs to pass before the customs chat channels get cleaned up from the database. Only channels with ownership handout enabled (default behavior) will be cleaned. #Default: 14 - (Enabled, Clean channels that haven\'t been used for 14 days) #0  - (Disabled, Infinite channel storage)'),
('PreserveCustomChannelInterval', 'int', 140, '5', NULL, 'Interval (in minutes) at which custom channel data is saved to the database #Default: 5 minutes'),
('PersistentCharacterCleanFlags', 'int', 141, '0', NULL, 'Determines the character clean flags that remain set after cleanups. This is a bitmask value, check /doc/CharacterDBCleanup.txt for more information. #Example: 14 - (Cleaning up skills, talents and spells will remain enabled after the next cleanup) #Default: 0  - (All cleanup methods will be disabled after the next cleanup)'),
('DungeonFinder.OptionsMask', 'int', 142, '1', NULL, 'Description: Dungeon and raid finder system. Value is a bitmask consisting of: #LFG_OPTION_ENABLE_DUNGEON_FINDER = 1,     Enable the dungeon finder browser #LFG_OPTION_ENABLE_RAID_BROWSER   = 2, Enable the raid browser'),
('AccountInstancesPerHour', 'int', 143, '5', NULL, 'Controls the max amount of different instances player can enter within hour. #Default: 5'),
('XP.Boost.Daymask', 'int', 144, '65', NULL, 'Enables experience boost during the defined days. This field is a bitmask. #Default: 0 - (Disabled) #1 - (Sunday) #2 - (Monday) #4 - (Tuesday) #8 - (Wednesday) #16 - (Thursday) #32 - (Friday) #64 - (Saturday) #65 - (Weekend only) #127 - (Always active)'),
('Warden.ClientResponseDelay', 'int', 145, '600', NULL, 'Time (in seconds) before client is getting disconnecting for not responding. #Default: 600 - (10 Minutes) #0 - (Disabled, client won\'t be kicked)'),
('Warden.ClientCheckHoldOff', 'int', 146, '30', NULL, 'Time (in seconds) to wait before sending the next check request to the client. A low number increases traffic and load on client and server side. #Default: 30 - (30 Seconds) #0  - (Send check as soon as possible)'),
('Warden.ClientCheckFailAction', 'int', 147, '0', NULL, 'Default action being taken if a client check failed. Actions can be overwritten for each single check via warden_action table in characters database. #Default: 0 - (Disabled, Logging only) #1 - (Kick) #2 - (Ban)'),
('Warden.BanDuration', 'int', 148, '86400', NULL, 'Time (in seconds) an account will be banned if ClientCheckFailAction is set to ban. #Default: 86400 - (24 hours) #0 - (Permanent ban)'),
('Warden.NumInjectionChecks', 'int', 149, '9', NULL, 'Number of Warden checks of the respective category that are sent per cycle.'),
('Warden.NumLuaSandboxChecks', 'int', 150, '1', NULL, 'Number of Warden checks of the respective category that are sent per cycle.'),
('Warden.NumClientModChecks', 'int', 151, '1', NULL, 'Number of Warden checks of the respective category that are sent per cycle.'),
('Wintergrasp.PlayerMax', 'int', 152, '100', NULL, 'Maximum number of players allowed in Wintergrasp.'),
('Wintergrasp.PlayerMin', 'int', 153, '0', NULL, 'Minimum number of players required for Wintergrasp.'),
('Wintergrasp.PlayerMinLvl', 'int', 154, '77', NULL, 'Required character level for the Wintergrasp battle.'),
('Wintergrasp.BattleTimer', 'int', 155, '30', NULL, 'Time (in minutes) for the Wintergrasp battle to last.'),
('Wintergrasp.NoBattleTimer', 'int', 156, '150', NULL, 'Time (in minutes) between Wintergrasp battles.'),
('Wintergrasp.CrashRestartTimer', 'int', 157, '10', NULL, 'Time (in minutes) to delay the restart of Wintergrasp if the world server crashed during a running battle.'),
('PacketSpoof.Policy', 'int', 158, '1', NULL, 'Determines the course of action when packet spoofing is detected. #Default: 1 - (Log + kick) #0 - (Log only \'network\') #2 - (Log + kick + ban)'),
('PacketSpoof.BanMode', 'int', 159, '0', NULL, 'If PacketSpoof.Policy equals 2, this will determine the ban mode. #Note: Banning by character not supported for logical reasons. #Default: 0 - Ban Account #2 - Ban IP'),
('PacketSpoof.BanDuration', 'int', 160, '86400', NULL, 'Duration of the ban in seconds. Only valid if PacketSpoof.Policy is set to 2. #Set to 0 for permanent ban. #Default:  86400 seconds (1 day)'),
('Account.PasswordChangeSecurity', 'int', 161, '0', NULL, 'Controls how secure the password changes are. # Default: 0 - None (Old and new password) #1 - Email (Email confirmation necessary) #2 - RBAC (RBAC enable or disables email confirmation per group)'),
('Battleground.RewardWinnerHonorFirst', 'int', 162, '30', NULL, 'Random Battlegrounds / call to the arms rewards.'),
('Battleground.RewardWinnerArenaFirst', 'int', 163, '25', NULL, 'Random Battlegrounds / call to the arms rewards.'),
('Battleground.RewardWinnerHonorLast', 'int', 164, '15', NULL, 'Random Battlegrounds / call to the arms rewards.'),
('Battleground.RewardWinnerArenaLast', 'int', 165, '0', NULL, 'Random Battlegrounds / call to the arms rewards.'),
('Battleground.RewardLoserHonorFirst', 'int', 166, '5', NULL, 'Random Battlegrounds / call to the arms rewards.'),
('Battleground.RewardLoserHonorLast', 'int', 167, '5', NULL, 'Random Battlegrounds / call to the arms rewards.'),
('BirthdayTime', 'int', 168, '1222964635', NULL, 'Set to date of project\'s birth in UNIX time. By default the date when #TrinityCore was started (Thu Oct 2, 2008) #Default: 1222964635'),
('Creature.PickPocketRefillDelay', 'int', 169, '600', NULL, 'Time in seconds that the server will wait before refilling the pickpocket loot for a creature #Default: 600'),
('Creature.MovingStopTimeForPlayer', 'int', 170, '180000', NULL, 'Time (in milliseconds) during which creature will not move after interaction with player.'),
('AuctionHouseBot.Update.Interval', 'int', 171, '20', NULL, 'Interval in seconds for AHBot to get updated'),
('Guild.CharterCost', 'int', 172, '1000', NULL, 'Amount of money (in Copper) the petitions costs. 1000 - (10 Silver)'),
('ArenaTeam.CharterCost.2v2', 'int', 173, '800000', NULL, 'Amount of money (in Copper) the petitions costs. 800000 - (80 Gold)'),
('ArenaTeam.CharterCost.3v3', 'int', 174, '1200000', NULL, 'Amount of money (in Copper) the petitions costs. 1200000 - (120 Gold)'),
('ArenaTeam.CharterCost.5v5', 'int', 175, '2000000', NULL, 'Amount of money (in Copper) the petitions costs. 2000000 - (200 Gold)'),
('NoGrayAggro.Above', 'int', 176, '0', NULL, 'Gray mobs will not aggro players above/below some levels NoGrayAggro.Above: If player is at this level or above, gray mobs will not attack NoGrayAggro.Below: If player is at this level or below, gray mobs will not attack #Example: You can for example make players free from gray until they reach level 30. #Then gray will start to attack them, until they reach max level (80 for example): #NoGrayAggro.Above = 80 #NoGrayAggro.Below = 29 #Default: 0 - (Blizzlike)'),
('NoGrayAggro.Below', 'int', 177, '0', NULL, 'Gray mobs will not aggro players above/below some levels NoGrayAggro.Above: If player is at this level or above, gray mobs will not attack NoGrayAggro.Below: If player is at this level or below, gray mobs will not attack #Example: You can for example make players free from gray until they reach level 30. #Then gray will start to attack them, until they reach max level (80 for example): #NoGrayAggro.Above = 80 #NoGrayAggro.Below = 29 #Default: 0 - (Blizzlike)'),
('Auction.GetAllScanDelay', 'int', 178, '900', NULL, 'Sets the minimum time in seconds, a single player character can perform a GetAll scan. The value is only held in memory so a server restart will clear it. Setting this to zero, will disable GetAll functions completely. #Default:  900 - (GetAll scan limited to once every 15mins per player character)'),
('Auction.SearchDelay', 'int', 179, '300', NULL, 'Sets the minimum time in milliseconds (seconds x 1000), that the client must wait between auction search operations. This can be increased if somehow Auction House activity is causing too much load. #Default: 300 - (Time delay between auction searches set to 0.3secs)'),
('TalentsInspecting', 'int', 180, '1', NULL, 'Allow/disallow inspecting other characters\' talents. Doesn\'t affect game master accounts. #2 - (Enabled for all characters) #Default: 1 - (Enabled for characters of the same faction) #0 - (Talent inspecting is disabled)'),
('Respawn.MinCheckIntervalMS', 'int', 181, '5000', NULL, 'Minimum time that needs to pass between respawn checks for any given map. #Default: 5000 - 5 seconds'),
('Respawn.DynamicMode', 'int', 182, '0', NULL, 'Select which mode (if any) should be used to adjust respawn of creatures. This will only affect creatures that have dynamic spawn rate scaling enabled in the spawn group table (by default, gathering nodes and quest targets with respawn time <30min #1 - Use number of players in zone #Default: 0 - No dynamic respawn function'),
('Respawn.GuidWarnLevel', 'int', 183, '12000000', NULL, 'The point at which the highest guid for creatures or gameobjects in any map must reach before the warning logic is enabled. A restart will then be queued at the next quiet time The maximum guid per map is 16,777,216. So, it must be less than this value. #Default: 12000000 - 12 million'),
('Respawn.GuidAlertLevel', 'int', 184, '16000000', NULL, 'The point at which the highest guid for creatures or gameobjects in any map must reach before the alert logic is enabled. A restart will then be triggered for 30 min. from that point. The maximum guid per map is 16,777,216. So, it must be less than this value. #Default: 16000000 - 16 million'),
('Respawn.RestartQuietTime', 'int', 185, '3', NULL, 'The hour at which the server will be restarted after the Respawn.GuidWarnLevel threshold has been reached. This can be between 0 and 23. 20 will be 8pm server time #Default: 3 - 3am'),
('Respawn.DynamicMinimumCreature', 'int', 186, '10', NULL, 'The minimum respawn time for a creature under dynamic scaling. #Default: 10 - (10 seconds)'),
('Respawn.DynamicMinimumGameObject', 'int', 187, '10', NULL, 'The minimum respawn time for a GameObject under dynamic scaling.'),
('Respawn.WarningFrequency', 'int', 188, '1800', NULL, 'The frequency (in seconds) that the warning message will be sent to users after a quiet time restart is triggered. The message will repeat each time this many seconds passed until the server is restarted. If set to 0, no warnings will be sent. #Default: 1800 - (30 minutes)'),
('SocketTimeOutTimeActive', 'int', 189, '60', NULL, 'Time (in seconds) after which an idle connection is dropped while logged into the world.'),
('AntiCheat.PendingMoveChangesTimeoutTime', 'int', 190, '0', NULL, 'Time each client has to acknowledge a movement change until they are kicked.');
