DELETE FROM `world_custom_config` WHERE `Type` = 'bool' AND `IDInTypeGroup` between 0 and 50;
INSERT INTO `world_custom_config`(`OptionName`, `Type`, `IDInTypeGroup`, `DefaultValue`, `CustomValue`, `Description`) VALUES 
-- AT configs
('AntiCheats.FakeJumper.Enabled', 'bool', 0, '1', NULL, 'Enable AntiCheat.FakeJumper : when player sent a move opcode (with new Z higher) when has flag falling (client can\'t sent any new packets when falling) It\'s normal for Gagarin hacks and with Air Mode + \"space\" click = \"falling\" mode (player can\'t change orientation of flying, but it move up)'),
('AntiCheats.FakeFlyingmode.Enabled', 'bool', 1, '1', NULL, 'Enable AntiCheat.FakeFlyingmode : when player sent a move opcode with added fly flag but on server this flag doesn\'t restricted for player. It\'s normal for Hitchhiker\'s Hack with Air Mode'),
('AntiCheats.DoubleJump.Enabled', 'bool', 2, '1', NULL, 'Enable AntiCheat.DoubleJump Kick when player sent opcode jump when has flag falling (client can\'t do this)'),
('AntiCheats.FlyHack.Enabled', 'bool', 3, '1', NULL, 'Enable AntiCheat.FlyHack'),
('AntiCheats.SpeedHack.Enabled', 'bool', 4, '1', NULL, 'Enable AntiCheat.SpeedHack'),
('AntiCheats.IgnoreControlMovement.Enabled', 'bool', 5, '1', NULL, 'Enable AntiCheat.IgnoreControlMovement : when player in root state - client can\'t send a new movement packets'),
('AntiCheats.SpeedHack.Kick.Enabled', 'bool', 6, '1', NULL, 'Enable AntiCheat.SpeedHack Kick when detected'),
('AntiCheats.FlyHack.Kick.Enabled', 'bool', 7, '1', NULL, 'Enable AntiCheat.FlyHack Kick when detected'),
('AntiCheats.FakeJumper.Kick.Enabled', 'bool', 8, '1', NULL, 'Enable AntiCheats.FakeJumper Kick when detected'),
('AntiCheats.FakeFlyingmode.Kick.Enabled', 'bool', 9, '1', NULL, 'Enable AntiCheats.FakeFlyingmode Kick when detected'),
('AntiCheats.NoFallingDmg.Kick.Enabled', 'bool', 10, '1', NULL, 'Enable AntiCheats.NoFallingDmg Kick when detected'),
('Config.Vip.Debuff.Command', 'bool', 11, '0', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Bank.Command', 'bool', 12, '0', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Mail.Command', 'bool', 13, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Repair.Command', 'bool', 14, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Reset.Talents.Command', 'bool', 15, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Taxi.Command', 'bool', 16, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Home.Command', 'bool', 17, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Change.Race.Command', 'bool', 18, '0', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Customize.Command', 'bool', 19, '0', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Capital.Command', 'bool', 20, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Appear.Command', 'bool', 21, '1', NULL, 'Enable/Disable custom vip command'),
('Config.Vip.Item.Helper', 'bool', 22, '1', NULL, 'Enable/Disable Item helper in game'),
('CheckM2ObjectLoS', 'bool', 23, '1', NULL, 'Include M2 objects (trees etc.) in line of sight checks.'),
('CrossfactionBG.enable', 'bool', 24, '0', NULL, 'Mixed battleground'),
('Chat.StrictMessages.Enabled', 'bool', 25, '1', NULL, 'Limit player message to language specific symbol set. Prevents character messages and ignore request if not allowed symbols are used'),
('DalaranGEvent.InstantReviveAndReturn.Enable', 'bool', 26, '0', NULL, NULL),
('DalaranGEvent.Squad.Enable', 'bool', 27, '0', NULL, NULL),
('GSystem.LootBroadcast.Enabled', 'bool', 28, '1', NULL, 'Guild announce when member take a loot with Quality >= EPIC'),
('GSystem.GuildLevel.Enabled', 'bool', 29, '1', NULL, 'Make a possible guild level system'),
('GSystem.GuildWars.Enabled', 'bool', 30, '1', NULL, 'Give possibility to make Guild Wars between guilds'),
('GSystem.GuildWars.BetweenBothFaction.Enabled', 'bool', 31, '1', NULL, 'Give possibility to make Guild Wars between guilds from both faction (Alliance and Horde)'),
('GSystem.GuildLevel.ShowLevelGuild.WhoList.Enabled', 'bool', 32, '1', NULL, 'Make a visible guild level in whoList'),
('GSystem.GuildLevel.ShowLevelGuild.QueryList.Enabled', 'bool', 33, '1', NULL, 'Make a visible guild level in query opcode (visible name/guild above character)'),
('GSystem.GuildWars.ShowLevelGuild.EnemyList.Enabled', 'bool', 34, '1', NULL, 'Show Enemy Guild Level in GW enemy list'),
('LFG.Channel.Everywhere', 'bool', 35, '1', NULL, 'Allow access at LookupForGroup channel to characters without condition of LFG state.'),
('LFG.CrossFaction.Groups', 'bool', 36, '0', NULL, 'Enable/Disable custom system for crossfaction DungeonFinder groups'),
('Mail.Antispam.Enabled', 'bool', 37, '1', NULL, 'When player will receive this limit, he just can\'t bid or bidout from auction. Calendar will not sent mail him.  And another player can\'t sent mail to him, just will see error overloaded mailbox of receiver.'),
('Mail.External.Enabled', 'bool', 38, '1', NULL, 'MailMgr will look in External table for receive a new mails from site ot something else'),
('Player.AutoLearnSpells.Enabled', 'bool', 39, '0', NULL, 'Player will auto learn spell when reach a level (table player_spells_for_level)'),
('Player.UniversalLanguage.Enabled', 'bool', 40, '0', NULL, 'Player talking on Universal language (need for different chatMgr and 1 language for SAY and etc)'),
('Player.PVPBonusCapReward.Enabled', 'bool', 41, '1', NULL, 'Enable/Disable custom PVP bonus cap reward for arena. It give bonus weekly reward when cap is complited (1500/1500 by default)'),
('Player.DuelPhase.Enabled', 'bool', 42, '1', NULL, 'Make a special phase for duel members, they will see only oponent, and can\'t see others units'),
('Player.BAGScript.Enabled', 'bool', 43, '0', NULL, 'Created character will receive a bags bonus'),
('Player.StartPack.Enabled', 'bool', 44, '0', NULL, 'Give a possibility to receive start-pack items from item helper'),
('Player.FLABScript.Enabled', 'bool', 45, '1', NULL, 'First character on account will receive a money bonus'),
('RaidInfo.Enabled', 'bool', 46, '0', NULL, 'Enable/Disable custom raid info system for world announce of killed bosses'),
('OSXPlayers.Enabled', 'bool', 47, '1', NULL, 'We can block connect for players from OSX OS system'),
('VAS.Unit.Enabled', 'bool', 48, '0', NULL, 'VAS Auto Balance system'),
('vmap.enableLOS', 'bool', 49, '1', NULL, 'VMmap support for line of sight and height calculation.'),
('vmap.enableHeight', 'bool', 50, '1', NULL, 'VMmap support for line of sight and height calculation.');