INSERT INTO `trinity_string`(`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES 
(12000, 'transX: {} transY: {} transZ: {} transOrient: {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12001, 'The character has VIP privileges: {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Игрок имеет VIP привилегии: {}'),
(12002, '│ CanFly ?: {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(12003, 'You have sent too many mails than available {} in a short time interval.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
-- Special event
(12004, '{}: {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12005, '{}: has been started', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12006, '{}: has been ended', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
-- Dalaran Crater Event
(12010, '|cffe6cc80Dalaran Crater PVP |cFFF00000(Battle Royale) |cffe6cc80Event will start in |cff00ff0030|cffe6cc80seconds. |cff00ff00{} |cffe6cc80Players will fight!. Prepare to FIGHT!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Кратер Даларана PVP |cFFF00000(Королевская битва) |cffe6cc80Событие будет запущено через |cff00ff0030|cffe6cc80секунд. |cff00ff00{} |cffe6cc80Игроков примут участие в битве! Готовьтесь к БИТВЕ!'),
(12011, '|cffe6cc80Dalaran Crater PVP |cFFF00000(Battle Royale) |cffe6cc80Event has been Started!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Кратер Даларана PVP |cFFF00000(Королевская битва) |cffe6cc80Событие было запущено!'),
(12012, '|cffe6cc80Dalaran Crater PVP |cFFF00000(Battle Royale) |cffe6cc80Event will ended in 1 minute. |cff00ff00{} |cffe6cc80Players still alive', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Кратер Даларана PVP |cFFF00000(Королевская битва) |cffe6cc80Событие завершится через 1 минуту! |cff00ff00{} |cffe6cc80Игроков ещё живы!'),
(12013, '|cffe6cc80Dalaran Crater PVP |cFFF00000(Battle Royale) |cffe6cc80Event has been Stoped for time out duration!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Кратер Даларана PVP |cFFF00000(Королевская битва) |cffe6cc80Событие завершилось в связи с истечением срока!'),
(12014, '|cffe6cc80Dalaran Crater PVP |cFFF00000(Battle Royale) |cffe6cc80Event has been Stoped! Winner of this match |cFFF00000{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Кратер Даларана PVP |cFFF00000(Королевская битва) |cffe6cc80Событие завершилось. Победителем признан игрок |cFFF00000{}'),
(12015, '|cffe6cc80All members of |cFFF00000Dalaran Crater Event |cffe6cc80will be revived and teleported in previous location in 45 seconds', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Все участники |cFFF00000Ивента Кратер Даларана|cffe6cc80будут воскрешены и телепортированы обратно через 45 секунд'),
(12016, '|cffe6cc80Player |cff00ff00{} |cffe6cc80has leave the Battle. Alive players : |cff00ff00{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Игрок |cff00ff00{} |cffe6cc80покинул Битву. Живых игроков осталось : |cff00ff00{}'),
(12017, '|cffe6cc80You can not take a participation in |cFFF00000Dalaran Event |cffe6cc80(you are died). Try to enjoy in next time', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Вы не смогли принять участие в |cFFF00000Событие Кратер Даларана |cffe6cc80(так как были мертвы). Попробуйте принять участие в следующий раз'),
(12018, '|cffe6cc80Dalaran Crater PVP |cFFF00000(Battle Royale) |cffe6cc80Event can not be started. Not enough players. Try to enjoy in next time', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Кратер Даларана PVP |cFFF00000(Королевская битва) |cffe6cc80Событие не было запущено. Недостаточно игроков. Попробуйте принять участие в следующий раз'),
(12019, '|cffe6cc80Dalaran Crater PVP |cFFF00000(Battle Royale) |cffe6cc80Event will be started in 1 minute', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Кратер Даларана PVP |cFFF00000(Королевская битва) |cffe6cc80Событие будет стартовать через 1 минуту'),
(12020, '|cffe6cc80Dalaran Crater PVP |cFFF00000(Battle Royale) |cffe6cc80Event will be started in 30 seconds', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Кратер Даларана PVP |cFFF00000(Королевская битва) |cffe6cc80Событие будет стартовать через 30 секунд'),
(12021, '|cffe6cc80You have successfully registered in Dalaran Crater PVP |cFFF00000(Battle Royale) |cffe6cc80Event, |cff00ff00{} |cffe6cc80Players registered', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Вы успешно зарегистрировались на участие в Кратер Даларана PVP |cFFF00000(Королевская битва) |cffe6cc80Событии, |cff00ff00{} |cffe6cc80Игроков зарегистрировано'),
(12022, '|cffe6cc80You have successfully canceled registration in Dalaran Crater PVP |cFFF00000(Battle Royale) |cffe6cc80Event', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Вы успешно сняли заявку на участие в Кратер Даларана PVP |cFFF00000(Королевская битва) |cffe6cc80Событии'),
(12023, 'Register in Dalaran Crater Event PVP(Battle Royale) Queue', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Зарегистрироваться на участие в Кратер Даларана PVP'),
(12024, 'Leave Dalaran Crater Event PVP (Battle Royale) - Queue', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Покинуть Кратер Даларана PVP'),
(12025, 'Dalaran Crater Event PVP (Battle Royale) - will Available', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Событие Кратер даларана доступно'),
-- GSystem
(12030, '|cffe6cc80Not enough guild members for start Guild War', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Недостаточно игроков в гильдии для начала Войны Гильдий'),
(12031, '|cffe6cc80Not enough guild members in target guild for starting Guild War', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80В противоположной гильдии недостаточно игроков для начала Войны Гильдий'),
(12032, '|cffe6cc80You can start new Guild War only', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Вы сможете начать новую Войну Гильдий лишь'),
(12033, '|cffe6cc80Congratulations! The guild has reached a |cff00ff00{} |cffe6cc80level. The last experience has gained by {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Поздравляем! Гильдия достигла |cff00ff00{} |cffe6cc80 уровня. Последние очки опыта были добыты {}'),
(12034, '|cffe6cc80Congratulations! The guild has reached a |cff00ff00{} |cffe6cc80 level', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Поздравляем! Гильдия достигла |cff00ff00{} |cffe6cc80 уровня.'),
(12035, '|cffe6cc80The Guild has received a |cff00ff00{} |cffe6cc80 experience. Points has gained by {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Гильдия заработала |cff00ff00{} |cffe6cc80 очков опыта, добытые благодаря {}'),
(12036, '|cffe6cc80The Guild has received a |cff00ff00{} |cffe6cc80 experience.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Гильдия заработала |cff00ff00{} |cffe6cc80 очков опыта.'),
(12037, '|cffe6cc80The Guild has entered in Guild War with |cFFF00000{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Гильдия вступила в Войну с |cFFF00000{}'),
(12038, '|cffe6cc80The Guild has ended Guild War with |c00FF23CC{}|cffe6cc80.\n|cffe6cc80The Winner of this Guild War : |cff00ff00{}|cffe6cc80. Guild Rating has been changed on \"|cff00ff00{}|cffe6cc80\".', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Гильдия окончила Войну Гильдий с |c00FF23CC{}|cffe6cc80.\n|cffe6cc80Победителем Войны признана : |cff00ff00{}|cffe6cc80. Рейтинг гильдии был изменен на \"|cff00ff00{}|cffe6cc80\".'),
(12039, '|cffe6cc80The Guild has |cff00ff00{}|cffe6cc80 level, and |cff00ff00{} / 1500|cffe6cc80 experience for next level.\n|cffe6cc80Guild Rating Points |cff00ff00{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Гильдия имеет |cff00ff00{}|cffe6cc80 уровень и |cff00ff00{} / 1500|cffe6cc80 очков опыта до следующего уровня.\n|cffe6cc80Гильдейские очки рейтинга |cff00ff00{}'),
(12040, '|cFFF00000The Guild was fined by |c00FF23CC{} |cffe6cc80on |cff00ff00{} |cffe6cc80levels. Now Guild have |cff00ff00{} |cffe6cc80level', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cFFF00000Гильдия была оштрафована |c00FF23CC{} |cffe6cc80на |cff00ff00{} |cFFF00000уровней, и сейчас уровень гильдии равен |cff00ff00{}'),
(12041, ' level', NULL, NULL, NULL, NULL, NULL, NULL, NULL, ' уровня'),
(12042, 'The Guild {} has received {} additional levels, and now has {} level', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Гильдия {} получила {} дополнительных уровней, и сейчас имеет {} уровень'),
(12043, 'The Guild {} has received {} additional experience, and now has {} Exp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Гильдия {} получила {} дополнительных очков опыта, и сейчас имеет {} очков опыта'),
(12044, 'The Guild {} has lost {} levels, and now has {} level', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Гильдия {} была понижена на {} уровней, и теперь имеет {} уровень'),
(12045, '|cffe6cc80The Guild has no enemies at the moment', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80У Гильдии нет врагов на данный момент'),
(12046, '|cffe6cc80The Guild is currently hostile to : \n|cFFF00000{}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80У Гильдия в настоящий момент враждует с : \n|cFFF00000{}'),
(12047, '|cffe6cc80The Guild |cff00ff00{} |cffe6cc80is not enemy of your guild', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Гильдия |cff00ff00{} |cffe6cc80не является врагом для вашей гильдии'),
(12048, '|cffe6cc80The Guild |cff00ff00{} |cffe6cc80already is enemy of your guild', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Гильдия |cff00ff00{} |cffe6cc80уже является врагом вашей гильдии на данный момент'),
(12049, 'You declared a Guild War against {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вы объявилу Войну Гильдии {}'),
(12050, 'You admitted defeat in this war against the guild {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вы признали свое поражение в войне против гильдии {}'),
(12051, '|caa88aa88To use this feature, your guild must reach a |cff00ff00{} |caa88aa88level', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|caa88aa88Для пользования данной функцией, ваша гильдия должна достичь |cff00ff00{} |caa88aa88уровня'),
(12052, 'You have not rights to declare Guild War.\nYou should to have guild rank with rights to |cff00ff00modify guild information', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'У вас недостаточно прав гильдии для объявления войны другой гильдии.\nНеобходимо иметь ранг с правами |cff00ff00изменения гильдейской информации'),
(12053, '|cffe6cc80You can declare War only inside one faction (Alliance or Horde)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80Вы можете объявить Войну только гильдии из вашей фракции (Альянс или Орда)'),
(12054, '|TInterface\\icons\\spell_shadow_darksummoning:25:25:-15:0|t Guild Menu|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\spell_shadow_darksummoning:25:25:-15:0|t Гильдейское меню|r'),
(12055, '|TInterface\\icons\\spell_shadow_shadesofdarkness:25:25:-15:0|t Guild Info|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\spell_shadow_shadesofdarkness:25:25:-15:0|t Гильдейское инфо|r'),
(12056, '|TInterface\\icons\\spell_shadow_deathpact:25:25:-15:0|t Guild War Info|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\spell_shadow_deathpact:25:25:-15:0|t Гильдейские Войны, инфо|r'),
(12057, '|TInterface\\icons\\Achievement_Arena_3v3_4:25:25:-15:0|t Declare The War with guild:|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Achievement_Arena_3v3_4:25:25:-15:0|t Объявить Гильдейскую Войну с гильдией:|r'),
(12058, '|TInterface\\icons\\Achievement_BG_3flagcap_nodeaths:25:25:-15:0|t Admit defeat with guild:|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Achievement_BG_3flagcap_nodeaths:25:25:-15:0|t Признать поражение в Войне с гильдией:|r'),
(12059, 'Are you sure you want to Declare The War?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вы уверены, что готовы объявить Войну?'),
(12060, 'Are you sure you want to Admit defeat?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вы уверены, что готовы признать поражение?'),
-- missed LANG_GSYSTEM_ANNOUNCE_RATING_UP_BY
-- missed LANG_GSYSTEM_ANNOUNCE_RATING_UP
(12063, 'Guild Level System disabled', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Уровни гильдий отключены'),
(12064, 'Guild Wars disabled', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Войны гильдий отключены.'),
-- Guild loot
(12100, 'has received', '받은', 'reçu', 'erhalten', '有一個', 'มี', 'recibido', 'recibido', 'Получил'),
(12101, 'has received', '받은', 'reçu', 'erhalten', '我收到', 'ผมได้รับ', 'recibido', 'recibido', 'Получила'),
-- FLAB
(12102, '|cffe6cc80[{}]: We glad to see your first character here, and present you a little bonus :|r {:01}|TInterface\\MoneyFrame\\UI-GoldIcon:0:0:2:0|t {:02}|TInterface\\MoneyFrame\\UI-SilverIcon:0:0:2:0|t {:02}|TInterface\\MoneyFrame\\UI-CopperIcon:0:0:2:0|t', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cffe6cc80[{}]: Мы рады видеть вас и вашего первого персонажа, и дарим вам небольшой презент :|r {:01}|TInterface\\MoneyFrame\\UI-GoldIcon:0:0:2:0|t {:02}|TInterface\\MoneyFrame\\UI-SilverIcon:0:0:2:0|t {:02}|TInterface\\MoneyFrame\\UI-CopperIcon:0:0:2:0|t'),
-- Raid info
(12103, '|cffff0000[RAID INFO]|r |cffe6cc80{} {} {} defeated by the {} with leader:|r |cFFDCDCDC{}|r {}|cffe6cc80. Players ({} / {}) is alive|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12104, '|cffff0000Members:|r |cffe6cc80Tanks -|r |cFF7CFC00{}|r|cffe6cc80, Healers -|r |cFF7CFC00{}|r|cffe6cc80, Damagers -|r |cFF7CFC00{}|r |cffe6cc80 (Avg GS: {})|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12105, '|cffff0000Status:|r |cffe6cc80({} / {}) boss completed|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12106, '|cffff0000Boss|r |cffe6cc80 has been defeated for {}|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
-- Anticheat
(12120, 'AntiCheat: SpeedHack Detected for {}, normal distance for this time and speed = {}, distance from packet = {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12121, 'AntiCheat: FlyHack Detected for {} , player can not fly', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12122, 'AntiCheat: FlyHack Detected for {}, player has Swimming flag, but not in water', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12123, 'AntiCheat: FlyHack Detected for {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12124, 'AntiCheat: DoubleJump Detected for {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12125, 'AntiCheat: Fake Jumper Detected for {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12126, 'AntiCheat: FakeFlying mode Detected for {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12127, 'AntiCheat: Wallclimb Detected for Account id : {}, Player {}, diffZ = {}, distance = {}, angle = {}, Map = {}, mapId = {}, X = {}, Y = {}, Z = {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12128, 'AntiCheat: Ignore control Hack Detected for Account : {}, Player : {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(12129, 'AntiCheat: NoFallingDamage Hack Detected for Account : {}, Player : {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

-- ArenaSpectator
(12150, '2vs2 (Current games: ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2vs2 (Текущие игры: '),
(12151, '3vs3 (Current games: ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3vs3 (Текущие игры: '),
(12152, '5vs5 (Current games: ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '5vs5 (Текущие игры: '),
(12153, 'ERROR: Target name is wrong, please check if he`s online.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ОШИбКА: Неверное имя цели, пожалуйста, проверьте, если он онлайн.'),
(12154, 'ERROR: You are Frozen.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ОШИбКА: Вы заморожены.'),
(12155, 'ERROR: Wait for arena start.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ОШИбКА: Ожидайте начала арены.'),
(12156, 'ERROR: You can`t spectating non-player units.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ОШИбКА: Вы не можете наблюдать за неигровыми юнитами.'),
(12157, 'ERROR: You can`t spectating yourself.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ОШИбКА: Вы не можете наблюдать за собой.'),
(12158, 'ERROR: Please dismiss your pet before spectating.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ОШИбКА: Пожалуйста, уберите вашего питомца перед наблюдением.'),
(12159, 'ERROR: Player is not in arena.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ОШИбКА: Игрок не на арене.'),
(12160, 'ERROR: You can`t spectating spectators.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ОШИбКА: Вы не можете наблюдать за зрителями.'),
(12161, 'ERROR: You can`t spectating when you are on mount.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ОШИбКА: Вы не можете наблюдать, когда находитесь на верховом животном.'),
(12162, 'ERROR: Please leave battleground/arena Queue before spectating.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ОШИбКА: Пожалуйста, покиньте очередь на поле битвы/арену перед наблюдением.'),
(12163, 'Update', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Обновить'),
(12164, 'Return main menu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вернутся в главное меню'),
(12165, 'ERROR: You are not spectator.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ОШИБКА: Вы не зритель.'),
(12166, 'ERROR: Can`t do that. Your target is spectator.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ОШИБКА: Не могу этого сделать. Ваша цель - зритель.'),
(12167, 'ERROR: Can`t do that. Different arenas?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ОШИБКА: Не могу этого сделать. Разные арены?'),
(12168, 'ERROR: Can`t target invisible players.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ОШИБКА: Не может нацеливаться на невидимых игроков.'),
(12169, 'ERROR: Can`t find player.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ОШИБКА: Не могу найти игрока.'),

-- Vip Commands
(12170, 'You are not vip.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Доступно только VIP игрокам.'),
(12171, 'Сommand disable', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Команда отключена.'),
(12172, 'error', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Произошла ошибка.'),
(12173, 'You can not use this command on Battleground or the arena!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вы не можете использовать данную команду на поле боя или на арене!'),
(12174, 'You can not use this command in stealth mode!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вы не можете использовать данную команду в режиме незаметности!'),
(12175, 'You are dead and you can not use this command!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вы мертвы и не можете использовать данную команду!'),
(12176, 'Race Change will be requested at next login.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Смена расы будет предложена при следующем входе в игровой мир!'),
(12177, 'Character customize will be requested at next login.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Смена внешности персонажа будет предложена при следующем входе в игровой мир!'),
(12178, 'You must be in the group', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вы должны находится в группе!'),
(12179, 'Your target player has not vip privileges!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Указанный игрок не имеет ВИП привилегий!'),
(12180, 'The remaining VIP time will expire in: {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Оставшееся VIP время истечет через: {}'),
(12181, 'The remaining VIP time is less than 5 minutes!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Оставшееся время VIP привилегий составляет менее 5 минут!'),
(12182, 'Your VIP time has been expired!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Время VIP привилегий истекло!'),
(12183, 'The remaining VIP time of this target will expire in: {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Оставшееся VIP время указанного игрока истечет через: {}'),

-- Custom Item
(12200, '|cff00ffffYou already have this item!|r', NULL, '|cff00ffffVous avez déjà cet objet !|r', NULL, NULL, NULL, NULL, NULL, '|cff00ffffУ вас уже имеется данная вещь!|r'),
(12201, '|cff00ff00Payment complete. You need to do log-out by character and set a new name for character. Do not forget to clear folder Cache after rename!|r', NULL, '|cff00ff00Payment validé. Vous devez vous déconnecter de votre personnage et le renommer. N\'oubliez pas d\'effacer le dossier Cache après l\'avoir renommé !|r', NULL, NULL, NULL, NULL, NULL, '|cff00ff00Оплата успешно произведена. Сделайте логаут и введите новое имя своего персонажа.Не забудьте после смены имени, выйти из игры и удалить из клиента папку Cache!|r'),
(12202, '|cff00ff00Payment complete. You need to do log-out by character and set customize for character.Do not forget to clear folder Cache after rename!|r', NULL, '|cff00ff00Payment validé. Vous devez vous déconnecter de votre personnage et le personnaliser. N\'oubliez pas d\'effacer le dossier Cache après l\'avoir personnalisé !|r', NULL, NULL, NULL, NULL, NULL, '|cff00ff00Оплата успешно произведена. Сделайте логаут и измените внешность своего персонажа.Не забудьте после смены внешности, выйти из игры и удалить из клиента папку Cache!|r'),
(12203, '|cff00ff00Payment complete. You need to do log-out by character and change faction for character.Do not forget to clear folder Cache after rename!|r', NULL, '|cff00ff00Payment validé. Vous devez vous déconnecter de votre personnage et changer de faction. N\'oubliez pas d\'effacer le dossier Cache après l\'avoir changé de faction !|r', NULL, NULL, NULL, NULL, NULL, '|cff00ff00Оплата успешно произведена. Сделайте логаут и измените фракцию своего персонажа.Не забудьте после смены фракции, выйти из игры и удалить из клиента папку Cache!|r'),
(12204, '|cff00ff00Payment complete. You need to do log-out by character and change race for character.Do not forget to clear folder Cache after change race!|r', NULL, '|cff00ff00Payment validé. Vous devez vous déconnecter de votre personnage et changer de race. N\'oubliez pas d\'effacer le dossier Cache après avoir changé de race !|r', NULL, NULL, NULL, NULL, NULL, '|cff00ff00Оплата успешно произведена. Сделайте логаут и измените расу своего персонажа.Не забудьте после смены расы, выйти из игры и удалить из клиента папку Cache!|r'),
(12205, '|cffff0000You have not enough A.P. for payment!|r', NULL, '|cffff0000Vous n\'avez pas assez d\'A.P pour le payement !|r', NULL, NULL, NULL, NULL, NULL, '|cffff0000У вас недостаточно A.P. для совершения покупки!|r'),
(12206, '|cff0000ffAll your spell cooldowns has been reset!|r', NULL, '|cff0000ff Les temps de recharge de vos sorts ont été réinitialisés !|r', NULL, NULL, NULL, NULL, NULL, '|cff0000ffВремя перезарядки всех заклинаний и способностей сброшено!|r'),
(12207, '|cff00ffffYou can not use this function so often!|r', NULL, '|cff00ffffVous ne pouvez pas utiliser cette fonction aussi souvent !|r', NULL, NULL, NULL, NULL, NULL, '|cff00ffffВы не можете использовать функцию так часто!|r'),
(12208, '|cff0000ffCooldown of quests has been reset!|r', NULL, '|cff0000ffQuêtes journalières réinitialisé !|r', NULL, NULL, NULL, NULL, NULL, '|cff0000ffКД заданий успешно сброшено!|r'),
(12209, '|cff0000ffRaid dungeon binds and cooldowns has been reset!|r', NULL, '|cff0000ffRaids et donjons journaliers réinitialisés !|r', NULL, NULL, NULL, NULL, NULL, '|cff0000ffРейдовые подземелья успешно обновлены! КД сброшено!|r'),
(12210, '|TInterface\\icons\\Inv_trinket_honorhold:25:25:-15:0|tAccount coins: ', NULL, '|TInterface\\icons\\Inv_misc_token_thrallmar:25:25:-15:0|tJetons du compte: ', NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Inv_misc_token_thrallmar:25:25:-15:0|tБонусов на аккаунте : '),
(12211, '|TInterface/ICONS/Spell_Arcane_TeleportStormWind:25:25:-15:0|tStormwind', NULL, '|TInterface/ICONS/Spell_Arcane_TeleportStormWind:25:25:-15:0|tHurlevent', NULL, NULL, NULL, NULL, NULL, '|TInterface/ICONS/Spell_Arcane_TeleportStormWind:25:25:-15:0|tШтормград'),
(12212, '|TInterface/ICONS/Spell_Arcane_TeleportOrgrimmar:25:25:-15:0|tOrgrimmar', NULL, '|TInterface/ICONS/Spell_Arcane_TeleportOrgrimmar:25:25:-15:0|tOrgrimmar', NULL, NULL, NULL, NULL, NULL, '|TInterface/ICONS/Spell_Arcane_TeleportOrgrimmar:25:25:-15:0|tОргриммар'),
(12213, 'Are you sure you want to travel in Stormwind?', NULL, 'Êtes-vous sûr de vouloir aller à Hurlevent ?', NULL, NULL, NULL, NULL, NULL, 'Вы уверены, что вы хотите попасть в Штормград?'),
(12214, 'Are you sure you want to travel in Orgrimmar?', NULL, 'Êtes-vous sûr de vouloir aller à Orgrimmar ?', NULL, NULL, NULL, NULL, NULL, 'Вы уверены, что вы хотите попасть в Orgrimmar?'),
(12215, '|TInterface\\icons\\Inv_inscription_pigment_bug07:25:25:-15:0|tVIP Account menu', NULL, '|TInterface\\icons\\Inv_inscription_pigment_bug07:25:25:-15:0|tMenu du compte VIP', NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Inv_inscription_pigment_bug07:25:25:-15:0|tУправление Вип Аккаунтом'),
(12216, '|TInterface\\icons\\Inv_inscription_weaponscroll01:25:25:-15:0|t|cffD80000Server information|r', NULL, '|TInterface\\icons\\Inv_inscription_weaponscroll01:25:25:-15:0|t|cffD80000Informations sur le serveur|r', NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Inv_inscription_weaponscroll01:25:25:-15:0|t|cffD80000Информация о сервере|r'),
(12217, '|TInterface\\icons\\Inv_inscription_pigment_bug07:25:25:-15:0|tAccount: [|cffE80000buy VIP time|r]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Inv_inscription_pigment_bug07:25:25:-15:0|tАккаунт: [|cffE80000купить VIP время|r]'),
(12218, 'VIP account: [|cffE80000increase VIP time|r]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'VIP Аккаунт: [|cffE80000Увеличить время действий привилегий|r]'),
(12219, '|TInterface\\icons\\Spell_chargenegative:25:25:-15:0|tClose', NULL, '|TInterface\\icons\\Spell_chargenegative:25:25:-15:0|tFermer', NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Spell_chargenegative:25:25:-15:0|tЗакрыть'),
(12220, '|cff006699You have successfully upgraded your level!|r', NULL, '|cff006699Vous avez amélioré votre niveau avec succès|r', NULL, NULL, NULL, NULL, NULL, '|cff006699Вы успешно повысили свой уровень!|r'),
(12221, '|TInterface\\icons\\Inv_misc_note_02:25:25:-15:0|tList of available commands', NULL, '|TInterface\\icons\\Inv_misc_note_02:25:25:-15:0|tListe des commandes disponibles', NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Inv_misc_note_02:25:25:-15:0|tСписок доступных комманд'),
(12222, '|TInterface\\icons\\Inv_misc_tournaments_banner_scourge:25:25:-15:0|tCharacter management', NULL, '|TInterface\\icons\\Inv_misc_tournaments_banner_scourge:25:25:-15:0|tGérer le personnage', NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Inv_misc_tournaments_banner_scourge:25:25:-15:0|tУправление Персонажем'),
(12223, '|TInterface/ICONS/spell_holy_rapture:25:25:-15:0|tChanging the character', NULL, '|TInterface/ICONS/spell_holy_rapture:25:25:-15:0|tChanger le personnage', NULL, NULL, NULL, NULL, NULL, '|TInterface/ICONS/spell_holy_rapture:25:25:-15:0|tИзменение персонажа'),
(12224, '|TInterface\\icons\\achievement_level_80:25:25:-15:0|tClass skills', NULL, '|TInterface\\icons\\achievement_level_80:25:25:-15:0|tCompétences de classe', NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\achievement_level_80:25:25:-15:0|tКлассовые навыки'),
(12225, '|TInterface\\icons\\Inv_throwingknife_02:25:25:-15:0|tRepair all equipment', NULL, '|TInterface\\icons\\Inv_throwingknife_02:25:25:-15:0|tRéparer tous les équipements', NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Inv_throwingknife_02:25:25:-15:0|tПочинить всю экипировку'),
(12226, '|TInterface/ICONS/ability_druid_cower:25:25:-15:0|tRemove Deserter', NULL, '|TInterface/ICONS/ability_druid_cower:25:25:-15:0|tSupprimer le débuff Déserteur', NULL, NULL, NULL, NULL, NULL, '|TInterface/ICONS/ability_druid_cower:25:25:-15:0|tСнять Дезертира'),
(12227, '|TInterface\\icons\\spell_shadow_deathscream:25:25:-15:0|tRemove Weakness', NULL, '|TInterface\\icons\\spell_shadow_deathscream:25:25:-15:0|tSupprimer le débuff Faiblesse', NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\spell_shadow_deathscream:25:25:-15:0|tСнять Слабость'),
(12228, '|TInterface\\icons\\Spell_holy_wordfortitude:25:25:-15:0|tGet the buffs', NULL, '|TInterface\\icons\\Spell_holy_wordfortitude:25:25:-15:0|tObtenez les buffs', NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Spell_holy_wordfortitude:25:25:-15:0|tПолучить баффы'),
(12229, '|TInterface/ICONS/spell_holy_borrowedtime:25:25:-15:0|tRemove spell cooldowns', NULL, '|TInterface/ICONS/spell_holy_borrowedtime:25:25:-15:0|tSupprimer les temps de recharge des sorts', NULL, NULL, NULL, NULL, NULL, '|TInterface/ICONS/spell_holy_borrowedtime:25:25:-15:0|tСбросить КД на способности'),
(12230, '|TInterface\\icons\\Ability_DualWield:25:25:-15:0|tDual specialization', NULL, '|TInterface\\icons\\Ability_DualWield:25:25:-15:0|tDouble spécialisation', NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Ability_DualWield:25:25:-15:0|tДвойная специализация'),
(12231, '|TInterface\\icons\\ability_marksmanship:25:25:-15:0|tReset talents', NULL, '|TInterface\\icons\\ability_marksmanship:25:25:-15:0|tRéinitialiser vos talents', NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\ability_marksmanship:25:25:-15:0|tСброс талантов'),
(12232, 'Are you sure you want to reset your talents?', NULL, 'Êtes vous sur de vouloir réinitialiser vos talents ?', NULL, NULL, NULL, NULL, NULL, 'Вы уверены, что хотите сбросить таланты?'),
(12233, '|TInterface\\icons\\achievement_general:25:25:-15:0|tSkills weapon', NULL, '|TInterface\\icons\\achievement_general:25:25:-15:0|tCompétences d\'armes', NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\achievement_general:25:25:-15:0|tОружейные навыки'),
(12234, '|TInterface\\icons\\trade_engineering:25:25:-15:0|tImprove skills of protecting and owning weapons to the maximum', NULL, '|TInterface\\icons\\trade_engineering:25:25:-15:0|tAméliorer les compétences de protection et de possession de type d\'armes au maximum', NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\trade_engineering:25:25:-15:0|tУлучшить навыки защиты и владения оружием до максимума'),
(12235, 'Your talents have been successfully reset.', NULL, 'Vos talents ont été réinitialisés avec succès.', NULL, NULL, NULL, NULL, NULL, 'Ваши таланты успешно сброшены.'),
(12236, 'You have successfully learned all the weapons skills for your class.', NULL, 'Vous avez appris avec succès toutes les compétences d\'armes pour votre classe.', NULL, NULL, NULL, NULL, NULL, 'Вы успешно изучили все оружейные навыки для своего класса.'),
(12237, 'Your skills of defense and possession of weapons are improved to the maximum.', NULL, 'Vos compétences de défense et de possession de type d\'armes sont améliorées au maximum.', NULL, NULL, NULL, NULL, NULL, 'Ваши навыки защиты и владения оружием улучшены до максимума.'),
(12238, 'All your equipment is repaired.', NULL, 'Tout votre équipement a été réparé', NULL, NULL, NULL, NULL, NULL, 'Вся ваша экипировка была подлатана!'),
(12239, 'Aura Deserter not found!', NULL, 'Le débuff Déserteur n\'est pas en cours', NULL, NULL, NULL, NULL, NULL, 'Аура Дезертир не найдена!'),
(12240, 'Aura Deserter was successfully removed!', NULL, 'Le débuff Déserteur a été retiré avec succès !', NULL, NULL, NULL, NULL, NULL, 'Аура Дезертир успешно убрана!'),
(12241, '|TInterface/ICONS/spell_holy_rapture:25:25:-15:0|tChange name[|cffff0000100|r Arena Points]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface/ICONS/spell_holy_rapture:25:25:-15:0|tСмена имени[|cffff0000100|r Арена поинтов]'),
(12242, '|TInterface/ICONS/spell_holy_rapture:25:25:-15:0|tChange of appearance[|cffff0000200|r Arena Points]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface/ICONS/spell_holy_rapture:25:25:-15:0|tСмена внешности [|cffff0000200|r Арена поинтов]'),
(12243, '|TInterface/ICONS/spell_holy_rapture:25:25:-15:0|tChange faction[|cffff0000500|r Arena Points]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface/ICONS/spell_holy_rapture:25:25:-15:0|tСмена фракции[|cffff0000500|r Арена поинтов'),
(12244, '|TInterface/ICONS/spell_holy_rapture:25:25:-15:0|tChange race[|cffff0000250|r Arena Points]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface/ICONS/spell_holy_rapture:25:25:-15:0|tСмена расы[|cffff0000250|r Арена поинтов]'),
(12245, '|cffD80000Rates|r', NULL, 'Taux', NULL, NULL, NULL, NULL, NULL, '|cffD80000Рейты|r'),
(12246, '|cff660099Rates XP for kill|r x:', NULL, '|cff660099Taux d\'XP des ennemis tués|r x:', NULL, NULL, NULL, NULL, NULL, '|cff660099Рейты на опыт за убийство|r x:'),
(12247, '|cff660099Rates XP for quest|r x:', NULL, '|cff660099Taux d\'XP des quêtes|r x:', NULL, NULL, NULL, NULL, NULL, '|cff660099Рейты на опыт за задания|r x:'),
(12248, '|cff660099Rate of reputation|r x:', NULL, '|cff660099Taux de réputation|r x:', NULL, NULL, NULL, NULL, NULL, '|cff660099Рейт репутации|r x:'),
(12249, '|cff660099Rate of gold|r x:', NULL, '|cff660099Taux d\'argent|r x:', NULL, NULL, NULL, NULL, NULL, '|cff660099Рейт золота|r x:'),
(12250, '|cff660099Rate of honor|r x:', NULL, '|cff660099Taux d\'honneur|r x:', NULL, NULL, NULL, NULL, NULL, '|cff660099Рейт Хонора|r x:'),
(12251, 'Buy VIP for [ |cffD800007|r ] Days [20 coins]', NULL, 'Acheter [ |cffD800007|r ] jours de privilèges VIP pour [20 jetons]', NULL, NULL, NULL, NULL, NULL, 'Купить VIP на [ |cffD800007|r ] Дней [20 Бонусов]'),
(12252, 'Buy VIP for [ |cffD8000014|r ] Days [40 coins]', NULL, 'Acheter [ |cffD8000014|r ] jours de privilèges VIP pour [40 jetons]', NULL, NULL, NULL, NULL, NULL, 'Купить VIP на [ |cffD8000014|r ] Дней [40 Бонусов]'),
(12253, 'Buy VIP for [ |cffD8000031|r ] Days [80 coins]', NULL, 'Acheter [ |cffD8000031|r ] jours de privilèges VIP pour [80 jetons]', NULL, NULL, NULL, NULL, NULL, 'Купить VIP на [ |cffD8000031|r ] День [80 Бонусов]'),
(12254, 'Are you sure you want to buy VIP time for 7 days ?', NULL, 'Êtes vous sur de vouloir acheter 7 jours de privilèges VIP ?', NULL, NULL, NULL, NULL, NULL, 'Вы уверены что хотите купить VIP аккаунт на 7 дней ?'),
(12255, 'Are you sure you want to buy VIP time for 14 days ?', NULL, 'Êtes vous sur de vouloir acheter 14 jours de privilèges VIP ?', NULL, NULL, NULL, NULL, NULL, 'Вы уверены что хотите купить VIP аккаунт на 14 дней ?'),
(12256, 'Are you sure you want to buy VIP time for 31 days ?', NULL, 'Êtes vous sur de vouloir acheter 31 jours de privilèges VIP ?', NULL, NULL, NULL, NULL, NULL, 'Вы уверены что хотите купить VIP аккаунт на 31 день ?'),
(12257, 'Buy additional VIP time for [ |cffD800007|r ] Days [20 coins]', NULL, 'Acheter [ |cffD800007|r ] jours de privilèges VIP [20 jetons]', NULL, NULL, NULL, NULL, NULL, 'Увеличить время VIP привилегий на [ |cffD800007|r ] Дней [20 Бонусов]'),
(12258, 'Buy additional VIP time for [ |cffD8000014|r ] Days [40 coins]', NULL, 'Acheter [ |cffD8000014|r ] jours de privilèges VIP [40 jetons]', NULL, NULL, NULL, NULL, NULL, 'Увеличить время VIP привилегий на [ |cffD8000014|r ] Дней [40 Бонусов]'),
(12259, 'Buy additional VIP time for [ |cffD8000031|r ] Days [80 coins]', NULL, 'Acheter [ |cffD8000031|r ] jours de privilèges VIP [80 jetons]', NULL, NULL, NULL, NULL, NULL, 'Увеличить время VIP привилегий на [ |cffD8000031|r ] День [80 Бонусов]'),
(12260, 'Are you sure you want to buy additional VIP time for 7 days ?', NULL, 'Êtes-vous sûr de vouloir acheter 7 jours de privilèges VIP supplémentaire ?', NULL, NULL, NULL, NULL, NULL, 'Вы уверены что хотите Увеличить время VIP привилегий на 7 дней ?'),
(12261, 'Are you sure you want to buy additional VIP time for 14 days ?', NULL, 'Êtes-vous sûr de vouloir acheter 14 jours de privilèges VIP supplémentaire ?', NULL, NULL, NULL, NULL, NULL, 'Вы уверены что хотите Увеличить время VIP привилегий на 14 дней ?'),
(12262, 'Are you sure you want to buy additional VIP time for 31 days ?', NULL, 'Êtes-vous sûr de vouloir acheter 31 jours de privilèges VIP supplémentaire ?', NULL, NULL, NULL, NULL, NULL, 'Вы уверены что хотите Увеличить время VIP привилегий на 31 день ?'),
(12263, '|cff006699Not enough coins|r', NULL, '|cff006699Pas assez de jetons|r', NULL, NULL, NULL, NULL, NULL, '|cff006699Недостаточно бонусов|r'),
(12264, '|cff006699You have: |cff00FF33{} coins|r', NULL, '|cff006699Vous avez: |cff00FF33{} jetons|r', NULL, NULL, NULL, NULL, NULL, '|cff006699У вас: |cff00FF33{} бонусов|r'),
(12265, '|cff006699You need additional: |cffFF0000{}|r', NULL, '|cff006699Il vous manque: |cffFF0000{}|r', NULL, NULL, NULL, NULL, NULL, '|cff006699Нужно еще: |cffFF0000{}|r'),
(12266, 'You can not use it on BattleGround or Arena!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вы не можете использовать его на БГ и Арене!'),
(12267, 'You can not use it while you in stealth!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вы не можете использовать его, пока находитесь в режиме незаметности!'),
(12268, 'You can not use it while you dead!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вы не можете использовать его, пока вы мертвы!'),
(12269, '|cff006699You successfully bought an item {}|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cff006699You successfully bought an item {}|r'),
(12270, '|cff006699Time of your VIP privileges has been increased for {} days!|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|cff006699Time of your VIP privileges has been increased for {} days!|r'),
(12271, '|TInterface\\icons\\Ability_Mage_PotentSpirit:25:25:-15:0|tTrade Shop', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Ability_Mage_PotentSpirit:25:25:-15:0|tМагазин'),
(12272, '|TInterface\\icons\\Achievement_BG_interruptX_flagcapture_attempts:25:25:-15:0|tYour Weekly PVP Bonus Cap : (', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Achievement_BG_interruptX_flagcapture_attempts:25:25:-15:0|tYour Weekly PVP Bonus Cap : ('),
(12273, '|TInterface\\icons\\Achievement_BG_interruptX_flagcapture_attempts_1game:25:25:-15:0|tYour Weekly PVP Bonus Cap : (', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Achievement_BG_interruptX_flagcapture_attempts_1game:25:25:-15:0|tYour Weekly PVP Bonus Cap : ('),
(12274, '|TInterface\\icons\\Spell_chargepositive:25:25:-15:0|tBank', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Spell_chargepositive:25:25:-15:0|tБанк'),

-- LANG_GOINFO_PHASEMASK
(12275, 'Phase: {}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
-- LANG_ITEM_START_PACK_ITEM
(12276, '|TInterface\\icons\\Ability_Warrior_Intervene:25:25:-15:0|t Receive start-pack items', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Ability_Warrior_Intervene:25:25:-15:0|t Получить стартовый пакет'),

(12300, '|TInterface\\icons\\Inv_inscription_pigment_bug07:25:25:-15:0|tEnter Promo - Code', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Inv_inscription_pigment_bug07:25:25:-15:0|tВвести промокод'),
(12301, 'Are you sure that you know correct code?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вы уверены, что знаете верный код?'),
(12302, '|TInterface\\icons\\achievement_level_80:25:25:-15:0|t Class skills - GM|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\achievement_level_80:25:25:-15:0|t Изучение заклинаний - GM|r'),
(12303, '|TInterface/ICONS/inv_crate_04:25:25:-15:0|t Delivery of bags', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface/ICONS/inv_crate_04:25:25:-15:0|t Получить сумки'),
(12304, '|TInterface\\icons\\Inv_misc_coin_01:25:25:-15:0|t Level up at 80', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface\\icons\\Inv_misc_coin_01:25:25:-15:0|t Повысить уровень до 80'),
(12305, 'Promo code already used or entered incorrectly', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Промокод использован или введен неверно'),
(12306, 'You have successfully received rewards for the promotional code', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вы успешно получили награды по промокоду'),

-- transmogrified
(13000, 'Item transmogrified', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Предмет трансморгрифицирован'),
(13001, 'Equipment slot is empty', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Слот экипировки пуст'),
(13002, 'Invalid source item selected', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Некорректный исходный предмет выбран.'),
(13003, 'Source item does not exist', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Исходный предмет не существует'),
(13004, 'Destination item does not exist', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Целевой предмет не существует'),
(13005, 'Selected items are invalid', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Выбранные предметы некорректны'),
(13006, 'Not enough money', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Недостаточно денег'),
(13007, 'You don\'t have enough tokens', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'У вас недостаточно токенов'),
(13008, 'Transmogrifications removed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Трансморгрификация удалена'),
(13009, 'There are no transmogrifications', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Трансморгрификации отсутствуют'),
(13010, 'Head', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Голова'),
(13011, 'Shoulders', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Плечи'),
(13012, 'Shirt', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Рубашка'),
(13013, 'Chest', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Тело'),
(13014, 'Waist', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Пояс'),
(13015, 'Legs', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ноги'),
(13016, 'Feet', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Обувь'),
(13017, 'Wrists', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Запястья'),
(13018, 'Hands', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Руки'),
(13019, 'Back', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Спина'),
(13020, 'Main Hand', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Правая рука'),
(13021, 'Off Hand', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Левая рука'),
(13022, 'Ranged', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Оружие дальнего боя'),
(13023, 'Tabard', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Гербовая накидка'),
(13024, '|TInterface/ICONS/INV_Misc_Book_11:30:30:-18:0|tHow transmogrification works', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface/ICONS/INV_Misc_Book_11:30:30:-18:0|tКак трансморгрификация работает'),
(13025, '|TInterface/ICONS/INV_Enchant_Disenchant:30:30:-18:0|tRemove all transmogrifications', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface/ICONS/INV_Enchant_Disenchant:30:30:-18:0|tУдалить все трансморгрификации'),
(13026, 'Remove transmogrifications from all equipped items?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Удалить трансморгрификацию со всех одетых предметов?'),
(13027, '|TInterface/PaperDollInfoFrame/UI-GearManager-Undo:30:30:-18:0|tUpdate menu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface/PaperDollInfoFrame/UI-GearManager-Undo:30:30:-18:0|tОбновить меню'),
(13028, '|TInterface/ICONS/Ability_Spy:30:30:-18:0|tBack...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface/ICONS/Ability_Spy:30:30:-18:0|tНазад...'),
(13029, '|TInterface/ICONS/INV_Enchant_Disenchant:30:30:-18:0|tRemove transmogrification', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface/ICONS/INV_Enchant_Disenchant:30:30:-18:0|tУдалить трансморгрификацию'),
(13030, 'Remove transmogrification from the slot?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Удалить трансморгрификацию с этого предмета?'),
(13031, 'Invalid name inserted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Введено некорректное имя'),
(13032, '|TInterface/RAIDFRAME/UI-RAIDFRAME-MAINASSIST:30:30:-18:0|tManage sets', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface/RAIDFRAME/UI-RAIDFRAME-MAINASSIST:30:30:-18:0|tУправления комплектами'),
(13033, '|TInterface/ICONS/INV_Misc_Book_11:30:30:-18:0|tHow sets work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface/ICONS/INV_Misc_Book_11:30:30:-18:0|tКак комплекты работают'),
(13034, '|TInterface/GuildBankFrame/UI-GuildBankFrame-NewTab:30:30:-18:0|tSave set', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface/GuildBankFrame/UI-GuildBankFrame-NewTab:30:30:-18:0|tСохранить комплект'),
(13035, 'Insert set name', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Введите название комплекта'),
(13036, '|TInterface/ICONS/INV_Misc_Statue_02:30:30:-18:0|tUse set', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface/ICONS/INV_Misc_Statue_02:30:30:-18:0|tИспользовать комплект'),
(13037, 'Using this set for transmogrify will bind transmogrified items to you and make them non-refundable and non-tradeable.\nDo you wish to continue?\n\n', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'После трансморгрификации вы не сможете вернуть предметы торговцу, передать и они будут привязаны к вам.\nВы хотите продолжить?\n\n'),
(13038, '|TInterface/PaperDollInfoFrame/UI-GearManager-LeaveItem-Opaque:30:30:-18:0|tDelete set', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '|TInterface/PaperDollInfoFrame/UI-GearManager-LeaveItem-Opaque:30:30:-18:0|tУдалить комплект'),
(13039, 'Are you sure you want to delete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Вы действительно хотите удалить'),
(13040, 'Using this item for transmogrify will bind it to you and make it non-refundable and non-tradeable.\nDo you wish to continue?\n\n', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Использование этого итема для трансформирования свяжет его с вами и сделает его персональным и не подлежащим торговле.\nВы хотите продолжить?\n\n');
